### ISSUE TITLE
ddev post hooks work fine in linux, not at all in windows

### ISSUE THREAD

**Issue by btopro** [drud/ddev#1010]
Maybe I'm missing something but I thought that the post hooks would be executed in the container and not local machine. Anyway, the following post hooks work fine in OSX but bricks on windows https://github.com/elmsln/haxcms/blob/master/.ddev/config.yaml#L68

Don't know that this is really a ddev issue but figured I'd post here in case

**Comment by btopro** [comment]
trying to get user/group association for nginx since it needs write on a folder but it seemed to be bombing on the whole command running at all when syntax is fine in osx based ddev invoking. just trying to isolate whether that's even possible since I know docker in windows is a trainwreck

**Comment by rfay** [comment]
So in the container, everything runs as one user, for the vast majority of interactions, you shouldn't be naming or changing user or group *anything*. nginx runs as either the same uid as the user on the host (on macOS and linux) or as root (on Windows). Everything running inside the container runs as the same user, unprivileged in most situations. For everything else there's sudo.

**Comment by rfay** [comment]
I'm assuming that thumbs-up means this issue is resolved, so closing, but feel free to continue the conversation! Happy to help sort any of that out.
