### ISSUE TITLE
Add aliases for multiple sites and loss of configurations

### ISSUE THREAD

**Issue by Gonzalo2683** [drud/ddev#1012]
Hello, i have a drupal  multisite , I have added the scripts where I define the aliases of these sites and they work well, the problem is that when for example my work day ends, I turn off the computer, the next day, start with ddev start, the files of configuration are no longer. I know it has to do with the docker containers, but is there any way I can keep these files and not have to add them every time I start the containers?

Forgive my ignorance, have a little information on how to deal with this situation is very useful.

Thank you

**Comment by rickmanelius** [comment]
Hi @Gonzalo2683. When you say you've added the scripts, where do those live? Are you generating them into the container? Can they be committed to the codebase and available when ddev start occurs? One way to do this programmatically with each start is to, in config.yml, use a post-start action to perform drush or shell commands to set things up the way you want them each time. https://ddev.readthedocs.io/en/latest/users/extending-commands/

**Comment by Gonzalo2683** [comment]
Hi @rickmanelius , the alias scripts are the following location:
Enter the server by ssh
```
ddev ssh --service web
cd ~/.drush
```
There you find a folder called **aliases**

![alias_path](https://user-images.githubusercontent.com/1046320/43209109-42710638-9002-11e8-93b5-cbcd1e594d6b.png)

This is the place where you add the aliases

**Comment by rfay** [comment]
I recommend the technique in https://stackoverflow.com/questions/51065163/how-can-i-get-my-drush-aliases-into-the-ddev-web-container

**Comment by Gonzalo2683** [comment]
Excellent, everything is working successfully

**Comment by rfay** [comment]
Glad to hear it! Closing this, happy to continue the conversation though.
