### ISSUE TITLE
Consider automatically updating the AUR repo

### ISSUE THREAD

**Issue by cweagans** [drud/ddev#1019]
Right now, we manually bump the version that's deployed to the [AUR repo](https://aur.archlinux.org/packages/ddev-bin/). This means that there's at least some lag between when a new ddev version is released and when it's available for Arch users.

This should be fairly straightforward to do, as it's essentially just templating out a text file, running a script that ships with Arch, and pushing the result to a Git repo.

This would need to be done after the Linux x64 build is packaged/uploaded and after the sha256sums are calculated. I'm not sure if that part of the release is automated yet, so that would impact whether or not automated AUR updates are even possible right now.

**Comment by rfay** [comment]
@cweagans has volunteered to do a PR for this...

**Comment by cweagans** [comment]
I've got this on my list to look at in June.

**Comment by rfay** [comment]
Closing in favor of https://github.com/drud/ddev/issues/2213
