### ISSUE TITLE
Consider supporting configuration of router mailhog port and phpmyadmin port (8025 and 8036)

### ISSUE THREAD

**Issue by gmcdaniel-espi** [drud/ddev#1025]
I could not start ddev because port 8025 was in use by a Homestead VirtualBox VM. I did not have my ports configured to point to 8025. I found the port referenced in the Docker config files and change them to 8825 and tried to restart but I received the same message. There was no other reference to port 8025 in the site/config files. The only way I could get the site to work was by stopping the VM.

**Comment by rfay** [comment]
Port 8025 is used by the mailhog utility provided by ddev. I imagine you're using it for your mailhog in your Homestead VirtualBox VM as well. Is it possible to stop the Homestead VM? Unfortunately we don't provide the ability to reconfigure the mailhog port at this time, although it wouldn't be too hard.

**Comment by gmcdaniel-espi** [comment]
Not a problem. You might reference it in the docs. Thank you.

**Comment by rfay** [comment]
I think we had somebody else stumble on that recently (8025 is the default for mailhog), so we'll definitely be thinking about how to resolve that, maybe through configuration or something.

**Comment by DanielRuf** [comment]
Hi, is there any news?

**Comment by rfay** [comment]
No, until you just woke this one up only one person had ever mentioned it, so no, it doesn't hasn't gotten traction yet. What is your situation? What is the conflict for you?

**Comment by DanielRuf** [comment]
The current conflict is that we also use mailhog locally and may want to change the docker-compose file.

Is this an epic or a smaller feature request?
So far I have no experience with Go development but if it is small I could try to see if I could create concepts for possible solutions before we write the needed code.

**Comment by rfay** [comment]
Thanks. Since the 8025 port is opened by the router, this is a feature of the router's docker-compose file in pkg/ddevapp/templates.go; One option would be to just allow overrides of the ~/.ddev/router-compose.yaml.

**Comment by DanielRuf** [comment]
> One option would be to just allow overrides of the ~/.ddev/router-compose.yaml.

Which would be great.

**Comment by wazum** [comment]
I have the same issue

**Comment by rfay** [comment]
This is probably pretty easy to solve now that we have a global ddev configuration.

**Comment by rfay** [comment]
Hmm, I wonder if people with this problem should just be using their own mailhog, and instead of offering just port config, we should offer a different hostname as well.

**Comment by rfay** [comment]
Yet another technique is to put mailhog it's own container (either global or per project) and make it optional.
