### ISSUE TITLE
Purchase and deploy 2 windows laptops as testbots

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1026]
Every push does 2 windows tests (container and overall ddev testing), and they take quite a bit longer than mac or linux. Azure has not worked out as well as we hoped. We need more capacity, so probably we should deploy 2 more windows laptops.

I'll try to find a good (hopefully cheap) model we can buy.

**Comment by rfay** [comment]
I think we can buy two of [these Dell Latitude Laptops](https://www.bestbuy.com/site/dell-latitude-13-3-refurbished-laptop-intel-core-i5-8gb-memory-256gb-solid-state-drive-black/5514005.p?skuId=5514005) that actually come with Win 10 Pro at $360 each. Over to you @rickmanelius

**Comment by rickmanelius** [comment]
@pgalligan80126 bump. Can we get an approval on this to unblock testing?

**Comment by rfay** [comment]
We waited too long for the specified laptops and they were gone. Instead I ordered 2 of https://www.bestbuy.com/site/dell-latitude-12-5-laptop-intel-core-i5-8gb-memory-256gb-solid-state-drive-pre-owned-black/6219242.p?skuId=6219242 - these don't come with Win 10 Pro, but oh well.

**Comment by rfay** [comment]
I think you're asking about purchasing Win10 Pro.  I think we can just use unregistered Win10Pro to start with; otherwise it's $99 each I think.

**Comment by rickmanelius** [comment]
Unregistered works as long as it doesn't add unnecessary overhead in setting up, running, and maintaining the tests!

**Comment by rfay** [comment]
This issue was moved to drud/general#175
