### ISSUE TITLE
Allow non existing document root in config

### ISSUE THREAD

**Issue by codemonkey1988** [drud/ddev#1035]
**Is your feature request related to a problem? Please describe.**
When you want to start a new project or start working on an existing one, there might be the case, that the actual document root for the project does not exist because it is generated by composer. Currently you either have to run composer install on your host machine or set the project root directory as document root.
In the first case, you need to have php and composer running on your local machine (and also the correct php version) which seems the opposite goal of ddev. In the second case, you can start ddev, run composer install or create-project, then shut down ddev and reconfigure the docroot.

Both solutions are not very nice. One actual example is running TYPO3 with the `helhum/typo3-secure-web` package. The document root for this project needs not to be stored in version control (normally).

**Describe the solution you'd like**
Instead of an error, ddev should throw a warning, that the document root does not exist but continue starting up. So the developer can run composer install inside the docker container.

**Describe alternatives you've considered**
When a non existing document root breaks nginx startup, ddev might create the docroot folder structure by itself. But this would be a worse solution then the given one above I think.

**Comment by mfrieling** [comment]
The same issue also applies for `ddev ssh` (and depending commands like `ddev exec`) which fails with the error message
> Failed to ssh: error restoring AppConfig: no project name given
I'll add further details to #1048.

**Comment by rfay** [comment]
The way you work around it is just using "" or "." for the docroot until you have one, and using the "php" apptype until then.  So you `ddev config` and accept 'php' as the apptype and '' as the docroot; then after you do your composer and have a docroot, you rerun `ddev config` and update the docroot and apptypes.  More details in https://github.com/drud/ddev/issues/697

**Comment by mfrieling** [comment]
That means temporarily modifying files under version control. And I have seen it often enough that those temp changes are overseen and slip into a commit. And then the next developer pulls and spends hours over hours searching why nothing works anymore in his environment. Therefore it is not an option for an already set-up project (for creating a new one like in #697 yes).

**Comment by rfay** [comment]
I pretty much recommend not committing .ddev/config.yaml, but others have other opinions. It's worth committing if you have hooks populated.  But no, it only requires changing them until you have the project built, and then everything stays the same. Depends on your process of course.

**Comment by codemonkey1988** [comment]
@rfay That's not absolutely correct. We got projects without the document root directory commited into Git. The document root folder is generated by running composer install.
So when someone joins the project, the config file needs to be changed temporarly. We keep it in Git because of the configured hooks, like you said.

**Comment by mfrieling** [comment]
I personally have two scenarios where it makes sense to put the config.yaml into Git, besides the already mentioned hooks:

1. Every developer needs the exact same environment setup, especially when it comes to hostnames. There are several reasons for it, like module licensing where the hostname must match the value in the license (welcome to the Magento world) or where two systems interact with each other via APIs and you're developing both of them.
2. You have a team of developers spread over a whole continent with not all of them so experiences outside their specific software technology, and using different OS. All of them should be able to setup their dev environment as fast and easy as possible. With config.yaml in Git this becomes true (install Docker & DDEV, git clone your repo and `ddev start`).

So in my opinion putting config.yaml into Git is not bad, but of course the `docker-compose.yaml` must not be in Git. There you can provide override files with the specific configs which should be in Git.

**Comment by rfay** [comment]
Thanks so much for your perspective on this @mfrieling ! It helps us learn always.
