### ISSUE TITLE
Allow specifying target container for hook execution

### ISSUE THREAD

**Issue by codemonkey1988** [drud/ddev#1038]
**Is your feature request related to a problem? Please describe.**
When you want to execute a hook in different container than the web container, you currently need to use the `exec-host` command an run `ddev exec -s my-service my-command`.

**Describe the solution you'd like**
It would be nice, if you could somehow specify the target container for the hook to execute.
One possible solution could be integrating the services name into the exec command.

Example:
When you got a service named _node_ you can execute a hook in it by using `exec-node`. This solution would keep the current syntax. `exec-host` would stay as be special keyword and only `exec` would be the same as `exec-web` (it it might be an alias for compatibility.

The whole hook config could look like this:

    hooks:
      post-start:
        exec: composer install -d /var/www/html
        exec-node: npm install

**Comment by rfay** [comment]
I think this is long-neglected but a really valid application. I wish our existing config language had a spot for the container name. It really allow something like:

```
hooks:
  post-start:
    exec:
      container: db
      command: mysql --version
```

**Comment by andrewfrench** [comment]
This seems like a natural progression as people increasingly use custom containers, and I'd imagine there are some use cases for executing hooks on our existing non-web containers now. 

On the back end, we already support `exec`-ing commands on arbitrary containers, but we'll need to decide on the front-end parsing and error handling specifics.

**Comment by codemonkey1988** [comment]
@rfay Your solution would be the better one I think, but it would also be a breaking change for many people unless you keep the current syntax for compatibility. I don't know how you will handle breaking changes in stable releases, but this might annoy people when they have to update all their ddev projects with hooks.

**Comment by kristoftorfs** [comment]
@codemonkey1988 To be honest, I don't think keeping this backwards compatible is that hard. If the `exec` node is a string it's defined in the old way, if it's a hash it's the new way. 

Is there any progress made on this? I literally have zero projects where I don't use custom services and this would be a major improvement.

**Comment by rfay** [comment]
Thanks for chiming in on this @kristoftorfs - Just an FYI about workarounds you probably already use... If the web container has access to the other service, then hooks can be executed against the web container and take action against another container. For example, since the web container has mysql access to the db container, you can add a hook that does a mysql command.
