### ISSUE TITLE
Phpmyadmin image creating/starting optional

### ISSUE THREAD

**Issue by spoonerWeb** [drud/ddev#1044]
**Is your feature request related to a problem? Please describe.**
For my local environment on my Mac I have SequelPro, other people use HeidiSQL or MySQL Workbench for their DB connections. Imho there is no need to start phpmyadmin by default all the time.

**Describe the solution you'd like**
I would like to have the option in the YAML file to activate phpmyadmin. By default, it's deactivated.

**Describe alternatives you've considered**
No alternatives. :)

**Comment by rfay** [comment]
I'd be interested in why the phpmyadmin container is annoying. Is it just the problem of having something running that you don't use? Or are you running into resource constraints? (I also never use it and often forget it's there, would be interested to know how many people do use it.)

You *can* easily get rid of most of the weight of the phpmyadmin container by just swapping out the docker image for "busybox". In your .ddev/ create `docker-compose.phpmyadmin.yaml` with these contents:

```
version: '3'

services:
  dba:
    image: "busybox"
```

I do think it's possible we should just make phpmyadmin be an add-on.

**Comment by spoonerWeb** [comment]
Cool, that workaround is a good option.
I want to have less docker images and prevent to have docker images I don't use. That's why the phpmyadmin image is a thorn in my side.
But I'll take your solution. 👍
