### ISSUE TITLE
Create a permanent URL for download links of latest versions

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#1050]
Discussed in the Drupal #ddev Slack channel:

"One thing that would be nice is a url that always points to the recommended version of ddev for each os. It could then be hardlink it in the docs rather than telling people to go search out the right executable."

**Comment by rfay** [comment]
I'm not entirely sure this is necessary, as https://github.com/drud/ddev/releases always works.

**Comment by mfrieling** [comment]
The link should be enough but the existing link https://github.com/drud/ddev/releases/latest is more specific as it shows only the latest release and not all available releases.

But an update check in DDEV itself would be nice. If it runs only once per day or if requested by a parameter (either with `ddev --version` or e. g. `ddev version --check-updates`) which fetches the git tags and looks for the latest version tag or parses the HTML of https://github.com/drud/ddev/releases/latest. But as Github doesn't provide a proper class or id for the link to the version tag this would be some dirty HTML parsing.

**Comment by rfay** [comment]
I'm going to close this as I don't understand what is needed beyond https://github.com/drud/ddev/releases/latest - ongoing conversation is welcome!
