### ISSUE TITLE
Add flags for config.yaml options

### ISSUE THREAD

**Issue by andrewfrench** [drud/ddev#1051]
**Is your feature request related to a problem? Please describe.**
DDEV-UI needs additional CLI flags for `ddev config`. Currently, the UI will have to edit the config.yaml file directly to control things like PHP version, host names, FQDNs, ports, etc., but these should all be programmatically configurable using command flags.

**Describe the solution you'd like**
In addition to `ddev config --docroot xxx --projectname yyy --projecttype zzz`, there should be: 
- `--php-version version`
- `--http-port port` and `--https-port port`
- `--xdebug-enabled true|false`
- `--additional-hostnames hostname[,hostname]`
- `--additional-fqdns fqdn[,fqdn]`

**Comment by mfrieling** [comment]
And please add a flag like `--apply` or whichever name you think fits best. If `config.yaml` already has values for docroot, projectname and projecttype this flag should not ask the user for them but just generate/update the required files like `docker-compose.yaml`, `settings.ddev.php` (for Drupal projects) etc. in scenarios where the `config.yaml` is in Git or just to regenerate the other files (e. g. after updating DDEV).
