### ISSUE TITLE
ddev cannot find running project

### ISSUE THREAD

**Issue by finex** [drud/ddev#1052]
**Describe the bug**
Commands like `ddev ssh`, `ddev exec`,  `ddev stop` or  `ddev start` returns the following error (from the project directory which contains `.ddev/` folder):

```
a project (web container) in running state already exists for
```
If I append the project name to `start` and `stop`, the command works as expected. `exec` and `ssh` doesn't get the project name as parameter.

If I stop and remove the project, I can start again and do a command like "ddev ssh" but if I open a new terminal it doesn't work anymore (from the new opened terminal). I've tried both using zsh and bash shell.

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Arch Linux, Linux Kernel 4.17.14
 - Docker version information: Docker version 18.05.0-ce, build f150324782
 - ddev version information: v1.0.0

**Comment by rfay** [comment]
When I've seen this happen it's a result of having a stopped project of the same name in a different directory. As you point out, `ddev rm <project>` solves it, as it should.

**Comment by finex** [comment]
Hi @rfay,
after some testing I've found the problem: the project directory is inside another directory which is symlinked on my home directory.

Example:
`/mnt/projects/ddev/projectname`
and:
`~/projects` --> `/mnt/projects/ddev/projectname`, resulting in `~/projects/ddev/projectname` (shown in `ddev list`).

When `ddev start` is executed from one path, following `ddev` commands for the same project need to be started from the identical path because it doesn't follow the symbolic link.

**Comment by finex** [comment]
I'm closing this bug. Probably a better error message or a small warning on the docs could be helpful for other users? Thanks for the support!

**Comment by rfay** [comment]
Thanks so much for chasing this down. 

From slack though...

>Looking at your comment on the github issue maybe I misunderstood. I had thought you were saying that you had tried to use ddev from two different paths that were logically the same but had different nominal paths.
