### ISSUE TITLE
ddev config overrides TYPO3 AdditionalConfiguration.php when no LocalConfiguration.php found

### ISSUE THREAD

**Issue by ulrichmathes** [drud/ddev#1053]
The documentation says that AdditionalConfiguration.php will only be modified if file does not exists or is managed by DDEV. 

> For TYPO3, DDEV settings are written to AdditionalConfiguration.php. If AdditionalConfiguration.php exists and is not managed by DDEV, it will not be modified.

This is not true for `ddev config` when TYPO3 is has been set up

Hint in `ddev config` about this behavior:
> TYPO3 does not seem to have been set up yet, missing LocalConfiguration.php ([...]/public/typo3conf/AdditionalConfiguration.php)

**To Reproduce**
1. `composer create-project typo3/cms-base-distribution my-typo3-site ^8`
2. `cd my-typo3-site`
3. `echo "<?php" > public/typo3conf/AdditionalConfiguration.php`
4. `ddev config`

**Expected behavior**
AdditionalConfiguration.php should not be modified.

**Version and configuration information:**
 - Host computer OS and Version: Linux
 - Docker version: 18.06.0-ce
 - ddev version information:
> cli   	v1.0.0                    
> web   	drud/ddev-webserver:v1.0.0
> db    	drud/ddev-dbserver:v1.0.0 
> dba   	drud/phpmyadmin:v1.0.0    
> router	drud/ddev-router:v1.0.0   
> commit	v1.0.0                    
> domain	ddev.local
 - config.yaml:
```
type: typo3
docroot: public
php_version: "7.2"
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
```

**Comment by rfay** [comment]
I can recreate this and agree that this isn't the expected behavior, although it does seem unlikely to have an unmanaged AdditionalConfiguration.php and *no* LocalConfiguration.php. I'll put this into our next sprint.

**Comment by ulrichmathes** [comment]
Great.

Explanation why i need this: I'm recreating the boilerplate for our TYPO3 projects using ddev. There we have dotenv configurations within the AdditionalConfiguration.php but TYPO3 is not installed yet (no LocalConfiguration.php) before calling ddev config.

**Comment by rfay** [comment]
I'm sure you know that ddev will not be able to add any of its own config if you do that, but I'm sure you've got that covered.
