### ISSUE TITLE
Usability improvements to snapshot functionality

### ISSUE THREAD

**Issue by ultimike** [drud/ddev#1057]
The snapshot functionality is solid - love it so far! Here's a couple of suggestions to make it even better:

1. Have "ddev restore-snapshot" automatically restore the most recent snapshot when no snapshot_name is provided.  
2.  Add a "ddev snapshot --list" flag to show a list of all available snapshots for a given project.  

I could also be convinced to move "ddev restore-snapshot" to "ddev snapshot --restore" - I think having a small set of commands is one of the really nice things about DDEV.

-mike

**Comment by rfay** [comment]
Thanks!

**Comment by rfay** [comment]
Closing in favor of #1163, comment moved over to that one.

**Comment by rfay** [comment]
I hope you'll try out v1.17.0-alpha3, which has this feature,  and give your feedback!
