### ISSUE TITLE
Create master build for ddev, start nightly build of all components.

### ISSUE THREAD

**Issue by rfay** [drud/ddev#106]
## What happened (or feature request):

Feature Request: We need a master build for ddev which verifies that all of its components work as of the current time; the master build can then be run in a Circle nightly build. 

This is a spinoff/specialization of drud/general#17, which is too general and basically needs to be retired. 

- [x] Finish master build (currently in https://github.com/drud/build.base, probably should be moved to its own territory)
- [x] Configure Circle to build and test nightly. 
- [x] Consider moving the master build into ddev repo itself.

## Related source links or issues (like source JIRA issue):

drud/general#17 is the original master issue.

**Comment by rickmanelius** [comment]
Not sure if this has already been completed as a result of all the referenced issues that are now merged and closed. @rfay when you get a chance, can you confirm if this ticket is still relevant?

**Comment by rfay** [comment]
This just went in today, but until the nightly build has actually worked, this should stay open.

**Comment by rfay** [comment]
This is completed and now just has to be maintained.
