### ISSUE TITLE
Feature request - Generate Kubernetes Manifests 

### ISSUE THREAD

**Issue by jmarkel** [drud/ddev#1063]
It would be extremely useful for ddev to produce Kubernetes manifests in addition to docker-compose yaml files when running ddev config. This would make it so much easier to deploy configurations into the local docker k8s or on minikube, as well as helping to deploy tested systems onto cloud-based k8s systems.

**Comment by jmarkel** [comment]
Well, I don't think it IS outside ddev's goals. K8s is where cloud computing container orchestration is going. The ideal dev environment mirrors, as much as possible, the environment that the software will eventually run in when deployed for production, so local dev environments are, or at least seem to be, heading toward Docker-embedded k8s or minikube, not raw docker containers orchestrated by docker-compose.

**Comment by mac-dev** [comment]
I vote for this because it can vital if you are forced to deploy on a company infrastructure and using hosters is no option.

**Comment by rfay** [comment]
This is not currently a part of our roadplan, so I'm going to close it for now. We always appreciate generous thinking and suggestions!

**Comment by fabarea** [comment]
I don't know about the path and the way to properly implement it but it would be useful since Kubernetes is gaining presence.

**Comment by rfay** [comment]
DDEV-Live is coming... but DDEV-Local (this product) doesn't use Kubernetes.
