### ISSUE TITLE
Installation on Windows 10 for non-privileged user

### ISSUE THREAD

**Issue by mfrieling** [drud/ddev#1064]
**Describe the bug**
I want to install DDEV on Windows 10 (Pro or Education) as a non-privileged user, or better said a user with limited permissions.

**To Reproduce**
1. Find a Windows 10 computer which is administrated by the central IT department, e. g. in a larger company or a university.
2. Login with a normal non-privileged user, e. g. a staff member who has no Administrator role on that computer.
3. Download and install DDEV 1.1.1  (latest version when creating this issue). You will be prompted for administrative credentials in order to perform the installation. Select all options including adding DDEV to $PATH etc.
4. Open a CMD, PowerShell or Git Bash and type `ddev`. Evtl. logout from Windows and in again, you can even restart Windows.
5. Login as the administrative user you've used for the installation and do step 4.

**Expected behavior**
At step 4 and 5 it shows the DDEV help. While this works in step 5 in step 4 (as the normal user) you will get an error that `ddev` is not a known command.

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Windows 10 Education, managed by university IT
 - Docker version information (use `docker version`) and insert it here:
**Client:**
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:28 2018
 OS/Arch:           windows/amd64
 Experimental:      false
**Server:**
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     true
 - ddev version information: installed 1.1.1

**Additional context**
DDEV installs in the context of the administrative user elevating the installation process but should either  in the context of the user starting the installation, or system globally/for all users.

**Comment by rfay** [comment]
So with the current design of ddev, it's easy easy easy to install ddev wherever you want (you don't have to use the windows installer, just download the binary). BUT... you still have the problem that we need admin access to edit /etc/hosts. Somehow you're going to have to do that.  We have an open issue (but back-burner) to use a DNS subdomain with wildcard instead, but it's not going anywhere right now.

**Comment by mfrieling** [comment]
@rfay yes the hosts file is a problem on Windows, but still this is a bug in the installer. And it is easy to fix by adding the DDEV path to the system PATH variable instead of the user one. In my situation the admin access would not be a problem because I'm also the IT responsible of my department at university (the Students Union) and have an account with admin access. But as we are all volunteering and people change regularly, we do not have person- but function-connected accounts. And I need to use DDEV with the function related account and not the department IT account.

**Comment by mfrieling** [comment]
Windows hosts file is a more generic problem that just the admin access requirement of DDEV. It has two other problems which could affect DDEV as well:

1. It doesn't support wildcard entries like `127.0.0.1 *.ddev.local` which of course would make things a lot easier (adding the one entry during installation and it is done).
2. While Chrome, Firefox, Opera, Safari, Internet Explorer <= 11, most other programs and Windows functionality itself use the hosts file, Microsoft Edge does not. So whatever you do with DDEV or other solutions relying on entries in the Windows hosts file, with Edge you're screwed. This goes for the other way round as well where firewalls etc. add entries for suspicious sites redirecting them to localhost to prevent access. Edge ignores it.

To make Edge work with DDEV there is a workaround using the [Fiddler Web Debugger from Telerik](https://www.telerik.com/fiddler) which has a feature called _Host Remapping_:

![fiddler_host_remapping](https://user-images.githubusercontent.com/8668756/44299340-2cac2800-a2f4-11e8-8916-8d3363107428.jpg)

As Fiddler works as a dynamic proxy and captures all traffic including the one from Edge, it processes all DNS requests against its internal hosts file (if Host Remapping is enabled) and only if no entry is found it passes the request on to the DNS servers.

Maybe this could be an option to implement a similar dynamic proxy which uses it's own hosts file filled with *.ddev.local and all configured and active FQDNs which works on MacOS and Linux as well as on Windows? And then make it a separate product to use standalone or as dependency of DDEV.

**Comment by mfrieling** [comment]
Yes, hosts file is only related to this topic as of needing admin access. But you started talking about it.

What I mean about the hosts file is, if you can find another solution working with hostnames than using the hosts file at all, you don't need admin access for it. I showed Telerik Fiddler's host remapping feature as one example. So if you can implement such kind of feature for dynamic DNS resolving as a proxy with its own hosts file that problem is solved. Or instead of implenting it on your own and have to learn internals of the DNS protocol utilizing an existing one like https://github.com/jedisct1/dnscrypt-proxy would be feasible. Feel free to create a feature request out of it if you think it might be a solution.

**Comment by rfay** [comment]
Are you going to be able to get Docker itself installed without admin privs? Are you going to be able to share the drives without admin privs?

**Comment by rfay** [comment]
A PR is welcome, but I don't know how to solve this and don't have an environment in which to solve it, and it's not the problem most people face, so closing this for now.
