### ISSUE TITLE
ddev snapshot doesn't work

### ISSUE THREAD

**Issue by dhoffmann1979** [drud/ddev#1066]
**Describe the bug**
When i enter "ddev snapshot" in the Projects root, an error occurs.

**To Reproduce**
1. Go to Project root
2. Enter "ddev snapshot"

**Expected behavior**
A snapshot should be generated.

**Screenshots**
See Attachment
![bildschirmfoto 2018-08-20 um 14 27 57](https://user-images.githubusercontent.com/1279518/44340493-5052a800-a485-11e8-9fb7-e09f1c8e0d56.png)

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macOS High Sierra 10.13.6
 - Docker version information (use `docker version`) and insert it here.
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:26 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     true

 - ddev version information (use `ddev version`)
router  drud/ddev-router:v1.1.0   
commit  v1.1.1                    
domain  ddev.local                
cli     v1.1.1                    
web     drud/ddev-webserver:v1.1.0
db      drud/ddev-dbserver:v1.1.0 
dba     drud/phpmyadmin:v1.1.0    

 - config.yaml contents for the misbehaving project
APIVersion: v1.1.1
name: eplan-pam-dev
type: php
docroot: Web
php_version: "7.1"
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default

# This config.yaml was created with ddev version v1.1.1 
# webimage: drud/ddev-webserver:v1.1.0
# dbimage: drud/ddev-dbserver:v1.1.0
# dbaimage: drud/phpmyadmin:v1.1.0
# However we do not recommend explicitly wiring these images into the
# config.yaml as they may break future versions of ddev.
# You can update this config.yaml using 'ddev config'.

# Key features of ddev's config.yaml:

# name: <projectname> # Name of the project, automatically provides
#   http://projectname.ddev.local and https://projectname.ddev.local

# type: <projecttype>  # drupal6/7/8, backdrop, typo3, wordpress, php

# docroot: <relative_path> # Relative path to the directory containing index.php.

# php_version: "7.1"  # PHP version to use, "5.6", "7.0", "7.1", "7.2"

# You can explicitly specify the webimage, dbimage, dbaimage lines but this
# is not recommended, as the images are often closely tied to ddev's' behavior,
# so this can break upgrades.

# webimage: <docker_image>  # nginx/php docker image.
# dbimage: <docker_image>  # mariadb docker image.
# dbaimage: <docker_image>

# router_http_port: <port>  # Port to be used for http (defaults to port 80)
# router_https_port: <port> # Port for https (defaults to 443)

# xdebug_enabled: false  # Set to true to enable xdebug and "ddev start" or "ddev restart"

#additional_hostnames:
# - somename
# - someothername
# would provide http and https URLs for "somename.ddev.local"
# and "someothername.ddev.local".

#additional_fqdns:
# - example.com
# - sub1.example.com
# would provide http and https URLs for "example.com" and "sub1.example.com"
# Please take care with this because it can cause great confusion.

# provider: default # Currently either "default" or "pantheon"
#
# Many ddev commands can be extended to run tasks after the ddev command is
# executed.
# See https://ddev.readthedocs.io/en/latest/users/extending-commands/ for more
# information on the commands that can be extended and the tasks you can define
# for them. Example:
#hooks:

**Comment by rfay** [comment]
Sorry it's giving you trouble. Please try on another project as well (just create another dummy). That will help see if it's something about the project.

On *this* project, please use `ddev ssh -s db` to ssh into the db container and get the /var/log/mariaback_backup* log that's there. (If you `cp /var/log/mariabackup* /mnt/ddev_config` it will be in your project .ddev folder, where it's easy to put in a gist and report here.

**Comment by dhoffmann1979** [comment]
in an empty dummy project it works without problems.

the log file contains to lines:
180820 13:54:17 Connecting to MySQL server host: localhost, user: root, password: set, port: not set, socket: /var/tmp/mysql.sock
Failed to connect to MySQL server: Access denied for user 'root'@'localhost' (using password: YES).

**Comment by rfay** [comment]
Oh, I think you have a pre-v0.19.0 database! You upgraded from something pre-v0.19.0? I think you might have this: https://stackoverflow.com/questions/50635617/after-upgrading-to-ddev-v0-19-0-i-cant-do-a-ddev-import-db-access-denied-for-r

Could you please try this, `ddev ssh` and `mysql -uroot -proot` and GRANT ALL ON *.* TO 'root'@'%' IDENTIFIED BY 'rooty';` and `FLUSH PRIVILEGES`;

As I remember the bottom line is that the root@% password (which should be just "root") was not correct pre-v0.19.0. 

There's also the workaround of [dumping your db](https://stackoverflow.com/questions/50123540/how-can-i-export-a-database-from-ddev) and then `ddev remove --remove-data` and reimport it. If, of course, it's what it sounds like.

**Comment by dhoffmann1979** [comment]
it was a version 1.0.0 project.
The Stackoverflow hint doesn't work because remove-data tries to make a snapshot.

The SQL Commands doesn't have the result expected.

**Comment by rfay** [comment]
If the database was from pre-v0.19.0 (possibly) and you hadn't tried an import-db in the meantime you'd get this (I think).  I'll grab an old ddev out of homebrew and try an exact workaround for you, but it will be a couple of hours from now.

**Comment by dhoffmann1979** [comment]
where can i find the database files in my file system so i can delete them manually ?

**Comment by dhoffmann1979** [comment]
SOLVED: I removed the database volume from docker and reimported a mysqldump. now it works. thx

**Comment by rfay** [comment]
Thanks!
