### ISSUE TITLE
Version mismatch error after upgrade

### ISSUE THREAD

**Issue by jmarkel** [drud/ddev#1069]
When running ``ddev start`` with an outdated set of config files, the "version" stanza in docker-compose.yaml is automatically updated to the latest. In this case, it's updated from '3' to '3.6'. If one has additional docker-compose files for add-on services, e.g. solr, created at the earlier release level, ``ddev start`` does NOT automatically change the version there to match the version in docker-compose.yaml. That causes ``ddev start`` to fail with a version mismatch error:
```Failed to start jnjhwsch: Failed to run docker-compose [-f /Users/jeff/ddev/jnjhwsch/.ddev/docker-compose.yaml -f /Users/jeff/ddev/jnjhwsch/.ddev/docker-compose.solr.yaml up -d], err='exit status 1', stdout='', stderr='Version mismatch: file /Users/jeff/ddev/jnjhwsch/.ddev/docker-compose.yaml specifies version 3.6 but extension file /Users/jeff/ddev/jnjhwsch/.ddev/docker-compose.solr.yaml uses version 3.0'```

**To Reproduce**
1. Run ``ddev config` on a site with ddev 1.0.0
2. Create a docker-compose.solr.yaml file at the same version level as docker-compose.yaml ('3')
3. Run `ddev start`` etc and bring up system
4. Update ddev to 1.1.1
5. Change .ddev/config.yaml APIVersion from v1.0.0 to v1.1.1
6. Run ``ddev start``

**Expected behavior**
Version is updated in all of the configuration's docker-compose...yaml files, and ddev containers/system launch successfully

**Screenshots**

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macOS Sierra 10.12.6
 - Docker version information:
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:26 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     true
 - ddev version information (use `ddev version`)
 - config.yaml contents for the misbehaving project
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? Solr

**Comment by rfay** [comment]
Yes, we don't think it's right to update your custom docker-compose.*.yaml so we put that in the [release notes](https://github.com/drud/ddev/releases/tag/v1.1.0) hoping people would see it. But I know lots of people wouldn't see the release notes.

**Comment by jmarkel** [comment]
I'd suggest, then, when there's a potential mismatch, that ``ddev start`` updates **NONE** of the version numbers and fails fast, with an error message to the effect that there is a mismatch and it should be resolved manually, because a partially automatic change without any accompanying instructions at runtime is a recipe for confusion (and more bug reports)

**Comment by rfay** [comment]
Our general strategy is to ask people to disable custom config during upgrades. I know that's not always expected, but we ask for it on nearly every release.  In this release there was not even a way to not update the docker-compose.yaml version, because it was invalid in version 3. 

Definitely sorry to frustrate you on this. It's kind of the tradeoff between writing lots of custom one-time code for people who customize, or trying to make it simple and hope it works out for people using the release notes.

**Comment by jmarkel** [comment]
Who do you know who reads release notes when it's a point release?

**Comment by jmarkel** [comment]
I would, though, reiterate my earlier suggestion - either fail fast and report it in a meaningful way, or do what's needed not to fail, and report what was done. In either case, it's not left to the user to decipher an at-best semi-comprehensible error message.

**Comment by rfay** [comment]
We do know that people who are smart enough to extend ddev are going to have to battle out of some of their own issues, and we'll continue to do our best to notify people when that may be needed. Maybe next time an explicit tweet or something about the exact requirement will help with this.
