### ISSUE TITLE
Provide hooks for other commands

### ISSUE THREAD

**Issue by mfrieling** [drud/ddev#1071]
Please provide hooks for commands like `stop`, `snapshot` and `restore-snapshot`. This would be useful e. g. to create snapshots or script other tasks before stopping or creating a files backup together with a snapshot which can be restored using `ddev import-files` when restoring a snapshot or starting DDEV again.

**Comment by mfrieling** [comment]
A hook for `post-ssh` would be helpful as well to e. g. source some aliases etc. I just found out that the `source` command cannot be executed via a hook, neither directly (`source [file]` nor with sh: `sh source [file]`):
```
--- Running exec command: source /mnt/ddev_config/aliases.sh ---
Failed to start trinitec: post-start exec failed: Failed to run docker-compose [-f E:\my-project\.ddev\docker-compose.yaml -f E:\my-project\.ddev\docker-compose.ssh.yaml exec -T web source /mnt/ddev_config/aliases.sh], err='exit status 126', stdout='OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"source\": executable file not found in $PATH": unknown
```

**Comment by Mon-Tea** [comment]
I think a `status` hook could be useful for e.g. a local deployment.
It could used like this:

I deploy a project and before I do this, the Deployscript checks with **ddev check-status <projectname>** if the server is always running.
If it's not running ddev start will be triggered by the Deployscript, if it's already started the next step will be executed: **ddev import-db --src=xyz.sql** ...
and so on ;)
