### ISSUE TITLE
Maybe add a troubleshooting step for host with PHP 5.6 running phpunit on 7.2

### ISSUE THREAD

**Issue by mradcliffe** [drud/ddev#1082]
Similar to [quicksprint #53](https://github.com/drud/quicksprint/issues/53), but I think this is probably a useful documentation addition to DDEV docs.

A user may have (and want to keep) PHP 5.6 on their host even though running a DDEV Drupal environment using PHP 7.2. If I ran `composer drupal-phpunit-upgrade` on the host then no files would be updated so it would be useful to update the docs as either a troubleshooting section or a testing section to refer to running `ddev exec composer drupal-phpunit-upgrade` or note.

**Comment by rfay** [comment]
I don't understand... composer is not installed on the host at all, nor is php. ddev requires nothing of the type on the host.

**Comment by rfay** [comment]
Closing until followup, none yet.
