### ISSUE TITLE
ddev remove --remove-data does not delete the database

### ISSUE THREAD

**Issue by juergen-venne** [drud/ddev#1089]
**Describe the bug**
ddev remove --remove-data

I get this error:
```
Creating database snapshot ccp_remove_data_snapshot_20180828171834
Failed to create snapshot: Failed to run docker-compose [-f /Users/jvenne/vm/dev_ccp/.ddev/docker-compose.yaml exec -T db bash -c mariabackup --backup --target-dir=/mnt/ddev_config/db_snapshots/ccp_remove_data_snapshot_20180828171834 --user root --password root --socket=/var/tmp/mysql.sock 2>/var/log/mariadbackup_backup_ccp_remove_data_snapshot_20180828171834.log], err='exit status 1', stdout='', stderr='', stdout=, stderr=
Failed to remove ddev project ccp: Failed to run docker-compose [-f /Users/jvenne/vm/dev_ccp/.ddev/docker-compose.yaml exec -T db bash -c mariabackup --backup --target-dir=/mnt/ddev_config/db_snapshots/ccp_remove_data_snapshot_20180828171834 --user root --password root --socket=/var/tmp/mysql.sock 2>/var/log/mariadbackup_backup_ccp_remove_data_snapshot_20180828171834.log], err='exit status 1', stdout='', stderr=''
```

**To Reproduce**
`ddev remove --remove-data`

**Expected behavior**
I expect the database to be removed. I don't need a snapshot.

**Screenshots**

**Version and configuration information (please complete the following information):**
```
macOS High Sierra 10.13.6
docker version:
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:26 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     true 
```
```
ddev version:
db    	drud/ddev-dbserver:v1.1.0
dba   	drud/phpmyadmin:v1.1.0
router	drud/ddev-router:v1.1.0
commit	v1.1.1
domain	ddev.local
cli   	v1.1.1
web   	drud/ddev-webserver:v1.1.0

```
config.yaml content: 
```
APIVersion: v1.1.1
name: ccp
type: typo3
docroot: web
php_version: "7.2"
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
```

**Comment by juergen-venne** [comment]
Just in case to clearify: I'm not seeking advice to fix my database. I just want to completely get rid of the containers and database files of that project.

**Comment by andrewfrench** [comment]
I can understand how snapshotting after providing `--remove-data` can lead to unexpected results (given that it's not actually removing all project data). It might be that we need to provide some more explicit flag options surrounding snapshots.

In the meantime, you can remove project data _without_ snapshotting by providing the `--omit-snapshot` flag.

**Comment by rfay** [comment]
As Andrew said, using `--omit-snapshot` solves your immediate problem. If you're interested in helping us by chasing the actual problem, you could review the log, which would help loads. 

In the example you quoted, the log is in the db container at /var/log/mariadbackup_backup_ccp_remove_data_snapshot_20180828171834.log so could be 
 reviewed by `ddev ssh -s -db` and then inspect that log, possibly with just `cat /var/log/mariadbackup_backup_ccp_remove_data_snapshot_20180828171834.log`

**Comment by rfay** [comment]
Closing, hoping this is all good for you at this point, sorry you had trouble. Happy to continue the conversation here or elsewhere.
