### ISSUE TITLE
drupal and backdrop settings.php needs to be based on default.settings.php

### ISSUE THREAD

**Issue by hmartens** [drud/ddev#1097]
**Is your feature request related to a problem? Please describe.**
When you do a "ddev config" and there is no settings.php file then ddev creates one automatically with all the db settings. But ddev is not adding the standard line that is normally in a settings.php file by default namely:
$settings['container_yamls'][] = $app_root . '/' . $site_path . '/services.yml';
This means that if you enable twig debug or any other change in your services.yml file it will not work because Drupal does not know it should load the services.yml file.

**Describe the solution you'd like**
Please make ddev add this line when it creates a settings.php file:
$settings['container_yamls'][] = $app_root . '/' . $site_path . '/services.yml';

**Additional context**
Thanks for an amazing project! You rock!

Edit by rfay 9/12/2018: IMO we need to expand the scope of this one. Essentially for Drupal6/7/8 and Backdrop we need to use the default.settings.php as a base if no settings.php is provided, rather than just writing our condensed version.  Of course we'll add the "include settings.ddev.php" stanza to it.

**Comment by dclear** [comment]
Thank you, @hmartens - we'll get this into queue!

**Comment by rfay** [comment]
One little extra detail: You're probably better having a standard settings.php in general on your project. ddev really just wants to add the settings.ddev.php, not the whole settings.php. But we probably need to copy the real default.settings.php in order to create the settings.php rather than just making one.

**Comment by rfay** [comment]
IMO we really need to make a real settings.php instead of a truncated/simple one, and that's the bottom line problem. I added that idea to the title and the OP.

**Comment by stijn-blomme** [comment]
Was able to fix this by committing a settings.local.php file under ./local-dev/settings.local.php and creating a symlink to this file in a pre-start hook 

`hooks:
  pre-start:
    - exec-host: "ln -s ../../../local/settings.local.php web/sites/default/settings.local.php"
`

**Comment by rfay** [comment]
From https://github.com/drud/ddev/issues/1811 , which is being closed in favor of this one:
* https://www.drupal.org/node/2598914 has a list of basic things that should be done for a local setup. We don't do all of them. These can be added to settings.ddev.php.
* settings.ddev.php (and other things created by ddev) could be kept in the .ddev directory

**Comment by finex** [comment]
Hi, what's the status of this issue? I'm currently fixing the problem by manually editing the settings.ddev.php with my custom settings like the one suggested by @hmartens, but a more complete settings file should be very useful. Thank you :-)

**Comment by rfay** [comment]
Hi @finex ! There's no actual progress on this specifically, but ddev has loads more ways to give you control of your settings files. Please take a read through https://ddev.com/ddev-local/controlling-cms-settings-files-in-ddev-local/ to get the full list of ways you can control it.

**Comment by finex** [comment]
Hi @rfay , thanks for the hint! There seem to be a lot of features that I wasn't aware of  :+1:
