### ISSUE TITLE
Provide links to mailhog and phpMyAdmin as PHP env variable

### ISSUE THREAD

**Issue by wmdbMattes** [drud/ddev#1098]
As a user I want to be able to see the links to both mailhog and phpMyAdmin in my CMS.
In order to provide those links, I need to be able to access them in any given way, the easiest would be env variables.
That way we can add a dedicated tab into TYPO3s admin panel allowing for quick access to the services without the necessity to remember ports.

**Comment by rfay** [comment]
My initial reaction to this is that it's getting too deeply into supporting specific needs of specific sites.

**Comment by rfay** [comment]
Is this the  same as #1099? Should we close one of them?

**Comment by wmdbMattes** [comment]
The idea in this ticket got "bigger" once more people thought about it so I'll go ahead and close this one in favour of #1099
