### ISSUE TITLE
Provide Application Links via ddev config

### ISSUE THREAD

**Issue by Lefaux** [drud/ddev#1099]
During development, my ddev setup might bring in additional applications like a SOLR Management Interface, Redis UI or Elasticsearch UIs.

As a developer, I want to be able to provide application links based on configuration in config.yaml.

In my concrete application (and maybe even in DDEV UI) I want to be able to access those links easily (on PHP level maybe as env variables or alike.
Placeholders for the project's URL might come in handy as well.

Idea of config.yaml

```
APIVersion: v1.1.1
name: awesome-project
type: typo3
docroot: public
php_version: "7.2"
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
applicationLinks:
  "Bitbucket Repo": https://bitbucket.typo3.com/repo/browse/awesome-repo
  "Mailhog": {projectUrl}:1025
  "PHPMyAdmin: {projectUrl}:8036
  "Elasticsearch HEAD": {projectUrl}:9200/_plugins/HEAD
```

**Comment by rfay** [comment]
Could you say more about where the links would be used? Are they for inside the container? Outside? Are they for presentation to the developer? In `ddev describe`?

**Comment by wmdbMattes** [comment]
ddev describe would the one place.
The main usecase to me would be having it as part of the rendered HTML in the CMS.
So as I am logged into TYPO3 I want to show those links in the system panel to allow quick access to developer-related resources like a Confluence page, Mailhog, PhpMyAdmin or even a link to an interactive click dummy.

This way devs don‘t have to jump back and forth between readme.md and the system

**Comment by rfay** [comment]
`ddev describe` now provides links to services which are exposed via ddev-router. Closing.
