### ISSUE TITLE
nginx-php-fpm container should not change permissions/ownership of mounted files

### ISSUE THREAD

**Issue by rfay** [drud/ddev#110]
## What happened (or feature request):

The /start.sh that we ship with nginx-php-fpm7 container does this:

`chgrp -R nginx /var/www/html`

This changes the file permissions of the mounted files, which is pretty much a no-no.

It also takes forever, and makes our ddev startup take 30+ seconds when it could probably take just 5-6 seconds (to be seen). 

## What you expected to happen:

File permissions on the mounted filesystem should be left as-is. 

## How to reproduce it (as minimally and precisely as possible):

Inspect the start.sh

## Related source links or issues (like source JIRA issue):

Related issue, #96 - which deals with the problems that result from changing owner and perms.

**Comment by rickmanelius** [comment]
@rfay is this still valid/actionable?

**Comment by rfay** [comment]
I think we solved this long ago.

**Comment by rfay** [comment]
However, we'll certainly look closely in the security change and make sure it's not doing it, so it's valid to leave it open for review. Bottom line is we don't want to change owner or group (ever) on host-mounted files.

**Comment by rickmanelius** [comment]
Alrighty. We'll leave it in v0.7 to confirm. Thanks!

**Comment by rfay** [comment]
The offending chgrp is definitely not in there any more. Closing.
