### ISSUE TITLE
Bind mount source path has changed and unable to "ddev start"

### ISSUE THREAD

**Issue by rpkoller** [drud/ddev#1102]
Hi, I've installed DDEV 1.1.1 via Homebrew on MacOS 10.13.6 with Docker 18.06.1-ce-mac73 (26764). Docker had the basic setup. I've simply installed a current Drupal 8 install with `composer create-project drupal-composer/drupal-project:8.x-dev ddevsite --stability dev` in `~/sites` for initial testing purposes. But the install was creeping slow and so was the loading of each new page afterwards - the CPU peaked between 100 to 160% constantly and the fans where steadily running at max.everything took forever. I performed a `ddev stop` afterwards. After some research I then went with the recommendations of the following post over in the docker for-mac issue tracker 
https://github.com/docker/for-mac/issues/1759#issuecomment-412486531 . Kubernetes got disabled, switched off experimental features on daemon, set under advanced to `1 cpu`, to`4gb` out of `8gb` of memory and left swap to `1gb` and removed under file sharing `/users` and `/volumes` and replaced the former with `/users/myuser/sites` (the directory containing all the web related projects utilizing docker). problem is when i try to restart the ddevsite project with `ddev start` afterwards i get: 

`Unable to get project(s): a project (web container) in exited state already exists for ddevsite that was created at /Users/myuser/sites/ddevsite`

When i take a look into the `.ddev` subfolder inside the `ddevsite`project folder i am unable to find any hint to a path containing `/Users/myuser/sites/ddevsite` neither in the `config.yaml` nor in the `docker-compose.yaml`. I also looked into `/Users/myuser/sites/ddevsite/web/sites/default/settings.ddev.php` also nothing in that regard. Is there a way to update the bin mount source path so i am able to utilize the already present setup so that i dont end up having any unused old skeletons in the closet? Thanks Ralf

**Comment by rfay** [comment]
Somehow you ended up with a web container created in a different directory. You should be able to use `ddev rm -R ddevsite` to get rid of it; if not, `docker rm -f $(docker ps -aq)` will kill off all containers (including non-ddev containers). `docker ps -a` shows all containers including non-ddev containers.

**Comment by rpkoller** [comment]
at first thanks for the fast reply!

hmmmm strange thing is I never moved anything?! I just removed `/users`and`/volumes`from the file sharing setting in the docker prefs as I told while ddevsite was stopped. So the site is still recognized: 

```
$> ddev list
NAME      TYPE     LOCATION          URL(s)                       STATUS
ddevsite  drupal8  ~/sites/ddevsite  http://ddevsite.ddev.local   stopped
                                     https://ddevsite.ddev.local

DDEV ROUTER STATUS: not found
The router is not currently running. Your sites are likely inaccessible at this time.
Try running 'ddev start' on a site to recreate the router.
```

Odd thing is that the router container isn't found and shown when I perform: 

```
$> docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                    PORTS               NAMES
a0c4cbb23bf1        drud/phpmyadmin:v1.1.0       "/run.sh phpmyadmin"     13 hours ago        Exited (0) 13 hours ago                       ddev-ddevsite-dba
158fad8af18a        drud/ddev-webserver:v1.1.0   "/start.sh"              13 hours ago        Exited (0) 13 hours ago                       ddev-ddevsite-web
cd15c4138d39        drud/ddev-dbserver:v1.1.0    "/docker-entrypoint.…"   13 hours ago        Exited (0) 13 hours ago                       cd15c4138d39_ddev-ddevsite-db
```

the router container isn't showing up there.  ddev doesn't have anything else where it stores anything? everything could be found either with `docker ps -a`on the container side or within the project inside `.ddev`? So safest and cleanest would be simply destroying those three containers and deleting the ddevsite folder and start fresh?

**Comment by rfay** [comment]
I don't think anything will work if you removed /Users from the docker share. And do `docker rm -f $(docker ps -aq)` to get rid of the stopped containers.

**Comment by rfay** [comment]
I recommend that you do a docker reset-to-defaults as a starting point; if you do that you don't even have to remove those containers. It will give you a decent starting point. That will also delete the docker volume that has your database on it, so that will be clean as well.

**Comment by rpkoller** [comment]
thanks a lot! indeed the reset was the fastest and most convenient way. thanks for the heads up! will try later to find a configuration without fans running and faster execution on the docker side of things :)
