### ISSUE TITLE
Can't execute ddev start command, docker problem

### ISSUE THREAD

**Issue by iamandrewluca** [drud/ddev#1105]
I tried to change the version in `docker-compose.yaml` but when I run `ddev start` it changes back to `3.6`  
I recently upgraded to Ubuntu 18.04  
I had this problem also with `ddev v1.1.0`  
Anybody encountered this issue?

```bash
⇒  ddev start
Starting my-project...Running Command  Command=ip address show dev docker0
Version in "/home/aluca/Projects/my-project/.ddev/docker-compose.yaml" is unsupported.

You might be seeing this error because you're using the wrong Compose file version.
Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key,
or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

Failed to start my-project: Failed to run docker-compose [-f /home/aluca/Projects/my-project/.ddev/docker-compose.yaml up -d],
err='exit status 1', stdout='', stderr='Version in"/home/aluca/Projects/my-project/.ddev/docker-compose.yaml" is unsupported.
```
```bash
⇒  uname -a
Linux acula 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
```bash
⇒  lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```
```bash
⇒  docker -v
Docker version 18.06.1-ce, build e68fc7a
```
```bash
⇒  docker-compose -v
docker-compose version 1.19.0, build 9e633ef
```
```bash
⇒  ddev version
commit  v1.2.0
domain  ddev.local
cli     v1.2.0
web     drud/ddev-webserver:v1.2.0
db      drud/ddev-dbserver:v1.2.0
dba     drud/phpmyadmin:v1.2.0
router  drud/ddev-router:v1.2.0
```
```bash
⇒  head -n 4 .ddev/docker-compose.yaml
version: '3.6'
#ddev-generated
services:
  db:
```

**Comment by rfay** [comment]
docker-compose.yaml is autogenerated every time ddev starts; the version there is the one that should be used. If you're using ddev v1.1.0+ it will be 3.6.

docker-compose.yaml is [not user-editable](https://ddev.readthedocs.io/en/latest/users/extend/custom-compose-files/#restrictions-on-the-docker-composeyaml-file) the way you make changes is by adding on additional docker-compose.*.yaml files that override or add additional features. See https://ddev.readthedocs.io/en/latest/users/extend/custom-compose-files/

There are a number of examples of docker-compose addons that users have come up with in https://stackoverflow.com/tags/ddev

**Comment by iamandrewluca** [comment]
Ok, it seems is because of outdated `docker-compose`.  
Aptitude on ubuntu has an older version of `compose`  
I installed last version using [this instructions](https://docs.docker.com/compose/install/#install-compose) and it started. Thanks!

**Comment by rfay** [comment]
Thanks, yeah Linux users have a lot of trouble with that. We have a docker install page, https://ddev.readthedocs.io/en/latest/users/docker_installation/ to try to guide people, but it's not that easy!
