### ISSUE TITLE
apache-fpm (and probably apache-cgi) webserver_type don't work on windows

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1109]
**Describe the bug**
Ooops. We never tested apache-fpm on Windows, (and don't have automated tests yet). And we probably weren't planning on automated tests on Windows for apache-fpm :(

Basically, we generate a username in apache's envvars directory, and it comes out to be uid_0, but we don't have uid_0 in /etc/passwd. 

**To Reproduce**

Try running any project with apache-fpm for the webserver type on Windows. It doesn't work.

**Additional context**

This can be fixed by just adding uid_0 and gid_0 to the /etc/passwd and /etc/group file, I think.

**Comment by Outdoorsman** [comment]
Just confirming what you've already said here. I'm getting this error after doing `ddev config` and setting it to `apache-cgi` or `apache-fpm`.

```
Failed to start test2: web service health check timed out: labels map[com.ddev.site-name:test2 com.docker.compose.service:web] timed out without becoming healthy, status=unhealthy
```

**Comment by rfay** [comment]
@Outdoorsman Would love to have you test the artifacts for #1111 in https://circleci.com/gh/drud/ddev/3537#artifacts/containers/0

**Comment by Outdoorsman** [comment]
@rfay I installed `.exe` file in Windows from above and got this error... 

```
#1: PHP Warning: igbinary_unserialize_header: unsupported version: "O:44"..., should begin with a binary version header of "\x00\x00\x00\x01" or "\x00\x00\x00\x02" in /var/www/html/example.com/typo3_src-6.2.31/typo3/sysext/core/Classes/Cache/Frontend/VariableFrontend.php line 99
```

**Comment by rfay** [comment]
Do you have some post-start steps in your config.yaml? Please comment them out for now if you would, and do a `ddev rm` and a `ddev start` again.

**Comment by rfay** [comment]
Wait a minute. TYPO3 6.2? We haven't ever deliberately supported anything before TYPO3 8... ???

**Comment by Outdoorsman** [comment]
Oops, yes this was in `config.yaml`. I did a `ddev remove` and `ddev start` again and got the same error.

```
hooks:
  post-start:
  - exec: sudo apt-get remove --yes php-igbinary
```

This may just be a TYPO3 6.2 issue as you're pointing out. My personal reason for needing Apache is because I can't get TYPO3 4.5 or 6.2 to run in Nginx and I have ton of these to update still.

**Comment by rfay** [comment]
Can you point me to some step-by-step instructions on how to do a simple 6.2 project? Maybe you could do one and see if you have this problem on a plain vanilla TYPO3 6.2. Push it to github or give me a tarball? I'll give it a try. But I don't have that much expertise with TYPO3 in general, and certainly not with old versions.
