### ISSUE TITLE
Linux installer looks for "brew"

### ISSUE THREAD

**Issue by finex** [drud/ddev#1114]
I've just updated ddev to latest 1.2 (from 1.1) on Archlinux and the installer returned the following error before completing the process:

```
which: no brew in (/path)
```
(`/path` is an example)
 
**Steps to reproduce the behavior:**
1. Execute `curl https://raw.githubusercontent.com/drud/ddev/master/install_ddev.sh | bash`

**Expected behaviour**
'brew' should not be looked for on linux environment.

**Version and configuration information**
 - Host computer OS and Version: Archlinux 4.18.7-arch1-1-ARCH
 - Docker version information: 18.06.0-ce

**Comment by rfay** [comment]
I'm unable to recreate the behavior you specified with `curl https://raw.githubusercontent.com/drud/ddev/master/install_ddev.sh | bash` on Ubuntu 16.04. That installer hasn't changed in forever, so I'm surprised you'd have a different experience. Have you perhaps globally set `set -o pipefail` in your bash environment?

It really shouldn't use "which" anyway, it should use "command", but the reason it uses it is to figure out if there's a different place to put the bash completion stuff, and there *should* be nothing wrong with using that on Linux.

**Comment by finex** [comment]
Hi @rfay ... I'm using ZSH, not Bash, could this be the cause?

**Comment by rfay** [comment]
Well, the technique you said you used, `curl https://raw.githubusercontent.com/drud/ddev/master/install_ddev.sh | bash` explicitly uses bash, so I don't see that happening. Could you try it again in a new terminal window? It does no harm.

**Comment by finex** [comment]
Same thing... After the error i've also the following message but it shouldn't be related:

```
Bash completion for ddev was not installed. You may manually install /tmp/ddev_bash_completion.sh in your bash_completions.d directory.
```
I've also tried on a clean Manjaro virtual machine (based on archlinux) and I've got the same error message. I confirm it is working on Ubuntu... very strange...

**Comment by rfay** [comment]
I went ahead and tested this in Arch Linux and saw the output you mention, but it's not fatal, the script finishes just fine. install_ddev.sh is *not* just a linux script but also macOS, which is why it's putting the bash completion stuff in the right place *if* it finds homebrew. https://github.com/drud/ddev/pull/1119 will quiet that message.
