### ISSUE TITLE
ddev with apache - mod.ssl is not installed by default

### ISSUE THREAD

**Issue by peterbenke** [drud/ddev#1126]
I have a OXID eShop running with ddev / ngnix and everything works fine.
Tried to change to Apache, but there I have problems to run the website with ssh.
I get "ERR_TOO_MANY_REDIRECTS" in admin-area and links with parameter "force_sid", which is an indication, that ssl does not work properly.

config.yaml:
`webserver_type: apache-fpm`

Looking enabled modules:
`ddev ssh
cd /etc/apache2/mods-enabled/`

=> mod.ssl is missing

Tried to create symbolic links inside /etc/apache2/mods-enabled/ to /etc/apache2/mods-available/
`ln -s ../mods-available/ssl.conf ssl.conf`
`ln -s ../mods-available/ssl.load ssl.load`

And then:
`ddev restart`

=> Failed...

So, could you enable mod.ssl by default?

`ddev version:`
`cli   	v1.2.0`               
`web   	drud/ddev-webserver:v1.2.0`
`db    	drud/ddev-dbserver:v1.2.0`
`dba   	drud/phpmyadmin:v1.2.0`  
`router	drud/ddev-router:v1.2.0`
`commit	v1.2.0`
`domain	ddev.local`

Thank you

**Comment by rfay** [comment]
First, if everybody is likely to need mod.ssl, we can certainly enable it. 

But you can enable any module you want in a post-start hook:

```
hooks:
    post-start:
      - exec: bash -c "a2enmod ssl && apachectl restart"
```

HOWEVER... I doubt that's what you want. SSL in ddev is terminated on the *router*, a completely different container running nginx. 

And.. We noted an important problem with apache redirects under ssl. Could you please test https://github.com/drud/ddev/pull/1124 and see if that solves the problem for you? You can just add `webimage: drud/ddev-webserver:20180922_apache_https` in your .ddev/config.yaml.

**Comment by peterbenke** [comment]
Hi Randy,

thank you!
Yes, adding `webimage: drud/ddev-webserver:20180922_apache_https` to my config.yaml solved the problem. But, this is just a workaround for the moment, right?

**Comment by rfay** [comment]
That PR #1124 will make it into the next release v1.3.0 in a couple of weeks. Closing this as a dup then. (Feel free to continue the conversation). If you'd confirm in #1124 that it solves your problem that would be great.
