### ISSUE TITLE
Add explicit ddev composer (in container) support "ddev composer" command

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1131]
**Is your feature request related to a problem? Please describe.**

macOS and Linux users often use composer on the host, and it *can* work out OK, although there are problems with matching php versions and available packages.

However, on Windows a "composer install" can result in generated code that is not even reasonable correct for the deployment environment (ddev web container or Linux server). For example, if you use `composer require drush/drush` on windows, you get completely different content for vendor/bin/drush than you would get with the same command in the container. 

**Describe the solution you'd like**

As a result, it's my opinion that we should be pushing all users toward using composer in the container, using a `ddev composer` command that would support most composer actions. 

It should be able to do at least `ddev composer install`, `ddev composer upgrade` and `ddev composer create-project`. The first two are trivial (already). create-project is harder because it has to be done in a dummy directory and then the contents copied in.

I don't actually see how there's a lot of work to be done to accomplish any of these other than create-project. The others should just be pass-through commands working just like `ddev exec composer ...`

It's actually possible that we don't need anything more than a `ddev composer-create-project`, and that all the other composer commands are so easily handled with exec.

**Describe alternatives you've considered**

https://stackoverflow.com/questions/49660082/how-can-i-run-composer-with-ddev shows the current state of the art; The last two links are user-provided techniques that work, but are awkward. 

**Additional context**

Related problems: 
* [As a ddev user, I want to be able to use ssh/rsync from within the web container #414](https://github.com/drud/ddev/issues/414) would allow those with private repositories to easily access them, and there are a number of people with private composer repos.
* The solution here should probably provide for a shared (mounted from host) composer cache for each php version.

**Comment by dclear** [comment]
@afrench: can you add a relative estimate / complexity for this? Gracias!

![screen shot 2018-10-23 at 1 42 40 pm](https://user-images.githubusercontent.com/1197912/47386311-8e5c8a00-d6c9-11e8-8233-7aa7a46d9ace.png)

**Comment by medarob** [comment]
I tried DDEV on windows with TYPO3 and I didn't even know that there could be a difference between using composer inside or outside the container. I used it outside the container. This is a very confusing topic because it seems to work outside the container aswell. I would like to have a general recommended approach.

**Comment by rfay** [comment]
The `ddev composer` command is coming to you in this week's release, v1.4.0. We hope you'll like it and it will help give you a predictable usage pattern for composer.
