### ISSUE TITLE
A command to lockdown a specific DDEV image from connecting to the internet

### ISSUE THREAD

**Issue by cferthorney** [drud/ddev#1133]
**Is your feature request related to a problem? Please describe.**
I have a known hacked Drupal 7 code base full of `base64_encode()` PHP which connects to a site that itself is hacked and full of malware. I need to test the extent of such the hack (Checking content, etc rather than hacked modules). It would be nice to be able to say to DDEV to not allow this image to connect to anything remote resource (Possibly even my local environment for safety)

**Describe the solution you'd like**
It would be nice to have a parameter on `ddev start` such as `ddev start --no-network` or something which would stop any network traffic on that site from connecting to the outside world.

**Describe alternatives you've considered**
- Having run `base64_decode()` the PHP, I put the URL the site is connecting to in my host file as `127.0.0.1` and `::1`. This is effective, but isn't as elegant as having it automatically stopping it connecting to all URLs (In case I missed one). I didn't want to let it "phone home" to an address I'd missed in content/not spotted in the X hundred additional PHP files due to marginally different encoding.
- I disabled `base64_decode` and `setcookie` in the DDEV PHP instance's `php.ini` file to stop it decoding. I don't like disabling something Drupal may need to use (I am thinking security plugins, or console tools such as `platform` here). `setCookie` obviously stops me from logging in without some work to spoof a session cookie. Realistically not viable longer term.
- Considered writing something to add to the DDEV router, but I don't understand DDEV's routing protocols well enough and didn't want to risk breaking every other site I have on there.
- Considered just cleaning up the code, but again I could easily miss stuff.  This was an inherited project with no git history, massively behind on updates, poor multisite use etc, poorly documented patching (Both available on Drupal.org and written by the developer).  The client also wanted to know the extent of the hack.

**Comment by rfay** [comment]
I recommend you install a firewall like ufw in the web container for this project.

For example, 

hooks:
  post-start:
    - exec: bash -c "sudo apt-get update && sudo apt-get install ufw"
   - exec: bash -c "sudo ufw default deny outgoing && sudo ufw default deny incoming"

I tried this (in ddev ssh) and it *failed*; ufw/iptables were unwilling to work.  ([Simple ufw link](https://askubuntu.com/questions/448836/how-do-i-with-ufw-deny-all-outgoing-ports-excepting-the-ones-i-need)

Docker-compose add-ons could also be used, https://docs.docker.com/network/

But don't forget that just shutting down networking on your *host* is a super effective way to do this. Turn off networking on the host while you're working on this project. 

Just an FYI: I had a server compromised with the same drupalgeddon2. I rolled back to pre-drupalgeddon2 backups and rebuilt the server from scratch. It's not possible to know what else in the system (other than the codebase) is compromised. The stuff you're looking at is just the entrypoint.

**Comment by rfay** [comment]
This simple solution seems to work fine:

Add a .ddev/docker-compose.nonetwork.yaml with these contents:
```
version: '3.6'
services:
  web:
    network_mode:  none
```

**Comment by cferthorney** [comment]
Thanks Randy. I consider this closed :)

**Comment by rfay** [comment]
Just don't forget that with that solution you really can't do networking, meaning no web access from the host. You may want to create a special image for this project, using docker to derive FROM ddev-webserver image and maybe adding lynx to it. curl is already on there, so you can use that, but it's hard to work a site too much with that.
