### ISSUE TITLE
Allow disabling containers (phpmyadmin, etc)

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1152]
**Is your feature request related to a problem? Please describe.**

People regularly ask for the ability to disable phpmyadmin container. On occasion they ask to disable the ddev-dbserver. 

This would be a very simple add to the config.yaml. 

**Describe the solution you'd like**

```
omit_containers: 
    - phpmyadmin
    - ddev-dbserver
```

**Comment by KaffDaddy** [comment]
+1 for this feature request. I have not used the phpmyadmin container once since I use DDEV. I am using 'ddev sequelpro' on macOS. I know that this feature is only available on my OS and not on windows machines, but I wish to have this feature. :-)
