### ISSUE TITLE
Wordpress projects don't need the warning to run wp to change URL

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1156]
**Describe the bug**

Wordpress projects don't need the warning to run wp to change the URL. Instead, we should be adding 
define('WP_HOME', <site_url>);, and no changes will be required. 

So:
1. Remove that from post-import-db action (or remove the action if that's all that's in there)
2. Add WP_HOME setting to config-wp-ddev.php

**Comment by andrewfrench** [comment]
This will be resolved in #932
