### ISSUE TITLE
Improve usability of snapshot and restore-snapshot

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1163]
**Is your feature request related to a problem? Please describe.**

Our database snapshot feature is nice, but could use some usability improvements:

**On `ddev snahpshot`**
* If no snapshot name is provided, ask for one, offering the current timestamped snapshot name as a default.

**On `ddev restore-snapshot`
* If no name is provided, offer a list with the most recent at the top
* Add autocompletion for possible names (This might be a heavy lift, not sure)

**Comment by mglaman** [comment]
What if it just autogenerated a name for me, if I didn't provide one? Or a default on the prompt for a name. Generally I don't want to think of a name and just want a project name with timestamp. Unless I took one for a very specific reason beyond "I want a quick rollback option.

Restore should show a list.

**Comment by rfay** [comment]
It already does autogenerate a name, based on date/timestamp. Just `ddev snapshot` does that.

**Comment by rfay** [comment]
@ultimike commented in https://github.com/drud/ddev/issues/1057#issue-351212850

> The snapshot functionality is solid - love it so far! Here's a couple of suggestions to make it even better:

> Have "ddev restore-snapshot" automatically restore the most recent snapshot when no snapshot_name is provided.
> Add a "ddev snapshot --list" flag to show a list of all available snapshots for a given project.
> I could also be convinced to move "ddev restore-snapshot" to "ddev snapshot --restore" - I think having a small set of commands is one of the really nice things about DDEV.

> -mike

I'll keep this issue and close the other one.

**Comment by karol-haltenberger** [comment]
A few suggestions:

`ddev snapshot -d/--delete`     Delete last snapshot....or maybe list snapshots to be more safe and...
`ddev snapshot -d/--delete -n <snapshot-name>`   Delete named snapshot

It could also be a different command: `ddev delete-snapshot [-n]`

**Comment by tommym9** [comment]
A way to list snapshots from the cli would be fantastic.

Also being able to pass a name to the `ddev snapshot` command would be useful. For example `ddev snapshot before-d9-upgrade`

Cheers

Tom

**Comment by rfay** [comment]
`ddev snapshot` already has --name option and it's recommended. See `ddev snapshot -h`

Adding a custom command to list snapshots is super easy and it's a great idea!

**Comment by rfay** [comment]
I hope you'll all try out v1.17.0-alpha3 and give your feedback! - that includes @ultimike, thanks!

**Comment by bserem** [comment]
Just got the 1.17 release and I wanted to say a huge thanks for this.

**Comment by rfay** [comment]
Thanks is due to amazing work of @cmuench !
