### ISSUE TITLE
Fix ABSPATH detection on Windows

### ISSUE THREAD

**Issue by andrewfrench** [drud/ddev#1175]
**Describe the bug**
WordPress in a subdirectory on Windows causes the ABSPATH value to erroneously contain a `.` character instead of the correct path.

**To Reproduce**
On Windows, 

- Create a WordPress project where WP is located in a directory like: `docroot/wp/` and has no existing wp-config.php
- `ddev config`
- `docroot/wp-config.php` has an incorrect ABSPATH value

**Expected behavior**
ABSPATH should be set to something like `dir(__FILE__) . "/wp"`, not `dir(__FILE__) . "/."`

**Version and configuration information (please complete the following information):**
- Windows
- ddev v1.3.0

**Comment by rfay** [comment]
We might as well add the test stanza for WP-in-subdir (https://github.com/drud/ddev/issues/1167) in this one. Once again we're skunked by not having Windows tests for a new feature.
