### ISSUE TITLE
ddev config fails on Windows with a panic

### ISSUE THREAD

**Issue by ms-slasher13** [drud/ddev#1177]
**Describe the bug**
Project Type [wordpress, typo3, backdrop, php, drupal6, drupal7, drupal8] (php):                                                                                                                                                                                                drupal8
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xa19c45]

goroutine 1 [running]:
github.com/drud/ddev/pkg/ddevapp.(*DdevApp).CreateSettingsFile(0xc0001a1380, 0x0                                                                                                                                                                                               , 0x0, 0x0, 0x0)
        /go/src/github.com/drud/ddev/pkg/ddevapp/apptypes.go:104 +0x585
github.com/drud/ddev/cmd/ddev/cmd.handleConfigRun(0x1426ea0, 0x1453620, 0x0, 0x0                                                                                                                                                                                               )
        /go/src/github.com/drud/ddev/cmd/ddev/cmd/config.go:111 +0x2f8
github.com/drud/ddev/vendor/github.com/spf13/cobra.(*Command).execute(0x1426ea0,                                                                                                                                                                                                0x1453620, 0x0, 0x0, 0x1426ea0, 0x1453620)
        /go/src/github.com/drud/ddev/vendor/github.com/spf13/cobra/command.go:76                                                                                                                                                                                               6 +0x2d3
github.com/drud/ddev/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1428fe0                                                                                                                                                                                               , 0xc000209f88, 0x405537, 0xc000064058)
        /go/src/github.com/drud/ddev/vendor/github.com/spf13/cobra/command.go:85                                                                                                                                                                                               2 +0x304
github.com/drud/ddev/vendor/github.com/spf13/cobra.(*Command).Execute(0x1428fe0,                                                                                                                                                                                                0x0, 0x0)
        /go/src/github.com/drud/ddev/vendor/github.com/spf13/cobra/command.go:80                                                                                                                                                                                               0 +0x32
github.com/drud/ddev/cmd/ddev/cmd.Execute()
        /go/src/github.com/drud/ddev/cmd/ddev/cmd/root.go:105 +0x42
main.main()
        /go/src/github.com/drud/ddev/cmd/ddev/main.go:6 +0x27

**To Reproduce**
1. ddev config
2. ...
3. enter drupal8

**Version and configuration information (please complete the following information):**
 - Windows 10
 - Docker 18.06.1-ce
 - ddev version 1.3.0

**Comment by rfay** [comment]
Wow, sorry for the trouble and thanks for letting us know.

I'm unable to recreate this on Windows 10 Pro with Docker for WIndows. (You didn't mention the Windows 10 version you're using though).

I assume you're typing in "drupal8" because ddev didn't automatically recognize your project as drupal8? Was there an existing .ddev/config.yaml?

Anyway, if you can recreate this we'd love to work with you on it. If it would be possible to provide us a tarball or some other way to see the structure of your repository?

Did this work for you with ddev v1.2? If you weren't a ddev v1.2 user, do you have some overly ambitious virus checker/security program?

Thanks for working with us on this. We don't want you or anybody else to have that panic!

**Comment by andrewfrench** [comment]
For reference:
https://github.com/drud/ddev/blob/73e7f0f694f6ad7662525d6c4c0023d5dc49f4ab/pkg/ddevapp/apptypes.go#L100-L113

I'm specifically interested in the entire state (contents, permissions, entire paths to, etc) of your `$DOCROOT/sites/default` and `$DOCROOT/sites/default/settings.ddev.php` files if they exist. Like @rfay, I haven't had any luck trying to reproduce this on Windows 10 Pro 1803, Docker 18.06.1-ce, and ddev v1.3.0.

**Comment by rfay** [comment]
Ah, I do see that the repo was *not* autodetected (it was detected as PHP). `Project Type [wordpress, typo3, backdrop, php, drupal6, drupal7, drupal8] (php): drupal8`

**Comment by rfay** [comment]
I think I see what's going on here. We're getting an err that is *not* about not existing, a different error. Thus we have an invalid fileinfo. Then we try to use the fileinfo.

**Comment by rfay** [comment]
```
$ sudo chown root sites && sudo chmod 000 sites
$ ddev config
You are reconfiguring the project at /Users/rfay/workspace/d8git.
The existing configuration will be updated and replaced.
Project name (d8git):

The docroot is the directory from which your site is served. This is a relative path from your project root (/Users/rfay/workspace/d8git)
You may leave this value blank if your site files are in the project root
Docroot Location (current directory):
Found a drupal8 codebase at /Users/rfay/workspace/d8git.
Project Type [wordpress, typo3, backdrop, php, drupal6, drupal7, drupal8] (drupal8):
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x160286e]

goroutine 1 [running]:
github.com/drud/ddev/pkg/ddevapp.(*DdevApp).CreateSettingsFile(0xc00016b860, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/drud/ddev/pkg/ddevapp/apptypes.go:104 +0x57e
github.com/drud/ddev/cmd/ddev/cmd.handleConfigRun(0x200c080, 0x2039ce0, 0x0, 0x0)
	/go/src/github.com/drud/ddev/cmd/ddev/cmd/config.go:111 +0x2f1
github.com/drud/ddev/vendor/github.com/spf13/cobra.(*Command).execute(0x200c080, 0x2039ce0, 0x0, 0x0, 0x200c080, 0x2039ce0)
	/go/src/github.com/drud/ddev/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/drud/ddev/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x200e1c0, 0xc0001e9f88, 0x10053a0, 0xc00006e058)
	/go/src/github.com/drud/ddev/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/drud/ddev/vendor/github.com/spf13/cobra.(*Command).Execute(0x200e1c0, 0x0, 0x0)
	/go/src/github.com/drud/ddev/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/drud/ddev/cmd/ddev/cmd.Execute()
	/go/src/github.com/drud/ddev/cmd/ddev/cmd/root.go:105 +0x3b
main.main()
	/go/src/github.com/drud/ddev/cmd/ddev/main.go:6 +0x20
```

**Comment by rfay** [comment]
@ms-slasher13 just a note that you should be able to get past this problem by just setting the permissions on your host filesystem to writeable for the whole project. Right-click on the project in Explorer and uncheck the "read-only" checkbox and apply.

<img width="365" alt="windows_10_pro" src="https://user-images.githubusercontent.com/112444/47102418-f4449f80-d1f9-11e8-8bf9-10d5a7b304f5.png">


This will be solved in https://github.com/drud/ddev/pull/1213 in the next release, and we appreciate you letting us know about it and describing it so well.
