### ISSUE TITLE
critical invalid character error with `dev config pantheon`

### ISSUE THREAD

**Issue by kay-o** [drud/ddev#1200]
**Describe the bug**
Two separate machines have same issue with dev config pantheon:
```
$ ddev config pantheon
Creating a new ddev project config in the current directory (/Users/username/projectname) 
Once completed, your configuration will be written to /Users/username/projectname/.ddev/config.yaml

Project name (projectname):
invalid character '-' after top-level value
```

**To Reproduce**
1. on High Sierra, enter the following in Terminal (success at each except ```ddev config pantheon```):
```
$ git clone ssh://username@serveraddress.drush.in:2222/~/repository.git projectname
$ cd projectname/
$ brew upgrade
$ brew tap drud/ddev
$ brew install ddev
$ ddev auth-pantheon ***
$ ddev config pantheon
```
2. See error above
3. retry with different Pantheon-based projects with different naming patterns
4. retry on other Mac machines with same result (one of which had recently updated ddev with brew vs new install; that machine required removal of old versions)
5. confirm ddev config works when no 3rd party is specified (success at each):
```
$ ddev config
$ ddev start
```

**Expected behavior**
Creation of .ddev/config.yml

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macOS High Sierra
 - Docker version information (use `docker version`) and insert it here.
one machine with
```
Client:
 Version:           18.09.0-ce-beta1
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        78a6bdb
 Built:             Thu Sep  6 22:41:53 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
 Version:           18.09.0-ce-beta1
 API version:       1.39 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       78a6bdb
  Built:             Thu Sep  6 22:41:53 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```
and another machine with
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```
 - ddev version information (use `ddev version`)
 - config.yaml contents for the misbehaving project
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

**Additional context**
Add any other context about the problem here. Thanks!

**Comment by andrewfrench** [comment]
Hi @kay-o, thanks for reporting this!

It looks to me like this is a result of some malformed JSON being returned by Pantheon in response to a request for your sites, unmarshaled on line 53 below:

https://github.com/drud/ddev/blob/6e61e6be56a3781437f9cfc05673ab161e978fa2/vendor/github.com/drud/go-pantheon/pkg/pantheon/session.go#L29-L54

I'm not having much luck getting Pantheon to return malformed JSON, are you able to confirm that you can still reproduce this and it's not a transient API issue from Pantheon?

**Comment by rfay** [comment]
@kay-o Would it be possible for you to add me to your pantheon project on this temporarily? I don't think we'll be able to solve it otherwise. My pantheon account is randy <at> randyfay.com. @andrewfrench is correct, you're getting a Pantheon response that we've never seen before.

**Comment by rfay** [comment]
@kay-o without help from you we can't do anything with this issue, but we look forward to continuing the conversation. Closing this for now as no response.
