### ISSUE TITLE
Add file sequelpro.spf to .gitignore in .ddev folder

### ISSUE THREAD

**Issue by spoonerWeb** [drud/ddev#1216]
**Is your feature request related to a problem? Please describe.**
When I open SequelPro in a ddev project, the file `sequelpro.spf` is generated, but not deleted after closing the application. Then, I have this file as not ignored file in my Git repository.

**Describe the solution you'd like**
I would like to have that file in .gitignore file in .ddev folder which is generated (and overwrites my changes)

**Comment by rfay** [comment]
Absolutely, thanks. Also an interim note, you can take over the .gitignore in the project .ddev just by removing the `#ddev-generated:` first line, then ddev will respect that you own it.
