### ISSUE TITLE
As a developer, I want a strategy for integration with 3rd party providers.

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#122]
## What happened (or feature request):

Feature Request

## What you expected to happen:

As part of the overarching goals of the DRUD product suite, we have made `ddev` such that it can be used as a stand-alone project. That said, we want to make sure that it can integrate with various 3rd party PaaS hosting solutions as well as other endpoints (which can be as simple as a drush archive). The concept of "private plugins" is touched on here because we need to allow organizations to create their own versions that are not fit to include in the public repo.

This proposal issue is going to require a significant amount of work before this is actionable. However, this is something that we need to get ahead of for the purpose of creating and maintaining runway. 

This will need a meeting/discussion to discuss the architecture and technical implications before it can become actionable.

**Comment by rickmanelius** [comment]
IMHO, issue #183 is a critical dependency for this. This issue then becomes a specific set of metadata and business logic to implement it.

**Comment by rickmanelius** [comment]
I consider this in an actionable state.

**Comment by rickmanelius** [comment]
In addition to extending existing commands, we should consider when a 3rd party integration may require new commands. I think I may take a crack at this tomorrow.

**Comment by rickmanelius** [comment]
Inventory Potential of End-user Goals

## Data

* Pull down database from production.
* Pull down database from one of several environments.
* Pull down files from production.
* Pull down database from one of several environments.
* Push files and/or database to one of several environments.

## Pre/Post Hooks

* Post import of files OR database, run an arbitrary set of commands specified in a yml file.
* Pre import of files OR database, run an arbitrary set of commands specified in a yml file.
* Pre push of files or database, run an arbitrary set of commands specified in a yml file.
* Post push of files or database, run an arbitrary set of commands specified in a yml file.
  * This last item might not be valid because the provider may not allow this here.

## Metadata

* Query to obtain available environments (if possible based on provider API).
* Obtain metadata regarding available environments (if possible based on provider API).

## Shortcuts

* Obtain onetime login links to the application on one of the environments.
* SSH shortcut into one of the environments.

## Configuration Enhancements

* Extension of the base .ddev/config.yml to include application type and provider specific metadata. See https://github.com/drud/ddev/issues/183#issuecomment-299300422
* Automatic specification of containers matching production infrastructure.

## Bonus/Wishlist

* Create local backups
* Restore from local backup

**Comment by rickmanelius** [comment]
@beeradb and I had a meeting yesterday to discuss. While the items in this issue and the related issue #183 (pre/post hooks) are tracking in the right direction in terms of a potential final state, it's a heavy lift and we are attempting a 2nd pass at this to get to a working MVP. To be clear, even a simple ability to import directly from a provider is already a major win, so getting that out there in a workable state will help inform other choices that will help make this more robust.

If we think of the shortest path to a working import from Pantheon, it might look something like this:

* `ddev config pantheon` extends the default `ddev config` command. This in turn replaces the stock webserver and database containers with pantheon specific images within config.yml (alternatively, we could store a 2nd config-PROVIDER.yml).
* We assume that Redis/Solr containers are not used yet for a basic WordPress/Drupal site, and direct users to our custom container instructions if they wish to extend.
* `ddev config pantheon` asks additional questions (or it simply directs the end-user to open up the config file) to specify any API/credential information necessary to interact through the terminus API.
* We add `ddev import pantheon`. The import command simply merges import-files and import-db when run without an additional argument. When a provider argument is provided, we can key off additional questions such as the source environment for the files and databases.
* Based on the previous bullet, we add `ddev import` as a shortcut to run the import-files and import-db commands in series.

Additional Information:

* My vote would be to have a yml pattern that starts with site type at the parent and then namespaces for each provider plugin. It's possible that someone might want to use both a pantheon and drush plugin interchangeably based on workflow.

**Comment by rickmanelius** [comment]
Follow-up note. We'll need at least a short-term search/replace for WordPress. #108

**Comment by rickmanelius** [comment]
Related #341

**Comment by rickmanelius** [comment]
This is a long-standing issue that I want to get ahead of now that we have refactored the Pantheon config as well as addressed the drud-s3 configurations. However, there is still much to be discussed or tested, such as:

* on overall strategy around testing
* container creation/maintenance (with dimensions of CMS and/or provider)
* creating an idealized plugin approach and what is addressed for each "plugin"
* research onto the LOE of what it would take to address Acquia and Platform.sh

I don't see this as something that will result in action this sprint, but I want to get ahead of it and schedule out conversations should anything become actionable and addressable in the upcoming sprints.

**Comment by rickmanelius** [comment]
Added @rfay to this as an assignee, more because (when we have something to start discussing) it will require time and attention from his side.

**Comment by rfay** [comment]
Closing this as obsolete, although the time may come.
