### ISSUE TITLE
Change hostname check to enable using local dns server

### ISSUE THREAD

**Issue by codemonkey1988** [drud/ddev#1220]
**Is your feature request related to a problem? Please describe.**
When you got many (30+) ddev projects on your machine, you have at least 30+ ddev hostnames in your hosts file. At some point, the dns resolving gets really slow because of these.

**Describe the solution you'd like**
Ddev should check, if the projects hostname is resolved to 127.0.0.1 instead of checking the hosts file for the hostname. With this change, a user might set up a local dns server to resolve ddev hostnames to prevent them from added to the hosts file.
When removing a project ddev should keep checking the hosts file, to make sure, there is no abandoned entry in it.

**Additional context**
This problem occures on my machine with about 30+ ddev hostnames in my hosts file. In that case, the dns resolving takes up to 5 seconds for each request. When I clean up the hosts file, every works fine again.
- MacBook Pro End 2013
- OS X 10.13.6
- Ddev 1.3.0
- Docker CE 18.06.1-ce-mac73 (26764)

**Comment by rfay** [comment]
This is probably a duplicate of [Subdomain, Local DNS support: Don't require hosts file manipulation #416](https://github.com/drud/ddev/issues/416) - We weren't really willing to do the intrusive and risky thing of getting people's DNS messed up by running dnsmasq or the like (and that really can mess things up). So we got .ddev.site and planned to use a wildcard on it.  But then people pushed back quite hard about "What if I'm on an airplane". And the design we came up with there in #416 seemed to solve everybody's problem, but in the meantime we and everybody else got use to /etc/hosts.

And of course remember to `ddev rm --remove-data` when appropriate (removes both database and /etc/hosts entry) and `sudo ddev hostname --remove-inactive` which will get rid of all hosts that ddev thinks it owns and which are not currently in use.

**Comment by codemonkey1988** [comment]
I do not think, that this feature is a duplicate as mentioned above.
This feature request is not about implementing a dns resolver into ddev, but to give people the option to do resolve dns in other ways. Ddev should keeps its behaviour by adding hostnames to the systems host file, but only when the given hostname could not be resolved to 127.0.0.1.

So ddev would work like normal. But if you set up a dns resolver by your own, ddev should recognize that the hostname for a project is already resolved correctly to 127.0.0.1 and should not add the hostname to systems hosts file.

There is only one edge case I can think of that would break dns resolving. That is when you set up a dns resolver in your network (not on your machine) and disconnect from that network. As long as you did not restart your ddev project, the hostname could not be resolved. But I think that will be a quite uncommon use case.

**Comment by rfay** [comment]
Oh, as a workaround, just `export DRUD_NONINTERACTIVE=true` and it will do exactly that I think. It just won't try to create the hostname.

**Comment by rfay** [comment]
Oh, as a workaround, just `export DRUD_NONINTERACTIVE=true` and it will do exactly that I think. It just won't try to create the hostname.

**Comment by codemonkey1988** [comment]
Sounds cool, I will try this and will give feedback here.

**Comment by andrewfrench** [comment]
I agree that this isn't quite a duplicate of #416 &mdash; this is a reasonably different (and much lower level of effort) request, but it's still ultimately part of the same conversation. To start by testing whether the hostname already resolves to 127.0.0.1 seems like a reasonable compromise as it opens the door to using a more robust DNS manager if the user is comfortable configuring and managing one, but in the majority of cases, will simply fall back to ddev editing the hosts file.

It seems to me the challenge here is not so much with implementing any of these approaches, but in understanding the complexity we're adding by introducing each option (hosts file editing, *.ddev.site, local DNS manager, all of the above) in support, documentation, maintenance, and testing contexts.

As @rfay mentioned, if you're noticing any slowdown that you might associate with too many ddev hostnames being registered, `ddev hostname --remove-inactive` is your best bet right now.

**Comment by codemonkey1988** [comment]
> It seems to me the challenge here is not so much with implementing any of these approaches, but in understanding the complexity we're adding by introducing each option (hosts file editing, *.ddev.site, local DNS manager, all of the above) in support, documentation, maintenance, and testing contexts.

I'm not quite sure if I understand you correct, but we are not talking about implementing different dns resolver options into ddev. I see that this was or is a goal which is not reachable at the moment because of several issues. By adding the explained option, I did not see that you have to support other dns resolving methods, users might implement by their own. You might mention it in your documentation, that using other dns resolvers is an option, but nothing more.

I think I will point out my ddev usage for a better understanding of the situation.
I use ddev for many active projects. One project is e.g. a microservice architecture based on PHP (Lumen and Laravel) with about 10 services and each one with an additional fqdn. This results in about 20 hostnames. In addition to that, I got about 15 TYPO3 projects (also with multiple hostnames because of multiple languages) and some Symfony and plain php projects.
Long story short, even if I run `ddev hostname --remove-inactive` is does not remove any project, because all of them are active. (I'm working on them regularly) I currently have to remove each project using `ddev remove` after working on it in order to use the `ddev hostname --remove-inactive` command which is quite annoying.

I'm not sure if I am currently an edge case but my company also uses ddev as development platform and some other employees ran into the same issue.

But I tried the workaround from @rfay using `export DRUD_NONINTERACTIVE=true` which works quite well. I setup a local dnsmasq and exported the mentioned variable. When I now start a new project, nothing is written to the hosts file. I get an info during the start but that is acceptable for me. So from my point of view, this issue somehow seems resolved but only with a workaround which might change in the future.

**Comment by andrewfrench** [comment]
Thanks @codemonkey1988 &mdash; I think we generally agree on this, and your use case does actually change my understanding of your problem. I'd imagine you microservice architecture isn't the most common among our users, but I don't think we should consider it an edge case not worth discussing.

**Comment by codemonkey1988** [comment]
Thanks @andrewfrench 
As I said, I currently have a working solution. But it would be nice, if this feature somehow finds its way into ddev so that I do not have to worry that this workaround will fail me some day :)

Sadly, I have no experience with go so I could not provide a PR for this but if you need any other help on this, please let me know.

**Comment by rfay** [comment]
This absolutely works now in v1.9 - DNS lookup is used by default, and you can use any base tld you want to use. /etc/hosts is only populated if the DNS lookup fails (or is different from the docker ip, usually 127.0.0.1)

**Comment by rfay** [comment]
@codemonkey1988 if I missed some of your argument, please continue here and we'll reopen, but if I understood properly, you should be good to go.
