### ISSUE TITLE
poor ddev performance on macOS with a project with many files

### ISSUE THREAD

**Issue by froemken** [drud/ddev#1224]
Hello ddev-Team,

I have seen that there are a lot of performance issues for docker/ddev on a Mac. And yes, it's the com.docker.hyperkit process.
My current idea: Creating a new docker machine with driver "virtualbox". All needed env vars are set, so "docker run" should use my new drive now.
Now I have following errors:
When I import a dump.sql.gz I get:

cat: can't open '/db/dump.sql': Permission denied

Further I only can open my project via IP and not by domain anymore.

Do you have any hints for me?

Stefan

**Comment by rfay** [comment]
Hi @froemken - You're using docker machine, which I assume means you're using Docker Toolbox. Are you using it on Windows 10 Home?  Docker Toolbox is absolutely not our preferred environment, and was added last, and is only supported on Windows 10.  Please say more about what you actually did and your environment, but I don't think it's likely we'll be able to support this.

**Comment by froemken** [comment]
Hello @rfay 

I'm on MacOS High Sierra Version 10.13.6
MacBook Pro Retina 2012
with 16GB RAM

Docker 18.06.1-ce-mac73 (26764)
Compose: 1.22.0

My problem is that my TYPO3-project needs 10 seconds to load a Site. The fans in my MacBook are very loud, and process com.docker.hyperkit needs 39 of energy. While loading a site this process grows up to 300 energy temporary.
As I have written: I have seen many postings with my problem. It seems to be a Docker<-->Mac Problem. As HyperKit was a very jung project my idea was to change IO to a virtualbox instead of hyperkit. Don't know if this will be faster. It was only a test and a information to you, that driver virtualbox seems not to be compatible with ddev.

I have seen settings like enable fast-sync or on-sync, but it seems that they are not available anymore in newer versions. 3 postings have written: Set polling-interval to 4000 or disable it, but I don't know where to set that.

Your docker-compose.yaml has ":cached" already set at volumes, so my question is: Did you know any further performance improvements for Docker/Ddev on a Mac?

I already have tried reducing CPU to 1 and set RAM to 8GB.

Today I have copied full project incl. all docker/ddev to an ubuntu server in virtualbox on my Mac and yeah that's much faster. Website loads in less than a second, but energy consumption is still near 50.

What can I do to speed up ddev on my Mac? Currently it is not useable.

Stefan

**Comment by rfay** [comment]
Are you using docker for Mac or docker toolbox?

**Comment by froemken** [comment]
Don‘t know what Docker toolbox is. So I‘m sure to have Docker for Mac.

**Comment by rfay** [comment]
No response on this, hoping you've made progress, and we're happy to continue the conversation, closing for now. Suggestions on a path forward are above.

**Comment by rfay** [comment]
I should mention we give interactive support on Slack in the #ddev channels in both the typo3 and drupal slack setups, and are happy to help you there. https://ddev.readthedocs.io/en/latest/#support

**Comment by froemken** [comment]
You missed some answers from me:

- Yes, I can confirm that I have docker-for-mac
- I currently have set amount of CPUs to 4.
- I have installed virtualbox in parallel and then:
`docker-machine create --driver virtualbox docker-virtualbox`
then: `docker-machine env docker-virtualbox`
then: `eval "$(docker-machine env docker-virtualbox)"`
With this three lines you can switch all Shell commands to use docker in virtualbox, while docker-for-mac is still running normally in parallel.
- I think that a project with 334.270 files is not a little project ;-) Any yes, maybe because of this huge amount of files which has to be in sync, ddev/docker needs so much RAM. Maybe.

Stefan

**Comment by rfay** [comment]
Please do not use the docker-virtualbox technique, as we can't offer any support for that. 

You had said this was a modest project. 334K files is a lot. A lot. So maybe that is the issue.

But the way to start on this (if you didn't already) is to try a simple project and see if it works. Like a basic Drupal or TYPO3 clone and setup. If that works to your expectations then we know that the base case works on your machine.

I have heard of people using http://docker-sync.io/ with ddev on macOS, and haven't spent a lot of time with it yet. You might give that a try and see if it helps at all. My problem with it to date is that it's not robust on all OSs (poor on WIndows).

**Comment by froemken** [comment]
docker-virtualbox was only an idea, a try, to speed up performance. As it does not work I have removed that: Set Factory defaults and removed all Env vars.

I have just created an empty TYPO3 9.5.1 DDev project and compared it with an empty TYPO3 9.5.1 on my local installed Apache. The speed differs between 0 and 100ms. And I have reduced RAM back to 2 GB and Cores to 2. So, you're right, there is nearly no performance issue at small projects.

So, we can be sure that there is a problem to keep all these thousands of files in sync. As a TYPO3 programmer I only need typo3conf folder in sync. I don't need synchronization for fileadmin/ and uploads/, but I don't want to COPY all these 140GB of files into a named volume. Do you have another idea? Maybe implement NFS-mounts or whatever to ddev?

I have heard of docker-sync, but I don't know how to work with that. How to disable synchronization of local files and ddev container? Don't know. Named Volumes? IMO with docker-sync I can start a synchronization myself. But it only makes sense, if synchronization is disabled. Any ideas?

Thank you for your help.

Stefan

**Comment by rfay** [comment]
Oh, one thing I never mentioned: Your opcache may be exhausted. With that many PHP files it's hard to imagine it not being exhausted. You can view its status with just a php file in your project with 

```
<?php
phpinfo();
```

Please take a look at that. It may be that you just have to increase opcache config.

**Comment by rfay** [comment]
Reopening since responses happening now. We'd love to get a handle on what's happening to you. Is there any way you can share your repository, or a similar sanitized repo?

**Comment by rfay** [comment]
Oh, and a related thing to try is turning off your antivirus temporarily. Think about what the poor antivirus has to do when 334K files are in play!

**Comment by froemken** [comment]
Interesting:

Today I have started my big project again, but I have forgotten to set RAM back to 10GB and CPU from 2 to 4. The project runs without any problems. The fan of my MacBook is very quiet today, don't know what happens.

There was an update of Command Line Utilities on my Mac at 30. October:
https://developer.apple.com/documentation/xcode_release_notes/xcode_10_1_release_notes

But I can't find any filesystem related updates.

Hmmm...for now I'm happy, but I will keep an eye on it.

Stefan

**Comment by rfay** [comment]
An interesting performance issue to follow with docker-for-mac that seems to affect some people more than others and sounds a bit like yours: https://github.com/docker/for-mac/issues/2601

**Comment by rfay** [comment]
Since this seems to be working for you, and seems to have been a docker issue, closing for now, but we're always interested in followup.
