### ISSUE TITLE
Automate Docker image builds

### ISSUE THREAD

**Issue by andrewfrench** [drud/ddev#1225]
Incorporate the building and pushing of Docker images into release automation.

Options:
- Utilize Docker Hub's automated build process to initiate tag builds
- Build and push images from CircleCI (may require a new Drud Docker Hub user to complete `docker login` before pushing)

**Comment by rfay** [comment]
I seem to remember that Dockerhub fundamentally can't do our builds; However that may have been back in the day when we also did go builds of binaries that were installed inside the docker image. So give it a try. I guess the one reservation is that with our current build system we've gone through the testing process before pushing. But who knows, maybe there's some value there.

**Comment by andrewfrench** [comment]
I've been playing around with their build system and it looks like we may be playing more nicely with it these days, I have our four (for now) images building successfully:

https://hub.docker.com/u/andrewfrench
https://hub.docker.com/r/andrewfrench/ddev-webserver/builds/

Although these images haven't been extensively tested yet. I think there are very real concerns surrounding orchestration (having correctly tagged images exist _before_ testing, etc), but I think there might be some reasonable solutions to that problem.

**Comment by rfay** [comment]
Just a note on this one: build, push/ *test*. If we're building on dockerhub, we need to have a test after that to validate behavior.

**Comment by rfay** [comment]
Closing in favor of #2617
