### ISSUE TITLE
Access to webserver by name within container doesn't work if additional_hostnames invoked

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1235]
**Describe the bug**

In https://github.com/drud/ddev/pull/1151 we made it so you could access the webserver by full URL from within the web container. For example, `curl https://d8git.ddev.local`. The way it's set up, d8git.ddev.local resolves to the IP address of the *ddev-router*. 

However, once you add anything to additional_hostnames, all the IPs resolve to 127.0.0.1. As a result, http to the hostname *may* work if there's no alternate port, but https or most everything is broken.

**To Reproduce**

* ddev ssh
* ping main hostname of project. It should be the same as the ddev-router address (maybe 172.18.0.5 or something) and *not* 127.0.0.1
* exit
* Add to additional_hostnames in .ddev/config.yaml
* ddev start
* ddev ssh
* ping main hostname or any other additional_hostnames; they will resolve to 127.0.0.1, not going through the router. You can demonstrate the problem by hitting any of the supported URLs via https, for example for the main project being d8git, hit https://d8git.ddev.local and it will fail with connection refused (because it's hitting port 443 on the web container instead of going to the router)

**Expected behavior**

**Screenshots**

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: [e.g. Windows 10, macOS High Sierra]
 - Docker version information (use `docker version`) and insert it here.
 - ddev version information (use `ddev version`)
 - config.yaml contents for the misbehaving project
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

**Additional context**
Add any other context about the problem here. Thanks!

**Comment by rfay** [comment]
I think this workaround (though fragile) might work until we can sort this out:

This depends on the router normally getting the IP address 172.18.0.6, if your router has a different address, change it. You can find out its address with `ping ddev-router` inside the web container.

* Add a .ddev/docker-compose.hosts.yaml (particular name doesn't matter)

```
version: '3.6'
services:
  web:
    extra_hosts:
      - extraname1.ddev.local:172.18.0.6
      - extraname2.ddev.local:172.18.0.6
    environment:
      - VIRTUAL_HOST=originalname.ddev.local,extraname1.ddev.local,extraname2.ddev.local
```

**Comment by d3pendent** [comment]
Is there a variable that contains the IP addess of the docker0 network gateway?
Since developers could have different system setups, it's not perfect to commit this file into any projects repository.

**Comment by RinyVT** [comment]
Currently facing the same problem.
In TYPO3 CMS9 the possibility has been added to set normal content pages as error-handling output (for example 404, 403 etc.)

TYPO3 tries to access the frontend and cache the output.
In my case I have additional_hostnames and TYPO3 is trying to access the url, for example https://project.ddev.local/404
This results in an `Connection Refused`.

Unfortunately the workaround is not do-able because we share the ddev setup within our team and thus the ddev-router ip is not the same. But for temporary testing-purposes this works!

**Comment by rfay** [comment]
Thanks for the followup from slack, much appreciated. Hope to get this solved in the near future.

**Comment by hirasso** [comment]
Is the above still the recommended solution, via a custom `.ddev/docker-compose.hosts.yaml`?

**Comment by rfay** [comment]
@hirasso no, thanks to @stasadev 's work, this is no longer necessary. the FQDN of `additional_hostnames` is automatically routed through the `ddev-router` these days.

**Comment by hirasso** [comment]
Thank you @rfay for getting back to me so quickly!

Intersting... so a curl against ddev's primary url from within the container should work? I'm using a custom port and https.

If so, I'll need to investigate further why it doesn't seem to be working for me. Might need to create a reduced test case.

**Comment by rfay** [comment]
I tested before responding. Please give it a try, and please use current DDEV v1.25.1. Best to test in a simple demonstration project.

**Comment by hirasso** [comment]
Wow... it works like a charm!! Thank you for the fantastic work on ddev.
