### ISSUE TITLE
Failed to start ddev router

### ISSUE THREAD

**Issue by FeWo11** [drud/ddev#1237]
**Bugdescription**
I tried to start ddev with "ddev start" and everything starts but the ddev-router. 
It says 
> Failed to start demo: ddev-router failed to become ready: health check timed out: labels map[com.docker.compose.service:ddev-router] timed out without becoming healthy, status=unhealthy

**To Reproduce**
For me it's reproducable by just starting ddev.

**Expected behavior**
I expected it to start normally without an error.

**Version and configuration information:**
 - Host computer OS and Version: Windows 10
 - Docker version information:
> Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

> Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     false

 - ddev version information:
> dba     drud/phpmyadmin:v1.3.0
router  drud/ddev-router:v1.3.0
commit  v1.3.0
domain  ddev.local
cli     v1.3.0
web     drud/ddev-webserver:v1.3.0
db      drud/ddev-dbserver:v1.3.0

 - config.yaml contents:
> APIVersion: v1.3.0
name: demo
type: typo3
docroot: public
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default

**Additional context**
We are using a company proxy but I dont know if it effects the problem, because it's defined in docker and everything else like pulling containers works fine.

**Comment by rfay** [comment]
The most common reason for this to happen is if the same additional_hostname or additional_fqdn is created in more than one project. Could you please `ddev rm -a` to stop and remove all projects, and then start the one project that is giving trouble? 

If that doesn't solve it could you please `ddev rm -a` and

* mkdir junk
* cd junk
* ddev config (choose 'php' type)
* ddev start

and see if you get the same problem.

**Comment by FeWo11** [comment]
Same Problem as mentioned before:
`Failed to start junk: ddev-router failed to become ready: health check timed out: labels map[com.docker.compose.service:ddev-router] timed out without becoming healthy, status=unhealthy`

And  
> "start the one project that is giving trouble?"

 It's not only one project, it happens with every project I try to start.

**Comment by rfay** [comment]
Does `docker logs ddev-router` give you any information?

I think you'll end up using `docker exec -it ddev-router bash` to get into the router; when you get in there please try `nginx -t` and see if it complains about broken nginx config.

**Comment by rfay** [comment]
Well, I'd say you're on the track, but I'm baffled. 

Inside ddev-router (`docker exec -it ddev-router`) you should be able to see the healthcheck fail, `curl http://localhost/healthcheck` - Is that the case? 

It's as if something or someone changed the nginx config in ddev-router. 

Note that if it's just  *reporting* as failed in this case, it may still be operational just fine.

I don't know how your proxy can be involved in this, unless it's something you've introduced into docker configuration. Nothing goes off your box in this situation.

**Comment by rfay** [comment]
Could you provide the generated ~/.ddev/router-compose.yaml please ?

Also, please `pwd` for the directory in which your project is, thanks.

**Comment by FeWo11** [comment]
`curl http://localhost/healthcheck` was the best hint. I had to add "localhost" to noProxy. 
Thank you very much for your quick replies.

**Comment by rfay** [comment]
That's really weird. That must mean you have the *container* set up with your proxy. I didn't understand  that part. Also, your proxy environment must use /etc/hosts for resolution *last* because localhost is in /etc/hosts on that image.

**Comment by aviboy2006** [comment]
> The most common reason for this to happen is if the same additional_hostname or additional_fqdn is created in more than one project. Could you please `ddev rm -a` to stop and remove all projects, and then start the one project that is giving trouble?
> 
> If that doesn't solve it could you please `ddev rm -a` and
> 
> * mkdir junk
> * cd junk
> * ddev config (choose 'php' type)
> * ddev start
> 
> and see if you get the same problem.

Thanks for this.
