### ISSUE TITLE
ddev doesn't show all major command line output

### ISSUE THREAD

**Issue by nbiwki** [drud/ddev#1239]
**Describe the bug**
I got follow Message from "ddev start":
"The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing." followed by 2 new lines.
Than i search on the internet and find out this is a message from docker-compose, but is missing a very important line: "Continue with the new image? [yN]"

**To Reproduce**
I build own images based von drud/ddev-webserver and delete old builds with docker rmi -f <id>. If i replaced by the same name i got the error.

**Version and configuration information (please complete the following information):**
OS: Linux nb 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
ddev: 
domain  ddev.local                
cli     v1.3.0                    
web     drud/ddev-webserver:v1.3.0
db      drud/ddev-dbserver:v1.3.0 
dba     drud/phpmyadmin:v1.3.0    
router  drud/ddev-router:v1.3.0   
commit  v1.3.0   

docker-compose version 1.22.0, build f46880fe
Docker Version:          18.06.1-ce

Thanks!

**Comment by rfay** [comment]
Oh, I'm sorry I didn't read carefully

> I build own images based von drud/ddev-webserver and delete old builds with docker rmi -f . If i replaced by the same name i got the error.

If you're going to build your own images, please don't name them drud/ddev-webserver. Name them for your own account. Push them to nbiwki/ddev-webserver, and add them to the config.yaml with the tag you require.

Maybe if you can mention what you're trying to accomplish we can give some suggestions. But what you've done here is definitely not something we know how to support.  (We don't even encourage people to create their own images, but certainly you can't use the drud/ddev-webserver image repo)

**Comment by nbiwki** [comment]
No, i din't give my build the same name. The fork was an accident by trying to look at all forks of ddev. :-)

i created an Dockerfile with 'FROM drud/ddev-webserver:20181017_add_ssh' and add my own commands to customize like 'RUN apt-get...'

now i do docker build -t awesome-ddev-webserver-clone. if i change something i do docker rmi -f <id> and redo the build.

**Comment by rfay** [comment]
Just FYI, you don't have to `docker rmi`, you can just do the new build. 

In our ecosystem, we use `make container`, and to do a new tag `make container VERSION=xxx` for the tag.

**Comment by rfay** [comment]
I'm going to close this for now, but happy to continue the conversation. ddev is definitely not designed to handle the situation you've created here, but it's possible I just don't fully understand.
