### ISSUE TITLE
TYPO3 console getaddrinfo failed

### ISSUE THREAD

**Issue by lukeskywalker1985** [drud/ddev#1245]
After successfully started typo3-v9 with ddev I tried to run TYPO3 console on Windows 10 CMD or PowerShell...
```
C:\ddev\typo3-base-distribution-9.5\vendor\bin> .\typo3cms.bat
TYPO3 Console 5.6.0
```

... I try to execute a command like `.\typo3cms.bat cache:flush` I get this error message:

>  [ Doctrine\DBAL\Exception\ConnectionException ]
>   An exception occurred in driver: php_network_getaddresses: getaddrinfo failed:  Unknown Host
> 
> Caused by:
> 
>   [ Doctrine\DBAL\Driver\Mysqli\MysqliException ]
>   php_network_getaddresses: getaddrinfo failed: Unknown Host

Has somebody the same problem and know how to solve it ?

Many thanks!

**Comment by dnozdrin** [comment]
The same issue on Linux Mint with DDEV 1.3.0

**Comment by Kephson** [comment]
Hi,
you could execute the typo3_console e.g. with executing it inside the container:
`ddev exec /var/www/html/vendor/bin/typo3cms cache:flush`

**Comment by rfay** [comment]
It sure sounds like you have name resolution failures inside the container. Please `ddev ssh` and then `ping google.com`. What do you see? If it says "Name or service not found", then name resolution isn't working. If it tries to ping but fails, then you have other network access trouble.

The most likely problem is firewall-related. 

However... Where are you running typo3cms.bat, and what is in it? It looks like you're running a batch file (unusual to use .bat any more) on the host, in which case this has nothing whatever to do with ddev. 

@dnozdrin if you're seeing name resolution problems, they're not when running a .bat file on the host, what's your situation? Please open a different issue, or we're happy to support you on Slack or elsewhere, https://ddev.readthedocs.io/en/latest/#support

**Comment by lukeskywalker1985** [comment]
@Kephson Perfect, now it works ! Thank you 👍
