### ISSUE TITLE
ddev should support bash autocomplete

### ISSUE THREAD

**Issue by rfay** [drud/ddev#125]
## What happened (or feature request):

ddev doesn't currently seem to support bash/zsh autocomplete. But *everybody* else does :)

## What you expected to happen:

I expect to be able to hit tab and get autocomplete suggestions.

## How to reproduce it (as minimally and precisely as possible):

Type `ddev ` and hit tab.

## Anything else do we need to know:

At the time this ticket is being addressed, spf13 does not directly support zsh autocomplete, although they're (maybe) working on it. Kube implemented it separately. 

The strategy here will be to do bash autocomplete now and monitor the zsh issue, https://github.com/spf13/cobra/issues/107

## Related source links or issues (like source JIRA issue):

**Comment by rickmanelius** [comment]
Bump. Worth prioritizing?

**Comment by rfay** [comment]
*Way* worth it to me!

**Comment by rickmanelius** [comment]
@cyberswat I know you're getting more time in the issue queue. Is this something you'd like to tackle for v0.8?

**Comment by cyberswat** [comment]
Sure thing.  I poked at this a bit in the traditional way before we figured out that it was something cobra would provide.

**Comment by cyberswat** [comment]
@rickmanelius I think it makes sense to get this assigned to another developer.  There are some great resources out there to get started with including https://github.com/spf13/cobra/blob/master/bash_completions.go and https://github.com/spf13/cobra/blob/master/bash_completions.md.  Let's get this reassigned.

**Comment by rfay** [comment]
Cobra does not yet directly support zsh, but it might before long (https://github.com/spf13/cobra/issues/107)

Kubernetes took their own route and wrote a [separate zsh completion generator](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/completion.go) but I don't really see the value of doing that and then maintaining the code.

Would it be OK to change this issue to support bash only at this point?

**Comment by rickmanelius** [comment]
Bash is better than nothing!

**Comment by rfay** [comment]
I guess that was a thumbs-up so I'll change the title and OP.
