### ISSUE TITLE
ddev stop/start <anything> is accepted as a command, but only starts current app (arg processing)

### ISSUE THREAD

**Issue by rfay** [drud/ddev#127]
## What happened (or feature request):

I tried `ddev stop drud-d7` while in the drud-d8 app (testing [ddev describe PR #116](https://github.com/drud/ddev/pull/116). It stopped drud-d8 instead of drud-d8. The fact is that all arguments are accepted, for example `ddev stop this stinking devsite` is accepted (and acted upon).  I did this in light of the fact that we now support "app" as 3rd arg of `ddev describe` and I wondered if this had been done globally, as a normal user would probably expect. 

## What you expected to happen:

I expected it to either stop drud-d7 or give me an error about an invalid argument.

## How to reproduce it (as minimally and precisely as possible):

Run `ddev stop this stinking devsite` when in a valid app directory.

## Related source links or issues (like source JIRA issue):

This was discovered in testing #116

**Comment by rfay** [comment]
I'd like to go ahead and do this one just from an args-processing viewpoint (give the usage if they add extra args). It's trivial (I think).

**Comment by tannerjfco** [comment]
The behavior for start is addressed in #123, as we wanted similar behavior on import commands. For stop/rm, we were discussing different behavior in #78. I think we should close this ticket and resolve the other commands with the decided path forward on #78

**Comment by rfay** [comment]
Works for me, closing in favor of #123 - when we do that though let's make sure that all commands don't accept spurious extra args.
