### ISSUE TITLE
Create DDEV Start/Stop/Restart Scenarios in Gherkin

### ISSUE THREAD

**Issue by mafriend** [drud/ddev#1273]
Goals: Each sprint, identify a small number of test scenarios from Product Feature Testing Outline to flesh out with full steps and release showstopper status

For this next sprint, let's try to flush out the following scenarios:
Scenario: DDEV Start
Scenario: DDEV Stop
Scenario: DDEV Restart

*Note*: These scenarios will probably be more like Scenario outlines as they will run through start, stop, and restart with each supported CMS and version (WP, Drupal6, Drupal7, Drupal8, TYPO3 v8, TYPO3 v9, and Backdrop).

These may seem like a lot of scenarios to attempt to tackle in one sprint, but once we flush out the details for one, the other should fall into place!

Thanks!

**Comment by rfay** [comment]
Closing a there's not current work with gherkin.
