### ISSUE TITLE
Flesh Out and Determine Severity of User Scenarios For Test Plan/Automation Use

### ISSUE THREAD

**Issue by mafriend** [drud/ddev#1274]
Goals: Each sprint, identify a small number of test scenarios from Product Feature Testing Outline to flesh out with full steps and release showstopper status

What does "fleshing out" entail?
Fleshing out entails breaking out the gherkin into automatable steps for the Local product and adding in validation around THEN steps. Most scenarios will be relatively short but others might involve additional steps or configurations in order to start automating them or including them in regression test suites.

How do we categorize severity?
Scenarios are currently being worked on from most critical to least critical. The most critical scenarios are scenarios that would prevent us from deploying if they failed. Least critical scenarios are those that would possibly prevent us from holding up a deploy, but for the most part would just be fixed as part of a hotfix later. Least critical scenarios are ones around edge cases or usecases that only a very few number of our customers encounter and therefore have a smaller impact.

**Comment by rfay** [comment]
This is obsolete.
