### ISSUE TITLE
How do I stop the `ddev-ssh-agent` agent?

### ISSUE THREAD

**Issue by alphex** [drud/ddev#1278]
I couldn't find anything in the doumentation, or another issue that seems to answer this, so I'm posting a meta issue...

When I'm done working on something, I should use `ddev stop`, to stop my ddev docker containers... correct?  

When I do that, the `ddev-ssh-agent` is still running.     What's the best way to stop ALL ddev operations?

I'm evaluating DDEV against Lando right now, and lando has `lando poweroff` which stops all of the containers, and I was wondering if there was something like that.

Thanks!

**Comment by rfay** [comment]
Closing, as this is answered. Feel free to continue the conversation!

**Comment by meredevelopment** [comment]
For future people `ddev poweroff`
