### ISSUE TITLE
ddev auth ssh does not recognize ed25519 keys

### ISSUE THREAD

**Issue by PascaleBeier** [drud/ddev#1282]
**Describe the bug**
ddev auth ssh does not look for id_ed25519 and possible other keys than id_[rd]sa.

**To Reproduce**
1. generate a new ed25519 ssh key
2. run `ddev auth ssh`
4. See error `No keys matching id_[rd]sa were found in the directory.`

**Expected behavior**
ed25519 keys to be recognized as ssh keys as well

**Version and configuration information (please complete the following information):**
 - Windows 10
 - 18.06.1-ce
 - v1.4.0

**Additional context**
ddev auth ssh should accept other ssh key formats as well.

**Comment by rfay** [comment]
It does not recognize keys except rsa and dsa that are not named id_rsa and id_dsa, and I never even knew about ed25519!

We can add that pretty easily.

But for now, a workaround for you (please try it):

```
mkdir ~/.ddevworkaround
cp ~/.ssh/id_ed25519 ~/.ddevworkaround/id_rsa
ddev ssh auth -d ~/.ddevworkaround
```

**Comment by PascaleBeier** [comment]
Thanks for the quick answer randy!

Getting an error 
`OCI runtime exec failed: exec failed: Cwd must be an absolute path: unknown` following your steps.

I ended up generating a new id_rsa ssh-key in the meantime.

**Comment by rfay** [comment]
@PascaleBeier  I'd love if you could take the PR #1295 for a test run, it should pick up any keys (of any type)  in ~/.ssh or the directory you specify with -d. Build artifacts to try out are at https://circleci.com/gh/drud/ddev/6142#artifacts/containers/0

**Comment by PascaleBeier** [comment]
Works fine, sorry for the delay!
