### ISSUE TITLE
Rework code to avoid shelling out to external commands

### ISSUE THREAD

**Issue by rfay** [drud/ddev#129]
## What happened (or feature request):

ddev has a huge pile of places where we rely on shelling out to Unix/Linux/MacOs commands. Each one of these is a fatal bug when we get to Windows, and is even a vulnerability in MacOS usage, as the command it finds in the path might be different from what we expect, or might not be available.

Basically, we need to go back through and remove the shelling execution and replace it with golang constructs or libraries.

## What you expected to happen:

OS-independent, system-independent code.

## How to reproduce it (as minimally and precisely as possible):

Just review code for [exec.Command(](https://github.com/drud/ddev/search?utf8=%E2%9C%93&q=%22exec%5C.Command%28%22&type=), [system.RunCommand(](https://github.com/drud/ddev/search?utf8=%E2%9C%93&q=system.RunCommand&type=), [system.RunCommandPipe(](https://github.com/drud/ddev/search?utf8=%E2%9C%93&q=system.RunCommandPipe&type=) - there may be others. 

## Related source links or issues (like source JIRA issue):

**Comment by rickmanelius** [comment]
We agree as a team that we will not introduce more of these items moving forward and we will fix/address areas where we are refactoring.
