### ISSUE TITLE
Content Encoding Error

### ISSUE THREAD

**Issue by bessone** [drud/ddev#1309]
I created a drupal 7 project starting from an existing installation.
All the configuration was successful, "ddev start" does its job.
When I try to access via HTTP with the browser, however, I get the error "Content Encoding Error".

**Screenshots**
![image](https://user-images.githubusercontent.com/1089510/49211834-c047c700-f3c0-11e8-8d8c-0b9312a87a88.png)
![image](https://user-images.githubusercontent.com/1089510/49211870-db1a3b80-f3c0-11e8-8fde-27d10ca2242d.png)

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Windows 10
 - Docker version 18.09.0
 - ddev version v1.4.1
 - config.yaml 
```
APIVersion: v1.4.1
name: abbonamenti.ecodelchisone.it
type: drupal7
docroot: ""
php_version: "7.1"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
```
Is something related to nginx?

Any help will be appreciated! 
Thanks!

**Comment by rfay** [comment]
Could you please use a browser or curl to see what content-encoding is being sent?

If you set up a regular old drupal7 download it doesn't do this right? Do you have any nginx or php overrides in the project's .ddev that could affect it?

**Comment by bessone** [comment]
I've just tried a clean Drupal 7.61 and the problem does not repeat.

I tried with CURL and I see the HTML source, the response headers are these:
```
HTTP/1.1 200 OK
Server: nginx/1.15.3
Date: Thu, 29 Nov 2018 15:35:00 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
X-Drupal-Cache: HIT
Etag: "1543482014-0"
Content-Language: it
X-Generator: Drupal 7 (http://drupal.org)
Cache-Control: public, max-age=0
Last-Modified: Thu, 29 Nov 2018 09:00:14 GMT
Expires: Sun, 19 Nov 1978 05:00:00 GMT
Vary: Cookie,Accept-Encoding
```

I tried with Firefox and Chrome (see screenshot from previous post), I have not tried with MS Edge, but I do not think I change anything ;)

**Comment by rfay** [comment]
So if you don't have the problem with a plain D7 project, then there's something about your code that's changing the encoding?  I don't see any headers setting an encoding in your curl. 

If it's possible to share the project code with me I'll try it out, but it sure appears to be something about your project.

Does it happen on your plain D7 project when you change the language to it?

**Comment by bessone** [comment]
If I do not import the project database I do not have that error (of course I have the drupal error), as soon as I import the database the browsers give that error (but not with CURL).

After some research I found this:
https://www.drupaleasy.com/quicktips/browser-fail-unsupported-form-compression-related-php-notice

Probably the installation has some module that gives output problems. Online (with Apache), however, works perfectly

**Comment by rfay** [comment]
Why don't you switch your ddev project to webserver_type: apache-fpm or apache-cgi and see what the results are? There may be a .htaccess which is providing config that a module needs.

**Comment by bessone** [comment]
Right, wrong argument and wron link, sorry.

But I found the problem! This is a very old project with Drupal 7.43, after updating the core at 7.61 the problem has disappeared. It remains strange why it happened, but it's okay anyway.
Thanks for your patience.

Just one last question, if I change the webserver_type to apache, then **ddev rm** and **ddev start** nothing changes, remains nginx.
Where am I doing wrong? Sorry, these are my first hours with DDEV

**Comment by rfay** [comment]
It's because there's a reverse-proxy, ddev-router, in front of the apache-based web project. Explained in https://stackoverflow.com/questions/52774173/why-do-i-see-nginx-headers-when-ddev-is-configured-to-use-apache

Glad you got it sorted out!

**Comment by rfay** [comment]
Closing as this seems to be resolved. Thanks!
