### ISSUE TITLE
Re-running ddev config replaces settings.ddev.php

### ISSUE THREAD

**Issue by ctorgalson** [drud/ddev#1310]
**Describe the bug**

I'm not positive if this is a by-design behaviour with a misleading comment, or if the comment is right and this isn't supposed to happen.

- The comment in `settings.ddev.php` says that the file will not be overwritten or deleted if the `#ddev-generated` comment is removed.
- Re-running `ddev config` (e.g. as is required after updating `ddev`) causes the file to be replaced.

**To Reproduce**

- Run `ddev config` in a new Drupal site.
- Remove the comment in `docroot/sites/default/settings.ddev.php`.
- Re-run `ddev config`

**Expected behavior**

The file is not replaced/altered.

**Screenshots**

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macOS High Sierra
 - Docker version information

        Client: Docker Engine - Community
         Version:           18.09.0
         API version:       1.39
         Go version:        go1.10.4
         Git commit:        4d60db4
         Built:             Wed Nov  7 00:47:43 2018
         OS/Arch:           darwin/amd64
         Experimental:      false

        Server: Docker Engine - Community
         Engine:
          Version:          18.09.0
          API version:      1.39 (minimum version 1.12)
          Go version:       go1.10.4
          Git commit:       4d60db4
          Built:            Wed Nov  7 00:55:00 2018
          OS/Arch:          linux/amd64
          Experimental:     true

 - ddev version information

          db            	drud/ddev-dbserver:v1.4.0
          router        	drud/ddev-router:v1.4.0
          ddev-ssh-agent	drud/ddev-ssh-agent:v1.4.0
          domain        	ddev.local
          cli           	v1.4.0
          web           	drud/ddev-webserver:v1.4.0
          dba           	drud/phpmyadmin:v1.4.0
          commit        	v1.4.0

 - config.yaml contents for the misbehaving project

   <details>

        APIVersion: v1.4.0
        name: ddev-bug
        type: drupal8
        docroot: web
        php_version: "7.1"
        webserver_type: nginx-fpm
        router_http_port: "80"
        router_https_port: "443"
        xdebug_enabled: false
        additional_hostnames: []
        additional_fqdns: []
        provider: default

        # This config.yaml was created with ddev version v1.4.0 
        # webimage: drud/ddev-webserver:v1.4.0
        # dbimage: drud/ddev-dbserver:v1.4.0
        # dbaimage: drud/phpmyadmin:v1.4.0
        # However we do not recommend explicitly wiring these images into the
        # config.yaml as they may break future versions of ddev.
        # You can update this config.yaml using 'ddev config'.

        # Key features of ddev's config.yaml:

        # name: <projectname> # Name of the project, automatically provides
        #   http://projectname.ddev.local and https://projectname.ddev.local

        # type: <projecttype>  # drupal6/7/8, backdrop, typo3, wordpress, php

        # docroot: <relative_path> # Relative path to the directory containing index.php.

        # php_version: "7.1"  # PHP version to use, "5.6", "7.0", "7.1", "7.2"

        # You can explicitly specify the webimage, dbimage, dbaimage lines but this
        # is not recommended, as the images are often closely tied to ddev's' behavior,
        # so this can break upgrades.

        # webimage: <docker_image>  # nginx/php docker image.
        # dbimage: <docker_image>  # mariadb docker image.
        # dbaimage: <docker_image>

        # router_http_port: <port>  # Port to be used for http (defaults to port 80)
        # router_https_port: <port> # Port for https (defaults to 443)

        # xdebug_enabled: false  # Set to true to enable xdebug and "ddev start" or "ddev restart"

        # webserver_type: nginx-fpm  # Can be set to apache-fpm or apache-cgi as well

        # additional_hostnames:
        #  - somename
        #  - someothername
        # would provide http and https URLs for "somename.ddev.local"
        # and "someothername.ddev.local".

        # additional_fqdns:
        #  - example.com
        #  - sub1.example.com
        # would provide http and https URLs for "example.com" and "sub1.example.com"
        # Please take care with this because it can cause great confusion.

        # upload_dir: custom/upload/dir
        # would set the destination path for ddev import-files to custom/upload/dir.

        # working_dir:
        #   web: /var/www/html
        #   db: /home
        # would set the default working directory for the web and db services. 
        # These values specify the destination directory for ddev ssh and the 
        # directory in which commands passed into ddev exec are run. 

        # omit_containers: ["dba", "ddev-ssh-agent"]
        # would omit the dba (phpMyAdmin) and ddev-ssh-agent containers. Currently
        # only those two containers can be omitted here.

        # provider: default # Currently either "default" or "pantheon"
        #
        # Many ddev commands can be extended to run tasks after the ddev command is
        # executed.
        # See https://ddev.readthedocs.io/en/stable/users/extending-commands/ for more
        # information on the commands that can be extended and the tasks you can define
        # for them. Example:
        #hooks:
        # post-import-db:
        #   - exec: drush cr
        #   - exec: drush updb

   </details>

 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

  - No custom config.

**Additional context**

I've attached a shell script to demo the issue. Remove the .txt extension, make executable and run:

<details>

```sh
➜ rm -rf ddev-bug/ && ./ddev-bug.sh

Starting demo.

Cloning Drupal...

Running ddev setup...

Removing comment...

The '#ddev-managed' comment is gone!

<?php


$databases['default']['default'] = array(
  'database' => "db",
  'username' => "db",
  'password' => "db",
  'host' => "db",
  'driver' => "mysql",
  'port' => 3306,

Re-running ddev setup...

The '#ddev-managed' comment is back!

<?php

/**
 #ddev-generated: Automatically generated Drupal settings file.
 ddev manages this file and may delete or overwrite the file unless this comment is removed.
 */

$databases['default']['default'] = array(
  'database' => "db",
  'username' => "db",


Demo complete.
```

</details>

[ddev-bug.sh.txt](https://github.com/drud/ddev/files/2628712/ddev-bug.sh.txt)

**Comment by rfay** [comment]
Yeah, I confirm this inappropriate behavior.  For your work though, we don't ever recommend fiddling with settings.ddev.php, use settings.local.php instead. We'll get this fixed though. Probably that comment at the top should say something stronger as well.
