### ISSUE TITLE
Behat tests in BLT

### ISSUE THREAD

**Issue by alex-moreno** [drud/ddev#1329]
**Is your feature request related to a problem? Please describe.**
A colleague of mine is testing blt a bit deeper than me, and found some issues regarding Behat tests:

> Behat testing is not working (out of the box `Could not find Google Chrome. Please add an alias for "google-chrome" to your CLI environment.`)

**Describe the solution you'd like**
Should this be OOB, so no extra config is needed from the user, or maybe a build process?

**Comment by alex-moreno** [comment]
oh wow, that was quick Ray :-) 

I will need to test it myself, or ask my colleague to have a look, I'll let you know as soon as possible.

**Comment by sharique** [comment]
We can install google chrome by adding the following in post-install hook

```yaml
hooks:
  post-start:
  - exec: "sudo apt-get update"
  - exec: "wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
  - exec: "sudo dpkg -i google-chrome-stable_current_amd64.deb"
  - exec: "sudo apt-get -fy install"```

**Comment by sharique** [comment]
Ideally, we should be using separate images, so that at the time of testing we can easily switch browser at the time of testing.

**Comment by sharique** [comment]
Behat tests are still failing due to connection timeout.

**Comment by rfay** [comment]
I'd love to see us get explicit behat testing instructions into drud/ddev-contrib

Note that there are easier ways to add packages these days.

**Comment by lcatlett** [comment]
https://github.com/lcatlett/blt-ddev adds ddev integration to BLT and also resolves the behat challenges mentioned in this issue

**Comment by rfay** [comment]
So awesome! https://twitter.com/randyfay/status/1165621322614919169 - and added a link in https://github.com/drud/awesome-ddev

**Comment by rfay** [comment]
I'm going to close this issue then in favor of https://github.com/lcatlett/blt-ddev, thanks so much!
