### ISSUE TITLE
Webcache loses the ability to track changes on the host

### ISSUE THREAD

**Issue by andrewfrench** [drud/ddev#1339]
**Describe the bug**
The bgsync webcache container can seemingly lose the ability to track changes to the host filesystem. When this happens, the container will continue to pass the healthcheck, but no files changes will sync from host to web container.

**To Reproduce**
These steps will not guarantee reproduction, but generally:
1. Start a project with `webserver_cache: true`
2. `ddev composer create drupal-composer/drupal-project:8.x-dev`
3. Wait for project files to sync from the web container to the host (about a minute)
3. Install Drupal
4. Watch bgsync logs with `ddev logs -s bgsync -f`
4. On the host, `rm -rf ./*` to remove all project files
5. Files will be removed on the host, but will still exist in the web container
6. bgsync will continue to log healthcheck information, but will not log sync events
6. Wait to ensure that Unison has not noticed and will not sync the changes to the project on the host filesystem

**Expected behavior**
Changes should be consistently bidirectional.

**Comment by rfay** [comment]
I"m going to remove this from the v1.6.1 project in favor of discussion on deprecating the feature as suggested in #1495

**Comment by rfay** [comment]
Closing in favor of #1495, we'll deprecate webcache.
