### ISSUE TITLE
PHP 7.3 doesn't work with apache-fpm

### ISSUE THREAD

**Issue by brotkrueml** [drud/ddev#1346]
**Describe the bug**
After updating to ddev 1.5.0 I set the PHP version to 7.3. Restarting ddev brings up the following error:
`Failed to start zzz: web container failed: log=phpstatus FAILED, err=container /ddev-zzz-web unhealthy: phpstatus FAILED`
I am experiencing this problem on two different machines with two different TYPO3 projects. I also deactivated xdebug, but the same problem occurs.

**To Reproduce**
I just changed the PHP version to 7.3. With 7.2 everything works well.

**Expected behavior**
PHP 7.3 is working.

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Ubuntu 18.04
 - Docker version information: 18.09.0
 - ddev version information: 1.5.0
 - config.yaml contents for the misbehaving project:
    APIVersion: v1.5.0
    name: zzz
    type: typo3
    docroot: public
    php_version: "7.3"
    webserver_type: apache-fpm
    router_http_port: "8080"
    router_https_port: "8443"
    xdebug_enabled: true
    additional_hostnames: []
    additional_fqdns: []
    mariadb_version: "10.2"
    webcache_enabled: false
    omit_containers:
      - dba
      - ddev-ssh-agent
    provider: default
    hooks:
      post-start:
        - exec: composer install
        - exec: yarn --cwd packages/theme/Build
        - exec: vendor/bin/typo3cms database:updateschema
        - exec: vendor/bin/typo3cms cache:flush

 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?
     version: '3.6'

     services:
       web:
         environment:
         - TYPO3_CONTEXT=Development

**Comment by brotkrueml** [comment]
Okay, let's go:

**With apache-fpm and disabled hooks:**

+ set -o errexit nounset pipefail
+ DDEV_PHP_VERSION=7.3
+ DDEV_WEBSERVER_TYPE=apache-fpm
+ '[' -n public ']'
+ export WEBSERVER_DOCROOT=/var/www/html/public
+ WEBSERVER_DOCROOT=/var/www/html/public
+ export NGINX_DOCROOT=/var/www/html/public
+ NGINX_DOCROOT=/var/www/html/public
+ '[' -f /mnt/ddev_config/nginx-site.conf ']'
+ '[' -f /mnt/ddev_config/apache/apache-site.conf ']'
+ '[' -n 7.3 ']'
+ update-alternatives --set php /usr/bin/php7.3
update-alternatives: using /usr/bin/php7.3 to provide /usr/bin/php (php) in manual mode
+ ln -sf /usr/sbin/php-fpm7.3 /usr/sbin/php-fpm
+ export PHP_INI=/etc/php/7.3/fpm/php.ini
+ PHP_INI=/etc/php/7.3/fpm/php.ini
+ '[' -d /mnt/ddev_config/php ']'
+ '[' typo3 = backdrop ']'
+ rm -f /etc/nginx/nginx-site.conf
+ '[' -f /etc/nginx/nginx-site-typo3.conf ']'
+ ln -s /etc/nginx/nginx-site-typo3.conf /etc/nginx/nginx-site.conf
+ rm -f /etc/apache2/apache-site.conf
+ '[' -f /etc/apache2/ddev_apache-typo3.conf ']'
+ ln -s -f /etc/apache2/apache-site-default.conf /etc/apache2/apache-site.conf
+ envsubst '$WEBSERVER_DOCROOT,$NGINX_DOCROOT'
+ envsubst '$WEBSERVER_DOCROOT'
++ id -u
++ id -g
+ printf '\nexport APACHE_RUN_USER=uid_1000\nexport APACHE_RUN_GROUP=gid_1000\n'
+ '[' apache-fpm = apache-cgi ']'
+ '[' apache-fpm = apache-fpm ']'
+ a2enmod proxy_fcgi setenvif
Considering dependency proxy for proxy_fcgi:
Enabling module proxy.
Enabling module proxy_fcgi.
Module setenvif already enabled
To activate the new configuration, you need to run:
  service apache2 restart
+ a2enconf php7.3-fpm
Enabling conf php7.3-fpm.
To activate the new configuration, you need to run:
  service apache2 reload
+ a2enmod rewrite
Module rewrite already enabled
+ a2dissite 000-default
Site 000-default disabled.
To activate the new configuration, you need to run:
  service apache2 reload
+ '[' true '!=' true ']'
+ ls /var/www/html
++ id -u
++ id -g
+ sudo chown -R 1000:1000 /mnt/composer_cache/
+ echo 'Server started'
+ exec /usr/bin/supervisord -n -c /etc/supervisor/supervisord-apache-fpm.conf
Server started
2018-12-20 15:40:34,684 INFO Included extra file "/etc/supervisor/apache.conf" during parsing
2018-12-20 15:40:34,684 INFO Included extra file "/etc/supervisor/php-fpm.conf" during parsing
2018-12-20 15:40:34,684 INFO Included extra file "/etc/supervisor/conf.d/mailhog.conf" during parsing
2018-12-20 15:40:34,684 INFO Included extra file "/etc/supervisor/conf.d/supervisor.conf" during parsing
2018-12-20 15:40:34,685 INFO supervisord started with pid 1
2018-12-20 15:40:35,689 INFO spawned: 'child_exit_monitor' with pid 57
2018-12-20 15:40:35,691 INFO spawned: 'php-fpm' with pid 58
2018-12-20 15:40:35,694 INFO spawned: 'apache2' with pid 59
2018-12-20 15:40:35,697 INFO spawned: 'mailhog' with pid 60
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
[Thu Dec 20 15:40:35.747301 2018] [mpm_prefork:notice] [pid 66] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Thu Dec 20 15:40:35.747381 2018] [core:notice] [pid 66] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
[20-Dec-2018 15:40:35] NOTICE: fpm is running, pid 58
[20-Dec-2018 15:40:35] NOTICE: ready to handle connections
[20-Dec-2018 15:40:35] NOTICE: systemd monitor interval set to 10000ms
2018-12-20 15:40:36,765 INFO success: child_exit_monitor entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-12-20 15:40:36,766 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-12-20 15:40:36,766 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-12-20 15:40:36,766 INFO success: mailhog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[Thu Dec 20 15:40:38.525333 2018] [proxy:error] [pid 71] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.3-fpm.sock (*) failed
[Thu Dec 20 15:40:38.525390 2018] [proxy_fcgi:error] [pid 71] [client 127.0.0.1:35070] AH01079: failed to make connection to backend: httpd-UDS
[Thu Dec 20 15:40:42.782311 2018] [proxy:error] [pid 70] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.3-fpm.sock (*) failed
[Thu Dec 20 15:40:42.782368 2018] [proxy_fcgi:error] [pid 70] [client 127.0.0.1:35108] AH01079: failed to make connection to backend: httpd-UDS
[Thu Dec 20 15:40:46.992189 2018] [proxy:error] [pid 72] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.3-fpm.sock (*) failed
[Thu Dec 20 15:40:46.992243 2018] [proxy_fcgi:error] [pid 72] [client 127.0.0.1:35146] AH01079: failed to make connection to backend: httpd-UDS
[Thu Dec 20 15:40:51.226735 2018] [proxy:error] [pid 68] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.3-fpm.sock (*) failed
[Thu Dec 20 15:40:51.226789 2018] [proxy_fcgi:error] [pid 68] [client 127.0.0.1:35184] AH01079: failed to make connection to backend: httpd-UDS
[Thu Dec 20 15:40:55.516337 2018] [proxy:error] [pid 69] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.3-fpm.sock (*) failed
[Thu Dec 20 15:40:55.516388 2018] [proxy_fcgi:error] [pid 69] [client 127.0.0.1:35220] AH01079: failed to make connection to backend: httpd-UDS
[Thu Dec 20 15:40:59.733355 2018] [proxy:error] [pid 71] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.3-fpm.sock (*) failed
[Thu Dec 20 15:40:59.733370 2018] [proxy_fcgi:error] [pid 71] [client 127.0.0.1:35266] AH01079: failed to make connection to backend: httpd-UDS
[Thu Dec 20 15:41:03.986995 2018] [proxy:error] [pid 70] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.3-fpm.sock (*) failed
[Thu Dec 20 15:41:03.987010 2018] [proxy_fcgi:error] [pid 70] [client 127.0.0.1:35304] AH01079: failed to make connection to backend: httpd-UDS
[Thu Dec 20 15:41:08.218291 2018] [proxy:error] [pid 72] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.3-fpm.sock (*) failed
[Thu Dec 20 15:41:08.218306 2018] [proxy_fcgi:error] [pid 72] [client 127.0.0.1:35342] AH01079: failed to make connection to backend: httpd-UDS
[Thu Dec 20 15:41:12.449181 2018] [proxy:error] [pid 68] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.3-fpm.sock (*) failed
[Thu Dec 20 15:41:12.449195 2018] [proxy_fcgi:error] [pid 68] [client 127.0.0.1:35384] AH01079: failed to make connection to backend: httpd-UDS

**With nginx-fpm and hooks disabled:**

Webserver runs, but calling URL got "Bad Gateway"

+ set -o errexit nounset pipefail
+ DDEV_PHP_VERSION=7.3
+ DDEV_WEBSERVER_TYPE=nginx-fpm
+ '[' -n public ']'
+ export WEBSERVER_DOCROOT=/var/www/html/public
+ WEBSERVER_DOCROOT=/var/www/html/public
+ export NGINX_DOCROOT=/var/www/html/public
+ NGINX_DOCROOT=/var/www/html/public
+ '[' -f /mnt/ddev_config/nginx-site.conf ']'
+ '[' -f /mnt/ddev_config/apache/apache-site.conf ']'
+ '[' -n 7.3 ']'
+ update-alternatives --set php /usr/bin/php7.3
update-alternatives: using /usr/bin/php7.3 to provide /usr/bin/php (php) in manual mode
+ ln -sf /usr/sbin/php-fpm7.3 /usr/sbin/php-fpm
+ export PHP_INI=/etc/php/7.3/fpm/php.ini
+ PHP_INI=/etc/php/7.3/fpm/php.ini
+ '[' -d /mnt/ddev_config/php ']'
+ '[' typo3 = backdrop ']'
+ rm -f /etc/nginx/nginx-site.conf
+ '[' -f /etc/nginx/nginx-site-typo3.conf ']'
+ ln -s /etc/nginx/nginx-site-typo3.conf /etc/nginx/nginx-site.conf
+ rm -f /etc/apache2/apache-site.conf
+ '[' -f /etc/apache2/ddev_apache-typo3.conf ']'
+ ln -s -f /etc/apache2/apache-site-default.conf /etc/apache2/apache-site.conf
+ envsubst '$WEBSERVER_DOCROOT,$NGINX_DOCROOT'
+ envsubst '$WEBSERVER_DOCROOT'
++ id -u
++ id -g
+ printf '\nexport APACHE_RUN_USER=uid_1000\nexport APACHE_RUN_GROUP=gid_1000\n'
+ '[' nginx-fpm = apache-cgi ']'
+ '[' nginx-fpm = apache-fpm ']'
+ '[' true '!=' true ']'
+ ls /var/www/html
++ id -u
++ id -g
+ sudo chown -R 1000:1000 /mnt/composer_cache/
+ echo 'Server started'
+ exec /usr/bin/supervisord -n -c /etc/supervisor/supervisord-nginx-fpm.conf
Server started
2018-12-20 15:44:08,632 INFO Included extra file "/etc/supervisor/php-fpm.conf" during parsing
2018-12-20 15:44:08,632 INFO Included extra file "/etc/supervisor/conf.d/mailhog.conf" during parsing
2018-12-20 15:44:08,632 INFO Included extra file "/etc/supervisor/conf.d/supervisor.conf" during parsing
2018-12-20 15:44:08,633 INFO supervisord started with pid 1
2018-12-20 15:44:09,637 INFO spawned: 'child_exit_monitor' with pid 25
2018-12-20 15:44:09,640 INFO spawned: 'php-fpm' with pid 26
2018-12-20 15:44:09,645 INFO spawned: 'nginx' with pid 27
2018-12-20 15:44:09,648 INFO spawned: 'mailhog' with pid 28
[20-Dec-2018 15:44:09] NOTICE: fpm is running, pid 26
[20-Dec-2018 15:44:09] NOTICE: ready to handle connections
[20-Dec-2018 15:44:09] NOTICE: systemd monitor interval set to 10000ms
2018-12-20 15:44:10,707 INFO success: child_exit_monitor entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-12-20 15:44:10,707 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-12-20 15:44:10,707 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-12-20 15:44:10,707 INFO success: mailhog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[20-Dec-2018 15:44:24] WARNING: [pool www] child 37 exited on signal 11 (SIGSEGV - core dumped) after 14.748245 seconds from start
2018/12/20 15:44:24 [error] 34#34: *7 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.18.0.4, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "jobrouter.ddev.local:8080"
[20-Dec-2018 15:44:24] NOTICE: [pool www] child 74 started
2018/12/20 15:44:35 [error] 34#34: *16 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.18.0.4, server: _, request: "GET /typo3/ HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "jobrouter.ddev.local:8080"
[20-Dec-2018 15:44:35] WARNING: [pool www] child 38 exited on signal 11 (SIGSEGV - core dumped) after 26.027269 seconds from start
[20-Dec-2018 15:44:35] NOTICE: [pool www] child 108 started

Hope, that helps.

**Comment by rfay** [comment]
So it works fine (except for the php-fpm child coredumping early) with your hooks disabled? 

If that's the case, could you please try the actions in your hooks one at a time (manually) to see which one kills php-fpm?

**Comment by brotkrueml** [comment]
Oh, you misunderstood me: I have to run ddev with Apache, the container has the described problems (also without the hooks). I switched temporarily to nginx (just to see if it works there), here I experienced some other problems (Bad gateway, the php-fpm process died). So in both scenarios PHP 7.3 doesn't work for me in a TYPO3 environment. According the website, TYPO3 v9 should be PHP 7.3 compatible: https://typo3.org/cms/roadmap/#legend - so this shouldn't be the problem.

**Comment by rfay** [comment]
Please try a plain TYPO3 project without hooks or any additional configuration.  I imagine you'll find that works. 

Then please work from there to the action that causes php-fpm to die (which seems to be what's happening). If you can get it to happen on a plain TYPO3 project, then we'll have a strategy we can work with to fix it. 

Thanks for working with us on this.

**Comment by rfay** [comment]
I confirm this behavior with a plain TYPO3 install with apache, so that should mean that either we or the PHP project or TYPO3 should be able to fix it. We just need to figure out the next step with figuring out why php-fpm dies. That may not be easy.

**Comment by rfay** [comment]
Updated the title, this doesn't have to do with TYPO3; AFAICT it's php7.3 + apache-fpm

**Comment by rfay** [comment]
And an additional problem to be sorted out in this issue: We should have caught this in tests.
