### ISSUE TITLE
Chrome: Content-Security-Policy with browsersync

### ISSUE THREAD

**Issue by landwire** [drud/ddev#1359]
**Describe the bug**
I am running my ddev Backend Site through a local browsersync proxy. This works fine, but gave me security issues. I added 
`add_header 'Access-Control-Allow-Origin' '*';`
and this worked fine. Chrome however throws errors after reloading the page:

> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-Na0J8gwa7Fw3My1JYYDtZZwgXsGMhTdqj73IVDa5OPE='), or a nonce ('nonce-...') is required to enable inline execution.

So I added ` add_header "Content-Security-Policy" "script-src 'self' * 'unsafe-inline' 'unsafe-eval'; frame-src 'self'; object-src 'self'";`

But this does not seem to have any effect.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: [e.g. Windows 10, macOS High Sierra]
 - Docker version information (use `docker version`) and insert it here.
 - ddev version information (use `ddev version`)
 - config.yaml contents for the misbehaving project
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

**Additional context**
Add any other context about the problem here. Thanks!

**Comment by rfay** [comment]
Sorry, this won't be actionable without more setup information from you. Please give step-by-step instructions on how you are set up and what happened.  Please do it with a generic CMS setup (Drupal?) so that we can tell it doesn't have to do with custom code and setup, so we can recreate it.

I tried a trivial browsersync setup with https://www.browsersync.io/#install and saw nothing like this.

**Comment by rfay** [comment]
No response from OP, but we're sure interested in making this work for you. Please feel free to follow up here, but closing this for now.
