### ISSUE TITLE
Webcache feature: bgsync error

### ISSUE THREAD

**Issue by MrPaulDriver** [drud/ddev#1360]
Have gotten off to a good start with the new webcache feature on Mac OS, I am now running into a bgsync problem and find that I am unable to run ddev start with webcache_enabled. 

I am not aware of anything changing. webcache_enabled was working for me, but now it is not.

Assuming a site called 'drupal'. After removing and restarting, I get the following output.

```
Starting drupal...
Creating volume "ddev-drupal_webcachevol" with default driver
Creating ddev-drupal-bgsync ... done
Creating ddev-drupal-db     ... done
Creating ddev-drupal-dba    ... done
Creating ddev-drupal-web    ... done

ddev-router is up-to-date
Running Command  Command=docker cp /Users/paul/Sites/drupal/. ddev-drupal-bgsync:/fastdockermount
Command Result  Result=
repo files push to container completed in 6.755562142s
Failed to start drupal: bgsync container failed: log=waiting to start unison, err=container /ddev-drupal-bgsync unhealthy: waiting to start unison

```

**Comment by MrPaulDriver** [comment]
Resetting Docker to factory defaults did the trick.

Thanks Rudy

**Comment by rfay** [comment]
If you don't mind I'm going to close this one as it doesn't add a particular technique to recreate a webcache error. We will absolutely be working on weaknesses in coming releases before it's declared not "experimental"
