### ISSUE TITLE
webache use rsync instead of cp

### ISSUE THREAD

**Issue by kaystrobach** [drud/ddev#1363]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when ddev starts up, as bgsync takes ages.

**Describe the solution you'd like**

use rsync instead of plain old cp

`Running Command  Command=docker cp /Users/kay/Development/SBS/Lapo/. ddev-lapo-bgsync:/fastdockermount`

**Additional context**
using a big flow application.

**Comment by kaystrobach** [comment]
also sometimes sync does not recognize file changes.

**Comment by rfay** [comment]
@kaystrobach This doesn't use cp. The initial `docker cp` is to prepopulate the entire project inside the container. It's vastly faster than any other technique we've ever seen. But it's just the start. Then the unison application takes over, which uses fsnotify to find out when things change, and rsync to sync them when they do. It's 2-way sync, which rsync cannot do alone.

Happy to continue the conversation here.

And really wanting to here specific issues, especially if we can come up with ways to recreate them.

**Comment by kaystrobach** [comment]
Ok, for it just looked like cp, as the command is printed out on the cli during startup.

Rsync should be faster from the second start on, as it has very clever techniques to sync dirs.
