### ISSUE TITLE
ddev composer [scriptname] returns always exit code 0

### ISSUE THREAD

**Issue by codemonkey1988** [drud/ddev#1373]
**Describe the bug**
When I run a script defined in composer.json using `ddev composer [scriptname]`, the command always returns exit code 0 even if the executed script returns another exit code.
When using `ddev exec composer [scriptname] -d /var/www/html`, the exit code is correct.

**To Reproduce**
1. Add a new script to your composer.json like `"test-exit-code": "exit 1"`
2. Run `ddev composer test-exit-code && echo $?`

**Expected behavior**
The command should fail with exit code 1.

**Version and configuration information (please complete the following information):**
 - macOS 10.14.2
 - Docker version 18.09.0
 - ddev version 1.5.1

**Additional context**
I'm using this to run php-cs-fixer. I added a script to composer so that I can just run `composer phpcs` instead of typing the whole command. I'm using this also in a pre-commit hook and because of the exit code 0, the hook will never abort the commit.

**Comment by rfay** [comment]
Thanks for reporting this, it does sound like something that needs to be fixed.

**Comment by codemonkey1988** [comment]
I don't think this issue has a high priority but it would be nice to see this fixed.
