### ISSUE TITLE
ddev no longer respects dbimage: <imagespec> in config.yaml

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1374]
**Describe the bug**

If you put an alternate dbimage: in config.yaml, it is no longer respected; the version wired into ddev is used instead.

**To Reproduce**

Put 
```
dbimage: drud/ddev-dbserver:v1.4.0-10.2
```
into config.yaml. It will be ignored when you `ddev start`

**Expected behavior**

It should kind of be respected.

**Version and configuration information (please complete the following information):**

```
bgsync        	drud/ddev-bgsync:v1.5.0
cli           	v1.5.1-19-g44175b7f
commit        	v1.5.1-19-g44175b7f
db            	drud/ddev-dbserver:20190103_import-db-progress-10.2
dba           	drud/phpmyadmin:v1.5.0
ddev-ssh-agent	drud/ddev-ssh-agent:v1.5.0
docker        	18.09.0
docker-compose	1.23.2
domain        	ddev.local
router        	drud/ddev-router:v1.5.0
web           	drud/ddev-webserver:20190107_web_container_maint
```
**Additional context**
Add any other context about the problem here. Thanks!

**Comment by longwave** [comment]
Hah, I thought this was just me doing something wrong when trying to locally develop #1349, never realised it was an actual real bug!
