### ISSUE TITLE
Can't start database service on Windows 10 for Drupal 8

### ISSUE THREAD

**Issue by yaazkal** [drud/ddev#1387]
**Describe the bug**
Can't start a Drupal 8 project using Windows 10 Pro, Docker Desktop 2.0.0.2 and DDEV 1.5.2

**To Reproduce**
1. Fresh install Docker 2.0
2. Fresh install DDEV 1.5.2
3. Clone a Drupal 8 project 
4. `cd example.com` (to be at the drupal project folder)
5. `composer install`
6. `ddev config`
7. `ddev start`

8.

```
Network ddev_default created
Starting example.com...
Creating volume "ddev-ssh-agent_dot_ssh" with default driver
Creating volume "ddev-ssh-agent_socket_dir" with default driver
Pulling ddev-ssh-agent (drud/ddev-ssh-agent:v1.5.2)...
Creating ddev-ssh-agent ... done

ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
You must manually add the following entry to your hosts file:
127.0.0.1 example.com.ddev.local
Or with root/administrative privileges execute 'ddev hostname example.com.ddev.local 127.0.0.1'
Creating volume "example.com-mariadb" with default driver
Creating volume "ddev-composer-cache" with default driver
Pulling db (drud/ddev-dbserver:v1.5.2-10.2)...
Pulling web (drud/ddev-webserver:v1.5.2)...
Pulling dba (drud/phpmyadmin:v1.5.2)...
Creating ddev-example.com-db ... error

ERROR: for ddev-example.com-db  Cannot start service db: driver failed programming external connectivity on endpoint ddev-example.com-db (3f04edd4b1f78bac9346bbe13bf24cd8f9c36a5b75e1e8ba7aba8a0fa76d13b6): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:32777:tcp:172.18.0.3:3306: input/output error

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint ddev-example.com-db (3f04edd4b1f78bac9346bbe13bf24cd8f9c36a5b75e1e8ba7aba8a0fa76d13b6): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:32777:tcp:172.18.0.3:3306: input/output error
Encountered errors while bringing up the project.
Failed to start example.com: Failed to run docker-compose [-f C:\Sitios\example.com\.ddev\docker-compose.yaml up -d], err='exit status 1', stdout='v1.5.2-10.2: Pulling from drud/ddev-dbserver
v1.5.2: Pulling from drud/ddev-webserver
v1.5.2: Pulling from drud/phpmyadmin
', stderr='Creating volume "example.com-mariadb" with default driver
Creating volume "ddev-composer-cache" with default driver
Pulling db (drud/ddev-dbserver:v1.5.2-10.2)...
Pulling web (drud/ddev-webserver:v1.5.2)...
Pulling dba (drud/phpmyadmin:v1.5.2)...
Creating ddev-example.com-db ... error

ERROR: for ddev-example.com-db  Cannot start service db: driver failed programming external connectivity on endpoint ddev-example.com-db (3f04edd4b1f78bac9346bbe13bf24cd8f9c36a5b75e1e8ba7aba8a0fa76d13b6): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:32777:tcp:172.18.0.3:3306: input/output error

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint ddev-example.com-db (3f04edd4b1f78bac9346bbe13bf24cd8f9c36a5b75e1e8ba7aba8a0fa76d13b6): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:32777:tcp:172.18.0.3:3306: input/output error
Encountered errors while bringing up the project.'
```

**Expected behavior**
Well, it should start a site or at least shows that it was good to start :)

**Screenshots**
N/A

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Windows 10 Pro 
 - Docker version information (use `docker version`) and insert it here.
```
Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:34:26 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:41:49 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```
 - ddev version information (use `ddev version`)
```
bgsync          drud/ddev-bgsync:v1.5.2
cli             v1.5.2
commit          v1.5.2
db              drud/ddev-dbserver:v1.5.2-10.2
dba             drud/phpmyadmin:v1.5.2
ddev-ssh-agent  drud/ddev-ssh-agent:v1.5.2
docker          18.09.1
docker-compose  1.23.2
domain          ddev.local
router          drud/ddev-router:v1.5.2
web             drud/ddev-webserver:v1.5.2
```
 - config.yaml contents for the misbehaving project
```
APIVersion: v1.5.2
name: example.com
type: drupal8
docroot: ""
php_version: "7.1"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
webcache_enabled: false
provider: default
```
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?
None

**Additional context**
There is not docroot or web folder for the project; vendor and drupal are at the same root folder level. I don't think is related but I had to point it.

**Comment by rfay** [comment]
I imagine you haven't shared the C: drive in Docker, please go to "File sharing" and share it. Unfortunately on docker-for-windows, every time you factory reset you have to do that over again.

To see if docker is working correctly, use the magic formula in https://ddev.readthedocs.io/en/latest/users/docker_installation/#testing-and-troubleshooting-your-docker-installation

Let me know if that was it.

**Comment by yaazkal** [comment]
Thanks. It is shared actually. I'll try the magic formula and will update later this issue.

**Comment by yaazkal** [comment]
So, trying the magic formula (using git bash as pointed on the docs):

```
 $ docker run --rm -t -p 80:80 -v "/$PWD:/tmp/projdir" -v "/$HOME:/tmp/homedir" busybox sh -c "echo ---- Project Directory && ls //tmp/projdir && echo ---- Home Directory && ls //tmp/homedir"
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
57c14dd66db0: Pulling fs layer
57c14dd66db0: Verifying Checksum
57c14dd66db0: Download complete
57c14dd66db0: Pull complete
Digest: sha256:7964ad52e396a6e045c39b5a44438424ac52e12e4d5a25d94895f2058cb863a0
Status: Downloaded newer image for busybox:latest
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: driver failed programming external connectivity on endpoint pedantic_joliot (ac6bd1debb378a41c7eda328f5a4d753e387860bb2413ca8d9efd2baa293108e): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:80:tcp:172.17.0.2:80: input/output error.
```

Am I missing something? Not sure then if I need to open any ports on the firewall. I just configured the corresponding 445 port for Docker.

I'll google and see if I can find any information about `Error starting userland proxy: mkdir /port/tcp:0.0.0.0:80:tcp:172.17.0.2:80: input/output error`

**Comment by yaazkal** [comment]
Looks like disabling `Experimental features` as pointed [here](https://github.com/docker/for-win/issues/573#issuecomment-288368024) do the trick and the magic formula seems to work. I'll try again to start up the project and update this issue as needed.

**Comment by rfay** [comment]
This magic formula tries to bind to the default port 80; If port 80 is in use, you'll have that trouble.

What were you trying to accomplish with Experimental Features?

**Comment by yaazkal** [comment]
> What were you trying to accomplish with Experimental Features?

Oh, nothing, just that they are enabled by default.

**Comment by yaazkal** [comment]
It is working!

As `Experimental features` are enabled by default, I'll suggest to add that information to the docs if you thing is relevant.

Thanks so much !

**Comment by rfay** [comment]
Yay that it's working for you!

Experimental features are *not* enabled by default, I just checked. I see they're explained at https://github.com/docker/cli/tree/master/experimental#docker-experimental-features, but definitely not default, so I don't know either how it got enabled for you... or anything :)

But so glad it's working for you. I've only seen the kind of behavior you had when the drive is not shared, which unfortunately happens a lot on Windows.

Closing since it's working for you.

**Comment by yaazkal** [comment]
Well, not sure why they where enabled then. The user at the issue that I pointed earlier seems to had it enabled by default too.

Anyway seems to be the fix on Windows.

Thanks again!

**Comment by slaterbbx** [comment]
Its not the fix as stated in that thread, you will surely have this issue again very soon. All you did was restart docker, which is actually the fix for the issue. For some reason, the way docker starts up initially is the underlying issue and you must restart it every time you log on to your windows machine.
