### ISSUE TITLE
`ddev auth ssh` on Docker Toolbox shows `stdin` instead of filename

### ISSUE THREAD

**Issue by jfastnacht** [drud/ddev#1394]
**Describe the bug**
When I run `ddev auth ssh` in my project it shows `Enter passphrase for (stdin):` for each key file in my `.ssh` directory instead of the actual name of the key file.

**To Reproduce**
1. Run `ddev auth ssh` in the project
2. You see `Enter passphrase for (stdin):`
3. Enter passphrase of one of your key files
4. Error or success adding the identity

**Expected behavior**
It should show something like `Enter passphrase for ('C:\Users\j.fastnacht\.ssh\id_rsa'):`

**Screenshots**
I have two keyfiles in my `.ssh` directory. It shows `stdin` for each of them and I had to figure out which one is which.

```
λ ddev auth ssh
Enter passphrase for (stdin): ******
Identity added: (stdin) ((stdin))
Enter passphrase for (stdin): ******
Identity added: (stdin) ((stdin))
```

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Windows 8.1
 - Docker version information:
```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.11.1
 Git commit:        4d60db472b
 Built:             Thu Nov  8 21:14:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:52:55 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
 - ddev version information: 1.5.2
 - config.yaml contents for the misbehaving project
```
APIVersion: v1.3.0
name: ***
type: typo3
docroot: app/web
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
```
Tried with other projects (also APIVersion 1.5.2) with the same error.

 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

Custom config: No.

**Additional context**
I'm running cmd within Cmder, not PowerShell.

**Comment by rfay** [comment]
Thanks so much, that seems worth solving. There are interesting technical reasons we can't show the exact key name, but I would think we could make it less ambiguous.

**Comment by rfay** [comment]
Oh I just noticed @jfastnacht you're using WIndows 8.1. How is that? We've never tested there, but expect that ddev will work anywhere docker toolbox does.

**Comment by rfay** [comment]
Updated the title; this is a docker windows-only issue; the problem is that keys get mounted into the container with permission 777, and ssh-add absolutely refuses to deal with that, but there's no way to fix that inside the container (or anywhere else).

**Comment by jfastnacht** [comment]
@rfay 
> Oh I just noticed @jfastnacht you're using WIndows 8.1. How is that with ddev? We've never tested there, but expect that ddev will work anywhere docker toolbox does.

It's working very well so far. Problems I encountered were mostly Docker (Toolbox) related, not ddev. Thank you very much, ddev is awesome!

**Comment by rfay** [comment]
Thanks so much for testing!

I don't like the passphrase in plaintext either; that's docker toolbox only, I couldn't figure out a way around it. 

There are *lots* of constraints in Docker Toolbox :) We highly recommend Docker for Windows, which is the place that Docker actually maintains the product. Docker Toolbox is pretty much on autopilot.

**Comment by jfastnacht** [comment]
I can't use Docker for Windows on Windows 8.1, unfortunately. I can't tell when I will be able to switchover, so I have to deal with Docker Toolbox up to that point.

I think that the issue is solved for me, thank you!

**Comment by rfay** [comment]
No, I totally understand about Win8 and Toolbox. Was just saying that the number of things that have to be handled in a one-off way for Toolbox is quite shocking.

I'd love to have you review our upcoming NFS support PR and see if it gives you improved performance, https://github.com/drud/ddev/pull/1396#issuecomment-457872155
