### ISSUE TITLE
Implement support for datagrip similar to sequelpro support

### ISSUE THREAD

**Issue by kaystrobach** [drud/ddev#1397]
**Is your feature request related to a problem? Please describe.**

Datagrip is an application, which has a similar functionality like sequelpro.
Sadly sequelpro is getting more and more instable, so we need an alternative:

* https://www.jetbrains.com/datagrip/

**Describe the solution you'd like**

* Implement the same functionality like `ddev sequelpro` for `ddev datagrip` for passing the database DSN and credentials, either via `FILE` or via `ENV Vars` or `ARGUMENT`
* Should either launch datagrip with setup or phpstorm with the same file (datagrip can be integrated as plugin)
* makes development easier.

**Describe alternatives you've considered**

* manuall datagrip setup

**Additional context**

* https://www.jetbrains.com/help/datagrip/working-with-the-ide-features-from-command-line.html
* https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000180404-Ability-to-connect-to-a-database-from-the-command-line

**Comment by rfay** [comment]
The fantastic thing about datagrip is that it's multiplatform, unlike sequelpro.
The bad thing is it's really pricey.

I wonder if we could use [stable port number for accessing mysql](https://github.com/drud/ddev/issues/941) or something like it as a general technique, and then somehow use global config to determine what tool gets run.

**Comment by kaystrobach** [comment]
https://twitter.com/datagrip/status/1088006341120139264
> @kaystrobach @jetbrains Can we ask you to describe the use case? How are you going to use this feature?

**Comment by kaystrobach** [comment]
jetbrains reacted with a new ticket:

* https://youtrack.jetbrains.com/issue/DBE-7685

**Comment by kaystrobach** [comment]
just spend some time to understand datagrip connection handling:

There is a file called **.idea/dataSources.xml** 

If you would simply update that file with ddev the connection would be accessable from phpstorm and from datagrip - this works atleast if you first start ddev and then phpstorm

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="DataSourceManagerImpl" format="xml" multifile-model="true">
    <data-source source="LOCAL" name="ddev - connection name" uuid="d0c53247-ec9f-44c8-9f4c-ea8f03b67892">
      <driver-ref>mysql.8</driver-ref>
      <synchronize>true</synchronize>
      <jdbc-driver>com.mysql.jdbc.Driver</jdbc-driver>
      <jdbc-url>jdbc:mysql://127.0.0.1:32768/db</jdbc-url>
      <driver-properties>
        <property name="autoReconnect" value="true" />
        <property name="zeroDateTimeBehavior" value="CONVERT_TO_NULL" />
        <property name="tinyInt1isBit" value="false" />
        <property name="characterEncoding" value="utf8" />
        <property name="characterSetResults" value="utf8" />
        <property name="yearIsDateType" value="false" />
      </driver-properties>
    </data-source>
  </component>
</project>
```

**Comment by kaystrobach** [comment]
but it seems to not work always ... so it still needs some investigation

**Comment by rfay** [comment]
This is super easy to do now with custom commands, so there's an example for mysqlworkbench in every ddev project (.ddev/commands/host/mysqlworkbench.example). Contributions are welcome for other tools (probably https://github.com/drud/ddev-contrib is the best place). Closing this for now as I think community-contributed commands are the path forward for things like this.

**Comment by josefglatz** [comment]
@kaystrobach any progress here?

**Comment by natereprogle** [comment]
I hate to necro this issue, but it's the first one I came across when Googling (Even though I see a few other issues)

I took the time to create a DDEV Add-On to support opening DataGrip just like when using `ddev sequelpro` or `ddev sequelace`. It can be installed with `ddev add-on get natereprogle/ddev-datagrip`. Hopefully this helps anyone finding there way here 6 years later 😄

This is really only helpful if you don't use PhpStorm, as DDEV has a plugin for PhpStorm which automatically handles datasource configuration. However, maybe someone will still find some use for this!

**Comment by kaystrobach** [comment]
you are my hero.

**Comment by natereprogle** [comment]
> you are my hero.

Glad I could help, 7 years late though haha! I will say, the only annoyance is that the first run of DataGrip requires a manual refresh. After that, any subsequent launch is fine. This is a limitation of DataGrip I believe, no amount of configuration changes I made were able to force DataGrip to refresh the data source on first launch.

**Comment by kaystrobach** [comment]
maybe it makes sense to ask jetbrains for a cli interface to get that automated, I think there was a proposal to do that.

* https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000180404-Ability-to-connect-to-a-database-from-the-command-line
* https://youtrack.jetbrains.com/issue/DBE-7685

**Comment by rfay** [comment]
Fixed with https://github.com/natereprogle/ddev-datagrip

`ddev add-on get natereprogle/ddev-datagrip`

Thanks!
