### ISSUE TITLE
Support installation of CiviCrm

### ISSUE THREAD

**Issue by nigelwhite** [drud/ddev#1398]
**Is your feature request related to a problem? Please describe.**
I could not install CiviCrm in a normal ddev Drupal 7. When running the CiviCrm installation script, via the browser, I get "Could not create a database trigger".

**Describe the solution you'd like**
CiviCrm requirements at https://docs.civicrm.org/sysadmin/en/latest/requirements/ includes mysql trigger support is required. It would be great if ddev provided this out of the box.

**Describe alternatives you've considered**
I tried MariaDB [db]> GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, TRIGGER, CREATE ROUTINE, ALTER ROUTINE ON db.* TO 'db'@'localhost' IDENTIFIED BY 'db'; and I got the response Query OK, 0 rows affected (0.01 sec). This made no difference. Still got "Could not create a database trigger".

https://civicrm.stackexchange.com/questions/2770/database-trigger-error-message suggests another option, if you are using binary logging. I don't know if I am or not, so I didn't try that.

**Comment by rfay** [comment]
Please use the root user to do the grants and see how that goes.  In either web or db container:
`
mysql -uroot -proot 
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, TRIGGER, CREATE ROUTINE, ALTER ROUTINE ON db.* TO 'db'@'%' IDENTIFIED BY 'db';
`

You can do this in post-import-db or post-start hooks if you want to also.

**Comment by rfay** [comment]
Hmm, turns out this isn't about privileges but mysql configuration.

You can solve this problem in the sort term by creation .ddev/mysql/trigger.cnf with the contents
```
[mysqld]
log_bin_trust_function_creators=on
```

That got me through the D7 civicrm setup just fine.  #1399 will add that by default.

**Comment by nigelwhite** [comment]
Perfect. Civi installed smoothly. Many thanks
