### ISSUE TITLE
Mariadb fails on startup with docker on ext2 "InnoDB: preallocating 67108864 bytes for file ./ib_logfile101 failed with error 95"

### ISSUE THREAD

**Issue by quietone1** [drud/ddev#1406]
**Describe the bug**
Maria container fails. Tried with drupal 6, drupal 8 and simple project of type php. The last suggested by rfay on Slack. 

**To Reproduce**
```
$ ddev config --project-type=php; ddev start
Creating a new ddev project config in the current directory (/mnt/tohora/projects/junk)
Once completed, your configuration will be written to /mnt/tohora/projects/junk/.ddev/config.yaml

Found a php codebase at /mnt/tohora/projects/junk
Project type has no settings paths configured, so not creating settings file.
Configuration complete. You may now run 'ddev start'.
Starting junk...
Creating ddev-ssh-agent ... done

ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
Running Command  Command=ip address show dev docker0
ddev needs to add an entry to your hostfile.
It will require administrative privileges via the sudo command, so you may be required
to enter your password for sudo. ddev is about to issue the command:
   sudo /usr/local/bin/ddev hostname junk.ddev.local 127.0.0.1
Please enter your password if prompted.
Running Command  Command=sudo /usr/local/bin/ddev hostname junk.ddev.local 127.0.0.1
Creating volume "junk-mariadb" with default driver
Creating ddev-junk-db ... done
Creating ddev-junk-web ... done
Creating ddev-junk-dba ... done

Creating ddev-router ... done

Failed to start junk: db container failed: log=ERROR 2002 (HY000): Can't connect to MySQL server on '127.0.0.1' (115)
, err=container /ddev-junk-db unhealthy: ERROR 2002 (HY000): Can't connect to MySQL server on '127.0.0.1' (115)
```

**Expected behavior**
A working maria db container.

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: [e.g. Windows 10, macOS High Sierra]
`Debian GNU/Linux 9.7 (stretch) - A new install`
 - Docker version information (use `docker version`) and insert it here.
```
$ docker version
Client:
Version:           18.09.1
API version:       1.39
Go version:        go1.10.6
Git commit:        4c52b90
Built:             Wed Jan  9 19:35:59 2019
OS/Arch:           linux/amd64
Experimental:      false

Server: Docker Engine - Community
Engine:
 Version:          18.09.1
 API version:      1.39 (minimum version 1.12)
 Go version:       go1.10.6
 Git commit:       4c52b90
 Built:            Wed Jan  9 19:02:44 2019
 OS/Arch:          linux/amd64
 Experimental:     false
```
 - ddev version information (use `ddev version`)
```
$ ddev version
bgsync        	drud/ddev-bgsync:v1.5.2                                        
cli           	v1.5.2                                                         
commit        	v1.5.2                                                         
db            	drud/ddev-dbserver:v1.5.2-10.2                                 
dba           	drud/phpmyadmin:v1.5.2                                         
ddev-ssh-agent	drud/ddev-ssh-agent:v1.5.2                                     
docker        	failed to GetDockerVersion(): cannot connect to Docker endpoint
docker-compose	1.22.0                                                         
domain        	ddev.local                                                     
router        	drud/ddev-router:v1.5.2                                        
web           	drud/ddev-webserver:v1.5.2   
```
 - config.yaml contents for the misbehaving project
Discussed with rfay in Slack and he suggested trying a junk project
```
$ cat config.yaml 
APIVersion: v1.5.2
name: junk
type: php
docroot: ""
php_version: "7.1"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
webcache_enabled: false
provider: default


# This config.yaml was created with ddev version v1.5.2 
# webimage: drud/ddev-webserver:v1.5.2
# dbimage: drud/ddev-dbserver:v1.5.2-10.2
# dbaimage: drud/phpmyadmin:v1.5.2
# bgsyncimage: drud/ddev-bgsync:v1.5.2
# However we do not recommend explicitly wiring these images into the
# config.yaml as they may break future versions of ddev.
# You can update this config.yaml using 'ddev config'.

# Key features of ddev's config.yaml:

# name: <projectname> # Name of the project, automatically provides
#   http://projectname.ddev.local and https://projectname.ddev.local

# type: <projecttype>  # drupal6/7/8, backdrop, typo3, wordpress, php

# docroot: <relative_path> # Relative path to the directory containing index.php.

# php_version: "7.1"  # PHP version to use, "5.6", "7.0", "7.1", "7.2", "7.3"

# You can explicitly specify the webimage, dbimage, dbaimage lines but this
# is not recommended, as the images are often closely tied to ddev's' behavior,
# so this can break upgrades.

# webimage: <docker_image>  # nginx/php docker image.
# dbimage: <docker_image>  # mariadb docker image.
# dbaimage: <docker_image>
# bgsyncimage: <docker_image>

# router_http_port: <port>  # Port to be used for http (defaults to port 80)
# router_https_port: <port> # Port for https (defaults to 443)

# xdebug_enabled: false  # Set to true to enable xdebug and "ddev start" or "ddev restart"

# webserver_type: nginx-fpm  # Can be set to apache-fpm or apache-cgi as well

# additional_hostnames:
#  - somename
#  - someothername
# would provide http and https URLs for "somename.ddev.local"
# and "someothername.ddev.local".

# additional_fqdns:
#  - example.com
#  - sub1.example.com
# would provide http and https URLs for "example.com" and "sub1.example.com"
# Please take care with this because it can cause great confusion.

# upload_dir: custom/upload/dir
# would set the destination path for ddev import-files to custom/upload/dir.

# working_dir:
#   web: /var/www/html
#   db: /home
# would set the default working directory for the web and db services. 
# These values specify the destination directory for ddev ssh and the 
# directory in which commands passed into ddev exec are run. 

# omit_containers: ["dba", "ddev-ssh-agent"]
# would omit the dba (phpMyAdmin) and ddev-ssh-agent containers. Currently
# only those two containers can be omitted here.
# Note that these containers can also be omitted globally in the 
# ~/.ddev/global_config.yaml or with the "ddev config global" command.


# provider: default # Currently either "default" or "pantheon"
#
# Many ddev commands can be extended to run tasks after the ddev command is
# executed.
# See https://ddev.readthedocs.io/en/stable/users/extending-commands/ for more
# information on the commands that can be extended and the tasks you can define
# for them. Example:
```

 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?
Nothing has been added or changed in .ddev by me.

**Additional context**
Add any other context about the problem here. Thanks!
Laptop has two disks, both fully encrypted LVM, with firewall, LXC containers and lando (only use of docker). /var/lib/docker is in its own partition. My uid is not 1001 not 1000. 
Testing done here was after a re boot and turning off firewall then restart networking and docker.

I reported a similar problem with docker4drupal that is unresolved, https://github.com/wodby/docker4drupal/issues/244. That makes me wonder what ddev has in common with docker4drupal that is different from lando.

I used [https://mariadb.com/kb/en/library/installing-and-using-mariadb-via-docker/ these instructions], for my sanity, to check that I can bring up a mariadb container. I just did the `docker run ...` and then `docker exec ...` into the container and proved to myself that I could access the db server. That all worked just fine. 

rfay spun up a Debian 9 system with encryption and ddev worked.

rfay was thinking the problem has to do with disks and how things are mounted, that is in my words.

**Comment by quietone1** [comment]
For a test I unmounted /var/lib/docker (a partition on HDD) so that a new dir would be created on the SSD. Then went to the project 'junk' directory and started the project.
```
$ ddev start
Network ddev_default created 
Starting junk... 
Creating volume "ddev-ssh-agent_dot_ssh" with default driver 
Creating volume "ddev-ssh-agent_socket_dir" with default driver 
Pulling ddev-ssh-agent (drud/ddev-ssh-agent:v1.5.2)... 
Creating ddev-ssh-agent ... done
 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
Running Command  Command=ip address show dev docker0
Creating volume "junk-mariadb" with default driver 
Creating volume "ddev-composer-cache" with default driver 
Pulling db (drud/ddev-dbserver:v1.5.2-10.2)... 
Pulling web (drud/ddev-webserver:v1.5.2)... 
Pulling dba (drud/phpmyadmin:v1.5.2)... 
Creating ddev-junk-db ... done
Creating ddev-junk-dba ... done
Creating ddev-junk-web ... done
 
Creating volume "ddev-router-cert-cache" with default driver 
Pulling ddev-router (drud/ddev-router:v1.5.2)... 
Creating ddev-router ... done
 
Successfully started junk 
Project can be reached at http://junk.ddev.local, https://junk.ddev.local, http://127.0.0.1:32771 
```
But just this one project and /var/lib/docker uses 3.7G out of the 9.2G available in /var. That is why I made a much larger separate partition for /var/lib/docker.

Not sure how I want to solve this and it is too late in the day now anyway. I do want to know more about how ddev uses /var/lib/docker.

**Comment by rfay** [comment]
Good thinking, thanks for the excellent work on this!

Full log of the mariadb startup failure is at [gist](https://gist.github.com/quietone1/cf22c4b0157c231eb7c5306db7891d6d)

It sounds like you're really onto it now. My bet is that docker4drupal might well work with your new filesystem setup also. However, as I remember docker4drupal uses the library/mariadb container, which is debian, and for some odd reason debian containers have trouble bind-mounting mariadb. There's a long and sordid history there that nobody seems to quite understand. (It's actually the reason that our mariadb container is based on alpine instead of debian).

**Comment by rfay** [comment]
Oh I forgot about your question:
> I do want to know more about how ddev uses /var/lib/docker.

So ddev doesn't even know that there *is* a /var/lib/docker, in fact in many environments it runs in there is not one. ddev is a wrapper on docker and docker-composer, it does no manipulation of anything directly.

ddev does these things:
* bind-mount the project directory from the host into the container. (A bind-mount is basically a direct filesystem mount on linux). You don't seem to be having any trouble with that.
* Use containers, obviously
* Use docker volumes, which are implemented as special (linux) filesystems inside docker's world, which most likely means their physical expression is in /var/lib/docker in your case on Debian.  Docker volumes in my experience behave like normal ext4 filesystems and have been very, very resilient on multiple operating systems compared to bind-mounts.  The mariadb /var/lib/mysql is a mounted docker volume. It gets mounted in the docker-compose.yaml like this:
```
    volumes:
      - type: "volume"
        source: mariadb-database
        target: "/var/lib/mysql"
        volume:
          nocopy: true
```

And the volume description is like this:
```
volumes:
  mariadb-database:
    name: "${DDEV_SITENAME}-mariadb"
```

**Comment by quietone1** [comment]
rfay, Thanks for the explanations. I've only have time to skim them now but I noticed

> Docker volumes in my experience behave like normal ext4 filesystems

My /var/lib/docker is ext2. That should not matter but maybe it does?

**Comment by rfay** [comment]
I also wouldn't expect it to matter, but would be fascinating if it did. I assume when you got it to work /var/lib/docker was on the root filesystem right?  What is the type of the root filesystem?

I thought ext2 was dusty old stuff, but I don't keep up with filesystems much.

The root filesystem (only filesystem) on the default Debian machines I brought up was ext4.

**Comment by rfay** [comment]
Fascinating. Do you have any spare disk you could provision to create an ext4 to test it against?

I see in https://www.thegeekstuff.com/2011/05/ext2-ext3-ext4/ that ext2 is in fact very, very old. 

ext3 became the default filesystem in debian like in 2000, https://wiki.debian.org/Ext3 - ext4 became the default in Jessie in 2015. So ext2 is not going to have much testing on it.

I'd recommend that you just reformat that partition as ext4. I don't think it can do any harm can it? It only had /var/lib/docker on it?

**Comment by rfay** [comment]
I spun up a Debian VM with /var/lib/docker on ext2. I get the same exact failure that you had, so this is a docker issue that is really never going to be solved, because it's in nobody's interest for them to support a filesystem that has been out of vogue for 20 years. I'm going to close this, but think you'll be just fine if you:

* uninstall docker
* reformat your /var/lib/docker as ext4
* install docker

Thanks for persevering on this! And hope you can now get ddev working.

**Comment by quietone1** [comment]
@rfay, Thanks for all your help.
I finally got around to running tune2fs on /var/lib/docker and after doing ddev started without errors.

**Comment by rfay** [comment]
So you used tune2fs to convert to an ext3 filesystem? 

Thanks for the report back!
