### ISSUE TITLE
Portainer - GUI for Docker management

### ISSUE THREAD

**Issue by alesrebec** [drud/ddev#1412]
Any love to get Portainer https://hub.docker.com/r/portainer/portainer/ in ddev?

I'm running multiple projects with ddev simultaneously and I started missing out portainer which I have been using before.
It's very useful if you want to have a great overview on all containers and networks and it's easier to manage them from one place.

Screenshot (from the web):

![portainer-dashboard](https://user-images.githubusercontent.com/426177/51992818-fd5a3380-24ad-11e9-9f72-b0ff22fbe173.png)

![portainer-remove-containers-via-gui](https://user-images.githubusercontent.com/426177/51992825-00552400-24ae-11e9-82ad-9b6d29a93527.png)

**Comment by rfay** [comment]
I gave a quick try on both macOS and Linux and it failed to be able to manage on the "local" tab:

<img width="762" alt="ubuntu_16_04_gui" src="https://user-images.githubusercontent.com/112444/52019102-fa5d4400-24a9-11e9-8392-5b89a6f67cff.png">

So unfortunately I remain unfamiliar with portainer. But could you say a bit about what you'd like to be able to see and do? We don't actually *like* to expose the containers to people, hoping that most people can see a project as a project and not as separate containers, but we do know that many people will see it as containers. 

Anyway, if there's a path forward to experiment with it, and if you could say more about what you'd like to see, that would be great.

**Comment by alesrebec** [comment]
Install should be pretty straightforward on Linux.
https://www.portainer.io/installation/

```
$ docker volume create portainer_data
$ docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer
```
If you followed those steps, you should be able to Connect to "Local" on http://localhost:9000

Worked for me the first time I tried, seeing this:

![screenshot from 2019-01-31 09-52-11](https://user-images.githubusercontent.com/426177/52042656-01359680-253e-11e9-9541-ff6c59684b65.png)

**What is it good for?**

It depends on the nature of your work and what you want to know.
It helps me with a good graphical representation of all running containers, storage being used for all/each, managing to stop selected ones because I run multiple simultaneously and I don't want to reach SWAP.
Even though you see them as containers, not projects, you can easily search by their name, for example "projectx" and just use select all checkbox to stop, kill, restart, etc.. them. Treating them as projects.

You also get to see the graphical stats of the running containers:

![screenshot from 2019-01-31 10-01-32](https://user-images.githubusercontent.com/426177/52043183-4dcda180-253f-11e9-9dd3-bb2f00601e06.png)

Or view logs, open CMD witch Quick Actions on specific container...

![screenshot from 2019-01-31 10-03-06](https://user-images.githubusercontent.com/426177/52043261-88373e80-253f-11e9-9a68-de0210af4abe.png)

![screenshot from 2019-01-31 10-03-44](https://user-images.githubusercontent.com/426177/52043283-96855a80-253f-11e9-8dae-fdf5c5d72edd.png)

**Comment by alesrebec** [comment]
I also have Ubuntu (18.04) and used "local" as you.
After clicking on "Connect" button I was in.
Just make sure you run the container with the docker.sock flags (in red on your screenshot).

P.S. Just tried again on a different machine running Ubuntu.
```
docker volume create portainer_data
docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer
```
Visiting localhost:9000, entering admin password twice register, selecting Local, clicking connect, I'm in.

**Comment by alesrebec** [comment]
```
$ ddev version
bgsync        	drud/ddev-bgsync:v1.5.2       
cli           	v1.5.2                        
commit        	v1.5.2                        
db            	drud/ddev-dbserver:v1.5.2-10.2
dba           	drud/phpmyadmin:v1.5.2        
ddev-ssh-agent	drud/ddev-ssh-agent:v1.5.2    
docker        	18.09.0                       
docker-compose	1.21.2                        
domain        	ddev.local                    
router        	drud/ddev-router:v1.5.2       
web           	drud/ddev-webserver:v1.5.2   
```

**Comment by alesrebec** [comment]
Happy to hear you found the button ;)

Well there are two ways we could approach this.

1.) Suggest people in the documentation there's this GUI called Portainer, put some screenshot and that's it.

2.) Give people an option to install it. Present it either when you are installing ddev, configuring a project or have a separate command for "add-ons" or "additional services", which I noticed in ddev that could be living under a specific command ready to install them.

**Comment by alesrebec** [comment]
If it conflicts with your Xdebug that runs on port 9000 by default just map it with a different port when running (for example 9001:9000).

```
docker volume create portainer_data
docker run -d -p **9001**:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer
```

Portainer will be accessible on http://localhost:9001

**Comment by alesrebec** [comment]
I found it easier if I move it to a docker-compose.yml file which auto-runs always on restart:

```
version: '3'
services:
    portainer:
        ports:
            - '9001:9000'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - 'portainer_data:/data'
        image: portainer/portainer
        restart: always

volumes:
    portainer_data:
```

Accessible on http://localhost:9001 so it doesn't interfere with Xdebug.

**Comment by rfay** [comment]
Portainer is a great tool, and highly recommended. However, I don't think it adds direct value for ddev. Mostly ddev users don't have to be aware of the various containers, and don't have to have docker knowledge. Closing, happy to continue the conversation.
