### ISSUE TITLE
Fix import-files for project type php (or correct message and documentation) 

### ISSUE THREAD

**Issue by RobertLang** [drud/ddev#1416]
**Describe the bug**
When I try to use `ddev import-files` in a project with type **_php_** nothing is extracted and a success message is printed.

**To Reproduce**
1. Create a new project with type PHP
```
ddev config --create-docroot --project-type php --upload-dir project/media --docroot project
```
2. Copy archive file to project (e.g. media.zip)
3. Try to import files
```
ddev import-files --src=media.zip
```
Prints out message: Successfully imported files for bug 
4. No files have been extracted

**Expected behavior**
I would expect the contents of the archive to be extracted to the configured directory. Or if the method is not supported in php, that an error message is shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/6792844/52043172-473f2a00-253f-11e9-8b9b-be600b6929a3.png)
![image](https://user-images.githubusercontent.com/6792844/52043230-73f34180-253f-11e9-8972-b16c923a4a69.png)

**Version and configuration information (please complete the following information):**
 - macOS Mojave 10.14.3
 - Docker version 18.09.1 ( Git commit: 4c52b90, Built:  Wed Jan  9 19:41:49 2019)
 - ddev version v1.5.2
 - config.yaml
```
APIVersion: v1.5.2
name: bug
type: php
docroot: project
php_version: "7.1"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
webcache_enabled: false
provider: default
upload_dir: project/media
```

**Comment by rfay** [comment]
Thanks for following this up. #1420 should fix that.
