### ISSUE TITLE
ddev only creates settings.ddev.php on `ddev config`

### ISSUE THREAD

**Issue by markdorison** [drud/ddev#1423]
**Describe the bug**
ddev only creates `settings.ddev.php` when `ddev config` is run (https://github.com/drud/ddev/issues/692) and adds it to `.gitignore`, but when multiple developers are collaborating on a repository, the settings file is not present as expected.

**To Reproduce**
1. Clone repo.
1. Run `ddev config`
1. Commit ddev configuration to repository.
1. Push repo.
1. Have a collaborator clone the repository.
1. Collaborator runs `ddev start`.
1. Collaborator attempts to run `drush site-install`, but since `settings.ddev.php` does not exist, this fails.

**Expected behavior**
Since `settings.ddev.php` is ignored by git by default, I would expect it to be regenerated on `ddev start` if it does not exist.

An alternative could be to remove `settings.ddev.php` from `.gitignore` and commit it to the repository. Is that what is recommended in this scenario?

**Version and configuration information (please complete the following information):**
 - macOS Mojave 10.14.2
 - Docker version 18.09.1
 - ddev v1.5.2

**Comment by rfay** [comment]
Hmm, we always expected everybody to do the `ddev config` step. 

You absolutely have the option of removing #ddev-generated from the settings.ddev.php and committing it. Is that the appropriate solution?

**Comment by markdorison** [comment]
@rfay I _think_ that would work for our scenario. Maybe this is a documentation TODO for using ddev with collaborators on a repository?

Running `ddev config` seemed strange to us in this situation especially as it could result in a modified `.ddev/config.yaml` if for instance, the new collaborator's `ddev` version differed slightly from what was most recently committed to the repo.

**Comment by rfay** [comment]
Another thing you can do is use project type 'php' and then settings are just your responsibility; ddev won't try to mess with them.

**Comment by rfay** [comment]
Closed by accident, this still have valuable conversation.

**Comment by mglaman** [comment]
Agreed: https://twitter.com/nmdmatt/status/1091735366418292737

```
Need to open an issue: generate CMS settings without needing to run config. Or ddev config -y to reuse existing config
```

**Comment by alex1yaremchuk** [comment]
My question is related to the change implemented in this issue. 

on restart ddev changes settings.php including settings.ddev.php

Pantheon suggests another scheme for including custom local changes: file settings.local.php which is already included in settings.php 

it would be cleaner approach if I could make ddev not to put include into settings.php but have it from settings.local.php (I can put it there manually).

**Comment by rfay** [comment]
DDEV used `settings.local.php` in its early days, but that conflicted with the "normal" use of `settings.local.php` which can *also* be used with DDEV, if you set the settings.php to use it. That's why DDEV uses its own settings file these days. People can *also* use a settings.local.php as it's often used on a deployment, to override configuration specified in the settings.php, but without checking in the file. (Note that `settings.ddev.php` really shouldn't ever be edited or committed, it's intended to be managed by DDEV.)
