### ISSUE TITLE
 docker-compose requirements: 1.24.0-rc1 is less than 1.21.0

### ISSUE THREAD

**Issue by mglaman** [drud/ddev#1431]
**Describe the bug**
Parsing of the Docker Composer version is wrong.

**To Reproduce**
Update to Docker  Desktop for Mac 2.0.2.0 edge
```
~/project(master) » ddev start                                                                                                                               
The docker-compose version currently installed does not meet ddev's requirements: 1.24.0-rc1 is less than 1.21.0 
```

**Expected behavior**
1.24.0-rc1 is > 1.21.0

**Version and configuration information (please complete the following information):**
bgsync        	drud/ddev-bgsync:v1.5.2       
cli           	v1.5.2                        
commit        	v1.5.2                        
db            	drud/ddev-dbserver:v1.5.2-10.2
dba           	drud/phpmyadmin:v1.5.2        
ddev-ssh-agent	drud/ddev-ssh-agent:v1.5.2    
docker        	18.09.1                       
docker-compose	1.24.0-rc1                    
domain        	ddev.local                    
router        	drud/ddev-router:v1.5.2       
web           	drud/ddev-webserver:v1.5.2     

**Additional context**
Add any other context about the problem here. Thanks!

**Comment by rfay** [comment]
Thanks, somebody else pointed that out today, and we've actually seen it sometime in the past. Will try to get it sorted.

**Comment by rfay** [comment]
Sadly, this is https://github.com/drud/ddev/pull/738 reappearing from the past. It seems that I learned the lesson back then and then lost track of it somewhere.

**Comment by rfay** [comment]
For testing, to save away all images (but not volumes) before switching between edge and stable: `docker save $(docker images -q) -o ~/tmp/docker_images.20190206.tar` and then `docker load -i ~/tmp/docker_images.20190206.tar`

**Comment by mglaman** [comment]
👍thanks @rfay

**Comment by Jerrik** [comment]
How can I get these changes with Homebrew?

**Comment by rfay** [comment]
@Jerrik you have to wait until next week for homebrew. However, you can download the macOS assets from https://circleci.com/gh/drud/ddev/9829#artifacts/containers/0 and just put the mac binary in your path before /usr/local/bin (So for example, put the mac binary in ~/bin/ddev and make sure that ~/bin is in your PATH before /usr/local/bin.

**Comment by Jerrik** [comment]
Thanks @rfay

**Comment by aguerrerowk** [comment]
is there any way to setup the docker compose version to work?

**Comment by rfay** [comment]
@aguerrerowk People all over the world are using docker-compose successfully. If you need the current version (on Linux I assume) You have to download it or use Linuxbrew to install it, see https://ddev.readthedocs.io/en/stable/users/docker_installation/#linux-installation-docker-ce

Otherwise, please give more detail on the issue you're facing.

**Comment by aguerrerowk** [comment]
@rfay  i want to work with the 2.2 version on my dockerfile but i cannot do it because the version assignation is automatic 
![image](https://user-images.githubusercontent.com/58917057/75801345-fc4aa400-5d48-11ea-897c-ebe05941a47c.png)

**Comment by rfay** [comment]
Could you say more about the problem you're having? The docker compose version (like 1.24) is not related to the yaml version (like 3.6) and neither is related to a dockerfile version or docker version. Current latest docker compose is 1.26.0-rc2
