### ISSUE TITLE
ddev start fails due to docker-compose version compare (docker edge channel - 18.09.1)

### ISSUE THREAD

**Issue by rasgor** [drud/ddev#1432]
**Describe the bug**
ddev start fails due to docker-compose version comparison with message
```The docker-compose version currently installed does not meet ddev's requirements: 1.24.0-rc1 is less than 1.21.0```

**To Reproduce**
1. Install latest docker version 18.09.1 (edge channel) 
2. ddev start

**Expected behavior**
Valid version compare even if docker-compose version is tagged with additional info (e.g. -rc1)

**Comment by rfay** [comment]
Duplicate of https://github.com/drud/ddev/issues/1431, but thanks for the report!
