### ISSUE TITLE
Forwarding SSH Agent from local machine

### ISSUE THREAD

**Issue by fiasco** [drud/ddev#1437]
I'm using Acquia's BLT tool which has the ability to restore my local database from an Acquia environment. In order to do this, I need to ssh from the webserver via drush to do a sql-sync. However, in order to do this, my ssh session into the webserver needs to carry my ssh agent from my host shell.

Is there a way to do `ddev ssh -A` like you would `ssh -A` to forward your ssh agent?

**Comment by fiasco** [comment]
> If you want to use your personal ssh keys within the web container, that's possible. Use ddev auth ssh to add the keys from your ~/.ssh directory and provide a passphrase, and then those keys will be usable from within the web container. You generally only have to ddev auth ssh one time per computer reboot.

Ok - I ought to RTFM. Sorry - https://ddev.readthedocs.io/en/stable/users/cli-usage/#ssh-into-containers

**Comment by rfay** [comment]
`ddev auth ssh` is actually what it sounds like you want. Give that a try.
