### ISSUE TITLE
deb.sury.org (was) ending support/distribution of PHP 5.6/7.0 in April 2019

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1448]
**Describe the bug**

Please see https://www.patreon.com/posts/ubuntu-14-04-php-22093917 - 

Sury is ending 5.6 and 7.0, so we either have to drop them or find a way to provide them without him (like downloading and stashing the .deb's?) 

Of course they have no support from anybody already as both are EOL.

This means that to support those (which we should) we need to figure out a way to stash the .deb's or learn how to build, or something.

**Comment by rfay** [comment]
Opened issue with Sury (for us to build) [oerdnj/deb.sury.org#1092](https://github.com/oerdnj/deb.sury.org/issues/1092)

**Comment by rfay** [comment]
Pinged deb.sury.org on twitter and pinged oerdnj/deb.sury.org#1092

**Comment by rfay** [comment]
https://askubuntu.com/a/15214 demonstrates how to download all the (existing and currently used) packages as .deb packages. 

So, in a debian container or on a debian machine,

`sudo apt-get update && sudo apt-get remove php5.6* php7.0*`
`for v in php5.6 php7.0; do sudo apt-get  install --download-only --no-install-recommends --no-install-suggests -y $v-apcu $v-bcmath $v-bz2 $v-curl $v-cgi $v-cli $v-common $v-fpm $v-gd $v-intl $v-json $v-mysql $v-mbstring $v-memcached $v-opcache $v-redis $v-soap $v-sqlite3 $v-readline $v-xdebug $v-xml $v-xmlrpc $v-zip $v-mcrypt libapache2-mod-$v ; done`

And the files are in /var/cache/apt/archives where they can be copied out.

**Comment by brianrinaldi** [comment]
Site list with php versions up in google sheets, shared with dstoline.

**Comment by rfay** [comment]
@brianrinaldi you probably meant to post that in the hosting issue related to this?

**Comment by rfay** [comment]
Also note the solution in #1485, which would work for hosting as well. It would sure be great to just not run unsupported php though.

**Comment by rfay** [comment]
Sure has relented and for now will keep PHP 5.6 and 7.0 in his repository. https://www.patreon.com/posts/php-5-6-and-php-25226448?utm_medium=social&utm_source=twitter&utm_campaign=postshare

**Comment by rfay** [comment]
The approach in the PR worked and can be redone later. Hibernating this for now.

**Comment by rfay** [comment]
Closing this until it comes up again. I think the technique here in #1485 will work when we need it.
