### ISSUE TITLE
NFS mount failed

### ISSUE THREAD

**Issue by SvenLie** [drud/ddev#1449]
When i start ddev on Windows 10 Pro with enabled NFS mount it fail.

> ERROR: for d77ed1aace86_ddev-blablabla-web  Cannot start service web: error while mounting volume '/var/lib/docker/volumes/ddev-svenlieberthp_nfsmount/_data': error while mounting volume with options: type='nfs' device=':/PATHTOROOT' o='addr=host.docker.internal,hard,nolock,rw': connection refused

> ERROR: for web  Cannot start service web: error while mounting volume '/var/lib/docker/volumes/ddev-blablabla_nfsmount/_data': error while mounting volume with options: type='nfs' device=':/PATHTOROOT' o='addr=host.docker.internal,hard,nolock,rw': connection refused
Encountered errors while bringing up the project.'

**Comment by SvenLie** [comment]
I had to install windows_ddev_nfs_setup.sh altough i installed ddev trough the installer.

https://ddev.readthedocs.io/en/latest/users/performance/#using-nfs-to-mount-the-project-into-the-container

**Comment by rfay** [comment]
Thanks, sorry you had trouble with this. Although it would be technically possible to install and configure NFS for you in the installer, it would seem to be a violation of your ownership of your machine. It also would break anybody that had NFS running for any other reason. This might possibly be less likely on Windows, which doesn't have built-in NFS, but could be a real problem on macOS and Linux, where NFS is taken for granted.
