### ISSUE TITLE
Accept https callbacks with valid (not self-signed) certificate

### ISSUE THREAD

**Issue by JeffVeit** [drud/ddev#1450]
It's not unusual for a project to interact with other systems, and good practice requires data to be sent over https. Ddev uses its own certificate in when responding to https callbacks from external systems, and this certificate is often not acceptable to services sending data, which makes it difficult to use ddev to develop when external systems are involved.

_Notes_

- ddev uses the same certificate for all sites. In fact the router software jwilder/nginx-proxy has the ability to use the correct certificate. I think the nginx template file would need alteration to more closely match the jwilder version. https://github.com/jwilder/nginx-proxy/blob/master/README.md#ssl-support
-  jwilder/nginx-proxy has an associated container which works with LetsEncrypt. This requires port 80, so it won't work with projects that use other ports. https://github.com/jwilder/nginx-proxy/blob/master/README.md#ssl-support-using-letsencrypt 

_Workarounds_
- As a hacked workaround, you can set up a non-ddev Nginx reverse proxy outside of ddev with the correct certificate. This terminates the https request, and passes the request into ddev. It's clutzy as a solution because the whole project is no longer in ddev. If you want to use LetsEncrypt, you'll need to set this up on port 80. You will need to switch your ddev containers off port 80. This workaround requires port 80 to be reachable from the internet, and of course having a domain correctly set up.
- An alternative workaround is to tunnel from a computer on the internet, through to your dev machine. See rfay's article here - https://randyfay.com/content/tunneling-http-debug-or-develop-external-webservice-call . This will not work if the external service does not accept the ddev self-signed certificate.

**Comment by rfay** [comment]
Hmm, #1540 is going to give us *trusted* certs (trusted by the host, trusted inside the container) but is not a "valid" cert. You can actually get your certificate revoked for using it on a non-internet IP, as I understand, right? 

I think ngrok might satisfy the need here (as in https://github.com/drud/ddev/issues/375), maybe we should push forward on that one? Would love to hear from you @JeffVeit

**Comment by rfay** [comment]
IMO the combination of trusted mkcert certs and `ddev share` solve this problem. Happy to continue the conversation here @JeffVeit if you have any concerns or don't think that has done the job.
