### ISSUE TITLE
windows_ddev_nfs_setup.sh issue with spaces in path name

### ISSUE THREAD

**Issue by kristoftorfs** [drud/ddev#1452]
**Describe the bug**
If the Windows username has a space in it, the nfsd service will not be able to start due to the `pathFile` argument not being escaped properly.

**To Reproduce**
1. Run `windows_ddev_nfs_setup.sh`
2. You get the error "nfsd: Unexpected status SERVICE_PAUSED in response to START control".

**Expected behavior**
The nfsd service should start without issues.

**Screenshots**

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Windows 10
 - Docker version 2.0.2
 - ddev version 1.6.0

**Comment by rfay** [comment]
@kristoftorfs could you please test the script at https://raw.githubusercontent.com/drud/ddev/57f1dc61d2c0bd865e5f02335f534946f5d9dfd0/scripts/windows_ddev_nfs_setup.sh, in #1453 ?

Thanks for the report!

**Comment by kristoftorfs** [comment]
The actual issue is in this line:
```bash
sudo nssm install nfsd "${winnfsd}" -id ${DDEV_WINDOWS_UID} ${DDEV_WINDOWS_GID} -log off -pathFile "$HOME/.ddev/nfs_exports.txt"
```

I managed to solve this with
```bash
winpty sudo nssm install nfsd "${winnfsd}" -id ${DDEV_WINDOWS_UID} ${DDEV_WINDOWS_GID} -log off -pathFile "\"$HOME/.ddev/nfs_exports.txt\""
```

**Comment by rfay** [comment]
Hmm, in testing I had [line 43](https://github.com/drud/ddev/pull/1453/files#diff-34b8c3d2f6dc975a534bab4e9b675ad9L43) failing; However it looks like you're testing in a git-bash window, and I was testing in a cmder window. Did you really need winpty?

**Comment by kristoftorfs** [comment]
In git bash without winpty the path would be converted to `/c/Users/Kristof Torfs/.ddev/nfs_exports.txt` as soon as I added quotes. Perhaps another possibility (instead of writing console-specific code) is adding a note to the documentation informing the user that he would need to edit the service and add the quotes manually in cases like this.

**Comment by rfay** [comment]
@kristoftorfs thanks so much for hanging in there on this. It's way too painful! I have another version out there that should work in most git-for-windows environments. Please test https://github.com/drud/ddev/blob/e0fdc174813b2c5e0ef5aa8267ef6a9a022ce547/scripts/windows_ddev_nfs_setup.sh [raw](https://github.com/drud/ddev/raw/e0fdc174813b2c5e0ef5aa8267ef6a9a022ce547/scripts/windows_ddev_nfs_setup.sh)

Reporting results in #1453 would be slightly easier for me, but whatever is easiest for you. Thanks so much!
