### ISSUE TITLE
Config mariadb_version not working with ddev 1.6.0

### ISSUE THREAD

**Issue by codemonkey1988** [drud/ddev#1455]
**Describe the bug**
Since ddev 1.6.0, the configuration value `mariadb_version` does not have any effect.
When you change it to 10.1, ddev will use `drud/ddev-dbserver:v1.6.0-10.2` as the database image. The only way is to set the database image `dbimage: drud/ddev-dbserver:v1.6.0-10.1`

**To Reproduce**
1. MAke sure you're running ddev 1.6.0
2. Create a new project and run `ddev config`
3. Edit the config.yaml and change `mariadb_version` to 10.1
4. Run `ddev start`
5. Check your containers - it will start with 10.2 image

**Expected behavior**
The project should run the database container with `drud/ddev-dbserver:v1.6.0-10.1` when `mariadb_version` is set to 10.1.

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: MacOS 10.14.3
 - Docker version information: 10.09.1
 - ddev version information: 1.6.0
 - config.yaml contents for the misbehaving project
```
APIVersion: v1.6.0
name: my-project
type: typo3
docroot: public
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.1"
webcache_enabled: false
provider: default
```

**Comment by rfay** [comment]
Thanks for this. Sorry for the regression.

**Comment by stucki** [comment]
I can confirm this.

**Comment by freshworkx** [comment]
I can confirm this. Tested with TYPO3 version 7.6, display a warning in system environment check:
"Your MariaDB version 10.2.19-MariaDB-log is too new. TYPO3 CMS does not run with this version."
