### ISSUE TITLE
Global setting for omit_containers applied in every project config

### ISSUE THREAD

**Issue by codemonkey1988** [drud/ddev#1456]
**Describe the bug**
When you disable the dba container globaly by running `ddev config global --omit-containers=dba` this configuration got written to every projects config.yaml after running `ddev config`. This might be a missbehaviour. In my case, I want to disable it for all projects, but my team members might need this container. 

**To Reproduce**
1. Run `ddev config global --omit-containers=dba`
2. Run `ddev config` in some folder
3. Check the _.ddev/config.yaml_ file - There will be a `omit_containers` config with dba item

**Expected behavior**
When disabling containers globaly, it should not be written to a project config.yaml when running `ddev config`.

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: MacOS 10.14.3
- Docker version information: 10.09.1
- ddev version information: 1.6.0

**Comment by rfay** [comment]
Thanks for the report, you're certainly right. I'd be interested in how you stumbled on it.

**Comment by codemonkey1988** [comment]
I'm working in a small team and everyone is using ddev for development. Therefore we add the ddev config also to our git, so that everyone can use it (and the configured hooks). So when I'm running `ddev config`, I always check what changed in the file before commiting it. There I realized, that this config was added. Currently I'm removing this config by hand before commiting the file.
Because other team members should not be affected by my decision to use sequel pro only.

**Comment by rfay** [comment]
That helps, thanks so much! It's obviously a bug, but I wouldn't have understood this exact impact.

**Comment by WarpedOne** [comment]
In a group environment sharing DDEV configs, this could be a problem. On an individual workflow, this is probably working the way it should. To solve the group problem, maybe adding a global config of project/global/propagate would help.

Proposed solution:
A) No global omit_containers parameter:
  1) No project omit_containers parameter-All containers started
  2) Project omit_containers parameter: Specified containers not started
B) Global omit_containers parameter specified
  1) No new config_priority parameter: Project level priority
    a) No project omit_containers: All containers started, use `ddev config` to propagate settings.
    b) Project omit_containers: Project level containers specified not started.
  2) Global config_priority parameter specified:
    a) Project priority-`ddev config` does NOT set project omit_containers-must update manually
      1) No project omit_containers parameter-All containers started
      2) Project omit_containers parameter: Specified containers not started
    b) Global priority-`ddev config` does NOT set project omit_containers-must update manually
      1) No project omit_containers parameter-Use global omit_containers parameter
      2) Project omit_containers parameter specified-Ignore & use global omit_containers parameter
    c) Propagate-Defaults to B.1 specified above-Project priority-`ddev config` propagates setting
