### ISSUE TITLE
Failed to purge the temporary install directory

### ISSUE THREAD

**Issue by amitaibu** [drud/ddev#1457]
**Describe the bug**
I'm getting an error when running `ddev composer create drupal-composer/drupal-project:8.x-dev --stability dev --no-interaction`

**Additional context**
https://stackoverflow.com/questions/54693417/failed-to-purge-the-temporary-install-directory

**Non related stuff**
@rfay happy to see you back in my Drupal related life 😸

**Comment by rfay** [comment]
So great to see you too. Sorry for this regression. Odd that it happened, odd that the test doesn't catch it.

**Comment by rfay** [comment]
Thanks so much for the report, @amitaibu , #1486 should fix this up. Turns out it was only a warning anyway, but it's always cool when you can fix a bug by removing code!
