### ISSUE TITLE
Improve WordPress quickstart docs

### ISSUE THREAD

**Issue by DanielRuf** [drud/ddev#1458]
https://ddev.readthedocs.io/en/latest/users/cli-usage/#wordpress-quickstart

The clone commands seem to be wrong.

**Comment by rfay** [comment]
The URL is just an example if that's what you mean. The assumption is that you have a WordPress site somewhere in git and you're going to clone it and work on it. Suggestions about what you'd like to see or what would be more familiar are very welcome.

**Comment by DanielRuf** [comment]
Sure but as a first time user I would like to see a first working example (isn't drud/wordpress an example?) and a step for step documentation.

I miss some things from setup to first working project.

**Comment by DanielRuf** [comment]
The start from the link in the repo:
https://ddev.readthedocs.io/en/stable/

**Comment by DanielRuf** [comment]
After clicking next:

https://ddev.readthedocs.io/en/stable/users/cli-usage/

Then Quickstart Guides but these are not really quickstart guides.

Only Getting Started provides some steps to run ddev with a demo setup.

The others say "clone the project and run ddev". But no introduction to how ddev works, how a demo setup can look like, including template .ddev files and how we get from there to our project.

Because what if needed parts are missing in projects (composer.json / non-composer based setups but we want to see what ddev can automate and ease.

**Comment by DanielRuf** [comment]
I miss some hint to https://github.com/drud/wordpress and the others and this one also fails on my Windows 10 machine with an nginx error duting creation.

The "demo" part is somehow not there for beginners to see how fast we get from repo to live website ;-)

**Comment by rfay** [comment]
Thanks, I think it would be reasonable. And PRs are welcome (and easy). We'd love to see how you'd do it as a WP dev. https://github.com/drud/ddev/blob/master/docs/users/cli-usage.md

**Comment by rfay** [comment]
The docs have been updated to prefer a composer installation technique using wordpress/skeleton, see https://ddev.readthedocs.io/en/stable/users/cli-usage/#wordpress-quickstart - We're sure open to other improvements, always listening. Thanks!
