### ISSUE TITLE
As a user, I want ImageMagick to include the webp delegate to encode and decode images from and to webp

### ISSUE THREAD

**Issue by PascaleBeier** [drud/ddev#1460]
**Is your feature request related to a problem? Please describe.**
As a user, I want ImageMagick to include the webp delegate to encode and decode images from and to webp.

**Describe the solution you'd like**
It would be optimal to include the webp delegate in the provided ImageMagick app.

**Describe alternatives you've considered**
A user could recompile / add the webp delegate manually.

**Comment by rfay** [comment]
Do you have installation instructions? Please say how we'd validate that it is working the way you want.

**Comment by rfay** [comment]
No response from OP. I'll close this until we get a response, happy to reopen it then.

**Comment by moe2k** [comment]
You should be able to install the delegate using 
`sudo apt-get install webp
`

Then you can verify if it works correctly by checking if the output of
`convert -list delegate | grep webp`
 contains webp.

Additionally you can test a conversion from jpg to webp using 
`convert source.jpg target.webp` and verify the target image's format is webp.

**Comment by rfay** [comment]
On ddev v1.9+ you would just use
`webimage_extra_packages: [webp]`

in your config.yaml. Anybody that needs webp (or cwebp) can do this.

**Comment by moe2k** [comment]
Thank you, that works like a charm!
