### ISSUE TITLE
docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/busybox/manifests/latest: unauthorized: incorrect username or password

### ISSUE THREAD

**Issue by MrPaulDriver** [drud/ddev#1461]
I am following the video at https://www.drud.com/ddev-local/ddev-local-nfs-mounting-setup-macos/ but I am unable to run the install script. I have granted iTerm full disk access and have Docker running.

Terminal output copied below. What I am doing wrong? 

Pauls-MBP:Downloads paul$ chmod +x macos_ddev_nfs_setup.sh
Pauls-MBP:Downloads paul$ ./macos_ddev_nfs_setup.sh
Unable to find image 'busybox:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/busybox/manifests/latest: unauthorized: incorrect username or password.
See 'docker run --help'.
Docker does not seem to be running or functional, please check it for problems
Pauls-MBP:Downloads paul$

**Comment by rfay** [comment]
This is almost always fixed with `docker logout`. I'm not sure how it happens.  It's a docker problem only.

**Comment by MrPaulDriver** [comment]
Thank you. `docker logout` worked.

**Comment by rfay** [comment]
Thanks! I don't know what they do that gets it messed up. None of our images require login, but somehow either docker gets confused or there's somehow an invalid login, and then people get this.
