### ISSUE TITLE
docker version issue: "18.6.0-ce is less than 18.06.1-alpha1 "

### ISSUE THREAD

**Issue by btopro** [drud/ddev#1463]
In the latest version of ddev running on OSX 10.11.6 it gives the following error message now:
```
The docker version currently installed does not meet ddev's requirements: 18.6.0-ce is less than 18.06.1-alpha1 
```

Is there a way to downgrade or suggest to people the way to downgrade ddev if they get into this situation?

**Comment by rfay** [comment]
Hi @btopro , it looks like you're still on docker 18.06.0, and the minimum requirement is 18.06.1? Could you upgrade your docker and see how it goes? Current docker is 18.09.2, shortly they'll come out with 19.03. I assume you're on ddev v1.6.0, and it does require docker 18.06.1+, let me know if I'm misunderstanding. (We changed the minimum requirement from 18.06.1 to 18.06.1-alpha1 in v1.6.0 because of a weird technical constraint with version constraints, but that shouldn't have affected you; if you're running docker 18.06.0, it should already not have worked with previous versions.

**Comment by btopro** [comment]
ya, docker is capped on older versions of OSX; is there a way to downgrade / install a specific version of ddev?

**Comment by btopro** [comment]
system requirements may need updated in docs section as it claims 18.06 and OS 10.11 (tho that doesn't appear to be the case now)
```
System Requirements
Docker version 18.06 or higher. Linux users make sure you upgrade docker-compose and do the post-install steps
docker-compose 1.21.0 and higher (bundled with Docker in Docker for Mac and Docker for Windows)
OS Support
macOS El Capitan and higher (macOS 10.11 and higher but it should run anywhere docker-ce runs)
Linux: Most Linux distributions which can run Docker-ce are fine. This includes at least Ubuntu 14.04+, Debian Jessie+, Fedora 25+. Make sure to follow the docker-ce post-install steps
Windows 10 Pro or Enterprise with Docker-for-windows
Windows 10 Home (or other Windows version) with Docker Toolbox
```

**Comment by rfay** [comment]
I did not know that they had changed that. I see they're saying 10.12 now in https://docs.docker.com/docker-for-mac/install/

Unfortunately, ddev isl completely limited to supporting what docker is willing to support.  

I assume this issue means you don't have a way to upgrade your mac?

It's easy to use older versions of ddev. Just download the version you want from releases. If you're using homebrew  `brew switch v1.5.2` gets you back to 1.5.2 if you installed that. If you didn't install it, the homebrew technique is slightly harder. But just download the one you want, untar it, and put it in /usr/local/bin.

**Comment by btopro** [comment]
yeah I was worried about that. Lost an hour trying. Now time to just upgrade, have my computer become a brick and then hopefully IT group restore it.

Thanks for up'ing the docs issue -- As a general rule of thumb a lot of regulated spaces (education, gov, med) have to ride several versions behind on OS versions.

I'll close this now that you've opened a doc specific issue to address this
