### ISSUE TITLE
How to best spring-clean old unused DDEV volumes

### ISSUE THREAD

**Issue by rpkoller** [drud/ddev#1465]
When I first started toying around with DDEV I was unaware of `ddev remove --remove-data`. I've just used `ddev remove`. That lead to a few relics. If I currently do a `ddev list` I only have a single site installed and listed (stopped at the moment): 

```
NAME      TYPE     LOCATION          URL(s)                       STATUS
ddevdemo  drupal8  ~/Sites/ddevdemo  http://ddevdemo.ddev.local   stopped
                                     https://ddevdemo.ddev.local  sync active

DDEV ROUTER STATUS: exited
The router is not yet healthy. Your projects may not be accessible.
If it doesn't become healthy try running 'ddev start' on a project to recreate it.
```
reflected in a `docker ps -a`:
```
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                       PORTS                                                                                      NAMES
6826498715e9        drud/ddev-ssh-agent:v1.6.0       "/entry.sh ssh-agent"    3 days ago          Exited (255) 3 minutes ago                                                                                              ddev-ssh-agent
c98a11382b9e        drud/ddev-webserver:v1.6.0       "/start.sh"              3 days ago          Exited (0) 3 days ago                                                                                                   ddev-ddevdemo-web
86b05f6826f7        drud/phpmyadmin:v1.6.0           "/run.sh phpmyadmin"     3 days ago          Exited (0) 3 days ago                                                                                                   ddev-ddevdemo-dba
67208da9b1c2        drud/ddev-dbserver:v1.6.0-10.2   "/docker-entrypoint.…"   3 days ago          Exited (0) 3 days ago                                                                                                   ddev-ddevdemo-db
8fc5fcb91595        drud/ddev-router:v1.6.0          "/app/docker-entrypo…"   3 days ago          Exited (255) 3 minutes ago   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:8025->8025/tcp, 0.0.0.0:8036->8036/tcp   ddev-router
57b6a08be246        drud/ddev-bgsync:v1.6.0          "bg-sync"                5 days ago          Up 3 minutes (healthy)
```
but when I do a `docker volume ls` I get a list of the available and registered volumes which consists not only of the ones related to the `ddevdemo` project but also of projects only removed with `ddev remove` and not `ddev remove --remove-data`:
```
DRIVER              VOLUME NAME
local               Craft-mariadb
local               ddev-composer-cache
local               ddev-ddevdemo_unisoncatalogvol
local               ddev-ddevdemo_webcachevol
local               ddev-ddevdrupal_unisoncatalogvol
local               ddev-ddevdrupal_webcachevol
local               ddev-gutenspeed_unisoncatalogvol
local               ddev-gutenspeed_webcachevol
local               ddev-router-cert-cache
local               ddev-ssh-agent_dot_ssh
local               ddev-ssh-agent_socket_dir
local               ddevdemo-mariadb
local               ddevdrupal-mariadb
local               gutenspeed-mariadb
local               myd8site-mariadb
```
What would be the cleanest way for a spring-clean and removing unused volumes? A `docker volume prune` would be the appropriate choice or even a `docker system prune` to eliminate even more unused data related to older projects? And in case one of the two would be the right choice would it be reasonable to create a ddev command alias for that like e.g.`ddev cleanup` or at least leave a remark in the documentation about it (I could write a rough draft for that).

**Comment by rfay** [comment]
`docker volume rm $(docker volume ls -q | grep mariadb)`
will kill off the mariadb volumes. 
If you want to kill the rest of any volumes created by ddev, `docker volume rm $(docker volume ls -q | grep ddev)`
Of course you'll want to `docker volume ls` before you do that. 

While spring cleaning, you may want to remove any site folders from ~/.ddev (databases used to be stored there). 

And if you have any containers showing that you don't want in `docker ps -a`, then `docker  stop $(docker ps -q) && docker rm -f $(docker ps -aq)`. Again, do a `docker ps -a` first so you make sure you know what you're aiming at.

**Comment by rpkoller** [comment]
@rfay also thanks for the tips in here! those helped to save a few gigabyte ;))

**Comment by rpkoller** [comment]
yep cool thanks noticed the `ddev delete images` command already in the merged pull request.

**Comment by blainelang** [comment]
I ran into issues today of not being able to restore a database. Kept getting MySQL ERROR 1114 (HY000) that tables were full. I had been using ddev import-db for to restore this site and database  successfully multiple times over the past few days. Database backup was nearly 700 Meg .sql file.

This is on a MAC and googling for answers clearly noted this was being caused by insufficient disk space but there was still 10GB free on my disk. 

@rfay pointed me at the size of the docker image but it was already at the max 64GB
Ran `docker system prune` (but it did not free up anything)

The command `docker volume ls` showed something like 50 items for projects that I had created and deleted over the past two years. 

I removed all of them using this command: `docker volume ls -qf dangling=true | xargs docker volume rm`

Success: Database now restores and I have an another 8Gb of free disk space

**Comment by rfay** [comment]
BTW, `docker system prune --volumes` would have been the way to kill off the volumes all automatically. And lose all databases everywhere.

**Comment by gitressa** [comment]
I needed to clean up the HDD for old Docker images (it had been a long time) and found `docker system prune` which worked like a charm, and the clean up reclaimed +50 GB of space.

https://docs.docker.com/engine/manage-resources/pruning/

I did get some errors when I tried to start DDEV projects afterwards, and they didn't work ... But after running `ddev start` a few times, they seem to be working again.

Is there a better method than `docker system prune`, or is it the most efficient?

```
$ docker system prune
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all dangling images
  - unused build cache

Are you sure you want to continue? [y/N] y
Deleted Networks:
solr9_solr

Deleted Images:
deleted: sha256:a27369ea2611c58b8b46971a9c77439575283ff7cf7d3da882e07d3b8236009b
deleted: sha256:d52763aa305f5391ce068bf29dddb8817bbf3f1ac00c3d60bfcc990e9516ab53
deleted: sha256:0def85ee52a45f25db00b72194bb9f6ba682a641272e8a1fee15a85125a15cab
deleted: sha256:3587d336762e5b6eee14038a2baf6b078e06dda12269e2489bd5fb288f906424
[...]
Deleted build cache objects:
kjxgybgqdt7ccpt6zg5q1d66u
z3o7hiabuabh4otpmmy8ow4yh
s8xjnsk7yhpfdj7r891p738cn
[...]
Total reclaimed space: 50.07GB


$ ddev start
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: can't get final child's PID from pipe: EOF: unknown 

Failed to start drupal-d10: composeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-drupal-d10 docker-compose -f /home/user/dev/drupal_d10/.ddev/.ddev-docker-compose-full.yaml up -d', action='[up -d]', err='exit status 1', stdout='', stderr=' Network ddev-drupal-d10_default  Creating
```

See also:
- https://github.com/ddev/ddev/issues/1562.

**Comment by rfay** [comment]
To clean up images that ddev has been involved in: `ddev delete images` or `ddev delete images --all`, see https://ddev.readthedocs.io/en/stable/users/usage/commands/#delete-images

I routinely delete all images as long as I have good internet to replace them: `docker rm -f $(docker ps -aq)` and then `docker rmi -f $(docker images -q)`

**Comment by gitressa** [comment]
Thanks for the link and the commands @rfay. Asking as a Docker non-expert, perhaps this would be a fair way to sort them, in ascending levels of destruction?

- Delete stopped Docker containers, networks not in use, dangling images
`docker system prune`
- Delete all DDEV Docker images
`ddev delete images --all`
- Delete all Docker containers and images
`docker rm -f $(docker ps -aq)`
and then
`docker rmi -f $(docker images -q)`

**Comment by rfay** [comment]
None of those are destructive, unless you don't have internet to re-pull the images. Images are just files that are cached from dockerhub.

`ddev delete images` is the least scope, as it only deletes images that ddev is not currently using.
`ddev delete images --all` is next, as it deletes all images that ddev owns.

**Comment by reinis-danenbergsons** [comment]
In case someone has setup like me - ddev in WSL 2.
After deleting images, reclaim space with `optimize-vhd`. Useful for spring cleaning or if you want to move your virtual disk image to different pc.
After first `optimize-vhd` my vhdx file was 370gb, but after cleaning ddev images and doing `optimize-vhd` again, the vhdx file went down to 70gb.

**Comment by rfay** [comment]
I see this SO link for WSL2 optimize-vhd: https://superuser.com/questions/1606213/how-do-i-get-back-unused-disk-space-from-ubuntu-on-wsl2 - it's something you do with a cmdlet in PowerShell

The SO link doesn't appear to be very authoritative. Did you find better documentation @reinis-danenbergsons ?

**Comment by nickchomey** [comment]
optimize-vhd never worked for me in Windows 11 Home. I had to use diskpart - this looks correct: https://tkacz.pro/wsl-reclaiming-storage-space/

Though, i found that that had limited utility sometimes. The best (but slowest) way to do this was to export, unregister, then re-import the image. 

Something like this (adjust paths accordingly) 

```
wsl --shutdown
wsl --export Ubuntu2404 F:\WSL\Ubuntu2404.tar.gz
wsl --unregister Ubuntu2404
wsl --import Ubuntu2404 D:\WSL\Ubuntu2404 F:\WSL\Ubuntu2404.tar.gz
```  

I now just use Pop_OS (Ubuntu fork, sort of), so no longer an issue.

**Comment by reinis-danenbergsons** [comment]
@rfay [here's](https://learn.microsoft.com/en-us/powershell/module/hyper-v/optimize-vhd) documentation for `optimize-vhd`. The command is only available is you have Hyper-V module enabled on Windows. It's as simple as:
```
wsl --shutdown
Optimize-VHD -Path F:\WSL\ext4.vhdx -Mode Full
```

Also as @nickchomey mentioned, if `optimize-vhd` isn't available then you can use the guide linked in [his comment](https://github.com/ddev/ddev/issues/1465#issuecomment-3694110449). Just avoid doing the "preparation" part unless you know what you are doing. Main commands are:
```
wsl --shutdown
diskpart
select vdisk file="F:\WSL\ext4.vhdx"
attach vdisk readonly
compact vdisk
detach vdisk
```

There also is a third option (which I think is the latest one) to set your distro in wsl to be sparse so that space is automatically reclaimed, tho I didn't manage to get it working:
```
wsl --manage <distro> --set-sparse true
```

Note: if your distro is mounted as a disk volume in windows, then close and don't open file explorer after shutting down wsl. If you open file explorer then wsl will automatically start and, to use optimize-vhd or diskpart, wsl needs to be shutdown.

**Comment by rfay** [comment]
Thanks @reinis-danenbergsons. None of these are really related to this issue, which is about Docker volumes. Would you please open a tutorial issue about WSL VM cleaning, with the various options? Just explain all the many things you and others know there, thanks!
