### ISSUE TITLE
backdrop installer reports permissions problem

### ISSUE THREAD

**Issue by robertgarrigos** [drud/ddev#1468]
**Describe the bug**
backdrop cannot install a module or theme and reports "Permissions are not set up properly"

**To Reproduce**
* install a clean backdrop either latest 1.x or 1.12.3
* go to admin/modules/install an try to install any module

**Expected behavior**
installer should download the module and enable it

**Screenshots**
![backdrop_permissions_error](https://user-images.githubusercontent.com/105581/53352956-137bd800-3924-11e9-9b5a-cfa1c529b896.png)

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macosx 10.14.3
 - Docker version information
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 - ddev version information (use `ddev version`)
bgsync        	drud/ddev-bgsync:v1.6.0
cli           	v1.6.0
commit        	v1.6.0
db            	drud/ddev-dbserver:v1.6.0-10.2
dba           	drud/phpmyadmin:v1.6.0
ddev-ssh-agent	drud/ddev-ssh-agent:v1.6.0
docker        	18.09.2
docker-compose	1.23.2
domain        	ddev.local
router        	drud/ddev-router:v1.6.0
web           	drud/ddev-webserver:v1.6.0
 - config.yaml contents for the misbehaving project: no config.yml
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? No

**Comment by rfay** [comment]
Hmm, I wasn't able to recreate this problem on macOS using backdrop 1.12.3 and a completely clean install.  I think you may have a backdrop or permissions issue on your mac?

Could you please `ddev ssh` and `ls -l . modules` and report the results here? Thanks!

**Comment by robertgarrigos** [comment]
These were the permissions I had:
```
-rw-r--r--  1 uid_33  gid_33  3978 Feb 23 15:06 README.md
drwxr-xr-x 16 uid_501 gid_20   512 Feb 23 15:06 core
-rw-r--r--  1 uid_501 gid_20   537 Feb 25 20:24 ddev_drush_settings.php
drwxr-xr-x 13 uid_33  gid_33   416 Feb 25 15:55 files
-rwxr-xr-x  1 uid_33  gid_33   578 Feb 23 15:06 index.php
drwxr-xr-x  3 uid_33  gid_33    96 Feb 23 15:06 layouts
drwxr-xr-x  3 uid_33  gid_33    96 Feb 23 15:06 modules
-rw-r--r--  1 uid_33  gid_33  1216 Feb 23 15:06 robots.txt
-rw-r--r--  1 uid_501 gid_20   911 Feb 25 15:01 settings.ddev.php
-rw-r--r--  1 uid_33  gid_33 15640 Feb 25 15:01 settings.php
drwxr-xr-x  4 uid_33  gid_33   128 Feb 23 15:06 sites
drwxr-xr-x  3 uid_33  gid_33    96 Feb 23 15:06 themes
```
I changed to:

```
-rw-r--r--  1 uid_33  gid_33  3978 Feb 23 15:06 README.md
drwxr-xr-x 16 uid_501 gid_20   512 Feb 23 15:06 core
-rw-r--r--  1 uid_501 gid_20   537 Feb 25 20:24 ddev_drush_settings.php
drwxr-xr-x 13 uid_33  gid_33   416 Feb 25 15:55 files
-rwxr-xr-x  1 uid_33  gid_33   578 Feb 23 15:06 index.php
drwxr-xr-x  3 uid_33  gid_33    96 Feb 23 15:06 layouts
drwxrwxrwx  3 uid_33  gid_33    96 Feb 23 15:06 modules
-rw-r--r--  1 uid_33  gid_33  1216 Feb 23 15:06 robots.txt
-rw-r--r--  1 uid_501 gid_20   911 Feb 25 15:01 settings.ddev.php
-rw-r--r--  1 uid_33  gid_33 15640 Feb 25 15:01 settings.php
drwxr-xr-x  4 uid_33  gid_33   128 Feb 23 15:06 sites
drwxr-xr-x  3 uid_33  gid_33    96 Feb 23 15:06 themes
```
and still same error.

thank you!

**Comment by rfay** [comment]
This is macOS. What's your id on macOS? 501 right (use `id`) to find out, on the host. 

It looks to me like your files on the host are not owned by you, they're owned by uid 33. That won't work. I don't know how it got that way. It's a host-side problem.

On the host (on the mac)
`sudo chown -R $(whoami) <projectdir>`
will likely fix this problem. But you'll want to figure out what UID 33 is, where it came from, and how your files got checked out as uid 33. On my system uid 33 is `_appstore`. Not a good thing :)

**Comment by robertgarrigos** [comment]
Thanks @rfay I just deleted the backdrop files and copied again. They are owned now by uid_501 and got no problems. :-)
