### ISSUE TITLE
WordPress: Errors with the wp-cli - Undefined index: SERVER_NAME

### ISSUE THREAD

**Issue by fschmittlein** [drud/ddev#1469]
**Describe the bug**
Install the plugin 'contact-form-7' with 'wp plugin install contact-form-7 --activate' i get the error, but the plugin is working. i see the error on more plugins.

PHP Notice:  Undefined index: SERVER_NAME in /var/www/html/web/wp-content/plugins/contact-form-7/includes/contact-form-template.php on line 113
Notice: Undefined index: SERVER_NAME in /var/www/html/web/wp-content/plugins/contact-form-7/includes/contact-form-template.php on line 113
PHP Notice:  Undefined index: SERVER_NAME in /var/www/html/web/wp-content/plugins/contact-form-7/includes/functions.php on line 365
Notice: Undefined index: SERVER_NAME in /var/www/html/web/wp-content/plugins/contact-form-7/includes/functions.php on line 365

PHP Notice:  Undefined index: SERVER_NAME in /var/www/html/web/wp-content/plugins/contact-form-7/includes/contact-form-template.php on line 113
Notice: Undefined index: SERVER_NAME in /var/www/html/web/wp-content/plugins/contact-form-7/includes/contact-form-template.php on line 113
PHP Notice:  Undefined index: SERVER_NAME in /var/www/html/web/wp-content/plugins/contact-form-7/includes/functions.php on line 365
Notice: Undefined index: SERVER_NAME in /var/www/html/web/wp-content/plugins/contact-form-7/includes/functions.php on line 365

**To Reproduce**
1. wp plugin install contact-form-7 --activate

**Comment by rfay** [comment]
Seems we haven't had a lot of usage of wp-cli! But couldn't this be a problem with the contact-form-7 plugin? It appears to be built only for installation in the context of a webserver. I don't think this is a ddev problem, but will look forward to hearing what you come up with.

**Comment by rfay** [comment]
When you run PHP as a CLI, $_SERVER is not set, so $_SERVER['SERVER_NAME'] is not available. This seems to be a result of contact-form-7 not expecting to be run with wp-cli.  I don't see any error like this when installing contact-form-7 via the web route.  Thanks for reporting!
