### ISSUE TITLE
Add import support for zip

### ISSUE THREAD

**Issue by tannerjfco** [drud/ddev#147]
## What happened (or feature request):
Feature Request
Our import functionality currently only supports tar/gz format archives, but ZIP is a pretty popular archive format as well, and we don't support that.

## What you expected to happen:
We should introduce support for zip format archives so that we can support the most popular archive formats for users.

## Related source links or issues:

**Comment by rickmanelius** [comment]
Seems straightforward/low hanging fruit. Converted to actionable.
