### ISSUE TITLE
NFS Setup secure by default

### ISSUE THREAD

**Issue by kaystrobach** [drud/ddev#1471]
**Is your feature request related to a problem? Please describe.**

* NFS Configuration feels weird and the defaults are generally unsecure.

**Describe the solution you'd like**

* To ensure safety DDEV should ship an own NFS deamon only listening on 127.0.0.1 to ensure security and system integrity.

**Describe alternatives you've considered**

* configure the OS 

**Additional context**

* https://github.com/drud/ddev/pull/1442
* https://ddev.readthedocs.io/en/stable/users/performance/#macos-nfs-setup

**Comment by rfay** [comment]
I'm in some agreement, but there are a few factors that argue against:
* Most dev machines have a decent firewall blocking nfs
* Maintaining a separate NFS daemon for 3 platforms would be a real problem, making this approach impossible I'd think. 
* The docs certainly encourage people to do something in line with their own security expectations (of course we know that people often skip by this or don't understand how to do it).

**Comment by kaystrobach** [comment]
The last point is the biggest problem imho.

**Comment by rfay** [comment]
@dacostafilipe sends this [gist](https://gist.github.com/dacostafilipe/d4889f3f5245cd1b44963a4c02b08068) as an example of sharing only a started project.

**Comment by rfay** [comment]
Reviewing the situation:
* Allowed clients: Currently on macOS and Linux all "public" IP addresses are allowed as clients. 10.*, 172.28, 192.168. In reality it should only be the ddev_default network (or the proper network on docker toolbox)
* Allowed source: On macOS and Linux it's currently sharing all of /home, which is too much. Better might be ~/ and even better ~/sites or ~/workspace (wherever users put their projects). Going to ~/ is pretty easy, going farther than that probably means the user will have to configure.  (On WIndows, it's defaulting to the whole C: drive, which clearly isn't what we want, better ~/)

**Comment by rfay** [comment]
@kaystrobach could you please review #1616 ? Would be much appreciated!

**Comment by kaystrobach** [comment]
I wonder if there can’t be a ddev share for osx and linux (always same folder) where symlinks are created per project. This would dramatically reduce the risk to expose the full home directory.

**Comment by rfay** [comment]
I don't think nfsd can do anything very good with symlinks; if it followed them (and the target weren't shared) it would be a horrible security situation.

The reason I keep sticking to a simple share is to keep it straightforward for all platforms and simple for users. 

Note that in #1616 (would love it if you'd try it) you'll find that the sharing is limited to the local machine in every case, so except where there is shared machine, this shouldn't be an issue.

**Comment by kaystrobach** [comment]
short testing done and it looks good so far.
