### ISSUE TITLE
ddev restore-snapshot failed to restore snapshot:  db container failed: can't connect to MySQL Server

### ISSUE THREAD

**Issue by deviantintegral** [drud/ddev#1477]
**Describe the bug**

I'm testing out database snapshot functionality, and I can't restore a snapshot.

**To Reproduce**

1. Follow the quickstart guide to set up Drupal 8 via composer (this shouldn't be required, it's just what I did).
1. Import a database with `ddev import-db --src=<path>`. In my case, it was a 4.7GB D8 database from a live site.
1. Create a snapshot with `ddev snapshot`.
1. Try to restore the snapshot:

```
ddev restore-snapshot d8_20190301164958ddev restore-snapshot d8_20190301164958
Stopping ddev-d8-web ... done
Stopping ddev-d8-dba ... done
Stopping ddev-d8-db  ... done

Stopping ddev-router ... done
Removing ddev-router ... done
Network ddev_default is external, skipping
Removing container: ddev-d8-web
Removing container: ddev-d8-dba
Removing container: ddev-d8-db
Network ddev_default is external, skipping
Network ddev_default is external, skipping
Creating ddev-d8-db ... done
Creating ddev-d8-dba ... done
Creating ddev-d8-web ... done

Creating ddev-router ... done

Failed to restore snapshot d8_20190301164958 for project d8: Failed to start project for RestoreSnapshot: db container failed: log=ERROR 2002 (HY000): Can't connect to MySQL server on '127.0.0.1' (115)
, err=container /ddev-d8-db unhealthy: ERROR 2002 (HY000): Can't connect to MySQL server on '127.0.0.1' (115)
```

Note that mariadb is running fine, and I can connect to it without issue.

**Version and configuration information (please complete the following information):**
 - macOS 10.14.3
 - Docker version information (use `docker version`) and insert it here.

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

 - ddev version information (use `ddev version`)
```
bgsync        	drud/ddev-bgsync:v1.6.0
cli           	v1.6.0
commit        	v1.6.0
db            	drud/ddev-dbserver:v1.6.0-10.2
dba           	drud/phpmyadmin:v1.6.0
ddev-ssh-agent	drud/ddev-ssh-agent:v1.6.0
docker        	18.09.2
docker-compose	1.23.2
domain        	ddev.local
router        	drud/ddev-router:v1.6.0
web           	drud/ddev-webserver:v1.6.0
```

 - config.yaml contents for the misbehaving project
```
APIVersion: v1.6.0
name: d8
type: drupal8
docroot: web
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
webcache_enabled: false
nfs_mount_enabled: false
provider: default
```

**Comment by rfay** [comment]
I'm unable to recreate this problem. But I may not have a 4.7GB db to test it with, I'll take a look. Lots of people are using snapshots with large databases though.  If you are able to share the db with me, that would be lovely. 

Does the database actually get restored, despite the error?

What OS are you running on?

Please share the `ddev logs -s db` as a gist.

The way the restore works is it starts up a new instance and does a mariabackup restore on the way up, so it's apparently hitting an error there, or perhaps it just takes too long for the db to initialize with the big db.

**Comment by rfay** [comment]
I did create a 3.8GB database using the technique in https://stackoverflow.com/a/45221000/215713 (added to a d8 umami install), and then was able to snapshot and restore it just fine (macOS).

**Comment by deviantintegral** [comment]
Sorry, I don't think I can share this database.

> Does the database actually get restored, despite the error?

I just checked, and it does! However, the logs don't show a slow mysql start, but if the connectivity check is async this would make sense.

> What OS are you running on?

macOS 10.14.

Here's the db logs: https://gist.github.com/deviantintegral/fa0dc9b6811bac791f9478f69522f796

**Comment by rfay** [comment]
@deviantintegral thanks.

Could you try adding a .ddev/docker-compose.longhealth.yaml with these contents (or experiment with them) and see if it changes the behavior? My suspicion is that it just takes too long and the healthcheck times out, but it does come up. That's a LOT of tables!

```
version: '3.6'
services:
  db:
    healthcheck:
      interval: 5s
      retries: 12
      start_period: 60s
```

**Comment by deviantintegral** [comment]
The modified health check worked for me. Thanks!

**Comment by jameswilson** [comment]
I hit the same error message when restoring a snapshot that was 7 GB on disk (!) and ended up creating a `.ddev/docker-compose.dbhealthcheck.yaml` file that essentially doubled the default `interval` and `retries` values, so that the math ended up matching the value of the `timeout` field.   I found that changing start_period from the default of 20 seconds had no effect for me.

If you hit the error message from the issue description above, I recommend entering the defaults, then double them and run `time ddev restore-snapshot <snapshot_name>` until you're able to successfully restore the snapshot.

My approach:

1. Put the current defaults as of August 2020:

    ```yaml
    # Put this in .ddev/docker-compose.dbhealthcheck.yaml
    version: '3.6'
    services:
      db:
        healthcheck:
          interval: 1s
          retries: 30
          start_period: 20s
          timeout: 120s
    ```

2. Then double the interval and retries values and bump the value of the timeout field to the product of those two (2*60 = 120):

    ```
          interval: 2s
          retries: 60
          start_period: 20s
          timeout: 120s
    ```

3. Run `time ddev restore-snapshot <name>`, and if it fails, double the interval and retries values and bump the timeout accordingly.

    ```
          interval: 4s
          retries: 120
          start_period: 20s
          timeout: 560s
    ```

**Comment by rfay** [comment]
Here's another strategy, which basically amounts to short-circuiting the healthcheck altogether, since it's only hurting us here. I'd appreciate if you could try this out.

```
version: '3.6'
services:
  db:
    healthcheck:
      test: ["CMD", "true"]
      interval: 10s
```

Reopening this issue, since it can use a little bit of documentation or revisiting the values. I remember now that the timeout values were changed to cut down on battery usage/docker activity (which was good), but definitely lost their edge for this use-case.

**Comment by croane** [comment]
FYI, I encountered this issue with a massive woocommerce site that is currently 8.4GB. The last suggestion seemed to work great for me!

I'll mention that I work for a web development shop that was using docksal heavily over the last few years. We liked it, but with massive sites the performance was an issue. Switching to docksal really made this massive site load much more quickly. I was able to create custom code to import the vaultpress db in 26m (vs around 3h in docksal). I may share this code at some point for others to use.

**Comment by rfay** [comment]
There is some ongoing work on the `ddev snapshot restore` feature in https://github.com/drud/ddev/pull/2747 - hopefully I'll be able to complete that before too long.

Note that if you like snapshots and haven't tried out the new consolidated and prompted features in the v1.17 alphas, you'll like them. https://github.com/drud/ddev/releases/tag/v1.17.0-alpha3
