### ISSUE TITLE
Installing and Running Drupal Varbase

### ISSUE THREAD

**Issue by AlexCreamer** [drud/ddev#1481]
Hi, I tried installing Varbase with `ddev composer create Vardot/varbase-project --stability dev --no-interaction`, and I got a directory with a inner structure that looks like:
```
2019-03-03  08:18 PM    <DIR>          .ddev
2019-03-03  10:23 PM    <DIR>          .git
2019-03-03  09:25 PM               532 .gitignore
2019-03-03  09:26 PM    <DIR>          .tmp_ddev_composer_create_WSbJOJ
2019-03-03  10:23 PM    <DIR>          bin
2019-03-03  09:25 PM             4,151 composer.json
2019-03-03  10:20 PM           549,388 composer.lock
2019-03-03  10:27 PM    <DIR>          docroot
2019-03-03  09:25 PM            18,046 LICENSE
2019-03-03  09:25 PM             2,738 README.md
2019-03-03  10:26 PM    <DIR>          vendor
```
and when I run `ddev start`, and the containers are successfully running, I get a page that say's `403 forbidden`. I have the `docroot` folder  shown above as the docroot requested by `ddev config`.

**Comment by andrewfrench** [comment]
Hi @AlexCreamer, I was able to get to an install page with the following commands:

- `ddev config --project-type php`
- `ddev composer create Vardot/varbase-project --stability dev --no-interaction`
- `ddev config --project-type drupal8 --docroot docroot` (or use autodetected values)
- `ddev start`

Can you try again with the above in a fresh DDEV project and let me know if that fails?

**Comment by rfay** [comment]
Yeah it does look like your docroot is just wrong. You can just edit it in .ddev/config.yaml.

**Comment by AlexCreamer** [comment]
I have `docroot` as my docroot in my config.yml.

I will try what AndrewFrench suggested. :)

**Comment by AlexCreamer** [comment]
I got the following message when trying step 2 of what Andrew suggested:
```
 ddev composer create Vardot/varbase-project --stability dev --no-interaction
Warning: Any existing contents of the project root (C:\Users\DC\Projects) will be removed
Removing any existing files in project root
Executing composer command: composer create-project Vardot/varbase-project /var/www/html/.tmp_ddev_composer_create_uhVomk --stability dev --no-interaction

The "https://repo.packagist.org/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
failed to open stream: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
https://repo.packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
```
Not sure how to fix this.

**Comment by rfay** [comment]
Your internet was broken at that time. 

If it persists, ddev rm and restart docker.

**Comment by AlexCreamer** [comment]
I never got to try what you suggested, but restarting my computer made it work! ^_^

**Comment by begrafx** [comment]
This thread was helpful. I did a variation of the above, here's my CONFIG.YAML file:
`name: varbase
type: drupal9
docroot: docroot
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.3"
mysql_version: ""
nfs_mount_enabled: false
mutagen_enabled: false
use_dns_when_possible: true
composer_version: "2"
web_environment: []
`
I created the directory, CD into it, I did a `ddev config` setting up as above, then gave the command: 
`ddev composer create Vardot/varbase-project --stability dev --no-interaction`

which pulled the repository down. `ddev launch` started the install process (after the required activity). The only issue I encountered with this method is, when the installer started, it stops and asks me for the database information (which a normal DDEV setup doesn't do). I've found everything else, but  I don't seem to be able to find the database name that ddev is using. I did `ddev describe` and I tried `ddev-varbase-db` and `ddev-varbase-db:3306` but Varbase keeps coming back saying it can't find the database, so I'm guessing I'm using the wrong name.

**Comment by rfay** [comment]
Ddev always uses the database name "db", on host "db",  with user "db" and password "db".

**Comment by begrafx** [comment]
I tried "db" as database name, database username and database password, and got the same error. As you can see from the CONFIG.YAML above, it is specified as "drupal9". 
Under "Advanced Options" I have tried it with "Host" set both as "localhost" and as "localhost:51526" (as it shows from ddev describe). 


Here is the output of `ddev describe`

`% ddev describe
┌───────────────────────────────────────────────────────────────────────────┐
│ Project: varbase ~/WebDev/varbase https://varbase.ddev.site               │
├────────────┬──────┬──────────────────────────────────┬────────────────────┤
│ SERVICE    │ STAT │ URL/PORT                         │ INFO               │
├────────────┼──────┼──────────────────────────────────┼────────────────────┤
│ web        │ OK   │ https://varbase.ddev.site        │ drupal9 PHP7.4     │
│            │      │ InDocker: ddev-varbase-web:443,8 │ nginx-fpm          │
│            │      │ 0,8025                           │ docroot:'docroot'  │
│            │      │ Host: localhost:51529,51530      │                    │
├────────────┼──────┼──────────────────────────────────┼────────────────────┤
│ db         │ OK   │ InDocker: ddev-varbase-db:3306   │ MariaDB 10.3       │
│            │      │ Host: localhost:51526            │ User/Pass: 'db/db' │
│            │      │                                  │ or 'root/root'     │
├────────────┼──────┼──────────────────────────────────┼────────────────────┤
│ PHPMyAdmin │ OK   │ https://varbase.ddev.site:8037   │                    │
│            │      │ InDocker: ddev-varbase-dba:80,80 │                    │
│            │      │ `ddev launch -p`                 │                    │
├────────────┼──────┼──────────────────────────────────┼────────────────────┤
│ Mailhog    │      │ MailHog: https://varbase.ddev.si │                    │
│            │      │ te:8026                          │                    │
│            │      │ `ddev launch -m`                 │                    │
├────────────┼──────┼──────────────────────────────────┼────────────────────┤
│ All URLs   │      │ https://varbase.ddev.site,       │                    │
│            │      │ https://127.0.0.1:51529,         │                    │
│            │      │ http://varbase.ddev.site,        │                    │
│            │      │ http://127.0.0.1:51530           │                    │
└────────────┴──────┴──────────────────────────────────┴────────────────────┘
 
`

**Comment by begrafx** [comment]
This is the message I get:

`Error message
Resolve all issues below to continue the installation. For help configuring your database server, see the [installation handbook](https://www.drupal.org/docs/8/install), or contact your hosting provider.

    Failed to connect to your database server. The server reports the following message: SQLSTATE[HY000] [2002] No such file or directory.
        Is the database server running?
        Does the database exist or does the database user have sufficient privileges to create the database?
        Have you entered the correct database name?
        Have you entered the correct username and password?
        Have you entered the correct database hostname and port number?`

**Comment by rfay** [comment]
Most likely you haven't set the db host to "db".  You can add printf-debugging or step through with xdebug to find out what your settings.php really has in it.

"No such file or directory" may mean that you're trying to use a socket to connect, so look at that. 

You can easily verify that the db server is working with `ddev mysql`

**Comment by begrafx** [comment]
It works fine with all the other DDEV projects I have going. And when I enter `ddev mysql` I get:

`Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 812
Server version: 10.3.32-MariaDB-1:10.3.32+maria~focal-log mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [db]> 
`

**Comment by rfay** [comment]
Exactly. So you just have to get your settings.php set up correctly. That's it.

**Comment by begrafx** [comment]
OK... so did I do something wrong... as I say, every other DDEV setup I've done, it just finds the database and handles that all on its own. Trying to sort out what's different about this one.

**Comment by rfay** [comment]
Every DDEV setup by default adds an include to settings.php that brings in settings.ddev.php, which is where the db settings are. Take a look at your settings.php if that's not there, it's most likely because the project type in .ddev/config.yaml is not correct (you want it to be drupal8 or drupal9 or something right?). Or perhaps the docroot is wrong. Or perhaps you have project type 'php' and you're managing the settings yourself, which means you have to add those things to settings.php or settings.local.php or whatever yourself.

**Comment by begrafx** [comment]
OK. That was it. I copied a `settings.ddev.php` file over from another project, modified it per the `ddev describe` information from my Varbase project, then I looked at that original project's settings.php file, and found the lines to include the settings.ddev.php file, and added them to the Varbase project's settings.php file, relaunched the Varbase project, and it worked. In looking, I didn't see that a settings.ddev.php file even existed in my Varbase project prior to my doing this. I had run the `ddev config` process. Now for clarification, on this one I simply entered `ddev config` and then answered each of the prompts, specifying that it was a Drupal 9 project, that docroot was the docroot, etc. (rather than entering `ddev config --project-type=drupal9 --docroot=web [etc. etc.]` as I commonly would). At what point is the settings.ddev.php file generated? I'm trying to sort out where I err'd in my original process.

**Comment by rfay** [comment]
On a *drupal* project (one that is project type drupal*, that you can see by looking in the .ddev/config.yaml) the settings.ddev.php gets generated on config and also on start. UNLESS you have removed  the `#ddev-generated` line from the file. 

Please read through https://ddev.readthedocs.io/en/latest/users/topics/settings_files/

**Comment by begrafx** [comment]
Thank you. I'll check it out.

**Comment by begrafx** [comment]
OK. This worked for me, getting Varbase to install with DDEV.


`mkdir my-varbase-site
cd my-varbase-site
ddev config project-type=drupal9 --docroot=docroot --create-docroot --mutagen-enabled
ddev composer create "Vardot/varbase-project --stability dev --no-interaction"
`
I've found I didn't even need to give a `ddev start` command. Using this process, it starts on its own.

**Comment by rfay** [comment]
Thanks for reporting back. I imagine the original one wasn't set up with drupal9 project type.

**Comment by begrafx** [comment]
It was (see the CONFIG.YAML shared above). I'm not certain what the difference was, but this sequence works like a charm. (I blame "digital gremlins".)
