### ISSUE TITLE
Add .mysql and .mysql.gz to list of import-db filetypes in docs and ddev help import-db

### ISSUE THREAD

**Issue by nigelwhite** [drud/ddev#1483]
For us drupal users an easy way to get a database download from a remote site is the backup_migrate module which allows a one-click download of the database. This results in mydownload.mysql.gz. At the moment the ddev import-db command cannot process the result.

I am not sure of the most efficient workaround. I tired renaming the file to sql.gz but this didn't work for me.

There are a couple of closed requests for the same thing so I am just adding my vote.

Thanks

**Comment by nigelwhite** [comment]
For us drupal users an easy way to get a database download from a remote site is the backup_migrate module which allows a one-click download of the database. This results in mydownload.mysql.gz. At the moment the ddev import-db command cannot process the result.

I am not sure of the most efficient workaround. I tired renaming the file to sql.gz but this didn't work for me.

There are a couple of closed requests for the same thing so I am just adding my vote.

Thanks

**Comment by rfay** [comment]
It already handles .mysql.gz, you're asking for something quite different right?  Please edit the title and OP to say what you ant.

**Comment by rfay** [comment]
I just tested:

```
rfay@rfay-mbp-2017:~/workspace/randyfay$ ddev import-db --src=.tarballs/RandyFay.com-2018-05-04T15-40-00.mysql.gz
3.89MiB 0:00:02 [1.79MiB/s] [==========================================================================>] 100%
Ensuring write permissions for randyfay
Existing settings.php file includes settings.ddev.php
Successfully imported database for randyfay
```

**Comment by nigelwhite** [comment]
Thanks, that's good to know. But I still get

`$ ddev import-db --src=~/Downloads/OysterCatcher-2019-03-05T22-24-42.mysql.gz
Failed to import database for oyster: failed to extract provided archive: gzip: invalid header `

Probably me being dense as usual

**Comment by rfay** [comment]
For most people this is a result of the file actually *not* being a gzip file. 

Please run `file ~/Downloads/OysterCatcher-2019-03-05T22-24-42.mysql.gz`.  I think you'll find it's not compressed. 

Note that there is a bug in ever-so-many versions of backup_migrate where the compression never occurs, but the file is shown with the name ".gz" anyway, https://www.drupal.org/project/backup_migrate/issues/2926610 - I've battled it many times. I recommend chiming in on that issue that it's still a problem. I've tried enough times.

**Comment by nigelwhite** [comment]
Thank you so much for explaining.

For others who are confused and want a work-around, you can rename the downloaded file to .sql each time. I've ended up changing my settings in backup_migrate to compression = none. This outputs .mysql which also works.

@rfay I was also thrown by .mysql.gz not appearing in the list of supported file types, in the docs at https://ddev.readthedocs.io/en/stable/users/cli-usage/#exporting-a-database. I guess that may confuse others too.

Thanks again

**Comment by rfay** [comment]
I'll leave this open and change the title so we get the docs updated. We should also update `ddev help import-db` so it offers .mysql and .mysql.gz as options. 

I'll never understand why backup_migrate used .mysql as a file extension instead of .sql.

Even though this backup_migrate bug is insidious and it's been that way for years, I'm reluctant to go debug it for the maintainers.

**Comment by rfay** [comment]
@nigelwhite I did a PR for backup_migrate to solve this problem with Chrome, and would love to have your testing and +1 there. https://www.drupal.org/project/backup_migrate/issues/2926610#comment-13019097

**Comment by nigelwhite** [comment]
Thanks @rfay. I'm keen to test this: using a clean install of Drupal 7.
Got stuck trying to do it via git.
I downloaded your patch and, in the web root, did
```git apply patches/backup_migrate.2926610_11.fix_no_compression_0.patch```
what I got was ```error: includes/files.inc: No such file or directory```
This is the first time I've tried applying a patch. Its sure to be something I'm not doing....

**Comment by rfay** [comment]
Basic patch instructions are at https://drupal.org/patch

But the basic idea here is you should 

    cd sites/all/modules/backup_migrate
    patch -p1 </where/you/downloaded/the/patch.patch

That's mostly it. You can use `git apply` if you have a git checkout of backup_migrate in sites/all/modules/backup_migrate and you're in that directory.
