### ISSUE TITLE
Global Drush 9 as an option for Drupal 8 sites

### ISSUE THREAD

**Issue by AronNovak** [drud/ddev#1488]
There's a site which is going to be hosted on Pantheon. If we install site-local Drush 9, DDEV works fine, however it conflicts with Terminus, the recommendation is to not have Drush 9 (site) locally: https://pantheon.io/blog/drush-940-release-available-pantheon
So at deployments, right we remove the local Drush before pushing the code to Pantheon

**Describe the solution you'd like**
DDEV could make it possible to use global Drush 9 via [cgr](https://github.com/consolidation/cgr), to have a `drush_version` option, similarly to `php_version`.

**Describe alternatives you've considered**
Also it could work that with a bunch of shell commands, to perform the change in a longer way via `config.yaml`.

**Comment by rfay** [comment]
ddev has drush 8 installed in the container, not drush 9, and it's intended to be used as a drush launcher, nothing else.  There is also a drush launcher project, would that help?

We haven't had any complaints about our pantheon integration and the current setup, and lots of people using Pantheon. Could you say more about the conflict? Are you saying you can't do a site-local drush 8 installation as is recommended by all?

**Comment by AronNovak** [comment]
@rfay 
Sure, let me elaborate on this one.
Drush **9** is not supported by Pantheon right now. For our project, it would be a must, as it has the `drush si --existing-config` option. We had back-and-forth with the support, for now, with Drush 8, the site works well, with Drush 9, not quite.

So our current setup:
## GH repo
 - site-local Drush 9

## Artifact Pantheon repo
 - global Drush 8

As if we add site-local Drush 9 to Pantheon, the global Drush 8 is not in use, as the commands are re-routed to the site-local one. So that's our problem, if we could get rid of the site-local Drush 9, it would simplify our build script, but of course, if Pantheon will make the Drush 9 support stable, it would be even better.

**Comment by rfay** [comment]
So almost everybody uses a site-local drush for stability and compatibility reasons right? It's just part of a `composer install`? Isn't that the recommended strategy?

I think providing a drush9 is in ddev's future anyway, but it doesn't seem like it's really the key thing for you?

**Comment by rfay** [comment]
When we provide an explicit drush9 we will want to provide a working drush.yml that does what the old ddev_drush_settings.php used to do, if that's possible. It would be *especially* nice if we can get `drush uli` to work correctly with drush 9. 

A file in sites/default/drush.yml with these contents is *supposed* to accomplish this but I haven't succeeded:

```
drush: 
  options:
    uri: d8composer.ddev.local
```

**Comment by rfay** [comment]
Drush 9 does not support any option except site-local, so we'll never have a global drush9.  From the top of https://docs.drush.org/en/master/install/ :

> Drush 9 only supports one install method. It requires that your Drupal 8 site be built with Composer and Drush be listed as a dependency
