### ISSUE TITLE
Host binding of database should be to 127.0.0.1 only, not to 0.0.0.0

### ISSUE THREAD

**Issue by t3easy** [drud/ddev#1491]
**Describe the bug**
Don't map db container to 0.0.0.0

**To Reproduce**
1. Configure ddev and start the project
2. run `docker ps`
3. See that the db container maps it's port to 0.0.0.0

**Expected behavior**
Map to just 127.0.0.1 like:

```
  db:
    ports:
    - 127.0.0.1::3306
```

**Comment by t3easy** [comment]
https://github.com/drud/ddev/blob/64a43c837a0769c09159855a492dda732c38e2d8/pkg/ddevapp/templates.go#L27

**Comment by rfay** [comment]
Please explain the issue. The DB container is only on 3306 inside the container. It's on an ephemeral port on the host.

**Comment by t3easy** [comment]
If there is any documentation how to build and test, I would be happy to send a PR.

**Comment by rfay** [comment]
Basically, you need golang, `brew install golang` on macOS.
Then https://github.com/drud/ddev/blob/master/docs/developers/building-contributing.md

Mostly just `make` and your binary will end up in .gotmp/bin/darwin_amd64/ddev

Thanks!

**Comment by rfay** [comment]
There's a PR with artifacts to test on https://github.com/drud/ddev/pull/1502#issuecomment-475048732 and I'd love to have some feedback on it.
