### ISSUE TITLE
Deprecate experimental webcache feature

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1495]
**Describe the bug**

Webcache (bgcache) has so very many problems in a cross-platform or a stressing environment; we'll likely never be able to get predictable behavior out of it on Windows. 

We should consider deprecating this experimental feature, perhaps removing it in v1.8.0 or somewhere there.

**Comment by rfay** [comment]
Responses on slack have been consistent that NFS is better and we should let webcache go. I think we should announce immediately:

* No further support for it
* Removal of the feature June 1, 2019 or so.

In addition, we should remove the docs immediately.

**Comment by pcambra** [comment]
I want to point out that *based on my benchmarks*, in my experience, running tests from within the container using webcache is ~10x faster than NFS.

**Comment by rfay** [comment]
@pcambra we're leaving it in there for now, you were the only one who spoke up in its favor. We're just not running tests against it any more, and docs indicate deprecated.
