### ISSUE TITLE
Custom php config doesn't work with apache-cgi webserver_type

### ISSUE THREAD

**Issue by pauloffb** [drud/ddev#1499]
I've setup a ddev project with the following config:

```
APIVersion: v1.6.0
name: test-project
type: php
docroot: web
php_version: "7.2"
webserver_type: apache-cgi
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
webcache_enabled: false
nfs_mount_enabled: false
provider: default
```

I created a file at .ddev/php/my-config.ini with:

```
[PHP]
max_execution_time = 240
display_errors = Off
```

After I ddev rm  && ddev start i check phpinfo() and I still get default values for PHP config

I've tried to enter the container and under /etc/php I get my custom my-php.ini inside 7.2/fpm folder and not under 7.2/cgi folder as I think would be expected.

Am I doing anything wrong?

My version reports

```
bgsync          drud/ddev-bgsync:v1.6.0       
cli             v1.6.0                        
commit          v1.6.0                        
db              drud/ddev-dbserver:v1.6.0-10.2
dba             drud/phpmyadmin:v1.6.0        
ddev-ssh-agent  drud/ddev-ssh-agent:v1.6.0    
docker          18.09.3-ce                    
docker-compose  1.23.2                        
domain          ddev.local                    
router          drud/ddev-router:v1.6.0       
web             drud/ddev-webserver:v1.6.0    
```

**Comment by rfay** [comment]
When you do a `ddev start` does it show something like `Using custom PHP configuration: [/Users/rfay/workspace/d7git/.ddev/php/my-config.ini]` ?

**Comment by rfay** [comment]
I tried with your exact example and it worked fine. Could you please provide the `pwd` from your .ddev/php directory?

**Comment by pauloffb** [comment]
Yes it shows the message every time I start

**Comment by rfay** [comment]
Please `cd .ddev/php` and provide the output of `pwd`. 

How are you looking at phpinfo? Just a `phpinfo();` file?

I just noticed you're using apache-cgi and tried it, and I seem to get your result, so it sounds like a bug with the rarely-used apache-cgi configuration. I'd recommend changing to apache-fpm for the short term. I'll update the title.

**Comment by stat1x** [comment]
I have a similar issue by using `webserver_type: apache-fpm` and trying to change the vhost configuration in `.ddev/apache/apache-site.conf`.

I have this message on start-up :
```
Using custom apache configuration in apache/apache-site.conf 
Custom configuration takes effect when container is created, 
usually on start, use 'ddev restart' if you're not seeing it take effect. 
```
But the apache configuration in the container does not change.

I'm using ddev v1.9.1 (which is amazing!!!!!! thank you so much for it).

**Comment by stat1x** [comment]
Sorry it was my bad. I used an environment variable in a wrong way...
I was doing 
```
	Alias "/$SERVICE_NAME/$APP_NAME" "$WEBSERVER_DOCROOT"
```
instead of 
```
	Alias /${SERVICE_NAME}/${APP_NAME} "$WEBSERVER_DOCROOT"
```
So my alias was not working. 
You can ignore my previous comment.

**Comment by rfay** [comment]
I just tested this with apache-cgi and I don't see any problems with custom php usage, so closing this for now, but happy to follow up here or elsewhere.
