### ISSUE TITLE
Relax nginx/php config in both ddev-webserver and ddev-router

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1507]
**Describe the bug**

Most of the packet-size limitations in nginx/apache/php are intended to prevent server abuse or overuse by malicious clients or bad code. But those aren't really goals for ddev, so it would be useful to a few people to:

* Set nginx's client_max_body_size to 0 (disabling that feature) on both ddev-webserver and ddev-router.
* Increase php upload_max_filesize and  post_max_size
* Increase php max_input_vars
* I don't think there's an equivalent apache config, but it's worth looking.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: [e.g. Windows 10, macOS High Sierra]
 - Docker version information (use `docker version`) and insert it here.
 - ddev version information (use `ddev version`)
 - config.yaml contents for the misbehaving project
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

**Additional context**
Add any other context about the problem here. Thanks!

**Comment by RobertLang** [comment]
The limit in Apache is set via the LimitRequestBody directive and defaults to 0, so this should be ok.

However there is another Config which could be set to 0: LimitXMLRequestBody (Default: 1 M)
https://httpd.apache.org/docs/trunk/de/mod/core.html#limitxmlrequestbody

Personally I never had a problem with the XML body size.

**Comment by rfay** [comment]
Thanks @RobertLang - Could you say more about the situation where you hit the client_max_body_size problem in the router? I wasn't familiar with the technology you were testing.

**Comment by RobertLang** [comment]
I was integrating a resumable file upload for larger files using the tus protokoll (https://tus.io/) and tus-php (https://github.com/ankitpokhrel/tus-php). 
Everything worked nicely until I hit the 100 M barrier configured in the ddev-router. The router returned an error: Nginx: 413 – Request Entity Too Large which, after doing some research on google, led me to the solution to change the client_max_body_size on the ddev-router container.
After changing that value uploads with several gigs of data were possible.
