### ISSUE TITLE
ddev version show mariadb 10.2

### ISSUE THREAD

**Issue by padina** [drud/ddev#1509]
I use in my configuration "dbimage: drud/ddev-dbserver:v1.6.0-10.1" and it works fine. 
If I try to check the version with 'ddev version', i will get the information:

bgsync        	drud/ddev-bgsync:v1.6.0       
cli           	v1.6.0                        
commit        	v1.6.0                        
db            	drud/ddev-dbserver:v1.6.0-10.2
dba           	drud/phpmyadmin:v1.6.0        
ddev-ssh-agent	drud/ddev-ssh-agent:v1.6.0    
docker        	18.09.3                       
docker-compose	1.23.1                        
domain        	ddev.local                    
router        	drud/ddev-router:v1.6.0       
web           	drud/ddev-webserver:v1.6.0

**Comment by rfay** [comment]
Thanks for this issue! ddev reports the compiled defaults for images, not the overridden image versions. But I think it would be better for it to work like you expected it to work.

**Comment by rfay** [comment]
I added this into #960, so will close this here in favor of improving `ddev version` there.
