### ISSUE TITLE
Clean up ddev release process

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1516]
**Describe the bug**

Our releasing process isn't what we'd like it to be. It's much harder than ever before, mostly due to incomplete homebrew process and incomplete choco process.

* Fix docs for trigger_release.sh so they reflect actual usage
* Automate the homebrew bottle creation process. It's possible that goreleaser (which has automatic homebrew built in) could do more of the process for us.
* Fix choco push process so it can be done automated, or at least documented correctly.

**Comment by rfay** [comment]
First major step, automatically building the homebrew bottles, went in with #1524. 
Docs for trigger_release.sh have also been updated.

Now:
* Better docs (or technique) for pushing to chocolatey
* Automatic update of homebrew? Or at least PR creation?
* Automatic push to AUR? @cweagans  ?

**Comment by cweagans** [comment]
@rfay automated AUR push would be awesome. I'm not going to be able to do that for a while, but I can help with info/access in the mean time. I'll put this on my todo list for 1-2 months from now.

**Comment by rfay** [comment]
This is good enough for now.
