### ISSUE TITLE
global omit_containers leaks into project omit_containers on `ddev config`

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1521]
**Describe the bug**

A user pointed out in slack some time ago that the global omit_containers can leak into/be replicated in the project .ddev/config.yaml

**To Reproduce**

`ddev config global --omit-containers=dba,ddev-ssh-agent`
`ddev config` a local project

`omit_containers: [dba, ddev-ssh-agent]` will show up in the project .ddev/config.yaml

**Expected behavior**

The global config shouldn't show up in the local

**Additional context**

This is a cautionary tale for anything we put in global with the exact same name as in local, and also we need to just learn to prevent the leakage. So this is not just a problem for omit_containers, but for anything we think might be in both places with the same name. Probably indicates a failure of how we build the "app" object.

**Comment by WarpedOne** [comment]
https://github.com/drud/ddev/issues/1456

**Comment by rfay** [comment]
Thanks, closing in favor of #1456 . I guess I thought it hadn't been captured in an issue. The general problem is blocking us from adding more things to global config, because we have to not have this happen with other things too.
