### ISSUE TITLE
Changing the email of the Pantheon user results in `Failed to get project(s): 401 Unauthorized: 401` error 

### ISSUE THREAD

**Issue by kreynen** [drud/ddev#1522]
**Describe the bug**
I'm not sure exactly what you'd add to https://github.com/drud/ddev/blob/master/docs/users/providers/pantheon.md, but I just lost an hour trying to figure this out. Hopefully this helps the next person who runs into this.

**To Reproduce**
1. With an existing ddev instance that's tied to Pantheon, change the email address of the Pantheon user used to generation the machine token
2. Run `ddev start`
3. You will get a `Failed to get project(s): 401 Unauthorized: 401` error

What's confusing is initially the instance is still running and you can still use something like `drush uli`, but `drush up` will result in the `Failed to get project(s): 401 Unauthorized: 401` error. `ddev restart` results in a `Failed to restart: 401 Unauthorized: 401` error.

The simple fix was to issue a new machine token and repeat that process. Just took me awhile to get there.

**Comment by rfay** [comment]
So it was in fact probably unauthorized/invalid token?

Do you think this is the same as https://github.com/drud/ddev/issues/728 ?

Thanks so much for the report.

**Comment by rfay** [comment]
No response from OP, so I'm going to assume it's the same as #728 (which has the workaround). Thanks for the report, closing, but happy to continue the conversation.
