### ISSUE TITLE
Improve `ddev list` command

### ISSUE THREAD

**Issue by beeradb** [drud/ddev#153]
## What happened (or feature request):
We haven't updated the `ddev list` command since we forked this from the original drud too. We did add the very helpful `ddev describe` which gives detailed information about a running site, but the `ddev list` command is lacking in several ways.

```
ddev/drupal8 ‹gke:drud-test› git:(master) ✗ » ddev list
1 local site found.
NAME   	TYPE   	URL                      	DATABASE URL   	STATUS
drupal8	drupal8	http://drupal8.ddev.local	127.0.0.1:32861	running

```

As you can see, there's no info about where the site is located, and it still uses the outdated database URLs

## What you expected to happen:
We should update the list command to provide more useful information. Here's what I suggest:

```
To get more detailed information, you can run `ddev describe [NAME]` on any site in the list.

NAME   	LOCATION                            	TYPE   	URL                      	STATUS
drupal8	/Users/beeradb/Projects/ddev/drupal8	drupal8	http://drupal8.ddev.local	running
```

**Comment by rfay** [comment]
I agree that the database URL can be moved out of here, and it's wrong anyway right, because we now have routing for it?

Please add:
* Check 'status' for reasonable values that are obvious. 

Do you think the LOCATION could be shortened somehow? I'd assume it will often be in ~, which saves some (and makes clearer). Not sure how to do that well or properly.

**Comment by tannerjfco** [comment]
We should be able to detect user's home dir and shorten for display.

I actually think we could do without TYPE as well to free up some space. Users tend to know what platform their site is, and we still have the info in describe.

**Comment by beeradb** [comment]
The homedir thing seems like an obvious win to me. As for removing type or finding other ways to shorten it, I'd be open but would love to see a need established before we jump to doing that (i.e. at what resolution/font size does this actually become an issue?).

**Comment by rickmanelius** [comment]
This is great. Feedback:

- Agreed on moving DB location. Users needing that can leverage `describe`.
- I'm torn on leaving "type" in. I agree with Tanner that it's likely obvious to the person building the site and something that can be pulled up in describe. On smaller screens (13" laptop), it might push things out a bit more. That said, I can see leaving it for now until we get more feedback from end-users.
- Love the ~/homedir idea.

So with bullet 2 being a coin flip IMHO, I think we're in agreement on everything else and we can proceed.

**Comment by rickmanelius** [comment]
PR is closed. Updating this to reflect that.
