### ISSUE TITLE
Windows 10 - nfsd: Unexpected status SERVICE_STOPPED in response to START control 

### ISSUE THREAD

**Issue by 4lxndr** [drud/ddev#1535]
Hello,

i just installed Ddev 1.7.1  and run through the setup for nfs support. The output:
```
$ ./windows_ddev_nfs_setup.sh
SERVICE_STOPPED
nfsd was already installed, starting it. You can configure its behavior with 'nssm edit nfsd'
nfsd: Unexpected status SERVICE_STOPPED in response to START control.
```

I checked as mentioned the event viewer:
```
Failed to start service nfsd.  Program C:\Programme\ddev\winnfsd.exe
C:\Program Files\ddev\winnfsd.exe couldn't be launched. CreateProcess() failed: System cant find the file
```

The `ddev debug nfsmount` shows:
```
$ ddev debug nfsmount
unable to access nfs mount: failed to StartContainer: API error (500): error while mounting volume '/var/lib/docker/volumes/testnfsmount/_data': error while mounting volume with options: type='nfs' device=':/C/Users/xyz/Desktop/test' o='addr=host.docker.internal,hard,nolock,rw': connection refused output=
``` 

BUT if i start winnfsd manually by ` winnfsd "C:\\"`:
```
$ ddev debug nfsmount
Successfully accessed NFS mount of C:\Users\xyz\Desktop\test
TARGET    SOURCE                       FSTYPE OPTIONS
/nfsmount :/C/Users/xyz/Desktop/test nfs    rw,relatime,vers=3,rsize=32768,wsize=32768,namlen=255,hard,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.65.2,mountvers=3,mountproto=tcp,local_lock=all,addr=192.168.65.2
/nfsmount/.ddev
```

I also added "NFS server for windows" to the firewall rules. 

Any ideas what the problem could be?

thx

**Comment by 4lxndr** [comment]
Seems to be a problem with the windows symlink (or whatever) `C:\Programme` VS `C:\Program Files`. After removing the service and adding it manually with `C:\Program Files\ddev\winnfsd.exe` the output of `$ sudo nssm status nfsd` is `SERVICE_RUNNING`. But `ddev debug nfsmount` still fails with: 
```
unable to access nfs mount: failed to StartContainer: API error (500): error while mounting volume '/var/lib/docker/volumes/testnfsmount/_data': error while mounting volume with options: type='nfs' device=':/C/Users/xyz/Desktop/test' o='addr=host.docker.internal,hard,nolock,rw': permission denied output=
```

**Comment by rfay** [comment]
@4lxndr did you go through the debugging steps https://ddev.readthedocs.io/en/stable/users/performance/#windows-specific-nfs-debugging ? It sounds like you don't have the right shares in ~/.ddev/nfs_exports.txt ? Since you ran winnfsd manually maybe you didn't run it with the pointer to the exports? You can, of course, use any exports file you want, or specify the exports on the command line. 

BTW, if you figure out the problem you had with a link I'd like to know about it. There is no reference in windows_ddev_nfs_setup.sh to "Program Files" or anything. Perhaps there's some kind of problem in the ddev windows installer?

**Comment by 4lxndr** [comment]
Hey @rfay thanks for getting in touch.

the main problem was nfsd with the state `SERVICE_STOPPED`. I cant reproduce the wrong path. The output of `which winnfsd` is saved to the variable in the shell script and it is `/c/Program Files/ddev/winnfsd`. I know it was somehow a different one in the first step but i cant repdoruce in the cmd neither in the git bash. 

Today i removed all the ddev stuff and installed the latest version again and executed the windows_ddev_nfs_setup script. Dont know why, but now its working 🤷‍♂️ 

Sorry for the trouble, i will install this awesome tool this week on couple of windows machines. Lets see. 

Keep the good work.

**Comment by rfay** [comment]
Thanks so much for studying this. We're super interested in your experience. It wouldn't surprise me at all if there were a problem with the "Program Files" as opposed to "Programme", I haven't seen that path before. Keep in touch!
