### ISSUE TITLE
TYPO3 8.7 Database Analyzer does not execute queries inside Install Tool

### ISSUE THREAD

**Issue by lmaxheim** [drud/ddev#1539]
**Describe the bug**
The database analyzer does not execute selected queries when TYPO3 is used with Maria DB 10.1.

**To Reproduce**
1. Start the project with `ddev start` 
2. Navigate to the TYPO3 install tool and switch to the Database Analyzer:
![1](https://user-images.githubusercontent.com/8383759/56286957-63546f80-611b-11e9-90fc-f9316288753a.png)
3. Select as many MySQL commands as you like and execute them:
![2](https://user-images.githubusercontent.com/8383759/56287009-8da62d00-611b-11e9-9205-1c22ec642afb.png)

**Expected behavior**
The install tool should now have executed the corresponding queries and thus updated the database.

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Ubuntu 18.04 bionic
 - Docker version information (use `docker version`) and insert it here.
        Client:
Version: 18.09.5
API version: 1.39
Go version: go1.10.8
Git commit: e8ff056
Built: Thu Apr 11 04:43:57 2019
OS/Arch: linux/amd64
Experimental: false

      Server:
Engine:
Version: 18.09.5
API version: 1.39 (minimum version 1.12)
Go version: go1.10.8
Git commit: e8ff056
Built: Thu Apr 11 04:10:53 2019
OS/Arch: linux/amd64
Experimental: false

 - ddev version information (use `ddev version`)
bgsync        	drud/ddev-bgsync:v1.6.0
cli           	v1.6.0
commit        	v1.6.0
db            	drud/ddev-dbserver:v1.6.0-10.2
dba           	drud/phpmyadmin:v1.6.0        
ddev-ssh-agent	drud/ddev-ssh-agent:v1.6.0    
docker        	18.09.5                       
docker-compose	1.23.2                        
domain        	ddev.local                    
router        	drud/ddev-router:v1.6.0       
web           	drud/ddev-webserver:v1.6.0 

 - config.yaml contents for the misbehaving project
APIVersion: v1.6.0
name: my-project-name
type: typo3
docroot: web
php_version: "7.1"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.1"
webcache_enabled: false
nfs_mount_enabled: false
provider: default

**Additional context**
Since TYPO3 is supported by DDev, I assumed that besides the development of templates and extensions, you also have the possibility to perform and test TYPO3 updates locally using DDev, similar to using XAMPP on a Windows computer. The [issue](https://github.com/drud/ddev/issues/985)  also affects the Install Tool, but the use case is different.

**Comment by rfay** [comment]
I'm unable to recreate your issue. I used a TYPO3 v8.7.20 generic install using MariaDB 10.1, then went to the installtool database analyzer and it happily executed the two queries that it needed to execute. 

Might this be specific to your particular project database? Have you tried it in another hosting environment? If you can share the project and database I can try it, but please do try it with a generic install and see how it does.

**Comment by lmaxheim** [comment]
Hi, 
I have created a new project to ensure that there are no issues in my previously posted environment, and performed the following steps to reproduce the bug:

1. Install TYPO3 via composer:
- https://get.typo3.org/version/8#downloadComposer
- `composer create-project typo3/cms-base-distribution my-new-project 8.7`
- Composer now installs the latest version of TYPO3 8.7 (8.7.24)

2. Setup DDev
- `ddev config`
- It generates the following configuration:
```
APIVersion: v1.6.0
name: hello-github
type: typo3
docroot: web
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
webcache_enabled: false
nfs_mount_enabled: false
provider: default
```
- Finally i changed the version of mariadb to "10.1"

3. Starting DDev with the configuration posted above
4. Next, i have performed the steps of the install tool wizard.

Now TYPO3 is installed. When I call the Install Tool now,  I can successfully reproduce the error described above by selecting any number of queries and clicking the execute button. The database analyzer is called again and no change is visible.

I am also irritated by the database version, which is shown in the overview:
![](https://user-images.githubusercontent.com/8383759/56298403-5ee78100-6132-11e9-8e75-5e7b76ed239f.png)

I don't know what I'm doing wrong here.

**Comment by rfay** [comment]
You cannot change the DB type to 10.1 *after* it's been created... Is that what I understood you did? You need to:

0. Please use ddev v1.7.1, as there were some weird bugs in v1.6.0 that affected mariadb_version.
1. Remove the database (`ddev rm -RO`)
2. Set the mariadb_version to 10.1
3. Install with 10.1
4. Test.

**Comment by lmaxheim** [comment]
After updating to 1.7.1 it works fine!
Thank you very much, you saved my day!
