### ISSUE TITLE
Rename rm and ssh commands

### ISSUE THREAD

**Issue by tannerjfco** [drud/ddev#154]
## What happened (or feature request):
Feature request. Currently, the majority of our command names are full word or close to it, which helps provide clarity to their intent. This is not the case for two of our commands, rm and ssh, and while I don't think it's hard to understand what these commands are for, they could still be clearer.

## What you expected to happen:
I propose that

1. "rm" be renamed to "remove", with "rm" as an alias.
2. "ssh" be renamed to "shell", with "sh" as an alias.  Another option could be to rename to "login".

## Related source links or issues:

**Comment by rfay** [comment]
I'd personally like to keep ssh as an alias :) Just so natural, and based on vagrant usage.

**Comment by tannerjfco** [comment]
Adding aliases is trivial, I'm fine keeping ssh as one. Thinking a bit more on this though, perhaps we should remove the "ssh" command entirely and use "exec" for both purposes? I don't think it would be difficult to do.

**Comment by beeradb** [comment]
I agree with moving rm -> rename, but not so much with ssh.

SSH is the common term for that functionality. No one says "Secure shell" or "shell" in every-day use. I'm fine with adding aliases if we feel it needs clarity, but "ssh" is the best term for that functionality and is more clear than the alternatives.

**Comment by rickmanelius** [comment]
I like the idea of the longer (and clearer) name with the shorter alias for remove.

I agree with Randy and Brad. SSH is a common term and a command. It also denotes what is being done whereas shell implies the outcome and sh could be confused with running a shell script.

**Comment by tannerjfco** [comment]
I've opened #223 to rename the rm command. I have no objection leaving the ssh command as is.

**Comment by rickmanelius** [comment]
@tannerjfco I assume there is nothing left for this one? Please close if it's complete!

**Comment by tannerjfco** [comment]
rm has been renamed, ssh was not, and i'm fine with that. closing.
