### ISSUE TITLE
Custom mysql / mariadb cnf file prevent container restart

### ISSUE THREAD

**Issue by cmonard** [drud/ddev#1541]
When providing custom mysql configuration in :
.ddev/mysql/myconf.cnf

The file is used on first start, but when you stop+start / restart ddev, the db container can't start cause it's unable to overwrite the custom file. 
If you connect db container : 
ddev ssh --service=db
and try to list mysql conf.d directory you will notice the file in 444 mode :
ls -al /etc/mysql/conf.d/myconf.cnf
will output (for example) : 
-r--r--r-- 1 uid_501 gid_20 175 Apr 17 08:31 myconf.cnf

1. Add special configuration for mysql
2. Start then Stop ddev
3. Start again and...

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macOS Mojave - 10.14.4
 - Docker version information: 18.09.2
 - ddev version information: v1.7.1
 - config.yaml contents for the misbehaving project: no modification from default file

**Comment by rfay** [comment]
Thanks for this report, somebody noticed that and pointed out in slack the other day, maybe you.

The very simple workaround is use the superior `ddev rm && ddev start` and it will be OK. 

I still think we should fix this.

**Comment by rfay** [comment]
One mitigating factor is that as things look right now, in the next release, `ddev restart` will not cause this problem, and neither will `ddev stop && ddev start`. However, `ddev pause && ddev start` still would (next release)

**Comment by RobertLang** [comment]
I can confirm that this error happens under the same versions of MacOS, docker and docker-compose as above when using `ddev restart`.
`ddev rm && ddev start` fixes the error.

It seems to be some sort of file permission issue as the log shows following:
```
++ echo /mnt/ddev_config/mysql/no_utf8mb4.cnf /mnt/ddev_config/mysql/nostrict.cnf
+ '[' -d /mnt/ddev_config/mysql -a '/mnt/ddev_config/mysql/no_utf8mb4.cnf /mnt/ddev_config/mysql/nostrict.cnf' '!=' '/mnt/ddev_config/mysql/*.cnf' ']'
+ cp /mnt/ddev_config/mysql/no_utf8mb4.cnf /mnt/ddev_config/mysql/nostrict.cnf /etc/mysql/conf.d
cp: cannot create regular file '/etc/mysql/conf.d/no_utf8mb4.cnf': Permission denied
cp: cannot create regular file '/etc/mysql/conf.d/nostrict.cnf': Permission denied
```
