### ISSUE TITLE
Add example config files for additional services to the main "ddev config" operation

### ISSUE THREAD

**Issue by damienmckenna** [drud/ddev#1548]
**The problem**
The documentation provides details on enabling additional services. However, installing additional services, like Solr, requires knowing where to find documentation and then finding additional configuration files.

**Requested solution**
Add the configuration files for each supported additional service to the .ddev directory after running "ddev config", with the necessary lines commented out so that they don't install unless modified; improve the inline documentation of these files to explain how to use them.

**Comment by rfay** [comment]
Thanks for the suggestion. I guess I've always assumed that our suggested docker-compose.*.yaml are too simple for real usage, and that people want to do way more than our suggested examples. There's some real merit here though.

**Comment by WebsiteDeveloper** [comment]
Another option would also be to basically ask which features should be added automatically like vue-cli
See: https://cli.vuejs.org/guide/creating-a-project.html#vue-create

**Comment by rfay** [comment]
FYI this suggestion resulted in example Dockerfile.example's in the v1.8.0 custom container build feature. So it's already having an impact. Thanks!

**Comment by rfay** [comment]
Closing in favor of the more ambitious https://github.com/drud/ddev/issues/3068 - that one actually moves to maintained recipes and installs with a ddev command.
