### ISSUE TITLE
Add a "ddev mysql" command

### ISSUE THREAD

**Issue by dmitryd** [drud/ddev#1551]
While `ddev exec --service db mysql` is documented, it would be much easier & faster to type `ddev db` for this. Could you implement it, please?

Thanks!

**Comment by rfay** [comment]
Could you say more about what you use the mysql command for? It sounds like you must do it a lot. 

Note that there are so many ways to access the database:
* Use it on the host (`ddev describe` shows how)
* Use it in the web container (`ddev exec mysql`)
* Use phpmyadmin (see `ddev describe`)
* Use `ddev sequelpro` (macOS only)
* (I personally use `ddev ssh` and just use mysql in the web container)

**Comment by mglaman** [comment]
I find myself having to 

```
ddev ssh
../vendor/bin/drush sqlc
```

or I use `ddev describe` to put the port in DataGrip. I would like to see a `ddev db` shortcut. Platform.sh has `platform sql` as their shortcut to launch into the database CLI.

**Comment by rfay** [comment]
I don't object... but 
FYI, 
* `drush sql-cli` works fine **on the host** if you have drush8 on the host. 
* You don't have to use vendor/bin because the drush launcher shipped in the container works fine
* Since v1.7.1 it's possible to force the port that the db container binds to, so it's easy to use other tools. 

And come to think of it, I don't know why we never provided a direct mysql command, since it's right there in `ddev describe`

Just making noise about options.

I guess I didn't really understand the OP. What's being asked for is a simple command like `ddev sequelpro` that uses mysql in a one-shot I guess.

**Comment by rfay** [comment]
Interested in what the votes would be for the name of a command. `ddev mysql` ?

**Comment by dmitryd** [comment]
@rfay I am an advanced sql user and I prefer console. Launching Sequel Pro or typying a long command (`ddev exec .......`) for something as trivial as launching a mysql console for making several analytical queries is an overkil. The purpose of every environment (including `ddev`) is to simplify the life for people and make them focus on their real tasks. Thus adding a `ddev db` would give access database to those, who prefer a low level, direct sql database access.

**Comment by rfay** [comment]
Thanks for helping me understand @dmitryd - 

The reality is we're long overdue for allowing a tty and interactive behavior on `ddev exec`. I wonder if just `ddev exec mysql` with interactive behavior would do the job for most of us. 

(I use mysql as you do, almost never use another tool. My habit is to `ddev ssh` and then use it (from the web container). We certainly should have easier ways though.

**Comment by rfay** [comment]
Just FYI https://github.com/drud/ddev/pull/1571 allows easy `ddev exec mysql` and things like `ddev exec vi index.php`

**Comment by mglaman** [comment]
I would be happy with `ddev exec mysql`; because I have tried `ddev exec drush sqlc` as a short cut as well.

**Comment by rfay** [comment]
#1571 also makes `ddev exec sqlc` work fine, along with other drush commands that want interaction.

**Comment by selwynpolit** [comment]
Perhaps using a drush alias would make this easier.  Something like `drush @d8git.dev sqlc` would be consistent with drush usage elsewhere. I often use drush aliases to issue commands to Drupal on remote servers.  It seems that it shouldn't be too difficult to set up a drush alias for a drupal 8 site.  I'm hitting some snags tho.  It looks like the command to ssh into a docker container is something like: 
`docker exec -it b20ef7e7d141 bash`
I need something more along the lines of ssh user@server
Any suggestions?

**Comment by rfay** [comment]
You'll want to use `ddev exec` I would think. Note that drush also works on the host for many commands. But there's no ssh server inside the web container, so you can't use real ssh.
