### ISSUE TITLE
Place database to the local file system on macOS

### ISSUE THREAD

**Issue by dmitryd** [drud/ddev#1552]
Docker on macOS places its file system in a single file, which mostly grows. It is extremely hard to shrink this file (only manually, black magic, easy to break docker). For example, it is 42GB in my installation, while actual allocated space there is just 6GB right now, so 36GB is a waste from previous containers.

When there are a lot of database requests (like logging to the database), that docker file system file may grow a lot. Remove that database but its space in the docker file system will never be free again.

It makes sense by default to map mysql database directory to a local file system. This will keep docker file system allocation under control.

Please, consider mapping mysql volume to a local file system inside `./.ddev` on macOS.

**Comment by rfay** [comment]
Actually, it was there until maybe a year ago. Docker unfortunately does bind-mounted volumes quite differently on various operating systems, so it was a nightmare to maintain and had serious performance problems as well. But yes, that's the history of ddev's database - it was always bind-mounted.

I recommend you try out `ddev snapshot` and `ddev remove --remove-data` and `ddev restore-snapshot <snapshotname>` from time to time, that kills off the volume. (Of course, just export and import of the database is fine as well)

**Comment by rfay** [comment]
No response yet from OP, closing. Happy to continue the conversation here.
