### ISSUE TITLE
Ddev v1.7 creates ddev_drush_settings.php in wrong place

### ISSUE THREAD

**Issue by rthideaway** [drud/ddev#1553]
With 1.7 update the ddev starts to place `ddev_drush_settings.php` in wrong directory. It places it into directory where you are when running `ddev start`:
```
user@pc:/var/www/project$ ddev start && realpath ddev_drush_settings.php
/var/www/project/ddev_drush_settings.php
```

Another example by stepping to different folder:
```
user@pc:/var/www/project$ cd backend && ddev start && realpath ddev_drush_settings.php
/var/www/project/backend/ddev_drush_settings.php
```

With previous 1.6 version it placed the file to the same folder where other settings files were, namely to `docroot/sites/default`. Now this does not work.

**Comment by rthideaway** [comment]
Forgot to mention we use drupal8 project type.

**Comment by rfay** [comment]
Thanks so much for the report!

**Comment by rfay** [comment]
Thanks so much for pointing this out. #1554 should solve it. It was an odd one.
