### ISSUE TITLE
custom PHP configuration for apache-cgi has no effect

### ISSUE THREAD

**Issue by igaumann** [drud/ddev#1556]
when i use apache-cgi as webserver_type the custom PHP configuration .ddev/php/ has no effect.

**Comment by rfay** [comment]
Thanks for the report, it was easy to confirm. https://github.com/drud/ddev/pull/1557 fixes it.

**Comment by rfay** [comment]
@igaumann could you say why you use apache-cgi? I thought basically nobody uses it. Your reasoning helps us to understand how people use ddev.

**Comment by rfay** [comment]
Thanks so much for reporting this @igaumann - it will be fixed in the next release. 

I'd still love to hear why you choose apache-cgi, and how it works for you.

**Comment by igaumann** [comment]
At my hoster I could only adjust the php values via the htaccess and I had problems using the same htaccess with apache-fpm (ddev 1.3.0). Therefore, the web server was still set in the config.yaml. Now there are no problems anymore.

**Comment by rfay** [comment]
Thanks so much, that helps me understand. Of course you need a new hoster... but that's in your hands :)
