### ISSUE TITLE
Access to Roadmap wiki page is denied

### ISSUE THREAD

**Issue by vmmello** [drud/ddev#1564]
Hi,

The link to the roadmap wiki page as linked from the current **README.md** file is returning the following error message at the top of the page when visiting the URL:

```
You do not have permission to update this wiki.
```

I was just trying to view the page by clicking on the link referenced on the readme file (I was not trying to update the page), but it returns that message and doesn't show the roadmap page.

Is the Roadmap page still supposed to be available? If so, maybe there's a permission problem.

Thanks in advance.

**Comment by rfay** [comment]
Thanks. It seems to have been deleted, so is giving you that error because it thinks you want to create it. We have roadmap work in progress, so will plan to recreate it.

Do you have things that you think should be on the roadmap?

**Comment by rfay** [comment]
I recreated the roadmap page (but just with "coming soon"), and we'll be starting it over again in coming weeks. We've had a couple of roadmap meetings.
