### ISSUE TITLE
allow to define default db and asset collection of files (folder zip) for initial startup

### ISSUE THREAD

**Issue by kaystrobach** [drud/ddev#1567]
**Is your feature request related to a problem? Please describe.**

I just want, that if there is no existing database / files and automated import is made.

**Describe the solution you'd like**

define a sql / sql.gz file and a zip file, which gets imported on the first start

**Describe alternatives you've considered**

start / stop hooks

**Additional context**

**Comment by rfay** [comment]
I like it. Would it just be a file with a magic name that was loaded on `ddev start` if there were no tables in the `db` database?

**Comment by kaystrobach** [comment]
jepp, we can also have a convention (over configuration), so that:

* .ddev/defaults/assets.zip
* .ddev/defaults/sqldump.sql

will be importet

**Comment by rfay** [comment]
It would be harder to determine whether assets were already loaded. And for most people, since they reside with the code, that's a one-time thing anyway.

**Comment by kaystrobach** [comment]
the alternative would be a hook, which is only executed in a freshly installed volume, this would make live easier in many cases, as this hook could also execute the import command

**Comment by rfay** [comment]
I just noticed that this issue is still open. There has been a nice recipe for this for a long time in https://github.com/drud/ddev-contrib/tree/master/hook-examples/import-db-if-empty, and it's extensible for anybody who wants this behavior. I'm going to say that that's good enough and close this.
