### ISSUE TITLE
Download code does not fail properly when file unavailable

### ISSUE THREAD

**Issue by rfay** [drud/ddev#157]
## What happened (or feature request):

[system.DownloadFile()](https://github.com/drud/ddev/blob/a9b3e2d2a65d8bce746b0ad361b3559a05f14138/vendor/github.com/drud/drud-go/utils/system/system.go#L66-L89) (from drud-go) doesn't handle a missing target asset correctly; it downloads a file saying "404" or something like that. This is used extensively in our testcommon stuff and results in failure after-the-fact in the untar section.

The problem is with our use of http.Get()
>// An error is returned if there were too many redirects or if there
>// was an HTTP protocol error. A non-2xx response doesn't cause an
>// error.

So we need to figure out how to handle the case of non-200 correctly, because we're definitely not doing it right now.

## What you expected to happen:

A download attempt against a non-available asset should result in an error.

## How to reproduce it (as minimally and precisely as possible):

This happens every time our tests run, in TestInvalidTestSite - the download "succeeds" but the untar fails, because the file actually obtained is not a tarball. The resultant "tar file" contains just "404: Not Found"

```
$ cat /private/var/folders/db/741gx8tj20d5z1f3zjpvw2vh0000gp/T/drupal8download868081747/drupal8.tar.gz
404: Not Found
```

## Anything else do we need to know:

This code actually resides currently in drud-go. It's worth considering pulling it into our own pkg/lib

## Related source links or issues:

**Comment by tannerjfco** [comment]
Fixed in #291
