### ISSUE TITLE
DDEV deleted everything in my home directory

### ISSUE THREAD

**Issue by jpoesen** [drud/ddev#1574]
**Describe the bug**

DDEV seems to have picked up the wrong directory path and nuked everything in my home directory rather than in the new project directory.

* Just finished installing docker, docker-compose, ddev on a relatively new laptop.
* Tried to initialise a new D8 project.
* Followed the steps as described in the docs at https://ddev.readthedocs.io/en/stable/users/cli-usage/#drupal-8-quickstart.

**To Reproduce**
```
 $ ~/projects  mkdir d8site

 $ ~/projects cd d8site 

 $ ~/projects/d8site ddev config --project-type php --php-version 7.1
You are reconfiguring the project at /home/jpoesen. 
The existing configuration will be updated and replaced. 
Found a php codebase at /home/jpoesen/projects/d8site 
Project type has no settings paths configured, so not creating settings file. 
Configuration complete. You may now run 'ddev start'. 

~/projects/d8site ddev composer create drupal-composer/drupal-project:8.x-dev --stability dev --no-interaction
Warning: Any existing contents of the project root (/home/jpoesen) will be removed 
Removing any existing files in project root 
Failed to create project: permission denied 
```

Because of 'no-interaction', at this point everything in /home/jpoesen is erased. 
If I had run this without no-interaction I might have spotted that /home/jpoesen was about to get nuked.

**Version and configuration information (please complete the following information):*
- Host OS: ubuntu bionic
- Docker version 18.09.5, build e8ff056
- ddev v1.7.1

Happy to help troubleshoot. As long as the root cause (which may well be something on my end) is not found, I can't trust ddev anymore, understandably, since all my downloads, project files, ... got nuked.

Thanks.

**Comment by rfay** [comment]
Oh my goodness. You somehow had a ~/.ddev/config.yaml in your home directory, and it thought that was the project directory. You had probably accidentally done a `ddev config` earlier in your home directory. 

We haven't had a report of this before, but it's pretty obvious what happened, and really sorry that happened! And thanks for the clear description, and for actually capturing the output. I wouldn't have ever been able to understand it without seeing `You are reconfiguring the project at /home/jpoesen`

**Comment by rfay** [comment]
I guess the bogus ~/.ddev/config.yaml got destroyed for you as part of this disaster so we don't have to worry about that again. :(

**Comment by jpoesen** [comment]
Thanks rfay. I did indeed have a .ddev directory in my home folder. I have no idea how it got there. I may have accidentally done a ```ddev config in there```, who knows. Also don't know why it lingered after the nuke.

I'll accept that this is mostly my fault, but it would be nice if there were some way ddev could check for the existence of a .ddev directory on your home folder and/or detect if it's about to delete everything in /home/${USER}...

**Comment by rfay** [comment]
There *should* be a ~/.ddev, but it shouldn't have a config.yaml, there's a global_config.yaml in there though. 

It's not even partly your fault, it's a bad bug IMO, so sure appreciate you describing it so well.

**Comment by jpoesen** [comment]
I tried to check ```history``` to see if I could spot if I did anything wrong, but of course, that's gone too, together with the whole bashrc / zsh config and such :/

**Comment by rfay** [comment]
Things that can be done to prevent this:
* Don't allow `ddev config` in home directory
* Don't allow config to accept finding ~/.ddev/config.yaml
* Consider reverting [#1275 Look in parent directories for an existing .ddev/config.yaml, fixes](https://github.com/drud/ddev/pull/1275). Probably should seriously consider it.

I'm not sure we can properly prevent discovery of unintended parent directories,

**Comment by jpoesen** [comment]
Thanks. I deleted ~/.ddev, reinstalled ddev, and initialised a new project without error.

Thanks for the quick response, much appreciated. This is a very nasty side effect, so I also greatly appreciate you're serious about thinking of ways to prevent this for others.

This issue is resolved for me. I'll let you close / reassign / ... 
J.
