### ISSUE TITLE
phpMyAdmin - Error

### ISSUE THREAD

**Issue by ldavidsp** [drud/ddev#1577]
error when accessing phpmyadmin with port 8036, mysqli extension not found.
![image](https://user-images.githubusercontent.com/44006503/57380671-a75cf200-7166-11e9-9bf2-924afee5d830.png)

**Comment by rfay** [comment]
No response from OP, closing, but happy to continue the conversation, and would love to hear more about the situation you encountered @ldavidsp , maybe it's the language of the browser or something?
