### ISSUE TITLE
Fixed order of "additional_hostnames" output on ddev start 

### ISSUE THREAD

**Issue by diteljuice** [drud/ddev#1580]
When starting DDEV, at the end all available `additional_hostnames` are listed ("Successfully started XXX - Project can be reached at"). The ordering seems to be random, the position of the hostnames vary from start to start.
Finding a host address when using a lot of host names (i.e. multi domain installations or subdomains) can be pretty annoying.

**Comment by rfay** [comment]
That sure seems reasonable to me!
