### ISSUE TITLE
"ddev exec drush" hardcodes certain responses?

### ISSUE THREAD

**Issue by damienmckenna** [drud/ddev#1584]
**Describe the bug**
This may be fixed in 1.8.0, I have not tested the latest codebase yet..

A common practice I have is to use "drush upc -n" to work out what updates are available, before deciding which updates to download. With ddev this is not possible as it seems it detects when drush is being executed and passes the "-y" argument to skip all prompts.

**To Reproduce**
* Run `ddev exec drush upc -n`
* Expected results: a list of available updates is presented, but none are applied.
* Actual results: all available updates are applied.

**Expected behavior**
No updates are applied when the "-n" argument is passed to `ddev exec drush upc`.

**Version and configuration information (please complete the following information):**
```ddev version
bgsync        	drud/ddev-bgsync:v1.7.0       
cli           	v1.7.1                        
commit        	v1.7.1                        
db            	drud/ddev-dbserver:v1.7.0-10.2
dba           	drud/phpmyadmin:v1.7.0        
ddev-ssh-agent	drud/ddev-ssh-agent:v1.7.0    
docker        	18.09.2                       
docker-compose	1.23.2                        
domain        	ddev.local                    
router        	drud/ddev-router:v1.7.0       
web           	drud/ddev-webserver:v1.7.0
```

**Comment by rfay** [comment]
This is actually a long-run deliberate behavior, but it's definitely time to come out. When in `ddev exec` context (more for exec hook context) `drush` defaults to -y. It was really never right, I never really quite understood why we did it, but thanks for bringing it up and let's get it out of there!

**Comment by rfay** [comment]
#1586 should fix this... in fact I just did my 7.67 upgrades with it. Thanks for pointing it out.

I've been working around that problem for a year and a half of Drupal upgrades by just using `ddev ssh` and using drush inside. But now that with v1.8.0 we'll have interactive drush, it's mighty nice to have the interactive behavior and lose the --yes.

**Comment by damienmckenna** [comment]
Thanks rfay!
