### ISSUE TITLE
install_ddev.sh should be able to install a named version

### ISSUE THREAD

**Issue by alesrebec** [drud/ddev#1587]
v1.8.0-rc1 cannot be installed because https://github.com/drud/ddev/releases/latest in https://github.com/drud/ddev/blob/v1.8.0-rc1/scripts/install_ddev.sh is not returning the last (1.8.0-rc1) release.

I think install_ddev.sh should have a way to install the version you want, not always the lastest version (which is preventing us to install rc versions).

cc @rfay

**Comment by rfay** [comment]
Thanks. Yeah, install_ddev.sh isn't really up for a lot of things. The reason it doesn't install the rc is that the rc is a *prerelease*, so doesn't show up as the latest release. 

I agree that allowing it to specify a specific release (even a prerelease) is the way to go. The goal, of course, is to never have anybody accidentally install something that's not fully released, but to make it easy for people to test. And it can be a hard balance, and certainly not one that's achieved yet.

**Comment by Davesjoshin** [comment]
Almost asked for the same thing. Is there a way to modify that install_ddev to allow this meanwhile?

**Comment by rfay** [comment]
I recommend just downloading the tarball for your OS and untarring/unzipping and copying the ddev binary on top of the existing one.  If you installed on macOS or Linux with the install.sh, that's going to be in /usr/local/bin. So untar, then `ddev stop -a --stop-ssh-agent`, then `cp ddev /usr/local/bin` (requires sudo on Linux). That's all there is to it.

I'd be interested to know why you don't want the latest version though, is there something that is blocking you?

**Comment by Davesjoshin** [comment]
Thank you, we will try this.

To answer your question, we have custom inits set up for our projects and we have a lot of projects. So we can’t update unless we know it’s going to work. Right now our set up doesn’t work with 1.10, which we are currently figuring out. The ability to install the desired version would help with this testing.

**Comment by rfay** [comment]
Thanks for letting us know about the issue. We'd be happy to help you figure out what's going on with 1.10 as well. I always recommend homebrew for Linux and macOS, but it isn't that good at installing older versions either.
