### ISSUE TITLE
Sentry prevents using DDEV when offline

### ISSUE THREAD

**Issue by mglaman** [drud/ddev#1601]
**Describe the bug**
When offline, connection to Sentry.io causes app to crash.

**To Reproduce**
1. Disable network connections
2. Run ddev start

**Expected behavior**
🎉 works as expected

**Screenshots**

```
Post https://sentry.io/api/160826/store/: dial tcp: lookup sentry.io on [::1]:53: read udp [::1]:59231->[::1]:53: read: connection refused
```

**Comment by rfay** [comment]
Shucks, sorry that happened to you.

Workaround: Turn off sentry either in ~/.ddev/global_config.yaml or via `ddev config global --instrumentation-opt-in=false`

It will be interesting to see what we can figure out.

**Comment by mglaman** [comment]
Actually I think it's a somewhat random happening. I didn't omit the ssh agent from a project (most do.) Docker tried to pull the image for 1.8 and timed out due to there being no connection. Running ddev start again threw the Docker error and then the Sentry.io error.

So, I'm assuming ddev would have failed anyways on the failed image pull. 

Once I commented out the container it worked again. I was just offline for a while and couldn't follow up with my original issue.
