### ISSUE TITLE
Remove a project which has a status of 'not found'

### ISSUE THREAD

**Issue by 24ma13wg** [drud/ddev#1603]
Somehow, my project appeared in duplicate on running `ddev list`. I removed the project with `ddev remove foo`. Now my project is listed just once with the _STATUS_ of _not found_, but I cannot find a way to remove this.

How can I remove this project also? My intention is that when I next run `ddev start foo` my project will be listed only once.

**Comment by rfay** [comment]
Hi - You have a container that somehow got orphaned. I"m surprised that `ddev remove <project>` doesn't work for you the second time, but:

I recommend `ddev remove -a` - that may do it for you. But you don't mention what version of ddev you have. 

What I usually do with a tricky docker situation is `docker stop $(docker ps -q) && docker rm -f $(docker ps -aq)`  - try that, but only if it's only ddev you have running, that will stop all docker containers, so if you have another docker application you'll have to think more carefully.

**Comment by 24ma13wg** [comment]
Running `ddev remove -a` returned: _Failed to stop containers for foo: no project to stop_, but `docker stop $(docker ps -q) && docker rm -f $(docker ps -aq)` removed it. On running `ddev start` I now have just a single project listed. This problem began when I renamed the root folder of my project. My version is:
```
bgsync          drud/ddev-bgsync:v1.7.0       
cli             v1.7.1                        
commit          v1.7.1                        
db              drud/ddev-dbserver:v1.7.0-10.2
dba             drud/phpmyadmin:v1.7.0        
ddev-ssh-agent  drud/ddev-ssh-agent:v1.7.0    
docker          18.09.2                       
docker-compose  1.23.2                        
domain          ddev.local                    
router          drud/ddev-router:v1.7.0       
web             drud/ddev-webserver:v1.7.0
```
All is good now. Thanks.
