### ISSUE TITLE
Missing error check on docker-compose actions (or at least ddev rm)

### ISSUE THREAD

**Issue by rfay** [drud/ddev#161]
## What happened (or feature request):

I was doing an 'rm' on a site, but I had introduced an error in the docker-compose.yaml, and ddev informed me that it was successful:

```
$ ddev rm
ERROR: The Compose file '/Users/rfay/workspace/randyfay/.ddev/docker-compose.yaml' is invalid because:
Unsupported config option for services.local-randyfay-web: 'group'
Successfully removed the randyfay application.
```

## What you expected to happen:

An error + failure should have been emitted.

## How to reproduce it (as minimally and precisely as possible):

Introduce an error in a running config and try a ddev rm.

## Related source links or issues:

**Comment by tannerjfco** [comment]
Were the containers still removed despite the failure? If so I'm thinking this behavior is a result of the extra cleanup logic that exists to remove containers if no compose file exists. https://github.com/drud/ddev/blob/master/pkg/plugins/platform/local.go#L448

**Comment by rfay** [comment]
No, the containers weren't removed. After I fixed the error and re-ran the command they were removed.
