### ISSUE TITLE
.gitignore mismatch on Linux/case-sensitive filesystem if webimage_extra_packages is used

### ISSUE THREAD

**Issue by andreasfernandez** [drud/ddev#1610]
**Describe the bug**
The `.gitignore` file gets a new entry called `/.webImageExtra`. On a case-sensitive file system (most likely when running on Linux), this doesn't work, as the directories name is actually `/.webimageExtra`.

**To Reproduce**
0. Have a case-sensitive file system
1. Make use of `webimage_extra_packages` (`webimage_extra_packages: [php7.2-ldap]` in my case)
2. Run `ddev start`
3. `git status` lists `.webimageExtra` as "untracked"

**Expected behavior**
The directory `.webimageExtra` should be correctly ignored and not listed as "untracked".

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Fedora Linux 30
 - Docker version information: 19.03.0-beta4
 - ddev version information: v1.8.0 
 - config.yaml: https://pastebin.com/tcZb6dXt

This issue might occur with `dbimage_extra_packages` as well.

**Comment by rfay** [comment]
Thanks for catching this and reporting.
