### ISSUE TITLE
Disable http links after successful startup (and in ddev describe)

### ISSUE THREAD

**Issue by diteljuice** [drud/ddev#1612]
**Is your feature request related to a problem? Please describe.**
With the release 1.8.0 it's quite easy to use SSL certificates in DDEV. So I would like to have the option the disable the http hostnames after successful DDEV startup.
This might be no bigger problem when using one or two additional hostnames. But in a multidomain installation (i.e. TYPO3) this can get very confusing. When working with for example 10 hostnames the list will grow to 20 URL's.

**Describe the solution you'd like**
Implement an option in the config.yaml like:
- list_https_only: true
- list_http_hostnames: false

**Additional context**
![Bildschirmfoto 2019-05-21 um 09 59 30](https://user-images.githubusercontent.com/34167544/58078510-33333d00-7baf-11e9-8812-9f96ae6aecd4.png)

**Comment by rfay** [comment]
That's a lot of URLs!

**Comment by diteljuice** [comment]
Yes it is. ;)

Using TYPO3 it is not totally uncommon to have multidomain installations. It's a key feature of the CMS.
One installation I manage has about 40 domains configured. ;)

**Comment by rfay** [comment]
It seems to me like with that many hostnames, just the https URLs would be too many.   I wonder if there's a more elegant solution to this, somehow trimming the total names. Note, of course, that `ddev list` only shows the main project URLs

**Comment by diteljuice** [comment]
Using Z-Shell (zsh) it's possible to open an URL by mouse click on mac OSX. Even with a lot hostnames I know where a specific URL is located, but it would be nicer to just turn the unused http hostnames off, for better readability. 
For people who do not need the hostnames at all, they could turn it off completely (`disable_hostname_list`).
What do you think @rfay?

**Comment by rfay** [comment]
With iterm2 I always open with a mouse click (on bash). 

Unfortunately, the http URLs won't be "unused" for everybody, because they may not take the time to set up mkcert, or may not care about http. 

I think a config might work. Always hate to add extra configs every time a problem needs to be solved, but will consider it!

**Comment by diteljuice** [comment]
You're right. But I think it's about making things comfortable. It's no a importent thing though

**Comment by rfay** [comment]
I added the request to shorten the list in ddev describe as well. 

But it seems to me that this is still just a general problem for people who use a lot of hostnames. http/https is one way at it, but it's a more general problem.

**Comment by kaystrobach** [comment]
Another option would be to have a project starting page like old xampp.

This can be easily created with php from the env vars 🤔 and served via http(s)

**Comment by rfay** [comment]
I remember xampp from back in the day, but don't remember the project starting page. Wouldn't we want the project itself to control the project starting page? I'm interested!

**Comment by kaystrobach** [comment]
I’ll do a mock in the next days. Get me some time.

Btw. I would also prefer to deprecate the project type and move that into composer packages, which read and provide env vars. ... just thinking.

**Comment by kaystrobach** [comment]
Regarding the mock do you have marketing rules for ddev? Logo colors, styles?

**Comment by rfay** [comment]
Not all project types even use composer, or use it in a way that would fit your conception. I think https://drive.google.com/open?id=130w1nJvIajYi_UmuJ1BRFxiCU5zmRixg is the best logo stuff at this point.
