### ISSUE TITLE
mysql --execute option via ddev exec mysql -e not working anymore

### ISSUE THREAD

**Issue by progmirosMA** [drud/ddev#1613]
**Describe the bug**
```dddev exec mysql -u db -pdb db -e "<some statement>"``` used to work. 
Now ddev seems to strip the doublequotes and exits with:
```Failed to execute command mysql -u db -pdb db -e <some statement>: exit status 1```

**To Reproduce**
1. Go to any ddev container
2. Execute a Statment from outside the container like ```ddev exec mysql -u db -db db -e "select * from table_xx;"``` 

**Expected behavior**
the sql statement should be executed

**Version and configuration information (please complete the following information):**
 - macOS Mojave 10.14.5
 - Docker Desktop Community 2.0.0.3, Channel: stable
 - ddev 1.8.0

config.yaml
```
name: <projectname>
type: php
docroot: pub
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: true
provider: default
```

**Comment by rfay** [comment]
This is due to quoting on the host and also in the container, since `ddev exec` is now executed by  bash inside the container.

For your example, please use

`dddev exec 'mysql -u db -db db -e "<some statement>"`

Simpler (the user and pass and database are default):

`ddev exec 'mysql -e "SHOW TABLES;"'`

**Comment by progmirosMA** [comment]
How to escape singlequotes in the statement?

```ddev exec 'mysql -e "update this set that = '1' where something = '2';"'```

would be:

```ddev exec 'mysql -e "update this set that = '"'"'1'"'"' where something = '"'"'2'"'"';```

**Comment by progmirosMA** [comment]
not nice, but someone saves to type "ddev ssh". hey! :-)

**Comment by rfay** [comment]
Also `ddev exec 'mysql -e "update users set langcode=\"en\" where uid=3;"'`
