### ISSUE TITLE
Create a "ddev launch" command

### ISSUE THREAD

**Issue by jigarius** [drud/ddev#1618]
**Is your feature request related to a problem? Please describe.**
When ddev is ready, one has to copy the URL and paste it in the browser to launch the site.

**Describe the solution you'd like**
A command like `ddev launch --browser=whatever` would definitely make life easier.

**Describe alternatives you've considered**
On Drupal sites, I can do `drush uli` to launch the site and login, but if the site is not Drupal, then I have to copy and paste manually.

**Comment by rfay** [comment]
There's another issue suggesting this, and it's a good idea. 

But I should mention that most terminals (like iterm2 on macOS, cmder on Windows, most Linux) allow you to click the URL, with command or control keys, or right-click and open.

**Comment by rfay** [comment]
Closing as duplicate of https://github.com/drud/ddev/issues/910, but a question:

How would you choose which URL to open? https? http? What if there are a bunch of others?

**Comment by rfay** [comment]
Added in #1862.
