### ISSUE TITLE
Detect if Docker might run out of space before performing --import-db

### ISSUE THREAD

**Issue by damienmckenna** [drud/ddev#1620]
**Is your feature request related to a problem? Please describe.**
Ran into a problem where --import-db with a 3.6gb SQL file resulted in the Docker container filling up, but nothing indicated this to me, instead it sat there for 30 minutes until I shut down ddev via "ddev stop", and then it took me a few hours of poking it with a stick to realize what the source of the problem was.

**Describe the solution you'd like**
Have the --import-db system either warn if the Docker container might run out of space before it begins, or detect that it has ran out of space while it is importing. It could then point to a documentation page on how to increase the available Docker container space, or other suggestions. There might also be value in having an option to skip this step.

**Describe alternatives you've considered**
🤷‍♂ 

**Additional context**
This might be best handled directly in Docker.

**Comment by rfay** [comment]
There are so many ways to use up docker resources (memory, cpu, etc), and so many options for different docker environments. I'm not optimistic that we'll be able to handle this. 

[Check and warn for low docker disk space and memory #863](https://github.com/drud/ddev/issues/863) is an old version of the same issue. 

Even `docker system df -v` doesn't give adequate information, as it doesn't say whether you're in trouble.

**Comment by rfay** [comment]
I'm way open to cross-platform techniques to do this, but don't know how it could work. On a piped-in database (now available in import-db or `ddev mysql`) it would be completely impossible to predict, and we don't know how to tell how much available space docker has in a cross-platform way. Closing for now, but #863 remains open. Happy to continue the conversation.
