### ISSUE TITLE
Drush commands should use HTTPS hostname by default

### ISSUE THREAD

**Issue by damienmckenna** [drud/ddev#1624]
**Is your feature request related to a problem? Please describe.**
Now that ddev supports pain-free HTTPS automagically in 1.8.0, Drush commands should reference the HTTPS hostname instead of the HTTP one.

**Describe the solution you'd like**
All Drush commands would use the HTTPS hostname instead of the HTTP one.

**Comment by damienmckenna** [comment]
Looking through the codebase, DDEV_URL comes from app.GetHTTPURL() in DockerEnv() from ddevapp.go. The GetHTTPURL() function specifically hardcodes "http" at the top of the function. Maybe it shouldn't (-:

**Comment by damienmckenna** [comment]
How about using GetHTTPSURL() instead of GetHTTPURL()?

**Comment by rfay** [comment]
This seems reasonable... but not every user is going to take the time to get https going, or cares... So every user that didn't would be broken and not know why.
