### ISSUE TITLE
Sign the ddev binary on macOS and Windows

### ISSUE THREAD

**Issue by unn** [drud/ddev#1626]
**Is your feature request related to a problem? Please describe.**
I'm a user of the firewall app Little Snitch, when I fire up a `ddev start` Little Snitch prompts me to trust network activity of the suspicious package `ddev`, typically making connections to GitHub or Sentry. Little Snitch considers all unsigned binaries as suspicious.

**Describe the solution you'd like**
Sign all the binaries we distribute.

**Describe alternatives you've considered**

**Additional context**

**Comment by rfay** [comment]
* Kevin was kind enough to get the developer.apple.com account set up so we don't get locked out all the time. 
* [Basic procedures](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html)
* [Digicert article](https://www.digicert.com/code-signing/mac-os-codesign-tool.htm)
* [sauceline/isign](https://github.com/saucelabs/isign) tool for signing on Linux ([article](http://neilk.net/blog/2016/02/11/isign/)

**Comment by rfay** [comment]
Sadly, isign appears to be unmaintained. I'm unable to install it on macOS or recent linux either.

**Comment by rfay** [comment]
1. Get a signed certificate https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html (I created "Apple Distribution: DRUD Technology, LLC (3BAN66AG5M)"
2. Export the cert as a .p12 file. It will require a password on the exported cert. 
3. Push the file to the CI server (or provide it however)
4. Create the keychain for use on the test CI server: `security create-keychain -p test buildagent.keychain && security unlock-keychain -p test buildagent.keychain && security default-keychain -s buildagent.keychain ` (`security list-keychains` will show the new keychain)
5. `security import <certfile.p12> -k buildagent.keychain -P <password_from_export> -T /usr/bin/codesign`
6. `security set-key-partition-list -S apple-tool:,apple: -s -k <password_from_certificate> buildagent.keychain`
7. `codesign -s "Apple Distribution: DRUD Technology, LLC (3BAN66AG5M)" .gotmp/bin/darwin_amd64/*`

**Comment by rfay** [comment]
@unn I'm afraid this may be something we should defer. 
* The only way that I found to sign on linux is unmaintained and nonfunctional.
* The only way I know to sign the *windows* binary on Linux (osslsigncode) actually silently fails on macOS :( Otherwise we could do the whole release on macOS.
* Signing on macOS requires re-architecting our release process and splitting it into two two different jobs.

It just seems like a lot of work and churn for something that only you have reported. I would like to see it happen though, but it doesn't seem to compete well with other priorities.

**Comment by unn** [comment]
😢 I guess that's okay.

**Comment by rfay** [comment]
I'll keep looking for good ways to do this, and strategize as I learn more about CircleCI and how we do the release process.

**Comment by rfay** [comment]
https://github.com/mtrojnar/osslsigncode/issues/12 follows up ways to get a newer osslsigncode. 
And I'm able to get osslsigncode to sign Windows binaries now. So we might be able to get the entire build to run on macOS now, which would be OK.
