### ISSUE TITLE
Consider supporting additional mysql variants (mysql 5.7, 8, mariadb 10.3+) and Postgres?

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1627]
**Is your feature request related to a problem? Please describe.**

People generally like to have the dbserver be the same software they're using on the server. Since mariadb isn't really a drop-in replacement for anything any more, the differentiation continues. 

Unfortunately, we hitched our wagon to mariadb some time ago, when it was in fact pretty much a drop-in replacement and could meet people's needs. So we use the terminology "mariadb_version" in config instead of something more general. So this would be something that would have to change.

Maybe Postgres too?

**Describe the solution you'd like**

I'm pretty sure we'd need a separate container for each, but can do a far better job building from the same base than we're currently doing, which is all copy/paste and not well maintainable. 

We'd have to change the configuration mechanism and naming of the image.

**Comment by rfay** [comment]
This is important; 
* Non-mariadb variants may not have `ddev snapshot` and `ddev restore-snapshot` though
* The current dual-copy Dockerfile and such needs to be replaced with a consolidated build.

**Comment by dacostafilipe** [comment]
We are starting to move our Apps from MySQL/MariaDB to PostgreSQL as the features and performance are simply better.

At the moment, we just add a custom service the our ddev configuration and it more or less works. We would welcome the official support of PostgreSQL.

**Comment by rfay** [comment]
Yeah, we will certainly consider official support. In the meantime, would you document your strategy with a PR in https://github.com/drud/ddev-contrib @dacostafilipe ? The pending PR https://github.com/drud/ddev-contrib/pull/6 does that for mysql versions, would love your review on it, and would love your postgresql approach.

**Comment by dacostafilipe** [comment]
Example created : https://github.com/drud/ddev-contrib/pull/7

**Comment by rfay** [comment]
For those who might hit this issue looking for PostgreSQL, see https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/postgres

Multiple MariaDB and MySQL versions will be available in v1.12
