### ISSUE TITLE
Feature request: make ddev stop work in SSH'd environment

### ISSUE THREAD

**Issue by Krisseck** [drud/ddev#1628]
Just a small feature request that I run into daily.

I often `ddev ssh` into the container and leave it running like that. Then once I am finished with the project, I try to run `ddev stop`, but of course it says `ddev: command not found`. I need to `exit` and then run `ddev stop`

Would it be possible for some `ddev` commands to work on the SSH container?

**Comment by rfay** [comment]
I certainly don't know how to do this at this moment. `ddev ssh`, like ssh-ing between hosts, essentially puts you on a completely different machine, isolated from the host. It might be possible for `ddev stop` to be aliased inside the container to 'exit', but that seems like it would just confuse people.

**Comment by rfay** [comment]
I have no ideas how we'd do this with any predictability, but if anybody comes up with any creative approaches let's continue the conversation. Closing for now.

Of course we could have a script called "ddev" in the container that just said "I'm sorry, I can't do that, Dave". Would that help though?
