### ISSUE TITLE
ssl (mkcert) support additional fqdns

### ISSUE THREAD

**Issue by beoss** [drud/ddev#1633]
Consider adding support to add additional_fqdns values into the mkcert certificate generation and installation process.

**Comment by rfay** [comment]
It already does support all of the FQDN's that are provided. 

However, if the *real* fqdn already has a cert that your browser trusts, that may give you trouble.

Can you give a full example of what's giving you trouble? 

If so, please try it out with something that certainly doesn't have a cert, like "host.example.com".

**Comment by rfay** [comment]
I just tested this again, and it's tested in our automated tests. the certs are fully supported in additional_fqdns, and this works even if the real domain exists with a real cert.

I'm happy to continue the conversation here with your specific experience and try to get to the bottom of it, but closing this for now.
