### ISSUE TITLE
False Link for Git Repos

### ISSUE THREAD

**Issue by cschoeni** [drud/ddev#1635]
In your Documentation ist the link for clone the github false.
```bash
git clone https://github.com/example-user/my-drupal8-site
```

**Comment by rfay** [comment]
Well, it's an example, not false. Would it be more descriptive if it were https://github.com/example/example-site-repo.git ? How can we communicate that it's an example, standing in for your own site? 

If you want to clone a starter Drupal site, you're better with the composer example in the quickstart.

Again, give us a hint how to make this more obvious that it's an example.
