### ISSUE TITLE
Replace Sentry integration with Segment

### ISSUE THREAD

**Issue by unn** [drud/ddev#1640]
**Is your feature request related to a problem? Please describe.**
Sentry is a great service for error and exception handling, but it's really not meant to be an audience management or a data analytics tool. We have integrated or plan on integrating several of our tools with Segment. It makes sense to utilize the same tools across product lines where possible.

**Describe the solution you'd like**
Replace the analytics gathering integrations currently handled by Sentry with Segment.

**Additional context**
- It appears from Segments documentation that they don't yet support server (server here because of golang) installs. See https://segment.com/docs/destinations/sentry/ We'll probably have to continue to implement the exception and error tracking until a time when Segment can support server-based Sentry. I've reached out to both companies to inquire about time lines.

- https://drud.slack.com/archives/C45DF87JT/p1559668781009000

**Comment by rfay** [comment]
@unn The first wheezing Segment events went through: https://app.segment.com/drud/sources/ddev_local_dev/debugger

BUT... I'm baffled how we'll use that. What of those thousands of destinations would be useful? Obviously without valid destinations we don't have any use for this service.

Note that we don't have to have segment push to sentry, we can just push to both of them.

**Comment by unn** [comment]
Right you are, in the dev source, we probably won't have a destination but the production one will 100% be connected to Amplitude. I'll get it configured, at the moment there isn't much to see there.

**Comment by rfay** [comment]
One note @unn, I don't know how to identify users (which is absolutely required by segment) except by host id. So what I did was use a hashed hostid. Other thoughts are solicited...

**Comment by unn** [comment]
https://segment.com/docs/spec/identify/#anonymous-id?

**Comment by rfay** [comment]
It looks to me like the hashed hostid is a great fill-in there? It's anonymized by the hash, etc. What do you think?

**Comment by unn** [comment]
Makes sense to me.

**Comment by rfay** [comment]
@unn i see you connected prod to amplify, but I'm pretty much blocked on this until I can see how the data will be used so I can send useful stuff. Can we do a dev setup (or use prod for now), and get me access to Amplify? Thanks.

**Comment by unn** [comment]
Invite sent. Though I'll note that without data Amplitude is a little bare bones, since it's hard to setup dashboards without having any data there yet.

Dashboard items I'm planning on creating:
- Monthly active users (MAU)
- OSes
- Median time to upgrade
- Versions in the wild
