### ISSUE TITLE
Documentation isn't parsing markdown lists correctly

### ISSUE THREAD

**Issue by ctorgalson** [drud/ddev#1646]
**Describe the bug**

Looking into #1645, I found that the relevant section is [structured as an unordered markdown list](https://github.com/drud/ddev/blob/master/docs/users/extend/additional-services.md#apache-solr), but [the page at ddev.readthedocs.io](https://ddev.readthedocs.io/en/latest/users/extend/additional-services/#apache-solr) renders it _without transforming the markdown_:

**To Reproduce**

Visit e.g. https://ddev.readthedocs.io/en/latest/users/extend/additional-services/#apache-solr and compare to the source at https://github.com/drud/ddev/blob/master/docs/users/extend/additional-services.md#apache-solr.

**Expected behavior**

Content rendered as unordered list.

**Screenshots**

![image](https://user-images.githubusercontent.com/1063424/59253159-eaaaf480-8c2d-11e9-9de3-46944c54e083.png)

**Version and configuration information (please complete the following information):**

Latest stable Firefox and Chrome, but versions aren't really relevant--the created code does not contain an ordered list:

```html
<p><strong>Interacting with Apache Solr</strong>
- The Solr admin interface will be accessible at: <code>http://&lt;projectname&gt;.ddev.site:8983/solr/</code> For example, if the project is named "myproject" the hostname will be: <code>http://myproject.ddev.site:8983/solr/</code>
- To access the Solr container from the web container use: <code>http://solr:8983/solr/</code>
- A Solr core is automatically created with the name "dev"; it can be accessed at the URL: http://solr:8983/solr/dev</p>
```

**Additional context**

If anyone knows what the fix is to get readthedocs.io to process the content correctly (and how to test it!), I can create a PR.

**Comment by rfay** [comment]
Usually the problem with readthedocs is not having a blank line before the list. Thanks for noticing and looking into this!

**Comment by rfay** [comment]
@ctorgalson it does look like it's the leading blank line that's missing for readthedocs, would love it if you could fix that in your PR. Thanks!

**Comment by ctorgalson** [comment]
@rfay I'll push something up tomorrow.

**Comment by rfay** [comment]
And yay, thanks!

<img width="1091" alt="Additional_Services_-_ddev_Documentation" src="https://user-images.githubusercontent.com/112444/59768330-670e8a80-9261-11e9-929e-2ecf21b32930.png">
