### ISSUE TITLE
ddev creates unwanted wp-config.php when installing wordpress/skeleton project

### ISSUE THREAD

**Issue by lopezs** [drud/ddev#1647]
**Describe the bug**
When setting up a composer-based WordPress project  as described in the ddev documentation, ddev creates ```wp-config.php``` and ```wp-config-ddev.php``` in the WordPress subdirectory. This means ```wordpress/skeleton```'s own ```wp-config.php``` located in the project root, is being ignored.

I think this may be related to #1518 ? 

**To Reproduce**
Follow [Composer Setup Example](https://ddev.readthedocs.io/en/latest/users/cli-usage/#wordpress-quickstart) in ddev's documentation:
```
mkdir my-wordpress-site
cd my-wordpress-site
ddev config --project-type=php
ddev composer create wordpress/skeleton --no-interaction --prefer-dist
ddev config --docroot=wp --project-type=wordpress
ddev restart

# Now try installing a theme or plugin. If you log in to WordPress they will not be 
# available because it's not aware of the custom theme or plugin folders
ddev composer require wpackagist-theme/hueman
ddev composer require wpackagist-plugin/bbpress
```

**Expected behavior**
ddev should detect the wordpress/skeleton version of ```wp-config.php``` and not attempt to create it's own inside ```/wp/``` 

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Ubuntu 18.04.2 LTS
 - Docker version: 
```
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```
 - ddev version
```
DDEV-Local version      v1.8.0                        
commit                  v1.8.0                        
db                      drud/ddev-dbserver:v1.8.0-10.2
dba                     drud/phpmyadmin:v1.8.0        
ddev-ssh-agent          drud/ddev-ssh-agent:v1.8.0    
docker                  18.09.6                       
docker-compose          1.23.2                        
domain                  ddev.local                    
os                      linux                         
router                  drud/ddev-router:v1.8.0       
web                     drud/ddev-webserver:v1.8.0   
```
 - config.yaml 
```
APIVersion: v1.8.0
name: wp-skeleton-test
type: wordpress
docroot: wp
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
```

**Comment by rfay** [comment]
Thanks for the report on this.

**Comment by rfay** [comment]
#1928 points out that wordpress/skeleton isn't really maintained and doesn't work right at all anyway, so not going to spend effort on this one. The docs will now suggest roots/bedrock. In that case, there's still an extraneous wp-ddev-config.php, but the output also explains how to get rid of complaining messages. I'd love to have your review on https://github.com/drud/ddev/pull/1918
