### ISSUE TITLE
Modify import-files to detect if tarball includes a parent folder.

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#165]
## What happened (or feature request):

Feature Request. Initial report here https://github.com/drud/ddev/pull/123#issuecomment-294198585.

## What you expected to happen:

Depending on whether a user creates a tarball using a trailing slash, a .tar or a .tar.gz file may unzip with or without an enclosing folder. For example, Pantheon allows users to create backups and download zip files for the code base, databases, and files. However, when you unzip the files folder, it encloses the files within a files-ENVIRONMENT folder. The only way to handle this as an end-user is to unzip and target the files directly.

Unfortunately, the only workaround would be to autodetect if there was a single folder and attempt the file import from that location. This hard coded assumption could result in other problems, such as instances where a files directory literally has one folder.

I might suggest a prompt. "We notice there is only one folder, should we import from within that folder"? I'm not exactly thrilled with that solution, but I know we'll hit this snag in both directions for people performing a manual import.

**Comment by rfay** [comment]
This will need a bit more for successful implementation, perhaps a specific set of tarball contents and actions to be taken.

For example:
* Pantheon format
* Drupal files if it includes the 'files' dir
* Drupal files if it comes from the repo up (starting in the docroot)

???

**Comment by tannerjfco** [comment]
The only reasonable way i see to address this is to provide a way for a user to define a path that exists in their archive to extract from instead of the root of the archive. Archives could consist of anything and could be structured in a variety of ways. When it comes to provider plugins, it will be appropriate to deal with the set of known formats and extract accordingly, but I think when it comes to the local file plugin, the user should be responsible for knowing their archive structure enough to specify what part should be extracted.

**Comment by beeradb** [comment]
It could be that we also check for expected paths for any known formats (drush archives, pantheon exports, etc.).

I haven't looked closely enough at those formats to know if there's a usable pattern present, though.

**Comment by rickmanelius** [comment]
Thinking about this more, it might be a scoping error to put this on the 'local' plugin. Each provider will have a standardized archive format for files and the database. And for drush archives, we may want to consider that its own provider plugin. At that point, the only way to trip up on this is using the local plugin.

Perhaps a different way to solve/resolve would be simply a warning. "We noticed a single '/files' directory within your archive. Shall we proceed to move that to files/files? (y/n)"?

**Comment by tannerjfco** [comment]
It's possible for a site's upload directory to only contain a single folder. Key example is wordpress, which by default organizes its uploads directory by year/month directories, so a wordpress site in its first year of existence is likely to only have a single folder.

#218 introduces changes to our Untar functionality to allow us to specify a folder to extract from within the archive. We could expose this as an optional flag / prompt on the import commands, and this would allow users to extract from an archive without having to ensure a specific structure. This would allow for users to use full site archives like drush archives for both commands.

**Comment by rickmanelius** [comment]
Nice to know that this functionality exists! And good point on the use case where a single directory would be typical for a new WordPress site. From my perspective, I think that while it is possible for an end-user to know the directory to include within the import-files command, that requires them to first unzip it in order to then inspect and then re-run on the zipped version.

What might be better is to ask a follow-up question if a single folder is detected. Example:

"A single folder ('2017') was found within the specified archive. Occasionally, a zip file will contain a parent folder that is not intended to be included when importing the files. Example: an archive may contain archive-folder/my-image.jpg and you want it to be located at sites/default/files/my-image.jpg instead of sites/default/files/archive-folder/my-image.jpg. If you don't want to include the '2017' folder, you can add (INSERT FLAGS) to your import-files command. Would you like to run that now (Y/N)?"

**Comment by rickmanelius** [comment]
To get this actionable, I need no pushback on the proposed solution of warning/educating the user about the implications and providing the ability to strip out the parent folder in a follow-up question. @tannerjfco thoughts?

**Comment by rickmanelius** [comment]
Might be handy for a sanity check from @rfay and/or @beeradb as a sanity check on the solution proposed in https://github.com/drud/ddev/issues/165#issuecomment-301887623.

**Comment by rfay** [comment]
It would actually require a full pass through the tarball to detect the "single dir" (or extract it and then look at the result).  Although this is a very important idea, I think trying to babysit the user on the contents of their tarball will be a never-ending task.  What if it *doesn't* contain a single folder, but *does* contain the full docroot, for example?

**Comment by tannerjfco** [comment]
I agree with @rfay, there's no way we could truly safeguard this command against how people might create an archive. In addition, I think its pretty unlikely a user is going to create an archive of their files just to satisfy format requirements we impose. We allow for directories to be specified for import, so there's no real benefit to satisfying our archive requirement.

I still feel like providing a way for users to specify a path within their archive to extract from provides the greatest value in this situation. While it does require users to know their archive contents, it would allow this command to work with an archive of structure. A user may need to inspect an archive initially, but if they're dealing w/ similar archive formats for multiple sites/backups, then that one inspection allows them to use the import command successfully for their other projects.

**Comment by rickmanelius** [comment]
Ok. Provider plugins will utilize a known structure, making this a moot point for all but someone manually importing. And someone willing to go through those steps will likely have the skill to debug themselves. I would still prefer to warn them, but the warning itself might be as a result of a false positive based on the situation. Marking as closed.
