### ISSUE TITLE
Install hirak/prestissimo globally on the php containe

### ISSUE THREAD

**Issue by hanoii** [drud/ddev#1650]
Any reason against installing [hirak/prestissimo](https://github.com/hirak/prestissimo) globally on the php container?

Just trying out ddev and find it odd it wasn't already installed. Performance-wise is a very good improvement.

**Comment by mglaman** [comment]
Depends on how many use the app container for `composer install`

**Comment by KaffDaddy** [comment]
This would be great!

**Comment by RobertLang** [comment]
I haven't used prestissimo before, so I don't know if it possibly has a side effect on normal install processes with composer. 
Also it's very easy to install by yourself if you really need it.
```
hooks:
  post-start:
    - exec: composer global require hirak/prestissimo
```
So, from my point of view it's not really necessary to include it.
But: If it doesn't kill my composer setups and speeds things up a bit, why not.

**Comment by rfay** [comment]
I went ahead and did a PR #1654  to add hirak/prestissimo, would love any feedback. You can just temporarily add `webimage: drud/ddev-webserver:20190618_prestissimo` to your .ddev/config.yaml file and do a composer build.
