### ISSUE TITLE
`ddev-ssh-agent` CPU consumption

### ISSUE THREAD

**Issue by j6s** [drud/ddev#1663]
**Describe the bug**
For a container that does not do a lot of complicated actions the CPU consumption seems a bit high: On my system (i7-7700HQ) it jumps to about 20% every couple of seconds.

To be fair, this is not a 'hard bug' - but the categorization as 'bug' seemed most fitting.

**To Reproduce**
1. Start a ddev project to ensure that the ssh agent is up
2. Observe CPU usage using `docker stats`

**Expected behavior**
I would expect the `ssh-agent` in the container to have a similar resource consumption as on my host system (as in, close to none)

**Screenshots**
![screenrecord-2019-06-24_19 18 40](https://user-images.githubusercontent.com/3374170/60038820-8ec47f00-96b5-11e9-98a8-38dff3dd378d.gif)

**Version and configuration information (please complete the following information):**
```bash
$ uname -a 
Linux jo-tp 5.1.8-arch1-1-ARCH #1 SMP PREEMPT Sun Jun 9 20:28:28 UTC 2019 x86_64 GNU/Linux

$ docker version
Client:
 Version:           18.09.6-ce
 API version:       1.39
 Go version:        go1.12.4
 Git commit:        481bc77156
 Built:             Sat May 11 06:11:03 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.6-ce
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.12.4
  Git commit:       481bc77156
  Built:            Sat May 11 06:10:35 2019
  OS/Arch:          linux/amd64
  Experimental:     false

$ docker-compose version 
docker-compose version 1.24.0, build unknown
docker-py version: 4.0.2
CPython version: 3.7.3
OpenSSL version: OpenSSL 1.1.1c  28 May 2019

$ ddev version 
bgsync        	drud/ddev-bgsync:v1.5.2       
cli           	v1.5.2                        
commit        	v1.5.2                        
db            	drud/ddev-dbserver:v1.5.2-10.2
dba           	drud/phpmyadmin:v1.5.2        
ddev-ssh-agent	drud/ddev-ssh-agent:v1.5.2    
docker        	18.09.6-ce                    
docker-compose	1.24.0                        
domain        	ddev.local                    
router        	drud/ddev-router:v1.5.2       
web           	drud/ddev-webserver:v1.5.2 
```

**Additional context**
Having had a quick look at the Dockerfile and looking at the timing of the spikes I would suspect the healthcheck script.

Also, while composing this report I noticed that I am not using the current version of ddev on this machine - however I am fairly certain that I have seen similar behaviour on my work PC. Will add a quick update when I have confirmed this behaviour on the current version.

**Comment by rfay** [comment]
Yes, it's definitely the healthcheck, and should be easy to fix on that one. I'd like to fix it on all of the containers, but have been stymied each time I look, since docker doesn't provide a way to change the healthcheck interval at startup time, and we want to know very early when the container is ready for fast startup times.

**Comment by j6s** [comment]
Update: I updated ddev (previously: 1.5.2, installed by manually downloading the binary - now: 1.8.0, installed from AUR) and restarted the ssh-agent container by manually stopping it (`docker stop ddev-ssh-agent`) and using `ddev start` in a project. I confirmed that the upped container uses the new v1.8.0 image.

New ddev version information is

```
$ ddev version 
DDEV-Local version	v1.8.0                        
commit            	v1.8.0                        
db                	drud/ddev-dbserver:v1.8.0-10.2
dba               	drud/phpmyadmin:v1.8.0        
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.8.0    
docker            	18.09.6-ce                    
docker-compose    	1.24.0                        
domain            	ddev.local                    
os                	linux                         
router            	drud/ddev-router:v1.8.0       
web               	drud/ddev-webserver:v1.8.0 
```

The behaviour is the same in 1.8.0

**Comment by j6s** [comment]
Looking at the [healthcheck documentation](https://docs.docker.com/engine/reference/builder/#healthcheck) I would imagine that a longer interval with a well chosen start period could work here.

Additionally, in the meantime `killall` is being called twice every healthcheck (once for `socat` and once for `ssh-agent`) - each call of `killall` will evaluate the list of running processes, reading `/proc/*/stat`.

Using `killall -0 socat ssh-agent` instead of `killall -0 socat && killall -0 ssh-agent` would cut down on that a bit (unsure how much though, will do some investigation later).

**Comment by rfay** [comment]
A PR would be very welcome. Note that the ssh container is the least of our problems, as it's just one container. The web and db containers would be far more important. The only fundamental requirement is that `ddev start` not get (much?) slower.

**Comment by rfay** [comment]
@j6s I'd love it if you could give a review of #1674 and see how it works out for you. Artifacts for download are listed in the PR.

**Comment by j6s** [comment]
Looks good -

I did not perceive any slowdown in startup times and CPU consumption as well as exchanged events are down significantly.

Times to cold-start (including ssh-agent) a project on my PC:

1.8.0:
```
$ time ddev start
[...]
3.02user 0.28system 0:19.12elapsed 17%CPU (0avgtext+0avgdata 40580maxresident)k
1344inputs+32outputs (7major+61072minor)pagefaults 0swaps
```

your fix:
```
$ time /home/j/Downloads/ddev_linux.v1.9.1-8-gc4909aed/ddev start
[...]
2.95user 0.28system 0:15.72elapsed 20%CPU (0avgtext+0avgdata 40632maxresident)k
0inputs+40outputs (0major+61043minor)pagefaults 0swaps
```

**Comment by rfay** [comment]
Thanks so much. I think it actually could end up being a little faster because of the 1s interval, it means it gets checked sooner. But since it takes 2-3 seconds for these things to get healthy, that probably comes out in the wash. 

An interesting tool is `docker inspect ddev-router | jq ".[].State.Health"` (change name of container as needed). It shows the last few healthchecks so you can see how they happen.
