### ISSUE TITLE
Update the set of default apache2 modules to include common ones

### ISSUE THREAD

**Issue by greggles** [drud/ddev#1672]
**Is your feature request related to a problem? Please describe.**
I was trying to debug some htaccess file changes related to mod_expires. They weren't working and the solution was that the apache2 module mod_expires was not installed. It would be nice to support that since it's used by the default Drupal .htaccess file.

**Describe the solution you'd like**
Install some more Apache modules by default, like mod_expires.

**Describe alternatives you've considered**
Current workaround is in config.yaml:

```
hooks:
  post-start:
  - exec: a2enmod expires && apache2ctl graceful
```

**Additional context**
It would be great if a hosting company could comment below with their list of apache modules they provide. I tried gathering this information on an Acquia server and found that it's blocked by requiring more permissions than a typical user has.

**Comment by rfay** [comment]
Thanks for this. 
- mod_expires
- mod_headers
- @juban suggested https://tn123.org/mod_xsendfile/,  but it seems like a less likely candidate as not a standard, included module.

**Comment by greggles** [comment]
Those 2 look good to me for Drupal 7/8.

On [Twitter](https://twitter.com/greggles/status/1143957338660851712) I got suggestions for mod_security, mod_deflate/mod_brotli. Those all seem special enough that people could figure this out for themselves.
