### ISSUE TITLE
ddev-router failed to become ready - picks up a solr docker container

### ISSUE THREAD

**Issue by jacobsenj** [drud/ddev#1676]
**Describe the bug**
The ddev router can't start if I have a solr docker container running. It trys to pick it up and route to it automagically.

```
Creating ddev-router ... done

Failed to start lightning-it: ddev-router failed to become ready: logOutput=2019/06/27 11:29:15 [emerg] 1544#1544: no servers are inside upstream in /etc/nginx/conf.d/default.conf:161
nginx: [emerg] no servers are inside upstream in /etc/nginx/conf.d/default.conf:161
nginx: configuration file /etc/nginx/nginx.conf test failed
, err=container /ddev-router unhealthy: 2019/06/27 11:29:15 [emerg] 1544#1544: no servers are inside upstream in /etc/nginx/conf.d/default.conf:161
nginx: [emerg] no servers are inside upstream in /etc/nginx/conf.d/default.conf:161
nginx: configuration file /etc/nginx/nginx.conf test failed
```

Here are the lines from within the router container from `/etc/nginx/conf.d/default.conf:161`:
```
    # solr-6.6.5.localhost
    upstream solr-6.6.5.localhost-80 {
    }
```

**To Reproduce**
1. Run a solr container using this docker-compose.yml contents as an example:
```
solr:
  container_name: solr-6.6.5
  image: solr:6.6.5
  ports:
    - "8984:8983"
  restart: unless-stopped
  environment:
    VIRTUAL_HOST: solr-6.6.5.localhost
    SOLR_HEAP: 1024m
```
2. Verify the solr service is running at http://localhost:8984
3. Try to ddev start on your project
4. See error in description

**Expected behavior**
The router should not pick up my solr docker container and try to route to it.

**Version and configuration information (please complete the following information):**
 - OSX 10.14.5
 - Docker version 18.09.2, build 6247962
 - ddev version v1.9.0
 - config.yaml contents for the misbehaving project:
```APIVersion: v1.9.0
name: demo
type: typo3
docroot: web
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
hooks:
  post-import-db:
    - exec: /var/www/html/vendor/bin/typo3cms cache:flush
    - exec: /var/www/html/vendor/bin/typo3cms database:updateschema
  post-start:
    - exec: composer install -d /var/www/html
omit_containers: [dba]
#webimage_extra_packages: [php7.2-gmp]
project_tld: localhost
use_dns_when_possible: yes
timezone: Europe/Berlin
```

**Additional context**
If I stop the solr container, ddev router starts as expected.

docker ps:
```
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                     PORTS                                                                        NAMES
349b40064b82        drud/ddev-router:v1.9.0          "/app/docker-entrypo…"   6 minutes ago       Up 6 minutes (unhealthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:8025->8025/tcp             ddev-router
e683daf1451d        ddev-demo_web                    "/start.sh"              7 minutes ago       Up 6 minutes (healthy)     127.0.0.1:32824->80/tcp, 127.0.0.1:32823->443/tcp, 0.0.0.0:32789->8025/tcp   ddev-demo-web
b4c74f7e8b75        drud/ddev-dbserver:v1.9.0-10.2   "/docker-entrypoint.…"   7 minutes ago       Up 6 minutes (healthy)     127.0.0.1:32822->3306/tcp                                                    ddev-demo-db
df7bf44020fb        solr:6.6.5                       "docker-entrypoint.s…"   7 minutes ago       Up 7 minutes               0.0.0.0:8984->8983/tcp                                                       solr-6.6.5
72d28bbb45da        drud/ddev-ssh-agent:v1.9.0       "/entry.sh ssh-agent"    2 hours ago         Up 2 hours (healthy)                                                                                    ddev-ssh-agent
```

**Comment by rfay** [comment]
Could you please try the standard example solr config instead? I think it will work for you. Then work your way back to what the difference is?

https://ddev.readthedocs.io/en/stable/users/extend/additional-services/#apache-solr

**Comment by jacobsenj** [comment]
The ddev project is not intended to use the running solr container. It‘s just a docker container running on my system.

**Comment by rfay** [comment]
Your configuration above specifically starts a new solr container. If you want to use a *different, outside* solr container, you'll have to have that container on the `ddev_default` network, and then address it directly in your solr client config.

**Comment by jacobsenj** [comment]
No, I do not specifically start a new solr container. It's just sitting there on my docker and runs and I do not want to use it from the ddev machine. But I have to stop it, if I want to use ddev, and I don't think this is good. Maybe there is the requirement "Do not have any docker containers running while trying to use ddev", then it's fine for me.

**Comment by rfay** [comment]
Please remove the line `    VIRTUAL_HOST: solr-6.6.5.localhost` from your other standalone docker-compose.yaml. That environment variable is an explicit signal to ddev-router that it needs to try to present the web interface for the container. And you don't want it to. And it doesn't have enough information. I tested and it worked fine.
