### ISSUE TITLE
Add settings.ddev.php loader to settings.local.php if present

### ISSUE THREAD

**Issue by damienmckenna** [drud/ddev#1680]
In Drupal 8 there's a file called "settings.local.php" which is supported by default.settings.php and the included .gitignore file. This provides an out-of-the-box pattern for creating of a settings file which is only used by the individual local install and is not committed to the code repository.

DDEV-Local creates its own settings.ddev.php file. While this file is ignored by D8 core's .gitignore file, the changes made to sites/default/settings.php may be committed. As such, enabling ddev on a site introduces the likelihood of there being changes to the codebase recognized by git.

**Describe the solution you'd like**
I would like it if `ddev config` made changes to sites/default/settings.local.php if present, and only then checked sites/default/settings.php.

**Comment by rfay** [comment]
That still wouldn't be quite enough, ddev would have to parse settings.php to make sure it was *loading* settings.local.php. And of course settings.local.php is not universally used. 

I resisted the very idea of editing the user's settings.php for a really long time, but it really has worked out well for the real world and users' experience.

**Comment by rfay** [comment]
And of course as I know you know, settings.php is fine doing the conditional import of both settings.local.php and settings.ddev.php

BTW, the first round of the includes actually used settings.local.php for the ddev settings, but of course that ran into conflict with people's existing settings.local.php, etc.

**Comment by damienmckenna** [comment]
Maybe an option to not change sites/default/settings.php every time the project is started? Would changing the project to `php` instead of e.g. `drupal7` also solve this?

**Comment by rfay** [comment]
Yes, I was going to suggest `type: php` - With `type: php` ddev doesn't try to do anything with settings.  For many people using almost any CMS who prefer to manage their own world, the generic 'php' setting is the right thing.

**Comment by rfay** [comment]
I do recommend using project type: php for this need; the conflict between ease of use and correctness for everybody is just never-ending. I'm going to close this for now. Thanks for bringing it up, and happy to continue the conversation.
