### ISSUE TITLE
List project urls in table form

### ISSUE THREAD

**Issue by andy-blum** [drud/ddev#1685]
**Is your feature request related to a problem? Please describe.**
Whenever starting up a project or using `ddev describe`, the project's urls are in a comma-separated list. In some CLI applications, these links are clickable, but go to the project's url with a trailing comma

**Describe the solution you'd like**
List project urls in some format other than a comma-separated list. Potential options include:
- a table layout
- a space-separated list

**Comment by rfay** [comment]
Seems reasonable to me. What OS and terminal application are you using that picks up the comma?

**Comment by andy-blum** [comment]
I'm using mac mojave (10.14.5), and the terminal built into VS Code

**Comment by rfay** [comment]
I hope you'll try this out and let us know if it works for you @andy-blum ; it will be in the next prerelease and next release. Thanks!
