### ISSUE TITLE
Connection to registry-1.docker.io fails "unauthorized: incorrect username or password"

### ISSUE THREAD

**Issue by nicodh** [drud/ddev#1689]
I just installed ddev 1.9.1 on MacOS Mojave (10.14.5)

When starting a ddev project I get this output:

`ddev start
Starting dialog... 
Recreating ddev-ssh-agent ... done
 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
Pushing mkcert rootca certs to ddev-global-cache 
Pushed mkcert rootca certs to ddev-global-cache 
Error response from daemon: Get https://registry-1.docker.io/v2/drud/ddev-webserver/manifests/v1.9.0: unauthorized: incorrect username or password
Failed to start dialog: exit status 1 `

My docker version is: 
Docker version 18.09.2, build 6247962
docker-compose version 1.23.2, build 1110ad01

**Comment by rfay** [comment]
Hi, thanks for the report.

This is fixed easily with `docker logout`. It's some kind of long-running docker or dockerhub issue that happens periodically to people. Doesn't make any sense at all, as all of ddev's docker images are public.

**Comment by nicodh** [comment]
Thanks - that indeed fixed the problem!

**Comment by rfay** [comment]
Glad it worked! I wonder if they'll ever fix that :)

**Comment by kreynen** [comment]
I just ran into this as well.  Thanks for the quick fix!

**Comment by SCrocky** [comment]
Also had the issue, thanks for the fix :pray:
