### ISSUE TITLE
ddev import-db should accept data from /dev/stdin

### ISSUE THREAD

**Issue by jonaseberledmind** [drud/ddev#1690]
**Is your feature request related to a problem? Please describe.**
I have my SQL data stored in several files. I would like to import them to a DB.

**Describe the solution you'd like**
It would be nice to be able to pipe SQL data in `ddev --import-db` like
```
cat db/sql/struct/* db/sql/data/* | ddev --import-db
```

**Describe alternatives you've considered**

I use 
```
cat db/sql/struct/* db/sql/data/* | docker exec -i ddev-<PROJECTNAME>-db mysql --default-character-set=utf8 db
```
as a workaround to pipe SQL data into the "mysql" command in the container.
Notice the `docker exec -i` which connects the host's stdin to the command.

**Comment by rfay** [comment]
Thanks!

**Comment by rfay** [comment]
Actually, #1700 gets us set up for this, but doesn't actually solve this problem, reopening.

**Comment by rfay** [comment]
The example in `ddev import-db -h` doesn't have any information about this usage, still needs to be added. Also we should check the docs.
