### ISSUE TITLE
Container needs build-essential packages, especially 'make', for npm

### ISSUE THREAD

**Issue by agviu** [drud/ddev#1692]
**Describe the bug**
Running `npm install` ends up giving an error about missing `make` command.

**To Reproduce**
1. Create a brand new ddev installation (v1.9.2)
2. Choose drupal8 as environment when configuring ddev.
3. Place the package.json file in the ddev folder.
4. Run `npm install`

**package.json content**
{
  "name": "name",
  "version": "1.0.0",
  "description": "",
  "main": "gulpfile.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build-sass": "gulp sass"
  },
  "author": "Me",
  "license": "ISC",
  "devDependencies": {
    "autoprefixer": "^6.5.1",
    "gulp": "^3.9.1",
    "gulp-postcss": "^6.2.0",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^2.3.2",
    "gulp-sourcemaps": "^1.8.0",
    "postcss-easysprites": "^0.1.7"
  }
}
**Expected behavior**
Install gulp and sass pacakges.

**Error message**
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/var/www/html/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/var/www/html/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/var/www/html/node_modules/which/which.js:80:29)
gyp ERR! stack     at /var/www/html/node_modules/which/which.js:89:16
gyp ERR! stack     at /var/www/html/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /var/www/html/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.9.125-linuxkit
gyp ERR! command "/usr/bin/node" "/var/www/html/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/www/html/node_modules/node-sass
gyp ERR! node -v v8.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macOS Mojave 10.14.5
 - Docker version information: 18.09.2.
 - ddev version information:
DDEV-Local version	v1.9.1
commit            	v1.9.1
db                	drud/ddev-dbserver:v1.9.0-10.2
dba               	drud/phpmyadmin:v1.9.0
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.9.0
docker            	18.09.2
docker-compose    	1.23.2
os                	darwin
router            	drud/ddev-router:v1.9.0
web               	drud/ddev-webserver:v1.9.0

**Additional context**
The comand `make` is needed in order to complete the installation.

**Comment by rfay** [comment]
I assume this is `npm install` in a particular directory, for a particular purpose?
If you're doing the npm install in a post-start hook I recommend trying this in config.yaml:
`webimage_extra_packages: [build-essential]`

Alternately, you can do both at once in .ddev/web-build/Dockerfile (see the Dockerfile.example) with 
something like
```
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential
RUN npm install --global gulp-cli
```

**Comment by rfay** [comment]
I tried it with your package.json, but am pretty sure that's invalid because of double-single-quotes in
`"test": "echo "Error: no test specified" && exit 1",`
If I set up this `.ddev/web-build/Dockerfile`:
```
ARG BASE_IMAGE=drud/ddev-webserver:v1.9.0
FROM $BASE_IMAGE
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential
If I use this package.json 
```

And then use this package.json
```
{
  "name": "name",
  "version": "1.0.0",
  "description": "",
  "main": "gulpfile.js",
  "scripts": {
    "test": "echo 'Error: no test specified' && exit 1",
    "build-sass": "gulp sass"
  },
  "author": "Me",
  "license": "ISC",
  "devDependencies": {
    "autoprefixer": "^6.5.1",
    "gulp": "^3.9.1",
    "gulp-postcss": "^6.2.0",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^2.3.2",
    "gulp-sourcemaps": "^1.8.0",
    "postcss-easysprites": "^0.1.7"
  }
}
```

and `npm install` in the directory where the package.json is, it seems to work fine.

**Comment by agviu** [comment]
I confirm that it works by adding the build-essential package in the Dockerfile.
It adds the 'make' command, needed to build the entire set.
No need to change the package.json file.
Thanks!

**Comment by rfay** [comment]
Thanks!
