### ISSUE TITLE
Use same local-bound DB port after restart

### ISSUE THREAD

**Issue by jonaseberledmind** [drud/ddev#1695]
**Is your feature request related to a problem? Please describe.**
The port to connect to the DB changes after every `ddev restart`. This requires changing the setup of DB applications.

**Describe the solution you'd like**
When a port was found on first run, it should be reused on next runs (if still free, of course. If not, a warning would be helpful)

**Describe alternatives you've considered**
Adapting the docker-compose file for the DB. But that makes it basically not sharable any more with colleagues.

**Additional context**

**Comment by rfay** [comment]
A solution for this was implemented a couple of releases ago, 
In your config.yaml `host_db_port: "59002"` - You can set it to any available port and it will be the same every time.

**Comment by jonaseberledmind** [comment]
Ah, neat! I did not know that.

I put that in a `config.db-port.yaml` which is git-ignored so the `config.yaml` is still sharable.
