### ISSUE TITLE
ddev could have a config.yaml item to determine its expected composer.json location

### ISSUE THREAD

**Issue by ghost** [drud/ddev#1699]
**Is your feature request related to a problem? Please describe.**
I do not have the composer.json on the root level. I cannot use `ddev composer` then.

For convenience, I already have set the `config.yaml` setting `working_dir=` to the main web directory. I would expect that to influence composer's working directory as well.

```
$ ddev composer install
```
runs 
```
Failed to run docker-compose [-f /home/jonas/www/ratbacher.de/.ddev/docker-compose.yaml -f /home/jonas/www/ratbacher.de/.ddev/docker-compose.env.yaml -f /home/jonas/www/ratbacher.de/.ddev/docker-compose.redis.yaml exec -w /var/www/html -T web bash -c composer install], err='exit status 1', stdout='', stderr='Composer could not find a composer.json file in /var/www/html
```
which ignores the `working_dir=` - setting but instead uses explicitly `exec -w /var/www/html`

**Describe the solution you'd like**
`ddev composer` should either have the possibility to use a `composer_root_dir=` setting or just use the already existing `working_dir=`. Both would make sense to me. The 1st implementation would not be breaking, though.

**Describe alternatives you've considered**
`ddev composer --working-dir=/var/www/html/webroot ...` works, but is tedious.

`ddev ssh`, then `composer` works also, but defeats the purpose of a `ddev composer` command and the according *-composer hooks.

Thank you for considering!

**Comment by rfay** [comment]
I'm sure you already know that you can `ddev ssh` and `composer install -d ...`. On macOS and Linux this is completely equivalent, and it might be on Windows with NFS. However, `ddev composer...` on regular Windows is hugely better because of its handling of symlinks in the container.

**Comment by jonaseberledmind** [comment]
That's why it would be great when teams could use `ddev composer...` even when composer.json is not on the root dir.

**Comment by jonaseberledmind** [comment]
It looks like it is here https://github.com/drud/ddev/blob/6ba9fd61c8f1984b165e928523de282b6e412fcf/pkg/ddevapp/composer.go#L20 where the fixed dir is given. Sorry, I am a Go noob.

Could we get the configured `working_dir` (or a new option `composer_root_dir`) there?

**Comment by rfay** [comment]
In v1.11, `ddev composer install -d <somedir>` works fine. I'm going to close this assuming that works for you @jonaseberledmind 

`ddev composer install -d junk1` will install into /var/www/html/junk1 (assuming a composer.json there)
`ddev composer install -d /var/www/html/junk1` does the same.

**Comment by jonaseberledmind** [comment]
Maybe we could revisit this topic @rfay?

I think `ddev exec composer` (which respects the working_dir) should be the same as `ddev composer`.

**Comment by rfay** [comment]
`ddev exec composer` works fine for non-Windows OS. And it should also work with -d. I'm not sure the question you're asking @jonaseberle - The reason `ddev composer` exists really is for Windows, where symlinks have to be cleaned up.

**Comment by jonaseberledmind** [comment]
I am not taking this. We are a mixed team and `ddev composer` is  way easier to remember for all. `ddev exec...` is for the specialists.

Please let `ddev composer` use the working directory specified in `config.yaml`.

**Comment by rfay** [comment]
Sorry, I didn't understand most anything you were saying. Ever. For most people, defaulting to working dir for would break all composer builds. For example, with Drupal the composer.json is in root, and working dir is web.

Reopening this, but please propose a robust solution that might work for most people.  The vast majority of composer builds for anything I'm familiar with put composer.json in repo root .

I suspect you need a new config element, not working dir?

**Comment by JBlocks** [comment]
A configuration option in the yml file to change the working dir would be great!
I dont want to add a directive `-d /var/www/html/Source` on each execution.

**Comment by rfay** [comment]
That's a really good workaround. And it goes ahead and provides the extra fixup that ddev does on Windows because it still uses `ddev composer`

**Comment by rfay** [comment]
I changed the title, "`ddev composer` could have a config.yaml item to determine its expected composer.json location"

It seems I got lost in the various options.

IMO since everybody has a workaround to do what they need with composer, this isn't a high priority right now, I'm deprioritizing and removing from this release cycle. Sorry to disappoint you.

Remember that `ddev exec composer`, `ddev composer -d` and `ddev ssh` with any composer pattern you like are totally available here.

**Comment by andrewbelcher** [comment]
It's worth noting that you can place that in `.ddev/commands/web/composer`, which means it'll replace the standard `ddev composer` command, which is a bit easier cognitively and means there's no real benefit to a config property for it.

Although it's worth noting that you'll probably want to also add something like `PATH=$PATH:/var/www/html/SUBPATH/vendor/bin` to `.ddev/homeadditions/.bash_aliases` so it picks up the compose bin path!

**Comment by jonaseberle** [comment]
@andrewbelcher No, it is not possible to replace the default command.

**Comment by andrewbelcher** [comment]
Apologies, you are completely right! Perhaps allowing that would be worth considering.

**Comment by rfay** [comment]
`ddev composer` is mostly a wrapper on composer, but it has the subcommand `ddev composer create`, which is a wrapper on `composer create-project`, which is a different animal. Maybe we'll figure out how to do that differently some day.

**Comment by andrewbelcher** [comment]
Maybe there is an argument for allowing the composer dir to be configurable then. Would resolve the bin path issue too. Though it's such an edge case it's probably better to just discourage that set up and leave a bit of pain for those that plough on or inherit something like that!

**Comment by rfay** [comment]
I definitely think there's some improvement for `ddev composer` down the pike. 

See also
* https://github.com/drud/ddev/issues/2680
* https://github.com/drud/ddev/issues/2547
* and especially https://github.com/drud/ddev/issues/2422
