### ISSUE TITLE
The DDEV_URL variable is not set. Defaulting to a blank string. 

### ISSUE THREAD

**Issue by alesrebec** [drud/ddev#1701]
I started getting this notice one every command run inside ddev
"The DDEV_URL variable is not set. Defaulting to a blank string."

Can't find anywhere to set it in config?

**Comment by rfay** [comment]
Thanks for opening this issue. 

In v1.9, DDEV_URL was obsoleted as it had no usage and no purpose. So you have a docker-compose.*.yaml that uses it, and it hasn't changed, and so your third-party service is making that noise at startup. You can just remove that line from your docker-compose.*.yaml.

**Comment by alesrebec** [comment]
I see.
Thanks.
