### ISSUE TITLE
400 Bad Request on Install

### ISSUE THREAD

**Issue by fcplweb** [drud/ddev#1705]
I started a new project in DDEV following the quickstart guide:

mkdir my-drupal8-site
cd my-drupal8-site
ddev config --project-type php
ddev composer create drupal-composer/drupal-project:8.x-dev --stability dev --no-interaction --prefer-dist
ddev config --project-type drupal8
ddev restart

Upon restart I go to the URL ddev provided and it shows the Drupal 8 install page. I select english as my language and save and continue. It then gives a 400 error "The plain HTTP request was sent to HTTPS port" 

From the command line I ddev ssh then ls and it shows the files for my project so the project is loaded. Not sure what my next step should be.

**Comment by rfay** [comment]
Thanks for the report, we always want to hear when people have trouble (or success!)

I used your exact steps (on macOS) and then I used the named https URL https://my-drupal8-site.ddev.site/ to install Drupal 8.7.4. I wasn't able to recreate the problem you hit. Could you try again and give more info about the OS you're on, and the browser you used, and which URL you used for the installation?

**Comment by rfay** [comment]
OK, I tried the localhost (127.0.0.1) URL, and got the error your mention. at http://127.0.0.1:32812/core/install.php?langcode=en (on my system)

<img width="1175" alt="400_The_plain_HTTP_request_was_sent_to_HTTPS_port" src="https://user-images.githubusercontent.com/112444/61190483-043ec200-a65a-11e9-9159-1a6677ee73ed.png">

It looks to me like this is a Drupal installer bug, where it's assumed that localhost is a non-https address.  I was actually able to continue the install by using the next URL https://127.0.0.1:32812/core/install.php?langcode=en (changed http to https). I had to do that a few times, but actually got through the install :)

Your best choice to go forward is to use the named URL, https://my-drupal8-site.ddev.site/ in this case, and you should be fine. You can also use the http version of that URL and it will work fine. 

Kind of an interesting Drupal installer bug.

**Comment by fcplweb** [comment]
Hi rfay - thank you for the response. I had tried to push it forward by switching the http to https without success. Today - I tried again today after starting ddev / Docker and...it allowed me to install Drupal by using the switching to https. Thanks for your help!

**Comment by rfay** [comment]
Thanks for letting me know, glad it's working for you.

**Comment by DavidBruchmann** [comment]
I had the same problem with TYPO3 today and suspect that there is some issue concerning the port.
The issue showed only up when I used https://127.0.0.1:55012.

**Comment by rfay** [comment]
Most code doesn't assume that there will be a port involved, so it's usually better to use the *.ddev.site URL and avoid trouble.

**Comment by kingfisher64** [comment]
@rfay thanks for that bit of advice, v helpful to know. I thought there would be no difference however using the ddev link there is no such issue.

**Comment by rfay** [comment]
@kingfisher64 this is a closed issue from 5 years ago. Please don't comment here, or at least don't comment unless you give much more complete information. Mostly you should create a new issue or come over to Discord if you have a current problem.
