### ISSUE TITLE
Improve the suggestion in case of DDEV version mismatch

### ISSUE THREAD

**Issue by AronNovak** [drud/ddev#1706]
The issue:
```
Your /foobar/drupal/.ddev/config.yaml version is v1.9.1, but ddev is version v1.9.0. 
Please run 'ddev config' to update your config.yaml.
```

**Describe the solution you'd like**:
Actually the message should encourage a local DDEV version update, `ddev config` is not really meaningful in this case. So we could compare version strings and have two cases in `pkg/ddevapp/ddevapp.go` , one for lower local version, one for greater local version.

**Describe alternatives you've considered**
Alternatively we should change the text to cover both cases, less logic, a bit less user friendly of course.

**Comment by rfay** [comment]
This was fixed in #1707, thanks!
