### ISSUE TITLE
Allow automatic adding to settings.ddev.php

### ISSUE THREAD

**Issue by yanniboi** [drud/ddev#1709]
**Is your feature request related to a problem? Please describe.**

We have certain additional settings for our development environments that always apply to ddev environments. We would like to be able store them somewhere so that they get included in the settings.ddev.php.

**Describe the solution you'd like**

Potentially something like a default settings include file in the .ddev directory that always gets added to settings.ddev.php or an environment variable that is the path to a file to be added when the ddev settings file in generated.

**Describe alternatives you've considered**

Committing the ddev.settings.php to git for a project. Not a very attractive alternative...

**Comment by rfay** [comment]
Why don't you use settings.local.php? You just have to enable it in the standard settings.php (D8) or add the conditional include (D7 and below).

You *can* remove the "#ddev-generated" line from settings.ddev.php and take it over, but settings.local.php is a better option.

**Comment by rfay** [comment]
No reply from OP, but I think settings.local.php is the natural fix for Drupal and this problem, so closing. Happy to continue the conversation here.
