### ISSUE TITLE
http url no longer provided - https url only

### ISSUE THREAD

**Issue by nigelwhite** [drud/ddev#1711]
**Describe the bug**
ddev start does not provide a http address - only an https address
Successfully started d8test 
Project can be reached at https://d8test.ddev.site, https://127.0.0.1:32780 

$ ddev describe
NAME    TYPE     LOCATION                    URL                       STATUS        
d8test  drupal8  ~/docker-sites/ddev/d8test  https://d8test.ddev.site  running

Project Information
-----------------
PHP version:    7.2                                              
URLs:           https://d8test.ddev.site, https://127.0.0.1:32777

MySQL Credentials
-----------------
Username:       db  
Password:       db  
Database name:  db  
Host:           db  
Port:               
MariaDB version 10.2
To connect to mysql from your host machine, use port 32776 on 127.0.0.1.
For example: mysql --host=127.0.0.1 --port=32776 --user=db --password=db --database=db

Other Services
--------------
MailHog:        http://d8test.ddev.site:8025
phpMyAdmin:     http://d8test.ddev.site:8036

DDEV ROUTER STATUS: healthy
ssh-auth status: healthy

**To Reproduce**
I had not used ddev on my laptop for a while, so I was asked to update ddev.
$ brew upgrade ddev
$ ddev config
Then I got warnings about cert so I followed instructions
$ sudo apt install libnss3-tools
$ mkcert -install
Using the local CA at "/home/nigel/.local/share/mkcert" ✨
The local CA is now installed in the Firefox and/or Chrome/Chromium trust store (requires browser restart)! 🦊
close browser
$ ddev restart
The Drupal site opens at https://127.0.0.1:32777, but when I want to log in at http://127.0.0.1:32777/user/login I get
400 The plain HTTP request was sent to HTTPS port

**Expected behavior**
On my other Ubuntu machine there is a http url provided. I use this for local development.

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Ubuntu 18.04.2
 - Docker version information (use `docker version`) and insert it here. 18.09.6
 - ddev version information (use `ddev version`) 1.9.1
 - config.yaml contents for the misbehaving project

APIVersion: v1.9.1
name: d8test
type: drupal8
docroot: web
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "81"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
timezone: ""

 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? no

Thank you

**Comment by rfay** [comment]
Yeah, if you have configured mkcert, that's the case. If you just remove the mkcert root CAs you'll have the http URLs back.  However, I definitely agree that we have to make a way to provide the http URLs. Thanks for this issue. They were removed because people were seeing just too many URLs and couldn't parse all the output. But we'll get a flag or something to show all URLs.

**Comment by nigelwhite** [comment]
Thanks
I did $mkcert -uninstall
"The local CA is now uninstalled from the system trust store"
$ ddev stop
power off and reboot laptop
$ ddev start
successfully started - but still only gives https urls
Is there some other action I need to take?

**Comment by rfay** [comment]
Yeah, sorry. `rm -r $(mkcert -CAROOT)`. ddev looks for those files to see if mkcert is enabled. 

Can you help me understand better why http is important to your situation?  (But making a way to provide *all* URLs is certainly going to happen.)

**Comment by nigelwhite** [comment]
That worked. Many thanks.
My (newbie) use case was -
when I want to log in at http://127.0.0.1:32777/user/login I get
400 The plain HTTP request was sent to HTTPS port.

I knew I'd just followed instructions to add mkcert so I guessed it was related.

Now, on ddev start, there are warnings like
mkcert may not be properly installed, please install it, `brew install mkcert nss`, `choco install -y mkcert`, etc. and then `mkcert -install`: <nil> 
but I guess I just ignore those. The main thing is that the site is working again.

Many thanks

**Comment by rfay** [comment]
Why are you using the 127.0.0.1 port instead of the ddevtest.ddev.site URL? (There seem to be some D8 bugs related to using https on localhost, which I think is probably what bit you.)

**Comment by nigelwhite** [comment]
No reason. I think it was the first one that hit my eye and then I just fell into the habit.
Thanks for the tip - I'll use the ddev.site url from now on
