### ISSUE TITLE
Improve custom command error handling - check for running project or service

### ISSUE THREAD

**Issue by andrewfrench** [drud/ddev#1716]
**Is your feature request related to a problem? Please describe.**
When a custom command targets a non-running container, the error is fairly opaque:

`Failed to run <cmd> : failed to load any docker-compose.*y*l files: <nil>`

**Describe the solution you'd like**
An error message that describes the issue more generally:

`Failed to run <cmd>: <project> is not running`

**Comment by rfay** [comment]
Thanks for this! Maybe can clean up the similar stuff that comes out when you stop an already-stopped project.

Another approach on this issue is to not run custom commands at all if the project isn't started?
