### ISSUE TITLE
Update segment to send "common fields" 

### ISSUE THREAD

**Issue by unn** [drud/ddev#1726]
**Describe the bug**
Our custom `OS`, `ddev_version`, and `instrumentation_user` should be updated to leverage common fields, see links below.

**Expected behavior**
Our custom implementation of `OS` should be replaced by the common field os.
Our custom implementation of `ddev_version` should be replaced by the common field app version.
Our custom implementation of `instrumentation_user` should be replaced with a common trait like name or a custom trait. 

**Additional context**
https://segment.com/docs/spec/common/#context
https://github.com/segmentio/analytics-go/blob/v3.0/context.go#L95 
https://github.com/segmentio/analytics-go/blob/v3.0/context.go#L39

**Comment by rfay** [comment]
While doing this:
* Consider moving the global_config.yaml specification of a known user to a specific field of its own.
