### ISSUE TITLE
Pass ddev composer create --no-install flag (and other flags)

### ISSUE THREAD

**Issue by WarpedOne** [drud/ddev#1737]
**Is your feature request related to a problem? Please describe.**
Entered command 'ddev composer help create`
A list showed `--no-install` as a valid flag.
Entered command `ddev composer create drupal-composer/drupal-project:8.x-dev --stability dev --no-install`
It halted with an `unknown flag` error.

**Describe the solution you'd like**
I need to get the composer files set up with the `ddev composer create` command, then edit it before running the install, rather than waiting for the install to complete, deleting all but the composer.json/lock files and running the install again.
If a flag does not adversely affect ddev, just pass it to composer. There are other flags that do not appear on the output when it errors unknown flags.

**Describe alternatives you've considered**
In the past, I have downloaded the zip file containing the project and unzipped contents to the local directory. Depending on whether this is windows or not, permissions might not be the same. Windows is very flakey when it comes to permissions shared with a linux environment.

**Additional context**
Contents of command execution and results:
`$ ddev composer help create
Usage:
  create-project [options] [--] [<package>] [<directory>] [<version>]

Arguments:
  package                              Package name to be installed
  directory                            Directory where the files should be created
  version                              Version, will default to latest

Options:
  -s, --stability=STABILITY            Minimum-stability allowed (unless a version is specified).
      --prefer-source                  Forces installation from package sources when possible, including VCS information.
      --prefer-dist                    Forces installation from package dist even for dev versions.
      --repository=REPOSITORY          Pick a different repository (as url or json config) to look for the package.
      --repository-url=REPOSITORY-URL  DEPRECATED: Use --repository instead.
      --dev                            Enables installation of require-dev packages (enabled by default, only present for BC).
      --no-dev                         Disables installation of require-dev packages.
      --no-custom-installers           DEPRECATED: Use no-plugins instead.
      --no-scripts                     Whether to prevent execution of all defined scripts in the root package.
      --no-progress                    Do not output download progress.
      --no-secure-http                 Disable the secure-http config option temporarily while installing the root package. Use at your own risk. Using this flag is a bad idea.
      --keep-vcs                       Whether to prevent deleting the vcs folder.
      --remove-vcs                     Whether to force deletion of the vcs folder without prompting.
      --no-install                     Whether to skip installation of the package dependencies.
      --ignore-platform-reqs           Ignore platform requirements (php & ext- packages).
  -h, --help                           Display this help message
  -q, --quiet                          Do not output any message
  -V, --version                        Display this application version
      --ansi                           Force ANSI output
      --no-ansi                        Disable ANSI output
  -n, --no-interaction                 Do not ask any interactive question
      --profile                        Display timing and memory usage information
      --no-plugins                     Whether to disable plugins.
  -d, --working-dir=WORKING-DIR        If specified, use the given directory as working directory.
  -v|vv|vvv, --verbose                 Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  The create-project command creates a new project from a given
  package into a new directory. If executed without params and in a directory
  with a composer.json file it installs the packages for the current project.
  
  You can use this command to bootstrap new projects or setup a clean
  version-controlled installation for developers of your project.
  
  php composer.phar create-project vendor/project target-directory [version]
  
  You can also specify the version with the package name using = or : as separator.
  
  php composer.phar create-project vendor/project:version target-directory
  
  To install unstable packages, either specify the version you want, or use the
  --stability=dev (where dev can be one of RC, beta, alpha or dev).
  
  To setup a developer workable version you should create the project using the source
  controlled code by appending the '--prefer-source' flag.
  
  To install a package from another repository than the default one you
  can pass the '--repository=https://myrepository.org' flag.
  
  Read more at https://getcomposer.org/doc/03-cli.md#create-project

$ ddev composer create drupal-composer/drupal-project:8.x-dev --stability dev --no-install

Error: unknown flag: --no-install
Usage:
  ddev composer create [flags] <package> [<version>]

Examples:
ddev composer create drupal-composer/drupal-project:8.x-dev --stability dev --no-interaction
ddev composer create typo3/cms-base-distribution ^9

Flags:
      --dev                Pass the --dev flag to composer create-project
  -h, --help               help for create
      --no-dev             Pass the --no-dev flag to composer create-project
      --no-interaction     Pass the --no-interaction flag to composer create-project
      --prefer-dist        Pass the --prefer-dist flag to composer create-project
      --stability string   Pass the --stability <arg> option to composer create-project

Global Flags:
  -j, --json-output   If true, user-oriented output will be in JSON format.`

**Comment by rfay** [comment]
Sure seems reasonable. It seems to me like `ddev composer` and friends should accept *most* flags that get tagged on.

**Comment by ultimike** [comment]
I'd like to be able to use it with `ddev composer create-project drupal-composer/drupal-project:8.x-dev --stability dev --no-interaction --no-install` so that I (and my students) can get the template, make some tweaks to it (like using webflo/drupal-core-strict) prior to running `ddev composer install`.

**Comment by rfay** [comment]
(I really want this to accept all composer flags but...)

A really valid way to do the same thing is just to curl the composer.json from the required source and then `ddev composer install` after making your tweaks. I do suspect that despite its widespread usage `composer create-project` is not that useful.

**Comment by ultimike** [comment]
I understand, but the [Drupal Composer/Drupal Project Composer template](https://github.com/drupal-composer/drupal-project/) is a bit more than just a composer.json file - is there a way to curl all of it?

**Comment by rfay** [comment]
You're right, I just tried it. It *almost* worked but then croaked on the scripthandler stuff. 

I'll take a look at this today. There are many, many use-cases where it's an annoying problem.

**Comment by rfay** [comment]
#1816 should fix this. 

I'd love it if people could see if it meets their expectations.

Artifacts for testing are at https://circleci.com/gh/drud/ddev/17553#artifacts/containers/0

**Comment by ultimike** [comment]
#1816 works for my use case: `ddev composer create drupal-composer/drupal-project:8.x-dev --stability dev --no-interaction --no-install`
