### ISSUE TITLE
Add debug flag to show hirak/prestissimo output, otherwise suppress by default.

### ISSUE THREAD

**Issue by WarpedOne** [drud/ddev#1738]
**Is your feature request related to a problem? Please describe.**
When hirak/prestissimo was added to 1.9.0, composer install/upgrade functions exploded with multiples of additional information.

**Describe the solution you'd like**
As this might help with debugging, I suggest that it be added as an optional debug item, instead of as default output.

**Additional context**
Possible related issue: https://github.com/drud/ddev/issues/782

**Comment by rfay** [comment]
Thanks for the issue - Most people seem to have been happy enough with the speedup to not worry about it. But I'd love to see that suppressed, I don't know any real purpose it serves. Did you see any clue in hirak/prestissimo about how this can be suppressed?

**Comment by WarpedOne** [comment]
In hirak/prestissimo queue: https://github.com/hirak/prestissimo/issues/125

**Comment by rfay** [comment]
Except that's from 2016 right? No optional config... ???

**Comment by WarpedOne** [comment]
Not sure what the code does. Maybe it got overwritten?

**Comment by WarpedOne** [comment]
https://github.com/hirak/prestissimo/pull/128/commits/34683f0e4c1bce5d3d684ae3694e8437904f92f2

**Comment by WarpedOne** [comment]
Looks like STDOUT/STDIO were mentioned in other issues that were posted. Maybe they switched, leaving this output on a different stream.

**Comment by WarpedOne** [comment]
$io->writeError("    <comment>$successCnt/$totalCnt</comment>:\t$url", true, IO\IOInterface::VERBOSE);

**Comment by rfay** [comment]
There's no code introduced to make prestissimo run; it's just installed globally and this is what happens.

**Comment by WarpedOne** [comment]
That was code from prestissimo patch

**Comment by rfay** [comment]
I understand. But I'm just saying that prestissimo installed globally does not seem to have any configuration for this.

**Comment by kaystrobach** [comment]
please keep the output - it really helps, if a package has download problems.

**Comment by rfay** [comment]
Interesting... prestissimo seems to either be broken or lost in v1.10+, not sure. But I see everything downloaded the first time, and the output you hate is GONE @WarpedOne :)

**Comment by kaystrobach** [comment]
Worked for me - is your cache gone?

**Comment by rfay** [comment]
To test, I killed off the cache and did a composer build, and everything was one-by-one download.

**Comment by WarpedOne** [comment]
@kaystrobach Errors could be forced out, but successful ones suppressed by default. I'm just suggesting that too much output obscures a normal stream, but full output should be available if requested. By default, debugging output should be in debug mode and not production mode. Including Prestissimo suddenly included a lot more output that had to be checked to make sure it wasn't a bunch of new errors. Even having just the summary line with normal output and detail in a debug mode would be a great improvement.

**Comment by rfay** [comment]
#1820: This was accidentally lost and nobody seems to care, so I closed that one. Closing this one to go with it.
