### ISSUE TITLE
Don't delete existing EOL newline characters in config.yaml

### ISSUE THREAD

**Issue by mfrieling** [drud/ddev#1740]
**Describe the bug**
Running `ddev config` always deletes an existing EOL newline character at the end of the file, which is enforced in projects by https://editorconfig.org rules:

```
# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true
```

See https://thoughtbot.com/blog/no-newline-at-end-of-file#history-lesson and http://gcc.gnu.org/ml/gcc/2003-11/msg01568.html about this (which references section 2.1.1.2 of the ANSI C 1989 standard and others).

**To Reproduce**
1. Create an new DDEV project by running `ddev config` in an empty folder
2. Manually edit the `.ddev/config.yaml` file in an editor of your choice and add an empty newline at the end of the file.
3. Optionally create a Git repository in the same folder to better monitor the changes (`git init && git add -f .ddev/config.yaml && git commit -m "DDEV config created"`
4. Run `ddev config` again confirming all questions and then check the end of the file manually or do a `git diff`.

**Expected behavior**
1. Don't delete existing EOL newline characters in `.ddev/config.yaml` or other manipulated files.
2. (optional) Add the EOL newline character to any DDEV generated file by default according to the ANSI C 1989 standard.

**Screenshots**
![ddev_eol](https://user-images.githubusercontent.com/8668756/62056628-5cf78880-b21e-11e9-9de2-2f5b51284e81.jpg)

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Windows 10
 - Docker version:  18.09.2
 - ddev version: 1.5.0 - 1.10.0-alpha3

**Comment by rfay** [comment]
Should be pretty easy. ddev recreates the config.yaml on every ddev start, but it can certainly include the final EOL.

**Comment by rfay** [comment]
@mfrieling It looks like this only happens on project type php and drupal7. Easy patch...
