### ISSUE TITLE
Use wildcard FQDN for ddev sites instead of manipulating /etc/hosts (most of the time)

### ISSUE THREAD

**Issue by rfay** [drud/ddev#175]
## What happened (or feature request):

Feature request: Our current way of specifying a ddev hostname for a site involves manipulating /etc/hosts, which requires root permissions. However, we can do what kalabox does and switch to using an actual resolvable domainame which has a wildcard on it. We can retain the `ddev hostname` command for uses when people are offline and give them explicit instructions on it.

Spinoff from [Security: ddev can be used to sudo an arbitrary command ](https://github.com/drud/ddev/issues/117)

## Related source links or issues:

**Comment by rickmanelius** [comment]
This was touched on today. @rfay Can you provide additional information what this would look like as well as what the fallback would be if an internet connection was not available?

**Comment by rfay** [comment]
The way current versions of kalabox do this is they put a wildcard dns record for *.kbox.site, so that `anythingyouwant.kbox.site` will resolve to 127.0.0.1.  We could do *.ddev.site or any such. 

When offline, a person would have to manually add a hosts file entry. On osx or linux, this could be done with `sudo ddev hostname me.ddev.site 127.0.0.1`. I would expect on windows we'd have to give instructions about how to run ddev with admin privs. (Or have them edit c:\windows\system32\drivers\etc\hosts)

BTW, our current usage of .local isn't exactly correct, as it is in fact reserved for [specific local mDNS operations](https://en.wikipedia.org/wiki/.local).

**Comment by rickmanelius** [comment]
Related issues:

* Features similar to vagrant share.
* Could this help us with local SSL.

**Comment by rfay** [comment]
AFAIK it's impossible to get a real SSL cert that points to a non-internet IP address, so it probably wouldn't do that. 

I don't think it's related to the ideas in "vagrant share"

**Comment by rickmanelius** [comment]
@rfay In my experience, the process of generating a CSR to obtain an SSL does not require providing the IP address or having the domain A record pointed at a server/IP address.

**Comment by rickmanelius** [comment]
Now on the flip side, getting a real, non-self signed cert to work without connection to the internet, that's a separate item that I'm not sure would work/not work. So breaking this into two components: 1) getting an issued SSL cert and 2) getting said cert to work locally against 127.0.0.1 without connection to the internet.

**Comment by rfay** [comment]
I might be having a brain fart. Easy to test. You're certainly right that the IP is a part of getting a cert. Either I'm just off in lala land or *browsers* no longer accept.

**Comment by rfay** [comment]
On SSL: Sorry, I was just backwards confused. I was thinking about issuing a cert for an unregistrable domain (like .local or whatever). I was able to put junkssl.drud.com on my local machine at 127.0.0.1, and use our drud.com wildcard to access it, both firefox and chrome were fine with it. 

The one issue here is that we'd have to distribute a key/crt for the wildcard cert, which would mean that even a slightly ambitious person could use that in another context. But since we control the DNS, it doesn't seem like *that* big an issue, but worthy of thought.

However... this doesn't really have anything to do with this issue, because DNS is unneeded for the use of SSL. Just having a name in the hosts file and a wildcard cert configured on the nginx container would do the job just fine.

![screenshot_5_17_17__10_59_am](https://cloud.githubusercontent.com/assets/112444/26166404/a5ebbd10-3af0-11e7-83d8-1cf5bc20eabc.png)

**Comment by rickmanelius** [comment]
This is not a priority at the moment. Pulling out of this for now.

**Comment by rickmanelius** [comment]
This will also be addressed in #416 and we will continue to use /etc/host as a fallback when access to a valid TLD is not achievable.
