### ISSUE TITLE
Provide clearer feedback when a hook's "exec" or "exec-host" task fails

### ISSUE THREAD

**Issue by greggles** [drud/ddev#1765]
**Is your feature request related to a problem? Please describe.**
When a hook runs and the command it's running fails the output can be pretty disorienting.  It made me wonder if ddev was broken somehow. 

**Describe the solution you'd like**
It would be nice if the output showing errors could also suggest to the user something like "Try commenting out the hook and rerunning the command with ddev exec." When it fails in `ddev exec` it could also be good to say "Try running with ddev ssh."

**Describe alternatives you've considered**
It could also be good to truncate the output and say "Some of the output is shown here. Rerun the command using `ddev exec` to view all the error output."

**Additional context**
<img width="1363" alt="1__fish__Users_gknaddison_Sites_devdesktop_datacommons-prod__fish_" src="https://user-images.githubusercontent.com/392568/62426335-ac1b3e80-b6a0-11e9-9d5b-633a403e5c87.png">

https://gist.github.com/greggles/77865f1ef2da06cf05fd0b8aec3b1c42

**Comment by greggles** [comment]
I've seen similar feedback at the end of other command tools like brew or maybe npm/yarn/gulp. It would say something like "There was a problem running the command. Read the error messages from earlier in the report. This is not an error with brew." Or something.

**Comment by rfay** [comment]
Thanks for the good report. The next time you run across a better style of reporting, could you capture it in a screenshot and put it here? Hopefully it will be long since fixed by then, but well, things aren't always ;)

**Comment by greggles** [comment]
This [react and babel issue](https://stackoverflow.com/questions/53768470/problems-with-babel-loader-in-react-create-app) gives an example of some of the potential language you could use when a hook has exited with a nonzero status code.

```
There might be a problem with the hook running the command: 

    {command that failed without any output}

It is likely not a bug in DDEV, but something you need to fix in running that command.
You could try commenting out that line in your .ddev/config.yaml to see if the error goes away. 
You should try running the command manually.
```

**Comment by rfay** [comment]
Thanks!

**Comment by rfay** [comment]
@greggles would love to see what you think of the PR in #1860, artifacts are listed at https://github.com/drud/ddev/pull/1860#issuecomment-538617008
