### ISSUE TITLE
ddev start fails after recent update of Docker to 2.1.0.1

### ISSUE THREAD

**Issue by klonos** [drud/ddev#1778]
**Describe the bug**
After updating Docker from 2.1.0.0 to 2.1.0.1...

**To Reproduce**
1. `ddev start` on an existing project

```
ddev start
Starting myproject... 
Building db 
Building web 
ddev-myproject-db is up-to-date 
ddev-myproject-dba is up-to-date 
Starting ddev-myproject-web ... done

ddev-router is up-to-date 
Failed to start myproject: web container failed: log=, err=container exited, please use 'ddev logs -s web` to find out why it failed
```

...

```
ddev logs -s web
...
...
+ mkdir -p /home/username/.drush/commands
+ ln -s /var/tmp/backdrop_drush_commands /home/username/.drush/commands/backdrop
ln: failed to create symbolic link '/home/username/.drush/commands/backdrop/backdrop_drush_commands': Permission denied
```

**Expected behavior**
Project starts as per usual.

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: MacOS Mojave 10.14.6
 - Docker version information: 19.03.1
 - ddev version information: 1.10.0
 - config.yaml contents for the misbehaving project
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them? **No custom configuration - project was running fine before the Docker update.**

**Additional context**
This is obviously a Backdrop CMS project - things seem to fail when trying to symlink backdrop drush.

**Comment by rfay** [comment]
Thanks for the report. I assumed you edited `ln: failed to create symbolic link '/home/username/.drush/commands/backdrop/backdrop_drush_commands': Permission denied` ?

**Comment by rfay** [comment]
I'm unable to recreate this. Could you please `ddev poweroff` and then restart docker and see if it still does it?

**Comment by klonos** [comment]
Yup. Real username is `greg`, and here's the output of `id -a`:

```
uid=501(greg) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),701(com.apple.sharepoint.group.1),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh)
```

In the meantime, I have reverted to 2.1.0.0 and things work again.

**Comment by rfay** [comment]
When you get brave again, I'd appreciate it if you'd try doing the `ddev poweroff` and see what happens. My uid is also 501 (as most simple mac setups are), and your username isn't interesting enough to make a difference, sad to say.

**Comment by rfay** [comment]
Oh, please do provide your .ddev/config.yaml when you get a chance. Thanks!

**Comment by klonos** [comment]
> ... your username isn't interesting enough to make a difference...

Ha 😆 

> When you get brave again ...

Restoring Docker to the previous version has borked all my local installations, so I may need to wait for a next bug release of Docker before I upgrade. ...wish I had my old Mac with me ...I could get as brave as I want there and give it a go 😞 😅 

Here's my config.yml (confirmed to work with Docker 2.1.0.0, but fail with 2.1.0.1):

```
cat .ddev/config.yaml 
APIVersion: v1.10.0
name: "myproject"
type: backdrop
docroot: docroot
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "8080"
router_https_port: "4343"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
timezone: ""
```

**Comment by klonos** [comment]
...here's my global config, in case it matters:

```
cat ~/.ddev/global_config.yaml 
APIVersion: v1.10.0
omit_containers: []
instrumentation_opt_in: true
last_used_version: v1.6.0
project_info:
...
...
```

Wondering why it says last used version is 1.6.0 🤔

**Comment by rfay** [comment]
There's nothing very interesting in your config.yaml's, thanks for sharing those.

Don't forget to dump you db from time to time. That's the only thing that can't be completely recreated even after a docker factory reset. `ddev snapshot` or `ddev export-db`. I keep a .tarballs directory in each project with a variety of dumps in it.

Basically, you should be able to factory-reset docker any time and be fine if you just have a db dump.  I do it periodically.

My only guess so far is that you shut down docker while your projects were running, which isn't normally that bad (although docker doesn't notify running containers in that case, and sometimes database corruption can happen, but that has nothing to do with what you're seeing)

I do recommend `ddev poweroff` or `ddev stop -a --stop-ssh-agent` before turning off (or upgrading) docker though. It's also required before ddev upgrades. It's conceivable that you had that situation, so when the upgraded docker came up, you has a project in the "stopped" state, and then you did a `ddev start` and it failed to recover. In that case, a `ddev stop` or `ddev poweroff` would have solved it though. 

But I haven't been able to recreate this.

**Comment by hebbet** [comment]
i'm having a similar problem after the update to 2.1.0.1

> Building db
Service 'db' failed to build: The command '/bin/sh -c (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -m --gid "$username" --comment '' --uid $uid "$username" || useradd   -m --gid "$username" --comment '' "$username")' returned a non-zero code: 6
Failed to start wp: Failed to run docker-compose [-f C:\projects\wp\.ddev\docker-compose.yaml up --build -d], err='exit status 1', stdout='Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
 ---> c57ecd0827ec
Step 3/6 : ARG username
 ---> Running in 914787e4f3a7
Removing intermediate container 914787e4f3a7
 ---> 397b097d7da6
Step 4/6 : ARG uid
 ---> Running in a3a8042b9fbb
Removing intermediate container a3a8042b9fbb
 ---> 9ecfa6b7a5b0
Step 5/6 : ARG gid
 ---> Running in 4ed72688406b
Removing intermediate container 4ed72688406b
 ---> fc76042626ba
Step 6/6 : RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -m --gid "$username" --comment '' --uid $uid "$username" || useradd   -m --gid "$username" --comment '' "$username")
 ---> Running in b82def75a53c
groupadd: GID '1000' already exists
groupadd: Can't get unique GID (no more available GIDs)
useradd: group 'pascal' does not exist
useradd: group 'pascal' does not exist
', stderr='Building db
Service 'db' failed to build: The command '/bin/sh -c (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -m --gid "$username" --comment '' --uid $uid "$username" || useradd   -m --gid "$username" --comment '' "$username")' returned a non-zero code: 6'

I tried to remove all data with ``ddev stop --remove-data --omit-snapshot`` but the problem still exists.

**Comment by rfay** [comment]
@hebbet your problem is different. In your config.yaml you have a pinned dbimage, please remove that line and `ddev restart`. If you need mariadb 10.1, use `mariadb_version: 10.1`. Old images won't work here.

**Comment by rfay** [comment]
Lots and lots of people have now updated without trouble, and no other reports have been received, so I'm going to close this for now, happy to continue the conversation here.
