### ISSUE TITLE
Database import fails: pv: /mnt/ddev_config/importdb291747059/*.*sql: No such file or directory

### ISSUE THREAD

**Issue by localhorst** [drud/ddev#1787]
**Describe the bug**
Database import fails, but I get a final message "Successfully imported database for projectname"

```
λ ddev import-db --src=.ddev/tmp/db.sql.gz
pv: /mnt/ddev_config/importdb291747059/*.*sql: No such file or directory
AdditionalConfiguration.php already exists and is managed by the user.
Successfully imported database for foobar
```

But: In PhpMyAdmin / mysql, database db is empty and has no tables. 
I was able to import the database with PhpMyAdmins import function

**To Reproduce**
- Update project from DDEV 1.9.1 to 1.10.1 with ddev config
- dev import-db --src=.ddev/tmp/db.sql.gz

**Expected behavior**
Database is imported and db content is accessible. 

**Version and configuration information (please complete the following information):**
- Windows 10 
- Docker 2.1.0.1
- ddev: 
```
DDEV-Local version      v1.10.1
commit                  v1.10.1
db                      drud/ddev-dbserver:v1.10.0-10.2
dba                     drud/phpmyadmin:v1.10.0
ddev-ssh-agent          drud/ddev-ssh-agent:v1.10.1
docker                  19.03.1
docker type             Docker Desktop For Windows
docker-compose          1.24.1
os                      windows
router                  drud/ddev-router:v1.10.0
web                     drud/ddev-webserver:v1.10.0
```
- config.yaml:
```
APIVersion: v1.10.1
name: foobar
type: typo3
docroot: htdocs
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: true
provider: default
use_dns_when_possible: true
timezone: ""
```

**Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?**
- Solr configuration (docker-compose.solr.yml)
- Yes, I have removed the Solr configuration. The problem remains. 

**What I have tried**
- Get rid of old images with `ddev remove --remove-data --omit-snapshot`
- Use .ddev/tmp/db.sql instead of .ddev/tmp/db.sql.gz

Thanks for looking into this.

**Comment by rfay** [comment]
* Please make sure you have adequate disk space allocated to docker, although I don't suspect that's the problem given your description. Use the Docker Desktop app to increase the available disk space.
* Just so you know about the workaround so you can get your job done, in v1.10+ you can use two different techniques in v1.10 that don't require copying the sql file to the docker mount: 1) `zcat db.sql.gz | ddev import-db` and `zcat db.sql.gz | ddev mysql db`
* Is is possible that your db.sql.gz is not a valid gzipped .sql file? Are you able to share it?
* I'm unable to recreate your issue on Windows with ddev v1.10.2, no matter how I try it. (I do recommend strongly that Windows users upgraded to v1.10.2, since there were installer issues with earlier v1.10 releases)
* Would you mind downloading this database file and try importing it? This is what I used to test. https://www.dropbox.com/s/whm5uw7ane67me9/db.sql.gz?dl=0

**Comment by localhorst** [comment]
Hi @rfay, 

It's resolved. It was probably related to a Docker problem mounting the shared drives. 
I can't defintely say what helped, but I have two (related) suspects:

- Kaspersky has tightened their firewall settings relating in silent failure of shared drives. If you want to check up on this, go to Docker > Settings > Shared Drives, then unshare and reshare your drives. Docker might tell you that a firewall is blocking the share. 

- Changing vEthernet (DockerNat) adapter settings as described here: https://stackoverflow.com/a/52753321/283854

Remember that I originally turned off Kaspersky, however I guess I should have restarted Docker after that.

Note: 
I had enough space on my filesystem as well as in docker, and the sql.gz / .sql files were valid. 

Thanks for your awesome support!

**Comment by rfay** [comment]
Could you say just a bit more about your firewall and/or virus checker situation? 

Unsharing and re-sharing the drive is a super-effective technique on Windows, thanks for mentioning that. It needs to go in the docs. That often solves the problem where the user's password has changed as well.

**Comment by localhorst** [comment]
I have a corporate license of Kaspersky for Windows 10.
Version 19.0.0.1088

I have updated the Kaspersky program module just before the error occured. 
Kaspersky runs with modified settings (lowered security in ragards to Docker & DDEV) 
Right now, ddev is working with Kaspersky Firewall activated. 
In Kaspersky's firewall settings, I have registered several processes to be treated as trusted. (application rules)

Kaspersky is registered as the systemwide virus software. 

I found 2 Hyper-V network adapters:
10.0.75.1/28 (vEthernet (DockerNAT)) - Public network
172.17.92.81/28 (vEthernet (Default Switch)) - Local network

Do you need any more info?

**Comment by rfay** [comment]
Thanks, that will help others to understand what happened - I just wanted it written down for the future. It would probably help if you mention for others the specifics of 

> I have registered several processes to be treated as trusted. (application rules)

Do you need this issue reopened?

**Comment by supdake** [comment]
I am having this issue as well.  I am running in ubuntu on wsl2. Drive space is not a problem, ddev ssh -s db gets me to the db prompt, df /mnt/ddev_config returns 'df: /mnt/ddev_config: No such file or directory'  did a poweroff and start no errors, but didn't fix it.  Any help would be amazing.

**Comment by rfay** [comment]
@supdake what DDEV version are you running? Since this was closed in 2019, I imagine you should open a new issue.

If /mnt/ddev_config is not mounted into the container, your Docker provider definitely isn't working and you should restart it. 

If you're not using at least DDEV v1.21.6 you should be. 

DDEV actually checks on `ddev start` to make sure that /mnt/ddev-config is mounted and warns you on start. 

Anyway, check your docker provider, restart it, open a new issue, and make sure you do the required `ddev debug test` output and include that as requested.

**Comment by supdake** [comment]
I will open a new ticket, but ddev version is 1.21.6., but I don't see a /mnt/ddev-config warning on ddev start.

the debug:

ben@PF3DHS3K:~/dev/academymortgage$ ddev debug test
Running bash [-c /tmp/test_ddev.sh]
======= Existing project config =========
These config files were loaded for project academymortgage: [/home/ben/dev/academymortgage/.ddev/config.yaml]
name: academymortgage
type: drupal9
php_version: 8.0
webserver_type: nginx-fpm
webimage: drud/ddev-webserver:v1.21.5
router_http_port: 80
router_https_port: 443
additional_hostnames: []
additional_fqdns: []
database: {mariadb 10.4}
mailhog_port: 8025
mailhog_https_port: 8026
phpmyadmin_port: 8036
phpmyadmin_https_port: 8037
project_tld: ddev.site
use_dns_when_possible: true
composer_version: 2
nodejs_version: 16
default_container_timeout: 120
======= Creating dummy project named  tryddevproject-16909 in ../tryddevproject-16909 =========
OS Information: Linux PF3DHS3K 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
User information: uid=1000(ben) gid=1000(ben) groups=1000(ben),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),116(netdev),999(docker)
DDEV version:  ITEM             VALUE
 DDEV version     v1.21.6
 architecture     amd64
 db               drud/ddev-dbserver-mariadb-10.4:v1.21.5
 dba              phpmyadmin:5
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.5
 docker           24.0.4
 docker-compose   v2.15.1
 docker-platform  PF3DHS3K
 mutagen          0.16.0
 os               linux
 router           drud/ddev-router:v1.21.5
 web              drud/ddev-webserver:v1.21.5
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
mutagen-enabled=false
nfs-mount-enabled=false
router-bind-all-interfaces=false
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
auto-restart-containers=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=
use-docker-compose-from-path=false
project-tld=
xdebug-ide-location=
no-bind-mounts=false
use-traefik=false
wsl2-no-windows-hosts-mgt=false

======= DOCKER info =========
docker location: -rwxr-xr-x 1 root root 35922416 Jul  7 08:50 /usr/bin/docker
docker version:
Client: Docker Engine - Community
 Version:           24.0.4
 API version:       1.43
 Go version:        go1.20.5
 Git commit:        3713ee1
 Built:             Fri Jul  7 14:50:55 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.4
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.5
  Git commit:       4ffc614
  Built:            Fri Jul  7 14:50:55 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
DOCKER_DEFAULT_PLATFORM=notset
======= Mutagen Info =========
======= Docker Info =========
Docker platform: PF3DHS3K
Using docker context: default (unix:///var/run/docker.sock)
docker-compose: v2.15.1
Using DOCKER_HOST=unix:///var/run/docker.sock
Docker version: 24.0.4
Able to run simple container that mounts a volume.
Able to use internet inside container.
Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                1006.9G      5.7G    949.9G   1% /

Container ddev-academymortgage-dba  Removed
Container ddev-academymortgage-db  Removed
Container ddev-academymortgage-web  Removed
Network ddev-academymortgage_default  Removed
Project academymortgage has been stopped.
The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again.
Existing docker containers:
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
Creating a new ddev project config in the current directory (/home/ben/dev/tryddevproject-16909)
Once completed, your configuration will be written to /home/ben/dev/tryddevproject-16909/.ddev/config.yaml

Configuring unrecognized codebase as project type 'php' at /home/ben/dev/tryddevproject-16909/web
Configuration complete. You may now run 'ddev start'.
Network ddev_default created
Starting tryddevproject-16909...
Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
Network ddev-tryddevproject-16909_default  Created
Container ddev-tryddevproject-16909-dba  Started
Container ddev-tryddevproject-16909-web  Started
Container ddev-tryddevproject-16909-db  Started
Container ddev-router  Started
Successfully started tryddevproject-16909
Project can be reached at https://tryddevproject-16909.ddev.site https://127.0.0.1:32819
======== Curl of site from inside container:
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 21 Jul 2023 16:11:44 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== curl -I of http://tryddevproject-16909.ddev.site from outside:
HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Fri, 21 Jul 2023 16:11:44 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== full curl of http://tryddevproject-16909.ddev.site from outside:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-16909'
======== Project ownership on host:
drwxr-xr-x 4 ben ben 4096 Jul 21 10:11 ../tryddevproject-16909
======== Project ownership in container:
drwxr-xr-x 4 ben ben 4096 Jul 21 16:11 /var/www/html
======== In-container filesystem:
Filesystem     Type  1K-blocks    Used Available Use% Mounted on
/dev/sdc       ext4 1055762868 6181008 995878388   1% /var/www/html
======== curl again of tryddevproject-16909 from host:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-16909'
Thanks for running the diagnostic. It was successful.
Please provide the output of this script in a new gist at gist.github.com
Running ddev launch in 5 seconds
If you're brave and you have jq you can delete all tryddevproject instances with this one-liner:
    ddev delete -Oy $(ddev list -j |jq -r .raw[].name | grep tryddevproject)
In the future ddev debug test will also provide this option.

Please delete this project after debugging with 'ddev delete -Oy tryddevproject-16909'
