### ISSUE TITLE
Container only update once then is frozen in time.

### ISSUE THREAD

**Issue by voyou-sbeaulieu** [drud/ddev#1795]
**Describe the bug**
We currently have a problem with one project. Every time we do a ddev start it's working fine but after 1-2 reload, the website is still available but nothing we do on the code effect it. No change at all. Look's like the container and the code aren't linked anymore... If we do a ddev restart it's working again for 1-2 reload... This already happens to us few time but only once max. This time it's doing it all the time.

**To Reproduce**
1. Just do ddev start
2.  reload page 1-2 time.
3. container and code aren't linked anymore...
4. ddev restart for a quick fix but then 2. again

**Expected behavior**
Should work as other projects.

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: [macOS High Sierra]
 - Docker version information:
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 - ddev version information (use `ddev version`)
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
Sysopss-MacBook-Pro:wp-placerosemere sbeaulieu$ ddev version
DDEV-Local version      v1.8.0                        
commit                  v1.8.0                        
db                      drud/ddev-dbserver:v1.8.0-10.2
dba                     drud/phpmyadmin:v1.8.0        
ddev-ssh-agent          drud/ddev-ssh-agent:v1.8.0    
docker                  18.09.2                       
docker-compose          1.23.2                        
domain                  ddev.local                    
os                      darwin                        
router                  drud/ddev-router:v1.8.0       
web                     drud/ddev-webserver:v1.8.0 
 - config.yaml contents for the misbehaving project
APIVersion: v1.8.0
name: wp-placerosemere
type: php
docroot: public
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "8000"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default

 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?
Nothing...

**Comment by rfay** [comment]
It sounds like docker isn't working right for you. If you haven't already restart docker, and restart the computer as well. 

You're editing the code on the host right, and making changes there? And then you `ddev ssh` and you don't see those changes reflected inside the container? Please check that out carefully to see. If you're editing on the host and it's not updating in the container, then something's wrong with docker.  Besides restarting docker, check your disk and memory allocation for docker.

**Comment by rfay** [comment]
No response from OP, hoping this is working for you, happy to continue the conversation here, but closing this for now.
