### ISSUE TITLE
Option to expose web environment to network

### ISSUE THREAD

**Issue by FamousWolf** [drud/ddev#1798]
**Is your feature request related to a problem? Please describe.**
Since version 1.10.0 the web environment is only accessible from localhost. Before it was accessible from other devices on the same network. We use ddev for multiple projects. Often we need to try/view something on a colleague's environment. So we have an internal DNS to point *.developername.internaldomain to the development environments. We then use `additional_fqdns` in config.yaml to make it available through projectname.developername.internaldomain.

**Describe the solution you'd like**
I would like a configuration option `exposeToNetwork` (or something similar) in config.yaml to expose the web environment to the network. Default should be false.

**Describe alternatives you've considered**
We've tried `ddev share`, but without a paid account the subdomain keeps changing. We're currently using the solution in #1794, which works, but a cleaner solution would be great.

**Comment by tkieslich** [comment]
I have a Solution with custom command under in commands/host/env
```
#!/usr/bin/env bash

## Description: Enable Access to ddev Webserver in local Network
## Usage: ddev expose
## Example: call url from other device in your local network like 192.168.178.122:8899 (Host-IP:given-Port)

# env

socat tcp-listen:8899,reuseaddr,fork tcp:localhost:32770
#socat tcp-listen:8899,reuseaddr,fork tcp:localhost:${DDEV_HOST_WEBSERVER_PORT}
```
under macos you have to install socat with `brew install socat'.
There is an Issue with DDEV_HOST_WEBSERVER_PORT in env #1812 but it works for us.

**Comment by rfay** [comment]
A note to all in this issue that v1.11.0-rc1 has #1798, which makes it all much easier.
