### ISSUE TITLE
Use parallelization to reduce platform/binary test times

### ISSUE THREAD

**Issue by beeradb** [drud/ddev#180]
## What happened (or feature request):
Currently, our tests are running at about 15 minutes, 11 of which are actual tests. We've seen a fairly dramatic increase over the last few weeks and we've added additional test sites. It would be nice to reduce overall test time by starting to take advantage of golang parallel test running.

## What you expected to happen:
Right now our code does support parallel testing. It would be nice to convert our tests for ddev stop/start/restart to all execute in parallel, which should reduce test times quite a bit without too much effort.

## How to reproduce it (as minimally and precisely as possible):
run `make test` and observe how long it takes.

## Related source links or issues:

**Comment by rickmanelius** [comment]
@beeradb Any sense of what the LOE would be? That would help prioritize.

**Comment by rickmanelius** [comment]
Updating the tags because this was in flight. @beeradb can we get a reference to the open PR?

**Comment by rickmanelius** [comment]
Similar to my comment in your PR, shall we summarize the issues surrounding this and close or tag hibernate and come back to it? @beeradb

**Comment by beeradb** [comment]
I took a  stab at this in https://github.com/drud/ddev/pull/206 and ended up backing off, due to a few constraints:

- We use environment variables when starting sites. When trying to start multiple sites at once, we end up with multiple goroutines overwriting environment variables and stepping on each others toes.
- This is (possibly) fixable by adding delays to the start, but this introduces complexity that's probably not worth it. Even if we could fix it this way, in circle we don't have the docker images available during test runs, so we end up needing to prime those via a docker pull beforehand.
- This could also be achieved via circle parallelization, but I'm not keen on resorting to circle-specific features unless we really really need it. I'd much rather things work the same everywhere, and use language features over CI features. This is consistent with what we do elsewhere, where our circle config is basically setup + a call to `make test`

**Comment by rickmanelius** [comment]
@beeradb naive question. Is it possible/practical to snapshot environment variables into a config file and then use that as the source of truth? I imagine it would require a non-trivial amount of rework, but I'm just shooting in the dark to see if there is a way to still utilize environment variables up until a point of triggering the start and then freezing from there.

**Comment by rickmanelius** [comment]
Also, short of my question sparking an idea, I'm assuming this is ready to close out to return to at a later date.

**Comment by rickmanelius** [comment]
Weird. Not sure why the PR isn't pulling up inline https://github.com/drud/ddev/pull/206.

**Comment by beeradb** [comment]
@rickmanelius I'd prefer just to move it back to incubate. I still think the issue is valid and there may be a point where it's worth the effort, but we're just not there quite yet imho.

**Comment by rickmanelius** [comment]
Adding to a future milestone and we can see when it makes sense to address this based on other timelines and resourcing.

**Comment by rfay** [comment]
We don't need to keep this on the books right now. Even though test times have increased, we're doing fine. I think it will be reasonable to take a pass at shortening test times at some time in the future, but probably parallelization isn't how we'll get it. But we don't need this issue to remind us.
