### ISSUE TITLE
Drupal sites/all/drush/drush.yml breaks multisite drush aliases; Use DRUSH_OPTIONS_URI instead

### ISSUE THREAD

**Issue by arafalov** [drud/ddev#1806]
**Describe the bug**
I am not entirely sure if it is a bug, a feature, or a documentation request. All I know is that it broke ddev update in a strange way and took a while to troubleshoot.

Basically, ddev seems to generate web/sites/all/drush/drush.yml that sets uri parameter. Setting the parameter globally is not recommended for multisite configuration.

Granted, ddev does not support multisite natively anyway, but this is something that - I believe - worked a while ago and stopped due to drush configuration reorganization (in 1.9?).

**To Reproduce**
1. Setup Drupal 8 multisite with drush alias files
2. Run drush status in one of non-default directories
3. Observe the information coming from default configuration (database name, url, etc)
4. Delete/comment out all/drush/drush.yml
5. Rerun drush status and observe correct information

**Expected behavior**
Not sure, as I don't know what problem that file was solving. So, maybe it should be a mention in documentation instead.

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: MacOS Mojave
 - Docker: 18.09.2
 - ddev: v1.10.2
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? Yes (in override file), to declare additional hostnames and DB creation commands.

**Comment by rfay** [comment]
Easy solution, not sure if it's what you want:
* Remove the line with #ddev-generated in sites/all/drush/drush.yml
* Delete or change any contents as you see fit.
* Check in the changed file. ddev will never touch it again.

The generated drush.yml makes it so people can use drush *with* a proper URL both inside the container and on the host.

**Comment by arafalov** [comment]
Right. I figured that out. After a lot of trial and error. So I am trying
to save others from same struggle.

That's why I think that just a one line in the docs maybe sufficient. Just
for those desperately searching for "multisite" keyword.

**Comment by rfay** [comment]
There's probably more to it than that. Would you care to draft (or outline) a multisite-drupal-on-ddev PR? Discuss multiple databases, drush.yml, etc? Or perhaps do a simple setup in github.com/drud/ddev-contrib with a recipe?

**Comment by arafalov** [comment]
I don't know everything but I can definitely do a starter outline in the
next few days.

**Comment by rfay** [comment]
The more I think about it ddev-contrib gives you the most flexibility and you don't have to shoehorn it in, and you can be very specific to Drupal multisite usage.  Thanks!

**Comment by arafalov** [comment]
I do not see a mention of ddev-contrib anywhere in the main documentation
for DDev. So if - hypothetically - I already documented the whole multisite
setup there, I still would not be able to discover the information existing.

Or am I missing something?

**Comment by rfay** [comment]
ddev-contrib is still new, and needs better referencing from the main docs. But the idea is that (mostly) the main docs are less specific about specific CMSs and applications, and people can go completely nuts with specific recipes for very vertical things in in ddev-contrib (and it's easier to get changes in there). This is a small open-source project. I'm the only maintainer. The docs aren't perfect :) But you can make them better with your contributions. Thanks!

**Comment by rfay** [comment]
(@Gonzalo2683 got troubles solved in https://github.com/drud/ddev/issues/1813)

I think after [the multisite example/recipe](https://github.com/drud/ddev-contrib/pull/10) lands, we should look at moving the drush.yml config that caused trouble here into `drush/sites/self.site.yml` if that seems like it will work. It would be nice for that `drush/drush.yml` not to be in people's way.

**Comment by rfay** [comment]
The environment variable DRUSH_OPTIONS_URI is less intrusive, recommended for this by @greg.1.anderson, see https://docs.drush.org/en/master/using-drush-configuration/

We would probably lose proper operation of `drush uli` on the host side, but it's probably OK.

**Comment by rfay** [comment]
I think the right answer to this one is going to be to let people turn off ddev's settings file generation, as in #2024

**Comment by rfay** [comment]
In v1.13, you can turn off settings file management. Hope you can test this out and see if you like it in prerelease (edge) https://github.com/drud/ddev/releases/tag/v1.13.0-rc1
