### ISSUE TITLE
Webserver symlink resolver is caching some folders

### ISSUE THREAD

**Issue by pquerner** [drud/ddev#1807]
In a setup, where symlinks on files are used, you only see the first file version - its then cached and you won't see any changes happend to the file, until the instance is restarted (ddev restart).

**To Reproduce**
These steps are for an TYPO3 installation, only.
1. Install TYPO3 CMS ^9.5 (actual version should not matter)
1.1 Add
```
  "extra": {
    "typo3/cms": {
      "root-dir": "private",
      "web-dir": "public"
    }
  },
```
to your composer.json file. This is required for `helhum/typo3-secure-web`
2. `composer require helhum/typo3-secure-web`
3. `composer install`
4. Install TYPO3 and add bootstrap_package to root TS
5. `composer dump -o`

Now you will have a folder structure like this

```
.
├── composer.json
├── composer.lock
├── private
│   ├── fileadmin
│   ├── index.php
│   ├── typo3
│   ├── typo3conf
│   ├── typo3temp
│   └── uploads
├── public
│   ├── fileadmin -> ../private/fileadmin
│   ├── index.php
│   ├── typo3
│   ├── typo3conf
│   ├── typo3temp
│   └── uploads
```

Important is what `helhum/typo3-secure-web` did to the file structure.
If you take a look at the public folder, you only find "public" worthy stuff symlinked there - from the counter part in the private folder. Such as

```
│   ├── ./public/typo3conf
│   │   └── ext
│   │       ├── bootstrap_package
│   │       │   └── Resources
│   │       │       └── Public -> ../../../../../private/typo3conf/ext/bootstrap_package/Resources/Public
```

Now here comes the fun part. **Sometimes** (I havent figured when and why) if your path includes `Js` or `js` it does cache the file. If your `js` path is `JavaScript` (like for instance in ext:bootstrap_package) then its not cached.
If your extension adds some javascript to the site via `page.includeJS` and it includes the path `Js` the file will be hardcached (I dont know if thats an actual term). If you change that, no matter what you do (apart from `ddev restart`) you will only ever see the original file again.

I've an extension which resource name for javascript file is `js` and had this issue. I tested it against ext:bootstrap_package, where the resources path for js files is `JavaScript` and it worked right out of the box. So I changed the path for the other extension also to JavaScript and voilá it worked. 

**Version and configuration information (please complete the following information):**
 - Mac OS 10.14.5
 - Docker
```
docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:18:17 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
 - ddev version 
```
ddev version
DDEV-Local version	v1.10.2                        
commit            	v1.10.2                        
db                	drud/ddev-dbserver:v1.10.0-10.2
dba               	drud/phpmyadmin:v1.10.0        
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.10.2    
docker            	19.03.1                        
docker-compose    	1.24.1                         
os                	darwin                         
router            	drud/ddev-router:v1.10.0       
web               	drud/ddev-webserver:v1.10.2
```
 - config.yaml contents for the misbehaving project
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?
Yes, and yes.
nginx/cache.conf
```
location ~ \.(css|js)(.*)$ {
    expires -1;
    add_header Cache-Control no-store;
    fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    fastcgi_param DOCUMENT_ROOT $realpath_root;
}
```
I tried that because I think its because of nginx symlink caching, see here for more information (might change the original config to have this, but I did not test it fully)
https://serverfault.com/questions/848503/nginx-caching-symlinks

**Comment by rfay** [comment]
Thanks for the excellent issue and description. So your nginx config fix didn't solve it right? Is there a predictable way to recreate the problem? The way I read the issue there's not a consistent way to recreate?

**Comment by pquerner** [comment]
No, the nginx config did not fix it.
I've only been able to target "js" / "Js" vs. "JavaScript" so far. 
I'll try to create you a tarball asap so you can just spin it up and play with it.

**Comment by pquerner** [comment]
A sleep later I no longer have this issue. I was preparing a tarball this morning and couldnt even get to see the issue there. Also not on the project I was experiencing it with yesterday. I shall silently close this issue and burry myself in shame.

**Comment by rfay** [comment]
Nah, it will be back. When it comes back try to trap that little guy. Thanks for the effort on this!
