### ISSUE TITLE
exec-host and exec hook command output should be displayed even if there's an error

### ISSUE THREAD

**Issue by cdracars** [drud/ddev#1818]
**Describe the bug**
If passing a bash script into the exec function error messages from the script does not output to the screen however the exit code does.

**To Reproduce**
1. Create a bash script that throws an error message with exit 1.
2. Place bash in config under the exec section
3. Restart DDev

**Expected behavior**
DDev should display the error message along with the exit code and stop the execution.

**Screenshots**

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macOS Mojave
 - Docker version information 
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:18:17 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

 - ddev version information: 
DDEV-Local version	v1.10.2
commit            	v1.10.2
db                	drud/ddev-dbserver:v1.10.0-10.2
dba               	drud/phpmyadmin:v1.10.0
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.10.2
docker            	19.03.1
docker-compose    	1.24.1
os                	darwin
router            	drud/ddev-router:v1.10.0
web               	drud/ddev-webserver:v1.10.2

**Comment by rfay** [comment]
Example I used:
```
hooks:
  pre-start:
    - exec-host: bash -c 'echo "broken" &&  exit 1'
```
