### ISSUE TITLE
ddev fails on Linux with groupadd errors

### ISSUE THREAD

**Issue by nicodh** [drud/ddev#1821]
**Describe the bug**
After upgrading to ddev 10.x 
I get an error when running ddev start

Service 'db' failed to build: The command '/bin/sh -c (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")' returned a non-zero code: 6 
Failed to start myproject: Failed to run docker-compose [-f /home/myproject/.ddev/docker-compose.yaml -f /home/myproject/.ddev/docker-compose.environment.yaml up --build -d], err='exit status 1', stdout='Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
 ---> c57ecd0827ec
Step 3/6 : ARG username
 ---> Using cache
 ---> 2de48f2f77fd
Step 4/6 : ARG uid
 ---> Using cache
 ---> 91f420774269
Step 5/6 : ARG gid
 ---> Using cache
 ---> e608c2797459
Step 6/6 : RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")
 ---> Running in dd83df4f467f
groupadd: GID '1000' already exists
groupadd: Can't get unique GID (no more available GIDs)
useradd: group 'myusername' does not exist
useradd: group 'myusername' does not exist

After downgrading to ddev v1.9.1 it works again.
I tried 1.10.3 & 1.11 alpha

I'm on Ubuntu 18.04

**Comment by rfay** [comment]
I think you have a pinned dbimage in your config.yaml.  please remove it and try again. Onld images won't work. If you need mariadb 10.1 use mariadb_version:10.1 instead of pinning an image.

**Comment by nicodh** [comment]
Thanks! That solved the problem!
