### ISSUE TITLE
Add "last run date" and "version" to "ddev list"

### ISSUE THREAD

**Issue by ultimike** [drud/ddev#1830]
I think it would be helpful to add a couple of columns to the "ddev list" command output. Specifically, a "last run date" (or similar) as well as the version of DDEV config that the project is based on. 

Maybe hide these (and other?) extra columns behind a "--all" option?

-mike

**Comment by rfay** [comment]
I already have trouble with the width of `ddev list`, so am not really in favor of this. I'm going to close for now, but happy to reopen if anybody else comes on board.
