### ISSUE TITLE
Drupal settings.local.php and services.yml, disable cache and twig debugging not work

### ISSUE THREAD

**Issue by webabond** [drud/ddev#1831]
**Describe the bug**
Hi, i develop a Theme with DDEV and Drupal8, When i enable the Twig Debugging in services.yml it not works, i not see the comments in firefox or chrome. Also when i disable the cache in settings.local.php for frontend tools like browsersync, its not working.
**To Reproduce**
Go to sites folder and copy the example.settings.local.php to settings.local.php and enable the lines:
$settings['cache']['bins']['render'] = 'cache.backend.null';
$settings['cache']['bins']['dynamic_page_cache'] = 'cache.backend.null';

and go also to sites/default, copy the file: default.services.yml to services.yml and change unter twig-debug: debug to true and cache to null. 

All this settings do nothing, we not have for debugging or the cache is disabled. 

**Expected behavior**
Disable the Cache and enable Twig debugging.

**Comment by rfay** [comment]
Sounds like you've got it all working, closing this for now, happy to continue the conversation.
