### ISSUE TITLE
Add xz support to import-db, import-files, maybe export-db

### ISSUE THREAD

**Issue by agviu** [drud/ddev#1838]
**Is your feature request related to a problem? Please describe.**
xz is a very good compressor, which is being used more and more everyday. The linux kernel project releases in xz, by default, for example.

**Describe the solution you'd like**
Include support of xz compressed files for the commands 'import-db' and 'import-files'.

**Describe alternatives you've considered**
Currently gzip and tar are supported, so these can be used.

**Additional context**
So ideally I could import-db files compressed with xz (*.sql.xz) and import-files also compressed with xz (tar.xz).

**Comment by rfay** [comment]
For mysql, you should know that the mysq,, export-db and import-db commands accept stdin/stdout, so it's super easy to do the traditional thing:
```
xz -dc file.sql.xz | ddev mysql db
xz -dc file.sql.xz | ddev import-db
ddev export-db --gzip=false | xz >db.sql.xz
ddev exec mysqldump db | xz >db.sql.xz
```
```

**Comment by rfay** [comment]
However, I can see how this would be really great for import-db, if you use xz for compression and get the tarball down. Just recognizing .xz out of the box would be really nice.

**Comment by rfay** [comment]
I imagine we can do this someday, but in a year of the issue being open there hasn't been a "me too" added here. Happy to reopen in the future.
