### ISSUE TITLE
Allow additional_fqdns to have real certificates

### ISSUE THREAD

**Issue by andrewbelcher** [drud/ddev#1843]
**Is your feature request related to a problem? Please describe.**
`additional_fqdns` allows you to set up fully qualified domain names that get routed to a site. With #1834, this can now be open to external network interfaces, expressly to solve the scenario of people wanting to use DDev for CI/CD/Staging applications. However, when you visit your FQDN, you are served an invalid certificate - the master certificated from `mkcert`.

**Describe the solution you'd like**
The two obvious options seem to be:
- (simpler) allow you to mount genuine certificates for FQDNs.
- (harder) use certbot to auto generate certificates for FQDNs.

I think the first is more than acceptable, as the type of person who is going to use DDev for CI/CD/Staging purposes _should_ be more than capable of generating and providing the certificate themselves. The second just makes their life simpler, but probably adds a level of complexity and support that shouldn't really be on DDev's plate.

**Comment by andrewbelcher** [comment]
Not worked with go and I'm a noob with Docker, but from a quick look at the structure of https://github.com/drud/ddev/blob/master/containers/ddev-router/nginx.tmpl, I would expect the solution would be something along the lines of:

- House the real key/certificate (and potentially chain) in `.ddev/??`
- Inject this into the router container as `/etc/nginx/certs/project-{$project}.(crt|key|chain.crt)`
- In the loop around [L286](https://github.com/drud/ddev/blob/master/containers/ddev-router/nginx.tmpl#L286), check if `$host` is FQDN (may be a more direct way to check) and whether there is a certificate. If so, set `$cert := coalesce "project-" $project` (guess at the templating syntax) for that loop to so it points at that rather than the master key.

**Comment by rfay** [comment]
Hmm, you're stretching ddev more all the time. It's intended to be a local development environment, and it already has `ddev share` for securely sharing with others.

Did you know that you can use mkcert to install the root ca from the dev box as trusted root ca on other systems? Just copy the files from $(mkcert -CAROOT) on the source machine into the $(mkcert -CAROOT) on the machine you want to trust it, and use $(mkcert -install)

**Comment by rfay** [comment]
See [Installing the CA on other systems](https://github.com/FiloSottile/mkcert#installing-the-ca-on-other-systems)

**Comment by andrewbelcher** [comment]
@rfay yes, I'm very aware of that, so I would take absolute no offence if you decided this was _too_ far and said no! There has to come a point where we find a different tool for the job!

**Comment by rfay** [comment]
This is now possible in v1.16.0+ (currently the alphas), https://ddev.readthedocs.io/en/latest/users/extend/custom-tls-certificates/#custom-tls-certificates. Closing.
