### ISSUE TITLE
ddev auth ssh insists i enter a passphrase to enable my key, i don't have a passphrase, and it fails

### ISSUE THREAD

**Issue by mlncn** [drud/ddev#1844]
**Describe the bug**

Since at least ddev version v1.10.2 but probably a little bit before i haven't been able to use `ddev ssh auth` anymore, because it asks me to enter a passphrase that simply doesn't exist.

Has anyone else seen this?

**To Reproduce**

Have a single SSH identity *without* a passphrase for its private key.

```
ddev poweroff
ddev auth ssh
Building ddev-ssh-agent 
Creating ddev-ssh-agent ... done
 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
Enter passphrase for /home/mlncn/.ssh/id_rsa: 
```

If the identity were added, the key enabled anyway this would be a minor annoyance, but it isn't, forcing me to run composer from outside of ddev.

**Expected behavior**

The ssh agent inside ddev machines can see my identity (`ssh-add -L`)

**Additional context**

I've made sure i don't have any other keys in ~/.ssh, and nothing at all in ~/.ssh/config, and that it's definitely looking at the expected private key, and that this key still works for all other purposes.

I'm at a loss and hoping someone at least has a pointer.  Ideally that's not "add a passphrase to your SSH key, ya newb", but i'll accept that with good reasons  :-)

**Comment by mlncn** [comment]
Related to #414 trying to derive a workaround from the days before this command but haven't worked it out yet.

**Comment by mlncn** [comment]
`~/.ssh/id_rsa` is owned by me with permission 600.

**Comment by mlncn** [comment]
It is a large and... possibly nonstandard, i can't remember, size, but there's no question the key itself works, using it constantly for our servers, GitLab.com, Drupal/GitLab, etc.

**Comment by mlncn** [comment]
I worked around this by adding another key:

```
ssh-keygen -f ~/.ssh/ddevworkaround
```

Then it simple worked for that one:

```
ddev auth ssh
Identity added: /home/mlncn/.ssh/ddevworkaround (mlncn@oryx)
```

....  and now i've looked at the password and keys manager for the old and new keys, and *it* thinks i have a passphrase for the old one, and not for the new one, which leads me to conclude...

I do have a passphrase and completely forgot it.

Which leads to a a very minor question for DDEV:

* Can `ddev auth ssh` use my keyring like everything else?  (And really, it used to work.)

And a very big question for me:

* How could i have forgotten even having a passphrase, let alone what it was?

**Comment by rfay** [comment]
So `ddev auth ssh` doesn't understand macOS keyrings or gpg keyrings, just your ssh authentication, whatever is in ~/.ssh. Does that answer the minor question for ddev?

**Comment by mlncn** [comment]
Yup.

So if it used to be working and now isn't, it would seem that i set the passphrase accidentally, which would explain not remembering it, or i'm confusing which computer i was using when, which given how much the new one has been in for repair is quite possible.

Thanks!

**Comment by rfay** [comment]
Glad you got it all sorted out!
