### ISSUE TITLE
Extend the command 'ddev describe' to include CMS-specific details (esp. WordPress)

### ISSUE THREAD

**Issue by fschmittlein** [drud/ddev#1845]
I need for my project https://github.com/fschmittlein/WordPress-Distribution a useful output to print the password for the wordpress admin user. Maybe we can print more information later.

**Comment by fschmittlein** [comment]
Slack chat: https://typo3.slack.com/archives/C8TRNQ601/p1569162649055600

**Comment by rfay** [comment]
Any thoughts on how ddev could know the WordPress admin user/pass? Or are you thinking this would be made available in config.yaml or some other text file?
Any other CMS-specific things you'd like in `ddev describe`?

**Comment by rfay** [comment]
Related: #788 : Show information about 3rd-party services in `ddev describe`.

**Comment by wolffc** [comment]
in our typo3 project we have a bunch of additional services we would like to "report" (show urls / credentials) in `ddev describe` 

i think the most versatile way would be to add post-describe hooks / command so every project could ship its own information provider scirpts which add to the output of ddev describe.

**Comment by rfay** [comment]
Agreed, this is definitely a priority. I'm not quite yet exactly sure how to do it; it will mean parsing docker compose config of the extra services, but that should be do-able. We may have to specify particular magic keys that give this info.

**Comment by rfay** [comment]
As of v1.14+ 3rd party service details are exposed, especially URLs.  I don't know how ddev could possibly know anything like default usernames or passwords. 

I'm going to close this for now @fschmittlein but happy to continue the conversation and reopen it or try a more focused approach to what to provide. At least we're now one step closer.
