### ISSUE TITLE
Allow ddev custom commands with any extension, but ignore the extension.

### ISSUE THREAD

**Issue by wizonesolutions** [drud/ddev#1852]
**Is your feature request related to a problem? Please describe.**
When I create custom commands in PhpStorm, it prompts me for the file type for each one. File types are global, so associating each specific commandfile with Text or Shell Script might cause problems with other projects in the future.

**Describe the solution you'd like**
Allow command files to have extensions (`.sh`, `.rb`, `.php`, whatever, anything except `.example`) but be referred to by their unsuffixed name. For example, `xd.sh` would be runnable as `ddev xd`. (`xd` is a short form alias for `disable_xdebug`).

**Describe alternatives you've considered**
I tried seeing if `xd.sh` would work, but it would only respond to `ddev xd.sh`.

**Comment by rfay** [comment]
Thanks for the good thinking... My first impression is that this would be a bad idea because "command.sh" and "command.cmd" and "command.php" would all respond to "command". Who knows who would win.

Note that PHPStorm will be very, very happy to edit your command, even recognizes it as a bash script and does syntax coloring.  New->File->junkcommand Works fine. I tell it it's a bash script. But maybe easier to `touch newcommand` and move forward from there.

**Comment by wizonesolutions** [comment]
Yeah, it's not a difficult workaround, it just...pollutes the PhpStorm file types :wink: 

I think that ddev should just throw an error if it doesn't know which command to use. It's an extreme edge case because the developer can easily edit their custom commands and fix the issue in seconds. They're unlikely to create identically-named commands to begin with. If they did, it would probably be a lapse in thinking, and they're likely to test the command immediately, get the error from ddev, and go, "Ah!" and fix it.

**Comment by rfay** [comment]
In the Linux/Unix/Mac world extensions aren't actually used, just shebang's, so I don't think we'll do this. 

I agree about the PHPStorm annoyance. I almost had that licked the other day by hitting ESC when it asked for that, but it wasn't repeatable.

**Comment by wizonesolutions** [comment]
OK. Is it possible to hide commands from ddev? Maybe by storing them
outside of the folder (with an extension) and symlinking them in (without
one)?

**Comment by rfay** [comment]
Currently, it's easy to hide them from ddev by calling them "something. example". Why would you have them in the commands directory if you don't want ddev to find them?

**Comment by wizonesolutions** [comment]
I meant more as a workaround to waiting for the IDE to index the new "file
extension." I could symlink it as the actual command name I want, but edit
it with an extension.

**Comment by rfay** [comment]
Make it .mycommand.sh then, and symlink to mycommand.
