### ISSUE TITLE
WordPress: Add support for ClassicPress

### ISSUE THREAD

**Issue by btopro** [drud/ddev#1853]
ClassicPress (CP) is a popular fork of WordPress (WP) that's completely compatible with WordPress. If I get ClassicPress and run `ddev init` it detects WP and starts the install correctly.

https://www.classicpress.net/

As far as "support" really this could probably be mostly some UI mentions and an image that nearly identical to the WP image / routine but has CP listed. CP reminds me a lot of the reasons why Backdrop forked -- a community going in a different direction based on heavily overlapping code but yet different context and scope from those currently leading the community. There's hundreds in their slack channel and I'm increasingly seeing plugin developers say they support WP / CP.

Please consider adding support either via documentation tweaks or in sections talking about communities DDEV supports. I think it would look good on the project and help foster that community as well (since it's basically just pointing out that yes, this stuff does work basically out of the box with it already and makes it super simple).

**Comment by btopro** [comment]
`composer require classicpress/classicpress`
https://packagist.org/packages/classicpress/classicpress

**Comment by rfay** [comment]
I think the best place for somethjing like this is a writeup in https://github.com/drud/ddev-contrib - would you be willing to do a PR there? As you say, it's pretty simple, and it will let people know how things work.

**Comment by btopro** [comment]
happy to help but not following from that repo as to how I'd best do that. is there a drupal or wordpress example recipe somewhere I can use to pattern off of?

**Comment by rfay** [comment]
I'd say https://ddev.readthedocs.io/en/stable/users/cli-usage/#wordpress-quickstart is the best recipe, but in a ddev-contrib PR (maybe in the recipes section, like the [REDAXO recipe](https://github.com/drud/ddev-contrib/tree/master/recipes/redaxo-cms) you could explain what ClassicPress is about and any thing that might be unusual about it.

Thanks!

**Comment by rfay** [comment]
I tried ClassicPress out and it does seem to work out of the box just fine and just like WordPress. So what you're asking is that we just mention in the docs as equivalent support?

I do think that the REDAXO recipe would be a good thing to imitate for a ClassicPress recipe in ddev-contrib.

**Comment by rfay** [comment]
Looking forward to a PR to ddev-contrib expounding the benefits of ClassicPress, especially with composer. Thanks so much!
