### ISSUE TITLE
Dockerfile context for containers should probably be .ddev/web-build/Dockerfile

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1855]
**Describe the bug**

@wizonesolutions points out that it's difficult and awkward to add files to a .ddev/web-build/Dockerfile build, because the *context* is set to the ddev-owned .ddev/.webimageBuild directory.

So for example, if you want to use ADD to add a script into the web image, you would have to put that script in .ddev/.webimageBuild, which isn't a very good place, and not really in "user space". 

A possible solution would be for ddev to copy the contents of .ddev/web-build/ into .ddev/.webimageBuild at start time. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: [e.g. Windows 10, macOS High Sierra]
 - Docker version information (use `docker version`) and insert it here.
 - ddev version information (use `ddev version`)
 - config.yaml contents for the misbehaving project
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

**Additional context**
Add any other context about the problem here. Thanks!

**Comment by rfay** [comment]
I took an initial look at this and it was a little complicated, but I think if the Dockerfile is explicitly specified outside context it could work. It's also worth looking at the .ddev/web-build/Dockerfile and .ddev/.web-build/Dockerfile as multi-stage build instead of concatenated Dockerfiles...

Another technique would just be to copy whatever's in .ddev/web-build/ into the context area at build time.

**Comment by mglaman** [comment]
Ran into this. I tried to copy in additional ngnix config

**Comment by rfay** [comment]
Hope you can test this out and see if you like it in prerelease (edge) https://github.com/drud/ddev/releases/tag/v1.13.0-rc1
