### ISSUE TITLE
fresh drupal 8 error

### ISSUE THREAD

**Issue by theobouwman** [drud/ddev#1863]
I just did a fresh drupal 8 install with devv en am getting this error:
```
The website encountered an unexpected error. Please try again later.
```
With these logs:
```
2019/10/03 19:15:03 [error] 2157#2157: *28 FastCGI sent in stderr: "PHP message: Error: Class 'Drupal\image\Plugin\Field\FieldType\ImageItem' not found in /var/www/html/web/core/lib/Drupal/Core/Field/FieldConfigStorageBase.php on line 30 #0 /var/www/html/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(193): Drupal\Core\Field\FieldConfigStorageBase->mapFromStorageRecords(Array, Array)
#1 /var/www/html/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(300): Drupal\Core\Config\Entity\ConfigEntityStorage->doLoadMultiple(Array)
#2 /var/www/html/web/core/lib/Drupal/Core/Entity/EntityBase.php(541): Drupal\Core\Entity\EntityStorageBase->loadMultiple(Array)
#3 /var/www/html/web/core/modules/field/field.module(202): Drupal\Core\Entity\EntityBase::loadMultiple(Array)
#4 [internal function]: field_entity_bundle_field_info(Object(Drupal\Core\Entity\ContentEntityType), 'user', Array)
#5 /var/www/html/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(392): call_user_func_array('field_entity_bu...', Array)
#6 /var/www/html/web/core/lib/Drupal/Core/Entity/EntityField" while reading response header from upstream, client: 172.18.0.6, server: _, request: "POST /user/login HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "mysite.ddev.site", referrer: "https://mysite.ddev.site/user/login"
```

**Comment by rfay** [comment]
Could you say how you did the fresh drupal8 install? Did you do it like this?

https://ddev.readthedocs.io/en/latest/users/cli-usage/#drupal-8-quickstart

Did you remember to `ddev composer install` if not ?

**Comment by theobouwman** [comment]
jup, dit not work

**Comment by rfay** [comment]
Sorry, I can't help with so little information. I'd appreciate if you could start again, make sure you have current ddev, and go through https://ddev.readthedocs.io/en/latest/users/cli-usage/#drupal-8-quickstart (in a new directory) and then let me know explicitly what didn't work and when it didn't work. I've done it dozens of times without trouble. If you can post here your exact steps and when you had trouble it would be great.

**Comment by rfay** [comment]
No response from OP, but happy to continue the conversation here, but closing for now.  I think a fresh D8 install with the quickstart instructions will work OK.

**Comment by JonathanW-Q2** [comment]
Hi @rfay , I am having this issue as well. I'm using DDEV v1.12.0 on Windows 10 Enterprise 1809 with Docker Desktop v2.2.0.0 (42247). Initially, I tried to setup a Drupal 8 environment using the Drupal 8 Quickstart instructions, but that generated a bunch of errors. So, I deleted everything and started over using your instructions here: https://github.com/drud/ddev/issues/697#issuecomment-405740743

Those instructions worked without generating any errors, but when I visit the site URL, it gives the error:
`The website encountered an unexpected error. Please try again later.`

I ran "ddev logs", but I'm not quite sure what to make of the output. My level of knowledge appears to be limited here. :) I've attached the output to this post. Any ideas what might be going on? Is there anything else I can do to help narrow down the issue?
[ddev_logs.txt](https://github.com/drud/ddev/files/4104865/ddev_logs.txt)

**Comment by JonathanW-Q2** [comment]
I managed to get the site working, although I still don't know what the initial issue was caused by. I ran `ddev exec drush st` and it indicated that the database connected and the bootstrap was successful. So, I tried using drush to run the standard install with the following:
`ddev exec drush site:install standard --db-url='mysql://db:db@db/db' --site-name='Drupal 8 Test'`
That succeeded, and when I went to the site URL it came up normally.

I've got my site running, but I'm happy to redo everything to try and hunt down the initial issue if you'd like.

**Comment by rfay** [comment]
@JonathanW-Q2 The problem you're having is the Drupal issue https://www.drupal.org/project/drupal/issues/3103529 - at least I would assume so. Please follow up there. AFAICT it has nothing to do with ddev.

Note though that Docker Desktop 2.2.0.0 is a catastrophe on Windows - Unless you're using `nfs_mount_enabled: true` (which makes stuff work). Almost nothing works unless you're using NFS.

**Comment by JonathanW-Q2** [comment]
Thanks for the reply @rfay . I'll keep an eye on that issue. That's interesting that you say Docker Desktop is problematic on Windows. I haven't run into any issues with it so far. In fact, it fixed an issue with using shared drives while on a VPN for me. Hopefully I'm not speaking too soon. ;)

**Comment by rfay** [comment]
It's only this week's 2.2.0.0 release of Docker Desktop that's problematic. Has created havoc. Not recommended unless you take the time to set up NFS, which is way worth doing anyway. Take a look at the issues at the top of the [issue list](https://github.com/drud/ddev/issues)
