### ISSUE TITLE
Cannot create container for service db: invalid mount config for type "bind": bind source path does not exist:

### ISSUE THREAD

**Issue by mikikuke** [drud/ddev#1864]
I installed docker toolbox for windows 10 home
it works..it installed everything
then I installed ddev windows installer and i ran this

created directory ddev
cd into that directory and ran 
ddev config
put the directory name  where I will put my drupal 8 files
selected drupal8 from install questions
then ran
ddev start
and I got these errors

Cannot create container for service db: invalid mount config for type "bind": bind source path does not exist:

full error is

$ ddev start
Starting radiestezija...
mkcert may not be properly installed, we suggest installing it for trusted https support, `brew install mkcert nss`, `choco install -y mkcert`, etc. and then `mkcert -install`
Building db
Building web
Creating ddev-radiestezija-db ... error

ERROR: for ddev-radiestezija-db  Cannot create container for service db: invalid mount config for type "bind": bind source path does not exist: /d/ddev/.ddev

ERROR: for db  Cannot create container for service db: invalid mount config for type "bind": bind source path does not exist: /d/ddev/.ddev
Encountered errors while bringing up the project.
Failed to start radiestezija: Failed to run docker-compose [-f D:\ddev\.ddev\docker-compose.yaml up --build -d], err='exit status 1', stdout='Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
 ---> 8cee191bf6ed
Step 3/6 : ARG username
 ---> Using cache
 ---> fb19fb44a580
Step 4/6 : ARG uid
 ---> Using cache
 ---> 6cfceb43f5dd
Step 5/6 : ARG gid
 ---> Using cache
 ---> d234f266874d
Step 6/6 : RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")
 ---> Using cache
 ---> 2c037e2c0213

Successfully built 2c037e2c0213
Successfully tagged drud/ddev-dbserver:v1.11.0-10.2-built
Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
 ---> b8e18695926f
Step 3/6 : ARG username
 ---> Using cache
 ---> a99e36ba30dd
Step 4/6 : ARG uid
 ---> Using cache
 ---> 10eb29fe788d
Step 5/6 : ARG gid
 ---> Using cache
 ---> 97f517663dfc
Step 6/6 : RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")
 ---> Using cache
 ---> daecf7e84ce2

Successfully built daecf7e84ce2
Successfully tagged drud/ddev-webserver:v1.11.0-built
', stderr='Building db
Building web
Creating ddev-radiestezija-db ... error

ERROR: for ddev-radiestezija-db  Cannot create container for service db: invalid mount config for type "bind": bind source path does not exist: /d/ddev/.ddev

ERROR: for db  Cannot create container for service db: invalid mount config for type "bind": bind source path does not exist: /d/ddev/.ddev
Encountered errors while bringing up the project.'

**Comment by rfay** [comment]
Hi there - In Docker Toolbox, only the home directory is shared with docker by default: 

> Your project directory must be inside your home directory, as only the home directory is shared with Docker by default. Docker Toolbox (via Virtualbox) can share other paths, see [link](https://stackoverflow.com/a/35498478/215713)

https://ddev.readthedocs.io/en/stable/users/docker_installation/#windows-installation-docker-toolbox

**Comment by mikikuke** [comment]
you mean project directory for ddev installation?
i installed docker toolbox on c:/programfiles/dockertoolbox
you want to say i need to start ddev in that directory and not for example on d:/ddev

**Comment by mikikuke** [comment]
i installed mkcert with choco and ran the ddev start again

got this

something with db not being installed

λ ddev start
Starting radiestezija...
mkcert may not be properly installed, we suggest installing it for trusted https support, `brew install mkcert nss`, `choco install -y mkcert`, etc. and then `mkcert -install`
Building db
Building web
Creating ddev-radiestezija-db ... error

ERROR: for ddev-radiestezija-db  Cannot create container for service db: invalid mount config for type "bind": bind source path does not exist: /d/ddev/.ddev

ERROR: for db  Cannot create container for service db: invalid mount config for type "bind": bind source path does not exist: /d/ddev/.ddev
Encountered errors while bringing up the project.
Failed to start radiestezija: Failed to run docker-compose [-f D:\ddev\.ddev\docker-compose.yaml up --build -d], err='exit status 1', stdout='Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
 ---> 8cee191bf6ed
Step 3/6 : ARG username
 ---> Using cache
 ---> fb19fb44a580
Step 4/6 : ARG uid
 ---> Using cache
 ---> 6cfceb43f5dd
Step 5/6 : ARG gid
 ---> Using cache
 ---> d234f266874d
Step 6/6 : RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")
 ---> Using cache
 ---> 2c037e2c0213

Successfully built 2c037e2c0213
Successfully tagged drud/ddev-dbserver:v1.11.0-10.2-built
Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
 ---> b8e18695926f
Step 3/6 : ARG username
 ---> Using cache
 ---> a99e36ba30dd
Step 4/6 : ARG uid
 ---> Using cache
 ---> 10eb29fe788d
Step 5/6 : ARG gid
 ---> Using cache
 ---> 97f517663dfc
Step 6/6 : RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")
 ---> Using cache
 ---> daecf7e84ce2

Successfully built daecf7e84ce2
Successfully tagged drud/ddev-webserver:v1.11.0-built
', stderr='Building db
Building web
Creating ddev-radiestezija-db ... error

ERROR: for ddev-radiestezija-db  Cannot create container for service db: invalid mount config for type "bind": bind source path does not exist: /d/ddev/.ddev

ERROR: for db  Cannot create container for service db: invalid mount config for type "bind": bind source path does not exist: /d/ddev/.ddev
Encountered errors while bringing up the project.'

**Comment by rfay** [comment]
No, it's your *home* directory that's the issue. Your *project* needs to be in your home directory unless you do some configuration work with toolbox. 

So if your home directory is C:\Users\mikikuke, I'd recommend putting your ddev project in C:\Users\mikikuke\sites\mysite or something like that.

**Comment by mikikuke** [comment]
i dont know where my home directoy is....you mean where i installed docker toolbox?

**Comment by rfay** [comment]
Your home directory is in C:\Users\<something> on a Windows machine. If your login is mikikuke, for example, it's probably "C:\Users\mikikuke".

**Comment by mikikuke** [comment]
I see
yes i have c/users/miki
so I should cd to that folder and start ddev inside....can I create ddev subfolder for better organization?
like c:/users/miki/ddev

**Comment by rfay** [comment]
I recommend creating a directory that is where you put projects, like C:\Users\miki\sites. Then create  a project in there that has a name representing the project you're working on. So if your project is "awesomesite", put the project in C:\users\mikl\sites\awesomesite

**Comment by mikikuke** [comment]
C:\Users\fende\ddev
λ ddev config
Creating a new ddev project config in the current directory (C:\Users\fende\ddev)
Once completed, your configuration will be written to C:\Users\fende\ddev\.ddev\config.yaml

Project name (ddev): radiestezija

The docroot is the directory from which your site is served.
This is a relative path from your project root at C:\Users\fende\ddev
You may leave this value blank if your site files are in the project root
Docroot Location (current directory): radiestezija
Warning: the provided docroot at C:\Users\fende\ddev\radiestezija does not currently exist.
Create docroot at C:\Users\fende\ddev\radiestezija? [Y/n] (yes): y
Created docroot at C:\Users\fende\ddev\radiestezija.
Found a php codebase at C:\Users\fende\ddev\radiestezija.
Project Type [drupal7, drupal8, wordpress, typo3, backdrop, php, drupal6] (php): drupal8
Failed to write config: project radiestezija project root is already set to D:\ddev, refusing to change it to C:\Users\fende\ddev; you can `ddev rm --unlist` and start again if the listed project root is in error

**Comment by mikikuke** [comment]
i went to d:/ddev and use command  ddev rm --unlist  but nothing happened

**Comment by mikikuke** [comment]
i tried different name for the project 
ddev config radies8  and it worked....
but how to delete first project and unlist 
because now I have to use another name

I ran this   
λ ddev rm radiestezija --unlist
Project radiestezija is already stopped.

but still that project is mapped to d:ddev location

**Comment by mikikuke** [comment]
after new project was complete i visited  
radies.ddev.site   
or ip i got
but i get  No input file specified.
does that mean i need to put drupal files here?

**Comment by rfay** [comment]
It sounds like you don't have an index.php or index.html in the docroot. 

I recommend trying one of the quickstart recipes in https://ddev.readthedocs.io/en/stable/users/cli-usage/

**Comment by mikikuke** [comment]
but i dont want a new site...i want to work on a clone that is on my server....
so i just download all the files in this directoy

**Comment by rfay** [comment]
The quickstart explains how to check out an existing project as one option. 

You can also just download the files, same thing.

You'll have to make sure that the docroot in your .ddev/config.yaml has the directory of your index.php of index.html.

**Comment by mikikuke** [comment]
also do i need to run this?

Special considerations for Docker Toolbox:

Your project directory must be inside your home directory, as only the home directory is shared with Docker by default. Docker Toolbox (via Virtualbox) can share other paths, see link.
Please increase the memory allocated from the default 1GB to at least 2GB and increase the disk size to at least 50GB.

docker-machine rm default
docker-machine create -d virtualbox --virtualbox-cpu-count=2 --virtualbox-memory=2048 --virtualbox-disk-size=50000 default
docker-machine stop
Then exit Docker Quickstart Terminal and restart it to restart Docker Toolbox.


the index.php is inside /web folder...because I used composer to install it

**Comment by rfay** [comment]
I recommend increasing your docker toolbox memory and stuff, but you don't have to do it right now. Right now it's important to just work on this one project.

Since your index.php is in the "web" directory, you need `docroot: web` in your config.yaml. Just check to make sure that's what you have.

**Comment by mikikuke** [comment]
also how to fill up the settings file to connect to db?
in xampp user was root, passwork was blank...
and in ddev? I cant find this info anywhere
and the db name is same as name of ddev import db?  same name of the file?

**Comment by rfay** [comment]
ddev describe

But ddev config sets all that up for you

**Comment by mikikuke** [comment]
great that gave me all the info

and to work on another site.....
i had to type ddev stop
and then ddev config .....
and ddev start for new site  
how do you switch between several drupal sites?

**Comment by mikikuke** [comment]
also i tried to do it again with same project name, but the project is still attached to d: location instead of home dir

Failed to write config: project radiestezija project root is already set to D:\ddev, refusing to change it to C:\Users\fende\ddev\radiestezija; you can `ddev rm --unlist` and start again if the listed project root is in error

i ran the ddev rm --unlist command inside  d:/ddev   and home directory c:/users/fende but nothing happens

**Comment by rfay** [comment]
Each project goes in its own directory. Typically the project name is the same as the directory name. Many projects can be going at the same time.

**Comment by mikikuke** [comment]
but i deleted directories and now i cant config with same name......
so i should just organize it like this

DDEV
   ----name1
   ----name2
   ........name3

i move inside each name folder and just run ddev config or ddev start? and it will continue?

**Comment by rfay** [comment]
I recommend:

sites
--- name1
--- name2

etc. I have lots of different kinds of projects. But your choice. Projects aren't usually organized by the tool you're currently using with them. And the same project can be used with multiple local tools or for different reasons. I have projects that aren't sites. I use "workspace" instead, but whatever.

**Comment by mikikuke** [comment]
can you work also with html sites ? or is it just fo cms? Cause I want to stop using xampp

**Comment by rfay** [comment]
Yes ddev works fine with HTML and PHP sites in general, and probably lots of others too.

**Comment by rfay** [comment]
Glad you got it going, closing for now. Happy to continue the conversation here or elsewhere.
