### ISSUE TITLE
I cant remove projects in ddev

### ISSUE THREAD

**Issue by mikikuke** [drud/ddev#1865]
I ran ddev config and name the project river for example
i deleted the folder later on 

and ran command again  
ddev  config 
name the project river 
but i get error...
it says 

Failed to write config: project river project root is already set to C:\Users\fende\ddev, refusing to change it to C:\Users\fende\ddev\river; you can `ddev rm --unlist` and start again if the listed project root is in error

I tried several commands
ddev rm --unlist
ddev rm -a
etc nothing works....
old projects seems to be stores somewhere inside ddev

**Comment by rfay** [comment]
ddev delete <project>

**Comment by mikikuke** [comment]
for example i tried to install ddev project on d: drive and later on you told me it needs to be started in home dir   c:  user  etc....
i deleted that folder on d:  
and now when i try to config the project with same name inside the  c::/users/mik/ddev/drupal
I get this error

Failed to write config: project radiestezija project root is already set to D:\ddev, refusing to change it to C:\Users\mik\ddev\drupal; you can `ddev rm --unlist` and start again if the listed project root is in error


I tried to run ddev delete drupal....but i get this

λ ddev delete radiestezija
OK to delete this project and its database?
  radiestezija in D:\ddev
The code and its .ddev directory will not be touched.
A database snapshot will be made before the database is deleted.
OK to delete radiestezija? [Y/n] (yes): y
project must be started to do the snapshot
Failed to start project radiestezija: Invalid Semantic Version

**Comment by rfay** [comment]
`ddev help delete` will explain to you how to run it without snapshot.
`ddev delete --omit-snapshot <project>` or `ddev delete -O <project>`

**Comment by mikikuke** [comment]
i did it thanks
