### ISSUE TITLE
HTML sites and multi databases in 1 project

### ISSUE THREAD

**Issue by mikikuke** [drud/ddev#1866]
Is it possible to use ddev for HTML sites? 

What to do if you want to have 2 databases in 2 project....
for example migration from 7 to 8....
when you do migrate you need to specify db of old d7 drupal site and have new d8 databse already installed......

**Comment by rfay** [comment]
You'll probably want to read the ddev FAQ, which tells how one project can communicate with another, https://ddev.readthedocs.io/en/stable/users/faq/

This article is great for migration with ddev, https://dev.acquia.com/blog/migrating-drupal-6-drupal-8-boss

**Comment by rfay** [comment]
Hope that gave you enough info. Closing for now, happy to continue the conversation here or elsewhere.
