### ISSUE TITLE
Allow --ignore-table= in command export-db

### ISSUE THREAD

**Issue by enzolutions** [drud/ddev#1867]
**Is your feature request related to a problem? Please describe.**
Allow user export the databse without specific tables i.e
```bash
mysqldump --host=localhost --port=32777 --user=db --password=db db \
--ignore-table=watchdog
```

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by rfay** [comment]
Please try using the `ddev mysqldump` example command. Just go into .ddev/commands/db and `ln -s mysqldump.example mysqldump` and you should have a `ddev mysqldump` comman d that will do whatever you want.

Note that you can also use mysqldump any time in the web container... which already has your project mounted, so you can dump into a .tarballs folder in your project, for example, that is mounted onto the host.

**Comment by enzolutions** [comment]
thanks
