### ISSUE TITLE
macOS Catalina: nfsd needs to change exported dir to /System/Volumes/Data/...

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1869]
**Describe the bug**

People who use nfsd and upgrade to Catalina are getting no shares; `showmount -e` shows nothing, and `nfsd checkexports` shows errors like this:

```
$ nfsd checkexports
---> Got line: #/Users/rfay -alldirs -mapall=501:20
---> Got line: /Users/rfay -alldirs -mapall=501:20 localhost
/System/Volumes/Data using UUID CBD1C659-0D22-4494-BEA6-43958CDA4391
exports:2: exported dir/fs mismatch: /Users/rfay /System/Volumes/Data
---> Got line: /Users/rfay/workspace -alldirs -mapall=501:20 localhost
/System/Volumes/Data using UUID CBD1C659-0D22-4494-BEA6-43958CDA4391
exports:3: exported dir/fs mismatch: /Users/rfay/workspace /System/Volumes/Data
```

The problem seems to be that in macOS Catalina the /etc/exports file requires /System/Volumes/Data in front of the shared path.

Partial workaround (does not solve the problem completely for ddev) is to 
1. Edit /etc/exports to change each shared path to prepend /System/Volumes/Data, so `/Users/rfay/workspace -alldirs -mapall=501:20 localhost` becomes `/System/Volumes/Data/Users/rfay/workspace -alldirs -mapall=501:20 localhost`
2. Run `nfsd checkexports` is the next step; make sure it has no complaints.
3. `sudo nfsd restart`
4. `showmount -e` should now show exported shares. 

Required items in the PR:
* ddev has to mount /System/Volumes/Data/... instead of just /Users/...
* Update the scripts/macos_ddev_nfs_setup.sh to be aware of this problem and work on all supported macOS versions.
* Update the docs to mention `nfsd checkexports`, it's mighty nice. 
* Update the docs to mention macOS debugging techniques: Run console, search for nfsd, restart
**Expected behavior**

Thanks to https://github.com/hashicorp/vagrant/issues/10961#issuecomment-511363979

**Comment by cyberswat** [comment]
Can confirm that the workaround is simple, works, and is persistent through reboots.

**Comment by rfay** [comment]
Workaround for ddev, add docker-compose.catalina.yaml like this:
```
version: '3.6'
volumes:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=host.docker.internal,hard,nolock,rw"
      device: ":/System/Volumes/Data/Users/rfay/workspace/d8composer"
```
