### ISSUE TITLE
MariaDB v10.3

### ISSUE THREAD

**Issue by motormord** [drud/ddev#1870]
Is it possible to provide MariaDB 10.3 in the existing DB container?

**Comment by rfay** [comment]
Not currently. However, I'm working on a way to add 10.3 and 10.4 and possibly other versions.

If you need an immediate workaround, the Oracle MySqL technique in https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/mysql will almost certainly work with minor modifications.
