### ISSUE TITLE
`import-db` missing from bash completions

### ISSUE THREAD

**Issue by karlshea** [drud/ddev#1872]
**Describe the bug**

`ddev import[TAB]` used to offer `import-db` and `import-files`, now it only completes `import-files`. Additionally, none of the import-db options (e.g. `--src`) are completed either.

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macOS Mojave/macOS Catalina
 - Docker version information: 19.03.2
 - ddev version information: v1.11.1
 - config.yaml contents for the misbehaving project

ddev on my machine is installed through Homebrew.

**Comment by rfay** [comment]
Thanks for this issue. I even know why I think. In some recent version import-db was only shown if you were in a project directory, and when the bash completions are created, there's no project directory.
