### ISSUE TITLE
Docker image of ddev-ssh-agent not avialable

### ISSUE THREAD

**Issue by rthideaway** [drud/ddev#1885]
Suddenlly out of the blue the docker image of ddev-ssh-agent is unavailable:
```
$ docker pull drud/ddev-ssh-agent
Using default tag: latest
Error response from daemon: received unexpected HTTP status: 503 Service Unavailable
```

This makes all our builds to fail as we are bringing up our sites via ddev on CircleCI. So images are downloaded on every build. That's unfortunately super critical for us as we cannot run any build  :/

**Comment by rthideaway** [comment]
actually this is not related, I noticed that docker site has issues:
https://status.docker.com/

closing it

**Comment by rfay** [comment]
We always appreciate it when people point out problems! Thanks.
