### ISSUE TITLE
Eclipse and xdebug  Integration with Drupal 8 and  DDev

### ISSUE THREAD

**Issue by AlexOwlCode** [drud/ddev#1887]
**Describe the bug**
1)Code Dependency Error on all file in ddev project
2)xdebug seem not work well  on eclipse and ddev,  track only index.php file

**To Reproduce**
i have  setup a local Drupal Enviroment  [https://www.drupal.org/docs/official_docs/en/_local_development_guide.html](url)
and create my web site
After i setup  eclipse PHP  and xdebug 
[https://wiki.eclipse.org/Debugging_using_XDebug](url)

**Expected behavior**
1) i Expect no dependency error
2) Debug track all file 

**Screenshots**
![EclipseError](https://user-images.githubusercontent.com/56627065/66898710-fa7e7f00-eff9-11e9-81d5-7f7e4324f9f0.JPG)

**Version**
 - Windows 10 
 - Docker version 19.03.1
 - ddev version  v1.11.1
 -config:
 APIVersion: v1.11.1
name: project11
type: drupal8
docroot: web
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: true
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
timezone: ""

**Comment by rfay** [comment]
I didn't know anybody still used eclipse or that it was still maintained. I do recommend one of the documented Ides, but every ide I've used has worked. I sure recommend the excellent phpstorm.

**Comment by rfay** [comment]
Thinking about the dependency problem... Is this a working install? Is it possible you haven't done a composer install yet?

**Comment by rfay** [comment]
It took me a while to remember how Eclipse is configured, but everything worked fine for me. I used a standard Drupal 8 composer build (https://ddev.readthedocs.io/en/latest/users/cli-usage/#drupal-8-quickstart)  and configuration like this. 

![debug_configuration](https://user-images.githubusercontent.com/112444/67024598-fb500780-f104-11e9-869e-b00b14c5f3ff.png)

![PHP-server-server](https://user-images.githubusercontent.com/112444/67024616-0014bb80-f105-11e9-8f5c-331106a65712.png)

![php-server-debugger](https://user-images.githubusercontent.com/112444/67024625-03a84280-f105-11e9-8382-294a38728cf2.png)

![php-server-path](https://user-images.githubusercontent.com/112444/67024642-09058d00-f105-11e9-8d58-1e1d461cd79d.png)

**Comment by rfay** [comment]
No response from OP, but this was a good exercise, hope it's working for you. Happy to continue the conversation here though, but closing for now.
