### ISSUE TITLE
Multiple docroots in project: custom nginx-site.conf with multiple docroots

### ISSUE THREAD

**Issue by jcrichto** [drud/ddev#1889]
We have an older site that uses multiple domains that correspond to different countries. I cannot get ddev to take a `additional_hostnames:` defined in the `.ddev/config.yaml` and resolve using a custom nginx server block vhost I define in a custom `.ddev/nginx-site.conf`.  I'm trying the most basic index.php in that test root to avoid this being an issue or complexity with the cms.

For our set up, I need to pass each site through a different index.php file that lives in different document roots.  As an example, I cloned out the default `nginx-site.conf` from `/etc/nginx/nginx-site-default.conf` and put in my .ddev folder named `nginx-site.conf`.  Here is what I appended to the bottom of my custom `nginx-site.conf`.

```
# CANADA - EN
server {
    listen 443 ssl;

    server_name ca.example.com.ddev.site;
    # here is where I redefine the docroot and just put a test index.php just to see if it work.
	root /var/www/html/lang/test;

    ssl_certificate /etc/ssl/certs/master.crt;
    ssl_certificate_key /etc/ssl/certs/master.key;
}
```

I then ran `ddev restart` and load up `https://ca.example.com.ddev.site` but it still loads the default nginx site above this server block and not the file defined in root.

Is this possible to do or am I missing a step?  We have this set up working with an older setup, but I'm trying to configure this old project with ddev to keep consistency with our other projects.

**Comment by rfay** [comment]
Can I ask why you don't just use the config.yaml's `additional_hostnames: [x, y, z]` or `additional_fqdns: [a.b.c.com]` ?

**Comment by jcrichto** [comment]
I am using `additional_hostnames:` but I need a different nginx root for each hostname.  I don't need to worry about the .ddev.site being different so I don't think I need to worry about `additional_fqdns:`  Here's a simplified tree showing the directory structure for each hostname.

```
├── lang
│   ├── en_au (au.example.ddev.site docroot)
│   │   └── index.php
│   ├── en_ca (ca.example.ddev.site docroot)
│   │   └── index.php
│   ├── en_gb (gb.example.ddev.site docroot)
│   │   └── index.php
│   ├── en_nz (nz.example.ddev.site docroot)
│   │   └── index.php
│   ├── fr_ca (ca-fr.example.ddev.site docroot)
│   │   └── index.php
│   ├── fr_fr (fr.example.ddev.site docroot)
│   │   └── index.php
│   └── test (test.example.ddev.site docroot)
│       └── index.php
└── public
    └── index.php (ddev project docroot defined by ddev config)
```

**Comment by rfay** [comment]
So you want multiple docroots; that's not something I've ever tried.  I'd love to see it work, sometmes people need it. 

You can also experiment inside the container and use `kill -1` on the nginx process. 

Another approach is to use apache-fpm if that's easier.

**Comment by jcrichto** [comment]
I'll play with the apache-fpm route.  I didn't explore that much, maybe it will behave differently.

**Comment by jcrichto** [comment]
I just got it working in case somebody else needs to know.  I was configuring the vhosts on 443.  All you need is to set up a vhost on 80 since I guess it sits behind the ddev router that handles ssl.

```
# UK
server {
    listen 80;

    server_name uk.example.com.ddev.site;
    root /var/www/html/lang/en_gb;

    include /etc/nginx/nginx_default.conf;

    location ~ \.php$ {
        root /var/www/html/lang/en_gb;
    }
}
```

**Comment by rfay** [comment]
Sorry, I should have caught that. Thanks.

**Comment by rfay** [comment]
I'd love it if you'd share your full final config with multiple sites as well.

**Comment by rfay** [comment]
#1850 is closed in favor of this one, but it has some suggestions as well.
