### ISSUE TITLE
Broken sql dump when ddev is not running before creating the dump

### ISSUE THREAD

**Issue by andre-spindler** [drud/ddev#1892]
I'm working with win10pro, using ddev 1.10.2 and 1.11.1. on different systems. Both have the same behaviour.
When exporting the database (before a ddev update, for example) I do something like this: `ddev export-db --gzip=false >backup.sql`. This syntax is part of the output from `ddev help export-db`.
This works fine, if the current ddev project is already running.
But the sqldump is broken, if the ddev project is not running. In this case the ddev project is started first, and the complete output is written to the dump file. The ddev status messages and the sql dump itself. So any import of this dump fails.
Suggestion: to prevent this, the export-db command should check the submitted command and suppress its own output. Or the users should be forced to use the -f switch for export-db. In this case the output from the help command has to be changed and perhaps also the online documentation.

**Comment by rfay** [comment]
Thanks, that's definitely a bug and appreciate you pointing it out.
