### ISSUE TITLE
ddev Windows uninstaller is not signed

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1898]
**Describe the bug**

The ddev windows uninstaller is not signed. It ought to be.

We do this for the ddev binary and the installer binary here: https://github.com/drud/ddev/blob/85fcf65cedfed2ddbefe7162a698c364835fc728/Makefile#L143-L148

There's no reason not to do the uninstaller.

**Comment by gilbertsoft** [comment]
see https://nsis.sourceforge.io/Signing_an_Uninstaller

**Comment by rfay** [comment]
Not going to worry about this at this point.
