### ISSUE TITLE
v1.11.2 - DB problem with php, but shell and phpmyadmin works -- Connect Error (2002) Connection refused

### ISSUE THREAD

**Issue by it-scripter** [drud/ddev#1901]
**Describe the bug**
After an update to docker 2.1.0.4 and ddev 1.11.2 I have no connection to the database from php. Via CLI/mysql in the container and via phpmyadmin it works. The error message is: Connect Error (2002) Connection refused

**To Reproduce**
Upgrade to ddev 1.11.2 with brew
ddev config
ddev start

**Expected behavior**
At least using a tiny php script to test the connection to the DB with a new connection. 

**Version and configuration information:**
output of ddev version
DDEV-Local version: v1.11.2                        
commit:  v1.11.2                        
db:  drud/ddev-dbserver:v1.11.0-10.2
dba: drud/phpmyadmin:v1.11.0        
ddev-ssh-agent: drud/ddev-ssh-agent:v1.11.0    
docker: 19.03.4                        
docker-compose: 1.24.1                         
os: darwin                         
router: drud/ddev-router:v1.11.0       
web: drud/ddev-webserver:v1.11.0  

config.yaml:
APIVersion: v1.11.2
name: test-01
type: php
docroot: "site"
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
timezone: ""

- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? 
No custom setting in the test case 

**Additional context**
--

**Comment by rfay** [comment]
Before each upgrade please do a `ddev poweroff` . If that doesn't solve this for you please `ddev start` and `ddev ssh` and say what happens when you run `ping db` and `mysql`

If you haven't already please also restart docker (after `ddev poweroff`)

**Comment by it-scripter** [comment]
Thank you, rfay.
In the meantime I had already uninstalled and reinstalled ddev and still had no success. 
After your hint I did poweroff and restart of ddev again. 
In the container ping resolves db to 172.24.0.3 and in my test script it works to access the database. 
This is then first a work-around.

**Comment by rfay** [comment]
Does that mean that it's working for you now @it-scripter ? 

`ddev poweroff` isn't a workaround, it's a required step in every upgrade, included as a required step each time in the release notes. We may figure out how to do that automatically...

**Comment by it-scripter** [comment]
Please excuse the imprecise wording: It works with the determined IP. The workaround for me now is to use the determined IP. Normally 127.0.0.1 would be the IP for the database.
Thank you very much for your help.

**Comment by rfay** [comment]
Please read the output of `ddev describe` 

Because the DB server is in its own container the IP will never be 127.0.0.1 unless you're in the DB container itself, or if you're accessing with a provided port from the host. 

You should be able to use host=db within the web container.

**Comment by it-scripter** [comment]
Something in the (maybe wrong) settings in an older project led me in the wrong direction. The problem is now solved. Thanks again.

**Comment by rfay** [comment]
Glad it's working for you.
