### ISSUE TITLE
DDEV adds <none> images along the webserver, dbserver and the ssh-client images

### ISSUE THREAD

**Issue by rpkoller** [drud/ddev#1912]
**Describe the bug**
DDEV has three `<none>` images for each built webserver, dbserver and ssh-agent image. Which means instead of 1867MB used it takes 7468MB? 

**To Reproduce**
`docker images -a`returns the following list: 

```
$> docker images -a
REPOSITORY            TAG                  IMAGE ID            CREATED             SIZE
drud/ddev-webserver   v1.11.0-built        b4e9557e397f        4 weeks ago         1.27GB
<none>                <none>               e0fdf7386613        4 weeks ago         1.27GB
<none>                <none>               61f87d74bc47        4 weeks ago         1.27GB
<none>                <none>               21da85015216        4 weeks ago         1.27GB
drud/ddev-dbserver    v1.11.0-10.2-built   3dcc748b3431        4 weeks ago         412MB
<none>                <none>               b37090e9e7d8        4 weeks ago         412MB
<none>                <none>               c3763d7a3c52        4 weeks ago         412MB
<none>                <none>               892ecaf458d7        4 weeks ago         412MB
drud/ddev-ssh-agent   v1.11.0-built        fdf8ec4d35fd        4 weeks ago         185MB
<none>                <none>               2cd84041a459        4 weeks ago         185MB
<none>                <none>               ec0c67173ec1        4 weeks ago         185MB
<none>                <none>               94c8476b9252        4 weeks ago         185MB
drud/phpmyadmin       v1.11.0              063f2dc8277a        6 weeks ago         153MB
drud/ddev-webserver   v1.11.0              b8e18695926f        6 weeks ago         1.27GB
drud/ddev-ssh-agent   v1.11.0              2455a3109b97        6 weeks ago         185MB
drud/ddev-router      v1.11.0              7d1a56f08a1c        6 weeks ago         191MB
drud/ddev-dbserver    v1.11.0-10.2         8cee191bf6ed        6 weeks ago         412MB
```
There are three `<none>` images for each built image. Based on this article http://www.projectatomic.io/blog/2015/07/what-are-docker-none-none-images/ "good" `<none>` images should have a size of zero, while the "bad" ones have a size like the ones my DDEV install has. But the they aren't dangling which is their characteristic described in the article. Cuz `docker images -f dangling=true` has returned zero results. 

**Expected behavior**
I would have expected either no `<none>` images or if present a size of zero. 

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macOS High Sierra 10.13.6
 - Docker version information (use `docker version`) and insert it here.
```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Thu Oct 17 23:50:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
 - ddev version information (use `ddev version`)
```
DDEV-Local version	v1.11.2
commit            	v1.11.2
db                	drud/ddev-dbserver:v1.11.0-10.2
dba               	drud/phpmyadmin:v1.11.0
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.11.0
docker            	19.03.4
docker-compose    	1.24.1
os                	darwin
router            	drud/ddev-router:v1.11.0
web               	drud/ddev-webserver:v1.11.0
```
 - config.yaml contents for the misbehaving project
not limited to a single project but is a general behavior. one config.yaml looks like that: 
```
APIVersion: v1.11.2
name: drupal88alpha
type: drupal8
docroot: ""
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
timezone: ""
```
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?
no custom configuration

**Comment by rfay** [comment]
Good point. Thanks for bringing it up. I wonder what those are from.

**Comment by rfay** [comment]
Oh, I don't think you should be using `docker images -a`, which shows intermediate images, which are totally valid. Do you have the same results with just `docker images`?  Note that just because an image is listed in `docker images -a` it doesn't mean that it takes up space, just that it has an explicit ID.

**Comment by rpkoller** [comment]
Ahhhhh did some more research based on your answer. Well the initial fact that made me wonder and suspicious was that, based on the article ( http://www.projectatomic.io/blog/2015/07/what-are-docker-none-none-images/ ), the `<none>` images got a size value. But intermediate ones had the value of zero in the article while those with a value on size are dangling. But in contrast to the fact the there weren't any dangling images listed by Docker but I had the listed sizes. That puzzled me. 

But did `docker image` like you suggested and i got: 

![Bildschirmfoto 2019-11-05 um 23 21 48](https://user-images.githubusercontent.com/1665422/68259198-7a1bce80-0039-11ea-8a1b-e048b6af95cd.png)

Then I looked for a command for the actual sizes images, containers, volumes and local caches take and got that: 

![Bildschirmfoto 2019-11-06 um 01 54 50](https://user-images.githubusercontent.com/1665422/68259234-9ae42400-0039-11ea-8952-982ecdd685fb.png)

So all good and false alarm from my side. :/ Sorry.  But the toll size wise would been too tall not to investigate or at least bring it up in here ;)

**Comment by rfay** [comment]
Thanks so much for studying this out!
