### ISSUE TITLE
DDEV project isn't starting based on a case sensitivity issue

### ISSUE THREAD

**Issue by rpkoller** [drud/ddev#1913]
**Describe the bug**
From time to time a project isn't starting stating that the path to the root of the project has changed but in fact it hasn't.

**To Reproduce**
I doubt it will be possible to reproduce, even I am unable reliably. It just "happens" from time to time. Steps I apply which lead to the problem and the measure I apply to "solve" it are: 
1. `ddev start`
2. The output says: 
```
Starting drupal88alpha...
Failed to start drupal88alpha: project drupal88alpha project root is already set to /Users/myuser/sites/drupal88alpha, refusing to change it to /Users/myuser/Sites/drupal88alpha; you can `ddev rm --unlist` and start again if the listed project root is in error
```
3. I open `~/.ddev/global_config.yaml`
4. Change the lower case of `sites` to the upper case `Sites` or the other way around for the particular site path as it is needed. Afterwards `ddev start`works again flawlessly

I am running DDEV on MacOS 10.13.6 with APFS case insensitive. In the finder Sites is uppercase but in the terminal I am able to get to the Sites directory using the lowercase way with 'cd ~/sites`. 

**Expected behavior**
I would hope DDEV wouldn't refuse to start based of case insensitivities if possible? 

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macOS High Sierra 10.3.6
 - Docker version information (use `docker version`) and insert it here.
```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Thu Oct 17 23:50:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
 - ddev version information (use `ddev version`)
```
DDEV-Local version	v1.11.2
commit            	v1.11.2
db                	drud/ddev-dbserver:v1.11.0-10.2
dba               	drud/phpmyadmin:v1.11.0
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.11.0
docker            	19.03.4
docker-compose    	1.24.1
os                	darwin
router            	drud/ddev-router:v1.11.0
web               	drud/ddev-webserver:v1.11.0
```
 - config.yaml contents for the misbehaving project
not limited to a single project. but the project file to which it happened in the example above is: 
```
APIVersion: v1.11.2
name: drupal88alpha
type: drupal8
docroot: ""
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
timezone: ""
```
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?
no

**Comment by rfay** [comment]
Yeah, ddev works across many platforms, and as you know even APFS has a case-sensitive mode, and almost all linux systems use case-sensitive filesystems.  So ddev doesn't try to work around this problem. 

You have many options though:
* Change the name of the project to match the case you usually use.
* Use bash autocomplete to navigate to the directory you want to use; it will never use the wrong case.

In general, in the world of computers... use the case that the operating system suggests. The alternative is way more pain than ddev alone is giving you right now.

**Comment by rpkoller** [comment]
ahhhhhhh I guess I've figured out what lead to the issue in the first place. Your second recommendation did the trick. Both works on my operating system, navigating to the same directory:
```
[myuser@mycomputer][~]
$> cd Sites
[myuser@mycomputer][~/Sites]
$> ..
[myuser@mycomputer][~]
$> cd sites
[myuser@mycomputer][~/sites]
$>
```
I must have accidentally used the upper case once for the sites directory. The file system might be case insensitive but the case actually matters for starting ddev. Meaning the case of the path I am currently in in the terminal has to be identical with the one stored in the according paths in `~/.ddev/global_config.yaml`. Set all path cases to lower case in the yaml file and as a fail safe will add an alias to the terminal as well as the auto complete suggestion you've made. Now i understood what was causing the issue as well as leading to it. Thanks!
