### ISSUE TITLE
WordPress: Use Bedrock for documentation (requires ddev improvements to support it)

### ISSUE THREAD

**Issue by rpkoller** [drud/ddev#1928]
**Describe the bug**
If you try to install WordPress with Composer like suggested in https://ddev.readthedocs.io/en/latest/users/cli-usage/#wordpress-quickstart you run into an unresolveable requirement package wise cuz `wpackagist-plugin/wp-i18n` is deprecated.

**To Reproduce**
1. `composer create wordpress/skeleton ~/sites/wordpress --no-interaction --prefer-dist`

**Screenshots**
![Bildschirmfoto 2019-11-08 um 11 50 02](https://user-images.githubusercontent.com/1665422/68471356-4f3e9f80-021e-11ea-840b-c576a716c343.png)

https://wpackagist.org/search?q=wp-i18n&type=any&search= is shown as inactive and got removed from the plugin repo 2018 https://wordpress.org/plugins/wp-i18n/

The best maintained and bespoke solution would be the Composer install of Bedrock: https://roots.io/bedrock/ but it is highly opinionated. Also Bedrock doesn't work well along with DDEV out of the box yet. Other options might be https://packagist.org/packages/johnpbloch/wordpress which `wordpress/skeleton` also uses as dependency and as a foundation. Another option might be https://github.com/markjaquith/WordPress-Skeleton

**Comment by rfay** [comment]
Thanks. I'm actually working on better WP support at the moment, so this helps.

**Comment by DanielRuf** [comment]
It still fails on the latest version of ddev with `wpackagist-plugin/wp-i18n`.
What is the new way?

**Comment by DanielRuf** [comment]
Ah ok, it is now the bedrock setup. Expected some hint from ddev to use this now.

https://ddev.readthedocs.io/en/latest/users/cli-usage/#wordpress-quickstart

**Comment by rfay** [comment]
Hope you got that sorted. The quickstart in the docs is intended to be the hint :)
