### ISSUE TITLE
Request for import-db and import-files work from https, etc

### ISSUE THREAD

**Issue by siliconmeadow** [drud/ddev#1930]
**Is your feature request related to a problem? Please describe.**
With several developers working on a single project, we have users regularly downloading tarballed sql dumps and "public files directory" tarballs. Many copies of these files on many users' machines as well as the considered canonical source seems a waste of storage space.

**Describe the solution you'd like**
I would be handy if you could do something like:

```ddev import-db src=https://domain.dom/sql.gz```

**Describe alternatives you've considered**
We are currently using this technique:

```wget -qO - http://domain.dom/db.sql.gz | gunzip -c | ddev exec --service=db mysql db```

so my suggestion merely cuts down an a few keystrokes in the wiki where we document ddev deployments. The slightly shorter syntax is a bit easier for remember.

**Additional context**
Of course the file will still need downloading first, but perhaps if it's in `tmp` and after successful extraction and importing, the files are deleted?

**Comment by rfay** [comment]
It's a good idea. Thanks!

**Comment by rfay** [comment]
I suspect there are too many different ways to do this, depending on the hosting or asset storage of every team, so am going to punt this to ddev-contrib. There are already two good custom commands there, https://github.com/drud/ddev-contrib/tree/master/custom-commands/fetchproductiondb and https://github.com/drud/ddev-contrib/tree/master/custom-commands/dump-and-deploy-db - closing this for now.
