### ISSUE TITLE
Xcode Simulator SSL Certificate Warning

### ISSUE THREAD

**Issue by webkomplize** [drud/ddev#1931]
**Describe the bug**
Xcode Simulator throws ssl warning calling a ddev site.

**To Reproduce**
1. Open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app
2. Open your ddev site
3. Simulator throws ssl warning

**Expected behavior**
No SSL warning and showing the site.

**Screenshots**
![Bildschirmfoto 2019-11-08 um 22 12 18](https://user-images.githubusercontent.com/56588484/68510887-ef271800-0274-11ea-8cb8-eb60168351cf.png)

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: MacOS 10.14.5 
 - Docker version: 19.03.4
 - ddev version: v1.10.2
 - config.yaml contents:
```
APIVersion: v1.10.2
name: www.test.de
type: php
docroot: ""
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
timezone: ""
```

**Comment by rfay** [comment]
mkcert installs a system CA, and a firefox CA, but I guess the Xcode simulator doesn't respect the system CA. You *can* manually add the mkcert CA to your Xcode simulator I'm sure (but I don't yet know how, hope you'll update here).  The CA files to add to your simulator are in `mkcert -CAROOT`. Probably what you need to add is the file `$(mkcert -CAROOT)/rootCA-key.pem`

**Comment by rfay** [comment]
Would you mind making an upstream issue for this in https://github.com/FiloSottile/mkcert ? I'm pretty sure you can explain it completely with your info there. AFAICT from your description, the issue is that the Xcode simulator doesn't use the macOS system store, it must have its own?.

**Comment by rfay** [comment]
No response from OP. Closing, but happy to continue the conversation here.

**Comment by jessedobbelaere** [comment]
Sorry to revive this old issue. If others like me end up here, the fix is really simple (https://www.process-one.net/blog/using-a-local-development-trusted-ca-on-macos/)

1. Drag `~/Library/Application Support/mkcert/rootCA.pem` onto the XCode Simulator
2. Go in iOS Settings > General > About > Certificate Trust Settings. It should say `mkcert` with full trust. 
3. 🎉

**Comment by jamesmacwhite** [comment]
@jessedobbelaere Hero! This should be in the docs somewhere if it isn't already. I've exclusively had to just install Xcode for the iOS simulator because of Safari's new behaviour with viewport height and the bottom bar in iOS 26.

**Comment by rfay** [comment]
A PR to https://docs.ddev.com/en/stable/users/install/configuring-browsers/ is welcome, you can just click the pencil in the upper right.

**Comment by jamesmacwhite** [comment]
Thanks @rfay, happy to PR this, will submit one in the next few hours!

**Comment by jamesmacwhite** [comment]
PR opened for the docs addition.
