### ISSUE TITLE
Add docs for `ddev delete`

### ISSUE THREAD

**Issue by andy-blum** [drud/ddev#1932]
**Is your feature request related to a problem? Please describe.**
Every now and again I need to install a project a colleague is working on for a specific issue over a short amount of time. It would be nice to have an easier-to-remember command to fully remove that project & its data from my machine

**Describe the solution you'd like**
Adding the alias `ddev destroy` to the `ddev stop --remove-data --omit-snapshot <projectname>` command

**Additional context**
- In my personal use-case, destroying the containers and data would also always be followed by removing the codebase from my machine. I'm not sure if deleting the local codebase is something DDEV is interested in doing, but it might be a nice-to-have flag option

- With the alias `destroy` it's pretty clear that users know they're taking an irreversible, destructive command, but adding a 'are you sure' or a 'type the name of this project to completely remove it' is definitely in order.

**Comment by rfay** [comment]
How about `ddev delete` ? It's been in there for a couple of versions now :)

**Comment by andy-blum** [comment]
Having trouble finding that in the docs. Is it listed in there?

**Comment by andy-blum** [comment]
https://ddev.readthedocs.io/en/latest/users/cli-usage/#removing-projects-from-your-collection-known-to-ddev

**Comment by rfay** [comment]
It would also be good to add it to https://ddev.readthedocs.io/en/latest/users/cli-usage/#favorite-commands

**Comment by rfay** [comment]
Reopened and retitled to get it into the docs, a PR would also be welcome. 

Remember that `ddev -h` is the most important doc though, and `ddev <command> -h` is *really* useful. And easier than google.

**Comment by rfay** [comment]
It is in "favorite commands", https://ddev.readthedocs.io/en/stable/users/cli-usage/#favorite-commands

It should also be in https://ddev.readthedocs.io/en/latest/users/cli-usage/#removing-projects-from-your-collection-known-to-ddev
