### ISSUE TITLE
Performance Testing, Management, Comparison (immediate and long-term techniques)

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#195]
## What happened (or feature request):

Feature request.

## What you expected to happen:

While we have done performance audits with respect to which file mount solution balances speed w/other factors, we haven't to my knowledge done a thorough analysis of resource allocation, php/mysql/nginx configuration tuning, etc. For example, when spinning up a Drupal 8 site, the installation from the standard profile takes an excessively long period of time compared to a test run against simplytest.me. I feel like there must be some quick wins there.

Additionally, it would be great to have automation in place to make sure that things like installation times don't exceed some massively high threshold, indicating a configuration or a new version of php/apache/nginx/mysql caused a massive performance loss.

## Related source links or issues:

**Comment by rickmanelius** [comment]
@beeradb updated issue summary to reflect the larger intention of what was stated in the roadmap https://github.com/drud/ddev/wiki/roadmap. Thanks for alerting me to the fact that this was still a placeholder ticket!

**Comment by rickmanelius** [comment]
Needs to be split into audit our current results, how do we track over time, how do we add to circle, and how do we compare to competitors.

**Comment by rickmanelius** [comment]
Adding more detail to get this to an actionable state.

## Audit the default mysql and nginx configurations.
## Audit the container resource allocations.

## Measurements

* [ ] For each of our test CMS installations (WordPress, Drupal 7, and Drupal 8), obtain the time required to run `ddev start` and get to the install page.
* [ ] For each of our test CMS installations (WordPress, Drupal 7, and Drupal 8), run a site install of a standard profile using WP-CLI and/or drush and measure the site speed.

## Testing/CI

* [ ] Plan for integration w/Circle CI on how to run start/stop.

## Logging

* [ ] Ultimately, storing these results for each build would be a bonus but not a requirement.

## File System

* [ ] Review of the different file mount options and the performance, pros/cons of each.

## Competitive Analysis

* [ ] Identify 3 competitors that we wish to benchmark against.
* [ ] Idenfity metrics that we wish to compare against (time to first startup? First site install? Devel generate?)
* [ ] Identify a means that we can repeat these tests automatically and with reasonable frequency.

This would probably be useful to split into separate tickets and leave this as a meta issue.

**Comment by rickmanelius** [comment]
Given the size/complexity of this, any thoughts on the inventory provided? @rfay @tannerjfco @beeradb? I'm happy to start splitting this into child issues and leave this more as a meta issue with an updated summary that links to all the child issues.

**Comment by rfay** [comment]
I think it's ready to split out - the only problem is determining how much effort we want to spend on it. We may not be ready for 2 weeks of developing benchmarks for competitors, for example. Might be possible to just create all the issues and then incubate based on priorities. For example, adding ddev up/down timing and a couple of curls to test access time, and storing the results, is low-hanging fruit.  Not trivial, but clearly in our world.

For the items under "Audits" I don't think that's quite the right word - maybe "Optimizations?" - we just need to check and make sure we're not doing silly things with config and sizing.

**Comment by rickmanelius** [comment]
@rfay Thanks for the feedback! Agreed that not everything in that list would have an equal priority and I think we should focus on the low hanging fruit first. We could use milestones and/or labels (actionable versus hibernate) to delineate what is important now versus a wishlist item. The automated tests against competitors seems like a heavy lift.

Noted on the word selection. I'll rename to something like "App/Service Optimizations". Thanks again!

**Comment by rickmanelius** [comment]
Given the size of this issue, it's recommended that this issue be converted to a meta issue with sub-issues filed to make this more trackable/manageable. If we pursue that, child issues should be included in the issue summary as a checklist w/links to the children.

An additional item to add:

* [ ] documentation regarding our current performance and what drove our decisions to our default configurations (e.g. known best practices referenced X, overall experience at Y, results of manual/automated testing against CMS Z, etc).

**Comment by rickmanelius** [comment]
During sprint planning, we discussed making this ticket a bit more focused, especially since it is believed that the biggest performance gains will be achieved once we've evaluated the file mount issues. To that end, there are three main items:

* [Decision on webmount caching](https://github.com/drud/ddev/issues/253)
* [Repeat ddev performance comparison w/competitors](https://github.com/drud/ddev/issues/257)
* Introduce automated tests to record/track performance trends over time

We can either keep this as a meta issue (which would require splitting off the automated testing portion into a child issue) or we can repurpose and limit the scope of this ticket to that objective. I prefer the former, but it's not a strong preference.

With that said, I believe this is 100% actionable given those 3 bullets in this comment (and any follow-up documentation necessary).

**Comment by rickmanelius** [comment]
Given that all the related/child issues are provisioned elsewhere, closing this issue for now. Also, provisioned an issue to track down performance issues related to the Drupal 8 site install time through the UI on macOS https://github.com/drud/ddev/issues/283.
