### ISSUE TITLE
changing to MySQL instead of MariaDB

### ISSUE THREAD

**Issue by Kayu84** [drud/ddev#1956]
**Describe the bug**
ddev doesn't use MySQL like described in the Documentation

ddev config --mysql-version=8.0
Error: unknown flag: --mysql-version

https://ddev.readthedocs.io/en/latest/users/extend/database_types/#database-server-types

**To Reproduce**
1. brew tap drud/ddev && brew install ddev
2. ddev config
3. ddev config --mysql-version=8.0

**Expected behavior**
ddev describe should show MySQL instead of MariaDB

**Version and configuration information (please complete the following information):**
 - macOS High Sierra
 - Docker Engine: 19.03.4 / Compose: 1.24.1
 - ddev version v1.11.2
 - config.yaml 
```
APIVersion: v1.11.2
name: whtest
type: typo3
docroot: web
php_version: "7.2"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns:
- wh.test
mysql_version: "8.0"
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
timezone: ""
```

**Additional informations**
Need to switch to MySQL to support doctrine/dbal Column information schema
https://forge.typo3.org/issues/82023
I can't use doctrine/dbal 2.7.0 because TYPO3 v8.7.29 required 2.5

**Comment by rfay** [comment]
mysql support is in the latest edge releases, not in stable yet. It will be in v1.12 in the next month or so. I hope you'll try it and report your results, https://github.com/drud/ddev/releases/tag/v1.12.0-alpha2

**Comment by Kayu84** [comment]
@rfay thank you, that helps me much :)
So i was struggling in the Doku while i thought the latest was the Version 1.11.2

Well, if i want to switch from the site i mentioned in my post to v1.11.2 i got a 404, so yes, now i see it's not supported.

i've tried the latest v1.12.0-alpha2 and it works :) IT WORKS. This solves so many issues on my current project. Thank you

**Comment by rfay** [comment]
Glad it's working for you! In the docs, there is a 'stable" and a "latest". The default is "stable", which wouldn't have had this info. But google probably steered you to "latest". Sure glad it's working for you!
