### ISSUE TITLE
Allow nginx overrides of "http" context, not just "server" context

### ISSUE THREAD

**Issue by gilbertsoft** [drud/ddev#1957]
**Is your feature request related to a problem? Please describe.**
Some configurations like the server directive for another website are possible at http context only but DDEV offers only includes for the server context.

**Describe the solution you'd like**
It would be nice to have the same feature as for the server context (files in .ddev/nginx/) available for the http context. This could be simply achieved by the line `include /mnt/ddev_config/nginx/http/*.conf;` after the last server block.

Ofc same would be nice for Apache too, but I never had to change the Apache configuration so far and I don't know the details of the available options there.

**Describe alternatives you've considered**
Alternative is currently to provide the full nginx configuration.

**Additional context**
This would be a quick solution for the issues #1850 and #1889 too.

**Comment by rfay** [comment]
Thanks!

**Comment by rfay** [comment]
Closing in favor of https://github.com/drud/ddev/issues/2263 - That will allow much more user configuration of nginx, including multiple docroots/subsites.
