### ISSUE TITLE
Use one MySQL-Server & PhpMyAdmin container instead of one for each DDEV

### ISSUE THREAD

**Issue by typoworx-de** [drud/ddev#1958]
**Is your feature request related to a problem? Please describe.**
I think it's overhead using one MySQL & PhpMyAdmin container for each DDEV-Project. It would make more sense to use only one Docker-Container for MySQL & PhpMyAdmin for all DDEV Projects/Instances.

**Describe the solution you'd like**
One Docker-Container for MySQL managing all DDEV-Projects/Instances. DDEV could use SSH or Docker-CLI to coordinate managing databases for each Project/Instance.

**Comment by rfay** [comment]
Thanks for the suggestion, but this wouldn't work out for a number of reasons:
* All databases for all projects would then have to have unique names. 
* It would be impossible to support the many versions of MySQL and MariaDB that ddev supports, you could have only one. 

You may want to consider stopping projects that you're not using, then they don't take up any resources.
