### ISSUE TITLE
Use HA-Proxy instead of NGINX for DDEV-Router

### ISSUE THREAD

**Issue by typoworx-de** [drud/ddev#1959]
**Is your feature request related to a problem? Please describe.**
NGINX is good. But I think using HA-Proxy would be a more reliable solution at all.

**Describe the solution you'd like**
I really would like DDEV to run on another IP-Binding the user may configure himself, f.e. 127.0.15.1 to avoid collision with other development environment running already on developer's machine. Alternatively do not map any ports and make DDEV natively make use of the Docker-IP given by Network-Bridge (f.e. 172.0.18.2) which is assigned to DDEV Docker-Stack Container's anyway already.

Here comes HA-Proxy in play...
HA-Proxy is able to determine hostname-based routing. So there would be ONE instance of DDEV-Router in Docker listening to 127.n.n.n and port 80/443 being able to route the http(s) hostname to the correct Docker internal container. It also would be possible to show a customized error-page like "Container currently offline" if the routed DDEV-Container Hostname is unreachable.

Being able to configure DDEV IP binding (either disabled using only internal bridge-ip like 172.n.n.n or custom IP or default to 127.0.0.1) would let the user have more power over DDEV. Any collisions with existing development-environment on the developer-machine (like existing apache/nginx etc.) are resolved if DDEV won't force the user to bind to 127.0.0.1 and port 80/443.

**Additional context**
related to #1958

**Comment by rfay** [comment]
It's very unlikely that we'd make an architectural change to a mature tool that would affect everybody in order to solve a feature request that has only come up once in the life of the product.

**Comment by typoworx-de** [comment]
Well I don't think in your way. It would be an improvement and get us rid of coping with different ports for every DDEV running. Just remember there may be running different DDEV's at once for some developers having to work in parallel on more than one project.

Let's see if other users vote up this feature.

**Comment by rfay** [comment]
I don't see us changing stream after all this time, so I'm going to close this one. If we *were* going to switch, the leading contender would be [traefik](https://hub.docker.com/_/traefik).
