### ISSUE TITLE
Allow dropping all existing database tables before import

### ISSUE THREAD

**Issue by mglaman** [drud/ddev#1961]
**Is your feature request related to a problem? Please describe.**
In #810 the database used to be dropped automatically when importing a database. This functionality has changed. It's useful to drop all tables, especially when testing release updates and needing to revert to a previous database up over and over.

**Describe the solution you'd like**

Add a `-d` `--drop` flag to `--import-db` so that I can import a database from source and drop all tables.

```
ddev import-db --src --drop
```

**Comment by rfay** [comment]
Actually, I'd be of the opinion that *drop* should be the default, and no-drop an option. I was swayed too easily by that PR that changed it. And a flag would have been a better idea in the first place.

**Comment by mglaman** [comment]
So change to drop by default, which reverts back to previous behavior (that most think might still be happening, unaware that it no longer drops) and adds a `--no-drop` flag to prevent dropping tables

**Comment by rfay** [comment]
Yes, I'd agree with that. Obviously we'd need to communicate it well, but I think that's the most user-friendly solution.

**Comment by rfay** [comment]
Hope you can test this out and see if you like it in prerelease (edge) https://github.com/drud/ddev/releases/tag/v1.13.0-rc1
