### ISSUE TITLE
ddev v1.12.0 Test Plan

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1964]
Artifacts and more install instructions are at [https://github.com/drud/ddev/releases](https://github.com/drud/ddev/releases) - v1.12.0-rc1  can be installed with `brew upgrade drud/ddev-edge/ddev` (edge) and chocolatey (with `choco upgrade --pre ddev`)

Feel free to test the items that are interesting to you; please report both problems and successes in this issue, or with a new followup issue if it merits one. If you have trouble, please mention the context (OS, existing or new project, etc.) Thanks!

1. **Pantheon changes in [#1916](https://github.com/drud/ddev/pull/1916)**: Make sure that standard pantheon support works as always. `ddev auth-pantheon` with a valid key and `ddev config pantheon` with a project on pantheon and `ddev pull`
2. **ddev launch**: Try the `ddev launch` command on macOS, Linux, and especially Windows.
    - Try just `ddev launch`
    - Try `ddev launch <uri>` as well, for example, `ddev launch admin/reports/status/php` and `ddev launch /admin/reports/status/php`
3. **Xdebug 2.8 and PHP7.4:** 
    - Enable XDebug with `ddev exec enable_xdebug`
    - Verify that phpinfo (admin/reports/status/php on Drupal) shows XDebug 2.8
    - In an IDE like PHPStorm, verify that debugging works (set a breakpoint in index.php, set listener, hit web page.)
    - Switch to PHP7.4 and make sure it works also.
4. **Windows Installer**: 
    - Use the new Windows Installer, verify that it installs the right things into C:\Program Files\DDEV
    - Uninstall with the provided uninstaller, verify that it uninstalls everything
    - Install with Chocolatey (release candidates can be installed with `choco install --pre ddev` and verify success. (Note that with a Chocolatey install, less additional binaries are installed, since Chocolatey installs them instead of us bundling them with ddev installer)
    - Uninstall with Chocolatey (`choco uninstall ddev`) and make sure it cleans up the DDEV directory.
5. **exec-host bash-context handling**: For #1950, make sure that environment variables are substituted:
Add a pre-start hook and `ddev start`; you should see the variable interpreted. Try this on Windows as well:
```
hooks:
  pre-start:
  - exec-host: echo $HOME
```
6. **WordPress Improvements**: Both the support implementation for WordPress and the quickstart docs have changed. 
    - Use the WP (bedrock) [quickstart docs](https://ddev.readthedocs.io/en/latest/users/cli-usage/#wordpress-quickstart) to install a WordPress project
    - Make sure that `ddev pull` works with a Pantheon site.
    - Use a regular [WordPress](https://wordpress.org/download/) code download and/or [ClassicPress](https://www.classicpress.net/get-classicpress/) download to install a WordPress project.
    - Try ClassicPress using their [composer technique](https://docs.classicpress.net/installing-classicpress/installing-with-composer/),
    - Make sure that taking the suggested actions during `ddev config` quiets down the output.
    - Verify that `ddev exec wp` and `ddev-exec wp-cli` both work.
    - Verify that $WP_HOME gets set up with the https:// URL on an installation that has mkcert install done.
7. **Apache Solr docs**: Run through the new [Apache Solr docs](https://ddev.readthedocs.io/en/latest/users/extend/additional-services/#apache-solr) to verify.
8. **MariaDB and MySQL Changes**: #1874 introduces a massive change that completely redoes the build of MariaDB container, renames them, allows most MySQL versions as well. Note that once you've created a database with `ddev start`, it's awkward or impossible to change that database type before killing it off with something like `ddev stop -RO`. Because MySQL 8.0 is not compatible with MariaDB 5.5, etc.
    - Read [the docs](https://ddev.readthedocs.io/en/latest/users/extend/database_types/#database-server-types) on this
    - Try using `mariadb_version: 5.5` etc.
    - Try using `mysql_version: 8.0` etc
    - Try using both together (it should complain)
    - Try snapshots using various. And restore them.
9. **export-db**: Don't allow export-db if the project is not yet started. #1915, the startup chatter was included in the output in that case. Make sure that if you `ddev export-db` an unstarted project it just complains.
10. **Updated drush and node versions**: `ddev exec drush --version` should show 8.3.1, `ddev exec node --version` should show v12.13.0
11. **Missing ddev commands outside a project and missing autocomplete**: #1917 solves the problem of commands like export-db not showing up when not in a project. And as a result the fact they're not in autocomplete.
    - in ~/tmp, type `ddev`. You should see export-db, import-db, and snapshot
    - In ~/tmp type `ddev imp` and hit tab. You should get autocomplete.
12. **TYPO3_CONF_VARS change in AdditionalConfiguration.php**: The style of preparing the TYPO3_CONF_VARS was significantly changed in #1759. Make sure this works ok in TYPO3 v8, v9, v10.
13. **Command file changes**: Command scripts had several changes. 1) Ignore dot files in commands 2) make commands executable, 3) existing commands with "#ddev-generated" in them get update, 4) existing commands **without** #ddev-generated are left alone and not updated. 
    - `touch .ddev/commands/host/.gitattributes` and just run `ddev` - it should not show up
    - Create a random bash script in .ddev/commands/web and don't make it executable. Type `ddev`. It should now be executable.
    - Remove the "#ddev-generated" from .ddev/commands/host/launch. Type `ddev`. It should not be changed.
    - Remove .ddev/commands/host/launch and type `ddev`. It should be re-added.
    - Edit .ddev/commands/host/launch and leave the #ddev-generated in there but update other content (add a comment or something). Type `ddev`, your content should be gone.
14. **ReadTheDocs organization improvements**: Please take a minor peruse of the organization of the left side of [https://ddev.readthedocs.io/en/latest/](https://ddev.readthedocs.io/en/latest/) and click around and make sure it makes some sense.
15. **Improved hook/task output**: #1860 improves hook output. 
    - A failed task no longer halts the entire operation (test)
    - The output on failure should be comprehensible, not couched in a bunch of docker-compose nonsense.
    - You can test this with an exec operation like "kdkdk" :)
16. **sqlite3 in web image**: `ddev exec sqlite3 --version` should give joy.
17. **Difficult package installs on web container**: in #1951 there was a fix to allow packages to be installed even if there was a major update that affected config files in the container. Test this way:
    - Set `webimage: drud/ddev-webserver:v1.11.0` to recreate the starting point of [#1947](https://github.com/drud/ddev/issues/1947)
    - `webimage_extra_packages: [php-yaml, php7.3-ldap]`
    - `ddev restart`
    - Make sure to remove the webimage line from your test config.yaml after you're done.

**Comment by rfay** [comment]
Here are my results, to be updated as I continue. Mostly done on WSL2 (Debian 10) with a homebrew install of the edge channel (v1.12.0-rc1)

1. ✅ **Pantheon, and with WIndows**: `ddev auth-pantheon` and `ddev config pantheon` and `ddev pull` worked on a never-before-seen WordPress site (ddevwptest). 
2. 

## Questions and worries
1. On WSL2 (Debian10), it's prompting me about instrumentation every single time I `ddev start`. I'm not sure if this is related to

**Comment by andrewfrench** [comment]
My results on MacOS 10.15 Beta:

1. 🕚 

2. ✅ **ddev launch**
I created a project with `/index.php` and `/path/index.php`. `ddev launch` directed me to `https://v1.12.0.ddev.site/` and `ddev launch path/` directed me to `https://v1.12.0.ddev.site/path/`.

**Comment by rfay** [comment]
Everything seems to be in pretty good shape. I've pushed a v1.12.0-rc2. We'll get that into homebrew and chocolatey, and release soon.

**Comment by rfay** [comment]
Releasing v1.12.0
