### ISSUE TITLE
Build ARM version of ddev

### ISSUE THREAD

**Issue by jgonyea** [drud/ddev#1966]
**Describe the bug**
I'm currently attempting to get ddev to run on my arm processor powered Pinebook Pro.  I was able to get both docker and docker-compose installed, but the binary for ddev is most likely built just for x86.

**To Reproduce**
1. Install docker/ docker-compose for arm
2. Install ddev via the `https://ddev.readthedocs.io/en/latest/#installationupgrade-script-linux-and-macos` command
3. Attempt to run `ddev`

**Expected behavior**
Basic help to display for ddev commands arguments

**Actual behavior**
`$ ddev`
`bash: /usr/local/bin/ddev: cannot execute binary file: Exec format error`

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Ubuntu Mate, 18.04
 - Docker version information: Docker version 19.03.5, build 633a0ea
 - ddev version information: unable to run

**Additional context**
As mentioned above, I'm on the Pinebook Pro, an Arm powered machine, which I suspect is my main issue.  If someone could point me in the right direction for how to compile for arm, that would awesome for my (very small) use-case.

**Comment by rfay** [comment]
It looks like since Docker now supports Arm, it ought to be possible. Are you able to do ordinary things with Docker? 

Doesn't the pinebook have pretty limited memory?

**Comment by rfay** [comment]
The specs look pretty limited, https://www.pine64.org/pinebook-pro/

**Comment by rfay** [comment]
Please try this out, https://www.dropbox.com/s/013wn7xyb5zzpss/ddev_arm_v1.12.0-rc1.tar.gz?dl=0

**Comment by jgonyea** [comment]
@rfay , this got me much closer!  DDev is running now, but fails on the ddev-ssh-agent build.  I disabled that via `omit_containers` key in my `./ddev/config.yaml`, but then the build fails on the db container  build.

**Comment by jgonyea** [comment]
Specs are definitely limited (4GB of Ram, hexacore ~2GHz arm).

I'm not very familiar with docker, so if there's some sort of arm processor override or specific tag I should be using, please let me know.

**Comment by rfay** [comment]
Could you show the error output on trying to get the ddev-ssh-agent going? Thanks.

**Comment by jgonyea** [comment]
Note: I deleted all my docker images and started again with a brand new ddev project.

`$ PATH_TO_CUSTOM_DDEV\ddev config`
Creating a new ddev project config in the current directory (/home/rock64/projects/tmp) 
Once completed, your configuration will be written to /home/rock64/projects/tmp/.ddev/config.yaml
 
Project name (tmp): 

The docroot is the directory from which your site is served.
This is a relative path from your project root at /home/rock64/projects/tmp 
You may leave this value blank if your site files are in the project root 
Docroot Location (current directory): 
Found a php codebase at /home/rock64/projects/tmp. 
Project Type [drupal8, wordpress, typo3, backdrop, php, drupal6, drupal7] (php): 
Project type has no settings paths configured, so not creating settings file. 
Configuration complete. You may now run 'ddev start'. 
Instrumentation is opted in, but SentryDSN is not available. 
Instrumentation is opted in, but SegmentKey is not available. 

`$ PATH_TO_CUSTOM_DDEV\ddev start`
[Process pulls a bunch of docker images]
.
.
.
Building ddev-ssh-agent 
Service 'ddev-ssh-agent' failed to build: The command '/bin/sh -c (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")' returned a non-zero code: 1 
Failed to start tmp: failed to start ddev-ssh-agent: Failed to run docker-compose [-f /home/rock64/.ddev/ssh-auth-compose.yaml -p ddev-ssh-agent up --build --force-recreate -d], err='exit status 1', stdout='Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
 ---> 5780ca23a654
Step 3/6 : ARG username
 ---> Running in 6a49fa76627c
Removing intermediate container 6a49fa76627c
 ---> c866371ff094
Step 4/6 : ARG uid
 ---> Running in 65834d1fa611
Removing intermediate container 65834d1fa611
 ---> d52ced7f0ac5
Step 5/6 : ARG gid
 ---> Running in 0841557ce8f1
Removing intermediate container 0841557ce8f1
 ---> ffc6260f8f74
Step 6/6 : RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")
 ---> Running in 89457e7ceb8d
standard_init_linux.go:211: exec user process caused "exec format error"
', stderr='Building ddev-ssh-agent
Service 'ddev-ssh-agent' failed to build: The command '/bin/sh -c (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")' returned a non-zero code: 1'

**Comment by rfay** [comment]
I wonder if it's possible that Docker on Arm expects to run arm-based images. 

Could you try `docker run -it --rm drud/ddev-ssh-agent:v1.12.0 bash`

When you're in there, try running "groupadd someuser" and just "sh"

It does look like from https://engineering.docker.com/2019/06/getting-started-with-docker-for-arm-on-linux/ that you may have to take extra steps to run x86 images on Arm.

**Comment by jgonyea** [comment]
`rock64@pinebookpro:~/projects$ docker run -it --rm drud/ddev-ssh-agent:v1.12.0 bash`
Unable to find image 'drud/ddev-ssh-agent:v1.12.0' locally
v1.12.0: Pulling from drud/ddev-ssh-agent
be50d4e619fe: Already exists 
e7529b48149b: Already exists 
7a33dcda49ce: Already exists 
53957f29cead: Already exists 
e662ace2460c: Already exists 
744a9ace49aa: Already exists 
991a64fc324a: Already exists 
Digest: sha256:e0617ddecb05f2ee8981cbc0a8b1f8595034fe1094d7e57bf16e962c67446d6a
Status: Downloaded newer image for drud/ddev-ssh-agent:v1.12.0
standard_init_linux.go:211: exec user process caused "exec format error"

Thanks, I'll take a look at the building portion and see if I can build the containers locally.  It's not something I'm super familiar with, but I have a hard head and I can bang it through most walls.

Thanks for the quick replies (and for the super helpfuly tool of ddev)

**Comment by rfay** [comment]
Yep, that's saying that the program "bash" inside the container is of the wrong architecture. 

Besides building the containers yourself, the other option is to figure out how to run amd64 docker images on ARM.

**Comment by rfay** [comment]
Based on your discoveries I'm going to close this for now. Happy to support ongoing research here or elsewhere,.

**Comment by rfay** [comment]
I hope you'll be able to try out the current alphas on your pinebook, I'd love to hear your experience.

**Comment by jgonyea** [comment]
Sorry for the long delay,
I was able to pull the repo and make the master branch on my pinebook pro.  After moving the ddev executable, ddev functioned as it does on my x86 machine.  I was able to build out both a plain PHP site (GravCMS) as well as a MySQL based one (WP).

Congratulations!

**Comment by jgonyea** [comment]
I should also note that I had migrated from Ubuntu Mate on the PinebookPro to Manjaro, as it had better package support for some of my other requirements.  I did not try the arm build of ddev on Ubuntu Mate.

**Comment by rfay** [comment]
DDEV v1.16.0 is already released and can be used! Don't have to do any building. But since homebrew isn't out there, the best way to install is with the install_ddev.sh script, which pulls the right architecture.
