### ISSUE TITLE
ddev commands ends with segment.io output

### ISSUE THREAD

**Issue by juergen-venne** [drud/ddev#1967]
**Describe the bug**
running command
`ddev config`
quits with this output:
`...`
`Project Type [drupal7, drupal8, wordpress, typo3, backdrop, php, drupal6] (php):`
`Generating AdditionalConfiguration.php file for database connection.`
`Configuration complete. You may now run 'ddev start'.`
`segment 2019/11/21 10:12:59 ERROR: sending request - Post https://api.segment.io/v1/batch: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`
`segment 2019/11/21 10:12:59 ERROR: 2 messages dropped because they failed to be sent and the client was closed`

**To Reproduce**
create a new project:
`mkdir test; cd test`
`ddev config`
press enter on every input request

**Expected behavior**
I don't want that error messages :-)

**Screenshots**

**Version and configuration information (please complete the following information):**
 - macOS Catalina 10.15.1
 - Docker version 
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
- docker-compose version 1.24.1, build 4667896b
 - ddev version v1.11.2
 - config.yaml default values
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? No, empty new project

**Additional context**
ddev was installed with homebrew
Severel other ddev commands behave the same:
`ddev describe`
`NAME  TYPE   LOCATION      URL  STATUS`
`xxxx   typo3  ~/vm/dev_xxxx       stopped`
`segment 2019/11/21 10:40:44 ERROR: sending request - Post https://api.segment.io/v1/batch: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`
`segment 2019/11/21 10:40:44 ERROR: 2 messages dropped because they failed to be sent and the client was closed`
Also `ddev start`, `ddev auth ssh`...

**Comment by rfay** [comment]
You're complaining about the segment messages right? I think those are a result of a spam-catcher you have configured, which is setting the DNS for api.segment.io be localhost probably. I think if you allow api.segment.io though, it will be OK.

But also, you can just turn off instrumentation with
`ddev config global --instrumentation-opt-in=false`, which will tell ddev to stop trying instrumentation.

I'm pretty sure this is a duplicate of https://github.com/drud/ddev/issues/1767, where pi-hole was the cause of the problem.

**Comment by juergen-venne** [comment]
Looks like a duplicate, yes. 
I switched it off, thank you.
