### ISSUE TITLE
.gitignore not picking up /commands/db/mysql

### ISSUE THREAD

**Issue by graham73may** [drud/ddev#1984]
# The issue
Running `ddev config` on a project sets up ddev, when you go to `git add` and `git commit` you end up committing `/.ddev/commands/db/mysql`. 

# Fix
Every new project I end up having to edit the `/.ddev/.gitignore file and change

`/commands/*/*.example`

to

`/commands/*/*`

# Notes
I'm using PHPStorm's VCS functionality (don't know if this is useful information!)

**Comment by rfay** [comment]
Please say what version of ddev you're using, and please create a new junk ddev project and use git itself to see if this is a problem there. If you've committed the .gitignores and ddev has tried to update them, that would cause this.

**Comment by graham73may** [comment]
Hi Randy!

Currently using v1.11.1

I just created an empty folder project but it only gave me these folders:
![image](https://user-images.githubusercontent.com/6642498/69796564-27f84400-11c6-11ea-946b-c068ab13a781.png)

Is there something I need to do for ddev to generate a `commands` folder? One of my "real" projects has a lot more inside: 
![image](https://user-images.githubusercontent.com/6642498/69796628-3e9e9b00-11c6-11ea-94ce-846e1150ea6d.png)

**Comment by graham73may** [comment]
Ah I've run a few more commands and now have the extra folders!

If I go to commit it is picking up the mysql command file: 

![image](https://user-images.githubusercontent.com/6642498/69796743-74438400-11c6-11ea-9cf5-a1b0f23808eb.png)

**Comment by rfay** [comment]
Ah, thanks for pointing this out. It looks to me like this was fixed in https://github.com/drud/ddev/commit/70a8b0d1e5bc382307fa6552c0e4187fbf83cc48

I think if you try v1.12.0-rc2 you will see it working.

**Comment by graham73may** [comment]
Always one step ahead! Thank you :). 

Just updated to v1.12's release and this issue is fixed already. 

![image](https://user-images.githubusercontent.com/6642498/70215493-7f059800-1735-11ea-8826-8400d2e020c1.png)

**Comment by rfay** [comment]
Thanks for reporting this!
