### ISSUE TITLE
Update drush version to 8.3.2

### ISSUE THREAD

**Issue by truls1502** [drud/ddev#1999]
**Describe the bug**
When I did `drush make`-command; I got the error such as:
```
truls1502$ ddev ssh
truls1502@web:/var/www/html/web$ drush make ../site.make
Make new site in the current directory? (y/n): y
include(phar:///usr/local/bin/drush8/vendor/composer/../../src/Internal/Symfony/Yaml/Yaml.php): failed to open stream: phar error:        [warning]
"src/Internal/Symfony/Yaml/Yaml.php" is not a file in phar "/usr/local/bin/drush8" ClassLoader.php:444
include(): Failed opening 'phar:///usr/local/bin/drush8/vendor/composer/../../src/Internal/Symfony/Yaml/Yaml.php' for inclusion           [warning]
(include_path='.:/usr/share/php') ClassLoader.php:444
PHP Fatal error:  Class 'Drush\Internal\Symfony\Yaml\Yaml' not found in phar:///usr/local/bin/drush8/lib/Drush/Make/Parser/ParserYaml.php on line 26
Fatal error: Class 'Drush\Internal\Symfony\Yaml\Yaml' not found in phar:///usr/local/bin/drush8/lib/Drush/Make/Parser/ParserYaml.php on line 26
Drush command terminated abnormally due to an unrecoverable error.                                                                        [error]
Error: Class 'Drush\Internal\Symfony\Yaml\Yaml' not found in phar:///usr/local/bin/drush8/lib/Drush/Make/Parser/ParserYaml.php, line 26
```

After talked on #drush-channel and they mentioned the issue should be resolved on [Drush version 8.3.2](https://github.com/drush-ops/drush/releases/tag/8.3.2). 
So [this line](https://github.com/drud/ddev/blob/v1.12.0/containers/ddev-webserver/Dockerfile#L7) needs to be fixed.

So I tried to add a new file `.ddev/web-build/Dockerfile` with below:
```
ARG BASE_IMAGE=drud/ddev-webserver:v1.12.1
FROM $BASE_IMAGE

ENV DRUSH_VERSION=8.3.2

RUN curl -sSL "https://github.com/drush-ops/drush/releases/download/${DRUSH_VERSION}/drush.phar" -o /usr/local/bin/drush8 && chmod +x /usr/local/bin/drush8
```

Then it is working smooth now. 

**To Reproduce**
1. `ddev config --project-name="DrushMake"  --project-type="drupal7" --php-version="5.6"`
2. `ddev start && ddev exec drush make site.make` (You need a make file).

**Expected behavior**
It shouldn't throw such error.

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macOS Catalina
 - Docker version:
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by rfay** [comment]
How about that. I wouldn't have expected old-old drush make to be affected by a minor-version update in drush. 

Would you like to do a PR?

**Comment by rfay** [comment]
For your own problem with this, you'll probably want to temporarily put the upgrade process into .ddev/web-build/Dockerfile so it just automatically gets 8.3.2

**Comment by truls1502** [comment]
> How about that. I wouldn't have expected old-old drush make to be affected by a minor-version update in drush.
> 
> Would you like to do a PR?

I am working on PR now. Just created the issue first to use the issue number :)

**Comment by truls1502** [comment]
> For your own problem with this, you'll probably want to temporarily put the upgrade process into .ddev/web-build/Dockerfile so it just automatically gets 8.3.2

Yes, I am using this solution as temporary until the release next release with this Drush version. 😊 

We can noticed others from https://github.com/drush-ops/drush/issues/4253 had similar problem with make.

**Comment by ssudhak** [comment]
I am facing this issue 8.4.10. Please confirm if this commit was added to it.

**Comment by rfay** [comment]
The current version of drush8 is 8.4.10 The version shipped in ddev v1.19+ is 8.4.8, but v1.19.2 will have drush8 8.4.10

Drush 8 is obsolete though - you should probably be using something else. 

I didn't really understand what you were asking @ssudhak - Were you asking something about drush 8.3.2? Were you requesting an update to 8.4.10?

**Comment by ssudhak** [comment]
@rfay , sorry if i confused you. I was getting this error for Drush 8.4.10. Not using ddev. Was browsing throw drush issues in github and ultimately landed here :) . But help me understand here, was the fixes done for this issue in ddev? because if u are going to use 8.4.10, you might be getting same issue.

**Comment by rfay** [comment]
If you're not using ddev...  then of course you shouldn't be commenting here. And drush 8 is obsolete. The drush repo is https://github.com/drush-ops/drush - problems with drush should be taken up there.

Again, all ddev projects in the last 2 years have had a higher drush version. 

I invite you to the ddev community, https://ddev.readthedocs.io/en/latest/

**Comment by rfay** [comment]
You can always install the version of drush you want in a project using a Dockerfile, just add a RUN statement that curls or wgets the version you want. https://ddev.readthedocs.io/en/latest/users/extend/customizing-images/#adding-extra-dockerfiles-for-webimage-and-dbimage

I had hoped that 8.4.11 would also fix
* https://github.com/drush-ops/drush/issues/4979
but no such luck

But @nikolay-jobiqo - what version of Drupal are you running drush against?

**Comment by nikolay-jobiqo** [comment]
I am using drush 8.4.11 for Drupal 7.90 from yesterday. 
Before I was using drush 8.4.8, because it was provided in ddev 1.18 and 1.19.
And was able to run `drush make` and `drush vget`.

**Comment by rfay** [comment]
This seems to be solved upstream now, so Drush will be upgraded to 8.4.12 for D7 in 
* https://github.com/ddev/ddev/pull/4754
