### ISSUE TITLE
ddev install - alternatives to brew for multi-user computers (permissions/ownership/group conflicts)

### ISSUE THREAD

**Issue by therobyouknow** [drud/ddev#2002]
**Is your feature request related to a problem? Please describe.**
_**I use multiple user accounts to keep different kinds of work separate:
Home, Community, Projects, Work
However, I use ddev in several of these users. The problem is permissions. ddev and brew are stored in system folders that are common across all users. To ensure updates, upgrades, config start and stop proceed without failing, certainly system folders and their contents need to be read/write accessible to the current user. But if I login to another user, there will be problems because of this.**_

**Describe the solution you'd like**
**_For the ddev installation to work with any of the users on a computer, without permission changes, ownership changes etc._**

**Describe alternatives you've considered**
**_A clear and concise description of any alternative solutions or features you've considered.
I'm looking into ddev installation options to see if there is an alternative to brew._**

**Additional context**

**Comment by rfay** [comment]
Could you please say what OS and variant you're using?

**Comment by therobyouknow** [comment]
macOS Catalina. I'll get the specific 10.15.x version as soon as I can. Thanks for your response so far rfay.

**Comment by rfay** [comment]
That's all I needed @therobyouknow, thanks. 

Essentially, it sounds like homebrew just doesn't work for you at all for anything, not just ddev. And I've had to change users before and it's awkward. 

I do see a [number of articles on this subject](https://www.google.com/search?q=homebrew+macos+with+different+users&oq=homebrew+macos+with+different+users&aqs=chrome..69i57j0l2.8330j1j7&sourceid=chrome&ie=UTF-8). I myself have just changed the ownership of /usr/local/* when switching, `sudo chown -R <newuser> /usr/local/*`, but I'll bet those articles suggest something better.

Of course, https://ddev.readthedocs.io/en/stable/#installationupgrade-script-linux-and-macos explains how to use the scripted approach to installing ddev. And I don't think the ownership matters when installed that way. Make sure to `brew unlink ddev` before using the script.

**Comment by rfay** [comment]
This actually isn't a ddev issue, but an issue of homebrew assuming that macs are used by one user. The above suggestions should sort it out, and the many ways to install ddev also provide options. Closing for now, happy to continue the conversation here.

**Comment by therobyouknow** [comment]
Thank you @rfay for responding and advising on solutions. Happy for this issue to remain closed.

To add some value to the discussion: Yes - the way around it for me is to ensure that whatever user I'm logged in as has the sufficient permissions.

The following commands seem to do the trick for me ( in the case of `robdavisprojects` user needing to use brew ) :

```
sudo chown -R robdavisprojects /home/linuxbrew/
sudo chgrp -R robdavisprojects /home/linuxbrew/
sudo chmod -R u+w,g+w,o+w /home/linuxbrew/
```


```
robdaviswork@Workstation-U64:~$ sudo chown -R robdavisprojects /home/linuxbrew/
[sudo] password for robdaviswork: 
robdaviswork@Workstation-U64:~$ sudo chgrp -R robdavisprojects /home/linuxbrew/
robdaviswork@Workstation-U64:~$ brew update
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/lock.sh: line 27: /home/linuxbrew/.linuxbrew/var/homebrew/locks/update: Permission denied
Traceback (most recent call last):
	2: from -e:1:in `<main>'
	1: from -e:1:in `new'
-e:1:in `initialize': Bad file descriptor (Errno::EBADF)
Error: Another active Homebrew update process is already in progress.
Please wait for it to finish or terminate it to continue.
robdaviswork@Workstation-U64:~$ sudo chmod -R u+w,g+w,o+w /home/linuxbrew/
robdaviswork@Workstation-U64:~$ brew update
Updated 2 taps (drud/ddev and homebrew/cask).
==> Updated Formulae
drud/ddev/ddev ✔
robdaviswork@Workstation-U64:~$ 
```

**Comment by rfay** [comment]
Glad you got it working!
