### ISSUE TITLE
Serve WASM w/ the correct encoding

### ISSUE THREAD

**Issue by btopro** [drud/ddev#2009]
minor apache setting but if you have any wasm asset in your repo then they aren't being served w/ the correct encoding which JS is strict about.

Should be like a 1 line fix on startup of the apache image im just not sure where it goes -- https://blog.toddlichty.com/serving-a-wasm-file-from-apache/

`sudo echo "application/wasm wasm" >> /etc/mime.types` should be about all thats needed but I wasnt able to get it to work in postinstall

**Comment by rfay** [comment]
Thanks @btopro - 
* Could you please describe how to detect (and thus test) this? 
* Is this also a problem with any of the nginx configs?

**Comment by rfay** [comment]
A more effective way to test this fix per the article might be to add a .ddev/web-build/Dockerfile with `RUN echo "application/wasm wasm" >> /etc/mime.types` in it, and see if that does the job.

In your test above you'd have needed to get apache to reload, probably a `killall -HUP apache2` or something like that.

**Comment by rfay** [comment]
Oh, I see Debian buster already includes this in /etc/mime.types, so probably https://github.com/drud/ddev/pull/1983 will fix this. I *think* you could test it by (just) (temporarily) putting `webimage: drud/ddev-webserver:20191126_debian_buster` in your config.yaml.
