### ISSUE TITLE
ddev launch: DDEV_PRIMARY_URL uses first hostname from alphabetically sorted list of hostnames

### ISSUE THREAD

**Issue by peterkraume** [drud/ddev#2014]
**Describe the bug**
The `ddev launch` command uses `$DDEV_PRIMARY_URL` to set the hostname to open in a browser. It seems that the list of hostnames is sorted alphabetically.

**Expected behavior**
I'd expect ddev to use the project name as DDEV_PRIMARY_URL.

**To Reproduce**
Create a project with this configuration:
```
APIVersion: v1.12.0
name: ekw
type: typo3
docroot: public
php_version: "7.3"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames:
- ckm
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
timezone: Europe/Berlin
```

When you start ddev, you can already see the alphabetically sorted list of hostnames:
```
Successfully started ekw
Project can be reached at https://ckm.ddev.site https://ekw.ddev.site https://127.0.0.1:32772
```

If you hit `ddev launch`, https://ckm.ddev is opened instead of the expected https://ekw.ddev.site

**Additional context**
I've already discussed this issue with Randy on Slack:
https://typo3.slack.com/archives/C8TRNQ601/p1577731610020600

Seems that the hostnames are sorted here:
https://github.com/drud/ddev/blob/4d7cf50357e76654e37b6bd01549480047cd84e0/pkg/ddevapp/ddevapp.go#L1511
https://github.com/drud/ddev/blob/06754053ebecabe991fb25019eeb1a6fd8d85b81/pkg/ddevapp/config.go#L495

**Comment by rfay** [comment]
We should sort only the ones that come after the basic URL, not sort all together as equals.

**Comment by rfay** [comment]
Hope you can test this out and see if you like it in prerelease (edge) https://github.com/drud/ddev/releases/tag/v1.13.0-rc1
