### ISSUE TITLE
Reorg docs out of README, launch docs site

### ISSUE THREAD

**Issue by tannerjfco** [drud/ddev#202]
## What happened (or feature request):
Our current docs are almost entirely contained within the README (with exception to a couple linked pages). This will not scale as our documentation needs increase, and we would like to re-orient the README to provide more of a value proposition.

## What you expected to happen:
I see the following as necessary steps to provide more robust documentation for users:
- [x] Determine a strategy for docs site hosting: ReadTheDocs, mkdocs, static site build, etc
- [x] Reorganize the sections of the current README into separate documentation pages/sections.
- [x] Revise the README to provide description, value proposition, installation, and getting started info. 

## Related source links or issues:

**Comment by tannerjfco** [comment]
Unless there's any objection, I think we should proceed with ReadTheDocs, since its free and should provide what we need without too much effort. We could explore alternatives to fully control and/or host the doc site, but I don't think its worth spending the effort at this time.

**Comment by rickmanelius** [comment]
A couple other acceptance criteria, then I agree that this is good to go!

* [ ] Selection of a domain/URL pattern.
* [ ] List of implications regarding managing readthedocs across multiple projects (public and private). Do we use one readthedocs to rule them all? Have a single landing page that links out to individual pages?
* [ ] Decision of whether or not we could/should use this for internal documentation as well.

**Comment by tannerjfco** [comment]
- ddev.readthedocs.org
- docs would be per-project
- public projects only. readthedocs provides a pro offering but is currently in invite-only beta.

**Comment by rickmanelius** [comment]
Additional item
* [ ] Create an outline/wishlist and rank these by priority. Determine what would be sufficient for the relaunch and what can be pulled into different tickets.

**Comment by rickmanelius** [comment]
* [ ] Decision on whether or not including each project roadmap would be appropriate within this strategy.

I would love it to so we don't have an independent wiki and we can PR against the docs alongside feature changes, but if it's going to be problematic to shoehorn this in, then keeping a wiki per project is going to continue for now because the alternative of creating a documentation repo will become unwieldy IMHO.

**Comment by beeradb** [comment]
Since part of this push is to improve and expand documentation, I just thought I'd drop what appears to be an excellent guide here: http://www.writethedocs.org/guide/

**Comment by tannerjfco** [comment]
This is done! https://ddev.readthedocs.io is now live.
