### ISSUE TITLE
Homebrew & ddev don't seem to get along

### ISSUE THREAD

**Issue by jmevalentin** [drud/ddev#2020]
It seems that all sites initiated with ddev default to one of the sites setup in my local vhost file. What would be causing this?

**Comment by rfay** [comment]
Hi @jmevalentin - homebrew is a way of installing ddev, it's only used for installing and updating. 

Also, there's no vhost file involved (and I don't know what that is). Maybe you're saying you have Apache set up and it's running and you're accidentally using it? You'll want to turn Apache off, maybe as described here: https://ddev.readthedocs.io/en/stable/users/troubleshooting/#method-2-fix-port-conflicts-by-stopping-the-competing-application

If you're talking about the /etc/hosts file, I recommend that you begin ddev without using additional_fqdn; in that case ddev doesn't use your /etc/hosts at all, it uses DNS to resolve sites like "myproject.ddev.site" and doesn't involve your /etc/hosts at all.

**Comment by jmevalentin** [comment]
@rfay - Thanks for the response. I installed my local stack (Apache, PHP, Mysql) via homebrew and have always used that. I decided to try ddev and it actually worked for a short period, and my previous local sites that were running on my local stack failed. I'm not sure what I did to get them working again, but now ddev doesn't work. It seems to create a site and shows me the url when I run `ddev start`, but when I go to that url, it loads up one of the sites listed in my vhost file (which is the configuration of all of the loca virtual hosts). Are you saying that it's not possible to run a ddev site on a system that has its own stack? That would kind of suck.

**Comment by rfay** [comment]
As above, please stop Apache on your local machine. Nothing on your local machine is relevant to ddev working (except docker). 

You haven't said whether you're on Linux or macos, but if you're on mac, you would temporarily disable Apache with `sudo apachectl stop` or permanently disable it as described in many places like https://superuser.com/questions/455505/how-do-i-start-apache-in-osx-mountain-lion-mavericks

Most people do *not* install Apache with homebrew on macOS (because it comes with Apache). But if you're using the *homebrew* apache2, you could disable it with `brew services stop httpd`

**Comment by jmevalentin** [comment]
@rfay , thanks again for your response. I suppose that's a solution. I was just hoping that I could run ddev without stopping apache, since I'm using it for other local development, and tend to do a lot of different things at once and stopping and starting things is a pain. However, if that's the way it is, I can't hope for a better solution and I'll try your suggestion. Thanks so much for clarifying this.

Best to you!

**Comment by rfay** [comment]
Yes, of course you can do that. You just have to choose what ports you're going to use for what. It's explained in the troubleshooting link, https://ddev.readthedocs.io/en/stable/users/troubleshooting/#webserver-ports-are-already-occupied-by-another-webserver

If you want to run Apache on port 80, you'll need to configure your project for another port (maybe 8080 and 8443). 

In the long run you'll probably want all your projects in ddev, and then you wouldn't have to do that workaround, but it works fine to just have ddev (or apache) on a different port.

**Comment by rfay** [comment]
I haven't heard back from you, so closing this, but happy to continue the conversation here, just reply and I'll see it.
