### ISSUE TITLE
Add project type "drupal" to stand for Drupal 8 and Drupal 9

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2029]
**Is your feature request related to a problem? Please describe.**

Although there's no functional difference between drupal 8 and drupal 9, people will soon be asking about drupal 9. Actually, they already have. 

I think the obvious answer is to switch to a project type of "drupal" for drupal 8 and drupal 9. I'm not sure exactly how to do this without breaking things, but it should be possible.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rfay** [comment]
The other thing that happens with this is that Drupal 9's minimum MariaDB version is now 10.3 (the default is 10.2) so we probably need to change the default for the "drupal" type to 10.3.

**Comment by alesrebec** [comment]
Just thinking about futureproofness. Are we ok with just "drupal" for both D8 and D9?
When D10 comes out, we don't know if this will require a change.
I do like just "drupal" though if the system can then recognize which major version it is to set the right dependencies.

**Comment by rfay** [comment]
In the world of things that move so fast, we don't have to make a perfect decision accounting for  Drupal 10, but you're right that it's a reasonable consideration.

However, an episode with dependencies hit the other day (https://github.com/drud/ddev/issues/2119); Drupal 9 now requires a minimum of MariaDB 10.3  ([issue](https://github.com/drud/ddev/issues/2119))(10.2 is the default).

**Comment by rfay** [comment]
Also, you're right about how nice it would be for ddev to make minor distinctions between some versions. Having a "minor" version distinction would also be nice. We have the same problem with TYPO3 - just one project type is used for support of v8/v9/v10... and although that is holding for now, it won't for long I don't think.
