### ISSUE TITLE
TestValidateAsset() in appimport_test.go needs to use unique dirs, clean up

### ISSUE THREAD

**Issue by rfay** [drud/ddev#203]
## What happened (or feature request):

I noticed in a test run the error `2017/05/05 08:14:28 ERROR:mkdir testing/data: file exists` and found that in TestValidateAsset() we're creating directories right in the user homedir. 

## What you expected to happen:

* Normally directories would be created via tmpdir, but this is a unique case and what it's testing is valid.
* However, directory names should be unique so that we can't have a later collision, use a way to create a tmpdir in ~/tmp or something.
* Make sure artifacts are cleaned up (This may already be being done, maybe I hit ctrl-c)

## How to reproduce it (as minimally and precisely as possible):

```
mkdir -p pkg/appimport/testing/data
make testpkg
```

## Related source links or issues:

**Comment by rickmanelius** [comment]
@beeradb @tannerjfco Can either of you confirm this is still an issue?

**Comment by rfay** [comment]
`mkdir ~/testpath && make testpkg` will show this. 

```
=== RUN   TestValidateAsset
--- FAIL: TestValidateAsset (0.00s)
        Error Trace:    appimport_test.go:44
	Error:		Received unexpected error mkdir /Users/rfay/testpath: file exists

FAIL
FAIL	github.com/drud/ddev/pkg/appimport	0.019s
```

It's not that big a deal, but we should probably find a way not to create things in dev's home dir.
