### ISSUE TITLE
'restore-snapshot' got lost from bash completions

### ISSUE THREAD

**Issue by a8w4** [drud/ddev#2031]
it is missing in the later versions of ddev - I've searched the file "ddev_bash_completion.sh" in ddev_linux.v1.12.0.tar.gz and ddev_linux.v1.11.2.tar.gz

**Comment by rfay** [comment]
It might have been lost for a long, long time. Fixed by #2032 . Thanks for catching this.

**Comment by a8w4** [comment]
my pleasure - thanks for creating DDEV - I love it!

**Comment by rfay** [comment]
Fixed in v1.13
