### ISSUE TITLE
Docker Desktop 2.2.0.0 on Windows: No consistency in file mounts

### ISSUE THREAD

**Issue by Kephson** [drud/ddev#2046]
**Describe the bug**
Installing a e.g. a TYPO3 project via composer with a composer.json file with "ddev composer install".
After changing the composer.json file and doing "ddev composer update" nothing will be changed (I think the file is cached because of new Docker file caching).

**To Reproduce**
1. Install a composer project with "ddev composer install" on Windows with Docker Desktop 2.2
2. Change the composer.json file
3. Do a "ddev composer update"
4. Nothing will be changed by composer and the changed in composer.json will be ignored

**Expected behavior**
The changes in composer.json file should be used and e.g. new packages installed or updated.

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Windows 10 (newest release)
 - Docker version information: Docker Desktop 2.2 with Docker 19.03.5
 - ddev version information: 1.12.1

**Comment by leymannx** [comment]
So you updated the composer.json manually? And doing `ddev composer update --lock` and then `ddev composer install`? Does that fix the problem?

**Comment by rfay** [comment]
I haven't looked at the (many) docker 2.2.0.0 problems on Windows yet, but probably using NFS mounting would fix most of them. Not saying it's worth sticking with docker 2.2.0.0, but it's a great technique in general, https://ddev.readthedocs.io/en/stable/users/performance/

**Comment by rfay** [comment]
I think you're saying that *composer.json* is not being updated in the container when changed on the host, is that correct @Kephson ? Can you try to confirm that by changing it and viewing it inside the container?

**Comment by rfay** [comment]
This is https://github.com/docker/for-win/issues/5530 - Basically their [vaunted new Fuse filesystem](https://www.docker.com/blog/new-filesharing-implementation-in-docker-desktop-windows/) doesn't work in this release. I've tested a number of things, and changes inside the container don't get reflected to the host; changes on the host don't get reflected into the container.

**Comment by Kephson** [comment]
many thanks @rfay for your fast answer and suport!
I checked now how to work with NFS on Windows and now it works like before also with Docker Desktop 2.2.
I installed NFS and enabled it in my ddev project, now also "ddev composer update" works like before.

**Comment by rfay** [comment]
It looks to me like they just added cache consistency configuration into Windows without telling anybody, from a comment in https://github.com/docker/for-win/issues/5530#issuecomment-577634366

So probably this can be fixed by changing to "consistent"  as the cache requirement, see https://docs.docker.com/compose/compose-file/#caching-options-for-volume-mounts-docker-desktop-for-mac - note that they haven't updated the docs to say that it happens anywhere but macOS. 

I also note that the fact that we've long used :cached on macOS could cause some composer issues, where the container side does major updates and it doesn't show up in time on the host side, because the host side is favored. Unfortunately, :cached is a huge win for performance on mac (but nowhere near as much as nfs_mount_enabled)

**Comment by joshuasosa** [comment]
Tried changing to 'consistent' and it didn't work for me. Following the instruction in [docker/for-win#5530](https://github.com/docker/for-win/issues/5530#issuecomment-578228528) to add a disable-filesystem-caching file fixed it for me.

**Comment by rfay** [comment]
I note that they seem to have basically withdrawn 2.2.0.0 - When I check for updates on a non-updated machine, it no longer offers 2.2.0.0. 

@joshuasosa what does performance seem like with the disable-filesystem-caching setup?

**Comment by rfay** [comment]
A couple of details:
* 2.2.0.0 on macOS seems to be fine. It didn't introduce a major new feature like on Windows side.
* 2.2.0.0 on Windows works fine if you use nfs_mount_enabled (which is recommended anyway)

**Comment by Azovsky** [comment]
Just FYI:
On Win 10, Docker Desk. 2.2.0.0, Ddev v1.13.0 had this issue.
I updated `nfs_mount_enabled: false` line to "true" in `.ddev/config.yaml` file (like @rfay said above), restart and all good.
Thanks all!

**Comment by rfay** [comment]
Docker Desktop for Windows 2.2.0.3 was released today; I tested a prerelease and it seemed like it was going to be fine.
