### ISSUE TITLE
TestGetApps and TestGetAppsEmpty fail if there are sites configured not by the tests

### ISSUE THREAD

**Issue by rfay** [drud/ddev#205]
## What happened (or feature request):

I ran `make testpkg` but there was an existing unrelated site in ddev. It caused the tests to fail with 

```
=== RUN   TestGetApps
--- FAIL: TestGetApps (0.03s)
        Error Trace:    local_test.go:148
	Error:		Not equal: 4 (expected)
			        != 3 (actual)
```

TestGetAppsEmpty has the same problem:
```
--- FAIL: TestGetAppsEmpty (0.02s)
        Error Trace:    local_test.go:320
	Error:		Not equal: 1 (expected)
			        != 0 (actual)

FAIL
FAIL	github.com/drud/ddev/pkg/plugins/platform	522.081s
```

## What you expected to happen:

Tests should not be broken by non-test state, if possible

## How to reproduce it (as minimally and precisely as possible):

* Start a ddev site (or have it stopped)
* Run `make testpkg`

## Related source links or issues:

**Comment by rickmanelius** [comment]
@rfay I see a merged pull request referencing this. Does this solve/fix the issue?

**Comment by rfay** [comment]
Yeah, #279 isn't a full approach but it's good enough for now. Closing.
