### ISSUE TITLE
'ddev composer require' fails

### ISSUE THREAD

**Issue by JonathanW-Q2** [drud/ddev#2059]
**Describe the bug**
I'm not sure what I've done to my DDEV environment, but the "ddev composer require" command now fails.

**To Reproduce**
1. Go to the project directory.
2. Run the command, 'ddev composer require drupal/some_package'
3. It produces an error like the following and doesn't install the module:

`
$ ddev composer require drupal/adminimal_admin_toolbar
The "https://packages.drupal.org/8/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
https://packages.drupal.org/8 could not be fully loaded, package information was loaded from the local cache and may be out of date

  [Composer\Downloader\TransportException]
  The "https://packages.drupal.org/8/drupal/adminimal_admin_toolbar%245b2bdadaa9a527818576588d4f6f3548a519021e0cef3eb1e03e2858aabbc5bc.json" file could not be downloaded: SSL operation failed with cod
  e 1. OpenSSL Error messages:
  error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
  Failed to enable crypto
  failed to open stream: operation failed

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

composer [require drupal/adminimal_admin_toolbar] failed, composer command failed: exit status 1. stderr=
`

**Expected behavior**
I expected the module to be installed without errors.

**Screenshots**
![composer_require](https://user-images.githubusercontent.com/58003651/73479612-ec146300-435d-11ea-9509-cb3e6e48e985.jpg)

**Version and configuration information (please complete the following information):**
 - Windows 10 Enterprise 1809
 - Docker version 19.03.5 (Docker Desktop 2.2.0.0 (42247)
 - ddev version 1.12.0
 - openssl version 1.1.01 (inside the "web" container)
 - openssl version 1.1.1 (outside the container)
 - config.yaml contents for the misbehaving project:

APIVersion: v1.12.0
name: d8
type: drupal8
docroot: web
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
nfs_mount_enabled: true
provider: default
use_dns_when_possible: true
timezone: "America/Chicago"

 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder?  <-- no

**Additional context**
If I run `curl https://packages.drupal.org/8/packages.json` within the "web" container, I get the following message:

`
$ curl https://packages.drupal.org/8/packages.json
curl: (60) SSL certificate problem: certificate is not yet valid
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
`

The command works correctly outside of the container.

I tried updating openssl both inside and outside the "web" container, but that didn't help. I did notice that the time inside the container is about a day and half behind, although I'm not sure if that could be related to this issue.

Any thoughts on what might be causing this issue or what else I could try doing to narrow down the cause?

**Comment by rfay** [comment]
Have you tried using composer for anything else? Do you have a proxy of some type going? 

Here's what I see with a Drupal 8.8 composer build:
```
rfay@rfay-win10home:~/workspace/d88$ ddev composer require drupal/adminimal_admin_toolbar
Using version ^1.10 for drupal/adminimal_admin_toolbar
./composer.json has been updated
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing drupal/admin_toolbar (2.0.0): Downloading (100%)
  - Installing drupal/adminimal_admin_toolbar (1.10.0): Downloading (100%)
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.
Package zendframework/zend-feed is abandoned, you should avoid using it. Use laminas/laminas-feed instead.
Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.
Writing lock file
Generating autoload files
Scaffolding files for drupal/core:
  - Copy [project-root]/.editorconfig from assets/scaffold/files/editorconfig
  - Copy [project-root]/.gitattributes from assets/scaffold/files/gitattributes
  - Copy [web-root]/.csslintrc from assets/scaffold/files/csslintrc
  - Copy [web-root]/.eslintignore from assets/scaffold/files/eslintignore
  - Copy [web-root]/.eslintrc.json from assets/scaffold/files/eslintrc.json
  - Copy [web-root]/.ht.router.php from assets/scaffold/files/ht.router.php
  - Copy [web-root]/.htaccess from assets/scaffold/files/htaccess
  - Copy [web-root]/example.gitignore from assets/scaffold/files/example.gitignore
  - Copy [web-root]/index.php from assets/scaffold/files/index.php
  - Copy [web-root]/INSTALL.txt from assets/scaffold/files/drupal.INSTALL.txt
  - Copy [web-root]/README.txt from assets/scaffold/files/drupal.README.txt
  - Copy [web-root]/robots.txt from assets/scaffold/files/robots.txt
  - Copy [web-root]/update.php from assets/scaffold/files/update.php
  - Copy [web-root]/web.config from assets/scaffold/files/web.config
  - Copy [web-root]/sites/README.txt from assets/scaffold/files/sites.README.txt
  - Copy [web-root]/sites/development.services.yml from assets/scaffold/files/development.services.yml
  - Copy [web-root]/sites/example.settings.local.php from assets/scaffold/files/example.settings.local.php
  - Copy [web-root]/sites/example.sites.php from assets/scaffold/files/example.sites.php
  - Copy [web-root]/sites/default/default.services.yml from assets/scaffold/files/default.services.yml
  - Copy [web-root]/sites/default/default.settings.php from assets/scaffold/files/default.settings.php
  - Copy [web-root]/modules/README.txt from assets/scaffold/files/modules.README.txt
  - Copy [web-root]/profiles/README.txt from assets/scaffold/files/profiles.README.txt
  - Copy [web-root]/themes/README.txt from assets/scaffold/files/themes.README.txt
> DrupalProject\composer\ScriptHandler::createRequiredFiles
```

**Comment by rfay** [comment]
Oh, I suspect you might have caught them updating their certificate. I see a not-before of *today* on their cert:

![image](https://user-images.githubusercontent.com/112444/73481708-a81f5f00-4359-11ea-999a-9caebb67aec9.png)

**Comment by JonathanW-Q2** [comment]
Ahhh, that would make sense! The date within the container is showing 1/29/2020. Is there a recommended way that I could correct the time inside the container? If not, then I'll wait until tomorrow and see if the issue has resolved itself. Great catch!

**Comment by rfay** [comment]
`ddev exec date` 

If your project has been up a long time, do a `ddev restart` to get the time synced to the host time again.

**Comment by JonathanW-Q2** [comment]
On a fluke, I decided to restart Docker and that seemed to have fixed the date issue in the container. And now the 'composer require' command is working again. Yay! So, I think you found the cause of the issue. Thanks for your help!

**Comment by rfay** [comment]
Glad it's working!
