### ISSUE TITLE
Segment event details empty, resulting in "Project type 'none'"

### ISSUE THREAD

**Issue by unn** [drud/ddev#2065]
While investigating ddev start configurations, I'm noticing several project types of `none`. I'm not exactly sure where `none` is coming from but I wanted to make sure that `none` is an intentional choice on our end in some default, or an intentional choice on the users end.

**Comment by rfay** [comment]
"(none)" seems to be Amplitude's reporting for "not set".

It is not an intentional or appropriate choice by ddev or by users. 

This is probably ddev reporting without the app being initialized.  I don't know how that happens. 

I would imagine that the reporting is either `"type": "",` or else the `type` attribute is omitted.

Just speculating: There may be a command that we're reporting that happens outside app context. Or these could be failures that happen outside app context. For example, `ddev start` when in a non-app context.

**Comment by rfay** [comment]
I'm hoping this isn't an initialization-order issue like https://github.com/drud/ddev/issues/1882 was for global_config.yaml, but I don't think so, because the segment reporting happens late, not early.

**Comment by rfay** [comment]
This may very well be a result of undefined init() behavior like #1882 . init() is evil.

Here's the code:

https://github.com/drud/ddev/blob/49754767f684a02139349516ecb6741e19b1f289/cmd/ddev/cmd/root.go#L145-L173

These inits are executed in alpha order in that cmd package, root.go comes far down the list, but not at the bottom. Comes before start.go though...

**Comment by rfay** [comment]
This problem isn't solved, sadly.

**Comment by rfay** [comment]
This is an example of a report that doesn't have required information, seen on segment. 

<img width="659" alt="Sources_-_ddev-local-prod_-_Segment" src="https://user-images.githubusercontent.com/112444/80968915-01be7c00-8dd6-11ea-94d7-6f71ecdadcda.png">

**Comment by rfay** [comment]
Can look at these with https://analytics.amplitude.com/ddev/chart/4xowhkh and then use "User streams" to chase them.

**Comment by rfay** [comment]
I note that 	app.SetInstrumentationAppTags() is being done *early* but may be missed. 			ddevapp.SetInstrumentationBaseTags() is done very *late* (right before sending). I imagine they should be done in the same place, if possible.

**Comment by rfay** [comment]
By studying Amplitude data I was able to figure out a way to recreate this.
1. Edit ~/.ddev/global_config.yaml and delete the lines containing `instrumentation_opt_in` and `last_started_version`
2. `ddev start` 
3. Accept instrumentation

That `ddev start` will show up without any app information in segment.

**Comment by rfay** [comment]
@unn I note that there will still be a few things that come through without app context. For example, `ddev auth ssh` is not generally executed in the context of a project, so no project type or PHP version can be available.

**Comment by unn** [comment]
That makes sense.
