### ISSUE TITLE
Windows: Can't create web container when using nfs mounts

### ISSUE THREAD

**Issue by loeffe1** [drud/ddev#2074]
I am getting an error when starting the web container when using nfs mounts.

_ddev debug nfsmount_ output:

```
unable to access nfs mount: failed to StartContainer: API error (500): error while mounting volume '/var/lib/docker/volumes/testnfsmount/_data': failed to mount local volume: mount :/c/Users/my.user/projects/test_project:/var/lib/docker/volumes/t
estnfsmount/_data, data: addr=127.0.0.1,hard,nolock: operation not supported output=
```

I have gone through all windows specific debugging steps, the nfsd service is running and I have added the firewall exception.

I used the below script to set up the service since the one coming with ddev did not work for me (the service would always pause after starting) 

https://github.com/drud/ddev/blob/e0fdc174813b2c5e0ef5aa8267ef6a9a022ce547/scripts/windows_ddev_nfs_setup.sh

My projects are located in my user folder, nfs_exports.txt includes this line:
`C:\ > /C`

Windows 10 v1809
Docker Desktop 2.2.0.0
ddev 1.13.0

**Comment by rfay** [comment]
I think your exports file needs a lower case 'c'
```
C:\ > /c
```

**Comment by rfay** [comment]
Here's what my nfs_exports.txt says:
```
C:\Users\rfay > /c/Users/rfay
```

I don't know where you got the link for the script you used... It should be https://github.com/drud/ddev/blob/master/scripts/windows_ddev_nfs_setup.sh - but nevertheless, your nfs_export.txt was not created by either of those, it was created a long, long time ago. I can't remember when or why the C changed to a 'c', but it was many moons ago.

**Comment by loeffe1** [comment]
I removed the service and recreated it using the script linked in the docs. I had to replace $DOCKER_HOST with npipe:////./pipe/docker_engine and the line
`
sudo nssm install nfsd "${winnfsd}" -id ${DDEV_WINDOWS_UID} ${DDEV_WINDOWS_GID} -addr $nfs_addr -log off -pathFile "\"$HOMEDRIVE$HOMEPATH\.ddev\nfs_exports.txt\""`

with

`winpty sudo nssm install nfsd "${winnfsd}" -id ${DDEV_WINDOWS_UID} ${DDEV_WINDOWS_GID} -log off -pathFile "\"$HOME/.ddev/nfs_exports.txt\""`

Without the latter edit, the service would be created but never go into running state:

```
Service "nfsd" installed successfully!
nfsd: Unexpected status SERVICE_PAUSED in response to START control.
SERVICE_PAUSED
winnfsd has been installed as service nfsd serving the mounts in ~/.ddev/nfs_exports.txt
```

After the change the service is running and nfs_exports.txt includes the correct user path with a lower c. However a ddev debug nfsmount will still give me the unable to access nfs mount error.
My username includes a dot (.). Could this be causing problems?

**Comment by rfay** [comment]
I'd appreciate it if you could say why you had to change the script. I have never seen winpty be necessary to run nssm...   Are you running the script inside git-bash? 

It *is* "normal" for nssm start to say "nfsd: Unexpected status SERVICE_START_PENDING in response to START control" when it starts up. I guess there should be a sleep introduced there.

After it says "pending" you can probe it with `nssm status nfsd` and you'll see it's up.

As far as changing $DOCKER_HOST... it's not supposed to be set if you're using Windows 10 Pro. That line that uses is is only encountered if a Docker Toolbox installation is encountered. So perhaps $DOCKER_TOOLBOX_INSTALL_PATH is set in your environment? Perhaps Docker Toolbox is even installed? If that's the case, please completely uninstall Docker Toolbox, and make sure that that doesn't exist any more in the system environment variables.

**Comment by rfay** [comment]
I just tested with a username containing a dot (randy.fay) and had no trouble. Also had no request for winpty.

**Comment by rfay** [comment]
I did find when testing on my new user (randy.fay) that I had some really annoying problems with winnfsd crashing. When you run it as a service, you have to run the Windows "Event Viewer" to see the crashes (on left pane, select "Windows Logs" -> "Application Logs" to see them.

If you do see nfsd crashing there, experiment with running it manually (in cmd or PS):
```
winnfsd -pathFile C:\Users\randy.fay\.ddev\nfs_exports.txt -log on
```

You should see it say "Listening" and then it should report all your actions when you try `ddev debug nfsmount`

After fiddling aimlessly trying to get it not to crash, I tried this nfs_exports.txt:
```
# Exports for winnfsd for ddev
# You can edit these yourself to match your workflow
# But nfs must share your project directory
# Additional lines can be added for additional directories or drives.
C:\Users\randy.fay > /c/Users/randy.fay
C:\ > /c
```
I have no idea why that would help, and I have not had this experience before. I'm wondering if it's funky windows permissions or something, but ...

Once you have it running successfully manually, you should be able to kill that and then successfully run `nssm start nfsd`. I did a couple of `nssm remove nfsd` and then ran the script again.

Again, no clue why winnfsd is crashing; it seems to me there's a crazy error just parsing the exports file.

One thing you can do is change the service configuration in nssm to not use the nfs_exports.txt if it's going to be that picky and annoying.

I tried this:
1. `nssm edit nfsd`
2. Changed the arguments there to `-id 1000 1000 -addr 127.0.0.1 -log off C:\Users\randy.fay /c/Users/randy.fay`
3. `nssm restart`

I think that might be a good path if you're having trouble with winnfsd crashing.

When you run that and you're *successful* it does not return to the prompt. 
I was trying lots of things and

**Comment by loeffe1** [comment]
> I'd appreciate it if you could say why you had to change the script. I have never seen winpty be necessary to run nssm... Are you running the script inside git-bash?
> 
> It is "normal" for nssm start to say "nfsd: Unexpected status SERVICE_START_PENDING in response to START control" when it starts up. I guess there should be a sleep introduced there.

I did use git bash to run the script via the sh command. Without changing the script as described by me, the servive would be created in state SERVICE_**PAUSED**. I have never encountered the SERVICE_START_PENDING state. Also I have never been able to start the service once it had been initiliazed with a script that would create it with state SERVICE_PAUSED.

I used the winpty line (aswell as the old script I mentioned in my initial post) from this discussion: https://github.com/drud/ddev/issues/1452

> As far as changing $DOCKER_HOST... it's not supposed to be set if you're using Windows 10 Pro. That line that uses is is only encountered if a Docker Toolbox installation is encountered. So perhaps $DOCKER_TOOLBOX_INSTALL_PATH is set in your environment? Perhaps Docker Toolbox is even installed? If that's the case, please completely uninstall Docker Toolbox, and make sure that that doesn't exist any more in the system environment variables.

I did find out that I still had a choco docker-toolbox package installed, so this explains why I ran into that line.

I have rolled back to Docker Desktop 2.1.0.5 because I really needed symlinks to work and gave up on the nfs mounts for now. However now I am running into a new issue, so I am afraid I will have to figure out this new problem first.

Thank you so much for your help. I will post my experiencies once I feel confident enough to try nfs mounts again.

**Comment by rfay** [comment]
Thanks so much for all your effort on this. FYI Docker 2.2.0.3 is out today, which solves lots of things in that bad 2.2.0.0 release. But if I were you  I'd be hesitant to mess with ANYTHING!

**Comment by rfay** [comment]
I'm going to close this for now, happy to continue the conversation here or in any other support channel later.

**Comment by rfay** [comment]
Future googlers: please note that the docs for debugging NFS on Windows are at https://ddev.readthedocs.io/en/stable/users/performance/#windows-specific-nfs-debugging - there's a lot there. 

Also please note that WSL2 is the preferred path forward for Windows users as of May 2020, and it doesn't even need NFS at all, and is super-speedy. Please see https://ddev.readthedocs.io/en/latest/#installation for installation instructions. There's also a nice blog post on it at https://ddev.com/ddev-local/ddev-wsl2-getting-started/
