### ISSUE TITLE
A way for watching the logs

### ISSUE THREAD

**Issue by jepster** [drud/ddev#2078]
I would like to be able to "watch" the webserver and database logs. I am currently not sure how the logs for the "ddev logs" command are gathered. If I check the logs from the /var/log/php-fpm.log and /var/log/nginx/error.log file, then this logs are empty. But if I check "ddev logs", I can see some expected PHP exceptions from my application. 

Usually I was doing something like that for debugging my application:
**tail -f /var/log/*.log**

Then I could see all the new log entries and start debugging. In DDEV I do not see any updates via the mentioned way with my "tail" command.

Could you point me here in the right direction, please?

**Comment by unn** [comment]
It's the same, in fact, `ddev logs -f`

Check out the help text there for other cool options. `ddev logs --help`

**Comment by rfay** [comment]
@jepster happy to continue the conversation here and reopen this if you need to, but I *think* `ddev logs -f` and `ddev logs -s db -f` will probably help. There are in fact a couple of logs in the web container that don't get spit out to that, so it may be worth `ddev ssh` and review the logs in /var/logs and /var/logs/nginx, where you can tail them if necessary.

**Comment by jepster** [comment]
Thanks for your explanations!

**Comment by penyaskito** [comment]
Needed this today.

`ddev exec  tail -f /var/log/nginx/access.log`
