### ISSUE TITLE
Can't run Drush commands from outside the container anymore

### ISSUE THREAD

**Issue by leymannx** [drud/ddev#2080]
**Describe the bug**

When I initially wrote this issue I thought it happened because of the new Drupal Composer template. But it seems to be DDEV 1.13.0 that introduced this behaviour. It has worked in DDEV 1.12.1.

---

Now that the docs switched the Drupal 8 quickstart guide to use the `drupal/recommended-project` instead of `drupal-composer/drupal-project` the settings.php doesn't get created anymore during the `ddev composer create` command so that DDEV now appends the lines to include its own settings.ddev.php to a nearly empty file. It only has the opening PHP tags in it, and then comes the standard settings.ddev.php include.

```php
<?php

// #ddev-generated: Automatically generated Drupal settings file.
if (file_exists($app_root . '/' . $site_path . '/settings.ddev.php') && getenv('IS_DDEV_PROJECT') == 'true') {
  include $app_root . '/' . $site_path . '/settings.ddev.php';
}
```

I then strangely can install Drupal via Drush but only when running `ddev exec drush site:install` and not when running `drush site:install` from outside the container (although having Drush Launcher, and `mysql` installed on my Mac – and it also worked with the former `drupal-composer/drupal-project` setup).

**To Reproduce**

1. Follow the Drupal 8 quickstart guide. (Wondering why there's two times `ddev start` refs https://github.com/drud/ddev/pull/2071/files#r376984193)

```bash
mkdir my-drupal8-site
cd my-drupal8-site
ddev config --project-type=drupal8 --docroot=web --create-docroot=true
ddev start
ddev composer create drupal/recommended-project
ddev composer remove drupal/core-project-message
ddev composer require drush/drush
ddev start
```

2. Install Drupal via Drush, one time from `ddev exec drush si` and the other time from `drush si`.

2.1. `ddev exec drush si` (works fine)

```bash
$ ddev exec drush -y site:install --account-name=admin --account-pass=admin

 // You are about to DROP all tables in your 'db' database. Do you want to
 // continue?: yes.

 [notice] Starting Drupal installation. This takes a while.
 [success] Installation complete.
```

2.2. `drush si` (doesn't work anymore)

```bash
$ drush -y site:install --account-name=admin --account-pass=admin

 // You are about to CREATE the 'drupal' database. Do you want to continue?:
 // yes.

 [warning] Failed to drop or create the database. Do it yourself before installing. ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (61)

 [notice] Starting Drupal installation. This takes a while.

In install.core.inc line 974:

  Resolve all issues below to continue the installation. For help configuri
  ng your database server, see the <a href="https://www.drupal.org/docs/8/i
  nstall">installation handbook</a>, or contact your hosting provider.<div
  class="item-list"><ul><li>Failed to connect to your database server. The
  server reports the following message: <em class="placeholder">SQLSTATE[HY
  000] [2002] Connection refused</em>.<ul><li>Is the database server runnin
  g?</li><li>Does the database exist or does the database user have suffici
  ent privileges to create the database?</li><li>Have you entered the corre
  ct database name?</li><li>Have you entered the correct username and passw
  ord?</li><li>Have you entered the correct database hostname and port numb
  er?</li></ul></li></ul></div>


site:install [--db-url DB-URL] [--db-prefix DB-PREFIX] [--db-su DB-SU] [--db-su-pw DB-SU-PW] [--account-name [ACCOUNT-NAME]] [--account-mail [ACCOUNT-MAIL]] [--site-mail [SITE-MAIL]] [--account-pass ACCOUNT-PASS] [--locale [LOCALE]] [--site-name [SITE-NAME]] [--site-pass SITE-PASS] [--sites-subdir SITES-SUBDIR] [--config-dir CONFIG-DIR] [--existing-config] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--notify] [--druplicon] [--xh-link XH-LINK] [--] <command> [<profile>]...
```

3. The same happens when running `drush cr`.

3.1. `ddev exec drush cr`

```bash
$ ddev exec drush cr
 [success] Cache rebuild complete.
```

3.2. `drush cr`

```bash
$ drush cache:rebuild

In Settings.php line 159:

  Missing $settings['hash_salt'] in settings.php.


cache:rebuild [--cache-clear [CACHE-CLEAR]] [--no-cache-clear] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--notify] [--druplicon] [--xh-link XH-LINK] [--] <command>
```

**Expected behavior**

Having Drush Launcher, PHP and `mysql` installed locally executing Drush commands should work like it did before.

**Screenshots**

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macOS Catalina
 - Docker version: Docker version 19.03.5, build 633a0ea
 - ddev version:
```
DDEV-Local version	v1.13.0
commit            	v1.13.0
db                	drud/ddev-dbserver-mariadb-10.2:v1.13.0
dba               	phpmyadmin/phpmyadmin:5
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.13.0
docker            	19.03.5
docker-compose    	1.25.2
os                	darwin
router            	drud/ddev-router:v1.13.0
web               	drud/ddev-webserver:v1.13.0
```
 - config.yaml contents:
```yaml
APIVersion: v1.13.0
name: recommended
type: drupal8
docroot: web
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
timezone: ""
```

```
PHP 7.3.13 (cli) (built: Dec 18 2019 16:08:06) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.13, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.13, Copyright (c) 1999-2018, by Zend Technologies
```

```
$ mysql --version
mysql  Ver 8.0.19 for osx10.15 on x86_64 (Homebrew)
```

**Additional context**

This only seems to be happening with new projects created with DDEV 1.13.0. For older projects it's still working "normally" and I can execute Drush commands from outside the container and it just finds the right connection and everything is working fine. 🤔

**Comment by rfay** [comment]
Hi @leymannx - I think your problem is mentioned in the release notes, https://github.com/drud/ddev/releases/tag/v1.13.0

> If you use drush on the host to interact with your project, please export IS_DDEV_PROJECT=true in your environment. The settings files have no way to know that you want to use ddev settings if you don't do this.

Is that true?

**Comment by leymannx** [comment]
Uh I should have read them more carefully. Let me check! BRB

**Comment by leymannx** [comment]
Hummmm, so on my Mac I run `export IS_DDEV_PROJECT=true`, right? I did that and then `drush si` again but the error persists. But only in the newly created projects.

**Comment by leymannx** [comment]
Ah sorry, I forgot the second `ddev start`!  Now it's working. Thanks Randy!

Wondering if this shouldn't be highlighted more prominently in the docs. But maybe this issue here is good enough for now for others to find it.

Is it really necessary to have the first `ddev start` though?

**Comment by rfay** [comment]
I don't understand "second ddev start" or the context here. 

You're saying that you have to `ddev start` after changing the environment variable, that's definitely true. My recommendation is to just put the export into your .profile or equivalent if you use drush this way.

**Comment by leymannx** [comment]
I performed the following steps right from the [docs](https://ddev.readthedocs.io/en/latest/users/cli-usage/#drupal-8-quickstart). A fresh setup. And it has two `ddev start` in it.

```bash
mkdir my-drupal8-site
cd my-drupal8-site
ddev config --project-type=drupal8 --docroot=web --create-docroot=true
ddev start
ddev composer create drupal/recommended-project
ddev composer remove drupal/core-project-message
ddev composer require drush/drush
ddev start
```

**Comment by rfay** [comment]
I *thought* this issue was about running drush on the host?

The second ddev start there may not be completely required (and you're looking at the "latest" docs, not "stable"). I generally start or restart after massive changes like this. I wouldn't be surprised if this works without the second start though.

**Comment by leymannx** [comment]
This issue occurred when I wanted to test out the new Drupal core template in DDEV and see what happens. New DDEV version, new Composer template, new quickstart guide. I don't know exactly what is related to what, I'm just trying to understand the changes.

Thanks for the quick reply anyways! Totally in love with DDEV. 💛

**Comment by rfay** [comment]
Yay, glad it's working for you.

**Comment by leymannx** [comment]
Ah yeah, now I found the corresponding lines in the `settings.ddev.php`. Makes sense.

```php
$host = "db";
$port = 3306;

// If DDEV_PHP_VERSION is not set but IS_DDEV_PROJECT *is*, it means we're running (drush) on the host,
// so use the host-side bind port on docker IP
if (empty(getenv('DDEV_PHP_VERSION') && getenv('IS_DDEV_PROJECT') == 'true')) {
  $host = "127.0.0.1";
  $port = 32797;
} 

$databases['default']['default'] = array(
  'database' => "db",
  'username' => "db",
  'password' => "db",
  'host' => $host,
  'driver' => "mysql",
  'port' => $port,
  'prefix' => "",
);
```
