### ISSUE TITLE
Document Xdebug for PHP CLI

### ISSUE THREAD

**Issue by jepster** [drud/ddev#2081]
Hi,

Xdebug works fine for webbrowser related processes. Is there also an intended way to use Xdebug for the PHP CLI?

**Comment by rfay** [comment]
It's basically the same as command-line xdebug anywhere, but there's a nice article about it at https://glamanate.com/blog/xdebug-over-command-line-ddev

I think it would be reasonable to add docs to our xdebug section to say how this works.

**Comment by jepster** [comment]
Thanks again for your quick reply. You are definitely a responsible maintainer @rfay! We could solve our issue. Debugging CLI PHP scripts is working fine now via DDEV for us.

**Comment by rfay** [comment]
Reopening for explicit docs
