### ISSUE TITLE
apache-fpm Drupal 8: "No input file specified." on update.php/selection on web update.php

### ISSUE THREAD

**Issue by leymannx** [drud/ddev#2083]
**Describe the bug**

When performing database updates from Drupal's admin UI under http://foobar.ddev.site/update.php, I run into an error 500 saying "No input file specified".

**To Reproduce**

1. Create new DDEV/Drupal project. Apache webserver.

	   mkdir foobar && cd foobar
	   ddev config --project-type php
	   printf 'y' | ddev composer create --no-interaction --prefer-dist drupal-composer/drupal-project:8.x-dev
	   ddev config --project-type drupal8 --php-version 7.3 --webserver-type apache-fpm
	   ddev restart
2. Install Drupal
           ddev exec drush -y si --account-name=admin --account-pass=admin
3. Login http://foobar.ddev.site/user
4. Go to http://foobar.ddev.site/update.php
5. Click "Continue"
6. ---> Error: "No input file specified."

Tried the same with `RewriteBase /` in Drupal's `.htaccess` uncommented, then `ddev restart` just to be sure, but it's the same. "No input file specified" when hitting "Continue" on http://foobar.ddev.site/update.php.

**Expected behavior**

Database update routine should be started.

**Screenshots**

<img width="496" alt="Screenshot 2020-02-12 at 12 02 12" src="https://user-images.githubusercontent.com/3585653/74329164-8da0a900-4d8f-11ea-89e9-ff3493fc2b97.png">

**Version and configuration information (please complete the following information):**
 - macOS Catalina
 - Docker version 19.03.5, build 633a0ea
 - ddev version
    ``` 
   DDEV-Local version	v1.13.0
   commit            	v1.13.0
   db                	drud/ddev-dbserver-mariadb-10.2:v1.13.0
   dba               	phpmyadmin/phpmyadmin:5
   ddev-ssh-agent    	drud/ddev-ssh-agent:v1.13.0
   docker            	19.03.5
   docker-compose    	1.25.4
   os                	darwin
   router            	drud/ddev-router:v1.13.0
   web               	drud/ddev-webserver:v1.13.0
   ```
 - config.yaml
    ```
   APIVersion: v1.13.0
   name: foobar
   type: drupal8
   docroot: web
   php_version: "7.3"
   webserver_type: apache-fpm
   router_http_port: "80"
   router_https_port: "443"
   xdebug_enabled: false
   additional_hostnames: []
   additional_fqdns: []
   nfs_mount_enabled: false
   provider: default
   use_dns_when_possible: true
   timezone: ""

**Comment by rfay** [comment]
I can replicate that using apache-fpm (but not nginx-fpm, which works fine). When it hits https://d8composer.ddev.site/update.php/selection you get the "no input file"

But I'm surprised to see it on Apache as well. 

I imagine there has to be a special rewrite for update.php in the apache config, as would be done for nginx in https://www.drupal.org/project/drupal/issues/2606180#comment-12479409

You have at least a few options for now:
* Use nginx-fpm
* Use `ddev exec drush updb` (or my preference is to `ddev ssh` and use `drush updb`)

I'd be interested to know why you want Apache here.

**Comment by leymannx** [comment]
Apache to mimic client's live env. Drush definitely is a valid workaround. I remember seeing the same once at a coworker's machine when trying to access /install.php but I couldn't reproduce it until now.

Do you think that's maybe due to some customized Apache conf DDEV-wise? Would this also affect DDEV Live (which is not the issue right now, so maybe off-topic)?

**Comment by rfay** [comment]
DDEV-Live is in fact off-topic, but I don't believe there will be an Apache config offered there in the near future.

**Comment by leymannx** [comment]
Got it!!! Putting a `my-php.ini` in `.ddev/php` with the following content and then restarting the container fixed it!!!

```ini
cgi.fix_pathinfo=1
```

I'll submit a PR in a few minutes.
