### ISSUE TITLE
'php' project type uses nginx config derived from Drupal nginx config, should be more generic - Laravel Conflict

### ISSUE THREAD

**Issue by jdoubleu** [drud/ddev#2084]
**Describe the bug**
Nginx inside the webserver is [adding the requested relative URL as `q` query parameter](https://github.com/drud/ddev/blob/master/containers/ddev-webserver/files/etc/nginx/nginx_default.conf#L14) to the request which is then passed to PHP (fcgi).
This parameter appears in the global `$_GET` PHP array.

Since I am using Laravel with DDEV this pollutes Laravel's signature verification. The signature verification functions [collects all query params from the current request](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Routing/UrlGenerator.php#L383) and verifies it against the previously calculated signature. However this current request includes the `q` query param, while the precalculated signature doesn't include it.

**To Reproduce**
1. Create an empy ddev project with the PHP configration.
2. Create a `index.php` in the `public` folder and add a debug breakpoint.
3. Open the project in your browser and append an arbitraty path (e.g. `myproject.ddev.site/some/path/`).
4. See that the global `$_GET` array contains `q=some/path/`.

**Expected behavior**
There are no additional query params in the `$_GET` or `$_REQUEST` array other than the user-provided ones.

**Version and configuration information (please complete the following information):**
 - ddev version information: v1.12.1

**Screenshot**
![Screenshot 2020-02-12 at 16 22 37](https://user-images.githubusercontent.com/11274444/74349068-fe59bc80-4db3-11ea-8848-d63915d38868.png)

**Additional context**
As mentioned before, this confuses Laravel's signature validation middleware which is used for email verification: https://github.com/laravel/framework/issues/30594#issuecomment-585235650.

**Comment by rfay** [comment]
This is likely a result of the default nginx configuration being derived from a default Drupal configuration.

Probably:
* You should use a custom nginx configuration (https://ddev.readthedocs.io/en/stable/users/extend/customization-extendibility/#providing-custom-nginx-configuration) - you may want to replace the whole thing, referred to as "legacy"
* ddev should probably use a more generic configuration for "php" projects. If you get yours working, we'll consider doing that.

**Comment by jdoubleu** [comment]
Unfortunately it is not possible to override the `location` directive to remove the additional query parameter.

I'd have to replace the whole site configuration which is deprecated, as you said.

I'm trying to create a generic nginx configuration for PHP projects in general and move the current customizations to the Drupal configs?

**Comment by rfay** [comment]
Deprecated is way too strong. That approach is the only way to do many relevant things with nginx config, so recommended. 

Yes, you're trying to make a generic PHP config, one that's most likely to succeed. @cweagans this is what you wanted to do, right? 

Each supported CMS type has its own default nginx config, so Drupal6/7/8 already have theirs; there's no need for "moving" anything, just getting you a config that's sane for your purposes (and maybe for others).

**Comment by cweagans** [comment]
Sort of. I just wanted ddev to not try to mess with my settings.php, so I was using the php project type as a workaround for that.

**Comment by rfay** [comment]
Right @cweagans but you offered this PR, https://github.com/drud/ddev/pull/1894, for something you were working on. I'd think we'd probably want a default 'php' nginx-config that was even simpler than just that change though.

**Comment by cweagans** [comment]
Oh, right. I forgot about that. Yeah, a super simple PHP config is probably the right thing. Just enough to run hello world + rewrite /foo/bar to index.php/foo/bar for nice URLs. That'd probably cover the majority of applications.

**Comment by rfay** [comment]
But would a config that simple break you on Laravel @jdoubleu ?

**Comment by rfay** [comment]
Another path I'd love to pursue is explicit support for Laravel.  I don't think this would take all that much more than a community-approved nginx config.

**Comment by rfay** [comment]
I should mention too that the recipe in https://github.com/drud/ddev-contrib/tree/master/recipes/laravel has seemed to work for people in general. 

The problem you have only shows up with email verification? Is that why we haven't heard about it before?

**Comment by jdoubleu** [comment]
> But would a config that simple break you on Laravel @jdoubleu ?

No, I think a simple config like that would be enough for most PHP projects. As long as all other [FastCGI params](https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/#fastcgi-params) (e.g. script name, path info, request info, etc.) are set, every PHP script should be able to determine the current requested path through `$_SERVER` variable.

> Another path I'd love to pursue is explicit support for Laravel. I don't think this would take all that much more than a community-approved nginx config.
I agree. Additionally to the basic PHP configuration, Laravel in DDEV could benefit from additional  rules e.g. for the public storage and media and some caching.

However, Laravel's minimal [webserver configuration documentation](https://laravel.com/docs/6.x#pretty-urls) doesn't add any special rules.

Besides that, DDEV would be competing against [Laravel Homestead](https://laravel.com/docs/6.x/homestead), a custom local development environment using Vagrant, made for Laravel. It provides way more services than DDEV does out of the box. I know it's still possible to add custom services to DDEV, however with Homestead it is as easy as running a simple command. The most important services I can think of are Redis and Elasticsearch along with MySQL and Mailhog which are already available in DDEV.

> The problem you have only shows up with email verification? Is that why we haven't heard about it before?

The root cause for the stated issue lives in the [`ValidateSignature` middleware](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Routing/Middleware/ValidateSignature.php#L19-L25) in the HTTP request pipeline. This middleware will verify the current [request against a signature](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Routing/UrlGenerator.php#L371-L389) (of the supposed request), embedded in the current request. Since DDEV added the `q` parameter to the request, the signature check fails.
This middleware can be added to any route in Laravel. The most common route it's used for is the email verification endpoint. That's why I noticed this issue.

**Comment by rfay** [comment]
Anyway @jdoubleu , if you can use a custom .ddev/nginx-site.conf that gets you where you want to go, please do post it here. Thanks!

**Comment by jdoubleu** [comment]
> [..] please do post it here.

Sorry for the delay! You can find my `.ddev/nginx-site.conf` below. It currently fits my case. However, it is missing some features (e.g. static file caching and compression), that I consider required by some larger Laravel applications. Unfortunately I couldn't find any other resources but the mentioned [Laravel Setup Guide](https://laravel.com/docs/6.x#pretty-urls). Furthermore I am not sure which rules to keep, I just left the whole config as it was and only added the Laravel specific part. The Vagrant fix, for example, might be removed.

```
# taken from https://github.com/drud/ddev/blob/master/containers/ddev-webserver/files/etc/nginx/nginx-site-default.conf
# according to https://ddev.readthedocs.io/en/stable/users/extend/customization-extendibility/#providing-custom-nginx-configuration
# see https://github.com/drud/ddev/issues/2084

# ddev default config

# You can override ddev's configuration by placing an edited copy
# of this config (or one of the other ones) in .ddev/nginx-site.conf
# See https://ddev.readthedocs.io/en/stable/users/extend/customization-extendibility/#providing-custom-nginx-configuration

# Set https to 'on' if x-forwarded-proto is https
map $http_x_forwarded_proto $fcgi_https {
    default off;
    https on;
}

server {
    listen 80;
    listen [::]:80 default ipv6only=on;

    # The WEBSERVER_DOCROOT variable is substituted with
    # its value when the container is started.
    root $WEBSERVER_DOCROOT;

    include /etc/nginx/monitoring.conf;

    # the following is taken from https://github.com/drud/ddev/blob/master/containers/ddev-webserver/files/etc/nginx/nginx_default.conf
    index index.php index.htm index.html;

    # Make site accessible from http://localhost/
    server_name _;

    # Disable sendfile as per https://docs.vagrantup.com/v2/synced-folders/virtualbox.html
    sendfile off;
    error_log /dev/stdout info;
    access_log /var/log/nginx/access.log;

    # see https://laravel.com/docs/6.x#pretty-urls
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # pass the PHP scripts to FastCGI server listening on socket
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php-fpm.sock;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_intercept_errors off;
        # fastcgi_read_timeout should match max_execution_time in php.ini
        fastcgi_read_timeout 10m;
        fastcgi_param SERVER_NAME $host;
        fastcgi_param HTTPS $fcgi_https;
    }
}


server {
    listen 443 ssl;
    listen [::]:443 default ipv6only=on;

    # The WEBSERVER_DOCROOT variable is substituted with
    # its value when the container is started.
    root $WEBSERVER_DOCROOT;

    ssl_certificate /etc/ssl/certs/master.crt;
    ssl_certificate_key /etc/ssl/certs/master.key;

    include /etc/nginx/monitoring.conf;

    # the following is taken from https://github.com/drud/ddev/blob/master/containers/ddev-webserver/files/etc/nginx/nginx_default.conf
    index index.php index.htm index.html;

    # Make site accessible from http://localhost/
    server_name _;

    # Disable sendfile as per https://docs.vagrantup.com/v2/synced-folders/virtualbox.html
    sendfile off;
    error_log /dev/stdout info;
    access_log /var/log/nginx/access.log;

    # see https://laravel.com/docs/6.x#pretty-urls
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # pass the PHP scripts to FastCGI server listening on socket
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php-fpm.sock;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_intercept_errors off;
        # fastcgi_read_timeout should match max_execution_time in php.ini
        fastcgi_read_timeout 10m;
        fastcgi_param SERVER_NAME $host;
        fastcgi_param HTTPS $fcgi_https;
    }
}
```

**Comment by rfay** [comment]
Thanks so much!

**Comment by rfay** [comment]
Just a note that #2263 uses a somewhat simplified nginx configuration for the "php" or default project type. 

Also, Laravel also is a first-class project type with its own dedicated nginx configuration. I hope that everybody interested in this issue will try out the alphas for v1.15.  Laravel support is already in [v1.15-alpha4](https://github.com/drud/ddev/releases/tag/v1.15-alpha4). When #2263 is pulled I'll do another alpha, and that would be a fantastic testing opportunity, since the nginx configs all got mucked around a bit with the change there.
