### ISSUE TITLE
Support `name: $auto` in .ddev/config.yaml

### ISSUE THREAD

**Issue by cweagans** [drud/ddev#2085]
**Is your feature request related to a problem? Please describe.**

We have several hundred sites that are all based on a common repository. We have a standard ddev configuration in that repository, and when we roll out updates from that repository to ddev's config.yaml, everyone has to `ddev config` and rename their projects again (because they have several different projects based on this repository up and running on their workstation at any given time).

We manage the ddev configuration centrally so that all of our projects behave the same way, so when a new ddev version comes out, we'll update the ddev config in our central repo.

**Describe the solution you'd like**
I'd like to set `name: $auto` (or something like that) in config.yaml and have ddev automatically determine a project name when I run `ddev start`. So if I have `projectname/.ddev/config.yaml`, I'd like the ddev project to be called `projectname`. If `projectname` already exists elsewhere, then I guess throw an error and ask the user to `ddev config`.

Taking this a step further, I'd even advocate for this being a default behavior -- there's probably not a good reason to force people to name their projects if they've already named the directory where the project lives.

**Describe alternatives you've considered**

**Additional context**

**Comment by rfay** [comment]
FYI, I think you already have this. If you delete the `name` line from .ddev/config.yaml, it just uses the directory name. Does that do it?

**Comment by cweagans** [comment]
Sort of. If I re-do `ddev config` for any reason, it re-adds the name. I'm hoping for some way to tell it to not do that if possible.

**Comment by rfay** [comment]
@cweagans I was wondering if the wildcard additional_hostnames in https://github.com/drud/ddev/pull/2393 would help you with this problem in any way.

**Comment by cweagans** [comment]
I don't think so. We only ever need one hostname per project + the project is always checked out into a directory that matches the name of the project.

**Comment by rfay** [comment]
I think the world would be a better place if the directory name were always the default name, but we allowed overriding it.

**Comment by cweagans** [comment]
💯 agreed completely, although it may not always be possible to use the directory name directly. For our specific use case, it will always work, but I could see a case where there are e.g. underscores in the directory name or something.

**Comment by rfay** [comment]
Since just leaving out the `name` attribute works fine for this need, I think we can just go with that for now.
