### ISSUE TITLE
Add fish shell to web container

### ISSUE THREAD

**Issue by agviu** [drud/ddev#2088]
It would be nice to have the option, out of the box, of using the fish command line shell. Once you get use to it is hard to go back to bash, which is always the default.

**Comment by leymannx** [comment]
I'm using DDEV in Fish shell every day. I don't remember any problem when setting it up.

**Comment by agviu** [comment]
How did you install it in the container?

**Comment by leymannx** [comment]
Ah you mean in the container. I misunderstood that. Maybe you can update the title to "Add Fish shell to web container". And then this would also need some  configuration maybe to define a default shell.

**Comment by rfay** [comment]
I'm sure you can add the package with webimage_extra_packages, https://ddev.readthedocs.io/en/stable/users/extend/customizing-images/#adding-extra-debian-packages-with-webimage_extra_packages-and-dbimage_extra_packages then use a post start hook or custom dockerfile to set default shell.  

This article about zsh should point the way, https://www.ddev.com/ddev-local/oh-my-zsh-using-custom-commands-and-other-goodies-to-add-to-ddev/

**Comment by rfay** [comment]
I checked and 
* It is easy to add the fish package with `webimage_extra_packages: [fish]`
* That doesn't get you all the way there because `ddev ssh` actually explicitly runs bash. But once in a bash shell you can run "fish". 

However, you can add "fish" as the last line of a .profile you add to .ddev/homeadditions ... and it will run it even though bash is having to run it. Here's my .ddev/homeadditions/.profile:
```
# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
fish
```

Here you go...
```
$ ddev ssh
Welcome to fish, the friendly interactive shell
rfay@d8composer-web /v/w/h/web>
```

**Comment by agviu** [comment]
Yes it works very nicely, thank you very much!
This is a great addition!

**Comment by chrisfromredfin** [comment]
Is there a good place in the docs to add this? I feel like that's the right answer here. I know there's also the old ddev-contrib repo (or something like that) - but we're moving away from that, yeah?

**Comment by rfay** [comment]
How about an add-on that adds a `ddev fish` custom command?

**Comment by hanoii** [comment]
FYI: https://github.com/hanoii/ddev-fish
