### ISSUE TITLE
Failing name resolutions inside web container on Ubuntu 19.10

### ISSUE THREAD

**Issue by dmgig** [drud/ddev#2089]
**Describe the bug**
ddev container cannot connect to the internet.

**To Reproduce**
1. run `ddev config` and set up and start a php project
2. run `ddev ssh`
3. run `wget google.com`
4. response is:
```
Resolving google.com (google.com)... failed: Temporary failure in name resolution.
wget: unable to resolve host address 'google.com'
```
5. this is the same behavior for all sites, running `sudo apt update` also fails to connect:
```
W: Failed to fetch http://deb.debian.org/debian/dists/buster/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/dists/buster/updates/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://nginx.org/packages/debian/dists/buster/InRelease  Temporary failure resolving 'nginx.org'
```

**Expected behavior**
The container should be able to connect to the internet upon creation

**Version and configuration information (please complete the following information):**
 - Ubuntu 19.10
 - Docker version 19.03.6
 - ddev version v1.13.0
 - config.yaml base config, no overrides
 - no other custom configuration

**Additional context**
My host can connect to the internet without any issues.

I see a solution [here](https://stackoverflow.com/questions/20430371/my-docker-container-has-no-internet), to update `/etc/resolv.conf` but I am not sure why this has started to happen as it used to work. I reinstalled ddev, and wiped the global `.ddev` file.

My ddev `/etc/resolv.conf`upon creation.

```
search mshome.net
nameserver 127.0.0.11
options ndots:0
```

**Comment by rfay** [comment]
This isn't really a ddev issue, might be a docker issue, but I don't think it's been a problem. I'd start by turning off any firewall you have running to test. And see if it's just name resolution of if all network connectivity is broken. (Ping by up address)

**Comment by dmgig** [comment]
Thanks for the comment.

There's no firewall running and it seems to just be name resolution (I cannot ping `google.com` but I can ping their ip at `172.217.21.174`.

Anyhow, like you said this is probably an issue with docker changing the `resolv.conf` file. I will look into that.

**Comment by rfay** [comment]
I brought up my trusty 19.10 instance and am not seeing any problems.  If this isn't caused by a firewall on your computer, could it be a firewall on your network's router?

```
rfay@ubuntu:~/workspace/junk$ ddev ssh
rfay@junk-web:/var/www/html$ ping google.com
PING google.com (172.217.11.78) 56(84) bytes of data.
64 bytes from lax17s34-in-f14.1e100.net (172.217.11.78): icmp_seq=1 ttl=127 time=749 ms
64 bytes from lax17s34-in-f14.1e100.net (172.217.11.78): icmp_seq=2 ttl=127 time=497 ms
^C
--- google.com ping statistics ---
3 packets transmitted, 2 received, 33% packet loss, time 2353ms
rtt min/avg/max/mdev = 497.707/623.771/749.835/126.064 ms
```

Here's what a "normal" /etc/resolv.conf looks like inside docker container:
```
cat /etc/resolv.conf 
search localdomain
nameserver 127.0.0.11
options ndots:0
```

The 127.0.0.11 is (I think) Docker's nameserver. It's how names like "db" or "solr" get resolved, and I think it passes on regular queries to the configured nameserver on the host. 

BTW, what is the nameserver you're using on the host? Look in /etc/rsolv.conf on your Ubuntu instance to see. It normally comes from DHCP. Maybe It's refusing to serve?

Does `docker version` below match?
```
rfay@ubuntu:~$ docker version
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by dmgig** [comment]
Hi - thanks again. I appreciate the help  - it is certainly an issue on my end. Without any changes on my end, it now works on a fresh ddev instance following the same steps above.

So, it's not a problem now. I will have to do more investigation.

FWIW, my docker info is as follows - it all seems to match yours.

```
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:25 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by rfay** [comment]
Glad it's working!
