### ISSUE TITLE
Next Windows Installer

### ISSUE THREAD

**Issue by gilbertsoft** [drud/ddev#2095]
Task List for the next Windows Installer. Open issue see https://github.com/drud/ddev/issues?q=is%3Aissue+is%3Aopen+label%3Awindows-installer

- [ ] Issue #
- [ ] Issue #
- [ ] Issue #

**Comment by rfay** [comment]
This isn't currently a useful issue, we can reopen when needed. I certainly want a better Windows installer based on a newer framework and possibly doing the WSL2 install work for us.
