### ISSUE TITLE
Latest version of Magerun2 doesn't support PHP below version 7.2.0

### ISSUE THREAD

**Issue by paulvandermeijs** [drud/ddev#2097]
**Describe the bug**
Ddev comes with the latest version of Magerun2 but this version only supports PHP versions 7.2.0 and above. If a lower version is used in the web container this results in an error when magerun2 is called.

**To Reproduce**
1. Create a new project with `ddev config`
2. Change `php_version` to `"7.1"` in `config.yaml`
3. Run the project with `ddev start`
4. Log in to the container with `ddev ssh`
5. Run `magerun2`
6. An error is shown with the following message: `ErrorException: PHP Version is lower than 7.2.0. Please upgrade your runtime.`

**Expected behavior**
Magerun2 should run.

**Comment by paulvandermeijs** [comment]
Maybe a solution could be to have multiple versions of magerun2 installed in the container and then symlink a version based on a config setting but I wouldn't exactly know the right way to implement this.

**Comment by rfay** [comment]
Doesn't magento2 require PHP 7.2?

**Comment by rfay** [comment]
I don't see a reason to support magento 2 or its tools with php versions below the current supported PHP version in that CMS, so closing.
