### ISSUE TITLE
Introduce variables per container (service)

### ISSUE THREAD

**Issue by rthideaway** [drud/ddev#2105]
**Is your feature request related to a problem? Please describe.**
We recently introduced redis container, but we are not able to clear the caches via local drush commands as we cannot recognize the host and port of redis container, thus we cannot reach it.

**Describe the solution you'd like**
Ddev always regenerates `settings.ddev.php` file on `ddev start` with actual port of webserver container. Please include also ports of other services, so it looks like this:
```
if (empty(getenv('DDEV_PHP_VERSION'))) {
  $host = "127.0.0.1";
  $port = 32784;
  $solr_port = 32788;
  $redis_port = 32786;
} 
```

This way we can cover both cases, with config like this:
```
$settings['redis.connection']['host'] = isset($redis_port) ? '127.0.0.1' : 'redis';
$settings['redis.connection']['port'] = $redis_port ?? '6379';
```

When local drush command is executed then the host is `127.0.0.1` with a port `32786`. When called via `ddev exec drush` (or ddev webserver) the server name is `redis` (recognized as part of ddev network) and default port 6379.

Variable name could be derived from service name, or from the name of partial docker compose file like `docker-compose.redis.yaml`. We could even mark the specific service with label and introduce variables only for services marked with specific labels, eg `com.ddev.expose-variabl: true`

**Describe alternatives you've considered**
None alternative so far

**Additional context**
None

**Comment by rfay** [comment]
The current design of ddev doesn't actually know anything about what you might add as additional services like redis. And the way you might do it is free-form. However, you have complete control of all that in your docker-compose.yaml. You can absolutely add environment variables to your docker-compose.redis.yaml if that helps, many people do that. 

I should point out that you don't have to let ddev do the settings.ddev.php modification, you can manage all that yourself if you use `disable_settings_management: true` (new in v1.13).

**Comment by rthideaway** [comment]
I understand the model, that's why this is a feature request :) I like the fact that services hav a new ports everytime ddev starts and I like how it's solved for webserver container so it's reached locally. But we would need the same for redis. So the same way this is created:
```
if (empty(getenv('DDEV_PHP_VERSION'))) {
  $host = "127.0.0.1";
  $port = 32784;
} 
```

Just by enriched with a new variables of other services in ddev network

**Comment by rfay** [comment]
One other alternative to mention: In what's probably the canonical redis config, https://stackoverflow.com/questions/51476781/can-i-have-redis-available-in-my-ddev-container/, the redis port is provided as an exposed (and standard) port via ddev-router (on port 6379). And within the container, the hostname of the project is aliased to ddev-router. That means you can access redis via http://<project>.ddev.site:6379 inside the web container if you're using that config.  This only works for services that expose an http port, as the routing is done based on the host header.

**Comment by rthideaway** [comment]
Accessing redis from web container is not a problem. Since they are all on `ddev_default` network and I can use hostname `redis` and default port `6379`. That works fine. The problem is accessing redis from local (host machine), for example when executing command via local drush. This does not go via webserver container, but via local host machine. In that case I want to have simple `if` in the `settings.php` so I can access redis by using `localhost` (127.0.0.1) and exposed port to redis container. But I don't know the port of the container as it changes over time. That's why I thought that ddev could just set this port to variable the same way as it already does for webserver container

**Comment by rthideaway** [comment]
I can achieve what we need by using post-hook:
```
hooks:
  post-start:
  - exec-host: ./backend/scripts/set-ports.sh
```

where `set-ports.sh` content is:
```
#!/bin/bash

# Set ports for particular containers (services) so they are reachable from local

set -e

CWD=$(dirname $0)

REDIS_PORT=$(docker inspect ddev-nameotheprojectinddevconf-redis --format '{{ (index (index .NetworkSettings.Ports "6379/tcp") 0).HostPort }}')

cat <<EOT > ${CWD}/web/sites/default/ddev-ports.settings.php
<?php

// If DDEV_PHP_VERSION is not set, it means we're running on the host,
// so use the host-side bind port on docker IP to access certain services
// (eg redis).
if (empty(getenv('DDEV_PHP_VERSION'))) {
  \$redis_port = ${REDIS_PORT};
}
EOT


```

This creates partial settings file `ddev-ports.settings.php` which contains actual redis port in a variable. And then our settings file will just need to use it:
```
// Redis config.
if (file_exists(__DIR__ . '/ddev-ports.settings.php')) {
  require __DIR__ . '/ddev-ports.settings.php';
}

$settings['redis.connection']['interface'] = 'PhpRedis';
$settings['redis.connection']['instance'] = 'jobiqo8';
$settings['redis.connection']['host'] = isset($redis_port) ? '127.0.0.1' : 'redis';
$settings['redis.connection']['port'] = $redis_port ?? '6379';
$settings['cache']['default'] = 'cache.backend.redis';
```

That already works, but be more happy, if ddev provides ports of services already so I don't need to hack it myself.

**Comment by rfay** [comment]
As I was saying [above](https://github.com/drud/ddev/issues/2105#issuecomment-595222642) the canonical redis configuration provides redis available from the host (but you have to use the URL).  You can't use "localhost", but you *can* use "http://<project>.ddev.site:6379". Have you tried that? I"m sure you can get drush to do that for you...
