### ISSUE TITLE
Pantheon integration problems in 1.13.1, fixed with re-authorization

### ISSUE THREAD

**Issue by andy-blum** [drud/ddev#2108]
**Describe the bug**
After updating to ddev 1.13.1 this morning I'm unable to successfully run `ddev config pantheon` on projects

**To Reproduce**
1. `ddev poweroff`
2. `brew update && brew upgrade`
3. `ddev config pantheon`

**Screenshots**
<img width="1089" alt="Screen Shot 2020-03-10 at 9 45 31 AM" src="https://user-images.githubusercontent.com/25532785/76319412-9369ab80-62b5-11ea-9af4-5a1a4ce424ac.png">
<img width="1075" alt="Screen Shot 2020-03-10 at 9 41 32 AM" src="https://user-images.githubusercontent.com/25532785/76319421-95336f00-62b5-11ea-86fd-0504bab868d7.png">

**Version and configuration information (please complete the following information):**
 - macOS 10.15.3
 - Docker 19.03.5
 - ddev 1.13.1 (previously 1.13.0)
 - project default config.yml
 - no custom configurations

**Additional context**
- pantheon config in `~/.ddev/` was in tact, but re-authorizing seems to have fixed it.
- wasn't sure an issue was appropriate, but pantheon auth wasn't mentioned in the release notes and figured I ought to make sure you're aware of the problem

**Comment by rfay** [comment]
`ddev auth pantheon` is required, was mentioned in the v1.3.0 release notes, https://github.com/drud/ddev/releases/tag/v1.13.0, "Key Features".  "Pantheon integration has been completely redone. 1) The "auth" command is now ddev auth pantheon instead of ddev auth-pantheon. Everything else works the same, but you'll need to re-authenticate with pantheon, and use ddev config pantheon to set up"

**Comment by rfay** [comment]
And BTW, THANKS! We always appreciate you taking the time to make an issue like this, even if it might end up being a communication issue one way or another.

**Comment by andy-blum** [comment]
So moving forward in every version will require re-authorization? I had 1.13.0 working fine, but broke on the 1.13.1 update.

**Comment by rfay** [comment]
No, upgrading does not require re-authorization. The auth stuff is saved in the ddev-global-cache volume. There were no changes of any kind in this area for v1.13.1.

**Comment by andy-blum** [comment]
That's what occurred in this issue, though. I went from 1.13.0 to 1.13.1 and had issues with pantheon.

**Comment by rfay** [comment]
Your screenshots show you using terminus on the host. I guess that's to demonstrate what's out there on Pantheon? If you're able to demonstrate the issue again (I doubt it) it would be better to show terminus usage inside the container and show the terminus config.

I don't know of any reason for losing your terminus auth going from 1.3.0 to 1.3.1, unless some docker volumes were deleted.

**Comment by rfay** [comment]
I tested this as well as I know how and am unable to recreate your situation. If you have additional configuration or a one-off thing you did (or especially if you deleted volumes) please let me know how I can test better. Given the following sequence it behaves perfectly through an upgrade:

`brew switch ddev 1.13.0`

`ddev start`

`ddev ssh`

`terminus self:clear-cache`

(`ddev config pantheon` results in failure "terminus env:list --field=id ' failed")

`ddev auth pantheon <token>`

`ddev config pantheon` (succeeds)

`ddev poweroff`

`brew switch ddev 1.13.1`

`ddev config pantheon` (succeeds)

**Comment by mark-casias** [comment]
since updating to 1.13.1 I have been continually getting the following on all my projects. I tried re-authorizing and that failed as well.

`Pull failed: unable to get Pantheon environments for project  - does the ddev project name match the pantheon project name? ('terminus env:list --field=id ' failed) `

**Comment by mark-casias** [comment]
Update: I did not run `ddev config pantheon` after upgrading, and once I did that, I was able to pull properly.

**Comment by andy-blum** [comment]
@mark-casias were you also updating to 1.13.1 from 1.13.0?

**Comment by mark-casias** [comment]
Correct

**Comment by rfay** [comment]
If either of you are able to point out what might have been different between your situation and the recreation scenario in https://github.com/drud/ddev/issues/2108#issuecomment-597343839 I'd love to hear it, thanks. I haven't been able to recreate this. Of course if people did *not* `ddev auth pantheon` between v1.12 (0r earlier) and v1.13+, they absolutely have to `ddev auth pantheon` when arriving at the first v1.13+ version, because it's an entirely new architecture and command.

**Comment by andy-blum** [comment]
A new wrinkle to this - I just had issues with pantheon again, without changing the ddev api. Again, running `ddev auth pantheon` fixed it, but I just used the machine token that was already stored in `~/.ddev/pantheonconfig.json`

Another interesting sidenote is that the `expires_at` value is from 2 months ago, even after re-authorizing

**Comment by rfay** [comment]
~/.ddev/pantheonconfig.json is no longer used. It's there from older versions of ddev. You can safely delete it. But your token in there is apparently the same as you've always used. You can keep it around if that's a handy place to remember your token.

Note that if you factory-reset Docker or delete the ddev-global-cache volume you'll lose the volume where the pantheon token is stored (ddev-global-cache), and that will cause you to have to re-authenticate.

**Comment by rfay** [comment]
I'll be interested in your results on upgrade to v1.14.0, thanks.

**Comment by andy-blum** [comment]
No issues that I've noticed so far through the release candidates or 1.14.0

**Comment by mark-casias** [comment]
I was able to update to 1.14.0 and connect to my pantheon repos. I think this can be closed.

**Comment by rfay** [comment]
I'll close it, but I never understood what was happening. So we'll reopen if the troubles come back. All I can think of is some docker incident that deleted the ddev-global-cache volume.
