### ISSUE TITLE
Pipe custom web container commands through dos2unix before executing

### ISSUE THREAD

**Issue by mieserfettsack** [drud/ddev#2111]
**Use case**
User clones a repository to his machine. When the user executes a custom ddev command there is no guarantee that this command will work due CRLF or CR problematic. In "normal" environments the file which has LF line endings will work as expected.

**Example custom ddev command located here: .ddev/commands/web/rmrf**

```
#!/bin/bash

echo "Read mail really fast"
rm -Rf /
```

Lately I have to deal with people working on Windows and reporting the following errors, when spawning an environment using custom scripts, that works for everyone else.

**Error that occurs when the file has CRLF**

```
$ ddev rmrf
bash: /mnt/ddev_config/commands/web/rmrf: /bin/bash^M: bad interpreter: No such file or directory
Failed to run rmrf : exit status 126
```

**Error that occurs when the file has CR**

```
$ ddev rmrf
echo: bad interpreter: No such file or directory /bin/bash
Failed to run rmrf: exit status 126
```

**The problem**
Since we can not be sure, that those workers can setup there git correctly we must deal with the problematic, that files will have CRLF or something else after clone. We told them to use tools like dos2unix or setup there IDEs "correctly". But this leads to stupid problems like commits of the custom command because of line break change and extra communications.

**Solution?**

Maybe you could pipe the content of the custom command through dos2unix, sed or something similar to make sure that every custom command will be executed with LF without touching file.

**Comment by rfay** [comment]
It's worth a thought. I've certainly run into that. I think the docs even warn against it. It's true of all custom commands or scripts or Dockerfiles or files added to Dockerfiles as well.

**Comment by rfay** [comment]
Related: Add .gitignore to .ddev/commands: #2126

**Comment by mieserfettsack** [comment]
I know about .gitattributes. Users are still able to download repository via zip from gitlab for exmaple or .gitattributes can be overwritten or ingored by some fancy git client.

**Comment by rfay** [comment]
Understood, just cross-linking. 

Since you seem to have had some pain on this, I'd appreciate suggestions you might have on how to improve the Windows section on Custom Commands, https://ddev.readthedocs.io/en/stable/users/extend/custom-commands/#known-windows-os-issues

**Comment by rfay** [comment]
https://github.com/drud/ddev/pull/2236 takes some remedial action on this, refusing to execute custom commands with CR in them, and warning the user, so going to call that good for now, closing this.
