### ISSUE TITLE
gzip database snapshots for smaller filesystem usage

### ISSUE THREAD

**Issue by rogerrogers** [drud/ddev#2114]
The snapshot feature is really nice, but it generates huge database files. The same db can be exported at 1% of the size. Wondering if there is a more efficient way this can be done, or possibly compress the exported files? As it is, the snapshots take up storage space quickly.

**Comment by rfay** [comment]
Agreed on the size. I don't think there's anything to be done about it though, it's essentially a binary copy of the entire /var/lib/mysql directory, saved by mysqlbackup.  The answer is to use `ddev export-db` if you can't afford the space.

Here's the output of a size check of a simple Drupal8 installation:
```
$ du -sh * | sort -h
4.0K	backup-my.cnf
4.0K	db_mariadb_version.txt
4.0K	ib_buffer_pool
4.0K	xtrabackup_binlog_info
4.0K	xtrabackup_checkpoints
4.0K	xtrabackup_info
4.0K	xtrabackup_logfile
668K	sys
1.0M	performance_schema
 24M	mysql
 70M	db
 76M	ibdata1
```

So 24M (14%) for the mysql database (admin), 70M (41%) for the "db" database (the application), and 76M (44%) for ibdata1 (the basic temporary storage mysqld uses)

These do seem like large numbers. The db database here, exported as plain text, is only 6M. However, they're the exact same numbers of the db container's /var/lib/db (this one is running mysql 5.7)

@jeffsheltren do you have any suggestions about generally getting mysql/mariadb to use smaller files?

**Comment by rogerrogers** [comment]
For me, if I just compress the entire snapshot it goes from 231Mb to 8Mb for this particular db, I could do nearly 30 snapshots for the price of one if we just compressed. So, ideal solution would be to automatically compress/decompress when creating/restoring snapshots.

I realize this brings a new dependency. I suppose I'm actually just putting a request out there to make the snapshot feature a bit more sophisticated. It would also be super helpful to have a way to list all snapshots directly from terminal to make recovery easier than looking in the file system.

Loving ddev, thanks for all the work everyone has put into this project.

**Comment by rfay** [comment]
gzipping the snapshot is a totally reasonable idea. I think it would work. Good thinking!

**Comment by WarpedOne** [comment]
Could be an optional DDEV config that defaults to the old way of uncompressed, but has the option to compress it. Possibly as an additional final step. Although it might be better to create the output compressed instead of the additional compression step on systems with limited space.

**Comment by rfay** [comment]
Seems to me you'd always want it compressed if you took the time to build that capability... ???

**Comment by shaal** [comment]
+1 for this feature, it would be great for cloud environments such as Gitpod.

**Comment by rfay** [comment]
@longwave points out https://mariadb.com/kb/en/using-encryption-and-compression-tools-with-mariabackup/#compressing-and-decompressing-backup-with-gzip - mariadbackup has a native way to do this.

It's possible it doesn't work for xtrabackup though.
