### ISSUE TITLE
Make APIVersion be the API version, and not ddev's version

### ISSUE THREAD

**Issue by jcnventura** [drud/ddev#2116]
**Is your feature request related to a problem? Please describe.**
When we config a project, ddev introduces a 'APIVersion' line in the config.yaml file that is used to track the version of ddev in which the project was created.

However, in practice this is being used by ddev to constantly pester the user about the config having been generated in a new version of ddev, if a developer uses a slightly older version.

For instance, it seems that there's virtually no difference between ddev 1.13.0 and 1.13.1. However, if I create a project while using 1.13.1, a colleague that uses 1.13.0 will see a warning.

In most of our projects, the only file we commit inside the .ddev folder is the config.yaml, so in effect this is only tracking the version of the __config file__ schema.

**Describe the solution you'd like**
I'd like to see a solution where in projects that don't have special needs, developer will not be pestered about updating to the latest version. In theory, the tool could from time to time 'call home' and warn the user that a new version is available. But this too should be possible to disable somehow, if you really want to stay in version 1.12.2.

**Describe alternatives you've considered**
If somehow the version is that important, can this maybe be moved to a new git-ignored file, or to an annotation in docker-compose.yaml?

**Additional context**
Maybe also think about removing all the commented-out section that is inserted at the end of the config.yaml file, and simply provide a link the file in github.com (i.e. https://github.com/drud/ddev/blob/v1.13.1/pkg/ddevapp/templates.go#L189). Running ddev config on an existing project changes the comments on this file, requiring some attention during the PR review, that could simply be ignored.

**Comment by rfay** [comment]
It's a good point. If we're going to use the APIVersion at all (It's never been used for anything except pestering, despite original intents to do so) then we should version the config file type.

**Comment by jcnventura** [comment]
Thanks a lot for this!

**Comment by rfay** [comment]
I was so glad you pointed out how silly it was. Since we've never ever ended up using it, it just made sense to make it go away.
