### ISSUE TITLE
Rework host.docker.internal handling on Linux (upcoming Docker 20.04)

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2117]
**Describe the bug**

Docker has finally made progress in providing the "host.docker.internal" hostname on the Linux side. We've long had a workaround for that, but it will be nice when they finally get it fully in there to use the actual supported approach. 

Docker 20.04 is supposed to have this feature. 

* The longstanding issue: https://github.com/moby/moby/pull/40007#issuecomment-578729356
* The (merged) PR summary: https://github.com/moby/moby/pull/40007#issuecomment-578729356

This will require extra_hosts to be populated in docker-compose.yaml, hopefully they'll support that properly.

The `docker run` technique is `docker run --add-host host.docker.internal:host-gateway`

It's not clear whether docker-compose will be updated to handle "host-gateway" immedidiately

**Comment by bluemix** [comment]
I hope there are updates :]

**Comment by rfay** [comment]
@bluemix what problem are you trying to solve?

**Comment by bluemix** [comment]
I was using `host.docker.internal` for Mac.
Today, I deployed on Linux, and is `host.docker.internal` unknown.
Then, I saw it needs Docker 20.04 for Linux to work, and I asked if there are updates on
when 20.04 will land :)

I solved the above issue by using:
```
    extra_hosts:
      - "host.docker.internal:<docker-ip>"
```
for docker-compose.yam files on Linux.

**Comment by rfay** [comment]
You don't have to do that on ddev linux. ddev explicitly defines host.docker.internal on Linux.

**Comment by rfay** [comment]
On linux, inside the container, you will already see 

`extra_hosts: [ "host.docker.internal:172.17.0.1" ]` or similar inside docker-compose.yaml

But if you have further concerns with this, could you open another issue or use another support mechanism? This is about reworking ddev when the next version of linux docker comes out.

**Comment by bluemix** [comment]
I am on the wrong page here.
very sorry.
thought this repo is about _Docker Dev_, because I was doing things quickly and didn't read the repo.
sorry again for any inconveniences.
thanks for your reply and time.

**Comment by damianobarbati** [comment]
@rfay I've been using docker for 3 years by now. 
A very annoying part is the different behaviour on macos and linux when it comes to `host.docker.internal`.
You need to resolve to the host but you have different behaviours on OS so you can't just throw the extra host `host.docker.internal:172.17.0.1` in `docker-compose.yml` (or `docker run`).

**Comment by rfay** [comment]
@damianobarbati ddev has had a workaround to add host.docker.internal on Linux containers for 2-3 years, not sure. This issue is about being able to *remove* the workaround, because the Docker folks are making progress with allowing its addition in the Linux containers.

**Comment by damianobarbati** [comment]
@rfay that's good news and that's why I'm keeping up to date in this thread :)

But `--add-host host.docker.internal:host-gateway` will work no-matter-what on both macos and linux? 
Any gotchas?

**Comment by rfay** [comment]
Closing this in favor of https://github.com/drud/ddev/issues/2904
