### ISSUE TITLE
First ddev start after a performance optimization returned, ERROR: failed to save CA key: open /mnt/ddev-global-cache/mkcert/rootCA-key.pem: permission denied

### ISSUE THREAD

**Issue by rpkoller** [drud/ddev#2121]
**Describe the bug**
Per default the file sharing resources in Docker for Mac are 
`/Users`
`/Volumes`
`/private`
`/tmp`
Since Docker is monitoring all binded paths the amount of files monitored and changing is exorbitant. I've tried altering the path list down to `~/Sites` a few months ago but back then DDEV failed to start. Remembered one episode on Talking Drupal a while ago there they recommended also adding the hidden settings folder in the user directory for Lando in their case. So I gave it another try (since the fans of my computer were on heavy rotation even more than normal the whole day which was no fun at all). It actually worked adding `~/.ddev` alongside `~/Sites`. So I applied `ddev config` as well as `ddev start` which pulled all the necessary containers. But in the end it exited and failed with: 

![Bildschirmfoto 2020-03-22 um 03 11 09](https://user-images.githubusercontent.com/1665422/77240830-d9463e00-6bea-11ea-85a2-9469f493bec0.png)

Afterwards I've just activated the NFS mount and did a `ddev start` again and it is working now. I was able to set up a site with the Umami profile. But thought I provide the mentioned error log never the less. Maybe I just have to extend the list of binded paths? maybe `~/.ssh` ? 
 
**To Reproduce**
1. Remove  `/Users`  `/Volumes`  `/private`   `/tmp` in Docker Desktop Preferences in Resources/File-Sharing
2. Add `~/Sites` `~/.ddev` instead
3. `composer -n --prefer-dist create-project drupal/recommended-project:^8 ddevtest` in `~/Sites`
4. `cd ~/Sites`
5. `ddev config`
6. `ddev start`

**Expected behavior**
I would have expected that the web server properly starts. 

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: `MBP early 2011 8GB RAM & SSD with macOS High Sierra 10.13.6.
 - Docker version information (use `docker version`) and insert it here.
```
$> docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
 - ddev version information (use `ddev version`)
```
$> ddev version
DDEV-Local version	v1.13.1
commit            	v1.13.1
db                	drud/ddev-dbserver-mariadb-10.2:v1.13.0
dba               	phpmyadmin/phpmyadmin:5
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.13.0
docker            	19.03.8
docker-compose    	1.25.4
os                	darwin
router            	drud/ddev-router:v1.13.0
web               	drud/ddev-webserver:v1.13.1
```
- config.yaml contents for the misbehaving project
```
APIVersion: v1.13.1
name: ddevtest
type: drupal8
docroot: web
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
nfs_mount_enabled: true
provider: default
use_dns_when_possible: true
timezone: ""
```
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

**Additional context**
The error log:

```
$> ddev logs -s web
+ set -o errexit nounset pipefail
+ rm -f /tmp/healthy
+ DDEV_PHP_VERSION=7.3
+ DDEV_WEBSERVER_TYPE=nginx-fpm
+ '[' -n web ']'
+ export WEBSERVER_DOCROOT=/var/www/html/web
+ WEBSERVER_DOCROOT=/var/www/html/web
+ export NGINX_DOCROOT=/var/www/html/web
+ NGINX_DOCROOT=/var/www/html/web
+ '[' -f /mnt/ddev_config/nginx-site.conf ']'
+ '[' -f /mnt/ddev_config/apache/apache-site.conf ']'
+ '[' -n 7.3 ']'
+ update-alternatives --set php /usr/bin/php7.3
+ ln -sf /usr/sbin/php-fpm7.3 /usr/sbin/php-fpm
+ export PHP_INI=/etc/php/7.3/fpm/php.ini
+ PHP_INI=/etc/php/7.3/fpm/php.ini
+ '[' '!' -z ']'
+ '[' -d /mnt/ddev_config/php ']'
+ '[' drupal8 = backdrop ']'
+ rm -f /etc/nginx/nginx-site.conf
+ '[' -f /etc/nginx/nginx-site-drupal8.conf ']'
+ ln -s /etc/nginx/nginx-site-drupal8.conf /etc/nginx/nginx-site.conf
+ rm -f /etc/apache2/apache-site.conf
+ '[' -f /etc/apache2/ddev_apache-drupal8.conf ']'
+ ln -s -f /etc/apache2/apache-site-default.conf /etc/apache2/apache-site.conf
+ envsubst '$WEBSERVER_DOCROOT,$NGINX_DOCROOT'
+ envsubst '$WEBSERVER_DOCROOT'
++ id -un
++ id -gn
+ printf '\nexport APACHE_RUN_USER=myuser\nexport APACHE_RUN_GROUP=myuser\n'
+ a2enmod access_compat alias auth_basic authn_core authn_file authz_core authz_host authz_user autoindex deflate dir env filter mime mpm_prefork negotiation reqtimeout rewrite setenvif status
Considering dependency authn_core for access_compat:
Module authn_core already enabled
Module access_compat already enabled
Module alias already enabled
Considering dependency authn_core for auth_basic:
Module authn_core already enabled
Module auth_basic already enabled
Module authn_core already enabled
Module authn_file already enabled
Module authz_core already enabled
Considering dependency authz_core for authz_host:
Module authz_core already enabled
Module authz_host already enabled
Considering dependency authz_core for authz_user:
Module authz_core already enabled
Module authz_user already enabled
Module autoindex already enabled
Considering dependency filter for deflate:
Module filter already enabled
Module deflate already enabled
Module dir already enabled
Module env already enabled
Module filter already enabled
Module mime already enabled
Considering conflict mpm_event for mpm_prefork:
Considering conflict mpm_worker for mpm_prefork:
Module mpm_prefork already enabled
Module negotiation already enabled
Module reqtimeout already enabled
Enabling module rewrite.
Module setenvif already enabled
Module status already enabled
To activate the new configuration, you need to run:
  service apache2 restart
+ a2enconf charset localized-error-pages other-vhosts-access-log security serve-cgi-bin
Conf charset already enabled
Conf localized-error-pages already enabled
Conf other-vhosts-access-log already enabled
Conf security already enabled
Conf serve-cgi-bin already enabled
+ '[' nginx-fpm = apache-cgi ']'
+ '[' nginx-fpm = apache-fpm ']'
+ '[' false '!=' true ']'
+ disable_xdebug
Disabled xdebug
+ ls /var/www/html
+ sudo mkdir -p /mnt/ddev-global-cache/terminus/cache
+ sudo cp -r /home/.ssh /home/.ssh-agent /home/.drush /home/.gitconfig /home/.my.cnf /home/myuser/
+ sudo mkdir -p /mnt/ddev-global-cache/bashhistory/ddevtest-web
++ id -u
++ id -g
+ sudo chown -R 501:20 /mnt/ddev-global-cache/ /home/myuser/.ssh /home/myuser/.ssh-agent /home/myuser/.drush /home/myuser/.gitconfig /home/myuser/.my.cnf
+ '[' -d /mnt/ddev_config/homeadditions ']'
+ cp -r /mnt/ddev_config/homeadditions/. /home/myuser/
+ sudo mkdir -p /mnt/ddev-global-cache/mkcert
+ sudo chmod -R ugo+rw /mnt/ddev-global-cache/mkcert
+ mkcert -install
ERROR: failed to save CA key: open /mnt/ddev-global-cache/mkcert/rootCA-key.pem: permission denied
```

**Comment by rfay** [comment]
The key to the last is `ERROR: failed to save CA key: open /mnt/ddev-global-cache/mkcert/rootCA-key.pem: permission denied` - I'm pretty sure you have somehow used "sudo" with `mkcert -install`. 

You can see if that's what happened, the files are in the directory named by `mkcert -CAROOT`. If that directory of the files are owned by root, then that's what it is.  Even if not, the files in the ddev-global-cache are owned by root. You can see those when you `ddev ssh` by `ls -l /mnt/ddev-global-cache/mkcert` and we'll get rid of them by killing off the docker volume. 

```
ddev poweroff
mkcert -uninstall
# If it fails, use sudo 
rm -r "$(mkcert -CAROOT)"
# if it fails, use sudo
docker volume rm ddev-global-cache
```

**Comment by rpkoller** [comment]
hmmmm the odd part. I forgot to mention when changing the filesharing ressources I've removed all containers, images and volumes before. so if fixing the issue like described would be as last resort removing the `ddev-global-cache` volume that was removed beforehand the error happened. 

and i've checked the `mkcert` folder like you suggested now. ssh'ed into the container and it is owned by my user account and not `root`. `ddev start`and everything else basically still just works flawlessly with the new smaller binding footprint of filesharing ressoures. it seems it was just a "hickup" on the first start. but no idea how that could happen taking into consideration that that the ownership is properly set as expected. :/

**Comment by rfay** [comment]
So you're good now?

**Comment by rpkoller** [comment]
yep it seem so everything is working properly with the lesser bindings. but as i said just wanted to inform you about the potential issue. maybe that hickup might turn up for others as well. but on my side it seems stable now again. and a little lesse fan spinning it seems as well.

**Comment by rfay** [comment]
I don't understand "lesser bindings". Can you explain what you mean?

**Comment by rfay** [comment]
Feel free to come into Drupal slack #ddev or any of the other [support channels](https://ddev.readthedocs.io/en/stable/#support-and-user-contributed-documentation) or just ping me in the midcamp slack if that's easier.

**Comment by rpkoller** [comment]
Guess two screenshots explain it more easily... I've changed from the default settings: 
![Bildschirmfoto 2020-03-22 um 16 31 55](https://user-images.githubusercontent.com/1665422/77253493-f0247900-6c5a-11ea-8d89-0edfaf000b9a.png)
to those: 
![Bildschirmfoto 2020-03-22 um 16 32 02](https://user-images.githubusercontent.com/1665422/77253496-f74b8700-6c5a-11ea-9bb5-21750b6258bb.png)
so Docker has less files to monitor and only the ones relevant to the containers i use.

**Comment by rfay** [comment]
There's nothing wrong with the default shares. I recommend them, very few people ever change them on macOS. They do no harm. But glad it's working for you. People often need /tmp, etc.

Also, you've moved to NFS, so ~/.ddev/nfs_exports.txt controls more of this...

**Comment by rpkoller** [comment]
hm due to the fact that i only have an old 2 core less capable computer with only 8 GB of ram and running on MacOS the shares were one point recommended repeatedly on the docker side github issue tracker, as well its documentation and also in podcasts and blogs i've searched. therefor i tried to give it a spin and it got at least a little better so far. have to test tonight a bit more intensive. 

but aside that i am using nfs but there is not nfs_export.txt in my global ddev folder?

![Bildschirmfoto 2020-03-22 um 16 52 04](https://user-images.githubusercontent.com/1665422/77253864-a8ebb780-6c5d-11ea-9032-67d663409ed4.png)

should be one there?

**Comment by rfay** [comment]
Sorry, I got confused. You're on mac, so /etc/exports is where most of the sharing happens.

**Comment by rfay** [comment]
Interesting about the limiting of docker shares being recommended to you. I'd doubt that, but glad it worked for you!

**Comment by rpkoller** [comment]
hm i suppose you were right... brought not that much of an improvement as i hoped... i got it working in contrast to my previous effort a few months ago but the benefits are more or less marginal and to some degree imaginary... reverted back to standard settings for the filesharing ressources... i suppose i either need a new mac or i get a second linux box for the work with docker... but in the current setup it doesnt make much of sense it seems :/

**Comment by rfay** [comment]
Yes, as far as I understand the "shares" in Docker are about *permissions*, not about listening. You're giving docker *permission* to access those areas. I would have guessed that the articles you were reading suggested to minimize the size of the directory actually *mounted*, which does in fact limit how much docker has to listen to (and is also the reason that huge projects tend to be slower).

I'm impressed with your successful use of a 2011 MBP, and think it's great you've used it all these years. You probably will like a new one though. The ones about to come out have decent keyboard. The new Macbook Air already has the good keyboard.

**Comment by rfay** [comment]
It sounds to me like this is sorted out, so closing, glad it's working for you. Happy to continue the conversation here or elsewhere.
