### ISSUE TITLE
Pantheon config dir differs from ddev config dir

### ISSUE THREAD

**Issue by CoreyWycliffe** [drud/ddev#2122]
**Describe the bug**
If you are developing for Pantheon and locally with ddev and you happen to exclude the settings.pantheon.php file your config directory will be different in both environments.

Pantheon uses `$settings['config_sync_directory'] = 'sites/default/config';`
ddev uses `$settings['config_sync_directory'] = 'sites/default/files/sync';`

How I discovered this was that I had to turn off Redis for my local environment and have it on for Pantheon. See - https://github.com/pantheon-systems/drops-8/issues/301#event-3147991539

**To Reproduce**
1. Create a pantheon site based on their Drupal 8 upstream - https://github.com/pantheon-systems/drops-8
2. Modify your settings.php file to only load settings.pantheon.php on a Pantheon site, see https://github.com/pantheon-systems/drops-8/issues/301#event-3147991539
3. Change the same configuration, both locally and on pantheon
4. run a `drush cex` command to see what the config difference is on pantheon and then on ddev. Are they the same? Is it different?

**Expected behavior**
There would be a way for ddev to set your own config path via `config.yaml` file

**Version and configuration information (please complete the following information):**
 - Local MacOS 10.15.3, and Pantheon hosted server
 - Docker version 19.03.5
 - ddev version v1.13.1

**Additional context**
This is a structure issue. I can't load my settings.pantheon.php file because that would break the site, but without it then ddev settings file doesn't know the shared configuration path between them.

They should both, for me, be at `sites/default/config` but not everyone will have the same path. It would be nice to specify it.

**Comment by rfay** [comment]
I don't think ddev has a way to find out where the config_sync_directory is, could be wrong. But one fix is to add `$settings['config_sync_directory'] = 'sites/default/config';` to your settings.php *after* the inclusion of settings.ddev.php

ddev's setting is just an example, of course.

**Comment by CoreyWycliffe** [comment]
I'm not sure what you meant by ddev finding out where the config directory is. But I could try the default config settings at the bottom of my settings file

**Comment by rfay** [comment]
I'm saying that ddev doesn't have a way to know how Pantheon has set the `$settings['config_sync_directory']` - sorry that was vague.

Note that you can always do a "settings.local.php" as well, and enable the include of that in settings.php (if you're using a standard settings.php)
