### ISSUE TITLE
Make phpmyadmin available on HTTPS

### ISSUE THREAD

**Issue by brace110** [drud/ddev#2124]
**Context**
To switch to Phpmyadmin I have to add a different port and change https to http to hop over. 
Just a port change should be enough. It's also cleaner / nicer to support both http and https.

**Describe the solution you'd like**
Support HTTPS for Phpmyadmin on port 8036.

**Comment by rfay** [comment]
This is easy to do, but slightly harder to do on port 8036. Not everybody uses mkcert and trusted SSL, so they'd have to click through the browser denial if they didn't have that set up.

It's *super* easy to do on a port like 8037. Then we'd just have to report the additional URL in `ddev describe`. 

Related: https://github.com/drud/ddev/pull/2102 - which wanted to add a command to launch PhpMyAdmin, a great idea, simple. That one got lost in the weeds. But can be done.

**Comment by brace110** [comment]
Port 8037 would a perfect solution as well. Please make it happen. It will make switching easier and it'll put ddev to perfection.
