### ISSUE TITLE
Update Composer on container start

### ISSUE THREAD

**Issue by gilbertsoft** [drud/ddev#2125]
**Is your feature request related to a problem? Please describe.**
The installed composer binary is not always up to date.

**Describe the solution you'd like**
This could be done during the container startup by calling composer self-update.

**Describe alternatives you've considered**
Update could also be done by the user by calling `ddev exec sudo composer self-update`.

**Comment by rfay** [comment]
I'd be interested to know why it's important to have the absolute latest composer.

Other solutions of course are:
* Self-update in post-start hook
* Self-update in .ddev/web-build/Dockerfile (which would update once, but not every time, but likely more often than updating ddev)

**Comment by gilbertsoft** [comment]
Struggled over this while running `composer diagnose` which is a normal task during development and this command complains if not the latest version is installed.

**Comment by rfay** [comment]
I do hate to do anything that makes `ddev start` slower... because it's really fast compared to lots of related tools and I'd hate for it to slow down.

**Comment by rfay** [comment]
In my environment a `composer self-update` takes 4.7 seconds if an update is required, about 2 seconds if it isn't.

**Comment by gilbertsoft** [comment]
I absolutely agree! composer is really bad in speed also for other commands and consumes so much RAM. I'll think about other solutions to achieve this...

**Comment by rfay** [comment]
I'm going to close this for now, but am happy to continue the conversation here.  I think people for whom this is really important can add a post-import exec hook to self-update.
