### ISSUE TITLE
Add .gitattributes to .ddev/commands to keep CRLF out of commands

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2126]
**Is your feature request related to a problem? Please describe.**

Windows users who create custom commands often run into a failure like this when they run the command:

```
bash: /mnt/ddev_config/commands/web/artisan: /bin/bash^M: bad interpreter: No such file or directory
Failed to run artisan : exit status 126
```

This is caused by CRLF in the custom command script, and bash never ever will accept that. 

Mostly people need to use LF only in their editor, and that's an easy way to avoid this. But we can add a .gitattributes to .ddev/commands, something like this:

```
#ddev-generated
# Make sure that all command scripts don't get CRLF in them
* -text eol=lf
```

**Comment by gilbertsoft** [comment]
Is this error already mentioned somewhere in the docs/faqs? Imho would not be bad because this error is not self explaining.

**Comment by rfay** [comment]
Yes, I think https://ddev.readthedocs.io/en/stable/users/extend/custom-commands/#known-windows-os-issues is pretty clear about these issues, happy to add more.

**Comment by gilbertsoft** [comment]
I think we should add this strange error message too. If somebody searches for the error he will hopefully land on this doc page. But I'm not sure about which parts should be added, perhaps the whole message like this `bash: /mnt/ddev_config/commands: /bin/bash^M: bad interpreter: No such file or directory`?
