### ISSUE TITLE
Install PHP gRPC pecl/PEAR extension

### ISSUE THREAD

**Issue by ldavidsp** [drud/ddev#2130]
I am using firestore in my php project the cal I use with ddev, I would like you to install the grpc extension, since I must install it manually to be able to use firestore with ddev thanks.

**Comment by rfay** [comment]
I think the solution in https://stackoverflow.com/a/60554990/215713 will work for you. That shows a pecl install of a different extension, so you just need to swap mcrypt for grpc according to https://cloud.google.com/php/grpc

AFAICT there isn't a debian package for php-grpc, so you'd need to use the Dockerfile approach.  It's easier with the packaged approach.

**Comment by rfay** [comment]
No response from OP, but the suggested solution should work. Happy to continue the conversation here or elsewhere, but closing for now.

**Comment by cmuench** [comment]
Maybe that can help: https://github.com/cmuench/grpc-demo/blob/master/examples/php/.ddev/web-build/Dockerfile
