### ISSUE TITLE
Host ssh config not copied to docker, ssh keys won't connect

### ISSUE THREAD

**Issue by damienmckenna** [drud/ddev#2132]
**Is your feature request related to a problem? Please describe.**
It is commonplace to have multiple ssh keys on a computer - different servers have different key requirements, if one is compromised it doesn't mean all accounts on all servers are compromised, etc.

The "auth ssh" command in ddev-local makes the ssh keys available to connect to other servers, but it does not copy the ssh config file so there is no connection between those ssh keys and the individual servers being connected to. As a result, some commands will fail because they do not have the appropriate ssh key assigned for the given ssh commands.

**Describe the solution you'd like**
I'd like for there to be a scenario that results in host computer's ssh config file's contents getting copied to the docker instances. I noted that the web instance has a config file already, hence suggesting the contents be copied instead of just copying the file wholesale.

**Describe alternatives you've considered**
None right now.

**Additional context**
This problem arose when using the `ddev blt` command, which passes all arguments through to the Acquia `blt` shell command.

**Comment by rfay** [comment]
You can do this by adding your .ssh/config into .ddev/homeadditions/.ssh, and it will be copied into the container on start

```
mkdir <projectroot>/.ddev/homeadditions/.ssh
cp ~/.ssh/config <projectroot>/.ddev/homeadditions/.ssh
ddev restart
```

I experimented with this by creating a .ddev/homeadditions/.ssh/config that looked like this:
```
Host <somehost>.thefays.us
 LogLevel debug
```

and after `ddev restart` a connection to the named host was done with LogLevel debug.

If you want to get fancier, you could add a pre-start hook that copied the config from ~/.ssh into .ddev/homeadditions/.ssh

**Comment by damienmckenna** [comment]
Testing through it some more, just having the config present doesn't work as the config points to specific key files that aren't available...

So what does `ddev auth ssh` actually do? I'll have to dig into the code a little.

**Comment by rfay** [comment]
`ddev auth ssh` runs an ssh-agent, it does not bring the keys into the container or copy them.

You *can* copy the keys into the container with the same strategy, just copy your whole .ssh directory into .ddev/homeadditions in a pre-start exec-host command.

**Comment by damienmckenna** [comment]
Thanks for your suggestions. I was able to solve the problem by copying the `~/.ssh` directory to `.ddev/homeadditions/.ssh` and then it worked.

**Comment by rfay** [comment]
Glad it's working!

**Comment by tobiasbaehr** [comment]
I stumbled into that trap too.

Then the command needs a better descriptions?

Also the part of https://ddev.readthedocs.io/en/stable/users/cli-usage/#ssh-into-containers and /or https://ddev.readthedocs.io/en/stable/users/extend/in-container-configuration/.

I mean starting an ssh-agent without keys in the proper place, is not really useful. :D

**Comment by rfay** [comment]
@tobiasbaehr if you could make explicit docs suggestions or a PR it would be great. There aren't any ssh agents in the world that proxy the config files; that's just not their intent, and of course config is often host-specific and usage-specific, so may not work if you blindly copy it.

**Comment by lilz-sofia** [comment]
Hi, I stumbled upon a similar problem. With the solution @rfay mentioned in his [comment](https://github.com/ddev/ddev/issues/2132#issuecomment-605513258) I am for some reason unable to fix it. When building the Dockerfile, I get the error: 
```
#27 ERROR: failed to calculate checksum of ref 20b722b6-d871-4b57-80a0-9750560477d6::wwfygfwt0ww8guqqv11qr9pm5: "~/.ssh/config": not found
```

How can I copy the config file from host to the container?

**Comment by stasadev** [comment]
Hi @lilz-sofia, can you explain in more detail what you are trying to do?

The provided solution does not involve building Dockerfiles, and this issue is very old and may not be relevant.

Maybe it's better to open a new issue and provide all the steps to reproduce?

**Comment by lilz-sofia** [comment]
@stasadev 
Hi, I'm sorry you're right it was a different issue than this. I resolved it anyways. 
Thank you~
