### ISSUE TITLE
web-build ADD do not copy

### ISSUE THREAD

**Issue by Mordef** [drud/ddev#2146]
Using .ddev/web-build/Dockerfile with:

`ADD foo.php /`

The folder .ddev/web-build/ contains a file named foo.php.
After ddev start the .ddev/.webimageBuild/Dockerfile is updated with

`ADD foo.php /`

But the start fails with:
Service web failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder.../foo.php: no such file or directory

When i copy the file to .ddev/.webimageBuild/foo.php it works

**Comment by rfay** [comment]
The feature that allows ADD was added in v1.13. What version do you have? `ddev --version`

**Comment by Mordef** [comment]
thank you, was 1.12, with 1.13 it works fine.

**Comment by rfay** [comment]
Glad it's working for you!
