### ISSUE TITLE
Remove hostnames from /etc/hosts on ddev stop, not just ddev delete

### ISSUE THREAD

**Issue by kaystrobach** [drud/ddev#2147]
**Describe the bug**

Ddev has 2 was to configure hostnames, the first one will have `<hostname>.ddev.site` the second one creates an entry in the `/etc/hosts` and so redirects all traffic to `example.com` to ddev, this works fine for creating the entry. This works fine for creating the entry.

The Problem occurs once you stop the container and now think the default behaviour is restored. It is not. The entry in the ´/etc/hosts` is kept.

This removal should also be triggered on `ddev poweroff`

```yaml
additional_hostnames:
- example.com
additional_fqdns:
- example.com
```

**To Reproduce**

* use the above yaml segment in a project and try to access example.com after shutting down ddev.

**Expected behavior**
remove entries from `/etc/hosts` once environment got stopped

**Screenshots**
-

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: OSX Catalina 10.15.4
 - Docker version information 19.03.8
 - ddev version information v1.13.1
 - config.yaml contents for the misbehaving project, see above
 - Do you have any custom configuration : yes, behaviour does not change

**Additional context**
thank you for providing ddev!

**Comment by rfay** [comment]
ddev has always removed hosts that it adds when you do a `ddev delete` or `ddev stop --remove-data`, and that has seemed to be adequate for people.  Adding the hostname on every `ddev start` and removing it on `ddev stop` seems like it would be a little annoying. 

Note that you can also `sudo ddev hostname --remove-inactive` or `sudo ddev hostname -R` to kill off any hostnames that ddev knows it created (for projects that aren't running). 

If you think ddev should manage the hosts file on start and stop, it's not unreasonable, and is a fine feature request.  

I'm sure you know one thing to avoid whenever possible is using an FQDN that masks a real internet address. It's no end of pain.

**Comment by kaystrobach** [comment]
Totally agree, thats why i mentioned bith ways of setting the hostname.

I would only set and unset the fqdns on start and stop. The others have not that kind of impact.

**Comment by rfay** [comment]
I'm hesitant to consider this "critical" since the feature has been there for 3 years and nobody has ever complained (and both the current, documented technique and your suggestion are valid)

**Comment by kaystrobach** [comment]
Fine

**Comment by rfay** [comment]
A man of few words :)

**Comment by kaystrobach** [comment]
Just as a background:

we have 2 projects, were we use oauth and saml2, debugging it's sometimes needed to use the production uri. And 2 devs had a real headache to understand why they get timeouts for the production site after starting their device after vacation ...

**Comment by rfay** [comment]
Yes, absolute disaster when shadowing a real fqdn :(

You could easily add a post-stop exec-host hook that did a `sudo ddev hostname -r <fqdn>` and you'd have this already.

**Comment by kaystrobach** [comment]
that's a nice workaround! - will add that instantly

**Comment by kaystrobach** [comment]
need to test that further, but does not seem to get removed. I will check lateron

**Comment by rfay** [comment]
I just tried this recipe in my .ddev/config.yaml, and it was fine, accomplishing what you want.

```
additional_fqdns:
- some.example.com
hooks:
  post-stop:
  - exec-host: sudo ddev hostname -r some.example.com 127.0.0.1
```

**Comment by kaystrobach** [comment]
the ip was missing, i think i will add the `fqdns` via a custom command for now, as this also reduces the risk of accidentially being in the wrong environment

**Comment by rfay** [comment]
Since this works for you, and the status quo has worked for a long time, I'm going to close this for now, but happy to continue the conversation here or elsewhere, and happy to reopen if needed.
