### ISSUE TITLE
HOST_DOCKER_INTERNAL_IP being empty in webserver container on Macs

### ISSUE THREAD

**Issue by rthideaway** [drud/ddev#2148]
**Describe the bug**
Ddev is setting `HOST_DOCKER_INTERNAL_IP` env variable for webserver container. For linux OS this is correctly set, but for Mac OS this is empty. Would be good to make it consistent for both operating systems.

**To Reproduce**
1. Make sure you're using Mac OS
2. Run ddev project
3. SSH into webserver container with `ddev ssh`
4. Check for `HOST_DOCKER_INTERNAL_IP` env variable with `env | grep HOST_DOCKER_INTERNAL_IP`
5. You'll see variable being empty:
```
HOST_DOCKER_INTERNAL_IP=
```

**Expected behavior**
Variable should be correctly set to the same IP as `host.docker.internal` host entry

**Version and configuration information (please complete the following information):**
 - macOS Catalina 10.15.2
 - Docker version 19.03.5
 - Ddev version 1.13.1
 - we have custom php config in `php/25-php-memory-limit.ini` with content:
```
[PHP]
memory_limit = 256M;
```

**Comment by rfay** [comment]
On Windows and MacOS, the host.docker.internal name is automatically set by Docker, and we don't need the environment variable. The environment variable is only generated on Linux because we have to derive this. There's also no way for ddev to know what it's going to be on macOS or Windows.

**Comment by rthideaway** [comment]
> Could you say what problem you were trying to solve?

Well we have a bit of unusual development stack with ddev containers when one of the services is running on the host machine. We were using this variable to talk to that service from ddev webserver container. But recently we found out it's not presented on Mac and was failing for one of our developers.

Anyway I think this is not important as we can use `host.docker.internal`. Seems this presented in ddev webserver container and can be used.

Thank you explanation of the problem. I think this issue can be closed.

**Comment by rfay** [comment]
Thanks, glad it's working for you!
