### ISSUE TITLE
Feature Request: Add NVM-parameter in config.yaml

### ISSUE THREAD

**Issue by truls1502** [drud/ddev#2151]
## Motivation
It is not related to a problem, but it is about to make developer and team life easier when we have the frustrating to install NVM by manually.

As we can see, there are two options today:
-  Use `Dockerfile`, but it is not sensing to use the method, especially, as teams who have different developers and not all developers have the same DDEV version. So, it is hard for the team to maintaining the ARG-part with the docker image and DDEV version.
- Install it by `post-start` with bash, but this is not friendly for the developer who is jumping over projects often since sometimes they need to do `ddev pause` then back to the project.

## Solution/suggestion
Could we add a new parameter in the `config.yaml`? If it is true, then it installs only one time with other tools such as composer, Drush etc, if not true then it doesn't install the nvm.
```
nvm: true
```

**Comment by rfay** [comment]
Just to respond... the ARG part in a Dockerfile is overridden at build time and uses the actual version of the webimage that ddev is using.  Does that solve your problem? Essentially the ARG part is irrelevant in `ARG BASE_IMAGE=drud/ddev-webserver:v1.13.1`. We should either document that or see if we can get rid of it.

**Comment by rfay** [comment]
I'm going to go ahead and close this one for now since you have a path with node and whatever you want in project Dockerfile. Happy to continue the conversation here or elsewhere, and happy to reopen this if you think it's still necessary.
