### ISSUE TITLE
Documents Windows Cert install wrong cert name

### ISSUE THREAD

**Issue by can0199** [drud/ddev#2169]
In the install tutorial on the site: https://ddev.readthedocs.io/en/stable/

there you describe how to install the cert on firefox, there you say 

import following file: rootCA-key.pem 

there have to be selected the rootCA.pem not the key file.

On the docs in your repo it is right

**Comment by rfay** [comment]
This was fixed in https://github.com/drud/ddev/pull/2153 - that's why you see it in the docs. You'll also see it in "latest" docs, https://ddev.readthedocs.io/en/latest/

**Comment by can0199** [comment]
ohh i dont see it

Thanks for the fast reply.

i wish a nice easter week
