### ISSUE TITLE
Install wkhtmltopdf (Drupal8 Entity Print)

### ISSUE THREAD

**Issue by maxplus** [drud/ddev#2176]
Hi,
I'm looking for the best way to add the command line tool wkhtmltopdf for a Drupal8 project using Entity Print.
Because I'm not a Linux expert, I read the docs and searched for adding wkhtmltopdf using webimage_extra_packages or a custom Dockerfile.

The solution is adding this to your config.yaml file: `webimage_extra_packages: ["wkhtmltopdf"]`
Then when you ssh into your container, you can see `whereis wkhtmltopdf` has as result `wkhtmltopdf: /usr/bin/wkhtmltopdf`
=> so in Drupal Entity Print you can use the path /usr/bin/wkhtmltopdf as path for wkhtmltopdf.

Might be handy for someone else ;-)

**Comment by rfay** [comment]
Thanks for sharing this!

**Comment by skeemer** [comment]
I've created an addon that grabs the wkhtmltopdf with patched Qt from the wkhtmltopdf website.
`ddev get skeemer/ddev-wkhtmltox`

This should help with various networking issues that can arise when using the distro's wkhtmltopdf.

**Comment by VadymTseiko** [comment]
Hello, I have a question about ddev with wkhtmltopdf, I face some issue when configure my local env. I added it to my config.yaml webimage_extra_packages: ["wkhtmltopdf"] as was described in the comment above. And all seems fine, but pdf files that was generated via entity_print are a bit broken(it seems that this functionality hasn't been working in sync with dev and production).  On my dev and master envs all works fine. I tried to solve this problem with ddev get skeemer/ddev-wkhtmltox but this really didn't fix it. I decided to check if it's problem with entity_print or environment or else, and when I setup local env on docksal all seems to work fine. Im preferring ddev more, and if u can give some advice how to fix problem, maybe I missed something it would be much appreciated.

**Comment by rfay** [comment]
This isn't going to be a result of anything DDEV can do; this is just a Debian package that you're installing. You can compare the version you're using (`ddev exec apt info wkhtmltopdf`) with the version you're using on docksal, maybe that will give you a hint. But the best thing would be to open an issue on https://github.com/skeemer/ddev-wkhtmltox and describe more carefully what's happening - "a bit broken" is not going to help very much. @skeemer uses it so may be able to give advice.

**Comment by VadymTseiko** [comment]
Thanks, @rfay for your reply. I'll try to figure out something, maybe there is something with wkhtmltopdf version on a different env's as you said.

**Comment by skeemer** [comment]
@VadymTseiko Make sure you removed it from the webimage_extra_packages or you'll be installing the binaries twice and feel free to follow-up over on the addon issues https://github.com/skeemer/ddev-wkhtmltox as @rfay mentioned.
