### ISSUE TITLE
Support alternate remote $DOCKER_HOST

### ISSUE THREAD

**Issue by jasonruyle** [drud/ddev#2177]
**Describe the bug**
When adding specific values to your .env in your project, it breaks DDEV.
ddev version shows:

```
DDEV-Local version      v1.13.1
commit                  v1.13.1
db                      drud/ddev-dbserver-mariadb-10.2:v1.13.0
dba                     phpmyadmin/phpmyadmin:5
ddev-ssh-agent          drud/ddev-ssh-agent:v1.13.0
docker                  failed to GetDockerVersion(): Get tcp://gitlab.companyhost.com/version: unsupported protocol scheme "tcp"
docker type             Docker Desktop For Windows
docker-compose          1.25.0-rc4
os                      windows
router                  drud/ddev-router:v1.13.0
web                     drud/ddev-webserver:v1.13.1
```

**To Reproduce**
1. Type any ddev command when project isn't started.

**Expected behavior**
It worked as expected. I modified my DOCKER_HOST.

**Version and configuration information (please complete the following information):**
Windows

**Additional context**

Adding in your projects .env file:
```
DOCKER_HOST=any value other then what ddev wants
```
I broke DDEV because I added the value of DOCKER_HOST to my .env file (wrote a script to deploy a snapshot using make for our CI/CD).

I'm wondering if you could update the Troubleshooting documents to let people know not to use the values DOCKER_HOST in their .env files or it will break things.

**Comment by rfay** [comment]
Nobody has ever pioneered the use of DOCKER_HOST before; ddev is built for local development, so the default DOCKER_HOST is all that has ever been tested. You're certainly welcome to pioneer that approach, but I don't know what the results will be.

Are you able to do regular docker commands or docker-compose commands with DOCKER_HOST set to the new value? If not, your problem is not with ddev.

**Comment by jasonruyle** [comment]
Oh, clearly I shouldn't of used DOCKER_HOST in my .env.
I was only thinking in terms of the documentation. If someone decides to do what I did, hopefully they can find this issue or see it in the Troubleshooting area.

All I did was change the value of DOCKER_HOST to GITLAB_HOST and it works. I'll close the comment.
