### ISSUE TITLE
.gitignore does not ignore new docker-compose files

### ISSUE THREAD

**Issue by Mactory** [drud/ddev#2180]
**Describe the bug**
Recently the docker-compose files were renamed `.ddev-docker-compose-{base|full}.yaml.` This naming not updated in my `.gitignore`.

**To Reproduce**
1. Start a ddev project
2. check the contents of .gitignore

**Expected behavior**
should contain 
```
/.ddev-docker-compose-base.yaml
/.ddev-docker-compose-full.yaml
```

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macOS Catalina
 - Docker version information (use `docker version`) and insert it here.
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
 - ddev version information (use `ddev version`)
```
DDEV-Local version	v1.14.0-rc1
commit            	v1.14.0-rc1
db                	drud/ddev-dbserver-mariadb-10.2:v1.13.0
dba               	phpmyadmin/phpmyadmin:5
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.13.0
docker            	19.03.8
docker-compose    	1.25.4
os                	darwin
router            	drud/ddev-router:20200411_webimage_maint
web               	drud/ddev-webserver:20200411_webimage_maint
```
 - config.yaml contents for the misbehaving project
```
name: ddev2
type: php
docroot: web
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
no_project_mount: true
additional_hostnames: []
additional_fqdns: []
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
```
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?
No, I don't

**Additional context**
Add any other context about the problem here. Thanks!

**Comment by rfay** [comment]
Great catch, thanks. I see 
```
/.docker-compose-base.yaml  
/.docker-compose-full.yaml  
``` 
in the generated .gitignore, so it looks to me like I changed the name after I got it into the gitignore.

💯 for catching this, thanks!

**Comment by rfay** [comment]
Will be fixed in #2182, and in rc2

I appreciate this that much more because I've messed this up in the past and it hasn't been caught until the release is out. THANKS!

**Comment by rfay** [comment]
@Mactory would appreciate your review of https://github.com/drud/ddev/pull/2182

**Comment by rfay** [comment]
I'd also be interested in your description of how you detected this, @Mactory . There's not currently an automated test, and it would be reasonable to do something like `ddev start`, `git add`, `ddev start` again, look for uncommitted, but I haven't quite figured out how it should work. Since I'm usually work on temporary test projects, I tend to be blind to issues like this that are not exactly functional issues but super important to teams.

**Comment by rfay** [comment]
https://github.com/drud/ddev/pull/2182#issuecomment-614796590 has outline for test

**Comment by Mactory** [comment]
I basically stumbled upon this by chance. As I said in the other PR, I was looking for a way to add the `.ddev` folder directly to our wordpress theme folder so that I can check that folder into our git repo and make it easy for all developers in the team to setup their env.

So when trying out if everything was working, I added the folder to my git repo and noticed afterwards, that the automatically generated docker-compose files were included in git.

**Comment by rfay** [comment]
I'm very pleased with the new test in #2180 - it uncovered another mistake in the gitignore; the new xdebug command was gitignored... but in the wrong directory.
