### ISSUE TITLE
Override default webserver and database containers when specifying a 3rd party provider.

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#219]
## What happened (or feature request):

* Feature request

## What you expected to happen:

When running `ddev config PROVIDER`, we need to help the end-user achieve infrastructure parity by replacing the stock container images used in the docker-compose.yml file with ones for that provider.

## Related source links or issues:

* [MVP Integration with Pantheon](https://github.com/drud/ddev/issues/216)
* [As a developer, I want integration with 3rd party providers.](https://github.com/drud/ddev/issues/122)

**Comment by rickmanelius** [comment]
* This relates to https://github.com/drud/ddev/issues/469, which might be a better issue to track this.
* This topic comes up as part of the larger discussion of hosting provider and community container support. I would like to put a flow diagram together to highlight my thinking. Moving this to incubate and then moving to a more appropriate milestone once it's actionable.

**Comment by rfay** [comment]
This is obsolete, and the issues in it can be addressed when we add another provided (probably DDEV-Live). But it's not clear that we will have separate container images, as we do not for pantheon.
