### ISSUE TITLE
ddev describe should show more information about 3rd party services

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2190]
**Describe the bug**

As of v1.14+ `ddev describe` shows some information about third-party services like solr that have an exposed URL. However, it doesn't say anything about services that don't have an http url, and it should at least list them. For example, if rabbitmq or memcached is enabled, it should at least show in the output, and perhaps inform more output.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: [e.g. Windows 10, macOS High Sierra]
 - Docker version information (use `docker version`) and insert it here.
 - ddev version information (use `ddev version`)
 - config.yaml contents for the misbehaving project
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

**Additional context**
Add any other context about the problem here. Thanks!

**Comment by jpmschuler** [comment]
Perhaps an environment variable like `DESCRIBE_TEXT` could be added. In the following example myserviceA is exposed and myserviceB is not exposed, both have that new environment variable.
Before:
```
Other Services
--------------
MailHog (https):     	https://ddev-typo3-entermediadb.ddev.site:8026
MailHog:             	http://ddev-typo3-entermediadb.ddev.site:8025
myservice A (https):	https://ddev-typo3-entermediadb.ddev.site:8090
```
After:
```
Other Services
--------------
MailHog (https):     	https://ddev-typo3-entermediadb.ddev.site:8026
MailHog:             	http://ddev-typo3-entermediadb.ddev.site:8025
myserviceA (https):	https://ddev-typo3-entermediadb.ddev.site:8090
                        a tool for lorem ipsum dolor sit amet
myserviceB:	        a logging backend which is needed by lorem ipsum dolor sit amet
```
