### ISSUE TITLE
Add an option to disable .gitignore generation

### ISSUE THREAD

**Issue by dmitryd** [drud/ddev#2191]
**Is your feature request related to a problem? Please describe.**

When I use `ddev start` in my TYPO3 project, ddev automatically adds a `.gitignore` file to my file system inside `web/typo3conf/`. I have a central `.gitignore` file where I manage everything. So I do not want any automatically generated files in my project directories. I want to keep it tidy and controlled by me, not be the software that I use.

**Describe the solution you'd like**

Please, add an option to disable generation of ANYTHING outside of .ddev directory. ddev should not add its files outside of its own directory.

**Describe alternatives you've considered**

I could add those files git `.git/info/exclude` but the files will still be there and it would be a mess. It would be better if ddev does not force unneeded files in my projects.

Thank you.

**Comment by rfay** [comment]
This already exists - `disable_settings_management: true` in your .ddev/config.yaml will prevent gitignore creation and you'll be fully in charge. More details on the many ways to manage settings files at https://ddev.com/ddev-local/controlling-cms-settings-files-in-ddev-local/

**Comment by dmitryd** [comment]
@rfay This is not the same because that setting disables absolutely every file creation, including creation of system configuration files for new projects.

In TYPO3 you always want `web/typo3conf/LocalConfiguration.php` in git but it would be prohibited by `.gitignore`. You may also want to some other files and even something inside the `ext/` subfolder. Therefore, in project we control what is available for git via central `.gitignore` in the project root. So therefore file `web/typo3conf/.gitignore` is not welcome all the time.

May be, you have an idea how it can be disabled in another way?

**Comment by dmitryd** [comment]
Though I guess I can change this setting _after_ I built the project, right? And then it should not add .gitignore anymore?

**Comment by rfay** [comment]
The only thing in the generated public/typo3conf/.gitignore is AdditionalConfiguration.php, not Localconfiguration.php. Does that relate to this? You say 

> In TYPO3 you always want web/typo3conf/LocalConfiguration.php in git but it would be prohibited by .gitignore

But I'm not sure of either of your assertions, either that you always want LocalConfiguration.php in git and it's going to be prohibited by .gitignore (not by ddev's .gitignore anyway). 

But yes, you can absolutely create the files and then turn off the setting, or create the files and then take them over by removing the #ddev-generated, as described in https://ddev.com/ddev-local/controlling-cms-settings-files-in-ddev-local/

**Comment by dmitryd** [comment]
> Does that relate to this? You say

It is because this file adds settings that are calculated from other parameters (for example, proxy settings). So this file is not necessarily should be ignored.

> But yes, you can absolutely create the files and then turn off the setting, or create the files and then take them over by removing the #ddev-generated, as described in https://ddev.com/ddev-local/controlling-cms-settings-files-in-ddev-local/

Thank you. This would be my workflow from now on. and thanks for the great product!
