### ISSUE TITLE
Update & Redesign ddev describe output (and ddev list and ddev version)

### ISSUE THREAD

**Issue by andy-blum** [drud/ddev#2195]
The `ddev describe` output is a bit cluttered and has some pieces missing now. Setting this issue up as meta/discussion to encourage community input.

Below is the current output for a drupal8 project 'example.com'

```
NAME         TYPE     LOCATION             URL                            STATUS
example.com  drupal8  ~/Sites/example.com  https://example.com.ddev.site  running

Project Information
-------------------
PHP version:      	7.3
NFS mount enabled:	true
Database type:    	mariadb
MariaDB version:  	10.2

URLs
----
https://example.com.ddev.site
https://127.0.0.1:32791
http://example.com.ddev.site
http://127.0.0.1:32792

MySQL/MariaDB Credentials
-------------------------
Username: "db", Password: "db", Default database: "db"

or use root credentials when needed: Username: "root", Password: "root"

Database hostname and port INSIDE container: db:3306
To connect to db server inside container or in project settings files:
mysql --host=db --user=db --password=db --database=db
Database hostname and port from HOST: 127.0.0.1:32790
To connect to mysql from your host machine,
mysql --host=127.0.0.1 --port=32790 --user=db --password=db --database=db

Other Services
--------------
MailHog (https):	https://example.com.ddev.site:8026
MailHog:        	http://example.com.ddev.site:8025

DDEV ROUTER STATUS: healthy
ssh-auth status: healthy
```

**Comment by andy-blum** [comment]
[My initial complaint](https://github.com/drud/ddev/issues/2174#issuecomment-615333930) is regarding the output of the database credentials. I suggest:

```
MySQL/MariaDB Credentials
-------------------------

Username (root):  root
Password (root):  root
Username:         db
Password:         db

host:port (internal):  db:3306
host:port (external): 127.0.0.1:XXXXX
```

**Comment by andy-blum** [comment]
I think another immediate improvement would be to transfer the first two lines into the same table format

```
example.com
-------------------------------------------------
Type:               drupal8
Location:           ~/Sites/example.com
URL:                https://example.com.ddev.site
Status:             Running
-------------------------------------------------
```

**Comment by andy-blum** [comment]
I think it might also be worth splitting the container/server info to sit along side other relevant information, giving us 5 main sections:

- Basic Info
- Webserver Info
- Database Info
- Services/Settings/Tools/Misc
- Global DDEV status info (I don't ever use this info and wouldn't be sad to see it gone)

```
example.com
-------------------------------------------------
Type:               drupal8
Location:           ~/Sites/example.com
URL:                https://example.com.ddev.site
Status:             Running
-------------------------------------------------


Webserver
-------------------------------------------------
Type:               nginx-fpm
PHP version:      	7.3
Docroot:            /var/html/www/web/

Aliases:            https://sample-alias.ddev.site
                    https://127.0.0.1:32791
                    http://127.0.0.1:32792
-------------------------------------------------


Database
-------------------------------------------------
Type:               mariadb v10.2

Username (root):    root
Password (root):    root
Username:           db
Password:           db

host:port (int):    db:3306
host:port (ext):    127.0.0.1:XXXXX
-------------------------------------------------


Services, Settings & Tools
-------------------------------------------------
MailHog (https):	  https://example.com.ddev.site:8026
MailHog:        	  http://example.com.ddev.site:8025
PHPMyAdmin:         [info here if enabled]
redis:              [info here if enabled]
NFS mount:	        enabled
xDebug:             enabled
-------------------------------------------------


DDEV Statuses
-------------------------------------------------
router:    healthy
ssh-auth:  healthy
-------------------------------------------------
```

**Comment by shaal** [comment]
I really like the clean design in the comment above (https://github.com/drud/ddev/issues/2195#issuecomment-615379523)
When columns are aligned, and each section has a similar structure with title above it, it makes it very clear and easy to read.

**Comment by brianyoungblood** [comment]
Maybe this is found in another discussion but I always want to type ddev status on a project. I’m fighting the urge to do a alias for describe.

**Comment by rfay** [comment]
It would be easy to add an alias, but I'm not sure that would be helpful to everybody. *You* @brianyoungblood  however can easily add a custom global host command that just does `ddev describe`. You'll like it.

**Comment by brianyoungblood** [comment]
@rfay yup exactly my urge and I’ve done other aliases as well. I was also compelled to share in hopes of this feedback. I’d rather not alias this one so quickly and just change my behavior in this case unless I had others with the urge. New format of describe looks good to me as well.

**Comment by shaal** [comment]
+1 for `ddev status` as an alias to `ddev describe`.
I would use `ddev status` because to me it's more intuitive.

**Comment by rpkoller** [comment]
haha also a +1 from me for `ddev status`. yesterday when i read this thread the first time and wanted to compare the suggested with the current state, since i use `ddev describe` rather rarely, i first typed in `ddev status` by accident ;)

**Comment by rfay** [comment]
OK, you status lovers, https://github.com/drud/ddev/pull/2955

**Comment by andrewbelcher** [comment]
I'm not much of a designer, so not sure I can give much input on that front, but one thing I would suggest considering is splitting out some of the information into a verbose mode / being able to get information about specific services. E.g.

`ddev describe`: Short, concise summary of all services
`ddev describe -v`: Full information about all services
`ddev describe db`: Full information about the database container
`ddev describe web`: Full information about the web container

I've just run `ddev describe` on my current project in the terminal of PHPStorm, which is at 60% of the height of my full HD monitor, and I have more than the terminal height of information, resulting in what is arguably the most important bits of information (URL and status) needing scrolling to see.

The _MySQL/MariaDB Credentials_ in particular are quite verbose by default. And whilst I like the readability improvements of the above suggestions, they may actually make the problem worse by making the output even taller.

**Comment by andrewbelcher** [comment]
A few resources I've seen that might be helpful for others like me who are visual design challenged:

- https://blog.developer.atlassian.com/10-design-principles-for-delightful-clis/#2c19 - perhaps using colours (or as in the example ascii characters) for headers and key info
- https://devcenter.heroku.com/articles/cli-style-guide#grep-parseable - perhaps not necessary if we allow the service to be an argument

Another thing that might be helpful is being able to add information in `config.yaml` that's project specific. Not sure if this is best at the top, bottom or both?

**Comment by andy-blum** [comment]
I like the [recommendation for an expanded set of describe modes](https://github.com/drud/ddev/issues/2195#issuecomment-823933464), though I'm not sure what I'd consider priority 1 for the 'short' version. Any suggestions there @andrewbelcher ?

**Comment by andrewbelcher** [comment]
I guess I would say the key bits of information for each service would be:

- name
- state (with colour coding preferably)
- primary or key urls (or equiv where relevant)
- maybe a short descriptive thing if relevant, version p

Fitting with the grep parseable, perhaps something along the lines of
```
Name:               example
Type:               drupal8
Location:           ~/Sites/example
URL:                https://example.ddev.site
Status:             Running
DDev router:        healthy     
ssh-auth:           healthy


| Service  | Name  | State   | URL/Port                       | Version             |
| -------- | ----- | ------- | ------------------------------ | ------------------- |
| Web      | web   | running | https://example.ddev.site      | Apache 2.4, PHP 7.3 |
| Database | db    | running | db:3306 127.0.0.1:31000        | MariaDB 10.2        |
| Solr     | solr  | error   | https://example.ddev.site:8983 | 7.5                 |
| MailHog  | -     | running | https://example.ddev.site:2026 |                     |
| Redis    | redis | running | redis:6379                     |                     |


Some configurable (but optional) descriptive text that comes from config.yaml to allow teams to set up 
helpful information for on-boarding or other common activities.
```

**Comment by andrewbelcher** [comment]
https://github.com/drud/ddev/pull/2965 is a (REALLY) rough start at some of this... Fun first foray into go and contributing to DDev - I expect tests will fail as I've not even looked at that and I have some issues that I'm not familiar enough with Go / DDev's set up to sort myself, but here's the output so far:

![image](https://user-images.githubusercontent.com/7072329/116078146-29b18a00-a68e-11eb-9918-836660e167a0.png)

![image](https://user-images.githubusercontent.com/7072329/116078343-62516380-a68e-11eb-907d-35b105196509.png)

![image](https://user-images.githubusercontent.com/7072329/116078369-6a110800-a68e-11eb-9897-3a41fbf2ab09.png)

![image](https://user-images.githubusercontent.com/7072329/116078392-72694300-a68e-11eb-8d0f-1b0b6b83e85d.png)

![image](https://user-images.githubusercontent.com/7072329/116078444-844ae600-a68e-11eb-9aab-459cbc8d6729.png)
