### ISSUE TITLE
Try to put ddev drush.yml in more than one place in filesystem

### ISSUE THREAD

**Issue by jcnventura** [drud/ddev#2196]
**Is your feature request related to a problem? Please describe.**
Since #2025 was merged , ddev tries to create the drush/drush.yml file instead of web/sites/all/drush.yml.

Because of this change, projects that already had a drush/drush.yml file no longer get a ddev-generated file with the correct site URL, and, as a result, `drush uli` returns `http://default` as ddev's base path.

**Describe the solution you'd like**
According to the [example.drush.yml](https://github.com/drush-ops/drush/blob/master/examples/example.drush.yml) (line 17), drush will try to locate the drush.yml file in 
> 2. Drupal /drush and sites/all/drush folders, or the /drush folder in the directory above the Drupal root.

Of the three locations, described above, ddev used to place the file in the second option, and now places it in the third location.

My preferred solution is that ddev first try to create the file in drush/drush.yml (current behaviour), and if that fails, attempt to create it in web/sites/all/drush.yml (previous behaviour), and only then give up with the "Failed to WriteDrushYML" error.

**Describe alternatives you've considered**
Another option would be for ddev to modify the existing drush.yml, but since that is a committed file in our case, it would mark it as modified, introducing the risk that somebody could commit it.

**Comment by rfay** [comment]
You might be a candidate for managing your own settings files. There are many ways to do that, summary in https://ddev.com/ddev-local/controlling-cms-settings-files-in-ddev-local/

**Comment by jcnventura** [comment]
We really, really would like to have ddev still create the drush.yml automatically.

**Comment by jcnventura** [comment]
Note that the previous behaviour worked fine for us with v1.12. It was only now that we started using v1.13 that my colleagues complained about the missing correct URL configuration.

One option would be for us to go back to 1.12, but then we would start to be pestered by #2116.

I believe the solution in the PR improves the `disable_settings_management: false` option, keeps the location added in #2025 as the preferred location, by taking advantage of drush's multiple lookup paths for this file.

**Comment by rfay** [comment]
Closing this in favor of #2216

**Comment by rfay** [comment]
@jcnventura and @truls1502 I hope you can test the prerelease [v1.15-alpha5](https://github.com/drud/ddev/releases/tag/v1.15-alpha5) for the DRUSH_OPTIONS_URI support while it's still in prerelease, thanks!
