### ISSUE TITLE
Docs need to quote commands that have "^" in them for people who use Windows cmd

### ISSUE THREAD

**Issue by mataski** [drud/ddev#2202]
**Describe the bug**
Can't install Drupal 8.

**To Reproduce**
Follow documentation at https://ddev.readthedocs.io/en/latest/users/cli-usage/#drupal-8-quickstart

Line: ddev composer create drupal/recommended-project:^8

**Error**
```
Executing composer command: composer create-project drupal/recommended-project:8 /var/www/html/.tmp_ddev_composer_create_wWaaNJ

Creating a "drupal/recommended-project:8" project at "./.tmp_ddev_composer_create_wWaaNJ"

  [InvalidArgumentException]
  Could not find package drupal/recommended-project with version 8.

Failed to create project:exit status 1, stderr=
```

**Version and configuration information (please complete the following information):**
win10, ddev v1.14.0-rc2, docker 19.03.8, fresh install nothing custom

**Comment by rfay** [comment]
I think you typoed the command. From https://ddev.readthedocs.io/en/latest/users/cli-usage/#drupal-8-quickstart you want 

`ddev composer create drupal/recommended-project:^8`

**Comment by mataski** [comment]
thats what i wrote

`ddev composer create drupal/recommended-project:^8`

spits out

`Executing composer command: composer create-project drupal/recommended-project:8`

**Comment by rfay** [comment]
Oh, you're using cmd on Windows maybe? "^" is a reserved character in cmd. 

We recommend using git bash, as that's what most people do and it's more predictable. 

However, I think `ddev composer create "drupal/recommended-project:^8"` might work for you and fix that. If it works for you, we'll update the docs to put the quotes in there.

**Comment by rfay** [comment]
We'll close this with the docs fix, thanks!
