### ISSUE TITLE
Takes ages to install Drupal with Composer on Windows

### ISSUE THREAD

**Issue by mataski** [drud/ddev#2204]
**Describe the bug**
It's just too slow, on a i7-3770 16GB RAM Windows 10 takes 5 minutes vs <1 minute on random Linode 1 CPU instance with 1GB RAM?

**To Reproduce**
1. Just do the usual:

```
ddev config --project-type=drupal8 --docroot=web --create-docroot
ddev start
ddev composer create "drupal/recommended-project:^8"
```

**Expected behavior**
Should take less than a minute. That's not even actual installation Drupal, it's just downloading and deploying all the vendors and dependencies while it eats CPU, I don't think that's internet issues with 300/300 up and down.

**Screenshots**
Whole process on a screencast https://streamable.com/32lys9

**Version and configuration information (please complete the following information):**
 - win10, ddev v1.14.0-rc2, docker 19.03.8, fresh install nothing custom, no other websites deployed or running, just this one fresh install of D8 with Composer.

**Additional context**
I just don't think that's right. It takes this much to set it up on localhost? Also even after installing it, browsing and loading pages is really slow and I don't get why, vanilla install of Drupal 8 on ghetto setup with XAMPP on same machine is still faster.

**Comment by rfay** [comment]
There's a huge difference between Docker on Linux and on Windows or MacOS. I'd encourage you to try out WSL2 on Windows, where you'll find very similar performance to the Linode. 

Also I encourage you to try out NFS, which makes a huge difference, https://ddev.readthedocs.io/en/stable/users/performance/#using-nfs-to-mount-the-project-into-the-container

Also, note that your entire composer operation is cached globally in a docker volume, so the next time you run this you won't have all the downloads.

**Comment by mataski** [comment]
Screencap is with NFS installed.

It was already cached, you can see in the screencap, it says 'Loading from cache', why does the loading take so long, it's just Drupal core.

**Comment by rfay** [comment]
The basic problem is that NTFS is optimized for large files, not small ones. 

My results:
macOS (2017 MBP) with ddev: 3:23
windows with ddev: 5:45
Windows native (NTFS, no ddev at all, composer build, all dependencies cached): 6:50

So yes, Windows and NTFS are the problem. Although Windows has great strengths, the NTFS problem with projects with many, many files is a big problem. 

When you try out WSL2, make sure you work *inside* the WSL2 space, not on the mounted NTFS drive. That's where you get the huge performance boost.

**Comment by mataski** [comment]
I ended up going with vanilla stack, Nginx/PHP/MariaDB light speed.
