### ISSUE TITLE
Add per-project-type commands (`ddev drush`, `ddev typo3cms`)

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2209]
**Is your feature request related to a problem? Please describe.**

Most Drupal users want a `ddev drush` command, and TYPO3 users want a `ddev typo3cms`. But Drupal users don't want to see a typo3 command, etc.

**Describe the solution you'd like**

Per-CMS, allow adding extra commands based on the CMS type. So the same as we add the "launch" or "xdebug" command, but per-project-type.

This could be done by just adding another keyword into the command.

**Describe alternatives you've considered**

**Additional context**

**Comment by gilbertsoft** [comment]
Nice idea with the keyword, this could easy be achieved.

**Comment by gilbertsoft** [comment]
From Slack https://typo3.slack.com/archives/C8TRNQ601/p1587558888434900:
Perhaps we should rethink the keyword idea and use the project type as file extension to enable various versions of a command for the different project types... The template should then copied e. g. on ddev start to the final file name.
