### ISSUE TITLE
ddev launch is outputting debug information. 

### ISSUE THREAD

**Issue by graham73may** [drud/ddev#2211]
**Describe the bug**
Just installed 1.14.0. Is this the expected behaviour for ddev launch ?

```
❯  ddev launch
+ FULLURL=https://project.ddev.site
+ HTTPS=
+ '[' https = https ']'
+ HTTPS=true
+ :
+ case $1 in
+ break
+ '[' -n '' ']'
+ case $OSTYPE in
+ start https://project.ddev.site
```

**To Reproduce**
Execute a `ddev launch` command.

Issue also occurs for `ddev launch -p`

**Expected behavior**
No debugging output!

**Version and configuration information:**
- Windows 10
- Docker Version: 19.03.8
- DDEV-Local version: v1.14.0

**Comment by rfay** [comment]
Thanks. Sorry that slipped in there.
