### ISSUE TITLE
Stream the output of hook commands instead of waiting until the command has completed

### ISSUE THREAD

**Issue by cweagans** [drud/ddev#2214]
**Is your feature request related to a problem? Please describe.**

I have a long running (30-ish seconds) hook command. There are some places where it outputs a bit of text to show progress to the end user as execution progresses, but ddev seems to put all of the output into a buffer and prints it all at once when the command is finished.

**Describe the solution you'd like**
Instead, it would be helpful to just immediately print any output from hook commands in real time.

**Comment by rfay** [comment]
Thanks, this is really important.  I almost solved it in a previous PR, but backed away.
