### ISSUE TITLE
Allow disabling global flags for custom commands

### ISSUE THREAD

**Issue by helhum** [drud/ddev#2215]
**Is your feature request related to a problem? Please describe.**
Custom ddev commands serve two purposes:

1. Creating new ddev commands

Inventing new commands for ddev to interact with the current project.

e.g. `ddev launch` which can launch a browser with a dedicated URL, but also with custom options like `-p` to launch phpmyadmin

2. Wrapping binaries that exist in the container to be easily executed through ddev.

e.g. `ddev drush` or `ddev typo3`

For the first, it is very nice that a global help option exists, that parses the command file and outputs a help message accordingly.

For the latter it is unfortunate that calling this binary in the container, behaves different than calling it as custom command.
e.g. `ddev typo3 -h` outputs the global help, whereas `ddev exec vendor/bin/typo3 -h` outputs the help of this binary.

**Describe the solution you'd like**

It would be great, if a custom commands could disable handling of global options,
by specifying this in a comment of the command file.

Maybe like this:

```
## GlobalOptions: false
```

**Comment by helhum** [comment]
Oh, maybe it would be worth considering doing that for `ddev composer` as well, so that `ddev composer` in all cases behaves the same as `ddev exec /usr/local/bin/composer`

**Comment by rfay** [comment]
Actually, `ddev composer` doesn't, because of the very awkward `ddev composer create` instead of `ddev composer create-project`, since the composer project stubbornly refuses to let you do a create-project in current directory.

**Comment by helhum** [comment]
> Actually, ddev composer doesn't, because of the very awkward ddev composer create instead of ddev composer create-project, since the composer project stubbornly refuses to let you do a create-project in current directory

ah, good point! fair enough!

**Comment by helhum** [comment]
> You can use `--` 
> Anyways, there is also a viable workaround at the user level.

This ticket wasn't meant as help request for myself asking how to reach the help option of any command, but rather as hint that the existing behavior might lead to confusion for inexperienced users and a request to add an option to make command wrappers (e.g. `ddev typo3` behave exactly the same wrapped and unwrapped (`ddev exec vendor/bin/typo3`). 

But at this point it seems viable to not care for consistency any more.

**Comment by jonaseberle** [comment]
Sorry, I didn't want to shoot down that suggestion. I just wanted to make sure that one common way to deal with it as a user is mentioned here. 
If consistency is possible to achieve here, that's of course even better.
