### ISSUE TITLE
Use DRUSH_OPTIONS_URI instead of creating a drush.yml file

### ISSUE THREAD

**Issue by jcnventura** [drud/ddev#2216]
**Is your feature request related to a problem? Please describe.**
ddev is currently having to create a drush.yml file to store the site's primary URL. This can conflict with existing files.

**Describe the solution you'd like**
Drush 9 and above support setting this via an environment variable called DRUSH_OPTIONS_URI. We should remove the creation of the ddev-provided drush.yml file (keeping for now the drushrc.php for Drush 8 installs, as this solution is not applicable there).

**Describe alternatives you've considered**
We can also keep creating the existing file. With all the side-effects and collisions that it has.

**Additional context**
Related to #2196

**Comment by rfay** [comment]
There's another fantastic reason for doing this: When people use a repo that has been used for ddev in a different context (lando or something), the drush.yml can cause trouble. So using DRUSH_OPTIONS_URI would limit that damage.

**Comment by pirog** [comment]
@rfay FWIW `DRUSH_OPTIONS_URI` is what we recommend and use in Lando for similar "limit the damage" reasons.

That said, i do feel like there may be some marketing benefits to DDEV if Lando or other tools users ran `lando drush uli` and got a `ddev` branded URL in return ;)

WAIT I THOUGHT I WAS USING LANDO?
AM I USING DDEV? 
SHOULD I USE DDEV? 
**I DONT KNOW WHAT TO BELIEVE ANYMORE!**
_WE ARE ALL LIVING IN A GIANT COMPUTER SIMULATION_

**Comment by rfay** [comment]
@jcnventura and @truls1502 I hope you can test the prerelease [v1.15-alpha5](https://github.com/drud/ddev/releases/tag/v1.15-alpha5) for the DRUSH_OPTIONS_URI support while it's still in prerelease, thanks!
