### ISSUE TITLE
`ddev config` should check for docker installation

### ISSUE THREAD

**Issue by andrewbelcher** [drud/ddev#2222]
**Describe the bug**
I was trying to get a not-very-technical person started with DDev to try and do a little theming in a Drupal 8 project. I gave them the DDev installation instructions and they installed DDev and ran the `ddev config` command to create the settings files etc. This obviously failed.

Once docker was installed they tried again in a new directory, but were told the project was already registered. `ddev rm --unlist` was recommended, but this failed as it couldn't find `docker-compose.yaml`.

**To Reproduce**
1. Have a fresh install of DDev (i.e. nothing in ~/.ddev), but docker stopped/not installed.
2. Clone an existing DDev project.
3. Run `ddev config`/`ddev start` -> will fail due to no docker
4. Install/start docker
5. Clone the DDev project in a different directory.
6. Run `ddev config` -> will fail due to already being registered, suggests `ddev rm --unlist`
7. Run `ddev rm --unlist` -> will fail due to no `docker-composer.yaml`.

**Expected behavior**
1. Perhaps we should stop and error immediately on all commands if docker is not available?
2. `ddev rm --unlist` should manage to run even if `docker-composer.yaml` is missing?
3. Perhaps give an option as part of `ddev config`/`ddev start` to replace the previous listed project inline?

**Version and configuration information (please complete the following information):**
 - Mac OS
Don't have any further details.

**Additional context**
I was able to work out the issue quite quickly, but for someone less technical they couldn't make any progress.

**Comment by andrewbelcher** [comment]
No idea if it's something worth trying to fix, but I thought at least getting this up here may help some poor sod trying to google the issue!

**Comment by rfay** [comment]
Just a note... a `ddev config` in the same directory as it was *originally* done will work fine in this scenario. It was apparently done in a new directory. Also, if anyone is trying to sort this out and gets in a loop, just edit out items in ~/.ddev/global_config.yaml, it does no harm, that's just a registry.

**Comment by rfay** [comment]
`ddev start` checks:
```
 % ddev start
Could not connect to docker. Please ensure Docker is installed and running. 
```
but `ddev config` doesn't check. That's an easy fix.
