### ISSUE TITLE
too many levels of symbolic links

### ISSUE THREAD

**Issue by Ptosek** [drud/ddev#2227]
Hello,

i update to last ddev 1.14 and i cannot start the project. I run ddev start and after installing i got this error

failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/273f96443d97099ec0c5fce1745b5984a5a52c815e44aaef321b6efe4dfc0c0f/merged: too many levels of symbolic links
Failed to start xxxx: exit status 1

I am trying clean installation and same. 

Thanks for answers :)

Windows 10
Docker version: 19.03.8
ddev version: v1.14.0

config.yaml (nothing changed)
name: xxxx
type: wordpress
docroot: web
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
use_dns_when_possible: true

**Comment by rfay** [comment]
Hi @Ptosek - Something is wrong in your docker installation. I'd recommend 

1. `ddev poweroff`
2.  Restart docker
3. `docker system prune`
4. `docker rm -f $(docker ps -aq)` (removes all containers)
5. `docker rmi -f $(docker images -q) (removes all images. they'll get re-downloaded)

If that doesn't do the trick, do a docker factory reset, but you'll lose any database volumes you have, so make sure you have db dumps before doing that.

**Comment by rfay** [comment]
No response from @Ptosek , but I hope you got it fixed. I think the instructions above will get you going. This really doesn't seem to have to do with ddev, although I know it seems to. Happy to continue the conversation here, but closing this for now.

**Comment by paradojo** [comment]
> Hi @Ptosek - Something is wrong in your docker installation. I'd recommend
> 
> 1. `ddev poweroff`
> 2. Restart docker
> 3. `docker system prune`
> 4. `docker rm -f $(docker ps -aq)` (removes all containers)
> 5. `docker rmi -f $(docker images -q) (removes all images. they'll get re-downloaded)
> 
> If that doesn't do the trick, do a docker factory reset, but you'll lose any database volumes you have, so make sure you have db dumps before doing that.

This worked for me, thank you

**Comment by rfay** [comment]
@paradojo Did you just try all those things or did one specifically solve it?

**Comment by marinef75** [comment]
worked for me 👍

**Comment by git1362** [comment]
works for me 👍

**Comment by joestringer** [comment]
`docker system prune` was the trick for me.

**Comment by SYM1000** [comment]
Restarting to factory defaults solved it!
[How to do factory reset](https://www.kindacode.com/article/how-to-reset-docker-desktop/)

**Comment by angtheod** [comment]
`docker system prune` didn't work for me
Docker version 20.10.17, build 100c701,
docker-compose version 1.29.2, build 5becea4c

For me the problem was using these two images together
**php:8.1.5-fpm-alpine
mysql:5.7**

I changed the db image to mysql:8.0 and it was fixed.

**Comment by rfay** [comment]
Wow, @angtheod - DDEV doesn't use either of those images. I assume you're in the wrong issue here?

**Comment by angtheod** [comment]
@rfay that would be a valid assumption to make :)
