### ISSUE TITLE
Drupal 8 nginx configuration doesn't serve static pages 

### ISSUE THREAD

**Issue by wakkoism** [drud/ddev#2228]
**Describe the bug**
We are using patternlab in Drupal 8 that serve up static content
When going to  the url below, it should be reading the index.html file that lives inside that directory.
https://example.com/themes/custom/custom_theme/patternlab/?p=viewall-global-colors

There is an index.html page that lives in that folder there that it is supposed to hit but does not happened, instead loads the root /index.php file of Drupal.

**To Reproduce**
1. https://example.com/themes/custom/custom_theme/patternlab/?p=viewall-global-colors
2. Loads the Drupal 404 page.

**Expected behavior**
Going to https://example.com/themes/custom/custom_theme/patternlab/?p=viewall-global-colors, should load the pattern lab page.

**Additional context**
I've changed https://github.com/drud/ddev/blob/master/containers/ddev-webserver/files/etc/nginx/nginx_drupal8.conf#L13 to
```
try_files $uri $uri/ /index.php?$query_string
```
That seem to work.

**Comment by rfay** [comment]
I'm pretty sure that correct drupal config never allows accessing anything directly inside a theme does it? And especially indexing it?

You absolutely can replace the entire config and check it into your project, https://ddev.readthedocs.io/en/stable/users/extend/customization-extendibility/#providing-custom-nginx-configuration

**Comment by wakkoism** [comment]
I've ended up extending the nginx config using the following
```
    location ~ \/patternlab {
        absolute_redirect off;
        try_files $uri $uri/ /index.php?$query_string;
    }
```

As far as the theme folder, you can access certain files directly within the theme folder but not indexing it.

**Comment by rfay** [comment]
I'm glad you got this solved, and put the solution here. In general, most nginx and apache configurations for Drupal don't allow direct access to html files, and certainly not "indexing" of directories (which is what index.html is about)

Closing for now, happy to continue the conversation.
