### ISSUE TITLE
Prompt user to run `auth pantheon` if `config pantheon`, or `pull` fails

### ISSUE THREAD

**Issue by eojthebrave** [drud/ddev#2241]
**Describe the bug**

Running `ddev config pantheon` when ddev is not currently authenticated with Pantheon can lead to some cryptic error messages.

Example:

```
ddev config pantheon

<some interactive steps>

Project Type [php, wordpress, backdrop, magento, drupal6, drupal7, drupal8, typo3, magento2] (drupal7):
unable to get Pantheon environments for project dme - does the ddev project name match the pantheon project name? ('terminus env:list --field=id ' failed)

There was a problem configuring your project: unable to get Pantheon environments for project dme - does the ddev project name match the pantheon project name? ('terminus env:list --field=id ' failed)
```
 
You also get the same error when running `ddev pull`, for a project configured to pull from Pantheon, if you're not authenticated.

Running `terminus env:list {SITE_ID} --field=id` on my machine works as expected.

The issue seems to happen because terminus inside the ddev container isn't authenticated? But the error displayed doesn't help make that clear.

I've had this happen a couple of times, and the solution for me has been to run `ddev auth pantheon {API_KEY}`. But it always takes me a while to figure that out.

**Expected behavior**

It would be nice if the error output when this happens also includes something that prompts you to run `ddev auth pantheon` if necessary.

The relevant message appears to be here https://github.com/drud/ddev/blob/4d7cf50357e76654e37b6bd01549480047cd84e0/pkg/ddevapp/providerPantheon.go#L279

**Comment by rfay** [comment]
Thanks, great idea.
