### ISSUE TITLE
`ddev config pantheon` does not change provider if "default" provider is already set

### ISSUE THREAD

**Issue by andy-blum** [drud/ddev#2243]
**Describe the bug**
Setting up a new project with `ddev config pantheon` properly sets the provider value, but re-configuring a _running_ project (e.g. after accidentally running `ddev config`) does not update the provider value

**To Reproduce**
1. `ddev config`
2. `ddev start`
3. `ddev config pantheon`
4. The `provider` value in config.yaml still says `default`

**Expected behavior**
DDEV should update the provider value to `pantheon`

**Screenshots**
![Screen Shot 2020-05-07 at 10 00 26 AM](https://user-images.githubusercontent.com/25532785/81303442-af859100-9049-11ea-8301-dac496346b63.png)
![Screen Shot 2020-05-07 at 10 00 59 AM](https://user-images.githubusercontent.com/25532785/81303467-b7453580-9049-11ea-8bc8-0b83ef3260b4.png)

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macOS 10.15.4
 - Docker version: 19.03.8
 - ddev version: 1.14.1
 - config.yaml contents: see screenshot

**Additional context**

**Comment by rfay** [comment]
I confirm that, thanks!
