### ISSUE TITLE
composer install freezes randomly

### ISSUE THREAD

**Issue by mac-dev** [drud/ddev#2248]
running composer install inside ddev web container freezes randomly

**To Reproduce**
1. ddev ssh
2. composer install
3. process suddenly freezes and CPU goes Idle
4. composer install stops e.g. at 

  - Installing symfony/class-loader (v3.4.35): Reading /mnt/ddev-global-cache/composer/files/symfony/class-loader/4b20f38b53bc3ffa29fcca03b428c360f617ddac.zip from cache
Loading from cache
 Extracting archiveExecuting command (CWD): unzip -qq  '/var/www/html/vendor/symfony/class-loader/bc1db44bdc4721e3642788e352a06db3' -d '/var/www/html/vendor/composer/a30d92b0'

**Workaround**
Only killing docker helps to get ddev stopped.

Running composer install again and again with freshly started docker sequentielly finally let us complete the install.

**Additional Info**
Sometimes before it happend that the connection to docker daemon was lost with:
 pipe\docker_engine_linux: The system cannot find the file specified
Since updateing to the latest Docker Desktop for Windows it now looks like it is always freezing but not loosing the connection.

**Version and configuration information:**
 - Host computer OS and Version: Windows 10 Version	10.0.17763 Build 17763
 - Docker version information  19.03.8
 - ddev version information  v1.13.1
 - config.yaml - default config.yaml
 
Attached find our composer.json
[composer.zip](https://github.com/drud/ddev/files/4618480/composer.zip)

**Comment by rfay** [comment]
It sounds like your composer cache might be corrupted.  Try deleting the cache by just `ddev ssh` and `rm -rf /mnt/ddev-global-cache/composer/*`

You could also `docker volume rm ddev-global-cache` but you lose just a little more that way, bash history, `mkcert -install` has to be redone, terminus cache.

**Comment by mac-dev** [comment]
Worked after deleting the composer cache. But I had to restart docker one again as doing an `rm -rf /var/www/html/web` got stuck. Will let it run once again and close the issue if its fine.

**Comment by mac-dev** [comment]
Tested it with filled composer cache, worked too. Closing the issue.

**Comment by rfay** [comment]
Glad it's working for you. I haven't heard of this happening before. Might have been a docker fail, corrupted disk. So it's definitely worth considering deleting that docker volume, may be time to reset docker to factory, especially if you have any more trouble.

What version of Docker Desktop did you have?

**Comment by mac-dev** [comment]
I had 2.2.05 before but there have been disconnects to Docker Daemon at
that point of composer install.
Now running 2.3.x.x and got those freezes.
I did a factory reset right now and starting from scratch. Docker Volume
was quite old. So this might have been the culprit.
Another thing I have in focus is the company wide on access scanner from
McAfee.


Am Mi., 13. Mai 2020 um 04:31 Uhr schrieb Randy Fay <
notifications@github.com>:

**Comment by rfay** [comment]
Thanks - is there any possibility this could be a regression in Docker 2.3.0.2? Please let me know how this turns out.

It could also possibly be a problem with the actual upstream composer package of course, but it sounds like you've already ruled that out.

BTW, on Windows I strongly recommend `ddev composer install` instead of using `composer install` inside the container, because `ddev composer install` cleans up symlinks after it's done.  For more information, https://ddev.readthedocs.io/en/stable/users/developer-tools/#ddev-and-composer

**Comment by mac-dev** [comment]
We are still facing this issues.

Docker Desktop freezes on composer install or drush cex not always but regularrly when many files (100-200) are changed and synced.
During that sync phpstorm will start to index those new files to and I guess McAfee EPS will start scanning those files.
After a Docker Desktop restart Containers run fine again but the might freeze by running e.g. drush cex again.
Stopping PHPStorm indexing does not solve that. So I am into investigation of the McAfee EPS stuff.

Docker Desktop 2.3.0.3
Windows 10 Enterprise 1809 17763.1294
BTW. Windows Developer Mode is disabled here bei GPO or whatever and can't be enabled by our team :-(
P.S.: Don't use Docker on Windows! Don't use Docker on Windows! Don't use Windows ....
P.P.S.: I guess it is time to find a new job ;-)

**Comment by rfay** [comment]
If you have the option of moving on to WSL2, do it quickly! It's great.  

I assume you have docker configured in the legacy Hyper-V mode, which is a mode they are leaving behind and giving less attention to.

Docker on Windows has generally been great, except for a couple of problem releases, which you don't have. 

If Docker is freezing on you, how do you describe that? Does it take a docker restart to fix? 

If you have a way to demonstrate the problem, could you report it in https://github.com/docker/for-win/issues ? They're really quite responsive if you give them a way to completely understand and recreate the issue.

**Comment by rfay** [comment]
I guess turning off McAfee will be one of your tests as you investigate.
