### ISSUE TITLE
Document or simplify the tooling for staticrequired

### ISSUE THREAD

**Issue by NBZ4live** [drud/ddev#2253]
Hi,

https://github.com/drud/ddev/blob/master/docs/developers/building-contributing.md does list `make staticrequired` as one of the building steps.

But to run it (to build the Go app) you first will need to install `markdownlint` (which is actually a markdownlint-cli npm package) and mkdocs (which is a python package that can be installed through pip).

I do see 2 problems here:

1. It is not documented and not hinted during `make staticrequired`. It just break with an error message and forces you to google for this tools
2. If you don't have node installed on your machine, you will have to install it to get `markdownlint-cli` through npm to build Go, which does feel like unneeded overhead.

Either this should be documented or the tools should be put into the build container.

**Comment by rfay** [comment]
#2254 pushes all this into the golang-build-container. Thanks for pointing this out! When you're the only one that works on these things most of the time you don't necessarily notice these things.
