### ISSUE TITLE
Add ddev open command

### ISSUE THREAD

**Issue by crydotsnake** [drud/ddev#2265]
# Command Description

If i type `ddev open` in a ddev project directory, the project should open in my default web browser. 

To make it a little bit nicer:
`ddev open --https` To open the project via https
`ddev open --http` To open the project via http

Or something like that.

**Comment by rfay** [comment]
`ddev launch` is the command you're looking for :)

**Comment by crydotsnake** [comment]
Ahh! didnt know there was a command for that 🙈
