### ISSUE TITLE
Write documentation for using ddev alongside kalabox

### ISSUE THREAD

**Issue by beeradb** [drud/ddev#227]
## What happened (or feature request):
ddev currently cannot run alongside an existing kalabox installation. This is because both kalabox and ddev use a router which tried to bind to port 80, and from my memory, the kalabox router is particularly heavy handed and doesn't automatically shut down when exiting or removing all sites from a kalabox installation.

## What you expected to happen:
Let's determine the easiest way to run kalabox and ddev side by side, or to remove the kalabox router and allow ddev to work as expected. We should write the results as documentation so we can be sure users have a clear path to running the tools on the same machine.

## How to reproduce it (as minimally and precisely as possible):
Install and start a kalabox site. Attempt to start a ddev site.

## Related Issues
https://github.com/kalabox/kalabox/issues/1771

**Comment by tannerjfco** [comment]
We added a section to the docs to generally cover current port requirements, noting other environments need to be turned off. https://ddev.readthedocs.io/en/latest/?badge=latest#using-ddev-with-other-development-environments

We could add more specific directions for specific tools, but there are a *ton* of tools out there, especially when you consider across Windows, Mac, and Linux. Should we provide notes for some of the major ones? Or should we keep this information generic? If we want to provide notes for the most popular tools, which tools should those be?

**Comment by rickmanelius** [comment]
Maybe we make a very quick reference and call it a day. Example: "Any docker based tool (e.g. Kalabox, Docker VM, etc.)"

**Comment by rickmanelius** [comment]
As per our testing, these kbox is completely incompatible with ddev and its supported version of her Docker for Mac. A warning needs to be added.

**Comment by rickmanelius** [comment]
Related https://github.com/drud/ddev/issues/126.

**Comment by rickmanelius** [comment]
Review again around July 1st to see if it's still a problem. Ideally, this is just a warning for tool incompatibility beyond just Kbox and not just for this specific compatibility.

**Comment by rfay** [comment]
Still not possible to run kalabox with current docker, so still not possible to run kalabox alongside ddev

**Comment by rfay** [comment]
This actually does work, but since the GUI hides errors I was confused.

1. Stop all ddev sites with ddev stop. Otherwise they will fight over port 80.
2. Install kalabox, but on the 2nd step choose to "Customize", and *do not install docker*, it's a very old version of docker.

![install_kalabox_and_kalabox_and_downloads_and_write_documentation_for_using_ddev_alongside_kalabox_ _issue__227_ _drud_ddev](https://user-images.githubusercontent.com/112444/27935473-8496fe1e-6268-11e7-9cfb-e7ef98ceae6b.png)

![install_kalabox_and_write_documentation_for_using_ddev_alongside_kalabox_ _issue__227_ _drud_ddev](https://user-images.githubusercontent.com/112444/27935494-a5419872-6268-11e7-80c9-15e7a1db7394.png)

3. Use the command-line "kbox" for testing at first, as the GUI does not report useful errors (even contention for port 80). 
4. Whenever you switch between kbox and ddev, make sure to stop all sites of each to avoid the contention for port 80.

**Comment by rickmanelius** [comment]
Sidenote. Given that the Kalabox team has explicitly stated Lando as being the successor, perhaps this is something best solved with documentation knowing that Kalabox might be getting less attention moving forward.

**Comment by rickmanelius** [comment]
I propose the following:
* Search/file an issue over at https://github.com/kalabox/kalabox to see if they are willing to update Docker.
* If it's not a priority, we just document potential incompatibilities.
* We resolve the issue about other products/offerings using port 80 https://github.com/drud/ddev/issues/126.

**Comment by rfay** [comment]
@rickmanelius it turned out I was currently wrong (even though I said it several times) - Kalabox works with current docker, so these can be used next to each other. Shut one off, turn the other on.

**Comment by rickmanelius** [comment]
Ok cool! Then we just need to still create a snippet of documentation that notes there may be some incompatibilities with other tools and perhaps a way to turn off dev when trying to use another solution.

**Comment by rickmanelius** [comment]
@beeradb I believe this is addressed here https://ddev.readthedocs.io/en/latest/#using-ddev-with-other-development-environments.

**Comment by rickmanelius** [comment]
Adding to Brad simply to review if the current docs are sufficient. Also noting that we have another feature request to check port 80 here https://github.com/drud/ddev/issues/126

**Comment by rickmanelius** [comment]
Calling this one closed. Also, https://github.com/drud/ddev/issues/126 will provide additional help for end-users to sanity check this type of issue.
