### ISSUE TITLE
ddev custom commands seem to "eat" anything entered while they're running

### ISSUE THREAD

**Issue by wizonesolutions** [drud/ddev#2273]
**Describe the bug**
If I start typing a command that I want to appear in my terminal after a ddev custom command finishes, it will be "eaten" and not appear in the terminal afterward.

**To Reproduce**
1. Run a custom command like `ddev xdebug` (or a command that sleeps for a few seconds, maybe)
2. Before the command finishes, start typing another one like `ddev xe`

**Expected behavior**
`ddev xe` is waiting on the command prompt once `ddev xdebug` finishes

**Actual behavior**
Command prompt is blank.

**Screenshots**
-

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Linux (Manjaro)
 - Docker version information (use `docker version`) and insert it here.
```
Client:
 Version:           19.03.8-ce
 API version:       1.40
 Go version:        go1.14.1
 Git commit:        afacb8b7f0
 Built:             Thu Apr  2 00:04:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.1
  Git commit:       afacb8b7f0
  Built:            Thu Apr  2 00:04:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.4.m
  GitCommit:        d76c121f76a5fc8a462dc64594aea72fe18e1178.m
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
 - ddev version information (use `ddev version`)
```
DDEV-Local version	v1.14.2                                
commit            	v1.14.2                                
db                	drud/ddev-dbserver-mariadb-10.2:v1.14.1
dba               	phpmyadmin/phpmyadmin:5                
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.14.0            
docker            	19.03.8-ce                             
docker-compose    	1.25.0-rc4                             
os                	linux                                  
router            	drud/ddev-router:v1.14.0               
web               	drud/ddev-webserver:v1.14.2            
```
 - config.yaml contents for the misbehaving project
N/A (kinda has private naming in it)
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?
No custom config.

**Additional context**
-

**Comment by rfay** [comment]
Is this the same for host commands and web commands? Is it true for other (non-shell) ddev commands? Normally, this is all about terminal buffering, I'm not sure whether there's a solution or a cross-platform solution.  What shell are you using?

**Comment by rfay** [comment]
I took a look at this, it only seems to happen for shell-based commands that are in-container commands, doesn't happen with host commands.

The reason it's happening is that stdin is owned by those commands as they're executing *inside the container*, so it doesn't make it back to your terminal on the host. I don't think you'd want it any other way. The way it is right now `echo "SHOW TABLES;" | ddev mysql` works great. And this is why. Your keystrokes are going into the custom command as it executes inside the container.

**Comment by wizonesolutions** [comment]
Ah, that makes sense! That explains a lot. Probably no good way around it
other than just chaining commands all at once e.g. with &&.
