### ISSUE TITLE
Broken Backend

### ISSUE THREAD

**Issue by benhosmer** [drud/ddev#2275]
**Describe the bug**
502: Unresponsive/broken ddev back-end site.

This is the ddev-router container: The back-end webserver at the URL you specified is not responding. You may want to use "ddev restart" to restart the site.
**To Reproduce**
1. `composer create-project drupal/recommended-project bawk.local/`
2. `ddev config` accept the defaults, ie docroot in web etc
3. `ddev {start,restart`

```
[bhosmer@localhost bawk.local]$ ddev restart
Restarting project bawk... 
Network ddev_default is external, skipping 
Network ddev_default is external, skipping 
Building ddev-ssh-agent 
Creating ddev-ssh-agent ... done
 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
mkcert may not be properly installed, we suggest installing it for trusted https support, `brew install mkcert nss`, `choco install -y mkcert`, etc. and then `mkcert -install` 
Running   Command=ip address show dev docker0
Building db 
Building web 
Creating ddev-bawk-db ... done
Creating ddev-bawk-web ... done
Creating ddev-bawk-dba ... done
 
Creating ddev-router ... done
 
Ensuring write permissions for bawk 
Ensuring write permissions for bawk 
Existing settings.php file includes settings.ddev.php 
Restarted bawk 
Your project can be reached at http://bawk.ddev.site http://127.0.0.1:32783 
```

**Expected behavior**
I expect to see my site at one of the urls from above. However, I get:

```
502: Unresponsive/broken ddev back-end site.

This is the ddev-router container: The back-end webserver at the URL you specified is not responding. You may want to use "ddev restart" to restart the site.
```

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: [e.g. Windows 10, macOS High Sierra]
 Fedora 32
 - Docker version information (use `docker version`) and insert it here.
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:26:43 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:24:37 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

 - ddev version information (use `ddev version`)
DDEV-Local version	v1.14.2                                
commit            	v1.14.2                                
db                	drud/ddev-dbserver-mariadb-10.2:v1.14.1
dba               	phpmyadmin/phpmyadmin:5                
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.14.0            
docker            	19.03.5                                
docker-compose    	1.25.0-rc4                             
os                	linux                                  
router            	drud/ddev-router:v1.14.0               
web               	drud/ddev-webserver:v1.14.2             

 - config.yaml contents for the misbehaving project
```
name: bawk
type: drupal8
docroot: web
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
use_dns_when_possible: true
```

 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?
No.
**Additional context**
Add any other context about the problem here. Thanks!
ddev router logs:
```
forego     | starting nginx.1 on port 5000
forego     | starting dockergen.1 on port 5100
forego     | starting dockergen.1 on port 5300
dockergen.1 | 2020/05/22 18:16:49 Generated '/gen-cert.sh' from 4 containers
dockergen.1 | 2020/05/22 18:16:49 Running 'chmod ugo+x /gen-cert.sh && /gen-cert.sh && sleep 1 && nginx -s reload'
dockergen.1 | 2020/05/22 18:16:49 Generated '/etc/nginx/conf.d/default.conf' from 4 containers
dockergen.1 | 2020/05/22 18:16:49 Running 'sleep 1 && nginx -s reload'
nginx.1    | 2020/05/22 18:16:50 [error] 999#999: *1 open() "/usr/share/nginx/html/healthcheck" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /healthcheck HTTP/1.1", host: "127.0.0.1"
nginx.1    | 127.0.0.1 - - [22/May/2020:18:16:50 +0000] "GET /healthcheck HTTP/1.1" 404 153 "-" "curl/7.64.0" "-"
dockergen.1 | 2020/05/22 18:16:50 Watching docker events
dockergen.1 | 2020/05/22 18:16:50 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'sleep 1 && nginx -s reload'
dockergen.1 | 2020/05/22 18:16:51 [chmod ugo+x /gen-cert.sh && /gen-cert.sh && sleep 1 && nginx -s reload]: + mkcert -cert-file /etc/nginx/certs/master.crt -key-file /etc/nginx/certs/master.key bawk.ddev.site 127.0.0.1 localhost '*.ddev.local' '*.ddev.site'
dockergen.1 | /gen-cert.sh && /gen-cert.sh && sleep 1 && nginx -s reload]:  - "*.ddev.site"
dockergen.1 | 2020/05/22 18:16:51 Watching docker events
dockergen.1 | 2020/05/22 18:16:51 Contents of /gen-cert.sh did not change. Skipping notification 'chmod ugo+x /gen-cert.sh && /gen-cert.sh && sleep 1 && nginx -s reload'
nginx.1    | 2020/05/22 18:16:59 [error] 1049#1049: *3 connect() failed (113: No route to host) while connecting to upstream, client: 172.18.0.1, server: bawk.ddev.site, request: "GET / HTTP/1.1", upstream: "http://172.18.0.4:80/", host: "bawk.ddev.site"
nginx.1    | bawk.ddev.site 172.18.0.1 - - [22/May/2020:18:16:59 +0000] "GET / HTTP/1.1" 502 507 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
nginx.1    | bawk.ddev.site 172.18.0.1 - - [22/May/2020:18:16:59 +0000] "GET /favicon.ico HTTP/1.1" 499 0 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
```

**Comment by rfay** [comment]
Hi @benhosmer - thanks for the report.

What do you see with `ddev list` and `ddev logs`? 

Basically it's saying that it can't reach the webserver. It does look like something is wrong in docker-world.

**Comment by rfay** [comment]
I assume you've never set up a ddev site before on this machine? Please do confirm that you followed all the steps in https://ddev.readthedocs.io/en/stable/users/docker_installation/#linux-installation-docker-ce

I do recommend that you use `ddev composer create` for a first project, using the quickstart, but that shouldn't have anything to do with this. See https://ddev.readthedocs.io/en/stable/users/cli-usage/#drupal-8-quickstart

**Comment by benhosmer** [comment]
ddev list:

```
ddev list
unable to create project at project root /tmp/testddev: project root /tmp/testddev does not exist 
unable to create project at project root /home/bhosmer/usda/drupal-docker2/nginx/docroot/tmp: project root /home/bhosmer/usda/drupal-docker2/nginx/docroot/tmp does not exist 
NAME              TYPE     LOCATION                                              URL                    STATUS                                                                               
bawk              drupal8  ~/usda/drupal-docker2/nginx/docroot/bawk.local        http://bawk.ddev.site  running                                                                       
bawk              drupal8  ~/usda/drupal-docker2/nginx/docroot/bawk.local        http://bawk.ddev.site  running                                                                       
cuke.local        drupal8  ~/usda/drupal-docker2/nginx/docroot/cuke.local                               stopped                                                                       
d8-demo.local     drupal8  ~/usda/drupal-docker2/nginx/docroot/d8-demo.local                            stopped                                                                       
drupal            drupal8  ~/learn-composer/drupal                                                      stopped                                                                       
flspota.local     drupal8  ~/usda/drupal-docker2/nginx/docroot/flspota.local                            stopped                                                                       
fns-d8.local      drupal8  ~/usda/drupal-docker2/nginx/docroot/fns-d8.local                             stopped                                                                       
pasto             drupal7  ~/usda/drupal-docker2/nginx/docroot/pasto                                    stopped                                                                       
testddev                   /tmp/testddev                                                                project directory missing: /tmp/testddev                                      
tmp                        ~/usda/drupal-docker2/nginx/docroot/tmp                                      project directory missing: /home/bhosmer/usda/drupal-docker2/nginx/docroot/tmp
usda-gov.local    drupal8  ~/usda/drupal-docker2/nginx/docroot/usda-gov.local                           stopped                                                                       
wic-breast.local  drupal8  ~/usda/drupal-docker2/nginx/docroot/wic-breast.local                         stopped                                                                       

DDEV ROUTER STATUS: healthy 
```
[ddev-logs.txt](https://github.com/drud/ddev/files/4669899/ddev-logs.txt)

Also @rfay I've used ddev before with mulitple projects and it worked fine. I recently upgraded to Fedora 32, but I don't see anything that sticks out to me.

**Comment by rfay** [comment]
Oh, I see you have two items with the same name, recommend that you `ddev poweroff` and then edit ~/.ddev/global_config.yaml to remove the lines related to both of them, then `ddev start` again. It looks like you might have renamed a project in place?

**Comment by rfay** [comment]
I note that your web container also can't connect to the db container:

```
FastCGI sent in stderr: "PHP message: PDOException: SQLSTATE[HY000] [2002] No route to host in /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(416): PDO->__construct('mysql:host=db;p...', 'db', 'db', Array)
#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(371): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#2 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(166): Drupal\Core\Database\Database::openConnection('default', 'default')
#3 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#6 /var/www/html/web/core/lib/Drup" while reading response header from upstream, client: 172.18.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "127.0.0.1:32786"
[22-May-2020 18:28:54] WARNING: [pool www] child 1023 said into stderr: "NOTICE: PHP message: PDOException: SQLSTATE[HY000] [2002] No route to host in /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(416): PDO->__construct('mysql:host=db;p...', 'db', 'db', Array)"
```

**Comment by rfay** [comment]
Oh, have you always been using ".local" as your suffix? I sure recommend "ddev.site", the default, which requires no editing of the hosts file.

Also, not sure that ".local" always works as is, never tried that.

But neither of those should have anything to do with the trouble you're having, which is totally internal names inside docker, and unrelated to the fqdn.

**Comment by rfay** [comment]
Could you please do a `ddev poweroff` and then show me the results of `ddev start`? I don't think it will help, but it seems like docker networking is broken.

**Comment by rfay** [comment]
Oh, it looks like you have https://www.reddit.com/r/Fedora/comments/fx5z9e/communication_between_docker_containers_blocked/

Looks like it's firewalld

**Comment by benhosmer** [comment]
@rfay thanks for bump to look at firewalld. I bet that's definitely the culprit since I suspect some new firewall rules came across on my upgrade. Related to this, I'm going to put in a feature request for ddev to support podman as well as docker. I'll come back and close this once I figure out the correct settings so it's documented for anyone else.

**Comment by benhosmer** [comment]
For anyone else that encounters this after using or upgrading a RedHat family of operating systems:
https://github.com/docker/for-linux/issues/955#issuecomment-621685878 had the answer that fixed it.

```
firewall-cmd --permanent --zone=trusted --add-interface=docker0
firewall-cmd --zone=FedoraWorkstation --add-masquerade --permanent
firewall-cmd --reload
```
I had to restart docker and then just do a full reboot for everything to work. Thanks again Randy for the hint at how to fix this.
