### ISSUE TITLE
Redis clash when multiple projects use it?

### ISSUE THREAD

**Issue by damienmckenna** [drud/ddev#2280]
I think I'm seeing a problem where multiple projects running Redis connect to a single container.

**To Reproduce**
* Set up multiple D7 projects using Redis.
* Have both both projects running simultaneously.
* Run `ddev . drush st` for one project.
* Run `ddev . drush st` for the second project.
* The second project will indicate it is using the first project's theme.

**Expected behavior**
The two projects should show the correct information for both projects, i.e. different themes, etc.

**Screenshots**

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macOS 10.14.6
 - Docker version information: 19.03.8
 - ddev version information: v1.14.2
 - ddev extras: Redis

**Comment by rfay** [comment]
Hi @damienmckenna - I assume you're using the recipe at https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/redis ? 

I don't know much about redis, but that recipe does *not* seem to be intended for multiple projects to use at the same time. It's intended to be a redis container added to each project. 

Have you added the docker-compose.redis.yaml to each project?

If you do a `docker ps | grep redis` you should see containers running for each project.

**Comment by rfay** [comment]
Closing, no response from OP. Happy to continue the conversation here or elsewhere.

**Comment by damienmckenna** [comment]
Sorry, it has been a difficult few months.

I think the problem was elsewhere, including PEBCAK X-)

Thanks rfay.
