### ISSUE TITLE
Error and warning messages on ddev export-db should go to stderr, not stdout

### ISSUE THREAD

**Issue by dmgig** [drud/ddev#2281]
**Is your feature request related to a problem? Please describe.**

When using `export-db` with ddev not started, a gzip file is created. No error prints to the terminal, but the export failed. The only error message is one written to the new .gz file: "ddev can't export-db until the project is started, please start it first." It isn't readily apparent that anything failed.

**Describe the solution you'd like**

A mistake on my part to not check the file, but an error message printed to the terminal would be preferred to one that is sort of hidden in what could be mistaken for a successful export.

**Describe alternatives you've considered**

Could (should) check it manually or have used it enough to know that, in this case, no news is bad news.

**Additional context**

To recreate:

- create a fresh ddev project
- run `ddev export-db > test.sql.gz` before starting project
- `cat file.sql.gz` to see the "ddev can't export-db until the project is started, please start it first." message.

**Comment by rfay** [comment]
Thanks, that's important to fix. Error messages on most commands, but especially on `ddev export-db` should go to stderr to resolve this problem. That's already fixed in one place, but thanks for pointing out that this one is still there.
