### ISSUE TITLE
Docs: Replace Magento 1 (after end of support) with OpenMage (open source clone of Magento 1)

### ISSUE THREAD

**Issue by kkrieger85** [drud/ddev#2283]
Ref: https://github.com/drud/ddev/blob/master/docs/users/cli-usage.md#magento-1-quickstart

- Link to "Magento release page" is wrong. The link goes to https://github.com/OpenMage/magento-mirror which is a mirror for magento 1 releases

- I agree, to not recommend Magento 1 (delivered by Magento an Adobe company).
- Let's remove this recommendation for Magento1 and replace it with [OpenMage/Magento-LTS](https://github.com/OpenMage/magento-lts)

**Comment by rfay** [comment]
That sounds totally reasonable to me, PR is welcome.
