### ISSUE TITLE
502 Bad Gateway and then DDev stops working - all projects won't start

### ISSUE THREAD

**Issue by CreateSean** [drud/ddev#2285]
**Describe the bug**
While working on a project, updating twig code, all of a sudden  the project will return a 502 bad gateway error in the browser. 

Stop Ddev and then run DDEv start and get the following error:

Failed to start project-name: ddev-router failed to become ready: logOutput=, err=container exited, please use `'ddev logs -s ddev-router`` to find out why it failed

running ddev logs outputs this:
```
Using the local CA at "/root/.local/share/mkcert" ✨        
ERROR: failed to read the CA certificate: unexpected content
```

I then ran ddev poweroff and restarted - got the same issue. Rebooted compuger and got the same issue. 

Am **unable to work on any projects** at this point.

**Expected behavior**

**Screenshots**

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Windows 10
 - Docker version information 19.03.8
 - ddev version information 1.14.2
 - config.yaml contents for the misbehaving project
-- APIVersion: v1.13.1
name: compugen-new
type: php
docroot: public
php_version: "7.3"
mysql_version: "5.7"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
timezone: ""
host_db_port: "32890"
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? no

**Additional context**
This is the full output when running `ddev start`

```
λ ddev start
Starting compugen-new...
Building ddev-ssh-agent
Creating ddev-ssh-agent ... done

ssh-agent container is running: If you want to add authentication to the 
ssh-agent container, run 'ddev auth ssh' to enable your keys.
Pushing mkcert rootca certs to ddev-global-cache
failed to copy root CA into docker volume: container run failed with exit code 1, output=''
Pushed mkcert rootca certs to ddev-global-cache
Building db
Building web
Creating ddev-compugen-new-db ... done
Creating ddev-compugen-new-dba ... done
Creating ddev-compugen-new-web ... done

Creating ddev-router ... done

Failed to start compugen-new: ddev-router failed to become ready: logOutput=, err=container exited, please use 'ddev logs -s ddev-router` to find 
out why it failed
```

**Comment by rfay** [comment]
Somebody else reported this, the fix for them was `ddev poweroff` and  then restart docker. What version of Docker Desktop for Windows are you using?

**Comment by CreateSean** [comment]
Docker 19.03.8

restarting docker appears to have fixed it. weird.

**Comment by rfay** [comment]
Thanks, please take a look at the "About docker desktop" and report the version of Docker desktop, thanks.

**Comment by CreateSean** [comment]
Okay and 2 minutes later I've got the same issue.

**Comment by rfay** [comment]
Please show the results of `docker logs ddev-router`

**Comment by rfay** [comment]
And then if you haven't already, rebuild the mkcert CA with the instructions in https://github.com/drud/ddev/issues/2285#issuecomment-636928527 (this does no harm)

OH, please check to make sure you're not out of docker disk space, that would sure do it.

**Comment by CreateSean** [comment]
docker logs here: https://pastebin.com/sjTKi0du

How do I see if I'm out of space?

**Comment by rfay** [comment]
![image](https://user-images.githubusercontent.com/112444/83427911-b86e4600-a3ee-11ea-98c0-039907b816be.png)

**Comment by rfay** [comment]
Hoping to hear what your results are, @CreateSean , since this has happened to at least one other person.

**Comment by CreateSean** [comment]
rebuilding mkcert seems tohave worked for me. I'm haven't had a problem in 2 hours.

Thank you for your time @rfay

**Comment by rfay** [comment]
Thanks. Sure is weird. Will be interested to hear if you disk space looks like it's running low.

**Comment by CreateSean** [comment]
I have plenty of disk space 

![image](https://user-images.githubusercontent.com/6899490/83443175-4f4ef880-a417-11ea-8f1e-382b48ec256e.png)

**Comment by rfay** [comment]
Thanks, I wonder what's happening. Now the fact that you made an issue will help collect information for the future. We'll be able to make sure we know whether it's just Windows, etc.

**Comment by CreateSean** [comment]
This issue happened again. I resolved it by once again following the instructions in this comment https://github.com/drud/ddev/issues/2285#issuecomment-636928527 after restarting docker.

**Comment by cepheiVV** [comment]
This happened in my ddev version v1.22.4 with Docker Desktop 4.25.2 after renaming my ddev project:

 - ddev delete
 - renamed the directory the .ddev is in
 - ddev config --project-name=<new_name>
 - ddev restart
 - ddev launch
 - now getting "Bad Gateway"

First tried to uninstall and reinstall mkcert as described above. Didn't help.
Then tried to restart Docker Desktop and ddev restart. Now getting invalid SSL cert error in https requests. After a minute or so I'm back to "Bad Gateway" on the same request.
Another ddev project on my machine does work fine (SSL cert works), so it must be related to this very project.

**Comment by scshasha** [comment]
Thanks, the solution works! @cepheiVV @rfay
