### ISSUE TITLE
Confirm viability of authenticating with and downloading assets from Pantheon.

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#229]
## What happened (or feature request):

* Precursor testing/prototyping for the [Pantheon MVP](https://github.com/drud/ddev/issues/216) issue.

## What you expected to happen:

* [x] Confirm authentication w/terminus (authenticate, store token, use token, update token).
* [x] Confirm downloading of file and database assets.

## Anything else do we need to know:

* We should probably create a basic Pantheon account using accounts@drud.com and spin up a vanilla test-Drupal-site-XYZ.

## Related source links or issues:

* [Pantheon MVP](https://github.com/drud/ddev/issues/216)

**Comment by beeradb** [comment]
This has been delivered at https://github.com/drud/elysium and is ready for review at this point. 

I'm still working to flesh out documentation and will update here once I'm happy with those efforts.

**Comment by beeradb** [comment]
Documentation is done (for now) and ready for review.

**Comment by rickmanelius** [comment]
@beeradb Where would be the appropriate place to track reviews? In the new repo? Or @rfay / @tannerjfco adding feedback here? Given this is more technical and (probably) less end-user facing, what feedback (if any) are you looking for from me?

**Comment by rfay** [comment]
I think at least one of us needs to spend enough time experimenting with elysium, commenting, making issues or PRs. Grokking it. *not* in the first-run context of connecting it with ddev.

**Comment by beeradb** [comment]
@rickmanelius I don't believe feedback is needed from you at this point. I think that will come when we have actual pantheon integration in ddev.

 I'm happy with any of the following approaches for feedback:
- Google doc
- Issues in elysium
- Comments here
- PR with a bunch of @to-do's in code
- Some other idea.

pretty much open to any method, really.

**Comment by rickmanelius** [comment]
@rfay following up to see if you have had a chance to review before our Wednesday knowledge transfer / @beeradb heading out on PTO this week.

**Comment by rfay** [comment]
My key goal for today (Tues 6/6/2017) is to see where I can get grokking elysium.

**Comment by rfay** [comment]
IMO this ticket is complete with Brad's current version of Elysium.
