### ISSUE TITLE
ddev crashes with SIGILL: illegal instruction PC=0x1063790 m=0 sigcode=1 on MacOS Catalina

### ISSUE THREAD

**Issue by Moongazer** [drud/ddev#2293]
**Describe the bug**
After setup the environment like explained in the manuals (1. Docker, 2. Homebrew, 3. DDEV), I tried to run `ddev --version` to see if it's working. But it crashes with this output:

```
devMBP3:~ developer$ ddev --version
SIGILL: illegal instruction
PC=0x1063790 m=0 sigcode=1

goroutine 1 [running, locked to thread]:
runtime.asyncPreempt()
	/usr/local/go/src/runtime/preempt_amd64.s:8 fp=0xc0001b8490 sp=0xc0001b8488 pc=0x1063790
github.com/aws/aws-sdk-go/aws/endpoints.init()
	/workdir/vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go:269 +0x1c7fc fp=0xc0001bfe98 sp=0xc0001b8490 pc=0x1574ffc
runtime.doInit(0x2153e20)
	/usr/local/go/src/runtime/proc.go:5414 +0x8a fp=0xc0001bfec8 sp=0xc0001bfe98 pc=0x10415aa
runtime.doInit(0x2155da0)
	/usr/local/go/src/runtime/proc.go:5409 +0x57 fp=0xc0001bfef8 sp=0xc0001bfec8 pc=0x1041577
runtime.doInit(0x215c420)
	/usr/local/go/src/runtime/proc.go:5409 +0x57 fp=0xc0001bff28 sp=0xc0001bfef8 pc=0x1041577
runtime.doInit(0x215e0e0)
	/usr/local/go/src/runtime/proc.go:5409 +0x57 fp=0xc0001bff58 sp=0xc0001bff28 pc=0x1041577
runtime.doInit(0x214ebc0)
	/usr/local/go/src/runtime/proc.go:5409 +0x57 fp=0xc0001bff88 sp=0xc0001bff58 pc=0x1041577
runtime.main()
	/usr/local/go/src/runtime/proc.go:190 +0x1ce fp=0xc0001bffe0 sp=0xc0001bff88 pc=0x1034b0e
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0001bffe8 sp=0xc0001bffe0 pc=0x1061f11

rax    0xc0001dad10
rbx    0x10
rcx    0x0
rdx    0x0
rdi    0xc0001bfe88
rsi    0xc0001bfe88
rbp    0xc0001bfe88
rsp    0xc0001b8488
r8     0xc0001e2528
r9     0x203000
r10    0x8
r11    0x75
r12    0xf5
r13    0x0
r14    0x1b874f4
r15    0x0
rip    0x1063790
rflags 0x10206
cs     0x2b
fs     0x0
gs     0x0
devMBP3:~ developer$ 
```

**Version and configuration information:**
 - Fresh installed MacOS Catalina 10.15.5 on MacBook Pro (Mid 2010), 500GB SSD, 8GB RAM
 - Homebrew 2.3.0
 - Docker Desktop 2.3.0.3 (45519):
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false
Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by rfay** [comment]
Most people are using macOS, and most with Catalina. 

Could you please provide the output of
* `which ddev`
* `brew link ddev`

I would recommend `brew uninstall ddev` and then `brew install ddev` just for grins.

**Comment by Moongazer** [comment]
> Could you please provide the output of
```
devMBP3:~ developer$ which ddev
/usr/local/bin/ddev

devMBP3:~ developer$ which link ddev
/bin/link
/usr/local/bin/ddev
```

> I would recommend `brew uninstall ddev` and then `brew install ddev` just for grins.

Thanks for your fast response. I did reinstall ddev but the issue persists. During the reinstall I saw that it loads `*sierra.bottle.tar.gz` also my OS is Catalina, is this expected behavior? 

```
devMBP3:~ developer$ brew uninstall ddev
Uninstalling /usr/local/Cellar/ddev/1.14.2... (5 files, 24MB)

devMBP3:~ developer$ brew install ddev
==> Installing ddev from drud/ddev
==> Downloading https://github.com/drud/ddev/releases/download/v1.14.2//ddev-1.14.2.sierra.bottle.tar.gz
Already downloaded: /Users/developer/Library/Caches/Homebrew/downloads/7b5223babced0f490e6af942d193a060eeabff3d65350134a016024eee285d03--ddev-1.14.2.sierra.bottle.tar.gz
==> Pouring ddev-1.14.2.sierra.bottle.tar.gz
==> Caveats
Make sure to do a `mkcert -install` if you haven't done it before, it may require your sudo password.

ddev requires docker and docker-compose.
Docker installation instructions at https://ddev.readthedocs.io/en/stable/users/docker_installation/

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/ddev/1.14.2: 5 files, 24MB

devMBP3:~ developer$ ddev --version
SIGILL: illegal instruction
PC=0x1063790 m=0 sigcode=1
...
```

**Comment by rfay** [comment]
Ok... Updating to 10.15.5…!

Thanks

**Comment by rfay** [comment]
Just remembered this issue with "Cylance" from long ago, https://github.com/drud/ddev/issues/513

**Comment by rfay** [comment]
I updated to 10.15.5 and can't recreate the issue. 

I have to confess I had no idea you could run Catalina on a 2010 machine. 

Oh, as a matter of fact they say you can't... https://support.apple.com/kb/SP803?locale=en_US
 - the oldest supported hardware for an MBP on Catalina is mid-2012.

So what's up with that?

**Comment by Moongazer** [comment]
> I have to confess I had no idea you could run Catalina on a 2010 machine.
A friend refurnished this Mac and used a patch tool to install it (http://dosdude1.com/catalina/).

Everything is working super smooth, Wifi, Cam, Audio, all hardware, also other software like Docker, Adobe etc. So I'm wondering why DDEV is not, as it is based on Docker I thought. But maybe you're right and this is the issue here... which would be really sad.

**Comment by Moongazer** [comment]
Yes, whats why I was wondering, Docker seems to run, at least the hello-world image... so strange :-(
```
devMBP3:~ developer$ docker --version
Docker version 19.03.8, build afacb8b
devMBP3:~ developer$ docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.
[...]
```

**Comment by rfay** [comment]
If you want to be ambitious you can try to build this yourself. All it requires is golang (`brew install golang`).  Then https://github.com/drud/ddev/blob/master/docs/developers/building-contributing.md

It would be interesting to see. 

It still looks more like a virus checker or something killing it. I did look at mac hardware history, and all macs switched to 64-bit in like 2007, I had been wondering if your computer was 32-bit. 

It would be super interesting to see if an earlier OS would work better for you. Catalina is the most restrictive and difficult version they have ever released. The ddev binary has to be signed and notarized. Those are new to Catalina, and that might be something different about other binaries you are looking at. 

Just for interest sake, I put an unsigned, un-notarized binary at https://ln2.sync.com/dl/6bbab5c50/e6ph6r9f-miez8ug9-u5w4a6hh-u7ru6dgz

But I'm not sure Catalina will let you run it...

**Comment by Moongazer** [comment]
> If you want to be ambitious you can try to build this yourself. All it requires is golang (`brew install golang`). Then https://github.com/drud/ddev/blob/master/docs/developers/building-contributing.md

Dude, I highly appreciate your help! :-) The last time I tried compiling something under Linux/Unix was ~15 years ago, I needed a crazy amount of strange libs, dependencies and tools which themself needed other libs again, resulting in incompatible cross-dependencies... and at the end my system was a fully messed-up piece of crap and nothing was really working anymore.
From this experience, I was expecting something similar, but now I'm super happy to see how easy it can be: after installing golang and run make, it compiles without a single line of warning/error/problem or whatever :-D And even more important: 
```
devMBP3:darwin_amd64 developer$ ./ddev --version
ddev version v1.15-alpha3
```
**It's working!** I tried it also with a real project, all web and DB server images are downloaded, installed and started like expected! Super great, thanks a lot!
So, does this can help you in any form, or should we just let it documented here in case others run into the same issue? I am happy with this solution and don't mind to recompile it myself for the next stable release :)

Here is what I did to install it:
1) Copy the compiled artifact to `/usr/local/MyVendor/ddev/1.15-alpha3/bin`
2) Changed symlink of `/usr/local/bin/ddev` pointing to the self compiled artifact

Or do you recommend something else to do it better? Probably this manual change will break things during future interactings with brew!?

Another question: In the original installation folder exists a `etc/bash_completion.d` file. Do I need this, and if so, can I just copy the original one e.g. from `ddev/1.14.2/etc/bash_completion.d` to my own folder?

**Comment by rfay** [comment]
That's amazing. It probably means that you did somehow get a bad binary from homebrew, but that's hard to do, but maybe it happened. 

What I would do for right now is `brew unlink ddev` and `cp .gotmp/bin/darwin_amd64/ddev /usr/local/bin`. Then you just have your binary in /usr/local/bin.

You can put your bash completions anywhere you want that bash completions work.

I notice that you were using the stable channel of homebrew before. At some point I'd appreciate it if you'd `rm /usr/local/bin/ddev && brew tap drud/ddev-edge && brew install drud/ddev-edge/ddev` just to see if you get a working ddev that way.

**Comment by Moongazer** [comment]
> I notice that you were using the stable channel of homebrew before. At some point I'd appreciate it if you'd `rm /usr/local/bin/ddev && brew tap drud/ddev-edge && brew install drud/ddev-edge/ddev` just to see if you get a working ddev that way.

This seems to help too! Brew installed the same version (1.15-alpha3) from the edge channel and this works also like expected. Maybe there have been some code changes between 1.14 and 1.15 related to the above described issue?! Anyway, it looks like the problem is solved than, thanks again :)

**Comment by rfay** [comment]
Again, glad it's working. But not a code change. I know you'll keep me up to date with future results. I think something odd went on with homebrew; we should have captured the result.
