### ISSUE TITLE
Upgrade repos for Drupal 7, Drupal 8, and WordPress

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#230]
## What happened (or feature request):

* Task request

## What you expected to happen:

We currently run tests against Drupal 7, Drupal, and, and WordPress. All of our repos are currently out of date, including security updates. Given some of the significant changes that have occurred in Drupal 8, we should get onto the 8.3.x branch instead of the current 8.2.x branch.

**Comment by rickmanelius** [comment]
As we discussed offline, there are larger implications in making it so that we don't have to maintain and/or update these 3 repositories. For example, we could clone off of the Drupal mirror https://github.com/drupal/drupal and simply run `ddev config` with the default options when running our tests.

Short term, I'm mostly interested in getting Drupal 8 upgraded to the 8.3.x branch before we run any performance tests in #195. Happy to split out a separate issue for the larger solution, but this is a more focused request.

**Comment by rfay** [comment]
drupal8 upgrade is pending in https://github.com/drud/ddev/pull/236 and https://github.com/drud/drupal8/pull/4

I would really like us to lose this approach, but for @rickmanelius and the purpose of immediate perf testing, here it is.

**Comment by rickmanelius** [comment]
@rfay understood re:above. When this issue is closed out, let's get a different issue filed for a better long term solution.

**Comment by rfay** [comment]
If you have no objection, can we change the scope of this to just drupal8? I'm not sure what pushes us on anything else. 

I spun off the idea of using direct downloads instead of our own forks in https://github.com/drud/ddev/issues/237

**Comment by rfay** [comment]
Drupal 8.3.2 upgrade is done in https://github.com/drud/ddev/pull/236, which has been merged. Does that complete this?

**Comment by rickmanelius** [comment]
@rfay question, it looks like the changelog is still showing 8.3.1. https://github.com/drud/drupal8/blob/master/docroot/core/CHANGELOG.txt#L1.

I can live with ignoring Drupal 7 and WordPress.

**Comment by rfay** [comment]
They failed to update the CHANGELOG.txt for 8.3.2 :) Pretty funny, http://cgit.drupalcode.org/drupal/tree/core/CHANGELOG.txt?h=8.3.2 - if you want to get a commit credit here's an easy patch!

**Comment by rickmanelius** [comment]
Ha! I'll consider this closed :)
