### ISSUE TITLE
ddev auth ssh fails: invalid mount config for type "bind": bind source path does not exist

### ISSUE THREAD

**Issue by Bellangelo** [drud/ddev#2307]
Running ddev auth ssh results in error. 
Here is the output:
`docker: Error response from daemon: invalid mount config for type "bind": bind s
ource path does not exist: /c/Users/[user]/.ssh.
See 'docker run --help'.
Docker command 'docker [run -it --rm --volumes-from=ddev-ssh-agent --user=1000 -
-mount=type=bind,src=//c/Users/[user]/.ssh,dst=/home/[user]/.ssh drud/ddev
-ssh-agent:v1.13.0-built ssh-add]' failed: exit status 125
`
In the docker "user-friendly" message the path is correct but in the command it has an extra slash. Running the command without this extra slash works fine.

The command has the same output in Powershell and Git Bash.

To Re-produce it just run `ddev auth ssh` in one of your projects.

Versions:
DDEV-Local version: v1.14.0-rc1
ddev-ssh-agent: drud/ddev-ssh-agent:v1.13.0
docker: 19.03.8
docker type: Docker Desktop For Windows
docker-compose: 1.25.0-rc4
os: windows 10

**Comment by rfay** [comment]
Could you please update to current ddev (v1.14.2) ? 

Docker Desktop for Windows had a regression where it stopped accepting the "//", but they seem to have fixed that. What version of Docker Desktop for Windows are you using? Current is 2.3.0.3

As a result of that regression, ddev's code was changed in recent alpha releases to lose the "//" as well (which was really helpful). But I think updating to current *edge* ddev release would also fix this, https://github.com/drud/ddev/releases/tag/v1.15-alpha4

**Comment by rfay** [comment]
I confirm that `ddev auth ssh` works fine with Docker Desktop for Windows 2.3.0.3 and ddev v1.4.2

**Comment by Bellangelo** [comment]
I am running Docker Desktop for Windows ( 2.3.0.1 ). 
Upgrading to ddev version 1.4.2 fixed the problem.
Thank you!

**Comment by rfay** [comment]
Glad it's working for you!
