### ISSUE TITLE
DDEV running sluggishly on new MacOS update

### ISSUE THREAD

**Issue by andy-blum** [drud/ddev#2308]
**Describe the bug**
I unfortunately don't have any real comparison data, but anecdotally, DDEV is feeling really slow immediately following the new MacOS update - we're talking ~60s page loads that yesterday were probably in the 5-15s range maximum. I thought it might be an issue in the ddev-edge release, but the performance issues remained even after downgrading to 1.14.2

Is there a way I can run benchmarks or help debug why this is running so slowly?

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Mac OS 10.15.5 (19F101)
 - Docker: Community Edition, 19.03.8
 - ddev: 1.14.2 (also current edge release)
 - global nfs_mount enabled
```
type: drupal8
docroot: /
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
nfs_mount_enabled: true
provider: pantheon
omit_containers: [dba]
use_dns_when_possible: true
```

**Comment by rfay** [comment]
I haven't had any trouble with 10.15.5, but definitely listening. 

Did you also upgrade docker? What version of Docker Desktop for Mac are you running? Current is 2.3.0.3, but I wouldn't expect that to make a difference. 

Please temporarily disable any virus checking that you may have enabled, as that's a classic way to slow things down. 

I assume you're coming from 10.15.4, not from Mojave...  Catalina is definitely slower, but not to the extent you're reporting.

**Comment by rfay** [comment]
If you haven't rebooted, of course, you should.

**Comment by andy-blum** [comment]
Yeah, docker desktop on 2.3.0.3, no anti-virus running, updating from previous version of catalina.

I haven't tried rebooting since observing the issue, but the machine did just reboot after the update. Will re-boot and report back.

**Comment by andy-blum** [comment]
After rebooting and starting/using a couple projects the speed issues seem to be a fluke. Closing.
