### ISSUE TITLE
ERROR: failed to create the CAROOT: mkdir /mnt/c/Users/YOUR_WINDOWS_USERNAME: permission denied - https://ddev.com/ddev-local/ddev-wsl2-getting-started/

### ISSUE THREAD

**Issue by therobyouknow** [drud/ddev#2311]
**Describe the bug**

Followed guide:
https://ddev.com/ddev-local/ddev-wsl2-getting-started/

In this guide, in section "Installing the Linux version of DDEV", it has a step to issue command mkcert -install
When I run this command I get:

```
$  mkdir /mnt/c/Users/YOUR_WINDOWS_USERNAME
mkdir: cannot create directory ‘/mnt/c/Users/YOUR_WINDOWS_USERNAME’: Permission denied
```

**To Reproduce**

As above - issue the command 
`mkcert -install`

**Expected behavior**

For mkcert -install to run successfully

**Screenshots**

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: [e.g. Windows 10, macOS High Sierra]
Windows 10 Pro 64bit
 - Docker version information (use `docker version`) and insert it here.

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

 - ddev version information (use `ddev version`)

```
DDEV-Local version      v1.14.2
commit                  v1.14.2
db                      drud/ddev-dbserver-mariadb-10.2:v1.14.1
dba                     phpmyadmin/phpmyadmin:5
ddev-ssh-agent          drud/ddev-ssh-agent:v1.14.0
docker                  19.03.8
docker-compose          1.25.0-rc4
os                      linux
router                  drud/ddev-router:v1.14.0
web                     drud/ddev-webserver:v1.14.2
```

 - config.yaml contents for the misbehaving project

```
name: wms-develop
type: drupal8
docroot: docroot
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
use_dns_when_possible: true


# This config.yaml was created with ddev version v1.14.2
# webimage: drud/ddev-webserver:v1.14.2
# dbimage: drud/ddev-dbserver-mariadb-10.2:v1.14.1
# dbaimage: phpmyadmin/phpmyadmin:5
# However we do not recommend explicitly wiring these images into the
# config.yaml as they may break future versions of ddev.
# You can update this config.yaml using 'ddev config'.

# Key features of ddev's config.yaml:

# name: <projectname> # Name of the project, automatically provides
#   http://projectname.ddev.site and https://projectname.ddev.site

# type: <projecttype>  # drupal6/7/8, backdrop, typo3, wordpress, php

# docroot: <relative_path> # Relative path to the directory containing index.php.

# php_version: "7.3"  # PHP version to use, "5.6", "7.0", "7.1", "7.2", "7.3", "7.4"

# You can explicitly specify the webimage, dbimage, dbaimage lines but this
# is not recommended, as the images are often closely tied to ddev's' behavior,
# so this can break upgrades.

# webimage: <docker_image>  # nginx/php docker image.
# dbimage: <docker_image>  # mariadb docker image.
# dbaimage: <docker_image>

# mariadb_version and mysql_version
# ddev can use many versions of mariadb and mysql
# However these directives are mutually exclusive
# mariadb_version: 10.2
# mysql_version: 8.0

# router_http_port: <port>  # Port to be used for http (defaults to port 80)
# router_https_port: <port> # Port for https (defaults to 443)

# xdebug_enabled: false  # Set to true to enable xdebug and "ddev start" or "ddev restart"
# Note that for most people the commands
# "ddev exec enable_xdebug" and "ddev exec disable_xdebug" work better,
# as leaving xdebug enabled all the time is a big performance hit.

# webserver_type: nginx-fpm  # Can be set to apache-fpm or apache-cgi as well

# timezone: Europe/Berlin
# This is the timezone used in the containers and by PHP;
# it can be set to any valid timezone,
# see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# For example Europe/Dublin or MST7MDT

# additional_hostnames:
#  - somename
#  - someothername
# would provide http and https URLs for "somename.ddev.site"
# and "someothername.ddev.site".

# additional_fqdns:
#  - example.com
#  - sub1.example.com
# would provide http and https URLs for "example.com" and "sub1.example.com"
# Please take care with this because it can cause great confusion.

# upload_dir: custom/upload/dir
# would set the destination path for ddev import-files to custom/upload/dir.

# working_dir:
#   web: /var/www/html
#   db: /home
# would set the default working directory for the web and db services.
# These values specify the destination directory for ddev ssh and the
# directory in which commands passed into ddev exec are run.

# omit_containers: ["db", dba", "ddev-ssh-agent"]
# Currently only these containers are supported. Some containers can also be
# omitted globally in the ~/.ddev/global_config.yaml. Note that if you omit
# the "db" container, several standard features of ddev that access the
# database container will be unusable.

# nfs_mount_enabled: false
# Great performance improvement but requires host configuration first.
# See https://ddev.readthedocs.io/en/stable/users/performance/#using-nfs-to-mount-the-project-into-the-container

# host_https_port: "59002"
# The host port binding for https can be explicitly specified. It is
# dynamic unless otherwise specified.
# This is not used by most people, most people use the *router* instead
# of the localhost port.

# host_webserver_port: "59001"
# The host port binding for the ddev-webserver can be explicitly specified. It is
# dynamic unless otherwise specified.
# This is not used by most people, most people use the *router* instead
# of the localhost port.

# host_db_port: "59002"
# The host port binding for the ddev-dbserver can be explicitly specified. It is dynamic
# unless explicitly specified.

# phpmyadmin_port: "8036"
# phpmyadmin_https_port: "8037"
# The PHPMyAdmin ports can be changed from the default 8036 and 8037

# mailhog_port: "8025"
# mailhog_https_port: "8026"
# The MailHog ports can be changed from the default 8025 and 8026

# webimage_extra_packages: [php-yaml, php7.3-ldap]
# Extra Debian packages that are needed in the webimage can be added here

# dbimage_extra_packages: [telnet,netcat]
# Extra Debian packages that are needed in the dbimage can be added here

# use_dns_when_possible: true
# If the host has internet access and the domain configured can
# successfully be looked up, DNS will be used for hostname resolution
# instead of editing /etc/hosts
# Defaults to true

# project_tld: ddev.site
# The top-level domain used for project URLs
# The default "ddev.site" allows DNS lookup via a wildcard
# If you prefer you can change this to "ddev.local" to preserve
# pre-v1.9 behavior.

# ngrok_args: --subdomain mysite --auth username:pass
# Provide extra flags to the "ngrok http" command, see
# https://ngrok.com/docs#http or run "ngrok http -h"

# disable_settings_management: false
# If true, ddev will not create CMS-specific settings files like
# Drupal's settings.php/settings.ddev.php or TYPO3's AdditionalSettings.php
# In this case the user must provide all such settings.

# no_project_mount: false
# (Experimental) If true, ddev will not mount the project into the web container;
# the user is responsible for mounting it manually or via a script.
# This is to enable experimentation with alternate file mounting strategies.
# For advanced users only!

# provider: default # Currently either "default" or "pantheon"
#
# Many ddev commands can be extended to run tasks before or after the
# ddev command is executed, for example "post-start", "post-import-db",
# "pre-composer", "post-composer"
# See https://ddev.readthedocs.io/en/stable/users/extending-commands/ for more
# information on the commands that can be extended and the tasks you can define
# for them. Example:
#hooks:
# post-import-db:
#   - exec: drush cr
#   - exec: drush updb
```

 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

Standard setup, nothing special!

**Additional context**
Add any other context about the problem here. Thanks!

I also tried `sudo mkcert -install` and got:
`sudo: mkcert: command not found`

I also tried mkcert -install as root, using the direct path of mkcert and also sudo:

```
$ sudo /home/linuxbrew/.linuxbrew/bin/mkcert -install
Using the local CA at "/root/.local/share/mkcert" ✨
The local CA is already installed in the system trust store!

```

So that _seemed_ to work but it's not correct is it? Because the blog says:

> "you’ll notice that mkcert will use your Windows CA certificates ?:
> `Using the local CA at “/mnt/c/Users/YOUR_WINDOWS_USERNAME/AppData/Local/mkcert`”

ddev config and ddev start work but they don't give me a https local dev URL - which is what I would want and why I am trying to get mkcert to work.

I have this working fine on my full Ubuntu 20.04 operating system when booted into that, but not with Ubuntu 20.04 running over WSL2. I'd like to get the Windows setup working please.

I do wonder if mkcert -install is literally attempting to run that very command:
`mkdir /mnt/c/Users/YOUR_WINDOWS_USERNAME`

to cause the error

`ERROR: failed to create the CAROOT: mkdir /mnt/c/Users/YOUR_WINDOWS_USERNAME: permission denied`

When I literally run the command myself, I get the same error:
```
$ mkcert -install
ERROR: failed to create the CAROOT: mkdir /mnt/c/Users/YOUR_WINDOWS_USERNAME: permission denied
```

One question could be, why is mkcert attempting to create this folder and is there a config for mkcert to make it do this, which I should change to be something correct - i.e.  which works?

**Comment by therobyouknow** [comment]
Raised issue on mkcert as well and linked back from there to here:
https://github.com/FiloSottile/mkcert/issues/270

**Comment by therobyouknow** [comment]
This looks like the solution:

In my` .profile` file there was

`export CAROOT=/mnt/c/Users/YOUR_WINDOWS_USERNAME/AppData/Local/mkcert`

I changed this to

`export CAROOT=/mnt/c/Users/Rob/AppData/Local/mkcert`

And then closed my (only) shell for Ubuntu 20.04 and re-opened it, so that it would re-run .profile

And

**Comment by rfay** [comment]
Please take a look at the [article](https://ddev.com/ddev-local/ddev-wsl2-getting-started/) and see if it misled you somehow, thanks.

**Comment by therobyouknow** [comment]
"root" cause:

> Run `export CAROOT=/mnt/c/Users/YOUR_WINDOWS_USERNAME/AppData/Local/mkcert`. This will make sure that mkcert on Linux uses your Windows certificates when issuing SSL certificates, so you don’t get SSL warnings in your browser on Windows.
> 
> Run `echo 'export CAROOT=/mnt/c/Users/YOUR_WINDOWS_USERNAME/AppData/Local/mkcert' >> ~/.profile` to store this in your profile for future sessions.

I literally ran these commands, with the actual `YOUR_WINDOWS_USERNAME` in them! 

My fault, certainly. Though I could suggest adding in the blog post an additional note to say:

> "***NOTE**: of course, don't actually use `YOUR_WINDOWS_USERNAME` in the command, use your real user name. 
> 
> For example, if you're username is Rob, then the commands would be:
> 
> `export CAROOT=/mnt/c/Users/Rob/AppData/Local/mkcert`
> 
> `echo 'export CAROOT=/mnt/c/Users/Rob/AppData/Local/mkcert'`
> 
> "

(Perhaps put this before the command, so people are primed before they do it)

Most will find this obvious without my suggested note, I think, and do this properly, including me. However, when one is in a rush, perhaps tired, then like I was they might be "click-paste happy". Also, the capitals do make it look like some kind of official environment variable, so that's what probably got me.

Another thing to watch for is the full stops in the English sentence close by the code, that could be accidentally pasted in.

You know, I feel I'm being nit-picky here, but just wanted to help. But perhaps in the future someone else who does the blooper like me will find this solution (and relief) by finding my issue here.

I think you've done a super excellent job with ddev so I'll leave it with you to decide if you want to amend the excellent blog post. Thank you!
