### ISSUE TITLE
override ddev config export folder for drupal 8/9 but keeping settings.ddev.php managed by ddev 

### ISSUE THREAD

**Issue by therobyouknow** [drud/ddev#2312]
**Is your feature request related to a problem? Please describe.**

ddev default location for config export, as defined in settings.ddev.php is sites/all/default/files

I would like this to be configured in ddev to somewhere else, so that I can properly version control the exported config in git along with other site code, e.g. docroot/config/sync

Now, I do know that I can change settings.ddev.php and remove the comment to denote ddev has control over the file.

But my concern is that I might miss out on any future beneficial changes to settings.ddev.php in future versions of ddev, because I'm now controlling the file myself

**Describe the solution you'd like**

specific config export/import path in config.yaml so that ddev then populates the settings.ddev.php from this config, so that the settings.ddev.php file can remain under ddev control and machine generated by it, so that I can benefit from any future changes that ddev provides when generating this file.

So that I can put a config option in there:
config_import_export_path = config/sync

**Describe alternatives you've considered**

None

**Additional context**

None

(As an aside,[not necessary for this issue, but venting my spleen] this path sites/all/default/files concept came from the the community group-think of putting the config in there.

Which to me was a massive source of confusion about the philophy of the configuration initiative in drupal 8, especially with that long string of hash. How on earth was one supposed to git version track config when it's in a place which isn't supposed to be tracked, and moreover it's in a folder with a long hash string as part of the name?!

It made the concept obfuscated, all because I think they thought most would be on shared hosting which wouldn't allow a folder one above the docroot, talk about tail wagging the dog. Anyways...)

**Comment by rfay** [comment]
The settings.ddev.php is included in settings.php. You can override anything you want if you just do it below the settings.ddev.php. You can also enable the include of settings.local.php and do it there if that's more appropriate, as long as the settings.local.php include is below the settings.ddev.php include.

**Comment by therobyouknow** [comment]
Thank you @rfay !
