### ISSUE TITLE
Unable to start ddev project "no "ssl_certificate" is defined for the "listen ... ssl" directive"

### ISSUE THREAD

**Issue by naresh-qed42** [drud/ddev#2313]
~/ddev-projects/drupal-8.9.x(9.0.x*) » ddev restart                                                                                                                      nareshbavaskar@Nareshs-MacBook-Pro
Restarting project drupal-8.9.x...
mkcert may not be properly installed, we suggest installing it for trusted https support, `brew install mkcert nss`, `choco install -y mkcert`, etc. and then `mkcert -install`
Creating volume "drupal-8.9.x-mariadb" with default driver
Building db
Building web
Creating ddev-drupal-8.9.x-db ... done
Creating ddev-drupal-8.9.x-web ... done
Creating ddev-drupal-8.9.x-dba ... done

Recreating ddev-router ... done

Failed to restart drupal-8.9.x: ddev-router failed to become ready: logOutput=2020/06/16 13:12:33 [emerg] 1176#1176: no "ssl_certificate" is defined for the "listen ... ssl" directive in /etc/nginx/conf.d/default.conf:140
nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /etc/nginx/conf.d/default.conf:140
nginx: configuration file /etc/nginx/nginx.conf test failed
ddev-router healthcheck endpoint not responding
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
, err=container /ddev-router unhealthy: 2020/06/16 13:12:33 [emerg] 1176#1176: no "ssl_certificate" is defined for the "listen ... ssl" directive in /etc/nginx/conf.d/default.conf:140
nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /etc/nginx/conf.d/default.conf:140
nginx: configuration file /etc/nginx/nginx.conf test failed
ddev-router healthcheck endpoint not responding
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

**Tried to solve:**
1)ddev rm -a (no luck)
2) curl http://localhost/healthcheck (could not understood - from other issue solution)

It was running fine earlier, don't know what happened.

**Comment by rfay** [comment]
It looks like you deleted your mkcert CA directory probably. Could you please

```
ddev poweroff
mkcert -install
ddev start
```

Thanks!

**Comment by naresh-qed42** [comment]
yeah, it worked. 👍 
What a quick reply...Thank you so much

**Comment by rfay** [comment]
Glad it's working!

**Comment by naresh-qed42** [comment]
This error coming again.while deleting the project and then I have to again the above steps to resolve.
~/ddev-projects » ddev delete drupal90-ddev                                                                                                                              nareshbavaskar@Nareshs-MacBook-Pro
OK to delete this project and its database?
  drupal90-ddev in /Users/nareshbavaskar/ddev-projects/drupal90-ddev
The code and its .ddev directory will not be touched.
A database snapshot will be made before the database is deleted.
OK to delete drupal90-ddev? [Y/n] (yes): yes
project must be started to do the snapshot
Building db
Building web
Creating ddev-drupal90-ddev-db ... done
Creating ddev-drupal90-ddev-web ... done
Creating ddev-drupal90-ddev-dba ... done

Recreating ddev-router ... done

Failed to start project drupal90-ddev: ddev-router failed to become ready: logOutput=2020/06/16 17:27:48 [emerg] 1181#1181: no "ssl_certificate" is defined for the "listen ... ssl" directive in /etc/nginx/conf.d/default.conf:140
nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /etc/nginx/conf.d/default.conf:140
nginx: configuration file /etc/nginx/nginx.conf test failed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
ddev-router healthcheck endpoint not responding
, err=container /ddev-router unhealthy: 2020/06/16 17:27:48 [emerg] 1181#1181: no "ssl_certificate" is defined for the "listen ... ssl" directive in /etc/nginx/conf.d/default.conf:140
nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /etc/nginx/conf.d/default.conf:140
nginx: configuration file /etc/nginx/nginx.conf test failed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
ddev-router healthcheck endpoint not responding

**Comment by rfay** [comment]
You have apparently deleted the files in "$(mkcert -CAROOT)" again somehow?

But use `ddev delete --omit-snapshot <projectname>` to delete a project without starting it.

**Comment by naresh-qed42** [comment]
Nop, not deleted any files in  "$(mkcert -CAROOT)"..
I thought deleting project using  `ddev delete --omit-snapshot <projectname>` command will keep db and container memory in my Laptop (garbage).

**Comment by rfay** [comment]
Deleting the project with `ddev delete` deletes the database. And it deletes the name of the project out of the registry.
