### ISSUE TITLE
How to delete ddev project with `ddev delete` if the directory has been deleted already

### ISSUE THREAD

**Issue by naresh-qed42** [drud/ddev#2314]
/ddev-projects/drupal-9-new(9.0.x*) » ddev list                                                                                                                         nareshbavaskar@Nareshs-MacBook-Pro
unable to create project at project root /Library/WebServer/html/drupal-composer: project root /Library/WebServer/html/drupal-composer does not exist
unable to create project at project root /Library/WebServer/html/ddev-drupal: project root /Library/WebServer/html/ddev-drupal does not exist
unable to create project at project root /Library/WebServer/html/ddev-drupal9-site: project root /Library/WebServer/html/ddev-drupal9-site does not exist
NAME               TYPE     LOCATION                                   URL                             STATUS
ddev-drupal                 /Library/WebServer/html/ddev-drupal                                        project directory missing: /Library/WebServer/html/ddev-drupal
ddev-drupal9-site           /Library/WebServer/html/ddev-drupal9-site                                  project directory missing: /Library/WebServer/html/ddev-drupal9-site
drupal-9-new       drupal9  ~/ddev-projects/drupal-9-new               https://drupal-9-new.ddev.site  running
drupal-composer             /Library/WebServer/html/drupal-composer                                    project directory missing: /Library/WebServer/html/drupal-composer
drupal90-ddev      drupal9  ~/ddev-projects/drupal90-ddev                                              stopped

DDEV ROUTER STATUS: healthy
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~/ddev-projects/drupal-9-new(9.0.x*) » ddev delete ddev-drupal                                                                                                           nareshbavaskar@Nareshs-MacBook-Pro
unable to create project at project root /Library/WebServer/html/ddev-drupal: project root /Library/WebServer/html/ddev-drupal does not exist
unable to create project at project root /Library/WebServer/html/ddev-drupal9-site: project root /Library/WebServer/html/ddev-drupal9-site does not exist
unable to create project at project root /Library/WebServer/html/drupal-composer: project root /Library/WebServer/html/drupal-composer does not exist
OK to delete this project and its database?
  ddev-drupal in /Library/WebServer/html/ddev-drupal
The code and its .ddev directory will not be touched.
A database snapshot will be made before the database is deleted.
OK to delete ddev-drupal? [Y/n] (yes): yes
project must be started to do the snapshot
Failed to start project ddev-drupal: project ddev-drupal project root /Library/WebServer/html/ddev-drupal does not exist

I have tried to delete that project which directory is not available in my local. Tried to find solution on internet but no luck..Thanks!

**Comment by rfay** [comment]
`ddev delete --omit-snapshot drupal-9-new`

**Comment by naresh-qed42** [comment]
Thanks @rfay, it worked 👍

**Comment by a-r-m-i-n** [comment]
Just in case your folder name does not match the DDEV project name and you are looking for the actual project name: 
You'll find a **global_config.yaml** file, in ``~/.ddev/``. There, all projects (key and path) are listed under the key ``project_info``.
✌️

**Comment by rfay** [comment]
And you can actually just delete the line in the global_config.yaml and you'll be rid of the project, as long as you've already done a `ddev poweroff`
