### ISSUE TITLE
Problem with 'Found orphan containers (...) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.'

### ISSUE THREAD

**Issue by Padina14** [drud/ddev#2319]
Prelude:
I tried to integrate an additional container into the DDEV. That does not work. Then I took the configuration out.
After this the  error message, mentioned in the title, occurred after each start of DDEV. But after starting the container DDEV went into the 'paused' status as soon as I started a web request.

i tried to fix this with the `docker-compose up --remove-orphans`. But it does not work.

At least I uninstalled DEEV globally according to instructions and newly installed using the instruction for mac. The error message still appears. But the server luckily runs trouble-free after the first attempts.

I have no idea how to get rid of this error message.
It would be nice, if you could find some pointers in the documentation of DDEV on how DDEV is connected to Docker and how to continue debugging. I think the following information would be useful:

- Table with an overview of log-option and logging-flags
- Notes on helpful places where important configurations are stored (folder-tree-structure)
- Links to good debugging pages of docker and docker-compose

_// german Original text
Ich habe versucht, einen zusätzlichen Container in das DDEV zu integrieren. das funktioniert nicht. Ich nahm die Konfiguration wieder heraus. 
Danach trat die obige Fehlermeldung auf. Nach dem Starten des Container fuhr DDEV in den 'paused' -Status, sobald man einen Webrequest gestartet hat.

Ich habe DEEV einmal global deinstalliert. (gemäß Anleitung) und neu installiert. Die Fehlermeldung taucht immer noch auf. Der Server läuft nach ersten Versuchen störungsfrei.  

Ich habe keine Idee, wie ich diese Fehlermeldung wegbekomme. 
Es wäre schön, wenn man in der Dokumentation ein paar Hinweise finden würde, wie ddev mit Docker verbandelt ist und wie man weiter Debuggen könnte. 

- Übersicht zu Logs
- Hinweise zu hilfreichen Stellen, wo wichtige Konfigurationen hinterlegt sind 
- Hinweise auf wichtige Debugging-Seiten von Docker und docker-compose_

**Comment by rfay** [comment]
This sort-of-bug has been there from forever, it only happens when you do just exactly what you did. 

If you `ddev poweroff` you'll then see the leftover container with a `docker ps -a`. All you have to do is stop it with `docker rm <containername>` - or if you aren't doing anything except ddev, you can just `docker rm -f $(docker ps -aq)` and that will remove all containers.
