### ISSUE TITLE
Build multi-arch (supporting ARM64) versions of ddev binary and docker images

### ISSUE THREAD

**Issue by dennisameling** [drud/ddev#2322]
**Is your feature request related to a problem? Please describe.**
DDEV currently doesn't work on Windows (WSL2) or Linux on ARM devices. We'd need Docker images for ARM64 in order to run DDEV on these platforms.

**Describe the solution you'd like**
Docker images for ARM64 can potentially be built by using the `buildx` command https://www.docker.com/blog/multi-arch-images/, but this would need to be researched. Then, automated tests should run on an ARM64 host (either Linux or Windows WSL2) so that we can be sure that DDEV runs (and keeps running) properly on ARM64.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rfay** [comment]
Opened #2338 about the whole ARM64 and multi-arch process for the new macOS machines and macOS 11.
