### ISSUE TITLE
ddev export-db ><file> creates an invalid export when used with PowerShell

### ISSUE THREAD

**Issue by karikaariainen** [drud/ddev#2329]
**Describe the bug**
ddev export-db followed by ddev import-db renders the site broken.

**To Reproduce**

mkdir test20200624
cd test20200624
ddev config --project-type=drupal8 --docroot=web --create-docroot
ddev start
ddev composer create "drupal/recommended-project:^8"
ddev launch

[edit: install Drupal]

ddev export-db --gzip=false > fromddev.sql
(about 5 Mb)

Create a dump from phpMyAdmin fromphpmyadmin.sql (about 9 Mb).

Drop all tables.

ddev import-db --src=fromddev.sql

Result: "The website encountered an unexpected error. Please try again later." The site needs drush cache-rebuild, but even after that, there are only four views there: Recent comments, Recent content, Who'w new, Who's online block. Front page says "Page not found" while it should say "Welcome" etc.

Drop all tables.

ddev import-db --src=fromphpmyadmin.sql

Result: The site is fully functional immediately.

**Version and configuration information:**

Windows 10, Finnish
PowerShell through ConEmu

Docker 2.3.0.3.
ddev v1.14.2
Database 5.5.5-10.2.31-MariaDB-1:10.2.31+maria (tilde) bionic-log
PHP 7.3.17-1+0 (tilde) 20200419.57+debian10 (tilde) 1.gbp0fda17
Drupal Version 8.9.1
WEB SERVER nginx/1.18.0
PHP MEMORY LIMIT 1024M

config.yaml:

name: test20200624
type: drupal8
docroot: web
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames:
additional_fqdns:
provider: default
use_dns_when_possible: true

No custom configuration.

**Comment by rfay** [comment]
You don't mention going through the Drupal install process? I assume you did that after the composer build?

I just repeated your process exactly, but with the drupal install (using the web) after the composer create; I was unable to recreate your situation. It sounds like what would happen if you dumped a database after a partial install (without completing the form with username and email and such). But that wouldn't explain why your phpMyAdmin dump would work.

BTW with the default args all tables are dropped by `ddev import-db`, so there's no need to drop them otherwise.

**Comment by karikaariainen** [comment]
I forgot to list the install, sorry.

I was using PowerShell inside ConEmu, and I just realized there's NO problem if I just use the Command Prompt. I'll test further to see if the culprit is PowerShell or ConEmu. Maybe something goes wrong at printing to stdin and redirecting to file in that context.  

Yes, dropping of tables was unnecessary, thanks.

**Comment by rfay** [comment]
I do recommend using git-bash on Windows for most things. You'll find that a bash environment is by far the most used and most tested.

**Comment by karikaariainen** [comment]
I use Linux/bash and I wanted to use git-bash but found it horribly confusing with all the slashes and backslashes when referring to file names as I recall, but thanks for your suggestions, I'll reconsider it.

**Comment by rfay** [comment]
In git-bash you can and should use forward slashes for everything, I don't think there's a use for backslashes.

My project directory looks like this:
```
$ pwd
/c/Users/rfay/workspace/d8composer
```

PS is also pretty permissive about forward slashes. CMD is not.

**Comment by karikaariainen** [comment]
Very nice. Thank you so much.

**Comment by rfay** [comment]
Of course if your "comfortable" environment is Linux/bash, you'll want to go to WSL2 AS SOON AS YOU CAN! See setup instructions at https://ddev.com/ddev-local/ddev-wsl2-getting-started/

**Comment by karikaariainen** [comment]
I'm aware of that but hasn't yet looked into it. I will, thanks.

**Comment by karikaariainen** [comment]
**This is only a problem with PowerShell 7**, not with Command Prompt. Also ConEmu isn't a factor.

This produces a dump which creates a broken site when imported back:
ddev export-db --gzip=false > mysite.sql

This one doesn't give any error message when creating the dump, but the result is an invalid .gz file:
ddev export-db > mysite.sql.gz

**Comment by rfay** [comment]
I recommend trying `ddev export-db --gzip=false --file mysite.sql` and see if you get better results.

**Comment by karikaariainen** [comment]
In PowerShell 7
This works: ddev export-db --gzip=false --file mysite.sql
This doesn't work: ddev export-db --gzip=false > mysite.sql
(work = site is functional)

In PowerShell 5 neither work and the latter outputs this error:
ERROR: ASCII '\0' appeared in the statement, but this is not allowed unless option --binary-mode is enabled and mysql is run in non-interactive mode. Set --binary-mode to 1 if ASCII '\0' is expected. Query: '��-'.

**Comment by rfay** [comment]
I think if you inspect the file with an editor you'll find garbage or output at the beginning or the end; also if you use --gzip=true (the default) you'll have an invalid gzipped file. 

It seems the behavior of redirection is different in PowerShell.

Could you please show the whole output of your `ddev export-db`, with the command?

**Comment by karikaariainen** [comment]
The outputs are: 

ddev export-db --gzip=false --file mysite.sql
Wrote database dump from mysite database 'db' to file mysite.sql in plain text format.

ddev export-db --gzip=false > mysite.sql
Wrote database dump from mysite database 'db' to stdout in plain text format.

**Comment by rfay** [comment]
I expected the "Wrote database dump" to have disappeared into the file in the second example.

Please do inspect the damaged output file; I think you'll see right away what's happened. Also, since this is not a sensitive file, you could attach it here as a zipfile.

**Comment by rfay** [comment]
The output of the redirected file should be exactly the same as the result with `--file`, so you can just dump the two ways and do a diff on them.

**Comment by karikaariainen** [comment]
There are 35 differences and they all seem to be non-ascii characters, like ellipsis (three dots), the x between 450x450 etc. The one not working has Windows line endings, the one working has Unix line endings.

**Comment by rfay** [comment]
That's amazing that PowerShell could choose to alter the outgoing stream. Even changing to windows line endings seems inappropriate. 

I don't think there's anything ddev is going to be able to do about this.

**Comment by karikaariainen** [comment]
If you have two syntaxes of which one is known to not work in every context, why not just drop it? Or at least put up a warning. This is particularly decptive because the site resulting from this export-import is **almost** working and you may only realize later that something has gone wrong along the way. Sooner or later this will happen to someone else.

**Comment by rfay** [comment]
I'm able to recreate your results. The actual size of the file when redirected to stdout is huge, more than twice the correct size. Powershell must try to "help you" in some pretty significant ways. 

I assume the problem is buried deep in https://stackoverflow.com/a/40098904/215713 - but now I hate PowerShell more than I ever did before. I've taken it out of my will after all.

I'll make sure that the docs touchup for final v1.15 release uses --file for the default example instead of redirecton.
