### ISSUE TITLE
Add a new `ddev clean` command to remove unused or replaceable items

### ISSUE THREAD

**Issue by ultimike** [drud/ddev#2332]
While on a quest to clear up some hard drive space on my local machine, I discovered that the `~/.ddev/` directory was hiding a large amount of database backups. After confirming with @rfay on Slack, I set about to delete them - when I was through I reclaimed over 20GB of hard drive space (granted, I've been using DDEV for a few years, and have a significant number of projects).  

I think it would be a good idea to add a new command to automate the process. I suggested `ddev clean` above, but I'm not tied to that command name. Maybe `ddev cache-clear` or `ddev reclaim` or `ddev gimme-my-hd-space-back`.

Ideally, when run, the command should remove the following:

- `~/.ddev/<project-name>/mysql.saved/` - possibly from when the DB was moved from bind-mounted to a Docker volume.  
- `~/.ddev/<project-name>/mysql_migrated.back/` - possibly from when the DB was moved from bind-mounted to a Docker volume(?)    
- `~/.ddev/pantheon/<project-name>/` - database backups from each and every `ddev pull`...
- Any other location where .ddev is squirreling away DB backups.  

The command should also report how much disk space was reclaimed.

I would also suggest a couple of options on the command:

- `--dry-run` - does everything except actually deleting any files.  
- `--keep-recent` - keeps any files less than 1 year (or some reasonable time frame) old.

**Comment by rfay** [comment]
`ddev delete images` cleans up docker images. It would be great to have a clean command that would remove everything that is replaceable.

* images
* images-built (if that isn't being cleaned up)
* db snapshots? 
* test tarballs in ~/.ddev (only affects people who run tests locally)

**Comment by rpkoller** [comment]
`ddev delete images` gets rid of images in general if i understood the docs correctly? But in case of a DDEV update another measure would be really useful afterwards. a command deleting only images with version tags < the current version updated to (currently <1.5.1). My current approach after the update was: 

`docker images -a` resulting in a list like: 

```
drud/ddev-webserver               v1.15.1-d9gin-built       694d286e6653        13 seconds ago      1.27GB
<none>                            <none>                    b2eda55daa84        14 seconds ago      1.27GB
<none>                            <none>                    daca591c811a        14 seconds ago      1.27GB
<none>                            <none>                    c5cf75df96df        14 seconds ago      1.27GB
drud/ddev-dbserver-mariadb-10.3   v1.15.1-d9gin-built       b30f0e0e2010        4 minutes ago       498MB
<none>                            <none>                    a9f839b595ac        4 minutes ago       498MB
<none>                            <none>                    7b50491dfa66        4 minutes ago       498MB
<none>                            <none>                    ba6cfb5b5c63        4 minutes ago       498MB
drud/ddev-ssh-agent               v1.15.1-built             018b530fdfb3        4 minutes ago       117MB
<none>                            <none>                    413ca0092f5a        4 minutes ago       117MB
<none>                            <none>                    dd182e99ae45        4 minutes ago       117MB
<none>                            <none>                    e482a6c023fe        4 minutes ago       117MB
drud/ddev-webserver               v1.15.1                   d876b0fe987f        29 hours ago        1.27GB
drud/ddev-ssh-agent               v1.15.1                   f66b0ae743eb        29 hours ago        117MB
drud/ddev-router                  v1.15.1                   968905226762        29 hours ago        204MB
drud/ddev-dbserver-mariadb-10.3   v1.15.1                   0cd436dc8868        29 hours ago        498MB
drud/ddev-dbserver-mariadb-10.2   v1.15.0-wordpress-built   20acd011937f        3 days ago          449MB
<none>                            <none>                    030c77a77427        3 days ago          449MB
<none>                            <none>                    55e200a03d77        3 days ago          449MB
<none>                            <none>                    beaf8dca8a34        3 days ago          449MB
drud/ddev-webserver               v1.15.0-d9gin-built       154c824745d7        4 days ago          1.26GB
drud/ddev-webserver               v1.15.0-wordpress-built   154c824745d7        4 days ago          1.26GB
<none>                            <none>                    ea93efe64cfd        4 days ago          1.26GB
<none>                            <none>                    cfaf4456b493        4 days ago          1.26GB
<none>                            <none>                    627719b86d63        4 days ago          1.26GB
drud/ddev-dbserver-mariadb-10.3   v1.15.0-d9gin-built       a20baa95e301        4 days ago          498MB
<none>                            <none>                    0ed493ff99be        4 days ago          498MB
<none>                            <none>                    581d34466a2b        4 days ago          498MB
<none>                            <none>                    18a8f8996ca9        4 days ago          498MB
drud/ddev-ssh-agent               v1.15.0-built             0f91de04108f        4 days ago          117MB
<none>                            <none>                    59aee9bf708c        4 days ago          117MB
<none>                            <none>                    9c14dee4fe98        4 days ago          117MB
<none>                            <none>                    643a551f63a1        4 days ago          117MB
drud/ddev-webserver               v1.15.0                   b18fef685762        2 weeks ago         1.26GB
drud/ddev-ssh-agent               v1.15.0                   8c8ddc08f20f        2 weeks ago         117MB
drud/ddev-router                  v1.15.0                   932e8559e711        2 weeks ago         204MB
drud/ddev-dbserver-mariadb-10.3   v1.15.0                   9b4ffe7e40ec        2 weeks ago         498MB
drud/ddev-dbserver-mariadb-10.2   v1.15.0                   fe46a4d1a5cf        2 weeks ago         449MB
```
if i try to copy and paste image ids and perform e.g. 

`docker rmi 154c824745d7` 

leading often for images to 

```
Error response from daemon: conflict: unable to delete 154c824745d7 (cannot be forced) - image has dependent child images
```
so you i went stepwise through manually with: 

`docker rmi drud/ddev-webserver:v1.15.0-d9gin-built`

so a big yes please for a more sophisticated and convenient delete command for images of especially older outdated ddev images.

**Comment by rfay** [comment]
So first @rpkoller , you can use `ddev rmi -f` to force image deletion, but first do a `ddev stop`. 

`ddev delete images` tries to delete all *ddev* images that are not the current tagged versions. It may not be perfect. 

Sometimes it's worth it just to delete all images, `ddev poweroff && docker rmi -f $(docker images -q)`

The other day I had 96GB remaining in the docker disk space after deleting everything though, so I just did a docker factory reset.

**Comment by rpkoller** [comment]
@rfay well i even do a `ddev poweroff` before i start do housecleaning tasks in docker.... and the `-f` option is a good idea/suggestion. i will try next time thanks!  

if i understood correctly `ddev delete images` is bascially the thing i've suggested with `--keep recent` in https://github.com/drud/ddev/issues/2332#issuecomment-663309133 (guess i haven't understood its purpose and function in the docs) ...so with the current version 1.15.1 `ddev delete images`deletes all images with version tags < 1.15.1.... i will also give that a try as well... normally i am reluctant to perform a factory reset and wipe everything clean. i try to keep the transfer volume down and not reload stuff if possible.

**Comment by rfay** [comment]
I don't blame you for fearing docker factory reset. However, the only real thing you lose is databases, and I typically keep dumps or snapshots of everything that's important. Testing new insider Docker versions keeps me on my toes on this and just forces me to do that more often than I'd like.

**Comment by rfay** [comment]
@mikebarkas if you'd like to take this one on, here is some strategy:

* With this command, we're only trying to do things that have no direct harm. So avoiding destroying databases, etc. We never touch code.
* Find al the things to delete and then display them with a util.Confirm. (The real problem people might face would be loss of snapshots, so important to point that out well)

* Global: delete ~/.ddev/testcache and ~/.ddev/bin
* Foreach project .ddev:
  * downloads
  * db_snapshots
* Delete all images
* Give guidance on other things that can be deleted that have real consequences (`ddev delete --omit-snapshot` for each project, all images: `docker rmi -f $(docker images -q)`, all volumes (will lose all databases) `docker system prune --volumes`, deleting projects)

I'm torn about where to put this in the command hierarchy. @ultimike asked for `ddev clean` but since it's an unusual command it might be better stashed in `ddev debug clean`. 

@ultimike 's suggestion of `--dry-run` is a good one, so let's add that. I think we might want to leave `--yes` off of this one.

**Comment by mikebarkas** [comment]
Thanks @rfay , I will get started this week.
