### ISSUE TITLE
Support darwin/arm64 on Apple Silicon

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2338]
The announcement was made this week that macOS and mac hardware are going to switch to ARM chips.

This has major impact on DDEV-Local. We'll want to be prepared for the new hardware before it is released in Fall, 2020

- [x] Obtain ARM macOS hardware for testing with macOS 11 Big Sur beta
- [x] Prepare build techniques for Docker images (#2454)
- [x] Improve build techniques to build ddev fat binary with ARM (#2474)
- [x] Inform ddev-live cli build process of required changes
- [x] Make sure that all related resources are updated for ARM
    - [x] Docker Desktop
    - [x] mkcert (https://github.com/FiloSottile/mkcert/pull/284) - we may have to fork, as mkcert maintainer hasn't been responsive lately.

In order to have DDEV-Local ready for before new hardware comes out, we should
- [x] Subscribe to the [Universal App Quick Start Program](https://developer.apple.com/programs/universal/), which costs $500 and includes a loaner ARM machine which is to be returned after the program is complete.

Related: #2322 is about building binary and docker images, and it may come sooner.

**Comment by unn** [comment]
FYI @cyberswat

**Comment by rfay** [comment]
@cyberswat did submit the application for the program, thanks!

**Comment by cyberswat** [comment]
Still have not received a response on this.

**Comment by rfay** [comment]
The application was accepted, but when we got the email, it had like a 24-hour deadline and it was missed among all the other email. 

@cyberswat has resubmitted the application, hopefully we'll do better this time.

* I purchased a Raspberry Pi 4 (and installed 64-bit Raspberry Pi OS) for testing and was able to run ddev on it using https://github.com/drud/ddev/pull/2474 and https://github.com/drud/ddev/pull/2454 - we're making real progress there.
* I spun up an AWS EC2 Ubuntu machine and was able to run things fine (with no db container, those aren't done yet)

Quite a significant amount of build-reorganization will need to be done, as the assumption of amd64 is wired into all the builds.

**Comment by rfay** [comment]
gotip (upcoming v1.16) now has darwin/arm64:
```
rfay@rfay-mbp-2017:~/sdk/gotip/bin$ go tool dist list | grep darwin
darwin/amd64
darwin/arm64
```

**Comment by rfay** [comment]
We will purchase Apple Silicon as soon as it's available; gotip already builds arm64 binary, but of course we have nowhere to run it.

**Comment by rfay** [comment]
We now have a macbook Pro with Apple Silicon. 

Current situation explained in https://www.ddev.com/ddev-local/arm64-apple-silicon-m1-ddev-local-what-does-it-all-mean/ - but the biggest issue is ddev can't work until Docker Desktop does. Waiting for [Docker](https://www.docker.com/blog/apple-silicon-m1-chips-and-docker/).

**Comment by mglaman** [comment]
@rfay I have an Apple Silicon machine as well and can test as well!

**Comment by rfay** [comment]
Will look forward to it! Right now, we're just waiting for Docker to release a tech preview. Docker Desktop doesn't currently start on Silicon.

**Comment by ped** [comment]
Has anyone tried ddev with docker running in a VM on apple M1?  
https://finestructure.co/blog/2020/11/27/running-docker-on-apple-silicon-m1-follow-up

**Comment by rfay** [comment]
Unfortunately, Apple M1 also doesn't have VM support yet. Parallels is also working hard to come up with a tech preview. I don't think there are any options to do this at this point.

**Comment by ped** [comment]
But according to this article: 
https://finestructure.co/blog/2020/11/27/running-docker-on-apple-silicon-m1
and the follow up that i mentioned in my previous comment, this person managed to get a ubuntu vm running on an Apple M1 machine, as well as docker.

With that running it should be possible to run ddev in that ubuntu VM? Maybe not the best solution, but for now that would be better than nothing.

**Comment by rfay** [comment]
Yes, I think you'd be able to get ddev going this way in a Linux VM.

**Comment by ped** [comment]
Can you test that on your MacBook Pro with Apple M1, please? Would be great to know if that actually works! Thank you!

**Comment by rfay** [comment]
I'd love to, but it's off-track for me at the moment. Sounds like fun though! I was hoping you'd try it and tell me :)

**Comment by ped** [comment]
I'd love to try it, but being able to run ddev and docker are the last things holding me back from buying a new MacBook with Apple M1, so I can't test it.

**Comment by ped** [comment]
Hello everyone, 

according to this new [blogpost by Docker](https://www.docker.com/blog/docker-desktop-3-0-0-smaller-faster-releases/) they now have support for apple M1 in their preview build. 

Can one of you with an Apple M1 Mac check this out and test ddev on it please? 

Thanks!

**Comment by rfay** [comment]
Hi @ped  - here's my initial results after a ddev recompile for arm64 and loads and loads of work earlier this year by @dennisameling to make the *images* work 
https://twitter.com/randyfay/status/1337208925289005062

You can follow the progress to production ready in https://github.com/drud/ddev/pull/2687

This should make it into an early v1.17 alpha.
