### ISSUE TITLE
In WSL2 ddev start fails at docker-credential-desktop.exe, "error listing credentials"

### ISSUE THREAD

**Issue by karikaariainen** [drud/ddev#2342]
On a Finnish Windows 10 Pro, I went through the tutorial https://www.ddev.com/ddev-local/ddev-wsl2-getting-started/ and everything works, except when I run ddev start, I get:

docker.credentials.errors.StoreError: Credentials store docker-credential-desktop.exe exited with "error listing credentials - err: exit status 1, out: 'Elementtiä ei löydy.'".
Failed to start firsttest: failed to start ddev-ssh-agent: Failed to run docker-compose [-f /home/kari/.ddev/ssh-auth-compose.yaml -p ddev-ssh-agent up --build --force-recreate -d], err='exit status 255', stdout='', stderr='Creating volume "ddev-ssh-agent_dot_ssh" with default driver
Creating volume "ddev-ssh-agent_socket_dir" with default driver
Building ddev-ssh-agent
[13734] Failed to execute script docker-compose
Traceback (most recent call last):
  File "site-packages/docker/credentials/store.py", line 80, in _execute
  File "subprocess.py", line 411, in check_output
  File "subprocess.py", line 512, in run
subprocess.CalledProcessError: Command '['/mnt/c/Program Files/Docker/Docker/resources/bin/docker-credential-desktop.exe', 'list']' returned non-zero exit status 1.
etc.

"Elementtiä ei löydy." is Finnish for "The element can't be found".

The distro is Ubuntu 20.04 LTS, Docker Desktop is 2.3.0.3.

**Comment by rfay** [comment]
Hi @karikaariainen - There was a version of Docker Desktop that created a bogus .docker/config.json, see https://github.com/docker/for-mac/issues/3785#issuecomment-517791470

I think you might have that. I imagine a docker reset to factory defaults would fix this, also perhaps editing your (host-side)  ~/.docker/config.json.

**Comment by rfay** [comment]
Oh, you might try just `docker logout` as well. Some versions of docker have had the most annoying habit of not being  able to pull images while logged into hub.docker.com, and logging out solves it.

**Comment by karikaariainen** [comment]
This happens when ddev is run from Windows, too (WSL2 switched off). 

Solved by 
```
D:\ddev\mysite>docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: myusername
Password:
Login Succeeded
```

**Comment by rfay** [comment]
Interesting to know. You might want to mention that on one of those other issues. Sounds like you got it working!

Note that you absolutely do not have to be logged into dockerhub to use ddev, everything is anonymous download. But you're definitely seeing a docker bug.

**Comment by karikaariainen** [comment]
Somebody actually mentioned that in an other issue. Specifically loggin in, not out. I'll see if this helps on WSL2, too.

**Comment by karikaariainen** [comment]
Yep, sure does. Before logging in to Docker, `ddev start` fails on both WSL2-Ubuntu-ddev and Windows-ddev. After logging in, it works on both.

**Comment by rfay** [comment]
Thanks for sorting out this problem. 

If I understand, the answer was "`docker login` and then `docker logout` again (logout is optional)

**Comment by ninjaa** [comment]
I had to set  `"credsStore": ""` in my ~/.docker/config.json ... it was previously set to credentials.exe

**Comment by BennyAlex** [comment]
@ninjaa in my config it was set to desktop.exe and I had this bug. On my coworkers pc its also desktop.exe but he dosn't have any problems...

**Comment by uselessvevo** [comment]
> 
> 
> @ninjaa in my config it was set to desktop.exe and I had this bug. On my coworkers pc its also desktop.exe but he dosn't have any problems...

Have you solved your problem?

**Comment by BennyAlex** [comment]
@uselessvevo I just removed desktop.exe (so set it to empty string '')

**Comment by sinisimattia** [comment]
If someone is on Linux (or WSL) and none of the above solutions work, **try starting Docker as sudo**. It might help

**Comment by rfay** [comment]
You mean just starting it once with sudo @sinisimattia ? Because we don't want to be doing that normally, and ddev won't let you run it as sudo.

**Comment by sinisimattia** [comment]
@rfay Yes, only the first time

**Comment by BennyAlex** [comment]
@sinisimattia can you explain, how to do that exactly? I only use ddev, should I create a random container with pure docker first?

**Comment by sinisimattia** [comment]
This error is due to a questionable Docker update for Windows (not specific to ddev), the Docker instance in yout WSL uses the Windows credentials manager and stores your credentials in `~/.docker/config.json`.

Try the follwing command from inside WSL:

```
docker logout
```

If that does not work try it again as sudo (not ideal).

As a last resort you can reset Docker to factory defaults from Docker Desktop (from Windows) and everything should work fine.

**Comment by maciej-gawlas** [comment]
Following solution worked for me:
`In ~/.docker/config.json change credsStore to credStore`

**Comment by ad-on-is** [comment]
`"credStore": "desktop.exe"`
Is there some permanent solution to this? It's annoying, since each time I restart my PC, and start working in WSL,2 I have to apply this workaround.

**Comment by rfay** [comment]
Pretty sure you need to do it on the Windows side, and then docker startup just copies it to WSL2.

**Comment by ad-on-is** [comment]
> Pretty sure you need to do it on the Windows side, and then docker startup just copies it to WSL2.

Ok, and where do I change that on Windows side?

**Comment by rfay** [comment]
You change it in ~/.docker/config.json. (That's .docker/config.json in your home directory)

You might consider experimenting with just removing that file and rebooting or restarting docker desktop and letting docker desktop recreate it.

Here's what mine has in it.

`{"auths":{"https://index.docker.io/v1/":{}},"credsStore":"desktop","currentContext":"default","stackOrchestrator":"swarm"}`

**Comment by ad-on-is** [comment]
> You change it in ~/.docker/config.json. (That's .docker/config.json in your home directory)
> 
> You might consider experimenting with just removing that file and rebooting or restarting docker desktop and letting docker desktop recreate it.
> 
> Here's what mine has in it.
> 
> `{"auths":{"https://index.docker.io/v1/":{}},"credsStore":"desktop","currentContext":"default","stackOrchestrator":"swarm"}`

By `~/.docker/config.json` you mean `C:/users/xxx/.docker/config.json`, right?

Since every time I change it in WSL `home/xxx/.docker/config.json` it gets overwritten.

**Comment by rfay** [comment]
Yes, I'm saying change it (or experiment with just renaming it so docker can create a new one). 

Most docker config inside wsl2 is simply copied from the Windows side.

**Comment by ad-on-is** [comment]
> Yes, I'm saying change it (or experiment with just renaming it so docker can create a new one).
> 
> Most docker config inside wsl2 is simply copied from the Windows side.

I just did, in WSL it still appends credsStore to the config.json

**Comment by rfay** [comment]
What Docker Desktop version are you using please? Note that `credsStore` seems to be correct in current docker desktop 4.1.1

**Comment by ad-on-is** [comment]
> What Docker Desktop version are you using please? Note that `credsStore` seems to be correct in current docker desktop 4.1.1

I was on 3.3.1 and updated to 4.1.1 now. 

- After updatding, I deleted both files C:/users/xxx/.docker/config.json and /home/xxx/.docker/config.json
- Start Docker
- C:/users/xxx/.docker/config.json now only contains `{"credsStore":"desktop"}`
- /home/user/xxx/.docker/config.json now only contains `{"credsStore":"desktop.exe"}`
- Went inside WSL into a folder containing a `docker-compose.yml`
- Executed `docker-compose pull`
- Error: `error getting credentials - err: exit status 1, out: error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: `

Then I did the following:

- Changed /home/xxx/.docker/config.json to `{"credStore":"desktop.exe"}`
- Went into a folder containing a `docker-compose.yml`
- Executed `docker-compose pull`
- Works ✔️

**Comment by rfay** [comment]
I'm glad it's working for you.

**Comment by rfay** [comment]
It looks like most people who had this problem (https://github.com/docker/docker-credential-helpers/issues/24) ended up just deleting the credsStore line

**Comment by ad-on-is** [comment]
> I'm glad it's working for you.

But it doesn't work. 

I have to manually change it to credStore after restarting Docker, as I already mentioned in my original post.

**Comment by rfay** [comment]
Hmm, don't put a big checkmark on posts when things aren't working :)

Please follow this up in one of the many docker issues. Please delete that credsStore line in both Windows and wsl2 side. 

But this isn't the place for this. 

If I were you I'd remove those files in both WSL2 and on Windows, then do a docker factory reset.

**Comment by ad-on-is** [comment]
> Hmm, don't put a big checkmark on posts when things aren't working :)
> 
> Please follow this up in one of the many docker issues. Please delete that credsStore line in both Windows and wsl2 side.
> 
> But this isn't the place for this.
> 
> If I were you I'd remove those files in both WSL2 and on Windows, then do a docker factory reset.

Yeah, my mistake with the checkmark 😅 As I said, I deleted both files

**Comment by rfay** [comment]
I'm almost certain that if you uninstalled Docker (make sure first you have backups of databases - dumps or snapshots), then deleted ~/.docker on both Windows and WSL2, then installed docker, you'd have seen the end of this. The weird docker bug that created it was a few years ago and has long since calmed down.

**Comment by PaulHoza** [comment]
Hello, @rfay , first I want to VERY sincerely thank you for all your work on this wonderful tool.  It's been fantastic.  

Next.. I'll aplogize for reviving this closed thread and adding something somewhat unrelated to it... I found this thread when having my own similar problems on Linux and figured out a solution, so I wanted to add it to this thread for others' reference:

I'm using DDEV v1.18.2 with this docker version on Linux:
```
$ docker --version
Docker version 20.10.12, build e91ed57
```
I was having the same sort of problem of "error listing credentials" after a recent update to ddev and/or Docker (sorry, but I didn't know which happened before the problem showed up.)  I'll paste the full error message below, but I did solve the problem with info from this thread.

I figured out that for some reason, I had no ~/.docker/config.json at all on my machine.  I tried reinstalling Docker and such, but ultimately, I just created that file and pasted in the contents you listed above.  That didn't work until I just removed the contents of the string for credsStore.  After that, everything DDEV is back up & running wonderfully again!  Here are the contents of my ~/.docker/config.json just for completeness:  

`{"auths":{"https://index.docker.io/v1/":{}},"credsStore":"","currentContext":"default","stackOrchestrator":"swarm"}  
`  

Hope this helps someone else down the road!  
Thank you again, Randy! I appreciate you very much.

(Here's the full error I got, just for reference:)

```
$ ddev start
Starting testdev... 
1 error occurred: 
	* error listing credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: `` 
 
 
Failed to start testdev: failed to start ddev-ssh-agent: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-testdev docker-compose -f /home/paul/.ddev/.ssh-auth-compose-full.yaml -p ddev-ssh-agent up --build --force-recreate -d', action='[-p ddev-ssh-agent up --build --force-recreate -d]', err='exit status 1', stdout='', stderr='1 error occurred:
	* error listing credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``

' 
```

**Comment by rfay** [comment]
I'm glad it's working for you!

**Comment by ismaelchaquir** [comment]
> If someone is on Linux (or WSL) and none of the above solutions work, **try starting Docker as sudo**. It might help

using sudo before my docker command solved the issue for me, thanks

**Comment by danztensai** [comment]
> It looks like most people who had this problem ([docker/docker-credential-helpers#24](https://github.com/docker/docker-credential-helpers/issues/24)) ended up just deleting the credsStore line

this one solve the problem, Thank's

**Comment by zoloholic** [comment]
Here's what worked for me with Docker Desktop 4.23.0 (120376) and wsl 2

In ~/.docker/config.json change credsStore to credStore

**Comment by pysany** [comment]
저는 이게 효과 있었어요.
~/.docker/config.json 파일에서 
"docker.exe" 부분을  "" 으로 변경해줬음

**Comment by elliason** [comment]
I have the same problem on Win11 Docker Desktop 4.23.0 (120376), the same problem on every computer start. Deleting "desktop.exe" from credsStore fixes the problem but this needs to be done repeatedly every time computer starts, and its very annoying.

**Comment by chameleonhash** [comment]
> Following solution worked for me: `In ~/.docker/config.json change credsStore to credStore`

This works for me on Windows 11 in WSL2 - Kali Linux distro

**Comment by rfay** [comment]
@LiamKarlMitchell The fix should be the same. You can probably fix also just logging out of docker with `docker logout` or optionally logging out of Docker Desktop. Or by using another Docker provider. Or the fixes shown above. Or by removing ~/.docker/config.json, or by removing ~/.docker.

I haven't heard of the credsStore -> credStore bug for a few years now.
