### ISSUE TITLE
v1.15 Test Plan

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2344]
It's testing week here in the DDEV-Local factory.  We'd love community help, especially with validating the new nginx configurations for your favorite CMSs, but also with every other item that is interesting or relevant to you.  Please use [ddev v1.15.0-rc3](https://github.com/drud/ddev/releases/tag/v1.15.0-rc3) for your testing, it's available in homebrew (macOS, Linux, WSL2) and Chocolatey, and of course you can install other ways as shown in the release notes.

If you find a bug that you're pretty sure is a bug, then just open an issue for it.

To give feedback or ask questions, please just reply on this issue or discuss in slack or another other support channel.

1. MariaDB 10.5: 
    - Install Drupal9 using it, then take a tour
    - Verify that `ddev snapshot` and `ddev restore-snapshot` work
    - Verify that export-db and import-db do the right thing and result in a working site.
2. DDEV-Live integration:
    - Checkout a D8 site
    - `ddev auth ddev-live` with a valid token for the site
    - `ddev config ddev-live` to set up the site
    - `ddev pull` to update database and files
    - Verify site correctness
    - Use `ddev live <command>`, for example, `ddev live list sites`
3. BASH_ENV and addition of vendor/bin to PATH: Verify that `ddev exec 'echo $PATH'` contains /var/www/html/vendor/bin
4. zsh, oh-my-zsh and fish autocompletion:
    - Install ddev via homebrew
    - Run zsh and verify that ddev autocompletion works
    - Run fish and verify that ddev autocompletion works
    - Install manually to oh-my-zsh and verify that it works.
    - Test Powershell completion using the Powershell download and the technique in [https://superuser.com/questions/886951/run-powershell-script-when-you-open-powershell](https://superuser.com/questions/886951/run-powershell-script-when-you-open-powershell)
5. Laravel support
    - Use manual testing approach in [#2249](https://github.com/drud/ddev/pull/2249) to create a new laravel site and verify it.
6. DRUSH_OPTIONS_URL instead of drush/drush.yml
    - Create a D8 site from scratch using the quickstart
    - Verify that drush/drush.yml does not exist
    - Verify that `ddev exec drush uli` works, with correct  URL
7. `ddev launch` problems with specified URL
    - See [#2304](https://github.com/drud/ddev/pull/2304) for the problem
    - Change the router_http_port and router_https_port to alternate ports
    - Use `ddev launch`, `ddev launch -p` and `ddev launch -m` - they should all work correctly
8. Internet timeout improvements
    - Verify that it's possible to increase the timeout in global.yaml
    - Test in slow environment (vm with network conditioning)
9. WSL2 documentation
    - Run through the [WSL2 install documentation](https://ddev.readthedocs.io/en/latest/)  from scratch on a clean machine.
10. New apache and nginx configs, and new way of handling them.
    - Test with a real site on each supported CMS (including php), both apache and nginx
    - Test second docroot for apache and nginx.
11. Global custom commands
    - Add a global custom command and make sure it works correctly.
    - Add a project-level custom command that "shadows" the global one and verify that the project-level command overrides the global.
    - Make sure that CRLF in both global and project-level custom commands are detected and notified (and the command is not installed)
12. Global homeadditions
    - Add contents to ~/.ddev/homeadditions
    - Verify that they get added to the web container home directory on `ddev start`
    - Verify that any project-level homeadditions of the same name overwrite any global items.
13. Export-db handling when project stopped, in wrong directory, etc. Make sure stderr goes the right place.
    - `ddev export-db --gzip=false >junk.txt` should show an error when not in a project directory, and junk.txt should be empty.
    - `ddev export-db --gzip=false >junk.sql` in project directory should start the project and then export the file.
14. Project renaming in same directory
    - Try to rename an existing project with `ddev config --project-name=<newname>` and then `ddev start` it. It should give an error and the path to solve the problem.
15. Hook output streamed as it occurs
    - Add a hook that does a few things slowly - use the example in [#2335](https://github.com/drud/ddev/pull/2335)
    - `ddev start` and watch as the output happens
    - Verify that if input is requested during the hook execution it can be done, for example
    ```
    hooks:
      post-start:
        - exec: "echo hi there && for item in 1 2 3 4 5; do echo $item: $(date); sleep 1; done"
        - exec: "echo 'OK? Y/n' && read x"
     ```
16. Verify that web image behavior is compatible with v1.14 (after rebuild of image with ddev-images)
    * Packages installed (dpkg -l, get list, compare)
    * Configuration files (`docker cp` /etc/php from each container and compare the results)
17. Verify that instrumentation/telemetry behaves correctly, and that people are asked to opt in on a new version.
18. Documentation review

**Comment by rfay** [comment]
My results (updated as I go along). Testing mostly on Windows 10 Home with WSL2 and Ubuntu 20.04, Docker 2.3.0.3.


15. ✅ Worked great, and was even able to interact with the hook output.

**Comment by mglaman** [comment]
I just tried this, and `ddev config ddev-live` came up as an invalid argument.

**Comment by rfay** [comment]
What version of ddev were you using @mglaman ? Was this the first command you had ever issued in that project? I would still think it would work. Had you done the required `ddev auth ddev-live`?

**Comment by mglaman** [comment]
@rfay I downloaded `https://github.com/drud/ddev/releases/download/v1.15.0-rc3/ddev_macos.v1.15.0-rc3.tar.gz`. I was able to use `ddev auth ddev-live` and provide my token. But `ddev-live` came up as an invalid argument for `ddev config`.

**Comment by rfay** [comment]
I'm unable to recreate your result. If you could do a `ddev --version` it would help me, and show the entire sequence of commands. 

```
$ ddev --version
ddev version v1.15.0-rc3
rfay@rfay-mbp-2017:~/workspace/ddltest$ ddev config ddev-live
You are reconfiguring the project at /Users/rfay/workspace/ddltest.
The existing configuration will be updated and replaced.
Project name (ddltest):
```

**Comment by rfay** [comment]
I watched your stream. You downloaded the v1.15 version, but never put it into your path. For a little while (including the auth) you were using an explicit path to the new one. But then you copied a command (`ddev config ddev-live`) that did not include the explicit path.

**Comment by mglaman** [comment]
🤦‍♂️I did the first time to auth, and then probably forgot on the second time. Darn. Thanks for the catch. Writing the summary blog

**Comment by rfay** [comment]
I think all the concerns in https://github.com/drud/ddev/issues/2344#issuecomment-651240678 have been taken care of and v1.15.0 has been released.
