### ISSUE TITLE
PHPMyAdmin page remains active (with contents of another project), after ddev stop issued

### ISSUE THREAD

**Issue by crydotsnake** [drud/ddev#2345]
**Describe the bug**
When i say `ddev stop` to stop a project i can still go to the PHPMyAdmin Page.

**Screenshots**
If i type `ddev describe` it looks like this: 

![Bildschirmfoto 2020-06-29 um 20 06 57](https://user-images.githubusercontent.com/39345336/86040327-2173c880-ba44-11ea-8185-f23ccb924d60.png)

**Versions**
DDEV Version: v1.15-rc1 
Operating System: MacOS Catalina
Docker Version: 19.03.8
Docker-Compose: Version: 1.25.5

But it happens not on every project.

And it seems, when i type `ddev start` on `project1`, it also starts `project2`.

**Comment by rfay** [comment]
Good catch, I confirm this; but it seems to be showing the database of a different project. I imagine you'll see the same.

**Comment by crydotsnake** [comment]
Project1 and 2 are different. They are two seperate projects.

**Comment by rfay** [comment]
Right, I'm saying you're probably seeing the database from the other project in phpmyadmin afte you stop the one. I'm confirming the bug, trying to add some information.

**Comment by crydotsnake** [comment]
If you need any Help, i`m there! :).

**Comment by rfay** [comment]
I've been working on this a bit trying to understand the generated ddev-router nginx configurations. They seem completely right, and I can even reload the nginx and get the same behavior.

Also this happens with both phpmyadmin and mailhog; my bet it it happens with other services.

**Comment by crydotsnake** [comment]
Hello Randy!. I'm on the DDEV Version `v1.15.3` right now. And i dont have the issue there.

**Comment by crydotsnake** [comment]
Hello Randy,

I updated my DDEV Version to `v1.16.0-alpha1` and the issue is still there.

Now I found out that if I call the URL of project 1, for example, the same thing is displayed when I call project 2, even though project 2 contains completely different files.

**Comment by crydotsnake** [comment]
If you want, i can record a video for you to show you the issue.

**Comment by rfay** [comment]
@crydotsnake would love to have you test the PR (#2504) The artifacts are at https://app.circleci.com/pipelines/github/drud/ddev/2760/workflows/252d6e80-289d-464f-a17c-b51da905f989/jobs/27564/artifacts
