### ISSUE TITLE
apache-cgi gets inappropriately configured and Xdebug cannot be enabled if php7.2-ldap is added (v1.14.2, PHP 7.2, apache-fpm)

### ISSUE THREAD

**Issue by NicoHaase** [drud/ddev#2346]
**Describe the bug**
I use Xdebug on a daily basis, and usually enable it using `ddev exec enable_xdebug`. Today, I haven't been able to activate it properly using the following configuration:

```
name: project
type: php
docroot: public
php_version: "7.2"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
additional_hostnames: []
additional_fqdns: []
mysql_version: "5.7"
provider: default
webimage_extra_packages: [php7.2-ldap]
use_dns_when_possible: true
```

**To Reproduce**
1. Start the project
2. Check whether XDebug is enabled using `phpinfo` 
3. Start a SSH terminal using `ddev ssh`
4. Call `enable_xdebug`
5. Check whether XDebug is enabled using `phpinfo`

**Expected behavior**
Xdebug should be enabled not, but it is not

This works properly after changing to `nginx-fpm`, but I'd like to use Apache as this is closer to the live environment

**Comment by NicoHaase** [comment]
Next check: the CLI properly uses that new setting, debugging a shell command like `bin/console` works

**Comment by rfay** [comment]
Thanks for the report, but I'm unable to recreate your results. 

* I set up with `webserver_type: apache-fpm`
* `ddev start`
* `ddev xdebug on` (same as your command, but newer and nicer)
* Both phpinfo.php in web browser and `php -i` inside the container show xdebug enabled.

Could you try this on a clean project, just `mkdir junk && cd junk && ddev config  --webserver-type=apache-fpm && ddev start && ddev xdebug on` ? Create a phpinfo.php to test, or whatever.

I've never heard of this happening though, so keep your eyes open to see if we can find a reason.  

Just a note: I see you adding php7.2-ldap in your config.yaml, it is in there by default in upcoming v1.15.

**Comment by NicoHaase** [comment]
Strange - I cannot reproduce the problem in a new project, but I can neither spot any obvious difference between both configurations. Is there any way to dump the created docker compose configuration?

**Comment by rfay** [comment]
`ddev debug compose-config` or just view `.ddev/.ddev-docker-compose-full.yaml`

However, whether xdebug is enabled is not dependent on anything I know of in the docker-compose config, it's `phpenmod xdebug` inside the web container.

Do you have any custom php config in .ddev/php that might be overriding this? Any other customizations?

It would be interesting to see if `ddev config --xdebug-enabled && ddev start` would change anything. I doubt it.

**Comment by NicoHaase** [comment]
Indeed, using `ddev config --xdebug-enabled` enabled the debugger - but this enables it all the times, right? I'll have a look at the configuration and post differences.

What I've also tried, without success: `ddev stop -RO`

**Comment by rfay** [comment]
Yes, turning it on the config leaves it on all the time, although it's not bad for a workaround, but changing requires a `ddev start`

Could you please look at `ddev logs` on the misbehaving project after you try to `ddev xdebug on` ?

Also, experiment with manually enabling inside the web container. All that is actually going on is shown in /usr/local/bin/enable_xdebug. Look at that file and do the things in it one at a time. 

All it's doing in your case is 
```
phpenmod xdebug
killall -HUP php-fpm 2>/dev/null || true
```

You should be able to see the results of the phpenmod immediately, and see the results after kill -HUP on php-fpm in web stuff.

**Comment by NicoHaase** [comment]
The line

`webimage_extra_packages: [php7.2-ldap]`

makes the difference. Removing it restores the usual behavior. When having that line in my configuration, I cannot enable xdebug

**Comment by NicoHaase** [comment]
It gets stranger from check to check: the PHP versions differ. When having that line enabled, phpinfo shows the configuration is read from `/etc/php/7.2/apache2` (Server API: Apache 2.0 Handler). After removing it, the configuration is read from `/etc/php/7.2/fpm` (Server API: FPM/FastCGI)

**Comment by rfay** [comment]
There isn't actually any difference between the configs in /etc/php/7.2/apache2 and /etc/php/7.2/fpm, but that does sound like a bug.

Interesting about `webimage_extra_packages: [php7.2-ldap]` - that causes an extra docker build (one-time, not at start) to install that package. And it can force changes to config and force many more modules to be updated (probably did). But in ddev v1.14.2, it carefully uses -confOld, to use the old configuration.

**Comment by NicoHaase** [comment]
Maybe that's the problem: that `xdebug_enable` script only reloads Apache when `$WEBSERVER_TYPE == 'apache-cgi'` - but having it set to `apache-fpm` should be a clear advice not to use the common Apache handler, which is the case when using additional packages

**Comment by rfay** [comment]
No, there's no need to reload apache when using php-fpm; apache isn't related to use of xdebug, it's entirely handled inside php-fpm, a separate process. With apache-cgi, it's all one process.

**Comment by NicoHaase** [comment]
And why does phpinfo tell me I'm using `apache-cgi` while I've configured `webserver_type: apache-fpm`?

One missing piece: you've asked for a log, there it is:

```
[30-Jun-2020 14:20:28] NOTICE: Reloading in progress ...
[30-Jun-2020 14:20:28] NOTICE: reloading: execvp("/usr/sbin/php-fpm", {"/usr/sbin/php-fpm", "--nodaemonize", "--force-stderr", "--allow-to-run-as-root"})
[30-Jun-2020 14:20:28] NOTICE: using inherited socket fd=7, "/run/php-fpm.sock"
[30-Jun-2020 14:20:28] NOTICE: fpm is running, pid 1045
[30-Jun-2020 14:20:28] NOTICE: ready to handle connections
[30-Jun-2020 14:20:28] NOTICE: systemd monitor interval set to 10000ms
```

...and I do still think that this is the problem: after enabling xdebug, FPM is restarted, but Apache's configuration is not reloaded. When triggering this manually through `/etc/init.d/apache2 reload`, debugging is possible

**Comment by rfay** [comment]
I'm able to recreate your situation by adding `webimage_extra_packages: [php7.2-ldap]`, so yay!

My bet is that this only occurs when a major new PHP release has happened since the ddev version in use, and that the cascading list of things that have to be installed with php7.2-ldap ends up breaking something about the config. I don't think it should be too hard to chase down, and imaging that it can be recreated by a manual update of php7.2-ldap. 

Changed the title to represent the situation. Thanks so much for your patience in unraveling this!

I imagine that you wouldn't have trouble with https://github.com/drud/ddev/releases/tag/v1.15-rc1 because it has newer images. Also, it has php7.2-ldap from the beginning, but even if using some other extension that required a cascading set of changes it would probably not demonstrate this, because there's nothing that big. 

But a couple of months *after* the release of v1.15, this would probably happen again. It will be good to sort it out.

**Comment by rfay** [comment]
If you're using apache-cgi, then it will require a reload. So maybe there's a second bug? 

How does phpinfo tell you you're using apache-cgi?

**Comment by NicoHaase** [comment]
I have tons of patience if I think I found a bug :) Thank you for your fast support

phpinfo tells me about that in the third line:

**Comment by NicoHaase** [comment]
![Bildschirmfoto von 2020-06-30 16-25-09](https://user-images.githubusercontent.com/1069028/86138157-62281c00-baee-11ea-878a-ee784e866742.png)

**Comment by rfay** [comment]
It does appear that the root of this issue is that somehow we get switched to php-cgi with the forced upgrade.

Here's what happens when the update is done manually in the container. Note that libapache2-mod-php7.2 gets installed on top of existing. With --force-confold, nothing bad should happen, but obviously it does. 
```
$ sudo apt-get install  -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests php7.2-ldap
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libapache2-mod-php7.2 php7.2-bcmath php7.2-bz2 php7.2-cgi php7.2-cli php7.2-common
  php7.2-curl php7.2-fpm php7.2-gd php7.2-intl php7.2-json php7.2-mbstring
  php7.2-mysql php7.2-opcache php7.2-pgsql php7.2-readline php7.2-soap php7.2-sqlite3
  php7.2-xml php7.2-xmlrpc php7.2-zip
Suggested packages:
  php-pear
The following NEW packages will be installed:
  php7.2-ldap
The following packages will be upgraded:
  libapache2-mod-php7.2 php7.2-bcmath php7.2-bz2 php7.2-cgi php7.2-cli php7.2-common
  php7.2-curl php7.2-fpm php7.2-gd php7.2-intl php7.2-json php7.2-mbstring
  php7.2-mysql php7.2-opcache php7.2-pgsql php7.2-readline php7.2-soap php7.2-sqlite3
  php7.2-xml php7.2-xmlrpc php7.2-zip
21 upgraded, 1 newly installed, 0 to remove and 126 not upgraded.
Need to get 7645 kB of archives.
After this operation, 111 kB of additional disk space will be used.
Do you want to continue? [Y/n]
```

**Comment by rfay** [comment]
Here's what the startup code does:

https://github.com/drud/ddev/blob/e249a89200d3e0210e51ff71258e8d2f7425501c/containers/ddev-webserver/ddev-webserver-base-scripts/start.sh#L48-L57

Unfortunately, the install above re-enables `a2enmod php7.2` by placing /etc/apache2/mods-enabled/php7.2.conf and php7.2.load

Such an interesting turn of events. 

A proper fix for this would probably require rerunning the portion of start.sh code above after any additional packages being added.

**Comment by rfay** [comment]
Of course this is pretty obscure, and as of upcoming v1.15, apache-cgi will be deprecated and removed in v1.16. meaning that libapache2-mod-php7.x won't be installed any more. 

A fairly shortsighted approach to just this problem would be to update /usr/local/bin/enable_xdebug to always restart apache, but that's mighty ugly. 

What I'm thinking as of today is that this is too obscure to take on for the v1.15 release cycle. It will be immediately but temporarily solved with the release of v1.15 (and is already temporarily solved in v1.15-rc1), but of course, when another libapache-mod-php7.x comes along, it will be broken again in just this way.

**Comment by rfay** [comment]
Again, Thanks so much for holding on to get to the bottom of this @NicoHaase!

**Comment by rfay** [comment]
Closing, as apache-cgi will be removed in v1.16 and I don't think this can happen then.
