### ISSUE TITLE
Specifying alternate router ports during `ddev config`

### ISSUE THREAD

**Issue by begrafx** [drud/ddev#2352]
This issue was about how to specify the router ports on a machine that already has port 80 or port 443 occupied by something else you don't want to shut down. 

The documentation is at https://ddev.readthedocs.io/en/stable/users/troubleshooting/#webserver-ports-are-already-occupied-by-another-webserver

The ports can be changed by editing the .ddev/config.yaml `router_http_port` and `router_https_port` or using `ddev config` like this: `ddev config --http-port=8080 --https-port=8443`

After changing you must do a `ddev start` again.

Most people find it more useful in the long run to just shut down whatever is conflicting on port 80, and that works for most people. The [docs](https://ddev.readthedocs.io/en/stable/users/troubleshooting/#webserver-ports-are-already-occupied-by-another-webserver) tell how to do it for most situations.

**Comment by rfay** [comment]
Hi and welcome @begrafx  - You entered only a title and nothing else. Is there something we can help you with? Please be specific and give the complete context.

**Comment by begrafx** [comment]
An issue I've found, when DDEV sets up, it defaults to port 80. But I know I already have something using that, so I have to go in to the CONFIG.YAML file and change the HTTP port to 8080 or 8888 or whatever. This seems a long way to go, is there a way to tell DDEV from the start to use a different port? I've looked, and don't find anything about this in the documentation. Thanks.

**Comment by rfay** [comment]
I'm sure you already saw the response above, https://github.com/drud/ddev/issues/2352#issuecomment-652544821, I hope that helps. 

Whenever you start ddev and it hits a port conflict it also gives you the link to https://ddev.readthedocs.io/en/stable/users/troubleshooting/#webserver-ports-are-already-occupied-by-another-webserver to help you sort out port conflicts.

**Comment by begrafx** [comment]
Yes, I saw it as I was typing mine. Thanks. So am I correct in reading this to mean that I can use this to state the desired port to use from the get-go?

**Comment by rfay** [comment]
The best and easiest approach is to clear off the competing port user so you can use a standard port, which is great for development.

The troubleshooting section shows how to do all of the above. 

You can also `ddev config --router-http-port=8080 --router-https-port=8443`, perhaps *after* your initial configuration run, although you can do it before and it will do default values.

**Comment by begrafx** [comment]
OK...

`$ sudo lsof -i :80 -sTCP:LISTEN
Password:
COMMAND   PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
httpd      79 root    4u  IPv6 0xaf6ca6281885aab1      0t0  TCP *:http (LISTEN)
httpd     224 _www    4u  IPv6 0xaf6ca6281885aab1      0t0  TCP *:http (LISTEN)
httpd   22762 _www    4u  IPv6 0xaf6ca6281885aab1      0t0  TCP *:http (LISTEN)
`
I'm using MacOS Mojave. Am I interpreting this correctly, that Port 80 is already being used by MacOS's built-in webserver?

**Comment by rfay** [comment]
Yes, macOS can apache enabled, and it ships with macOS. But it's not "built in", as in it's not necessary for any normal uses of the OS that I know of. You can feel free to disable it and the docs I quoted above tell how.'

**Comment by begrafx** [comment]
I tried using the configuration you gave, and it did not work. 

`$ ddev config --router-http-port=8080
Error: unknown flag: --router-http-port`

**Comment by rfay** [comment]
I apologize, I had it wrong. `ddev config -h` will show you the options, or `ddev help config`, same thing.

The options are `ddev config --http-port=8080 --https-port=8443`

**Comment by begrafx** [comment]
Thank you. That worked.

**Comment by rfay** [comment]
Glad it's working for you.

**Comment by begrafx** [comment]
Again, thank you, @rfay for the prompt assistance. I note you are one of the team members on ddev, so perhaps I could toss in as a possible future addition, instead of (or perhaps in addition to) it defaulting to port 80, perhaps in the `ddev config` process it could ask if you want a different port? So if you wanted to use a different port, you could state that in the process? And if you're happy with Port 80, you just hit "enter" and move on along.

**Comment by rfay** [comment]
The reason it checks during `ddev start` is that the situation can be very different during start. So you might have done "config" a year ago, and are starting ever since then.

**Comment by begrafx** [comment]
Yes, I get that. I'm just saying, currently, if I already know that I'm using a port other than port 80, I know that I am going to have to go through the config process, and then once that is done, go in, edit the .YAML file, and then continue with the process. It would be nice, if I know I'm going to use a different port, to have the `ddev config` process ask me what port I want to use. 

For example, with my system, I know I am, at least 99 times out of 100, going to want to use port 8080. Which means, as it sits, everytime I set up a DDEV project, I have to go in and edit the .YAML file to 8080. Ideally, if there were like a "DDEV.CONFIG" file, that has the defaults in it, (similar to a "SETTINGS.PHP" file in Drupal), where I could just change the port, and have it use the one I want, going forward.

Just an idea for the drawing board. Thanks.

**Comment by rfay** [comment]
It's a good idea. 

Just a question: You found that it was Apache that was the problem right? Why didn't you just disable Apache?
