### ISSUE TITLE
Global Drush launcher does not work for Drupal 9

### ISSUE THREAD

**Issue by mglaman** [drud/ddev#2357]
**Describe the bug**
Ran `ddev exec drush uli` on a Drupal 9 site, and explosions

will triage this after livestream

```
ddev exec drush uli                                                              mglaman@Matts-iMac
Error: Call to undefined method Drush\Drupal\DrupalKernel::prepareLegacyRequest() in phar:///usr/local/bin/drush8/lib/Drush/Boot/DrupalBoot8.php on line 151 #0 phar:///usr/local/bin/drush8/includes/bootstrap.inc(354): Drush\Boot\DrupalBoot8->bootstrap_drupal_full()
#1 phar:///usr/local/bin/drush8/commands/user/user.drush.inc(389): drush_bootstrap(5)
#2 phar:///usr/local/bin/drush8/includes/command.inc(422): drush_user_login()
#3 phar:///usr/local/bin/drush8/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#4 phar:///usr/local/bin/drush8/includes/command.inc(199): drush_command()
#5 phar:///usr/local/bin/drush8/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#6 phar:///usr/local/bin/drush8/includes/preflight.inc(67): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#7 phar:///usr/local/bin/drush8/includes/startup.inc(465): drush_main()
#8 phar:///usr/local/bin/drush8/includes/startup.inc(369): drush_run_main(false, '/', 'Phar detected. ...')
#9 phar:///usr/local/bin/drush8/drush(114): drush_startup(Array)
#10 /usr/local/bin/drush8(10): require('phar:///usr/loc...')
#11 {main}
Drush command terminated abnormally due to an unrecoverable error.                                                        [error]
Error: Call to undefined method Drush\Drupal\DrupalKernel::prepareLegacyRequest() in Drush\Boot\DrupalBoot8->bootstrap_drupal_full() (line 151 of phar:///usr/local/bin/drush8/lib/Drush/Boot/DrupalBoot8.php).
Failed to execute command drush uli: exit status 1
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: [e.g. Windows 10, macOS High Sierra]
 - Docker version information (use `docker version`) and insert it here.
 - ddev version information (use `ddev version`)
 - config.yaml contents for the misbehaving project
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

**Additional context**
Add any other context about the problem here. Thanks!

**Comment by rfay** [comment]
You must site-install drush in D8 and D9. Your project didn't have drush install. `ddev composer require drush/drush`

**Comment by mglaman** [comment]
🤦 yeah, I forgot the `drupal/recommended-project` doesn't include Drush. My bad. Thanks @rfay !

**Comment by rfay** [comment]
Watching your live-stream now. BTW, you don't need ^9 on recommended-project, it's the default.  You *do* need ^8 for a D8 install.

**Comment by rfay** [comment]
Interestingly enough @mglaman drush8 does support `drush uli` on d8+. But not when it hasn't been installed.  Your error was caused by no installation having been done.

**Comment by mglaman** [comment]
@rfay weird. I had imported the remote DB and logged in via the UI. Definitely forgot to add Drush

**Comment by rfay** [comment]
Interesting. I do note that `drush8 uli` works fine on an installed D9, `drush uli` also works fine the same way. Not sure what was happening with you. 

The stack trace when Drupal hasn't been installed is in fact different from the one you posted, it's 

```
$ ddev exec drush uli
Error: Class 'Drupal\user\Entity\User' not found in                          [error]
Drush\User\User8->load_by_uid() (line 26 of
phar:///usr/local/bin/drush8/vendor/composer/../../lib/Drush/User/User8.php)
#0
phar:///usr/local/bin/drush8/vendor/composer/../../lib/Drush/User/UserList.php(103):
Drush\User\User8->load_by_uid('1')
#1
phar:///usr/local/bin/drush8/vendor/composer/../../lib/Drush/User/UserList.php(15):
Drush\User\UserList::getFromParameters(Array)
#2 phar:///usr/local/bin/drush8/commands/user/user.drush.inc(409):
Drush\User\UserList->__construct(1)
#3 phar:///usr/local/bin/drush8/includes/command.inc(422): drush_user_login()
#4 phar:///usr/local/bin/drush8/includes/command.inc(231):
_drush_invoke_hooks(Array, Array)
#5 phar:///usr/local/bin/drush8/includes/command.inc(199): drush_command()
#6 phar:///usr/local/bin/drush8/lib/Drush/Boot/BaseBoot.php(67):
drush_dispatch(Array)
#7 phar:///usr/local/bin/drush8/includes/preflight.inc(67):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#8 phar:///usr/local/bin/drush8/includes/startup.inc(465): drush_main()
#9 phar:///usr/local/bin/drush8/includes/startup.inc(369):
drush_run_main(false, '/', 'Phar detected. ...')
#10 phar:///usr/local/bin/drush8/drush(114): drush_startup(Array)
#11 /usr/local/bin/drush8(10): require('phar:///usr/loc...')
#12 {main}.
```

**Comment by rfay** [comment]
Yeah, I was just testing to see if we could do the drush launcher integration better and avoid some of these failures, and noted that `drush uli` with d9 works fine if it's been installed even with the fallback to drupal8.

Opened https://github.com/drud/ddev/issues/2368
