### ISSUE TITLE
Failed to start the project after nfs mount set enabled

### ISSUE THREAD

**Issue by naresh-qed42** [drud/ddev#2359]
**Details**
tried to implement the steps https://ddev.readthedocs.io/en/stable/users/performance/#debugging-ddev-start-failures-with-nfs_mount_enabled-true
to improve the performance of ddev in **mac os catalina**
the project was running fine but after running a script which given in above link in followed instruction it breaks my ddev start

**Command ran and error**
~/ddev-projects/barschool(develop*) » ddev start                                                                                                                   127 ↵ nareshbavaskar@Nareshs-MacBook-Pro
Starting barschool...
Building ddev-ssh-agent
Creating ddev-ssh-agent ... done

ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
Pushing mkcert rootca certs to ddev-global-cache
Pushed mkcert rootca certs to ddev-global-cache
Creating volume "ddev-barschool_nfsmount" with local driver
Building db
Building web
Creating ddev-barschool-db ... done
Creating ddev-barschool-web ... error
Creating ddev-barschool-dba ...

ERROR: for ddev-barschool-web  Cannot start service web: error while mounting volume '/var/lib/docker/volumes/ddev-barschool_nfsmount/_data': failed to mount local volume: mount :/System/Volumes/Data/UserCreating ddev-barschool-dba ... done

ERROR: for web  Cannot start service web: error while mounting volume '/var/lib/docker/volumes/ddev-barschool_nfsmount/_data': failed to mount local volume: mount :/System/Volumes/Data/Users/nareshbavaskar/ddev-projects/barschool:/var/lib/docker/volumes/ddev-barschool_nfsmount/_data, data: addr=192.168.65.2,hard,nolock: permission denied
Encountered errors while bringing up the project.
Failed to start barschool: Failed to run docker-compose [-f /Users/nareshbavaskar/ddev-projects/barschool/.ddev/.ddev-docker-compose-full.yaml up --build -d], err='exit status 1', stdout='Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
 ---> c768591d5f97
Step 3/6 : ARG username
 ---> Using cache
 ---> b29d21185279
Step 4/6 : ARG uid
 ---> Using cache
 ---> 6a6fdc19430d
Step 5/6 : ARG gid
 ---> Using cache
 ---> 1fb45b47284b
Step 6/6 : RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")
 ---> Using cache
 ---> 347730506bc4

Successfully built 347730506bc4
Successfully tagged drud/ddev-dbserver-mariadb-10.2:v1.14.1-barschool-built
Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
 ---> 9809067f633b
Step 3/6 : ARG username
 ---> Using cache
 ---> a0eb130c4a8c
Step 4/6 : ARG uid
 ---> Using cache
 ---> 4c1c0e8a78f0
Step 5/6 : ARG gid
 ---> Using cache
 ---> 686bd720aad1
Step 6/6 : RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")
 ---> Using cache
 ---> b9376c95a470

Successfully built b9376c95a470
Successfully tagged drud/ddev-webserver:v1.14.1-barschool-built
', stderr='Creating volume "ddev-barschool_nfsmount" with local driver
Building db
Building web
Creating ddev-barschool-db ... done
Creating ddev-barschool-web ... error
Creating ddev-barschool-dba ...

ERROR: for ddev-barschool-web  Cannot start service web: error while mounting volume '/var/lib/docker/volumes/ddev-barschool_nfsmount/_data': failed to mount local volume: mount :/System/Volumes/Data/UserCreating ddev-barschool-dba ... done

ERROR: for web  Cannot start service web: error while mounting volume '/var/lib/docker/volumes/ddev-barschool_nfsmount/_data': failed to mount local volume: mount :/System/Volumes/Data/Users/nareshbavaskar/ddev-projects/barschool:/var/lib/docker/volumes/ddev-barschool_nfsmount/_data, data: addr=192.168.65.2,hard,nolock: permission denied
Encountered errors while bringing up the project.'

Please let me know if you need more information to debug the issue

**Comment by rfay** [comment]
Hi - Your NFS server is denying connections.

If you didn't already set up the NFS server, then you have to do that first, https://ddev.readthedocs.io/en/stable/users/performance/#macos-nfs-setup

Please follow the macOS-specific debugging section at https://ddev.readthedocs.io/en/stable/users/performance/#macos-specific-nfs-debugging .

Please show the contents of your /etc/exports file.

Also, lots of people seem to get results with just a reboot or a `sudo nfsd restart`

**Comment by naresh-qed42** [comment]
/etc/exports file
`# <ds-nfs docksal
/Users 192.168.64.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

/System/Volumes/Data/Users/nareshbavaskar/workspace -alldirs -mapall=501:20 localhost `
followed suggested link step for mac os

and still facing an error
~/ddev-projects/barschool(develop*) » ddev debug nfsmount                                                                                                                nareshbavaskar@Nareshs-MacBook-Pro
NFS does not seem to be set up yet, see debugging instructions at https://ddev.readthedocs.io/en/stable/users/performance/#debugging-ddev-start-failures-with-nfs_mount_enabled-true
Details: error=failed to StartContainer: API error (500): error while mounting volume '/var/lib/docker/volumes/testnfsmount/_data': failed to mount local volume: mount :/System/Volumes/Data/Users/nareshbavaskar/ddev-projects/barschool:/var/lib/docker/volumes/testnfsmount/_data, data: addr=192.168.65.2,hard,nolock: permission denied
output=

and Thanks for the reply quickly  :)

**Comment by rfay** [comment]
You had your /etc/exports set up for Docksal, which takes it over.

It's certainly possible to have them co-exist, but the way that I recommend to do this is 
1. `sudo mv /etc/exports /etc/exports.docksal`
2. Run the ddev macos nfs installer, which will install /etc/exports with the line you need for ddev.
3. Get ddev working with nfs
4. Consolidate the two /etc/exports files.

**Comment by naresh-qed42** [comment]
oh yeah, it's working now, and NFS mount enabled:	true
thanks for the help @rfay 
(if you have any tips for speed up my Drupal 8 multisite project please share it, using mac os Catalina and docker for desktop)

**Comment by rfay** [comment]
Glad it's working for you!

You'll like the speed of ddev with NFS. If you want to live on the edge though, try Docker Edge, which has a new caching feature which is really fast, but not fully trustworthy perhaps. See https://github.com/drud/ddev/issues/2278

Do *not* use NFS and *also* enable mutagen caching. It just slows things down. One or the other. 

The edge version of Docker is working OK, so if you don't like the mutagen feature you can just turn it off and things will work fine.

**Comment by naresh-qed42** [comment]
Thanks for the suggestion, will definitely check that out

**Comment by MKorostoff** [comment]
The steps in https://github.com/drud/ddev/issues/2359#issuecomment-654404977 solved this for me

**Comment by jblechinger** [comment]
> Also, lots of people seem to get results with just a reboot or a `sudo nfsd restart`


I also had problems with nfsd but only if i **rebooted** my mac (Osx 12.2.1).
I fixed it by adding a script that runs 'nfsd update' on system boot.
I had the same error message as @naresh-qed42  mentioned but only if i rebooted my system.



> '/var/lib/docker/volumes/testnfsmount/_data': failed to mount local volume: mount :/System/Volumes/Data/Users/nareshbavaskar/ddev-projects/barschool:/var/lib/docker/volumes/testnfsmount/_data, data: addr=192.168.65.2,hard,nolock: permission denied
> output=

**Comment by rfay** [comment]
Wow, I didn't even know about `nfsd update`:
```
     update   Sends a SIGHUP to the running nfsd daemon to cause it to update
              its configuration.
```

So that would just cause nfsd to reread the (updated?) config.
