### ISSUE TITLE
Changes in files aren't notified to the host on macOS or Windows with nfs-mount-enabled (gatsby/gulp/etc) (inotify/fsnotify)

### ISSUE THREAD

**Issue by rvilar** [drud/ddev#2361]
**Describe the bug**
We are using ddev with a Gatsby environment, and we are using the Hot Module Reload (HMR) for developing purposes: when someone make a change in a JS or SCSS file, gatsby compiles the source and shows changes in live. Using Catalina (in Mojave, it works perfectly) when someone make a change in a file, the server aren't notified to make the hot reload. If I access to the server and I make the change directly there using vim, the HMR works and I can see the changes in live.

**To Reproduce**
1. Access to the server using `ddev ssh`
2. Once there execute `gatsby develop`
3. Open a JS file and make a change
4. See there is no change in gatsby console after the change.
5. Open a new terminal with `ddev ssh` and open the same file (or another) using vim. Make a change and you can see the HMR is been notified and compile the source files

**Expected behavior**
The behavior have to be the same in both cases. Other people in our team are using macOS Mojave and it works well.

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macOS Catalina
 - Docker version information: 19.03.8 (docker compose 1.25.5)
 - ddev version information: 1.14.2
 - config.yaml contents for the misbehaving project
```
name: testproject
type: php
docroot: ""
php_version: "7.3"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
omit_containers: [db, dba]
use_dns_when_possible: true
timezone: Europe/Madrid
disable_settings_management: true
```
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them? We have a little configuration for apache but doesn't affect this problem.

**Comment by rfay** [comment]
I assume you're talking about the inotify or fsnotify behavior. If you're using nfs_mount_enabled, NFS predates inotify, so notifications can't happen. I doubt that the difference would be Mojave vs Catalina, but NFS will definitely do it. 

For a perhaps similar issue, you might want to look at https://stackoverflow.com/questions/62701304/how-to-automatically-build-css-inside-a-ddev-project, which uses the watch inside the container.

**Comment by rfay** [comment]
You also may want to try out the edge version of docker, which uses mutagen caching and does support inotify. See https://github.com/drud/ddev/issues/2278 - Some folks with the same needs are very happy with mutagen caching.

**Comment by rvilar** [comment]
Thank you very much @rfay for your early response. I have updated docker to the last edge version and it works perfect! The performance is superb and with Drupal and composer it works...uauu!

I just wanna say thank you so much for this great tool and I will try to do my best to report any bug and to solve it if I jave enough knowledge.

**Comment by rfay** [comment]
Note that the version of Docker referred to here has long been removed, they gave up on it. But you can use mutagen using https://github.com/cweagans/ddev-mutagen, which is explicitly set up for this use-case. 

I expect that we'll have built-in mutagen at some time soon.

**Comment by rfay** [comment]
Possible resource: https://github.com/fsnotify/fsnotify
