### ISSUE TITLE
Consider setting DRUSH_LAUNCHER_FALLBACK only for Drupal 7

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2368]
**Describe the bug**

Since the arrival of drupal/recommended-project, people don't remember to `ddev composer require drush/drush` in their drupal8+ project, and as a result we get support questions about drush8 failures, which are pretty nasty stack traces.

DDEV-Local has drush launcher in the web container as /usr/local/bin/drush and /usr/local/bin/drush8 as $DRUSH_LAUNCHER_FALLBACK.

But I think maybe we shouldn't offer DRUSH_LAUNCHER_FALLBACK except on Drupal7, where it's useful. 

Asked for suggestions about this in Drush slack, https://drupal.slack.com/archives/C62H9CWQM/p1594213877202500

However, drush8 does work on a number of things in d8/9, including `drush uli`

**Comment by weitzman** [comment]
I think D7-only is great, if you can determine that. I quote from https://docs.drush.org/en/master/install/

> Drush only supports one install method. It requires that your Drupal site be built with Composer and Drush be listed as a dependency.

**Comment by mglaman** [comment]
+1 supports silly folk like me from opening issues :)

**Comment by rfay** [comment]
I like how drush 8.3.5 supports newer Drupal on some commands, although I do wish that people would understand that you need to site-install drush 10+ these days. 

Closing this though, the current approach is adequate. And @mglaman 's problem was different, not sure what happened.
