### ISSUE TITLE
Support sequelace in addition to sequelpro

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2369]
**Is your feature request related to a problem? Please describe.**

[sequelace](https://github.com/Sequel-Ace/Sequel-Ace) seems to be a drop-in replacement for sequelpro, which is poorly maintained these days (and the released version doesn't work with mysql 8)

- [ ]  Support SequelAce as if it were sequelpro
- [ ] Add "sequelace" as an alias for "sequelpro"
- [ ] Docs update

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kaystrobach** [comment]
Consider installation via brew and via appstore

**Comment by JCL324** [comment]
FYI, I have the most recent "nightly" build for Sequel Pro that does support mySQL 8. Get it here: https://sequelpro.com/test-builds. It's also crashes less and has multiple filters.

**Comment by rfay** [comment]
Fixed in https://github.com/drud/ddev/pull/2452, will add it to an alpha prerelease before too long.
