### ISSUE TITLE
Increase upload limit of 100M

### ISSUE THREAD

**Issue by webdevsuperfast** [drud/ddev#2378]
I'm fairly new to DDev coming from Local and Laravel Valet, can you point me where to the change the upload limit? It's currently set to 100M.

**Comment by rfay** [comment]
Do you need to upload something larger than 100M? That's quite unusual.  Can you say more about what you're trying to accomplish?

**Comment by webdevsuperfast** [comment]
Coming from both Local and Laravel Valet, both allowed me to increase upload limits. I'm trying to test out All-in-One WP Migration where backup sizes can be large. Just needed direction to change the values.

**Comment by rfay** [comment]
It's easy to change the limit in the web container - just override nginx and php configurations. But it's hard to do it on the ddev-router, which also has to have an nginx change. 

Again, there are very, very few servers anywhere on the internet that allow a 100M upload.  So I'm a little lost why you have to do that. 

You can change web container nginx configuration as described at https://ddev.readthedocs.io/en/stable/users/extend/customization-extendibility/#providing-custom-nginx-configuration

You can change web container PHP configuration as described at https://ddev.readthedocs.io/en/stable/users/extend/customization-extendibility/#providing-custom-php-configuration-phpini

If you change both of those, you can use the https://127.0.0.1 addresses (not the ddev.site addresses) and you'll be able to have ginormous upload limits.

**Comment by rfay** [comment]
You're aware that you have full access to the entire command line inside the web container with `ddev ssh` and `ddev exec` right?

**Comment by rfay** [comment]
My own experience is that any time you need an upload limit higher than about 20-30M, the design needs to be switched to a command-line approach (rather than a POST).

**Comment by webdevsuperfast** [comment]
@rfay thanks for pointing me to the right direction.
