### ISSUE TITLE
Implement platform.sh integration

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2384]
Pantheon and ddev-live have explicit integration in ddev. Platform.sh should have it too!

**Comment by wizonesolutions** [comment]
And Lando has a partnership with Platform.sh. They actually parse the `.platform.app.yaml` file. I don't know if DDEV wants to go that far, but some form of integration would be good to be competitive for developers who work with Platform.sh.

**Comment by cferthorney** [comment]
I'd love to see something as tight as the pantheon plugin is, or even better using the actual platform images too (Again similar to how [Lando's integration](https://docs.lando.dev/config/platformsh.html#getting-started) is now doing it) (This may be possible updating the images, but I feel if I'm customising the dockerfiles to that extent and when things go wrong it's my problem to sort, if its built in to be able to, at least testing etc would be better)

**Comment by rfay** [comment]
Thanks! I've tentatively marked this for the next major release. However, there's way too much marked 😸

**Comment by jameswilson** [comment]
Just noticed this revealing post on Platform.sh community slack. There is a hole here that other community members have been looking to fix:

> Hi, I need a local development environment that just works, with minimal likelihood of falling into a command line rabbit hole that never gets resolved. I need to pull my Platform.sh site code and data, update modules (with Drush not composer, as it’s a Drupal 7 site), and push it back to Platform. I know Lando is supposed to be the app the end all apps. I have encountered a million problems with it and can’t get it to work. Now I can’t even tell if there’s a current version or not. I install it, and 3 days later I’m still trying to figure how to resolve fatal errors. I also tried Vagrant and had a similar problem. I need to cut my losses here and just get something that works. I’m on an 8 kachillion dollar MacOS laptop. Isn’t there something I can get that just allows me to be be dumb and it will still work? This seems like a reasonable expectation at this point in technology. I love Platform, but I am months overdue to update a site on it that I could update really easily in some of the competing Drupal hosts via on-server dev. I am not complaining here - I just really need to update my site and local CLI dependent apps are not working. What app should I use. Please help - I really need to get this working, Thank you in advance!

Someone then responded:

>  I’m uber new here and just now testing platform. I’ve used lando and for the last year switched to DDev for the various reasons you mentioned. I’ve found it to be great, but not sure of the hoops I’ll need to navigate to work with platform. I hope not many. Again, super new to platform, but I really really hope it’s a easy thing to use DDevI can say with complete confidence that the support for DDev local is amazing.  The slack channel for DDev local on Drupal slack is fantastic. I dare say DDev has been fun. If nothing else you might just try it and know for yourself, if you don’t mind doing drush then ddev isn’t a scary thing or much more to wrap your head around.

Ddev is winning hearts and minds.

**Comment by jameswilson** [comment]
From same thread on Platform community slack, someone has also written a docker wrapper for platform: 

https://gitlab.com/contextualcode/platform_cc

**Comment by rfay** [comment]
The new Platform.sh integration made it into ddev v1.17.0-alpha5, I hope you'll all try it out, https://github.com/drud/ddev/releases/tag/v1.17.0-alpha5
