### ISSUE TITLE
ddev composer create should provide --yes/-y flag

### ISSUE THREAD

**Issue by benkyriakou** [drud/ddev#2387]
**Describe the bug**

Command-line options for `composer create-project` are passed through from `ddev composer create`. However, `--no-interaction` is a special case because I'd expect it to skip all prompts, but `ddev composer create` [has its own prompt](https://github.com/drud/ddev/blob/master/cmd/ddev/cmd/composer-create.go#L57) before running `composer create-project`. This prompt is not affected by `--no-interaction`.

**To Reproduce**
1. `ddev composer create --no-interaction "drupal/recommended-project:^8"`

**Expected behavior**

The command would run without any prompts.

**Screenshots**

![image](https://user-images.githubusercontent.com/6502501/87692415-a4568c00-c783-11ea-806d-3a65e427047e.png)

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Ubuntu 19.04
 - Docker version information (use `docker version`) and insert it here.
```
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 00:59:59 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:58:31 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
 - ddev version information 1.15.0
 - config.yaml contents for the misbehaving project
```
name: foo
type: drupal8
docroot: web
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
use_dns_when_possible: true
```

 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

**Comment by rfay** [comment]
It actually does support --no-interaction, which is talking to composer, but you need to give *ddev* -y, because ddev is asking there. So `ddev composer create -y --no-interaction "drupal/recommended-project:^8"`

**Comment by benkyriakou** [comment]
Unfortunately, on my machine, running that command still gives me the prompt. I tried a bunch of different invocations with different uses of -y but none of them seem to change the output.

**Comment by rfay** [comment]
I guess I'm just totally wrong. I don't see it in `ddev composer -h` or `ddev composer create -h`. 

Someone once ran `ddev composer create` in their home directory. It was not good. That's why that's there.

**Comment by rfay** [comment]
Just a note that `echo y | ddev composer create ...` works fine as a workaround.
