### ISSUE TITLE
Wildcard subdomains / hostnames

### ISSUE THREAD

**Issue by j6s** [drud/ddev#2391]
**Is your feature request related to a problem? Please describe.**
I have recently found myself working on a project that does sub-domain routing based on generated data
(e.g. `{UUID}.demo.myapp.com`).

While developing I found it a bit cumbersome to add new hostnames to the configuration file and restart ddev
everytime I added a new demo page. That in turn made me wish for wildcard subdomains / hostnames

**Describe the solution you'd like**
Ideally, it would be possible to use wildcards in `additional_hostnames` like this:
```yaml
additional_hostnames:
    - '*.demo.myapp'
```

**Additional context**
While trying to find out whether or not this already existed I stumbled over the implementation detail, that
the `ddev.site` domain is actually registered and just points to `127.0.0.1` to make setup easier. If a user is
offline however, entries in `/etc/hosts` are being generated.

With the online DNS setup wildcards should be fairly easy to support since you would just need to tell
ddev-router (which runs haproxy I think?) about the wildcard.
I suspect that the offline `/etc/hosts` setup is why wildcard hostnames could be an issue since there
are no wildcards in `/etc/hosts`.

**Comment by rfay** [comment]
Well, I didn't mean to but I fiddled with it a bit and #2391 seems to make it work. It can never work if /etc/hosts is in play, only when ddev.site or a similar TLD is used.
