### ISSUE TITLE
Increase phpMyAdmin memory limit or provide a way to override

### ISSUE THREAD

**Issue by bfuzze** [drud/ddev#2418]
**Is your feature request related to a problem? Please describe.**
I am trying to increase the memory limit for the phpmyadmin instance configured with the DDev development environment.  It does not seem to inherit from the custom .ddev/php/my-php.ini.  The default limit is too low for most common applications.

**Describe the solution you'd like**
Ideally, I'd like to be able to define custom php.ini settings to be appended to and override existing settings in a file called .ddev/php/phpmyadmin.ini

**Describe alternatives you've considered**
I can not find where the phpmyadmin (dba) container is configured. Presumably it is just using the base image, but then where is the base image specified so I can not adjust the build config. 

Thanks.

**Comment by rfay** [comment]
In v1.15+ it's actually quite high. Are you using v1.15+?  It was bumped to 1024MB in https://github.com/drud/ddev/pull/2269 

But I strongly recommend using `ddev import-db` or one of the many other techniques for interacting with the database. See https://www.ddev.com/ddev-local/ddev-local-database-management/

**Comment by rfay** [comment]
No response from OP, so closing, since the memory limit is very high currently. Happy to continue the conversation.

**Comment by RalfEisler** [comment]
I have the same problem. I need much more than 1024MB because of Composer V1. I cannot update to V2 at the moment and need the higher memory limit.
