### ISSUE TITLE
Feature Request - ddev launch <otherSiteName>

### ISSUE THREAD

**Issue by CreateSean** [drud/ddev#2419]
**Is your feature request related to a problem? Please describe.**
I'd like to use the `ddev launch` command to open a site outside of the currently directory

**Describe the solution you'd like**
If I'm looking at Site A  then `ddev launch` should open site A as expected, however I'd like to have the option to open Site B without navigating to site B's directory using `ddev launch -S SiteB` where -S is a parameter to open SiteB or some other site.

**Describe alternatives you've considered**
There are none available

**Additional context**
I find myself often switching to other sites I have set up locally so I can login to the CMS and copy various settings to the site I"m currently working on. Having this option would save me time and make things simple.

**Comment by rfay** [comment]
I think the answer to this one is https://github.com/drud/ddev/issues/2128, which is much more general, making it so you can run any command with context. 

Of course... you *can* just use bookmarks in your browser :)

**Comment by rfay** [comment]
Closing in favor of #2128
