### ISSUE TITLE
Documentation Audit

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#242]
## What happened (or feature request):

* Feature Request

## What you expected to happen:

A lot has changed between ddev v0.1 and v1.0. It would be incredibly helpful to review our CLI helper text and read the docs end to end to ensure that:

1. The information is self-consistent.
2. There are no major gaps or items missing.
3. We are linking to relevant blog articles and/or youtube videos that we've produced.
4. That all of our public repos meet our stated standards.

Any improvements that are specific to ddev's documentation should be noted in this ticket or #251.

## Related source links or issues:

* [Publishing Repositories](https://github.com/drud/community/blob/master/development/publishing_repositories.md)
* #251

**Comment by rickmanelius** [comment]
As stated in another thread https://github.com/drud/ddev/issues/251#issuecomment-315406863, we have 3 sources of information:

* [ddev GitHub Project README.md](https://github.com/drud/ddev/blob/master/README.md)
* [ddev RTD Documentation Site](https://ddev.readthedocs.io/en/latest/)
* [ddev project website](https://github.com/drud/ddev/issues/355), which doesn't exist yet.

IMHO, while we cannot completely eliminate overlap and some redundancy, I feel the intention of each endpoint is different. 

* GitHub project page: This provides a brief overview to gain interest and quickly send them to another location to learn about features, getting started, contributing, support, etc.
* Documentation: Goes into the nitty gritty of requirements, installation, functionality, developing, etc.
* Project Page: A marketing site that focuses primarily on features, benefits, end-user value, the branding, etc. 

Unless there is disagreement on these intentions, this helps us better evaluate the content, organization, and tone of each endpoint.

**Comment by rfay** [comment]
Let's reopen this if/when it becomes a priority.
