### ISSUE TITLE
Document performance tuning made to each image

### ISSUE THREAD

**Issue by damienmckenna** [drud/ddev#2421]
It seems like each Docker image has certain settings defined to aid with performance. It would be useful to document the settings.

**Comment by rfay** [comment]
For the DB server, it's pretty easy, `ddev ssh -s db` and examine /etc/my.cnf (also here: https://github.com/drud/ddev/blob/master/containers/ddev-dbserver/files/etc/my.cnf)

For the webserver, nginx.conf is in your project's .ddev/nginx_full/nginx-site.conf

I guess PHP might be interesting too, it's easy to browse those at https://github.com/drud/ddev/tree/master/containers/ddev-webserver/ddev-webserver-base-files/etc/php, or with `ddev ssh` and examine `/etc/php/<yourversion>/php.ini`.  In [php.ini](https://github.com/drud/ddev/blob/master/containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.3/fpm/php.ini) you'll see that opcache has very high settings for "modern" zillions of files CMSs like TYPO3, Drupal9, Magento2:

```
[opcache]
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=500
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=1000000
```

**Comment by rfay** [comment]
No response from OP, but happy to continue this conversation. Closing.
