### ISSUE TITLE
`ddev composer create` should copy the *contents* of created project, not remove project contents, and should use a non-shared directory

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2422]
**Describe the bug**

We haven't had many, but we had another instance of somebody pushing past all the warnings and deleting the wrong directory with `ddev composer create`, see https://www.drupal.org/forum/support/installing-drupal/2020-07-26/ddev-install-of-drupal-9-wipes-out-everything-in-parent#comment-13764911

**To Reproduce**

Easy to reproduce, just do as reported (quite completely) in https://www.drupal.org/forum/support/installing-drupal/2020-07-26/ddev-install-of-drupal-9-wipes-out-everything-in-parent#comment-13764911

**Expected behavior**

`ddev composer create` doesn't need to be as dangerous. Even though it warns and does its best, it just doesn't have to be so dangerous.

Instead of removing everything in the target directory (project root), instead copy (with overwrite) the full contents of the newly created subdirectory.

**Comment by rfay** [comment]
In addition, this will be massively faster on some platforms like traditional windows if we don't build on a docker-shared directory. Instead of building in a subdirectory, build in /tmp or elsewhere  and then move it.

**Comment by hanoii** [comment]
Found this by accident, but #5499 fixes this in a different manner.
