### ISSUE TITLE
project-type=drupal8 vs project-type=drupal9: Upgrading database to MariaDB 10.3

### ISSUE THREAD

**Issue by begrafx** [drud/ddev#2429]
Not a "Bug Report", more of a "use question". 

Say for example, I set up a Drupal 8 Site within DDEV. So of course the CONFIG.YAML file is going to say

`type: drupal8`

but... here's the question... What if I upgrade that Drupal 8 site to Drupal 9? Do I need to go back into the CONFIG.YAML file and update that to "drupal9" or does it make any difference?

**Comment by rfay** [comment]
For a long time, drupal9 had the same requirements as drupal8, but then at the last minute, they made MariaDB 10.3 a requirement.

So here's your get-ready-to-upgrade-a-drupal8-ddev-project instructions:

1. Make a database backup - use `ddev export-db` or any tool you like.
2. `ddev stop`
3. Change your project to MariaDB 10.3: `ddev config --mariadb-version=10.3`
4. `ddev start`

When I've tried this, it upgraded the database just fine and nothing further was required. If somehow in your case the database upgrade fails, just use `ddev import-db` to import the backup you made.

**Comment by rfay** [comment]
No response from OP but I think the answer explains what to do.
