### ISSUE TITLE
DDEV doesn't work wtih WSL1: Invalid Compose file, services.<>.ports should be a number or an object

### ISSUE THREAD

**Issue by gitfunk** [drud/ddev#2433]
**Describe the bug**
I am trying to install and start a Drupal 8 instance for the very first time using the Composer Setup Example (https://ddev.readthedocs.io/en/latest/users/cli-usage/#drupal-8-quickstart). When i get to **ddev start** i get an error about an invalid Compose file. 

**To Reproduce**
Following the Drupal 8 Quickstart example

1. mkdir my-drupal8-site
2. cd my-drupal8-site
3. ddev config --project-type=drupal8 --docroot=web --create-docroot
4. ddev start
5. 

elaw@PANTHEON2:/d/dev$ mkdir my-drupal-site
elaw@PANTHEON2:/d/dev$ cd my-drupal-site/
elaw@PANTHEON2:/d/dev/my-drupal-site$ ddev config --project-type=drupal8 --docroot=web --create-docroot
Creating a new ddev project config in the current directory (/d/dev/my-drupal-site) 
Once completed, your configuration will be written to /d/dev/my-drupal-site/.ddev/config.yaml
 
Created docroot at /d/dev/my-drupal-site/web 
You have specified a project type of drupal8 but no project of that type is found in /d/dev/my-drupal-site/web 
Ensuring write permissions for my-drupal-site 
No settings.php file exists, creating one 
Existing settings.php file includes settings.ddev.php 
Configuration complete. You may now run 'ddev start'. 
elaw@PANTHEON2:/d/dev/my-drupal-site$ ddev start
Starting my-drupal-site... 
Pushed mkcert rootca certs to ddev-global-cache 
Running   Command=ip address show dev docker0
The Compose file '/d/dev/my-drupal-site/.ddev/.ddev-docker-compose-base.yaml' is invalid because: 
services.db.ports contains an invalid type, it should be a number, or an object  
services.web.ports contains an invalid type, it should be a number, or an object 
services.web.ports contains an invalid type, it should be a number, or an object 
Failed to start my-drupal-site: Failed to run docker-compose [-f /d/dev/my-drupal-site/.ddev/.ddev-docker-compose-base.yaml config], err='exit status 1', stdout='', stderr='The Compose file '/d/dev/my-drupal-site/.ddev/.ddev-docker-compose-base.yaml' is invalid because:
services.db.ports contains an invalid type, it should be a number, or an object   
services.web.ports contains an invalid type, it should be a number, or an object  
services.web.ports contains an invalid type, it should be a number, or an object' 

**Expected behavior**
I expect to be able to get to the next step in the Quickstart guide in order to create a new Drupal 8 website

**Screenshots**

![image](https://user-images.githubusercontent.com/12546984/88992980-0c7ea380-d328-11ea-82ff-825ea9c361f1.png)

**Version and configuration information (please complete the following information):**

- Windows 10, WSL Ubuntu 1804, turns out i'm only on WSL1 still. 
- Docker Desktop 2.3.0.4 (46911)
- ddev version
DDEV-Local version      v1.15.3
commit                  v1.15.3                                 
db                      drud/ddev-dbserver-mariadb-10.2:v1.15.1 
dba                     phpmyadmin/phpmyadmin:5                 
ddev-ssh-agent          drud/ddev-ssh-agent:v1.15.1             
docker                  19.03.12                                
docker-compose          1.25.0-rc4                              
os                      linux                                   
router                  drud/ddev-router:v1.15.1                
web                     drud/ddev-webserver:v1.15.3

- config.yaml contents for the misbehaving project
- I haven't modified the quickstart files in any way.

**Additional context**
Add any other context about the problem here. Thanks!

**Comment by rfay** [comment]
DDEV-Local doesn't claim to work on WSL1, which is a completely different animal. Please use WSL2.

Here are the instructions, https://ddev.readthedocs.io/en/stable/#installation-or-upgrade-windows-wsl2

Here's a YouTube screencast showing WSL2 setup: https://www.youtube.com/watch?v=SwahVCBTo3w

Please use WSL2, thanks.

**Comment by rfay** [comment]
No response from OP, but happy to continue the conversation here or elsewhere. Closing.
