### ISSUE TITLE
Nginx custom configuration

### ISSUE THREAD

**Issue by bfuzze** [drud/ddev#2435]
**Describe the bug**
I don't see a way to override the nginx configuration, other than maybe getting creative with docker-composer-override, but the documents state to override this file .ddev/nginx_full/nginx-site.conf, but this file does not exist on my local instance.  Perhaps the documentation needs to be updated?

**To Reproduce**
See documentation:  
https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/
Section: Providing custom nginx configuration
Start a new Drupal 8 instance.
Observe that .ddev/nginx_full directory does not exist.

**Expected behavior**
.ddev/nginx_full/nginx-site.conf should be created when a new instance is set up.
.ddev/nginx_full/nginx-site.conf may be overridden as the documentation indicates.

**Version and configuration information (please complete the following information):**
ddev version v1.14.2
Ubuntu 18.04
Docker version 19.03.6, build 369ce74a3c

**Additional context**
Drupal 8 project

**Comment by rfay** [comment]
Please upgrade to current v1.15.3 (which is what the docs reference). 

If you'd like to use v1.14.2 still (I don't recommend that) the docs for doing it with that are at https://ddev.readthedocs.io/en/v1.14.2/users/extend/customization-extendibility/

But it was a lot more work. Upgrading is simple. https://github.com/drud/ddev/releases

**Comment by rfay** [comment]
Closing, but happy to continue the conversation here or elsewhere.
