### ISSUE TITLE
Additional Windows End-user Documentation

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#244]
This is a follow-up to #196, specifically with respect to the following:

"We probably need separate basic documentation for Windows. Otherwise it will be stilted and hard to test. I wouldn't be surprised if it can link to some of the same things, but really we should be talking about ddev.exe and using windows paths, etc."

End-users need to know about:

* How to set up their machine - basic install technique (We've decided on Windows 10 Pro, Docker-for-windows)
* Future possibility: Using Bash on Ubuntu on Windows as that becomes popular
* If we have a Windows install, explain how that works
* Environment variables ($DOCKER_HOST)? if needed

## Related source links or issues:

* https://github.com/drud/ddev/issues/196#issuecomment-302251570
* [Developer windows setup info](https://github.com/drud/ddev/issues/252)

**Comment by rickmanelius** [comment]
Related to https://github.com/drud/ddev/issues/511 as well as our recent experience getting a new Windows user up to speed. Here are variables that were not considered but that did affect us:

* Windows Enterprise doesn't support Docker for Windows.
* There is the ability to login via Windows/MS Cloud versus a local user.
* Multiple hard drive mounts.

I've asked for a write-up from the end-user that tested this out in the hopes that we can take/shape that language and pull into a Windows Troubleshooting guide.

**Comment by rfay** [comment]
* We don't know that Windows Enterprise doesn't support docker-for-windows (I don't think). What we learned is that the version one user tried to install on was unacceptable. 
* We do need to try cloud login and see if it affects things.
* I tested having the repo on a different drive from the home directory and had no trouble with it.

**Comment by rfay** [comment]
Windows Enterprise does now support docker-for-windows. 

Closing this as obsolete.
