### ISSUE TITLE
Allow setting additional config subdirectories of .ddev

### ISSUE THREAD

**Issue by stborchert** [drud/ddev#2444]
Currently configuration files, service definitions, etc., are loaded exclusively from directory _.ddev_. If I would like to override the default values I have to add a _config.*.yaml_ or _docker-compose.*.yaml_ directly to directory _.ddev_.

It would be great, if additional source directories for config overrides, custom services, custom commands, ... could be set so DDEV loads the definitions from these directories in addition to the overrides currently possible.

**Example config.yaml**

```yaml
name: myproject
type: drupal8
php_version: "7.3"
config_directories:
  - environments/ddev
  - /some/other/directory
```

### Use case (and current situation)

We created a small composer package for our projects that includes common DDEV configuration valid for all projects. Requiring this package creates the directory _.ddev_ with a default _config.yaml_ and some additional services and overrides.

Each project defines its necessary overrides for DDEV in a directory named _environments/ddev_. Running `composer install` copies the overrides (e.g. a custom service that compiles the theme or custom commands to run update scripts on the site) to the proper location in _.ddev_.
This allows us to commit only the overrides to the project repository while automatically including the basic DDEV installation files using composer.

### Problems

The definition of `config_directories` should be limited to the main _config.yaml_ only. Otherwise this could lead to recursion or other problems I couldn't think of yet if a _config.*.yml_ in one of those additional directories sets another path.

**Comment by rfay** [comment]
Thanks!

**Comment by rfay** [comment]
I don't see this getting any particular traction, so closing for now.

**Comment by jayredfin** [comment]
Request to re-open this issue. I have a similar need to point DDEV at a command folder so that I can manage custom DDEV commands with composer packages.

**Comment by rfay** [comment]
Let's discuss in a single place please. Currently discussion going on in https://discord.com/channels/664580571770388500/1068592266752573440/1122979486573539429

Again, something that hasn't been active for 2 years can be considered, but please join in the discord thread and see what's being discussed there.
