### ISSUE TITLE
Windows-native testing for ddev

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#245]
This is a follow-up to #196, discussing things we need to do to fully support Windows.

In order to support automated tests for WIndows, we need Windows-native testing to succeed. Currently we drive the tests with a Makefile that isn't intended to be compatible with windows-native environment. However, it really just needs to have the `go test` part separated out for usage by Windows.

> Building and testing
> * Currently building and testing are best done using make, and the whole system is notoriously hard to use on Windows because it uses unix tools like rm and yet has to use the windows docker.exe. It may be a rethink for us to build on Windows - build-tools is definitely not set up for it.
> * Full testing is normally done via make, which is not currently working. We can probably find a technique, but it's awfully hard right now.
> 

## Related source links or issues:

* https://github.com/drud/ddev/issues/196#issuecomment-302251570

**Comment by rfay** [comment]
https://github.com/drud/ddev/pull/387 went in, which is a lot of stuff, but we have a ways to go yet. The tests are currently so slow it's pretty tedious.

**Comment by rfay** [comment]
This is in and working, yay
