### ISSUE TITLE
ddev start stops with error: Version in ~/.ddev/ssh-auth-compose.yaml is unsupported.

### ISSUE THREAD

**Issue by GiorgosK** [drud/ddev#2450]
**Describe the bug**
Fresh installed ddev start stops with error: Version in ~/.ddev/ssh-auth-compose.yaml is unsupported.

**To Reproduce**

1. installing ddev for ubuntu 18.04 as per instructions (manual and/or using the script)
2. run sample ddev project 

```
$ ddev poweroff && mkdir testddev && cd testddev && ddev config --project-type=php && ddev start
Creating a new ddev project config in the current directory (/home/giorgos/testddev) 
Once completed, your configuration will be written to /home/giorgos/testddev/.ddev/config.yaml
 
Found a php codebase at /home/giorgos/testddev 
Project type has no settings paths configured, so not creating settings file. 
Configuration complete. You may now run 'ddev start'. 
It looks like you have a new ddev release.
May we send anonymous ddev usage statistics and errors?
To know what we will see please take a look at
https://ddev.readthedocs.io/en/stable/users/cli-usage/#opt-in-usage-information
Permission to beam up? [Y/n] (yes): 
Starting testddev... 
Version in "/home/giorgos/.ddev/ssh-auth-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1. 
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/ 
Failed to start testddev: failed to start ddev-ssh-agent: Failed to run docker-compose [-f /home/giorgos/.ddev/ssh-auth-compose.yaml -p ddev-ssh-agent up --build --force-recreate -d], err='exit status 1', stdout='', stderr='Version in "/home/giorgos/.ddev/ssh-auth-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/'
```

**Expected behavior**
I suppose project should start but it does not

**Version and configuration information (please complete the following information):**

I am on ubuntu 18.04 
And ddev is fresh installed with no customizations

```
$ ddev version
DDEV-Local version	v1.15.3                                
commit            	v1.15.3                                
db                	drud/ddev-dbserver-mariadb-10.2:v1.15.1
dba               	phpmyadmin/phpmyadmin:5                
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.15.1            
docker            	19.03.12                               
docker-compose    	1.25.0-rc4                             
os                	linux                                  
router            	drud/ddev-router:v1.15.1               
web               	drud/ddev-webserver:v1.15.3  
```

```
$ cat ~/.ddev/ssh-auth-compose.yaml 
version: '3.6'

volumes:
  dot_ssh:
  socket_dir:

services:
  ddev-ssh-agent:
    container_name: ddev-ssh-agent
    hostname: ddev-ssh-agent
    build:
      context: '/home/giorgos/.ddev/.sshimageBuild'
      args:
        BASE_IMAGE: drud/ddev-ssh-agent:v1.15.1
        username: 'giorgos'
        uid: '1000'
        gid: '1000'
    image: drud/ddev-ssh-agent:v1.15.1-built

    user: "$DDEV_UID:$DDEV_GID"
    volumes:
      - "dot_ssh:/tmp/.ssh"
      - "socket_dir:/tmp/.ssh-agent"
    environment:
      - SSH_AUTH_SOCK=/tmp/.ssh-agent/socket
    healthcheck:
      interval: 1s
      retries: 2
      start_period: 10s
      timeout: 62s
networks:
  default:
    external:
      name: ddev_default
```

Not sure if any more information is needed

**Comment by rfay** [comment]
How did you install docker-compose? It looks like perhaps you have an old one, but I'd expect ddev to refuse to run with a really old one. The Docker installation instructions (including docker-compose) are at https://ddev.readthedocs.io/en/stable/users/docker_installation/#linux-installation-docker-ce

Did you perhaps install docker or docker-compose with snap? I don't think that works. 

Please show `docker-compose --version`. The current version offered by homebrew/linuxbrew and also on [docker's download page}(https://docs.docker.com/compose/install/#install-compose) is 1.26.2. The version obtained by apt-get on 18.04 is 1.17.1, which is too old. 

You *seem* to have 1.25.0-rc4, but I don't know how you could have gotten that, but I would expect it to work. 

Please install docker and docker-compose per the [installation instructions](https://ddev.readthedocs.io/en/stable/users/docker_installation/#linux-installation-docker-ce) and see if you don't get further. I recommend using Linuxbrew for ddev and docker-compose.

**Comment by GiorgosK** [comment]
@rfay thanks did not realize but after further investigation I realized that there were different versions of `docker-compose` around and maybe the updated one was not the one actually used 

`docker-compose version`  resulted in something like 1.17 
so I had to follow the official installations instructions for docker compose https://docs.docker.com/compose/install/ and finally could move past this problem

```
$ ddev version
DDEV-Local version	v1.15.3                                
commit            	v1.15.3                                
db                	drud/ddev-dbserver-mariadb-10.2:v1.15.1
dba               	phpmyadmin/phpmyadmin:5                
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.15.1            
docker            	19.03.12                               
docker-compose    	1.25.0-rc4                             
os                	linux                                  
router            	drud/ddev-router:v1.15.1               
web               	drud/ddev-webserver:v1.15.3 
```

still there are 2 different versions around but at least now they are both closer to the latest

```
$ docker-compose version
docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
giorgos@ThinkPad-E590:gizra-starter (master %=)$ 
```

**Comment by rfay** [comment]
Sounds like you have it. Interestingly enough, I'm completely unable to run the docker-compose that apt installs on 18.04 (1.17), so can't test this problem easily.  But ddev should have detected that it was an old docker-compose and refused to run.

It's getting more and more unusual to see old docker-compose these days, and older versions of Ubuntu seem to be the only place it happens, when people miss that part of the instructions.

Closing, happy to continue the conversation.
