### ISSUE TITLE
Unable to Create a New Drupal 9 Project with MySQL

### ISSUE THREAD

**Issue by ScaryOrca** [drud/ddev#2451]
**Describe the bug**
When starting a new Drupal 9 project, if you specify to use MySQL, you're given the error `failed to validate config: both mariadb_version (10.3) and mysql_version (8.0) are set, but they are mutually exclusive`.

Creating a new Drupal 9 project without specifying to use MySQL using `ddev config --project-type=drupal9 --docroot=web --create-docroot`, and then trying to change it afterwards using `ddev config --mysql-version=8.0` results in the error `failed to validate config: both mariadb_version (10.3) and mysql_version (8.0) are set, but they are mutually exclusive`

**To Reproduce**
Run the command `ddev config --mysql-version=8.0 --project-type=drupal9 --docroot=web --create-docroot`. The project type `drupal8` isn't affected by this issue, only `drupal9`.

**Expected behavior**
A new Drupal 9 project should be created configured to use MySQL 8.0.

**Screenshots**
Trying to start a new Drupal 9 project with MySQL (notice that the Drupal 8 project is created without any errors):
<img width="1139" alt="Screen Shot 2020-08-13 at 10 37 11 AM" src="https://user-images.githubusercontent.com/942383/90155475-fa056080-dd50-11ea-90a7-252aafb70c09.png">

Trying to switch from MariaDB to MySQL immediately after starting Drupal 9 project:
<img width="1139" alt="Screen Shot 2020-08-13 at 10 53 24 AM" src="https://user-images.githubusercontent.com/942383/90157351-3df96500-dd53-11ea-89de-4f24379dc93c.png">

**Version and configuration information (please complete the following information):**

- Host computer OS and version: macOS Catalina
- Docker Desktop version: 2.3.0.4 (46911)
- ddev version information: 1.15.3

**Comment by rfay** [comment]
Yeah, you have to turn off mariadb_version to be able to use mysql_version, there's mutually exclusive. 

You'll need to either edit the .ddev/config.yaml to use one or the other, or use a command like

`ddev config --project-type=drupal9 --mariadb-version="" --mysql-version=8.0 --docroot=web --create-docroot`

**Comment by ScaryOrca** [comment]
Why is that a requirement for Drupal 9, but not for Drupal 8? I just tested creating two Drupal 8 projects in separate directories, one using

`ddev config --mysql-version=8.0 --project-type=drupal8 --docroot=web --create-docroot`

and one using

`ddev config --mariadb-version=10.4 --project-type=drupal8 --docroot=web --create-docroot`

Both created a Drupal 8 project without issues, and both config.yaml files have either only mariadb_version or mysql_version, not both.

**Comment by rfay** [comment]
Drupal 9 requires a minimum of MariaDB 10.3, and the default is 10.2. So on a Drupal 8 project, 10.2, the default, is fine, and it's not specified in the config.yaml. When you create a Drupal 9 project though, ddev specified the db type as mariadb 10.3, so then you have a conflict.

**Comment by rfay** [comment]
Hoping this makes sense, happy to continue the conversation here or elsewhere. Closing for now.
