### ISSUE TITLE
Extension of the "launch" command (ddev launch wordpress)

### ISSUE THREAD

**Issue by fschmittlein** [drud/ddev#2469]
**Describe the solution you'd like**
`ddev launch wordpress` (loads the WordPress Dashboard /wp-admin)

**Comment by rfay** [comment]
Just `ddev launch /wp-admin` does that.

**Comment by rfay** [comment]
`ddev help launch` shows all the options, some good ones there. 

Also, `ddev launch wp-admin` should work the same.
