### ISSUE TITLE
Consider moving contributing documentation to the community repository.

### ISSUE THREAD

**Issue by cyberswat** [drud/ddev#247]
## What happened (or feature request):

As we continue to grow and gain traction with our repositories it would be nice to have a centralized set of documentation that helps new and seasoned contributors understand the best way of engaging with us.

One way of growing this type of communication across all of our projects is to centralize this type of communication into our community documentation.  It would provide consistency across projects and minimize the amount of duplication necessary if this communication was constrained to project repositories.  An additional benefit is that it could allow for discovery of projects we are proud of from a centralized location.

This would have the added benefit of allowing potential contributors a method for understanding our workflows, what our labels mean, what their expectations should be, etc.  This would also allow us to reinforce the community aspects of our work as we continue to grow.

## What you expected to happen:

It would be great if we could move any documentation like https://github.com/drud/ddev/blob/master/CONTRIBUTING.md into the community repository while leaving pointers from the ddev repository to broader community guidelines.

## Anything else do we need to know:

The structure for the community repository does not yet contain an area to store this type of information.  It may be that we create a contributing folder, or something else entirely.

## Related source links or issues:

https://github.com/drud/community

**Comment by rickmanelius** [comment]
Overall, I'm in support of this because a significant portion (I would guess 80+ percent) of the ddev contributing page could be generalized and applied across the board. A notable exception would be the specific references to Go where other languages may appear in other repos.

There is also the question of tone/branding. I'm all for adding a bit of personality into the documents instead of them being clinical. That said, we haven't really defined what our overall voice is/should be. This is not a request to change anything at this time, but I'm more surfacing it as a placeholder to loop back.

**Comment by tannerjfco** [comment]
It is useful for each project to retain its own copy of CONTRIBUTING so that GitHub provides the message to users to review guidelines before submitting an issue.

**Comment by rickmanelius** [comment]
@tannerjfco Good point. Would it be appropriate/workable to put a shorter version in the repo and then link to the larger community one? My only concern on copies if that, depending on the number of repos that link to this guide, it could be tedious to submit multiple PRs each time it's updated.

**Comment by tannerjfco** [comment]
We could certainly do that, but I don't know how likely users are to follow another documentation link before contributing. I'm not certain how frequently we would have cause to change our contributing guidelines, especially a case that would require all projects to be updated. Either way, I do think its valid to have a copy of contributing guidelines in the community project.

**Comment by rfay** [comment]
As Tanner points out, we definitely have to have a CONTRIBUTING for github's purposes. If we need more than a short CONTRIBUTING document, I think it's OK to link to further documents.

However... Nobody reads anything, ever. So if we need a document that is bigger or more complex, we're making a mistake thinking anybody will actually read it. So I guess I'd be in favor of maintaining a small, normal, traditional CONTRIBUTING.md in each repo (and keeping it standard). It can link to whatever it needs to in the community repo... but it's unrealistic to expect people to follow the link.

**Comment by rickmanelius** [comment]
Closing because of the following:

1. No movement on this in over 3 months.
2. We're not hitting on this as a pain point at this time and we can re-open and address if that changes.
