### ISSUE TITLE
Nginx additional configurations needs work

### ISSUE THREAD

**Issue by bfuzze** [drud/ddev#2472]
Great product.  I'm really impressed with the performance and general stability.

**Describe the bug**
The instructions in the documentation are not working for me.  
https://ddev.readthedocs.io/en/stable/users/extend/customization-extendibility/#providing-custom-nginx-configuration

**To Reproduce**
There are a couple of issues...
1. The documentation states to add additional configurations under .ddev/nginx_full/.  Configurations put here were ignored.  I checked the /etc/nginx/sites-enabled/nginx-sites.conf and it was referencing /mnt/ddev_conf/nginx/*.conf.  I changed nginx_full to nginx and the files were recognized during startup, but see second issue.
2. Conf files seem properly formatted, but nginx says "nginx: [emerg] “server” directive is not allowed here"
3. Documentation states that there is an example file, but I couldn't find one.
4. The header in /etc/nginx/sites-enabled/nginx-sites.conf says to override with .ddev/nginx-sites.conf.  I tried this and the file was picked up during restart and additional server directives were accepted, but the result was 502 error when trying to access either domain.  

So either the documentation needs to be updated or there are some issues with supporting multiple sites.  Probably both.

**Expected behavior**
I'd like to be able to add additional domains to the config.yaml and additional nginx conf for each domain so I can run multiple sites from the same instance.

**Version and configuration information (please complete the following information):**
DDEV-Local version	v1.14.2                                
commit            	v1.14.2                                
db                	drud/ddev-dbserver-mariadb-10.2:v1.14.1
dba               	phpmyadmin/phpmyadmin:5                
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.14.0            
docker            	19.03.6                                
docker-compose    	1.25.0-rc4                             
os                	linux                                  
router            	drud/ddev-router:v1.14.0               
web               	drud/ddev-webserver:v1.14.2  

The only customizations in config.yaml are port numbers.
I am using the postgres service.

Thanks!

**Comment by rfay** [comment]
@bfuzze Please respond with specifics so we can address this, thanks.

**Comment by rfay** [comment]
No response from OP, wasn't able to understand the issue. Closing for now, happy to continue the conversation.
