### ISSUE TITLE
Add button for GitHub sponsorship

### ISSUE THREAD

**Issue by ekl1773** [drud/ddev#2478]
**Is your feature request related to a problem? Please describe.**
It is now possible to sponsor DDEV on GitHub, but this is only evident if you visit the organization's main page at https://github.com/drud or a featured repository (once the FUNDING.yml files merge).

**Describe the solution you'd like**
Please add a small button using the code below to the DDEV-Local documentation in an appropriate location such as [in the intro section here](https://ddev.readthedocs.io/) or perhaps in the support section?

`<iframe src="https://github.com/sponsors/drud/button" title="Sponsor drud" height="35" width="116" style="border: 0;"></iframe>`

**Describe alternatives you've considered**
There's also a larger format available but it doesn't seem stylistically in keeping with the docs.

`<iframe src="https://github.com/sponsors/drud/card" title="Sponsor drud" height="225" width="600" style="border: 0;"></iframe>`

**Additional context**
<img width="647" alt="Screen Shot 2020-08-25 at 3 38 13 PM" src="https://user-images.githubusercontent.com/2431475/91219681-068e9f00-e6e9-11ea-9f5f-089e76e7f3d9.png">

**Comment by rfay** [comment]
@ekl1773 Please take a look at https://test-ddev.readthedocs.io/en/latest/ and see if you like it. Bottom of page.

**Comment by ekl1773** [comment]
That seems good to me. I definitely like the small size. Maybe in a future docs update we can figure out something more prominent but this is good for now! Thank you.

**Comment by rfay** [comment]
Thanks, it will go in when I pull https://github.com/drud/ddev/pull/2447
