### ISSUE TITLE
Xdebug not working on Vscode and Drupal 8 (macOS)

### ISSUE THREAD

**Issue by powpow12** [drud/ddev#2482]
**Describe the bug**
After setting up Drupal 8 and ddev, I used the vscode instructions for setting up xdebug but it never breaks on my index.php file.

**To Reproduce**

1. Install [Drupal and ddev](https://ddev.readthedocs.io/en/stable/users/cli-usage/#composer-setup-example).
0. Install [vscode](https://code.visualstudio.com/download)
0. install [php-debug extension](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug) 
0. use [ddev vscode instructions](https://ddev.readthedocs.io/en/latest/users/step-debugging/#visual-studio-code-vscode-debugging-setup)
0. use [ddev's xdebug debugging instructions](https://ddev.readthedocs.io/en/latest/users/step-debugging/#troubleshooting-xdebug):

- [X] Make sure xdebug has been enabled in ddev; it's disabled by default for performance reasons. Most people use ddev xdebug on to enable it when they want it, and ddev xdebug off when they're done with it, but it can also be enabled in .ddev/config.yaml.
I added breakpoints to index.php
- [X] Don't assume that some obscure piece of code is being executed and put a breakpoint there. Start by putting a breakpoint at the first executable line in your index.php. Oh-so-many times people think it should be stopping, but their code is not being executed.
- [X] ddev ssh into the web container. Can you ping host.docker.internal (and get responses)? If you can't, you might have an over-aggressive firewall.
![image](https://user-images.githubusercontent.com/3721535/91658655-0cdd9c00-ea98-11ea-90ca-dc127981c322.png)
- [ ] ddev ssh: Can telnet host.docker.internal 9000 connect? If it does, you have something else running on port 9000, probably php-fpm. On the host, use sudo lsof -i :9000 -sTCP:LISTEN to find out what is there and stop it, or change the xdebug port and configure PHPStorm to use the new one . Don't continue debugging until your telnet command does not connect.

This is a confusing step, at first I thought I was expecting a connection, but reading it again I see that I am not. Here is what I get, 
![image](https://user-images.githubusercontent.com/3721535/91658810-845ffb00-ea99-11ea-9775-8a3ff30127da.png)

`lsof` is not an available command. 

Something that was unclear in the instructions, **what should pathMappings be set to?** After finishing the instructions of setting up drupal8 with ddev, we have a web directory but the template has `"/var/www/html": "${workspaceRoot}"`. I've tried update pathMappings to /var/www/html/web but it still doesn't break.

versions (if multiple versions listed, I tried both)
* ddev: v1.15.3
* php: 7.3/7.2
* drupal: 8.9.3
* xdebug: 2.9.6
* vscode: 1.47.3
* php-debug-extension: 1.13.0/1.12.6

**Expected behavior**
I expect the break point to hit in index.php

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: Macos Mojave 10.14.6 
- Docker Desktop version if on macOS or Windows: Version 2.0.0.3 (31259)
- ddev version information: v1.15.3

**Comment by powpow12** [comment]
This may be related to this https://github.com/felixfbecker/vscode-php-debug/issues/418.

**Comment by powpow12** [comment]
downloaded netstat and lsof, lsof returned nothing and maybe this will be more helpful to people that know what it means 

![image](https://user-images.githubusercontent.com/3721535/91668031-03bfef80-ead7-11ea-8332-e583bd7ae08e.png)

**Comment by rfay** [comment]
I haven't tried vscode on macOS, but will give it a try.

**Comment by rfay** [comment]
@powpow12  Based on your description, something is listening on port 9000 on the *host* (not inside the container). The most likely culprit is php-fpm (you can use `ps -ef | grep fpm` to look for it, and stop it with (perhaps) `brew services stop php` if it was installed with homebrew. 

lsof is intended to be used on the *host*, not inside the container. lsof is included in macOS, it's not something you have to install. From [docs](https://ddev.readthedocs.io/en/stable/users/step-debugging/#troubleshooting-xdebug) on the host, `sudo lsof -i :9000 -sTCP:LISTEN` . Make sure you have vscode *not* listening when debugging this, and make sure you don't have PHPStorm or some other IDE listening.

**Comment by rfay** [comment]
No response from OP, so closing. @powpow12 happy to continue the conversation here or elsewhere.
