### ISSUE TITLE
Add documentation to the docker-compose.yml template

### ISSUE THREAD

**Issue by rfay** [drud/ddev#249]
## What happened (or feature request):

It's really hard to know what all the magic in the docker-compose.yml is. There are special-purpose environment variables, and various magical incantations. 

## What you expected to happen:

As a user I expect to be able to read the file and make small adjustments with confidence, without a degree in docker-composology. 

Suggested approach:

* Template can add a comment before each section explaining what it's for and what the options are. Thus every generated docker-compose.yml would have an explanation of each line. 
* For extra wonderful credit, actually document the behavior of the output in place.

## Related source links or issues:

**Comment by rickmanelius** [comment]
I think this would be valuable, particularly for those wanting to extend. Probably something worth prioritizing after provider plugins.

**Comment by rickmanelius** [comment]
Moving to v1.1.0

**Comment by rfay** [comment]
docker-compose.yaml is now completely ddev-managed and is not to be edited by the user.
