### ISSUE TITLE
documentation of Drupal twig debugging, turning off Drupal caches, /sites/default/services.yml

### ISSUE THREAD

**Issue by ahillio** [drud/ddev#2490]
Hello!  I was just stuck wondering why twig debugging wasn't working.

I found that adding `$settings['container_yamls'][] = DRUPAL_ROOT . '/sites/default/services.yml';` to settings.php (via [d.o forum](https://www.drupal.org/forum/support/module-development-and-code-questions/2019-09-02/ddev-twig-debugging)) solved the problem for me.

Looks like someone else https://github.com/drud/ddev/issues/1831 had trouble with this.

When I searched ddev.readthedocs.io/ for "twig debug" I found no results.

Would it be worth mentioning this there?

**Comment by rfay** [comment]
Hi @ahillio - This is very much a drupal-specific thing, and really has nothing to do with ddev and everything to do with Drupal and Twig Debugging, it's mentioned 

Here's the answer in another issue: https://github.com/drud/ddev/issues/833#issuecomment-387588932

The Drupal doc is [Disable Drupal 8 caching during development](https://www.drupal.org/node/2598914), and again, it doesn't have to do with ddev.

If you can suggest where it be mentioned in the ddev docs, I"m open to adding it there, but this really isn't about ddev.

**Comment by ahillio** [comment]
Oh yeah... you're right (of course)... I guess the thing that's ddev-related is that ddev creates the settings.php so that all it's doing is sourcing the settings.ddev.php which is quite minimal and doesn't load the services.yml file.

It'd be great if the services.yml was sourced in a ddev environment by default.  I wonder if there are any other settings in the default.settings.php that would make sense for ddev to apply.

Is there any ddev config that will influence the settings.php or settings.ddev.php files?

One thing I'd like to do if ddev was capable of providing a default settings.php config, one which is not done in Drupal's default.setting.php, would be to set variables for https://www.drupal.org/project/environment_indicator.

**Comment by rfay** [comment]
Not every developer is doing front-end work and wants that services.yml set up. 

However, I raised the priority of https://github.com/drud/ddev/issues/1097 because of this discussion.

Please note that you don't have to let ddev create the settings.php, that's all up to you. There's a wide-ranging discussion of settings files at https://ddev.com/ddev-local/controlling-cms-settings-files-in-ddev-local/

**Comment by ahillio** [comment]
Cool thanks Randy.

I think if settings.php that ddev creates is based on Drupal's default.settings.php then that would eliminate the unexpected behavior here, and thus eliminate need for documentation.
