### ISSUE TITLE
Add the option to add flags to custom commands

### ISSUE THREAD

**Issue by gilbertsoft** [drud/ddev#2491]
**Is your feature request related to a problem? Please describe.**
More and more bundled custom commands are providing flags but there is not option to describe this flags in the custom command.

**Describe the solution you'd like**
There should be an option to add provided flags to the Cobra defintion (commandToAdd.Flags().BoolVarP() in commands.go should be sufficient).

**Describe alternatives you've considered**
Currently the flags can be shown in the example section.

**Additional context**

**Comment by rfay** [comment]
Well, there is a way, in the Usage section. I agree there could be more. But it shouldn't be in the cobra description, it should be in the script itself. 

See usage in `ddev launch` :

```
$ ddev launch -h
Launch a browser with the current site (shell host container command)

Usage:
  ddev launch [path] [-p|--phpmyadmin] [-m|--mailhog] [flags]

Examples:
"ddev launch" or "ddev launch /admin/reports/status/php" or "ddev launch phpinfo.php", for PHPMyAdmin "ddev launch -p", MailHog "ddev launch -m"

Flags:
  -h, --help   help for launch

Global Flags:
  -j, --json-output   If true, user-oriented output will be in JSON format.
```

**Comment by gilbertsoft** [comment]
Yeah, that's a good quick fix. But having the flags listed in the Flags section would be nice imho and not just the -h

**Comment by gilbertsoft** [comment]
BTW ofc I meant add a new item (flags) to the command description and add this to the cobra definition ofc. Adding it to the ddev source would ofc not make any sence.

**Comment by rfay** [comment]
I want to point your attention to what will be a really important issue, https://github.com/drud/ddev/issues/2128
