### ISSUE TITLE
Cleanup un-used databases/files from the ~/.ddev/ directory as part of ddev pull process

### ISSUE THREAD

**Issue by joshuaboltzmc** [drud/ddev#2503]
**Is your feature request related to a problem? Please describe.**
Yes, it is related to when you may receive the `no space left on device` error. This is due to your hard drive not having enough space available to do what DDev needs to do.

**Describe the solution you'd like**
As part of the `ddev pull` process, remove databases and files that were downloaded previously from integrations like Pantheon in the ~/.ddev/ folders, like `~/.ddev/pantheon/my-db.sql.gz`. This can be left un-attended for very long and racking up GBs of data in this folder until someone hits the `no space left on device` error, and then they need to figure out where to save space, which would likely lead to this folder as one culprit.

**Describe alternatives you've considered**
Possibly there's a hook that could be used to clean these old Pantheon DB and files at the start of a `ddev pull`? Or once the `ddev pull` completes? I believe it may make more sense to do on complete, since that would allow DDev to check if the database being imported is the same as an already imported one and skip the download and load it from disk. But, if it happens at complete, it would have to say `delete all DB/files` except this most recent one that we just downloaded and saved.

**Additional context**
There is another open issue that would introduce a `ddev clean` command, which would wipe away old, no-longer-needed files, such as old Pantheon database backups and files:
https://github.com/drud/ddev/issues/2332

But the issue I am opening is around making some of the cleanup happen as part of the `ddev pull` process.

**Comment by rfay** [comment]
As of upcoming v1.17.0-alpha5, ~/.ddev won't be used for these databases/files any more at all, and they get cleaned up on every pull. So the only thing we need to do is tell people to delete those files.
