### ISSUE TITLE
Installing Drupal Distributions in DDEV environment

### ISSUE THREAD

**Issue by begrafx** [drud/ddev#2508]
I have an issue which at first, I thought was an issue with OpenRestaurant, however, I found when I used MAMP and installed it there, it installs without issue. Thus, I am presuming that this issue is related to DDEV or something I'm doing. 

I'm able to install drupal in DDEV without issue using the quickstart method of 

`mkdir my-drupal8-site
cd my-drupal8-site
ddev config --project-type=drupal8 --docroot=web --create-docroot
ddev start
ddev composer create "drupal/recommended-project:^8"
ddev composer require drush/drush
ddev launch`

This works fine. However, if I want to use any distribution from Drupal, I encounter similar issues. I'll share my attempt today, to install OpenRestaurant, as an example. 

I start out and I run the command

`composer create-project openrestaurant/openrestaurant-project myrestaurant`

It pulls down the package.  I then run the `ddev config` process to give me the necessary servers. This completes without issue. I then use the `ddev launch` command which opens the browser and begins the install process. It goes through the choose language screen, and install screen, and then I receive: 

`An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /core/install.php?profile=openrestaurant&langcode=en&id=1&op=do_nojs&op=do
StatusText: OK
ResponseText: 
Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/web/core/modules/file/file.module on line 893
Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/web/core/modules/file/file.module on line 899
Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/web/core/modules/file/file.module on line 912
{"status":true,"percentage":"16","message":"Completed 9 of 57.","label":"Installed \u003Cem class=\u0022placeholder\u0022\u003EFile\u003C\/em\u003E module."}`

Giving me the option to continue to the error page. I do so, and I receive:

`The website encountered an unexpected error. Please try again later.
Drupal\Core\Config\UnmetDependenciesException: Configuration objects provided by <em class="placeholder">kitchen</em> have unmet dependencies: <em class="placeholder">block.block.kitchen_breadcrumbs (block)</em> in Drupal\Core\Config\UnmetDependenciesException::create() (line 98 of core/lib/Drupal/Core/Config/UnmetDependenciesException.php).

Drupal\Core\Config\UnmetDependenciesException::create('kitchen', Array) (Line: 469)
Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('theme', 'kitchen') (Line: 132)
Drupal\Core\ProxyClass\Config\ConfigInstaller->checkConfigurationToInstall('theme', 'kitchen') (Line: 168)
Drupal\Core\Extension\ThemeInstaller->install(Array, 1) (Line: 164)
Drupal\Core\Extension\ThemeHandler->install(Array) (Line: 1563)
install_profile_themes(Array) (Line: 671)
install_run_task(Array, Array) (Line: 549)
install_run_tasks(Array) (Line: 117)
install_drupal(Object) (Line: 44)
`

at which point I am dead in the water. I am unsure how to proceed. As I say, using the same composer command to pull down OpenRestaurant, and using MAMP, creating the database in PHPMyAdmin, and then running the install, it goes fine. So am I doing something wrong?

**Comment by rfay** [comment]
I always recommend using `ddev composer` so you're using the composer that matches your server. If you use composer on the host, it may not have the same extensions enabled or the same PHP version. 

Note that your openrestaurant-project  example is using Drupal 8.5.4, hopelessly out of date, so you may want to consider your options. 

I used `mkdir rest && cd rest && ddev config --project-type=drupal8 --docroot=web --create-docroot && ddev composer create openrestaurant/openrestaurant-project`

I then got the same failure you did. 

You'll note that you're getting "Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/web/core/modules/file/file.module on line 893", which looks a lot like a PHP complaint, probably deprecated usage.

The default version of PHP with ddev is 7.3. I downgraded it to 7.1 with `ddev config --php-version-7.1` and it worked fine.

Be aware that lightly used distributions like this are a way to get your website off on the wrong foot. This one uses Drupal 8.5.4, has no way to update to 8.8 or 8.9 or 9.0, and has only had maybe a total of 50 issues ever created. So it's like starting with something that has no future.

**Comment by begrafx** [comment]
Murphy's law, OF COURSE I'm going to pick something odd like that... am I using the right method for installing a normal (current) distro?

**Comment by rfay** [comment]
As I said, I suggest using `ddev composer` instead of using composer on the host/workstation. 

> I always recommend using ddev composer so you're using the composer that matches your server. If you use composer on the host, it may not have the same extensions enabled or the same PHP version.

> I used mkdir rest && cd rest && ddev config --project-type=drupal8 --docroot=web --create-docroot && ddev composer create openrestaurant/openrestaurant-project

**Comment by rfay** [comment]
Closing this for now, but happy to continue the conversation here or elsewhere. There's nothing different about installing a distribution as compared to any other project.
