### ISSUE TITLE
DDEV Drupal 8 Login

### ISSUE THREAD

**Issue by begrafx** [drud/ddev#2509]
Not sure what I did, or how, but somehow, I managed to get signed out of a Drupal 8 project I was working on. "No problem" I thought, so I closed the tab, and returned to the project in a new tab. The site comes up, but I am not logged in. "No problem". So I `ddev start [project]`. Project starts again just fine, but still not logged in. "No problem". `ddev poweroff` everything shuts down nicely. `ddev start` `ddev list`, shows it is running. `ddev launch` new tab opens, site comes up, but still not logged in. 

How do I get back in to Drupal  8 as admin? Help!

**Comment by rfay** [comment]
There are many ways to get logged in, but the easiest way is `drush uli`. So `ddev exec drush uli` or `ddev ssh` and then `drush uli`, then click the link it provides.

**Comment by begrafx** [comment]
Yes, I was about to try that, but I wasn't sure what DDEV did, and I didn't want to change something and cause further problems. Thank you.

**Comment by begrafx** [comment]
Awesome. I want to take a moment and say thank you, Randy. You have always been so quick to respond, and so patient and helpful as I'm learning my way through DDEV. I want you to know how much I appreciate all of it.

**Comment by rfay** [comment]
Thanks!

DDEV is just a hosting environment, and besides creating settings files for you, it doesn't know much about particular CMSs. So everything you'd do in any hosting environment... is the same as you do in ddev.
