### ISSUE TITLE
github ddev README.md Improvements

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#251]
## What happened (or feature request):

* Feature Request

## What you expected to happen:

While our readme.md is accurate, we should spend some time making sure that an end-users first interaction with it is compelling. Suggestions included linking to any tutorials, articles, videos, etc.

This was described in our last planning meeting 2017-05-16.

**Comment by rickmanelius** [comment]
This came up again in a recent conversation with @sgrandchamp and @cyberswat. Noting that we want/need to prioritize this in conjunction with items like https://github.com/drud/general/issues/119.

**Comment by rickmanelius** [comment]
Proposed next actions:
* [ ] Inventory of project pages that we like and/or find useful for engaging with end-users.
* [ ] Determine the goals of the project page.
* [ ] Review our project page to identify any major gaps and/or opportunities.

**Comment by rickmanelius** [comment]
@cyberswat @rfay @beeradb @tannerjfco 
Not asking for to spend a lot of time digging, but if anyone knows of any GitHub project pages that they found particularly nice/useful, please ping me with representative examples.

**Comment by rickmanelius** [comment]
Summarizing, there are 3 different locations that contain information related to ddev.

* GitHub Readme.md
* Documentation Site
* Project Website (planned with no scheduled ETA)

To that end, the GitHub readme.md used to serve as all 3 and is now doing double/triple duty. I recommend we slim it down considerably and have it structured as follows:

* Intro
  * This contains the one paragraph ddev overview that is currently on the readme.md.
  * An additional paragraph ddev fits into the overall mission of DRUD w/link to DRUD.com
* Getting Started
  * Link to documentation site.
  * Link to youtube videos.
  * Link to feature list to evaluate if ddev is right for you.
* Contributing
  * Link to guidelines.
  * Link to roadmap.
  * Link to issue queue.
* Support
  * Link to issue queue.
  * Link to Slack channel.
  * Note that other support options coming.

**Comment by rickmanelius** [comment]
@beeradb found this gem, which basically is a curated list of awesome GitHub readme pages! https://github.com/matiassingers/awesome-readme

**Comment by rfay** [comment]
As mentioned in https://github.com/drud/ddev/issues/434#issuecomment-330299123 - when working this we need to figure out how to consolidate the install and other instructions into a single set of instructions which *are* picked up by readthedocs. Currently, we have lots of important stuff in the README which is absolutely not in readthedocs except as duplicate info.

**Comment by rfay** [comment]
When this gets some love:
* The sample commands (captured output from ddev) in the README are way out of date, and somebody caught that at BADCamp. I doubt it's useful to have an explicit capture of ddev output in the README, but if it is it will have to be maintained.
* README still implies that Windows support is super-immature and we're not in a bad place right now.
* README says that ddev captures port 3306, it doesn't. BUT... we're about to capture 443, so we should say that.

**Comment by rickmanelius** [comment]
Finally getting to this. A few changes from my initial proposal (https://github.com/drud/ddev/issues/251#issuecomment-315406863) based on further review and feedback from @rfay.

* Support should proceed contribution in terms of the hierarchy because historically the scales are tipped in that direction (e.g. a larger percentage of end-users will want support versus have the time/means to contribute back).
* I'd like to create an animated gif of the zero to ddev video using this https://github.com/dergachev/screengif. Part of the reason is to convey the value prop quickly.
* @rfay made a good point that we need to ensure gaps in the main documentation are available. So when cutting info out of the readme.md, we need to ensure it lands in the docs.
* This pass is a stop-gap while we continue to work on a timeline to address the overall documentation.

**Comment by rickmanelius** [comment]
Updated assignees so either @rfay or @cweagans can take the lead on implementing the final round of suggested changes and we can bring this to a completion.

**Comment by rickmanelius** [comment]
PR merged. Closing
