### ISSUE TITLE
Support the use of SSH-Keys with AgentForwarding / ssh-agent

### ISSUE THREAD

**Issue by mrimann** [drud/ddev#2510]
When using ddev on my local machine, the use of `ddev auth ssh` reads in my SSH keys and I can use them from within ddev-containers, like e.g. for a `ddev composer update` that needs to access some private repositories. So far, all fine.

But now, I'd like to use Docker and ddev running on a remote system. For this I use ssh-agent / AgentForwarding. So I SSH from my localhost to the remote-host and have my SSH identity to use there and can SSH from there on, but with *my* SSH identity from my localhost. This works fine, except for ddev.

When I
- SSH into the remote host via `ssh -A user@host`
- and then `ddev auth ssh`
ddev shows the output below:

```
$ ddev auth ssh
No private keys were found in the directory.
```

So it seems to only read the files within `~/.ssh/` but doesn't recognize the SSH identities that I brought there via the SSH AgentForwarding.

**Comment by rfay** [comment]
It's an interesting idea. DDEV-Local is built for local development environments, so it's assumed that ssh keys would be on the workstation.

**Comment by mrimann** [comment]
I'm perfectly aware that this feature request covers a rare edge-case of usage regarding ddev :-)

So far, we're working with the SSH-Keys on the "remote" server (thus "local" as seen from ddev running on that host). That works for the moment.

**Comment by hanoii** [comment]
I happen to need this as well. Personally I am on OSX and while I personally don't use a docker-based setup for my everyday work, teamwise we use lando and now trying ddev and I help keeping it properly configured, but I don't like D4M so I have a linux VM with docker inside and I ssh into it and do all docker stuff in there. I was hoping this would work here.

On lando I managed to make it work with https://github.com/lando/lando/issues/478#issuecomment-781612804 that's more docker than lando. I am not that versed in ddev yet to know if that approach could work, just pointing it out in case it prompts for an idea.

**Comment by rfay** [comment]
@hanoii AFAICT what you did is exactly what ddev already does with `ddev auth ssh`. 

Although it's possible to carry ssh keys with you using chained `ssh -A`, unfortunately, ddev does not use ssh for access into the container. Even though the command is called `ddev ssh` it actually uses a docker exec command. I don't know of any secure way to proxy into that situation.

It's possible regular ssh into a container may be added in the future, in which case this might work. 

I opened https://github.com/drud/ddev/issues/3097 about the idea of incorporating a regular ssh server, which might get us to this.

Closing this for now, happy to reopen if anybody comes up with a technique (or #3097 might just solve it)

**Comment by davejamesmiller** [comment]
I think #3097 would be a good solution, but in the meantime this worked for me:

```yaml
# <project>/.ddev/docker-compose.ssh-agent.yaml
version: '3.6'

services:
  web:
    volumes:
      - '${SSH_AUTH_SOCK}:/tmp/ssh-agent'
    environment:
      - SSH_AUTH_SOCK=/tmp/ssh-agent
```

```bash
$ ddev restart
...
$ ddev ssh
dave@blog-web:/var/www/html$ ssh-add -l
2048 SHA256:IX...
```

This looks like the same solution as https://github.com/lando/lando/issues/478#issuecomment-781612804 mentioned above, but translated to DDEV.

The only downside is if `$SSH_AUTH_SOCK` changes on the host (e.g. when reconnecting SSH with agent forwarding) the container must be restarted. I work around that by using a symlink that's automatically updated by `~/.bashrc`:

```bash
link="$HOME/.ssh/ssh_auth_sock"
if [[ $SSH_AUTH_SOCK != $link ]] && [[ -S $SSH_AUTH_SOCK ]]; then
    ln -nsf "$SSH_AUTH_SOCK" "$HOME/.ssh/ssh_auth_sock"
fi
export SSH_AUTH_SOCK="$HOME/.ssh/ssh_auth_sock"
```

**Comment by rfay** [comment]
@davejamesmiller are you talking about agent forwarding? It sounds like you're just talking about regular SSH_AUTH_SOCK handling. The reason ddev runs its own agent (`ddev auth ssh` and handles its own SSH_AUTH_SOCK is that the mounting into the container doesn't work on all OSs. 

However, the bug that made it not work on macOS has been resolved, see https://github.com/drud/ddev/issues/1904

**Comment by davejamesmiller** [comment]
@rfay

> are you talking about agent forwarding?

Yes, I'm talking about agent forwarding. `ddev auth ssh` doesn't work for me because there is no `id_rsa` file (or equivalent) inside WSL2, because I use [wsl2-ssh-pageant](https://github.com/BlackReloaded/wsl2-ssh-pageant).

```
$ ddev auth ssh
Docker command 'docker [run -it --rm --volumes-from=ddev-ssh-agent --user=1000 --entrypoint= --mount=type=bind,src=/home/dave/.ssh,dst=/tmp/sshtmp drud/ddev-ssh-agent:v1.17.0-built bash -c cp -r /tmp/sshtmp ~/.ssh && chmod -R go-rwx ~/.ssh && cd ~/.ssh && ssh-add $(file * | awk -F: "/private key/ { print \$1 }")]' failed: exit status 1
Exited with code 1
```

> It sounds like you're just talking about regular SSH_AUTH_SOCK handling.

I'm not sure what you mean by that, since SSH agent forwarding uses SSH_AUTH_SOCK...

> The reason ddev runs its own agent (ddev auth ssh and handles its own SSH_AUTH_SOCK is that the mounting into the container doesn't work on all OSs.

Sure - I'm not suggesting the above will work for everyone, just noting that it works for me, and so may be useful for other people.

Thanks. 😎

**Comment by rfay** [comment]
Thanks so much for that! I didn't know about wsl2-ssh-pageant, which sounds very cool. My strategy so far has been to copy the private keys into the wsl2, which is nowhere near as good. This could be a great solution, and it's possible that now that docker fixed macOS to properly respect SSH_AUTH_SOCK mounting, this could work for lots of people.
