### ISSUE TITLE
Unable to access other ddev site (Drupal 7)  inside the ddev site (Drupal 8) 

### ISSUE THREAD

**Issue by naresh-qed42** [drud/ddev#2511]
![image](https://user-images.githubusercontent.com/49534054/93557209-02783900-f998-11ea-8cb2-a6fb0dce0802.png)

My goal is to upgrade the Drupal 7 site into Drupal 8, for that, I have installed both sites in ddev first.
1. https://drupal-8.9.x.ddev.site
2. https://drupal-7.x.ddev.site
Now to run the upgrade the Drupal 8 site needs to have access the db of Drupal 7 (both are in ddev)

### Drupal 7 site information: ddev describe 

> NAME        TYPE     LOCATION                    URL                           STATUS
>drupal-7.x  drupal7  ~/ddev-projects/drupal-7.x  https://drupal-7.x.ddev.site  running

>Project Information
>PHP version:      	7.2
>NFS mount enabled:	true
>Database type:    	mariadb
>MariaDB version:  	10.2

>URLs

>https://drupal-7.x.ddev.site
>https://127.0.0.1:32777
>http://drupal-7.x.ddev.site:84
>http://127.0.0.1:32778

>MySQL/MariaDB Credentials
>-------------------------
>Username: "db", Password: "db", Default database: "db"
>or use root credentials when needed: Username: "root", Password: "root"
>
>Database hostname and port INSIDE container: db:3306
>To connect to db server inside container or in project settings files:
>mysql --host=db --user=db --password=db --database=db
>Database hostname and port from HOST: 127.0.0.1:32774
>To connect to mysql from your host machine,
>mysql --host=127.0.0.1 --port=32774 --user=db --password=db --database=db

>Other Services
>--------------
>MailHog (https):   	https://drupal-7.x.ddev.site:8026
>MailHog:           	http://drupal-7.x.ddev.site:8025
>phpMyAdmin (https):	https://drupal-7.x.ddev.site:8037
>phpMyAdmin:        	http://drupal-7.x.ddev.site:8036

I think I am making the wrong entry in the below fields:
Database host:127.0.0.1
Database name:db
Database username:db
Database password:db
Port number:32774

can anyone please help me out into this?

**Comment by rfay** [comment]
The host value is never 127.0.0.1, it's always a different container. 

The hostname for the database is always "db" for a regular project. If you're trying to reach a different project (for a migration, for example), the hostname will be `ddev-<projectname>-db`

For more information, please see the [FAQ](https://ddev.readthedocs.io/en/stable/users/faq/) "Can different projects communicate with each other".

And you'll love this article about Drupal migrations: [Migrating from Drupal 6 to Drupal 8 Like a Boss](https://dev.acquia.com/blog/migrating-drupal-6-drupal-8-boss)

**Comment by naresh-qed42** [comment]
Fixed now,
actually there was a problem with the hostname, now set the `Database host:ddev-drupal-7.x-db` and `port:3306` and it worked.
thank you so much @rfay

**Comment by rfay** [comment]
Glad it's working for you!
