### ISSUE TITLE
v1.16.0-alpha3: ddev won't start due to port 80 being occupied, even when project is configured for other ports

### ISSUE THREAD

**Issue by chellman** [drud/ddev#2512]
**Describe the bug**
Projects configured with an alternate port for http (e.g. `router_http_port: 8800`) get blocked from starting when port 80 is in use. In 1.15, ddev starts the web container listening to the configured alternate port, so there's no blockage.

**To Reproduce**

1. Make sure port 80 is being used somehow, e.g. run `nc -l -p 80`.
2. In config.yaml, set `router_http_port` to something other than 80.  I've been using 8800.
3. `ddev start`
4. Get the error `Failed to start <project-name>: Unable to listen on required ports, port 80 is already in use`

**Expected behavior**
The project should start, listening on the configured port.

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: macOS 10.14.6
- Docker Desktop version: 2.3.0.4
- ddev version information: v1.16.0-alpha3
- config.yaml contents for the misbehaving project

```
name: ddev-test
type: php
docroot: ""
php_version: "7.0"
webserver_type: nginx-fpm
router_http_port: "8800"
router_https_port: "4430"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
use_dns_when_possible: true
```

- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

No custom configuration.  This is a freshly `ddev config`ed project.

**Additional context**

I'm not sure if there are any potential conflicts with port 443.

**Comment by rfay** [comment]
I'm using ncat, which has an option to not exit after the connection is made. You get it with `brew install nmap` and then run it with `ncat -l -k -p 80`
