### ISSUE TITLE
Update snapshot to deal better with existing named snapshots

### ISSUE THREAD

**Issue by chellman** [drud/ddev#2515]
**Is your feature request related to a problem? Please describe.**
I just tried to overwrite a snapshot I'd created a couple minutes before, expecting that ddev might give me an error like "that snapshot already exists" if it was a problem.  Instead I got this:

```
Failed to create snapshot: Failed to run docker-compose [-f /Users/chellman/Sites/ddev-test/.ddev/.ddev-docker-compose-full.yaml exec -w /home -T db bash -c set -eu && ( $(/backuptool.sh) --backup --target-dir=/mnt/ddev_config/db_snapshots/named-snapshot --user=root --password=root --socket=/var/tmp/mysql.sock 2>/var/log/mariadbackup_backup_named-snapshot.log && cp /var/lib/mysql/db_mariadb_version.txt /mnt/ddev_config/db_snapshots/named-snapshot)], err='exit status 1', stdout='', stderr='', stdout=, stderr=
Failed to snapshot ddev-test: Failed to run docker-compose [-f /Users/chellman/Sites/ddev-test/.ddev/.ddev-docker-compose-full.yaml exec -w /home -T db bash -c set -eu && ( $(/backuptool.sh) --backup --target-dir=/mnt/ddev_config/db_snapshots/named-snapshot --user=root --password=root --socket=/var/tmp/mysql.sock 2>/var/log/mariadbackup_backup_named-snapshot.log && cp /var/lib/mysql/db_mariadb_version.txt /mnt/ddev_config/db_snapshots/named-snapshot)], err='exit status 1', stdout='', stderr=''
```

Deleting the snapshot myself allowed it to proceed, but I think this could be improved.

**Describe the solution you'd like**
Ideally two things:

1.  Check whether the snapshot exists on the host before trying to execute the command.  If it does, return an error saying "that snapshot already exists", with maybe a reference to...
2. Add a switch to the snapshot command, `--overwrite` or the like, to delete and recreate the snapshot with the same name, or however works best.

**Describe alternatives you've considered**
The error message from Docker is really not particularly helpful. This is my best idea, at least for now, to deal with this.

**Comment by rfay** [comment]
Related: https://github.com/drud/ddev/issues/1886 about the overall interface to snapshotting.

**Comment by rfay** [comment]
Hoping you'll try out v1.17.0-alpha3 and give your feedback!
