### ISSUE TITLE
Add `ddev config local` command to configure a config.local.yaml file

### ISSUE THREAD

**Issue by gilbertsoft** [drud/ddev#2521]
**Is your feature request related to a problem? Please describe.**
`ddev config` with all it's options is great to automate the project setup but it's currently not possible to make changes for the `config.local.yaml`.

**Describe the solution you'd like**
A new sub command `ddev config local` which saves the options to `config.local.yaml` instead of the `config.yaml` would be great and makes the configuration of local options much easier.

**Describe alternatives you've considered**
Currently the `config.local.yaml` has to be changed in the editor.

**Comment by rfay** [comment]
Not a bad idea at all. Not sure the name would be right, and it might be quite a lot of work. The main config.go is quite a mess.

**Comment by gilbertsoft** [comment]
The config.go command does not look so bad on a first sight. I see things which could be optimized like
```
	if hostHTTPSPortArg != "" {
		app.HostHTTPSPort = hostHTTPSPortArg
	}

	if hostDBPortArg != "" {
		app.HostDBPort = hostDBPortArg
	}

	// If the mariaDBVersionArg is set, use it
	if cmd.Flag("mariadb-version").Changed {
		app.MariaDBVersion = mariaDBVersionArg
	}
```

Tons of the same lines which could be reduced each one to one line only by using a function.

I'm happy to provide you a cleaner and shorter solution here and add the suggested change if I find the time.

**Comment by rfay** [comment]
I'm fine with this if somebody wants to spend some time on it, but don't think it's ever going to get prioritized otherwise. Closing for now.
