### ISSUE TITLE
Add support for TablePlus

### ISSUE THREAD

**Issue by andy-blum** [drud/ddev#2522]
**Is your feature request related to a problem? Please describe.**
While SequelPro is still functional, it seems development on that project has stalled out, with the last complete [test build](https://sequelpro.com/test-builds) being over 1 year old and the [last full release](https://github.com/sequelpro/sequelpro/releases/) being more than 4 years old.

**Describe the solution you'd like**
It might be a good idea to add support for commands similar `ddev sequelpro` but for actively maintained SQL tools like [TablePlus](https://tableplus.com/) which has the added benefit of being available on Mac/Windows/Linux

**Comment by rfay** [comment]
SequelAce has already been added to ddev in the current alphas... Feel free to copy it and make a shell command for TablePlus and do a PR. Should be easy as pie.

**Comment by andy-blum** [comment]
Cool. I'll dive in and take a swing at it probably end of next week or after that as part of [Hacktoberfest](https://hacktoberfest.digitalocean.com/)

**Comment by andy-blum** [comment]
Saw the recent pre-release announcement with this added, thanks!

I do have a question though: Is there any specific reason application launching is only available in the mac version? tableplus is available on mac/win/linux as well. (I don't have the Go or OS skills to know if this is even possible or how to do it)

**Comment by rfay** [comment]
That's awesome, I didn't know Tableplus was available everywhere. It would be wonderful to have it recognized on Windows and Linux. It's not hard, either, and it's just shell scripting. The [tableplus script](https://github.com/drud/ddev/blob/master/cmd/ddev/cmd/global_dotddev_assets/commands/host/tableplus) would just have to be updated to look something like the [mysqlworkbench example](https://github.com/drud/ddev/blob/master/cmd/ddev/cmd/dotddev_assets/commands/host/mysqlworkbench.example) 

The [launch](https://github.com/drud/ddev/blob/c55a0f1d548ce9b4809190aa2f2251a5738d78d4/cmd/ddev/cmd/dotddev_assets/commands/host/launch#L59-L69) command also has support for alternate OSs. 

Are you interested in taking this on @andy-blum ? Or @bobbygryzynger ? Should be pretty straightforward, just requires Windows and Linux environments to test in.

**Comment by andy-blum** [comment]
Unfortunately, I don't really know shell scripting either. I'm a markup/css/js guy that just loves using ddev for local use.

Happy to chip in with documentation issues though, if you have them.

**Comment by bobbygryzynger** [comment]
I don't have a Windows environment to test in, but assuming the app would live in the same location as the in the mysqlworkbench example, I could take a look at this.
