### ISSUE TITLE
There are no environment variables available in local.

### ISSUE THREAD

**Issue by robiasto** [drud/ddev#2524]
**Describe the bug**
there are no environment variables available in local.

**To Reproduce**
You can try  in the db-container 
```
#!/bin/bash

## #ddev-generated
## Description: run mysql client in db container
## Usage: fetchlive
## Example: "ddev mysql" or "ddev mysql -uroot -proot" or "echo 'SHOW TABLES;' | ddev mysql"
## `ddev mysql --database=mysql -uroot -proot` gets you to the 'mysql' database with root privileges

printenv
echo ${DDEV_HOST_DB_PORT}
```
**Version and configuration information**

```
DDEV-Local version      v1.15.3                                
commit                  v1.15.3                                
db                      drud/ddev-dbserver-mariadb-10.2:v1.15.1
dba                     phpmyadmin/phpmyadmin:5                
ddev-ssh-agent          drud/ddev-ssh-agent:v1.15.1            
docker                  19.03.12                               
docker-compose          1.27.2                                 
os                      darwin                                 
router                  drud/ddev-router:v1.15.1               
web                     drud/ddev-webserver:v1.15.3
```

Host computer OS and Version:  macOS Catalina

**Comment by rfay** [comment]
DDEV_HOST_DB_PORT could never be useful on the db container. It's the port on the *host*, so is meaningless inside the db container.

Could you say what you're trying to accomplish?

**Comment by robiasto** [comment]
I try to add `https://github.com/drud/ddev-contrib/tree/master/custom-commands/fetchproductiondb`
to commands/db. It display this error: 
```
mkdir: cannot create directory '/.dumps': Permission denied
```
${DDEV_APPROOT} ist empty

I can only use vars from docker-compose-base.yaml and docker-compose-full.yaml

File: ddev-docker-compose-base.yaml
Container: db
```
environment:
      - COLUMNS=$COLUMNS
      - LINES=$LINES
      - TZ=
      - DDEV_PROJECT=t3-dev-name
```

File: ddev-docker-compose-full.yaml
Container: db
```
 environment:
      COLUMNS: '312'
      DDEV_PROJECT: t3-dev-name
      HOST_DB_PORT: '123'
      LINES: '21'
      TZ: ''
```

To be clear, that there is no project configuration issue. 
I tried the sctipt below in a clean build, directly after `ddev config`.
Maybe the DDEV_HOST_DB_PORT does not make any sense there, but it ist a part of the vars in db/README.txt 
and the problem affects all environment vars

```
printenv
echo ${DDEV_HOST_DB_PORT}
```

**Comment by robiasto** [comment]
Sorry, my fault.
It wasn't the correct container.

**Comment by rfay** [comment]
Glad it's working for you!
