### ISSUE TITLE
changelogger - CLI Tool for creating consistent and committable changelog entries

### ISSUE THREAD

**Issue by fschmittlein** [drud/ddev#2525]
Maybe the changelogger (https://github.com/churchtools/changelogger) can be included in ddev?

**Comment by rfay** [comment]
Thanks for the suggestion. What would you do with it if it were included? Where would you include it, in the web container?

Anyway, please say more about how you'd like to use it and how it would affect your workflow.

**Comment by rfay** [comment]
Didn't get a response from you @fschmittlein so I'm going to close this for now, and happy to continue the conversation and/or reopen this issue, but it's really important for you to explain why you would want this change.
