### ISSUE TITLE
Running phpunit tests PDOException: SQLSTATE[HY000] [2002] Connection timed out

### ISSUE THREAD

**Issue by tommym9** [drud/ddev#2530]
Hi,

I've followed the excellent guide here: https://mglaman.dev/blog/running-drupals-phpunit-test-suites-ddev for getting phpunit running in ddev with Drupal, but I've run into an issue when connecting to the database and I'm struggling to debug.

I've got `drupal/core-dev` as a dev requirement so that I can run tests. I copied the core `phpunit.xml.dist` file and have moved that into my root directory:

```
<?xml version="1.0" encoding="UTF-8"?>

<!-- TODO set checkForUnintentionallyCoveredCode="true" once https://www.drupal.org/node/2626832 is resolved. -->
<!-- PHPUnit expects functional tests to be run with either a privileged user
 or your current system user. See core/tests/README.md and
 https://www.drupal.org/node/2116263 for details.
-->
<phpunit bootstrap="web/core/tests/bootstrap.php" colors="true"
         beStrictAboutTestsThatDoNotTestAnything="true"
         beStrictAboutOutputDuringTests="true"
         beStrictAboutChangesToGlobalState="true"
         printerClass="\Drupal\Tests\Listeners\HtmlOutputPrinter">
  <php>
    <!-- Set error reporting to E_ALL. -->
    <ini name="error_reporting" value="32767"/>
    <!-- Do not limit the amount of memory tests take to run. -->
    <ini name="memory_limit" value="-1"/>
    <!-- Example SIMPLETEST_BASE_URL value: http://localhost -->
    <env name="SIMPLETEST_BASE_URL" value="http://localhost"/>
    <!-- Example SIMPLETEST_DB value: mysql://username:password@localhost/databasename#table_prefix -->
    <env name="SIMPLETEST_DB" value="mysql://db:db@db/db"/>
    <!-- Example BROWSERTEST_OUTPUT_DIRECTORY value: /path/to/webroot/sites/simpletest/browser_output -->
    <env name="BROWSERTEST_OUTPUT_DIRECTORY" value="sites/simpletest/browser_output"/>
    <!-- To have browsertest output use an alternative base URL. For example if
     SIMPLETEST_BASE_URL is an internal DDEV URL, you can set this to the
     external DDev URL so you can follow the links directly.
    -->
    <env name="BROWSERTEST_OUTPUT_BASE_URL" value=""/>
    <!-- To disable deprecation testing completely uncomment the next line. -->
    <!-- <env name="SYMFONY_DEPRECATIONS_HELPER" value="disabled"/> -->
    <!-- Example for changing the driver class for mink tests MINK_DRIVER_CLASS value: 'Drupal\FunctionalJavascriptTests\DrupalSelenium2Driver' -->
    <env name="MINK_DRIVER_CLASS" value=''/>
    <!-- Example for changing the driver args to mink tests MINK_DRIVER_ARGS value: '["http://127.0.0.1:8510"]' -->
    <env name="MINK_DRIVER_ARGS" value=''/>
    <!-- Example for changing the driver args to phantomjs tests MINK_DRIVER_ARGS_PHANTOMJS value: '["http://127.0.0.1:8510"]' -->
    <env name="MINK_DRIVER_ARGS_PHANTOMJS" value=''/>
    <!-- Example for changing the driver args to webdriver tests MINK_DRIVER_ARGS_WEBDRIVER value: '["chrome", { "chromeOptions": { "w3c": false } }, "http://localhost:4444/wd/hub"]' For using the Firefox browser, replace "chrome" with "firefox" -->
    <env name="MINK_DRIVER_ARGS_WEBDRIVER" value=''/>
  </php>
</phpunit>
```
I'm then running the tests by `ddev ssh` and then navigating to my `web` directory and running:

`../vendor/bin/phpunit -v -c ../phpunit.xml path-to-test`

But I'm getting a connection refused error from MySql:

```
Exception: PDOException: SQLSTATE[HY000] [2002] Connection refused
Drupal\Component\DependencyInjection\PhpArrayContainer->createService()() (Line: 79)
```

The db string is being pulled through to the connection in `web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php` as a var_dump of `$connection_options` shows:

```
array(8) {
  ["driver"]=>
  string(5) "mysql"
  ["username"]=>
  string(2) "db"
  ["password"]=>
  string(2) "db"
  ["host"]=>
  string(2) "db"
  ["database"]=>
  string(2) "db"
  ["namespace"]=>
  string(33) "Drupal\Core\Database\Driver\mysql"
  ["prefix"]=>
  array(1) {
    ["default"]=>
    string(12) "test59707422"
  }
  ["pdo"]=>
  array(5) {
    [3]=>
    int(2)
    [1000]=>
    bool(true)
    [1005]=>
    bool(true)
    [20]=>
    bool(true)
    [1013]=>
    bool(false)
  }
}
```

I'm going to keep investigating at my end, but any help is much appreciated.

Cheers

Tom

**Comment by rfay** [comment]
The credentials look right, but I think it's not using those credentials. It's probably using "localhost" somewhere for the host. 

You can easily tell if "connection refused" is valid, just `ddev ssh` and `telnet db 3306`. If it connects, the connection is not being refused. 

Please note the many resources on this topic in https://github.com/drud/ddev-contrib as well, including at least one based on Matt's article (https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/drupalci-chromedriver)

**Comment by rfay** [comment]
Are you possibly running phpunit on the host instead of inside the container? It needs to be running in the web container for those credentials to work.

**Comment by tommym9** [comment]
@rfay 

Thanks for the quick reply! `telnet db 3306` works just fine so it doesn't look like thats the problem.

I've just clocked that a new file `web/sites/simpletest/32770135/settings.php` with some odd looking settings has been added, so I'm going to investigate if that is being used instead of my settings.

Running these commands inside the container so should be good to use `db` as the database host.

I'll report back!

Cheers

Tom

**Comment by tommym9** [comment]
OK odd as you like. 

Looks like simpletest created a settings.php which had placeholders instead of actual db settings in it and then decided to use those which caused the issue.

Nowt to do with ddev, but thanks for your help on getting it debugged @rfay 

Closing now and I'm going to have a lie down.

**Comment by tommym9** [comment]
Hi,

For anyone else bumping into this issue, here is some more info. From what I can gather simpletest has done the following:

- ignored the db string in phpunit.xml
- made a copy of default.settings.php and stuck that into `sites/default/simpletest` directory

Then used those db credentials to try and connect to the database. The debug I added was showing the settings from `phpunit.xml` but they aren't being used at all.

Not sure what the fix is here as I seem to be the only person having the issue so its most likely a mis-configuration on my part.
