### ISSUE TITLE
Replace sequelpro command with sequelace

### ISSUE THREAD

**Issue by Mosnar** [drud/ddev#2532]
**Is your feature request related to a problem? Please describe.**
Sequel Pro is no longer maintained, hasn't been updated in years, and is prone to bugs.

**Describe the solution you'd like**
Sequel Pro has been forked to [Sequel Ace](https://github.com/Sequel-Ace/Sequel-Ace) and is a viable, maintained alternative.

**Comment by rfay** [comment]
Sequel Ace  and Table Plus are already supported in ddev v1.16.0-alpha5. If they're installed, and you're on mac, they show up.

The original issue was https://github.com/drud/ddev/issues/2369

Cllosing.
