### ISSUE TITLE
Provide updated mysql 8.0.x (Unpin mysql 8.0)

### ISSUE THREAD

**Issue by dawehner** [drud/ddev#2546]
**Is your feature request related to a problem? Please describe.**
Mysql's latest release is 8.0.21, which has a bunch of security fixes on top of the current ddev version of 8.0.19.

**Describe the solution you'd like**
Updating the makefile to point to 8.0.21 would certainly be enough.
I wonder, whether in the future it could be possible to specify the exact mysql version in the `config.yaml`. Right now specifying 8.0.21 results in:

```
λ ddev restart
Failed to get project(s): invalid mysql_version: 8.0.21, must be one of [5.5 5.6 5.7 8.0]
```

**Comment by rfay** [comment]
In ddev you always use only the Major.Minor ("8.0") to get 8.0.x. Current "8.0" behavior gets 8.0.19. However... you remind me that 8.0 was pinned at 8.0.19 due to a release problem with mysql and xtrabackup several months back, and it's time to free it and let it move forward (as long as they've solved that problem)

**Comment by rfay** [comment]
Thanks for pointing this out @dawehner . mysql 8.0 is unpinned, so 8.0.21 will be in next alpha and in v1.16.0

**Comment by dawehner** [comment]
> Thanks for pointing this out @dawehner . mysql 8.0 is unpinned, so 8.0.21 will be in next alpha and in v1.16.0

That's perfect! Thank you @rfay

**Comment by rfay** [comment]
Unfortunately, just as soon as this went in, Mysql 8.0.22 came out. And it was incompatible with xtrabackup again. So I had to pin Mysql to 8.0.21 :( See https://github.com/drud/ddev/pull/2570 for the xtradb issue, etc.

**Comment by dawehner** [comment]
Why is nothing ever easy
