### ISSUE TITLE
Repeatable CMS page access performance benchmark tools dev environments

### ISSUE THREAD

**Issue by rfay** [drud/ddev#256]
## What happened (or feature request):

There are probably three key areas of performance interest for users of ddev:

* How long does it take me to set up in the beginning
* How long does it take to start and set up a site (including importing)
* How does accessing the site feel? Can I get my job done without waiting for pages to load?

This ticket is about the third: Measuring the time it takes to access key pages in a CMS

We need access stats on a number of axes:
* Authenticated and unauthenticated (Especially admin auth, as many devs will use admin privs)
* Drupal and Wordpress generated pages, and static files

The tools that we use to do this should be able to create a site and populate it (by import), then provide page access times in a comparable format. They should work identically with ddev and other competing environments.

There are many tools available for benchmarking web apps, but it would be wonderful if we could also integrate this process with our Circleci builds (or probably a special circleci build dedicated to performance). That means that it needs to be package-able on linux.

## Related source links or issues:

**Comment by rickmanelius** [comment]
@rfay Fair to say this is handled in https://github.com/drud/ddev/pull/264 and https://github.com/drud/ddev/issues/238?

**Comment by rfay** [comment]
When #264 goes in it will automatically close this one.
