### ISSUE TITLE
v1.16.0-alpha6 -> additional_fqdns domains not loading in Firefox/Safari OSX

### ISSUE THREAD

**Issue by karlosb** [drud/ddev#2562]
**Describe the bug**
After upgrading to v1.16.0-alpha6 and running 'ddev config' site will not load via the additional_fqdns domain in either Firefox or Safari but *** will *** load in Chrome. This is on macOS Catalina 10.15.7

**To Reproduce**

1. Ran upgrade (via HomeBrew) to latest v1.16.0-alpha6 release.
2. Re-run 'ddev config' on existing ddev site project.
3. Load project via URL stated in config.yaml (under 'additional_fqdns').

**Expected behavior**
Should normally load site (this worked under v15.x release).

**Screenshots**

**Version and configuration information (please complete the following information):**

macOS Catalina 10.15.7
MacBook Pro (Retina, 15-inch, Mid 2015)
Docker Desktop 2.4.0.0 (48506) 
Docker Desktop version if on macOS or Windows (from "About Docker Desktop")

- DDEV Version:

DDEV-Local version	v1.16.0-alpha6
commit            	COMMIT should be overridden
db                	drud/ddev-dbserver-mariadb-10.2:v1.16.0-alpha5
dba               	phpmyadmin:5
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.16.0-alpha5
docker            	19.03.13
docker-compose    	1.27.4
os                	darwin
router            	drud/ddev-router:v1.16.0-alpha5
web               	drud/ddev-webserver:v1.16.0-alpha5

- config.yaml contents for the misbehaving project
name: project1
type: php
docroot: ""
php_version: "5.6"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns:
- local.project1
mariadb_version: "10.2"
provider: default
use_dns_when_possible: false
timezone: Europe/London

- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?
No

**Additional context**
Add any other context about the problem here. Thanks!

**Comment by rfay** [comment]
Sounds like a problem with the browser, right?
I assume it works fine with curl?

**Comment by karlosb** [comment]
Hi Randy

I have just tried:

curl -X POST http://local.project1 <http://local.project1/>

And I got get:

curl: (52) Empty reply from server

And project is definitely running?

**Comment by rfay** [comment]
You wouldn't use POST to experiment. Just `curl http://local.project1`

I assume `ping local.project1` shows it pinging 127.0.0.1?

**Comment by karlosb** [comment]
No it I get the following:

ping http://local.project <http://local.project/>1
PING http://local.proejct <http://local.proejct/>1 (92.242.132.24): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6
Request timeout for icmp_seq 7
Request timeout for icmp_seq 8

And timeout goes on for ages...

**Comment by rfay** [comment]
Ah, you have an invalid setting for local.project1. Perhaps it's in DNS? It should be 127.0.0.1. You're not using ddev. You're trying to access a completely different website. Wherever 92.242.132.24 is.

**Comment by rfay** [comment]
You should probably use a name that isn't resolved by your computer or DNS server. Perhaps "something.example.com"

**Comment by karlosb** [comment]
I have about 50+ plus sites all use ' local.domain_name ' in this style and they were all working ok.

In fact most of them still do until I run 'ddev config' on them and it brings the project up to date with v1.16.0-apha6 and then they stop working using that local.domain_name option (additional_fqdns).

Also I did try working with different DNS servers on mac OSX to try and resolve the issue, hence I have these in my DNS:

1.0.0.1
1.1.1.1
8.8.8.8
8.8.4.4
9.9.9.9
149.112.112.112

**Comment by karlosb** [comment]
In fact what is even bizarre about this is that I have ddev site called:

https://local.exp37

Which loads 100% ok in Firefox and all browsers on my BroadBand or 4G mobile network.

But when I run the terminal ping I get:
PING https://local.exp37 (92.242.132.24): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4

**Comment by rfay** [comment]
Please look in your /etc/hosts file. The most likely thing is that you have something in there for 92.242.132.24

Anyway, it's not ddev you're trying to access. 

ddev only tries to add to /etc/hosts when the name is not resolvable. In your environment it's resolvable. 

BTW, 92.242.132.24 has a reverse lookup of unallocated.barefruit.co.uk . Anything you know about?

**Comment by karlosb** [comment]
> BTW, 92.242.132.24 has a reverse lookup of unallocated.barefruit.co.uk . Anything you know about?

Absolutely no idea what that is!

**Comment by karlosb** [comment]
Just ran sudo nano /private/etc/hosts 
and there is nothing in my hosts file for 92.242.132.24

**Comment by rfay** [comment]
You're not using ping right either. 

It would be `ping local.exp32`, not `ping https://local.exp37`

We'll probably need to start over here. 

The first thing is this. When you want to use additional_fqdns, ddev tries to add them to your /etc/hosts file. You should see them there. 

To see if name lookup is working, you can use `ping <hostname>` to see if it looks them up. If it doesn't answer with 127.0.0.1, then name resolution isn't working on your computer, or it's misconfigured, or it has bizarre DNS.

**Comment by karlosb** [comment]
> You're not using ping right either.
> 
> It would be ping local.exp37, not ping https://local.exp37
> 
Ok I’ve just ran:

ping local.exp37
PING localhost (127.0.0.1): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3

And then ran:

ping local.project1
PING local.project1 (92.242.132.24): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4

You can see that local.exp37 has the correct 127.0.0.1 (not created using v1.16.0-alpha6).

And local.project1 still gets 92.242.132.24 (recently created using v1.16.0-alpha6).

> We'll probably need to start over here.
> 
> The first thing is this. When you want to use additional_fqdns, ddev tries to add them to your /etc/hosts file. You should see them there.
> 
Yes all my additional_fqdns domains are listed within the hosts file so this is ok.

**Comment by rfay** [comment]
Is local.project1 in your /etc/hosts file? What is the IP address there?

**Comment by rfay** [comment]
I should probably ask you why you're using these unusual fqdns... It would be so much easier not to use them. *.ddev.site works great.

**Comment by karlosb** [comment]
> Is local.project1 in your /etc/hosts file? What is the IP address there?
> 
Yes it is there along with all the other domains. 

127.0.0.1 is listed to the left of all the fqdns domain names listed.

I’ve also noticed that the following is there also:

127.0.0.1        kubernetes.docker.internal
127.0.0.1        kubernetes.docker.internal
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
> I should probably ask you why you're using these unusual fqdns... It would be so much easier not to use them. *.ddev.site <http://ddev.site/> works great.
> 

I just prefer the more custom domain names over the default .ddev.site <http://ddev.site/> domain.

To be honest it’s never been an issue using fqdns until I upgraded to v1.16.0-alpha6.

**Comment by rfay** [comment]
Anyway, I think if you'll just spin up a junk site, perhaps using the script in https://gist.github.com/rfay/361c4e1df165774a5262268ef6768884

Then after you've done it, add `additional_fqdns: [something.example.com]` to that project. I predict it will work fine. 

Again, if "local.project1" is in your /etc/hosts with the IP address 127.0.0.1, and you `ping local.project1` and get something else, then your problem has nothing to do with ddev, and everything to do with your computer or your network. I can't help you solve that. 

Note that it's not "ddev.site" that ddev uses by default. It's <projectname>.ddev.site. So every project has a different name.

**Comment by karlosb** [comment]
Just for the record I have switched to 4G network and ran:

ping local.project1
PING localhost (127.0.0.1): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq

So you get the correct 127.0.0.1 resolution but times out.

This also does not load on any browser.

Earlier today this would of worked on all browsers via 4G but now does not load on any.

I'll try creating a new project as mentioned above.

**Comment by karlosb** [comment]
I've just cut and paste the code into a new file testddev.sh and ran:

bash testddev.sh

But does not do anything?

Not sure what I'm doing wrong?

**Comment by karlosb** [comment]
Also:

For local.exp37 I have just pinged the default exp37.ddev.site and still get timeout errors.

But exp37.ddev.site loads all browsers no problem.

ping exp37.ddev.site
PING localhost (127.0.0.1): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6

**Comment by rfay** [comment]
So a firewall or something is blocking you from localhost. The next thing you should do it turn off your firewall and any virus checkers temporarily. Any normal mac can ping localhost and get a response. 

A more exact test is to `telnet localhost 80` (you may have to install telnet) and see if it connects.

But again, if your name resolution is sending you somewhere other than 127.0.0.1 for your project... and you see your project in /etc/hosts... you have to sort out what's wrong with your machine, your network, or your DNS server.

**Comment by karlosb** [comment]
Hi Randy,

Many thanks for the feedback.

I’ve tried knocking off the OSX prefs firewall and it still times out on DDEV fqdns domains, although pinging ‘localhost’ works ok.

In this example I tried another DDEV project with local.brilliant domain:

```
--- local.brilliant ping statistics ---
11 packets transmitted, 0 packets received, 100.0% packet loss
Sites/Bloody-Brilliant/local ping localhost
PING localhost (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.058 ms
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.087 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.071 ms
64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.078 ms
64 bytes from 127.0.0.1: icmp_seq=4 ttl=64 time=0.103 ms
64 bytes from 127.0.0.1: icmp_seq=5 ttl=64 time=0.071 ms
64 bytes from 127.0.0.1: icmp_seq=6 ttl=64 time=0.083 ms
64 bytes from 127.0.0.1: icmp_seq=7 ttl=64 time=0.059 ms
64 bytes from 127.0.0.1: icmp_seq=8 ttl=64 time=0.062 ms
64 bytes from 127.0.0.1: icmp_seq=9 ttl=64 time=0.089 ms
^C
--- localhost ping statistics ---
10 packets transmitted, 10 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.058/0.076/0.103/0.014 ms
Sites/Bloody-Brilliant/local ping local.brilliant
PING local.brilliant (92.242.132.24): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
```

Upon further research I saw something about checking the format of your hosts file as this can put a random IP in place (for example 92.242.132.24 I am getting for DDEV fqdns as above). So I checked the hosts file format:

```
file -b /etc/hosts
ASCII text, with very long lines
```

Not sure wether this should say:

‘ ASCII English text ' instead of just ‘ ASCII text ‘ ?

Also ‘ with very long lines ‘ - I am wondering if this may be causing an error?

For reference here is the contents of my HOSTS file:

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1    <— approx 40+ domains are listed in one big line here —>


255.255.255.255  broadcasthost
::1              localhost



# URL re-directs

127.0.0.1        kubernetes.docker.internal
127.0.0.1        kubernetes.docker.internal
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

**Comment by rfay** [comment]
Your name lookup for local.brilliant is also incorrect:
> PING local.brilliant (92.242.132.24):

You removed the localhost line from your /etc/hosts, so I can't say anything.

Anyway. Perhaps you have a local dns server running. But your name resolution is not working the way you think it is. Your browser requires on your system's name resolution; ddev has no way to influence your browser.

I recommend that you move to using the default *.ddev.site names (and not use fqdn) until you're able to figure out why your system is returning 92.242.132.24 for these name lookups. It's far easier anyway. 

Please do search your /etc/hosts file for 92.242.132.24 to make sure it's not in there somewhere.

OH, I think maybe you use virginmedia or a related server that's doing DNS hijacking to "help" you and serve you ads. https://community.virginmedia.com/t5/Networking-and-WiFi/DNS-hijacking-how-to-disable-opt-out/m-p/4145614

I recommend that you use a reputable DNS server, like 8.8.8.8 (google) or 1.1.1.1 (cloudflare).

**Comment by karlosb** [comment]
Hi Randy,

Many thanks for the further feedback.

Regarding:
> Your name lookup for local.brilliant is also incorrect:
> 
> PING local.brilliant (92.242.132.24):
> 
> You removed the localhost line from your /etc/hosts, so I can't say anything.
> 
Yes I removed the list because it was a bit data sensitive to client site names etc.
> Anyway. Perhaps you have a local dns server running. But your name resolution is not working the way you think it is. Your browser requires on your system's name resolution; ddev has no way to influence your browser.
> 
Ok, understood.
> I recommend that you move to using the default *.ddev.site names (and not use fqdn) until you're able to figure out why your system is returning 92.242.132.24 for these name lookups. It's far easier anyway.
> 
Yes I have been doing, and may just run with this in the future.
> Please do search your /etc/hosts file for 92.242.132.24 to make sure it's not in there somewhere.
> 
> OH, I think maybe you use virginmedia or a related server that's doing DNS hijacking to "help" you and serve you ads. https://community.virginmedia.com/t5/Networking-and-WiFi/DNS-hijacking-how-to-disable-opt-out/m-p/4145614 <https://community.virginmedia.com/t5/Networking-and-WiFi/DNS-hijacking-how-to-disable-opt-out/m-p/4145614>Yes my broadband is with Virgin Media.

No ads appear upon server errors though, but yes I can see from the supplied Virgin Media Support thread that it does mention the BareFruit company (ie. that random IP address 92.242.132.24). So that’s what that is about?!

I did follow that link in the thread to Virgins site to ‘opt out’ of the ‘advanced network search error search’ and clicked to confirm ‘opt out’.

I have re-ran ‘ping local.brilliant’ and still get the 92.242.132.24 with timeout errors 😒

It could be that I have to give it 24 hours for their DNS end to resolve the connection preference, not sure?
> I recommend that you use a reputable DNS server, like 8.8.8.8 (google) or 1.1.1.1 (cloudflare).
> 
Yes I was on the Google 8.8.8.8 DNS already, then have now put the 1.1.1.1 cloud flare one  in place.

Moving forward:

Yes it’s looking very much like the Virgin Media BroadBand connection using the BareFruit DNS 92.242.132.24 IP address.

Not really sure ‘how’ this is happening, and ‘how’ it’s been configured to run like this.

Hence I’ll look further into Virgin Media DNS thing to see how to get this fixed.

However when ’not’ using VirginBroand and using 4G another issue:

I’ve just rebooting this morning using 4G and ‘ping local.brilliant’ resolves to 127.0.0.1 and connects properly without timeout issues. (So definitely Virgin/BareFruit DNS issues hijacking 127.0.0.1).

However…..

Funny thing is though when I load ‘ https://local.brilliant <https://local.brilliant/> ‘ in the Browser it goes to ‘ myPHPAdmin’ for SQL DB connection!!!!

Never seen this before?

**Comment by rfay** [comment]
So we do now have it that it's your network.

You should know that you can change your computer's DNS settings, as suggested earlier. I really recommend not using a provider's DNS if they do this.

**Comment by karlosb** [comment]
Hi Randy,

Yes I’ve just ran some more tests and it turns out it is the wifi connection to a secondary booster adapter that Virgin Media provide (and this was giving the 92.242.132.24 instead of 127.0.0.1)

When I connected directly to the main router the terminal pings always result in 127.0.0.1 no matter what.

So this was the cause!

With the booster adapter unplugged, all  ddev fqdns now load as required (and ping at 127.0.0.01 as expected).

Having said all this I may just stick with the default  .ddev.site domain moving forward to avoid any more issues like this!

**Comment by rfay** [comment]
Yay! Glad you got it sorted out.
