### ISSUE TITLE
ddev auth pantheon does not like hyphens in the auth token provided by Pantheon

### ISSUE THREAD

**Issue by joshuaboltzmc** [drud/ddev#2569]
**Describe the bug**
In some cases, when creating an auth token at Pantheon:
https://dashboard.pantheon.io/users/#account/tokens/

It could be an auth token like so:
`-rD8cLUeEWzs9aaig6BjJaQnvxTw221YbrjwMFXr73DiA`

Notice the hyphen at the beginning.

When then running `ddev auth pantheon <token>`, an issue is encountered where it thinks its a flag being passed into the terminal window
Error: unknown shorthand flag: 'r' in -rD8cLUeEWzs9aaig6BjJaQnvxTw221YbrjwMFXr73DiA

I ran into this issue the first time, revoked the token, created a new token and same issue with it generating a token with a hyphen in the beginning. Luckily, the 3rd time was a charm and it did not include a hyphen at the start and was able to successfully auth with Pantheon via DDev.

**Comment by rfay** [comment]
Thanks for letting us know. It's unusual to let a "-" be part of a token, and even more unusual to let it be at the beginning of a token. So very many commands would fail with this situation.

**Comment by joshuaboltzmc** [comment]
While unusual and probably not typically occurring, I did have it happen 2 times in a row when generating the Pantheon token.

**Comment by rfay** [comment]
`ddev auth pantheon` no longer exists, so this doesn't need to be fiddled with any more.
