### ISSUE TITLE
v1.16.0-alpha7: mariadb_version and mysql_version error even if just mysql_version is set

### ISSUE THREAD

**Issue by susannemoog** [drud/ddev#2571]
**Describe the bug**
Before upgrading to 1.16.0 alpha7, we just used mysql_version in our ddev config, we did not set mariadb version at all. After the                 upgrade we have to explicitly set the latter one to empty, otherwise we'll get an error.

**To Reproduce**
Create a config file like:

```
name: my-little-project
type: php
docroot: public
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mysql_version: "5.7"
provider: default
webimage_extra_packages: []
use_dns_when_possible: true
composer_version: ""
```
Try `ddev start`: 
`both mariadb_version (10.2) and mysql_version (5.7) are set, but they are mutually exclusive`

Then I tried running ddev config, which then adds `mariadb_version: "10.2"` - which obviously does not work either. 

Only manually adding `mariadb_version:` (without value) works.

**Expected behavior**
Either: `ddev config` adds mariadb_version without value when mysql is set, or mariadb_version is optional and does not fall back to 10.2 which then conflicts with mysql.

**Version and configuration information (please complete the following information):**

- Windows 10, WSL2 
- Docker Desktop version 2.4.0.0
- ddev version v1.16.0-alpha7

**Comment by rfay** [comment]
Thanks for testing the alphas, and thanks for the bug report.

You should be able to `ddev config --mariadb-version=""` right, and solve the problem? Doesn't it prompt you to do that? 

Or just manually add to the .ddev/config.yaml:

```
mariadb_version: ""
mysql_version: "5.7"
```

The reason for making both explicit is that it will make it possible to change the default in a future version. I apologize for the inconvenience right now.

**Comment by susannemoog** [comment]
Yes, manually fixing is possible, that's what I meant, I was just confused that it "suddenly" fails and ddev config itself does not fix it - just got used to everything working ;) It's not a real problem and maybe just something for an upgrade guide.
(and no, I got no prompt to set anything, just this `Failed to get project(s): both mariadb_version (10.2) and mysql_version (5.7) are set, but they are mutually exclusive`

**Comment by rfay** [comment]
I do agree that this is a bug, and should be fixed before release. I don't see why it can't be fixed.

I was able to recreate it, but for me `ddev config --mariadb-version=""` fixed it fine, but you shouldn't have to know that.

**Comment by susannemoog** [comment]
Works, thanks :)

**Comment by rfay** [comment]
Thank you so much for reporting this and helping me understand how important it was @susannemoog .
