### ISSUE TITLE
Feature Request: Option for restoring the most recent snapshot

### ISSUE THREAD

**Issue by MrPaulDriver** [drud/ddev#2586]
**Is your feature request related to a problem? Please describe.**
When restoring a snapshot, it often necessary to lookup the name of the snapshot needed. Often this will be the most recent snapshot. 

**Describe the solution you'd like**
It would be good if a command was available which restored the most recent snapshot.

Something like `ddev restore-snapshot -latest`

**Comment by rfay** [comment]
This is a good idea. Could you add this to https://github.com/drud/ddev/issues/1886 and close this one please?

**Comment by MrPaulDriver** [comment]
Will do
