### ISSUE TITLE
`make container` doesn't work on arm64, at least ddev-webserver

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2588]
**Describe the bug**

`make container` fails on arm64. It's possible this is misconfiguration of bad version of buildx on Debian Buster?

```
$ make container
Makefile:21: warning: overriding recipe for target 'push'
../containers_shared.mak:15: warning: ignoring old recipe for target 'push'
container: drud/ddev-webserver:v1.16.0-alpha8-35-g192ca359
docker buildx build -o type=docker --label com.ddev.buildhost=pi1.thefays.us --target=ddev-webserver  -t drud/ddev-webserver:v1.16.0-alpha8-35-g192ca359  .
unknown shorthand flag: 'o' in -o
See 'docker --help'.
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: [e.g. Windows 10, macOS Catalina]
- Docker Desktop version if on macOS or Windows (from "About Docker Desktop")
- ddev version information (use `ddev version`)
- config.yaml contents for the misbehaving project
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

**Additional context**
Add any other context about the problem here. Thanks!

**Comment by dennisameling** [comment]
AFAIK this issue only shows up if `buildx` is not installed or installed incorrectly. Could you try running `docker buildx` and seeing what happens?

**Comment by rfay** [comment]
Yup, you;re right:
```
$ docker buildx
docker: 'buildx' is not a docker command.
```

I wonder why the error message says "unknown shorthand flag o"
