### ISSUE TITLE
'drupal9' is not a valid project type when entering it in ddev config setup ( ddev version v1.11.2 )

### ISSUE THREAD

**Issue by therobyouknow** [drud/ddev#2596]
`ddev version v1.11.2` - will update to see if still issue.

```
Project Type [drupal8, wordpress, typo3, backdrop, php, drupal6, drupal7] (php): drupal9
'drupal9' is not a valid project type. Allowed project types are: drupal8, wordpress, typo3, backdrop, php, drupal6, drupal7
```

So I chose `drupal8` as `drupal9` isn't offered. Wish me luck. I have this setup on an existing Ubuntu 20.04 machine but am now setting up for a macOS 10.15.7 machine.

I looked at:
https://github.com/drud/ddev/issues?q=is%3Aissue+drupal9

But not seeing similar enough to this situation.

OK to use `drupal8` for time being? I'd be inclined to think so.

**Comment by rfay** [comment]
The current stable version of ddev is v1.15.3, you're about a year behind. Drupal 9 didn't exist when your version of ddev was released.

I imagine you've got it now.
