### ISSUE TITLE
After upgrading to alpha9 (but also upgrading computer OS) ddev auth ssh gives permission issue

### ISSUE THREAD

**Issue by mlncn** [drud/ddev#2597]
**Describe the bug**

Running `ddev auth ssh` gives this error:

> Docker command 'docker [run -it --rm --volumes-from=ddev-ssh-agent --user=1000 --entrypoint= --mount=type=bind,src=/home/mlncn/.ssh,dst=/tmp/sshtmp drud/ddev-ssh-agent:v1.16.0-alpha5-built bash -c cp -r /tmp/sshtmp ~/.ssh && chmod -R go-rwx ~/.ssh && ssh-add]' failed: exit status 2

**To Reproduce**
`$ ddev poweroff`
`$ ddev auth ssh`
```
The DDEV_UID variable is not set. Defaulting to a blank string. 
The DDEV_GID variable is not set. Defaulting to a blank string. 
Building ddev-ssh-agent 
Creating ddev-ssh-agent ... done
 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
Error connecting to agent: Permission denied
Docker command 'docker [run -it --rm --volumes-from=ddev-ssh-agent --user=1000 --entrypoint= --mount=type=bind,src=/home/mlncn/.ssh,dst=/tmp/sshtmp drud/ddev-ssh-agent:v1.16.0-alpha5-built bash -c cp -r /tmp/sshtmp ~/.ssh && chmod -R go-rwx ~/.ssh && ssh-add]' failed: exit status 2 
```

**Expected behavior**

Asks me to type my SSH key passphrase (and complete without error).

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: System76 PopOS (Ubuntu-based) 20.10
$ which docker
/usr/bin/docker
$ docker --version
Docker version 19.03.13, build 4484c46
- ddev version information (use `ddev version`)
$ ddev version
DDEV-Local version	v1.16.0-alpha9                                   
commit            	COMMIT should be overridden                      
db                	drud/ddev-dbserver-mariadb-10.2:20201026_hardened
dba               	phpmyadmin:5                                     
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.16.0-alpha5               
docker            	19.03.13                                         
docker-compose    	1.25.0-rc4                                       
os                	linux                                            
router            	drud/ddev-router:v1.16.0-alpha5                  
web               	drud/ddev-webserver:20201026_hardened       
- config.yaml contents for the misbehaving project: N/A
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them? N/A

**Additional context**
Add any other context about the problem here. Thanks!

**Comment by rfay** [comment]
Thanks for testing! I think if you do a ddev start it will work. Not sure if it's always been that way.

**Comment by mlncn** [comment]
Still getting it after `ddev start`.  Must be something else on my system but i have no idea what.  Ownership is all good.

**Comment by mlncn** [comment]
OK,

```
ddev poweroff
ddev start
ddev auth ssh
```
worked!

**Comment by rfay** [comment]
Reopening; I think it should work the way you expected.

**Comment by rfay** [comment]
This regression seems to have been introduced in #2505 in v1.16.0-alpha3.
