### ISSUE TITLE
Improve Magento 2 quickstart to deal with Elasticsearch requirement

### ISSUE THREAD

**Issue by VivekShingala** [drud/ddev#2600]
**Describe the bug**
I installed ddev on my machine and used Magento 2 Quickstart steps to install latest Magento version but I got the error while setting up the magento.

**To Reproduce**

1. Go to 'Magento 2 Quickstart'
2. Run commands step by step
3. Run magento setup command `bin/magento setup:install  --db-host=db --db-name=db --db-user=db --db-password=db  --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com  --admin-user=admin --admin-password=admin123 --language=en_US`

**Expected behavior**
Magento setup should complete without any error

**Screenshots**
![https://snipboard.io/b8dyOM.jpg](https://snipboard.io/b8dyOM.jpg)

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: macOS Catalina
- Docker Desktop version if on macOS or Windows: 2.5.0.0
- ddev version information: v1.15.3

**Additional context**
We need one more container for elasticsearch for Magento 2.4.x.
- You must install and configure Elasticsearch 7.6.x before upgrading to Magento 2.4.x.
- Magento 2.4.x is tested with Elasticsearch 7.6.x only. You can use other 7.x versions at your discretion, but we recommend using the tested version of Elasticsearch.
- [More info here](https://devdocs.magento.com/guides/v2.4/install-gde/prereq/elasticsearch.html)

**Comment by rfay** [comment]
As you say, elasticsearch is not included by default, but there is a [recipe](https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/elasticsearch) for it in ddev-contrib. Previous versions of Magento haven't had it enabled by default though.

**Comment by VivekShingala** [comment]
Thanks @rfay 

I was looking for the recipe which you have mentioned. That solves this issue.

**Comment by rfay** [comment]
Thanks @VivekShingala - But previously the quickstart worked out of the box. You're saying it does not with Magento 2.4? 

Obviously Elasticsearch is a preferred add-on. But if it fails on initial start because of expecting elasticsearch the quickstart should be improved.

**Comment by VivekShingala** [comment]
Yes, quickstart breaks when we install 2.4 and elasticsearch container should be the part of it so that the installation go smooth.

**Comment by rfay** [comment]
Reopening for docs.
