### ISSUE TITLE
Add generic ddev pull provider

### ISSUE THREAD

**Issue by freelock** [drud/ddev#2601]
**Is your feature request related to a problem? Please describe.**

I like how easy it is to pull a recent database and files from a Pantheon site. However, we only use Pantheon on a small fraction of our sites. To streamline the provisioning of a site, I would like to add a provider to specify where to pull a recent database backup and file archive from.

**Describe the solution you'd like**

I am thinking about having our CI system publish a manifest for each file, providing a link for the most recent database and asset tarball. I'm thinking from a user perspective, this process would start with:

`ddev config custom https://path.to/manifest.json`

... this would be protected by an auth token or basic auth somehow, so some sort of authentication scheme (probably similar to Pantheon's token).

That would store the location in the .ddev/config file, so that any of our devs that wanted to get set up could then...

`ddev pull`

to get a fresh db and asset tarball, which DDEV then imports appropriately.

**Describe alternatives you've considered**

Other possibilities: allow multiple environments or sets of sources within the manifest file, designate a source environment or command for use with `drush rsync` and `drush sql-sync`...

**Comment by rfay** [comment]
Thanks for the careful writeup. Isn't this the same as https://github.com/drud/ddev/issues/2194 ?

**Comment by freelock** [comment]
Ha, yes, it sounds like exactly the same motivation, slightly different solution. I'll close this and comment over there...
