### ISSUE TITLE
Magento 2 Quickstart: PHP outdated

### ISSUE THREAD

**Issue by Morgy93** [drud/ddev#2602]
**Describe the bug**
I just tried to follow the [Magento 2 Quickstart](https://ddev.readthedocs.io/en/stable/users/cli-usage/#magento-2-quickstart) but it's not possible since the PHP version is outdated for the container `ddev-magento2-web` which is using php7.2

Error: `magento/product-community-edition 2.4.1 requires php ~7.3.0||~7.4.0 -> your PHP version (7.2.32) does not satisfy that requirement.`

**To Reproduce**

1. Go to https://ddev.readthedocs.io/en/stable/users/cli-usage/#magento-2-quickstart
2. Follow steps:

```sh
mkdir ddev-magento2 && cd ddev-magento2
ddev config --project-type=magento2 --docroot=pub --create-docroot
ddev start
ddev composer create --repository=https://repo.magento.com/ magento/project-community-edition
```
Last one will fail because of outdated php version

**Expected behavior**
I expect the quickstart guide to work without any errors.

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: Windows 10
- Docker Desktop version: 2.5.0.0 (49427)
- ddev version information:
```
DDEV-Local version      v1.15.3
commit                  v1.15.3
db                      drud/ddev-dbserver-mariadb-10.2:v1.15.1
dba                     phpmyadmin/phpmyadmin:5
ddev-ssh-agent          drud/ddev-ssh-agent:v1.15.1
docker                  19.03.13
docker-compose          1.25.0-rc4
os                      linux
router                  drud/ddev-router:v1.15.1
web                     drud/ddev-webserver:v1.15.3
```
- config.yaml contents for the misbehaving project:
```
name: magento2
type: magento2
docroot: pub
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
use_dns_when_possible: true

... only comments below here ...
```
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?
Nope, none.

**Additional context**
I'm able to fix it, but the quickstart guide should work out of the box, shouldn't it.

**Comment by rfay** [comment]
Thanks for the report!

**Comment by rfay** [comment]
@Morgy93 ddev has had PHP 7.3 as default for at least a year now. Are you running ddev v1.15.3?

**Comment by Morgy93** [comment]
@rfay The magento2 project type contains a function which overwrites the default php version to use php7.2
https://github.com/drud/ddev/blob/master/pkg/ddevapp/magento.go#L171

I already tried to create a PR for this #2603

**Comment by rfay** [comment]
Excellent, thanks! I guess previous magento2 required 7.2 and not 7.3.
