### ISSUE TITLE
Move from Buildkite to GitHub Actions

### ISSUE THREAD

**Issue by dennisameling** [drud/ddev#2604]
**Is your feature request related to a problem? Please describe.**
Buildkite seems quite slow and sometimes unreliable - builds have to be restarted sometimes.

**Describe the solution you'd like**
Run Windows, MacOS and Linux amd64 tests on GitHub Actions

**Describe alternatives you've considered**
N/A

**Additional context**
I tried setting up [GitHub Actions on Windows](https://github.com/dennisameling/ddev/blob/switch-to-github-actions/.github/workflows/windows-containers.yml), but found out later that GitHub's hosted runners [only support Windows containers (not Linux containers) at this time](https://github.com/actions/virtual-environments/issues/1143#issuecomment-651178811). Apart from that, we either need to use the Hyper-V or WSL2 backend on Windows, but Hyper-V isn't enabled on GitHub Actions and WSL2 can't be enabled on Windows Server 2019 because the image version is too old (most likely need to wait for Windows Server 2021 to get WSL2 support). I'm pretty sure the 2021 Windows Server LTSC build will have WSL2 support, so that's only a matter of time.

Regarding MacOS, I haven't tested things yet, but https://github.com/actions/virtual-environments/issues/1143#issuecomment-652264388 looks promising, which basically installs Docker on Mac using Homebrew. Do you want me to look into that further? Guess that would be a great start! Can't promise anything regarding NFS yet, but let's see how far we can get with the "regular" tests!

**Comment by rfay** [comment]
Thanks for this! The problems you ran into with Windows are the same old same old :( 

Looks like some good stuff on macOS... it would be great if it worked.

We can also do self-hosted github actions if it comes down to that.

Most of the restarts of tests on macOS and Windows though are due to 

1. Network connectivity issues
2. Docker instability

**Comment by rfay** [comment]
Oh another note: We'd love to move not just from buildkite, but also from CircleCI. In other words AMD64 Linux testing could move to github.

**Comment by dennisameling** [comment]
Okay, will spend some time this weekend to look into that. Apart from NFS I expect it to be pretty straightforward, but we'll see which roadblocks we'll run into 😅
