### ISSUE TITLE
Windows: Consider whether it's important to write/handle config.yml and docker-compose.yml in crlf native windows textfile format

### ISSUE THREAD

**Issue by rfay** [drud/ddev#261]
## What happened (or feature request):

On Windows we're creating text files in Unix format (with just LF at end of lines). Windows text files have CRLF at end of line. Lots of things handle this fine but it definitely shows that we're not windows-native and may be a problem to some developers who use editors like notepad that aren't up to the task.

Here's what our config.yml looks like in notepad:

![image](https://cloud.githubusercontent.com/assets/112444/26371403/d9be0eb0-3fb7-11e7-87c4-e223f27e7882.png)

## What you expected to happen:

Perhaps we want to write files in windows-native format, assuming that docker-compose can handle that.

## Related source links or issues:

**Comment by beeradb** [comment]
Adding to this: we also use `\n` quite often in CLI code. I assume it's probably handled OK by bash windows, but is there anywhere else that might be problematic?

**Comment by rfay** [comment]
If I'm not mistaken, \n is actually a *newline* in the local environment, at least it has been since the days of 'C', so I think this is working OK in golang as well.

**Comment by rfay** [comment]
References for work on this:
https://github.com/andybalholm/crlf
https://godoc.org/golang.org/x/text/transform
https://groups.google.com/forum/#!topic/golang-nuts/VwpNO73V1CE

**Comment by rickmanelius** [comment]
Tagging w/v1.0 because that is when we are targeting improved Windows support. See [Roadmap](https://github.com/drud/ddev/wiki/roadmap).

**Comment by rickmanelius** [comment]
Proposed next actions:
* [ ] Timeboxed audit (search) to find the number of usages of `\n` in our codebase.
* [ ] Research if there is a Go library to normalize this.

Not sure if this would be something that @nmccrory or @rfay would be more appropriate for. This also doesn't need to be queued this sprint.

**Comment by rfay** [comment]
IMO we can hibernate this until somebody cares.

**Comment by rickmanelius** [comment]
Works for me!

**Comment by rfay** [comment]
This has not blocked us at any point, nobody has ever complained. Closing for now.
