### ISSUE TITLE
Speed up, possibly pare down tests

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2619]
**Is your feature request related to a problem? Please describe.**

Tests are taking a really long time to run. Some of the test runs on Windows take more than 2 hours. However, the new arrangement of travis-ci tests, with some parallelization, finishes faster than anything else at this point.

**Describe the solution you'd like**

* Run some of the testpkg and testcmd CircleCI tests in parallel, as is done in the travisci. 
* Run the container builds and tests in parallel, instead of running them all sequentially
* Figure out how to run more relevant tests for certain PRs
* Consider a way to rerun only tests in the area of a failure; often failures are due to external dependencies, and it would be nice to just run those again.

Anyway, we spend a lot of time and effort and even money on the tests, and it would be nice for them to complete a little sooner and use less resources.

**Comment by rfay** [comment]
To reduce usage of our buildkite test runners, we can
* Create a [dynamic pipeline](https://buildkite.com/docs/pipelines/defining-steps#dynamic-pipelines) which only actually executes if golang code has changed
* Stop using so many buildkite permutations. Just do mac NFS and Windows NFS (and later we'll have WSL2)

**Comment by rfay** [comment]
I turned off all the macOS and Windows tests except one each for the full tests under NFS. We expect people to be using NFS anyway, and so we might as well focus our tests there.

**Comment by AronNovak** [comment]
@rfay Is there anything we can do in order to have green status from the CI overall? Otherwise sane PRs are red due to BuildKite. 
Should we try the dynamic pipeline route that you suggested above?

**Comment by rfay** [comment]
Mostly, the problem is not buildkite, but Docker Desktop, which is flaky in Windows and especially on macOS arm64. It's also where people do most of their work. If you have a specific problem or worry I can help with it. I look at every test situation and retest if I don't know the flaky failure intimately. On important PRs I normally get everything green before pulling. I can easily grant you retest privs on buildkite if you have a specific worry.

**Comment by rfay** [comment]
I happened to examine a Windows NFS buildkite build and there were some amazing offenders.

TestDdevXdebugEnabled takes more than 11 minutes!

--- PASS: TestGetFreePort (126.91s)
--- PASS: TestComposer (560.36s)
--- PASS: TestComposerVersion (103.60s)
--- PASS: TestExtraPackages (150.52s)
--- PASS: TestDdevStart (454.97s)
--- PASS: TestDdevStartUnmanagedSettings (471.01s)
--- PASS: TestDdevXdebugEnabled (683.87s)
--- PASS: TestDdevXhprofEnabled (248.60s)
--- PASS: TestDdevImportDB (159.11s)
--- PASS: TestDdevAllDatabases (267.51s)
--- PASS: TestDdevFullSiteSetup (137.89s)
--- PASS: TestDdevRestoreSnapshot (192.21s)
--- PASS: TestHttpsRedirection (109.17s)
--- PASS: TestWebserverType (134.79s)
--- PASS: TestMutagenSimple (1056.15s)
--- PASS: TestPortOverride (121.46s)
--- PASS: TestConfigMariaDBVersion (414.67s)
--- PASS: TestCmdMutagen (164.03s)
--- PASS: TestCmdPauseContainers (115.75s)
--- PASS: TestPoweroffOnNewVersion (116.53s)
--- PASS: TestCmdSnapshotRestore (104.56s)

**Comment by rfay** [comment]
I'm going to close this for now, as a number of things have been addressed and there's always more room for work on this. It's an ongoing priority, not an issue. But the recent improvements are good. 

* Buildkite and circleci don't waste time on docs now
* The github actions tests are more focused
