### ISSUE TITLE
Improve nginx-proxy to give a friendlier message when it can't find anything to proxy

### ISSUE THREAD

**Issue by rfay** [drud/ddev#262]
## What happened (or feature request):

nginx-proxy's job is to proxy a back-end container. However, it's just nginx, and when it can't do its job it makes an ugly complaint, 

![image](https://cloud.githubusercontent.com/assets/112444/26371667/a965633e-3fb8-11e7-9f53-bf710e5c0765.png)

## What you expected to happen:

Instead, it would be great if we gave a message "This is your friendly neighborhood nginx-proxy. I'm trying to reach the backend container named xxx on port xxx but I can't seem to get through. Please check your number and try again."

That would do two things just for us:
* Identify *which* nginx the problem was coming from, so we spend less time debugging
* Give debugging information to help resolve this, which could help enormously in supporting custom containers.

The very minimum we can do is a good error html file that identifies the proxy as the source of the message. Way better if we could add debugging info, but that might take us off into scripting hell?

## Related source links or issues:

**Comment by rickmanelius** [comment]
Considering this as useful polish. Tagging v1.0

**Comment by rfay** [comment]
This is a bit of a multilayered problem. There are two different nginx servers playing, and we'd like them both the help the user when things go wrong. For example, a user could mount bad code that would provoke any number of errors on the web container. Alternately, the actual web container could malfunction or be broken and the nginx-proxy then needs to report "real" information including a decent error message about what's going on.

Plan:
- [ ] Add 403, 404, and 40x, 50x error pages (and config) to the web container
- [ ] Add 403 handling to the proxy (This is normally a result of a missing downstream web container)
- [ ] Add 404, 502 handling to the proxy

**Comment by rfay** [comment]
This was fixed in https://github.com/drud/docker.ddev-router/issues/11 and https://github.com/drud/docker.nginx-php-fpm-local/issues/24

**Comment by rickmanelius** [comment]
BTW. Love these! My mind is already turning trying to think how we could potentially add branding. Perhaps link to our documentation.
