### ISSUE TITLE
Problem with 'ddev auth ssh -d' on Windows

### ISSUE THREAD

**Issue by amtmich** [drud/ddev#2625]
**Describe the bug**
Running command 
ddev auth ssh -d C:\Users\Michal\.ssh\ddev

No matter if I do have any keys in folder or not (folder empty) I am getting following response:
"No private keys were found in the directory."

I tried to putting there
id_rsa file
id_dsa file 

**Expected behavior**
SSH key file is loaded or more specific error is displayed (at the moment when I do have key in specified folder or I don't have anything - I am getting "No private keys were found in the directory.").

**Version and configuration information (please complete the following information):**

ddev version
DDEV-Local version      v1.15.3
commit                  v1.15.3
db                      drud/ddev-dbserver-mariadb-10.2:v1.15.1
dba                     phpmyadmin/phpmyadmin:5
ddev-ssh-agent          drud/ddev-ssh-agent:v1.15.1
docker                  19.03.13
docker type             Docker Desktop For Windows
docker-compose          1.25.0-rc4
os                      windows
router                  drud/ddev-router:v1.15.1
web                     drud/ddev-webserver:v1.15.3

**Comment by rfay** [comment]
The normal place to put ssh keys is in ~/.ssh (not C:\Users\Michal.ssh). 

I just tested on Windows in both cmd and PS and did not have this problem.

Please try putting your keys in C:\Users\Michal\.ssh (assuming that C:\Users\Michal is your home directory) and then just try `ddev auth ssh`

One possibility of course is that you don't have any private keys in the directory, so don't neglect that possibility. Where did your keys come from?

**Comment by gnuget** [comment]
Not so sure if related but updating to ddev v1.15.3  using WSL2 I got:

```
Unable to find image 'drud/ddev-ssh-agent:v1.15.1-built' locally
docker: Error response from daemon: manifest for drud/ddev-ssh-agent:v1.15.1-built not found: manifest unknown: manifest unknown.
See 'docker run --help'.
Docker command 'docker [run -it --rm --volumes-from=ddev-ssh-agent --user=1000 --mount=type=bind,src=/home/david/.ssh,dst=/home/david/.ssh drud/ddev-ssh-agent:v1.15.1-built ssh-add]' failed: exit status 125
```
I checked the docker images
```
 docker image ls | grep ssh
drud/ddev-ssh-agent               v1.15.1                         f66b0ae743eb        3 months ago        117MB
drud/ddev-ssh-agent               v1.14.0-built                   d8613dc26285        4 months ago        117MB
drud/ddev-ssh-agent               v1.14.0                         e634f7e41d0a        6 months ago        117MB
```

And it seems that it is looking for  `ddev-ssh-agent:v1.15.1-built`   and only exists `v1.15.1-built`  so I executed the comand directly using  the proper `ddev-ssh-agent`  image and I got:

```
docker run -it --rm --volumes-from=ddev-ssh-agent --user=1000 --mount=type=bind,src=/home/david/.ssh,dst=/home/david/.ssh drud/ddev-ssh-agent:v1.15.1 ssh-add
sudo: you do not exist in the passwd database
No private keys were found in the directory.
```
Which is the same error reported today by  @amtmich 

I hope this helps to find the problem, anything else that I can provide to help let me know

Thanks!

David.

**Comment by rfay** [comment]
The most likely cause of what you saw @gnuget is not having done a `ddev poweroff` at upgrade time.

But still, there are a number of improvements to the ddev-ssh-agent in about-to-be-released v1.16.0, you could try that out very easily and no risk at https://github.com/drud/ddev/releases/tag/v1.16.0-rc3

**Comment by gnuget** [comment]
Yes, you are right,  a `ddev poweroff` fixed my particular problem 😅

Thanks again! :-)

**Comment by rfay** [comment]
Every ddev upgrade deserves a `ddev poweroff` for exactly this reason, and every set of release notes asks for it. If there's a ddev-router or ddev-ssh-agent running, it's still running... and doesn't match the new executable or project. Glad it's working for you!

**Comment by amtmich** [comment]
Thank you @rfay @gnuget - after upgrading to newest ddev version my key can be found at least now, but still can not be loaded - this is what I am getting now.

`ddev auth ssh -d C:\Users\Michal\.ssh\ddev
Error loading key "/home/michal/.ssh/id_rsa": invalid format
Docker command 'docker [run -it --rm --volumes-from=ddev-ssh-agent --user=1000 --entrypoint= --mount=type=bind,src=/c/Users/Michal/.ssh/ddev,dst=/tmp/sshtmp drud/ddev-ssh-agent:v1.16.0-rc1-built bash -c cp -r /tmp/sshtmp ~/.ssh && chmod -R go-rwx ~/.ssh && cd ~/.ssh && ssh-add $(file * | awk -F: "/private key/ { print \$1 }")]' failed: exit status 1`

And this is they key which I am loading normally for other purposes and works fine. I tried with RSA and DSA formats (generated by Putty key generator).

**Comment by rfay** [comment]
The most likely problem is that your key is invalid. Putty has been pretty famous for key formats that don't match the rest of the world.

Please use git-bash and in there use `ssh-keygen`. 

You can also test your existing key in git-bash by starting an agent with `eval $(ssh-agent)` and then doing `ssh-add`. My bet is that it will say "invalid format"

**Comment by TiesAlex** [comment]
I had the same problem on DDEV 1.15.3, but a different one on 1.16:

```
cp: cannot open '/tmp/sshtmp/id_rsa' for reading: Permission denied
Docker command 'docker [run -it --rm --volumes-from=ddev-ssh-agent --user=1000 --entrypoint= --mount=type=bind,src=/c/.ssh,dst=/tmp/sshtmp drud/ddev-ssh-agent:v1.16.0-rc1-built bash -c cp -r /tmp/sshtmp ~/.ssh && chmod -R go-rwx ~/.ssh && cd ~/.ssh && ssh-add $(file * | awk -F: "/private key/ { print \$1 }")]' failed: exit status 1
```
```
$ cd /c/.ssh
$ dir
id_rsa  id_rsa.pub  known_hosts

```
Placing the Key in my Home directory resulted in the same error with, obviously, a different path.

I also tested my key with ssh-add, it told me "identity added". The key also works when i push to bitbucket

ddev version
DDEV-Local version      v1.16.0-rc3
commit                  COMMIT should be overridden
db                      drud/ddev-dbserver-mariadb-10.2:20201109_pin_mariadb
dba                     phpmyadmin:5
ddev-ssh-agent          drud/ddev-ssh-agent:v1.16.0-rc1
docker                  19.03.13
docker type             Docker Desktop For Windows
docker-compose          1.25.0-rc4
os                      windows
router                  drud/ddev-router:v1.16.0-rc1
web                     drud/ddev-webserver:20201107_writeable_composer

Any help would be greatly appreciated

**Comment by rfay** [comment]
@TiesAlex On docker desktop for Windows (Hyper-V) you will have to *share* the directory where the keys are.

**Comment by TiesAlex** [comment]
@rfay I was using Docker with WSL2. It works using Hyper-V. Do i have to use Hyper-V when working with ddev and ssh keys?

**Comment by rfay** [comment]
@TiesAlex thanks so much for working on this. It looks to me like you're doing `ddev auth ssh -d "/.ssh/"
`, which means that you have placed the keys in the *root* directory, which may not be readable at all.  I recommend placing them perhaps in someplace like C:\Users\rfay\tmp\sshtmp (if you're working on the windows side) or ~/tmp/sshtmp (if you're working in WSL2)

I know you have your docker back-end set to WSL2, but it wasn't clear if you're working with ddev on the Windows side or inside WSL2, maybe you can help me with that.

**Comment by TiesAlex** [comment]
@rfay So i launched "ddev auth ssh" from PowerShell on Windows. "ddev run ssh" works when Docker is in Hyper-V mode, but when i set it to WSL2 it no longer works. Sadly i am still very unexperienced with Docker, so i hope i am not wasting your time by asking too basic questions

**Comment by rfay** [comment]
@TiesAlex please show the exact command you issued. If you are really doing `ddev auth ssh -d "/.ssh/` (meaning that you have the keys in C:\) then please put them some place more appropriate.

**Comment by rfay** [comment]
Oh, and if you're issuing the command on PowerShell, use `ddev auth ssh -d C:\path\to\keys`

**Comment by amtmich** [comment]
> The most likely problem is that your key is invalid. Putty has been pretty famous for key formats that don't match the rest of the world.

Thank you @rfay - you were correct. Actually I can still work puttygen but what I need to do is to export my private key in order for that to work fine in linux, for the record if anyone will have sam problem:

To use it in linux you should start PuTTYgen, load the key (File->Load private key) and then export it as OpenSSH key ( Conversions->Export OpenSSH key)

**Comment by rfay** [comment]
It sounds like everybody but @TiesAlex has their problems solved in this thread. Waiting for actual command issued to solve that one.

**Comment by rfay** [comment]
No further response from @TiesAlex so closing this for now. Happy to continue the conversation here or elsewhere.
