### ISSUE TITLE
Docker Hub pull request limit reached in Travis

### ISSUE THREAD

**Issue by dennisameling** [drud/ddev#2628]
From https://travis-ci.com/github/drud/ddev/jobs/432297963:

```
failed to solve: rpc error: code = Unknown desc = failed to load cache key: failed to copy: httpReaderSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/mariadb/manifests/sha256:4377650a2acf2643490a048331d4ee785bbc3e93d6fac76f858209be833d06c3: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

We probably need to add a `docker login` command to the Travis config. Would you mind doing that @rfay, as I can't change the Travis config currently?

Thanks!

It is also possible to apply for a free OSS account, that would be perfect moving forward: https://www.docker.com/community/open-source/application

**Comment by rfay** [comment]
Maybe travis doesn't get the environment variables on forked builds? I configured it...  It's possible that it has to be configured for dennisameling/ddev? Or perhaps you have to turn off travis builds on your fork? We should see it trying to authenticate. Oh, maybe that piece didn't make it into the travis setup? It's in buildkite and circleci.

<img width="1002" alt="drud_ddev_-_Travis_CI" src="https://user-images.githubusercontent.com/112444/98673638-de403500-2314-11eb-9a6c-7db95fef820e.png">

**Comment by rfay** [comment]
It's there... https://github.com/drud/ddev/blob/af32898bd2bee5742e155793489ac7beba669cea/.travis/linux_travis_arm64_setup.sh#L9-L13

**Comment by rfay** [comment]
Apparently those environment variables aren't being seen in forked PRs

**Comment by rfay** [comment]
If I read https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions correctly, Travis provides no way to pass environment variables to a forked PR, which ends up making the whole Docker problem more severe. I hope Github actions has a way to solve this; I think I saw that they have an action specifically for this.

**Comment by rfay** [comment]
If travis-ci has docs on the docker rate limit problem they aren't listed on the docker page, https://docs.docker.com/docker-hub/download-rate-limit/#third-party-platforms

**Comment by rfay** [comment]
https://docs.travis-ci.com/user/docker/ has a mention (in the context of push), and mentions the pull rate limits at the top of the page, but doesn't really provide a way to solve it. I note that the master push I just did was fine, https://github.com/drud/ddev/runs/1379634648

<img width="438" alt="Job__97_1_-_drud_ddev_-_Travis_CI" src="https://user-images.githubusercontent.com/112444/98676741-38db9000-2319-11eb-9551-ef96502c0407.png">

But those don't show in either your or my forked builds.

But it seems to me that you and I can just configure our fork repositories with the necessary variables. I'll PM you the values after testing it myself.

**Comment by dennisameling** [comment]
Interesting. Looks like GH Actions is working on a solution where users won't be impacted by the new rate limit (only applies to cloud-hosted runners): https://github.com/actions/virtual-environments/issues/1445#issuecomment-713861495

Curious if Travis is working on a similar solution

**Comment by rfay** [comment]
I note that my PRs are being built twice, both as a PR and also as a branch push on rfay in Travis (#2629). The good news is that the rfay/ddev build gets the environment variables I configured for it. The bad news is that the PR build still doesn't.

**Comment by rfay** [comment]
Since Dockerhub pull enforcement is IP-based, the resultant problems will likely be intermittent, so it's possible we don't have to chase this right now. But anyway, I'll PM you the environment variables in gitter, and you can configure them into your dennisameling/ddev travis config. Then when it fails due to pull limit, we can at least look at the dennisameling build to see if it was OK.

**Comment by dennisameling** [comment]
Just posted in the Travis community about this: https://travis-ci.community/t/docker-hub-you-have-reached-your-pull-rate-limit/10517

**Comment by rfay** [comment]
It turns out Docker Hub has a potential exemption for open-source projects, https://www.docker.com/blog/expanded-support-for-open-source-software-projects/

I deleted the ancient private repos we had in there and applied. That would also probably solve this problem.

**Comment by rfay** [comment]
I applied to the open-source exemption, and they have accepted us into it! They had to make an exception because DDEV, a commercial entity, supports this project, but they were willing to let us in anyway. Yay for Docker!

**Comment by dennisameling** [comment]
Fantastic news! 🚀
