### ISSUE TITLE
PhpStorm with xDebug: mapping issue

### ISSUE THREAD

**Issue by StevenSymons** [drud/ddev#2643]
**Describe the bug**
My breakpoints don't fire when running xDebug with PhpStorm. The connection does work, so there's that, but I keep getting the same warning:
```
Debug session was finished without being paused
It may be caused by path mappings misconfiguration or not synchronized local and remote projects.
```

**To Reproduce**
The steps that I took are the 'official' ones from 'https://ddev.readthedocs.io/en/stable/users/step-debugging/#phpstorm'.

**Expected behavior**
I expected my breakpoints in PhpStorm to fire when going to the relevant project in my browser.

**Screenshots**
![Notification](https://user-images.githubusercontent.com/16440632/99463688-9c2b7a80-2936-11eb-947d-711665dbf74c.png)
![project-directory](https://user-images.githubusercontent.com/16440632/99463627-7d2ce880-2936-11eb-9e3e-ef35989fc6fa.png)
![Mapping](https://user-images.githubusercontent.com/16440632/99463758-c7ae6500-2936-11eb-890d-829fdfbf67e3.png)

**Version and configuration information (please complete the following information):**
- OS: Ubuntu 20.04.1 LTS (Focal Fossa)
- ddev: v1.15.3
- config.yaml contents:

```
name: vlevle
type: drupal8
docroot: web
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "8000"
router_https_port: "8443"
xdebug_enabled: true
additional_hostnames: []
additional_fqdns: []
provider: default
use_dns_when_possible: true
```

- Custom config:
I changed the port to 11011 with `xdebug.remote_port=11011` in `/.ddev/php/xdebug_remote_port.ini`

**Additional context**
I also had this problem on MacOS Mojave in the exact same way. A colleague of mine uses MacOS Catalina and also has the exact same problem.

Clearly we must be doing something wrong, because nobody else seems to have this mapping issue (not when you seemingly do it correctly anyway).

**Comment by rfay** [comment]
If you changed the port to 9001 in the php config... Did you change the port in PHPStorm? You don't mention doing that. 

Your mappings do look good, but "It may be caused by path mappings misconfiguration or not synchronized local and remote projects." should be a definite hint. 

You also don't mention having gone through the debugging steps at https://ddev.readthedocs.io/en/stable/users/step-debugging/#troubleshooting-xdebug - Could you please go through those very carefully and report the results that you have, step by step?

**Comment by rfay** [comment]
The simplest cause of the problem you're having is just to not be executing the code where your breakpoint is. Please make sure you've tried it with a breakpoint at the first line in your index.php.

**Comment by StevenSymons** [comment]
You were right, I was just executing the wrong code. I should have tested some obvious code instead of some shady code in a dark corner somewhere, hah.

Thanks for helping me!

**Comment by rfay** [comment]
Glad it's working for you!
