### ISSUE TITLE
ddev pull performance (Pantheon) regression in ddev v1.16.0

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2644]
**Describe the bug**

It takes a lot longer to do a `ddev pull -y` using Pantheon in ddev v1.16.0 than it did in v1.15.3

With a trivial Umami Drupal 8 installation on Pantheon, `time ddev pull -y` gets about 1:30 on v1.16.0, about 0:30 on v1.15.3

The terminus version isn't much different, 2.4.0 on ddev v1.15.3, terminus 2.4.1 on ddev v1.16.0

I tried downgrading terminus to 2.4.0 on ddev v1.16.0 and it didn't make it faster. (`curl -o /usr/local/bin/terminus -lL https://github.com/pantheon-systems/terminus/releases/download/2.4.0/terminus.phar`) and it didn't make any improvement.

A diff of providerPantheon.go against v1.15.3 shows essentially no changes made between the two versions. There was a minor change in the signature of dockerutil.RunSimpleContainer, but nothing else obvious. It's possible that the actual change to RunSimpleContainer is the underlying problem?

**Comment by sara-jean** [comment]
`ddev pull`, `ddev auth pantheon`, and `ddev config pantheon` are hanging and never completing for me since upgrading.

**Comment by rfay** [comment]
@sara-jean please open a separate issue with complete details. This is not the issue for you :) Make sure you show all the details, from `ddev auth pantheon` on. Thanks! And please make sure you `ddev poweroff` to start.

**Comment by rfay** [comment]
I'm going to close this as the entire thing has been reimplemented in v1.17.0, if you see trouble, please comment and I'll reopen, or we can start with a new issue. I'm betting the performance issue was a regression in terminus or something.
