### ISSUE TITLE
Shopware 6 on DDEV v1.16 node sass error when watch storefront

### ISSUE THREAD

**Issue by paravista** [drud/ddev#2645]
**When using ddev exec bin/watch-storefront.sh in the latest DDEV v1.16 in a Shopware 6 project I get the following error:**

Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (83)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.13.1
    at module.exports (/var/www/html/vendor/shopware/storefront/Resources/app/storefront/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/var/www/html/vendor/shopware/storefront/Resources/app/storefront/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.sassLoader (/var/www/html/vendor/shopware/storefront/Resources/app/storefront/node_modules/sass-loader/lib/loader.js:46:72)

This has been working in DDEV 1.15.x before. Error happens on existings projects as well as on a new blank Shopware 6 project I have set up after DDEV 1.16 update.

**To Reproduce**

1. Install Shopware 6 as in documentation (works fine, maybe the env var of APP_URL should be mentioned as well)
2. Base setup is working fine with Shopware production template 6.3
3. ddev exec bin/build-storefront.sh (which installs npm packages as well) has some error notes but finishes with a success message
4. expose ports 9998 and 9999 as mentioned in https://susi.dev/ddev-shopware-6 via .ddev/docker-compose.overrides.yaml
5. ddev exec bin/watch-storefront.sh breaks with the error mentioned above

note to step 3: 
- node-gyp rebuild > Error: not found: make
- Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.1/linux-x64-83_binding.node > Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.1/linux-x64-83_binding.node":
- Failed at the node-sass@4.13.1 postinstall script (altough in the end I have the node-sass package within my node_modules folder installed)

**Version and configuration information:**

- Host computer Windows 10
- Docker Desktop on Windows version 2.5.0.1
- Legacy WSL (NOT WSL2)
- ddev version 1.16.0
- setup with default "Shopware 6" DDEV template

**Additional context**
As a temporary solution is there a good way to downgrade from DDEV 1.16 to latest 1.15.x?
Using choco on WIN.

I assume switching to WSL2 might solve my issue.

Thanks for putting so much time into the great DDEV option!

**Comment by paravista** [comment]
OK, I think I got it sorted. It's no DDEV bug! But DDEV 1.16 comes with Node 14.x and node-sass 14.13.1, which is Shopware default is not compatible with Node 14.x. So you need to update node-sass to 14.14.1 and you are good to go.

By the way since DDEV v1.16.x my hot reload with SCSS does work very well. Had to do this directly inside the web container in v1.15. with VSCode before to get this working. But now I can again use phpStorm and everything is working fine!

Thanks a again for DDEV!

**Comment by rfay** [comment]
@paravista I didn't completely understand a couple of things.

1. Are there docs required to solve your usage of node-sass? Is this just an upgrade in your project?
2. I didn't understand SCSS hot reload issue or why PHPStorm is working better with it in v1.16

Thanks so much for using ddev, and thanks for your comments here and working through the shopware issues. I'm very much a shopware novice, so having people like you out there is absolutely critical.

**Comment by paravista** [comment]
First of all. Shopware is working with DDEV 1.16 in my environment out of the box. The node-sass issue just has any relevance as soon as you start developing a theme or a plugin as you need node for the building process.

1. As node-sass 14.13.1 is not compatible with the new Node version of DDEV 1.16 I just had 2 options, which are
A) downgrade DDEV Node version to 13.x or 
B) update the node-sass module, which is part of the standard Shopware 6 package and used for its build process. 

I went for option B although I am not sure if this is the best option as the node-sass package version definition is part of the Shopware 6 package and probably should not be modified. Maybe a note within the Quickstart Shopware 6 regarding new 1.16 node version and node-sass might be helpful (and if on it mentioning the needed APP_URL env var setting).

2. Has nothing to do with the original bug report. On DDEV 1.15.x and "nfs_mount_enabled: true", the JS watcher did not realize SASS file changes and thus not re-compile any CSS nor Updated the HTML page inside my browser during development. With VSCode you can directly open your project files inside the Composer container. Then of course changes to SASS files get realized and re-build is triggered. Think this is more a host file <-> ntfs_mount issue.

On DDEV 1.16, I have to admit I have just realized that I use the setting "nfs_mount_enabled: false" here (and this is probably the real reason), every change to the host project files (SASS and Twig) is triggering the re-build and reload as expected. For me this results in no more need of editing directly within the composer container, but just normally on my host system which I can do again now with phpStorm.

Hope this clears things up a bit. Sorry for confusion!

**Comment by rfay** [comment]
Thank you.

Yes, NFS does not support inotify notifications, which is why things like filesystem watchers can't watch over an NFS mount. This is unfortunate, but NFS predated inotify and just hasn't caught up. I don't know how you could suffer the slowness without NFS. 

I should note that @cweagans pioneered an approach to get around this which can be very pleasant, and other mutagen approaches may come along. https://github.com/cweagans/ddev-mutagen

**Comment by paravista** [comment]
Thanks a lot for the ddev-mutagen mention Randy! Will give it a try.

For SCSS adjustments I can live without NFS and will turn it on for other stuff to bring it back to speed.

By the end of the year I will switch to WSL2 anyways with probably phpStorm running inside.

**Comment by rfay** [comment]
Oh, you're on Windows? You'll absolutely love WSL2. So incredibly performant.
