### ISSUE TITLE
Can't access more than 2 ddev sites at the same time (after updating to v1.16.0, MacOS)

### ISSUE THREAD

**Issue by lecabori** [drud/ddev#2648]
**Describe the bug**
After updating to the latest version 1.16.0 on macOS I find that I can't browse to any site for any ddev project I start after the first started project.

**To Reproduce**

ddev start site1
open browser with this site: https://site1.ddev.site.  (all good)

then start new a project:
ddev start site2

browse to site2: https://site2.ddev.site. 
I get this error:

503: No ddev back-end site available.
This is the ddev-router container: There is no back-end webserver at the URL you specified. You may want to use "ddev start" to start the site.

**Expected behavior**
I expect the new site to open in the browser

**Screenshots**
![image](https://user-images.githubusercontent.com/31354117/99602402-65557300-29cf-11eb-809c-0e8a5d0836d6.png)

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: macOS Catalina 10.15.7
- Docker Desktop version: 2.5.0.1 (49550)
- ddev version information (use `ddev version`)

DDEV-Local version	v1.16.0
commit            	COMMIT should be overridden
db                	drud/ddev-dbserver-mariadb-10.2:v1.16.0
dba               	phpmyadmin:5
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.16.0
docker            	19.03.13
docker-compose    	1.27.4
os                	darwin
router            	drud/ddev-router:v1.16.0
web               	drud/ddev-webserver:v1.16.0

**Comment by rfay** [comment]
Please do the required `ddev poweroff` when upgrading ddev. This is the first thing mentioned in the [release notes for every relase](https://github.com/drud/ddev/releases/tag/v1.16.0). 

I imagine that will solve it for you.

**Comment by lecabori** [comment]
Hi, thanks for your reply. I definitely stopped all projects before the update and then did a ddev delete images after. 
I noticed that the issue is with the named urls, I can access the sites with the provided IP addresses

**Comment by rfay** [comment]
`ddev poweroff` doesn't just stop the projects, it stops the ddev-router and ddev-ssh-agent. The router is what you're having trouble with I think, and several people have reported this symptom when they didn't do a `ddev poweroff` at upgrade time. Could you please do a `ddev poweroff`? 

If that doesn't solve it, please run the script at https://gist.github.com/rfay/361c4e1df165774a5262268ef6768884 and report the results in a linked gist, thanks!

**Comment by lecabori** [comment]
Hi, 
 I have done a ddev poweroff and the issue persist. 
I also ran the provided script and it worked alright.
I have no issue with my projects working, the issue that I have is that in order to launch one project on the browser I first have to stop any other running project(s).
I can launch multiple open projects at once if instead of using the named urls I their IP address.

**Comment by lecabori** [comment]
https://gist.github.com/lecabori/c00f7c92861c66144c928917be7e2999

**Comment by lecabori** [comment]
Then after running the provided testddev script I do a ddev start on another project and then ddev launch. That results in the mentioned error

**Comment by rfay** [comment]
I'm sure we'll be able to get to the bottom of this.

I have 5 projects running right now, ddev v1.16.0, macOS, and they all work fine.

Could you please start a trivial project after the other one is running (and nothing else)

```
mkdir junk && cd junk
ddev config --project-type=php
printf "<?php\nphpinfo();\n" > index.php
ddev start
ddev launch
```

If that gets you the 503, (I imagine it will) 

* `ddev poweroff`
* What do you see then when you do `docker ps -a` ? 
* Kill off all containers you may have running with `docker rm -f $(docker ps -aq)`
* Try it again.

**Comment by rfay** [comment]
Oh, I should mention a classic problem that causes untold misery and unpredicable behavior. When people run out of the allocated disk space in Docker, totally unpredictable things happen. And this sometimes happens at upgrade time because new images get pulled. Please take a look on the resources page of Docker Desktop and see how you're doing for disk.

**Comment by lecabori** [comment]
Tried that, and yes, it failed. 
Docker Desktop seems alright:
![image](https://user-images.githubusercontent.com/31354117/99618873-38658800-29f0-11eb-91eb-fbc0763647ec.png)

the docker ps -a command showed a few containers, non related to ddev projects but  killed them all anyways. Then started one project, launched and it opened fine, then started a second one but it failed to launch with the usual error

**Comment by rfay** [comment]
The docker setup looks OK, but I've never seen anybody assign 8 cpus to Docker before. I've always just used the default 2 cpus. I'd say try to get to a more normal Docker configuration, but I doubt it has to do with what you're seeing. 

Please confirm that you did `docker rm -f $(docker ps -aq)` before your latest test, and that `docker ps -a` then showed nothing. 

Please confirm that when you're testing now it's just with the two dummy projects we've created in this issue; we're trying to rule out custom configuration.

Do you possibly have any configuration in ~/.ddev? Maybe you could show me the contents (top part, before the comments) of ~/.ddev/global_config.yaml, and please make sure there's no router-compose.*.yaml in there. (You can delete router-compose.yaml and ssh-auth-compose.yaml, they're no longer used). 

Please gist ~/.ddev/.router-compose.yaml and ~/.ddev/router-compose-full.yaml, thanks.

**Comment by lecabori** [comment]
yes, I did docker rm -f $(docker ps -aq) and then docker ps -a showed nothing after.
I only had the dummy projects when testing the above.
I don't have any custom configs in ~/.ddev:
![image](https://user-images.githubusercontent.com/31354117/99621070-ebd07b80-29f4-11eb-8e7f-5ce8a2f178fc.

I had the 2 files you mentioned (router-compose.yaml and ssh-auth-compose.yaml) and have deleted them  but that did not fix things up.

https://gist.github.com/lecabori/13eecab4980f4fb56fc503be1f69ddb7
https://gist.github.com/lecabori/e86d4428fad13e836aedd35689c9c1ba

**Comment by lecabori** [comment]
we can continue tomorrow, I am on the east coast :)

**Comment by rfay** [comment]
I can't see anything at all suspicious, thanks for all the info. 

One more thing that might be useful - Please gist the output of `docker logs ddev-router` after the failure, and please show the output of `curl -I <secondsite_URL>` (the failing one)

Do you have the ability to try this on a different computer, perhaps a coworker's computer?

I'm happy to try a zoom call to see if we can work it out as well.

**Comment by rfay** [comment]
I think I may have just experienced the problem you are having, and it looks like it was a lost message in the docker socket when the project is created, so the ddev-router doesn't know about the new project. I was able to work around it with `ddev restart`.  Does `ddev restart` fix it for you?

I'm wondering if having all those cores allocated to Docker Desktop is related here... too many things happening too fast? Could you turn your cores down to 2 and see if it affects behavior?

**Comment by rfay** [comment]
It also seems to me that when I have this problem, starting an *additional* project (in your case a 3rd project) can fix both of them. I have seven going now, which is usually too much for my setup. 

The way ddev-router works is it listens for changes on the docker socket, and recreates its (reverse-proxy) nginx configuration when it gets them. It rebuilds it from scratch. The 503-no-backend comes when it doesn't have configuration for a site.

**Comment by lecabori** [comment]
Hey Randy,
  Here are the gists for what you asked:
https://gist.github.com/lecabori/3d3af5d0384f427f761a0fe3e34b64dc
https://gist.github.com/lecabori/6a5c54a235c77d923e28a4a5c085fa76

I tried on my PC and it worked fine, I could start and launch 2 projects.
Sounds good to have a Zoom meeting.

I tried ddev restart but that did not worked out. But interestingly, earlier I started and launched 2 projects from the same iTerm2 tab (I usually do this on separate tabs) and I could launch them both. For a third one it didn't work nicely, I had to keep restarting it a few times both on a different tab and on the same time as the others, eventually somehow magically it launched...
I also had reduced the number of cores available to Docker

**Comment by rfay** [comment]
I think it's just inconsistent behavior. I have to work on some things this morning, but am hoping to be able to spend some focused debugging time later since I seem to be able to demonstrate this right now.

It would help me to see if you have the same problem if you could get the nginx config with `docker cp ddev-router:/etc/nginx/conf.d/default.conf /tmp` and then gist /tmp/default.conf for me. I'll need to know which site(s) are broken at the time you copy that, so maybe a `ddev list` and tell me which ones work.

**Comment by lecabori** [comment]
sounds good, thanks for all your help.

ddev list:

![image](https://user-images.githubusercontent.com/31354117/99685848-05071580-2a51-11eb-8227-9699062aa267.png)

these 2 work:
pirsa.ddev.site
scitalks.ddev.site.   (scitalks, with an "s" at the end, the one w/o the "s", scitalk is not launching)

the default.conf:
https://gist.github.com/lecabori/dc217028dbe71c122cf0219fbc81b45c

**Comment by rfay** [comment]
Unfortunately, it looks like maybe you don't have the problem I'm seeing, as the scitalks backend is there

```
    # scitalks.ddev.site
    upstream scitalks.ddev.site-80 {
    keepalive 100;
                        # ddev-scitalks-web
                        server 172.18.0.11:80;
    }
```

Could you `docker exec -it ddev-router nginx -s reload` and see if it has any effect?

**Comment by lecabori** [comment]
just to double check:
 scitalks.ddev.site works
the one that doesn't work is: 
  scitalk.ddev.site
(no "s" at the end of scitalk)

**Comment by lecabori** [comment]
and no, the reload command above doesn't fix the problem for the project that is not launching

**Comment by rfay** [comment]
Oh, good. You do have the same problem I have right now. Hopefully we'll be able to chase it down. Sorry, I misread your comment. 

your default.conf shows that only phpMyAdmin is set up for scitalk.ddev.site. I imagine that https://scitalk.ddev.site:8037 works and http://scitalk.ddev.site:8036 both work.

**Comment by lecabori** [comment]
that's correct, both phpMyAdmin work

**Comment by rfay** [comment]
I wrote this script ([gist](https://gist.github.com/rfay/378a377aa4f695799ee2b36e2847c2e6)) to try to recreate this. Versions of it ran over and over again successfully. 

However, once it started failing, I got exactly the failure mode that you have described. I ran it several times, it failed on the 2nd or 3rd site created. The nginx default.conf was essentially the same as the one you had when the problem happened. 

Logs at https://www.dropbox.com/s/egn5xece2o3dy59/testfailurelogs.20201119213704.tgz?dl=0

The kicker is... I just restarted docker and immediately it started working every single time. I'm sure that eventually I can get it to fail. 

I'd love to know if your experience is the same. It's looking like this is an obscure docker bug where the exposed ports aren't always coming through.

**Comment by lecabori** [comment]
Yes I am! I ran the script and it failed on the 2d every time I tried it. Then restarted Docker and voila! I ran it 3 times after that and it worked each of them

**Comment by rfay** [comment]
I think it will come back. It's either random or triggered by something we do. I've experimented with commenting out the `ddev poweroff`; that doesn't seem to change anything. 

It looks to me like perhaps the docker api doesn't return all the exposed ports on the failure case (so they don't get set up properly in ddev-router). So I added a query to the docker API to see what it's saying and capture that info.

**Comment by rfay** [comment]
When you next run the script, please get the updated version at https://gist.github.com/rfay/378a377aa4f695799ee2b36e2847c2e6 which has the docker api curl result. One of the two of us has to hit it again before long!

(The current one there has `ddev poweroff` commented out, but I don't think that matters.)

**Comment by rfay** [comment]
It also may matter whether you do the cleanup one-liner it gives you at the end, but I haven't been able to get any consistent results with anything I've done.

**Comment by rfay** [comment]
@lecabori should we write this off to docker misbehavior? Have you had it again?

**Comment by dr-bock** [comment]
Just wanted to confirm that I have the same problem since ddev 16.0 or the last docker update.

An early solution apart from the script here would be great. :)

**Comment by rfay** [comment]
@dr-bock most people who reported this had forgotten to do the required `ddev poweroff`, so please do that.

The script was not a way to fix the problem, it was a way to *demonstrate* the problem.

The only fix I know is to restart docker. So please:

1. `ddev poweroff`
2. Restart docker

**Comment by lecabori** [comment]
Yes, I still have the issue.
And doing the ddev poweroff and docker restart is how I get around it.

**Comment by rfay** [comment]
OK @lecabori , the path forward is to provide the tarball that the script creates please. I do recommend doing a docker factory reset to see if it changes anything. You'll lose all databases, so doing a snapshot or export-db ahead of time will be safer. `ddev snapshot --all` does a snapshot for all registered projects (the ones that show up in `ddev list`)

**Comment by rfay** [comment]
In addition to capturing the tarball, it may be worth trying the current Docker edge version, see https://docs.docker.com/docker-for-mac/edge-release-notes/

**Comment by lecabori** [comment]
do you want the tarball in a gist link ?

**Comment by rfay** [comment]
Yes, please provide the output of the script (as a gist) and also a link to the tarball. You'll have to put the tarball someplace like Dropbox, or figure out any other way you want to make it available.

**Comment by lecabori** [comment]
as soon as I am done with a series of meeting I will do this, probably after lunch. Sorry

**Comment by lecabori** [comment]
sorry for the delay, let me know if this is fine.
https://www.dropbox.com/sh/wekldwzyr8s103r/AABwFJ1576LkUWt4lFkgujo0a?dl=0
this was created earlier today running the script that you provided earlier. It failed on the second attempt I think.
I was trying to run the script again after one of my projects failed but it never failed even though mine had.

**Comment by rfay** [comment]
Thanks so much. I won't get to look at it immediately. Would love to hear if installing the latest docker edge relieves this for you. (It's not always true with edge, but currently you don't lose all images and volumes when you switch).

**Comment by rfay** [comment]
Thanks for the tarball! 

I examined testfailurelogs.20201124093800.tgz and find exactly what we thought we were finding before... Although the dockerapi containers listing shows all 3 ports (https://gist.github.com/rfay/9298e42de26319fd9d1e455a1c546517#file-docker_api_containers-json-L11-L27) 

It happens that tonight I'm able to break my own system (running Docker Edge) so am in a happy situation where I can study it at will. Unfortunately, I can't stay up all night and might not be able to leave it broken. But it's mighty nice to just be able to go look at it. This may be an intermittent Docker bug (triggered by some site any of us are using? some different config?) or it may be a bug in docker-gen, or it may be a bug in the nginx.tmpl that generates the nginx config. Most likely is the latter, since it seems to have changed in v1.16.0.

**Comment by rfay** [comment]
The good news is I'm getting better debugging/recreation techniques for this, using docker-gen right on the host, which reads what should be the same docker socket. But tomorrow is another day :)

**Comment by rfay** [comment]
I think I figured out what was going on, see #2648 - if you would please test it by following the instructions in "Manual testing" there, it would be ever-so-much appreciated,  @lecabori and @dr-bock  - Thanks so much for your help in reporting and debugging this issue.

**Comment by lecabori** [comment]
Hi, I added the file 
~/.ddev/router-compose.nginx.yaml 
then ddev poweroff
then ran the script but got the following error on the scree:

https://gist.github.com/lecabori/54ee5b3ae3bcb0c7a86c1248cf15d574

**Comment by rfay** [comment]
Thanks for testing!

Yes, you either have something using port 33277 or Docker messed up assigning it, but it doesn't have anything to do with what we're working on. So please try again. 

I have seen this before btw when launching lots of sites. Since we aren't asking ddev to manage any ports, I don't think it's relevant to what we're working on here.

**Comment by lecabori** [comment]
yes, a second run is worked.
I shall test more with my own projects

**Comment by lecabori** [comment]
I received the same error on starting one of my projects
(Cannot start service dba: driver failed programming external connectivity on endpoint)
The site was up after but not phpMyAdmin

**Comment by rfay** [comment]
It looks like you have something already listening on 33308 and 33318. Please debug what's listening there using the techniques in https://ddev.readthedocs.io/en/stable/users/troubleshooting/#webserver-ports-are-already-occupied-by-another-webserver

`sudo lsof -i :33308 -sTCP:LISTEN`
`sudo lsof -i :33318 -sTCP:LISTEN`

It won't surprise me if it's docker trying to listen; docker restart is the best way around this. You can also `docker ps -a` to discover what might be listening.

**Comment by lecabori** [comment]
I stopped it and the started it again and no errors were issued. Also started other 3 projects and it seems OK
running the above commands to see what's listening on those ports returned nothing.

**Comment by rfay** [comment]
If you're able to recreate the situation, try to note what order you were doing what in. I think a simple `ddev start` or perhaps a `ddev restart` will resolve port conflicts of this type (ephemeral ports) in any case, but couldn't swear to it.

**Comment by rfay** [comment]
@dr-bock I sure hope you'll be able to test this as well. It was such a tricky and apparently time-dependent issue that it's important that people who have hit it test it for a while. I'd like to get a point release out next week though.

**Comment by lecabori** [comment]
thank you!, I haven't had any more issues.

**Comment by rfay** [comment]
Thanks so much for all your help on this @lecabori - I hope this does the trick. I'll try to get an edge release out with this soon, and you can test with that, and hopefully we can do a point release shortly after that.

**Comment by rfay** [comment]
@lecabori @dr-bock I've released an edge release that you can test to see if things are really fixed. 

Please upgrade to https://github.com/drud/ddev/releases/tag/v1.16.2-alpha2

And don't forget to remove the workaround file (~/.ddev/router-compose.nginx.yaml)

**Comment by lecabori** [comment]
it seems good so far, I have successfully launched 2 projects
