### ISSUE TITLE
solr backend not reachable with ddev v1.16.0

### ISSUE THREAD

**Issue by iwm-donath** [drud/ddev#2649]
**Describe the bug**
After starting ddev, trying to reach the solr backend provided by ddev describe results in a connection refused error message. It works fine with ddev 1.15.3.

**To Reproduce**

1. ddev start
2. ddev describe
3. Click on solr url provided by ddev describe

**Expected behavior**
Get the solr backend.

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: tested on Windows 10 and macOS Catalina
- Docker Desktop version if on macOS or Windows (from "About Docker Desktop"): 2.3.0.5 (Windows 10), 2.5.0.1 (macOS)

- ddev version information (use `ddev version`): 1.16.0
- config.yaml contents for the misbehaving project: [ddev-yaml-solr.zip](https://github.com/drud/ddev/files/5567393/ddev-yaml-solr.zip)

**Comment by rfay** [comment]
This is https://github.com/drud/ddev/issues/2639 - and there's a workaround for you there. 

It the fix has already committed and will be released in v1.16.1

Thanks for reporting!
