### ISSUE TITLE
Determine how to handle additional service compose files

### ISSUE THREAD

**Issue by tannerjfco** [drud/ddev#265]
## What happened (or feature request):
The results of #121 introduced the ability for ddev to handle multiple docker compose files in the .ddev directory of a site. This allows users to define additional services in compose files formatted as `docker-compose.<service>.yml`. While the abilities are in place with the v0.5 release and documented, we still have some considerations open for how we would handle an ecosystem of these additional service files.

## What you expected to happen:

We should make decisions on the following items:

- Where should service files developed by DRUD be stored? In the ddev repo? In a separate library/collection repo?
- Where should contributed service files be stored? Should this differ from or match files developed by DRUD?
- What testing should we have for service files developed by DRUD? How do we want to handle testing these extra configurations overall?
- What testing, if any, should we have for contributed service files?
- How should documentation requirements for services be handled? inline docs on the service file? accompanying README, etc?

## Related source links or issues:

**Comment by tannerjfco** [comment]
Some thoughts on these:

> Where should service files developed by DRUD be stored? In the ddev repo? In a separate library/collection repo?
I could see some good reasons for using a separate repo for this. It could be more approachable to people looking to contribute. It could provide more visibility to what additional services are available for ddev. It could make testing various configurations more approachable/manageable, as we could have tests for them separate from the main ddev tests.

> Where should contributed service files be stored? Should this differ from or match files developed by DRUD?
We may want to distinguish "official" and "community" configs, so that we're not committed to maintaining every possible configuration that gets shared. Possibly create a path for configs to mature into "official" from "community". Maybe this is all thinking too far ahead, trying to consider having many configs from many places.

> What testing should we have for service files developed by DRUD? How do we want to handle testing these extra configurations overall?
This is an area where I think it makes sense to provide a separate repo for configs, as we could provide a separate test strategy for configs without impacting the main ddev tests.

> How should documentation requirements for services be handled? inline docs on the service file? accompanying README, etc?
Inline comments on the service file would be the easiest, but I'm not sure how we ensure people know to look there and follow along. A separate README might be more noticeable, perhaps each service gets its own folder to contain its own config and readme.

**Comment by rickmanelius** [comment]
Quick responses:

1. A repo of service files seems logical. Kindof like how Chef used to have a repository of additional recipes. Counterpoint: we would run into issues of potentially having multiple PRs if an issue needs to update ddev and the service file at the same time. 
2. Not opposed to tagging official versus community. Official definitely needs tests. Community... I wouldn't want all of our builds to come up failing. Maybe two repos? Or more crazy... a repo per service? Spitballing here, so if such a suggestion is inappropriate, I get it.
3. Agreed that we don't necessarily want to do full testing runs against all services on the main repo.
4. What if we had one global README front and center where the service files are stored and then use that as a pointer to a "services" section in our read the docs? I think that is going to be easier and it provides a consistent place for people to look (particularly those evaluating services).

**Comment by tannerjfco** [comment]
> A repo of service files seems logical. Kindof like how Chef used to have a repository of additional recipes. Counterpoint: we would run into issues of potentially having multiple PRs if an issue needs to update ddev and the service file at the same time.

I'm not certain there's a scenario where ddev and a service file should need to be updated at once. The one I can see is if the compose format changed dramatically, at which point we would have to update many service files.

> Agreed that we don't necessarily want to do full testing runs against all services on the main repo.

The new CircleCI workflows might provide a path to us running separate tests but in the same repo. Not sure if that's helpful or not for this, but wanted to note we may not require a separate repo to achieve separate tests.

> What if we had one global README front and center where the service files are stored and then use that as a pointer to a "services" section in our read the docs? I think that is going to be easier and it provides a consistent place for people to look (particularly those evaluating services).

Just to clarify what I mean here, I'm talking about instructions the user may need to follow to succeed in adding a specific service. For example, our solr configuration has instructions at the top to copy the solr conf from search api solr module: https://ddev.readthedocs.io/en/latest/users/customization-extendibility/#defining-an-additional-service-apache-solr-example

This does raise another consideration re: separate repo or not, in that if we want to provide service-specific docs in our doc site, we might want them in the main repo, though I'm not sure this is a requirement. We would need to evaluate what we can do with readthedocs.

**Comment by rickmanelius** [comment]
It sounds like a/the critical factor is whether or not we can include the service files in the main repo without having to run the full CircleCI set of tests across all of the services with each commit. In terms of docs, it would seem to me that keeping one set of documentation would be ideal instead of sending the user to either another read the docs site just for additional services OR having a separate readme per repo per service. And in that scenario, if we updated our interface for additional services, we'd have to hunt down each change in each repo...

I'm biased towards (while we start small) simply keep it in the main repo (if we can split the circleCI tests) and including this in our main docs until we reach a point where splitting them out makes sense. If you agree with that approach (or at least don't have major objections), I say we start down that path and re-evaluate when we're up to 4-5 services.

**Comment by tannerjfco** [comment]
Following that, summarized approach would be:

- Create a "services" directory in the ddev repo to house optional docker-compose service files. 
- Provide a listing of services in the docs, providing any relevant docs for the service.
- Implement a new test strategy alongside the existing main ddev tests, to allow for testing custom service configuration files. We will need to determine what exactly we are testing, and how often they should be tested. My opinion is that testing ability to start/run/remove a site w/ the configuration in place is reasonable to test, and that we could probably run these on a nightly basis. I don't think these tests would need to run w/ every PR opened.

**Comment by rickmanelius** [comment]
Your last summary works for me. Let's start there and if we need to evolve it, we can go from there.

While the issue summary needs to be updated to reflect, this is actionable.

**Comment by rickmanelius** [comment]
Pull request merged. Thanks!
