### ISSUE TITLE
Select node/npm version in config.yaml

### ISSUE THREAD

**Issue by agviu** [drud/ddev#2651]
**Is your feature request related to a problem? Please describe.**
Quite often the scripts that we need to compile need an specific version of node, not being compatible with modern versions of node.js In order to continue compiling these assets inside the web container, it would be ideal to have the possibility to choose which version of node.js to have installed in the container, in a simple way as we can do to choose PHP or composer version.

**Describe the solution you'd like**
To have a new option in config.yaml where to specify the major version of node installed in the container.

**Describe alternatives you've considered**
I am currently using the n command as an alternative, as it allows to install a different version of node. However a more global solution would be more elegant.

**Additional context**
It's common to have npm dependencies in modern projects, and some of them are not compatible with newer versions of node.js In order to being able of maintain old sites using modern versions of ddev, this feature is really needed.

**Comment by rfay** [comment]
The winning proposition so far is to add nvm. The problem is that nvm is a shell wrapper, so might not work for everybody; it's a bit complicated to get right. Ongoing discussion in https://github.com/drud/ddev/issues/2380 but this is a reasonable feature request to spin off.

Note that you can easily add a .ddev/web-build/Dockerfile that will install the version of node/npm that you want.

**Comment by rfay** [comment]
Just so everybody knows, there's already a way to set up a specific node version using the project's .ddev/web-build/Dockerfile. Create a .ddev/web-build/Dockerfile like this:

```Dockerfile
ARG BASE_IMAGE
FROM $BASE_IMAGE
# Install whatever nodejs version you want
ENV NODE_VERSION=12
RUN sudo apt-get remove -y nodejs
RUN curl -sSL --fail https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash -
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests nodejs
```

**Comment by bwml** [comment]
I couldn't get the above solution to work, but this NVM procedure is working (at the moment).
Looking forward to when this support is better integrated or a more refined approach.

Key points:
* NVM install
* Yarn key update
* Added global packages
* Restored/reinstalled npm
* Restored node symlink so the container references the correct version from host side.
`
ARG BASE_IMAGE
FROM $BASE_IMAGE

ENV NVM_DIR=/usr/local/nvm
ENV NODE_DEFAULT_VERSION=v8.17.0
ENV NODE_GLOBAL_PACKAGES="grunt-cli bower"

RUN sudo apt-get remove -y nodejs
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
RUN curl -sL https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh -o install_nvm.sh && \
    mkdir -p $NVM_DIR && bash install_nvm.sh && \
    echo "source $NVM_DIR/nvm.sh" >> /etc/profile && \
    bash -ic "nvm install $NODE_DEFAULT_VERSION && nvm use $NODE_DEFAULT_VERSION && nvm install-latest-npm && npm install --global $NODE_GLOBAL_PACKAGES && ln -s \"/usr/local/nvm/versions/node/$NODE_DEFAULT_VERSION/bin/node\" /usr/bin/node" && \
    chmod -R ugo+w $NVM_DIR
`
Hope this helps someone.

**Comment by rfay** [comment]
@bwml note that ddev in current versions is using the [recommended yarn install via npm](https://classic.yarnpkg.com/en/docs/install/#mac-stable) instead of using the apt package. The apt package is poorly maintained, and the key was expiring every single year.

**Comment by andrewbelcher** [comment]
You can also install nvm using npm, as per https://stackoverflow.com/a/23569481

So you'd do something along the lines of

```
RUN npm install -g n && n NODE_VERSION
```

**Comment by codemonkey1988** [comment]
Just read your Tweet @rfay  for version 1.19 suggests and want to wish for exact that feature. For our needs, selecting a major version world be fine. In our case, versions starting from node 12 would be great.

**Comment by dahaupt** [comment]
It would be great to have the latest LTS version of Node.js (v16) becoming the default from v1.19 onwards.

**Comment by rfay** [comment]
Thanks @dahaupt - I thought I checked just recently and 14 was still LTS version... But we'll get 16 in there as default for sure.

**Comment by rfay** [comment]
https://github.com/drud/ddev/issues/3375

**Comment by rfay** [comment]
#3612 allows changing nodejs version to 12, 14, 16, 17, still defaults to 16. Is that going to be adequate? Would love some testing on this, although I think if you're happy with that selection it's probably good enough.

**Comment by agviu** [comment]
What about legacy versions of nodejs like 10 or even 8 ?

**Comment by rfay** [comment]
It looks to me like nvm would work. nvm is sometimes awkward because it's defined at user level, and requires additions to profile, etc. But if people usually use nvm it might be OK.

**Comment by jonaseberle** [comment]
`nvm` would be amazing of course due to a commitable [`.nvmrc`](https://github.com/nvm-sh/nvm#nvmrc).
But a `.ddev/config.yaml` solution would be just as good IMHO.

**Comment by rfay** [comment]
The .nvmrc would be inside the container though... Interested in how that would work out.

**Comment by jonaseberle** [comment]
In `$HOME`? It's ok. It's just the default. We'll be able to override it on the project level. We would do `nvm use` somewhere in the project to use the `.nvmrc`.

That said - it is just as easy for us users to change a `.ddev/config.yaml` value and restart the container. I'd say go for what is easier to implement. At least we are not keen for anything below v14. v12 is EOL in April and having the supported ones is a big help already.

**Comment by HeikkiYlipaavalniemi** [comment]
How are the available nodejs versions configured in this setup if we would be using for example `.nvmrc`? Is it possible to add additional versions to the list? At least in our daily workflows with nvm it's an usual step that you need to also install the required nodejs version before its available for nvm if its a new project with a different original node version requirement..

For example trying to install nodejs version 16 before its been installed with nvm with `nvm install` leads to the following error:
`N/A: version "16 -> N/A" is not yet installed.`

**Comment by rfay** [comment]
With the current PR
* https://github.com/drud/ddev/issues/2651

both system nodejs and nvm are supported. So if you configure `node_version: 16` that becomes the system node. If you have `v14` in your .nvmrc, you'll need to do a `ddev nvm install` or do it another way. It persists though, so it's a one-time action. Any version supported by nvm can be used.

I would love to have you test the current PR. You can test it on gitpod with https://gitpod.io/#https://github.com/drud/ddev/pull/3612 or download the artifacts from https://github.com/drud/ddev/actions/runs/1879141287

**Comment by DanielRuf** [comment]
How do select a different npm version than the one which comes bundled with node?

In our setup we probably need npm 6 but Nodejs 14 and newer seem to come with npm 8.
Unfortunately setting only the Nodejs version does not help much.

**Comment by DanielRuf** [comment]
How do we select a different npm version than the one which comes bundled with node?

In our setup we probably need npm 6 but Nodejs 14 and newer seem to come with npm 8.
Unfortunately setting only the Nodejs version does not help much.

**Comment by rfay** [comment]
It's unusual to have npm version that's not the one that comes with node, but looks here like it's easy: https://feargalwalsh.medium.com/managing-multiple-npm-versions-locally-with-ease-ad2f7757bc1c

Use `ddev nvm` to use the node version you want, then install the npm version you want.

**Comment by DanielRuf** [comment]
@rfay thanks, but nvm was not what I've meant (we don't want to switch the node version). And yes, it is quite common to have a specific version or version range set in `engines` for `npm` (same applies to yarn v1 classic and yarn v2+ berry, they have different logic and lockfiles). Lockfiles for different npm versions are quite different (see `"lockfileVersion": ...` in `package-lock.json`.

https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion

> lockfileVersion
> 
> An integer version, starting at 1 with the version number of this document whose semantics were used when generating this package-lock.json.
> 
> Note that the file format changed significantly in npm v7 to track information that would have otherwise required looking in node_modules or the npm registry. Lockfiles generated by npm v7 will contain lockfileVersion: 2.
> 
>     No version provided: an "ancient" shrinkwrap file from a version of npm prior to npm v5.
>     1: The lockfile version used by npm v5 and v6.
>     2: The lockfile version used by npm v7, which is backwards compatible to v1 lockfiles.
>     3: The lockfile version used by npm v7, without backwards compatibility affordances. This is used for the hidden lockfile at > node_modules/.package-lock.json, and will likely be used in a future version of npm, once support for npm v6 is no longer relevant.
> 
> npm will always attempt to get whatever data it can out of a lockfile, even if it is not a version that it was designed to support.

Trying to use the wrong npm version with the wrong lockfile version often leads to crashes / errors.

In our case we use a hook, that works as expected, no extra commands needed:

```yaml
hooks:
  post-start:
    - exec: "npm i -g npm@6"
```

Would have been useful as `npm_version` setting, comparable to `nodejs_version` - because the title of the PR also suggests that we can freely set the npm version, but it is only about the Nodejs version.

**Comment by rfay** [comment]
It sounds like you already know how to do what needs to be done; if you have a feature request, you would do it in a new issue, but it might be better to figure out how to make your codebase more resilient and less dependent on specific npm versions.

**Comment by DanielRuf** [comment]
@rfay the tip with the hook came from @shochdoerfer in an internal ticket.

We have no direct control over the package.json file of the relevant part, because it is an admin backend of a CMS that ships with this version requirement. I will open a feature request regarding the missing `npm_version` setting.
