### ISSUE TITLE
Travis-ci build limits, get subscription

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2654]
Travis-CI's build limits are obviously going to be an issue for us, since we use them now for ARM64 builds.

I contacted them about open-source credits, they said:

Thanks for contacting Travis-CI Support! I’d love to help! We offer an Open Source/Educational Subscription for free to non-commercial Open Source projects. To qualify for an OSS subscription, the project must meet the following requirements:
* You are a project lead or regular committer (latest commit in the last month)
* Project must be at least 3 months old and is in active development (with regular commits and activity)
* Project meets the OSD specification
* Project must not be sponsored by a commercial company or organization (monetary or with employees paid to work on the project)
* Project can not provide commercial services or distribute paid versions of the software
Sounds like you and your project? We’d be very happy to support you. If your project does not match these requirements or you have questions, feel free to ask!

Unfortunately "Must not be sponsored by a commercial company" cuts us out.

I think we'll probably have to subscribe, which isn't that big a problem I don't think.

/cc @dennisameling

**Comment by dennisameling** [comment]
😞 that's a shame! Let me know if I need to exclude Travis temporarily from https://github.com/drud/ddev/pull/2615, it's really not necessary to run it over there until we have GH Actions up and running correctly

**Comment by rfay** [comment]
We haven't had any trouble so far, and I don't think it's going to be a problem to pay for their lower-end subscriptions. I just hope that includes pull requests. I love how fast the tests get done!

**Comment by rfay** [comment]
I unchecked the "use for OSS credits" checkbox, not sure what that does for us or against us.

<img width="910" alt="DDEV_-_Profile_-_Travis_CI" src="https://user-images.githubusercontent.com/112444/99860971-f05e7680-2b51-11eb-8d89-3209661a6af9.png">

**Comment by rfay** [comment]
[DDEV](https://ddev.com) is very generous in supporting this project. We now have the "1 concurrent build" subscription in Travis-CI

Thanks @cyberswat 

<img width="498" alt="DDEV_-_Profile_-_Travis_CI" src="https://user-images.githubusercontent.com/112444/99862143-e5a5e080-2b55-11eb-8cab-06c664e5208c.png">

**Comment by dennisameling** [comment]
That's fantastic! Thanks!!

**Comment by rfay** [comment]
Our "1 Concurrent Plan" means that only one job runs at a time. It seems to take about 3 times as long as before, which is probably OK right now. We're getting test coverage. It's great. The increased plans cost about what you'd expect. The disappointing thing is that the refactored parallel tests finished SO fast. I was always so happy to get the email. Oh well 👍 

<img width="712" alt="DDEV_-_Profile_-_Travis_CI" src="https://user-images.githubusercontent.com/112444/99890908-52d27800-2c21-11eb-9892-00420df520da.png">
