### ISSUE TITLE
Projects show up as 'Paused' after Docker restart or system reboot

### ISSUE THREAD

**Issue by begrafx** [drud/ddev#2658]
**Describe the bug**

This has happened a handful of times; it is by no means a "consistent" issue, nor at all reproducible. I'm not sure if it is a DDEV issue or a Docker issue. But on several occasions, I will be working along, and all of a sudden I start getting errors. It may be a 504 Gateway error as I try to `ddev launch`, or it may be a mass of red error message following a DDEV command; the common factor seems to be, I will do a `ddev list`, and it shows on the project in question, in yellow letters, `paused` and `db: running` 
Again, I'm not sure if this is DDEV or Docker, I'm not sure what causes it. Sometimes I can simply `ddev start` the project again, and all is well. Sometimes I have to `ddev poweroff` and then `ddev start`.

**Comment by rfay** [comment]
Usually "paused" means that the host computer has been rebooted, or docker has been restarted. You can also explicitly do `ddev pause`.

Essentially, ddev's docker containers don't automatically restart, although you *can* tell them to restart with the experimental (v1.16+) `ddev config global --auto-restart-containers` but your mileage may vary with that. It's not the default for a reason.

**Comment by begrafx** [comment]
Yeah, these are things I'd thought of, but none apply. Hasn't rebooted, docker hasn't (that I'm aware) restarted, I haven't paused anything. This usually shows up as I'm working along, all is going well, and then I'll give a DDEV command and get a screen full of red. I do a DDEV LIST and see it is paused. From what you're saying, I'm guessing this is a docker issue.

**Comment by rfay** [comment]
It could be that a container has died. If it's one specific container that is making it do this, you can examine that container. 

When you get an error of some kind, stop and do a `ddev list`. Figure out which project it is. Then look at the containers, `docker ps -a | grep <project>` You'll find one or more of those stopped. You can `docker logs <containername>` to get some insight into why it might have stopped. It could be an error.

As with all situations of this type, please check your docker file space (if on macOS or Windows Hyper-V backend) and check your memory allocated to docker.

**Comment by begrafx** [comment]
No, that's the thing, it isn't one container over and over, it may be this one this time, and then that one another time, and then this one over here a different time. Like I say, nothing reproducible about it.

**Comment by begrafx** [comment]
I'll do a `ddev logs -s <service>` next time it happens, and share the outcome with you.

**Comment by rfay** [comment]
Thanks - Please share as a gist (gist.github.com), rather than pasting directly here.  You should also do a `docker ps -a`

**Comment by begrafx** [comment]
Will do. Thank you.

**Comment by rfay** [comment]
Closing this for now. Looking forward to figuring out what is happening in your specific case. Feel free to follow up here or anywhere else.
