### ISSUE TITLE
Switch ddev version via brew

### ISSUE THREAD

**Issue by vcaraseni** [drud/ddev#2668]
I am trying to install specific 1.15.3 version of ddev via brew. Can someone pls help me - is it possible?! 
Thanks

**Comment by rfay** [comment]
They make it pretty hard these days. What I do is `export HOMEBREW_NO_INSTALL_CLEANUP=true` in my .profile, and then homebrew isn't always deleting the old ones. But you needed to do that in advance probably, although you can **try* `brew switch ddev 1.15.3`

However, the [install_ddev.sh](https://github.com/drud/ddev/blob/master/scripts/install_ddev.sh) script does fine with this, 

```
ddev poweroff
brew unlink ddev
install_ddev.sh v1.15.3
```

Now do whatever you need to do, then when you want brew-based ddev again
```
ddev poweroff
sudo rm /usr/local/bin/ddev
brew link ddev
```

**Comment by vcaraseni** [comment]
How i did it: 
I already tried to do `brew switch ddev 1.15.3` - but it didn't worked for me;
But as you wrote for [install_ddev.sh](https://github.com/drud/ddev/blob/master/scripts/install_ddev.sh) - i downloaded [1.15.3](https://github.com/drud/ddev/releases/tag/v1.15.3) release and changed it a bit: in install_ddev.sh file i hardcoded **LATEST_RELEASE** param to 1.15.3 because without it - it downloads the latest version anyway i.e. 1.16.2 in my case. 
So ran the install_ddev.sh and all worked fine to me. 

Thank you so much **rfay**.

**Comment by rfay** [comment]
@vcaraseni Could you say why you needed to downgrade to v1.15.3? We always want to hear!
