### ISSUE TITLE
curl call between two ddev servers always routes to the server making the call

### ISSUE THREAD

**Issue by dmgig** [drud/ddev#2677]
If I am running two ddev sites on the same host machine (say, `site1.ddev.site` and `site2.ddev.site`) then making a curl request from inside the `site1` container to the url of `site2` - this always shows the content from `site1` (and vice versa).

**To Reproduce**

Spin up two plain php ddev instances (say, `site1.ddev.site` and `site2.ddev.site`), add an `index.html` file to both indicating their name (`site1` or `site2`). 

`ddev ssh` into `site2` and execute `curl site1.ddev.site`. This will return `site2` (should return `site1`, right?). The reverse is true if running from `site1`.

Example: 

```
dmgig@site1-web:/var/www/html$ curl -i site2.ddev.site
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 02 Dec 2020 17:38:18 GMT
Content-Type: text/html
Content-Length: 6
Last-Modified: Wed, 02 Dec 2020 17:24:09 GMT
Connection: keep-alive
ETag: "5fc7cdb9-6"
Accept-Ranges: bytes

site1
```

Note: There's no problem connecting to other sites while inside the ddev containers. Nor are there any problems connecting to either site from the host machine.

**Expected behavior**

When making a curl request from one ddev site to another from another ddev server, the connection should work and not point to the server making the request.

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: macOS Catalina
- Docker Desktop version 2.5.0.1
- ddev version v1.16.0
- config.yaml contents - default
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? No

**Comment by rfay** [comment]
Remember that *.ddev.site is a DNS wildcard that resolves to 127.0.0.1 (the same web container). So you won't be able to do what you're talking about without some modifications. Please see the [FAQ](https://ddev.readthedocs.io/en/stable/users/faq/) on "How can two projects communicate with each other"

If you want to do exactly what you're now doing, you can create a `docker-compose.othersite.yaml with
```
version: '3.6'
services:
  web:
      external_links:
        - "ddev-router:secondsite.ddev.site"

**Comment by dmgig** [comment]
Ah, okay -  thank you for your help.

**Comment by felmab** [comment]
> If you want to do exactly what you're now doing, you can create a `docker-compose.othersite.yaml with
> 
> ```
> version: '3.6'
> services:
>   web:
>       external_links:
>         - "ddev-router:secondsite.ddev.site"
> ```

Terrific, thanks. I believe this would be worth adding in the [FAQ](https://ddev.readthedocs.io/en/stable/users/faq/) at section "Can different projects communicate with each other?". At least that's where I was expecting to find this piece of information.

**Comment by rfay** [comment]
@felmab added in #2695  - thanks for the nudge.
