### ISSUE TITLE
Simplify updating ddev by adding `ddev self-update` cmd

### ISSUE THREAD

**Issue by tbal** [drud/ddev#2680]
**Is your feature request related to a problem? Please describe.**
As a linux user my ddev updating workflow is like this: search for ddev install docs, get link for install shell script, download install shell script, make it executable, execute install shell script.
That often holds me off updating ddev shortly after I heard about a new update. 

**Describe the solution you'd like**
I would love to have a `ddev self-update` cmd like [`composer self-update`](https://getcomposer.org/doc/03-cli.md#self-update-selfupdate-). As first parameter it should accept the version.

**Comment by rfay** [comment]
Thanks for this great idea. I'm not entirely sure can work across platforms, but definitely worthy!

**Comment by rfay** [comment]
@tbal What OS do you use? Most people use `brew upgrade ddev` on macOS and Linux, and `choco upgrade ddev` on Windows. The shell script works fine, but package managers make it easier.

**Comment by tbal** [comment]
Using Ubuntu (18.04) here. Never thought about using `brew` on Linux, thought it would be a Mac tool.. ;)
I'm trying package managers wherever I can, using PPA for some packages and e.g. pip for docker-compose. Maybe I should give `brew` a try for ddev..
Nevertheless I would love to see something like `ddev self-update` someday, to have the updating tool just included.
But I understand, that it might be complex when it should work across platforms.

**Comment by rfay** [comment]
Yeah, homebrew for linux is great. https://brew.sh. But it's pretty slow to update. I continue to hope that we can eventually support regular apt packaging, see https://github.com/drud/ddev/issues/1678

**Comment by tbal** [comment]
Regular apt packaging would be awesome!

**Comment by jcnventura** [comment]
Update script user here, and very happy. Never got the point why homebrew even exists for Linux.

I understand the point on macOS: you have to make it more into Linux to make it usable. But on Linux itself??

Anyway, I'd be all in for being able to install and use ddev the same way I use composer: install script to download it and self-update.

**Comment by rfay** [comment]
It wouldn't be hard to bundle install_ddev.sh into the ddev binary and make a `ddev self-update`. It could try to figure out how ddev was installed (brew or script) and "do the right thing".  It wouldn't work for Windows, but would work everywhere else. It would confuse arch users who use the packages there.

**Comment by nico-loeber** [comment]
It would be great if ddev self-update could be executed in a non elevated shell (no sudo), as the binary should already be added to path.
Maybe parameterized to "recreate" the linking in the path folder. But it would be great if you could execute sudo ddev self-update then, insted of an error like the current install script does, that will promt you for credentials and will throw an error if you are already root / sudo.
This would make it possible to use the self update in an non interactive and automatic way.

**Comment by rfay** [comment]
It would be lovely to self-update without sudo, and it's worth thinking about, but right now that would seem to mean that we'd have to abandon all the existing install techniques, because most of them install into privileged directories that are already in the $PATH. And remember that we have at least 4 major OS environments here... And each has more than one way to install.

One of the basics of ddev is to try not to alter the host setup whenever possible; about the only exception to this is NFS, for which there's no other way. So I remain hesitant to add to $PATH, etc. And you'd be amazed how many people don't understand how $PATH works or how to change it or work with it.

**Comment by nico-loeber** [comment]
Okay, the non privileged install might not be a good idea as the binary might be directy located in /usr/bin or another protected in PATH directory. I just had a symlink in mind as most software is added to path in that way - my mistake.

But I would be really happy if "sudo ddev self-update" would work!

**Comment by rfay** [comment]
There are so many different ways to install DDEV, and all of them appropriate to their environment. It might be possible to detect the current installation technique and tell people how to do an upgrade?

**Comment by chrisfromredfin** [comment]
Big fan of `ddev self-update` would be a killer feature. +1

**Comment by rfay** [comment]
Thanks for your vote @chrisfromredfin - Not sure it's do-able given the many ways ddev can be installed. How do you install it and in what OS?

**Comment by chrisfromredfin** [comment]
Homebrew on macOS
--
Christopher J. Wells
Redfin Solutions, LLC
office: 908-4-DRUPAL
fax: 207-292-1414
***@***.***
www.redfinsolutions.com

**Comment by rfay** [comment]
So you'd want DDEV to do `brew update && brew upgrade ddev` for you when you did `ddev self-update` ?  What would be your hope?

**Comment by chrisfromredfin** [comment]
Yes, if that were my installation method (it is mine; not sure how to detect which install method was used) but that would be what it could hopefully do for me.

**Comment by Sandra-headscape** [comment]
> So you'd want DDEV to do `brew update && brew upgrade ddev` for you when you did `ddev self-update` ? [...]

that almost sounds like a line in the docs about adding an alias would be sufficient 🙈 

I'm using ddev via homebrew on mac os (m1), and followed the link that came with the update message to https://github.com/drud/ddev/releases - and think I'm going to add an alias.

It seems there's the basic functionality request (add an alias on macs with homebrew) and a whole bunch of additional things (detect OS, detect installation method, support installing different versions, and more), which I feel are out of scope for ddev itself.

I think the points for and against are all valid, and I'm personally ok for now, but I feel someone making a start on a feature for a PR or separate project could be useful. thanks!

**Comment by rfay** [comment]
Most people are now managing ddev with package-based solutions, and there may be more in the future, so I think this feature request won't work out, and would require lots of extra effort. 

It might be that someone could craft a custom command that would *say* what to do? It's not exactly self-update, but it would make it easy. The bash script could try to figure out how ddev was installed and then suggest the correct action for people?

**Comment by chrisfromredfin** [comment]
That's definitely a decent compromise, and could be moved over to
ddev-contrib maybe. For me, it's mostly that I forget the archaic brew
command I need. An alias might be enough for me... :-p

**Comment by rfay** [comment]
@chrisfromredfin what archaic brew command do you need? I just use `brew upgrade`...

**Comment by chrisfromredfin** [comment]
Moreso the package name. Wish it could be brew update ddev, but it's more
of the drud/drud stuff, right? And two druds? brew upgrade drud/drud/ddev?
And if I want a dev version I add something onto that? And also is it brew
update or upgrade, cuz that matters? (Most of my issue is with homebrew :) )

--
Christopher J. Wells (he/him/his)
908-4-DRUPAL
***@***.***
www.redfinsolutions.com

**Comment by rfay** [comment]
I'd love it if you folks could try out the PR, artifacts in https://github.com/drud/ddev/pull/4419#issuecomment-1332865877
