### ISSUE TITLE
Feature request: Default to ddev list --active-only

### ISSUE THREAD

**Issue by chellman** [drud/ddev#2682]
**Is your feature request related to a problem? Please describe.**

This is a twofold request to make `ddev list` fit the way I use it, to see if it matches other folks' use.

**Describe the solution you'd like**

The most important thing to me is seeing which projects are currently running.  `ddev list -A` is what I use, but capitalizing that A is bumming me out.  Could `-a` be added as additional option so as not to break other peoples' muscle memory, but make it easier to type?  I would expect that capitalized switches would be used as secondary options to the lowercase version, but there is no lowercase version here. I haven't looked through the other commands that might have this same capitals issue; this is the only one I've noticed so far.

A bigger change that I would maybe like even more is making `--active-only` the default behavior, with something like `ddev list --all` showing all projects.  I'd love that, but I realize a breaking change like that could be unwelcome.

**Comment by rfay** [comment]
Interesting. I didn't know anybody used that. It was originally kind of a stop-gap between the time long-ago when we *only* looked at docker to find out what was running.

One thing you might like... a quick custom command "lista" that was just a wrapper on `ddev list --active-only`

**Comment by chellman** [comment]
Yeah, just gave myself this in ~/.ddev/commands/host/la

```
#!/bin/bash

## Description: List active projects
## Usage: la
## Example: "ddev la"

ddev list --active-only
```

**Comment by chellman** [comment]
Unforeseen consequence of this approach - if I run the command in the directory of a ddev project that isn't running, ddev starts the project before running the command!

**Comment by rfay** [comment]
Yeah, custom commands start the project. Guess they probably shouldn't for host commands huh?

**Comment by chellman** [comment]
If possible, no.

If it weren't for the mixed shell issue (I use a different shell from others on the team), I'd just change it to a bash alias or whatever anyway. But if a host command could not auto-start the project, that seems like it would be a good thing.

**Comment by rfay** [comment]
https://github.com/drud/ddev/issues/2688

However... `ddev launch` is a host command, and it is nice that it starts...

**Comment by rfay** [comment]
I'm going to close this for now, happy to continue the conversation here or elsewhere. It seems like you have an adequate solution, and it's always troublesome to change things for everybody.
