### ISSUE TITLE
Create a service configuration for memcache

### ISSUE THREAD

**Issue by tannerjfco** [drud/ddev#269]
## What happened (or feature request):
Feature Request
In #121 we determined memcache was one of several popular services that can be a requirement for more complex applications. In order for ddev to facilitate local environments for these more complex applications, we should provide an optional service configuration for memcache.

## What you expected to happen:
A docker-compose configuration should be made, named `docker-compose.redis.yml`. This configuration should:

- Determine if an existing memcache docker image can be used, or if we need to develop / maintain our own.
- Define a service named memcache that provides a memcache container.
- Where possible, pre-configure the memcache container to reduce required setup for a user.
- Document any steps that are necessary after adding the service file to .ddev to be able to use memcache with a Drupal site.

The [example solr service in documentation](https://ddev.readthedocs.io/en/latest/users/customization-extendibility/#defining-an-additonal-service-apache-solr-example) is a good reference for how this service file should work.

## Related source links or issues:

**Comment by rickmanelius** [comment]
Closing for now until this becomes an end-user request, at which time we can re-open.

**Comment by rickmanelius** [comment]
Hi @jeffsheltren! This looks great and I agree with the approach of installing the PHP extensions would make sense. Long term, I want to include a better ability for users to add these additional docker-compose.service.yml files in a programmatic way, but I think we could easily start by adding another example in our documentation.

Summary. I think this is actionable with the PHP extensions installed and the above example file added to our docs. @jeffsheltren if you can add a PR, we'll get it reviewed and in. And as someone not very experienced with memcached, if you could give me a few ways to quickly test and assert its functional I would appreciate it.

**Comment by jeffsheltren** [comment]
I submitted #923 with the change to the PHP container. I realized that adding both php-memcache and php-memcached extensions added a lot of complexity to enable one but not the other, so I ended up only installing php-memcached -- since php-memcache appears unmaintained at this point.

For testing memcached itself, I would test to ensure that the PHP container can reach the memcached container on port 11211. If you can connect on that port via `telnet` or `nc`, typing `stats` and seeing stats returned should be enough to verify memcached is up and running.

**Comment by dclear** [comment]
thanks @jeffsheltren !

**Comment by rfay** [comment]
This was auto-closed, but if I'm not mistaken, #923 does not actually fix it right, just enables it to be fixed.

**Comment by andrewfrench** [comment]
Closing, this was resolved in #927. 👍
