### ISSUE TITLE
ZSH Autocomplete suggestions broken for some ddev subcommands

### ISSUE THREAD

**Issue by jameswilson** [drud/ddev#2702]
**Describe the bug**

ZSH autocomplete was added in #327 by pr #2234 

ZSH Autocomplete suggestion when typing `ddev <subcommand> ^I` or `ddev <subcommand> -^I` results in an error message in the console and no subcommand options being shown.

Note: `^I` represents the control character for the Horizontal Tab key and is the notation I'm using here to represent what clicking the `tab` key on a keyboard in the console looks like. Don't actually type out the characters `^I`!

Not all sub-commands are affected, and the majority of them work fine as expected.

The error message differs very slightly based on which subcommand is run:

* `ddev ssh ^I` and `ddev exec ^I` result in:
        _arguments:comparguments:325: invalid option definition: (-s --service)-s[Defines the service to connect to. [e.g. web, db]]:

* `ddev logs ^I` results in:
        _arguments:comparguments:325: invalid option definition: (-s --service)-s[Defines the service to retrieve logs from. [e.g. web, db]]:

The error message is repeated three times in console.

**To Reproduce**

1. Mac OS Catalina, which has Zshell installed by default.
2. Install Docker for Mac and ddev (current version v1.16.4)
3. Open Terminal.app
4. Type `ddev ssh ^I`.
5. Type `ddev exec ^I`.
6. Type `ddev logs ^I`.
4. See error messages after all three console commands.

**Expected behavior**
Typing `ddev ssh ^I` should first append a `-` to the command line, and a subsequent `^I` would then provide the option parameters list, like other command suggestions (see screenshots).

**Screenshots**
Some commands are broken:
<img width="1091" alt="Screen Shot 2020-12-17 at 5 27 32 AM" src="https://user-images.githubusercontent.com/243532/102476533-3ad7f380-4029-11eb-9419-f3d131369f43.png">

Other commands work fine:
<img width="777" alt="Screen Shot 2020-12-17 at 5 42 16 AM" src="https://user-images.githubusercontent.com/243532/102477664-a79fbd80-402a-11eb-871a-5c637c76f044.png">

**Version and configuration information:**

- macOS Catalina 10.15.6 (19G73)
- Docker Desktop version 3.0.1
- ddev version v1.16.4
- zsh 5.7.1 (x86_64-apple-darwin19.0) with Oh My ZSH & Powerlevel10k
- config.yaml contents don't matter for this problem as all projects are affected. 
- custom configurations don't matter for this problem as all projects are affected.

**Comment by rfay** [comment]
Thanks for this.  I'm not sure there's much to be done, except see if the generator library has been updated, which is an easy thing. 

You can inspect the actual generations and regenerate them too. Also please make sure you have the latest; if installing with homebrew you should, but they're in the tarball you can download with the matching release.

**Comment by rfay** [comment]
@jameswilson there are many different ways to install zsh completion. Could you please say what technique you're using? Are you using the homebrew version of zsh completions? I see you're using oh-my-zsh. Could you please see if you can recreate these problems with a simplest-possible zsh autocompletion setup?

I did an experimental PR, https://github.com/drud/ddev/pull/2715, that may help us to look at this.

**Comment by rfay** [comment]
I think the PR in #2715 does a better completion file, it's attached. Please put it wherever your completions go and see if it's an improvement. On my system, the completions where in /usr/local/share/zsh/site-functions/_ddev and I just replaced that with the file generated by the generator in #2715 (which is attached)

I note that commands like `ddev ssh` and `ddev exec` and `ddev logs` that don't take an extra argument still don't find the right thing, but they don't error anyway. And `ddev ssh -<tab>` does the right thing for sure.

[_zsh.txt](https://github.com/drud/ddev/files/5752491/_zsh.txt)

**Comment by rfay** [comment]
I went ahead and pulled #2715, so it will be in the next v1.17 alpha, and will be packaged in homebrew, so you can also try it then, but I'd still love to hear about the packaged _zsh.txt above.

**Comment by rfay** [comment]
I hope you'll try out [ddev v1.17.0-alpha3](https://github.com/drud/ddev/releases/tag/v1.17.0-alpha3), please give it a try. 

Closing this for now, happy to continue the conversation here or elsewhere.
