### ISSUE TITLE
ddev won't start after Docker Desktop for mac 3.0.2 upgrade

### ISSUE THREAD

**Issue by alechko** [drud/ddev#2703]
**Describe the bug**
`ddev start` to a working project now throws error for the web server:

EDIT: I've checked and this issue is reproducible with a new project as well, for example a plain php project generated from scratch won't start with the same error.

```
 core ✗ ddev restart
Restarting project adev... 
Removing container: ddev-adev-web 
Removing container: ddev-adev-dba 
Removing container: ddev-adev-db 
Removing container: c58eee01d7e6_ddev-adev-web 
Using custom PHP configuration: [/Users/dev/docker/project/.ddev/php/php.ini] 
Custom configuration takes effect when container is created,
usually on start, use 'ddev restart' if you're not seeing it take effect. 
Pushed mkcert rootca certs to ddev-global-cache/mkcert 
Building db 
Building web 
Creating ddev-adev-db ... done
Creating ddev-adev-dba ...  
Creating ddev-adev-web ... error
Creating ddev-adev-dba ... done
ERROR: for ddev-adev-web  Cannot start service web: error while creating mount source path '/host_mnt/Users/dev/docker/project/.ddev/apache': mkdir /host_mnt/Users/dev/docker/project/.ddev/apache: no such file or directory 
 
ERROR: for web  Cannot start service web: error while creating mount source path '/host_mnt/Users/dev/docker/project/.ddev/apache': mkdir /host_mnt/Users/dev/docker/project/.ddev/apache: no such file or directory 
Encountered errors while bringing up the project. 
Failed to restart adev: Failed to run docker-compose [-f /Users/dev/docker/project/.ddev/.ddev-docker-compose-full.yaml up --build -d], err='exit status 1', stdout='Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
 ---> 9f0d91cd757a
Step 3/6 : ARG username
 ---> Using cache
 ---> bc757d91f92d
Step 4/6 : ARG uid
 ---> Using cache
 ---> 933ecf3bb063
Step 5/6 : ARG gid
 ---> Using cache
 ---> 9654101b09c1
Step 6/6 : RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")
 ---> Using cache
 ---> fc394f422678

Successfully built fc394f422678
Successfully tagged drud/ddev-dbserver-mysql-5.7:v1.16.0-adev-built
Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
 ---> 9e6709a9d711
Step 3/6 : ARG username
 ---> Using cache
 ---> 0e403c792597
Step 4/6 : ARG uid
 ---> Using cache
 ---> f97253f25654
Step 5/6 : ARG gid
 ---> Using cache
 ---> fe10b44fc734
Step 6/6 : RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")
 ---> Using cache
 ---> 1fedcccba3b6

Successfully built 1fedcccba3b6
Successfully tagged drud/ddev-webserver:v1.16.3-adev-built
', stderr='Building db
Building web
Creating ddev-adev-db ... done
Creating ddev-adev-dba ... 
Creating ddev-adev-web ... error
Creating ddev-adev-dba ... done
ERROR: for ddev-adev-web  Cannot start service web: error while creating mount source path '/host_mnt/Users/dev/docker/project/.ddev/apache': mkdir /host_mnt/Users/dev/docker/project/.ddev/apache: no such file or directory

ERROR: for web  Cannot start service web: error while creating mount source path '/host_mnt/Users/dev/docker/project/.ddev/apache': mkdir /host_mnt/Users/dev/docker/project/.ddev/apache: no such file or directory
Encountered errors while bringing up the project.' 
```

**To Reproduce**
with Docker 20.10 and Docker Desktop 3.0.2 installed run `ddev start` or `ddev restart`

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: macOS 11.1 Big Sur
- Docker Desktop version 3.0.2
- ddev version information (use `ddev version`)
``` core (dialer) ✗ ddev version
DDEV-Local version      v1.16.4                                
db                      drud/ddev-dbserver-mariadb-10.2:v1.16.0
dba                     phpmyadmin:5                           
ddev-ssh-agent          drud/ddev-ssh-agent:v1.16.0            
docker                  20.10.0                                
docker-compose          1.27.4                                 
os                      darwin                                 
router                  drud/ddev-router:v1.16.2               
web                     drud/ddev-webserver:v1.16.3    
```

- config.yaml contents for the misbehaving project
```
name: adev
type: drupal7
docroot: core
php_version: "7.4"
webserver_type: apache-fpm
mysql_version: 5.7
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
use_dns_when_possible: true
```
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?
  - Yes, I have a `php.ini` override for `error_reporting` but that should not interfere, as the issue is not in the php layer. And I have tried to delete it with no success to resolve the issue.

**Workaround**

Roll back to Docker v3.0.0 seems to fix this issue.

**Comment by webdevsuperfast** [comment]
I also had this issue on catalina after upgrading Docker, resetting docker didn't solve it either.

**Comment by alechko** [comment]
@webdevsuperfast it seems that only rolling back the Docker fixes this at the moment. I've just rolled back to 3.0.0 and containers are loading properly, so it's gotta be related to Docker 3.0.2

**Comment by rfay** [comment]
This is https://github.com/docker/for-mac/issues/5157#issuecomment-748454520, best to stay on docker desktop for mac 3.0.1 until it's fixed.

**Comment by rfay** [comment]
And because of auto-upgrade in Docker Desktop, it's a pain to stay with 3.0.1. May be better to go back to 2.5.0.1. See https://github.com/docker/for-mac/issues/5163

You can install [Docker Desktop 2.5.0.1](https://desktop.docker.com/mac/stable/49550/Docker.dmg) and tell it not to upgrade.

**Comment by jwohlfeil** [comment]
Hm, no problems with Docker 3.0.2, Engine 20.10.0 and Catalina: 
![Docker Desktop_2020-12-21 08-21-38@2x](https://user-images.githubusercontent.com/443761/102750118-8fe77280-4365-11eb-942e-5338fe5ab772.jpg)

**Comment by rfay** [comment]
@jwohlfeil I imagine you have "gRPC FUSE" experimental setting turned to "off", which is another workaround for this problem. Thanks for reporting your experience! 

Docker already has a release in the process too.

**Comment by jwohlfeil** [comment]
> @jwohlfeil I imagine you have "gRPC FUSE" experimental setting turned to "off", which is another workaround for this problem. Thanks for reporting your experience!
> 
> Docker already has a release in the process too.

No, it's set: 
![image](https://user-images.githubusercontent.com/443761/102794865-44a48280-43ac-11eb-8a3d-45ec71b08ec8.png)

**Comment by rfay** [comment]
I'm amazed that you can do a `ddev start` with that and 3.0.2. Every ddev thing I've tried (and lando and lots of other things) are all broken. The internet is in a rage :)

**Comment by rfay** [comment]
@jwohlfeil do you have `omit_containers: [db]` perhaps? That would allow it to work I *think*.

**Comment by jwohlfeil** [comment]
@rfay Didn't set omit_containers, here is my ~/.ddev/global_config.yaml:

`omit_containers: []
nfs_mount_enabled: true
instrumentation_opt_in: true
router_bind_all_interfaces: false
internet_detection_timeout_ms: 750
last_started_version: v1.16.2
mkcert_caroot: /Users/jw/Library/Application Support/mkcert
use_hardened_images: false
use_letsencrypt: false
letsencrypt_email: ""
auto_restart_containers: false
project_info:
....`

Of course, the option is also not set per project.

**Comment by rfay** [comment]
Interesting, and doesn't matter much. I assume you've updated to 3.0.3 now, which works OK? I was unable to get the simplest of projects to start with 3.0.2. If you're interested in chasing this, and still on 3.0.2, would you mind running the script in https://gist.github.com/rfay/361c4e1df165774a5262268ef6768884 and capturing the output as a new gist?

**Comment by rfay** [comment]
Also interesting, you have CLI experimental features turned off, but the default is on. I wonder if that had anything to do with it.

**Comment by rfay** [comment]
Anyway, closing this one for now, as 3.0.3 seems to have solved the problem. Happy to continue the conversation here or elsewhere. 

There are a couple of unresolved issues in docker-land:

* https://github.com/docker/for-mac/issues/5157 was the thing that broke everybody in 3.0.2. All the PRs in 3.0.2 were rolled back and the result was 3.0.3 - but we assume that those Docker PRs will still have to come in another release.
* Docker Roadmap issue: [Please don't upgrade docker without asking first](https://github.com/docker/roadmap/issues/183)
