### ISSUE TITLE
Web Dockerfile not working

### ISSUE THREAD

**Issue by do-web** [drud/ddev#2705]
**Describe the bug**
I have created a Dockerfile in web-build with the fallowing:

`
RUN apt-get update && dpkg --configure -a && apt-get install -y --no-install-recommends \
  ca-certificates \
  apt-utils \
  dos2unix \
  cron
`

but after the image start nothing was installed. if i go to the container with ssh web i only can manually install it with apt install cron....

**Version and configuration information (please complete the following information):**

Mac Catalina
Docker Desktop 3.0.1
DDEV-Local version      v1.16.4

**Comment by rfay** [comment]
Looks like you must have solved it @do-web - But it would have been loads easier to use `webimage_extra_packages: ["ca-certificates", "apt-utils", "dos2unix", "cron"]` in config.yaml. 

For cron variants and possibilities, see https://github.com/drud/ddev-contrib
