### ISSUE TITLE
Add Swift Mailer config for Mailhog in Drupal settings

### ISSUE THREAD

**Issue by mglaman** [drud/ddev#2706]
**Is your feature request related to a problem? Please describe.**
I forget I always need to configure Drupal with Swiftmailer to talk to Mailhog over SMTP.

**Describe the solution you'd like**
It'd be rad if the settings.ddev.php provided config overrides for `swiftmailer.transport`. Like this

```
  $config['swiftmailer.transport']['transport'] = 'smtp';
  $config['swiftmailer.transport']['smtp_host'] = '127.0.0.1';
  $config['swiftmailer.transport']['smtp_port'] = '1025';
  $config['swiftmailer.transport']['smtp_encryption'] = '0';
```

**Describe alternatives you've considered**
Not doing this, just documenting it.

**Comment by rfay** [comment]
Seems reasonable to me. If people want something else they can override after the import of settings.ddev.php?

And if they don't use swiftmailer, it does no harm, right?

PR is welcome.

**Comment by mglaman** [comment]
Cool! I'll work on a PR. Folks can override it after the simport of settings.ddev.php and if swiftmailer doesn't exist, then it's just a dropped config override

**Comment by jfcartier** [comment]
This solution works with Mamp Pro 6. Thanks

**Comment by dercheffe** [comment]
Same method works also with new swiftmailer successor "symfony mailer" (project page: [https://www.drupal.org/project/symfony_mailer](https://www.drupal.org/project/symfony_mailer)). This overrides the predefined "native" transport.
`$config['symfony_mailer.mailer_transport.native']['plugin'] = 'smtp';
$config['symfony_mailer.mailer_transport.native']['configuration']['user']='';
$config['symfony_mailer.mailer_transport.native']['configuration']['pass']='';
$config['symfony_mailer.mailer_transport.native']['configuration']['host']='localhost';
$config['symfony_mailer.mailer_transport.native']['configuration']['port']='1025';`

**Comment by rfay** [comment]
I don't actually know why this wouldn't be reasonable to add to settings.ddev.php

**Comment by rfay** [comment]
Right, I'm just saying it could automatically be included in in the settings files in https://github.com/drud/ddev/tree/master/pkg/ddevapp/drupal - a PR would be welcome unless there's a reason to worry.

**Comment by rfay** [comment]
Swift Mailer is obsolete, now it's [Symfony Mailer](https://symfony.com/doc/current/mailer.html)

**Comment by luenemam** [comment]
`drupal\symfony_mailer:1.0.0-alpha6` switched default config to `sendmail`

new overrides are:
```
$config['symfony_mailer.mailer_transport.sendmail']['plugin'] = 'smtp';
$config['symfony_mailer.mailer_transport.sendmail']['configuration']['user']='';
$config['symfony_mailer.mailer_transport.sendmail']['configuration']['pass']='';
$config['symfony_mailer.mailer_transport.sendmail']['configuration']['host']='localhost';
$config['symfony_mailer.mailer_transport.sendmail']['configuration']['port']='1025';
```

**Comment by rfay** [comment]
Interested in doing a PR to add this to settings.ddev.php?

**Comment by luenemam** [comment]
Started a in #4214

**Comment by rfay** [comment]
This was fixed in 
* #4214
