### ISSUE TITLE
Docker 3.0.2 broke file accessing to ddev folder

### ISSUE THREAD

**Issue by bog-h** [drud/ddev#2710]
**Describe the bug**
After updating docker to version 3.0.2, ddev started to show problems on accessing folders nginx_full and apache inside the .ddev folder.

**To Reproduce**

1. Update docker to version 3.0.2
2. run ddev start
3. Optionally: make a backup of your .ddev folder, remove it, run ddev config

**Expected behavior**
A project should start without any problems

**Screenshots**
![image](https://user-images.githubusercontent.com/40270849/102753725-7ef22d80-4374-11eb-9450-7c330be93a28.png)

**Version and configuration information (please complete the following information):**

- Host computer macOS BigSur 11.1 (20C69)
- Docker Desktop version 3.0.2
- ddev version 1.16.4

**Additional context**
Failed to try to fix this problem with the next steps:

1. Give 777 permissions to all files and folders inside .ddev
2. ddev poweroff + ddev start
3. Remove .ddev folder and run ddev config
4. Add .ddev folder as a shared folder in the docker.

**After downgrading docker to version 3.0.1 everything is working fine.**

**Comment by rfay** [comment]
Hi @bog-h - this is https://github.com/drud/ddev/issues/2703 and you'll find workarounds there. They'll also have a new release today it seems.
