### ISSUE TITLE
Docker factory reset deletes all ddev databases and other docker volumes

### ISSUE THREAD

**Issue by begrafx** [drud/ddev#2722]
I was running DDEV all was running well. I got a notice in my CLI that DDEV had an update available, so I installed the update following the instructions (`https://github.com/docker/for-mac/issues/5201`) and as suggested, deleted the images. Following this, a Docker issue arose, which @rfay was kind enough to help me with. I did a Factory Reset on Docker, which did allow the DDEV project to start correctly; and did a `ddev launch` to start things off, but instead of coming up with my Drupal project as it was, Drupal goes directly to the Install sequence, as though this were a brand new project. I've stopped there, so as not to do any further damage/cause any additional problems. Have I somehow trashed my work, or is there some way of recovering?

**Comment by rfay** [comment]
A factory reset on Docker deletes all databases, because they're stored in docker volumes.  I always keep some database dumps around, or snapshots, for when this happens.

**Comment by begrafx** [comment]
So in other words, yes, I've basically trashed everything that I had in development?

**Comment by rfay** [comment]
Your databases are gone. I apologize for not warning you about this, I usually warn people. And most people keep database dumps around for situations like this.

If you have a backup of your system (like Time Machine or whatever) then you can probably restore docker data. I've never tried that.

Do learn how to use `ddev snapshot` and `ddev export-db` and use them whenever something important changes on your system. I keep a directory in each project called .tarballs, and occasionally dump to it with `ddev export-db --file=.tarballs/db.sql.gz`. Using `ddev snapshot` is easier, but oh well.

**Comment by begrafx** [comment]
I mistakenly thought that Snapshot was part of the process. So I hadn't been doing that. As you say, "Oh well..." So, before I trashcan everything, and start from square one (sometimes that 2nd time is easier, as you have a better idea of what you wanted to do, and how (and how NOT) to do it.) Is there any other recovery options? And, as DDEV still has stuff in `ddev list`, is there a way to reset that, rather than `ddev delete --omit-snapshot [projectname]` for each one?

**Comment by rfay** [comment]
I don't understand why you'd delete your projects. Only your databases are gone. Just use them as is.

**Comment by begrafx** [comment]
They're Drupal sites, so without a Database you have very little. Yes, I'll pull my custom themes out, and the like, but I don't see much else being salvageable.

**Comment by begrafx** [comment]
I'll pop this in here, rather than create a whole new issue, as this is hopefully a quick thing and is related to the above, somewhat.

I've been encountering an oddity with Docker recently. There are times I will restart my machine, and when it restarts, Docker does not launch. I go in and click the icon from the Applications menu, and nothing happens. I'm finding that if I completely power off my machine and let it sit for a bit, that when I start it again, Docker does launch. I'm thinking this may be early signs my HDD is going, but not to digress too far, my question is, if I get a new drive, or decide to uninstall/reinstall Docker, what do I need to make sure to back up, to make sure that DDEV and all of my projects will still work afterward?

**Comment by begrafx** [comment]
I've just updated to 3.3.3
