### ISSUE TITLE
Windows & WSL: Upper/Lowercase issues with project paths

### ISSUE THREAD

**Issue by a-r-m-i-n** [drud/ddev#2727]
**Describe the bug**
Sometimes DDEV reject starting projects with the following message:

> $ ddev start
> Starting xxx...
> Failed to start xxx: project xxx project root is already set to C:\dev\armin\xxx, refusing to change it to C:\Dev\armin\xxx; you can `ddev stop --
> unlist xxx` and start again if the listed project root is in error

The problem here: ``C:\dev`` vs. ``C:\Dev``

The actual folder name on Windows is "Dev" (capitalize). In WSL you can access it with both.

**To Reproduce**
Actually I don't when why it happens sometimes. Most of the time, it works. 

**Possible solution**
When on Windows in WSL mode (not sure if you are able to detect this) always register the project paths in lowercase.

Btw. unlisting the project before (re-)starting, works to fix the current state.

Thanks!

**Comment by rfay** [comment]
If you're mounting Windows projects into WSL2, don't do that. It causes horrible performance. Per the docs, please put projects in your home directory (/home/you/...) in WSL2. 

Please be specific about where this is happening. It looks like it's on Windows, but you mention WSL for some reason.

**Comment by rfay** [comment]
Also, always use the *canonical* name of the directory. Even though NTFS is case-insensitive, many other things aren't. So if you visit C:\Dev as `cd \dev` you'll get this kind of behavior. Use the canonical casing for everything you do.

**Comment by a-r-m-i-n** [comment]
Oh I got it. Because it's mounting my whole C:\ including WINDOWS. What a pitty. But this explains why my WSL2 is unusable.

**Comment by rfay** [comment]
Some things to read about setting up WSL2:

* The [docs](https://ddev.readthedocs.io/en/stable/#installation-or-upgrade-windows-wsl2) which are quite loud about not mounting NTFS filesystem into WSL2
* [DDEV-Local from Scratch on WSL2](https://ddev.com/ddev-local/watch-ddev-local-from-scratch-with-windows-wsl2/) screencast and article, which explains the nuances
* [DDEV-Local and PHPStorm Debugging with WSL2](https://ddev.com/ddev-local/ddev-local-and-phpstorm-debugging-with-wsl2/) 
* [DDEV and WSL2 Getting Started](https://ddev.com/ddev-local/ddev-wsl2-getting-started/)

WSL2 is absolutely wonderful. You just need your code in the right place.

**Comment by a-r-m-i-n** [comment]
@rfay I've watched your Screencast. You are installing ddev right in the ubuntu container and using its home dir for your projects. How do you access the project files from within Windows? Via SSH? Or am I forced to use this WSL integration of PHPStorm or VS Code? 

What I really would like to avoid, is the need to sync files between Windows and Linux. I've connected an Intel NUC PC running Linux natively to my Windows machine and there I also have great performance, but need to sync changes manually, because my Git is located locally in Windows file system - and this circumstance raises the potential of making mistakes. 

Thanks!

**Comment by rfay** [comment]
Hi @a-r-m-i-n - See https://ddev.com/ddev-local/ddev-local-and-phpstorm-debugging-with-wsl2/ for how to access the files from Windows. \\wsl$ - https://docs.microsoft.com/en-us/answers/questions/116126/access-wsl2ubuntu-drive-from-file-explorer.html

They're going to make that a little easier in the next major release. 

The problem of syncing between Windows and WSL2 is (along with networking issues) an awkwardness that is worth living with, given the amazing benefits.

**Comment by a-r-m-i-n** [comment]
Thanks! So, just for my understanding: When I access the files with \wsl$ they are also primarily based there, right? I dont have a copy in Windows. This makes not only the functionality but also the project files itself dependent to running Subsystem. Right?

What I am curious about is, where to use Git, then? Because I really like the GUI in PhpStorm. But it uses always the Git installed in Windows, right?

Then Windows Git will stage files which are exclusively available in WSL?

The approach with X11 is in my opinion too much. Before you do this, you should consider to switch your entire host OS to Ubuntu instead.

**Comment by rfay** [comment]
As a long-term fan of PhpStorm and Jetbrains, I'm disappointed with their slow progress on supporting WSL2. 

* You are correct, when you put the code in WSL2, but access it via \\wsl$, the code is inside WSL2 and there is no copy on the Windows side. 
* On using git, please note that current versions of PhpStorm support git with git binary inside WSL2, which I think does what you need, although I haven't tried it. https://blog.jetbrains.com/phpstorm/2020/06/phpstorm-2020-2-eap-3/. However, I'd just use git on the command line inside wsl2. 
* The X11 approach is not really all that bad, and MS promises that X11 will be native and fast in the next version. 

And it's important to note that vscode has wonderful, elegant native support for WSL2. Super easy to use, and a very appropriate way to use a GUI. So unfortunately PhpStorm is losing a fair number of people to vscode in this context.  The [DDEV and WSL2 Getting Started](https://ddev.com/ddev-local/ddev-wsl2-getting-started/) article explains how to use it.
