### ISSUE TITLE
Providing custom php-fpm configuration for PHP worker pool (pool.d/*.conf)

### ISSUE THREAD

**Issue by NochEinKamel** [drud/ddev#2730]
**Is your feature request related to a problem? Please describe.**
With the removal or apache-cgi and the switch to apache-fpm several settings cannot longer be changed via apache-config.
e.g. if you have multiple virtual hosts you could define different php.ini settings via "php_value" in the apache configuration. With php-fpm you need to set up a second worker pool with different configuration.

A more simple example is my problem at hand: I want to serve .phtml files but the default pool settings only allow .php files
> [06-Jan-2021 11:04:41] WARNING: [pool www] child 1785 said into stderr: "NOTICE: Access to the script '/var/www/html/www/info.phtml' has been denied (see security.limit_extensions)"
```
; Limits the extensions of the main script FPM will allow to parse. This can
; prevent configuration mistakes on the web server side. You should only limit
; FPM to .php extensions to prevent malicious users to use other extensions to
; exectute php code.
; Note: set an empty value to allow all extensions.
; Default Value: .php
;security.limit_extensions = .php .php3 .php4 .php5 .php7
```

**Workaround**
Writing an additional config file via hook works fine as workaround - or one could probably just copy .ddev/php/*conf to the pool.d folder here :-)

```
hooks:
  post-start:
    - exec: "echo '[www]\nsecurity.limit_extensions = .php .phtml' > /etc/php/7.3/fpm/pool.d/phtml.conf && killall -1 php-fpm"
```

**Proposed solution**

I would suggest to extend the solution for php.ini customizing:
`*.conf` files created in the `.ddev/php/` directory should be copied to the `pool.d` directory.

Thanks

**Comment by rfay** [comment]
There are a couple of ways to do this right now. I'd recommend just using a custom Dockerfile (.ddev/web-build/Dockerfile) to provide your own pool.d configuration. You'd put the new conf file .ddev/web-build and in the Dockerfile copy it to where it belongs. see https://ddev.readthedocs.io/en/stable/users/extend/customizing-images/#adding-extra-dockerfiles-for-webimage-and-dbimage
