### ISSUE TITLE
Expose Composer bin-dir as environment variable

### ISSUE THREAD

**Issue by gilbertsoft** [drud/ddev#2737]
**Is your feature request related to a problem? Please describe.**
Composer allows to change the bin-dir location in the project's composer.json. Many custom commands are using a fixed location vendor/bin and if changed though the composer.json these scripts to not longer work. One example is the setup for the TYPO3 Core contribution where this folder is set to `bin`.

**Describe the solution you'd like**
During the start we can parse the composer.json and expose the location to an env var which then can be used inside the custom command scripts.

**Describe alternatives you've considered**

**Additional context**

**Comment by gilbertsoft** [comment]
For TYPO3 there are also other things like the public dir which can be changed in the composer.json. Would be cool if we can catch this case too for project type typo3.

**Comment by rfay** [comment]
A very straightforward thing now, with ddev v1.17+, would be to explicitly put the PATH you want into .ddev/config.yaml using `web_environment`. Does this solve this appropriately @gilbertsoft ?

**Comment by rfay** [comment]
I'm going to close this as a dup of the more general #3022  - happy to reopen if just providing addition to `$PATH` in the web container is not a good enough solution.
