### ISSUE TITLE
Allow setting `project_tld` in global config

### ISSUE THREAD

**Issue by tbal** [drud/ddev#2746]
**Is your feature request related to a problem? Please describe.**
We use another `project_tld` in all of our projects, but always the same per user. E.g. `tilo.cosmo`, `randy.cosmo`, ...
These (wildcard) TLDs are mapped to the IP of every coworkers workstation inside the company network. This allows coworkers and mobile test devices inside the company network to access the ddev projects of everyone.

**Describe the solution you'd like**
`ddev config global --project-tld "tilo.cosmo"` 

Setting `project_tld` also inside a projects `.ddev/config.yaml`, than this one would be preferred.

**Describe alternatives you've considered**
Currently we use an interactive script as custom command (`commands/host/setup-local-domain`) to enter the project_tld in an prompt and write it to `.ddev/config.tld.yaml`.

**Comment by rfay** [comment]
This was completed in #4218.
