### ISSUE TITLE
How can I move a DDEV Project to a different directory?

### ISSUE THREAD

**Issue by begrafx** [drud/ddev#2755]
Not a bug, just a question. 

If I have my DDEV project(s) on the local drive of my machine, and I want to move it/them to an external drive, and still be able to work on them, am I "ok" as long as I move EVERYTHING, the hidden files, etc.? Or is there something somewhere that is specifically PATHed, to where relocating the projects would be an issue?

**Comment by rfay** [comment]
If you are going to keep the same name on your project:

1. `ddev stop --unlist` to take it out of global memory
2. Move it
3. `ddev start`

If you're on macOS Catalina and later and are using NFS, you'll need to allow full disk access as described in https://ddev.readthedocs.io/en/stable/users/performance/#upgrading-to-macos-catalina-and-above

**Comment by rfay** [comment]
Added to FAQ in https://github.com/drud/ddev/pull/2748, along with "how to rename project"

**Comment by rfay** [comment]
No response from OP, closing, happy to continue the conversation here or elsewhere.
