### ISSUE TITLE
Support 'ddev auth ssh' to be run as a systemd user service

### ISSUE THREAD

**Issue by Biont** [drud/ddev#2756]
**Is your feature request related to a problem? Please describe.**
I would like to automate the process of setting up SSH keys for use within ddev so I don't have to worry about it after every restart. Now I'm aware there's a couple of ways to do that and maybe I just chose the one route that causes problems, but it feels to me as if a systemd user service is the cleanest solution for this kind of problem since it will work regardless of the DE/WM used.

So here's my example service:

```
[Unit]
Description='DDEV auth ssh': Sets up DDEV authentication immediately after startup
Documentation=https://ddev.readthedocs.io/en/latest/users/cli-usage/
PartOf=graphical-session.target

[Service]
Type=simple
ExecStart=/usr/bin/ddev auth ssh

[Install]
WantedBy=multi-user.target
```

But this results in the following errors:

```
Jan 25 09:56:00 work systemd[673]: Started 'DDEV auth ssh': Sets up DDEV authentication immediately after startup.
Jan 25 09:56:00 work ddev[94415]: the input device is not a TTY
Jan 25 09:56:00 work ddev[94402]: Docker command 'docker [run -it --rm --volumes-from=ddev-ssh-agent --user=1000 --entrypoint= --mount=type=bind,src=/home/biont/.ssh,dst=/tmp/sshtmp drud/ddev-ssh-agent:v1.16.0-built bash -c cp -r /tmp/sshtmp ~/.ssh && chmod -R go-rwx ~/.ssh && cd ~/.ssh && ssh-add $(file * | awk -F: "/private key/ { print \$1 }")]' failed: exit status 1
Jan 25 09:56:00 work systemd[673]: ddev-ssh.service: Main process exited, code=exited, status=1/FAILURE
Jan 25 09:56:00 work systemd[673]: ddev-ssh.service: Failed with result 'exit-code'.

```

[The given error is  a problem known to the internet](https://www.google.com/search?q=systemd+docker+input+device+is+not+a+tty+site:stackoverflow.com&sa=X&ved=2ahUKEwieiqmbwbbuAhVE4aQKHWWIAWMQrQIoBHoECAUQBQ&biw=1171&bih=1316) and the common solution is to drop the `-it` flags from the `docker run` command. Unfortunaetely, this is beyond my reach since I only execute `ddev auth ssh` and I do not control the resulting docker commands.

**Describe the solution you'd like**
If possible, I'd suggest to drop the flags as mentioned. If this is not an option, I would be very happy to hear a suggestion how to avoid the error

**Describe alternatives you've considered**

- `.bashrc` - which restricts users to use bash
- XDG autostart files - which rely on a DE that implements it
- DE-specific ways to run scripts on startup - which only work in that specific DE

**Comment by rfay** [comment]
Are you using keys with no passphrase? The assumption of `ddev auth ssh` is that a passphrase is required for your keys. 

If you have no passphrases on your keys (not recommended) then you might try

```
docker run --rm --volumes-from=ddev-ssh-agent --user=1000 --entrypoint= --mount=type=bind,src=/home/rfay/.ssh,dst=/tmp/sshtmp drud/ddev-ssh-agent:v1.16.0-built bash -c 'cp -r /tmp/sshtmp ~/.ssh && chmod -R go-rwx ~/.ssh && cd ~/.ssh && ssh-add $(file * | awk -F: "/private key/ { print \$1 }")'
```

You'll have to change the mount src from /home/rfay/.ssh to the path to your ssh keys, and the uid from 1000 to your uid. 

Alternately, you can use one of the socat or pty tricks in https://unix.stackexchange.com/questions/249723/how-to-trick-a-command-into-thinking-its-output-is-going-to-a-terminal to try to convince `docker run -it` that you have a terminal when you really don't. 
```

**Comment by Biont** [comment]
Thank you for the feedback. I was hoping to get it working without basically copying out the command (since it's not portable and might change in the future). But yeah, I did not think about passphrases. Good point

**Comment by rfay** [comment]
Since ssh auth lasts until you restart ddev, you could just do something like this in your .profile or equivalent:

```
  if ! (docker ps | grep ddev-ssh-agent >/dev/null 2>&1);  then 
    ddev auth ssh; 
  fi
```

Then, when you log in, it will pause to let you put your key in.

```
$ if ! (docker ps | grep ddev-ssh-agent >/dev/null 2>&1);  then    ddev auth ssh;  fi
Building ddev-ssh-agent
Creating ddev-ssh-agent ... done

ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
Enter passphrase for id_rsa:
Identity added: id_rsa (id_rsa)
```

Closing this now, happy to continue the conversation here or elsewhere.

**Comment by rfay** [comment]
@Biont I"m working on a test that has to do a `ddev auth ssh` and realized that this can also be automated with expect, which does have things running in a pty.  For example, https://likegeeks.com/expect-command/

**Comment by rfay** [comment]
* Expect script with for [keys with no authentication](https://github.com/rfay/ddev/blob/bab9d295ec3d42e866436ea410c4017d3836b512/pkg/ddevapp/testdata/TestAcquiaPull/ddevauthssh.expect)
* Expect script for [keys that require authentication](https://github.com/drud/ddev/blob/master/cmd/ddev/cmd/testdata/TestCmdAuthSSH/ddevauthssh.expect)

**Comment by Biont** [comment]
Very intersting findings @rfay . Thanks for updating here, I'll try it out
