### ISSUE TITLE
Snapshot Restore fails when a  .DS_Store file exists in snapshot directory

### ISSUE THREAD

**Issue by croane** [drud/ddev#2765]
**Describe the bug**
When .DS_Store files get created in the snapshot folder, it prevents the snapshot from being able to be restored.

**To Reproduce**

1. Create a new snapshot with `ddev snapshot`
2. On mac, go into the snapshot folder inside of `.ddev/db_snapshots` in Finder. Then sort the files by file size. I think this will create a .DS_Store file. You could also right-click on the snapshot folder and select get info. I'm not sure which of these generates the file.
3. Restore the snapshot and you will see this error: Failed to restore snapshot 2020-01-29_sync for project gabby-develop2: Failed to start project for RestoreSnapshot: db container failed: log=, err=container exited, please use 'ddev logs -s db' to find out why it failed

**Expected behavior**
If we can delete the .DS_Store files in the snapshot folder before restoring, that fixes the problem: find . -name '.DS_Store' -type f -delete

**Screenshots**
<img width="662" alt="snapshot-restore-error" src="https://user-images.githubusercontent.com/7648514/106333718-809df380-6246-11eb-9d29-ba7121a2f773.png">

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: macOS Big Sur
- Docker Desktop version: 3.1.0
- ddev version information: v1.17.0-alpha3

**Comment by rfay** [comment]
Thanks for this. It will be a good fix. I know macOS is notorious for leaving unwanted files like this around. It would be interesting to know what other files might get thrown in for various reasons. Anyway, this seems like an easy fix.

@shaal this exact thing happened to you, right?

**Comment by shaal** [comment]
@rfay yes, exactly the same scenario.
I think it was because I used finder to look at the snapshot directory, that file was created, and then I couldn't restore snapshot anymore. Once I deleted that file, I was able to restore snapshots.

**Comment by rfay** [comment]
I'm pretty sure the problem here isn't creation of .DS_Store inside db_snapshots/ but rather inside one of the snapshots. 

I note that one can turn off this (ugly) macOS behavior, https://www.techrepublic.com/article/how-to-disable-the-creation-of-dsstore-files-for-mac-users-folders/

**Comment by rfay** [comment]
To create a .DS_Store reliably in the Finder, visit the directory and drag icons around to rearrange them. 

However, I note that you have to go into a *subdirectory* of your target directory sometimes to get the file created.
