### ISSUE TITLE
Simpler script-based installation for Linux/macOS (without HomeBrew)

### ISSUE THREAD

**Issue by gitressa** [drud/ddev#2769]
**Is your feature request related to a problem? Please describe.**
Homebrew seems to be popular with macOS, but I have for many years been using Ubuntu and never had the need for it, and it looks like installing Homebrew on Linux requires a bit of effort, looking at https://docs.brew.sh/Homebrew-on-Linux ...

**Describe the solution you'd like**
Both Docksal and Lando can be installed fairly easily, without relying on installing extra programs:

**Docksal**
`bash <(curl -fsSL https://get.docksal.io)`

**Lando**
`wget https://files.devwithlando.io/lando-stable.deb`
`sudo dpkg -i lando-stable.deb`

It would be awesome if DDEV similarly could be installed as easily, with a one- or two-liner :-)

**Comment by rfay** [comment]
It's already a one-liner with install_ddev.sh, see https://ddev.readthedocs.io/en/stable/#installationupgrade-script-linux-and-macos-armarm64-and-amd64-architectures

**Comment by rfay** [comment]
No response from OP, but I hope install_ddev.sh works for you @gitressa 

`curl -LO https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh && bash install_ddev.sh`

**Comment by gitressa** [comment]
Sorry @rfay, other things got in the way, but I tried the one-liner install, which worked flawlessly, great!

After installing DDEV I used the [Drupal 9 Quickstart](https://ddev.readthedocs.io/en/stable/users/cli-usage/#drupal-9-quickstart) to set up Drupal, which also worked perfectly, it runs fast, etc. So all in all 5/5.

I think the Quickstart guide could be improved slightly, by adding a few commands. For example, in Docksal you don't have to run `site:install` and in Lando you have to define database with `--db-url=mysql://drupal9:drupal9@database/drupal9`, so perhaps it would be helpful to add these two commands to finish the install process, and help get users up and running even faster?

```
ddev drush site:install
ddev drush uli
```
Also, it seemed to me like the `ddev launch` command wasn't necessary, and everything was already running?

I am not sure what the benefits of using Homebrew are as a Linux user? Perhaps you could consider moving the one-line install method up above the Homebrew install method, to make sure potential users are not lost, due to them thinking "that looks like a longer process", when in fact a very quick method exists?

**Comment by rfay** [comment]
The homebrew technique gets you the latest dependencies and for me the most important part is working bash/zsh autocompletion. 

`ddev launch` just opens a browser. It's certainly not "necessary"

The idea behind the quickstarts is to make it as short as possible. A PR to add the `drush si` and `drush uli` would be fine I guess

I'm glad it's all working for you!

**Comment by gitressa** [comment]
Thanks for clarifying! I suppose it is a matter of prioritizing what is most important ... I would consider getting people started with DDEV more important than `bash/zsh` autocompletion -- and those who desire `zsh` integration, will eventually figure out that Homebrew is the road to take.

Anyway, I have created an MR which adds `site:install` and `uli` to the Quickstart guide: #2780.

**Comment by gitressa** [comment]
I just got a mail with a link to a page full of legalese: 

> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our Contributor License Agreement before we can accept your contribution.
> You have signed the CLA already but the status is still pending? Let us recheck it.

I am not going to sign it, so perhaps I should just close this Merge Request?

**Comment by gitressa** [comment]
Thanks for merging into Master.

**Comment by rfay** [comment]
Thanks for the suggestion and PR! Sorry you were disturbed by the CLA. They're common in most projects, but I also find the legalese in this one too intimidating.

**Comment by gitressa** [comment]
Thanks! I haven't participated in many projects, but this is the first CLA I've encountered ...
I look forward to experiment some more with DDEV, have a great day!
