### ISSUE TITLE
MySQL connections are broken from the host

### ISSUE THREAD

**Issue by beeradb** [drud/ddev#277]
## What happened (or feature request):
I was doing some testing today and discovered the MySQL connections from the host aren't working as we intended.

It turns out we made an incorrect assumption when doing the TCP stream proxying on the router, and failed to realize that TCP streams don't support traffic splitting via the host parameter. In hindsight, this is pretty obvious, since TCP streams lack the "host" header that HTTP traffic uses to split traffic based on hostnames. However, either no one tested using multiple servers, or they just failed to realize that all traffic was going to the same MySQL instance. 

## What you expected to happen:
The bad news is this is not fixable with the current architecture and is probably a bigger rework than we'd like. The entire reasoning for MySQL proxying was to keep the networking internals of docker-compose hidden from the user, and create a consistent environment both on the host and within the container for hostnames used to connect to services such as MySQL. 

The good news is, even though this is a bigger rework than we'd like, it will allow us to reduce complexity all around. In the end, I'm optimistic that this will be a big win for reducing complexity and increasing maintainability.

The solution to fixing this likely requires a few pre-requisites:

- [ ] Move to docker-compose v3. https://github.com/drud/ddev/issues/272
- [ ] Remove the nginx-proxy completely. (yay). 
- [ ] Create a network per-application and assign an IPV4 address. We should no longer need a single shared network once the proxy is gone.
- [ ] Update all hostname aliasing to use the IPV4 address assigned to the app.

There is the additional challenge of making sure this is portable across hosts. Thus far our strategy has been to encourage committing docker-compose files. However, if we assign IP addresses to these networks we run into the following issues:

- The addresses need to be static so we can alias hostnames to them
- They also need to either be portable across multiple machines or derived on the fly at start time.

## How to reproduce it (as minimally and precisely as possible):
- Create two ddev applications. Run installations on each (to get data).
- Connect to the database from the host (i.e. using $appname.ddev.local)
- Observe that both connections connect to the same database.

## Related source links or issues:
https://docs.docker.com/compose/networking/

**Comment by rickmanelius** [comment]
It would make sense to tag as v0.8 milestone and prioritize in the next sprint given that this is a bug. Not removing incubate yet because there probably needs to be some additional detail/thought in solving the IP issues before we can proceed.

**Comment by rickmanelius** [comment]
We can convert this to actionable if we include one final AC:
* [ ] Strategy + Implementation for sharing docker compose files with fixed IP addresses (e.g. detect and alert end-user, detect and suggest, detect and correct on the fly, etc).

**Comment by rfay** [comment]
However, this "bug" is just an indicator for a redesign task, so needs to be at a higher level. It needs to indicate the redesign, which affects all connections, not just mysql. I'd recommend we spend a bit of time experimenting with it. In the drupal-vm approach, it also required a specific ifconfig alias creation on macos which may not be available on Linux or may not be doable at all on Windows. (It's related to what we do for setting a localhost alias for xdebug debugging, which also needs some attention now that we've expanded platforms.)

So I'd say this definitely is not itself actionable unless it's just a call for a design. That's probably actionable.

**Comment by rfay** [comment]
Note that it is probably possible for us to circumvent the OP at this time by just not exposing the mysql port directly, perhaps encouraging people to use `ddev exec drush sql-cli` for example.

**Comment by tannerjfco** [comment]
As noted in https://github.com/drud/ddev/issues/272#issuecomment-305016714, per-container IPs don't look to be a feasible approach for Docker for Mac. This unfortunately means we can't pursue the approach originally intended to resolve the OP. Given this, I am reverting the issue title to its original, and intend the following tasks to ensure users can reasonably interact with mysql and discover the port as needed:

- add the exposed and internal ports to ddev describe, w/ documentation explaining the difference
- remove the TCP_EXPOSE stuff since it doesn't accomplish what we're after
- ensure both db and web containers have mysql client configurations so users can run mysql commands w/o having to define connection/credentials

While this is not the ideal solution we intended and hoped for, I believe it will be sufficient. We provide phpMyAdmin out of the box, and offer pre-config for SequelPro on mac. I think if we also ensure the mysql clients in the db and web containers can be easily used, that we've covered most of the common use cases where a user might want to determine how to connect to the database.

**Comment by rickmanelius** [comment]
Technically, this should have been moved to v0.7. Updating milestone flag.

**Comment by rickmanelius** [comment]
Small nitpick, but the helper text should provide a fully working command OR hint that more information is needed. 

`mysql --host 127.0.0.1 --port 32780`

Needs to be extended:

`mysql --host 127.0.0.1 --port 32780 --user db --password db --database db`

**Comment by rfay** [comment]
https://github.com/drud/ddev/pull/316 improves the mysql example command.
