### ISSUE TITLE
npm install in custom Dockerfile doesn't work 

### ISSUE THREAD

**Issue by BennyAlex** [drud/ddev#2779]
**Describe the bug**
Hello,
I updated today to latest ddev (windows) version. Now when building the web container, the npm install command didnt' get execuded(?), so no node_modules folder is created on the disk. When running the install comand inside the container, it works fine. I tried to cd manually into project directory but didn't fixed it.

Heres my Dockerfile: 
```
ARG BASE_IMAGE
FROM $BASE_IMAGE
RUN npm install --global gulp-cli

# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
# Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteer
# installs, work.
RUN apt-get update \
    && apt-get install -y gconf-service libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxss1 libxtst6 libappindicator1 libnss3 libasound2 libatk1.0-0 libc6 ca-certificates fonts-liberation lsb-release xdg-utils wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \

RUN npm i
```

**To Reproduce**

1. Go to 'start a container with custom dockerfile'
2. After building, node_modules is missing.

**Expected behavior**
npm i runs as expected

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: Win 10 latest
- Docker Desktop version if on macOS or Windows (from "About Docker Desktop"): Win 3.1.0
- ddev version information (use `ddev version`): ddev version v1.16.6
- config.yaml contents for the misbehaving project:
```
name: recollectr
type: laravel
docroot: public
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
mysql_version: ""
provider: default
use_dns_when_possible: true
composer_version: ""
```

**Comment by rfay** [comment]
So the /var/www/html isn't the one you think it is. You can't access your project's /var/www/html during the Dockerfile build, because it's not mounted yet. So what you were doing here with
```
RUN cd /var/www/html/ \
    && rm -rf ./node_modules/ \
    && npm i
```

That can never work.

**Comment by BennyAlex** [comment]
@rfay 
As I said, I also tried it without cd (I tried it just because npm i didnt work). So `RUN npm i` should work, I thought?

**Comment by rfay** [comment]
No, it can't work, never could. You cannot access the mounted project during the Dockerfile build. It's not there. There's perhaps something else there (maybe an empty /var/www/html) but not your project. You can install the stuff you're installing with apt-get, but you cannot do the npm install in a custom Dockerfile. Your project is not there to be installed to.

**Comment by BennyAlex** [comment]
Ah okay. Can you explain, where I can call it , please? :)

**Comment by rfay** [comment]
In a post-start hook, or after start with `ddev exec npm install` or `ddev ssh` and `npm i`.

The Dockerfile is the *build* process for the image. You need to install something in your project, which does not exist during the build if the docker image.

**Comment by rfay** [comment]
You'll see a number of examples of post-start hooks in https://ddev.readthedocs.io/en/stable/users/extending-commands/

**Comment by rfay** [comment]
The docs in https://ddev.readthedocs.io/en/stable/users/extend/customizing-images/ already has

> Remember that the Dockerfile is building a docker image that will be used later with ddev. At the time the Dockerfile is executing, your code is not mounted and the container is not running, it's just being built.

but I added a bit more emphasis in https://github.com/drud/ddev/pull/2781

Closing. Happy to continue the conversation here or elsewhere.
