### ISSUE TITLE
Consider ddev releases as part of the build process.

### ISSUE THREAD

**Issue by cyberswat** [drud/ddev#278]
## What happened (or feature request):
I have a script that I use to package releases for ddev at https://gist.github.com/cyberswat/4423128d8bd82368610be6dc10a8fa12.

It downloads artifacts from circle ci and packages them for inclusion on the github release page.  For example, https://circleci.com/gh/drud/ddev/900 is the build that was run to create the binaries for the v0.5 release.  If the gist is saved as ddevrelease.sh then it would be executed as 

```ddevrelease.sh https://900-80669528-gh.circle-artifacts.com/0```

It downloads each of the binaries, creates an archive of them and then create a sha hash of them.

Not sure how this would fit into the build process, but it would be nice from a release persepctive.

**Comment by rfay** [comment]
I don't know of any reason to object to this. Do you want to go ahead and do a PR to add it to ddev?

I'm totally in favor of the circle build generating the sha hashes as well.

**Comment by cyberswat** [comment]
Not sure why this was hibernated and pushed out so far.  It's useful for each release we do.

**Comment by rickmanelius** [comment]
No particular reason. Just need to triage and get prioritized.

**Comment by rickmanelius** [comment]
Made it actionable so we can use and close out the v0.6 sprint :)

**Comment by rickmanelius** [comment]
@cyberswat I suggest adding a reference to the community docs similar to my release checklist (or even within the release checklist) to easily find in the future. https://github.com/drud/community/blob/master/development/product_release.md

**Comment by cyberswat** [comment]
FWIW having CircleCI generate the hashes would be valuable if CircleCI was also generating the *.tar.gz and the *.zip files that are being uploaded with a release.  This is not currently the case.

**Comment by rfay** [comment]
It's super easy to add the tarballs/zipballs and the hashes to the .circleci/config.yaml... Easier than writing a script to do it locally.

**Comment by rickmanelius** [comment]
@rfay @cyberswat I'm assuming this specific issue is no longer needed, correct?

**Comment by cyberswat** [comment]
I think it's safe to close this now that artifacts and hashes are being generated by Circle.
