### ISSUE TITLE
DDEV won't start, sudo fails during `ddev start` on Pop OS/Ubuntu 20.10: sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set

### ISSUE THREAD

**Issue by Vandaahl** [drud/ddev#2786]
I came back to DDEV after not using it for about a month or two. I'm on Ubuntu (Pop_OS actually) and upgraded to the current version of DDEV which is 1.16.6. Starting a project generates an error during boot. I run 'ddev logs -s web' and at the end of the output are these two lines:

+ sudo mkdir -p /mnt/ddev-global-cache/terminus/cache /mnt/ddev-global-cache/ddev-live
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

I don't know what to do. DDEV worked fine on this system in the recent past.

**Comment by rfay** [comment]
Hi @Vandaahl - It sounds like you're using NFS and have it set without root privileges? Are you using NFS? 

Please show the output of `docker version` - It does sound like something's wrong with docker or NFS. (It's not really useful to use NFS on Linux)

**Comment by Vandaahl** [comment]
Hi @rfay, thank you for taking a look. I'm not using NFS because as you say it would not be of use to me. I am also using Lando on this system and it works well.

Here's the output of docker version:

> Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

Output of lsb_release -a:

> No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 20.10
Release:	20.10
Codename:	groovy

**Comment by rfay** [comment]
Haven't seen anything like this with Ubuntu 20.10.  Did you possibly set your filesystem to nosuid?

**Comment by rfay** [comment]
I just installed Pop OS 20.10 from scratch, used the system default docker from apt-get, get the same version as you, and have no trouble with it at all.

I have to assume you have done something special with your OS or filesystem, and I'd love to know what. I imagine that setuid is disabled. 

You also might have disabled some capabilities in Docker.

**Comment by rfay** [comment]
I see this stackexchange about exactly this type of problem: https://unix.stackexchange.com/questions/546822/why-does-sudo-fail-inside-docker-complaining-about-nosuid

* https://github.com/wodby/docker4drupal/issues/388#issuecomment-500330953

`sudo mount` will show you all your filesystems and what options they're mounted with. 

`df /var/lib/docker` will show you what filesystem your docker stuff is mounted on. Normal would be /dev/sda1

I can use `sudo mount | grep sda1` to see the options on /dev/sda1. 

```
# mount |grep sda1
/dev/sda1 on / type ext4 (rw,noatime,errors=remount-ro)
```

I think you'll find that the filesystem where you have /var/lib/docker has `nosuid` set as an option.

**Comment by rfay** [comment]
As for why lando works - IIRC Lando runs all containers as (the default) root, so every process has full root privileges. DDEV instead runs the web container as an unprivileged user so that mostly bad things can't happen based on what happens inside the container. However, to do specific things sudo is provided, which relies on the suid (setuid) capability.

One option you have besides fixing the mount of the volume is to run ddev in the "hardened images" mode, `ddev global config --use-hardened-images` which doesn't use sudo this way (or provide sudo in the container). However, my bet is that will cause you other headaches. It's intended for a "casual webhosting" environment on a real server, but most people like to have full capabilities for their local dev.

**Comment by Vandaahl** [comment]
@rfay Your troubleshooting skills are on point. The stackexchange link you posted describes my situation exactly: I moved /var/lib/docker to another drive. And I did not know about the nosuid option so I kept the defaults set by the Disks utility. I have now removed the nosuid flag and all is well. Thank you so much!

**Comment by rfay** [comment]
Yay, glad it's working for you!
