### ISSUE TITLE
`ddev import-db` Removal of DDL statements in SQL dump can corrupt data if it contains DDL in the data

### ISSUE THREAD

**Issue by njt1982** [drud/ddev#2787]
**Describe the bug**

I have SQL exported from my prod server (MySQL 5.7) using `drush sql:dump` into a gzip SQL file.

I import it into my multisite setup like this:

`ddev import-db --target-db=SITE --src=/Users/nthompson/Downloads/SITE.sql.gz`

However... The `node__body` table is empty. There are no errors shown during import. The SQL file definitely has INSERT statements for this table.

If I to to PHPMyAdmin and import the same SQL file, the table then has data in it.

Equally, if I import it via SequelPro (invoked using `ddev sequelpro`, the same gzip file produces a DB with data in `node__body`.

I cannot see any "verbose" or "debug" flags on `import-db` to see what commands it runs.

Other tables do have data in them, although I've not done extensive inspection to see if its complete or there are is other missing data. The missing node body is enough of a bug for me at the moment 😉

**To Reproduce**

Command above: Simply import the DB.

**Version and configuration information (please complete the following information):**

Host: Big Sur 11.1
Docker Desktop:
![image](https://user-images.githubusercontent.com/384976/107151001-504a0980-6958-11eb-96c9-68d4edc6d18f.png)

```
DDEV-Local version	v1.16.2
db                	drud/ddev-dbserver-mariadb-10.2:v1.16.0
dba               	phpmyadmin:5
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.16.0
docker            	20.10.2
docker-compose    	1.27.4
os                	darwin
router            	drud/ddev-router:v1.16.2
web               	drud/ddev-webserver:v1.16.2
```

Config:
```
name: tmj-d8
type: drupal8
docroot: web
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: ""
mysql_version: "5.7"
provider: default
use_dns_when_possible: true
composer_version: ""
disable_settings_management: true
```

## .ddev/config.multisite.yaml
```
additional_hostnames:
  - tmj
  - ktw
hooks:
  post-start:
  - exec: mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS tmj; GRANT ALL ON tmj.* to 'db'@'%';"
    service: db
  - exec: mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS ktw; GRANT ALL ON ktw.* to 'db'@'%';"
    service: db
```

Let me know if there is anything you'd like me to test..

**Comment by rfay** [comment]
Hi @njt1982 - `ddev import-db` just does a `mysql db <yourfile`

You can experiment with the results manually by just using mysql inside the db container.

The most likely problem for this... which it sounds like you've explored, is that your dumpfile doesn't have the records in it you're looking for.

Use `zless` to look at your SITE.sql.gz - `zless /path/to/SITE.sql.gz` and search for the table and make sure the inserts are there.

I know you already did this, but again, that's by far the most likely reason.

If you're able to share the db dump with me privately, I'll be happy to see if I can recreate this.

**Comment by rfay** [comment]
I did read that you used PHPMyAdmin and SequelPro to import successfully. So the most likely thing is that you have two SIte.sql.gz files going, and one that you access via a GUI is not the same as the one you're accessing via the command line. I know that sounds silly.

You can use mysql on the host or `ddev mysql` (which runs the mysql client inside the db container) to do the same exact import. It looks like you have macOS, you can install mysql-client with homebrew, or use another technique.  For example, `gzip -dc /path/to/dumpfile.gz | ddev mysql db` or (look in `ddev describe` for port) `gzip -dc /path/to/dumpfile.sql.gz | mysql --host=127.0.0.1 --port=55113 --user=db --password=db --database=db`

All of these should result in the exact same thing if you're using the same dumpfile.

**Comment by njt1982** [comment]
Hiya. Thanks for replying so quick.

it is an incredibly odd issue, granted!

I can guarantee it’s 100% the same SQL file. My server backs them up with a day of the week time stamp and I downloaded today’s Sunday one just once. When it didn’t work I assumed my backups were broken so used zless already and could see the INSERT line for that table. This debugging also led me to find that adding  `—extra` lines to drush sql:dump causes it to stop excluding data from common tables like cache and watchdog (which inflated my sql by 8x). But that’s unrelated.

I’ve examine the SQL and there is definitely only one file.

does the ddev import command swallow errors anywhere? I couldn’t see a verbose or debug CLI switch in the docs. I’m wondering if there is a funky character in the SQL which ddev import doesn’t like?!

**Comment by njt1982** [comment]
Interesting thought... does ddev import use the MySQL client on the host or inside the container?

what if my OS X host environment has MySQL 5.6 installed and the container is 5.7?

I’ve experience issues with psql in the paste where mismatched client/server binaries caused random errors.

**Comment by rfay** [comment]
The mysql client on the host doesn't matter at all, in fact there's no need for one to be installed. The client that gets used is the one inside the db container.

I assume you're using matched mysql major versions on the server and in ddev? 

I have certainly seen php code choke on utf8mb4 data and toss it, but have never heard of the official mysql client doing this. 

`ddev import-db` is nothing more than a wrapper on the mysql client in the db container. I've never heard of a case where an error was ignored. 

I hope you'll stick with this so we can really understand it. Would you consider either simplifying or sanitizing the source db dump to where it's shareable? This seems really important. It's also quite likely that in the process of simplifying it you'll find out what is going on.

It seems that you're having trouble with the node__body table. You can dump just that table on the host with `mysqldump <dbname> node__body | gzip >node__body.sql.gz` and then you can test behavior with that. node__body on a drupal site is a very likely place to find utf8mb4 problems.

You should also be able to recreate this problem exporting from your successful db imports used via other techniques. Then you can delete rows from the node__body and then dump and check the results. It shouldn't be able to zero in on a shareable and understood situation.

**Comment by njt1982** [comment]
Thanks @rfay  - thats super useful information & tips. I'll give them a go.

I'm happy to share the DB with you (although not publically on GitHub 😉) -it's only my [blog](https://www.thingy-ma-jig.co.uk) so there is nothing "private" about it; all content is published.

I might also re-run the export using "single row" mode to see if it imports any rows and, if it does, which ones are missing....

**Comment by rfay** [comment]
You can get the db to me a number of ways. randy (at) randyfay.com, or PM on twitter @randyfay or Drupal slack. Thanks for your effort on this, it helps make ddev better. It seems like a pretty important problem to solve!

**Comment by rfay** [comment]
@njt1982 I hope you can get back to this because it seems like an important problem. Please see if you can recreate and get me the db, etc. Thanks!

**Comment by njt1982** [comment]
Hi @rfay - definitely want to resolve it. It's just been "one of those weeks" 😉

**Comment by njt1982** [comment]
Hi @rfay so... made some progress...

I changed the `drush sql:dump` to do `--ordered-dump`... Then re-ran the `ddev import-db` with it. DDEV ended up with 157 rows compared to production's 158.

A little querying later, I see that Node 38 is missing body content in ddev...
https://www.thingy-ma-jig.co.uk/blog/10-10-2006/drop-all-tables-in-a-mysql-database

There is *something* in this node which is the import is unhappy about.

This is the INSERT...

```
INSERT INTO `node__body` VALUES ('blog',0,38,38,'und',0,'<p>This morning I am faced with a task that will involve repeatedly dropping and reimporting a lot of data. MySQL has <strong><code>DROP TABLE</code></strong> and <strong><code>DROP DATABASE</code></strong> but there is no command to drop all tables or truncate the database.</p>\r\n<!--break-->\r\n<p>[adsense:468x60:4496506397]</p>\r\n<p>After finding a reference on the MySQL Lists (<a href=\"http://lists.mysql.com/mysql/193430\">http://lists.mysql.com/mysql/193430</a>) I started playing with the idea. I didn\'t want to have to dump into one file and then run that query. Also - the problem with the above concept is that it drops the table and then recreates it - not what i wanted!</p>\r\n<p>I then looked into using the pipe and <code>grep</code> features in Linux. Now I was getting somewhere! A few tweaks later and this is what I got:</p>\r\n<pre language=\"bash\">\r\nmysqldump -u[USERNAME] -p[PASSWORD] --add-drop-table --no-data [DATABASE] | grep ^DROP | mysql -u[USERNAME] -p[PASSWORD] [DATABASE]\r\n</pre>\r\n<p>In the above, <em>[USERNAME]</em>, <em>[PASSWORD]</em> &amp; <em>[DATABASE]</em> are all the details for your database. You might not need the username and password fields - depends on your setup!</p>','<p>This morning I am faced with a task that will involve repeatedly dropping and reimporting a lot of data. MySQL has <strong><code>DROP TABLE</code></strong> and <strong><code>DROP DATABASE</code></strong> but there is no command to drop all tables or truncate the database.</p>\r\n','full_html');
```

(which reminds me... I need to remove all those legacy adsense placeholders 😉)

It's clearly unhappy about something on that INSERT - but it doesn't throw any kind of warning or error... I'll drop you a copy of the DB.

**Comment by njt1982** [comment]
hmm... This is my config:

```
name: tmj-d8
type: drupal8
docroot: web
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: ""
mysql_version: "5.7"
provider: default
use_dns_when_possible: true
composer_version: ""
disable_settings_management: true
```

But This seems to indicate a much higher MySQL version?
```
(ddev) % ddev ssh
nthompson@tmj-d8-web:/var/www/html/web$ mysql --version
mysql  Ver 15.1 Distrib 10.3.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

Compared to production:
```
$ mysql --version
mysql  Ver 14.14 Distrib 5.7.33, for Linux (x86_64) using  EditLine wrapper
```

**Comment by njt1982** [comment]
hmm..
```
(ddev) [1] % ddev start
Starting tmj-d8...
Pushed mkcert rootca certs to ddev-global-cache/mkcert
Creating volume "tmj-d8-mariadb" with default driver
Building db
Building web
Creating ddev-tmj-d8-db ... done
Creating ddev-tmj-d8-dba ... done
Creating ddev-tmj-d8-web ... done

Creating ddev-router ... done
```

Shouldn't that be mysql, rather than maria?

_/me goes off to read the config.yml docs_

**Comment by njt1982** [comment]
hmm Docker Compose implies it's running 5.7 server..

```
services:
  db:
    build:
      args:
        BASE_IMAGE: drud/ddev-dbserver-mysql-5.7:v1.16.0
```

Is the issue the client in the web container is not matched to the server?

**Comment by njt1982** [comment]
It looks like the web client has Maria installed on it, even though config.yml is specifying MySQL 5.7...

```
apt list --installed
...
...
mariadb-client-10.3/now 1:10.3.25-0+deb10u1 amd64 [installed,local]
mariadb-client-core-10.3/now 1:10.3.25-0+deb10u1 amd64 [installed,local]
mariadb-client/now 1:10.3.25-0+deb10u1 all [installed,local]
mariadb-common/now 1:10.3.25-0+deb10u1 all [installed,local]
```

**Comment by njt1982** [comment]
Of course... this doesn't explain why a 14 year old blog post INSERT doesn't work 😉

**Comment by rfay** [comment]
The mysql used for `ddev import` is the one in the db container, `ddev ssh -s db`

The name of the docker volume is irrelevant; the volume name predated support for mysql, and it would have broken existing users if it changed.

**Comment by njt1982** [comment]
ahh I see... 

In that case, the version is as close-a-match as it should need to be!

`mysql  Ver 14.14 Distrib 5.7.32, for Linux (x86_64) using  EditLine wrapper`

**Comment by rfay** [comment]
The problem is https://github.com/drud/ddev/blob/37ac5f0893c82d18e077d7e1469c4200205b681e/pkg/ddevapp/ddevapp.go#L511-L516We remove DROP TABLE and such in order to keep people from shooting themselves in the foot with bad dumpfile imports. Obviously there are consequences of that and the regex will have to be better!

The [node in question](https://www.thingy-ma-jig.co.uk/blog/10-10-2006/drop-all-tables-in-a-mysql-database) actually contains the text "DROP DATABASE" :)

**Comment by rfay** [comment]
@njt1982 kindly provided the actual dump for testing. For reference when it's time to work on this issue, there are both line-per-row and line-per-table sql dumps in my Dropbox in the tmp directory.

**Comment by rfay** [comment]
This technique works for a corrupted WordPress import: `ddev exec -s db mysqldump db --order-by-primary --extended-insert=FALSE >~/tmp/primary.sql`

**Comment by rfay** [comment]
For a test, to create a dump that has the database name in it, `ddev exec -s <database> mysqldump --databases db >~/tmp/junk.sql`

**Comment by rfay** [comment]
@njt1982 you're awesome. Your careful notice of this has resulted in fixing a nasty bug.  Just for fun look at the blog post that broke ddev.com when it accidentally got imported into DDEV-Local, https://www.ddev.com/ddev-local/ddev-local-database-management/ - look familiar?

**Comment by njt1982** [comment]
Hah. I spy with my little eye, a DROP DATABASE. 😉
