### ISSUE TITLE
Documentation typo in Drupal 9 quickstart instructions

### ISSUE THREAD

**Issue by keithnoseworthy** [drud/ddev#2791]
Hi,

A minor point in https://ddev.readthedocs.io/en/latest/users/cli-usage/#drupal-9-quickstart .
The final command says "`ddev drush launch`". But when I run that I get this error: "Command "launch" is not defined.".

Should this be "`ddev launch`"

Thanks,
Keith

**Comment by rfay** [comment]
Thanks for catching that, yes, it should be `ddev launch`, that's a recent change. Something must have gone wrong.

**Comment by rfay** [comment]
Hmm, I don't see `ddev drush launch` anywhere on https://ddev.readthedocs.io/en/latest/users/cli-usage/#drupal-9-quickstart but I don't remember fixing this or seeing it in a PR.

Please check and let me know if there's still an issue, thanks!

**Comment by keithnoseworthy** [comment]
I got an email a couple of weeks ago saying it was fixed.ThanksKeithSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Randy Fay <notifications@github.com> Date: 2021-02-15  11:37 AM  (GMT-05:00) To: drud/ddev <ddev@noreply.github.com> Cc: Keith Noseworthy <keith.noseworthy@gmail.com>, Author <author@noreply.github.com> Subject: Re: [drud/ddev] Documentation typo in Drupal 9 quickstart instructions (#2791) 
Hmm, I don't see ddev drush launch anywhere on https://ddev.readthedocs.io/en/latest/users/cli-usage/#drupal-9-quickstart but I don't remember fixing this or seeing it in a PR.
Please check and let me know if there's still an issue, thanks!

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/drud/ddev/issues/2791#issuecomment-779335082",
"url": "https://github.com/drud/ddev/issues/2791#issuecomment-779335082",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
