### ISSUE TITLE
install_ddev.sh should insist on not being run as root

### ISSUE THREAD

**Issue by eduardluft** [drud/ddev#2792]
**Describe the bug**
Installation script on linux debian / ubuntu puts the executables under strange permissions. (user 501; group: 50)
Its not a fatal issue, because its works, but can lead to unexpected behaviors, especially when the uid is taken.

**To Reproduce**
Run `curl -LO https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh && bash install_ddev.sh`

Take a look at the installed files:
```
$ ls -lah /usr/local/bin/
-rwxr-xr-x 1  501 staff  20M Feb  3 23:02 ddev
-rwxr-xr-x 1  501 staff 4.6M Feb  3 23:46 mkcert
```
```
$ ls -lah /tmp/
-rw-r--r-- 1  501 staff  48K Feb  3 23:46 ddev_bash_completion.sh
-rw-r--r-- 1  501 staff 4.9K Feb  3 23:46 ddev_fish_completion.sh
-rw-r--r-- 1 root root   12M Feb  9 19:05 ddev_linux-amd64.v1.16.6.tar.gz
-rw-r--r-- 1  501 staff  29K Feb  3 23:46 ddev_zsh_completion.sh
```
```
$ cat /etc/group | grep staff
staff:x:50:
```

**Expected behavior**
User & group permission should be owned by root

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: "Kali 2020.3" and "Ubuntu 20.04.2 LTS"

**Comment by rfay** [comment]
Thanks - Could you please show the output of `id -a` on the host (on the linux computer)?

**Comment by eduardluft** [comment]
```
$ id -a
uid=0(root) gid=0(root) groups=0(root)
```

**Comment by rfay** [comment]
Please don't install (or do anything else with ddev as root). You're in there as the root user. Please use a normal user account.

**Comment by eduardluft** [comment]
Thanks for the fast respond.
Performing the steps under a normal user is done correctly.

```
docker run --rm -t -i kalilinux/kali-rolling /bin/bash
apt update
apt install curl sudo
adduser test
usermod -aG sudo test
su test
cd ~
curl -LO https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh && bash install_ddev.sh
```
```
test@ec0c7840af0f:~$ ls -la /usr/local/bin/
-rwxr-xr-x 1 test test 19973847 Feb  3 23:02 ddev
-rwxr-xr-x 1 test test     1642 Feb  9 20:55 macos_ddev_nfs_setup.sh
-rwxr-xr-x 1 test test  4816008 Feb  3 23:46 mkcert
```

Its currently not documented that the ddev should not be installed by a root user. (https://ddev.readthedocs.io/)
Neither does the installation script stop me from doing the installation via root.

Well then, I know now how to proceed further, thanks for the information.
I leave it to you to decide whether to close the case.

**Comment by rfay** [comment]
I think the script should insist on not being run as root. The NFS setup scripts do, 

https://github.com/drud/ddev/blob/3c45945785554cbe7ab0d0b3b1dcbe7282009013/scripts/debian_ubuntu_linux_ddev_nfs_setup.sh#L23-L26

We can just add that to this one.
