### ISSUE TITLE
WordPress config file overwrites some settings it probably shouldn't

### ISSUE THREAD

**Issue by chellman** [drud/ddev#2795]
**Describe the bug**

WordPress has the lovely behavior of hard-coding links, so when pulling a live site for local dev, one needs to update the hostname somehow.  What I usually do is set the WP_HOME and WP_SITEURL constants in my wp-config.php file, and use `local.example.com`.

Currently, wp-config-ddev.php is setting WP_HOME itself, in a way that overwrites anything that might already be there. It should probably be wrapped in `if (defined('WP_HOME'))` to avoid this problem.  That way I can use whichever version I like.

I also wonder why the table prefix is set in ddev's config file.  It's the same as what comes in the default wp-config.php, so if I've changed it in the main wp-config, I have to either manage the ddev settings myself (remove the autogenerated comment), or add another layer of settings (wp-config-local.php) as I would with a Drupal project.  I'm not opposed to doing the latter, I just don't understand why it's there, since it's the same as the default.

**To Reproduce**

- Configure a project with `local.example.com` in the additional_fqdns.
- ddev start
- Try to load `local.example.com` and see that you get redirected or other undesired behavior

**Expected behavior**

Leave my HOME setting along if it exists, and preferably don't reset the db prefix.

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: macOS Catalina
- Docker Desktop version: 2.5.0.1
- ddev version information: v1.17.0-alpha3
- config.yaml contents for the misbehaving project
```
name: example-site
type: wordpress
docroot: ""
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns:
  - local.example.com
mariadb_version: "10.3"
mysql_version: ""
provider: default
use_dns_when_possible: true
composer_version: ""
web_environment: []
```

**Additional context**

Here's an example wp-config.php:

```
<?php

define('WP_HTTP_HOST', 'http://local.example.com');

define( 'DISALLOW_FILE_EDIT', true );
define( 'WP_POST_REVISIONS', 10 );
define( 'AUTOSAVE_INTERVAL', 180 ); // Seconds

define( 'WP_CONTENT_DIR', dirname(__FILE__) . '/content' );
define( 'WP_CONTENT_URL', WP_HTTP_HOST . '/content' );
define( 'UPLOADS', 'files' );
define('WP_HOME', WP_HTTP_HOST);
define('WP_SITEURL', WP_HTTP_HOST);

// define( 'FORCE_SSL_LOGIN', true );
// define( 'FORCE_SSL_ADMIN', true );

//define( 'DB_NAME', 'example' );
//define( 'DB_USER', 'root' );
//define( 'DB_PASSWORD', 'root' );
//define( 'DB_HOST', '127.0.0.1' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

$table_prefix = 'exp_';

define( 'WP_DEBUG', false );

if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/' );
}

// Include for ddev-managed settings in wp-config-ddev.php.
$ddev_settings = dirname(__FILE__) . '/wp-config-ddev.php';
if (is_readable($ddev_settings) && !defined('DB_USER')) {
	require_once($ddev_settings);
}

require_once ABSPATH . 'wp-settings.php';
```

I can submit a PR for this to help speed it along, just want to make sure the need is understood and desirable for a fix.

**Comment by rfay** [comment]
@jdarrohn @alkymst could you weigh in on this?

**Comment by alkymst** [comment]
@chellman This has been a tricky problem to solve. As you have pointed out, WordPress's use of defines makes the ability to override the variables after the fact impossible. We have had to balance DDEV working by default and the ability for a user to override things.

An Idea we have been exploring is leveraging environment variables and treating `wp-config.php` as a template. This allows things to be overwritten from environment to environment. One of our concerns has been we don't want a DDEV created `wp-config.php` to get added to a repo, deployed and taking down a live site.

An example is how Bedrock handles this - https://roots.io/docs/bedrock/master/environment-variables/#wp-env 

What you have laid out I'm generally in favor of.

All config variables set by DDEV should be wrapped with `if (defined('FOO'))`.

Table prefix should also check that it already has not been set.

I agree moving the loading of `wp-config-ddev.php` to the bottom of `wp-config.php`, but above `require_once ABSPATH . 'wp-settings.php';` will allow you to override any of the generated settings.

Currently you can remove the ddev generated stanza.

```
// Include for ddev-managed settings in wp-config-ddev.php.
$ddev_settings = dirname(__FILE__) . '/wp-config-ddev.php';
if (is_readable($ddev_settings) && !defined('DB_USER')) {
	require_once($ddev_settings);
}
```

A `wp-config.php` Like this should give you what you need.

```
<?php

define('WP_HTTP_HOST', 'http://local.example.com');

define( 'DISALLOW_FILE_EDIT', true );
define( 'WP_POST_REVISIONS', 10 );
define( 'AUTOSAVE_INTERVAL', 180 ); // Seconds

define( 'WP_CONTENT_DIR', dirname(__FILE__) . '/content' );
define( 'WP_CONTENT_URL', WP_HTTP_HOST . '/content' );
define( 'UPLOADS', 'files' );
define('WP_HOME', WP_HTTP_HOST);
define('WP_SITEURL', WP_HTTP_HOST);

// define( 'FORCE_SSL_LOGIN', true );
// define( 'FORCE_SSL_ADMIN', true );

//define( 'DB_NAME', 'example' );
//define( 'DB_USER', 'root' );
//define( 'DB_PASSWORD', 'root' );
//define( 'DB_HOST', '127.0.0.1' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

$table_prefix = 'exp_';

define( 'WP_DEBUG', false );

if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/' );
}

require_once ABSPATH . 'wp-settings.php';
```

**Comment by working-name** [comment]
I think these are fine options, but on a personal level I script a `wp search-replace https://live.url https://live.dev` after importing the live database. That in my mind would prevent having to deal with a lot of the gotchas that come with hardcoding things in wp-config.php. This of course makes an assumption: db always goes downstream. I understand there are workflows where preserving or even pushing db to live is necessary, but those are probably few and far in between (ok to do manually).

**Comment by timnolte** [comment]
The fact that this still exists is a major problem for our adoption of DDev, especially with that fact that DDev is being opinionated with the table prefix. It has been a long time since July and seems like this just keeps getting pushed off. Is there a working branch in progress for these changes or are you looking for a PR to get this addressed? If there is some development needed I'll step up to the plate to get this fixed as it's a huge blocker for our company-wide adoption of DDev.

**Comment by rfay** [comment]
Thanks for your vote, it helps to prioritize. Please remember it's just me behind the keyboard unless somebody else chips in and does a PR. 

Yes, since you're a WP user it will help SO MUCH if you step up to the plate. I'll be very happy to help you along. 

Could you say more about "DDEV being opinionated with the table prefix"? DDEV is in fact opinionated about never using a table prefix, but that seems like the opposite of what you're saying.

**Comment by aManNamedJed** [comment]
I would be happy to take a look at any PRs that come in! Thanks!

**Comment by timnolte** [comment]
@rfay to answer your question about DDev being opinionated about the table prefix is that the code that generates the `wp-config-ddev.php` is setting the `$table_prefix` in such a way that makes it impossible to include that file into an existing `wp-config.php` that needs a different table prefix and not blow up because of the lack of checking for defined constants. I've opened up a PR that I believe should resolve these issues. I'm waiting for the PR checks to complete to grab the binary to do some local testing to confirm things are working as I'd expect.

**Comment by timnolte** [comment]
@aManNamedJed looks like the PR needs to be approved for checks to run. Was hoping to let that build the binary to test but I'll take a look at the developer guide here and see how I can go about getting this built locally to do some testing.

**Comment by rfay** [comment]
I approved the PR

**Comment by rfay** [comment]
@timnolte on opinionated table prefix... It sounds like you know exactly what to do. I imagine that should be another PR? Or at least another issue. Thanks for your help on this!

I don't know if I mentioned that it's super-easy to work on ddev in gitpod, https://github.com/drud/ddev/blob/master/docs/developers/building-contributing.md

**Comment by rfay** [comment]
Just noticed your fix to `$table_prefix = 'wp_';` - I never would have guessed that was in there. It must have been there a long time. Thanks for fixing! None of the other CMS's supported expect any table prefixes I don't think.

**Comment by timnolte** [comment]
@rfay after already cloning the repo and digging in I noticed there was some setup to use Gitpod, I have been dabbling with that on a couple of my WordPress plugins to allow developer to quickly spin up a development environment, as well as GitHub Codespaces. I actually do all of my personal development on a Chromebook so taking advantage of either Gitpod/Codespaces is a nice treat, even though I been moving all my development in general to Docker.

**Comment by timnolte** [comment]
@aManNamedJed & @rfay I've tested out the PR changes and it works in general. There can be some challenges given that `WP_HOME` & `WP_SITEURL` are tightly coupled. You can't manually override `WP_SITEURL` if you need to rely on the DDev generated `WP_HOME`. I think in general given the relatively known local development domain that would be generated for a project overriding `WP_HOME` with the anticipated domain name and then overriding `WP_SITEURL` works.

@chellman I'd be interested for you to download the generated artifact from my PR and give it a try with your setup and see if this is usable for you as well.

**Comment by chellman** [comment]
Thanks for the work on this @timnolte! I haven't been working on WordPress very much lately, and with the holidays I haven't been at my desk enough to be helpful, but this is much appreciated.
