### ISSUE TITLE
ddev start fails after deleting the project (and with custom Dockerfile) - upgrade ddev!

### ISSUE THREAD

**Issue by Diama1** [drud/ddev#2797]
**Describe the bug**
After running `ddev stop --remove-data --omit-snapshot ` and run `ddev start` the bug came

**To Reproduce**

1. `ddev start` on the existing Project

```
Starting ihangane... 
Building ddev-ssh-agent 
Recreating ddev-ssh-agent ... done
 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
Pushed mkcert rootca certs to ddev-global-cache/mkcert 
Building db 
Building web 
Service 'web' failed to build : The command '/bin/sh -c bash nodesource_setup.sh' returned a non-zero code: 1 
Failed to start ihangane: Failed to run docker-compose [-f /Users/diane/ihangane/.ddev/.ddev-docker-compose-full.yaml up --build -d], err='exit status 1', stdout='Step 1/6 : ARG BASE_IMAGE
```

**Expected behavior**
Project starts as per usual.

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: MacOS Mojave 10.14.6
- Docker Desktop version: 19.03.13
- ddev version information : v1.17.0-alpha1
- config.yaml contents for the misbehaving project
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?: No

**Additional context**
Add any other context about the problem here. Thanks!

**Comment by rfay** [comment]
Please upgrade to latest alpha. ddev v1.17.0-alpha4 was released because of an upstream expiration of a key that affects your Dockerfile to build.  When you deleted your project, you deleted the built image, so it had to be built again, and that's why it showed up at this point.

**Comment by Diama1** [comment]
@rfay Thank you so much. it worked!!!

**Comment by rfay** [comment]
Glad it's working for you!
