### ISSUE TITLE
`ddev auth ssh` not working with ed25519 keys

### ISSUE THREAD

**Issue by BennyAlex** [drud/ddev#2798]
Hello, running `ddev auth ssh` will return 

> Error loading key "/home/benny/.ssh/id_ed25519": invalid format
> Docker command 'docker [run -it --rm --volumes-from=ddev-ssh-agent --user=1000 --entrypoint= --mount=type=bind,src=/home/benny/.ssh,dst=/tmp/sshtmp drud/ddev-ssh-agent:v1.16.0-built bash -c cp -r /tmp/sshtmp ~/.ssh && chmod -R go-rwx ~/.ssh && cd ~/.ssh && ssh-add $(file * | awk -F: "/private key/ { print \$1 }")]' failed: exit status 1

I suggest it's a problem with the ed25519 format? Because my key is working normaly on git etc.

Latest ddev on WSL. Latest win version.

**Comment by gilbertsoft** [comment]
Did you create your key using Putty's Keygen? Putty comes with an propriotary key file format which can not be read by SSH. So you have to export your key to the correct format. There is a menu at the top to do this export, you also can load your existing key and export it to the correct format.

**Comment by rfay** [comment]
I am able to generate an ed25519 key and use it without errors, `ssh-keygen -t ed25519` and then `ddev auth ssh`

Could you please try that exact technique?

**Comment by BennyAlex** [comment]
@gilbertsoft  @rfay I created the key with `ssh-keygen -t ed25519 -C "your_email@example.com"` given by 
https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

I use putty but I converted the existing ssh key into putty-key.ppk which is also inside .ssh. But as the log says, ddev is using /home/benny/.ssh/id_ed25519

**Comment by BennyAlex** [comment]
Oh maybe I am wrong, I am using wsl and generated the keys on the host machine and I thought I can also use this keys in ddev, but as I see, ddev want to load it from /home/benny/.ssh which is inside the wsl. Do I have to generate different keys for wsl?

**Comment by rfay** [comment]
Just copy your key to wsl. It doesn't have to be a different key. There are other ways, but that's what I do.

**Comment by BennyAlex** [comment]
Ah okay, I must have done that already, the keys are the same. I can try to generate new ones but currently ddev isn't working at all (yesterday it just worked fine xd)

**Comment by rfay** [comment]
I guess if ddev isn't working at all maybe we should start there. Perhaps docker is broken? Please show the problems you're having, or open another issue, or join us in one of the more interactive support venues. https://ddev.readthedocs.io/en/stable/#support-and-user-contributed-documentation

**Comment by BennyAlex** [comment]
I removed my wsl distro completely, re-installed Ubuntu LTS and ddev and now it's working fine with my copied keys. Thanks for help.

**Comment by rfay** [comment]
Glad it's working for you. No idea what that would have been.

**Comment by BennyAlex** [comment]
My ddev worked fine, but after one night having my laptop in hibernate mode caused it to break. Dont know what this could have been...
