### ISSUE TITLE
Error: This does not seem to be a WordPress installation

### ISSUE THREAD

**Issue by nickw108** [drud/ddev#2811]
I'm having issues with WP-CLI 2.4.0 using ddev version v1.17.0-alpha4 on Apple M1, not sure if this is M1 related, though.

I created a new WordPress project and installed WordPress via web installer. Both frontend and backend work fine under https://wordpress-demo.ddev.site/. Executing `ddev wp` in `~/DDEV/wordpress-demo` works fine, it shows all available WP-CLI commands, but as soon as I call a specific command it shows an error, e.g.

```shell
➜ ddev wp core version
Error: This does not seem to be a WordPress installation.
Pass --path=`path/to/wordpress` or run `wp core download`.
Failed to execute command wp core version: exit status 1
``` 
I also tried executing the command from `~/DDEV/wordpress-demo/htdocs`which is where WordPress is located, as well as passing the path like so `--path="~/DDEV/wordpress-demo/htdocs"` and so `--path="/Users/nick/DDEV/wordpress-demo/htdocs"`, both return the same error.

And this didn't work either 😱 
```shell
➜ ddev wp core download
Error: Failed to get url 'https://api.wordpress.org/core/version-check/1.7/?locale=en_US': cURL error 28: Connection timed out after 10004 milliseconds.
Failed to run wp core download: exit status 1
```

Wondering if others experience problems with WP-CLI, too?

Oh yeah, and I tried the fix from issue https://github.com/drud/ddev/issues/1462, too. Doesn't make any difference.

**Comment by rfay** [comment]
So to simplify things, just `ddev ssh` and use the `wp` command there until you have things working. `ddev wp` is just a wrapper that runs that. So while you're debugging, do that. Obviously if you're unable to access api.wordpress.org, that's nothing to do with wp, but rather your networking or their server.

For pathing, you have to be thinking *inside* the container. Where everything starts with /var/www/html. So definitely start with `ddev ssh` and get wp doing what you want in there, and then you'll be ready to use `ddev wp` later.

**Comment by nickw108** [comment]
From inside the container the `wp` commands work, although I'm still getting the "unexpected error" that "WordPress could not establish a secure connection to WordPress.org". When I ping wordpress.org from outside the container, it works, but not from inside. And not only wordpress.org, but any domain I ping from the inside.

In addition to that there's various PHP warnings and notices, here's the complete output:
```shell
nick@wordpress-demo-web:/var/www/html/htdocs$ wp plugin list
PHP Warning:  An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration. If you continue to have problems, please try the <a href="https://wordpress.org/support/forums/">support forums</a>. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /var/www/html/htdocs/wp-includes/update.php on line 408
Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration. If you continue to have problems, please try the <a href="https://wordpress.org/support/forums/">support forums</a>. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /var/www/html/htdocs/wp-includes/update.php on line 408
PHP Notice:  Trying to access array offset on value of type null in phar:///usr/local/bin/wp-cli/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in phar:///usr/local/bin/wp-cli/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
PHP Notice:  Trying to access array offset on value of type null in phar:///usr/local/bin/wp-cli/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
Notice: Trying to access array offset on value of type null in phar:///usr/local/bin/wp-cli/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
PHP Notice:  Trying to access array offset on value of type null in phar:///usr/local/bin/wp-cli/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
Notice: Trying to access array offset on value of type null in phar:///usr/local/bin/wp-cli/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 662
PHP Notice:  Trying to access array offset on value of type null in phar:///usr/local/bin/wp-cli/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
Notice: Trying to access array offset on value of type null in phar:///usr/local/bin/wp-cli/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 663
+---------+----------+--------+---------+
| name    | status   | update | version |
+---------+----------+--------+---------+
| akismet | inactive | none   | 4.1.8   |
| hello   | inactive | none   | 1.7.2   |
+---------+----------+--------+---------+
```

**Comment by rfay** [comment]
It sounds like you have some network problems. Are you behind a proxy or a VPN?  Perhaps it's a work environment where they have a man-in-the-middle https inspection routine?  Do you have a way to turn off these features? If not, you'll have to do to the web image whatever is required of your work computer.

I have no trouble doing `curl -L https://wordpress.org` from inside the web container.

**Comment by nickw108** [comment]
I'm working from home. macOS firewall disabled and no other firewalls that I know of. If there were, I shouldn't be able to ping or curl https://wordpress.org from outside the container, should I?

Maybe it's a bug with my docker preview version? Will try upgrading to Docker Desktop preview 3.1.0 (60984) from February 11, 2021.

**Comment by nickw108** [comment]
Just read the following in the release notes 😅 
> The host.docker.internal and vm.docker.internal DNS entries now resolve.

**Comment by rfay** [comment]
I tested on a mac M1. host.docker.internal doesn't have to do with what you're facing.  But the release notes explain how to set up with it anyway.

**Comment by nickw108** [comment]
Upgrading to the latest preview version solved the connection issue.
```shell
nick@wordpress-demo-web:/var/www/html$ ping wordpress.org
PING wordpress.org (198.143.164.252) 56(84) bytes of data.
64 bytes from wordpress.org (198.143.164.252): icmp_seq=1 ttl=46 time=114 ms
64 bytes from wordpress.org (198.143.164.252): icmp_seq=2 ttl=46 time=112 ms
64 bytes from wordpress.org (198.143.164.252): icmp_seq=3 ttl=46 time=116 ms
```
Hence this now also works
```shell
nick@wordpress-demo-web:/var/www/html/htdocs$ wp plugin list
+---------+----------+--------+---------+
| name    | status   | update | version |
+---------+----------+--------+---------+
| akismet | inactive | none   | 4.1.8   |
| hello   | inactive | none   | 1.7.2   |
+---------+----------+--------+---------+
```
Thanks for your great support, very much appreciated!

**Comment by rfay** [comment]
Glad it's working for you! Happy to continue the conversation here or elsewhere. Closing this for now.
