### ISSUE TITLE
Automatically starting ddev on boot (Linux)

### ISSUE THREAD

**Issue by fabiankaimer** [drud/ddev#2812]
We're currently running our Drupal application using ddev and a reverse proxy on our Ubuntu server staging system. ddev is installed globally and works just fine.

The VM that the staging environment is running in, however, happens to be frequently rebooted. That means, every time the machine reboots I need to log in and start the environment again manually. I have already automated the restart of the reverspe proxy (wrote a service, deamonized it with systemctl) and would now like to do the same for ddev. I have written a simple bash script that basically just executes `ddev start` and I call it from another deamonized service but I always get the same error: `ddev: commanc not found`.

I suppose, it's because ddev is probably not available at boot or something? Is there any service that I should wait to start before executing my start script or is there any other option to execute the ddev start command on boot? I'm grateful for every suggestion. Thanks y'all!

**Comment by rfay** [comment]
"command not found" means that ddev isn't in your $PATH. When you're logged in and it's working, do a `which ddev` and then in your script, provide the full path, like /usr/local/bin/ddev

**Comment by rfay** [comment]
I use this startup script for casual webhosting on Debian/Ubuntu:

https://ddev.readthedocs.io/en/stable/users/alternate-uses/#casual-project-webosting-on-the-internet-including-lets-encrypt

**Comment by fabiankaimer** [comment]
First of all, thank you for explaining why ddev is not available on boot. Makes sense. Second: thanks a lot for the link, I have been scrolling through the docs for quite a while but I seem to have missed it. That's exactly what I need! I try to implement it and will close this issue afterwards.

**Comment by rfay** [comment]
Happy to continue the conversation here or elsewhere. Closing this for now.
