### ISSUE TITLE
Relax docker version constraint check (openSUSE Tumbleweed)

### ISSUE THREAD

**Issue by alpham8** [drud/ddev#2815]
**Is your feature request related to a problem? Please describe.**
Yes, indeed - I can't even start ``ddev`` since a few distro upgrades: On openSUSE Tumbleweed, which offers docker from its standard repositories, even though it isn't natively support by Docker itself.

But since a few versions of Tumbleweed, I got this error below when trying to bring up the docker-compose containers in my projects:

```
ddev start
The docker version currently installed does not meet ddev's requirements: Invalid Semantic Version
```

**Describe the solution you'd like**
So, my request would be, could you please relax the ddev's Docker version check a bit, that it would match also strings like ``20.10.3_ce``

**Describe alternatives you've considered**
I considered to contact the openSUSE Build Service (the openSUSE repo maintainers), but I think they won't change the distro standard semantic versioning of software just because of this packet. So, the other way around should be the best choice to continue on.

**Additional context**
You can see all details about the RPM packet built here: https://software.opensuse.org/package/docker
Or, by using ``zypper search docker`` and maybe ``zypper in docker``, if you like to and if you're already on openSUSE Tumbleweed.

I didnt' installed the ``docker-compose`` version from the repos, because the protocol was way too old for some other compose projects of mine. So, I installed it as describe in the official docker docs: https://docs.docker.com/compose/install/ by using ``sudo curl -L "https://github.com/docker/compose/releases/download/1.28.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose``

**Comment by rfay** [comment]
docker-compose isn't the problem here, it's docker. Please install docker per the instructions on https://docs.docker.com/engine/install/#other-linux-distributions

I'm not sure when a change like this would get implemented.

**Comment by rfay** [comment]
Could you please provide the output of `docker version` @alpham8 ?

**Comment by rfay** [comment]
@alpham8 https://github.com/drud/ddev/pull/2823 fixes this and it should be in the next alpha release.

**Comment by alpham8** [comment]
@rfay Much thanks for your quick help to that. And sorry for my delay, I was very busy the last days doing organising stuff.

Anyways, in the meanwhile I have talked ot the openSUSE guys. As it turns out, it is indeed a bug of the openSUSE project. The package maintainer named it incorrectly, and they said that should open up a bug. For your backreference, you can track it here: https://bugzilla.opensuse.org/show_bug.cgi?id=1182476

Again, thank you very much for providing us such a great piece of software 👍

**Comment by rfay** [comment]
Thanks so much for following that up in OpenSUSE. Sounds like maybe #2823 shouldn't be pulled then.  I don't see tremendous enthusiasm for a fix there though.

I wasn't able to get bugzilla to accept a password reset, so can't follow that issue. Good issue, well written, got the response it needed, thanks.

**Comment by alpham8** [comment]
There are some news related to that issue. Fabian Voigt wrote as a comment on the bug:

So, I aksed him, what that means and if he would change it, his answer:

> This is not a recent change, the suffix was added in 2017 when docker changed versioning scheme from 1.13.0 to 17.04.0_ce.
> 
> I suspect the error is that %{version} from the .spec file somehow gets into the output of "docker --version" now, which it didn't do previously.

And later on:
> (In reply to Fabian Vogt from comment #2)
> > (In reply to Fabian Vogt from comment #1)
> > > I suspect the error is that %{version} from the .spec file somehow gets into
> > > the output of "docker --version" now, which it didn't do previously.
> > 
> > Yep, the issue is that the .spec file has
> > 
> > export VERSION="$(cat ./VERSION 2>/dev/null || echo '%{version}')"
> > 
> > but that broke when the build was converted away from docker-ce.git to the
> > split repos. It seems like the VERSION file from docker-cli.git isn't
> > directly usable, it only lists "-dev" versions.
> 
> Thanks for your reply. Does that mean that you change it?


> No, as just fixing the path to VERSION resulted in the unusuable -dev version.

I did an distro upgrade, now I got:
```bash
cat /etc/os-release 
NAME="openSUSE Tumbleweed"
# VERSION="20210219"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20210219"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20210219"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo"
```

My current docker version string is as the following (shouldn't changed to the before value):
```bash
docker --version
Docker version 20.10.3_ce, build 46229ca1d815
```

**Comment by rfay** [comment]
Well, it seems silly to add a fix for one errant Linux distro, but it's in now, and it doesn't seem like it should do much harm. Will be in next alpha, and full release should be in a few weeks.
