### ISSUE TITLE
Documentation: PHP Step Debugging

### ISSUE THREAD

**Issue by Bujenoff** [drud/ddev#2824]
**Describe the bug**
I have recently been setting up xdebug for one of my DDEV environments again and I had some issues, so I went to the excellent documentation and followed the troubleshoot guide.

Here I [found some help here](https://ddev.readthedocs.io/en/stable/users/step-debugging/#using-xdebug-on-a-port-other-than-the-default) on how to change the xdebug port, however after DDEV has switched to version 3.x there are some differences in how the configuration of xdebug works and the documentation is no longer accurate.

In the documentation it says to use xdebug.remote_port like so:
`
[PHP]
xdebug.remote_port=11011
`
However in xdebug version 3.x it is recommended to use xdebug.client_port.
Using the xdebug.client_port fixed my issue and I got it to work again.

See the xdebug upgrade guide here: https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_port 

**To Reproduce**

1. Go to https://ddev.readthedocs.io/en/stable/users/step-debugging/#using-xdebug-on-a-port-other-than-the-default
2. See the remote_port example
3. Try changing the xdebug remote port in latest ddev version (1.16.6)
3.a Create php folder in the .ddev folder
3.b Add a php.ini file in the php folder
3.c Add xdebug.remote_port=11011 to the php.ini file
3.d Restart your ddev
4. Try using xdebug on the new port
5. See that it doesn't work.
6. Change the php.ini file to use the xdebug 3.x version of remote_port: xdebug.client_port=11011
7. Try using xdebug on the new port again
8. See that it works.

Ultimately, I don't create a lot of project issues, so I'm unsure of the detail level to give here.

DDEV still works fine with xdebug with the new settting, so I think it's just a matter o updating the documentation.

**Comment by rfay** [comment]
Thanks! Would you like to try a PR on the docs? You can just click "edit on githup" in the upper right on ddev.readthedocs.io on that page (https://ddev.readthedocs.io/en/stable/users/step-debugging)

**Comment by scor** [comment]
I ran into the same problem as well and was going to post a PR, but I'll let @Bujenoff go ahead and post it.

@rfay while on the topic, the default port for xdebug has changed from 9000 in xdebug2 to 9003 in xdebug3, something that PHPStorm is acknowledging: https://www.jetbrains.com/help/phpstorm/configuring-xdebug.html#integrationWithProduct - however ddev forces the default at the old 9000 value. Would you consider changing that to 9003 to remain in line with the default value of xdebug3?

**Comment by rfay** [comment]
@scor  I'd love to move to 9003, but that would assume only the latest PHPStorm, and it would assume PHPStorm... People use a lot of old PHPStorm and they use a lot of vscode, and even other IDEs. All of which still default to 9000.

**Comment by rfay** [comment]
This was fixed in https://github.com/drud/ddev/pull/2827, thanks!
