### ISSUE TITLE
New provider interface in latest ddev v1.17 alpha; `ddev config <provider>` is gone

### ISSUE THREAD

**Issue by bkbelton** [drud/ddev#2826]
It looks like the method of configuring a provider (like Pantheon) has changed? 
'ddev pull' gives this message:
Pull files and database using a configured provider plugin.
        Running pull will connect to the configured provider and download + import the
        latest backups.
Is there documentation on how to configure a pull for Pantheon? I am doing manually using import-db and import-files with downloaded tar.gz's, but I am wondering what the proper way to do 'ddev pull' is.

MacMini M1/ddev version v1.17.0-alpha6

**Comment by rfay** [comment]
Thanks, happy to continue the conversation here or elsewhere.
