### ISSUE TITLE
Evaluate and (Potentially) Optimize the Drupal 8 GUI Site Install Time on macOS

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#283]
## What happened (or feature request):

Feature Request

## What you expected to happen:

TL;DR, I would like to determine of the 2:1 ratio of install times between the Drupal 8 GUI install.php page and the `drush site install` is a theoretical limit OR if there are other factors at play. Potential parameters to investigate: native versus docker, file mount solution, host OS, php.ini discrepencies, etc.

## Related source links or issues:

**Comment by rfay** [comment]
Some results from one-shot case studies which could be flawed in various ways. These are all drupal8 installs (from our 8.3.2 repository). Most are using Macbook Air 2013 hardware.

Environment                                                          | drupal8 install time
----------------------------------------------  | --------------------
ddev, OSX, with nginx-proxy   | 7:45
ddev, OSX, without nginx-proxy | 7:50
ddev, OSX, without mount (drupal8 cloned in container)      | 5:22
native nginx/fpm, OSX | 2:50
ddev, Ubuntu 14.04 VM, 2GB, 1 cpu, no nginx-proxy, on Macbook air 2013 | 1:15 
native nginx/fpm, Ubuntu 14.04, linode 2G | 1:26

**Comment by rickmanelius** [comment]
It's incredibly impressive that a 2GB Linux VM beats the pants off a souped-up macOS + Macbook installation. I'm still curious how Docker for Mac adds that much overhead (almost 6X) for your particular setup! Alas, we will wait for Docker for Mac to analyze and improve said performance.

**Comment by rickmanelius** [comment]
Related https://github.com/drud/ddev/issues/257#issuecomment-306332027

**Comment by rickmanelius** [comment]
The last result by @rfay in #257 seems to indicate that the 2:1 ratio between the GUI and CLI install times for D8 is not necessarily a given and there are other factors at place. Copying the results here, he timed the following:

* kbox d8 install time web: 2:11
* kbox d8 drush si -y install time: 2:03

Closing this for now because it looks like most of the yield for Docker for Mac will be adjustments to the file and network performance issues, which are largely out of our control unless/until we adopt other solutions like Unison (which have other implications). Also could evaluate docker image resources and php.ini differences.
