### ISSUE TITLE
Remove drud-go usage from ddev

### ISSUE THREAD

**Issue by rfay** [drud/ddev#284]
## What happened (or feature request):

drud-go is becoming private, and will be decommissioned per https://github.com/drud/general/issues/110 - We should stop using it.

So... Remove usages of drud-go from ddev, and copy them into appropriate places in ddev where needed. But consider using other tools that have a better lineage.

**Comment by beeradb** [comment]
I did a quick test and it looks like we are fine for removal except for the following packages:

- github.com/drud/drud-go/utils/try
- github.com/drud/drud-go/utils/system
- github.com/drud/drud-go/utils/stringutil

**Comment by rfay** [comment]
Note that system.DownloadFile() has a very naive failure that dogs us all the time and it should *not* be copied - would be better to fix https://github.com/drud/ddev/issues/157

**Comment by beeradb** [comment]
We should probably just take on #157 before this, then?

**Comment by beeradb** [comment]
<dl>
<dt>github.com/drud/drud-go/utils/stringutil</dt> 
<dd>Only used for util.RandomString(). I'd say we should just copy it in.</dd>
<dt>github.com/drud/drud-go/utils/try</dt>
<dd>Only used in dockerutils.GetPodPort(). We could either bring it over, or just vendor https://github.com/matryer/try/blob/master/try.go which looks to b the original source. I'd probably just vendor it</dd>
</dl>

It seems like step 1 is to fix our system.DownloadFile issues, and then the rest of this should be trivial.

**Comment by tannerjfco** [comment]
stringutil and try are removed in #277. That leaves network and system:

```
tannerjfco drud/ddev ‹mysql-fix› » govendor list -v github.com/drud/drud-go/utils/network
 v  github.com/drud/drud-go/utils/network ::/vendor/github.com/drud/drud-go/utils/network
    └──  l  github.com/drud/ddev/cmd/ddev/cmd
tannerjfco drud/ddev ‹mysql-fix› » govendor list -v github.com/drud/drud-go/utils/system
 v  github.com/drud/drud-go/utils/system ::/vendor/github.com/drud/drud-go/utils/system
    ├──  l  github.com/drud/ddev/cmd/ddev/cmd
    ├──  l  github.com/drud/ddev/pkg/plugins/platform
    ├──  l  github.com/drud/ddev/pkg/testcommon
    └──  l  github.com/drud/ddev/pkg/util
```

**Comment by rickmanelius** [comment]
Making actionable and moving to the board.

**Comment by rickmanelius** [comment]
With the PR closed, can we close this issue @beeradb? Or is there more work to do?

**Comment by rfay** [comment]
No, there are still references to drud-go in the vendor directory:
```
$ grep -r drud-go *
vendor.json:			"path": "github.com/drud/drud-go/utils/cache",
vendor.json:			"path": "github.com/drud/drud-go/utils/network",
vendor.json:			"path": "github.com/drud/drud-go/utils/stringutil",
vendor.json:			"path": "github.com/drud/drud-go/utils/try",
```

**Comment by rickmanelius** [comment]
Ty. Moving from needs review to indicate it's still actionable!

**Comment by beeradb** [comment]
There are two open PRs which complete the remainder of this. #304 and #285.

Once those are merged we're done here! 🎈

**Comment by beeradb** [comment]
#304 and #285 have both been merged! closing this out.
