### ISSUE TITLE
Project names that are not the same as the folder name become unstable

### ISSUE THREAD

**Issue by bartlangelaan** [drud/ddev#2843]
**Describe the bug**
If you configure a project with a name that is not the same as the directory name, it behaves unexpectedly.

**To Reproduce**

The following script works perfectly (a ddev project "ddev-test" is created and re-configured).
```
mkdir ddev-test
cd ddev-test

ddev config --project-type=drupal9 --project-name=ddev-test
rm -rf .ddev
ddev config --project-type=drupal9 --project-name=ddev-test
```

The following does however not work _(the only difference is the folder name)_:
```
mkdir ddev_test
cd ddev_test

ddev config --project-type=drupal9 --project-name=ddev-test
rm -rf .ddev
ddev config --project-type=drupal9 --project-name=ddev-test
```

It shows this error:

- _This project root /home/bart/[path]/ddev_test already contains a project named ddev-test. You may want to remove the existing project with "ddev stop --unlist ddev-test"_

Also, when the `ddev list` command is run, it shows `ddev_test` and not `ddev-test` as name. 

**Expected behavior**
I expected the commands to work the exact same way, no matter the name of the folder. 
Also, I expect the 'list' command to always contain the name of the project instead of the name of the folder.

**Version and configuration information (please complete the following information):**

Host computer OS and Version: Windows 10 Pro with WSL2.

```
DDEV-Local version      v1.16.6                                
db                      drud/ddev-dbserver-mariadb-10.2:v1.16.0
dba                     phpmyadmin:5                           
ddev-ssh-agent          drud/ddev-ssh-agent:v1.16.0            
docker                  20.10.2                                
docker-compose          1.25.0-rc4                             
os                      linux                                  
router                  drud/ddev-router:v1.16.2               
web                     drud/ddev-webserver:v1.16.6
```

**Comment by rfay** [comment]
Hi @bartlangelaan 

You'll note that during

```
ddev config --project-type=drupal9 --project-name=ddev-test
rm -rf .ddev
ddev config --project-type=drupal9 --project-name=ddev-test
```

you did not delete the original project. You needed to not just delete its files, but also delete it from global configuration. You did this in the first series with `ddev stop --unlist`, which removes from global config but doesn't delete the database. It can also be done with `ddev delete`, which deletes both global configuration and the database or other volumes. 

So please don't go deleting projects from the filesystem without first deleting them from ddev.

AFAICT the behavior looks perfect. `ddev list` would have told you what to do with the project in each case.

**Comment by bartlangelaan** [comment]
But isn't it weird that this behaviour is inconstant? I thought it was supported that you can re-generate the .ddev folder by just running `ddev config`. And that _does_ work, but only if the _old_ project name is the same as the folder name (which is the case the most of the time for me, why it looks like a bug that it doesn't work when that's not the case).

**Comment by rfay** [comment]
You have created a project in that directory and not deleted it. It's remembered globally. You have global state. AFAICT the behavior is consistent, you just didn't understand the global component.

**Comment by bartlangelaan** [comment]
But it _does_ work when the project has the same name as the folder, and it _doesn't_ work when it's different. Which is inconsistent, right?

If you don't think this is weird behaviour, then it's fine with me! ;-) 
I just thought it was a bug because it did work on the 99% of the time for me, I only change the project name if it contains a special character in the folder name.

**Comment by rfay** [comment]
Of course, please don't use invalid characters in your project names (the underscore)

**Comment by rfay** [comment]
Basically, if you can demonstrate a problem where you're having trouble with a project when you *create*, then *delete*, then rm the files, then create again, let's chase it. Otherwise let's close this.

**Comment by rfay** [comment]
Closing for now, happy to reopen if you find this is worth chasing.

**Comment by dmitryd** [comment]
I also have this issue and `ddev stop --unlist whateverhere` does not help at all. It is simply not possible to do anything except matching the project's folder name to the project name. Those "stop" commands have no effect whatsoever.

**Comment by rfay** [comment]
I use `ddev stop --unlist <projectname>` regularly, but you can just edit ~/.ddev/global_config.yaml to remove items you don't want.

**Comment by dmitryd** [comment]
> I use ddev stop --unlist <projectname> regularly

It works in general and this is what ddev suggests. But it does not work in this case. It is not possible to do anything with the project of the folder name does not match the project name. Well, I did not try hacking the global config file yet...

**Comment by jorissteyn** [comment]
I can confirm this is not resolved. Deleting / unlisting is not enough to get the project working. It seems an absolute requirement for the folder name to be identical to the project name in `config.yaml`.

**Comment by stasadev** [comment]
The next version of DDEV (v1.23.2, which has not yet been released) should improve the situation:

- #6209

**Comment by JimBacon** [comment]
> I use `ddev stop --unlist <projectname>` regularly, but you can just edit ~/.ddev/global_config.yaml to remove items you don't want.

The file I had to edit was `~/.ddev/project_list.yaml`. I had two projects referencing the same folder. As soon as I cleaned that up it worked fine with a project having a different name from folder name.

**Comment by rfay** [comment]
`ddev delete` and `ddev stop --unlist` have been cranky about that situation, but will be better in next release. Doesn't seem to be related to the topic of this issue. I hope you'll try it out.

**Comment by JimBacon** [comment]
I'm a complete newb to ddev, didn't read the docs, made a mess, googled my error, ended up here, and solved my problem.
I commented to 

- help anyone else towards a solution by pointing at a different file to edit from the one suggested,
- reaffirm that there is no issue with a mismatch in project name and folder name.

Gratitude to the developers. Trying with intereset for some Drupal module development.

**Comment by rfay** [comment]
@nickchomey 

* [delete](https://ddev.readthedocs.io/en/stable/users/usage/commands/#delete) destroys the database and removes the registration with DDEV
* [stop --unlist](https://ddev.readthedocs.io/en/stable/users/usage/commands/#stop) only removes the registration with DDEV, does nothing destructive. (A `ddev start` in this directory or another one brings it right back)

If you see how to describe better in https://ddev.readthedocs.io/en/stable/users/usage/commands/ please click the pencil in the upper right and propose something, thanks!
