### ISSUE TITLE
https://ddev.readthedocs.io/en/latest/users/cli-usage/#snapshotting-and-restoring-a-database is outdated

### ISSUE THREAD

**Issue by zotornit** [drud/ddev#2846]
Looks like whole snapshot section is outdated. Since `restore-snapshot` is now used. 

DDEV version 1.16.7

**Comment by rfay** [comment]
Hi @zotornit - thanks so much for reporting an issue!

You're looking at the "latest" docs, which refer to the upcoming v1.17. The "stable" docs are at https://ddev.readthedocs.io/en/stable/users/cli-usage/#snapshotting-and-restoring-a-database and refer to the v1.16 version you're using.

Please take a look at the stable docs... but I'd love to have you try out the lovely new snapshot features in v1.17 and check out the docs for them (and make suggestions)

Also note that you can provide a PR for docs issues really easily by just clicking the "edit on github" link on every page. 

Closing, but happy to continue the conversation here or elsewhere.
