### ISSUE TITLE
Update Windows Signing Certificate

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2856]
**Describe the bug**

Our Windows signing certificate expires May 21, 2021.

We should update it.

**Comment by rfay** [comment]
The Windows code signing certificate was obtained from Digicert, and can be renewed there. 

It needs a credit card.
Amazingly they want $1422 for a 3-year cert.

**Comment by rfay** [comment]
It looks like they're vastly cheaper other places:
* $207 https://codesigningstore.com/microsoft-authenticode-signing?gclid=Cj0KCQiAs5eCBhCBARIsAEhk4r6X_QGW-BX-GjTCnwpcHHxZw_qhJAbZCdfi9Tw0ZeyRmAwfM7qURbAaAk_2EALw_wcB
* Comodo about the same, https://comodosslstore.com/code-signing
* Sectigo about the same https://sectigostore.com/code-signing/sectigo-code-signing-certificate
* Globalsign more expensive, but nowhere near digicert, https://shop.globalsign.com/en/code-signing

Price comparison here: https://www.sslshopper.com/cheap-code-signing-certificates.html

I wish we could just go with digicert and not rock the boat, but the digicert price is just way too much given the competitive landscape.

**Comment by rfay** [comment]
Some of the pricing difference is hidden in those comparisons. There are "regular" codesigning certs and "extended validation" certs.  So for example, Comodo has [extended validation for $266/year](https://codesigningstore.com/code-signing/comodo-ev-code-signing?gclid=Cj0KCQiAs5eCBhCBARIsAEhk4r6zzcILl41dNubBM68WUr0Y3VtetLEVfPUe0EcZr_9JONrfm1SijeEaAvIfEALw_wcB), far cheaper than Digicert, but more than the lowball numbers

**Comment by rfay** [comment]
SSL.com has [EV for 3 years for $747](https://www.ssl.com/certificates/ev-code-signing/buy/)

EV is probably best for us, since it assures instant trust.

**Comment by cyberswat** [comment]
We've passed the validation steps necessary to have this certificate issued. Last step is receiving the certificate through physical mail. Will update when I have additional information.

**Comment by rfay** [comment]
This will have to wait for the next release cycle, although it doesn't have to wait until v1.18 is fully released. Due to heroic efforts by @cyberswat and others, we got an EV Authenticode signing certificate, but that's a lot more trouble than I knew.  We now have to sign on a physical windows machine, so will need a github self-hosted runner or buildkite machine for this, and the password will have to be manually added. 

Some notes copied from notion note:

There are binaries of various ages scattered around sectigo's site, but they're generally old. Better and newer from globalsign at [https://support.globalsign.com/ssl/ssl-certificates-installation/safenet-drivers](https://support.globalsign.com/ssl/ssl-certificates-installation/safenet-drivers)

[Globalsign.com](http://globalsign.com) has the best faqs and examples, and even a video showing how to sign using the thing. [https://support.globalsign.com/code-signing/ev-code-signing-windows-7-and-8](https://support.globalsign.com/code-signing/ev-code-signing-windows-7-and-8)

The password which grants access to the key is in 1password, search for cert

It's currently set up (advanced settings) to allow batch processing, meaning you only have to provide the password once. 

You have to get the Windows 10 SDK and install it, but you only need the signing tools. Then the signtool.exe needs to be in path. I set this up on rfay-win10pro-1

Then install [https://www.globalsign.com/en/safenet-drivers/USB/10.8/GlobalSign-Safenet-Authentication-Tools-Windows-x64-10.8-R2.zip](https://www.globalsign.com/en/safenet-drivers/USB/10.8/GlobalSign-Safenet-Authentication-Tools-Windows-x64-10.8-R2.zip) which seemed to work pretty well. It shows the keyfob when installed. 

`signtool sign /a /tr [http://timestamp.globalsign.com/?signature=sha2](http://timestamp.globalsign.com/?signature=sha2) /td SHA256 c:/path/to/your/file.exe`

It pops up the notification for the password, and you use the password in 1password.

**Comment by rfay** [comment]
This is complete.
