### ISSUE TITLE
Unable to use default networks alongside ddev

### ISSUE THREAD

**Issue by saenglert** [drud/ddev#2857]
**Describe the bug**
During its first run ddev was unable to create its default network and gave the following error:
```
Failed to ensure docker network ddev_default: API error (404): could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
```
I was able to circumvent this by deleting all other networks which were implicitly created by my docker-compose files.

When trying to start up other projects after stopping my ddev project docker-compose gives the following error for all services defined in my docker-compose file:
```
ERROR: for mysql  Cannot start service mysql: b'network 540eb4a6cdd88e71e13d90e9ab8ed6a47efb9f7da7bf7412cdc410894760a59d not found'
```
Where `540eb4a6cdd88e71e13d90e9ab8ed6a47efb9f7da7bf7412cdc410894760a59d` is the network created for this docker-compose file. Explicitly added a network to my docker-compose file solves the problem.

I
**To Reproduce**
Steps to reproduce the behaviour:

1. Install ddev
2. Follow TYPO3 quick start guide
3. Use `ddev start`

**Expected behaviour**
ddev creates a network alongside exisitng ones.

**Version and configuration information (please complete the following information):**

- Windows 10
- Docker Desktop version 2.1.0.5
- ddev version v1.16.7
- config.yaml contents for the misbehaving project
```
name: ddev-test-typo3
type: typo3
docroot: public
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
mysql_version: ""
provider: default
use_dns_when_possible: true
composer_version: ""
```
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?
None present

**Additional context**
While the fix with an explicit network is simple enough I don't think ddev should interfere with existing setups.

**Comment by rfay** [comment]
Hi @saenglert - I see you're using a very old version of Docker. I imagine you've hit some kind of docker bug, but it's not easy to help if you aren't using a current version.  In debugging this, you may want to do a docker factory reset at some point, but beware that you will lose all docker volumes (meaning for ddev all databases), so you'll want to have backups via either `ddev snapshot` or `ddev export-db`. 

I see  quite a number of web-search hits on this although nobody's ever reported it related to ddev before:

https://www.google.com/search?q=docker+could+not+find+an+available%2C+non-overlapping+IPv4+address+pool&oq=docker+could+not+find+an+available%2C+non-overlapping+IPv4+address+pool&aqs=chrome..69i57j0.1157j0j7&sourceid=chrome&ie=UTF-8

**Comment by rfay** [comment]
FYI there is only *one* default network, not many. Happy to follow up with you on this, but this will be closed in a day or two if no response received.  Not that we can't continue the conversation here or elsewhere.

**Comment by saenglert** [comment]
As this is most likely a configuration error on my end I'll close the issue and post further questions in the ddev channel on the TYPO3 slack.

Thanks for your time!

**Comment by finex** [comment]
Hi, I'm experiencing the same problem using the latest Docker/DDev release: after adding a lot of ddev project (mostly Drupal) I've started to experiencing this issue. The following article give a good explanation: [https://straz.to/2021-09-08-docker-address-pools/]. This means that the default settings allow max 31 projects. 

Just change the `/etc/docker/daemon.json` file adding the `default-address-pools` settings increasing the `172.17.0.0/12` network size from `16` to `24`.
```json
{
  ...
  "default-address-pools" : [
    {
      "base" : "172.17.0.0/12",
      "size" : 24
    },
    {
      "base" : "192.168.0.0/16",
      "size" : 24
    }
  ]
}
```

**Comment by riconeitzel** [comment]
I just stumbled upon this issue … I also noticed "could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network" since a few weeks now. I only had 4 projects running and still ran into this issue.

This didn't happen back then. Perhaps it's worth thinking about the issue again. @rfay Should I create a new ticket?

**Comment by rfay** [comment]
I don't think this is anything DDEV can help with, it's a docker issue @riconeitzel - have you already done the suggested `docker network prune`? Does `docker network ls` show you lots of things?

**Comment by rfay** [comment]
It would be interesting to see your `docker network ls` when this happens.

Is there anything unusual about your workflow? Do you `ddev stop` when not using a project? When this happens, do you have lots of things in `ddev list` ?

**Comment by sparkalow** [comment]
Chiming in to say, I ran into this.  I used docker compose  for local projects prior to discovering DDEV.  I started using DDEV with an existing project count of around ~30  including my only DDEV setup.  Then I had to create another project outside of DDEV. That created an additional network and bumped me past the "32" limit. When I came back to the DDEV project days later I got the `Failed to ensure docker network ddev_default`. 

Spent an hour and found this thread and after realizing the issue, I simply deleted a no longer needed docker project and network and things are working temporarily until I can practice better docker hygiene.

It would be handy if DDEV output some helpful info about this along with the error message. A note like "This is potentially a Docker issue with network addressing..." would have saved me sometime and made it clear this was not a DDEV issue.

**Comment by rfay** [comment]
Thanks for the good idea. I'm not entirely sure DDEV can know enough to fix this up and give a better message. And docker providers may have different responses, etc. @sparkalow was this on Linux or what OS and Docker Provider?

**Comment by sparkalow** [comment]
@rfay  This was on OSX, Docker Desktop.

macOS Ventura 13.0.1
Docker platform: docker-desktop
docker-compose: v2.15.1
Docker version: 24.0.2

Concerning improving the error message... I see what you mean with a mix of providers. Perhaps a link to a webpage with more detail than is appropriate on the CLI.  At a minimum I think something that shifted blame from DDEV to the Docker provider would be helpful.  At first I was cursing DDEV until I researched the issue :)

**Comment by rfay** [comment]
Thanks, it's not relevant I don't think, but why are you running out-of-date Ventura and out-of-date Docker Desktop? For things like this and your careful troubleshooting it will be important to at least be on current versions of things. (Note that your system version of docker-compose is irrelevant because DDEV provides its own, as you should see with `ddev version`. )

**Comment by sparkalow** [comment]
@rfay I have other software packages preventing me from updating the OS. Then laziness and fear of breaking changes  stops the rest.   I will say this situation is temporary however and DDEV will most likely be part of our solution going forward.
