### ISSUE TITLE
GetContainerUIDGid() requires $USER to be set and otherwise panics

### ISSUE THREAD

**Issue by karlosb** [drud/ddev#2860]
**Describe the bug**
'ddev start ' is throwing an error when using in VSCode integrated Terminal pane editor.

**To Reproduce**

1. open VSCode
2. Click on terminal pane.
3. cd into local site DDEV directory
4. type ‘ddev start’

**Expected behavior**
Should start up current DDEV site.

**Version and configuration information (please complete the following information):**

- MacOS11.2.3 (Big Sur)
- Docker 3.1.0
- ddev version v1.17.0-alpha7

**Additional context**
- ‘ddev start’ **works** on MacOS iTerm & default Terminal App.
- Just in VSCode integrated terminal window - it throws an error.
- Please note: It ** was ** working up until yesterday (an update to VSCode App /VSCode Extension or DDEV must of broken the funcitonality of the command).

The error the VSCode (Terminal Pane) produces is:

> ddev start  
>  
> Starting define... 
> PANI[0000] CheckErr(): ERROR:user: Current requires cgo or $USER set in environment 
> panic: (*logrus.Entry) 0xc00020f3b0
> 
> goroutine 1 [running]:
> github.com/sirupsen/logrus.Entry.log(0xc000148000, 0xc00022c900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
>         /workdir/vendor/github.com/sirupsen/logrus/entry.go:239 +0x2ea
> github.com/sirupsen/logrus.(*Entry).Log(0xc00020f340, 0xc000000000, 0xc0002ad668, 0x2, 0x2)
>         /workdir/vendor/github.com/sirupsen/logrus/entry.go:268 +0xf0
> github.com/sirupsen/logrus.(*Logger).Log(0xc000148000, 0x0, 0xc0002ad668, 0x2, 0x2)
>         /workdir/vendor/github.com/sirupsen/logrus/logger.go:192 +0x7e
> github.com/sirupsen/logrus.(*Logger).Panic(...)
>         /workdir/vendor/github.com/sirupsen/logrus/logger.go:233
> github.com/sirupsen/logrus.Panic(...)
>         /workdir/vendor/github.com/sirupsen/logrus/exported.go:129
> github.com/drud/ddev/pkg/util.CheckErr(...)
>         /workdir/pkg/util/errcheck.go:15
> github.com/drud/ddev/pkg/util.GetContainerUIDGid(0xc0002ad6c8, 0x104d82c, 0x40, 0x16274c0, 0x1075f01, 0xc000173b00)
>         /workdir/pkg/util/utils.go:119 +0xae
> github.com/drud/ddev/pkg/ddevapp.(*DdevApp).DockerEnv(0xc00026fb80)
>         /workdir/pkg/ddevapp/ddevapp.go:1306 +0x37
> github.com/drud/ddev/pkg/ddevapp.(*DdevApp).Start(0xc00026fb80, 0x1700694, 0xe)
>         /workdir/pkg/ddevapp/ddevapp.go:793 +0x45
> github.com/drud/ddev/cmd/ddev/cmd.glob..func37(0x1b4d040, 0x1b87890, 0x0, 0x0)
>         /workdir/cmd/ddev/cmd/start.go:53 +0x213
> github.com/spf13/cobra.(*Command).execute(0x1b4d040, 0x1b87890, 0x0, 0x0, 0x1b4d040, 0x1b87890)
>         /workdir/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
> github.com/spf13/cobra.(*Command).ExecuteC(0x1b4c320, 0x1f5, 0x0, 0x0)
>         /workdir/vendor/github.com/spf13/cobra/command.go:958 +0x375
> github.com/spf13/cobra.(*Command).Execute(...)
>         /workdir/vendor/github.com/spf13/cobra/command.go:895
> github.com/drud/ddev/cmd/ddev/cmd.Execute()
>         /workdir/cmd/ddev/cmd/root.go:153 +0x3c
> main.main()
>         /workdir/cmd/ddev/main.go:21 +0xd9
>  ✘ ✝  Sites/Define-Creative/local   master  ddev version
> DDEV-Local version      v1.17.0-alpha7                                           
> db                      drud/ddev-dbserver-mariadb-10.3:20210213_db_image_no_sudo
> dba                     phpmyadmin:5                                             
> ddev-ssh-agent          drud/ddev-ssh-agent:20210217_ddev_ssh_agent_chown        
> docker                  20.10.2                                                  
> docker-compose          1.27.4                                                   
> os                      darwin                                                   
> router                  drud/ddev-router:20210106_nginx_default_server           
> web                     drud/ddev-webserver:20210226_heddn_assert_enable          
>  ✝  Sites/Define-Creative/local   master  ddev launch 
> PANI[0000] CheckErr(): ERROR:user: Current requires cgo or $USER set in environment 
> panic: (*logrus.Entry) 0xc00022c070
> 
> goroutine 1 [running]:
> github.com/sirupsen/logrus.Entry.log(0xc000122000, 0xc000101f80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
>         /workdir/vendor/github.com/sirupsen/logrus/entry.go:239 +0x2ea
> github.com/sirupsen/logrus.(*Entry).Log(0xc00022c000, 0xc000000000, 0xc000355940, 0x2, 0x2)
>         /workdir/vendor/github.com/sirupsen/logrus/entry.go:268 +0xf0
> github.com/sirupsen/logrus.(*Logger).Log(0xc000122000, 0x0, 0xc000355940, 0x2, 0x2)
>         /workdir/vendor/github.com/sirupsen/logrus/logger.go:192 +0x7e
> github.com/sirupsen/logrus.(*Logger).Panic(...)
>         /workdir/vendor/github.com/sirupsen/logrus/logger.go:233
> github.com/sirupsen/logrus.Panic(...)
>         /workdir/vendor/github.com/sirupsen/logrus/exported.go:129
> github.com/drud/ddev/pkg/util.CheckErr(...)
>         /workdir/pkg/util/errcheck.go:15
> github.com/drud/ddev/pkg/util.GetContainerUIDGid(0xc000355a90, 0xc000355be8, 0xc000355b50, 0xc000355c60, 0x1522790, 0xc000355af0)
>         /workdir/pkg/util/utils.go:119 +0xae
> github.com/drud/ddev/pkg/ddevapp.(*DdevApp).DockerEnv(0xc00014db80)
>         /workdir/pkg/ddevapp/ddevapp.go:1306 +0x37
> github.com/drud/ddev/cmd/ddev/cmd.makeHostCmd.func1(0xc00024e580, 0x1b87890, 0x0, 0x0)
>         /workdir/cmd/ddev/cmd/commands.go:223 +0x105
> github.com/spf13/cobra.(*Command).execute(0xc00024e580, 0x1b87890, 0x0, 0x0, 0xc00024e580, 0x1b87890)
>         /workdir/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
> github.com/spf13/cobra.(*Command).ExecuteC(0x1b4c320, 0x1f5, 0x0, 0x0)
>         /workdir/vendor/github.com/spf13/cobra/command.go:958 +0x375
> github.com/spf13/cobra.(*Command).Execute(...)
>         /workdir/vendor/github.com/spf13/cobra/command.go:895
> github.com/drud/ddev/cmd/ddev/cmd.Execute()
>         /workdir/cmd/ddev/cmd/root.go:153 +0x3c
> main.main()
>         /workdir/cmd/ddev/main.go:21 +0xd9
>  ✘ ✝  Sites/Define-Creative/local   master  ddev config
> You are reconfiguring the project at /Users/karlbowers/Sites/Define-Creative/local.
> The existing configuration will be updated and replaced.
> Project name (define): 
> 
> The docroot is the directory from which your site is served.
> This is a relative path from your project root at /Users/karlbowers/Sites/Define-Creative/local
> You may leave this value blank if your site files are in the project root
> Docroot Location (current directory): 
> Found a php codebase at /Users/karlbowers/Sites/Define-Creative/local.
> Project Type [backdrop, drupal6, drupal7, drupal8, drupal9, laravel, magento, magento2, php, shopware6, typo3, wordpress] (php): php
> Project type has no settings paths configured, so not creating settings file.
> Configuration complete. You may now run 'ddev start'.
> 
>  ✝  Sites/Define-Creative/local   master  
>  ✝  Sites/Define-Creative/local   master  ddev start 
> Starting define... 
> PANI[0000] CheckErr(): ERROR:user: Current requires cgo or $USER set in environment 
> panic: (*logrus.Entry) 0xc0000ec310
> 
> goroutine 1 [running]:
> github.com/sirupsen/logrus.Entry.log(0xc00011c000, 0xc00031dc20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
>         /workdir/vendor/github.com/sirupsen/logrus/entry.go:239 +0x2ea
> github.com/sirupsen/logrus.(*Entry).Log(0xc0000ec2a0, 0xc000000000, 0xc0002c1668, 0x2, 0x2)
>         /workdir/vendor/github.com/sirupsen/logrus/entry.go:268 +0xf0
> github.com/sirupsen/logrus.(*Logger).Log(0xc00011c000, 0x0, 0xc0002c1668, 0x2, 0x2)
>         /workdir/vendor/github.com/sirupsen/logrus/logger.go:192 +0x7e
> github.com/sirupsen/logrus.(*Logger).Panic(...)
>         /workdir/vendor/github.com/sirupsen/logrus/logger.go:233
> github.com/sirupsen/logrus.Panic(...)
>         /workdir/vendor/github.com/sirupsen/logrus/exported.go:129
> github.com/drud/ddev/pkg/util.CheckErr(...)
>         /workdir/pkg/util/errcheck.go:15
> github.com/drud/ddev/pkg/util.GetContainerUIDGid(0xc0002c16c8, 0x104d82c, 0x40, 0x16274c0, 0x1075f01, 0xc000029940)
>         /workdir/pkg/util/utils.go:119 +0xae
> github.com/drud/ddev/pkg/ddevapp.(*DdevApp).DockerEnv(0xc000136000)
>         /workdir/pkg/ddevapp/ddevapp.go:1306 +0x37
> github.com/drud/ddev/pkg/ddevapp.(*DdevApp).Start(0xc000136000, 0x1700694, 0xe)
>         /workdir/pkg/ddevapp/ddevapp.go:793 +0x45
> github.com/drud/ddev/cmd/ddev/cmd.glob..func37(0x1b4d040, 0x1b87890, 0x0, 0x0)
>         /workdir/cmd/ddev/cmd/start.go:53 +0x213
> github.com/spf13/cobra.(*Command).execute(0x1b4d040, 0x1b87890, 0x0, 0x0, 0x1b4d040, 0x1b87890)
>         /workdir/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
> github.com/spf13/cobra.(*Command).ExecuteC(0x1b4c320, 0x1f5, 0x0, 0x0)
>         /workdir/vendor/github.com/spf13/cobra/command.go:958 +0x375
> github.com/spf13/cobra.(*Command).Execute(...)
>         /workdir/vendor/github.com/spf13/cobra/command.go:895
> github.com/drud/ddev/cmd/ddev/cmd.Execute()
>         /workdir/cmd/ddev/cmd/root.go:153 +0x3c
> main.main()
>         /workdir/cmd/ddev/main.go:21 +0xd9

**Comment by rfay** [comment]
That's a pretty ugly error, but the first line tells it all. Apparently in your environment $USER isn't set. It should be set in any shell environment, but you can probably `export USER=<your-user-name>` to fix this.

It works fine in my vscode on macOS. I think if you're missing $USER there may be other problems that will follow you, like $HOME. 

<img width="702" alt="Cursor_and_Welcome_—_d9" src="https://user-images.githubusercontent.com/112444/110481079-6ad0e900-80a4-11eb-9a93-f26dc18f247c.png">

**Comment by rfay** [comment]
In your .bashrc or .zshrc or the init for whatever shell you use, add `export USER=your-username`

Unless your terminal is really screwy, that will do it. But your vscode/terminal is really screwy.

**Comment by rfay** [comment]
This can be recreated anywhere with `unset USER; ddev start`. It might as well be fixed, even though this is the first report of it.

**Comment by karlosb** [comment]
Hi @rfay,



I've added export USER=username (my actual username in here) to both .bashrc & .zshrc 

I use Oh My ZSH to I'm assuming it's .zshrc that the (iiTerm & VSCode) terminal is using.

And in VScode Terminal I've ran:
unset USER; ddev start

And I still get the issue of the above error.

Also in VSCode I've ran:
echo $USER (the is no USER name displayed)
then I've ran:
unset USER (still no USER name displayed)

In iTerm:
echo $USER (I get my actual correct username) ... so definately VSCode screwing up!!!

**Comment by karlosb** [comment]
Ok, so I think I've resolved this issue and at it appears top be unrelated to DDEV.

When installing the above mentioned FIG extension it actually ' unchecks ' the ‘ terminal.integrated.inheritEnv ‘setting in VSCode Integrated terminal settings.

![image](https://user-images.githubusercontent.com/7140268/110611837-806b0f00-8187-11eb-9f3c-6aea870fc1e6.png)

I know this is now unrelated to DDEV functionality, but still useful for anyone experiencing the VSCode USER setting issue.

Kind Regards
Karl

**Comment by karlosb** [comment]
Hi Randy,

Not a problem, Many thanks for the feedback.

Actually (after restarting my MacBookPro):
FIG has stopped working all together (in both iTerm and VSCode).
And ‘ddev start’ is erroring again (with or without ‘ terminal.integrated.inheritEnv ‘ checked in VSCode Integrated Terminal settings).
So still have the issue. 👀🙄🤦🏻‍♂️

I’ve got a Zoom call @6pm / 10am PT with the FIG developers so hopefully I’ll get some more feedback from them.

Any further suggestion are welcome if you have them 😀👍

Kind Regards

Karl


Karl Bowers
MD | Web Consultant / Developer

Expression 37 Ltd.
ExpressionEngine & Craft CMS Specialist

e:		***@***.***
m:		+44 (0) 7771 656606
t:		+44 (0) 1924 501813
w:		https://www.expression37.co.uk
skype: 	karlosb1972
linkedin: 	http://www.linkedin.com/in/karlbowers72

**Comment by rfay** [comment]
You probably just need HOME and USER environment variables defined.

**Comment by karlosb** [comment]
Hi Randy,

When I thought it was just the Terminal Pref mentioned, I commented out the suggested ‘ export USER=karlbowers ‘ in both .zshrc and .bashrc respectively.

I have now uncommented export USER=karlbowers in both files and restarted the mac several times and ‘ddev start’ now appears to be working along with FIG itself.

I assume this is what you meant by setting USER and HOME variables?

I’ll see how it goes🤞😂

Kind Regards

Karl


Karl Bowers
MD | Web Consultant / Developer

Expression 37 Ltd.
ExpressionEngine & Craft CMS Specialist

e:		***@***.***
m:		+44 (0) 7771 656606
t:		+44 (0) 1924 501813
w:		https://www.expression37.co.uk
skype: 	karlosb1972
linkedin: 	http://www.linkedin.com/in/karlbowers72

**Comment by rfay** [comment]
You and you alone are in charge of what's in your .zshrc. DDEV does not depend on it. You need to maintain it and manage it as you see fit.  There are lots of internet resources on this.

**Comment by karlosb** [comment]
Ok, understood 👍
