### ISSUE TITLE
Provide option to specify extraction dir for import-files and import-db

### ISSUE THREAD

**Issue by tannerjfco** [drud/ddev#287]
## What happened (or feature request):
Feature Request
We have the commands import-files and import-db, which allow users to import a database or uploaded file assets by specifying a path to import. The path provided can be an archive. If an archive is provided for import-db, it must have a sql dump at the root of the archive. If an archive is provided for import-files, the entire contents of the archive are extracted as the contents of the uploaded files directory for the site. This means that in order to provide an archive, the archive must be structured to provide what we're looking for at the root of the archive. It's unlikely that many users have archives perfectly formatted for use with the import commands as they currently stand. The current approach also doesn't allow for using full site archives such as drush archives, that provide the sql dump, code base, and file assets in a single archive.

## What you expected to happen:
We should provide the option for users to specify a path in an archive to extract from. This would allow users to provide assets from an archive without having to ensure they provide an archive of specific format. @rfay's recent work on archive extraction already provides the underlying functionality necessary to facilitate this, so we would just need to determine what the interfaces should be for the end user, and implement them.

The import commands can be used with flags or by answering prompts. We would need to determine what flag name to introduce, and what prompt to provide.

I was thinking the flag could be `--extractdir` or `--extractpath`, but I'm not set on either, and open to alternatives.

For the prompt, we could detect if the user provided an archive, and provide a second prompt:

```
tannerjfco Desktop/wptest1 » ddev import-db
Provide the path to the database you wish to import.
Import path:
~/Downloads/db.tar.gz

You provided an archive. Do you want to extract from a specific path in your archive? You may leave this blank if you wish to use the full archive contents:
sites/default/files
```

I'm open to alternatives for the prompt language as well. 

## Related source links or issues:

**Comment by rickmanelius** [comment]
Nitpick. Is it fair to say that it's not just the path to the database file, but also specifying within that which file to use? It's possible (think of some clients we've had in the past) where they have stored multiple database backups in the docroot and having to just guess might be problematic.

What would you suggest as a test for this?

This is close to actionable. Tagging v0.8.

**Comment by tannerjfco** [comment]
I'm pretty sure the functionality should allow for defining a specific file to extract, as well as directories, as desired. 

The extraction functionality already has test coverage for providing a path to filter, so additional test coverage will be to test providing a path to filter at the platform package level.
