### ISSUE TITLE
zend.assertions is set to -1, only Drupal 9 needs the setting to be 1

### ISSUE THREAD

**Issue by drupal-daffie** [drud/ddev#2878]
Drupal 9 uses the PHP function assert() in a lot of places, like in caching (core/lib/Drupal/Core/Cache/Cache.php). In caching it is used to make sure that no illegal data is inserted in the database. Therefore it is necessary for Drupal 9 sites that the PHP variable zend.assertions is set to 1 and not to -1 as it is now. To verify that the problem is solved, run the tests in the namespace Drupal\KernelTests\Core\Cache.

I am running DDEV on ubuntu 20.04. My DDEV version is v1.16.7 and I have also the extra service https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/mongodb installed. I have a custom php.ini file with the following content: 
`[PHP]
zend.assertions = 1
apc.enable_cli = 1`

By the way the test core/tests/Drupal/KernelTests/Core/Cache/ApcuBackendTest.php fails without the PHP variable apc.enable_cli is set to 1.

**Comment by rfay** [comment]
Hi @drupal-daffie - This was changed in v1.17.0-alpha7, would love to have you try it out, https://github.com/drud/ddev/releases/tag/v1.17.0-alpha7

Closing for now, but happy to continue the conversation here or elsewhere.

**Comment by drupal-daffie** [comment]
@rfay: Thank you for your response and happy to hear that it is fixed in v1.17. :)
