### ISSUE TITLE
Namespace container names for ddev

### ISSUE THREAD

**Issue by rfay** [drud/ddev#288]
## What happened (or feature request):

I was testing bootstrap/drud dev in https://github.com/drud/bootstrap/pull/285 and noted that it all broke down because of the use of the container name "nginx-proxy", which drud dev also uses.

Since we're using a name for that container, let's namespace the nbame, like ddev-nginx-proxy, so that we can co-exist with at least drud.

## What you expected to happen:

drud and ddev should coexist.

## How to reproduce it (as minimally and precisely as possible):

Try a drud add if you have worked with ddev.

## Related source links or issues:

**Comment by tannerjfco** [comment]
I have been thinking we should completely rename "nginx-proxy" to "ddev-router". It better describes the image's purpose, and we've strayed a fair bit from the upstream nginx-proxy it was originally forked from.

I would also be in favor of replacing the local- prefix on site containers with ddev-.

**Comment by rfay** [comment]
Totally agreed @tannerjfco

**Comment by rickmanelius** [comment]
No objections / sounds good. Sounds like a good cleanup item for v0.8.
