### ISSUE TITLE
I want to use `ddev import-files` even though I use project type "php"

### ISSUE THREAD

**Issue by RobertLang** [drud/ddev#2880]
**Is your feature request related to a problem? Please describe.**
When I use the project type **php** I'm not able to use the command `ddev import-files` to copy files to a specific folder location.
This is annoying because `ddev pull <provider>` relies on the import-files command to copy pulled files to it's destination folder.

**Describe the solution you'd like**
I would expect the `ddev import-files` command to work if the config option **upload_dir** is set in `.ddev/config.yaml`.

**Describe alternatives you've considered**
I've considered to ignore the error message when pulling files but there is no real reason why import-files needs more information than it's destination folder.

**Comment by rfay** [comment]
Probably `ddev import-files` should just check for upload_dir, rather than checking for project type. If upload_dir exists, it can proceed.  Shouldn't be hard.

Related: https://github.com/drud/ddev/issues/2440

**Comment by rfay** [comment]
@RobertLang would love it if you could test and review https://github.com/drud/ddev/pull/3374
