### ISSUE TITLE
Need to append port to URL with v1.17.0-alpha8

### ISSUE THREAD

**Issue by thomashempel** [drud/ddev#2887]
After upgrading to v1.17.0-alpha8 (from alpha7) - the web container is only reachable when I append the random port to URL. Otherwise I will get a 500 from nginx.

**To Reproduce**
start ddev

**Expected behavior**
Be able to access the web container via https://[projectname].ddev.site

**Screenshots**
<img width="629" alt="Screenshot 2021-03-23 at 07 51 20" src="https://user-images.githubusercontent.com/354084/112105778-1867f000-8bad-11eb-9c64-30fdf59eb1ba.png">
<img width="540" alt="Screenshot 2021-03-23 at 07 51 27" src="https://user-images.githubusercontent.com/354084/112105785-19008680-8bad-11eb-9279-e1cb0c3bfa17.png">

**Version and configuration information (please complete the following information):**

Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64
DDEV-Local version	v1.17.0-alpha8
db                	drud/ddev-dbserver-mariadb-10.3:20210213_db_image_no_sudo
dba               	phpmyadmin:5
ddev-ssh-agent    	drud/ddev-ssh-agent:20210217_ddev_ssh_agent_chown
docker            	20.10.5
docker-compose    	1.28.5
os                	darwin
router            	drud/ddev-router:20210106_nginx_default_server
web               	drud/ddev-webserver:20210308_push

**Additional information**

This is a default TYPO3 setup with one addition. I have a docker-compose.dev.yaml where I set a an extra environment variable.

```
version: '3.6'

services:
  web:
    environment:
      - TYPO3_CONTEXT=Development
``` 

I'm happy to provide further information if necessary.

**Comment by thomashempel** [comment]
After rebooting and re-installing docker and ddev from scratch, I still have this issue. 

I also tried a few of my other ddev (TYPO3) projects, and they all show this behavior.

Is there any way to switch back to alpha7, so I can test if it is really a problem with ddev and not anything else?

**Comment by thomashempel** [comment]
Well, I just saw that you already opened an issue over at Docker... https://github.com/docker/for-mac/issues/5476

So I guess this can be closed than?

**Comment by rfay** [comment]
The [alpha8 release notes](https://github.com/drud/ddev/releases/tag/v1.17.0-alpha8) explain this and give the link to the working docker preview version.

**Comment by thomashempel** [comment]
Thanks! Must have not read carefully enough. Sorry for wasting your time. And thanks for ddev :-)
