### ISSUE TITLE
Cannot start service web: error while mounting volume, Permission denied (NFS not enabled)

### ISSUE THREAD

**Issue by najimk** [drud/ddev#2902]
Am trying to setup a ddev drupal 9 project but am failing at the command "ddev start"
the error i get is "cannot start service web" error while mounting volume

![Screenshot from 2021-03-27 18-36-34](https://user-images.githubusercontent.com/11871322/112725959-f3b4a500-8f2b-11eb-8bde-9fd4edce057e.png)
This is my first attempt at DDEV so bare with me if my explanation is not so clear

**Comment by rfay** [comment]
Hi @najimk - welcome!

The problem is that you have nfs_mount_enabled set, but you don't have NFS working at this point.

[NFS is a way to speed up performance](https://ddev.readthedocs.io/en/latest/users/performance/#using-nfs-to-mount-the-project-into-the-web-container), and it's great on macOS and native WIndows. 

You don't say what OS or environment you're on, so if you mention that it will help me. 

For now,  start learning without NFS, then you can add it on later. 

`ddev config --nfs-mount-enabled=false && ddev config global --nfs-mount-enabled=false`

Then `ddev start` and you should be OK

**Comment by rfay** [comment]
I added an FAQ about this to the docs in https://github.com/drud/ddev/pull/2894/commits/4d906d2472a267639fe709e4d4e2ba3799a8a02b

**Comment by najimk** [comment]
> Hi @najimk - welcome!
> 
> The problem is that you have nfs_mount_enabled set, but you don't have NFS working at this point.
> 
> [NFS is a way to speed up performance](https://ddev.readthedocs.io/en/latest/users/performance/#using-nfs-to-mount-the-project-into-the-web-container), and it's great on macOS and native WIndows.
> 
> You don't say what OS or environment you're on, so if you mention that it will help me.
> 
> For now, start learning without NFS, then you can add it on later.
> 
> `ddev config --nfs-mount-enabled=false && ddev config global --nfs-mount-enabled=false`
> 
> Then `ddev start` and you should be OK

Thank you @rfay , am running on ubuntu 20.04 LTS, meanwhile let me try the procedure you have advised me and see how that comes out

**Comment by rfay** [comment]
Yeah, you don't need NFS on Ubuntu at all, so just turn that off and you'll be fine.

**Comment by najimk** [comment]
> Yeah, you don't need NFS on Ubuntu at all, so just turn that off and you'll be fine.

Well this work, i was able to start the project properly but browser access returns 403 Forbidden

Project Information
-------------------
PHP version:      	7.3    
NFS mount enabled:	false  
Database type:    	mariadb
MariaDB version:  	10.3   

URLs
----
https://d9test.ddev.site
https://127.0.0.1:49156 
http://d9test.ddev.site 
http://127.0.0.1:49157

**Comment by najimk** [comment]
Mailhog and phpmyAdmin services for this container are working but when i try accessing HTTP and HTTPS resources https://d9test.ddev.site i get 403 forbidden

**Comment by rfay** [comment]
The most common reason for a 403 on the main site is that the docroot isn't set correctly. take a look at your .ddev/config.yaml and see what the docroot says. It needs to be relative path to where your index.php is. If you're doing d9 with a composer build, it should be "web" for a recommended-project.

For a quick painless D9 test you might try the Drupal 9 quickstart, https://ddev.readthedocs.io/en/latest/users/cli-usage/#drupal-9-quickstart

**Comment by najimk** [comment]
> The most common reason for a 403 on the main site is that the docroot isn't set correctly. take a look at your .ddev/config.yaml and see what the docroot says. It needs to be relative path to where your index.php is. If you're doing d9 with a composer build, it should be "web" for a recommended-project.
> 
> For a quick painless D9 test you might try the Drupal 9 quickstart, https://ddev.readthedocs.io/en/latest/users/cli-usage/#drupal-9-quickstart

Thank you @rfay, sure enough, there was a problem with the files inside docroot, the process of pulling files from the repository had not completed successfully.  I managed to solve the problem by re-running;

`ddev composer create "drupal/recommended-project"` once again. 

Now everything is working properly. `

**Comment by rfay** [comment]
Glad it's working for you!
