### ISSUE TITLE
env variables defined in global_config web_environment are superfluously html-encoded

### ISSUE THREAD

**Issue by rooflack** [drud/ddev#2908]
Hi DDEV, and thanks for this pretty amazing project!

I'm trying to set up a project with the Acquia provider.
I added the ACQUIA_API_KEY and ACQUIA_API_SECRET, but authentication kept failing.
After trying to echo the variables using `ddev exec, I found out that there was a plus sign within the API Secret which got encoded as an HTML entity (&#43;), thus causing an erroneous secret to be passed to the auth system.

I dug around a little bit and was able to confirm the following:
- The HTML encoding happens with all web_enrionment variables, not only with Acquia-specific ones,
- The encoding takes place very early in the startup process, and not in the Acquia subsystem, as the `.ddev/.ddev-docker-compose-base.yaml` file already contains the HTML entity.

Here's how to reproduce the behavior (tested in *v1.17.0-rc1*):
- Set up a project that involves a Web container.
- Add a random variable in the `web_environment` section of `global_config.yaml`, for instance `FOO=bar+baz`.
- Startup the project.
- Run `ddev exec echo \$FOO`: the output will be `bar&#43;baz`.
- Alternatively, run `ddev ssh` and then `env |grep FOO`: again, this will output `FOO=bar&#43;baz`.
- Look inside `.ddev/.ddev-docker-compose-base.yaml` and search for FOO: the &#43; entity will be there too.

I really know very little about Go and only skimmed through the code, but I suspect this is caused by the fact that the function `RenderComposeYAML` in `pkg/ddevapp/config.go` uses [`html/template`](https://golang.org/pkg/html/template/) to produce the docker-compose file: according to the offical doc, `html/template` automatically encodes certain characters thare are deemed "unsafe" (for HTML) depending on the context they are found in.
I am wondering why this specific package is used, instead of the more basic [`text/template`](https://golang.org/pkg/text/template/) which does not auto-encode anything. I don't know whether or not it would be reasonable to simply switch from `html/template` to `text/template`: again, I've barely looked at the code, so there may be side effects that I have not identified, and it might be a bit more complicated than that. (For instance, I saw that `sprig.HtmlFuncMap()` was loaded for parsing, but don't know what it's used for, as I haven't seen any specific functions in the corresponding `DDevComposeTemplate` in `template.go`.)

Thanks for reading, and for your great work on this tool.

**Comment by rooflack** [comment]
Wow! that was some pretty quick response :)
Glad to help.
Feel free to let me know if there's anything else I can do to help on this.

**Comment by rfay** [comment]
Very impressive that you could
* Describe the problem so well
* Diagnose it with a test case
* Suggest the correct fix

Thanks so much! 

Artifacts will shortly be in https://github.com/drud/ddev/runs/2227606687 if you'd be interested in taking it for a spin. Not sure what platform you're on, but `brew unlink ddev` and put this binary in your $PATH and you should be able to give it a test.

**Comment by rfay** [comment]
https://github.com/drud/ddev/releases/tag/v1.17.0-rc2 contains this fix @rooflack. Hope you can give it a spin for everything in it. Wow do I appreciate you finding this.

**Comment by rooflack** [comment]
Just upgraded to rc2 and tested. Everything looking good :) Thanks!!
