### ISSUE TITLE
Provide tool to output all info required from vscode-php-debug github issue template please

### ISSUE THREAD

**Issue by therobyouknow** [drud/ddev#2914]
**Is your feature request related to a problem? Please describe.**

I've decided to suggest this ticket after raising 2 issues:
- https://github.com/xdebug/vscode-php-debug/issues/532
- https://github.com/xdebug/vscode-php-debug/issues/539

On clicking: https://github.com/xdebug/vscode-php-debug/issues/new

I get asked for the following things from the template for the new issue:

> PHP version:
> Xdebug version:
> Adapter version:
> 
> Your launch.json:
> Xdebug php.ini config:
> 
> Xdebug logfile (from setting `xdebug.remote_log` in php.ini):
> Adapter logfile (from setting `"log": true` in launch.json):

My suggestion is for a ddev tool to generate the above automatically to paste into the new ticket.

**Describe the solution you'd like**

`ddev generate-diagnostics xdebug`

- this command ^ would generate the template

**Describe alternatives you've considered**

Manually doing it. Don't know where to look for adapter version and logfile.

**Additional context**

**Comment by rfay** [comment]
No response, so closing this. I hope that `ddev xdebug on && ddev exec php -i` was a good answer for you. Happy to continue the conversation here or elsewhere.
