### ISSUE TITLE
HTTP only mode

### ISSUE THREAD

**Issue by tommym9** [drud/ddev#2917]
**Is your feature request related to a problem? Please describe.**
I've got a bit of an edge case where an application can be deployed in HTTPS and HTTP. For this reason I'd like to be able to toggle on and off the SSL certificate for my local so that I can test what needs work in HTTP only mode

**Describe alternatives you've considered**
I could uninstall mkcert and re-deploy, but then I need to re-install for HTTPS and pretty much all my other projects use HTTPS

A massive edge case, but just in case this is an easy-ish one to implement.

**Comment by rfay** [comment]
Hi @tommym9 - Did you know that http is always there? It just doesn't show in `ddev start` for space reasons. You can use `ddev describe` to see all the URLs. Or just remove the 's' from the https URL.

**Comment by tommym9** [comment]
Hi @rfay

Thats great thanks!

Cheers

Tom
