### ISSUE TITLE
php-imagick module missing for php 7 on ddev v1.17.0

### ISSUE THREAD

**Issue by facine** [drud/ddev#2934]
php7.*-imagick module seems not to be properly installed in ddev v1.17.0; I assume this is a result of an upstream change with deb.sury.org.

This can be worked around with `webimage_extra_packages: [php7.4-imagick]` in the project .ddev/config.yaml (change the php version as needed)

**Comment by rfay** [comment]
It seems the upstream install setup must have changed.

You can use `webimage_extra_packages: [php7.4-imagick]` for now. 

We'll get this fixed up in a point release.

**Comment by wilburec** [comment]
> webimage_extra_packages: [php7.4-imagick]

For anybody finding this and needing a quick fix, just add the directive quoted above to the ddev.config.  Or add to your custom ddev.local.config file if you have one.  Run 'ddev restart' to implement that change.

**Comment by rfay** [comment]
@wilburec this has already been fixed in v1.17.1, so the easiest thing is to upgrade to ddev v1.17.1
