### ISSUE TITLE
Create DDEV project with no interaction

### ISSUE THREAD

**Issue by cjohansson** [drud/ddev#2938]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when setting up test-environments which take hours but are stopped at questions that require a interaction, like: `Would you like to continue? [Y/n]`
or
```
Warning from repo.magento.com: You haven't provided your Magento authentication keys. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html
    Authentication required (repo.magento.com):
```
We have planned on using DDEV-LOCAL for automatic tests and we need the setup-flow to be without interaction

**Describe the solution you'd like**
A --no-interaction or --quiet flag that automatically answers Yes to all Yes/No questions, like `ddev start --quiet`

**Describe alternatives you've considered**
Checked the terminal help but did not find such a solution

**Additional context**
For some reason DDEV can't read my composer credentials from file so that needs to be inserted using interaction as well. Would be nice if that could be solved without interaction as well.

**Comment by rfay** [comment]
In ddev v1 17, use `ddev start -y`

In any version of ddev, set the environment variable `DDEV_NO_INTERACTION=TRUE`

For composer credentials, put your auth.json in homeadditions. Docs suggest this in homeadditions section.

**Comment by cjohansson** [comment]
Ok great, I have tried adding auth.json in homeadditions but I can't get it to work, this is my script

```bash
mkdir -p .ddev/homeadditions/.composer
echo '{"http-basic": {"repo.magento.com": {"username": "asdasd","password": "asdasd"}}}' > .ddev/homeadditions/.composer/auth.json
echo '{"http-basic": {"repo.magento.com": {"username": "asdasd","password": "asdasd"}}}' > auth.json
```

but it doesn't work

**Comment by rfay** [comment]
The copying happens on `ddev start`. https://ddev.readthedocs.io/en/stable/users/extend/in-container-configuration/

**Comment by cjohansson** [comment]
Some interactivity is now solved but this remains:

```
$ mkdir ddev-magento2 && cd ddev-magento2
$ ddev config --project-type=magento2 --docroot=pub --create-docroot

Creating a new ddev project config in the current directory (/home/christian/Downloads/ddev-magento2) 
Once completed, your configuration will be written to /home/christian/Downloads/ddev-magento2/.ddev/config.yaml
 
Created docroot at /home/christian/Downloads/ddev-magento2/pub 
You have specified a project type of magento2 but no project of that type is found in /home/christian/Downloads/ddev-magento2/pub 
No /home/christian/Downloads/ddev-magento2/app/etc/env.php file exists, creating one 
Unable to create settings file '/home/christian/Downloads/ddev-magento2/app/etc/env.php': open /home/christian/Downloads/ddev-magento2/app/etc/env.php: no such file or directory 
Configuration complete. You may now run 'ddev start'. 

$ ddev-magento2 ➜ ddev start -y
$ ddev composer create --repository=https://repo.magento.com/ magento/project-community-edition

Starting ddev-magento2... 
Running   Command=ip address show dev docker0
Building db 
Building web 
Creating ddev-ddev-magento2-db ... done
Creating ddev-ddev-magento2-dba ... done
Creating ddev-ddev-magento2-web ... done
 
Recreating ddev-router ... done
 
No /home/christian/Downloads/ddev-magento2/app/etc/env.php file exists, creating one 
Successfully started ddev-magento2 
Project can be reached at https://ddev-magento2.ddev.site https://127.0.0.1:49176 
Warning: ALL EXISTING CONTENT of the project root (/home/christian/Downloads/ddev-magento2) will be deleted
Would you like to continue? [Y/n] (yes): 
```

The -y flag does not seem to work with `ddev composer` command?
Is there a way to get pass this?

**Comment by rfay** [comment]
`ddev composer create -y` - `ddev composer create` does have the -y argument. 

With any of these you can also `echo y | ddev something`

**Comment by cjohansson** [comment]
Thanks, everything works now :+1:

**Comment by rfay** [comment]
Yay!

**Comment by cjohansson** [comment]
Well there is one thing left, after I run this

```
mkdir -p .ddev/homeadditions/.composer
echo '{"http-basic": {"repo.magento.com": {"username": "abc","password": "123"}}}' > .ddev/homeadditions/.composer/auth.json

ddev start

echo "Started DDEV";

echo y | ddev composer create --repository=https://repo.magento.com/ magento/project-community-edition
```

Which works non-interactively, the scripts seems to restart after composer directory is moved and when I later run this:

```
ddev exec bin/magento sampledata:deploy
ddev exec bin/magento setup:upgrade
```

Composer credentials are gone again and I can't seem to get them back, have tried this:

```
mkdir -p .ddev/homeadditions/.composer
echo '{"http-basic": {"repo.magento.com": {"username": "abc","password": "123"}}}' > .ddev/homeadditions/.composer/auth.json
ddev exec bin/magento sampledata:deploy
ddev exec bin/magento setup:upgrade
```

but it doesn't work

**Comment by rfay** [comment]
Not completely sure I understand, but I think what you're saying is that you have to study what's happening to auth.json.

So go into the web container and see what's in ~/.composer and figure out what might have happened to it.

**Comment by cjohansson** [comment]
It seems like the `auth.json` file is moved to the wrong location after `ddev composer` is finished. After this part:

```
Executing composer command: composer create-project --repository=https://repo.magento.com/ magento/project-community-edition /var/www/html/.tmp_ddev_composer_create_avHvHP

Creating a "magento/project-community-edition" project at "./.tmp_ddev_composer_create_avHvHP"
Installing magento/project-community-edition (2.4.2)
  - Installing magento/project-community-edition (2.4.2): Extracting archive
Created project in /var/www/html/.tmp_ddev_composer_create_avHvHP
```

But I found a solution and it is:

```
echo '{"http-basic": {"repo.magento.com": {"username": "abc","password": "123"}}}' > auth.json
ddev exec bin/magento sampledata:deploy
ddev exec bin/magento setup:upgrade
```
