### ISSUE TITLE
Add default configuration files on upgrade

### ISSUE THREAD

**Issue by richlawson** [drud/ddev#2945]
**Is your feature request related to a problem? Please describe.**
After upgrading to 1.17.0, none of the default provider files for `ddev pull` were available. I created a new ddev project and manually copied them over.

**Describe the solution you'd like**
Ideally, default configuration files related to upgrades would be created automatically.

**Describe alternatives you've considered**
I used the manual method I described above.

**Comment by rfay** [comment]
If you just type `ddev` once or `ddev start` they all get populated.

**Comment by richlawson** [comment]
Thank you for that! I think I used `ddev restart`.
