### ISSUE TITLE
How to delete a project which does not exists

### ISSUE THREAD

**Issue by froemken** [drud/ddev#2947]
I can't add diagnostic here, as there are all projects listed with customer number.

➜ git:(master) ddev delete fork
Project 'customer' was found in configured directory /Users/froemken/htdocs/kunden/customer and it is already used by project 'fork'. If you have changed the name of the project, please "ddev stop --unlist fork" 
Failed to get project(s): could not find requested project fork, you may need to use "ddev start" to add it to the project catalog
➜  git:(master) ddev stop --unlist fork
Failed to get project(s): could not find requested project fork, you may need to use "ddev start" to add it to the project catalog

➜  5160001-drs-baukasten git:(master) ddev version
DDEV-Local version	v1.16.5                                
db                	drud/ddev-dbserver-mariadb-10.2:v1.16.0
dba               	phpmyadmin:5                           
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.16.0            
docker            	20.10.5                                
docker-compose    	1.28.5                                 
os                	darwin                                 
router            	drud/ddev-router:v1.16.2               
web               	drud/ddev-webserver:v1.16.3             

- Host computer OS and Version: macOS Big Sur
- Docker Desktop version if on macOS or Windows (from "About Docker Desktop"): 3.2.2 61853
- config.yaml contents for the misbehaving project: no access. Project does not exists

**Comment by rfay** [comment]
Hi @froemken - 

`ddev delete --omit-snapshot -y <projectname>` or (as it prompts you there) `ddev stop --unlist fork`

`ddev stop --unlist` will not delete the old database; `ddev delete` will.

But if none of these works, just edit the ~/.ddev/global_config.yaml to remove the offending lines.

**Comment by froemken** [comment]
Hello @rfay 

thank you for your help

```
➜  git:(master) ddev delete --omit-snapshot -y fork
Project 'customer' was found in configured directory /Users/froemken/htdocs/kunden/customer and it is already used by project 'fork'. If you have changed the name of the project, please "ddev stop --unlist fork" 
Failed to get project(s): could not find requested project fork, you may need to use "ddev start" to add it to the project catalog
➜  git:(master) ddev stop --unlist fork
Project 'customer' was found in configured directory /Users/froemken/htdocs/kunden/customer and it is already used by project 'fork'. If you have changed the name of the project, please "ddev stop --unlist fork" 
Failed to get project(s): could not find requested project fork, you may need to use "ddev start" to add it to the project catalog
```

I found following lines in global_config.yaml and removed them:
```
  fork:
    approot: ""
```

Empty approot?!?! Don't get it. Good by my disturbing two lines ;-)

Stefan
