### ISSUE TITLE
Unable to Start ddev project after updating docker version/Mac Big sur

### ISSUE THREAD

**Issue by naresh-qed42** [drud/ddev#2954]
**Error output while ddev start**

> Creating ddev-drupal-8.9.x-dba          ... done
> Creating ddev-drupal-8.9.x-web          ... error
> 
> ERROR: for ddev-drupal-8.9.x-web  Cannot start service web: error while mounting volume '/var/lib/docker/volumes/ddev-drupal-89x_nfsmount/_data': failed to mount local volume: mount :/System/Volumes/Data/Users/nareshbavaskar/ddev-projects/drupal-8.9.x:/var/lib/docker/volumes/ddev-drupal-89x_nfsmount/_data, data: addr=192.168.65.2,hard,nolock: permission denied
> 
> ERROR: for web  Cannot start service web: error while mounting volume '/var/lib/docker/volumes/ddev-drupal-89x_nfsmount/_data': failed to mount local volume: mount :/System/Volumes/Data/Users/nareshbavaskar/ddev-projects/drupal-8.9.x:/var/lib/docker/volumes/ddev-drupal-89x_nfsmount/_data, data: addr=192.168.65.2,hard,nolock: permission denied
> Encountered errors while bringing up the project.
> Failed to restart drupal-8.9.x: Failed to run docker-compose [-f /Users/nareshbavaskar/ddev-projects/drupal-8.9.x/.ddev/.ddev-docker-compose-full.yaml up --build -d], err='exit status 1', stdout='Docker Compose is now in the Docker CLI, try `docker compose up`
> 
> 
> Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
> Successfully built df3551ef532145db64d2fcca8b514769a4e9da38e629d60d04d2c87e52023d7e
> 
> Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
> Successfully built c9896f28211e450d58663d664f226cef8c7d91e344237663a5f474d41bffa2ca
> ', stderr='Building db
> #1 [internal] load build definition from Dockerfile
> #1 sha256:b40b779a439e10e0d9b55a4ce9cd7283a42055c4a89aea2b0fcdc6fc543efa60
> #1 transferring dockerfile: 343B 0.0s done
> #1 DONE 0.0s
> 
> #2 [internal] load .dockerignore
> #2 sha256:6af802f64ca9bf6d77be1c5ee7bd42757069230dc81634a2297562b36e6dc565
> #2 transferring context: 2B done
> #2 DONE 0.0s
> 
> #3 [internal] load metadata for docker.io/drud/ddev-dbserver-mariadb-10.2:v1.14.1
> #3 sha256:7043214c271b08dbffe57cb6910f6a7da530dcd22d01ea4d25eff2f7b33defa8
> #3 DONE 0.0s
> 
> #4 [1/2] FROM docker.io/drud/ddev-dbserver-mariadb-10.2:v1.14.1
> #4 sha256:0a89f285ad2e80544e9de87823b56ce496db04b0c9086fa5d4c773c6b21a54cb
> #4 DONE 0.0s
> 
> #5 [2/2] RUN (groupadd --gid 20 "nareshbavaskar" || groupadd "nareshbavaskar" || true) && (useradd  -l -m -s "/bin/bash" --gid "nareshbavaskar" --comment '' --uid 501 "nareshbavaskar" || useradd  -l -m -s "/bin/bash" --gid "nareshbavaskar" --comment '' "nareshbavaskar")
> #5 sha256:229ce11cb0ee8028b6e70f9bc25ab69d526ca1f9d0e176b11d514f1f9f5c2077
> #5 CACHED
> 
> #6 exporting to image
> #6 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
> #6 exporting layers done
> #6 writing image sha256:df3551ef532145db64d2fcca8b514769a4e9da38e629d60d04d2c87e52023d7e done
> #6 naming to docker.io/drud/ddev-dbserver-mariadb-10.2:v1.14.1-drupal-8.9.x-built done
> #6 DONE 0.0s
> Building web
> #1 [internal] load build definition from Dockerfile
> #1 sha256:c8d6354e0c10d57d672b7f5425f843a6c149c9dce50cf74d3055c953753333c9
> #1 transferring dockerfile: 343B done
> #1 DONE 0.0s
> 
> #2 [internal] load .dockerignore
> #2 sha256:5e9703186fd3b38660cc1145f150f612dc0842f58d8fb6fc477f64d4a836c02b
> #2 transferring context: 2B done
> #2 DONE 0.0s
> 
> #3 [internal] load metadata for docker.io/drud/ddev-webserver:v1.14.1
> #3 sha256:40002839c1ee9e6d232c94b22ec0355a29273ea1a2009e41ee02276ec16b18b5
> #3 DONE 0.0s
> 
> #4 [1/2] FROM docker.io/drud/ddev-webserver:v1.14.1
> #4 sha256:e890b8aaefc05d07970fe47d22d63eacd3fa65648b9df4257bf1f77bfad79ca3
> #4 DONE 0.0s
> 
> #5 [2/2] RUN (groupadd --gid 20 "nareshbavaskar" || groupadd "nareshbavaskar" || true) && (useradd  -l -m -s "/bin/bash" --gid "nareshbavaskar" --comment '' --uid 501 "nareshbavaskar" || useradd  -l -m -s "/bin/bash" --gid "nareshbavaskar" --comment '' "nareshbavaskar")
> #5 sha256:7b0a0e9815664e4cb56f8fee5eca791de2a1c6f649149444742d121c14d88ca9
> #5 CACHED
> 
> #6 exporting to image
> #6 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
> #6 exporting layers done
> #6 writing image sha256:c9896f28211e450d58663d664f226cef8c7d91e344237663a5f474d41bffa2ca done
> #6 naming to docker.io/drud/ddev-webserver:v1.14.1-drupal-8.9.x-built done
> #6 DONE 0.0s
> Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
> Creating ddev-drupal-8.9.x-db ...
> Creating ddev-drupal-8.9.x-chromedriver ...
> Creating ddev-drupal-8.9.x-chromedriver ... done
> Creating ddev-drupal-8.9.x-db           ... done
> Creating ddev-drupal-8.9.x-dba          ...
> Creating ddev-drupal-8.9.x-web          ...
> Creating ddev-drupal-8.9.x-dba          ... done
> Creating ddev-drupal-8.9.x-web          ... error
> 
> ERROR: for ddev-drupal-8.9.x-web  Cannot start service web: error while mounting volume '/var/lib/docker/volumes/ddev-drupal-89x_nfsmount/_data': failed to mount local volume: mount :/System/Volumes/Data/Users/nareshbavaskar/ddev-projects/drupal-8.9.x:/var/lib/docker/volumes/ddev-drupal-89x_nfsmount/_data, data: addr=192.168.65.2,hard,nolock: permission denied
> 
> ERROR: for web  Cannot start service web: error while mounting volume '/var/lib/docker/volumes/ddev-drupal-89x_nfsmount/_data': failed to mount local volume: mount :/System/Volumes/Data/Users/nareshbavaskar/ddev-projects/drupal-8.9.x:/var/lib/docker/volumes/ddev-drupal-89x_nfsmount/_data, data: addr=192.168.65.2,hard,nolock: permission denied
> Encountered errors while bringing up the project.'> 

**To Reproduce**
Existing ddev project setup
Upgrade Mac OS version to macOS big sure 11.2.3
Upgrade docker desktop 3.3.1 version
ddev start --> error

**Version and configuration information (please complete the following information):**

- macOS Big Sur 11.2.3
- Docker Desktop version 3.3.1
- ddev version information (use `ddev version v1.14.1`)

**Comment by rfay** [comment]
Hi @naresh-qed42 - 

The problem you have here is that NFS is not properly working or configured. 

But could you please use the current version of ddev instead of one that's a year or more old? Obviously we don't test old versions of ddev with the latest version of Docker Desktop. 

Anyway, though, the problem is that you have nfs_mount_enabled turned on, and NFS is not configured right. I'd start with `sudo nfsd restart` and use `ddev debug nfsmount`. 

General NFS information is at https://ddev.readthedocs.io/en/stable/users/performance/#using-nfs-to-mount-the-project-into-the-web-container, and see the debugging/troubleshooting information there. 

You can also turn off NFS support with `ddev config global --nfs-mount-enabled=false && ddev config --nfs-mount-enabled=false`

**Comment by naresh-qed42** [comment]
@rfay thanks for very quick replay,

I have turned off NFS and its get fixed, working fine.

But would like to enabled NFS for speed up:
I have tried to solve NFS using above reference URL: (`/sbin/nfsd` this step is done)
Issue:
> ~/ddev-projects/drupal-9-new(9.1.x*) » ddev debug nfsmount                                                                                                               
NFS does not seem to be set up yet, see debugging instructions at https://ddev.readthedocs.io/en/stable/users/performance/#debugging-ddev-start-failures-with-nfs_mount_enabled-true
Details: error=failed to StartContainer: API error (500): error while mounting volume '/var/lib/docker/volumes/testnfsmount/_data': failed to mount local volume: mount :/System/Volumes/Data/Users/nareshbavaskar/ddev-projects/drupal-9-new:/var/lib/docker/volumes/testnfsmount/_data, data: addr=192.168.65.2,hard,nolock: permission denied
output=

Now I remember i just deleted /etc/exports yesterday for fixing some vagrant issue.
My current  `/etc/exports` file 
># VAGRANT-BEGIN: 501 6ce5c5e5-ef9e-49c9-b560-84b0ba0a172d
>"/System/Volumes/Data/Users/nareshbavaskar/vagrant-projects/drupal-9" -alldirs -mapall=501:20 192.168.88.88
># VAGRANT-END: 501 6ce5c5e5-ef9e-49c9-b560-84b0ba0a172d

also updated ddev with the latest version v1.17.1.

**Comment by rfay** [comment]
Please follow the instructions in the [docs](https://ddev.readthedocs.io/en/stable/users/performance/#macos-nfs-setup) to set up NFS. You'll run the script macos_ddev_nfs_setup.sh.

**Comment by naresh-qed42** [comment]
great thanks, NFS is working now @rfay

**Comment by rfay** [comment]
Glad it's working!
