### ISSUE TITLE
Update install_ddev.sh after v0.6 release is cut

### ISSUE THREAD

**Issue by rfay** [drud/ddev#296]
## What happened (or feature request):

We're moving to versioned tarballs like ddev_linux.v0.6.tar.gz (or at least circleci is generating tarballs like that) as of https://github.com/drud/ddev/pull/295

This breaks the behavior of install_ddev.sh, which expects to find a generically-named tarball. 

So if we use the versioned tarballs, we have to update install_ddev.sh to use them properly.

## Related source links or issues:

**Comment by cyberswat** [comment]
https://github.com/drud/ddev/releases/tag/v0.6 was tagged and released
