### ISSUE TITLE
ddev fails to start after recloning the project and run ddev start

### ISSUE THREAD

**Issue by Diama1** [drud/ddev#2962]
**Describe the bug**
After recloning the project and run `ddev start` the bug came

**To Reproduce**

1. `ddev start` on the existing Project

```
Ensuring write permissions for ihangane 
Ensuring write permissions for ihangane 
Existing settings.php file includes settings.ddev.php 
Executing post-start hook... 
=== Running task: Exec command 'chmod +x ./scripts/build && ./scripts/build' in container/service 'web', output below 
chmod: cannot access './scripts/build': No such file or directory
Task failed: Exec command 'chmod +x ./scripts/build && ./scripts/build' in container/service 'web': exit status 1 
A task failure does not mean that ddev failed, but your hook configuration has a command that failed. 
=== Running task: Exec command 'drush site-install -y hedley install_configure_form.update_status_module='array(FALSE,FALSE)' --locale=en --account-name="admin" --account-pass="admin" --account-mail="admin@example.com" --db-url=mysql://db:db@db/db --uri="https://ihangane.ddev.site:4443"' in container/service 'web', output below 
Command site-install needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.        [error]
The drush command 'site-install hedley install_configure_form.update_status_module=array(FALSE,FALSE)' could not be executed.                                    [error]
Task failed: Exec command 'drush site-install -y hedley install_configure_form.update_status_module='array(FALSE,FALSE)' --locale=en --account-name="admin" --account-pass="admin" --account-mail="admin@example.com" --db-url=mysql://db:db@db/db --uri="https://ihangane.ddev.site:4443"' in container/service 'web': exit status 1 
A task failure does not mean that ddev failed, but your hook configuration has a command that failed. 
=== Running task: Exec command 'drush en devel views_ui -y' in container/service 'web', output below 
Command pm-enable needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.           [error]
The drush command 'en devel views_ui' could not be executed.                                                                                                     [error]
Task failed: Exec command 'drush en devel views_ui -y' in container/service 'web': exit status 1 
A task failure does not mean that ddev failed, but your hook configuration has a command that failed. 
=== Running task: Exec command 'composer install -d sites/default/files/composer' in container/service 'web', output below 

                                                                                     
  [RuntimeException]                                                                 
  Invalid working directory specified, sites/default/files/composer does not exist.  
                                                                                     

Task failed: Exec command 'composer install -d sites/default/files/composer' in container/service 'web': exit status 1 
A task failure does not mean that ddev failed, but your hook configuration has a command that failed. 
=== Running task: Exec command 'drush uli' in container/service 'web', output below 
We could not find an applicable site for that command.                                                                                                           [error]
Task failed: Exec command 'drush uli' in container/service 'web': exit status 1 
A task failure does not mean that ddev failed, but your hook configuration has a command that failed. 
Successfully started ihangane 

```

**Expected behavior**
Project starts as per usual.

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: MacOS Mojave 10.14.6
- Docker Desktop version: 19.03.13
- ddev version information : vv1.17.0-alpha4
- config.yaml contents for the misbehaving project
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?: No

**Additional context**
Add any other context about the problem here. Thanks!

@rfay

**Comment by rfay** [comment]
All of these are problems with your project, none related to ddev. 

You seem to have lots of post-start hooks that rely on particular things being in the checked-out project, and they're not there. You'll need to debug your post-start hooks in your config.yaml.

For example, 
```
=== Running task: Exec command 'chmod +x ./scripts/build && ./scripts/build' in container/service 'web', output below 
chmod: cannot access './scripts/build': No such file or directory
```

You have a post-start hook that does a chmod on ./scripts/build... but that doesn't exist.

Please do upgrade to current stable ddev, v1.17.1.

You'll also want to read the v1.17.0 release notes, https://github.com/drud/ddev/releases/tag/v1.17.0 - If you recently upgraded to v1.17 and are on drupal*+, you'll note in the caveats that "Drupal8+ no longer has a "working_dir" that lands things on the docroot instead of the project root". That could affect your hooks.

**Comment by rfay** [comment]
No response from OP so closing. Happy to continue the conversation here or elsewhere. It looks like you have post-start hooks that don't work correctly, but it shouldn't be hard to get them sorted out.

**Comment by netbrothers-tr** [comment]
If you came here like me having trouble starting a project after moving it to a different directory and saw this kind of error message:

`Failed to start project(s): stat /path/to/old/project/directory: no such file or directory`,

here's my advice:

1. Stop all ddev projects: `ddev stop --all`.
2. Remove all the containers related to project in question with `docker rm ...`. Note: Their image names end with `-<project-name>-built`.
3. Start the project in question with `ddev start`.

**Comment by rfay** [comment]
The [DDEV FAQ "How can I move a project to another directory?"](https://docs.ddev.com/en/stable/users/usage/faq/#how-can-i-move-a-project-to-another-directory)
says this:

> Run [ddev stop --unlist](https://docs.ddev.com/en/stable/users/usage/commands/#stop), then move the directory, then run [ddev start](https://docs.ddev.com/en/stable/users/usage/commands/#start) in the new directory.

Please do try to avoid commenting in 5-year-old issues, and don't forget the FAQ and other docs. And you're always welcome in the [DDEV Discord](https://ddev.com/s/discord) for support.

**Comment by netbrothers-tr** [comment]
@rfay,

> Please do try to avoid commenting in 5-year-old issues, and don't forget the FAQ and other docs. And you're always welcome in the [DDEV Discord](https://ddev.com/s/discord) for support.

Noted. Won't happen again, if you wish so. I promise. Thanks for the hint with `--unlist`.
