### ISSUE TITLE
Docker 20.10.6  breaks ddev project

### ISSUE THREAD

**Issue by joaogarin** [drud/ddev#2967]
**Describe the bug**
Updating docker to 20.10.6 breaks (maybe only some) ddev projects

**To Reproduce**
Upgrade docker to 20.10.6

**Expected behavior**

That nothing breaks. I don't think its necessarily a problem with ddev..

**Version and configuration information (please complete the following information):**

- Ubuntu 20.04
- 20.10.6
- config.yaml contents for the misbehaving project (the part before the comments)
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? Yes : I have not tried without them.

Config : 

```
name: jd
type: drupal9
docroot: backend/web
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.4"
mysql_version: ""
provider: default
hooks:
  ...
use_dns_when_possible: true
composer_version: "2"
```

There are some hooks which for kind of security sake I am not posting here.

**Additional context**

It seems related to this problem that basically it tries to use ipv6 whcih ddev does not support. I am not 100% this is a problem on ddev side or docker..but thought it would be good to point out.

Downgrading to 20.10.0 e.g. solves the problem

**Comment by rfay** [comment]
Maybe you can say what OS you're on and fundamental details like that? Please fill in the requested information above. "Host computer OS", etc. 

The issue template also asks you to:

> 2. Please run a quick diagnostic and post the results as a new gist on gist.github.com (or on another pastebin-type site if you prefer). You can download [test_ddev.sh](https://raw.githubusercontent.com/drud/ddev/master/scripts/test_ddev.sh) and run it per the instructions at the top. That will help so we don't have to ask so many questions... And it it works, it probably means there's something wrong with your project, not ddev. Put the link to the gist here.

**Comment by rfay** [comment]
I'm not seeing any trouble with docker 20.10.6 on Ubuntu 20.04. In addition to the diagnostic and filling in the required details, if you can say exactly what happens it will be useful.

**Comment by joaogarin** [comment]
Hello, 

I have updated the issue with some more info. I will also ask internally for someone with a bit more ddev experience to test it in our setup this could also be related to custom config (which I think we have a lot). 

Feel free to also close the issue if this is not happening generically in ddev, I have the URL as a reference anyway and in case we find what is causing it we can reopen if we think it can be useful for ddev

**Comment by rfay** [comment]
Please run the test_ddev.sh as requested in https://github.com/drud/ddev/issues/2967#issuecomment-826985076 and post the results as a gist, thanks.

**Comment by rfay** [comment]
This change in 20.10.6 broke one ddev test, but I didn't see it break anything else: https://github.com/moby/moby/issues/42313

**Comment by rfay** [comment]
I hope you can provide the details of what your problem was, but haven't heard from you and unable to recreate whatever the problem was, so I'm going to close this. I'm happy to continue the conversation here or elsewhere, and looking forward to hearing what the actual issue was.
