### ISSUE TITLE
Enhance `ddev delete images` command to remove all ddev images

### ISSUE THREAD

**Issue by gilbertsoft** [drud/ddev#2968]
**Is your feature request related to a problem? Please describe.**
To remove older ddev images there is the command `ddev delete images`. If one likes to remove all ddev images he must use docker directly therefor and tbh I'm not able to remember the correct command and always have to use the description at https://ddev.readthedocs.io/en/stable/users/uninstall/.

**Describe the solution you'd like**
This could be solved by adding a flag (-a / --all) to the existing command and let ddev do the job.

**Comment by rfay** [comment]
I like this.

**Comment by weitzman** [comment]
Would be a useful addition IMO

**Comment by mikebarkas** [comment]
I will work on this.

**Comment by mikebarkas** [comment]
@rfay this remove image code is repeated many times for the delete images command.
I would like to wrap it into a function. Do you think this would be a good idea? I have it coded and working on my laptop.

    if err = dockerutil.RemoveImage(tag); err != nil {
        util.Warning("Failed to remove %s: %v", tag, err)
    }

**Comment by rfay** [comment]
Oh please.
