### ISSUE TITLE
MacOS 11.3.1,  ddev 1.17.1,  Docker Desktop 3.3.1 trouble with NFS (nfs-mount-enabled=true)

### ISSUE THREAD

**Issue by kamilmaliszewski** [drud/ddev#2971]
Hi, 

There is anyone who did update of MacOS? I am not sure if it is the main reason but after update ddev stopped worked for me in NFS mode. 

When I type `ddev debug nfsmount` I have error: 
```
NFS does not seem to be set up yet, see debugging instructions at https://ddev.readthedocs.io/en/stable/users/performance/#debugging-ddev-start-failures-with-nfs_mount_enabled-true
Details: error=failed to StartContainer: API error (500): error while mounting volume '/var/lib/docker/volumes/testnfsmount/_data': failed to mount local volume: mount :/System/Volumes/Data/Volumes/Projects/ltw:/var/lib/docker/volumes/testnfsmount/_data, data: addr=192.168.65.2,hard,nolock: permission denied
output=
```
Similar error is when I try to start project with `ddev start`

Fast solution was disable NFS for me and then ddev works

I'd like to know maybe if anyone here also did update, becuase I am not sure if it is connected with new MacOS version.

**Version and configuration information (please complete the following information):**

- MacOS BigSur 11.3
- Docker desktop 3.3.1
- ddev version 1.17.1

**Additional context**
- Before update everything works fine
- After update MacOS Dockers also was updated. Now it is Docker desktop 3.3.1 with docker engine 20.10.5. Before I had 3.3.0
- Mac with intel

Until I will make downgrade of MacOS I'd like to ask if someone with 11.3 can reproduce this bug?

**Comment by mccousin** [comment]
Same problem here after MacOS BigSur 11.3 update. But only with the mounts on my external drive. The ones in my user directory are still working.

**Comment by kamilmaliszewski** [comment]
@mccousin puh, so it seems that it is connected with update. Now the question is who is going to fix it ? :) If you found any better solution than disable NFS let me know pls

**Comment by mccousin** [comment]
As i mentioned. The projects in the user folder on the local drive do work for me. The ones located in /Volumes/externaldrive/ don't.

**Comment by kamilmaliszewski** [comment]
ah @mccousin sry I thought you mentioned that projects without NFS works for you. You mean other path inside user folder. I'll check it. Thx

**Comment by rfay** [comment]
I'm not having any trouble with macOS 11.3.1 + NFS + Docker Desktop 3.3.1. I tested both on amd64 and arm64 (M1).

The normal thing to do is to follow the troubleshooting link [provided in the error message](https://ddev.readthedocs.io/en/stable/users/performance/#debugging-ddev-start-failures-with-nfs_mount_enabled-true) - please do that.

I find that people sometimes need to restart nfs after an uipgrade (`sudo nfsd restart`)
I also find that people sometimes change user id for random reasons or something like that, or their /etc/exports gets messed up. Take a look at /etc/exports. Consider removing it and recreating it using the [setup script](https://raw.githubusercontent.com/drud/ddev/master/scripts/macos_ddev_nfs_setup.sh)

But please, follow the troubleshooting link and don't just assume that you're stuck.

**Comment by rfay** [comment]
@mccousin mentions in https://github.com/drud/ddev/issues/2971#issuecomment-829180472 that projects on an external drive aren't working. Note that for projects to work on an external drive you have to give nfsd full disk access permissions, as noted in the troubleshooting and macOS setup links.

**Comment by mccousin** [comment]
@rfay I followed the troubleshooting and used the setup script to recreate the etc/exports.
I gave nfsd full disk access permisssion. Stil the projects on /Users/username do work, but the ones on /Volumes/myexternalssddrive don't.

With ddev debug nfsmount I get the follwing output on the 

project on the external drive:

`NFS does not seem to be set up yet, see debugging instructions at https://ddev.readthedocs.io/en/stable/users/performance/#debugging-ddev-start-failures-with-nfs_mount_enabled-true
Details: error=failed to StartContainer: API error (500): error while mounting volume '/var/lib/docker/volumes/testnfsmount/_data': failed to mount local volume: mount :/System/Volumes/Data/Volumes/iMacData/Websites/testproject:/var/lib/docker/volumes/testnfsmount/_data, data: addr=192.168.65.2,hard,nolock: permission denied
output=
`
project in user directory on internal drive:

`TARGET    SOURCE                                                          FSTYPE OPTIONS
/nfsmount :/System/Volumes/Data/Users/markuscousin/testproject.de-2021 nfs    rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.65.2,mountvers=3,mountproto=tcp,local_lock=all,addr=192.168.65.2
/nfsmount/.ddev 
`

**Comment by kamilmaliszewski** [comment]
@rfay ok, I'll check and I'll try to give access to full disk, but strange that before update without this option everything worked correctly. But lets see whats happen

**Comment by rfay** [comment]
My experience is that by following the troubleshooting instructions you'll find the source of the problem. Usually running Console.app and watching why nfsd refuses gives the answer.

**Comment by rfay** [comment]
Has anybody mentioned what they upgraded *from* yet? If you're upgrading from something before Catalina or even Catalina you'll definitely have a first-timer's experience with Apple's increased controls.

**Comment by rfay** [comment]
I assume you've both done the first thing and rebooted your computer?

**Comment by mccousin** [comment]
I upgraded from 11.2.3

**Comment by kamilmaliszewski** [comment]
@rfay for me it was just one update. So probably last version was 11.2.3

**Comment by kamilmaliszewski** [comment]
@rfay I've reinstalled docker, reinstalled ddev, make few reboots so only thing which I can do yet is downgrade MacOS

**Comment by rfay** [comment]
Please follow the troubleshooting instructions. Go through them all the way. Look at the results in Console.app, which normally explain what the problem is. If you've done all that, I'll be happy to do a zoom with you and look at it. You each have completely different problems.

**Comment by mccousin** [comment]
changing the entry in the etc/exports

from

/Volumes/iMacData/Websites -alldirs -mapall=501:20 localhost
to
/Volumes/iMacData -alldirs -mapall=501:20 localhost

solved my problems.

**Comment by kamilmaliszewski** [comment]
@mccousin I did now the same what you:
- change from:
`/Volumes/Projects/_nfs -alldirs -mapall=501:20 localhost`
- to
`/Volumes/Projects -alldirs -mapall=501:20 localhost`
So one dir above and NFS again works
@rfay so it seems that we can close the issue. Not sure what was solution but without subdirectory it works. And what is important. I still have no full disk access
