### ISSUE TITLE
Add a command to enable xhprof for ddev (like xdebug)

### ISSUE THREAD

**Issue by LionsAd** [drud/ddev#2974]
I am always frustrated when I want to profile a web page and last I followed Daniels post here:

(https://daniel.town/profiling-php-in-ddev-using-tideways-locally/)

**Describe the solution you'd like**
@rfay now showed me that it's as simple as doing:

```
webimage_extra_packages: [php7.4-xhprof]
```

but I was not able to find that solution anywhere.

I would love that to be as simple as with xdebug to just do:

```
ddev xhprof on
```

and if I don't need it anymore:

```
ddev xhprof off
```

**Describe alternatives you've considered**

It can be done manual, but a command sounds nicer. OSS should not only support proprietary (even if free) solutions like blackfire, but always also provide a free alternative with equal ease of use. (My old Debian / GNU background shines through here :D)

**Additional context**

The command will be great!

**Comment by penyaskito** [comment]
This might help you in the meantime: https://github.com/drud/ddev-contrib/pull/128/commits/2c10736e13a0b8ae2a86f9b6b148f5aaab0a2506
