### ISSUE TITLE
Add support for e.g. xhprof-kit via xhprof to make it easier to profile things (similar to proprietary blackfire.io)

### ISSUE THREAD

**Issue by LionsAd** [drud/ddev#2975]
**Is your feature request related to a problem? Please describe.**

Profiling xhprof is still difficult and while capturing the data is possible with several modules, looking at it then is non-trivial.

**Describe the solution you'd like**

I have developed https://github.com/LionsAd/xhprof-kit which transparently via a index-perf.php (but could also be a preload script in php config which is better for DDEV) allows to intercept page requests and write the XHProf data to a log, but also shows a little page timer on the page itself (could be done as browser extension as well).

There is also a perf.php which can be included and used to profile e.g. drush or other commands.

It would be great if instead of just blackfire, it would be as easy to use the OSS xhprof.

**Additional context**

- One problem with Drupal 8/9 e.g. is that things are hardened down so a 2nd front-controller is hard, also need a container that can show the results.

Ideal scenario:

xhprof.ddev.local -> as UI
preload script, which outputs https://xhprof.ddev.local/index.php?run=12345 + times as a HTTP header or on the page (for non-POSTs or ajax requests).

-> makes it trivial to profile locally

**Comment by rfay** [comment]
This is in there in ddev v1.17.6, thanks for the issue! Looking forward to making it better as time goes on.
