### ISSUE TITLE
Remove special Windows symlink code and related composer docs

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2986]
There used to be significant problems with symlink creation on docker running under Windows, and ddev went to great lengths to replace those symlinks with links that would work.

This may not be relevant since Docker switched to gRPC a year or so ago, so review:

- [x] Is the symlink update even used any more?
- [x] Is it useful in any way?
- [ ] Update related docs, see https://ddev.readthedocs.io/en/stable/users/developer-tools/#windows-os-and-ddev-composer

**Comment by gilbertsoft** [comment]
I've tested the symlinks again and it looks they are created correctly without the help of DDEV. So I'd say this feature could be removed.

The following screenshot shows two of the created symlinks. I did run `ddev ssh` and `composer install` directly in the container for this test.

![grafik](https://user-images.githubusercontent.com/25326036/129960050-45608155-b594-476c-a0e1-006d93bf7f5e.png)

**Comment by rfay** [comment]
Thanks @gilbertsoft - Changed title to "remove".
