### ISSUE TITLE
Build PHP extensions from source with docker-php-ext-*

### ISSUE THREAD

**Issue by StudioMaX** [drud/ddev#2987]
**Is your feature request related to a problem? Please describe.**
The official [PHP Docker Images](https://hub.docker.com/_/php/#how-to-install-more-php-extensions) provides convenient `docker-php-ext-configure`, `docker-php-ext-enable`, `docker-php-ext-install` commands for building PHP extensions from source. This is often useful when you need to build an extension from source on the GitHub, when the branch is still under development and is not in any repositories.

An example: Build [Phalcon Framework v5.0.x](https://github.com/phalcon/cphalcon/tree/5.0.x), which is still in alpha for further testing and adaptation with the codebase of our project.

**Describe the solution you'd like**
Reimplement and provide these helper scripts in DDEV images.

**Describe alternatives you've considered**
https://github.com/docker-library/php/tree/master/7.4/buster/fpm

**Comment by rfay** [comment]
You can use this technique to build anything that's in pecl: https://stackoverflow.com/questions/60554989/how-can-i-install-a-pecl-extension-like-mcrypt-in-ddev-locals-web-container - does that work for you?

**Comment by StudioMaX** [comment]
Of course, we can install all the necessary extensions using the full installation commands - install gcc, php-dev, etc. for the extension stack. However, for many years there have been special helper scripts in the official docker-php repositories that make this task much easier when you need to build many extensions.

**Comment by rfay** [comment]
In your custom Dockerfile you can just curl those scripts and use them, of course.

**Comment by rfay** [comment]
I first tried this out in https://github.com/drud/ddev-contrib/pull/141 and my goodness is it nice. And so easy to add (I think)

**Comment by rfay** [comment]
For future reference, these are in https://github.com/docker-library/php, but unfortunately very-little documented, and of course they're focused on a single version of PHP. It's not clear to me how the PHP source is to be obtained.

**Comment by rfay** [comment]
docker-php-source requires the proper php source to already be downloaded. I get

```
rfay@d9-web:/usr/local/bin$ sudo docker-php-ext-install mcrypt
tar (child): /usr/src/php.tar.xz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Comment by rfay** [comment]
@StudioMaX would love it if you could take a look at the request in https://github.com/drud/ddev/pull/3071#issuecomment-868789753

**Comment by rfay** [comment]
This will be a great project for [ddev-contrib](https://github.com/drud/ddev-contrib), but it's not appropriate for the huge image size increase that would result from adding it. I didn't realize how much beyond the scripts was required.
