### ISSUE TITLE
Add Phive to the PHP image?

### ISSUE THREAD

**Issue by NicoHaase** [drud/ddev#2990]
To install development aids like PHPUnit or similar tools, we use [Phive](https://github.com/phar-io/phive). It would be great to include their Phar in the ddev PHP images, such that it can be used in the same way as composer

**Comment by rfay** [comment]
Hmm, we install magerun, magerun2, drush8, terminus, platform, and acli from phar files in the [ddev-webserver Dockerfile](https://github.com/drud/ddev/blob/master/containers/ddev-webserver/Dockerfile). This might be worth it right out of the box just to simplify those. 

PR is welcome.
