### ISSUE TITLE
Config seems to sporadically be deleted

### ISSUE THREAD

**Issue by MisterH001** [drud/ddev#2995]
**Run a Diagnostic and Paste Link Here**
https://gist.github.com/MisterH001/294e44ad45d15634a6d4bd0e88066dcc

**Describe the Problem**
(firstly, thank you for the utterly AWESOME tool!)

I am finding that a sites config (.ddev/config.yaml) seems to get deleted at random times. I haven't yet found a pattern. But I end up having to config the project again and update all the overrides I have in place (php version, additional_hostnames etc).
It's when I don't touch the project for a day or two (and perhaps load up other projects).
But I haven't found a pattern yet I'm afraid. 
I was juts wondering if you had encountered anything similar?

Thank you.

**Additional context**
Only thing I can think of that is different on this project to another one I have that doesn't seem to have this issue is that I have an additional_hostname configured (which is then used in the nginx-site.conf to set an environment variable) - nginx-site.conf does not get deleted.

**Comment by rfay** [comment]
No, I've never heard of this before. There is no code in ddev that does anything besides reading the .ddev/config.yaml. 

Do you have some scripting that starts or rebuilds your project? Do you periodically do a composer rebuild from scratch?

**Comment by rfay** [comment]
Most people commit the config.yaml, it seems to be good practice. But if not committed, a `git clean -f` would sure delete it!

**Comment by rfay** [comment]
Closing this, but happy to continue the conversation here or elsewhere.
