### ISSUE TITLE
ddev artisan global command not found

### ISSUE THREAD

**Issue by froemken** [drud/ddev#2999]
**Describe the Problem**

ddev does not know the laravel `artisan` command. But this command is registered as global command in my home directory:

```
➜  web cd ~/.ddev/commands/web 
➜  web ll
total 72
-rwxr-xr-x  1 froemken  staff   412B 12 Mai 22:15 README.txt
-rwxr-xr-x  1 froemken  staff   223B 12 Mai 22:15 artisan
-rwxr-xr-x  1 froemken  staff   2,0K 12 Mai 22:15 blackfire
-rwxr-xr-x  1 froemken  staff   392B 12 Mai 22:15 drush
-rwxr-xr-x  1 froemken  staff   268B 12 Mai 22:15 magento
-rwxr-xr-x  1 froemken  staff   190B 24 Apr 00:24 reload-nginx.example
-rwxr-xr-x  1 froemken  staff   335B 12 Mai 22:15 typo3
-rwxr-xr-x  1 froemken  staff   339B 12 Mai 22:15 typo3cms
-rwxr-xr-x  1 froemken  staff   225B 25 Mär 19:14 wp
```

Interesting, if I add my own artisan command in my local project, ddev echos:

```
not adding command artisan (/Users/froemken/htdocs/dashboard/.ddev/.global_commands/web/artisan) because it was already added to project dashboard
```

So I have removed my own artisan command.

Output of ddev help:

```
Available Commands:
  auth             A collection of authentication commands
  composer         Executes a composer command within the web container
  config           Create or modify a ddev project configuration in the current directory
  debug            A collection of debugging commands
  delete           Remove all project information (including database) for an existing project
  describe         Get a detailed description of a running ddev project.
  exec             Execute a shell command in the container for a service. Uses the web service by default.
  export-db        Dump a database to a file or to stdout
  help             Help about any command
  hostname         Manage your hostfile entries.
  import-db        Import a sql file into the project.
  import-files     Pull the uploaded files directory of an existing project to the default public upload directory of your project.
  list             List projects
  logs             Get the logs from your running services.
  pause            uses 'docker stop' to pause/stop the containers belonging to a project.
  poweroff         Completely stop all projects and containers
  restart          Restart a project or several projects.
  share            Share project on the internet via ngrok.
  snapshot         Create a database snapshot for one or more projects.
  ssh              Starts a shell session in the container for a service. Uses web service by default.
  start            Start a ddev project.
  stop             Stop and remove the containers of a project. Does not lose or harm anything unless you add --remove-data.
  version          print ddev version and component versions
```

**To Reproduce**

➜  dashboard> ddev artisan
Error: unknown command "artisan" for "ddev"
Run 'ddev --help' for usage.

But `ddev exec php artisan` works.
And `ddev exec artisan` fails:

```
➜  dashboard> ddev exec artisan    
bash: artisan: command not found
```

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: macOS Big Sur on Apple Silicon M1
- Docker Desktop version: 3.3.1
- ddev version information: 1.17.2
- Do you have any custom configuration. No, wait, Ok...I have activated the `ll` alias in homeadditions
- config.yaml contents

```
name: dashboard
type: php
docroot: public
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.3"
mysql_version: ""
use_dns_when_possible: true
timezone: Europe/Berlin
composer_version: "2"
web_environment: []
```

**Comment by rfay** [comment]
Hi @froemken - 

Because you use `type: php` the command is not loaded. It's only loaded for projects of type 'laravel'. You can look inside the script and see where that's specified. 

The idea is not to overwhelm everybody with commands they don't need; obviously Drupal and TYPO3 folk don't need to see `artisan` in the list of commands when they type `ddev` or `ddev help`

If you have `type: php` specified because you don't want ddev to fiddle with settings files, you may want instead to turn off settings management.

**Comment by froemken** [comment]
@rfay Damn you're right :-)

I was really sure that `laravel` was not listed in `ddev help config`, but it is:

`--project-type string              Provide the project type (one of backdrop, drupal6, drupal7, drupal8, drupal9, **laravel**, magento, magento2, php, shopware6, typo3, wordpress). This is autodetected and this flag is necessary only to override the detection.`

Don't know what happens to me that night...

Thank you for your help

Stefan

**Comment by rfay** [comment]
Glad you got it!
