### ISSUE TITLE
Docker restart results in nginx-proxy being MIA

### ISSUE THREAD

**Issue by rfay** [drud/ddev#300]
## What happened (or feature request):

I restarted docker. 
ddev sites became unusable because the nginx-proxy went away. (It stopped, was not deleted)
Easy to fix: `ddev start` brings the router back

## What you expected to happen:

Docker restart shouldn't break ddev

## How to reproduce it (as minimally and precisely as possible):

Start a site
Restart docker
Visit the site. You won't.

## Related source links or issues:

**Comment by beeradb** [comment]
I did some testing on this, and it's been present at least as far back as `v0.1`. I had thought it was perhaps a change we'd made to the router in the last few releases, but it certainly looks like it's a long-standing issue.

**Comment by beeradb** [comment]
Opened PR for this in https://github.com/drud/elysium/pull/6/files
