### ISSUE TITLE
should wp-config.php try to set ABSPATH only if it wasn't already?

### ISSUE THREAD

**Issue by working-name** [drud/ddev#3000]
**Is your feature request related to a problem? Please describe.**
When I spin up a wordpress install line 20 of wp-config.php has `define('ABSPATH...` causing an exception when debugging is on. If I wrap that in `if ( empty( ABSPATH ) ) { define... }` the issue doesn't happen. It seems the variable is set before wp-config.php is loaded.

**Describe the solution you'd like**
Wrap define in an if?

**Describe alternatives you've considered**
Nothing else comes to mind.

**Additional context**
![already-set-in-wp-load](https://user-images.githubusercontent.com/16505052/118067672-06195f80-b36f-11eb-91e0-978d54b05dc7.png)

**Comment by rfay** [comment]
PR is welcome. 

Probably https://github.com/drud/ddev/issues/2795 is closely related, would love your comments there as well.

**Comment by rfay** [comment]
PR is welcome, https://github.com/drud/ddev/blob/868e2ea76596b1fb8406bdce91f914bbf2f730fb/pkg/ddevapp/wordpress.go#L106

Thanks for sharing your WP expertise!

**Comment by rfay** [comment]
I think this was solved in 
* https://github.com/drud/ddev/pull/3468

So I'm going to close this for now, but happy to continue the conversation and reopen this if you don't find it adequate now. Thanks!
