### ISSUE TITLE
Problem with docker-compose after last docker update

### ISSUE THREAD

**Issue by bessone** [drud/ddev#3001]
**Describe the Problem**

Today after updating docker desktop on Windows 10 to the latest version 3.3.3 (64133) I am having trouble starting my ddev projects.

**To Reproduce**
Run "**_ddev start_**" in an existing project and the message "**_docker-compose does not appear to be installed_**"

**Version and configuration information (please complete the following information):**
DDEV v1.17.2
Docker Desktop for Windows 3.3.3 (64133)
Windows 10 Pro Build 19042

**Additional context**
I tried to run the "**_docker-compose_**" command from a shell and the command works, but as the last line it returns **_Docker Compose is now in the Docker CLI, try `docker compose`_**, could this be the problem?
Obviously running the "**_docker compose_**" command works

Thanks!

**Comment by bessone** [comment]
Resolved.

I tried to restart docker desktop several times but the problem remained, I finally restarted windows, and the problem was solved.

Sorry for the useless issue!

**Comment by rfay** [comment]
Glad it's working for you! There must have been something wrong with your PATH, or be careful that you don't somehow have two versions of docker-compose out there. But sounds like you've got it now.
