### ISSUE TITLE
Update wp-cli to latest version

### ISSUE THREAD

**Issue by bc1121** [drud/ddev#3021]
A new version of WP-CLI(2.50) was released yesterday. It's been one and a half years since the last release. The new version does solve an [issue](https://github.com/wp-cli/wp-cli/issues/5422) with PHP Notices/Warnings in PHP 7.4(+?)

I am assuming based on the changes made [here](https://github.com/drud/ddev/commit/71e771effb5a365c5d18021a7b832fc03eec1419) that the new version will automatically be included in the the next major, or possibly minor, DDEV release, just whenever new images are generated.

I'm commenting here just for discussion purposes, to share what I've learned, and hopefully to make it easier to answer future inquiries about when and how WP-CLI updates arrive in DDEV and provide workarounds for the interim.

### In the Mean Time
I'm in no hurry for new images as it's easy enough to update (`ddev exec wp cli update`) in any project to the latest version of WP-CLI.

At this point everything that followed was an admittedly trivial pursuit used purely as a learning exercise.

### Temporary Automations
I can think of at least a couple of ways to temporarily automate the update at the global .ddev or project .ddev level using .profile or Dockerfiles but I am unsure the most efficient method that won't overwrite or be overwritten by future DDEV updates. So far I have copied and modified .profile and dropped it in homeadditions folder at either the .ddev global or .ddev project level but that doesn't feel right because that's a generated file and I would rather append the file with a script than to overwrite future copies of the file. I am still learning about where to modify DDEV images without stepping on or being stepped on by updates or restarts.

### Just to See It Work
I wanted to see if I could make new images and use them, and I wanted to verify that making new images would automatically pull the latest WP-CLI

#### drud/ddev-images
modify Makefile if necesscary to target single platform (amd64 for me)
`-BUILD_ARCHS=linux/amd64,linux/arm64`
`+BUILD_ARCHS=linux/amd64`
`-DOCKER_BUILDKIT=1` ... `--platform linux/amd64,linux/arm64` ...
`+DOCKER_BUILDKIT=1` ... `--platform linux/amd64` ...

`make ddev-php-base VERSION=210520`

#### drud/ddev/containers/ddev-webserver
modify Dockerfile to build from the image built in the previous step
uncomment and change the tag on this line from Dockerfile
`FROM drud/ddev-php-base:210520 as ddev-webserver-base`

`make container`

#### project/.ddev/config.yaml
`webimage: yourImageIDHere # nginx/php docker image.`

`ddev restart`

`ddev exec wp --version`
WP-CLI 2.5.0

Success!

**Comment by rfay** [comment]
Yes, the next minor version of ddev (in about 2 weeks) will contain updated tools like wp.

If it's important to get that right away, you can easily do it in a .ddev/web-build/Dockerfile, and of course you can do what you're doing, or add `wp cli update` to a post-start hook.

**Comment by bc1121** [comment]
Thanks for the comment! I'll start to use .ddev/web-build/Dockerfile, and try a post-start hook to embed them in my tool chest.

**Comment by rfay** [comment]
This automatically gets updated on next release, so closing. Thanks for the note.
