### ISSUE TITLE
Make it easy to add to the web container $PATH

### ISSUE THREAD

**Issue by dercheffe** [drud/ddev#3022]
**Is your feature request related to a problem? Please describe.**
Since DDEV 1.17.0 drush launcher is removed and PATH variable is used to look for drush command.
In my use case, my project is located in a subdir of my ddev installation (due to be equivalent to my live server configuration).
**_Examples:_**
Path to my Project dir: 
_/opt/webserver/my-ddev-installation/my-drupal-project-folder_

My doc root:
_/opt/webserver/my-ddev-installation/my-drupal-project-folder/web_

Due to that PATH variable is pointed to _/opt/webserver/my-ddev-installation/vendor/bin_ (or in SSH _/var/www/html/vendor/bin_) my drush of my project can't be found

**Describe the solution you'd like**

- Provide an extra config param similar to the docroot param
- Per default it could assumed, that composer installation is one directory layer above **docroot**. So if docroot is _/opt/webserver/my-ddev-installation/my-drupal-project-folder/web_ then in most cases drush is located in _/opt/webserver/my-ddev-installation/my-drupal-project-folder/vendor/bin_
- Additionally provide a config param to install drush launcher

**Comment by rfay** [comment]
This is a good idea, but really has nothing to do with drush. People may need various things in their $PATH. It would be nice to make that easier to do. Currently one can do it fairly trivially with a .ddev/web-build/Dockerfile, or with a post-start hook, lots of ways. You might start with a post-start hook does a symlink, `ln -s /path/to/your/bindir/drush /usr/local/bin/drush`

**Comment by dercheffe** [comment]
Hi @rfay thanks for your reply :) didn't do a dockerfile or a post-start hook yet, but I'll figure that out. 

> People may need various things in their $PATH. It would be nice to make that easier to do. 
Perhaps its possible to define a param in config.yml to set one or more $PATH values. 

> This is a good idea, but really has nothing to do with drush.
You're right. Drupal console starts also crying when try to use their "drupal" alias.

**Comment by dercheffe** [comment]
FYI: The post hook solution works fine in general :+1: 

In my production environment I'm using drush launcher (yet).  When I simply copying my production site to my dev environment and then starting everything (inkl. post-start hook), executing drush alias throws following php error:
`require(drush.php): failed to open stream: No such file or directory in /var/www/html/youlife-rocks/vendor/bin/drush`
`PHP Fatal error:  require(): Failed opening required 'drush.php' (include_path='.:/usr/share/php') in /var/www/html/youlife-rocks/vendor/bin/drush`
After reinstalling drush via composer (without launcher) it works like a charm.
same behavior I could observe with drupal console and drupal console launcher

**Comment by rfay** [comment]
This is easy to do in ddev v1.17+

In your .ddev/config.yaml

```yaml
web_environment:
- PATH=$PATH:/some/new/path
```

This works for random things that need path added, does not work for `ddev ssh`, where the .bash_profile and such are involved.
