### ISSUE TITLE
ddev launch error: "command not found"

### ISSUE THREAD

**Issue by janisint** [drud/ddev#3023]
**Describe the bug**
When I run the command "ddev launch", instead of launching the projekt in my browser, it throws this error:

> /home/janisint/folder/folder2/myproject/.ddev/commands/host/launch: line 61: xdg-open: command not found
> Failed to run launch ; error=exit status 127

**To Reproduce**

1. Download the latest version of ddev (1.17.2)
2. Start any project with ddev launch
3. Issue "ddev launch"

**Expected behavior**
After issuing "ddev launch", the launch command should be executed correctly and open the browser.

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: Windows 10 | WSL with Ubuntu 20.04
- Docker Desktop version: 20.10.5
- ddev version: 1.17.2
- config.yaml contents for the misbehaving project (the part before the comments):
```
name: myproject
type: php
docroot: ""
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
mysql_version: ""
provider: default
use_dns_when_possible: true
composer_version: ""
```

**Comment by rfay** [comment]
Hi @janisint - You need to install xdb-open per the docs. Please see https://ddev.readthedocs.io/en/stable/#installation-or-upgrade-windows-wsl2 - step #2512 

> sudo apt-get update && sudo apt-get install -y xdg-utils to install the xdg-utils package that allows ddev launch to work

**Comment by janisint** [comment]
Thank you very much, this resolved the issue!
