### ISSUE TITLE
Support running ddev-dbserver Docker images solo and with docker-entrypoint.sh

### ISSUE THREAD

**Issue by hussainweb** [drud/ddev#3025]
**Is your feature request related to a problem? Please describe.**

I want to run the Docker image for the database directly using Docker, i.e., without `docker-compose`. This is possible in base images (official images) for MySQL and MariaDB but this fails when I use the same syntax for DDEV's database image.

If I run the command:
```bash
docker run -it drud/ddev-dbserver-mariadb-10.5:v1.17.0 bash
```

I see a log of output and then finally an error:
```
...
+ echo 'Starting mysqld.'
Starting mysqld.
+ exec mysqld --server-id=0
+ tail -f /var/log/mysqld.log
2021-05-29  1:47:34 0 [Warning] option 'server_id': unsigned value 0 adjusted to 1
2021-05-29  1:47:34 0 [Note] mysqld (mysqld 10.5.9-MariaDB-1:10.5.9+maria~focal-log) starting as process 1 ...
mysqld: Please consult the Knowledge Base to find out how to run mysqld as root!
2021-05-29  1:47:34 0 [ERROR] Aborting
```

I also tried running the image as user 999. This is the user `mysql` which is added by official images of both MySQL and MariaDB (and hence present in DDEV's image as well. But there is another error:
```
docker run -it --user 999:999 drud/ddev-dbserver-mariadb-10.5:v1.17.0 bash
...
+ echo 'Database initialized from /mysqlbase/'
Database initialized from /mysqlbase/
+ rm -f /tmp/initializing
++ cat /var/lib/mysql/db_mariadb_version.txt
+ database_db_version=10.5
+ '[' 10.5 '!=' 10.5 ']'
+ echo 10.5
+ cp -r /home/.my.cnf /home/.bashrc /home/mysql/
cp: target '/home/mysql/' is not a directory
```

The problem, in this case, is that the [docker-entrypoint](https://github.com/drud/ddev/blob/8b58eb19d4e4ebc498bf18d4e08eedd1ed605491/containers/ddev-dbserver/files/docker-entrypoint.sh#L91) tries to copy some files to the user's home directory, but there isn't one for `mysql`.

I wasn't sure to classify this as a bug or a feature request. I went with the latter because this behaviour was probably not a part of DDEV, even though it is a part of the base images.

This works for DDEV because there is an additional Dockerfile and a Docker-compose file that runs this image as user 501:20.

I have tested this with different Docker images and posted logs in [a PR comment](https://github.com/drud/ddev/pull/3026#issuecomment-851638910).

**Describe the solution you'd like**
I'd like to be able to run the images straightaway without using an additional `Dockerfile`. The reason is that I would like to use a database image based on this image directly in my CI. Right now, using this image directly in Gitlab CI breaks the pipeline because of the error.

The base official images handle this in the entrypoint by running as the `mysql` user if the image is run as root.
- For MariaDB: https://github.com/MariaDB/mariadb-docker/blob/2ef69de05f84aee8a141c0d37cdb5b9790ac91d9/10.6/docker-entrypoint.sh#L361
- For MySQL: https://github.com/docker-library/mysql/blob/a09a716a88ce34a17e16df3f8b091066d90e6f34/8.0/docker-entrypoint.sh#L376

I am thinking we could do something similar in DDEV's images as well. That way, the current approach with docker-compose won't break.

**Describe alternatives you've considered**
One alternative is that I could create this user and switch to it within my [`Dockerfile`](https://github.com/axelerant/db-docker/blob/a8fc874164f114139271c23da88e865f23c52f68/assets/dockerize-db-ddev/Dockerfile). But doing that would mean that my project's DDEV config's docker-compose files and `.dbImageBuild/Dockerfile` should change. Since I want to make this a reusable pattern across projects, it is not trivial to change these config files everywhere.

A second alternative is that I use my own entrypoint which adds this support. But I think it is better to add this support in the base DDEV image as it is also something that is present in the base images.

**Additional context**
This request is to make my [db-docker](https://github.com/axelerant/db-docker) solution work seamlessly for local development and CI while supporting DDEV. There is more work to do which we discussed in Slack and I am yet to create issues and PR for them.

**Comment by rfay** [comment]
The way you would run bash would be `docker run ... --entrypoint=bash`. Just FYI. So you could add your own entrypoint script just fine, etc.

**Comment by hussainweb** [comment]
@rfay, thanks. Running the entrypoint that way would not run the entrypoint script already present in the image, right? That's not the behaviour I want. I would have to copy the entire entrypoint file for that.

**Comment by rfay** [comment]
You can add your own entrypoint script or override the existing one using .ddev/db-build/Dockerfile. Just saying. But I guess since you're not running it in ddev's context that doesn't help you.

**Comment by hussainweb** [comment]
@rfay, yes, that's right. This is related to the discussion we had earlier for db-docker and that scenario is somewhat different. Here, the context is same but I see problems when running the image within CI. Unfortunately, Gitlab CI doesn't have ways to add extra Dockerfiles or override entrypoints for services. It expects that a Docker image should just start and keep running. That doesn't work for DDEV images. I have a log output in https://github.com/axelerant/db-docker/issues/18 if you're interested.

**Comment by rfay** [comment]
Closing this for now until you have time to work on it. Happy to reopen when that time comes, thanks!
