### ISSUE TITLE
Setting up Slow Query Log using DDev

### ISSUE THREAD

**Issue by dev-sukhjinder** [drud/ddev#3027]
**Problem**

I having issue setting slow query logs. I have created .ddev/mysql/mysql.cnf added following line

`
[mysqld]
slow_query_log = 1
slow_query_log_file = /var/log/mysql-slow.log
long_query_time = 2
`
under config.yml

`  post-start:
    - exec: sudo touch /var/log/mysql-slow.log
    - exec: sudo chmod 777 /var/log/mysql-slow.log
`

**Comment by rfay** [comment]
Please say what the issue you have is. Also, please edit to show what you actually have. 

You may be interested in https://github.com/drud/ddev-contrib/tree/master/custom-commands/general-log as well

**Comment by rfay** [comment]
According to https://mariadb.com/kb/en/slow-query-log-overview/ if you're using mariadb, you should use this in .ddev/mysql/slow.cnf:

```
[mariadb]
slow_query_log
slow_query_log_file=/var/log/slow-queries.log
```

It seems to work fine (you have to `ddev restart`)

Note that the output goes to /var/log/slow-queries.log in the web container, so you can access it with `ddev ssh -s db` and `tail -f /var/log/slow-queries.log` or `ddev exec -s db tail -f /var/log/slow-queries.log`

**Comment by rfay** [comment]
Did this work for you @dev-sukhjinder ?

**Comment by dev-sukhjinder** [comment]
> Did this work for you @dev-sukhjinder ?

@rfay I tried with your configuration, but unfortunately it isn't working for me. There is no slow query logs showing up

Below is the output of `ddev exec -s db tail -f /var/log/slow-queries.log`

```
$ ddev exec -s db tail -f /var/log/slow-queries.log
mysqld, Version: 10.3.28-MariaDB-1:10.3.28+maria~focal-log (mariadb.org binary distribution). started with:
Tcp port: 0  Unix socket: /var/tmp/mysql.sock
Time		    Id Command	Argument
mysqld, Version: 10.3.28-MariaDB-1:10.3.28+maria~focal-log (mariadb.org binary distribution). started with:
Tcp port: 0  Unix socket: /var/tmp/mysql.sock
Time		    Id Command	Argument
mysqld, Version: 10.3.28-MariaDB-1:10.3.28+maria~focal-log (mariadb.org binary distribution). started with:
Tcp port: 0  Unix socket: /var/tmp/mysql.sock
Time		    Id Command	Argument
```

**Comment by dev-sukhjinder** [comment]
> Please say what the issue you have is. Also, please edit to show what you actually have.
> 
> You may be interested in https://github.com/drud/ddev-contrib/tree/master/custom-commands/general-log as well

I have setup general_log, it shows all the queries but not possible to identify which one is slow query.

**Comment by rfay** [comment]
OK. I explained how to use the slow query log above. 

You do have to say *how slow* you care about to get the slow query to work. You'll need to set long_query_time, see https://mariadb.com/kb/en/slow-query-log-overview/#configuring-the-slow-query-log-time

**Comment by dev-sukhjinder** [comment]
@rfay Thanks ton, it worked after reducing long_query_time.

**Comment by rfay** [comment]
Glad it's working for you!
