### ISSUE TITLE
Update MariaDB in ddev-dbserver to 10.2.39, 10.3.30, 10.4.20, 10.5.11

### ISSUE THREAD

**Issue by alpham8** [drud/ddev#3040]
**Is your feature request related to a problem? Please describe.**
Currently, some MariaDB 10.3 version before 10.3.30 is running by default.

**Describe the solution you'd like**
Please update you container build to at least MariaDB 10.3.30, becaue otherwise we run into this fixed MariaDB Bug: https://jira.mariadb.org/browse/MDEV-25672

**Describe alternatives you've considered**
Installing MySQL 8 instead, which worked.

**Additional context**
This would block a Shopware 6 installation in the default configs using ``ddev config``.

**Comment by rfay** [comment]
But 10.3.30 is not available yet... we currently have 10.3.29... I see this bug exists in current 10.4.*, 10.5.*

If you'll ping when you see that 10.3.30 gets in there, I'll make sure we rebuild for the next release.

**Comment by rfay** [comment]
The releases came out today. The docker images are not out yet.

But I see that there's a 10.6 image now, so perhaps we'll add that in there.

**Comment by rfay** [comment]
These were picked up during the new image creation for https://github.com/drud/ddev/pull/3073

If you're interested in testing, the binaries are available at https://github.com/drud/ddev/actions/runs/985111546
