### ISSUE TITLE
Implement container volume caching with mutagen.io

### ISSUE THREAD

**Issue by rfay** [drud/ddev#3046]
**Problem**:
Docker Desktop for Mac (and Windows) are very slow to access mounted volumes, and the more files that get mounted, the worse the problem becomes. Magento2 or large Drupal9 or TYPO3 sites can become intolerable due to this.

Linux or WSL2 has native filesystem mounts, so does not suffer from this problem.

In the past two solutions have been wildly popular but somewhat unreliable. DDEV-Local in v1.5 had an "experimental webcache" feature based on [docker-bg-sync](https://github.com/cweagans/docker-bg-sync) that essentially made updating of shared filesystems asynchronous. And Docker Desktop for a while had an explicit integration with Mutagen.io which was wildly popular, but had the same consistency problems that docker-bg-sync had. 

**Describe the solution you'd like**

Mutagen.io has been maturing quite nicely and seems well-maintained. 

The problem is asynchronous 2-way sync will never be solved with consistent sync, but there are situations where speed is more important than consistency, and if users understand the tradeoffs, it should work out OK. 

**Describe alternatives you've considered**

Everything in the docs [Performance section](https://ddev.readthedocs.io/en/stable/users/performance/)

**Comment by alechko** [comment]
As a daily ddev user on mac this would be amazing! 

The load times are ridiculously high for *anything* that's coming from the web server, not just large projects.

For tests, I've initialized almost bare Symfony projects and got 10-15 sec load times from loading "myproject.ddev.site" default page, while serving php from  Symfony binary and using ddev as db/elastic/redis cluster the load times were <1 sec.

Utilizing NFS improves almost nothing, in fact, on some projects it makes things worse on occasion.

By the way, is [docker-sync](http://docker-sync.io/) also could be considered as an option? I know it has [issues for large projects](https://github.com/EugenMayer/docker-sync/issues/624#issuecomment-443445291) but it's always nice to have an alternative if mutagen.io is unavailable for some reason.

**Comment by rfay** [comment]
We had a whole feature with docker-sync a few years ago. It was way unreliable, would stop syncing and you'd never know why or when. And of course... it's really only useful for large projects.

**Comment by alechko** [comment]
hey @rfay, I'm having trouble setting up this feature, I'm getting an error:

```
 backend (main) ✗ ddev config --mutagen-enabled && ddev start
You are reconfiguring the project at /Users/user/dev/docker/project/backend.
The existing configuration will be updated and replaced.
Found a laravel codebase at /Users/user/dev/docker/project/backend/public
Project type has no settings paths configured, so not creating settings file.
Configuration complete. You may now run 'ddev start'.
The mutagen version currently installed does not meet ddev's requirements: no mutagen
The appropriate version will be downloaded when it is needed.
Starting project-backend...
Pushed mkcert rootca certs to ddev-global-cache/mkcert
Creating volume "project-backend_project_mutagen" with default driver
Building db
Building web
Creating ddev-project-backend-db ...
Creating ddev-project-backend-db ... done
Creating ddev-project-backend-web ...
Creating ddev-project-backend-web ... done
Starting mutagen sync process...
Using mutagen config file /Users/user/dev/docker/project/backend/.ddev/mutagen.yml
Failed to start project-backend: Failed to create mutagen sync session project-backend. You may be able to resolve this problem with 'ddev stop project-backend && docker volume rm project-backend_project_mutagen' (err=Failed to mutagen [sync create /Users/user/dev/docker/project/backend docker://ddev-project-backend-web/var/www/html --no-global-configuration --name project-backend --configuration-file=/Users/user/dev/docker/project/backend/.ddev/mutagen.yml] (fork/exec /Users/user/.ddev/.mutagen/bin/mutagen: no such file or directory), output=)
```

macos 11.4
```
 backend (main) ✗ ddev -v
ddev version v1.18.0-alpha1
 backend (main) ✗ mutagen version
0.11.8
```

**Comment by rfay** [comment]
Hi @alechko it would have been easier if you'd opened an issue for this instead of commenting in a closed issue. 

But I think what's going on is you have a running mutagen (version 0.11.8 probably). 

Could you please `ddev poweroff` and `killall mutagen` and see if that fixes it?

If not, please show me the output of the script https://raw.githubusercontent.com/drud/ddev/13c1b6b2914eddeb8d6ba71fea7c019f91d41ac8/scripts/diagnose_mutagen.sh

Also, if you don't need the mutagen from homebrew, could you please uninstall or unlink it? `brew uninstall mutagen-io/mutagen/mutagen` ?

**Comment by alechko** [comment]
Apologies for using the comments and not a new issue!

I did have mutagen installed with brew, after uninstalling it everything worked!

I think this might needs to be mentioned in the docs or in the error message.

Thanks for this feature :)

**Comment by rfay** [comment]
Thanks for the feedback, looking forward to hearing about your experiences. 

Next alpha I don't think will have that same problem.
