### ISSUE TITLE
Add ids to ddev list to improve qol

### ISSUE THREAD

**Issue by AlexTies** [drud/ddev#3048]
**Is your feature request related to a problem? Please describe.**
Well not realy, just a small time save / quality of life improvement

**Describe the solution you'd like**
So if you use the ddev list command, there is no unique id besides the project name assigned to each project. I'd love if the projects where numbered, so that i could use "ddev stop 1" instead of writing "ddev stop my-impossible-long-project-name" 
This would come in handy when you have multiple projects to shut down. Maybe also chaining would be an option. So that i could type "ddev stop 1 2 4" to stop project 1, 2 and 4 while leaving 3 alive. 

**Describe alternatives you've considered**
Maybe if numbering is not possible, short ids or random number between 1 and 1000 would be an option.

**Additional context**
The idea is "copied" from the ubuntu xinput command, there instead of writing the device name i can just use the assigned id

**Comment by rfay** [comment]
The "name" is the unique ID. 

So 
```
$ ddev list
NAME           TYPE     LOCATION                   URL                   STATUS
d9             drupal9  ~/workspace/d9             https://d9.ddev.site  running
ddev-gitpod    drupal9  ~/workspace/ddev-gitpod                          stopped
dockereofdemo  php      ~/workspace/dockereofdemo                        stopped
```

`ddev stop d9` or `ddev stop ddev-gitpod dockereofdemo`

**Comment by rfay** [comment]
I don't think this would work out with numeric IDs, since the project names are already unique, and since commands can be used in many contexts (without `ddev list`). For example. I often just type `ddev start d9` or `ddev ssh d9` without doing a `ddev list` first. 

Closing, happy to continue the conversation here or elsewhere.

**Comment by AlexTies** [comment]
Im not sure if i expressed myself right, so for example we have automatic project names according to naming conventions, for example one project could be called "2018-drupal-8-jobs.expensive-store.com", if every project inside ddev list had an numeric alias it would be a blessing for me because if it would be so i could just refer to the peoject by number instead of having to copy or tipe in the whole name i'd love that

**Comment by rfay** [comment]
I recommend that you use simpler project names, adjust your naming conventions? That would solve the problem. Maybe the fix is on your team's end?
