### ISSUE TITLE
findDirectivesInScriptCommand trims quotes from custom command files, breaks help text of provided commands

### ISSUE THREAD

**Issue by diegoe** [drud/ddev#3051]
**Describe the bug**
In `findDirectivesInScriptCommand`, spaces, quotes, and double quotes, are trimmed from strings in the command description:

```go
    for scanner.Scan() {
        line := scanner.Text()
        if strings.HasPrefix(line, "## ") && strings.Contains(line, ":") {
            line = strings.Replace(line, "## ", "", 1)
            parts := strings.SplitN(line, ":", 2)
            parts[1] = strings.Trim(parts[1], " \"'")
            directives[parts[0]] = parts[1]
        }
    }
```

This breaks the formatting of help lines in the default provided commands (example, `cmd/ddev/cmd/global_dotddev_assets/commands/web/drush`)

```shell
$ ddev drush --help
(...)
Examples:
  ddev drush uli" or "ddev drush sql-cli" or "ddev drush --version
(...)
```

Versus the source:
```shell
#ddev-generated
## Description: Run drush CLI inside the web container
## Usage: drush [flags] [args]
## Example: "ddev drush uli" or "ddev drush sql-cli" or "ddev drush --version"
## ProjectTypes: drupal7,drupal8,drupal9,backdrop
(...)
```

**To Reproduce**
Run commands like `ddev drush --help`

**Expected behavior**
String is passed as is, or at least the provided commands don't fall into this bug.

**Version and configuration information (please complete the following information):**

- macOS Big Sur 10.4
- Docker Desktop version 3.4.0
- ddev version information (use `ddev version`)
```
DDEV-Local version	v1.17.5
architecture      	arm64
db                	drud/ddev-dbserver-mariadb-10.3:v1.17.3
dba               	phpmyadmin:5
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.17.0
docker            	20.10.7
docker-compose    	1.29.2
os                	darwin
router            	drud/ddev-router:v1.17.3
web               	drud/ddev-webserver:v1.17.4
```

**Additional context**

**Comment by rfay** [comment]
Good eye! 

Want to do a PR? You don't even need a development environment to work on it  and test with gitpod. https://gitpod.io/#https://github.com/drud/ddev

More hints in https://github.com/drud/ddev/blob/master/docs/developers/building-contributing.md

**Comment by rfay** [comment]
This was fixed in https://github.com/drud/ddev/pull/3057
