### ISSUE TITLE
ddev logo

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#306]
## What happened (or feature request):

Feature Request

## What you expected to happen:

As we are pushing towards a 1.0 release (and beyond), we'll need a logo specific to ddev. This is a placeholder to get traction on that effort.

Next actions:

* [x] Determine a route to take to get logo ideas (newmedia, 99 designs, etc).
* [x] Draft up an initial set of ideas and guidance to provide to our PM at 99 designs (e.g. type, colors, fonts, etc).
* [x] Kickoff a logo contest.
* [x] Obtain team feedback at appropriate check points.
* [x] Iterate until we land on one we feel proud/excited about.

**Comment by rickmanelius** [comment]
This is a dependency to address first https://github.com/drud/marketing/issues/15.

**Comment by rickmanelius** [comment]
We're proceeding with 99 designs.

**Comment by rickmanelius** [comment]
Regarding the 7 logo types, the following breakdown is quite handy https://99designs.com/blog/tips/types-of-logos/.

My preference (in order) would be:

* Wordmark
* Abstract
* Emblem
* Combination

Mascot, letermark, and pictorial do not feel appropriate.

**Comment by rickmanelius** [comment]
Just throwing it out there. This has been getting some impressive coverage as an AI driven logo generator based on preferences https://logojoy.com/.

**Comment by rickmanelius** [comment]
I'll draft the verbiage for the 99designs contest in a google doc and post here for feedback. Then I would suggest we ship and start seeing what we get back.

**Comment by rickmanelius** [comment]
@cyberswat Here's a design brief for ddev. If you are comfortable with it as is, I'd say let's submit and start generating some logos! https://docs.google.com/document/d/1Lp-e46xI0nC8g3HbDbeLvzgO6slhVPezge-lIZw6DMw/edit#

**Comment by rickmanelius** [comment]
@cyberswat I know DCCO was a priority, but did we hear anything back from this?

**Comment by cyberswat** [comment]
No, we are finishing the previous work before beginning this one.

**Comment by rickmanelius** [comment]
@cyberswat Any chance we can move on this? Alternatively, I'm happy to also reach out to our contact at 99designs directly. Thanks!

**Comment by cyberswat** [comment]
@rickmanelius While your desire to own even more is commendable, it's not necessary.  The conversation for this was started yesterday along with a website and landing page for the product.  The previous work is hopefully concluding today and I promise to update you as soon as there is news.

**Comment by rickmanelius** [comment]
Definitely don't want to own if I don't have to :)

**Comment by rickmanelius** [comment]
This is good to go for now. Other follow-up items exist in the referenced issues.
