### ISSUE TITLE
Gather (Optional/Opt-in) Usage Statistics to Inform Roadmap Decisions

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#307]
## What happened (or feature request):

* Feature Request

## What you expected to happen:

Given that we do not put up any barrier to downloading/using ddev, it would be valuable to have some mechanism to (optionally and with the ability to opt-in/out) have a sense of the total number of active ddev users. Additionally, we could go a step further and gather statistics on the frequency of commands used. Obviously, we will want to sanitize the specific parameters specified so that there are no information disclosures. Still, it would be valuable to know what percentage of end-users use `ddev exec` and how frequently they use it.

More work and discussion would need to happen before this becomes actionable.

## Anything else do we need to know:

Any step in this direction would require us to have an explicit policy around data collection, retention.

## Related source links or issues:

**Comment by rickmanelius** [comment]
Related issue filed by Kevin https://github.com/drud/ddev/issues/315.

**Comment by rickmanelius** [comment]
@cyberswat Some initial thoughts https://docs.google.com/document/d/1Mle2aK0rwdmknz8ynb5Ll86cnIm0OMHIL2Wmd9Er2nY/edit#

**Comment by cyberswat** [comment]
I think this speaks to much more than understanding downloads and active users and want to make sure that is communicated from the beginning.  Those are two metrics that will be useful from the start for us, but the real goal here is to provide additional value to the users of our tools by ultimately making intelligent recommendations based on how they use our tools and the applications they are running.  I've updated the google doc and look forward to moving it's contents into the issue queues.

**Comment by rfay** [comment]
I think [sentry](https://sentry.io/for/go/) would be a nice way to do this. I spent just a little time with it a few months ago, but not enough.

**Comment by rickmanelius** [comment]
@cyberswat I'm onboard/aligned on the overall scope that this is beyond number of installs/downloads, as noted in the doc. Reviewed your notes and it looks like there are no major issues/pushback, so we can start to take the next pass on this in terms of individual features/tickets and any research items that are left (such as @rfay's suggestion of sentry as a means to achieve that end).

**Comment by rickmanelius** [comment]
Removing the "needs decision" label because philosophically we're onboard with this proceeding and the high-level objectives. Now it's time to get specifics together. Because the actual creation of this strategy is, in fact, actionable, I'm also removing the incubate label. We can then reference/link to the issue used to implement said functionality proposed in this issue. That would get this to a finish line.

**Comment by cyberswat** [comment]
Sentry looks like a great way to capture error related issues and the events leading up to them.  It has an on-premise option that allows for customizable storage backends.  It also has the concept of breadcrumbs that will allow us to key custom events for storage.  The hosted version exposes an API that seems like it would allow for us to retrieve data from them.

The ultimate goal with this kind of data is to build a dashboard that we can display to our end users.  Sentry looks like it could save us a lot of time setting the foundation for that type of work.  It looks like the hosted version could work for up to 4,000,000 events per month before we would need to form a special relationship with them or bring it internal.  The starting package gives us 100,000 events per month at a cost of $29.00 per month.  @rickmanelius I'd propose that we begin using sentry to start collecting error information and integrating into the ddev code base while we begin outlining the data points that we would want to surface.

**Comment by rfay** [comment]
[datadog](https://www.datadoghq.com/) might be an additional option. Had forgotten about that. I think sentry has a mighty-fine reputation though.

**Comment by rickmanelius** [comment]
Another item that @beeradb surfaced that might be an easy drop in solution for downloads https://bintray.com/. Also, a reminder on GitHub stats https://github.com/drud/ddev/graphs/traffic.

**Comment by rfay** [comment]
I note that the sirupsen/logrus library, which we mostly use, has explicit support for sentry, among a thousand other things. https://github.com/sirupsen/logrus (See "Hooks")

**Comment by rickmanelius** [comment]
@cyberswat is moving on this with the intro of Bintray. Probably worth changing the scope of this issue to any longer term data/stats goals with Bintry helping us track raw downloads.

**Comment by rickmanelius** [comment]
Updating issue to reflect that this is something that we will need to address sooner in the upcoming ddev roadmap.

**Comment by rickmanelius** [comment]
This should probably be broken up into sub-issues because the larger goal (optional full blown usage collection and reporting) is a significant engineering effort and there is low hanging fruit in simply collecting error reports as specified in the proposal doc attached to this issue. Additionally, there are certain foundational items (notably properly informing end-users of the option of collecting said information and having the appropriate messaging in place) that will also take time and effort.

To that end, I'm going to split out the first child issue to address the following:

* Prompting the ddev user with a request to gather error statistics.
  * Note: default answer is null so they have to consciously type "yes" or "no" instead of just hitting enter.
* Storing of this preference either via a global variable OR a yml file within ~/.ddev/
* Provision a Sentry account https://sentry.io/for/go/.
* Wherever error reporting is called out within the ddev codebase, if data collection is allowed, post to Sentry.
* Data privacy and usage policy on our website, referenced in our documentation, and referenced when a user is asked to provide data.
* Generate a weekly report to post to the ddev product team to review and determine if there are any actionable items.

The above will be refined into true acceptance criteria. Additionally, we will need to file children issues on the gathering and reporting of usage statistics. To that end, I'll leave this issue open as a meta and link the child issues from the summary.

**Comment by rickmanelius** [comment]
Pulling this out of the current sprint in favor of the new child issue #627.

**Comment by cyberswat** [comment]
@rfay Does it make sense to focus on Sentry support for debugging and not focus on additional metrics at this time?  My preference would be to dust off https://github.com/drud/ddev/issues/532, potentially move it to the hosting team, and have that surfaced into a dashboard in our system.  All that we really need to surface for now is how downloads trend over time.  Sentry provides immediate value for the user experience that requires far less complexity.

**Comment by rfay** [comment]
I would *really* like to see some actual usage stats if it comes readily. We keep making decisions about features and bugs based on what our most-active and most-vocal users have to say, and we'd be a lot better able to judge if we had overall usage stats. That said, if we can't get the usage stats easily, then download stats could be useful, but more useful for marketing than feature decisions.

**Comment by cyberswat** [comment]
I would like to see those statistics too and it sounds like logrus provides a robust mechanism to do that.  The download stats certainly could be used for marketing, but the intent of that request in #532 is more focused on requests from investor conversations.

We are going to have a continuous need to aggregate data like this to make informed choices with product roadmaps.  We are working through a bit of technical debt on the hosting side as it relates to a third party vendor used for log collection that we can avoid here.  If it's possible to feed the cli usage data into Prometheus it could give us better control and lower costs than relying on a third party service.  That's potentially a bigger engineering effort, but @jrthrawny could be one to consult once the decision is made.

Sentry provides a nice tidy system with a seemingly specific purpose at what seems like a great price for the service. It wouldn't be disappointing if the only data we get from them is focused on debugging and surfacing problems we aren't seeing.  Curious to see what you recommend after digging in.

**Comment by rfay** [comment]
I spent some time with Sentry today and it definitely can work. I'm optimistic and have some code working. There are some things I don't necessarily understand yet, and it forces a bit of command refactoring, but it should be good.

**Comment by unn** [comment]
Don't mean to throw a wrench in the gears but integration with segment.com would achieve goals of in-ddev error/stacktrace visibility via Sentry but also adds the ability to instrument the application via another tool TBD.

**Comment by rfay** [comment]
Thanks for the recommendation @unn - It looks like segment is about customer data though? And we want to capture activity  more than that. In fact, we explicitly don't want to capture customer data.
