### ISSUE TITLE
RFC: Provide option to run suggested commands after a typo

### ISSUE THREAD

**Issue by AMartinNo1** [drud/ddev#3072]
**Is your feature request related to a problem? Please describe.**
When running a ddev command you sometimes have typo and the current implementation provides suggestions. These are a good help already. However, you still need to fix the previous called command on your own.

**Describe the solution you'd like**
An interactive response:

```bash
Error: unknown command "laucnh" for "ddev"

Suggestions:
        [0] Cancel and fix on your own
        [1] launch

Choose your option:
```

**Describe alternatives you've considered**
Fix the command on your own - current behaviour which is ok but the new approach is more helpful / faster IMO.

**Additional context**
_Can't think of anything._

**Comment by rfay** [comment]
Thanks for the suggestion. We use a [spf13/cobra](https://github.com/spf13/cobra) for all this, I wonder if there's an issue there. You might want to raise one if not, or contribute a PR there?

**Comment by AMartinNo1** [comment]
I will have a look there but I am not familiar with `go`. So I assume I won't find time to do both - dig into go and check their issues for such a feature request.

**Comment by rfay** [comment]
I don't plan to prioritize this, but happy to continue the conversation, and if somebody comes along that can put some effort into it it will be welcomed!
