### ISSUE TITLE
Improve warning message when a project-level shell command overrides global shell command

### ISSUE THREAD

**Issue by bog-h** [drud/ddev#3074]
**Description:**

If a global command need to be updated, you cannot just override it, by placing a copy into the `commands` folder.
 DDEV will notify you each run time about "not adding command ... because it was already added to project" 

**Describe the solution you'd like:**

Prioritise commands from `commands` folder over `.global_commands` folder

**Describe alternatives you've considered:**

Alternatively we can add in the` config.yaml` array of
exclude_global_commands: [
'artisan',
'blackfire'
]

**Additional context**

![image](https://user-images.githubusercontent.com/40270849/123750773-a7c52380-d8bf-11eb-914a-853e712de865.png)

**Comment by rfay** [comment]
Hi @bog-h - The way you override a global command is in ~/.ddev/commands. Remove the #ddev-generated in the command you want to override there. 

Does that answer your question?

**Comment by rfay** [comment]
You never will change anything in .global_commands, ever. That's why it's hidden.

Global commands are defined in ~/.ddev/commands (that's in the .ddev folder in your home directory). Please change them there.

**Comment by bhmarnii** [comment]
@rfay I appreciate your help but looks like you don't read my text and don't look at the screenshot where I even marked it with red lines to make it more comfortable to the reader.

Please say how to override `.global_commads/web/artisan`, if you want to tell me to create` commands/web/artisan` then please look at the screenshot and read the topic again.

If you would like to say that I need to remove a comment from `commands/web/artisan` then please look at the screenshot and read the topic again.

No offense, but I think you didn't read the topic well or I totally cannot understand your advice, sorry.

**Comment by bhmarnii** [comment]
> Here's how this works.
> 
> * There are two kinds of shell commands, global and project.
> * Global commands are stored in your home directory, in the .ddev folder. So for example, the artisan command is in ~/.ddev/commands/web/artisan. If you want to override it, you would override it there by removing the #ddev-generated line from it. Then ddev will continue to use it but won't overwrite it.
> * Project-level commands are stored in your project directory, in .ddev/commands/web. If you happened to have an "artisan" command there, it will override the global one, but will complain and let you know that it's overriding.
> * The project .global_commands is a temporary copy of the global commands from your home directory. It's copied from the home directory global area on every `ddev start` and probably some other commands. It's not intended to be viewed or for you to even know it exists.
> 
> A PR with edits to the [docs](https://ddev.readthedocs.io/en/stable/users/extend/custom-commands/) is welcome, you just click the pencil in the upper right.
> 
> You override the global artisan command by editing it in your home directory in ~/.ddev/commands/web/artisan, and removing the #ddev-generated line.

Thank you for the clear explanation!

The issue may be closed, however, I would like to say that it may be not a good idea to:
 
" If you happened to have an "artisan" command there, it will override the global one, **but will complain and let you know that it's overriding.**"

Because it is the reason why this issue was created, I was sure that I did something wrong, with every run of my overridden command DDEV blames me starting with the phrase "not adding command.." and it looks like an error to be honest, at least adding "Info: your message" can help.

**Comment by rfay** [comment]
I think the basic thing is that the message needs to refer to the actual global command.

Currently it says

> not adding command drush (/Users/rfay/workspace/d9/.ddev/.global_commands/web/drush) because it was already added to project d9

It should say

> not adding global command drush (~/.ddev/commands/web/drush) because it was already added at the project level in project d9
