### ISSUE TITLE
Error with documentation - Git Clone installation

### ISSUE THREAD

**Issue by begrafx** [drud/ddev#3082]
This is the first time I've tried the "Git Clone" method, and I find an issue.

Following the "Drupal 9 Git Clone Example" instructions in the documentation, (https://ddev.readthedocs.io/en/stable/users/cli-usage/#drupal-9-quickstart) 

`Drupal 9 Git Clone Example¶

Note that the git URL shown below is an example only, you'll need to use your own project.

git clone https://github.com/example/example-site
cd example-site
ddev composer install
ddev launch
`
I  clone the GIT image, change into that directory, and, as instructed, issue the `ddev composer install` command. I receive the following message.

`Could not find a project in /[MyPath]/[MyProject]. Have you run 'ddev config'? Please specify a project name or change directories: no .ddev/config.yaml file was found in this directory or any parent`

I had thought it odd that there was no `ddev config` process, as with the "composer setup example". In checking, this issue exists from the documentation that I printed from August of 2020, and still exists in the current docs linked above.

**Comment by rfay** [comment]
I guess people haven't been using it :) You have to `ddev config`. 

What to try a PR? You just click the little pencil in the upper right of the doc page.

**Comment by begrafx** [comment]
Sure! Glad to help.

**Comment by begrafx** [comment]
A quick question (unrelated to the topic at hand, but not really worthy of a whole separate issue); I'm looking at setting up a Drupal project that is designed to work with Docksal. I know that Docksal is similar to DDEV, in how it works with Docker, etc. I'm wondering, if I set up this Docksal project, are you aware of any conflicts/issues that might be created between Docker and DDEV? Or will everything "play well together"?

**Comment by rfay** [comment]
ddev is built to try to avoid conflicts with other systems, so its settings are wrapped by $IS_DDEV_PROJECT. In general if you `ddev poweroff` before using it with docksal, and `fin poweroff` before using it with ddev, you'll be fine.

**Comment by begrafx** [comment]
Thanks Randy. You're always there with the answer. Much appreciated.

**Comment by rfay** [comment]
It's possible that docksal gets in ddev's way by generating unwanted config; I've tried this with lando with success, but haven't tested it with docksal.
