### ISSUE TITLE
How to change the Project URL after configured the project

### ISSUE THREAD

**Issue by naresh-qed42** [drud/ddev#3088]
Project Folder: `~/ddev-projects/drupal-8-composer`
after Setup Project
Current Site URL: `https://drupal-8-composer.ddev.site`

I want to just change the URL of the project with `https://local-subscriber.ddev.site` without changing the folder name `drupal-8-composer`

Thanks in advance :)

**Comment by rfay** [comment]
Hi @naresh-qed42 - Export the database, delete the project, change config.yaml (project name, hostnames if any), and start.

```
ddev export-db --file=/path/to/db.sql.gz
ddev delete 
ddev config --project-name=newname
ddev start
ddev import-db --src=/path/to/db.sql.gz
```

**Comment by naresh-qed42** [comment]
thanks @rfay , it worked 👍
