### ISSUE TITLE
Activate SSL client certificate checking (X.509) in Nginx custom config doesn't seem to work

### ISSUE THREAD

**Issue by juban** [drud/ddev#3089]
https://gist.github.com/juban/f3bd2a0670e1ec835e32a0c0e89da3f5

**Describe the Problem**

I'm trying to activate SSL client certificate checking in Nginx configuration by adding `ssl_client_certificate` and `ssl_verify_client` properties to the `.ddev/nginx_full/nginx-site.conf` file (I removed the comment so the file in not overwritten by ddev).

A custom CA certificate has been created and a client certificate signed with it. `ssl_client_certificate` point to the custom CA certificate.

When restarting Nginx with the new configuration, it is loaded normally. However, when accessing the ddev host, no client certificate is required when `ssl_verify_client ` is set to `on`. In other words, the expected 400 error is not thrown by Nginx though it should.

**To Reproduce**

* Create a custom CA certificat with openssl (as in https://gist.github.com/mtigas/952344 for exemple).
* Edit the `.ddev/nginx_full/nginx-site.conf` file and remove the ddev comment and add `ssl_client_certificate` and `ssl_certificate_key` as follow (exemple): 
```
...
    ssl_certificate /etc/ssl/certs/master.crt;
    ssl_certificate_key /etc/ssl/certs/master.key;

    # SSL client certificat configuration
    ssl_client_certificate /var/www/html/certs/mycustom_ca.pem;
    ssl_verify_client on; # Set to "on" if you only allow authenticated requests
    ssl_verify_depth 2;

    include /etc/nginx/monitoring.conf;
...
```
* Restart ddev
* Access the ddev host. No client certificat is required and public pages are accessible without any client certificate.

**Additional context**

As suggested by Randy Fay, the issue is probably related to the way ddev-router handle the request but I could not found a way to workaround that yet.

**Comment by rfay** [comment]
Thanks for opening the issue! Your changes will definitely have to be made to ddev-router if you're going through it (going through *.ddev.site or whatever). However you could make this kind of change and use the localhost URL (See `ddev describe` for that.)

But you could probably accomplish this with the overrides that are available for ddev-router, but it's an unusual thing to do.

What is it you're trying to accomplish? If it's just testing client cert validation, you might be happy with the localhost https URL.

**Comment by juban** [comment]
Thank you for your fast reply.
It is working by accessing the localhost URL \o/. Thank you for the suggestion!

My use case is trying to activate client certificate checking for a PHP API access. So for testing purpose, that will do the trick indeed.

However, I'm curious how I could override the router configuration to handle that with the ddev hostname? Have you a documentation or any exemple?

**Comment by rfay** [comment]
You can add a .ddev/router-compose.*.yaml and override features of the .ddev/.router-compose.yaml, meaning you can mount config in there. Usually doing it means understanding the generated nginx config though.

**Comment by juban** [comment]
I will try to take a look at that.
Thank you again for your help.

**Comment by rfay** [comment]
One thing you should be aware of... In a real production site, https termination is often on a reverse proxy or load balancer just like ddev-router. So you may very well have the same problem in production. But you're the one that knows your production situation.
