### ISSUE TITLE
unable to follow Pantheon instructions

### ISSUE THREAD

**Issue by bradbulger** [drud/ddev#3090]
Looking at the Pantheon Hosting Provider Integration docs, I get to this point

> In your project's .ddev/providers directory, copy pantheon.yaml.example to pantheon.yaml and edit the project environment variable under environment_variables. It will be in the format <projectname>.<environment>, for example yourprojectname.dev or (in cases of ambiguity) <project_uuid>.<environment>, for example 009a2cda-2c22-4eee-8f9d-96f017321555.dev.

I am setting this up using ddev 1.17.6. There is no .ddev/providers directory in my project. I see from #2826 that integration was recently updated, and I found cmd/ddev/cmd/dotddev_assets/providers/pantheon.yaml.example in the code. I copied that to .ddev/providers/pantheon.yaml in my project and that seemed to work. I was able to run `ddev pull pantheon` successfully.

I wasn't sure if this was a bug or a support request. Is there some global configuration thing I'm supposed to have done that the Pantheon document is assuming has already happened, maybe?

**Comment by rfay** [comment]
After you do a `ddev start` once you'll have a .providers directory.

**Comment by bradbulger** [comment]
Ah. I did think it was odd that the instructions skipped from ddev config to ddev **re**start. So I guess that's a missing step? Between existing 7 and 8?

**Comment by rfay** [comment]
I think the assumption is that someone would have started the project sometime in the past, not try to integrate a project before it had even been started. 

A PR to improve it is welcome, of course.

**Comment by bradbulger** [comment]
I thought ddev config was the command to create a ddev project, though? Yeah it is not at all clear that this is all meant to be taking place inside an already existing project, since I just created the directory of code with a git clone command in a previous step. I don't understand the assumed flow of steps in time there. I know that "well go fix it yourself" is the default solution but if I understood it well enough to write the documentation I wouldn't be here.

**Comment by rfay** [comment]
It sounded like you had a good suggestion :) You can just click the pencil in the upper right of the docs page to add a `ddev start` to the config, or change `ddev config` to `ddev config && ddev start`. 

I guess I never thought anybody would be adding Pantheon integration to a project that had never even been started. I sure recommend that you get familiar with ddev and do simple things like `ddev start` and related commands first, get everything going, before you do a `ddev pull`.

**Comment by bradbulger** [comment]
If I figure out something to recommend, I will open a bug report(?) to tie to a pull request.

For what it's worth, where I am coming from is, here is this project that already exists in Pantheon, I sure would like an easier way to work on it locally, oh maybe I'll try ddev. The Pantheon part came first.

**Comment by rfay** [comment]
Happy to help you get where you're going! Feel free to continue here or in any of the other support channels, https://ddev.readthedocs.io/en/stable/#support-and-user-contributed-documentation

Did you watch @mariohernandez  recent screencast on this? https://www.youtube.com/watch?v=uochIVLwBL4
