### ISSUE TITLE
Consider actual ssh as mechanism for ssh access to web container (run sshd inside web container)

### ISSUE THREAD

**Issue by rfay** [drud/ddev#3097]
Lots of people would have an easier time understanding and using ssh if `ddev ssh` actually involved ssh access.  For example, https://github.com/drud/ddev/issues/2510 could work with agent forwarding, and PhpStorm and related tools could use ssh. 

See https://github.com/drud/ddev-contrib/blob/master/recipes/sshd

See https://susi.dev/ddev-phpstorm-integration

**Comment by rfay** [comment]
I did a little experimentation with this. I think this approach would work:
* Generate a key and put it in ~/.ddev (probably ~/.ddev/.id_rsa)
* Start sshd in the web container; probably run it under supervisord
* Provide pubkey in the generated user

**Comment by weitzman** [comment]
This would be surprising to me and possibly many others. PHPStorm already works well with Docker containers, including those started by ddev.

**Comment by rfay** [comment]
Related:
#3130

Now that PhpStorm can exec into containers instead of just start them, ssh would most likely be slower. There do seem to be some cases where people want real ssh, but that doesn't mean that we need to implement the `ddev ssh` command in terms of that.

**Comment by rfay** [comment]
We won't do this, but improving the "regular" ssh feature described in ddev-contrib will be excellent. Should be easy to do with a `ddev get` recipe.
