### ISSUE TITLE
`ddev-router` does not work on VM with proxy after update from 1.16.* to 1.17.*

### ISSUE THREAD

**Issue by dguhl** [drud/ddev#3098]
[Full Gist Diagnostic](https://gist.github.com/dguhl/f23b64dbd2bb0a17be0c006e6f501ee3)

After upgrading from v1.16.7 to v1.17.7, the ddev-router does not work anymore. DDev is running on a VirtualBox Debian 10 buster behind a LAN proxy.

`ddev-router failed to become ready; debug with 'docker logs ddev-router'; logOutput=, err=health check timed out: labels map[com.docker.compose.service:ddev-router] timed out without becoming healthy, status=`

1. Install a VirtualBox VM with Debian 10 Buster
2. Configure proxy.
3. Create DDev config
4. Start DDev

It's not possible to downgrade, as ddev-homebrew is not versioned.

**Expected behavior**
The DDev containers start up and work just fine.

**Version and configuration information (please complete the following information):**

- Windows 10 with VirtualBox and Debian 10 Buster
- 1.17.7
- php and mysql project config
- no custom config
- LAN proxy to route through (I cannot get rid of that one, so don't "fix" it by suggesting it)

**Additional context**
It would have been more helpful for users if the Homebrew receipt would copy the versioning from the main project so that `brew` versioning could be utilized properly to work around untested new versions.

**Comment by rfay** [comment]
Please provide a gist with the output of `docker logs ddev-router` as the error message says. 

Could you say a bit about why you're using Virtualbox instead of WSL2, which has a far more likely future?

Your gist shows a completely different problem (duplicate mount for /var/lib/mysql) which is often seen on older versions of docker-compose like Debian 10 ships with. You can fix that issue by upgrading docker-compose with either `pip3 install docker-compose` or by downloading the binary from docker's site. IIRC this is an intermittent problem.

So let's get to where it starts up and get to the ddev-router problem, and see what the logs from ddev-router say.

**Comment by dguhl** [comment]
> Please provide a gist with the output of `docker logs ddev-router` as the error message says.

[Here is the gist you requested](https://gist.github.com/dguhl/495810065d6e93dcae369155547fe47d). To me, it was not telling at all, which is why I left it out in the first place.

> 
> Could you say a bit about why you're using Virtualbox instead of WSL2, which has a far more likely future?

I am in a migration team helping a company to migrate their software production away from VirtualBox towards WSL2. The latter just recently cleared the company's bar for a feasible process during ongoing production, and that triggered the internal preparations to follow that process. DDev enables us to quickly draw a containerized environment around our products and cave them out the former VirtualBox environment. 

> 
> Your gist shows a completely different problem (duplicate mount for /var/lib/mysql) which is often seen on older versions of docker-compose like Debian 10 ships with. You can fix that issue by upgrading docker-compose with either `pip3 install docker-compose` or by downloading the binary from docker's site. IIRC this is an intermittent problem.

I use the docker-compose package from Docker's APT sources, not from the maintainers. The duplicate mount can easily be solved if I were just removing the ddev-generated images. You ignored the earlier error in the same gist, which I outlined above:
`ddev-router failed to become ready; debug with 'docker logs ddev-router'; logOutput=, err=health check timed out: labels map[com.docker.compose.service:ddev-router] timed out without becoming healthy, status=`

**Comment by rfay** [comment]
Here's what I need for the ddev-router timeout:

`docker inspect --format "{{json .State.Health }}" ddev-router`

Please make sure it's not just slow. Do a `ddev list` a minute or two after the start.

**Comment by rfay** [comment]
I'm pretty sure you're using `apt-get install docker-compose`, which is just the Debian packaging (very, very old) of docker-compose. We can confirm that with `docker-compose --version`. Docker does not package docker-compose with their repositories at this time, never have to date, although they plan to.

**Comment by rfay** [comment]
I did a PR to bump the minimum required, https://github.com/drud/ddev/pull/3099, but in the process noted that the [ddev Debian installation instructions](https://ddev.readthedocs.io/en/stable/users/docker_installation/#linux-installation-docker-and-docker-compose) do already tell you to install docker and docker-compose from Docker using their technique, not to use the built-in docker and docker-compose on Debian 10. Obviously I should have updated the minimum version when I updated that doc.

**Comment by dguhl** [comment]
I uninstalled the faulty docker-compose version from the distro maintainers to reinstall it from GitHub. I re-run the test script and [created a new gist with their output](https://gist.github.com/dguhl/8f65edefc808f165f2d601d8fc82d49d). (Unfortunately, it's the same error, just without any report of double mounts.) 

I also ran inspection and created the gist output [here](https://gist.github.com/dguhl/e527d01cbead5b12f4fa62cb8171b08a).

**Comment by rfay** [comment]
Now it looks like your web container is failing, and maybe that's the whole thing. Make sure you do a `ddev poweroff` before testing things, as you have quite a number of things going now.

The last thing I see from the healthcheck in your web container is
`{"Start":"2021-07-12T18:45:52.624928183+02:00","End":"2021-07-12T18:45:52.72261712+02:00","ExitCode":1,"Output":"phpstatus: FAILED /var/www/html: OK mailhog: FAILED "`

So it looks like the healthcheck script is failing. I think that container should still be running in this case, so you should be able to `ddev ssh <projectname>` or if it won't let you, `docker exec -it ddev-<projectname>-web bash` and you can then run the healthcheck script manually with `bash -x /healthcheck.sh` and see what it's saying. 

You haven't mentioned the web container timing out in your previous descriptions of this problem. Is this the same as what you're seeing on your project?

I'm happy to do a call with you on this so we can look at it together. I'm on US Mountain time, UTC-7. Looks like you're on CET so it's already getting late in your day, but if you want to take a look still today we can.

**Comment by rfay** [comment]
Looking back at your original gist, I see that you installed docker with homebrew; that may be OK, but it's not the recommended technique. Did you reinstall both Docker and docker-compose using the Docker.com instructions?

**Comment by dguhl** [comment]
> Now it looks like your web container is failing, and maybe that's the whole thing. Make sure you do a ddev poweroff before testing things, as you have quite a number of things going now.

All I really have going on DDev in this machine was run and generated by the test script recommended for diagnosis. Everything else was off and removed and DDev only resides for diagnosis on the system now. The project I transform now will use `docker-compose` directly, as there is no problem in running that and the problem I described in this issue did not exist in 1.16 of DDev. 

After the company behind DDev closed down, the company I work for had to be convinced to wait for any further development of this project before making the decision to exclude and replace DDev as part of the process. The advantage of DDev really was its easy rollout and manageability by developers with little to no pre-existing knowledge, but if we weren't able to quickly call off an update of DDev to continue using an older version, just because any force-updated current version would brick the setup, this would be another big no for DDev and we would probably need to give up DDev for the transformation process then.

> I'm happy to do a call with you on this so we can look at it together. I'm on US Mountain time, UTC-7. Looks like you're on CET so it's already getting late in your day, but if you want to take a look still today we can.

Thank you for this kind offer but for strict NDA reasons we would not be able to make that call. We would really just be happy to be able to go back to 1.16 of DDev until 1.17 has been properly tested.

> You haven't mentioned the web container timing out in your previous descriptions of this problem. Is this the same as what you're seeing on your project?

If the container listing says the containers are "done", I do not assume that there is a problem. Also, it does not make sense to run in this very same problem no matter where I create a new ddev configuration on the machine. It also happens on other VMs.

> Looking back at your original gist, I see that you installed docker with homebrew; that may be OK, but it's not the recommended technique. Did you reinstall both Docker and docker-compose using the Docker.com instructions?

That I did. If docker was also installed by Homebrew, it must have been part of any installation process in Homebrew, as a dependency for example.

**Comment by rfay** [comment]
ddev v1.17 has been out for many months now (since April) so I expect that this is a configuration error or perhaps some weird thing about Virtualbox (but I doubt it). Perhaps you're mounting on a non-native filesystem. Anyway, if you can't accept direct help, you can do the things suggested in https://github.com/drud/ddev/issues/3098#issuecomment-878469916 - When you get into the web container, you should be able to run that healthcheck script and see what's going on.

But nothing you've demoed for me at this point is related to the original complaint, as far as I can tell.

You can also just `ddev poweroff && mkdir junk && cd junk && ddev config --auto && ddev start` and see what happens. If you get this same issue, it probably means php-fpm just isn't working, so that could actually be a problem with permissions on ports in the containers, so could possibly be something about virtualbox, but again, I doubt it.

**Comment by dguhl** [comment]
> Perhaps you're mounting on a non-native filesystem.
As a matter of fact, this error appears on when DDev config resides on both a Linux native file system and vboxsf, a VirtualBox emulated filesystem for external mount, as well.

> When you get into the web container, you should be able to run that healthcheck script and see what's going on.
I will run this healthcheck in office hours tomorrow (CEST), but as all the current outputs on our table here tell you as much as they tell me, I doubt that the healthcheck would output any significant hint to the problem.

In general, all errors regarding double database mounts or a Docker installation coming from Homebrew instead of APT would bare no reason why the router (which is somewhat of a withstanding component) would not start.

**Comment by rfay** [comment]
Right, you haven't yet showed me a situation where the router won't start. I'm hoping you can demonstrate that at some point. The earlier demo you did was a db container failure, the most recent was a web container failure.

**Comment by rfay** [comment]
Since you're on the way to WSL2 (which is fully supported) from Virtualbox (which is way not supported) you might be able to stay with v1.16 until you're on WSL2. But I have no clue why there would be any difference in behavior of the router between 1.16 and 1.17. But like I say... you haven't yet demonstrated the error you originally reported.

**Comment by rfay** [comment]
The router can't come up until your db and web containers come up.

**Comment by dguhl** [comment]
> you haven't yet demonstrated the error you originally reported.

Except that I did. The error appears in both demos, way before any other error, for example in line 40 [in this one](https://gist.github.com/dguhl/f23b64dbd2bb0a17be0c006e6f501ee3).

> The router can't come up until your db and web containers come up.

Again, then the DDev diagnosis script does not create proper db and web containers.

**Comment by rfay** [comment]
I'm trying to help you. You'll have to play along. 

Go ahead and try the simplest project I suggested, a junk project with no contents.

**Comment by dguhl** [comment]
> I'm trying to help you. You'll have to play along.

And you have to believe me when I give you feedback after following your instructions. Here is the gist of the "junk" test you gave me earlier: ["Junk" test](https://gist.github.com/dguhl/83322e50a207ebd0690efdfa7cd7e89e)

It also ends with a router fail. 

The health check states "phpstatus" and "mailhog" failed.

**Comment by rfay** [comment]
The router can't come up because the web container has failed. Ddev waits for the "all OK" from the web container. 

Now please do what I suggested and `ddev ssh` or `docker exec -it ddev-<project>-web bash` and try to figure out why the healthcheck script fails. Run `bash -x /healcheck.sh` and give it a shot.

**Comment by dguhl** [comment]
> Now please do what I suggested and ddev ssh or docker exec -it ddev-<project>-web bash and try to figure out why the healthcheck script fails. Run bash -x /healcheck.sh and give it a shot.

I did that already, it's in the three last lines of that last gist I gave you.

**Comment by rfay** [comment]
(I see you did a `bash +x`, you want to do a `bash -x`. Oddly, `bash -x` turns debug output on, and `bash +x` turns it off.

**Comment by rfay** [comment]
And you'll need to use your debugging skills inside the container to figure out why those are failing. You'll want to look at php-fpm's status and the nginx and php-fpm configuration. Obviously I would help you with this.

**Comment by dguhl** [comment]
> (I see you did a bash +x, you want to do a bash -x. Oddly, bash -x turns debug output on, and bash +x turns it off.

Nice, did not know that. I updated [the last gist](https://gist.github.com/dguhl/83322e50a207ebd0690efdfa7cd7e89e).

> And you'll need to use your debugging skills inside the container to figure out why those are failing. You'll want to look at php-fpm's status and the nginx and php-fpm configuration. Obviously I would help you with this.

Alright, no problem. The services of the junk project report back just fine:
```
root@junk-web:~# service --status-all
 [ - ]  apache-htcacheclean
 [ - ]  apache2
 [ - ]  blackfire-agent
 [ ? ]  hwclock.sh
 [ + ]  nginx
 [ + ]  nginx-debug
 [ - ]  php5.6-fpm
 [ - ]  php7.0-fpm
 [ - ]  php7.1-fpm
 [ - ]  php7.2-fpm
 [ - ]  php7.3-fpm
 [ + ]  php7.4-fpm
 [ - ]  php8.0-fpm
 [ - ]  procps
 [ - ]  rsync
 [ - ]  sudo
 [ + ]  supervisor
 [ - ]  x11-common
root@junk-web:~# service php7.4-fpm status
[ ok ] php-fpm7.4 is running.
root@junk-web:~# service nginx status
[ ok ] nginx is running.
root@junk-web:~#
```

Could it be that the services report back their success just too slow? Is the `sleeptime` of 59 maybe too short?

**Comment by rfay** [comment]
Your next task is to figure out why `curl --fail -s 127.0.0.1/phpstatus` fails. Just `ddev ssh` into the web container and debug that.

**Comment by dguhl** [comment]
I did that and I found out that if I replace the IP `127.0.0.1` with `localhost`, I can get mailhog and phpstatus.

**Comment by rfay** [comment]
So do you have a VPN or something that is rerouting traffic to 127.0.0.1?

What does `ping -c 1 localhost` show you?

**Comment by dguhl** [comment]
I have no VPN in my VM nor the host system there. I mentioned the LAN proxy in my initial report.

> What does ping -c 1 localhost show you? (inside the container)

```bash
guhl@junk-web:/var/www/html$ ping -c 1 localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.033 ms

--- localhost ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.033/0.033/0.033/0.000 ms
guhl@junk-web:/var/www/html$
```

**Comment by dguhl** [comment]
Could we have some bootstrapping problem here? The router is not there so the curl calls won't be dispatched, and since the curl calls won't be dispatched, the router won't come up?

**Comment by rfay** [comment]
Curl here is entirely within the web container, the router is not involved in any way. If you can curl 127.0.0.1 and you can't curl localhost... something is wrong with your networking/docker. 

Why don't you show the difference between `curl -I localhost/phpstatus` and `curl -I 127.0.0.1/phpstatus`

**Comment by dguhl** [comment]
> If you can curl 127.0.0.1 and you can't curl localhost... something is wrong with your networking/docker.

It's the other way round. Here's the difference between the curls:
```
guhl@junk-web:/var/www/html$ curl -I localhost/phpstatus
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 12 Jul 2021 19:57:00 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
Vary: Accept-Encoding
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: no-cache, no-store, must-revalidate, max-age=0

guhl@junk-web:/var/www/html$ curl -I 127.0.0.1/phpstatus
HTTP/1.1 503 Service Unavailable
Server: squid/3.5.23
Mime-Version: 1.0
Date: Mon, 12 Jul 2021 19:57:08 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 3625
X-Squid-Error: ERR_CONNECT_FAIL 111
Vary: Accept-Language
Content-Language: en
X-Cache: MISS from firewall2017
X-Cache-Lookup: MISS from firewall2017:3128
Via: 1.1 firewall2017 (squid/3.5.23)
Connection: keep-alive

guhl@junk-web:/var/www/html$
```

I repeated the IP calls and it is in fact the case that the LAN proxy informs me that it could not retrieve `"http://127.0.0.1:8025/"`, means that the IP call 

However, of course I have set localhost as well as 127.0.0.1 in the the conventional `$no_proxy` variable of the linux host's shell profile, but the DDev container does not take the no_proxy list from its host but creates its own:

```
guhl@junk-web:/var/www/html$ echo $no_proxy
127.0.0.0/8,localhost
```

IP class range notation is an invalid notation for the no_proxy list and it explains why curls on localhost work but curls on the IP do not.

**Comment by rfay** [comment]
There's the problem, "Server: squid/3.5.23"

You have 127.0.0.1 taken over by a squid proxy. There is no usage of squid anywhere in ddev. So your network/docker is routing 127.0.0.1 to somewhere it shouldn't. 

Please exclude 127.0.0.1 from your proxy settings in the docker configuration.

**Comment by rfay** [comment]
https://github.com/drud/ddev/commit/98e02d692a802ba48b0ea0851da55b46bace13bb

**Comment by dguhl** [comment]
It's excluded since the beginning.

```
guhl@marseille:~/junk$ cat ~/.docker/config.json
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://192.168.0.1:3128",
     "httpsProxy": "http://192.168.0.1:3128",
     "noProxy": "127.0.0.1,localhost"
   }
 }
}
guhl@marseille:~/junk$
```

`noProxy` was running with the IP range notation which was documented to work for Docker, but the container directly took that over for its own no_proxy configuration, so I changed the IP to simply .1

I rerun the whole "junk" rollout, and this gist is very weird: [weird output](https://gist.github.com/dguhl/af565ed33ab22e9a1afdefed2cb599d4)

Here is what's weird: I deleted the "junk" test and repeated a new instance for the "junk" test and it did not work until I also repeated the health check manually in the container - I would have expected that when I run a new configuration, the health check would result differently, not to what has been there before.

**Comment by dguhl** [comment]
The ddev-router image in docker, as well as the container, would have to be manually removed and recreated to make the health check work.

**Comment by rfay** [comment]
`ddev poweroff` is your friend. That kills off all containers. It's very unusual to have to delete images, but I've seen it happen. Images in a normal world are just static files downloaded by dockerhub, and of course are unrelated to any proxy configuration.

But it sounds like you have it working now?

I saw this once before, but it was the opposite - they were proxying localhost by accident, and only 127.0.0.1 would work. At that time we changed the healthcheck to use the IP address :)

**Comment by dguhl** [comment]
> ddev poweroff is your friend. That kills off all containers.

So you would think. But it did neither stop nor remove the `ddev-router`.

> Images in a normal world are just static files downloaded by dockerhub, and of course are unrelated to any proxy configuration.

Unless these downloads are derived to alter configurations, say, from the host's docker configuration. I am sure it's not optimal, either only a few distributions or Docker itself would support an IP range notation like /8, as they document it as a working configuration, but `ddev-router` would take over that range notation without ensuring it would even work with its base.

> But it sounds like you have it working now?

```
Digest: sha256:30bf3f056210d258dadf64ba155f06513c3e46410b0444fd681bb656c575bc28
Status: Downloaded newer image for drud/ddev-router:v1.17.6
docker.io/drud/ddev-router:v1.17.6
Building ddev-ssh-agent
Creating ddev-ssh-agent ...
Creating ddev-ssh-agent ... done
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
Pushed mkcert rootca certs to ddev-global-cache/mkcert
Running   Command=ip address show dev docker0
Building db
Building web
Creating ddev-junk-db ...
Creating ddev-junk-db ... done
Creating ddev-junk-dba ...
Creating ddev-junk-web ...
Creating ddev-junk-dba ... done
Creating ddev-junk-web ... done
Creating ddev-router ...
Creating ddev-router ... done
Project type has no settings paths configured, so not creating settings file.
Project type has no settings paths configured, so not creating settings file.
Successfully started junk
Project can be reached at https://junk.ddev.site https://127.0.0.1:49167
guhl@marseille:~/junk$ nano index.htm
guhl@marseille:~/junk$ curl https://127.0.0.1:49167
<h1>Issue 3098 resolved!</h1>
guhl@marseille:~/junk$
```

> they were proxying localhost by accident, and only 127.0.0.1 would work. At that time we changed the healthcheck to use the IP address :)

I would not recommend to change it back or change it in any other way, as the current configuration is basically working. I only recommend to check if the underlying system would support as `no_proxy` what Docker allows for a noProxy configuration, which would be an IP address like `127.0.0.0/8` - in the system we were testing here, this was just not supported.

And maybe it is possible to include a basic loopback check on 127.0.0.1 and localhost if a proxy is present.

**Comment by rfay** [comment]
The resolution here for anybody who might stumble upon it: Docker was misconfigured with inappropriate proxy addresses, and that cause the ddev-webserver healthcheck to be sent off to a squid proxy instead of staying inside the container. https://github.com/drud/ddev/commit/98e02d692a802ba48b0ea0851da55b46bace13bb adds to the docs to add turning off any proxy configuration in the troubleshooting phase.

**Comment by dguhl** [comment]
Actually, Docker [allows for configurations](https://docs.docker.com/network/proxy/#configure-the-docker-client) which would not be allowed in the container. The word "misconfiguration" is misleading. For troubleshooting, I did not turn off any proxy configuration but changed it into a configuration which was accepted by the `ddev-router`.

**Comment by rfay** [comment]
ddev-router wasn't involved in this at all. All of your docker containers were broken by this, as they all have healthchecks. The problem was due to proxy misconfiguration. I'm glad you got it sorted out. If you think there's a bug in what docker allows, please open an issue there.

**Comment by dguhl** [comment]
> ddev-router wasn't involved in this at all. All of your docker containers were broken by this, as they all have healthchecks.
ddev-router receives bad healthchecks even if the configuration was changed. They either were to be manually repeated on each of the containers or the containers were to be completely rebuilt with `ddev poweroff && ddev delete images && ddev start`.

I also opened this issue with the specific note that some users cannot get rid of their LAN proxy, for example in a company environment or other networks they lack control of. The solution would _not be_ to remove the proxy configuration for Docker completely. It's completely the opposite direction of what I did.

**Comment by rfay** [comment]
Again, this was the result of docker proxy misconfiguration. Again, if docker allowed you to misconfigure it, please open an issue with docker. Please be thankful for all the support you got with your misconfiguration problem and let this die.

**Comment by dguhl** [comment]
Well thank you for helping me working around a ddev compatibility problem with legitimate Docker environment configurations. I didn't have it with any other container, so I don't see the point to report an issue there.

**Comment by rfay** [comment]
For those who might want to configure for a web proxy in the future, there are instructions here: https://github.com/drud/ddev-contrib/tree/master/recipes/proxy
