### ISSUE TITLE
import-files and import-db report a failure for .tar format, succeed for .tar.gz format.

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#310]
## What happened (or feature request):

* Bug

```
$ ddev import-files --src=sdf_files.tar
2017/06/12 16:14:04 ERROR:invalid argument
```

```
$ ddev import-db --src=sdf_files.tar
2017/06/12 16:17:21 ERROR:invalid argument
```

## What you expected to happen:

Given `ddev import-files --help` states "The files can be provided as a directory
path or an archive in .tar, .tar.gz, .tgz, or .zip format.", I would expect that I can import a .tar file for either files or database.

## How to reproduce it (as minimally and precisely as possible):

* See attached files.tar and files.tar.gz
  * These were produced as follows:
     * On macOS, create folder1/folder2/folder 3 file structure.
     * `tar -cvf files.tar folder1`
     * `cp files.tar files2.tar && gzip files2.tar && mv files2.tar.gz files.tar.gz`
* `ddev start` a vanilla drupal 7.54 app (should not matter, but this is what I tested).
* This shows a success message `ddev import-files --src ~/Desktop/files.tar.gz`
* This shows a fail message `ddev import-files --src ~/Desktop/files.tar`
* It should be worth noting that the import does appear to work despite the failure message.

[files.tar.gz](https://github.com/drud/ddev/files/1069666/files.tar.gz)

It turns out you can't upload a standard .tar to a GitHub issue, but you should be able to simply create a copy and unzip the .tar.gz attachment.

**Comment by rfay** [comment]
I confirm this, I see the rather obscure:
```
2017/06/12 16:14:30 ERROR:invalid argument
```

Is that the same failure you saw @rickmanelius ?

**Comment by rickmanelius** [comment]
@rfay Yup, that's basically the error.

**Comment by rickmanelius** [comment]
PR succeeds. Not sure if Tanner needs to weigh in at a code level, but this false warning is now gone!
