### ISSUE TITLE
PHP_IDE_CONFIG - dont set via .bashrc

### ISSUE THREAD

**Issue by weitzman** [drud/ddev#3106]
**Is your feature request related to a problem? Please describe.**
I got confused when I ran `ddev exec drush` and PHPStorm was telling me that PHP_IDE_CONFIG needs to be set in the container. I would do a `ddev ssh` and then see it there.  

**Describe the solution you'd like**
Set PHP_IDE_CONFIG as  a regular env variable thats set even for non-login shells like DDEV_TLD, DDEV_PHP_VERSION, etc.

I prefer running commands via ddev exec versus ssh into the container because they stay in my bash history versus disappearing whenever the container is rebuilt. Plus my zsh is confugured on my host but I cant be bothered to do that in container.

**Comment by rfay** [comment]
Unfortunately, if you set PHP_IDE_CONFIG all the time, it breaks things, there was a whole set of point releases in 1.16 trying to sort this out. If it's set in every context, then the magic automatic setup in PHPStorm just goes away (PhpStorm thinks things are already set up if it's set). So this is trickier than it looks.

**Comment by rfay** [comment]
Happy to discuss this further, but I don't think there's a way to solve this, since whatever exec gets is what php-fpm gets as well, and if PHP_IDE_CONFIG is set for php-fpm, then PhpStorm doesn't prompt for config.

Happy to continue the conversation here or elsewhere.

**Comment by rfay** [comment]
@weitzman a super simple solution for you is to use `ddev drush` instead of `ddev exec drush` and add the tiny change suggested in https://github.com/drud/ddev/issues/2998#issuecomment-885278903 - I think it would be an easy PR also.

**Comment by cspitzlay** [comment]
I implemented something similar in https://github.com/drud/ddev/pull/3143 .  That should make it work for `ddev drush`.

But now that I read comment https://github.com/drud/ddev/issues/3106#issuecomment-884381505:  Would it be possible to set it both in interactive _and_ non-interactive shells so all "shell script commands" would be taken care of, and then _unset_ the variable somehow just for php-fpm? No idea about `ddev exec` though.

**Comment by rfay** [comment]
I explored everything  I could think of to *not* set it for php-fpm. Open to ideas. That would be a lot easier.

**Comment by cspitzlay** [comment]
Yeah, I should have known you already tried that. Too obvious.  :smile: 

My first idea was to wrap the binary /usr/sbin/php-fpm that is called for example in containers/ddev-webserver/ddev-webserver-prod-files/etc/supervisor/php-fpm.conf with a shell script that just said `unset PHP_IDE_CONFIG` and then called /usr/sbin/php-fpm with all the passed parameters. But I guess you already tried that or already know why that won't work.

**Comment by rfay** [comment]
No, I'd never assume that I tried everything that could be tried! Especially since this problem was discovered during a major release and needed to be solved fast in a point release. But now we're in a completely different situation, getting ready for a major release, but we know what the issues are. Give it a shot! I think this approach could work. I hate to wrap php-fpm, but it might be worth it. Probably supervisord has a way to set environment variables and you could just set it to "". That would be better than wrapping. I would have thought I'd try that.
