### ISSUE TITLE
`ddev list` and `ddev describe` should output version number of current configuration

### ISSUE THREAD

**Issue by peterkraume** [drud/ddev#3108]
**Describe the solution you'd like**
I would like to see the version number of the current configuration of each project when I use `ddev list`.

This would help me a lot to see where I need to upgrade the configuration e.g. to make use of new features in DDEV.

A plus would be if also `ddev describe` would output the version number of the current configuration.

**Comment by rfay** [comment]
I definitely like this idea. 

You know about `ddev --version` though right?

**Comment by peterkraume** [comment]
`ddev --version` is not what I mean. That shows only which version of DDEV is installed on my machine.

What I have in mind is the version of the configuration as printed in `.ddev/config.yaml` on a per project basis:
```
# This config.yaml was created with ddev version v1.17.7
```

I'd like to have a quick overview for which project I've already run `ddev config` after an update of DDEV, e.g. to make use of new features or setting options.

**Comment by peterkraume** [comment]
This could look like this:

```
NAME                VERSION          TYPE       LOCATION                                           URL                   STATUS
abe                 v1.17.7          typo3      ~/PhpstormProjects/privat/abe                                            stopped
amazing-demo        v1.16.2          typo3      ~/Development/ddev/amazing-demo                                          stopped
bookmark-test       v1.17.4          typo3      ~/Development/ddev/bookmark-test                                         stopped
```

**Comment by rfay** [comment]
It doesn't really matter any more what version the config was created with. The config hasn't changed in years (just new things added). I should probably remove that line. I removed the `APIVersion:` key from the config.yaml more than a year ago because it had never been used.

Bottom line: Don't worry about versioning of your config.yaml.

**Comment by rfay** [comment]
As far as adding something to every line of `ddev list`... you must have a much bigger screen and terminal window than I do.

**Comment by rfay** [comment]
Closing this for now, as configurations aren't versioned. But I think we should try to add ddev version info into #2195
