### ISSUE TITLE
curl error 60  SSL certificate problem: self signed certificate in certificate chain (Corporate VPN)

### ISSUE THREAD

**Issue by issahh89** [drud/ddev#3112]
Hello,

I'm working on Windows server 2019, i installed Docker and ddev (using `choco`) all exactly as mentioned in the documentation, all is good and working except for composer.

I'm trying to create a new Drupal 9 project as mentioned in the Drupal 9 quick start documentation https://ddev.readthedocs.io/en/stable/users/cli-usage/#drupal-9-quickstart

when i do this command: `ddev composer create "drupal/recommended-project"` i get this error `curl error 60 while downloading https://repo.packagist.org/packages.json: SSL certificate problem: self signed certificate in certificate chain`

if i do a `curl https://repo.packagist.org/packages.json` i will also get the same error.

I also tried to do `mkcert -install` then `ddev poweroff` then `ddev start` and still same error.

Can you help?

Thank you.

**Comment by rfay** [comment]
This doesn't have anything to do with ddev's certs  or with mkcert. 

If you're inside the container (`ddev ssh`)and you use `curl -I https://repo.packagist.org/packages.json` do you see this problem? If so, it's likely a temporary problem with packagist I would think.

**Comment by rfay** [comment]
Oh, just remembered: The most likely reason for this kind of problem is that you're on a corporate VPN which is doing deep packet inspection and intercepting your SSL connection. In that case, you'll have to install into your container something to make it trust your snooping boss. 

Related would be a proxy. You can read about how to properly set up a proxy at https://github.com/drud/ddev-contrib/blob/master/recipes/proxy

**Comment by issahh89** [comment]
You're right, even when i do `curl -I https://google.com` i get the same error, and yes i am on a corporate VPN, i will check the article that you mentioned and go through the configurations.

Thank you very much for your quick response.

**Comment by rfay** [comment]
What you have to do is get the certificates for your VPN and they have to be installed in the web container. There are a few ways to do this but one is to 

1. Copy the certificates into .ddev/web-build
2. Create a .ddev/web-build/Dockerfile something like this:

```dockerfile
ARG BASE_IMAGE
FROM $BASE_IMAGE
COPY your*.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates --fresh
```

**Comment by rfay** [comment]
No response from OP, but the technique is here. Happy to continue the conversation here or elsewhere, but closing this for now.

**Comment by ruby232** [comment]
I have the same issue.
I use:
OS: Ubuntu 22.04 
VP Type: Wireguard

**Comment by rfay** [comment]
The approach in https://github.com/drud/ddev/issues/3112#issuecomment-885609483 is what you have to do, but you'll need to make sure you have the right CA, etc. Your VPN provider or IT department may need to help you.

You can manually undertake the process that the Dockerfile uses to debug, then when you have it working, put the technique into the Dockerfile.

**Comment by ruby232** [comment]
Thanks @rfay for your response.

I use Surfshark as VPN provider. I downloaded the certificate in my account of https://surfshark.com/.
How can I know what is the right CA?

**Comment by rfay** [comment]
It's a CA cert that you're installing, adding an extra certificate authority.  I'm sorry I can't provide support for surfshark, but maybe they can help you. The basic idea is: "How do I avoid the self-signed certificate in certificate chain problem in linux". Please let us know what you figure out.
