### ISSUE TITLE
Docker warnings when using DDEV: "The HOST_DOCKER_INTERNAL_IP variable is not set" - docker-compose v2 beta

### ISSUE THREAD

**Issue by ultimike** [drud/ddev#3115]
I recently installed Lando on the same machine as DDEV. As part of this, I also had my Docker settings reset, so while I was at it, I also updated Docker for Mac.

When switching between Lando and DDEV projects, I have been pretty good at using `lando poweroff` and `ddev poweroff`, but when using DDEV, I get the following warnings:

```
WARN[0000] The HOST_DOCKER_INTERNAL_IP variable is not set. Defaulting to a blank string. 
WARN[0000] The TZ variable is not set. Defaulting to a blank string. 
WARN[0000] The TZ variable is not set. Defaulting to a blank string. 
WARN[0000] The HOST_DOCKER_INTERNAL_IP variable is not set. Defaulting to a blank string. 
WARN[0000] network default: network.external.name is deprecated in favor of network.name 
```

So, far, they seem harmless, but...

Any idea on how I can get things configured correctly?

-mike

**Comment by rfay** [comment]
Hi Mike - You have been canaried into the experimental new docker-compose, which is not yet functional. Please turn off the experimental setting for that in docker's experimental settings. 

Note that current ddev v1.17.7 will refuse to run if the experimental docker-compose is installed.

**Comment by ultimike** [comment]
Safe to assume that's something that Lando did when I installed it? Any idea if that feature is required by Lando?

If I disable it, I won't need to reset my Docker for Mac again, will I?

-mike

**Comment by rfay** [comment]
No, this is docker that did it to you. Has nothing to do with Lando. And Lando doesn't work with the experimental docker-compose either.

This is a result of Docker "canarying" you into an experimental feature which is not ready yet. 

* https://github.com/docker/for-mac/issues/5800

**Comment by rfay** [comment]
Disabling it will have no impact on your Docker Desktop.... except that you'll have a usable docker-compose.

**Comment by ultimike** [comment]
Roger that. I did a `ddev poweroff`, disabled Docker Composer V2, then started things back up again. So far, so good.

thanks,  
-mike

**Comment by ultimike** [comment]
Closing.
