### ISSUE TITLE
Acquia `acli auth:login` command and Platform.sh `platform db:dump` Segmentation fault on Mac M1

### ISSUE THREAD

**Issue by joshuami** [drud/ddev#3116]
**Describe the bug**

When developing on a Mac with a M1 processor and the ARM build of ddev, a segmentation fault occurs when running `ddev pull acquia` (using a correctly configured providers yaml file) or `ddev exec acli auth:login`. I've confirmed that the exact commands with exact ddev config on a Mac with an Intel processor work fine.

**To Reproduce**
`ddev exec acli auth:login` on a Drupal9 install with Acquia credentials on a Mac M1.

**Expected behavior**
I'm betting the compiled acli phar has some AMD architecture dependencies hidden within. This will impact users of the Acquia recipe only on Mac M1 environments. I will cross-post the bug report to Acquia, but I have a feeling many ddev users will start here.

**Screenshots**
![2021-07-23 at 4 51 PM](https://user-images.githubusercontent.com/4097978/126850944-de4d939c-13b5-4cd5-a937-76597a13c9a6.png)

![2021-07-23 at 4 54 PM](https://user-images.githubusercontent.com/4097978/126851039-685b3f25-e6de-4246-8ab1-82a4c7582851.png)

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: macOS Big Sur (M1)
- Docker Desktop version if on macOS or Windows (from "About Docker Desktop"): 3.5.2.18
- ddev version information (use `ddev version`): 1.17.7
- config.yaml contents for the misbehaving project (the part before the comments)

```
name: redacted
type: drupal9
docroot: docroot
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.3"
mysql_version: ""
use_dns_when_possible: true
composer_version: ""
web_environment: []
```
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them? None

**Comment by rfay** [comment]
Hi @joshuami - thanks for the detailed report.

This will be fixed with 
* #3102 

As mentioned there, temporarily add `webimage: drud/ddev-webserver:20210714_bullseye_web_image` to your .ddev/config.yaml

Please don't forget to remove that when this comes out in a real release.

I expect this to be in an alpha release in the edge channel in a week or two.

**Comment by rfay** [comment]
Note that this has the same effect on the Platform.sh's "platform" tool, which probably dies for the same reason (curl to a particularly sensitive host).
