### ISSUE TITLE
Several warnings show after updating Docker to 3.5.2 "HOST_DOCKER_INTERNAL_IP variable is not set" - Turn off experimental settings in docker

### ISSUE THREAD

**Issue by damienmckenna** [drud/ddev#3120]
After updating to Docker 3.5.2 the following shows up when I run any ddev command:

    WARN[0000] The TZ variable is not set. Defaulting to a blank string. 
    WARN[0000] The HOST_DOCKER_INTERNAL_IP variable is not set. Defaulting to a blank string. 
    WARN[0000] The TZ variable is not set. Defaulting to a blank string. 
    WARN[0000] The HOST_DOCKER_INTERNAL_IP variable is not set. Defaulting to a blank string. 
    WARN[0000] network default: network.external.name is deprecated in favor of network.name

**Comment by rfay** [comment]
Hi @damienmckenna -  Please turn off the "Experimental" docker-compose setting in Docker Desktop. You have been canaried into their evil plan. docker-compose v2 beta is not ready for prime time. See https://github.com/docker/for-mac/issues/5800 and https://github.com/drud/ddev/issues/3115

Also... if you had latest ddev it would have told you about this :)

**Comment by rfay** [comment]
Leaving this pinned, but closing.
