### ISSUE TITLE
DDEV user is not owner of /var/www/html share (macOS Docker Toolbox, unsupported)

### ISSUE THREAD

**Issue by jpea72** [drud/ddev#3121]
I'm on a 2010 Mac Pro on Big Sur.  I've installed docker via homebrew.

Docker version 20.10.7, build f0df35096d
ddev version v1.17.7

When I'm creating new projects with ddev, the images are not mapping my system id (501) to the docker user (1000).
Consequently I run into a lot of permissions issues.  Just wondering if there's a way to get this resolved.

Thank you

**Comment by rfay** [comment]
Hi @jpea72 - The docker user is not important, it's your user that's important.

Could you please (on the host) report the results of

```bash
id -a
ddev exec id -a
ddev exec ls -l 
```

I note that Big Sur doesn't support 2010 macs AFAIK, I thought 2013 was the latest year supported. Do you have something else interesting going on with your mac? (https://support.apple.com/kb/sp833?locale=en_US)

**Comment by jpea72** [comment]
```
$ id -a
uid=501(jkay) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),101(com.apple.access_screensharing-disabled),399(com.apple.access_ssh),400(com.apple.access_remote_ae),701(com.apple.sharepoint.group.1)

$ ddev exec id -a
uid=501(jkay) gid=20(dialout) groups=20(dialout)

$ ddev exec ls -l
total 0
drwxr-xr-x 1 1000 staff 160 Jul 28 16:48 web
```

I'm running open core, everything else seems to be fine.  I'm using docker to build executables for elixir and it seems to work just fine.  Just having this issue with the permissions on ddev projects.

**Comment by rfay** [comment]
As you see, ddev is certainly mapping your uid correctly. The only problem I see offhand is that the filesystem doesn't have the correct ownership (1000 instead of 501). 

Are you perhaps using Docker Toolbox, which is completely unsupported by ddev?

Please run the script https://github.com/drud/ddev/blob/master/scripts/test_ddev.sh and provide the results as a gist (gist.github.com). Thanks.

**Comment by jpea72** [comment]
Here's the gist:

https://gist.github.com/jpea72/0fd05f6f53e8d13c5fc791397ec906e8

**Comment by rfay** [comment]
"Docker Desktop for Mac File Doesn't Exist"

So you're using something other than Docker Desktop. 

I don't know if there might be a way for you to get Docker Toolbox working, I've never tried. DDEV has never supported it. 

But you can probably do a `sudo chown -R "$(id -u):$(id -g)" /var/www/html` in a ddev post-start hook.

**Comment by rfay** [comment]
No response from OP, and docker toolbox is not supported on any OS. But I hope you'll write up your techniques if you get it to work! People sometimes want to do interesting things with old macs! 

Closing for now, but happy to continue the conversation here or elsewhere.
