### ISSUE TITLE
Moving ddev projects to another computer (`ddev snapshot`)

### ISSUE THREAD

**Issue by begrafx** [drud/ddev#3126]
Let me start by saying, I recognize that this isn't a DDEV issue, and I apologize for taking people's time, putting this here; but I have asked this on the Docker Github page, and haven't gotten any responses, several days later. 

I have a 2012 Mac Mini, MacOS Mojave, 16gb RAM, the HDD is showing signs of dying, so before it does so, I have replaced it with an SSD. I have the HDD connected via USB, in an external case, so I still have access to that drive. I need to get my Docker Desktop moved to the SSD, so that I can get DDEV back in place, and get back to work. Can someone help me with what I need to do to move Docker? I believe I just need to set up a fresh install of Docker, and move the containers, but I'm still fairly new to dealing with Docker, so I'm not at all certain. I have been searching Google and YouTube, trying to find the answer to this on my own, and come up dry. The answers I've found all seem to be if you're on a Windows system, calling for using WSL.  

I appreciate the help.

**Comment by rfay** [comment]
For each project, just `ddev snapshot --name=before-move`

Then move your files. 

Then for each project `ddev snapshot restore before-move`

That's it. Don't worry about "moving docker"

Congrats on getting a new machine.

**Comment by begrafx** [comment]
Many thanks! Is there any way of doing the snapshots of all projects at once, or do I need to do them one by one? Either way, it's a great help. I thought I'd have to move docker containers and a lot of other hassles. I've said before, I'll say again, Randy Fay, You the man! Thank you.

**Comment by rfay** [comment]
If all of your projects show in `ddev list` then you can do a `ddev snapshot -a`

**Comment by begrafx** [comment]
Thank you, Randy. If you're ever in New England, let me know, I'll buy you lunch.
