### ISSUE TITLE
Status of ddev site as a whole should be reported, not just web container

### ISSUE THREAD

**Issue by rfay** [drud/ddev#313]
## What happened (or feature request):

I did a `ddev start` with port 80 deliberately already occupied (for https://github.com/drud/ddev/issues/126). 

* The web/db/dba containers came up
* The ddev-router container failed because port 80 was occupied.

The errors from ddev-router and ddev were probably adequate, although duplicate. But still all the other containers continued to run, and `ddev list` showed them in a healthy state, but as we know they were inoperable.

## What you expected to happen:

- ddev start should provide a failure message if the router is not running and healthy
- ddev list should provide a warning if the router is not running and healthy, indicating sites won't be accessible.
- ddev describe should provide a warning if the router is not running and healthy, indicating the site won't be accessible. 

## How to reproduce it (as minimally and precisely as possible):

* Stop all sites
* Put any process on port 80
* ddev start

## Related source links or issues:

[testing port 80 in advance - 126](https://github.com/drud/ddev/issues/126) is what I was experimenting with, and has direct bearing on this because if we tested first it might not happen in this particular situation.

**Comment by tannerjfco** [comment]
@rfay If we added a health check to ddev-router, checked health on ddev start, and produced a failure message, would that cover what you think needs to be done here? I'm assuming the port-checking would be a separate concern from this since it has its own issue.

**Comment by rfay** [comment]
Yeah, I don't think this is related to the port check. 

I guess I don't think that `ddev list` should show them running along just fine when they're not accessible? Should we do a stop if we're unable to successfully get the router going?

**Comment by tannerjfco** [comment]
I'm not sure we should do a stop, as it could be helpful to leave the incomplete state for debugging etc.

For ddev list, we could also check router health there, and provide a warning that any running sites aren't going to be accessible.

**Comment by rfay** [comment]
I agree that just checking router health in `ddev list` is about what we need. Might need it in describe or some other places?

**Comment by tannerjfco** [comment]
Updated OP "what you expected to happen" - adding the health check to router is implied. I can't think of anywhere else off-hand it would be useful to warn about a bad router situation.

**Comment by rfay** [comment]
I changed the title to fit the strategy @tannerjfco is headed, which is *reporting* and correct status management rather than stopping or obscuring when there's a problem.
