### ISSUE TITLE
How to use PhpStorm on Windows WSL2 with full integration including tests

### ISSUE THREAD

**Issue by nico-loeber** [drud/ddev#3130]
I try to run ddev as good as possible integrate in PHPStorm on Windows using WSL and Docker Desktop. Sadly PHPStorm can't use the generated docker-compose file for integration of a remote interpreter on Windows (WSL) because the absolute paths for the volumes can not be mapped corrrectly.
See this issue for more information:
https://youtrack.jetbrains.com/issue/WI-61699

A solution for this issue would be to use relative paths in the generated docker-compose file as shown by Eugene Morozov in the video you find attached to the ticket.

An alternative / workaround might be a post-x script that is manipulating the docker-compose.yaml after its generation.
Also there is a workaround Alexandru found, that you can mount your WSL as a Network Drive in Windows and reference the docker-compose.yml by this path.

If there is no need for the absolute path I would really appreciate marking them relative. Of course I am also interested in any other solution that does not require much efford.

**Comment by rfay** [comment]
Hi @nico-loeber - There has never been any intention of having PHPStorm use the .ddev/.ddev-docker-compose-base.yaml or ...full.yaml directly. It's a hidden file and hidden for a reason, not for direct access. Some people have succeeded in using it anyway, but you'll note that PhpStorm is using it directly, not accessing a project run or created by ddev. 

You may be interested in https://susi.dev/fully-integrate-ddev-and-phpstorm-including-unit-tests-with-coverage-update-2021

**Comment by nico-loeber** [comment]
Thank you very much for your response.

I already saw this blog post but hoped for some solution with less "custom scripting". Yes, it's possible to dump another docker-compose file which can be edited so it can be used by Phpstorm, but it doesnt feel right to me, as it might differ from the one actually used.
I noticed that the docker-compose-full.yaml is hidden but I thought this would be the source of truth for the docker container configuration.
Are there any plans to provide better PHPStorm integration?
Can I support in any way? Sadly I am not an experienced golang or java developer...

**Comment by rfay** [comment]
Unfortunately, PhpStorm docker integration is all about having PhpStorm in control and starting everything. And ddev is its own orchestration system. 

DDEV works fine with PhpStorm, thousands of people use it. Can you say what you're trying to accomplish?

**Comment by nico-loeber** [comment]
I would like to accomplish a "vagrant like" setup.
Means I run ddev start and afterwards I want to be able to use all the phpstorm features that are availabe for vagrant environments, like running single tests by clicking the play button beside their definition, or debugging code in cli environment.

I know it is already possible, but the way to achieve this is currently quite complicated and especially for "newbies" very difficult.

Current state:
- dump docker-compose
- remove debugging output from the first line
- replace port definitions (fixed in 2021.2)
- replaces paths
- configure remote interpreter (which is also quite complicated instead of the auto configures vagrant stuff)
- update the dumped docker-compose file regulary, as the configuration might change (I think?)

If you work in a team every team member wpuld need to do those steps for each project they work on.
Even if you automate these steps in a script if feels strange and not well integrated.

I hoped using the docker-compose-full file and configuring phpstorm once per project would work. This would be okay for me.
This seems to work for non WSL environments already and as you can see in the video in the PHPStorm ticket, it also works for relative paths in WSL.

I think for "auto configuration" you would need a PHPStorm plugin that is able to parse everything inside .ddev as there should be all information needed to configure a remote interpeter, ssh sessions and so on but sadly I do not know anyone who is able to write such a plugin... :(

**Comment by rfay** [comment]
The problem is that you're not actually using ddev for this. You're just using a config file that ddev created. 

You may also be interested in https://github.com/drud/ddev/issues/1579

The real issue here is that PhpStorm doesn't respect or allow access to containers that another process or orchestrator has created. 

I don't really see any likelihood of doing anything with this, since it would ignore about 50% of what ddev is. When you use PhpStorm the way you're doing it, you're not using DDEV at all.

**Comment by nico-loeber** [comment]
Well, PHPStorm IS using the running container started by ddev as far as I know.
In the past PHPStorm required always a start of the container on demand, but now there is a setting in the remote interprter options to reuse already running containers. PHPStorm just needs to identify this container and thus needs the path to the docker-compose file (Not sure which information is relevant, I guess the name of the container and some port config).

![image](https://user-images.githubusercontent.com/18308418/127705385-acdce364-b041-4c14-a226-3ee1a3336d84.png)

Maybe I misunderstand you. Or I misunderstand this setting.
In 2019 when the issue you mentioned was raised your description was absolutely true.

**Comment by rfay** [comment]
Fun, well maybe there's a path forward!

**Comment by rfay** [comment]
You're aware that you can run PhpStorm (Linux version) inside WSL2, correct, and also that you can use Projector? And also that you can have PHPStorm on native windows access the filesystem of WSL2?

**Comment by nico-loeber** [comment]
Yes. Currently I have PHPStorm installed on Windows, my project is located in WSL. This combines a good usability of PHPStorm in my windows environment and a good performance of my application since WSL -> docker does not need a nfs share or anything like that. Docker Desktop with actice WSL backend. Also the wsl indexing performance of PHPStorm was improved a lot with the last update by, so I am quite happy with my setup.
I already work with this setup for smaller private projects and I am very happy with all the features ddev offers and how simple it is to use.
But I would like to use it also in our company. To use it in company it has to be more simple to integrate in PHPStorm so you can let a junior dev checkout a project and start working without much knowledge about docker / ddev / PHPStorm.
Running ddev start and using the browser to access your project is very simple and great, but you want features like CLI Debugging, GUI for test execution and result visualization and other stuff PHPStorm offers as well of course.

**Comment by rfay** [comment]
If you run PhpStorm inside WSL2 your junior devs will be happy forever. It's super easy with latest insider builds (And Windows 11 beta), nothing to be done, you just install the linux version and use it. Also if you run the browser in there. 

Now that you've pointed out that PhpStorm can handle running stuff though, I'm interested in pursuing it, or you can. 

However, you'll note that .ddev-docker-compose-base.yaml, which is what ddev generates, uses relative symlinks. It's the preprocessing done by `docker-compose config` that turns the "full" into absolute paths.

**Comment by nico-loeber** [comment]
Running PHPStorm in WSL is an approach one of our teams chose. It seems to work quite well, maybe I should give it a try.
But the setup I just described is the one recommended by JetBrains. Also its easier for our IT if all GUI software is installed in windows and WSL is just used for helpers and as some sort of adapter for the efficient use of docker.

Anyway, I would really appreciate new features that allow a better integration and I am willing to help if I can.

**Comment by rfay** [comment]
Actually, JetBrains is *very* happy to have people running their tools inside WSL2 because they get 1000 less complaints per day :)

The reality is if everybody runs PhpStorm and their browser inside WSL2 for WSL2 development, it removes tons of complexity and is really a plus. The other super complexity with WSL2 is the mapping of network stuff to the Windows side. As you know, hostnames created in /etc/hosts inside WSL2 are completely unknown to the windows-side browser, causing people to be very confused. If everybody stays with *.ddev.site, then all is well, but as soon as they try to work offline (where DNS resolution doesn't work) or they try a different TLD or FQDN... Windows folks get really confused.

**Comment by rfay** [comment]
Have you tried using the .ddev-docker-compose-base.yaml with your docker-compose exec? It would probably complain about missing environment variables, but it might just do what you want.

**Comment by nico-loeber** [comment]
> Actually, JetBrains is _very_ happy to have people running their tools inside WSL2 because they get 1000 less complaints per day :)
> [...]

Haha, yes I get your point. For private use, running PHPStorm in WSL might be the better decission. But in company context... If you start installing all your software inside the WSL what are you using Windows for? Just to run Teams and Office Applications? ;) But this is another offtopic discussion I think.

> Have you tried using the .ddev-docker-compose-base.yaml with your docker-compose exec? It would probably complain about missing environment variables, but it might just do what you want.

I just tried, but with no success.
It just fails detecting the installed PHP Version like for the docker-compose-full.yaml with absolute paths.
I've increased the log verbosity and it shows warnings (log level debug) for the missing environment variables, that are treated as empty string, as well as an invalid mariadb definition.
Not sure what is the actual cause for the error. But it looks like there are even more problems than just absolute volume paths.

I understand that the docker-compose.yaml(s) were never thought to be used by any third party tool. But would it be an actual problem dumping the compose.yaml with relative paths for the volumes?

**Comment by rfay** [comment]
> I understand that the docker-compose.yaml(s) were never thought to be used by any third party tool. But would it be an actual problem dumping the compose.yaml with relative paths for the volumes?

The current problem is that ddev lets docker-compose run `docker-compose config` to get a "canonical" compose file (the -full file). That's how the absolute paths get there. Ddev isn't adding them. It might be possible to not do the preprocessing with config in advance, but it's worked out pretty well.

**Comment by rfay** [comment]
Hi @nico-loeber - I worked through this today and didn't have any trouble on either macOS or Windows with WSL2. I had to learn a bit, mostly from @susannemoog 's excellent article, but a slight adaptation of that article to current PhpStorm was all that was required.

Please try this out and give your feedback (and you too @susannemoog) and we'll add something like to to the docs.

Here's a basic technique to add full PhpStorm integration with a DDEV project.

This is based on the wonderful [article series](https://susi.dev/fully-integrate-ddev-and-phpstorm-including-unit-tests-with-coverage-update-2021) by Susi, and couldn't have been done without it, but since PhpStorm has fixed some things, this is far easier now.

Requirements:

- PhpStorm 2021.2 or higher
- Any platform, but if you're using Windows PhpStorm with WSL2 the path mappings are slightly more complex. I'll give WSL2 instructions as I go along.

1. Open a DDEV project. In my example, the project name is "d9". 
    - If you're on Windows using WSL2, open the project as a WSL2 project.  In other words, in the "Open" dialog, browse to \\wsl$\Ubuntu\home\rfay\workspace\d9 (in my example)
2. Under File→Settings→PHP (Windows) or Preferences→PHP (macOS), click the "..." to the right of "CLI Interpreter"
    - Use the "+" to select "From Docker, Vagrant, VM..."
    - Choose "Docker compose"
    - Create a server; the default name is "docker".  Choose "Docker for Windows" or "Docker for Mac"
    - In the "Path mappings" of the "Server" map the local paths (which on WSL2 means /home/...) to the in-container paths.  So "Virtual Machine Path" would be "/var/www/html" and "Local path" would be something like /Users/rfay/workspace/d9 (on macOS) or \\wsl$\Ubuntu\home\rfay\workspace\d9 on Windows using WSL2
    - Now back in the "Configure Remote PHP Interpreter" for "Configuration files" use .ddev/.ddev-docker-compose-full.yaml
    - Service: web
    - Add an environment variable COMPOSE_PROJECT_NAME=ddev-<projectname>. In my case, it's "ddev-d9"
    - In the CLI interpreter "Lifecycle" select "Connect to existing container"
3. Configure composer under PHP→Composer. 
    - Use "remote interpreter"
    - CLI Interpreter will be "web"
4. Under "Test Frameworks" click the "+" to add phpunit
    - PHPUnit by remote interpreter
    - Interpreter "web"
    - Choose "Path to phpunit.phar" and use /var/www/html/vendor/bin/phpunit (or wherever your phpunit is inside the container)
    - Default configuration file: /var/www/html/web/core/phpunit.xml or wherever yours is inside the container
5. Open Run/Debug configurations and use the "+" to add a phpunit configuration. Give it a name
    - Test scope (as you wish, or "Defined in config file")
    - Interpreter: "web" (the one we set up)
6. Run the runner!

**Comment by rfay** [comment]
@PhpStorm replied in twitter, https://twitter.com/phpstorm/status/1422257740160843777

> Please be aware that this might not work for someone because of https://youtrack.jetbrains.com/issue/WI-47028.

**Comment by cmuench** [comment]
Tested that on my Linux workstation. It works partially. I can execute a whole Test Suite at once. A cherry picked single test is not working. Then PHPStorm ignores the path mapping and searches for "/opt/project/..." which does not exist in already existing containers.

**Comment by nico-loeber** [comment]
Thank you @rfay, indeed I was able to run at least composer without any problems by the remote interpreter.
I think adding the mapping manually did the trick.
  
> Choose "Path to phpunit.phar" and use /var/www/html/vendor/bin/phpunit (or wherever your phpunit is inside the container)

This resulted in:

```
PHP Fatal error:  Uncaught UnexpectedValueException: Cannot create phar '/var/www/html/vendor/phpunit/phpunit/phpunit', file extension (or combination) not recognised or the directory does not exist in /opt/.phpstorm_helpers/phpunit.php:18
```

I switched to "Use Composer autoloader" which worked surprisingly.
Even running a single Test works just fine.

But I would like to note, that in neraly every configuration window I have warnings and errors that PHPStorm can not detect the installed PHP, Composer or PHPUnit version.
I'm not sure if it is still related to https://youtrack.jetbrains.com/issue/WI-61699 or https://youtrack.jetbrains.com/issue/WI-47028 .

This is a big step forward in my opinion, thank you so much!

Sadly I can not debug my tests as phpstorm says 
![image](https://user-images.githubusercontent.com/18308418/127984557-3c254588-2fd4-4d20-b3aa-58ee70cd18de.png)
event when xdebug is enabled.
If I check the interpreter settings I see an empty "debugger extension" input. I guess I need to enter something manually in here since PHPStorm can not autodetect it?

**Comment by rfay** [comment]
Hi @nico-loeber  - You did a `ddev xdebug on` right, to enable xdebug? It sounds like you did.

**Comment by rfay** [comment]
@nico-loeber I was able to get it debugging tests on both macOS and Windows/WSL2. 

The things I had to do:
* `touch "/path/to/docroot/Standard input code"` (This is something I've seen before to trick PhpStorm into not trying to map standard input)
* Make sure that you have an xdebug "server" with the proper name. Mine is "d9.ddev.site"
* Make sure that your xdebug server maps the whole project (\\wsl$\Ubuntu\home\rfay\workspace\d9 in my case) to /var/www/html
* Add PHP_IDE_CONFIG=serverName=d9.ddev.site as an environment variable in your Run/Test config. (In a shell inside the container this would be set for you)
* `ddev xdebug on`
* Click the listener in PhpStorm
* Run the test runner

I'll be happy to do a screenshare session with you if you'd like.

Please know that you don't need to get any of this set up to debug tests in ddev. You can just `ddev xdebug on` and `ddev ssh` and run phpunit. You do have to have the whole project mapped in your Xdebug server.

**Comment by rfay** [comment]
And thanks to @eojthebrave for https://drupalize.me/blog/debug-any-drupals-phpunit-tests-phpstorm-ddev-local-environment - full writeup on how it's done.

**Comment by nico-loeber** [comment]
Thank you @rfay and @eojthebrave. 
Even debugging tests from phpstorm gui works now. That's great!
But as you can see there are a lot of steps to do to archive this level of integration. Reducing the hurdles would be cool.

If I find some time I will try to understand the internals of ddev better. Maybe I can suggest something more concrete then.

Thank you very much for the great support again @rfay!

**Comment by cmuench** [comment]
> Tested that on my Linux workstation. It works partially. I can execute a whole Test Suite at once. A cherry picked single test is not working. Then PHPStorm ignores the path mapping and searches for "/opt/project/..." which does not exist in already existing containers.

Found the issue. I use Intellij Ultimate. The **python plugin** hooks into the docker volume generation. After the uninstall of the python plugin my unit tests are work with a "/opt/project" mount.

**Comment by SuddenlyRust** [comment]
I am facing another problem on my machine. The php version validation is not working and I can't figure out why.

![image](https://user-images.githubusercontent.com/14092921/128930263-846ca202-75aa-4035-b0b3-bae9feabf9a1.png)

I did submit a bug report for it: https://youtrack.jetbrains.com/issue/WI-61976

**Comment by tyler36** [comment]
Another guide + video that came out today is Running and debugging [PHPUnit tests in PHPStorm with DDev and xdebug](https://www.previousnext.com.au/blog/running-and-debugging-phpunit-tests-phpstorm-ddev-and-xdebug). 

Although it's not specific to WSL2, there might be a setting that they cover that you missed somewhere along the way.

**Comment by rfay** [comment]
This should all be working fine in v1.18.0-rc3, and I'd love a contribution to the docs based on the above. Please do test and see how it all works for you.

**Comment by nico-loeber** [comment]
Thank you very much for this release @rfay!
The integration works much better now, but there are still some issues:
- In combination with docker compose 2 RC enababled PHPStorm can't parse the docker-composer.yaml because 'host_ip' is unexpected. I've created an issue for that https://youtrack.jetbrains.com/issue/WI-62832
- If you use another PHPVersion than 7.4 PHPStorm can't auto detect your PHPUnit Version. It looks like this is caused by PHPStorm always using 7.4 (which is always shown as version of the remote interpreter even if 8.0 is configured) and composer2 which checkes the minmum php requirements when executing the auto loader.

Is it still required to set the COMPOSE_PROJECT_NAME environment variable in remote interpreter settings? I have placed it but it doesn't seem to make any difference. What is it used for?

I would like to thank you with more than just words, is it possible to sponsor you?

**Comment by rfay** [comment]
A note that the PhpStorm issue to use `docker-compose exec` instead of `docker-compose run` to get php info is https://youtrack.jetbrains.com/issue/WI-62463 - Until that issue is solved, you have to use `phpX.X` for the executable when setting up PhpStorm.

**Comment by rfay** [comment]
I think COMPOSE_PROJECT_NAME is still required, but will take a look when I go through the testing for this.

After I get this release out I'll be working on ways for people and orgs to sponsor, thanks!

**Comment by rfay** [comment]
Related docker-compose v2 issue reported by @deviatintegral 
* https://youtrack.jetbrains.com/issue/WI-61205
* https://github.com/docker/for-mac/issues/5800#issuecomment-926143291

**Comment by blankse** [comment]
> A note that the PhpStorm issue to use `docker-compose exec` instead of `docker-compose run` to get php info is https://youtrack.jetbrains.com/issue/WI-62463 - Until that issue is solved, you have to use `phpX.X` for the executable when setting up PhpStorm.

When I want to use the ddev interpreter for the PHPStan Quality Tool in PhpStorm it doesn't work ether with "php8.0" for the executable. It still uses version 7.4 :(

**Comment by ahmadzano** [comment]
I had same issue and I solved it by chaning the `version` in `docker-comose.yml` from `2.8` to `3`

**Comment by rfay** [comment]
There is no docker-compose.yaml here @ahmadzano ... What version in what file are you talking about?

**Comment by ahmadzano** [comment]
@rfay I had same issue @SuddenlyRust had but in a different project. Sorry if this isn't relevant to this project

**Comment by dahaupt** [comment]
> When I want to use the ddev interpreter for the PHPStan Quality Tool in PhpStorm it doesn't work ether with "php8.0" for the executable. It still uses version 7.4 :(

I can confirm this problem. I've closely followed the documentation, but I can not get PHPStan working. Other tools like Composer or Codeception are working fine using the configured remote interpreter.

In my case, this error message is shown after clicking the `Validate` button:

![grafik](https://user-images.githubusercontent.com/15915048/149197171-0219e356-de75-43d8-b759-644b5fbe57c5.png)

**Comment by rfay** [comment]
Recent versions of composer (2.2.*) have muddied the water here quite substantially by putting something other than links into vendor/bin. You may want to see if that's related to your trouble. Try it with composer 2.1.14 as well to see if that's an issue, `ddev config --composer-version=2.1.14 && ddev restart` and then do your `ddev composer install`. If that's the works your problem may be with the newer composer 2.2 behavior. Also, check your current composer version (`ddev composer --version`) and if it's not 2.2.4 you'll want the latest 2.2.4 in your testing if you're trying 2.2. `ddev config --composer-version=2.2.4`

**Comment by rfay** [comment]
As you get this sorted out, it would be worth a new issue @dahaupt . You should be able to figure out what's going on.

However, I note looking at your screenshot that xdebug is enabled, and that means that it's not properly using the "connect to existing container" but instead it's launching its own container. That could easily be the whole problem.

In https://ddev.readthedocs.io/en/latest/users/topics/phpstorm/
> 8. In the CLI interpreter "Lifecycle" select "Connect to existing container"

**Comment by dahaupt** [comment]
> I can confirm this problem. I've closely followed the documentation, but I can not get PHPStan working. Other tools like Composer or Codeception are working fine using the configured remote interpreter.

In a longer debugging session with @rfay, we found out that PHPStan actually does work with the remote interpreter. Only the check for the version, which happens when clicking the "Validate" button (see previous screenshot), leads to an error. So the problem should be related to [this error](https://youtrack.jetbrains.com/issue/WI-62463), but PHPStan can still be used correctly with the PHP Remote Interpreter.
