### ISSUE TITLE
Extraneous Newline after 'ddev exec' output

### ISSUE THREAD

**Issue by h1nds1ght** [drud/ddev#3131]
Everytime I execute `ddev exec` I get an additional new line

```
$ echo Hello
Hello
$ ddev exec 'echo Hello'
Hello

$
```

Maybe something is wrong in my setup. I tried it with a fresh setup and a new project, that has no modifications, but even then I have this new line. 

Is this the normal behavior or is it my fault?

**Comment by rfay** [comment]
I'm glad you asked. Fixed in https://github.com/drud/ddev/pull/3133
