### ISSUE TITLE
Mutagen error message shown when mutagen is not enabled

### ISSUE THREAD

**Issue by chellman** [drud/ddev#3135]
**Describe the bug**

When mutagen is neither installed, nor enabled on a project, an error message is shown that assumes one is trying to use it, and not succeeding:

`Unable to stop mutagen daemon: fork/exec /Users/chellman/.ddev/bin/mutagen: no such file or directory`

Obviously this makes sense, since at this point mutagen isn't installed.  I would expect that there would be no error message since my global and project configurations (at the point that I'm running ddev) don't have mutagen turned on.

**To Reproduce**

From a cold start:

- Uninstall mutagen, if installed
- Disable mutagen for ddev globally if needed, and on the project
- Run `ddev start`

**Expected behavior**

I expect no mention of mutagen doing anything, since it is not configured.

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: macOS Catalina
- Docker Desktop 3.5.2
- ddev v1.18.0-alpha2

**Additional context**

This came up on my first project start after installing ddev 1.18.  I'm going to try mutagen now, so this error message might become meaningful after that.  I'm just reporting this for situations where people aren't using mutagen, to avoid confusion.

**Comment by rfay** [comment]
Thanks for reporting this. I happened to notice it yesterday, and it's fixed in https://github.com/drud/ddev/pull/3134

**Comment by chellman** [comment]
Excellent!
