### ISSUE TITLE
ddev launch -t flag to open the TYPO3 backend

### ISSUE THREAD

**Issue by janisint** [drud/ddev#3136]
**Describe the solution you'd like**
It would be a nice little shortcut to have the **-t** flag when using **ddev launch** which would open the TYPO3 backend (website.com/typo3) immediately. That would be a very nice extra to the ddev launch command, surely useful to a lot of TYPO3 developers. The -t is short for -typo3.

**Describe alternatives you've considered**
The flag could differ from **-t**, i.e. **-be** would be an option.

**Priority**
Of course this feature request is not urgent at all, it would just be a nice to have which should not take too much time to implement.

**Comment by rfay** [comment]
Thanks for the suggestion!

Did you know that you can `ddev launch /typo3` ? Does that do everything you'd like?

**Comment by janisint** [comment]
Hi! Thanks for the quick response. In fact, I did not know about this possibility. This is absolutely perfect, thank you.
