### ISSUE TITLE
`ddev version` shouldn't show an error when mutagen hasn't yet been downloaded

### ISSUE THREAD

**Issue by dahaupt** [drud/ddev#3139]
**Describe the bug**
Output of mutagen information in `ddev version`:
```
mutagen    failed to GetMutagenVersion(): fork/exec /home/daniel/.ddev/bin/mutagen: no such file or directory
``` 

**Expected behavior**
Show `Mutagen is not installed`, or completely disable the mutagen feature on Linux, as it adds no value (as indicated in the [documentation](https://ddev.readthedocs.io/en/latest/users/performance/#using-mutagen)).

**Version and configuration information:**
- Host computer OS and Version: Linux (Ubuntu 21.04)
- ddev v1.18.0-alpha3

**Comment by rfay** [comment]
Hi @dahaupt and thanks for taking it for a spin!

That error message shouldn't really be a failure... Does it end up downloading it and working OK anyway?

Is there really no mutagen in /home/daniel/.ddev/bin/mutagen ?

**Comment by dahaupt** [comment]
@rfay There is no mutagen binary file inside `/home/daniel/.ddev/bin`. Actually, the directory `bin` does not even exist.

I already tried reinstalling ddev via brew, but the binary is still missing.

**Comment by rfay** [comment]
Yeah, it has nothing to do with brew, as ddev downloads the needed binary.

Could you please `ddev poweroff` and then show the output of `ddev start` in this directory? It should download the mutagen binary. 

Did you have a previous alpha version? 

`ddev version` won't find the mutagen version until you've done a `ddev start` and it's downloaded it. Sounds like the message in `ddev version` could be better? And it really shouldn't try to get the version when the binary isn't there yet.

**Comment by dahaupt** [comment]
There may be a misunderstanding here. I don't want to use mutagen (as I'm on Linux). But when I run `ddev config --mutagen-enabled`, the binary will be downloaded correctly.

So the binary correctly does not exist on my system. But then mutagen should not be mentioned in `ddev version`.

**Comment by rfay** [comment]
It's not going to be available unless you have done a `ddev start` with it.  Is there something wrong with
> mutagen           	not yet downloaded, will be automatically downloaded when needed

Would you use some other terminology?

Or are you saying that the mutagen shouldn't even have a line in `ddev version` ? But `ddev version` has no way to know whether you might have projects where it's enabled.

**Comment by dahaupt** [comment]
I thought using Mutagen on Linux was useless in terms of performance. Therefore, I would have rather suspected that it is not available under Linux at all. Or is that too short-sighted? It probably has other benefits I am not aware of.

The terminology though is fine! :+1:

**Comment by rfay** [comment]
Mutagen works fine on Linux. It just doesn't add enough value to bother with it. Some teams might standardize and everybody use it, I suppose, even if they're on Linux or WSL2.
