### ISSUE TITLE
Better status integration during mutagen sync flush, especially on start

### ISSUE THREAD

**Issue by rfay** [drud/ddev#3144]
When people try out `ddev config --mutagen-enabled` for the first time, there can be a delay during start that causes them to give up because they think nothing's happening. @xenoscopic suggests parsing or otherwise passing on the output of `mutagen sync monitor <syncname>`, which should really help people to understand.

**Comment by LionsAd** [comment]
I agree with that - especially the first `ddev start` feels really slow.

**Comment by LionsAd** [comment]
Even a message: `Mutagen enabled, syncing first time, please wait` would help ;)
