### ISSUE TITLE
ddev auth ssh: the input device is not a TTY

### ISSUE THREAD

**Issue by h1nds1ght** [drud/ddev#3147]
**Describe the bug**

The command "ddev auth ssh" throws the error "the input device is not a TTY" when executed by a remote script

**To Reproduce**

Create a file `auth.sh` in DDEV_APPROOT  with the following content:
```
#!/usr/bin/env bash
ddev auth ssh
```
Add a pre-start hook
```
exec-host: "curl -fsSL file:///$DDEV_APPROOT/auth.sh | bash"
```
Start the project with `ddev start` and you will get an error like

```
=== Running task: Exec command 'curl -fsSL file:///$DDEV_APPROOT/auth.sh | bash' on the host (silicon), output below
the input device is not a TTY
Docker command 'docker [run -it --rm --volumes-from=ddev-ssh-agent --user=501 --entrypoint= --mount=type=bind,src=/Users/foo/.ssh,dst=/tmp/sshtmp drud/ddev-ssh-agent:v1.17.0-built bash -c cp -r /tmp/sshtmp ~/.ssh && chmod -R go-rwx ~/.ssh && cd ~/.ssh && ssh-add $(file * | awk -F: "/private key/ { print \$1 }")]' failed: exit status 1
```

**Expected behavior**

Of course no error

**Version and configuration information:**

- Host computer OS and Version: macOS Big Sur
- Docker Desktop version: 3.5.2
- ddev version: v1.18.0-alpha2

**Additional context**
If I understand it right it is more or less a docker bug. The workaround seems to be to either use `COMPOSE_INTERACTIVE_NO_CLI=1` or `docker-compose exec -T ...`. I tried `export COMPOSE_INTERACTIVE_NO_CLI=1` with no success
https://github.com/docker/compose/issues/5696

**Comment by rfay** [comment]
`ssh-add` which is what's underneath here insists that you type the password on a terminal. You can't script it. 

But you might be able to just `exec-host: ddev auth ssh`

**Comment by h1nds1ght** [comment]
OK, I see the point. For typing a password, which is not always necessary, you would need a tty. So the only chance is to put it directly in the hook of the config.yaml?

**Comment by h1nds1ght** [comment]
I think I will give process substitution a try

```
bash <( curl -s ... )
```

Doesn't look nice but it works. Thank you for your input, you can close this issue.

**Comment by rfay** [comment]
I'm glad you got it to work. I didn't actually end up understanding what you were trying to do or how you solved it.
