### ISSUE TITLE
Analytics and intelligence in ddev

### ISSUE THREAD

**Issue by cyberswat** [drud/ddev#315]
## What happened (or feature request):
There is no mention in the current ddev roadmap of analytics or data collection that will help us determine how the tool is being used.  This kind of information is imperative to our overall strategy in regards to the intelligence engine and is part of what will help us make educated changes to the tool as usage increases.

## What you expected to happen:
It would be great to see analytics accounted for in the roadmap.

**Comment by rfay** [comment]
I have looked at [sentry](https://sentry.io) real-time error tracking as a part of this equation, but didn't get to completion.

**Comment by rickmanelius** [comment]
Noted. Added to the sprint planning board so that this gets the focus it needs during my next sweep.

**Comment by cyberswat** [comment]
Closing this to focus on #307
