### ISSUE TITLE
Cannot remove projects that have already been removed from the filesystem

### ISSUE THREAD

**Issue by Kayu84** [drud/ddev#3156]
I got a Problem that i cannot remove some old projects from a different location.
i'm using: `ddev stop --unlist t3monitoring-client`

`unable to create project at project root '/Volumes/TEYADI/gd/t3monitoring-client': project root /Volumes/TEYADI/gd/t3monitoring-client does not exist`

I want to start that Projects from my harddrive, the Volume doesn't exist anymore...
Ok, in a last case i could rename a different drive to "TEYADI", place a copy of the project into the location and remove it.

But for now i got no drive and i could not start the project (maybe i will rename it for today).

i've removed and unlist several other projects with the same methode, i think they are "folder name" = "project name".
And the last 3 projects are renamed.

ddev list doesn't show any active projects, just the same error message when trying to unlist.
I've also tried to remove them in docker, not sure if this is correct: docker stop `$(docker ps -q) && docker rm -f $(docker ps -aq)`

anyway, is there a chance to get the project names listed? Getting the full path doesn't help me to remove these project from ddev list and doesn't allow me to start my projects.

- macOS Big Sur
- Docker Desktop macOS 3.5.2

DDEV-Local version      v1.17.2                                
architecture            arm64                                  
db                      drud/ddev-dbserver-mariadb-10.3:v1.17.0
dba                     phpmyadmin:5                           
ddev-ssh-agent          drud/ddev-ssh-agent:v1.17.0            
docker                  20.10.7                                
docker-compose          1.29.2                                 
os                      darwin                                 
router                  drud/ddev-router:v1.17.0               
web                     drud/ddev-webserver:v1.17.2

**Comment by rfay** [comment]
Just edit the ~/.ddev/global_config.yaml and remove the lines that are causing trouble.

**Comment by rfay** [comment]
No response from OP, but that should do the job for you. Happy to continue the conversation here or elsewhere, but closing for now.
