### ISSUE TITLE
ddev not compatible with current docker release 3.6.0 (Turn off "experimental" docker-compose v2)

### ISSUE THREAD

**Issue by wayheyha** [drud/ddev#3159]
**Run a Diagnostic and Paste Link Here**

Problem: After todays docker upgrade to version 3.6.0 ddev is not working anymore. 

Reproduction: 

1. Upgrade Docker for Windows to version 3.6.0
2. switch to wsl2 distro
3. ddev start -> The docker-compose version currently installed does not meet ddev's requirements: exit status 1

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: Windows 10, WSL2 (Ubuntu)
- Docker Desktop 3.6.0 for Windows
- ddev version v1.17.7
- config.yaml: name: auth
type: laravel
docroot: laravel-jwt-auth/public
php_version: "7.4"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.3"
mysql_version: ""
use_dns_when_possible: true
composer_version: ""
web_environment: []
- no custom config

**Comment by rfay** [comment]
Please turn off the "experimental" setting that causes it to use docker-compose v2. I think on `ddev start` it would have told you to do that.

docker-compose v2 is not yet functional, but they're pushing it out to people anyway.

**Comment by rfay** [comment]
This is what I would have expected you to see:
```bash
$ ddev start
You have docker-compose v2 and it is not yet stable enough to use with ddev.
Please uncheck the 'Use Docker Compose V2' experimental feature
in Docker Desktop, or run 'docker-compose disable-v2'
The docker-compose version currently installed does not meet ddev's requirements: 2.0.0-rc.1 is greater than 1.999.0
```

**Comment by wayheyha** [comment]
> 
> 
> Please turn off the "experimental" setting that causes it to use docker-compose v2. I think on `ddev start` it would have told you to do that.
> 
> docker-compose v2 is not yet functional, but they're pushing it out to people anyway.

I thought i did that.. could you by any  chance tell me how to do this?

**Comment by rfay** [comment]
There are two ways

1. The docker menus are in the system tray in Windows, a little whale. It's in the lower right. Right click, settings, Experimental settings, uncheck docker-compose v2 (This is the recommended way)
2. `docker-compose disable-v2`

**Comment by wayheyha** [comment]
Thank you for you help! Unfortunately they were turned off

**Comment by wayheyha** [comment]
My Docker-Engine configuration is: 
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": false,
  "experimental": false,
  "features": {
    "buildkit": true
  },
  "builder": {
    "gc": {
      "enabled": true,
      "defaultKeepStorage": "20GB"
    }
  }
}

**Comment by rfay** [comment]
Please show the output of `docker-compose --version` in WSL2

As requested when you created this ticket, please run the script at https://raw.githubusercontent.com/drud/ddev/master/scripts/test_ddev.sh - that would have already given me this information.

**Comment by rfay** [comment]
Interesting. You really shouldn't have to reboot computer after docker update, but sometimes the docker update doesn't complete. Glad you got it sorted out!
