### ISSUE TITLE
Integrate with drupal/core-composer-scaffold

### ISSUE THREAD

**Issue by mstrelan** [drud/ddev#3185]
**Is your feature request related to a problem? Please describe.**
When using `drupal/core-composer-scaffold` with the [gitignore option](https://www.drupal.org/docs/develop/using-composer/using-drupals-composer-scaffold#toc_11) the following is written to `web/sites/default/.gitignore`

```
/default.services.yml
/default.settings.php
```

If this file has `#ddev-generated` at the top the lines added by the scaffold plugin will be removed when ddev is restarted.

**Describe the solution you'd like**
Integrate with `drupal/core-composer-scaffold` so they can coexist in harmony, or provide advice on the best way to solve this.

**Describe alternatives you've considered**
For now I'm removing the `#ddev-generated` tag in this file.

**Additional context**

**Comment by rfay** [comment]
So drupal/core-composer-scaffold wants to create a sites/default/.gitignore, and so does ddev... 

ddev's only interest in that directory is preventing settings.ddev.php from being committed by accident. I'm certainly open to other ideas about how to manage that.

The reality is that settings.ddev.php should always have been in the .ddev directory... but time marches on.

Besides removing the #ddev-generated you have the option of setting `disable_settings_managment: true`

**Comment by mstrelan** [comment]
One key difference is that drupal/core-composer-scaffold will append to the existing file rather than rewriting it. Nevertheless I haven't been able to think of a good way to deal with this. I think it's reasonable that if you're enabling the gitignore option in the scaffold plugin then you can deal with this yourself. And committing those two scaffold files isn't going to hurt anyone either.

**Comment by rfay** [comment]
What's the path forward on this @mstrelan ? Can you propose a PR?

**Comment by mstrelan** [comment]
I have a few ideas but I don't know if any of them are viable.

- Add all ddev ignored files to the root .gitignore file since `drupal/core-composer-scaffold`. This wouldn't help if using the legacy project structure where core/ and vendor/ are siblings.
- Add the ddev ignore files to `.git/info/exclude`. May need to check the git config to make sure that's the right path to the local excludesfile. Not sure if this would really help the situation.
- Move settings.ddev.php inside .ddev, but this is probably too disruptive.
- Try to detect if the scaffold plugin is adding stuff to the gitignore file and remove `#ddev-generated` from the file in that case

Also happy to just close this and move on.

**Comment by rfay** [comment]
I don't believe that ddev has any business editing the root gitignore or doing anything in .git/info/exclude. 

I do wish settings.ddev.php were inside .ddev. 

ddev is not a drupal-specific tool, so looking for the scaffold plugin seems out of scope. 

If you can see how moving settings.ddev.php inside .ddev would work out (probably with a symlink? Or maybe just the settings.php link being right?) then I'm open. It does seem disruptive. But I've always wished for it.

**Comment by mstrelan** [comment]
I also agree with this. Is there an open issue to discuss moving settings.ddev.php? I feel like that should be separate from this issue.

FWIW I have an existing project with the following in `settings.local.php`.

```php
// Automatically generated include for settings managed by ddev.
$ddev_settings = $app_root . '/../.ddev/settings.ddev.php';
if (getenv('IS_DDEV_PROJECT') == 'true' && is_readable($ddev_settings)) {
  require $ddev_settings;
}
```

**Comment by rfay** [comment]
I don't know of an issue about moving settings.ddev.php, but it would be so welcome if we could pull it off without breaking everybody.

**Comment by rfay** [comment]
This seems like a great candidate for a ddev add-on. The add-on could do exactly the things you think are necessary. Note that ddev add-ons can do more than extra services. I hope you'll consider taking that on! https://github.com/drud/ddev-addon-template

I'm going to close this for now, because that puts the whole thing in your hands, and when you're ready it can be promoted to an official add-on.
