### ISSUE TITLE
Allow enabling mutagen outside of main config.yaml with config.mutagen.yaml

### ISSUE THREAD

**Issue by deviantintegral** [drud/ddev#3190]
**Is your feature request related to a problem? Please describe.**

If mutagen is enabled in the committed `config.yml`, it's used for hosts that don't need it like Linux. I assume this happens on Windows / WSL2, but I haven't tried it.

**Describe the solution you'd like**

Since developers may want to test mutagen on any OS, they shouldn't be locked out entirely. But, being able to commit a "macOS" configuration without requiring `config.local.yml` edits would be nice improvement.

**Describe alternatives you've considered**

The best I can think of is local files excluded, or perhaps something like `config.OS-TYPE.yml` that could be expanded if there are other OS-specific options I'm not aware of.

**Comment by rfay** [comment]
The way to do this is just add a `config.mutagen.yaml` and not check it in, use it just on systems that want mutagen. It's not necessarily and OS definition. Mine happens to be called "config.rfay.yaml" and is has contents:
```yaml
mutagen_enabled: true
```
