### ISSUE TITLE
ddev composer --ansi shows ddev's help screen, consider to allow using '--' to delimit ddev's arguments

### ISSUE THREAD

**Issue by LionsAd** [drud/ddev#3195]
### Motivation

It's easiest to run commands via `ddev composer` or `ddev drush`, but if you want to add arguments that ddev does not know about you get ddev's help instead.

### Steps to reproduce

1.

```
ddev composer --ansi
```

Expected result: Composers help screen

Actual result: ddev's help screen

### Proposed solution

There is two ways to solve that:

- Stop argument parsing after the first "drush|composer" argument has been found and pass through.

But there is obviously ambiguity as it can be valid to want to see the help of ddev for composer.

So the second alternative is:

- Support '--' as delimiter so you can do:

```
ddev -- composer --ansi
```

`--` is widely used in Unix/Linux tools to say: "Stop argument parsing here and pass the remainder raw through the subcommand"

Thanks for considering!

**Comment by rfay** [comment]
So `ddev composer -- --ansi` already works and always has, so thanks for this @LionsAd , but I'm going to consider it done! :)
