### ISSUE TITLE
WordPress installation support for 'local' plugin

### ISSUE THREAD

**Issue by beeradb** [drud/ddev#32]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Task

**Information**:
This adds WP support to the work done in #27 

Done criteria:
- Latest version of Wordpress should work with this local plugin
- MySQL connection information should be printed alongside the site URL to assist the user in installing WP
- Pulling in assets such as a DB dump or a files backup is not required for this, but if it makes sense/saves time then it's fine as a stretch goal.

### Testing approach

- Should have tests to ensure the install page returns the correct HTTP status
- Should parse MySQL connection info from the CLI output and ensure the connection is working

**Comment by rickmanelius** [comment]
This looks like this ticket is mostly in a clean-up state. To confirm, I would like a manual test of spinning up a WordPress site using our WordPress repo (https://github.com/drud/wordpress) and then for testing purposes, like Drupal we just need to verify that we can get to the install screen.

In the future, I think it would be helpful to actually step through a Drupal site profile install and WP install because there can be a variety of things that trip this up (db credentials are wrong, templates don't work, etc).

**Comment by rickmanelius** [comment]
I'm pleased to report that it took all of 3 minutes from the time I finished this request to manually testing a successful WordPress install. I'm very happy about that :)

Now it's more about testing. We can either push the tests off to other tickets (example, the wp-config.php, describe, and import commands), or we can do more of an integrated test that actually runs `ddev exec` for drush and/or WPCLI and confirms an installation.

**Comment by rickmanelius** [comment]
Need feedback from either @rfay @beeradb @tannerjfco on what we want to do for an automated test (if anything). If nothing, this is complete.

**Comment by beeradb** [comment]
I would love to see a wordpress site added to our existing test coverage, preferably including an import (to check config functionality).

It seems like this could also be a great time to get explicit test coverage on the MySQL connection at  `sitename.ddev.local:3306`, although perhaps the import tests we have for drupal7/8 for other sites do that well enough.

**Comment by tannerjfco** [comment]
Wordpress was added to the test sites for local plugin tests in #123. https://github.com/drud/ddev/blob/master/pkg/plugins/platform/local_test.go#L30

**Comment by beeradb** [comment]
well then! I feel like we're probably pretty good on this, then.

**Comment by rickmanelius** [comment]
Cool. So I'm assuming this tests a success load of the install page. We'll revisit the need to test working site installs later on.
