### ISSUE TITLE
Can't configure mysql 5.7 database when mariadb database has already been created

### ISSUE THREAD

**Issue by ASauer** [drud/ddev#3205]
https://gist.github.com/ASauer/041691d5ca1d84f5a0802abd0ee2cbc9

ddev does not want to install mysql 5.7
it appears that it first want to export a mariadb to mysql...

**To Reproduce**

Make a folder and then go to the terminal
cd to this folder

`mkdir sauermusic`
`cd sauermusic`
`ddev config --project-type=drupal9 --php-version="7.4" --mariadb-version="" --mysql-version="5.7" --webserver-type="apache-fpm" --docroot=web --create-docroot`

This is what is output to the terminal:

```
Creating a new ddev project config in the current directory (/Volumes/Project/Website/SauerMusic_Website/sauermusic) 
Once completed, your configuration will be written to /Volumes/Project/Website/SauerMusic_Website/sauermusic/.ddev/config.yaml
 
Created docroot at /Volumes/Project/Website/SauerMusic_Website/sauermusic/web 
You have specified a project type of drupal9 but no project of that type is found in /Volumes/Project/Website/SauerMusic_Website/sauermusic/web 
Ensuring write permissions for sauermusic 
No settings.php file exists, creating one 
Existing settings.php file includes settings.ddev.php 
Configuration complete. You may now run 'ddev start'. 
```

`ddev start`
```
Starting sauermusic... 
v1.17.7: Pulling from drud/ddev-dbserver-mysql-5.7
b4d181a07f80: Pull complete 
a462b60610f5: Pull complete 
578fafb77ab8: Pull complete 
524046006037: Pull complete 
d0cbe54c8855: Pull complete 
aa18e05cc46d: Pull complete 
32ca814c833f: Pull complete 
52645b4af634: Pull complete 
bca6a5b14385: Pull complete 
309f36297c75: Pull complete 
7d75cacde0f8: Pull complete 
536a70b86e81: Pull complete 
4d28e16d312d: Pull complete 
77ebc46577a0: Pull complete 
81d10dd28353: Pull complete 
a6d37a259167: Pull complete 
d39fd4f1e28e: Pull complete 
cc423dbcbafa: Pull complete 
68d58a2e5142: Pull complete 
c713b722c8a2: Pull complete 
f94c3afb5041: Pull complete 
a50d16792204: Pull complete 
5105df19b59a: Pull complete 
Digest: sha256:e9e2aac7866be5b120886d0955d613fc1faf89bf89a590a4d125f5ff53ea6dbf
Status: Downloaded newer image for drud/ddev-dbserver-mysql-5.7:v1.17.7
docker.io/drud/ddev-dbserver-mysql-5.7:v1.17.7
Building db 
Building web 
Recreating ddev-sauermusic-db ...  
Recreating ddev-sauermusic-db ... done 
Recreating ddev-sauermusic-dba ...  
Recreating ddev-sauermusic-web ...  
Recreating ddev-sauermusic-web ... done 
Recreating ddev-sauermusic-dba ... done 
ddev-router is up-to-date 
Failed to start sauermusic: container failed to become healthy: err=container 'db' exited, please use 'ddev logs -s db' to find out why it failed
```

`ddev logs -s db`
```
+ set -eu
+ set -o pipefail
+ SOCKET=/var/tmp/mysql.sock
+ rm -f /tmp/healthy
+ '[' 0 = 2 -a '' = restore_snapshot ']'
++ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/sbin:/usr/local/bin:/usr/local/mysql/bin
++ mysqld -V
++ awk '{sub( /\.[0-9]+(-.*)?$/, "", $3); print $3 }'
+ server_db_version=5.7
++ echo '/mnt/ddev_config/mysql/*.cnf'
+ '[' -d /mnt/ddev_config/mysql -a '/mnt/ddev_config/mysql/*.cnf' '!=' '/mnt/ddev_config/mysql/*.cnf' ']'
+ export BACKUPTOOL=mariabackup
+ BACKUPTOOL=mariabackup
+ command -v xtrabackup
/usr/bin/xtrabackup
+ BACKUPTOOL=xtrabackup
+ '[' '!' -f /var/lib/mysql/db_mariadb_version.txt ']'
++ cat /var/lib/mysql/db_mariadb_version.txt
Starting with db server version=5.7 but database was created with '10.3'.
Attempting upgrade, but it may not work, you may need to export your database, 'ddev delete --omit-snapshot', start, and reimport.
+ database_db_version=10.3
+ '[' 5.7 '!=' 10.3 ']'
+ echo 'Starting with db server version=5.7 but database was created with '\''10.3'\''.'
+ echo 'Attempting upgrade, but it may not work, you may need to export your database, '\''ddev delete --omit-snapshot'\'', start, and reimport.'
+ pid=13
+ set +x
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/sbin:/usr/local/bin:/usr/local/mysql/bin
+ mysqld --skip-networking --skip-grant-tables --socket=/var/tmp/mysql.sock
MariaDB initialization startup failed
Failed to get mysqld running to run mysql_upgrade
```

**Expected behavior**

ddev configured with mysql 5.7

**Screenshots**

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: [e.g. Windows 10, macOS Big Sur, Linux (distro), WSL2 (distro)]
OSX 10.15.7 Catalina

- Docker Desktop version if on macOS or Windows (from "About Docker Desktop")
3.60 (67351)

- ddev version information (use `ddev version`)
1.17.7

- config.yaml contents for the misbehaving project (the part before the comments)
name: sauermusic
type: drupal9
docroot: web
php_version: "7.4"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: ""
mysql_version: "5.7"
use_dns_when_possible: true
composer_version: ""
web_environment: []

- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?
I think I did not get that far... (but I'm a newbie...)

**Additional context**

**Comment by ASauer** [comment]
### What happened
after running `ddev delete --omit-snapshot` and trying again, everything works now. I guess there already was a database with the same name that was preventing the install, I realize now. So this database is lost now (I guess). If this is true, it was nowhere to be found in the log file.

### What did I find
here it reads [(https://ddev.readthedocs.io/en/stable/users/cli-usage/#removing-projects-from-ddev-local)]:

> To remove a project from DDEV-Local's listing you can use the destructive option (deletes database, removes item from ddev's list, removes hostname entry in hosts file).

So, when posting `you may need to export your database, 'ddev delete --omit-snapshot'` it **does not export** the database, but **deletes** the database!

### Why didn't I do what was suggested
That is the reason I did not use this command in the first place since there never was a mariadb database, and a mysql database **was not created**, so why should I want to **export** a database that does not exist?!

If it said, as is correct, `you may need to **delete** your database, 'ddev delete --omit-snapshot'` I would have thought about the option that a database with this name already existed.

### Suggestion for improvement
If possible, and if my observations are correct, I want to suggest to reword this phrase in the error log.

**Comment by rfay** [comment]
It looks like you already had a project named "sauermusic", and it had an incompatible database type?

Please take a look at https://ddev.readthedocs.io/en/stable/users/extend/database_types/ and suggestions or a PR are welcome. 

I understand that you didn't *know* that you had an existing project with this name. You probably did a `ddev start` with the default (mariadb) configuration, which creates project and database. Once you've done that, it requires a little effort to get a new project started with mysql, as in the docs.

I didn't really understand what your suggestion was, so maybe you can restart what you think should happen.

**Comment by ASauer** [comment]
I was experimenting with how to set up `ddev config`.
After each experiment I deleted the folder I made with `mkdir` called `sauermusic`, to have a fresh start.
I had read the documentation at [](https://ddev.readthedocs.io/en/stable/users/extend/database_types/), and I did not want to change the db type, since I'm trying to make a template.
(Somehow making a link does not show up as a link: I select the text and click on the link button, I get two square brackets in front of the link, but placing them around the link does not change anything... I must be missing something...)

**So I suppose that by deleting this folder** I made with `mkdir`, **I also deleted the** `mariadb`.
The question is: am I correct that by doing this, the db was deleted?
That may help me clarify my suggestion.

Thanks for making the script :)
It makes debugging much easier!

**Comment by rfay** [comment]
I don't understand 
> Somehow making a link does not show up as a link

> After each experiment I deleted the folder I made with mkdir called sauermusic, to have a fresh start

Right, you didn't understand that deleting the folder didn't delete the project. The database was *not* deleted, because it's a docker volume, not stored with your project.

**Comment by ASauer** [comment]
OK, I guess I have to learn a lot more about Docker... 
Actually I wanted to use ddev to avoid having to learn to much about Docker, and using Drupal VM made life to complicated :) 
I started reading a book on Docker and did an online course, but I guess I have to learn more about the way and where files are stored...
So, forget about my suggestion.

About making a link:
It did not work in the previous post, and now it does...

So thanks for your help!

**Comment by rfay** [comment]
Thanks. You don't really have to know anything about docker to use ddev, and definitely don't need any courses. Hope you enjoy it as you continue your explorations!

**Comment by ASauer** [comment]
Well, I do have some Docker questions now:

`$ docker ps -a`
If I delete all containers, how will they be rebuilt using ddev?

`$ docker images`
If I delete all Images, how will they be rebuilt using ddev?

I've been searching the web, but can't find the answers...
As far as I understand, all that is needed is a Dockerfile to rebuild everything...

**Comment by rfay** [comment]
You're moving along fast!

With the design of ddev, both containers and images can be destroyed at any time without losing anything. You can delete all of both and nothing bad with happen (because the database, which is the only state not in your codebase) is stored as a docker *volume*. 

`ddev delete images` will explain this, the only problem with deleting all the images is they have to be downloaded again.

`ddev poweroff` deletes all ddev containers. 

You don't need a dockerfile for anything. The necessary images are pulled from hub.docker.com.

**Comment by ASauer** [comment]
Thx!
