### ISSUE TITLE
Show the correct port number

### ISSUE THREAD

**Issue by nerdstein** [drud/ddev#321]
## What happened (or feature request):

After running `ddev start`, I received the following message: `Your application can be reached at: http://core.ddev.local`

## What you expected to happen:

I expected this to show me a message respecting the port that I defined in my docker-compose.yml file.

In this case, I overrode the default port 80 with 8089

## How to reproduce it (as minimally and precisely as possible):

Change the port numbers and run `ddev start`

## Related source links or issues:

**Comment by rfay** [comment]
This seems like a pretty useful request!  We do have upcoming (soon) work in this area anyway for [Test port 80 rather than just try to use it: Graceful sharing and management #126
](https://github.com/drud/ddev/issues/126)

**Comment by rickmanelius** [comment]
Tagging with appropriate labels and putting to the sprint planning board.

**Comment by rickmanelius** [comment]
Linking what looks like a related issue https://github.com/drud/ddev/issues/323.

**Comment by rickmanelius** [comment]
Assigning over to @nmccrory. While the related issue solves the issue of fighting for the same port and the ability to customize, it will be helpful to confirm there are not other use cases that this touches on that are not considered in the other issue.

**Comment by rickmanelius** [comment]
Moving to @rfay because he's working on an upstream dependency. Then we can figure out what remains (if anything) for the scope of this ticket.

**Comment by rfay** [comment]
The overall problem here is not that we don't "show" the correct port, but that we don't currently support anything but ports 80/443. We want to though! Closing this one in favor of [Allow webserving on an alternate port instead of port 80/443](https://github.com/drud/ddev/issues/481) - Thanks for helping us think this through and for the excellent feedback @nerdstein .
