### ISSUE TITLE
`ddev describe` (v1.18-rc1) - displays PHPMyAdmin even when it's not enabled

### ISSUE THREAD

**Issue by shaal** [drud/ddev#3212]
**Run a Diagnostic and Paste Link Here**
https://gist.github.com/shaal/04896f67428722c4743384ed7685e2ee

**Describe the bug**

In DrupalPod, when using the omit-router new feature as part of ddev 1.18-rc1, when running 

`ddev status`
```
tWidth=193 urlPortWidth=77.2 infoWidth=48 
┌──────────┬─────────┬──────────────────────────────────────────┬──────────────────────┐
│ SERVICE  │ STAT    │ URL/PORT                                 │ INFO                 │
├──────────┼─────────┼──────────────────────────────────────────┼──────────────────────┤
│ Project  │         │ drupalpod                                │ /workspace/DrupalPod │
├──────────┼─────────┼──────────────────────────────────────────┼──────────────────────┤
│ web      │ running │ http://127.0.0.1:8080                    │ PHP 7.4 nginx-fpm    │
│          │         │ InDocker: ddev-drupalpod-web:443,80,8025 │                      │
│          │         │ Host: localhost:2222,8080                │                      │
├──────────┼─────────┼──────────────────────────────────────────┼──────────────────────┤
│ db       │ running │ InDocker: ddev-drupalpod-db:3306         │ MariaDB 10.3         │
│          │         │ Host: localhost:3306                     │ User/Pass: 'db/db'   │
│          │         │                                          │ or 'root/root'       │
├──────────┼─────────┼──────────────────────────────────────────┼──────────────────────┤
│ PHPMyAdm │ running │ InDocker: ddev-drupalpod-dba:80          │                      │
│ in       │         │ `ddev launch -p`                         │                      │
├──────────┼─────────┼──────────────────────────────────────────┼──────────────────────┤
│ Network  │         │ bind-all-interfaces ENABLED              │                      │
└──────────┴─────────┴──────────────────────────────────────────┴──────────────────────┘
```

`ddev launch -p`
```
/workspace/DrupalPod/.ddev/commands/host/launch: line 61: xdg-open: command not found
Failed to run launch -p; error=exit status 127
```

**To Reproduce**

1. Open https://github.com/shaal/DrupalPod/pull/34 in Gitpod
1. Run `ddev status`

**Expected behavior**

Display only services that are actually running.

**Screenshots**

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: [e.g. Windows 10, macOS Big Sur, Linux (distro), WSL2 (distro)]
- Docker Desktop version if on macOS or Windows (from "About Docker Desktop")
- ddev version information (use `ddev version`)
- config.yaml contents for the misbehaving project (the part before the comments)
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

**Additional context**

**Comment by rfay** [comment]
Did you `omit_containers["dba"]` ? Just  `omit_containers['ddev-router']` doesn't omit the dba container. You need to omit the dba container for that. As soon as I omit the dba container it does not show in ddev describe.

**Comment by rfay** [comment]
I checked in the provided gitpod and in fact, the dba container is not omitted. The only thing you omit is in global_config.yaml:
```
omit_containers: [ddev-router]
```

So if you just change that to `omit_containers: [ddev-router, dba]` you'll have the behavior you want... if that's what you want and you don't want anybody to have phpmyadmin.
