### ISSUE TITLE
Suggestions for the `ddev describe` and `ddev list` output

### ISSUE THREAD

**Issue by rpkoller** [drud/ddev#3242]
I've taken a look at the improved and updated output of `ddev describe` and `ddev list` in DDEV 1.18.0-rc2. I've noticed one or two details which might be discussed or perhaps improved further. 

**_ddev described_**

![ddev_describe](https://user-images.githubusercontent.com/1665422/132953235-cbed64fe-13a2-450e-a2c0-f8b4032dd2c7.png)

-  would it make sense to increase the width of the `SERVICE` column in the `describe.go` file in line 80 from `WidthMax: 8` to `WidthMax: 10` so there is no wrapping for the listed default containers provided by DDEV? 

-  would it make sense to switch the position of the headline row (SERVICE, STAT, URL/PORT, INFO) and the one currently underneath (Project, name,path)? Basically the Project row provides the context for the whole `describe` output underneath. It might be a better fit to place it as the title of the output on top of the table like: 

Project: danse ( ~/Sites/danse )

**_ddev list_**
![ddev_list](https://user-images.githubusercontent.com/1665422/132953980-a614e0af-d983-42a5-974b-4c7670b04fda.png)

-  you have the first row with NAME, TYPE, LOCATION, URL and STATUS. The title is written in capital letters. If you take now a look at the last row you also have capital letters. that gives the initial visual queue  that the last row would consist of  titles as well. often longer tables are bordered/cased by title rows but in this case ROUTER is an actual container like the others listed above. so why not change ROUTER to router and also move HEALTHY to the STATUS column and rename it to `running (health)`. Semantically it would be also a better fit there. Healthy is more of a status than a location.

**Comment by rfay** [comment]
Are you interested in giving a go at this? You can easily experiment with gitpod at https://gitpod.io/#https://github.com/drud/ddev (and you can also experiment on your machine, doesn't take too much setup, https://github.com/drud/ddev/blob/master/docs/developers/building-contributing.md

Any changes will have to come really fast though, all the outstanding issues to be included in v1.18 are closed, so it's testing time now. I don't mind minor cosmetic changes.

I would add to your list colorizing the "running" STAT in `ddev list`

I'm pretty sure that changing the headers to mixed case is just a minor change to the table styles, but I haven't looked at it. 

I've spent days and days trying to achieve the goals of making it mostly work out in any reasonable width terminal but also to look nice and expand properly. It's not easy. I don't mind you having a go at it, but doubt I'll put much more into it for this release.

**Comment by rfay** [comment]
I figured out how to do mixed-case for header and footer.

**Comment by rfay** [comment]
Your ideas were good and very much appreciated @rpkoller - I'd appreciate if you could review https://github.com/drud/ddev/pull/3243

**Comment by rpkoller** [comment]
uhhh you were faster. ;) i already started looking at ddev on gitlab but was a bit lost and overwhelmed. i sure would take a look and give a try but in case of the immanent release i would be the wrong pick to tackle that that quickly :D ( not a developer but happy to investigate and learn new stuff ;) )
