### ISSUE TITLE
Docs on adding additional daemons to ddev-webserver supervisord config

### ISSUE THREAD

**Issue by kristoftorfs** [drud/ddev#3282]
**Is your feature request related to a problem? Please describe.**
There is no easy way to add supervisord programs.

**Describe the solution you'd like**
I would like to be able to add custom supervisord programs, while keeping them in the git repository and be able to enable/disable them at will.

Optionally:
- Preferably, all supervisord programs should initially be disabled
- Allow disabling/enabling xdebug per supervisord program

**Comment by kristoftorfs** [comment]
I saw that article, but my concern with her method is that when (however unlikely) the ddev supervisord configuration files are updated in a future version we might break things.

Wouldn't it be possible to add another include directory in the main supervisor.conf that we can mount with a volume?

**Comment by rfay** [comment]
I don't actually object to another directory, but /etc/supervisor/conf.d is totally standard and expected. It's not something created by the ddev build, but a standard feature of supervisord. Unique new files in it shouldn't cause trouble that I foresee. But I suspect I'm misunderstanding something you're trying to say.

**Comment by tyler36** [comment]
There is a recipe, [Laravel Queue Worker](https://github.com/drud/ddev-contrib/tree/master/web-container-dockerfiles/laravel-queue-worker), that runs supervisor.

You might be able to adapt it for your use case.

**Comment by rfay** [comment]
The ddev-cron recipe does this as well, super easy, see https://github.com/tyler36/ddev-cron

**Comment by tyler36** [comment]
The ddev-laravel-queue recipe does this too:  https://github.com/tyler36/ddev-laravel-queue

**Comment by rfay** [comment]
This was fixed with the addition of 
* https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#running-extra-daemons-in-the-web-container
* https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#explicit-supervisord-configuration-for-additional-daemons
