### ISSUE TITLE
Official generic gitpod support

### ISSUE THREAD

**Issue by rfay** [drud/ddev#3283]
@shaal has done wonders with DrupalPod and ddev-gitpod... but we need a generic DDEV environment for GitPod and GitHub Codespaces, and it shouldn't be that hard to do. This will help loads of people.

**Comment by shaal** [comment]
I'd love to hear more!

(and help with anything I can of course)

**Comment by Decipher** [comment]
**CloudIDE** would be my preference.

**Comment by rfay** [comment]
Can you be more specific about what you're talking about @Decipher ?

**Comment by Decipher** [comment]
When you first run the `ddev config` command you are provided with 3 questions which determined the configuration for your codebase.

At the least, I would like to see a `CloudIDE` option added to these steps which allowed you to choose: `None, Gitpod, GitHub workspaces`. Ideally it could determine the default answer based of available environment variables.

DDev would maintain some template configuration to enable the CloudIDE specific changes, such as the `docker-compose.host-docker-internal.yaml` file that DrupalPod creates: https://github.com/shaal/DrupalPod/blob/main/.gitpod/ddev-in-gitpod-setup.sh#L38-L47

It would also be nice to have an advanced configuration option that allows you to choose the ports for specific services and other types of config, such as being able to set `bind_all_interfaces` to `TRUE`.

**Comment by rfay** [comment]
Thanks - 
* I would expect it to always `bind_all_interfaces` and turn off ddev-router in the case of GitPod. 
* host.docker.internal is not in our control and so it's found dynamically by DrupalPod/ddev-gitpod. There may be a way to work around this now that docker 20.10 is available.

**Comment by shaal** [comment]
I think the above comment is already resolved with ddev + gitpod recent changes, is that correct?

**Comment by rfay** [comment]
We can give it a shot! Not sure about the host.docker.internal issue, which is different from the need to `bind_all_interfaces`

**Comment by shaal** [comment]
When trying to run `ddev launch` inside Gitpod workspace, the following error is displayed: 
```bash
/workspace/DrupalPod/.ddev/commands/host/launch: line 61: xdg-open: command not found
Failed to run launch ; error=exit status 127
```

I think we should add that to this feature (+ #3371 ), so when running `ddev launch` inside a Gitpod workspace, it should not try open the browser directly. Instead, ddev can utilize Gitpod's own command - `gp preview 8080`

**Comment by shaal** [comment]
@rfay wouldn't it be better to split this into 2 separate PRs?

1. Launch a gitpod instance for any project (on github or gitlab) with a special URL
1. Add ddev flag for gitpod configuration (without adding any external config files like we currently have to create)

To me, the ddev Gitpod flag feature is the most urgent.
Please let me know how I can help.

**Comment by rfay** [comment]
Well, far more than 2 PRs :)  https://github.com/drud/ddev/pull/3371 is exploring this territory, but what we'll actually need for your first item is a separate repository that's used for launching (drud/ddev isn't the right one) and a website that will help generate the special URL. 

Please open an issue for your second item, explain what you're looking for and how you want to use it, thanks!

**Comment by rfay** [comment]
Official gitpod support begins with today's v1.18.2 release, along with https://github.com/drud/ddev-gitpod-launcher and the ddev chrome extension.

**Comment by weitzman** [comment]
Sounds great ... Whats the ddev chrome extension?

**Comment by rfay** [comment]
Look for ddev in chrome web store, install it. It has a ways to go, but it just creates a button like the gitpod chrome extension, which will open a repo using ddev-gitpod-launcher.

**Comment by rfay** [comment]
Docs in https://github.com/drud/ddev/pull/3434 @weitzman - would love to have your review.
