### ISSUE TITLE
config_yaml page in docs gets a table wider than the pane created for it

### ISSUE THREAD

**Issue by tyler36** [drud/ddev#3289]
**Problem**

Recently on Slack, you introduced me to the `omit_containers` configuration option. I was slightly embarassed that I missed it in my searchs so I visitied the [documentation](https://ddev.readthedocs.io/en/stable/users/extend/config_yaml/).

It was then that I noticed something weird ... some of the text appears cut off ('e' in additive). 
![ddev-1920x](https://user-images.githubusercontent.com/7234392/136485075-b4d3c0ad-31a6-4d97-b84e-07a2be2986a7.jpg)

It's not just that section either. The `ngrok_args` look fine here
![ddev-ngrok-1920](https://user-images.githubusercontent.com/7234392/136485080-39122958-d2dd-47b6-988b-0fa3ef147417.jpg)

... but are clearly different at this browser size. The above wouldn't work if you were playing along.
![ddev-ngro-expected](https://user-images.githubusercontent.com/7234392/136485085-9e1fad2d-054a-4258-9294-5b5b62a589c6.jpg)

Usually, I run my screen 1920 x 1080 so the "bad" screenshots were taken with Chrome full-screen; and is trigger at `1220px` breakpoint. I accidently discovered the issue when split a tab off to keep slack open while checking the documentation.

This effect also happens in MS Edge (94) but _Firefox (92, 93) is OK_. I am unable to check Safari.

**To Reproduce**

1. Open  [documentation](https://ddev.readthedocs.io/en/stable/users/extend/config_yaml/) in Chrome/MS Edge
2. Check text at full-screen
3. Check text around `1220px` +/- 50px

**Screenshots**

See above.

**Version and configuration information (please complete the following information):**

OS: Win10
Chrome: Version 94.0.4606.81 (Official Build) (64-bit)
Edge: Version 94.0.992.38 (Official build) (64-bit)
Firefox: 92 & 93

**Comment by rfay** [comment]
For somebody of your capabilities it's easier to fix this than to write an issue :) Just click the pencil on that page and edit it, thanks!

**Comment by rfay** [comment]
It looks like on some widths of browser the columns are wider than the pane created for them. You can move them back and forth, but it certainly isn't optimal.

**Comment by rfay** [comment]
Looks like it's just that table that has trouble, I don't see it happening on other pages right away. 

It also happens with `mkdocs serve`, so it's not a readthedocs problem, apparently a mkdocs problem I guess.

**Comment by rfay** [comment]
See https://github.com/drud/ddev/pull/3290

Would love to see you come up with a real solution, a casual review of https://github.com/mkdocs/mkdocs/issues doesn't turn up anything for me.
