### ISSUE TITLE
Solution for addressing `import-db` issues with phpmyadmin exports.

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#329]
## What happened (or feature request):

* Feature Request

## What you expected to happen:

We currently provide phpmyadmin as a tool for developers that prefer a UI over a CLI when interacting with an app's database. Unfortunately, database exports from phpmyadmin will by default place a "Create Table" command in the SQL file. If that database name happens to not match what is expected in ddev, the import will fail.

## How to reproduce it (as minimally and precisely as possible):

* Export a DB from phpmyadmin.
* Open the SQL file and change the name of the created database.
* Attempt an `import db` with the updated file.

**Comment by rfay** [comment]
I guess I don't think this has anything to do with ddev... It's one of the world's complexities that has to be resolved by the developer.

**Comment by rickmanelius** [comment]
Just leaving this as a placeholder to note an issue with a workflow that I didn't expect to hit a snag on :) This might be solved with an error message or link to FAQ versus business logic to correct! And the only reason I consider this in scope is if we provide phpmyadmin as a feature, this scenario is probably going to happen.

**Comment by rickmanelius** [comment]
I think this would be valuable to address, but I'm also happy to wait until it becomes an actual end-user request versus an anticipated need.
