### ISSUE TITLE
[docs search] console/js error: fix-search.js javascript error in mkdocs

### ISSUE THREAD

**Issue by tyler36** [drud/ddev#3291]
**Describe the bug**

While investigating #3289 I noticed that I was getting a console error.
```javascript
fix-search.js:20 Uncaught ReferenceError: $ is not defined
    at fix-search.js:20
    at fix-search.js:44
````

**To Reproduce**

1. Visit [documentation ](https://ddev.readthedocs.io/en/stable/) page.
2. Check other pages

**Screenshots**

![error-fix-search](https://user-images.githubusercontent.com/7234392/136496548-9690b509-a878-43b3-9eae-1d49409c2b6b.jpg)

**Version and configuration information (please complete the following information):**
Present in all tested browsers:
- Chrome 94
- Firefox 93
- MS Edge 94

OS: Win10

**Additional context**

Might be related to #3289 if site uses javascript to manipulate DOM.

**Comment by rfay** [comment]
This conversation would be better on the PR, but...

* You have to work with this branch I pushed, rfay:20211008_upgrade_mkdocs_material
* You don't need readthedocs at all, as this is all about mkdocs.
* The jsmin error was fixed a few weeks ago, so I imagine you're not using the code you need?

Please make sure you're using python3/pip3. I'm not sure about your environment, but in most places python3 is now called python3 and pip3 is now called pip3. 

In the requirements.txt of the current upstream/master or rfay:20211008_upgrade_mkdocs_material you'll see `jsmin==3.0.0`, so you definitely don't have the right thing checked out.

Once you get the right thing checked out, you can `mkdocs build` and `mkdocs serve`
