### ISSUE TITLE
Apache folder root ownership in nginx project causes error on DDEV start

### ISSUE THREAD

**Issue by kljr** [drud/ddev#3293]
https://gist.github.com/kljr/e64bc5e4e85bd1321742c6ea37dda3ee

1. Create a new project with nginx configured as webserver.
2. Run DDEV start.
3. An "apache" folder is created owned by root rather than the user.
4. DDEV delete
5. DDEV start
6. Error:
Failed to start projectname: open /home/projectname/ddev/apache/seconddocroot.conf.example: permission denied 
7. DDEV start again, no error.

**Comment by rfay** [comment]
Hmm, you didn't provide much of the test_ddev.sh script output... or maybe it died? 

* Please say what Linux distro you're using (and version)
* Please tell me if the regular Drupal 9 Quickstart works for you (https://ddev.readthedocs.io/en/stable/users/cli-usage/#drupal-9-composer-setup-example) - Or whatever CMS you're comfortable with, there are several quickstarts there. 

The apache folder is created on the host (on your computer) but if it's being created read-only on the host (please look) it means perhaps your UMASK is particularly restrictive?

Interesting that you can run `ddev start` the second time and it works. Is this repeatable? Please see if you can figure out what's going on with permissions.

**Comment by rfay** [comment]
I don't know how you can have a different experience with the D9 quickstart. Perhaps you can share your .ddev/config.yaml (just the top part). Please look for what's different between the quickstart and your workflow.

**Comment by rfay** [comment]
Is it possible you're using `ddev exec` with a `sudo` command?

**Comment by kljr** [comment]
In the config.yml of the affected project I have:

```
hooks:
  post-start:
  - exec: bash /var/www/html/.ddev/setup-drupal
```
1. If I remove that configuration, the ownership issue does not occur.

2. If I keep that configuration, but leave the referenced script blank, the ownership issue occurs.

Thus it appears the mere presence of the config is causing the issue, rather than something in the script.
