### ISSUE TITLE
Docs: Links for hosting provider integration examples are broken

### ISSUE THREAD

**Issue by mandrasch** [drud/ddev#3296]
https://ddev.readthedocs.io/en/stable/users/providers/provider-introduction/

e.g. link to https://github.com/drud/ddev/blob/master/cmd/ddev/cmd/dotddev_assets/providers/rsync.yaml.example

I found the file here - if these are the correct URLs, I can send a PR replacing the links in the docs.

https://github.com/drud/ddev/blob/master/pkg/ddevapp/dotddev_assets/providers/rsync.yaml.example

Thanks very much for providing DDEV! 👍

**Comment by rfay** [comment]
Thank you very much - looks like all those links are broken, thank you very much for fixing them - just click the pencil link on that page. And you have the right place to point to. Thanks!

**Comment by rfay** [comment]
Fixed in #3300 thanks!
