### ISSUE TITLE
Autogenerated code / templates on ddev start

### ISSUE THREAD

**Issue by wolfiesites** [drud/ddev#3297]
Hello, 
I d like to ask if there is a way to custom auto generated code / template after ddev start?

I know I can change it manually each time but imo its inefficient.

on example:
ddev generates this ``wp-config.php`` file on each wp project while ``ddev start``

and ABSPATH with combination of WP CLI commands generates this annoying notice in output in terminal:
"Notice: ABSPATH is already defined please bla bla bla"

To fix that, the template of ``wp-config.php`` needes to be changed for sth like that:

```
if( defined('ABSPATH')){
/** Absolute path to the WordPress directory. */
define('ABSPATH', dirname(__FILE__) . '/');
}
```

I would like to be able to change autogenerated template for ``wp-config.php`` file globally. 
Or have ability to define global hook which will be lunching command for each new created project. 
That command would be overriding this newly auto generated file.

That would solve the problem.

Awesome project!

**Comment by gilbertsoft** [comment]
A new binary will be available in some minutes in the assinged PR, please check @wolfiesites .

**Comment by rfay** [comment]
The binaries to take a look at are generated on https://github.com/drud/ddev/actions/runs/1326036484 so you can test and comment over there there in https://github.com/drud/ddev/pull/3298 @wolfiesites 

But you should know that you don't have to let ddev generate those settings files anyway, you can do it anyway you're comfortable with. Please take a look at https://ddev.readthedocs.io/en/stable/users/topics/settings_files/ and see if there's anything you'd suggest adding there.

**Comment by rfay** [comment]
To answer the original question though, there isn't a way to change the auto-generated code, but you can certainly prevent its generation, or take over the files after generated, or handle things by putting the include of generated files before or after your own code so you can do what you want.

WP is pretty hard this way because it uses defines, which make a mess.
