### ISSUE TITLE
Docs: Provide wordpress quickstart for the standard wordpress?

### ISSUE THREAD

**Issue by mandrasch** [drud/ddev#3299]
My open suggestion would be to provide an example of a standard wordpress installation which can be used out of the box in the quickstart chapter https://ddev.readthedocs.io/en/stable/users/cli-usage/#wordpress-quickstart

In my personal opinion roots/bedrock as first example is a little bit confusing to people who just want to get wordpress up and running. I thought in the beginning DDEVs project-type=wordpress is tightly couple with it (which I now know is not the case :))

A suggestion I came up with is this:

#### Setup Example Using WP-CLI

```bash
mkdir my-wp-site
cd my-wp-site
ddev config --project-type=wordpress --docroot=web --create-docroot
ddev start
ddev ssh
cd web/
wp core download
wp core install --url=https://my-wp-site.ddev.site --title="New WordPress" --admin_user=admin --admin_email=admin@example.com --prompt=admin_password
exit
ddev launch
```

I tested it on mac, it works, wp core install does not delete the existing wp-config.php, there are just two notices displayed:

```
PHP Notice:  Constant ABSPATH already defined in phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1231) : eval()'d code on line 18

Notice: Constant ABSPATH already defined in phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1231) : eval()'d code on line 18
```
Found https://github.com/drud/ddev/issues/3297, this should fix it? 🤔 

Just a suggestion, no hard feelings if this issue gets closed. Thanks for maintaining DDEV! 👍 👍 👍

**Comment by rfay** [comment]
This would be accepted, go ahead and do a PR. 

The problem with "standard" WP is there isn't actually a "standard", but I'm still willing to go with your definition of standard. Add it as a 3rd option on WP, and add it before "Composer Setup Example Using roots/bedrock" with a good descriptive name. You can do this by just editing https://ddev.readthedocs.io/en/stable/users/cli-usage/#wordpress-quickstart - click the pencil on that page in the upper right. But test it carefully please!

**Comment by rfay** [comment]
Before switching to the roots example, we had something like the git checkout instructions for years, https://ddev.readthedocs.io/en/stable/users/cli-usage/#git-clone-example

But it seemed so few people had their sites under git control that it had no meaning to them. Your strategy of a `wp core install` seems quite good.

**Comment by jonaseberle** [comment]
I would leave out the webroot `./web`.

This is a bit simpler (and uses `DDEV_PRIMARY_URL`):
```shell
mkdir my-wp-site
cd my-wp-site/
ddev config --project-type=wordpress
# "ddev start" is not even needed here since "ddev wp" will startup ddev, too
ddev wp core download
# optional: you can use this automated install or leave it out (and finish installation in the frontend)
ddev exec 'wp core install --url=$DDEV_PRIMARY_URL --title="New WordPress" --admin_user=admin --admin_email=admin@example.com --prompt=admin_password'
ddev launch
```

**Comment by jonaseberle** [comment]
Would be nice but I don't think so because `$DDEV_PRIMARY_URL` is not defined in the calling shell. I tried some escaping like 
`ddev wp core install --url='$DDEV_PRIMARY_URL' --title="New WordPress" --admin_user=admin --admin_email=admin@example.com --prompt=admin_password`
but to no avail.

**Comment by rfay** [comment]
`ddev wp 'core install --url=$DDEV_PRIMARY_URL --title="New WordPress" --admin_user=admin --admin_email=admin@example.com --prompt=admin_password'` works, but not sure it's worth the bother.

**Comment by rfay** [comment]
Looking forward to your docs PR, thanks.
