### ISSUE TITLE
Develop in container, don't mount anything

### ISSUE THREAD

**Issue by andyg5000** [drud/ddev#3303]
Hi,

I have a few colleagues that use DDEV and I'm wondering if it's possible to use vscode's develop in container https://code.visualstudio.com/docs/remote/containers and not map anything to the host OS. We basically just want docker volumes that can only be accessed in the ddev containers.

I looked for other similar issues and couldn't find one, so apologies if this is a dupe.

Thanks!
Andy

**Comment by rfay** [comment]
You can do exactly what you want using `no_project_mount` and adding your own volume mount via `docker-compose.*.yaml`, Or just turn on `mutagen_enabled` and it will do that for you.
