### ISSUE TITLE
Importing MySQL Database & Configuring an existing D8 site

### ISSUE THREAD

**Issue by begrafx** [drud/ddev#3304]
I need some help. I am attempting to move/copy a Drupal 8 site that is currently online, into DDEV to do some update work. I have "zipped" up the existing site, and exported the MySQL database. Then, on my local system, I created a new folder, I entered it and ran the `DDEV Config` process. Then I unzipped the archive into the folder, and I did a `ddev import-db`, which appears to have completed successfully:

`% ddev import-db
Provide the path to the database you wish to import. 
Pull path: ../edc-hold/i4222120_drup1.sql
 148MiB 0:00:22 [6.65MiB/s] [================================>] 100%            
Ensuring write permissions for edc-upgrade 
Existing settings.php file does not include settings.ddev.php, modifying to include ddev settings 
Successfully imported database 'db' for edc-upgrade 
Existing database 'db' was dropped before importing`

However, when I `ddev launch` the site, it goes to the install screen, so it isn't seeing the database. Based on what the import response is saying, and the install screen, clearly it isn't seeing the database. The settings.php file is still showing the old information from the original host, and the settings.ddev.php seems to match every other working DDEV site I look at. I've looked at the DDEV documentation, and I'm not seeing this addressed; so before I "blow something up", I wanted to seek direction. I'm not sure if I need to modify the settings.php or the settings.ddev.php (or both?) 

Thank you in advance.

**Comment by begrafx** [comment]
Just as reference, the `settings.php` file that it was using on the original host, that segment quoted above shows:

`$databases['default']['default'] = array (
  'database' => 'i4222120_drup1',
  'username' => 'i4222120_drup1',
  'password' => [PASSWORD]',
  'prefix' => 'drup_',
  'host' => 'localhost',
  'port' => '',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
  'driver' => 'mysql',
);`

as this is my first occasion to import a database into the DDEV environment, I'm not sure if I need to add some of this additional information into the `settings.ddev.php` file, or something?

**Comment by begrafx** [comment]
Here's what I get:

`$ drush sql-cli
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 127
Server version: 10.3.30-MariaDB-1:10.3.30+maria~focal-log mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [db]> 
`

**Comment by begrafx** [comment]
`MariaDB [db]> status
--------------
mysql  Ver 15.1 Distrib 10.3.29-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Connection id:		127
Current database:	db
Current user:		db@172.18.0.8
SSL:			Not in use
Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server:			MariaDB
Server version:		10.3.30-MariaDB-1:10.3.30+maria~focal-log mariadb.org binary distribution
Protocol version:	10
Connection:		db via TCP/IP
Server characterset:	utf8mb4
Db     characterset:	utf8mb4
Client characterset:	utf8
Conn.  characterset:	utf8mb4
TCP port:		3306
Uptime:			2 hours 10 min 14 sec

Threads: 7  Questions: 634  Slow queries: 0  Opens: 201  Flush tables: 1  Open tables: 192  Queries per second avg: 0.081
--------------`

**Comment by rfay** [comment]
You'd need to `show tables;` after. connecting with `drush sql-cli`

**Comment by rfay** [comment]
You can certainly remove the prefix from all the tables with some fancy sql statements, you'll find them easy enough, but it may not be that important. Just getting the config right will get you going, then if you want to undertake removing the prefix someday later you can do that.

**Comment by jose-carlos-2021** [comment]
ayuda por favor
no me reconoce la base de datos
tengo el settings.ddev.php y settings.php
the database is created
tables without prefix
settings
$databases['default']['default'] = array (
  'database' => 'db',
  'username' => 'db',
  'password' => 'db',
  'prefix' => '',
  'host' => 'localhost',
  'port' => '3306',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
  'driver' => 'mysql',
);

**Comment by rfay** [comment]
Host should be 'db', not 'localhost'

**Comment by jose-carlos-2021** [comment]
In other projects I have it as localhost and they work

I can't modify settings.ddev.php file
this is how it comes by default

// If DDEV_PHP_VERSION is not set but IS_DDEV_PROJECT *is*, it means we're running (drush) on the host,
// so use the host-side bind port on docker IP
if (empty(getenv('DDEV_PHP_VERSION') && getenv('IS_DDEV_PROJECT') == 'true')) {
  $host = "127.0.0.1";
  $port = 64865;
}

$databases['default']['default'] = array(
  'database' => "db",
  'username' => "db",
  'password' => "db",
  'host' => $host,
  'driver' => "mysql",
  'port' => $port,
  'prefix' => "",
);

drush status -l myhost
 PHP executable         :  /usr/bin/php
 PHP configuration      :  /etc/php/7.3/cli/php.ini
 PHP OS                 :  Linux
 Drush script           :  /var/www/html/vendor/drush/drush/drush.php
 Drush version          :  8.4.10
 Drush temp directory   :  /tmp
 Drush configuration    :
 Drush alias files      :

does not recognize the settings.ddev.php or databases

**Comment by rfay** [comment]
@jose-carlos-2021 You may be able to use "localhost" in your settings on a computer where the web server and the db server are on the same computer, but in ddev, they're in separate containers, and the hostname of the one that has the db server in it is "db". "localhost" can't work, you can't connect. 

Please open a new issue. This issue was closed many months ago. There are [lots of other ways to get support](https://ddev.readthedocs.io/en/latest/#support-and-user-contributed-documentation) (and more interactive support like on Discord, https://discord.gg/hCZFfAMc5k). 

When you open a new issue, please follow the instructions and do a `ddev debug test` and put the results in a gist on gist.github.com (or another pastebin)
