### ISSUE TITLE
Cant start ddev : Service 'web' failed to build (corrupted docker on linux/btrfs)

### ISSUE THREAD

**Issue by OCTOGONE-DEV** [drud/ddev#3306]
-
I'm facing a error at `ddev start` and cant start the ddev machine - Drupal 9 project.

Without succes, I've tried different version of docker-compose and I've tried to clean everything with
 `ddev poweroff && docker rm -f $(docker ps -a -q) && docker rmi $(docker images --filter "dangling=true" -q --no-trunc) && docker rmi -f $(docker images -q) && docker volume rm ddev-ssh-agent_dot_ssh ddev-ssh-agent_socket_dir`

**Error at ddev start** 
```

     Service 'web' failed to build : The command '/bin/sh -c (groupadd --gid $gid "$username" ||
     groupadd "$username" ||
     true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" ||
     useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username" ||
     useradd  -l -m -s "/bin/bash" --gid "$gid" --comment '' "$username")' returned a non-zero code: 9
```

[Console screenshot](https://i.stack.imgur.com/J6kPx.png)

- - - 

**OS**: Linux Mint 20.2 (BTRFS)

**Docker** version 20.10.9, build c2ea9bc

**docker-compose** version 1.29.2, build 5becea4

**Composer** version 2.1.9 2021-10-05 09:47:38

**ddev** version v1.18.0

**Comment by rfay** [comment]
Had you been using btrfs before? Do you have any reason to think it should work with Docker? I see these docs, https://docs.docker.com/storage/storagedriver/btrfs-driver/ but I wouldn't just expect btrfs to work. 

If you're not using the official docker repositories I guess you should try that.

**Comment by OCTOGONE-DEV** [comment]
What do you mean by "upstream"?

**Comment by rfay** [comment]
Linux Mint is based on Ubuntu or Debian.IIRC it can be one or the other for various versions of mint? I want to know what the upstream distro is (Ubuntu or Debian, and which version)

**Comment by OCTOGONE-DEV** [comment]
> Ubuntu 20.04 is not based on Debian 11, but thanks for the info. Debian 11 just came out, 20.04 came out in April 2020.
> 
> Are you using the Docker repositories or just using the docker you get from Mint?
Docker repo', i've used [this documentation](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04) to install docker :

**Comment by arturu** [comment]
I have had the same problem. In my case the "drud/ddev-ssh-agent" image was not being built. It took me 2 days to get back up and running :( 
My problem occurred after doing distribution updates (not ddev) and reboot.

At first the errors I saw was the following:
`Failed to start arturu5: failed to start ddev-ssh-agent: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-arturu5 docker-compose -f /home/arturu/.ddev/.ssh-auth-compose-full.yaml -p ddev-ssh-agent up --build --force-recreate -d', action='[-p ddev-ssh-agent up --build --force-recreate -d]', err='exit status 1', stdout='Sending build context to Docker daemon     259B
Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
', stderr='1 error occurred:
	* Status: pull access denied for 1000, repository does not exist or may require 'docker login': denied: requested access to the resource is denied, Code: 1
`
and
`Status: pull access denied for 1000, repository does not exist or may require 'docker login': denied: requested access to the resource is denied, Code: 1`

I removed all images and containers and the errors appeared: 
`The command '/bin/sh -c (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username" || useradd  -l -m -s "/bin/bash" --gid "$gid" --comment '' "$username")' returned a non-zero code: 6, Code: 6`
and
`groupadd: invalid group ID 'drud/ddev-ssh-agent:v1.18.0'`

Finally I was able to find this thread and this [reply ](https://github.com/drud/ddev/issues/3306#issuecomment-943655185) was very useful to me, however, I made several attempts to find the right solution for my case. 

I exported all the db with a mariadb docker image (10.3 the same version used by ddev)

`docker run --name salvami -v <project-name>-mariadb:/var/lib/mysql -e MARIADB_ROOT_PASSWORD=<pass> -d mariadb:10.3`

`docker exec -it salvami /bin/bash`

`cd /var/lib/mysql`

`mysqldump ... etc etc
exit`

`# cp /var/lib/docker/volumes/<project-name>-mariadb/_data/db-dump.sql ...`

- ddev poweroff
- docker system prune -a
- docker rm -f $(docker ps -a -q)
- docker rmi $(docker images --filter "dangling=true" -q --no-trunc)
- docker rmi -f $(docker images -q)
- remove all volumes
- uninstall ddev and docker-compose
- uninstall docker-ce and related package
- sudo rm -rf /var/lib/docker
- sudo rm -rf /etc/docker
- removed .ddev and .docker folder in /home/username
- reboot (<--- important!!! )
- re-installing everything (docker-compose from apt repository)
- ddev start in ddev machine folder
- ddev import-db ...

I solved it thanks to this tread, thanks. 


**OS** POP_OS 21.04 last update
**Composer** 2.0.9 2021-01-27 16:09:27
DDEV 
- **version** v1.18.0         
- **architecture**    amd64                                   
- **db** drud/ddev-dbserver-mariadb-10.3:v1.18.0 
- **dba** phpmyadmin:5                            
- **ddev-ssh-agent** drud/ddev-ssh-agent:v1.18.0             
- **docker** 20.10.10                                
- **docker-compose** 1.25.0                                  
- **mutagen** 0.12.0-beta7                            
- **os** Linux arturu 5.13.0-7620-generic # 20~1634827117~21.04~874b071-Ubuntu SMP Fri Oct 29 15:06:55 UTC  x86_64 x86_64 x86_64 GNU/Linux                                  
- **router** drud/ddev-router:v1.18.0                
- **web** drud/ddev-webserver:v1.18.0

**Comment by rfay** [comment]
Seems there's a way to get a corrupted docker image on Linux. I've also seen something like this on Gitpod.

**Comment by felmab** [comment]
The same is happening for me. Archlinux here, no BTRFS involved, so this issue might be more general and potentially affect a lot more users, thus it would be nice to find the cause of it.

Tried some of the things above, but honestly I am a bit reluctant to remove all volumes :scream: Right now I am stuck.

Docker version 20.10.10, build b485636f4b
Docker Compose version 2.1.0

DDEV
* **version** v1.18.0
* **architecture** amd64
* **db** drud/ddev-dbserver-mariadb-10.3:v1.18.0
* **dba** phpmyadmin:5
* **ddev-ssh-agent** drud/ddev-ssh-agent:v1.18.0
* **docker** 20.10.10
* **docker-compose**  2.1.0
* **mutagen** 0.12.0-beta7
* **os** linux
* **router** drud/ddev-router:v1.18.0
* **web** drud/ddev-webserver:v1.18.0

**Comment by felmab** [comment]
On my machine, Docker was upgraded on October 4, so it does not look like it is the culprit. The latest release of DDEV was on September 28. But then, I upgraded Docker Compose on November 3... wait!

After downgrading Docker Compose from 2.1.0 to 2.0.1, my projects can be launched again, hurray!

With a bit of luck, we might have narrowed it down... Now, the issue is we all use different versions of it: 1.29.2 for @OCTOGONE-DEV, 2.1.0 for me, and 1.25.0 for @arturu (BTW is this still valid after you reinstalled the package?).

**Comment by felmab** [comment]
Oh, I see @rfay already posted on [this issue](https://github.com/docker/compose/issues/8882) and opened [this one](https://github.com/docker/compose/issues/8891).

So:
* It is official: Docker Compose 2.1.0 breaks DDEV, please do not use it.
* However, one user has just reported 2.1.1 does work.
* @OCTOGONE-DEV and @arturu might have been affected by a different bug.

**Comment by arturu** [comment]
> ..., and 1.25.0 for @arturu (BTW is this still valid after you reinstalled the package?).

@felmab yes, after a clean install everything works with docker-compose 1.25, but I had to install docker-compose from the ubuntu repository (installing from homebrew didn't work). 

```
# apt info docker-compose
Package: docker-compose
Version: 1.25.0-1
...
Section: universe/admin
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Docker Compose Team <team+docker-compose@tracker.debian.org>
...
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu hirsute/universe amd64 Packages
```

> However, one user has just reported 2.1.1 does work.

Maybe, the upgrade doesn't work? From a clean installation, everything is fine.

**Comment by rfay** [comment]
docker-compose 2.1.1 seems to work OK from my testing.

**Comment by rfay** [comment]
Yes, just doing `ddev config` would recreate the needed files. I don't think it probably had anything to do with this issue, which was somehow related to btrfs.
