### ISSUE TITLE
Windows name lookup of *.ddev.site doesn't work (Windows hosts file)

### ISSUE THREAD

**Issue by therobyouknow** [drud/ddev#3318]
**Run a Diagnostic and Paste Link Here**

https://gist.github.com/therobyouknow/82fe9eddded5bb63b13eb89e396b006e

the test project created by the diagnostic script is not reachable:  https://tryddevproject-29004.ddev.site

**Describe the Problem**

Same problem as https://github.com/drud/ddev/issues/1566 but solution to remove /etc/hosts entries doesn't solve it.

Can access site via 127.0.0.1 address but not via ddev address.

Run ddev start

"Project can be reached at https://ligc-develop.ddev.site https://127.0.0.1:64649"

But on visiting  https://ligc-develop.ddev.site get:

![image](https://user-images.githubusercontent.com/1080646/137647750-058e45f5-e592-4625-b6c4-7a427ef70630.png)

"This site can’t be reached"

But  https://127.0.0.1:64649 is reachable.

**To Reproduce**

as above

**Screenshots**

as above

**Version and configuration information (please complete the following information):**

"ddev version v1.18.0"

Windows 10 Pro 64bit

see gist above

**Comment by rfay** [comment]
The title of your issue is "Windows name lookup of *.ddev.local doesn't work"

**Comment by rfay** [comment]
(The original title was "Earlier solution for this issue not working - http://projectname.ddev.local doesn't work on Windows"

Anyway, `ping somethingrandom.ddev.site` on the Windows side and see what happens.

**Comment by therobyouknow** [comment]
Revisiting this issue of "This site can’t be reached" again. 

Fortunately there are alternative solutions which I have found to work.

Option 1 - Run Chrome inside WSL2, which means that the networking with regard  Ubuntu in WSL is not required and so the associated issues (see below) are avoided. This is available on Windows 11 (https://scottspence.com/posts/use-chrome-in-ubuntu-wsl and https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps ) and I have found this to work there. I am also aware this should work on Windows 10, see here: https://pureinfotech.com/run-linux-gui-apps-wsl-windows-10/
Option 2 - Change the `/etc/hosts` file on the Windows side, as per previous comment https://github.com/drud/ddev/issues/3318#issuecomment-948965259 - this still holds and works on Windows 11 - I've just checked this today and it works.

There seem to be a number of issues with websites running inside WSL2 but are not visible outside - in a web browser running Windows - "This site can’t be reached".  

This issue doesn't appear to be a problem with ddev, but rather with Windows and WSL2, as these issues below suggest with other software stacks running in WSL2:
- https://github.com/microsoft/WSL/issues/5298#issuecomment-695181844
- https://github.com/microsoft/WSL/issues/5298#issuecomment-638223537



Here's how the original files look for me before editing:

`/etc/hosts on Ubuntu 20.04` in WSL2:

```
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateHosts = false
127.0.0.1 localhost scratchpads-dev.ddev.site
127.0.1.1       DELL7220.localdomain    DELL7220
<feff>
192.168.1.249   host.docker.internal
192.168.1.249   gateway.docker.internal
127.0.0.1       kubernetes.docker.internal

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```


`C:\Windows\System32\drivers\etc\hosts` on Windows 11 (original as is, before I would make any changes):

```
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost
# Added by Docker Desktop
192.168.1.249 host.docker.internal
192.168.1.249 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

Option 1 to run Chrome inside WSL2 seems to me it could be heavier on resources than other options. It involves running an additional windowing / GUI system. But it does work!

I tried Option 2 to update the `hosts` file on the Windows side as follows (see below) and that still works, so good to see that my previous noted comment still works https://github.com/drud/ddev/issues/3318#issuecomment-948965259  Note I kept the original line I edited as a comment, in case I need it again.

```
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost
# Added by Docker Desktop
192.168.1.249 host.docker.internal
192.168.1.249 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
#127.0.0.1 kubernetes.docker.internal
127.0.0.1 scratchpads-dev.ddev.site
# End of section

```

**Comment by rfay** [comment]
Thanks for the update. This is often a result of the few routers (mostly Fritzbox routers) that disallow "DNS Rebinding", so as long as people are using `*.ddev.site` solving that problem in one of the ways shown at https://ddev--4106.org.readthedocs.build/en/4106/users/basics/troubleshooting/#dns-rebinding-prohibited-cannot-resolve-or-unknown-host-or-no-address-associated-with-hostname is an option.

**Comment by therobyouknow** [comment]
> Thanks for the update. This is often a result of the few routers (mostly Fritzbox routers) that disallow "DNS Rebinding"

Understood, thank you. But it seems funny how a networking device external to my computer can interfere with accessing a site that exists on my computer.  On that basis of disallowing, seems like UK TalkTalk routers might be among those that disallow by default (where I saw the problem today), while UK Hyperoptic routers do allow (where I had ddev working earlier this week).

**Comment by rfay** [comment]
It's the domain name lookup. "DNS Rebinding" means allowing a name like `kdkdk.ddev.site` to be looked up as localhost, 127.0.0.1. It's considered an obscure security risk by some folks in corporate environments, so routers can prevent it. So if you can't look up `*.ddev.site` then ddev has to manipulate the /etc/hosts file. Again, you can see if this is your problem by using ping on the windows side and on the WSL2 side. And the docs page I linked to shows the many workarounds.
