### ISSUE TITLE
ddev Focus Group Questions

### ISSUE THREAD

**Issue by cyberswat** [drud/ddev#332]
## What happened (or feature request):
One of the ways we will be working to make ddev a top-notch product for users is focus groups.  We plan to engage groups of roughly 10 people at a time and would like to ask them a series of questions that are geared towards understanding how a tool like ddev can or can not help them.  The meta issue for this work is in https://github.com/drud/events/issues/2, but I'd like to turn the generation of the questions over to the ddev group.

The goal of this issue is to develop 8-12 questions that we feel can be used to help us create a great product.  I'm looking for active feedback from the team.

**Comment by rickmanelius** [comment]
I think the referenced issue is sufficient to track and we already have a robust set of questions there.
