### ISSUE TITLE
given a solr server successfully setup locally with ddev, what url for the solr server should i supply Drupal with in admin/config/search/apachesolr/settings/solr/edit

### ISSUE THREAD

**Issue by therobyouknow** [drud/ddev#3322]
**Run a Diagnostic and Paste Link Here**

https://gist.github.com/therobyouknow/c0ed0db36852aeed2d12d9ddc534ce53

**Describe the Problem**
What URL do I need to give Drupal solr settings, if my solr server address is: http://scratchpads-dev.ddev.site:8983/solr ?

as in: what do I put here for 'solr server url': admin/config/search/apachesolr/settings/solr/edit ?

I would have thought they could have just made life easy by allowing people to paste in the same URL as the one accessible in the browser, in my case: http://scratchpads-dev.ddev.site:8983/solr but not so.

I know this is slightly outside of ddev scope being about Drupal, but given ddev people and community overlap with Drupal I would think perhaps someone might know.

**To Reproduce**

go to:
`admin/config/search/apachesolr/settings/solr/edit`

enter server address: 
http://scratchpads-dev.ddev.site:8983/solr

Error message about server unreachable.

**Screenshots**
see https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6408#issuecomment-946681415

**Comment by rfay** [comment]
Please follow the step-by-step instructions in https://ddev.readthedocs.io/en/stable/users/extend/additional-services/#apache-solr

You also may want to use newer instructions that are in progress in ddev-contrib, with a newer approach. https://github.com/drud/ddev-contrib/pull/162

**Comment by rfay** [comment]
I hope you got this sorted out. If not, happy to help. Closing this for now.

**Comment by therobyouknow** [comment]
Thank you very much @rfay , yes we can close for now.  My colleague @benscott has provided code updates which I believe are working, here: https://github.com/NaturalHistoryMuseum/scratchpads2/tree/master/.ddev/solr
