### ISSUE TITLE
Feature Request: Download latest acquia backup instead of dumping it ourselves

### ISSUE THREAD

**Issue by siliconmeadow** [drud/ddev#3333]
**Provide ability to use existing Acquia backups**
When doing a `ddev pull acquia` an on-demand data dump is initiated, which can take a very long time. In most instances, using the backup databases that may have been created by Acquia would be sufficient. In my case, this saves an hour and a quarter.

**Existing backup downloaded by default with option for on-demand dump**
Here is the output from a Lando pull:

```
lando pull                                                                                                                                                                              ─╯
? Pull code from? none
? Pull database from? Stage, test (vcs: sprint4.18-certificate-functionality)
? Pull files from? none
--
Saved credentials to /var/www/.acquia/cloud_api.conf
    ✔ Destroying all current tables in local database if needed... 

 ! [NOTE] This is a multisite application. Drupal will load the default site unless you've configured sites.php for this
 !        environment: https://docs.acquia.com/cloud-platform/develop/drupal/multisite/                                 

                                                                                                                        
 [INFO] Using a database backup that is 11 hours old. Backup #189250915 was created at Sun Oct 24 6:48:35 UTC 2021.     
                                                                                                                        
        You can view your backups here:                                                                                 
        https://cloud.acquia.com/a/environments/12594-15786fc5-f286-4275-abf8-af232cce1823/databases                    
                                                                                                                        
        To generate a new backup, re-run this command with the --on-demand option.                                      
                                                                                                                        

    ✔ Importing Drupal database download
        }
    ✔ Checking db pull for expected tables...
    ✔ Pull completed successfully!
```

**Comment by rfay** [comment]
The acquia integration in soon-to-be-released release v1.18.1 downloads a gzipped database, which may fix the concerns you have, I'd appreciate it if you could try it out. It may solve the slowness issue. It still requires a dump on the server side, but the contents are brought down as a gzipped file.

**Comment by rfay** [comment]
@siliconmeadow could you please take a look at the acquia.yaml.example in ddev v1.18.1 and give it a try and see if it resolves your download issue?

**Comment by rfay** [comment]
Still hope you'll give that a try @siliconmeadow

**Comment by siliconmeadow** [comment]
Hi @rfay - am I right in thinking that the magic is:

```
drush @${project_id} sql-dump -n --alias-path=~/.drush --extra-dump=--no-tablespaces --gzip >db.sql.gz
```

If so, I've been successful with that in the past. I needed to change the `--extra-dump` to simply `--extra` when using Drush 8, but that's a different matter and I was considering how to handle different versions of Drush more gracefully.

Rather than doing this, what will perform better is if we download the latest db backup, as you'd saw was possible with `acli`, instead of creating an "on demand" one. I picked apart the [Lando Acquia plugin](https://github.com/lando/acquia/blob/main/scripts/acquia-pull.sh) to see what they were doing with their use of `acli`. Instead of the `drush sql-dump` command above, I've swapped it with:

```
acli -n pull:db @${project_id}
```
Which gets closer, but it seems like `acli` makes assumptions about the local environment and I can't see where to change that. In short, I don't see where they've specified `--host localhost --user drupal drupal`. Here is the verbose transcript when running `acli -n pull:db my_acquia_project.dev` directly in the web container:

```
ddev exec acli  -n -vvv pull:db rcnimain.dev                                                                                                                                                          ─╯

Box Requirements Checker
========================

> Using PHP 7.4.26
> PHP is using the following php.ini file:
  /etc/php/7.4/cli/php.ini

> Checking Box requirements:
  ✔ The application requires the version "^7.3 | ^8.0" or greater.
  ✔ The application requires the extension "json".
  ✔ The package "brick/math" requires the extension "json".
  ✔ The package "guzzlehttp/guzzle" requires the extension "json".
  ✔ The package "ramsey/uuid" requires the extension "json".
  ✔ The package "zumba/amplitude-php" requires the extension "curl".


 [OK] Your system is ready to run the application.


Acquia CLI version: 1.19.0
Connecting to database drupal
[notice] Command: 'which' 'mysql' [Exit: 0]
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)

[notice] Command: 'mysql' '--host' 'localhost' '--user' 'drupal' 'drupal' [Exit: 1]

In PullCommandBase.php line 371:

  [Acquia\Cli\Exception\AcquiaCliException]
  Unable to connect to local database using credentials mysql:://drupal:drupal@localhost/drupal. ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)


Exception trace:
  at phar:///usr/local/bin/acli/src/Command/Pull/PullCommandBase.php:371
 Acquia\Cli\Command\Pull\PullCommandBase->connectToLocalDatabase() at phar:///usr/local/bin/acli/src/Command/Pull/PullCommandBase.php:129
 Acquia\Cli\Command\Pull\PullCommandBase->pullDatabase() at phar:///usr/local/bin/acli/src/Command/Pull/PullDatabaseCommand.php:52
 Acquia\Cli\Command\Pull\PullDatabaseCommand->execute() at phar:///usr/local/bin/acli/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/acli/src/Command/CommandBase.php:428
 Acquia\Cli\Command\CommandBase->run() at phar:///usr/local/bin/acli/vendor/symfony/console/Application.php:1023
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/acli/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/acli/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/acli/bin/acli:69
 require() at /usr/local/bin/acli:14

pull:database [--no-scripts] [--on-demand] [--no-import] [--multiple-dbs] [--] [<environmentId> [<site>]]



 [help] You can find Acquia CLI documentation at https://docs.acquia.com/acquia-cli/

        You can submit a support ticket at https://insight.acquia.com/support/tickets/new?product=p:cli


Failed to execute command acli -n -vvv pull:db rcnimain.dev: exit status 1
```

On an aside, the web container has version 1.14.x of `acli`. I'll look at your image build scripts to see how to get a newer version can be installed.

**Comment by rfay** [comment]
I was asking you to take a look at the Acquia example as it is and try it out for speed. Could you give it a shot? https://github.com/drud/ddev/blob/master/pkg/ddevapp/dotddev_assets/providers/acquia.yaml.example

I see you tested with acli v1.19, which had major behavior change with aliases download, which is why it's pinned at v1.14.

But I'd love to have you test it as is and compare the speed to what you were after. It's currently set up to pull a gzipped dump. 

I'm wide open to improvements, and I saw that acli in a recent version had its own pull that might have some potential.

**Comment by siliconmeadow** [comment]
I tested exactly that feature for speed already.

**Comment by rfay** [comment]
Right, but I don't think you did since the recent revamp of the acquia.yaml.example, where it started to transfer gzipped versions of everything. Your feature request predated that change.

**Comment by siliconmeadow** [comment]
> Right, but I don't think you did since the recent revamp of the acquia.yaml.example, where it started to transfer gzipped versions of everything. Your feature request predated that change. The question is whether your feature request is still relevant given the changes.

I _did_ after the revamp of the file. Before 1.18.x was added. Within the same week of @greggmarshall's mod was added, I tried it out. I'm sorry I didn't mention it.

The way I see it is that the pull of the DB is actually not the most descriptive of names as it does pull the DB but also imports it.

The importing of the DB is fast. Doing a `drush sql-dump` is not near as fast as simply downloaded an already created gzipped file done from last night's backup. Which is what `exec acli  -n my_acquia_proj.dev` does. It's far more energy efficient.

**Comment by rfay** [comment]
Looking forward to an improvement. With ddev v1.18.2, it's no longer required to let ddev import the database, acli can do it or whatever. See https://ddev.readthedocs.io/en/latest/users/providers/provider-introduction/

**Comment by greggmarshall** [comment]
Another benefit of using the Acquia backups would be to reduce the load on the production server, assuming that's the DB being pulled.  If you have a half dozen developers, each doing the appropriate thing of starting each feature with a fresh copy of the DB, you could be doing a half dozen pulls a day.  My last project was concerned about it enough that we used a spare environment (they had a bunch) and had a weekly cron job update it from production then the developers pulled from there.

I'm not quite sure how to extract the name or id of the latest backup.  I saw the ACLI commands above but not sure how you go from the output of the first to the second in a script.

**Comment by siliconmeadow** [comment]
I'm checking to see how I can specify a different host, username, pw and database with `acli pull:db` as it's defaulting to 

```
[notice] Command: 'mysql' '--host' 'localhost' '--user' 'drupal' 'drupal' [Exit: 1]
```

**Comment by siliconmeadow** [comment]
I felt like I was making progress and thought my increased activity on this issue above was going in the right direction! Not so certain now.

**Comment by rfay** [comment]
acli doesn't seem to respect Drupal's settings.php for db connection? That would be weird. Definitely a bug report if it's happening. But as you know, every experiment you can try can be tried out first manually, line by line, inside the web container.

**Comment by siliconmeadow** [comment]
acli uses certain environmental variables for the db connection. [See the `setLocalDbHost` method](https://github.com/acquia/cli/blob/1.14.0/src/Command/CommandBase.php#L285), for example. I've set `ACLI_DB_USER`, `ACLI_DB_PASSWORD`,  `ACLI_DB_PASSWORD`, `ACLI_DB_NAME`, `ACLI_DB_HOST` to the values ddev expects (see full transcript below).

This moves things on considerably, as the file _does_get downloaded from Acquia.

After the file is downloaded, acli then drops the `db` database.

The next step, creating the `db` database fails, with an error which seems strange:

```
[notice] Command: 'mysql' '--host' 'db' '--user' 'db' '-e' 'DROP DATABASE IF EXISTS db' [Exit: 0]
Creating new empty database db
ERROR 1049 (42000): Unknown database 'db'

[notice] Command: 'mysql' '--host' 'db' '--user' 'db' '-e' 'create database db' [Exit: 1]
```

As I've typed this, I just remembered that when doing the Lando db pull the database is not dropped. Instead of dropping the db, each table is dropped. I'll have to investigate that next.


### Full transcript
```
ddev pull acquia --skip-files                                                                                                                                                                         ─╯
You're about to delete the current database and replace with the results of a fresh pull.
Would you like to continue? [Y/n] (yes):
Authenticating...
Saved credentials to /home/sheppardr/.acquia/cloud_api.conf
Obtaining database...

Box Requirements Checker
========================

> Using PHP 7.4.26
> PHP is using the following php.ini file:
  /etc/php/7.4/cli/php.ini

> Checking Box requirements:
  ✔ The application requires the version "^7.3 | ^8.0" or greater.
  ✔ The application requires the extension "json".
  ✔ The package "brick/math" requires the extension "json".
  ✔ The package "guzzlehttp/guzzle" requires the extension "json".
  ✔ The package "ramsey/uuid" requires the extension "json".
  ✔ The package "zumba/amplitude-php" requires the extension "curl".


 [OK] Your system is ready to run the application.


Acquia CLI version: 1.14.0
[debug] Searching for an environment matching alias redacted.
[debug] Found application redacted matching alias redacted.
[debug] Found environment redacted matching redacted.
Connecting to database db
[notice] Command: 'which' 'mysql' [Exit: 0]
[notice] Command: 'mysql' '--host' 'db' '--user' 'db' 'db' [Exit: 0]
[debug] Using environment Dev redacted
[debug] Using database backup (id #redacted) generated at 2021-12-14T08:42:34+00:00


 [INFO] Using a database backup that is 13 hours old. Backup #redacted was created at Tue Dec 14 8:42:34 UTC 2021.

        You can view your backups here:
        https://cloud.acquia.com/a/environments/redacted/databases

        To generate a new backup, re-run this command with the --on-demand option.


    ⌛ Downloading Drupal database copy from the Cloud Platform...
    ✔ Downloading Drupal database copy from the Cloud Platform
    ⌛ Importing Drupal database download...

Dropping database db
[notice] Command: 'mysql' '--host' 'db' '--user' 'db' '-e' 'DROP DATABASE IF EXISTS db' [Exit: 0]
Creating new empty database db
ERROR 1049 (42000): Unknown database 'db'

[notice] Command: 'mysql' '--host' 'db' '--user' 'db' '-e' 'create database db' [Exit: 1]

In PullCommandBase.php line 465:

  [Acquia\Cli\Exception\AcquiaCliException]
  Unable to create a local database. ERROR 1049 (42000): Unknown database 'db'


Exception trace:
  at phar:///usr/local/bin/acli/src/Command/Pull/PullCommandBase.php:465
 Acquia\Cli\Command\Pull\PullCommandBase->createLocalDatabase() at phar:///usr/local/bin/acli/src/Command/Pull/PullCommandBase.php:268
 Acquia\Cli\Command\Pull\PullCommandBase->importRemoteDatabase() at phar:///usr/local/bin/acli/src/Command/Pull/PullCommandBase.php:158
 Acquia\Cli\Command\Pull\PullCommandBase->pullDatabase() at phar:///usr/local/bin/acli/src/Command/Pull/PullDatabaseCommand.php:50
 Acquia\Cli\Command\Pull\PullDatabaseCommand->execute() at phar:///usr/local/bin/acli/vendor/symfony/console/Command/Command.php:299
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/acli/src/Command/CommandBase.php:414
 Acquia\Cli\Command\CommandBase->run() at phar:///usr/local/bin/acli/vendor/symfony/console/Application.php:996
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/acli/vendor/symfony/console/Application.php:295
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/acli/vendor/symfony/console/Application.php:167
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/acli/bin/acli:89
 require() at /usr/local/bin/acli:14

pull:database [--no-scripts] [--on-demand] [--no-import] [--] [<environmentId> [<site>]]



 [help] You can find Acquia CLI documentation at https://docs.acquia.com/acquia-cli/

        You can submit a support ticket at https://insight.acquia.com/support/tickets/new?product=p:cli


Pull failed: Failed to exec # set -x   # You can enable bash debugging output by uncommenting
set -eu -o pipefail
ls /var/www/html/.ddev >/dev/null # This just refreshes stale NFS if possible
pushd /var/www/html/.ddev/.downloads >/dev/null
acli pull:db -n -vvv @${project_id}
 on web: exit status 1
```

**Comment by rfay** [comment]
It's using "localhost" for the host, I assume. That's the standard problem.

**Comment by siliconmeadow** [comment]
> It's using "localhost" for the host, I assume. That's the standard problem.

I wish you'd have read my comment in more detail. I'd already established that and am on to the next thing to resolve. I despair.

**Comment by rfay** [comment]
I so appreciate all your work on this!

So the bottom line is... don't try to work inside the pull script until you can just do the things by hand, one by one.  Pioneer the acli command first.

But I see Access denied for user 'root'@'172.18.0.5' (using password: YES). Can you confirm that 172.28.0.5 is the right IP for the hostname `db` (`ping 172.28.0.5` and verify that it's `ddev-<project>-db`? Note that if you're using a ddev version before v1.18.2 you may have a docker-compose version that uses ambiguous hostnames, and 'db' may not land at the right place.

But try to get acli to work inside the web container and when it works there, then transplant the technique into the acquia.yaml. It's too hard to experiment with things using the acquia.yaml. 

It won't surprise me if you're up against an acli bug. But you should be able to demonstrate that pretty easily.

**Comment by rfay** [comment]
I'm also happy to do a zoom or whatever and work with you on this. We could have some fun.

**Comment by siliconmeadow** [comment]
Looking at this:

```
ERROR 1045 (28000): Access denied for user 'root'@'172.18.0.5' (using password: YES)

[notice] Command: 'mysql' '--host' 'db' '--user' 'root' 'db' [Exit: 1]
```

Lead me to log into the web container and using mysql directly.

```
ddev ssh                                                                                                                                                                                              ─╯
sheppardr@rcnimain-web:/var/www/html/docroot$ mysql --host db --user root db
ERROR 1045 (28000): Access denied for user 'root'@'172.18.0.5' (using password: YES)
```

If I add the `-p` so that I get prompted to enter the password (`root` as you say) it works:

```
sheppardr@rcnimain-web:/var/www/html/docroot$ mysql --host db --user root -p db
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 31
Server version: 10.3.32-MariaDB-1:10.3.32+maria~focal-log mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [db]>
```

Out of curiosity, when you simply type `mysql` it seems to be the equivalent of:

```
mysql --host db --user db db
```

__AND__ notice that password switch wasn't on that command. I'm wondering if there are further environmental variables for the mysql client command. Maybe there's a dot file for mysql or something?

**Comment by rfay** [comment]
Yes, and in latest ddev, the name of the host is `ddev-<project>-db`, so please use that.

**Comment by siliconmeadow** [comment]
I stepped sideways and renamed `.my.cnf` to `my.cnf.tmp` because I had a hunch that with acli, they hadn't made presumptions that whatever local environment you're working on would have a `.my.cnf` file. This moved further along:

```
ddev pull acquia --skip-files                                                                                                                                                                         ─╯
You're about to delete the current database and replace with the results of a fresh pull.
Would you like to continue? [Y/n] (yes):
Authenticating...
Saved credentials to /home/sheppardr/.acquia/cloud_api.conf
Obtaining database...

Box Requirements Checker
========================

> Using PHP 7.4.26
> PHP is using the following php.ini file:
  /etc/php/7.4/cli/php.ini

> Checking Box requirements:
  ✔ The application requires the version "^7.3 | ^8.0" or greater.
  ✔ The application requires the extension "json".
  ✔ The package "brick/math" requires the extension "json".
  ✔ The package "guzzlehttp/guzzle" requires the extension "json".
  ✔ The package "ramsey/uuid" requires the extension "json".
  ✔ The package "zumba/amplitude-php" requires the extension "curl".


 [OK] Your system is ready to run the application.


Acquia CLI version: 1.14.0
[debug] Searching for an environment matching alias rcnimain.dev.
[debug] Found application 15786fc5-f286-4275-abf8-af232cce1823 matching alias rcnimain.
[debug] Found environment 12595-15786fc5-f286-4275-abf8-af232cce1823 matching dev.
Connecting to database db
[notice] Command: 'which' 'mysql' [Exit: 0]
[notice] Command: 'mysql' '--host' 'db' '--user' 'db' 'db' [Exit: 0]
[debug] Using environment Dev 12595-15786fc5-f286-4275-abf8-af232cce1823
[debug] Using database backup (id #194708111) generated at 2021-12-15T08:42:29+00:00


 [INFO] Using a database backup that is 8 hours old. Backup #194708111 was created at Wed Dec 15 8:42:29 UTC 2021.

        You can view your backups here:
        https://cloud.acquia.com/a/environments/12595-15786fc5-f286-4275-abf8-af232cce1823/databases

        To generate a new backup, re-run this command with the --on-demand option.


    ⌛ Downloading Drupal database copy from the Cloud Platform...
    ✔ Downloading Drupal database copy from the Cloud Platform
    ⌛ Importing Drupal database download...

Dropping database db
[notice] Command: 'mysql' '--host' 'db' '--user' 'db' '-e' 'DROP DATABASE IF EXISTS db' [Exit: 0]
Creating new empty database db
[notice] Command: 'mysql' '--host' 'db' '--user' 'db' '-e' 'create database db' [Exit: 0]
Importing downloaded file to database db
[debug] Importing /tmp/dev-rcnimain-rcnimaindev-2021-12-15T08:42:29+00:00.sql.gz to MySQL on local machine
[notice] Command: 'which' 'gunzip' [Exit: 0]
[notice] Command: 'which' 'pv' [Exit: 1]

 [WARNING] Please install `pv` to see progress bar

    ✔ Importing Drupal database download
[notice] Command: 'which' 'drush' [Exit: 0]
{
    "php-os": "Linux",
    "php-conf": [
        "\/etc\/php\/7.4\/cli\/php.ini"
    ],
    "drush-script": "\/usr\/local\/bin\/drush8",
    "drush-version": "8.4.8",
    "drush-temp": "\/tmp",
    "drush-conf": [],
    "drush-alias-files": [],
    "%paths": []
}

[notice] Command: 'drush' 'status' '--fields=db-status,drush-version' '--format=json' '--no-interaction' [Exit: 0]
[notice] Drush does not have an active database connection. Skipping cache:rebuild
Importing database...
Pull failed: open : no such file or directory
```

I wonder which file it can't find.... I can see the file in `/tmp` on the web container.

**Comment by siliconmeadow** [comment]
@rfay - I might be at the end on this one, as I'm starting to wonder if the sole project I'm working on at the moment is too edge case.

1. It's D7 and using Drush 8. That in itself shouldn't really be a problem.
2. It was set up as a multi-site and the settings files are also set up in an unconventional way.

Here is the output from `ddev drush status`

```
ddev drush status                                                                                                                                                                                     ─╯
 Drupal version         :  7.82
 Site URI               :  local.rcni.com
 Database driver        :  mysql
 Database hostname      :  db
 Database port          :  3306
 Database username      :  db
 Database name          :  db
 PHP configuration      :  /etc/php/7.4/cli/php.ini
 PHP OS                 :  Linux
 Drush script           :  /usr/local/bin/drush8
 Drush version          :  8.4.8
 Drush temp directory   :  /tmp
 Drush configuration    :  /var/www/html/docroot/sites/default/drushrc.php /var/www/html/docroot/sites/all/drush/drushrc.php
 Drush alias files      :  /var/www/html/docroot/sites/rcn_nspace/drush/aliases.drushrc.php
 Drupal root            :  /var/www/html/docroot
 Drupal Settings File   :  sites/rcn_nspace/settings.php
 Site path              :  sites/rcn_nspace
```

**Comment by rfay** [comment]
Thanks so much for all the hard work on this. Multisite does in fact make it really hard to use the traditional technique, but now that the `pull` doesn't assume that ddev will do the import necessarily (acli can do it itself) that may work out. Anyway, thanks for all the hard work. If we can just figure out how acli is supposed to work we can make progress. There may be acli issues.

**Comment by begrafx** [comment]
I like the idea, but I am thinking, perhaps rather than add specific resources like Aquia, what if they were to add some way where tools/features that are routinely added in the install/setup process could be added to some file, which would check and add these items. I'm thinking, like a script/batch file, just have a file that had a list of commands like: 

`pull acquia
composer require drush/drush
composer require drupal/admin_toolbar`

Just my $.02

And another handy feature would be to add a command something like:

`ddev self-update`

**Comment by rfay** [comment]
We don't have access to Acquia any more; they promise to get it for us someday. But this will have to be postponed.

**Comment by rfay** [comment]
@siliconmeadow this is currently in head, `brew install --HEAD drud/ddev/ddev` and will be in v1.19.4 shortly, I hope it works for you. Of course you can try it without changing ddev at all, it's just a change to the acquia.example, https://github.com/drud/ddev/blob/6494172eb0f59ee3f39059e46667418939a557c8/pkg/ddevapp/dotddev_assets/providers/acquia.yaml.example#L41-L52
