### ISSUE TITLE
Amazon CA root certificate does not appear to be installed

### ISSUE THREAD

**Issue by jake-brandt** [drud/ddev#3344]
**Describe the bug**
Nginx' `proxy_pass` functionality will fail upon any requests out, via HTTPS, to any resources backed by an Amazon-issued certificate.

**To Reproduce**
Ensure your DDEV environment is configured to use Nginx (not Apache).

Add `proxy_pass` rules along the lines of the following:
```
    location ~ /test-ssl-fail/(.*) {
        proxy_pass https://<some-aws-signed-ssl-site>;
    }

    # NOTE this next rewrite is NOT SSL
    location ~ /test-non-ssl-pass/(.*) {
        proxy_pass http://<some-aws-signed-ssl-site>;
    }

    location ~ /test-ssl-pass/(.*) {
        proxy_pass https://www.google.com;
    }
```

After starting your DDEV container, observe that:
1) Going to any route under `/test-ssl-fail` will return an Nginx 502.
2) Going to any route under `/test-non-ssl-pass` will, if the site serves HTTP still, return at the very least a 404 or whatever response comes from the host.
3) Going to any route under `/test-ssl-pass` will result in a Google-branded 404 (meaning the SSL cert was accepted).

**Expected behavior**
All above tests should actually return the host's response instead of an Nginx 502.

**Version and configuration information (please complete the following information):**

- macOS Monterey
- Docker Desktop version 3.6.0
- ddev version 1.17.7

config.yaml contents:
```
name: mysite.com
type: wordpress
docroot: ""
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: [
  "my.site.com"
]
mariadb_version: "10.3"
mysql_version: ""
use_dns_when_possible: false
composer_version: ""
web_environment: []
```

**Comment by rfay** [comment]
No response from OP, so I'll close this, but happy to continue the conversation here or elsewhere.

**Comment by rfay** [comment]
I think you'll find it's completely documented now in https://ddev.readthedocs.io/en/latest/users/usage/networking/ (it will be in the "stable" version of the docs on next release in a couple of weeks.)
