### ISSUE TITLE
Failed to create mutagen sync session (unable to connect to daemon: client/daemon version mismatch) (Don't install mutagen separately)

### ISSUE THREAD

**Issue by marcvangend** [drud/ddev#3353]
**Run a Diagnostic and Paste Link Here**
https://gist.github.com/marcvangend/1d307a38d425e16797d9e788bbb9e785
(I hope you don't mind I anonymized some project/client names.)

**Describe the bug**
I wanted to give ddev 1.18.0 with Mutagen a try. After stopping+upgrading ddev, installing+starting mutagen and adding .ddev/config.mutagen.yaml, I started ddev, which failed with the following error:
```
Failed to start tni9: Failed to create mutagen sync session tni9. You may be able to resolve this problem with 'ddev stop tni9 && docker volume rm tni9_project_mutagen' (err=Failed to mutagen [sync create /Users/user/ddev/project docker://eebe95d1cbae7c6d31c956a7a4a9ef9d109bbfd9bca80d270f4c4fe8faa6e3e0/var/www/html --no-global-configuration --name project --configuration-file=/Users/user/ddev/project/.ddev/mutagen/mutagen.yml] (exit status 1), output=Error: unable to connect to daemon: client/daemon version mismatch (daemon restart recommended)
```

The words "client/daemon version mismatch" suggest to me that this may have to do with the fact that Mutagen 0.12.0 was only released 7 days ago. But if it is that simple to break the Mutagen integration, isn't this all a bit fragile? And wouldn't it be nice to do a version check and provide a helpful and friendly error message?

**To Reproduce**
See above.

**Expected behavior**
Ddev starts.

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: macOS Big Sur
- Docker Desktop version: 4.1.1
- ddev version information: 1.18.0
- config.yaml contents for the misbehaving project:
    ```
    name: project
    type: drupal9
    docroot: htdocs
    php_version: "7.4"
    webserver_type: nginx-fpm
    router_http_port: "80"
    router_https_port: "443"
    xdebug_enabled: false
    additional_hostnames: []
    additional_fqdns: []
    mariadb_version: ""
    mysql_version: "8.0"
    nfs_mount_enabled: false
    mutagen_enabled: false
    project_tld: lmn.gr
    use_dns_when_possible: true
    timezone: Europe/Amsterdam
    composer_version: "1"
    disable_settings_management: true
    web_environment: []
    ```
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? No

**Comment by rfay** [comment]
Hi @marcvangend - 

You are running a mutagen daemon of a different version on your computer. That's why it says "client/daemon version mismatch".  Only one version of mutagen daemon can run at a time.

Please stop the one you're running. `killall mutagen`. If you don't need mutagen for some other application, please uninstall it.

For v1.18.0, ddev installs mutagen 0.12.0-beta7 in ~/.ddev/bin. You don't have to do any installation.

DDEV mutagen docs are at https://ddev.readthedocs.io/en/latest/users/performance/#using-mutagen - In [caveats](https://ddev.readthedocs.io/en/latest/users/performance/#caveats-about-mutagen-integration) you see

> Only one mutagen version on machine please: Multiple mutagen versions can't coexist on one machine, so please stop any running mutagen. On macOS, killall mutagen. If you absolutely have to have mutagen installed via homebrew or another technique (for another project) make sure it's the same version as you get with `ddev debug mutagen version`.

**Comment by rfay** [comment]
`brew uninstall mutagen` would normally do the job to uninstall. But it sounds like the doc needs to say louder "YOU DON'T HAVE TO INSTALL MUTAGEN" because one other person tried that as well.

**Comment by rfay** [comment]
I added this commit to try to say it louder. Think this will help people that follow after you?

https://github.com/drud/ddev/commit/582fc110dba4f0432e8b1f46c071d67ed912e029

**Comment by marcvangend** [comment]
> I added this commit to try to say it louder. Think this will help people that follow after you?

Yes, I think that should help. Thank you.
