### ISSUE TITLE
Cannot have dollar sign ($) in environment variable value

### ISSUE THREAD

**Issue by paul-mckibben** [drud/ddev#3355]
**Run a Diagnostic and Paste Link Here**

https://gist.github.com/paul-mckibben/44d45179b6a1c84a30b6600e01e9dba3

**Describe the bug**
I'm using an environment variable to store an encryption key for the "key" module.
It looks like the $ character cannot be used within a string value of an environment variable.
Example: in my config.yaml file I had the following:
```
web_environment:
- '2FAKEY=p3s6v9y$B?E(H+MbQeThWmZq4t7w!z%C'
```

The getenv call from the key module returned this value:
`p3s6v9y?E(H+MbQeThWmZq4t7w!z%C`

You'll notice that two characters are missing: `$B`
Perhaps something is treating that as a variable?

Additionally, when I invoke `ddev xdebug on` I see the following warning:
```
WARN[0000] The "B" variable is not set. Defaulting to a blank string. 
```

**To Reproduce**
- Create a web_environment variable in config.yaml that has a $ in its string value.
- From within a PHP web application, invoke "getenv()" on the environment variable. See that the $ and one or more following characters is missing from the value.
- Invoke `ddev xdebug on` and notice a warning about a variable not set.

**Expected behavior**
"getenv()" should return the correct environment variable value specified in config.yaml even if the value includes the $ character.

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: Mac OS Catalina 10.15.7
- Docker Desktop version: 4.1.1 (69879)
- ddev version information: 
```
DDEV-Local version	v1.17.1                                
architecture      	amd64                                  
db                	drud/ddev-dbserver-mariadb-10.3:v1.17.0
dba               	phpmyadmin:5                           
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.17.0            
docker            	20.10.8                                
docker-compose    	v2.0.0                                 
os                	darwin                                 
router            	drud/ddev-router:v1.17.0               
web               	drud/ddev-webserver:v1.17.1 
```

- config.yaml contents for the misbehaving project
```
name: stellar
type: drupal9
docroot: web
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.3"
mysql_version: ""
use_dns_when_possible: true
composer_version: ""
web_environment:
- '2FAKEY=p3s6v9y$B?E(H+MbQeThWmZq4t7w!z%C'
```

- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them? - No.

**Additional context**
n/a

**Comment by rfay** [comment]
Thanks for this. I'm surprised we haven't seen it before. Maybe other key generators avoid the `$` because of problems like this. 

In slack you said this was generated with https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx and that you could get one without `$` by cycling through a few more times.

But we definitely would like this to work right.

**Comment by rfay** [comment]
Also, just for future reference, the variable name you used, `2FAKEY` is not a valid variable name, need to start with an alpha character I think.

**Comment by rfay** [comment]
This is a result of https://github.com/docker/compose/issues/8891 - I don't think there's a workaround unless the upstream fix can happen.

**Comment by ndeloof** [comment]
compose extends variables on the yaml file for any `$XXX` string. It's pretty uncommon to hard-code such keys/secrets in the compose file, most user have those stored in dot env file or passed by environment. If required, you can escape this dollar sign using double `$$`.

```yaml
web_environment:
- '2FAKEY=p3s6v9y$$B?E(H+MbQeThWmZq4t7w!z%C'
```

**Comment by rfay** [comment]
@ndeloof these find their way from the .ddev/config.yaml or global config into the temporary interpolated docker-compose file that ddev generates using `docker-compose config`. They're not "hard-coded into compose file". A new `.ddev/.ddev-docker-compose-full.yaml` is generated using `docker-compose config` during every start based on various inputs.

**Comment by rfay** [comment]
It looks to me like this can only be resolved by https://github.com/docker/compose/issues/8891 so I'm going to close this here. Will continue to think about it.

**Comment by gilbertsoft** [comment]
For these cases I'm using a .env file instead. It's not only DDEV who has problems with, I also have issues here with plain Debian systems. It's probably possible to escape it but I've stopped investigating here and used the .env approach.
