### ISSUE TITLE
unable to change exposed port number for domain name

### ISSUE THREAD

**Issue by bradbulger** [drud/ddev#3379]
My setup uses the name "easy" so the domain name is easy.ddev.site. I want the port numbers inside the container to be standard, 80 and 443, but the outside ports to be non-standard, 81 and 444. I tried adding a docker-compose.ports.yaml file to do the "ports" configuration, 

version: '3.6'
services:
  web:
    ports:
      - "81:80"
      - "444:443"

but that ends up only affecting the IP address, not the domain name. 

URLs
----
https://easy.ddev.site
https://127.0.0.1:444
http://easy.ddev.site
http://127.0.0.1:81

I'm not sure why the domain name is ending up configured differently. Any pointers about configuration or modifications that could fix this would be helpful.

**Comment by rfay** [comment]
* The ports inside the container are already 80 and 443, and you can't change them.
* If you want to expose an explicit port on localhost/127.0.0.1, you'll use `host_webserver_port` for http and `host_https_port` for https. You won't use any docker-compose file.
* `ddev-router` already puts your project on 80/443 by default, so you have to choose port other than 80/443 unless you use `router_http_port` and `router_https_port` to move it somewhere else. 

If you want to have http://easy.ddev.site:81 and http://easy.ddev.site:444, you would just put `router_http_port: 81` and `router_https_port: 444` in your .ddev/config.yaml.

**Comment by bradbulger** [comment]
That did make it somewhat clearer, thanks. Using router_http_port and router_https_port worked, once I got rid of that docker-compose.ports.yml file.

What I'm trying to do, for future searches on similar issues, is use chromedriver with Drupal 9 to do the Drupal FunctionalJavascripit tests with phpunit. I may have just not been specifying things correctly, but I could only get it working if I could avoid needing to use non-default port numbers in the container. Meanwhile I have something else using the standard ports on my machine, so from outside the container I needed the ddev site to use the non-standard ports. 

This set that up nicely. In "host_webserver_port", is "host" understood as the machine outside the container? As in docker compose 'ports' short syntax, HOST:CONTAINER.

Thanks for your help.

**Comment by rfay** [comment]
I recommend that you use one of the chromedriver recipes in https://github.com/drud/ddev-contrib

**Comment by rfay** [comment]
(Happy to continue the conversation here or elsewhere)
