### ISSUE TITLE
DDEV escapes specific characters per default

### ISSUE THREAD

**Issue by joshsedl** [drud/ddev#3395]
I ran into an issue, where I couldn't run a composer command in ddev and I don't know exactly why, it seems that ddev escapes specific characters by default.

Command I would like to run:
`ddev composer config --json extra.patches.package-mantainer/package '{"INSERT WHAT IT DOES": "PATH TO PATCH"}'`
This will create a placeholder patch in my composer.json file.

If I run the command in ddev, I get the following error:

![Error](https://user-images.githubusercontent.com/37101709/143209391-ed860246-15e6-4bce-8a1f-ef373a51868b.PNG)

But if I run the command via `ddev ssh` it works just fine and creates the composer config I expect:

![patch](https://user-images.githubusercontent.com/37101709/143209886-cbbe757f-3756-4ef2-a72b-428cc7b9121d.PNG)

This is a problem since I would like to run a custom startup-command in "host" where I run this snippet. Unfortunately if I only run
`composer config --json extra.patches.package-mantainer/package '{"INSERT WHAT IT DOES": "PATH TO PATCH"}'`, I'll get the error: `composer: command not found`

Appreciate any suggestions or changes! :)

**Comment by gilbertsoft** [comment]
Try this:
```
ddev composer config --json extra.patches.package-mantainer/package "'{\"INSERT WHAT IT DOES\": \"PATH TO PATCH\"}'"
```

**Comment by joshsedl** [comment]
Thank you! Working perfectly fine!

**Comment by rfay** [comment]
This is a duplicate of https://github.com/drud/ddev/issues/2547 - there's lots of explanation there why it happens.
