### ISSUE TITLE
Wrong database connected to projects when running multiple projects at the same time

### ISSUE THREAD

**Issue by koehnlein** [drud/ddev#3396]
**Run a Diagnostic and Paste Link Here**

<https://gist.github.com/koehnlein/08170fb158d8865abb317e9bf1c35642>

**Describe the bug**

Since a few days, my database containers are mixed up randomly, when more than one projects are running at the same time. When I am in project 1, I see project 2's database connected. This happens, when I create a connection from the web container to `db` and also when I use the projects phpMyAdmin container.

There are some things, I did **before** this problem occured. Unfortunately, I don't know, if one of these steps causes this problem:

* Renamed, deleted and (re)started one of my ddev projects
* Updated docker on my mac
* Updated ddev from 1.18.0 to 1.18.1

I already did a factory reset of my local docker installation to try to solve the problem. But it did not help. Is there a possibility to reset all ddev settings?

**To Reproduce**

Well, **I** can reproduce this by starting multiple ddevs at the same time. But I am afraid, you cannot reproduce this. :-/

**Expected behavior**

Each project should have the correct database connected when using host name `db`

**Screenshots**

-

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: macOS Monterey, 12.0.1
- Docker Desktop version if on macOS or Windows: 4.2.0 (70708)
- ddev version information: v1.18.1
- config.yaml contents for the misbehaving project: none, all projects affected
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? no

**Additional context**

**Comment by rfay** [comment]
This is a duplicate of https://github.com/drud/ddev/issues/3369 - please see details there. ;tldr: Use docker-compose v1 for now or make sure you use `ddev-<project>-db` for database name.

**Comment by koehnlein** [comment]
Wow, thank you for that fast response!

Sorry, I did not see the other ticket. 🤦‍♂️ I will close this ticket.

**Comment by rfay** [comment]
It's an odd problem, and a bit hard to describe. Thanks for taking the time to file a really good issue. Your title was excellent.
