### ISSUE TITLE
Mutagen configurations should bind-mount project .git directory

### ISSUE THREAD

**Issue by rfay** [drud/ddev#3400]
Currently, when you enable mutagen, it does not sync the project .git directory. This is mostly fine, but it leads to trouble with some composer configurations, see 

* https://github.com/drud/ddev/issues/3384
* https://github.com/drud/ddev/pull/3398

So an easy answer would be to have the generated docker-compose bind-mount .git as in https://ddev.readthedocs.io/en/latest/users/performance/#advanced-mutagen-configuration-options

Related:
* https://github.com/drud/ddev/issues/3357

**Comment by rfay** [comment]
See #3357 for the same thing with upload_dir - I'm sure both should be done together.

**Comment by deviantintegral** [comment]
Just a 👍 on doing this. I tried to poke holes in where it would fail, and the worst I could see would be if somehow composer needs a _lot_ of IO on the `.git` directory, leading to performance issues. That's easy enough to test when this work is done.
