### ISSUE TITLE
export-db sometimes writes files with trailing garbage

### ISSUE THREAD

**Issue by longwave** [drud/ddev#3402]
**Describe the bug**

Sometimes, `ddev export-db` appears to write trailing garbage to gzipped files.

**To Reproduce**

This is very inconsistent, I can't reproduce on demand and when it does happen then immediately rewriting the file succeeds:

```
$ ddev export-db -f db.sql.gz
Wrote database dump from site database 'db' to file db.sql.gz in gzip format.
$ gunzip db.sql.gz

gzip: db.sql.gz: decompression OK, trailing garbage ignored

$ rm db.sql 
$ ddev export-db -f db.sql.gz
Wrote database dump from site database 'db' to file db.sql.gz in gzip format.
$ gunzip db.sql.gz
$
```

**Expected behavior**

The file should always gunzip cleanly with no warnings.

**Version and configuration information (please complete the following information):**

Ubuntu 20.04
```
DDEV-Local version	v1.17.7                                
architecture      	amd64                                  
db                	drud/ddev-dbserver-mariadb-10.3:v1.17.7
dba               	phpmyadmin:5                           
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.17.0            
docker            	20.10.10                               
docker-compose    	1.23.2                                 
os                	linux                                  
router            	drud/ddev-router:v1.17.6               
web               	drud/ddev-webserver:v1.17.7         
```

**Comment by rfay** [comment]
Please use `zless` on your db dump to see what's in there. I think you'll find that it's something understandable. If you can share the dumpfile with me via PM I'll also take a look.
