### ISSUE TITLE
https://ddev.com/ site: images appear distorted (aspect ratio incorrect)

### ISSUE THREAD

**Issue by tyler36** [drud/ddev#3410]
**Describe the bug**
Appologies, but I'm not sure if this is in the scope of this repo. 

I stumbled across [DDEV ❤️ WSL2: getting started](https://ddev.com/ddev-local/ddev-wsl2-getting-started/) and noticed all the images appear "squished".

The first image appears fine, but all the others are off. It makes it difficult to read. The VScode screen is impossible to comprehend.

**To Reproduce**
- Visit https://ddev.com/ddev-local/ddev-wsl2-getting-started/
- Check images

**Version and configuration information (please complete the following information):**

Tested on Win10 with the following browsers
- Chrome 96.0.4664.45 (Official Build) (64-bit)
- Firefox 94.0.2 (64-bit)

**Comment by rfay** [comment]
I think everything there should now be in https://ddev.readthedocs.io/en/latest/#installation-or-upgrade-windows-wsl2 - let me know.

I do see the squished images, but don't really have any intention of maintaining that article. I'm quite intent on getting key information into the docs and not have them in other websites.

**Comment by tyler36** [comment]
Perfectly reasonable response. The other site was pretty high in the Google search results which is how I found it.

https://ddev.readthedocs.io/en/latest/#installation-or-upgrade-windows-wsl2 instructions are fine and working. 

I'll close the issue since there's nothing to do based on your comment.

**Comment by rfay** [comment]
I am able to edit that page, so should probably point to the docs. 

What there is to do is improve the docs here, always appreciate your input!
