### ISSUE TITLE
If using Drupal 7 and below, if using $base_url, you probably need to edit it when changing project name

### ISSUE THREAD

**Issue by hcksharp** [drud/ddev#3416]
For Drupal If you are renaming a project, also update your $base_url = in settings file to reflect the new domain.

**Comment by rfay** [comment]
This isn't related to ddev, and $base_url hasn't been a thing since Drupal 7. Also, it's pretty much always been a mistake to set it in any version of Drupal.

**Comment by rfay** [comment]
Change the title to "If using Drupal 7 and below, if using $base_url, you probably need to edit it when changing project name", but I think that's enough. Closing, happy to continue the discussion here or elsewhere.

**Comment by hcksharp** [comment]
Thanks Randy, didn't know. Maintaining a couple D7 sites and this one stumped me and thought I share just in case someone else runs across it. Is there a better place to share?
Fairly new ddev user and using it for a couple of Drupal 9 sites and migrated some older Drupal 7 sites to it. ddev just rocks, can have a project up in minutes. Cheers.

**Comment by rfay** [comment]
Yay! Yeah, it's just old drupaler knowledge, something to help in [Drupal Answers](https://drupal.stackexchange.com/) answering people's questions I guesss. Glad things are working for you!
