### ISSUE TITLE
Provide instructions for installing docker inside WSL2

### ISSUE THREAD

**Issue by rfay** [drud/ddev#3419]
People are starting to install docker inside WSL2 instead of using Docker Desktop, so it will be a good time to offer that alternative in the docs. 

I note that on Ubuntu 20.04 you can just `sudo apt-get install docker.io` and `sudo dockerd` but WSL2 doesn't have good service startup techniques.

@dennisameling are you still using this technique? Can you speak to how you do it (or a PR is welcome of course, but just some guidance would be great)

* https://blog.nillsf.com/index.php/2020/06/29/how-to-automatically-start-the-docker-daemon-on-wsl2/ provides a simple login script and very simple instructions. 
* https://medium.com/@XanderGrzy/docker-in-windows-wsl-2-bc62b5236d1c says just use `sudo service docker start`

* https://dev.to/bowmanjd/install-docker-on-windows-wsl-without-docker-desktop-34m9 provides detailed instructions to do this, but they're far more complicated than actually needed. He provides a couple of scripts though, including [docker-service.sh](https://github.com/bowmanjd/docker-wsl/blob/main/docker-service.sh) that can be quite appropriate.

**Comment by rfay** [comment]
Thanks! The one thing that seems to be missing is how to start docker on login or startup. Are you just doing `sudo service docker start` or do you have it in your .profile or whatever?

**Comment by mbomb007** [comment]
> Thanks! The one thing that seems to be missing is how to start docker on login or startup. Are you just doing `sudo service docker start` or do you have it in your .profile or whatever?

It's at the end:

```bash
echo "wsl.exe -u root service docker status > /dev/null || wsl.exe -u root service docker start > /dev/null" > ~/.bashrc
```

**Comment by mbomb007** [comment]
So while this guide is specific to WSL2 with Ubuntu, it could be developed into a more robust installation script that checks version and whether it's WSL or not.

**Comment by rfay** [comment]
Thanks - good idea

But you're using a manual command on the Windows side to start docker, right? It's not automated at all...

I think using sudoers in WSL2 would also be fine.

**Comment by mbomb007** [comment]
I would have to click to start WSL, I think...? I haven't restarted since I set it up.

Here's an option I remember seeing: https://www.how2shout.com/linux/how-to-start-wsl-services-automatically-on-ubuntu-with-windows-10-startup/

**Comment by tyler36** [comment]
> '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'

The [homebrew installation site](https://docs.brew.sh/Installation) uses '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"' (`master`, not `HEAD`). Is there a reason to differ from "official" installation?

**Comment by tyler36** [comment]
```shell
$ sudo apt update && sudo apt install -y docker-ce docker-ce-cli containerd.io
Get:1 https://download.docker.com/linux/ubuntu focal InRelease [57.7 kB]
Err:1 https://download.docker.com/linux/ubuntu focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
Hit:2 http://ppa.launchpad.net/ondrej/php/ubuntu focal InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease
Get:4 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Hit:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists... Done
W: GPG error: https://download.docker.com/linux/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
E: The repository 'https://download.docker.com/linux/ubuntu focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Scary warning.

**Comment by rfay** [comment]
* The recipe for homebrew should be the one on their site. `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
* If you're getting a problem with the docker packages, it means you didn't install their key per their instructions or something is wrong with their repo. Probably you forgot the key.

**Comment by tyler36** [comment]
> The recipe for homebrew should be the one on their site. /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

OK ... I had the [Homebrew documentation](https://docs.brew.sh/Installation) page bookmarked and was looking under the "Git Remote Mirroring". You are correct, the homepage has it as "HEAD".

> Probably you forgot the key
Right again, my bad. Strange thing is I remember running it  because it looked pretty with the syntax highlighing. It's even in the history.

**Comment by rfay** [comment]
I think we'll have a section in the docs in "topics" that explains this approach step-by-step, along with some other unusual setups. But docker inside WSL2 may very well become the preferred approach.

**Comment by rfay** [comment]
Thanks for all your help on this. I hope you'll review https://github.com/drud/ddev/pull/3477 either now or after it goes in. I'm sure it can be improved.
