### ISSUE TITLE
ddev start fails with "ddev-global-cache already exists but was not created by Docker Compose"

### ISSUE THREAD

**Issue by ohader** [drud/ddev#3422]
**Run a Diagnostic and Paste Link Here**

please see https://gist.github.com/ohader/bfeb7eb1379a8450bee5e0b6f30fc8cd

**Describe the Problem**

Starting a fresh new project with `ddev start` fails on macOS (Big Sur)

```ddev start
Starting in-die-2021...
Pushed mkcert rootca certs to ddev-global-cache/mkcert
volume "ddev-global-cache" already exists but was not created by Docker Compose. Use `external: true` to use an existing volume
Failed to start in-die-2021: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-in-die-2021 docker-compose -f /Users/olly/Development/ddev/in-die-2021/.ddev/.ddev-docker-compose-full.yaml up --build -d', action='[up --build -d]', err='exit status 1', stdout='#2 [drud/ddev-dbserver-mariadb-10.3:20211017_mysql_arm64-in-die-2021-built internal] load build definition from Dockerfile

...

#11 [drud/ddev-dbserver-mariadb-10.3:20211017_mysql_arm64-in-die-2021-built 2/2] RUN (groupadd --gid 20 "olly" || groupadd "olly" || true) && (useradd  -l -m -s "/bin/bash" --gid "olly" --comment '' --uid 501 "olly" || useradd  -l -m -s "/bin/bash" --gid "olly" --comment '' "olly" || useradd  -l -m -s "/bin/bash" --gid "20" --comment '' "olly")
#11 sha256:b4e029f395333987b2d8d0520070fe7964051269b7b79d985406eaf15138955a
#11 CACHED

#9 [drud/ddev-dbserver-mariadb-10.3:20211017_mysql_arm64-in-die-2021-built] exporting to image
#9 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#9 exporting layers done
#9 writing image sha256:1299c0d2e85717a5903e5199d44e5d9db00c040858bf38267aaf0542a884d2b9 done
#9 naming to docker.io/drud/ddev-dbserver-mariadb-10.3:20211017_mysql_arm64-in-die-2021-built done
#9 DONE 0.0s
', stderr='volume "ddev-global-cache" already exists but was not created by Docker Compose. Use `external: true` to use an existing volume'
```

List line in trace:
> `volume "ddev-global-cache" already exists but was not created by Docker Compose. Use `external: true` to use an existing volume`

**To Reproduce**

* created new project `in-die-2021`, `public` as web-root, `typo3` as project type
* tried to start DDEV using `ddev start`

**Additional context**

In order to track down the behavior I've removed existing projects using `ddev delete -aO`, there there's basically just one project configured in `~/.ddev/global_config.yaml`.

**Comment by ohader** [comment]
Seems to be a duplicate of #3404

**Comment by rfay** [comment]
Yes, it is, and is fixed in docker-compose 2.2.2. ddev will work around this in next release. 

Unfortunately the prerelease 2.2.1 was added to Docker Desktop 3.4.0, breaking everybody who upgraded.

Ways to fix:
* `docker-compose disable-v2`
* Downgrade to Docker Desktop 4.2.0 ([macOS](https://docs.docker.com/desktop/mac/release-notes/#docker-desktop-420) or [windows](https://docs.docker.com/desktop/windows/release-notes/#docker-desktop-420))
* Download the new [working release 2.2.2](https://github.com/docker/compose/releases/tag/v2.2.2) of docker-compose and put it in your $PATH

**Comment by ohader** [comment]
Upgrading to `v2.2.2` of `docker-compose` fixed the issue on my side.

On macOS x64 Intel
```bash
wget https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-darwin-x86_64 -O /usr/local/bin/docker-compose
```

**Comment by rfay** [comment]
Be careful as this may cause funky behavior on next docker desktop upgrade, you may need to remove it before upgrade.
