### ISSUE TITLE
Detection of typo3 project type does not work with installers v4

### ISSUE THREAD

**Issue by gilbertsoft** [drud/ddev#3429]
**Describe the bug**

Detection of typo3 project type no longer works with `typo3/cms-composer-installers` v4 see https://github.com/TYPO3/CmsComposerInstallers/pull/127.

I will come up with a solution soon, because we are about to release a first alpha version the next days propably...

**Comment by rfay** [comment]
Excellent, should be pretty easy. Are we going to need a new project type? Or can it live on as `typo3` ? Because of special requirements, drupal9 had to be split off, and drupal10 will also have to be split off.

**Comment by rfay** [comment]
Related: If we need to bump db or php version requirements, can we do that for all of typo3 type or not.

**Comment by gilbertsoft** [comment]
No new type needed, but the folder structure changes a little bit and that's the reason it's not longer detected. But so far I didn't look into the code. But will do in short, currently fixing and testing other stuff for this release but wana make sure it's mentioned here :)

**Comment by gilbertsoft** [comment]
No changes needed at all. The folder `typo3` which is used for the detection still exists. It was just a mistake within my tests.
