### ISSUE TITLE
ngrok and `ddev share` no longer work without a free account

### ISSUE THREAD

**Issue by rfay** [drud/ddev#3430]
TestShareCmd started failing today with text like this:

"Before you can serve HTML content, you must sign up for an ngrok account and install your authtoken."

<img width="784" alt="Welcome_to_ngrok_" src="https://user-images.githubusercontent.com/112444/145117538-1d017961-f7f7-440e-a399-118a7bae6a9d.png">

ngrok always used to work with limitations with no account or token. Now users will have to create a (free for now) account and will have to get the token installed. For ddev tests, it means we have another secret to carry around.

- [x] Provide ngrok token on test runners
- [x] Update docs so that people know about this. It's in more than one place, especially the "sharing" topic

Also, I note that Chrome is posting a big warning on ngrok.io sites, "Deceptive site ahead: Attackers on 8c11-72-174-68-105.ngrok.io may trick you into doing something dangerous like installing software or revealing your personal information (for example, passwords, phone numbers, or credit cards). " that you have to click around.

<img width="683" alt="Security_error" src="https://user-images.githubusercontent.com/112444/145118153-83ff48bb-47fd-407c-a851-81e628b895c6.png">

**Comment by Loque18** [comment]
did you solve it ?

**Comment by Jassy87** [comment]
My python application on google colab was up and running and today I got this message. I made an account and installed the Authtoken but the app is no longer running. Any help is appreciated :(

**Comment by rfay** [comment]
I assume this has nothing to do with ddev right? I didn't have any trouble even with a free ngrok account, but you should just test with ngrok directly, not with your python app, just use ngrok itself when debugging. Then if you can't sort it out maybe ngrok has some type of support?  But my bet is you'll get it sorted out if you start from scratch and just do one thing at a time.

**Comment by Jassy87** [comment]
Yes rfay, I was so nervous as my app wasn't running in front of my manager so I didn't notice 'ddev'. My issue is related to using ngrok with python & colab. I tried everything I could find on the web but still can't get it running. I emailed the support and hopefully they'll reply before my next demo!

**Comment by mrlasdt** [comment]
Fixed by installing ngrok authtoken in Colab. 
In my case, I used flask_ngrok and it init ngrok from `str(Path(tempfile.gettempdir(), "ngrok"))` which results 1 `/tmp/ngrok`. So do `/tmp/ngrok/ngrok authtoken <your token>` should work.

**Comment by Jassy87** [comment]
I fixed it by using **_pyngrok_** instead of flask_ngrok. As pyngrok enables the use of authentication parameters and subdomain name.
https://www.bizkit.ru/en/2021/07/04/19874/

**Comment by rfay** [comment]
Note that none of the reports above have anything to do with ddev.  Simply following the instructions from ngrok using `ngrok authtoken <token>` (if ngrok is in your $PATH) or `./ngrok authtoken <token>` (if you just downloaded ngrok per https://dashboard.ngrok.com/get-started/setup) will work fine with ddev.

**Comment by Biont** [comment]
@rfay How would you pull this of without ngrok installed on the host? It does not seem to pick up `.ngrok2/ngrok.yml` when I put it in `.ddev/homeadditions` nor does it seem to be possible to use the `ngrok` binary from a `post-start` hook.

**Comment by jonaseberle** [comment]
@Biont `ddev share` requires `ngrok` being installed on the host, not inside the container. It is not include in the ddev containers. Using `post-start` is neither necessary nor makes a lot of sense.
Please open a new issue if you would like to see that changed and include your use case.

I think it is easy enough to 
1. Register and follow the `ngrok authtoken` step at https://dashboard.ngrok.com/get-started/setup
2. make sure it is in your PATH
3. `ddev share`

**Comment by Biont** [comment]
>ddev share requires ngrok being installed on the host
I noticed that right after posting my comment and hoped I was quick enough to delete my comment before wasting anyone's time.
Unfortunately you were quicker, so I apologize for the noise!
