### ISSUE TITLE
`permission denied` errors on custom command on macOS: open ddev/commands/db/mysql: permission denied

### ISSUE THREAD

**Issue by Lefaux** [drud/ddev#3432]
While trying to start up a ddev project, I stumbled across the following error:

```Failed to start [PROJECTNAME]: open /Volumes/Web/vhosts/[PROJECTNAME]/.ddev/commands/db/mysql: permission denied```

It seems that TimeMachine sets additional meta data on all files in a given folder.
You can tell whether that's the case by doing an `ls -al` and watch out for a little `+`at the end of the ACLs.

Wrong:
```-rwxr-xr-x+  1 mathias.schreiber  admin  326 Dec  7 14:22 mysql```
Correct:
```-rwxr-xr-x  1 mathias.schreiber  admin  326 Dec  7 14:22 mysql```

I fixed it by doing `chmod -N` on all affected files (in my case: all of them, so I removed the meta data recursively).

I did NOT check for any implications with TimeMachine (and frankly, I don't really care for backing up that data, since it should be in GIT anyways), so please be aware that there _might_ be side effects of clearing the additional meta data.

**Comment by rfay** [comment]
Thanks so much for debugging this and writing it up. Hopefully I'll remember it next time.
