### ISSUE TITLE
Make "Your docker installation has less than ... available space" use an absolute value

### ISSUE THREAD

**Issue by jonaseberle** [drud/ddev#3433]
Especially on big disks the default 15% warning seems arbitrary.

https://github.com/drud/ddev/blob/71d5ba52ca605468930554e48324cb962cc03412/pkg/dockerutil/dockerutils.go#L1005-L1012

The warning is important, though. It is triggered after downloading images, but before any eventual custom `post-start` steps like `composer install`, `npm install` etc.

What is a reasonable value for required free disk space before running into problems? 5GB?

**Comment by rfay** [comment]
It's a good question. I've helped debug probably dozens of these out-of-space or nearly-out issues, and they cause completely unreasonable results. But the vast majority are on macOS, where there's a specific amount of disk allocated, and images and volumes fill it up, sometimes by big chunks. 

I agree that a 5 GB or 10 GB absolute amount might be better. One problem is that docker underestimates and under-reports, at least on macOS.

**Comment by rfay** [comment]
Interesting support situation today where db container couldn't come up. They ran the [diagnosis script](https://github.com/drud/ddev/blob/master/scripts/test_ddev.sh) which happened to show

```
======= Docker Info =========
Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                  94.2G     64.6G     24.8G  72% /
```

I only found out later that they had been in the process of importing a 40GB database when things went bad. 

Of course this was on macOS with Docker Desktop, where the whole disk is not available, as it typically is with your Linux situation @jonaseberle. But it could show that 24GB probably isn't enough.

**Comment by jonaseberle** [comment]
It happens on Linux installations, too that a usually huge `/home` and a usually relatively small `/` partition don't cater for an immensely growing `/var/lib/docker`. (Solution: Symlinking `/var/lib/docker` to somewhere else or configuring docker `data-root`)

The question is just which threshold would make sense. Being warned about "less than 15% available" on a huge partition is not so helpful, but maybe when < 10 GB are available to docker storage it is time to act?

**Comment by graham73may** [comment]
Just posting some Discord discussions here as this issue comes up high in the Google results. 

> I would do this (these 4 steps below will not harm or delete your projects/databases):
> 
> 1. upgrade DDEV to the latest stable (v1.23.4 at the moment)
> 2. remove all containers and images https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/#delete-and-re-download-docker-images
> 3. remove Docker builder cache with `docker builder prune`
> 4. `ddev start --all` to make all the projects ready.
> 
> These should at least remove the warning ⬆️

> And the biggest concern is your volumes, I see you have 104 volumes taking up 62.02 GB
> 
> These are DDEV databases (and maybe something else), if you don't have backups, make them with [ddev snapshot](https://ddev.readthedocs.io/en/stable/users/usage/commands/#snapshot) or [ddev export-db](https://ddev.readthedocs.io/en/stable/users/usage/commands/#export-db).
> 
> See the blog about backups https://ddev.com/blog/ddev-backups/
> 
> You can review the volumes:
> `docker volume ls`
> 
> and remove the things you no longer need (be careful here)
> `docker volume rm [volume-name]`

> Oh, and also you can view the size of individual Docker objects with
> `docker system df -v`
> 
> See https://stackoverflow.com/questions/57430694/is-there-a-way-to-determine-the-size-of-a-docker-volume-on-my-macos-machine

Thanks @stasadev 🙏

**Comment by rfay** [comment]
For most people on macOS (and especially on Docker Desktop), the easy answer is just expand the available disk space using the Docker UI. You can also expand with both Colima and Lima. On Orbstack it's not necessary.

**Comment by finnlewis** [comment]
> For most people on macOS (and especially on Docker Desktop), the easy answer is just expand the available disk space using the Docker UI. You can also expand with both Colima and Lima. On Orbstack it's not necessary.

@rfay I'm using Orbstack on macOS and I see this message often. I've not figured out what to do yet. You suggest that on Orbstack is not necessary to expand the available disk space using the UI. So is this message a false warning or should I dig deeper into Orbstack configuration?

**Comment by rfay** [comment]
@finnlewis I imagine you're generally out of disk space on the host. `df -h .` in your project directory should show you what's going on on the host. `ddev exec df -h .` should show you what's going on inside the container. Here you see that I have 576G available, which is what's available on the host:

```
$ ddev exec df -h .
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb1       697G  122G  576G  18% /var/www
```

**Comment by chrisfromredfin** [comment]
I also see this often, and I'm using OrbStack. I didn't realize it wasn't necessary to deal with, as I've spent many hours trying to find the OrbStack equivalent of expanding disk size. I end up usually running some docker prune commands, thinking that's necessary. So displaying this actually did create quite a bit of confusion for me. I wonder if it is beneficial to put in "(not necessary with OrbStack)" into the warning message or something. (Would this happen for me on OrbStack if I'm < 15% disk space _on the host_ ?)

**Comment by rfay** [comment]
@chrisfromredfin IMO It is in fact necessary to resolve it, or you get very crazy problems. The current setting is 5000000KB or 5GB. If you don't have 5GB on your host filesystem, that's bad. For you on a host system with less than 5GB available, you'll get crazy problems on the host as well as inside DDEV. 

The value used is defined here: https://github.com/ddev/ddev/blob/cdf8e17a210a8ea9c283d29ecdf9fb19c76b4598/pkg/nodeps/values.go#L130

It would be possible to do a simple PR to make it configurable, but IMO... you don't want less than 5GB on the host and you don't want it in the container either.

Yes, cleaning up your docker situation with `docker rmi -f $(docker images -q)` for example is a place to deal with this.
