### ISSUE TITLE
PHPStorm phpcs setup

### ISSUE THREAD

**Issue by iampuma** [drud/ddev#3435]
Configuring phpcs throws an error.

![image](https://user-images.githubusercontent.com/4799699/145391219-52cd913e-4f56-4ec6-a4a5-6076f9b55ef4.png)

![image](https://user-images.githubusercontent.com/4799699/145391122-6c4d76c7-ac44-46c9-8418-d068db343d1e.png)

**To Reproduce**

 - Setup any project
 - Define the phpcs path in PHPStorm
 - Observe when clicking validate, the error.

**Details**

- Host computer OS and Version: MacOS Monterey v12.0.1
- Docker Desktop 4.3.0
- ddev v1.18.1

**Comment by rfay** [comment]
Please see the [PhpStorm integration topic](https://ddev.readthedocs.io/en/latest/users/topics/phpstorm/) and note
* Docker Desktop 4.3.0 probably won't even work at all with ddev v1.18.1, please use v1.18.2
* PhpStorm has a number of problems still with docker-compose v2, so you'll need to switch to docker-compose v1, `ddev config global --required-docker-compose-version=v1.29.2`
* You absolutely have to use the "Connect to existing container" (Step 8 at https://ddev.readthedocs.io/en/latest/users/topics/phpstorm/#setup-technique) - It looks like you didn't do that because xdebug is obviously on.
<img width="543" alt="Cursor_and_CLI_Interpreters" src="https://user-images.githubusercontent.com/112444/145412681-4c7afc3e-76df-4b7e-ad8f-7fe7775a23e2.png">

**Comment by rfay** [comment]
Haven't heard back from you in 5 days, so closing this. Happy to continue the conversation here or elsewhere.

**Comment by iampuma** [comment]
Hi @rfay currently recently switched to a M1 chip, so could not get to your proposed solution yet. Thanks already for the reply.

**Comment by rfay** [comment]
OK looking forward to having you back on this.

**Comment by iampuma** [comment]
Hi @rfay 

Seems like with updating to:

 - Docker version 20.10.11
 - DDEV version v1.18.2
 - PhpStorm 2021.3

and afterwards selecting`ddev-docker-compose-full.yaml` did not like the `create_host_path` or `host_ip`

![image](https://user-images.githubusercontent.com/4799699/146176131-a1ddfce1-5024-42e0-953a-2bf60509d4d2.png)

This is a new setup Drupal 8 project.

**Comment by rfay** [comment]
Hi @iampuma - 

See the docs in https://ddev.readthedocs.io/en/latest/users/topics/phpstorm/ - 

* PhpStorm does not yet support docker-compose v2, which you're using. The bugs are linked in the doc. There are a few of them.
* If you have moved to the mac M1, docker-compose v1 is not available (and never will be) for arm64, but if you want to use it you can  enable Apple's Rosetta and `docker-compose disable-v2` (or uncheck the "use docker-compose v2" setting in Docker Desktop) and then `ddev config global --use-docker-compose-fromm-path` (or set it in ~/.ddev/global_config.yaml)

**Comment by iampuma** [comment]
Hi @rfay 

Okay thanks for the explanation, much appreciated. I see Docker has been made available for Apple Silicon and this is the one currently installed on my system. With the settings you mentioned above, it throws indeed the error:

`Failed to restart my-demo: Only amd64 architecture is supported for docker-compose v1, not arm64`

I also would not prefer to install the `intel` package and run this with `rosetta` as I am reading online comments of this having very slow performance. So for now I will just live with the fact this needs to be done by a local interpreter.

Thanks for helping out!

**Comment by rfay** [comment]
It's not the full intel Docker Desktop package you have to install - you don't have to install anything. You just need Rosetta enabled and `docker-compose disable-v2` and you'll be using the docker-compose v1.29.2.  There is no docker-compose v1 for arm64, so ddev can't download it for you, but you can use it from your path.

**Comment by iampuma** [comment]
So:
- `Docker 4.3.1 for Mac chip package`
- `Use Docker Compose V2` disabled in the Docker Desktop settings
- `ddev config global --required-docker-compose-version=v1.29.2`
- `rosetta` enabled

I run `ddev restart`, but it still throws `Failed to restart drupal: Only amd64 architecture is supported for docker-compose v1, not arm64`

So what do you mean with "you can use it from your path"? How I see it is:

I have Docker Desktop for Apple Silicon installed, which can not run composer v1, so DDEV will also not work.

**Comment by rfay** [comment]
No, you have to 
* Enable rosetta
* `docker-compose disable-v2` to get the (amd64) docker-compose in your PATH
* `ddev config global --use-docker-compose-from-path`. There is no version that ddev can download, so you have to use the one that's in the path

**Comment by iampuma** [comment]
That seems to have finally worked. The part that confused me was that `docker-compose disable-v2` is of course different than the checkbox in Docker Desktop. 

The settings seem to be setup correctly now:
![image](https://user-images.githubusercontent.com/4799699/146275581-61aa2e30-939c-45cb-9ae3-d9ef99cf924c.png)

![image](https://user-images.githubusercontent.com/4799699/146275662-da51c240-aa3a-4f9a-aab1-fe7edda918cc.png)

But PHPStorm still does not want to work:
![image](https://user-images.githubusercontent.com/4799699/146275770-1a9c1fff-bfe3-49f2-ad8f-f51819425251.png)

**Comment by rfay** [comment]
`docker-compose disable-v2` should do the exact same thing as unchecking the "use docker-compose v2" checkbox. 

Are you able to `ddev ssh` and run phpcs? 
What does it say for `which phpcs`? It should show where you have it installed in vendor/bin/phpcs in your project I'd think. And of course you do have coder module installed? 

Since I don't think anybody has mentioned worked with phpcs before in PhpStorm, we're likely at the end of my knowledge. But you may just be at the point of making phpcs work in there. FIrst, get it working inside the container on the command-line. Then move on to PhpStorm.

**Comment by iampuma** [comment]
So I have found the solution:

First of all, I have found that the problem in the first comment (Xdebug client port) was due to my local configuration. So PHPStorm validated my local setup instead of the docker container. The problem disappeared once I also disabled XDebug and restart php locally (so another PHPStorm bug I assume). Perhaps that could lie on the fact `local` is always configured and auto detected before any other additional configuration with my setup (also not removable as you see in the screenshot):
![image](https://user-images.githubusercontent.com/4799699/146284197-7ab11cbb-50db-4eb3-a840-89c41f0c0068.png)


Now for the additional requirement for setting up `phpcs`:
![image](https://user-images.githubusercontent.com/4799699/146284284-f2585c48-2068-4cc8-9169-6df1ff2aad0b.png)

![image](https://user-images.githubusercontent.com/4799699/146283734-1744097c-e7d8-462a-bb61-ec2dd77c9184.png)

I needed to setup the path manually with a copy paste, but after saving the configuration

![image](https://user-images.githubusercontent.com/4799699/146283565-a853a025-8c56-434e-b437-e237e25ab832.png)

So thanks for the help @rfay

**Comment by rfay** [comment]
Well yay! Could you please summarize here exactly what you had to do in total for the next person?

**Comment by rfay** [comment]
Probably the best thing would be to edit the original comment at the top saying "Solution" and give the blow-by-blow.

**Comment by iampuma** [comment]
So for the people arriving and the tldr;

Prerequisites:

1. `Use Docker Compose V2` unchecked in `Docker Desktop`
2. In case you have an M1 chip, `rosetta` is installed.
3. `ddev config global --required-docker-compose-version=` is set
4. `drupal/core-dev` is a dependency of your project (contains all dependencies required)

Steps:
1. Open the project in PHPStorm
2. Go to the composer.json and click `update` in the top corner to configure PHPStorm settings based on the current `composer.json`
3. Add a new CLI Interpreter under `Settings > PHP` as mentioned in the DDEV documentation https://ddev.readthedocs.io/en/latest/users/topics/phpstorm/#setup-technique. Make sure you do not forget any step like adding the `COMPOSE_PROJECT_NAME=ddev-myprojectname` and setting the `running container` options.
4. Now under `PHP > Quality Tools` select the `Interpreter: web` and click the `...` button.
5. Now Click the `+` to add a new PHP_Codesniffer ` web` interpreter.
6. Set the `PHP_Codesniffer path` to `/var/www/html/vendor/bin/phpcs` if it was not autodetected
7. Optionally set the `Path to phpcbf` to `/var/www/html/vendor/bin/phpcbf` if it was not autodetected
8. Now click `PHP_CodeSniffer inspection` and enable the `PHP_CodeSniffer` if it is not enabled yet
9. Now observe this form as it actually should contain the options `Drupal` and `DrupalPractice`. If it does, it will not work and will throw the error `phpcs: ERROR: the "Drupal" coding standard is not installed. The installed coding standards are MySource, PEAR, PSR1, PSR12, PSR2, Squiz and Zend`
10. So the solution is to select `Custom` as `Coding Standard`
11. The click the `...` button and set the ruleset to `vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml`
12. Tip: also add `,module,install` to the `Check files with extensions`
13. Save all forms

Potential issues:
 -  XDebug error on phpcs validation: make sure you disabled XDebug in the container `ddev xdebug off` (and locally too, even to be sure restart PHP, this seems to be a PHPStorm bug)
 - `PHP_CodeSniffer validation` form does not show the `Custom` option: save all forms until now, and reopen this form. Normally it should show up.

**Comment by rfay** [comment]
Awesome, thanks! Hopefully PhpStorm will get those docker-compose v2 issues sorted out in a coming release.
