### ISSUE TITLE
Add single variable to environment without removing other variables

### ISSUE THREAD

**Issue by mieserfettsack** [drud/ddev#3436]
**Is your feature request related to a problem? Please describe.**
I would like to change one single environment variable before running ddev on a different host. In my case I have more than one variable in my config.yaml. I tried to use ddev config --web-environment BLAH=123. This removes all other environments in config.yaml

**Describe the solution you'd like**
I would like to use ddev config --web-environment BLAH=123 to change a variable that exist or creates a new one if not. All other variables must be untouched.

**Describe alternatives you've considered**
Currently I am using sed to change that variable.

**Additional context**
I do not know about the right indentation inside a yaml file. When using dev config --web-environment the variable is not intended with tabs nor spaces. Maybe this is a bug.

**Comment by rfay** [comment]
You have a couple of options. DDEV doesn't merge that value when you use `ddev config` on it (or any other way)

Most people check in their config.yaml, so using `ddev config` to change it differently on different sites isn't that good.

But there are two easy options:

1. Edit the .ddev/config.yaml: Just edit it and add the new env you want. This is the same as using `ddev config` in most cases, but in this case you're more powerful.
2. Add a .ddev/config.thissite.yaml to override the values you want on each site. But you'll need to have all the values in there.
3. Use the old technique of putting the extras or overrides in a `docker-compose.env.yaml` like this:
```yaml
version: "3.6"
services:
  web:
    environment:
      - ZONE=xxx
      - ZFIVE=yyy
 ```

**Comment by rfay** [comment]
Oh, btw, yaml usually uses spaces, 2-per. And arrays seem to be fine either indented or not indented.

**Comment by mieserfettsack** [comment]
> You have a couple of options. DDEV doesn't merge that value when you use `ddev config` on it (or any other way)
> 
> Most people check in their config.yaml, so using `ddev config` to change it differently on different sites isn't that good.
> 
> But there are two easy options:
> 
> 1. Edit the .ddev/config.yaml: Just edit it and add the new env you want. This is the same as using `ddev config` in most cases, but in this case you're more powerful.
> 2. Add a .ddev/config.thissite.yaml to override the values you want on each site. But you'll need to have all the values in there.
> 3. Use the old technique of putting the extras or overrides in a `docker-compose.env.yaml` like this:
> 
> ```yaml
> version: "3.6"
> services:
>   web:
>     environment:
>       - ZONE=xxx
>       - ZFIVE=yyy
> ```

**Comment by mieserfettsack** [comment]
Okay, thanks for your answer. I do not think this is a

**Comment by rfay** [comment]
Looks like you didn't finish your sentence :)

**Comment by rfay** [comment]
I didn't understand your sentence, and didn't understand why you reopened after closing. So I'll close it again, happy to continue the conversation here or elsewhere, and if this needs to be reopened we can reopen.
