### ISSUE TITLE
Add `blackfire_enabled` setting to config.yaml

### ISSUE THREAD

**Issue by lolautruche** [drud/ddev#3438]
**Describe the solution you'd like**
Like for XDebug or XHProf, it would be nice to have a `blackfire_enabled` setting, so that Blackfire is enabled automatically.

**Describe alternatives you've considered**
Enable Blackfire automatically, only disable it when XHProf is enabled (it's OK to have XDebug in dev environments)?

**Additional context**

**Comment by rfay** [comment]
One option, that will work for you, just just 
```yaml
hooks:
  post-start:
  - exec-host: ddev blackfire
```

If this solves your problem, maybe no changes are required to ddev.

**Comment by rfay** [comment]
What do you think about that solution @lolautruche ? Does it meet your needs?

**Comment by lolautruche** [comment]
Yes it does, thank you 😊
