### ISSUE TITLE
Add `ddev php` command

### ISSUE THREAD

**Issue by lolautruche** [drud/ddev#3439]
**Describe the solution you'd like**
It would be nice and less verbose to have a `ddev php` command in lieu of doing `ddev exec php`, or `ddev ssh` to run PHP commands.

**Comment by rfay** [comment]
You know about the shortcut to exec, right? `ddev . php`, for example `ddev . php --version`.

You can also so very easily create a global custom command based on something like the [drush command](https://github.com/drud/ddev/blob/master/pkg/ddevapp/global_dotddev_assets/commands/web/drush) and have it today!

```bash
#!/bin/bash

## Description: Run php inside the web container
## Usage: php [flags] [args]
## Example: "ddev php --version"

php "$@"
```

**Comment by rfay** [comment]
What do you think, @lolautruche - does the solution above meet your needs? I'm always hesitant to just add new commands because then nobody knows what they all are.

**Comment by lolautruche** [comment]
It is a good workaround, but doesn't feel so natural. 
A php command would be a great addition and would feel more comfortable. I get your point about adding new commands, but I think this one would be more than safe 😅. 

For what it worth, Lando does have a php command 😉.

**Comment by rfay** [comment]
But this does add the php command so anybody can have it.  You just want it built-in? What doesn't feel natural? Adding this as a global command is exactly the same behavior as having it built-in, or am I missing something?

**Comment by lolautruche** [comment]
I know I can add a custom command, but as `ddev php` looked like a basic one to me, that's why I suggested to add it, just like `ddev composer` 😉

**Comment by joelpittet** [comment]
I'd use this to run things I do or like to do every so often that I usually use 3v4l.org for:

`ddev php -r 'print date("Y-m-d");'`

Just convenient to test it on my host (php 8.x) and in the container (php 7.4)... quickly

**Comment by mglaman** [comment]
I'd love being able to do `ddev php -a` and launch into an interactive shell

Currently have to do `ddev drush php`

**Comment by rfay** [comment]
Or `ddev exec php` of course :)

**Comment by lolautruche** [comment]
@mglaman Shouldn't we then consider adding [psysh](https://psysh.org/) along with a dedicated command? It is so much more comprehensive than `php -a`!

@rfay Is it already possible to add built-in global composer packages?

**Comment by rfay** [comment]
@lolautruche you can add anything global with a .ddev/web-build/Dockerfile, install it into /usr/local/bin

**Comment by mglaman** [comment]
@lolautruche no. That adds dependencies and unexpected conflicts in environments.

That library uses PHP-Parser. As does PHPStan and Rector.

I guess it wouldn't if global dependency... But it adds a bigger maintenance burden.

**Comment by lolautruche** [comment]
@mglaman Psysh is also available as a phar that could be installed independently. 
But that's beyond the scope of this issue 😅

**Comment by gilbertsoft** [comment]
I wonder why you guys need the php cli regularly so you think it should be added by default. Thinking back the last two weeks I had to run it exactly one time to check a configuration default of XDebug. Don't remember any other usage the last three years.

So I think using project or global custom commands instead should be fine normally where needed.

**Comment by rfay** [comment]
Oh, I shouldn't forget to mention that `ddev .` is a shortcut for `ddev exec`. So you can `ddev . php` as much as you want. It's pretty close to `ddev php` :)

**Comment by tyler36** [comment]
@lolautruche 
I added a ["tinker" command to ddev-contrib](https://github.com/drud/ddev-contrib/tree/master/custom-commands/tinker).

If your project uses Drush (Drupal) or Laravel, you can type `ddev tinker` to start their respective REPL via Psysh.
an interactive session inside the DDEV container.

**Comment by rfay** [comment]
A PR to add php command would be welcome if somebody wants to do it here. Copy https://github.com/drud/ddev/issues/3439#issuecomment-991113754 and put it in https://github.com/drud/ddev/tree/master/pkg/ddevapp/global_dotddev_assets/commands/web - that's all it takes :)

**Comment by tyler36** [comment]
Done. PR #3498

**Comment by rfay** [comment]
`ddev php` is in there!

**Comment by rfay** [comment]
There was a bug in the implementation, it was missing the `#ddev-generated` line at the top. That means that anybody that has gotten this in an alpha needs to delete the existing one, `rm ~/.ddev/commands/web/php` and it will be recreated. Otherwise, you'll have the original one forever, and won't get updates.
