### ISSUE TITLE
`ddev artisan`: Permission denied

### ISSUE THREAD

**Issue by tschni** [drud/ddev#3440]
**Run a Diagnostic and Paste Link Here**

https://www.toptal.com/developers/hastebin/taqameyama.yaml

**Describe the bug**

I have created a new DDEV Laravel project, now when I run `ddev artisan` in the terminal I only get the following error message:

![image](https://user-images.githubusercontent.com/58136516/145615883-6904d8ef-25bb-4b81-b455-efcf04f542bf.png)

However, when I run `ddev . php artisan` it works:

![image](https://user-images.githubusercontent.com/58136516/145616038-f2270d04-37e9-4b56-a766-96e9e6c409f0.png)

**Comment by rfay** [comment]
I imagine that the "artisan" command is not executable.
Please `ls -l artisan` in your project (and inside the container with `ddev exec ls -l artisan`

**Comment by tschni** [comment]
Here you go:

![image](https://user-images.githubusercontent.com/58136516/145619823-c99c2c1a-421e-4f1e-881f-9f8d93620498.png)

**Comment by rfay** [comment]
Right, you have to make that file executable. `chmod +x artisan`. 

This has nothing to do with ddev, but it does have to do with however you got that. It should have been made executable. I wonder if the composer build has changed with laravel or something. I think somebody else had this the other day. 

Closing, as this doesn't have to do with ddev. Happy to continue the conversation here or elsewhere.

**Comment by tschni** [comment]
You are completely right, now everything works, thanks and sorry for the confusion!

I have cloned the repository normally from Git, apparently the permissions are not set correctly, strange....
