### ISSUE TITLE
ddev v1.18.2: Windows WSL2 Xdebug not connecting to IDE

### ISSUE THREAD

**Issue by nhovratov** [drud/ddev#3441]
**Run a Diagnostic and Paste Link Here**

https://pastebin.com/SmAr8H7F

**Describe the bug**
Since the recent version of ddev, xdebug does not connect anymore to my IDE (phpstorm). I get this logs entry:
`[10-Dec-2021 17:02:19] WARNING: [pool www] child 3574 said into stderr: "NOTICE: PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9000 (through xdebug.client_host/xdebug.client_port) :-("`

**To Reproduce**
1. ddev xdebug on
2. Open the php app in a browser

**Expected behavior**
xdebug should connect to the IDE

**Version and configuration information (please complete the following information):**

ddev version v1.18.2
Docker Desktop 4.3.0
Windows 10 / WSL 2

**Additional context**
It worked before the update. I didn't change any configuration.

**Comment by rfay** [comment]
Please see today's thread in discord, https://discord.gg/kDvSFBSZfs "vscode WSL2 xdebug..."

The user there had `docker-ce` installed inside WSL2 and that broke it, because ddev was determining whether it was running in docker desktop by looking at the `docker` command, to see if it was the one from Docker Desktop.

**Comment by rfay** [comment]
And please make sure you work through the [Troubleshooting](https://ddev.readthedocs.io/en/latest/users/step-debugging/#troubleshooting-xdebug) section, but I imagine this is the problem

**Comment by nhovratov** [comment]
Hey, thanks for the quick reply. Yeah I've seen the new Troubleshooting section you added, but couldn't find an issue for that. Now that I've read your discord thread everything makes sense.

I deinstalled my local docker now.

For me, there is one small difference. My path to docker-desktop is:
`lrwxrwxrwx 1 root root 44 Dez 10 18:56 /usr/bin/docker -> /wsl/docker-desktop/cli-tools/usr/bin/docker`

The debugger still won't connect. I restarted everything already. Does it have to be `/mnt/wsl/docker-desktop/cli-tools/usr/bin/docker`?

**Comment by rfay** [comment]
Oh, I think I see the problem. Your distro is named "cli-tools", right? The code is mistaken in assuming that the docker command is in a distro named wsl. Just because it is for most people including me.

**Comment by rfay** [comment]
Or ... how can it be `/wsl` instead of `/mnt/wsl`? You have wsl.conf set to mount in a different place? 

Probably the target /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker is valid, so you can probably just either override that link or put a link earlier in your $PATH, `ln -s /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker /somewhere/early/in/path/docker`

**Comment by nhovratov** [comment]
I have

```
[automount]
root = /
```
I can't remember when or why I added that. Probably to make something work. I think it had something to do with the C volume being in /c/ and not /mnt/c.

**Comment by rfay** [comment]
I think going back to the default will fix it for you, but the logic in ddev v1.18.2 definitely needs to be improve. https://github.com/drud/ddev/blob/f3a5e3166717254aba2bede3469cee5f473f86c3/pkg/nodeps/utils.go#L68-L79

**Comment by nhovratov** [comment]
`ln -s /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker /somewhere/early/in/path/docker`

This works!

**Comment by rfay** [comment]
Yay!

Thanks for reaching out about this, and definitely have to find a more robust way to determine if we're running in WSL2 + Docker Desktop.

**Comment by nhovratov** [comment]
Thank you very much for your help! I very appreciate it. Now there is also an issue people can refer to, if they have the same issue as me.

One last thing: In the guide you wrote: `make sure that ls -l $(which docker) is not a link to /mnt/wsl.` Did you mean not a link to (local) /usr/bin/docker ?

**Comment by rfay** [comment]
The current usage is that if `docker` is not a link to /mnt/wsl/... then it assumes docker is installed inside WSL2 (not docker desktop). Is that the question you're asking?

**Comment by nhovratov** [comment]
Oh ok, I've read it wrong. All fine, thank you!

**Comment by rfay** [comment]
* https://github.com/drud/ddev/pull/3443

**Comment by tyler36** [comment]
Just got hit with this. 

Upgraded to `v1.19.0-alpha1`, and it worked.
