### ISSUE TITLE
Terminus issue after updating project to php 8

### ISSUE THREAD

**Issue by bkbelton** [drud/ddev#3442]
**Run a Diagnostic and Paste Link Here**
https://gist.github.com/bkbelton/178545df9a0b92f7d4de60405177503e

**Describe the Problem**
After reconfiguring project for php8 (revised entries in pantheon.yml and config.yaml), any terminus command returns:
PHP Warning:  require_once(phar:///usr/local/bin/terminus/vendor/symfony/polyfill-mbstring/Resources/mb_convert_variables.php8): Failed to open stream: phar error: "vendor/symfony/polyfill-mbstring/Resources/mb_convert_variables.php8" is not a file in phar "/usr/local/bin/terminus" in phar:///usr/local/bin/terminus/vendor/symfony/polyfill-mbstring/bootstrap.php on line 115

Warning: require_once(phar:///usr/local/bin/terminus/vendor/symfony/polyfill-mbstring/Resources/mb_convert_variables.php8): Failed to open stream: phar error: "vendor/symfony/polyfill-mbstring/Resources/mb_convert_variables.php8" is not a file in phar "/usr/local/bin/terminus" in phar:///usr/local/bin/terminus/vendor/symfony/polyfill-mbstring/bootstrap.php on line 115
PHP Fatal error:  Uncaught Error: Failed opening required 'phar:///usr/local/bin/terminus/vendor/symfony/polyfill-mbstring/Resources/mb_convert_variables.php8' (include_path='.:/usr/share/php') in phar:///usr/local/bin/terminus/vendor/symfony/polyfill-mbstring/bootstrap.php:115
Stack trace:
#0 phar:///usr/local/bin/terminus/vendor/composer/autoload_real.php(66): require()
#1 phar:///usr/local/bin/terminus/vendor/composer/autoload_real.php(56): composerRequire1921a2cbccef196fbc6abfa6353f7b27('0e6d7bf4a5811bf...', 'phar:///usr/loc...')
#2 phar:///usr/local/bin/terminus/vendor/autoload.php(7): ComposerAutoloaderInit1921a2cbccef196fbc6abfa6353f7b27::getLoader()
#3 phar:///usr/local/bin/terminus/bin/terminus(13): include_once('phar:///usr/loc...')
#4 /usr/local/bin/terminus(10): require('phar:///usr/loc...')
#5 {main}
  thrown in phar:///usr/local/bin/terminus/vendor/symfony/polyfill-mbstring/bootstrap.php on line 115

Fatal error: Uncaught Error: Failed opening required 'phar:///usr/local/bin/terminus/vendor/symfony/polyfill-mbstring/Resources/mb_convert_variables.php8' (include_path='.:/usr/share/php') in phar:///usr/local/bin/terminus/vendor/symfony/polyfill-mbstring/bootstrap.php:115
Stack trace:
#0 phar:///usr/local/bin/terminus/vendor/composer/autoload_real.php(66): require()
#1 phar:///usr/local/bin/terminus/vendor/composer/autoload_real.php(56): composerRequire1921a2cbccef196fbc6abfa6353f7b27('0e6d7bf4a5811bf...', 'phar:///usr/loc...')
#2 phar:///usr/local/bin/terminus/vendor/autoload.php(7): ComposerAutoloaderInit1921a2cbccef196fbc6abfa6353f7b27::getLoader()
#3 phar:///usr/local/bin/terminus/bin/terminus(13): include_once('phar:///usr/loc...')
#4 /usr/local/bin/terminus(10): require('phar:///usr/loc...')
#5 {main}
  thrown in phar:///usr/local/bin/terminus/vendor/symfony/polyfill-mbstring/bootstrap.php on line 115
Failed to execute command terminus --list: exit status 255

**To Reproduce**
1. Change pantheon.yml phpversion to 8.0  - "php_version: 8.0"
2. Change .ddev/config.yaml php entry tp "php_version: "8.0"
3. Push changes to pantheon - php version is successfully changed on Pantheon
4. git pull just in case
5. ddev restart
6. ddev exec terminus [any terminus command]
7. output as above

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: [e.g. Windows 10, macOS Big Sur, Linux (distro), WSL2 (distro)]
- Docker Desktop version if on macOS or Windows (from "About Docker Desktop")
- ddev version information (use `ddev version`)
- config.yaml contents for the misbehaving project
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

**Additional context**
This happens with either 'ddev exec terminis' or 'ddev ssh  / terminus'.  I apologize if I am missing some obvious configuration somewhere.

**Comment by rfay** [comment]
I get your same result. I don't think the bundled terminus version is ready for php8.0 yet.

I see several recent issues... https://github.com/pantheon-systems/terminus/issues?q=is%3Aissue+php8+is%3Aclosed

**Comment by bkbelton** [comment]
Great - thank you.

**Comment by bkbelton** [comment]
In case anyone else runs into this, I found that adding
`RUN curl -O https://raw.githubusercontent.com/alexfornuto/terminus-installer/master/installer.php && php installer.php` to .ddev/web-build/Dockerfile works.  That script is a 3rd party (non-Pantheon) script mentioned on the [Pantheon site](https://pantheon.io/docs/terminus/install#install-terminus)
