### ISSUE TITLE
NOTE: Docker Desktop 4.3.2 + WSL2 "Ports are not available" bug is back -- and a workaround

### ISSUE THREAD

**Issue by working-name** [drud/ddev#3487]
Hi there,

https://github.com/docker/for-win/issues/10008 That seems to be back with Docker Desktop 4.3.2

- Tried wsl shutdown, reboot, restart docker, reinstall docker, winnat restart, hyper-v reinstall (the whole port reserve thing made no sense). 
- I block windows updates, and pretty much every network connection by default (using Portmaster). No windows updates, not even "windows defender definitions" since November. 
- I manually updated Docker Desktop to 4.3.2 from 4.3.0 around 4-5 reboots ago. My computer stays on all the time, I reboot it when windows inevitably becomes stupid.
- Nothing has changed in terms of system software, I don't have new stuff I just installed, especially stuff that would utilize ports 80 and 443. 

What I'm saying is that the issue started seemingly out of the blue, and found no other way to get past it except with killing IP Helper while docker/ddev does its thing.

### Workaround
1. Open services, stop "IP Helper"
2. Start your container(s)
3. Start "IP Helper" back up.

```py
PS C:\Windows\system32> echo "Listening on 443:"; Get-Process -Id (Get-NetTCPConnection -LocalPort 443).OwningProcess; echo "Listening on 80:"; Get-Process -Id (Get-NetTCPConnection -LocalPort 80).OwningProcess
Listening on 443:

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    368      22     2804      10816       0.05  12120   0 svchost
Listening on 80:
    368      22     2804      10816       0.05  12120   0 svchost


PS C:\Windows\system32> echo "Listening on 443:"; Get-Process -Id (Get-NetTCPConnection -LocalPort 443).OwningProcess; echo "Listening on 80:"; Get-Process -Id (Get-NetTCPConnection -LocalPort 80).OwningProcess
Listening on 443:

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    447      34    31624      38372       1.34   4332   2 com.docker.backend
    383      23     3372      11088       0.08  13284   0 svchost
Listening on 80:
    447      34    31624      38372       1.34   4332   2 com.docker.backend
    383      23     3372      11088       0.08  13284   0 svchost
```

I've been reading around issues and so on and I noticed that for wsl2 it's recommended to treat it like a regular linux machine and install docker inside there. I haven't tried it out yet, no idea how the networking stack would work as I'd like to keep my GUI apps inside windows. Otherwise not much point in keeping windows 😁 I would absolutely hate having to forward ports from powershell 🤢 to get to the wsl2 services. They don't stick, wsl2 gets a different IP on every boot, unsuccessfully tried a bunch of scripts I found online to keep wsl2 ssh service up and forwarded. Again. Powershell. 🤢 🤮

**Comment by rfay** [comment]
The 3 test runners that do WSL2 testing for ddev aren't having any trouble with Docker 4.3.1 and 4.3.2. Note that there isn't any actual difference in operation between 4.3.0/4.3.1/4.3.2 - there were little add-ons for detecting the log4j vulnerability. I wonder what is going on with your machine. Do keep watching the Docker for Windows issue queue to see if others are having trouble.

**Comment by working-name** [comment]
Hmm good points. It might very well be my machine going crazy. Will reinstall windows 11 over the weekend and report back if there's changes.

**Comment by rfay** [comment]
You don't actually explain what's happening to you here, just saying that it seems to be like an old docker issue.

Key things to remember when debugging this:
* Go through all the [troubleshooting steps](https://ddev.readthedocs.io/en/latest/users/troubleshooting/). 
* Before reinstalling Windows I recommend a Docker Factory Reset. It's a lot easier. 
* When working with WSL2 you have to remember that there are two (or even more) different "computers" where port conflicts may occur.  WSL2 has an amazingly complex networking challenge with all these situations.
  * A process can be running on the *Windows* side. Use the suggested [Windows-side tools](https://ddev.readthedocs.io/en/latest/users/troubleshooting/#method-2-fix-port-conflicts-by-stopping-the-competing-application) to chase this.
  * A process can be running inside WSL2. Use the `sudo lsof -i :80 -sTCP:LISTEN` or `sudo lsof -i :443 -sTCP:LISTEN` technique inside WSL2 to chase this.
  * A process can be running in a different WSL2 distros. If you're only running one, then you don't have this, but it's something to watch out for.

**Comment by rfay** [comment]
Closing this for now, but happy to continue the conversation, and I'm also happy to do a call with you to see if we can sort it out, as long as you've already been through all the troubleshooting steps.

**Comment by working-name** [comment]
Sorry, just noticed this got further replies. You are right, I didn't just spell out the error; it's this:
`Cannot start service ddev-router: Ports are not available: listen tcp 127.0.0.1:443: bind: An attempt was made to access a socket in a way forbidden by its access permissions.`

I very much appreciate your offer to help, especially to give even more of your personal time. You're a very kind person, thank you 🙏 . I do not think we'll need to waste your time though, the workaround of killing svchost.exe and then running `ddev start` still works ok.

<hr>
TL;DR version:

I did not reinstall windows 11 yet as the issue has not happened since my last restart ( 14 days ago lol ). This time I did not restart, but I shut down docker to stop CPU abuse and didn't start it for a couple hours. Docker often causes ghost (ps aux as root and htop can't see the process) high cpu usage to vmmem (wsl2 process), and it generally stops once you restart docker desktop. Some people say it has to do with wsl2 VM trying to swap ram but I have found that to not be the case for me - even with 4GB of RAM used it still goes rogue.

In terms of the network part, it's a windows process - svchost.exe - that runs pretty much anything you can imagine (most often services, kinda like systemctl). In this case, it seems to be a service related to Teredo according to process explorer. That's a network tunneling utility, usually ipv6<->ipv4 but microsoft also uses it like a glorified port opening mechanism for xbox services.

As far as the troubleshooting steps go, I didn't follow the whole document. The reset to factory default for Docker Desktop is something I'll have to try out. That being said, I did bump into your troubleshooting steps when googling the issue and it all seemed like common sense stuff, gave it a cursory read. I had done most of them on my own. Namely:

- ddev poweroff
- wsl --shutdown
- remove docker, upgrade docker, shut down docker
- reboot windows 11 itself
- no firewall outside of portmaster which does not hinder LAN communication at all, no antiviruses because it's just me using this computer and I'm not ignorant in that aspect. Disabled windows defender via group policy.
- Docker Desktop was not running out of ssd space, had about 100GB free, now `/dev/sdb        251G  150G   89G  63% /`. WSL2 has access to all 8 CPU cores, and half my physical ram (32gb). Docker lets WSL2 manage resources.
- the only customization I make to ddev is xdebug port. I wasn't very concerned about this as no project changes occurred between ddev being able to start the router container and failing to listen on 80/443.
- Simplest ddev project bumps into the same issue.
```
~/dev/sites/simplest-test$ printf "<?php\nphpinfo()\n">index.php
user@dasmachine:~/dev/sites/simplest-test$ ddev start
Starting simplest-test...
Building ddev-ssh-agent
Creating ddev-ssh-agent ...
Creating ddev-ssh-agent ... done
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
Pushed mkcert rootca certs to ddev-global-cache/mkcert
Running   Command=ip address show dev docker0
Building db
Building web
Creating ddev-simplest-test-db ...
Creating ddev-simplest-test-db ... done
Creating ddev-simplest-test-web ...
Creating ddev-simplest-test-dba ...
Creating ddev-simplest-test-dba ... done
Creating ddev-simplest-test-web ... done
Creating ddev-router ...
Creating ddev-router ... error

ERROR: for ddev-router  Cannot start service ddev-router: Ports are not available: listen tcp 127.0.0.1:443: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

ERROR: for ddev-router  Cannot start service ddev-router: Ports are not available: listen tcp 127.0.0.1:443: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
Encountered errors while bringing up the project.
Failed to start simplest-test: failed to start ddev-router: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-simplest-test docker-compose -f /home/user/.ddev/.router-compose-full.yaml -p ddev-router up -d', action='[-p ddev-router up -d]', err='exit status 1', stdout='', stderr='Creating ddev-router ...
Creating ddev-router ... error

ERROR: for ddev-router  Cannot start service ddev-router: Ports are not available: listen tcp 127.0.0.1:443: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

ERROR: for ddev-router  Cannot start service ddev-router: Ports are not available: listen tcp 127.0.0.1:443: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
Encountered errors while bringing up the project.'
```
- do not wish to have ddev use something other than 80 and 443 as I want those for my local web dev.
- do not have more than 1 distro, only ubuntu.

So anyway, it's the networking stack as I mentioned in my initial post. There's a svchost.exe instance that tries to listen on TCP ports 80, 443, and other such ports. It's not going to go away anytime soon because the xbox services run on pretty much any modern windows computer regardless of actual use.

`netstat -tulpn | grep -P '(?:80|443)'` always comes back clean (wsl2 side).

When I kill the svchost.exe process(es) listening on ports 80 or 443 and try `ddev start` again, it succeeds.

The very confusing part is that those windows services (svchost.exe) get restarted and start listening on the very same port numbers. I can still get to ddev from other devices on my LAN or the internet even if I open up the ports in my router.

Therefore that's the reason I think the docker bug came back or Docker is in some way not requesting the ports properly - maybe there's some weird `netsh interface portproxy add v4tov4 listenport=` type command docker desktop should run or maybe bind a different network interface. No idea, I'm just speculating at this point, given that it's apparently possible to have 2 processes listening on the same port number and protocol with the wsl2 networking stack.

**Comment by rfay** [comment]
It sounds like you're on track to solve this.

From what I read, you have a process on the windows side that listens on port 443 and prevents ddev-router (in docker) from using it. 

I recommend that you use the techniques again in https://ddev.readthedocs.io/en/latest/users/troubleshooting/#method-1-fix-port-conflicts-by-configuring-your-project-to-use-different-ports and look especially for something listening on the Windows side. 

The tool mentioned there, [tcpview](https://docs.microsoft.com/en-us/sysinternals/downloads/tcpview) may help you.

You say 
> It's not going to go away anytime soon because the xbox services run on pretty much any modern windows computer regardless of actual use

I don't know why you would have "xbox" services running on "any modern windows computer", nor why something would be listening. I imagine you have a service on the Windows side that you don't want there, and you have to figure out what it is and uninstall it.

**Comment by working-name** [comment]
Yeah unfortunately I'm no closer to figuring out why this is going on. The service utilizing either port 443 or 80, seemingly randomly between the two, is IP Helper service ran through svchost.exe. It's not a user service, it's something utilized by both xbox services and `netsh`/wsl2 for port forwarding. I can't uninstall it, and I can't leave it stopped either because then I cannot access any services listening inside wsl2 from windows. Rock and a hard place.

https://working.name/docker.wsl2.port.issues.mp4

**Comment by rfay** [comment]
Please do just use a different port. It seems like since that computer has stuff you're unwilling to remove, you should just use `ddev config --router-http-port=8080 --router-https-port=8443` and be done with it. 

Another option you have is to stop using Docker Desktop and just use docker installed in WSL2. https://ddev.readthedocs.io/en/latest/users/docker_installation/#windows-installation-wsl2-with-docker-linux-installed-inside - I wouldn't be surprised if you'd have a better experience.

**Comment by working-name** [comment]
Unfortunately this isn't a case of not being willing to remove something from this computer. It's a microsoft service not something I can remove or even stop without dire consequences. I don't use the xbox stuff, and the second use for IP Helper is to handle the portproxy interface. 

I switched to docker + docker-compose within WSL2 as you recommended, then did a `netsh interface portproxy reset` as admin. After restarting wsl2 and ddev I can now get to the WSL2 services and don't have to run Docker Desktop. No issues so far with the exception of not being able to run any wsl.exe commands from windows or bash after installing docker in wsl2, so no automated starts of docker service. Which is not a huge deal for me as it's 99% working.

Thank you again for your insight, very helpful.
