### ISSUE TITLE
Add ddev debug update-settings

### ISSUE THREAD

**Issue by shaal** [drud/ddev#3517]
**Is your feature request related to a problem? Please describe.**

In DrupalPod, I'm trying to find ways to get an environment up and running in shortest time.
After ddev is already configured and running, when installing a site from scratch (using `ddev composer` commands), I want to be able to get ddev to update the settings files, without going through a full `ddev restart`.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jonaseberle** [comment]
Can you be more specific what is changed by `ddev composer` that needs a `ddev restart`?

**Comment by rfay** [comment]
Please just answer the question @shaal , rather than giving a link to an obscure PR that we have no context on.  I don't want to have to try to understand your PR.

**Comment by shaal** [comment]
Sorry, I think I misunderstood ddev's process.
`ddev config` creates the `settings.php` and `settings.ddev.php` file which I needed, without running `ddev restart`.

**Comment by rfay** [comment]
IIRC ddev makes the settings.php/settings.ddev.php on config and also on start. And for many of your usages it may make sense to create your own settings files and turn off ddev's creation. It's worth thinking about anyway.

**Comment by shaal** [comment]
Wherever possible, I prefer using ddev's default behavior.
