### ISSUE TITLE
symlinks in project/.ddev/custom_certs - maybe worth resolving symlink and copying source file(s)?

### ISSUE THREAD

**Issue by working-name** [drud/ddev#3524]
**Is your feature request related to a problem? Please describe.**

I attempted to symlink the crt and key files from `/etc/letsencypt/live/domain.com/` into `custom_certs` but it doesn't seem to be properly picked up. In fact, the self-signed certificate is utilized instead. 

I'm wondering if it's worth implementing resolving the symlinks and copying the source files instead so that when you start the container the next time, the copied certificate and key are always the latest - LE refreshes every 3 months (🤔 ?).

**Describe the solution you'd like**

I would like ddev to resolve the symlink and copy the actual source file into the router container.

**Describe alternatives you've considered**

I'm currently using a bash script to supplement the setup.
```shell
# this happens in project/.ddev/custom_certs
cp /etc/letsencrypt/archive/domain.name/$(basename $(readlink /etc/letsencrypt/live/domain.name/fullchain.pem)) project.domain.name.crt
cp /etc/letsencrypt/archive/domain.name/$(basename $(readlink /etc/letsencrypt/live/domain.name/privkey.pem)) project.domain.name.key
```

**Additional context**

I don't know anything about go unfortunately, but did look at the code, and it looks like the copy command resolves down to an external library `otiai10/copy/copy.go:38` which implements a switchboard to properly issue the OS specific copy command for the resource type in question. It seems to handle symlinks but not sure if it resolves it first or it just does the equivalent of `cp -P`, meaning just copies the symlink while maintaining its target.

Thank you!

**Comment by rfay** [comment]
I'm glad you're using the custom certs, and would love to know more how and why you're using them.

But did you know that ddev has direct native Let's Encrypt support?  https://ddev.readthedocs.io/en/latest/users/alternate-uses/#casual-project-webhosting-on-the-internet-including-lets-encrypt

**Comment by rfay** [comment]
The code that copies in is at https://github.com/drud/ddev/blob/11f2eeec84f8de831d9ee5cb6b4df67ac41ff360/pkg/ddevapp/ddevapp.go#L975-L984

I'm sure it could resolve the symlink, and a PR would be welcome, but this is a very rarely used feature, and looking forward to hearing how and why you use it :)

Note that symlinks are questionable in environments like Windows. 

Looks like dockerutil.CopyIntoVolume would need to check symlink and resolve it, not sure how good that would be for other usages.

**Comment by working-name** [comment]
Awesome stuff 👍 , I'll try to test it out, I guess any time is a good time to start fiddling with go. I know windows has some odd symlink stuff too but I doubt we'll have to support it since for now certbot is not a native windows utility.

I'm using custom certs because I already have a wildcard cert from LE, and I'm configuring ddev's project_tld to be the actual domain name. I'm playing around with a remote dev env complete with a hosted vscode, and with the help of the wildcard I don't have to worry about VPNs or running dnsmasq or anything of the sort. Not that the last couple options would not be good, they're both feasible options.

A second reason for which I chose wildcard vs native LE via ddev is the fact that I may bump into request limits with LE if each project gets its own cert.

**Comment by rfay** [comment]
I'm going to go ahead and close this for now, because it seems to have more to do with your scripting expectations than ddev's functionality. Happy to continue the conversation here or elsewhere though, and happy to reopen or help with a PR.
