### ISSUE TITLE
"ddev logs" always reports "DEBU[0000] Corrupted prefix: []" when DRUD_DEBUG is set

### ISSUE THREAD

**Issue by rfay** [drud/ddev#353]
## What happened (or feature request):

`ddev logs` or `ddev logs -s db` both emit `DEBU[0000] Corrupted prefix: []` in their output.

This only happens when DRUD_DEBUG is set.

The most likely place this is coming from is
```
vendor/github.com/docker/docker/pkg/stdcopy/stdcopy.go:					logrus.Debugf("Corrupted prefix: %v", buf[:nr])
```

This was introduced between 0.3 and 0.4 of ddev. However, there was no change to the vendored docker stdcopy there. The problem *could* be in upstream code as opposed to in our vendored code (the message may be coming from docker code?)

I'm not sure how important this is, but it is recreatable, is caused by changes in our code, and does say the word CORRUPTED, which strikes fear in my heart.

## Related source links or issues:

**Comment by rickmanelius** [comment]
Worth submitting an issue to the docker/moby GitHub project to make visible there and simply track here?

**Comment by rfay** [comment]
Well, we introduced this between 0.3 and 0.4, so I don't think so. Might  be.

**Comment by rickmanelius** [comment]
I'm not able to recreate with v0.9.3. Closing for now and we can re-open if it pops back up.
