### ISSUE TITLE
Replace occurrences of "ddev service get" with "ddev get"

### ISSUE THREAD

**Issue by leymannx** [drud/ddev#3545]
I'm on 1.19.0-alpha3 because I wanted to try out the new `ddev get` and `ddev service` command and it looks as in https://github.com/drud/ddev/commit/e54753a09c9f3f68c49383fe00a03805cdee4f75#diff-cca02240913a60cedcc8a38b0605bc35538e45ae96c1513197b5b6168450e09c a big typo found its way across the repo, or maybe I'm just confused:

On https://ddev.readthedocs.io/en/latest/users/extend/additional-services/#apache-solr and some other places it says `ddev service get` where it actually should be just `ddev get`, right?

**Comment by rfay** [comment]
You're awesome for trying it and awesome for catching that.

I was pretty far along when I realized you could "get" services, commands, global commands, Dockerfile configs, etc. So `ddev service get` didn't make any sense at that point.
