### ISSUE TITLE
Projects have bogus approot like '~/webdev/project` (with `~` in project root instead of using $HOME)

### ISSUE THREAD

**Issue by begrafx** [drud/ddev#3547]
I've encountered an issue which to me, makes very little sense. I'm not sure exactly how, but somehow, some of my DDEV projects have themselves showing a location of:

`~/WebDev/[project name]`

While others have themselves showing a location of: 

`/Volumes/[Volume Name]~/WebDev/[project name]` 

With the Volume Name being the default drive the machine boots from. 

To me, this should be no difference. As this is the primary drive, when I open terminal, it is already there, so I just have to `cd WebDev` and I'm where I need to be. The problem I'm finding is, if I move into any of the projects that are showing a location of `~/WebDev/[project name]` and I do a `ddev start`, everything is fine. If, on the other hand, I move into one of the projects that are showing a location of `/Volumes/[Volume Name]~/WebDev/[project name]`, I get ` 
Failed to start [Project Name]: project [Name] project root is already set to /Volumes/[Volume Name]/Users/brianeller/WebDev/[Project Name], refusing to change it to /Users/brianeller/WebDev/[Project Name]; you can `ddev stop --unlist [Project Name]` and start again if the listed project root is in error`

This makes no sense to me. They're both talking about the same place. But if I want to work with any of the `/Volumes...` projects instead of simply `cd WebDev` I have to `cd /Volumes/[Volume Name]/Users/brianeller/WebDev`then, if I `cd [project name]` it will start fine. As I look, and think about it, the only way I can figure that the variance would come about, would be because I have projects on both the internal primary volume, and also on an external volume. That in and of itself isn't an issue, but if I am working on something on the external volume,  and, I want to create a new project on the primary volume, I would follow the Quickstart steps, and I thought the issue came about where... if, from a folder on the external volume I go to start a new project on the primary volume, and I enter `mkdir /Volumes/[primary volume]...(entering all necessary information to make the new folder on the other volume)`and then `cd [into that new folder]` and create the project... but, as I think it through, this shouldn't be the case, because obviously, to do work in that new project, before I start the `ddev config...`command, I have to be in the desired folder, so the `ddev config...` command would be issued from the appropriate volume, so I'm stumped as to how I am getting these differing locations; but as I say, I'm more confused as to why DDEV considers it an issue, as either way, we're talking about the same place. 

I had considered using the `ddev stop --unlist [Project Name]` command, but in reading the docs I find:

`Or if you just don't want it to show up in ddev list any more, use ddev stop --unlist <projectname> to unlist it until the next time you ddev start or ddev config the project.`

Which doesn't appear to do anything to resolve the location issue. I had thought perhaps I needed to modify something in the `config.yaml` file, but I don't see any reference to the project location there. So the more I think about this, the more I am confusing myself, and the less sure I am as to what is best to do to resolve the issue. I'm sure that @rfay figured out the problem 3 paragraphs ago, so I'll submit this and respectfully await his wise direction.

**Comment by rfay** [comment]
I recommend that you just remove the offending projects from ~/.ddev/global_config.yaml.

I don't know how you got them that way, but you may find that you understand if you look at that file.

It will do no harm to just remove them and see what happens then.

**Comment by begrafx** [comment]
OK. As you're not suggesting it, would I be correct in thinking that it would be "bad" to attempt to 

`ddev poweroff`

and then edit the global_config.yaml file so that the currently different paths match the others?

**Comment by rfay** [comment]
I recommend just deleting the ones that are wrong from global_config.yaml, then they'll be recreated when you `ddev start` them.

**Comment by rfay** [comment]
I imagine you've got this sorted now by removing the bogus items from ~/.ddev/global_config.yaml, so closing.
