### ISSUE TITLE
`docker context` is used too much before the basic docker check is done

### ISSUE THREAD

**Issue by tyler36** [drud/ddev#3548]
**Run a Diagnostic and Paste Link Here**

**Describe the bug**
I'm running DDEV from WSL. After updating from `1.18.2` to `1.19.0-alpha3`, I get excessive warning.

```shell
ddev --version
WARN[0000] unable to run docker context inspect: exec: "docker": executable file not found in $PATH 
WARN[0000] unable to run docker context inspect: exec: "docker": executable file not found in $PATH 
WARN[0000] unable to run docker context inspect: exec: "docker": executable file not found in $PATH 
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
ddev version v1.19.0-alpha3
```

```shell
ddev xdebug on
WARN[0000] unable to run docker context inspect: exec: "docker": executable file not found in $PATH 
WARN[0000] unable to run docker context inspect: exec: "docker": executable file not found in $PATH 
WARN[0000] unable to run docker context inspect: exec: "docker": executable file not found in $PATH 
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
Enabled xdebug
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
```

- site appears to work fine otherwise; accessing & debugging both OK

**To Reproduce**

1. Update to latest version

```shell
brew unlink ddev && brew install drud/ddev-edge/ddev
```

2. Run basic command

```ddev
ddev --version
WARN[0000] unable to run docker context inspect: exec: "docker": executable file not found in $PATH 
WARN[0000] unable to run docker context inspect: exec: "docker": executable file not found in $PATH 
WARN[0000] unable to run docker context inspect: exec: "docker": executable file not found in $PATH 
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
ddev version v1.19.0-alpha3
```

**Expected behavior**

- Single warning

**Screenshots**

![image](https://user-images.githubusercontent.com/7234392/151091553-a37251c3-a000-4108-bcb0-01f4621d8432.png)

**Version and configuration information (please complete the following information):**

OS: WSL Ubuntu on Win10
DDEV: ddev version v1.19.0-alpha3
Docker Desktop:  4.4.4 (73704)

**Additional context**

**Comment by rfay** [comment]
Thanks for the feedback.

Looks like docker is not in your path? Or perhaps you have an old docker client that doesn't do `docker context` ?

**Comment by rfay** [comment]
I'm guessing maybe you don't have the docker client that comes with Docker Desktop, but maybe another one. Please show 
* `docker version`
* `docker context ls`

**Comment by tyler36** [comment]
That's strange. 

I did a full system restart and was getting the same error. Docker whale was stable but the error suggested a Docker problem. 

```shell
🕙 11:41:13  ❯ ddev start
WARN[0000] unable to run docker context inspect: exec: "docker": executable file not found in $PATH 
WARN[0000] unable to run docker context inspect: exec: "docker": executable file not found in $PATH 
WARN[0000] unable to run docker context inspect: exec: "docker": executable file not found in $PATH 
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
Could not connect to docker. Please ensure Docker is installed and running.
```

- So I restarted Docker again and it disappeared.

```
🕙 11:44:01  ❯ ddev start
Starting example-goo... 
Container ddev-ssh-agent  Recreate 
Container ddev-ssh-agent  Recreated 
```

From WSL:

```shell
docker version
Client: Docker Engine - Community
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:48 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by tyler36** [comment]
Nothing to do since a reboot/restart/restart "fixed" it. 

I thought it was something in the `alpha` since I know you've been working on detecting Docker in WSL. I had issue before with `1.18.2` and debugging from from WSL so that's why the update.

Thanks, as always, for the comprehensive debugging steps.

**Comment by rfay** [comment]
My bet is that you have more than one docker client on your WSL2 instance, and docker hadn't pushed theirs in there for some reason. Please exit docker and restart your WSL2 distro (so you will only have another docker client in there, not the one injected by Docker Desktop). 

Then take a look at the docker client you have and see where it came from.

Thanks for this! I think it's worth chasing.

**Comment by tyler36** [comment]
OK.

- Closed Docker-desktop
- Restart WSL

```shell
wsl --shutdown
```

- Open Ubuntu terminal
- Run diag commands

```shell
🕙 12:12:32  ❯ docker version

Command 'docker' not found, but can be installed with:

sudo apt install docker.io


🕙 12:12:36  ❯ docker info

Command 'docker' not found, but can be installed with:

sudo apt install docker.io


🕙 12:12:43  ❯ docker context ls

Command 'docker' not found, but can be installed with:

sudo apt install docker.io
```

**Comment by tyler36** [comment]
- Start Docker-desktop
 - Running same commands produces same output as above

```shell
🕙 12:15:58  ❯ docker version
Client: Docker Engine - Community
 Cloud integration: v1.0.22

...
```

**Comment by tyler36** [comment]
```shell
🕙 12:18:23  ❯ ls -l $(which docker)
lrwxrwxrwx 1 root root 48 Jan 26 12:15 /usr/bin/docker -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker
```

**Comment by rfay** [comment]
So it was telling you the truth originally I think, saying `docker not found in path` because Docker Desktop hasn't properly injected the client in there. 

Sure seems like we can make it be gentler about this. I think it's trying `docker context` before it tests to make sure docker is available maybe. 

Should be easy to demonstrate anytime docker is not in $PATH.

```
$ ddev --version
WARN[0000] unable to run docker context inspect: exec: "docker": executable file not found in $PATH
ddev version v1.19.0-alpha3-22-gf5698146-dirty
```


```
$ ddev start
WARN[0000] unable to run docker context inspect: exec: "docker": executable file not found in $PATH
WARN[0000] unable to run docker context inspect: exec: "docker": executable file not found in $PATH
WARN[0000] unable to run docker context inspect: exec: "docker": executable file not found in $PATH
WARN[0000] unable to run docker context inspect: exec: "docker": executable file not found in $PATH
WARN[0000] unable to run docker context inspect: exec: "docker": executable file not found in $PATH
WARN[0000] unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
unable to run docker context inspect: exec: "docker": executable file not found in $PATH
Could not connect to docker. Please ensure Docker is installed and running.
```

See the last part "Could not connect to docker" - that needs to happen before the `docker context` checks.

**Comment by rfay** [comment]
For your situation, of course, it was just that docker desktop had messed up pushing the docker client links into the distro.

**Comment by tyler36** [comment]
That sounds right. Would be a nice if we could reduce the "noise" for those (unfortunate) situations.

**Comment by shaal** [comment]
@rfay I see a similar error in Gitpod during prebuild (or imagebuild), In my case, I don't think it's related to ddev version
![image](https://user-images.githubusercontent.com/22901/152106254-62cefc1f-d1f8-4338-bfaa-70a388441b05.png)

Here's the latest custom docker image I use:
`FROM drupalpod/drupalpod-gitpod-base:20220202-optimized`

And it is generated through this setup:
https://github.com/shaal/DrupalPod/blob/optimized-docker-image/.gitpod/images/Dockerfile

**Comment by rfay** [comment]
You definitely need the docker client anywhere you are I'd think. And you don't currently have one in your $PATH. It's not able to find docker at all.

**Comment by travisbutterfield** [comment]
I just updated Docker Desktop to version 4.5.1. I'm using DDEV version 1.19.0-alpha3. I'm using WSL2. I have gotten this error recently, which prompted me to upgrade DDEV. I updated Docker Desktop today just to be on the latest, and after updating I'm consistently getting the "unable to run docker context inspect: exit status 1" error. DDEV seems to be working, but the docker command is not in my PATH now. Here's an example of what I'm seeing:
`ddev start cpop
WARN[0000] unable to run docker context inspect: exit status 1
WARN[0000] unable to run docker context inspect: exit status 1
WARN[0000] unable to run docker context inspect: exit status 1
WARN[0000] unable to run docker context inspect: exit status 1
WARN[0000] unable to run docker context inspect: exit status 1
WARN[0000] unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
Network ddev_default created
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
Starting cpop...
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
Container ddev-ssh-agent  Started
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
Pushed mkcert rootca certs to ddev-global-cache/mkcert
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
Network ddev-cpop_default  Created
Container ddev-cpop-dba  Started
Container ddev-cpop-web  Started
Container ddev-cpop-db  Started
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
Container ddev-router  Started
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
Ensuring write permissions for cpop
Existing settings.php file includes settings.ddev.php
Ensuring write permissions for cpop
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
Successfully started cpop
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
Project can be reached at https://cpop.ddev.site https://127.0.0.1:64778
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1
unable to run docker context inspect: exit status 1`

You can see that the container is working, but there's a lot of "noise" as was mentioned earlier. I'm not sure why docker isn't in my path anymore. Maybe something weird happened with the integration with WSL (as documented in the installation instruction step 8: "Go to Docker Desktop settings > Resources > WSL integration > enable integration for your distro (now docker commands will be available from within your WSL2 distro)."

**Comment by travisbutterfield** [comment]
As a follow-up, echoing the $PATH variable in WSL2 yields the following:
```
/home/travis/.volta/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/travis/.volta/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/Sennheiser/SoftphoneSDK/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Users/tbutterf/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/tbutterf/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin:/var/www/html/drupal_code_standards/vendor/bin
```

**Comment by travisbutterfield** [comment]
Also, strangely, when I run `echo $CAROOT` in WSL2, it returns nothing. So, that might be related somehow.

**Comment by rfay** [comment]
So @travisbutterfield when you start docker desktop, it injects the clients (docker, docker-compose) into WSL2. This is obviously one of the options in Docker Desktop, but I'm sure you have it set already. Mostly, when docker doesn't get injected, the solution is just to restart your WSL2 distro, restart the computer, or restart Docker Desktop. My bet is that any of the three will solve it. It's not an uncommon problem.

**Comment by travisbutterfield** [comment]
@rfay Weird. I had restarted all of those things a few times, but the problem persisted. But, I just restarted everything again, and now it's gone. I guess it's just intermittent. Oh well. Thanks for responding! :-)

**Comment by rfay** [comment]
It can be kind of cranky. You may want to try out the non-docker-desktop approach in https://ddev.readthedocs.io/en/latest/users/docker_installation/#windows-installation-wsl2-with-docker-linux-installed-inside and see how you like it. It's not as touchy as the Docker Desktop approach.
