### ISSUE TITLE
BC break – Drupal 9 & 10 config_sync_directory now unconditionally overridden by settings.ddev.php

### ISSUE THREAD

**Issue by leymannx** [drud/ddev#3549]
## Description

Trying out DDEV v1.19.0-alpha3 I noticed it comes with its own `settings.ddev.php` file for Drupal 9 & 10 now which has no condition anymore around `$settings['config_sync_directory'] = 'sites/default/files/sync';`.

* https://github.com/drud/ddev/tree/v1.19.0-alpha3/pkg/ddevapp/drupal/drupal9
* https://github.com/drud/ddev/tree/v1.19.0-alpha3/pkg/ddevapp/drupal/drupal10

In the `settings.php` file you normally define `$settings['config_sync_directory']` quite on top of the file. Best practice it so set it to a location outside the webroot, which is version tracked:
https://github.com/drud/ddev/blob/e54753a09c9f3f68c49383fe00a03805cdee4f75/pkg/ddevapp/drupal/drupal9/settings.php#L253-L264

Only quite on bottom of that `settings.php` file `settings.ddev.php` gets included:
https://github.com/drud/ddev/blob/e54753a09c9f3f68c49383fe00a03805cdee4f75/pkg/ddevapp/drupal/drupal9/settings.php#L759-L762

But this `settings.ddev.php` file now unconditionally overrides any prior `$settings['config_sync_directory']`:
https://github.com/drud/ddev/blob/e54753a09c9f3f68c49383fe00a03805cdee4f75/pkg/ddevapp/drupal/drupal9/settings.ddev.php#L42-L43

## Proposed resolution:

Similar to Drupal 8 let's wrap the `$settings['config_sync_directory']` line in the Drupal 9 `settings.ddev.php` to check if it has already been set: https://github.com/drud/ddev/blob/e54753a09c9f3f68c49383fe00a03805cdee4f75/pkg/ddevapp/drupal/drupal8/settings.ddev.php#L43-L55

**Comment by rfay** [comment]
Thanks, not sure how that happened.

Easy to do a PR if you want to...

Here's what it looked like in v1.18.2, https://github.com/drud/ddev/blob/0ee9cfb16ed1dd789f4648265849aaf899f4f6fa/pkg/ddevapp/drupal.go#L118-L136

**Comment by rfay** [comment]
I moved the settings.ddev.php 's to their own directory so they aren't embedded in go code, and must have messed up. But it means that PHP devs can now super easily contribute to improvements. Sorry to have messed it up.

**Comment by leymannx** [comment]
Cool, I'll create an PR now. My first contribution I think.

**Comment by jcnventura** [comment]
RTBC++. We have a lot of projects with existing settings.php files that rely on how it used to work, and those now break with DDEV 1.19-alpha3

**Comment by stewest** [comment]
This has returned

**Comment by rfay** [comment]
@stewest - I don't know of any changes in this area, but please don't make a cryptic comment in an old issue; open a new issue with full info and link to this one.  While you're there, please make sure that the `type` in your project is the `type` you want.
