### ISSUE TITLE
Feature request: translation system (and translations)

### ISSUE THREAD

**Issue by tyler36** [drud/ddev#3558]
**Is your feature request related to a problem? Please describe.**

I was thinking about the diversity of DDEV users that gave shout-outs in the [Discord Watercooler thread
](https://discord.com/channels/664580571770388500/919794291130388521/920492344447467531). And these are limited to those that use Discord and understood the English question.

How easy would it be to add translations to DDEV? 

**Describe the solution you'd like**

Primarily, I'm thinking
- [ ] error & warning messages
- [ ] `ddev describe` & `ddev status`
- [ ] maybe aliases for default commands

- This would be limited to ddev core only. 
- Translating the documentation is _outside the scope_.  

We would have a ddev-translation repo which anyone could add/edit.  We would have a special "debug" language, which would be an alias for "English" so everyone has a common interface for debugging on slack/discord.

**Describe alternatives you've considered**

**Additional context**

Having basic functionality in a Users preferred language might help increase usage especially with people who are not fluent or comfortable in English.

**Comment by rfay** [comment]
Wow, I've been avoiding that for years. 

Having maintained a multilingual website before, I know how hard it is to manage the translations and translator-contributors, and how difficult it is to maintain quality translations.

Still, it's a worthy ambition.

I've seen some golang techniques for string translation.

**Comment by tyler36** [comment]
I know. Juggling English & Japanese here. 

But, thinking out loud, it would be easier to "convert" co-workers. 

I wonder how long it take for someone to submit Elven, Klingon or Dothraki translations? 😄

**Comment by rfay** [comment]
This is a completely valid request, but I don't see it being attacked anytime soon, so I'm going to close this for now. "Me too" posts here are welcome to see if there is support for translations.

**Comment by Francewhoa** [comment]
I suggest https://weblate.org

For those not familiar with Weblate. It allows your community to easily do most of the translation. Weblate is "a libre software web-based continuous localization system, used by over 2500 libre projects and companies in more than 165 countries."

They offer a free self-hosted version at https://weblate.org/fr/download/

Or paid SaaS at https://weblate.org/fr/hosting/

Libre Source (Open Source) repository at https://github.com/WeblateOrg/weblate/

**Comment by tyler36** [comment]
Would be easier to add translation to the IDE (PHPStorm, VSCode) addon/extension?
