### ISSUE TITLE
Best way to handle multiple projects running simultaneously 

### ISSUE THREAD

**Issue by MisterH001** [drud/ddev#3559]
Firstly, thank you for such an amazing tool. I have been using it for 12 months and now I want to roll it out as part of my dev teams workflow.
I have a dedicated server (dedicated purely to ddev) and I was wondering what the best solution to running multiple sites/projects at the same time AND sharing all the URLs?
e.g. I have mydevsite1 & mydevsite2 & mydevsite 3 (etc!) all need to be worked on by multiple devs (along with client approval, QA etc) so they all need to have their own unique (and persistent) URLs.
I do have a top level domain that I can point all sub domains to the ddev server but I was wondering if this was a good idea?
Of course there is ngrok but there are limitations on the amount of online processes.

Any suggestions very welcome.
Thanks again!

**Comment by rfay** [comment]
Hi @MisterH001 - I don't recommend a separate server for most situations, because ddev is intended to be for local development. But it works fine. I run several live (small) production sites on a simple Linode VM, and the techniques in https://ddev.readthedocs.io/en/latest/users/alternate-uses/#casual-project-webhosting-on-the-internet-including-lets-encrypt will work for you. You may not need Let's Encrypt, but take a look at the basic idea.

**Comment by MisterH001** [comment]
Thanks Randy! Works flawlessly! :-) 
One last question, if I may, is there a way to view other services UIs such as mailhog, phpMyAdmin etc on a public URL?
Thanks again!

**Comment by rfay** [comment]
If you used `ddev config global --router-bind-all-interfaces` I think those should already be working for you.

**Comment by MisterH001** [comment]
Thanks Randy, I have used that but using the ports in the fdqn doesn't work.
e.g.: 
mailhog: mysite.com:8026
phpMyAdmin: mysite.com:3306 (or mysite.com:<ddev assigned port>)

Site can't be reached.
Many thanks

**Comment by rfay** [comment]
So what is the FQDN that you're using to access the main project? Let's say it's `proj1.myinternalsite.com`. So then you're using `https://proj1.myinternalsite.com` to access the proj1 site perhaps. So then `https://proj1.myinternalsite.com:8026` should work. `ddev describe` probably can't show you all the permutations. Of course it's up to you to set up DNS/hostnames to make the main hostname resolvable.

**Comment by rfay** [comment]
BTW, the database port isn't going to work out because it's not HTTP, therefore not proxy-able to ddev-router. You can likely directly use the ports with the `bind_all_interfaces: true` in .ddev/config.yaml, which will make all those direct-bound ports be exposed.

**Comment by MisterH001** [comment]
Thanks Randy
Correct I am using https://proj1.myinternalsite.com:8026 (etc) but no luck.
But I can now connect to MySQL (using SSH tunnel) via Heidi :-) 
Thanks

**Comment by rfay** [comment]
Sounds like you're making progress. You can use tools like `telnet proj1.myinternalsite.com 8026` and see if it connects. that will tell you if the port is actually listening, which it should be. 

Then you can use `curl` on it to see what's next if it's connecting.

`curl -I https://proj1.myinternalsite.com:8026/`

**Comment by rfay** [comment]
I guess you must have been successful, happy to continue the conversation here or elsewhere, but closing this for now.

**Comment by yanniboi** [comment]
For anyone else finding this issue, the new documentation lives here:

https://ddev.readthedocs.io/en/stable/users/topics/hosting/
