### ISSUE TITLE
Update WP-CLI v2.6.0

### ISSUE THREAD

**Issue by fschmittlein** [drud/ddev#3562]
Please update wp-cli to version 2.6.

https://make.wordpress.org/cli/2022/01/26/wp-cli-v2-6-0-release-notes/

**Comment by rfay** [comment]
Next alpha ddev v1.19.0-alpha4 will have wp-cli v2.6.0, and v1.19.0 will have that. You can easily add a post-update hook or .ddev/web-build/Dockerfile to update it with current, or you can `brew install --HEAD ddev` on mac/linux. Thank you so much for watching out for WP users!

I'm going to close this as it's taken care of, but happy to continue the conversation here are elsewhere.
