### ISSUE TITLE
xdebug override makes php & composer hang in the web container

### ISSUE THREAD

**Issue by sboden** [drud/ddev#3563]
Running ddev on Windows 10 with WSL2 (Ubuntu 20.04). With the default ddev installation composer works in the web container (after doing ddev ssh) but xdebug fails. When I override xdebug (as specified below), xdebug works but composer and php mysteriously hang. The problem is reproducible.

I installed ddev using homebrew as in the ddev documentation. "ddev version" output:

```
 ITEM            VALUE
 DDEV version    v1.18.2
 architecture    amd64
 db              drud/ddev-dbserver-mariadb-10.3:v1.18.2
 dba             phpmyadmin:5
 ddev-ssh-agent  drud/ddev-ssh-agent:v1.18.0
 docker          20.10.12
 docker-compose  v2.2.2
 mutagen         0.12.0
 os              linux
 router          drud/ddev-router:v1.18.2
 web             drud/ddev-webserver:v1.18.2
```

The xdebug override I put in a .ddev/php directory is as follows:

```
[PHP]
xdebug.mode=debug,develop
xdebug.client_host=192.168.100.33
xdebug.client_port=9000
xdebug.start_with_request=yes
xdebug.discover_client_host=1
```

where 192.168.100.33 is the IP address of the windows machine. With the file above in place, xdebug works but any php that you run inside of the web container just hangs.

**Comment by jonaseberle** [comment]
You mean xdebug does not stop at breakpoints by "xdebug fails"?

"Hanging" might indicate that the processes are waiting for you to continue or configure the breakpoint behaviour. That's expected if xdebug has been enabled.

How is your setup? Where is ddev, where is your IDE? Can you relate it to https://ddev.readthedocs.io/en/stable/users/step-debugging/ and if you have done the troubleshooting section there?

**Comment by sboden** [comment]
main OS is Windows 10, I installed ddev in the /home directory of a WSL2 Ubuntu 20.04. I also installed a native linux docker (without Docker Dekstop) in WSL. My IDE is phpstorm on windows itself (which since the last preview works using \\wsl$ to get to the files).

When I don't override xdebug, xdebug can't connect to phpstorm. Which is what I expected so I put the xdebug override in place  to have xdebug connect to phpstorm on windows. That works perfectly. But when I go then in to the web container (with ddev ssh) composer and php just hang when I run them.

Additionally, composer and php only hang with "ddev xdebug on", they work fine again with "ddev xdebug off" (but with the override in place). So it looks like composer and php are waiting at a (debug) breakpoint or so in the first case, but I phpstorm does not pop up at a breakpoint.

Edit: I found it. I had an obscure option in phpstorm activated specifying "Force break at first line when a script is outside the project". So since composer is not in my project it probably was waiting at a forced breakpoint. After switching that off, everything works ok.

**Comment by rfay** [comment]
Glad you got it sorted out! Didn't understand why you were overriding the xdebug config, which works out of the box most all the time. You don't have to do any xdebug config at all, no changes to php config. https://ddev.readthedocs.io/en/latest/users/step-debugging/
