### ISSUE TITLE
Un-ignore some local config.*.yaml files

### ISSUE THREAD

**Issue by jcnventura** [drud/ddev#3567]
We have a project template based on [drupal/recommended-project](https://github.com/drupal/recommended-project), that we use when creating a client project. This project template adds some DDEV, Tugboat, Drush and Drupal configuration files that we always use. One of the files that we decided to not include in this is a .ddev/config.yaml file, as this is added to the project via `ddev config` saving us the trouble of changing the values that DDEV already guesses so well.

The problem is that because we don't want to add the config.yaml file, we have to take advantage of the config.*.yaml feature to add extra config files (we currently have one to configure nvm and another that runs `drush deploy` on a post-import-db hook). However the same rule that is [used to load these files](https://github.com/drud/ddev/blob/cf31851d4ea41cf7b12ccc53dc3182614634b569/pkg/ddevapp/config.go#L290) is [used to .gitignore them](https://github.com/drud/ddev/blob/cf31851d4ea41cf7b12ccc53dc3182614634b569/pkg/ddevapp/config.go#L1048). We would like to add an exception to this .gitignore rule that 

**Describe the solution you'd like**
The suggestion is to add an extra .gitignore rule to allows files that are compliant with the config.*.yaml loading mechanism to be an exception to the existing .gitignore rule.
```
!/config.*.keep.y*ml
```
The above would allow files named config.drush.keep.yaml to be added to git during the normal project start-up process of `git add .ddev`.

**Describe alternatives you've considered**
The current solution we have is to document that these files must be forcefully added to git (`git add -f`), but experience shows that this is not always followed.

**Comment by rfay** [comment]
I would have thought that `git add -f .ddev/config.drush.keep.yaml` would work out OK for you.

I do consider the decision to gitignore these files to be suspect in general. Maybe `config.*.yaml` shouldn't be gitignored at all?

**Comment by jcnventura** [comment]
I agree that the ignore rule as it is makes little sense. But I also think that there should be a rule to add local changes without running the risk of them getting committed by mistake. So maybe a new rule to gitignore only all config.*.local.yaml ?

The problem of course is that such a change will suddenly flip how DDEV works, and a lot of files might get committed accidentally. This is the reason why I suggested the config.*.keep.yaml rule.

**Comment by jonaseberle** [comment]
In my opinion it is good as it is now.

If we make changes, let's please try to keep it fully backward-compatible. We've had quite some frustration after updates in the past with `.ddev/.gitignore` changes.
 
I like the suggestion by @jcnventura (with a slight change):
```
/config.*.y*ml
!/config.*.dist.y*ml
```
`dist` is used in [several](https://phpstan.org/config-reference#config-file) [tools](https://cs.symfony.com/doc/config.html) already to provide project-wide configuration, with possibilities to overwrite the settings for your current use case in another file.

**Comment by rfay** [comment]
I guess I think that git already provides exactly what's needed here with ``git add -f`, and we should just leave it the way it is. I appreciate the suggestion, but the more rules and "interesting" things we add, the harder everything is to understand, and often little things like this only end up benefiting one team (the one that understands it).

I'm going to close this, but appreciate the suggestion and am happy to continue the conversation here or elsewhere.
