### ISSUE TITLE
Configuring a blank project ready for new application install

### ISSUE THREAD

**Issue by MisterH001** [drud/ddev#3568]
Hi
I was wondering how it is possible to create a blank project ready for a particular application (in this case, Magento 2)

So I want to be able to install a brand new install of Magento 2, but in order to configure ddev with all required containers etc, it needs to have the file structure in place already (when running ddev config).

How can I get around this?

(currently I am having to copy over an existing Magento 2 .ddev folder (and editing it) to get this to work.)

Thank you!

**Comment by rfay** [comment]
Hi and welcome @MisterH001 - One thing you might want to do is to create a GitHub repository with your base project. Just do all the downloading of the basic thing and push it up. Then use that as a template. 

You can use `ddev config --project-type=magento2 --docroot=pub --create-docroot` and it will set up ddev regardless of whether you have magento2 already downloaded.

Do either of those ideas solve your question?

I imagine you already know about the Magento2 quickstart at https://ddev.readthedocs.io/en/latest/users/cli-usage/#magento-2-quickstart

**Comment by MisterH001** [comment]
Thanks Randy! That's perfect :-)

**Comment by rfay** [comment]
Glad it works for you :)
