### ISSUE TITLE
GraphicsMagick as strong default for TYPO3 based projects

### ISSUE THREAD

**Issue by josefglatz** [drud/ddev#3569]
**Is your feature request related to a problem? Please describe.**

The official guideline is the usage of GM instead of IM. For years we are prefer therefore GM instead of IM.

**Describe the solution you'd like**

Make GM also available per default like IM is

**Describe alternatives you've considered**

Actually it's necessary to always install GM manually

**Comment by rfay** [comment]
Could you please say more? Are you asking for Graphicsmagick to be installed by default? If so, please explain how to install it. How are you currently installing it? With `webimage_extra_packages` ? Is that a good-enough technique?

**Comment by josefglatz** [comment]
Hi @rfay . Yes exactly: `webimage_extra_packages: [ "graphicsmagick" ]`.

If it is no problem, that would be really cool for the whole TYPO3 community.
