### ISSUE TITLE
Provide better messaging if we can't connect to docker.sock

### ISSUE THREAD

**Issue by beeradb** [drud/ddev#357]
## What happened (or feature request):
If you have docker stopped and try to run a ddev command you end up with the following error message:

```The docker version currently installed does not meet ddev's requirements: Get http://unix.sock/version: dial unix /var/run/docker.sock: connect: no such file or directory```

## What you expected to happen:
This could be peoples first introduction to ddev. Seeing that message isn't ideal. It would be waaaay better if we had a nicer error message such as "Cannot connect to docker, are you sure it's running on the host?".

## How to reproduce it (as minimally and precisely as possible):
Stop docker. Run `ddev start`

**Comment by rfay** [comment]
I saw this just yesterday, so definitely agree. The connect is a completely different failure than the version check.

**Comment by rickmanelius** [comment]
Cool. I believe @tannerjfco mentioned he'd be willing to take this on. Added to the board.

**Comment by rickmanelius** [comment]
Looks like the PR was merged, so closing to clean up!
