### ISSUE TITLE
`ddev snapshot restore` should take either full name of snapshot or shortname

### ISSUE THREAD

**Issue by shaal** [drud/ddev#3570]
**Describe the bug**

I can no longer restore snapshots with the same name I used when I created them.

Previously, (up until ddev v.1.18), I could backup and restore snapshots with these commands:
Create new snapshot - `ddev snapshot -n name_of_snapshot`
Restore a snapshot - `ddev snapshot restore -n name_of_snapshot`

In ddev v1.19 alpha3, the snapshot's name has a new suffix, of the db-type and db-version:
e.g. `name_of_snapshot-mariadb_10.3.gz`

**To Reproduce**

Run these commands, in ddev v1.18 it works, but in ddev v1.19 that functionality is broken -
`ddev snapshot -n hello-world`
`ddev snapshot restore -n hello-world`

**Expected behavior**

Similar to version 1.18, I think users expect using the same name in snapshot backup and restore commands.

**Comment by rfay** [comment]
I agree this is some friction that should be removed.
