### ISSUE TITLE
Running "ddev config" with project type "drupal9" creates two "homeadditions" directories

### ISSUE THREAD

**Issue by joshsedl** [drud/ddev#3571]
I just ran "ddev config" in an empty folder with the following setup:
~~~
Creating a new ddev project config in the current directory (/home/josh/myprojects/test) 
Once completed, your configuration will be written to /home/josh/myprojects/test/.ddev/config.yaml
 
Project name (test):

The docroot is the directory from which your site is served.
This is a relative path from your project root at /home/josh/myprojects/test 
You may leave this value blank if your site files are in the project root
Docroot Location (current directory):
Found a php codebase at /home/josh/myprojects/test. 
Project Type [backdrop, drupal6, drupal7, drupal8, drupal9, laravel, magento, magento2, php, shopware6, typo3, wordpress] (php): drupal9
Ensuring write permissions for test 
No settings.php file exists, creating one
Existing settings.php file includes settings.ddev.php
Configuration complete. You may now run 'ddev start'.
~~~

After running "ddev start" I realised, that there are two seemingly identical "homeadditions" folder in the .ddev directory. One named ".homeadditions" and the other "homeadditions":

![Unbenannt](https://user-images.githubusercontent.com/37101709/152538849-53ec0c61-bddd-4f97-9e12-225f6bce69bf.PNG)

**Comment by rfay** [comment]
Hi @joshsedl - 

The one you're *supposed* to look at is called "homeadditions". The other one is ".homeadditions", (with a dot before it). On all operating systems besides Windows, you wouldn't see the second one by default, it's hidden. 

It's part of the implementation of homeadditions feature, stuff from the global homeadditions (homeadditions in the .ddev/homeadditions directory of your home directory) is copied into the project so it can be provided and merged as well.

Thanks for using ddev, and good eye! I'll close this, but happy to continue the conversation here or elsewhere.

**Comment by joshsedl** [comment]
Ah alright, thanks for the fast reply @rfay ! Appreciate it :)
