### ISSUE TITLE
Apple M1 with Headless Chrome fails

### ISSUE THREAD

**Issue by deepankerbhallaeffem** [drud/ddev#3578]
Hello All,

I have installed DDEV version v1.18.2 in Apple MacBook pro with M1 chip having macOS Big Sur with version 11.5.2.

But after installing and configuring with Docker version 4.4.2.

If I am entering the command to start the container i.e. "**ddev start**".

I am getting this error: **Failed to start mars: container failed to become healthy: err=container 'chrome' exited, please use 'ddev logs -s chrome' to find out why it failed** (attached screenshot for reference).

I have tried many things, but due to limited solutions on the internet still facing the same error. 

**Thus please help if anybody has seen the same problem.** 

<img width="1440" alt="Screenshot 2022-02-08 at 12 22 22 AM" src="https://user-images.githubusercontent.com/97514247/152852771-7196de10-a661-497e-bcf6-6d9ecc524557.png">

**Comment by rfay** [comment]
Hi @deepankerbhallaeffem - Headless Chrome is an add-on feature, and the one that was published for years doesn't work on Mac M1. 

You'll need to provide a link to the `docker-compose.chrome.yaml` that you're using. You'll want to see the current recipes in https://github.com/drud/ddev-contrib - note that https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/headless-chrome has in fact been updated to work with mac M1 (arm64).

**Comment by stborchert** [comment]
**Disclaimer**: This doesn't solve issues with the chromedriver itself but will show a different approach to get PHPUnit working (in case that's what you intend to do ;) ).

In our *config.yaml* we install *chromium* and *chromium-driver*:
```
webimage_extra_packages:
  - chromium
  - chromium-driver
```
Next thing is to have this in your *composer.json*:
```
    "require-dev": {
        "drupal/core-dev": "~9.3.0",
        "phpspec/prophecy-phpunit": "^2",
        "phpunit/phpunit": "^9.5",
        "weitzman/drupal-test-traits": "^1.5"
    },
```

The last step is to create a custom command in *.ddev/commands/web*.
*.ddev/commands/web/phpunit*:
```
#!/bin/bash

## Description: Runs phpunit tests
## Usage: phpunit
## Example: "ddev phpunit path/to/tests"
## Example: "ddev phpunit --testsuite=unit"

# Disable Xdebug to speed up test executions and to avoid debugger connection
# problems.
disable_xdebug

# Start ChromeDriver process.
nohup chromedriver --log-path=/var/www/html/tmp/chromedriver.log --port=9515 &> /dev/null &

# Run tests.
cd /var/www/html
phpunit --process-isolation $@
```

**Comment by stborchert** [comment]
Part of _phpunit.xml_:

```
  <php>
    <!-- Set error reporting to E_ALL. -->
    <ini name="error_reporting" value="32767"/>
    <!-- Do not limit the amount of memory tests take to run. -->
    <ini name="memory_limit" value="-1"/>
    <!-- Example SIMPLETEST_BASE_URL value: http://localhost -->
    <env name="SIMPLETEST_BASE_URL" value="http://<projectname>.ddev.site"/>
    <!-- Example SIMPLETEST_DB value: mysql://username:password@localhost/databasename#table_prefix -->
    <env name="SIMPLETEST_DB" value="sqlite://localhost//tmp/<projectname>.test.sqlite"/>
    <!-- Example BROWSERTEST_OUTPUT_DIRECTORY value: /path/to/webroot/sites/simpletest/browser_output -->
    <env name="BROWSERTEST_OUTPUT_DIRECTORY" value="./docroot/sites/simpletest/browser_output"/>
    <!-- To have browsertest output use an alternative base URL. For example if
     SIMPLETEST_BASE_URL is an internal DDEV URL, you can set this to the
     external DDev URL so you can follow the links directly.
    -->
    <env name="BROWSERTEST_OUTPUT_BASE_URL" value="http://<projectname>.ddev.site"/>
    <!-- To disable deprecation testing completely uncomment the next line. -->
    <!-- <env name="SYMFONY_DEPRECATIONS_HELPER" value="disabled"/> -->
    <!-- Example for changing the driver class for mink tests MINK_DRIVER_CLASS value: 'Drupal\FunctionalJavascriptTests\DrupalSelenium2Driver' -->
    <env name="MINK_DRIVER_CLASS" value=""/>
    <!-- Example for changing the driver args to mink tests MINK_DRIVER_ARGS value: '["http://127.0.0.1:8510"]' -->
    <env name="MINK_DRIVER_ARGS" value=""/>
    <!-- Example for changing the driver args to webdriver tests MINK_DRIVER_ARGS_WEBDRIVER value: '["chrome", { "chromeOptions": { "w3c": false } }, "http://localhost:4444/wd/hub"]' For using the Firefox browser, replace "chrome" with "firefox" -->
    <env name="MINK_DRIVER_ARGS_WEBDRIVER" value="[&quot;chrome&quot;, {&quot;browserName&quot;:&quot;chrome&quot;,&quot;chromeOptions&quot;:{&quot;args&quot;:[&quot;--disable-gpu&quot;,&quot;--disable-dev-shm-usage&quot;,&quot;--headless&quot;,&quot;--no-sandbox&quot;,&quot;--window-size=1920,1080&quot;]}}, &quot;http://localhost:9515&quot;]"/>
    <!-- Drupal Test Traits -->
    <env name="DTT_BASE_URL" value="http://<projectname>.ddev.site"/>
    <env name="DTT_API_URL" value="http://localhost:9222"/>
    <env name="DTT_MINK_DRIVER_ARGS" value="[&quot;chrome&quot;, {&quot;browserName&quot;:&quot;chrome&quot;,&quot;chromeOptions&quot;:{&quot;args&quot;:[&quot;--disable-gpu&quot;,&quot;--disable-dev-shm-usage&quot;,&quot;--headless&quot;,&quot;--no-sandbox&quot;,&quot;--window-size=1920,1080&quot;]}}, &quot;http://localhost:9515&quot;]"/>
    <!-- @todo This should not be necessary, but Drupal Test Traits currently throw a lot of deprecation warnings which make test jobs fail in CI. -->
    <env name="SYMFONY_DEPRECATIONS_HELPER" value="disabled"/>
  </php>
``` 

Replace all occurences of `<projectname>` with the actual name of your project.

**Comment by sbt2486** [comment]
The recommendation of @stborchert works for me too. However I had to add the option `--whitelisted-ips` in `chromeOptions` or it wouldn't work. I found this fix here: https://github.com/RobCherry/docker-chromedriver/issues/15

The complete line in my phpunit.xml looks as follows:

 ```
 <env name="MINK_DRIVER_ARGS_WEBDRIVER" value='["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--disable-dev-shm-usage","--headless","--no-sandbox","--window-size=1920,1080","--whitelisted-ips"]}}, "http://localhost:9515"]'/>
 ```

Before that option, chromedriver wouldn't start, here the error i found in chromedriver.log:

```
[1645694053.789][INFO]: Starting ChromeDriver 98.0.4758.80 (7f0488e8ba0d8e019187c6325a16c29d9b7f4989-refs/branch-heads/4758@{#972}) on port 9515
[1645694053.789][INFO]: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1645694053.791][SEVERE]: bind() failed: Cannot assign requested address (99)
[1645694053.791][INFO]: listen on IPv6 failed with error ERR_ADDRESS_INVALID

```

Btw. I also changed the ddev command slightly to get the chromedriver logfile working:

```
nohup chromedriver --log-path=/tmp/chromedriver.log --port=9515 &> /dev/null &
```

**Comment by rfay** [comment]
I'm going to close this for now, but we still have loads of general work to do on this project. 

- [ ] A new `ddev get` addon would be appropriate, and of course we need a solution that's general and works for bot.
- [ ] A solution that's generic for amd64 and arm64
- [ ] Updated recipes in ddev-contrib for things that still use chrome.

Would love it if those of you who are using headless chrome could step up and finish those up.

**Comment by smustgrave** [comment]
@stborchert could you provide the steps you did to get this working? I followed them but still can't get tests to run 

Updated my config.yml, added the composer packages, added the custom command, tried 100 combos for the phpunit.xml file but no luck.  Using a fresh download of ddev and drupal core 9.5.x

This is my composer.log if it's any help

[1654107368.305][INFO]: Starting ChromeDriver 102.0.5005.61 (0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}) on port 9223
[1654107368.307][INFO]: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1654107407.435][INFO]: [3e2578ee2e27c0e518601fa9782e4e9e] COMMAND InitSession {
   "desiredCapabilities": {
      "browserName": "chrome",
      "chromeOptions": {
         "args": [ "--disable-gpu", "--headless", "--whitelisted-ips" ]
      },
      "name": "Behat Test"
   }
}
[1654107407.436][INFO]: Populating Preferences file: {
   "alternate_error_pages": {
      "enabled": false
   },
   "autofill": {
      "enabled": false
   },
   "browser": {
      "check_default_browser": false
   },
   "distribution": {
      "import_bookmarks": false,
      "import_history": false,
      "import_search_engine": false,
      "make_chrome_default_for_user": false,
      "skip_first_run_ui": true
   },
   "dns_prefetching": {
      "enabled": false
   },
   "profile": {
      "content_settings": {
         "pattern_pairs": {
            "https://*,*": {
               "media-stream": {
                  "audio": "Default",
                  "video": "Default"
               }
            }
         }
      },
      "default_content_setting_values": {
         "geolocation": 1
      },
      "default_content_settings": {
         "geolocation": 1,
         "mouselock": 1,
         "notifications": 1,
         "popups": 1,
         "ppapi-broker": 1
      },
      "password_manager_enabled": false
   },
   "safebrowsing": {
      "enabled": false
   },
   "search": {
      "suggest_enabled": false
   },
   "translate": {
      "enabled": false
   }
}
[1654107407.436][INFO]: Populating Local State file: {
   "background_mode": {
      "enabled": false
   },
   "ssl": {
      "rev_checking": {
         "enabled": false
      }
   }
}
[1654107407.437][INFO]: Launching chrome: /usr/bin/chromium --allow-pre-commit-input --disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-gpu --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-automation --enable-blink-features=ShadowDOMV0 --enable-logging --headless --log-level=0 --no-first-run --no-service-autorun --password-store=basic --remote-debugging-port=0 --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.org.chromium.Chromium.cWQiba --whitelisted-ips data:,
[1654107407.492][INFO]: [3e2578ee2e27c0e518601fa9782e4e9e] RESPONSE InitSession ERROR unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by ethanteague** [comment]
Apologies for the non-value added comment, but this is still broken for me on M1. Followed all the steps / methods here, and tried several variations of said steps.

**Comment by rfay** [comment]
@ethanteague  Could you please try the new ddev add-on maintained by @weitzman ? https://github.com/drud/ddev-selenium-standalone-chrome

**Comment by ethanteague** [comment]
Well that was a fast reply! I did, and had nearly the same error trace, @rfay. Ty for your suggestion - the fact that I'm having an identical issue with @weitzman 's add-on tells me this is probably a me being dense problem.

**Comment by rfay** [comment]
Please open an issue there with your full details, thanks.
