### ISSUE TITLE
Update check (and ddev start) prints an error if the .ddev directory is not present

### ISSUE THREAD

**Issue by beeradb** [drud/ddev#358]
## What happened (or feature request):
When reviewing feedback from a new user I noticed the following printing in ddev output: 

`Could not perform update check: open /Users/user/.ddev/.update: no such file or directory`

This most likely doesn't happen to us because we already have a .ddev directory..

## What you expected to happen:
Update should either create the .ddev directory or fail silently if one does not exist.

## How to reproduce it (as minimally and precisely as possible):
1. Start an unbuntu container: `docker run ubuntu:16.04`
2. Download wget: `apt-get update` followed by `apt-get install wget -y`
3. wget the latest release of ddev: `wget https://github.com/drud/ddev/releases/download/v0.7/ddev_linux.v0.7.tar.gz` (as of writing this)
4. extract the archive: `tar -zxvf ddev_linux.v0.7.tar.gz`
5. Run ddev start on the extracted binary: `./ddev start`

And observe the following error message: `Could not perform update check: open /root/.ddev/.update: no such file or directory`

**Update: Since we now mount the db into ~/.ddev/sitename this also completely causes disaster with ddev, and sites can't start up successfully.**

**Comment by rfay** [comment]
When testing this, we should make sure to test on WIndows, as I've seen this routinely on windows.

**Comment by rickmanelius** [comment]
Good catch. I could imagine that failing silently is easiest, but then we might not actually get a prompt if someone's install is way out of date. Let's go with the approach of creating the directory.

**Comment by rickmanelius** [comment]
I believe @tannerjfco mentioned he might have time/capacity to take this on. Assigned over for now and added to the board.

**Comment by rfay** [comment]
Added an update: This is now fatal because the db container can't mount properly.
