### ISSUE TITLE
`ddev snapshot restore` doesn't work with postgres:9

### ISSUE THREAD

**Issue by rfay** [drud/ddev#3583]
Although `postgres:9` is supported and seems to work, `ddev snapshot restore` fails. If anybody has experience with `pg_basebackup` and can help study this it would be appreciated.

Options include:
* Fixing this
* Removing snapshot support for postgres:9
* Removing all support for postgres:9

**Comment by tyler36** [comment]
I am unable to create snapshots with the new postgres

Originally I tried on an existing postgres:10 project which I attempted to convert over to use the new integrated Postgres solution. The server was using the correct databse but I was getting an error: `failed to find a snapshot`.

I just created a new project from scratch, 

## Test

- Install Laravel

```shell
laravel new ddev-psql-demo
```

- Install DDEV, accepting defaults

```shell
ddev config
```

- Update DDEV to postgres

```shell
$ ddev config --database=postgres:14
Configuration complete. You may now run 'ddev start'.
```

- Start DDEV

```shell
$ ddev start
...
Project can be reached at https://ddev-psql-demo.ddev.site https://127.0.0.1:55915 
```

- Config Laravel to use database in `.env`

```env
DB_CONNECTION=pgsql
DB_HOST=ddev-ddev-psql-demo-db
DB_PORT=5432
DB_DATABASE=db
DB_USERNAME=db
DB_PASSWORD=db
```

- Run migration to confirm database is working

```shell
$ ddev artisan migrate
Migration table created successfully.
```

- Create backup

```shell
$ ddev snapshot --name=monkey
Creating database snapshot monkey-postgres_14.gz 
Created database snapshot monkey-postgres_14.gz 
```

- Confirm file is created: `./.ddev/db_snapshots/monkey-postgres_14.gz`
- Restore backup

```shell
$  ddev snapshot restore monkey
Failed to restore snapshot monkey for project ddev-psql-demo: failed to find a snapshot at /home/s-hendrix/code/playground/ddev-psql-demo/.ddev/db_snapshots/monkey
```

**Comment by tyler36** [comment]
So I got the error on `postgres:10` & `postgres:14`. 

You don't say what the original "error" with `postgres:9` is, but there might be another issue involved.

**Comment by rfay** [comment]
I think your problem is 
* https://github.com/drud/ddev/issues/3570

It's a user interface problem - For restore you have to use the full name of the snapshot. It needs to be improved.

**Comment by tyler36** [comment]
Thanks, I didn't see #3570.

`snapshot restore` works when using "full" filename:

```shell
$ ddev snapshot restore monkey-postgres_14.gz
Restored database snapshot monkey-postgres_14.gz
```

**Comment by rfay** [comment]
Also, don't forget that you can select a snapshot with just `ddev snapshot restore`. 

Would love to have you take a look at postgres:9 snapshot and restore. You can just create any old project with it, doesn't have to be a legit project.
