### ISSUE TITLE
Enable the `pg_trgm` extension for Postgres

### ISSUE THREAD

**Issue by rpkoller** [drud/ddev#3584]
When installing Drupal `9.3.5` with Postgres 14 in DDEV `1.19.0-alpha4` i get the following warning when running status report: 
![Bildschirmfoto 2022-02-08 um 17 44 01](https://user-images.githubusercontent.com/1665422/153034284-0dcb977e-0d8b-419b-94f1-94c3f3c993a0.png)
i am unaware if the `pg_trgm` extension would be an requirement for other cms'es as well for using Postgres but it would be convenient if that extension would be installed out of the box when setting up a project with DDEV for any cms requiring or recommend using it. In the context of Drupal it is recommended for Drupal 9 but will be a hard requirement for Drupal 10 according to the status report warning as well as the documentation page: https://www.drupal.org/docs/system-requirements/database-server-requirements 

@rfay asked about the installation process on dischord. it is simply the statement `CREATE EXTENSION pg_trgm` as described on the drupal docs page. just tried right now with adminer and it directly worked (never used postgres before nor installed any extension for it yet ;) ) 

But for consistency purpose would it make sense in case postgres is used to provide an option to set the to be installed extensions in the ddev config.yml file like for the `web-` and `dbimage` since for postgres another image is pulled? 
```
webimage_extra_packages: [php-yaml, php7.3-tidy]
dbimage_extra_packages: [telnet, netcat]
```

and on a side note.`create extension` is only supported on postgres 10-14, version 9.1-9.6 are not supported (just mention because the alpha 4 readme mentions issues with the snapshots on version 9.x so it looks like version 9 is supported as well by ddev) https://www.postgresql.org/docs/current/sql-createextension.html

**Comment by rfay** [comment]
If the technique is `CREATE EXTENSION pg_trgm` then that is not something that needs to be done by ddev does it? I would think that would be inappropriate for ddev to do... ? Seems like a Drupal user should just do that as required.

**Comment by rpkoller** [comment]
hm don't know. it is sort of cumbersome if you have first to remember that in case you install postgres that you also need to install that extension and then walk through the install. in my case i had to install adminer and then send the sql instruction through adminer to install. when i got more used to probably easier to achiev via the command line entirely even but i consider those essential build steps for an out of the box working environment important. and if you have to apply that step for each project you set up i consider that suboptimal tbh.

**Comment by rfay** [comment]
`ddev pgsql -c 'CREATE EXTENSION pg_trgm;'` seems like it would be a normal thing for Postgres users. Seems to me like part of database preparation.
