### ISSUE TITLE
How to install DDEV programmatically

### ISSUE THREAD

**Issue by nico-loeber** [drud/ddev#3585]
I would like to provide an automated way of installing and updating DDEV by clicking a button inside a Java application.
supported OS should be UNIX and Windows WSL (No native windows).

I tried using the install_ddev.sh script to do so, as this looks like the easiest way.
Sadly I get in trouble with the permission handling of this script.

To avoid any blocking password prompts I was executing the script with "wsl -d Ubuntu -u root bash -l install_ddev.sh".
I hoped this would solve the blocking issues as root is allowed to add the binary to /usr/local/bin and to execute mkcert.
I was a bit suprised that I got an error that I am not allowed to execute this script as root.

As I am developing on Windows 11 with WSL2 I didn't test the behavior in a Linux desktop environment yet. 
I hope sudo is configured with askpass there by default so a GUI password prompt is presented automatically.

I understand that this behavior is intended to enforce the user to confirm these actions with his password.
But I would be interested if anyone has an idea on how to install DDEV in a non interactive way, without security risks.
If the installer script was checked via a hash or something after download, I wouldn't be afraid to run it in WSL as root.

Any feedback is welcome.

**Comment by rfay** [comment]
Howdy - You can download the appropriate version of DDEV from any release and just place it in your $PATH; that works everywhere. And really, that's all that install_ddev.sh does, but it also gets mkcert and completion scripts. It could easily be updated to put ddev in a directory that does *not* require root for installation. You could even install a private ddev right in the PhpStorm space and use full path to get to it.

I do hope you'll support all PhpStorm environments though, Mac, Linux, Windows, WSL2.

**Comment by nico-loeber** [comment]
Thanks for your feedback, maybe bypassing the installer and directly downloading the binary is the right thing to do then.
I would like to make ddev also avaiable in PATH but maybe adding the binary location to path is the better solution in that case, than placing the binary in a a directory that is already in path.

> Installation or Upgrade - Windows (WSL2)[¶](https://ddev.readthedocs.io/en/stable/#installation-or-upgrade-windows-wsl2)
This is the recommended installation method for all Windows users that are on Windows 10 2004 or higher.

In case of a project that is not placed inside WSL I plan to show a notification suggesting to work in WSL with a reference to the docs instead of offering a DDEV installation in windows.
Using WSL2 the ddev executable installed in the selected WSL distro will be used and of course will be installed in there.
Mac, Linux, ... was meant with Unix and will be supported of course.

**Comment by rfay** [comment]
Closing this for now, happy to continue the conversation here or elsewhere.
