### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by alanmels** [drud/ddev#3591]
Per https://www.drupal.org/docs/system-requirements/php-requirements PHP 8.1 is recommended for Drupal 9.3.0. Unfortunately, setting it in the `config.yaml` and restarting my local ddev instance gave a notice PHP 8.1 is not supported, so I had to revert to PHP 8.0. Do you, guys, plan to roll out ddev with PHP 8.1 support soon?

**Comment by rfay** [comment]
PHP 8.1 is supported from ddev v1.18.2 forward. Please upgrade your ddev to current stable v1.18.2.

**Comment by alanmels** [comment]
Excellent. Thank you!
