### ISSUE TITLE
`ddev describe` should accept VIRTUAL_HOST environment variable

### ISSUE THREAD

**Issue by miromichalicka** [drud/ddev#3592]
**Describe the bug**
If you defne new service, you're able to define the URL for this service using VIRTUAL_HOST. However, [current code ](https://github.com/drud/ddev/blob/master/pkg/ddevapp/ddevapp.go#L329 ) is working with an assumption that the URL differs just by port number. 

**Expected behavior**
I would expect to see value from VIRTUAL_HOST combined with HTTP(S)_EXPOSE.

**Comment by rfay** [comment]
Can you please give a concrete example of what you'd like to see?

**Comment by miromichalicka** [comment]
Sure, I'll post it tomorrow also with a PR.

**Comment by rfay** [comment]
Why do you use a separate hostname for the frontend, instead of just using a different port?

**Comment by miromichalicka** [comment]
because we're actually running 10 of these frontend containers for single project, 80 projects, so it's looking slightly different in reality. Separate project is no-go for us for said reasons.

**Comment by rfay** [comment]
That's a great answer for not separating the front-end project, but most people just use a different port, not a different hostname, for the frontend. Most people probably use a nonstandard port for the backend and the default port for the frontend.

**Comment by rfay** [comment]
I don't have any objection to it. It will need docs and may need a test. I'm all in favor of your developers having improved DX!

**Comment by rfay** [comment]
No followup, will be interested in your PR, happy to continue the conversation here or elsewhere. 

You also may be interested in the new router, using traefik. https://ddev.readthedocs.io/en/latest/users/configuration/experimental/#traefik-router

I think it would allow you full flexibility to do anything you want. 

Closing for now.

**Comment by bhanu951** [comment]
@miromichalicka  were you able to achieve it ?
