### ISSUE TITLE
Merge `config.*.yaml` and `config.yaml environment variables and hooks

### ISSUE THREAD

**Issue by mikestreety** [drud/ddev#3598]
[Sorry for the vague title, I struggled to think of what to call it]

**Is your feature request related to a problem? Please describe.**

I am new to DDEV and am currently in the process of setting up some config files to share with my team.

We use TYPO3 set up with `.env` files but, as it is just the development environment (and for quick setup), I have committed the following to my `config.yaml`

```
web_environment:
- TYPO3_CONTEXT=Development/Local
- TYPO3_DB_HOST=db
- TYPO3_DB_USER=db
- TYPO3_DB_PASSWORD=db
- TYPO3_DB_NAME=db
```

The issue arose when I wanted to change the `TYPO3_CONTEXT` for my local install, without changing the committed file (for risk of accidental committing). Suggest [on Discord](https://discord.com/channels/664580571770388500/941661807855157258) was the creation of a `config.env.yaml` to override settings.

This worked, however I had to re-declare **all** of my variables.

**Describe the solution you'd like**

It would be great if you could just declare the variable you wish to overwrite

E.g.

```
web_environment:
- TYPO3_CONTEXT=Production
```

Rather than needing to reset the `DB` credentials again.

**Comment by jonaseberle** [comment]
We usually use `.env` files, too. And yes, we duplicate a lot of stuff (100 lines or more for all the cache/mail/... configurations) in them. I rather enjoy that it is so explicit.

If you want to do any kind merging of config, I suggest you do it in `AdditionalConfiguration.php`.

And for very simple sites where you only need 2 envs (local and live) the ddev-mechanism is sufficient: DB stuff is added by ddev to a ddev-managed `AdditionalConfiguration.php`.

**Comment by rfay** [comment]
Thanks for this issue. You're not the first one to hit it. I think there will be a variety of ways to do environment variables in the near future, so that may solve it as well.

**Comment by davereid** [comment]
We could definitely be using this on a company-wide project I'm working on that we're converting over from Lando. Would it be good if the environment variables were defined as an actual key/value format instead of the simple strings?

`.ddev/config.yml`
```yml
web_environment:
  MY_VARIABLE: value
```

`.ddev/config.local.yml`
```yml
web_environment:
  MY_VARIABLE: overridden value
```

**Comment by rfay** [comment]
> Would it be good if the environment variables were defined as an actual key/value format instead of the simple strings?

I'm pretty sure that the other format already works in yaml but I haven't tested it. I usually can remember VAR=value easier.

**Comment by torenware** [comment]
I don't think it matters. And there's a virtue to the current format: you can *unset* an environment variable by doing this in your list of string:

```yaml
web_environment:
- KEEP_THIS_ONE=newvalue
- LOSE_THIS_ONE=
```
You could not do this intuitively with a map of string.

**Comment by davereid-pfg** [comment]
I tried the key/value format and it failed due to YAML parsing when I tried to start ddev, so I don't think it is supported? I don't see why we couldn't "unset" a value the same way, by assigning it '~' or `null` as per https://stackoverflow.com/questions/34089496/empty-field-in-yaml.
