### ISSUE TITLE
Drupal 10 project support

### ISSUE THREAD

**Issue by lhridley** [drud/ddev#3599]
**Is your feature request related to a problem? Please describe.**

Executing `ddev config` does not give you an option to select a Drupal 10 project type.
**Describe the solution you'd like**

Add Drupal 10 as a project type option.

Note:  Drupal 10 requires a minimum PHP version of 8.1

**Comment by rfay** [comment]
Thanks for the issue! Drupal10 support has already been added, and is available in the current alpha releases.  You can use it already. However, there's not much different about it besides the php default. You may want to try https://github.com/drud/ddev/releases/tag/v1.19.0-alpha4
