### ISSUE TITLE
"Mutagen docker volume is not mounted" when mutagen not enabled but no_project_mount is set

### ISSUE THREAD

**Issue by kszymukowicz** [drud/ddev#3602]
hi

there is a project that uses non standard way of mounting
https://github.com/a-r-m-i-n/ddev-for-typo3-extensions

I tested on 1.18.2 and on 1.19.9 alpha4 and I get the same error wile starting this project. The error is:
`Mutagen docker volume is not mounted. Please use ddev restart`

- Host computer OS and Version: macOS Monterey M1
- Docker Desktop version: 4.3.2
- ddev version information:  1.18.2 and 1.19.9 alpha4 
- config.yaml contents for the misbehaving project: in https://github.com/a-r-m-i-n/ddev-for-typo3-extensions
- the gist with debug info: https://gist.github.com/kszymukowicz/1527a3b544ad184f67412274fbf489ac

**Comment by kszymukowicz** [comment]
Tnx for answer. 
Sry - I did not write that the same error is even if I disable mutagen.

**Comment by rfay** [comment]
Can you say what you're trying to accomplish by not using the standard mount point? I imagine you're going to be on your own with this.

**Comment by kszymukowicz** [comment]
I want to have ddev for TYPO3 extension - not TYPO3 project. 

The aim is to support developers with fast way to test extension changes in different TYPO3 versions (all TYPO3 in this ddev are symlinking to the same extension source).

This solution was working ok before ddev with mutagen.

**Comment by rfay** [comment]
Right, but why not use /var/www/html as the mount point? 

I imagine for this approach you would need to use `no_project_mount: true` in your config.yaml. Why don't you try that?

**Comment by kszymukowicz** [comment]
`no_project_mount: true` is used at https://github.com/a-r-m-i-n/ddev-for-typo3-extensions/blob/master/.ddev/config.yaml#L4

But let me try with mounting `/var/www/html`. I will come back in few hours or days :)
Thank you so far for helping.

**Comment by rfay** [comment]
I don't see how you can get that error unless mutagen is enabled either globally or locally:

https://github.com/drud/ddev/blob/f1c406eed3c9a9a447b370dd0165d5ccb0699ad6/pkg/ddevapp/ddevapp.go#L1059-L1072

**Comment by rfay** [comment]
Ah, I see it is a thing in IsMutagenEnabled() that affects your use-case:

https://github.com/drud/ddev/blob/a002ac32ef8b94983300ca20b572166e6c70ec40/pkg/ddevapp/mutagen.go#L486-L491

**Comment by rfay** [comment]
I was wrong about all that. I confused NoBindMounts with no_project_mount.

**Comment by rfay** [comment]
Could you please try a simple config that demonstrates the problem, just using no_project_mount? Despite my confusion above, I don't know how to get your error without mutagen enabled.

**Comment by kszymukowicz** [comment]
I removed `no_project_mount: true` and installed two versions of TYPO3 in one folder. The config now is much simpler and I am not going to use the solution from https://github.com/a-r-m-i-n/ddev-for-typo3-extensions.

For anyone who would like to see example solution of two or more TYPO3 in one ddev for extension testing please check https://github.com/sourcebroker/t3api/tree/release/2.0.0 and in future it will be in https://github.com/sourcebroker/t3api/tree/master.

Thanks for help @rfay

**Comment by rfay** [comment]
Glad it's working for you!
