### ISSUE TITLE
Recognise TablePlus from SetApp Subscriptions

### ISSUE THREAD

**Issue by riconeitzel** [drud/ddev#3606]
I'm using TablePlus via a setapp.com Subscription. The TablePlus binary is located here /Applications/Setapp/TablePlus.app instead.

That causes the `ddev tableplus` command to be not available on my machine.

Perhaps it would be nice to add an additional check for this subdirectory.

Thanks
Rico

**Comment by rfay** [comment]
FYI you can just edit the shell command in ~/.ddev/commands and remove the #ddev-generated line.

I definitely agree it that multiple paths should be possible.

**Comment by riconeitzel** [comment]
Hi @rfay

thanks for your hint. In ~/.ddev/commands/hosts/tableplus I removed the line you mentioned.
yet, it doesn't show up in the ddev command. 

Is there anything else I have to do?

It's not critical - I can setup the configuration my hosts manually, but it would be much more convenient, if this command would just work 😄

**Comment by riconeitzel** [comment]
Haha 😄 I just created a symlink - works fine as well 😂 could have thought of this a little earlier 🤦🏼‍♂️

```
ln -s /Applications/TablePlus.app /Applications/Setapp/TablePlus.app
```

**Comment by rfay** [comment]
I just created a PR for this. You can use the "tableplus" command from there, put it in ~/.ddev/commands/host, and remove the #ddev-generated line.  https://github.com/drud/ddev/blob/18595586b0e96b0caaff1711f2e2736552ded244/pkg/ddevapp/global_dotddev_assets/commands/host/tableplus

Artifacts are in https://github.com/drud/ddev/actions/runs/1859221888 if you want to manually test and review that PR, which would be wonderful.

**Comment by rfay** [comment]
Unfortunately, I don't think this can work as explained in https://github.com/drud/ddev/pull/3607#issuecomment-1047329825

But you can just copy /Applications/Setapp/TablePlus.app into /Applications

**Comment by luke3butler** [comment]
This solves the problem.
It also doesn't have any of the side-effects that come with copy/pasting the entire application, like losing the license or not updating automatically.

```
mkdir -p "/Applications/TablePlus.app/Contents/MacOS" && ln "/Applications/Setapp/TablePlus.app/Contents/MacOS/TablePlus" "/Applications/TablePlus.app/Contents/MacOS/TablePlus"
```
