### ISSUE TITLE
DDEV commands "import-db" and "export-db" should support bz2 and xz compressed dumps

### ISSUE THREAD

**Issue by bmack** [drud/ddev#3609]
We usually transfer our SQL files in "bzip2" or even "xz" these days, however importing them into DDEV Local only supports plain SQL and "gzip".

**Describe the solution you'd like**
It would be really cool, if DDEV Local should also detect "bz2" and "xz" file extensions.

**Describe alternatives you've considered**
I could do some bash piping, but that's just ugly :)

**Additional context**
I think the place for import-db is around here (but I'm no go expert) https://github.com/drud/ddev/blob/master/pkg/ddevapp/ddevapp.go#L466-L470

I'm willing to sponsor this feature (depends on the amount of work to be done of course) - just contact me with a quote, if you think this feature request is a good idea (I'm 100% OK if you think it's not needed).

**Comment by rfay** [comment]
The previous issue was
* https://github.com/drud/ddev/issues/1838

I would expect this to be a 4-8 hour project, not sure. It can't go into the v1.19.0 release I don't think, will have to focus on the things that have to get done for that. But it could go into a point release after that. You're welcome to sponsor it for however much you see fit on https://github.com/sponsors/rfay

**Comment by bmack** [comment]
Thanks for taking care of it. No rush for having it ready. The company I work for https://twitter.com/weareb13 took care of the financing. All set, if you need more info. let me know.

This change will save me roughly 1-2h per month! so this is going to be great, no matter when it's ready!

**Comment by rfay** [comment]
Saw that come through! Very generous. Amazed that it can save you that much time. Thanks for sponsoring, I know it will benefit others.

**Comment by scotthooker** [comment]
Question around this generally... If a DB, files archive etc... were in some wild format, required some wild preprocessing ( change of file perms, decrypted, maybe some removed, the DB archive needed _something_) is the intention pre-import-db hook has a wide enough scope that it can be done there?

**Comment by rfay** [comment]
@scotthooker Please use discord (https://discord.gg/hCZFfAMc5k) or one of the [other support venues](https://ddev.readthedocs.io/en/latest/#support-and-user-contributed-documentation) for new questions rather than hijacking existing issues. I haven't ever used pre-import-db for taking actions on the import itself; I would do that by preprocessing, like `gzip -dc db.sql.gz | awk '{do-something}' | ddev import-db` or something like that.

**Comment by rfay** [comment]
For anybody interested, testing request for PR in https://github.com/drud/ddev/pull/3721#issuecomment-1073274670
