### ISSUE TITLE
Recommended configuration for mounting a project into a custom docker service

### ISSUE THREAD

**Issue by justafish** [drud/ddev#3610]
When creating a new custom docker-compose based service I want to mount the project as a volume. Does following the example [here](https://github.com/drud/ddev-contrib/blob/master/docker-compose-services/old_php/.ddev/docker-compose.php.yaml#L17) mount the project it in the same way the web container does? e.g. fixes uid/guids, mutagen functionality etc

Thank you!

**Comment by rfay** [comment]
I hope taht was a good-enough answer @justafish - closing this for now, happy to continue the conversation here or elsewhere.
