### ISSUE TITLE
`disable_settings_management` is removed with `ddev config`

### ISSUE THREAD

**Issue by gilbertsoft** [drud/ddev#3613]
**Run a Diagnostic and Paste Link Here**

**Describe the bug**

If the configuration `disable_settings_management: false` is manually added to the `config.yaml` it gets removed when running `ddev config` afterwards.

**To Reproduce**

- add `disable_settings_management: false` to the `config.yaml`
- run `ddev config`

**Expected behavior**

`disable_settings_management: false` should not get removed.

**Screenshots**

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: WSL2 (Ubuntu)
- Docker Desktop version latest
- ddev version information 1.18.2

**Additional context**

**Comment by rfay** [comment]
Thanks!

**Comment by rfay** [comment]
@gilbertsoft I can't recreate this with current ddev. Could you please try with latest?

**Comment by gilbertsoft** [comment]
> @gilbertsoft I can't recreate this with current ddev. Could you please try with latest?

Found my mistake, just copied the example from the bottom which is `disable_settings_management: false` and that's the default and gets removed. But when I change it to `disable_settings_management: true` everything is fine.

Maybe we should change the example to `disable_settings_management: true`, false does not really make sense as it's the default.

**Comment by rfay** [comment]
Cool, thanks. 

Most of the examples in the bottom of the config.yaml show the default...

**Comment by gilbertsoft** [comment]
Yeah, if I would have read it carefully the mistake would not have happened at all. I guess this isn't the first time I'm struggling over this, but I'm fine anyway.

**Comment by rfay** [comment]
There are some awkward namings in there, and in global config as well.

**Comment by gilbertsoft** [comment]
Yes, prefixes like `disable_` do not really help. But just saw some optimizations regarding DBMS in 1.19 :)
