### ISSUE TITLE
stuck at Pushed mkcert rootca certs to ddev-global-cache/mkcert on M1 MBP

### ISSUE THREAD

**Issue by dextar47** [drud/ddev#3618]
When i try to start ddev with `ddev start` command then it gets stuck at this line `Pushed mkcert rootca certs to ddev-global-cache/mkcert` . I tried uninstalling mkcert and installing again, tried to uninstall and install again ddev as well but no luck so far.

**Comment by tyler36** [comment]
What version are you using?

```shell
ddev --version
```

**Comment by dextar47** [comment]
ddev version v1.18.2

**Comment by dextar47** [comment]
now its working miraculously. what i did, i waited long enough and thought lets see what happens. And finally its working

**Comment by tyler36** [comment]
Glad you got it working!

**Comment by rfay** [comment]
What happens with v1.18.2 is you have a big image to be pulled and it doesn't give enough info about what's going on, and you probably have slow internet. I think v1.19 has better feedback.
