### ISSUE TITLE
Remote Docker Instances are no longer supported

### ISSUE THREAD

**Issue by elmarputz** [drud/ddev#3619]
**Describe the Problem**

I'm trying to set up remote container support as described here: https://ddev.readthedocs.io/en/latest/users/docker_installation/#remote-docker-instances

My docker configuration works an is accessible. The first problem: the mentioned config value `ddev config global --no-bind-mounts` seems no to be available in my setup - it simply does not exist. Mutagen is  enabled globally and working. 
When starting the project, the container 'ddev-ssh-agent' is pulled and started on the remote system. 

But the the process fails with the following error:

`Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /MY_PROJECT_FOLDER/.ddev'`

Looking at the generated docker-compose files it shows, that ddev has added the configuration to the folder .ddev as a bind mount, which seems not to work with a remote container setup. 
Is there are way to get this to work or is this experimental feature no longer in active development?

**Version and configuration information (please complete the following information):**

Host OS: Mac OS 12.2
Docker Version: Docker Desktop 4.5.0
Dev version: 1.18.2

**Comment by rfay** [comment]
This only works in the latest alphas, please use v1.19.0-alpha5. When you use the docs that are "latest", you're using the ones that have latest code. When you use the docs that are "stable", you're using docs for most recent stable release. You won't find this in https://ddev.readthedocs.io/en/stable/

But I hope you'll try it out and give feedback!
