### ISSUE TITLE
Many messages about "Project level command overrides"

### ISSUE THREAD

**Issue by bserem** [drud/ddev#3628]
**Describe the Problem**
No troubles with DDEV, diagnostics run fine: https://gist.github.com/bserem/7ec29e276487a27ad723507834cae057

After working on #3518 where I had to run a second copy of ddev (custom compile) I get these messages when I am running the original version (1.18.2):
```
Project-level command 'mysql' is overriding the global 'mysql' command
Project-level command 'launch' is overriding the global 'launch' command
Project-level command 'xdebug' is overriding the global 'xdebug' command
```

Everything works fine, but my terminal just got crowded.

**To Reproduce**
Can't say much, I just executed the second version

**Screenshots**
![image](https://user-images.githubusercontent.com/520237/155618919-757414bc-9b06-4e8d-8a31-0df45f92cee3.png)

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: Linux Debian Testing
- ddev version information: 1.18.2
- config.yaml contents for the misbehaving project: affects all projects
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? No

**Comment by rfay** [comment]
This is a result of you using an old version of ddev after using the current HEAD. The current HEAD doesn't complain... and your old v1.18.2 recreates the in-project shell commands (and does complain).

**Comment by bserem** [comment]
Ok, so only way to fix it is to wait for the next version and update?

Thanks

**Comment by rfay** [comment]
All you have to do is remove those items from ~/.ddev/commands
