### ISSUE TITLE
Assumption about setting colors in output is not valid; doesn't work in cmd on windows

### ISSUE THREAD

**Issue by rfay** [drud/ddev#363]
## What happened (or feature request):

We have an assumption in our code that we can output control characters to change colors, and it's not really valid. 

<img width="526" alt="term_color" src="https://user-images.githubusercontent.com/112444/27710249-4417e1f0-5cdc-11e7-866a-1c59aa2100a7.PNG">

We probably have to adjust the places that we output control characters to respect the terminal capabilities of the current terminal. Alternately we could do it by operating system.

## What you expected to happen:

I don't expect to see raw control characters.

## How to reproduce it (as minimally and precisely as possible):

Do a `ddev list` against a running system on windows cmd.

## Related source links or issues:

**Comment by beeradb** [comment]
https://github.com/fatih/color is the package we use and it claims to have windows support. Fixing this may be as easy as updating the package.

Their examples are a bit different from our usage, though, so there may still be some adjustment needed.

**Comment by beeradb** [comment]
Just adding this: it looks like it was merged in February of this year, which is definitely after we added the package to vendor. https://github.com/fatih/color/pull/61

**Comment by rfay** [comment]
I may have been too fixated on ddev list - it appears to me that some other things are working. For example, the success after db import is greenish.

<img width="509" alt="colors" src="https://user-images.githubusercontent.com/112444/27998075-d084b1f2-64c2-11e7-9b85-e8467f6b7e29.PNG">

**Comment by rfay** [comment]
This is pretty ugly for our poor Windows users. Time to take a look at it. Moving it into the sprint for prioritization.

**Comment by rfay** [comment]
* Logrus issue: https://github.com/sirupsen/logrus/issues/496
* fatih/color supports windows, but you have to Fprintf(color.Output, ....), which breaks our integration with Logrus logging (for json) See "Windows is supported too" on https://github.com/fatih/color

**Comment by rfay** [comment]
Added to v0.18.0. Although there is apparently some support, it's my expectation that we'll have to just turn off colors to get suitable behavior in all windows "terminals".
