### ISSUE TITLE
Improve Laravel's explicit integration by actually updating the .env file

### ISSUE THREAD

**Issue by tyler36** [drud/ddev#3636]
**Is your feature request related to a problem? Please describe.**

DDEV does a good job of setting up itself and pre-configuring a Drupal project.
It would be nice if we could automate other frameworks too. 

**Describe the solution you'd like**
After running `ddev config` in a new Laravel project, there are 2 additional steps required.
- Updating PHP version. Addressed in #3588 
- Updaitng Laravel `.env` file

```diff
# These are the current defaults
APP_URL=http://localhost
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=laravel
DB_USERNAME=root
DB_PASSWORD=
```

Eg. Assuming I create  a new project call phpcs-demo 

## Test

- Start a new `Laravel` project

```shell
laravel new phpcs-demo
cd phpcs-demo
```

- Add `DDEV` to project, accepting all default

```shell
$ ddev config
...
Configuration complete. You may now run 'ddev start'.
```

- Bump DDEV `PHP` version in `./.ddev/config.yaml`

```yaml
php_version: "8.0"
```

- Config Laravel `.env`

```env
APP_URL=https://phpcs-demo.ddev.site
DB_CONNECTION=mysql
DB_HOST=ddev-phpcs-demo-db
DB_DATABASE=db
DB_USERNAME=db
DB_PASSWORD=db
```

This assumes a `mysql` database, but I _think_ all of these might be ddev variables already?
It would get great if a laravel-project type ddev config could automatically update the `.env` file too.

**Additional context**
Ideally, we would want to update other supported frameworks (WP, Magento) but I have no idea how involved those are. A Laravel feels like an easy win to start though.

**Comment by rfay** [comment]
Thanks for this!
I imagine you're queueing up a PR for this, but reading this issue it's not clear to me what you want to do.

**Comment by tyler36** [comment]
No PR on the way, more of a `TODO` placeholder

After running `ddev config` , if  the project type = 'laravel', ddev should update the `.env` file with its setting.

```diff
- APP_URL=http://localhost
+ APP_URL=<DDEV_PRIMARY_URL>
- DB_CONNECTION=mysql
+ DB_CONNECTION=<DDEV_DB_TYPE>
- DB_HOST=127.0.0.1
+ DB_HOST=<DDEV_DB_HOST>
- DB_PORT=3306
+ DB_PORT=<DDEV_DB_PORT>
- DB_DATABASE=laravel
+ DB_DATABASE=db
- DB_USERNAME=root
+ DB_USERNAME=db
- DB_PASSWORD=
+ DB_PASSWORD=db
```

Does GO have good filewriting support?

**Comment by rfay** [comment]
It's happy to write files, and ddev writes oh-so-many. This is the equivalent of what is done in settings.ddev.php.

I imagine there's a reason that I did this in Laravel instead of writing the .env directly, but I don't remember what it was:

https://github.com/drud/ddev/blob/8b38b9e7b53d7026ec2f44f5d01213c7dfb1b1ad/pkg/ddevapp/laravel.go#L22-L34

**Comment by tyler36** [comment]
On `1.19.0-alpha5`, is the database type and database port exposed to a host/web command script?

I have a script that adds the URL and "db" for database but I need to change the database driver/port based on the DDEV config.

I want to do something like:

```bash
...
        | sed  -E 's/DB_PORT=(.*)/DB_PORT=$DDEV_DB_PORT/g' \
        | sed  -E 's/DB_CONNECTION=(.*)/DB_CONNECTION=$DDEV_DB_TYPE/g' \
        | sed  -E 's/DB_(HOST|DATABASE|USERNAME|PASSWORD)=(.*)/DB_\1=db/g' \
```

**Comment by rfay** [comment]
I have a little custom command named "vars" that I use for checking these things:
```
$ cat vars
#!/bin/bash

set | grep DDEV
```

It should work fine on host or web (~/.ddev/commands/host or ~/.ddev/commands/web)

Here's what I see on host side:
```
DDEV_APPROOT=/Users/rfay/workspace/d9
DDEV_DBAIMAGE=phpmyadmin:5
DDEV_DBIMAGE=postgres:14
DDEV_DB_CONTAINER_COMMAND='-c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf'
DDEV_DEBUG=true
DDEV_DOCROOT=web
DDEV_FILES_DIR=/var/www/html/web/sites/default/files
DDEV_GID=20
DDEV_HOSTNAME=d9.ddev.site,mac
DDEV_HOST_DB_PORT=49712
DDEV_HOST_HTTPS_PORT=
DDEV_HOST_WEBSERVER_PORT=
DDEV_LIVE_NO_ANALYTICS=true
DDEV_MAILHOG_HTTPS_PORT=8026
DDEV_MAILHOG_PORT=8025
DDEV_PHPMYADMIN_HTTPS_PORT=8037
DDEV_PHPMYADMIN_PORT=8036
DDEV_PHP_VERSION=7.4
DDEV_PLATFORM_API_TOKEN=_gWx3fGS_qOkA3HJad4jA9ug56d6D7dctAkmv5WTEjU
DDEV_PRIMARY_URL=https://d9.ddev.site
DDEV_PROJECT=d9
DDEV_PROJECT_TYPE=drupal9
DDEV_ROUTER_HTTPS_PORT=443
DDEV_ROUTER_HTTP_PORT=80
DDEV_SITENAME=d9
DDEV_TLD=ddev.site
DDEV_UID=501
DDEV_WEBIMAGE=drud/ddev-webserver:20220227_change_path_environment
DDEV_WEBSERVER_TYPE=nginx-fpm
DDEV_XDEBUG_ENABLED=false
IS_DDEV_PROJECT=true
```

The docs on available env vars, which may not be perfect, are at https://ddev.readthedocs.io/en/latest/users/extend/custom-commands/#environment-variables-provided

**Comment by mandrasch** [comment]
+1 for this, cool idea :-)

Side note for interested readers: I tried to use something like this for APP_URL replace command

```bash
ddev exec 'echo ${DDEV_PRIMARY_URL} && cat .env.example | sed -E \\'\s\/APP_URL=(.*)\/APP_URL=${DDEV_PRIMARY_URL}\/g\\'\ > .env'
```
for the APP_URL, but couldn't get it to work yet because of the escaping of shell commands.  

```bash
ddev exec "echo ${DDEV_PRIMARY_URL}" # doesn't work, empty output
ddev exec 'echo ${DDEV_PRIMARY_URL}' # works
```

**Comment by tyler36** [comment]
@mandrasch  yeah, DDEV generate a `settings.php` for Drupal.

I think we should have a post-install hook, or maybe a custom command that writes back to the `.env`

**Comment by mandrasch** [comment]
> +1 for this, cool idea :-)
> 
> Side note for interested readers: I tried to use something like this for APP_URL replace command
> 
> ```shell
> ddev exec 'cat .env.example | sed -E \\'\s\/APP_URL=(.*)\/APP_URL=${DDEV_PRIMARY_URL}\/g\\'\ > .env'
> ```
> 
> for the APP_URL, but couldn't get it to work yet because of the escaping of shell/bash commands.
> 
> ```shell
> ddev exec "echo ${DDEV_PRIMARY_URL}" # doesn't work, empty output
> ddev exec 'echo ${DDEV_PRIMARY_URL}' # works
> ```

Side note, now I got it :-)

```
ddev exec 'sed -i "/APP_URL=/c APP_URL=$DDEV_PRIMARY_URL" .env'
```

**Comment by rfay** [comment]
Would love to have you do a PR @mandrasch !

**Comment by khalwat** [comment]
> I think we should have a post-install hook, or maybe a custom command that writes back to the .env

This is what we'd ideally like to have for our Craft CMS project type as well. A way to call a function in our integration that runs _after_ `ddev project create` so we can clean up the `.env` file.
