### ISSUE TITLE
Site can't connect to the database

### ISSUE THREAD

**Issue by cedewey** [drud/ddev#364]
## What happened (or feature request):
Ran ddev start on a project.
Navigated to local site
Received error- ddev web container: 500 or 501: Internal Server Error or Unimplemented

## How to reproduce it (as minimally and precisely as possible):
- Vanilla Drupal 8 install with a handful of contrib modules

## Anything else do we need to know:
The site was working before so I'm not sure why the issue now.

I've checked the settings.php file and it matches the db creds from ddev describe
user: db
db: db
pw: db
host: db
port: 3306

Here's the full print out of the errors

2017/06/29 21:35:06 [error] 18#18: *3 FastCGI sent in stderr: "PHP message: PDOException: SQLSTATE[HY000] [2002] Connection timed out in /var/www/html/docroot/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/html/docroot/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=db;p...', 'db', 'db', Array)
#1 /var/www/html/docroot/core/lib/Drupal/Core/Database/Database.php(376): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#2 /var/www/html/docroot/core/lib/Drupal/Core/Database/Database.php(166): Drupal\Core\Database\Database::openConnection('default', 'default')
#3 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#4 /var/www/html/docroot/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#5 /var/www/html/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#6 /var/www/ht" while reading response header from upstream, client: 172.18.0.5, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "drupal.ddev.local"
172.18.0.5 - - [29/Jun/2017:21:35:06 +0000] "GET / HTTP/1.1" 500 535 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0"

**Comment by rickmanelius** [comment]
Hey @cedewey. Since this is a new site, can you confirm that there was no settings.php in sites/default directory before you ran ddev start? This is something we may need to do a  better job of tracking/cleaning up.

**Comment by cedewey** [comment]
Yes, that's right. I downloaded Drupal from drupal.org and then ran through the install process as normal.

**Comment by beeradb** [comment]
@cedewey can you provide the contents of your `.ddev/config.yaml` file?

**Comment by rickmanelius** [comment]
Going to consider this closed at this point given that this spun into a convo in Slack that I believed got this to a completion point. Thanks, @cedewey!
