### ISSUE TITLE
ddev v1.19.0 test plan - community help requested!

### ISSUE THREAD

**Issue by rfay** [drud/ddev#3645]
It's testing time again here in the DDEV-Local factory. We love community help with every item that is interesting or relevant to you, and just *using* the release candidates is hugely helpful, because you may stumble across something in your regular workflow. Please use [ddev v1.19.0-rc2](https://github.com/drud/ddev/releases/tag/v1.19.0-rc2) or later for your testing (or `brew install --HEAD ddev`).

I don't think in general you'll have trouble using this in your daily workflow, so would love you do do that. You can switch back and forth , see [How can I install a specific version of DDEV in the FAQ](https://ddev.readthedocs.io/en/latest/users/faq/).

If you find a bug that you're pretty sure is a bug, then [[just open an issue for it](https://github.com/drud/ddev/issues/new?assignees=&labels=&template=Bug_report.md&title=)](https://github.com/drud/ddev/issues/new?assignees=&labels=&template=Bug_report.md&title=).

To give feedback or ask questions, please just reply on this issue or discuss in [[discord](https://discord.gg/hCZFfAMc5k)](https://discord.gg/hCZFfAMc5k) or another other support channel.

I am maintaining the [provisional release notes for v1.19.0](https://www.notion.so/v1-19-0-provisional-release-notes-9a05a76bcfc84a06b8f24bab2fd7ea19) and would love any comments on those.

1. `ddev debug dockercheck`
2. `ddev debug test`
3. $PATH change inside web container using homeadditions/.bashrc.d/path.sh ([docs](https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#altering-the-in-container-path))
4. `ddev exec` and custom web commands can behave much better in combination with quotes, see https://github.com/drud/ddev/issues/2547
5. `ddev get --list` and `ddev get --list --all`

6. `ddev get` now provides access to tested and supported services/recipes (see [docs](https://ddev.readthedocs.io/en/latest/users/extend/additional-services/)). Try each official recipe:
    1. `ddev get --list`
    2. `ddev get drud/ddev-beanstalkd`
    3. `ddev get drud/ddev-memcached`
    4. `ddev get drud/ddev-redis`
    5. `ddev get drud/ddev-drupal9-solr`
7. `ddev service enable` and `ddev service disable` swap `docker-compose.<service>.yaml` in and out of the .ddev directory. Test out.
8. Database configuration changes from `mariadb_version` and `mysql_version` to `database: mariadb:10.5` and `database: mysql:5.7` and `database: postgres: 14`. 
    1. Test several items in .ddev/config.yaml
    2. Test several items using `ddev config --database=postgres:13` for example
    3. Existing config.yaml usages of `mariadb_version` and `mysql_version` should still work.
9. Postgresql support: Use database type `postgres:9` through `postgres:14` and make sure it works where needed. (Snapshots not allowed on postgres:9)
    1. `ddev export-db`
    2. `ddev import-db`
    3. `ddev snapshot`
    4. `ddev snapshot restore`
    5. General usage.
10. macOS: Use ddev with Colima
11. windows WSL2: Use ddev with inside-wsl2 installation of docker and with Docker Desktop turned off. ([docs](https://ddev.readthedocs.io/en/latest/users/docker_installation/#windows-installation-wsl2-with-docker-linux-installed-inside)
12. Test with remote docker instance ([docs](https://ddev.readthedocs.io/en/latest/users/docker_installation/#remote-docker-instances)). You may want to try this with a VM running docker.
13. Bare in-container hostnames: You can (once again) use in-container hostnames like `db` or `solr` without having to use fully-qualified names like `ddev-<project>-db`.  Verify that ddev web container has no ambiguity even without `links`. See testing instructions in https://github.com/drud/ddev/pull/3403
14. Test improved WordPress setup per https://github.com/drud/ddev/pull/3468. See manual testing instructions there.
15. Gzipped database snapshots:
    1. Test snapshot and snapshot restore
    2. Test restoring an existing directory-based snapshot
16. `ddev start` now tests available disk space against an absolute value (5GB) rather than a percentage.  Test to make sure that it does flag low values. This can be done with artificially using space or by altering the value in nodeps/values.go (Also see https://github.com/drud/ddev/pull/3646)
17. Verify that graphicsmagick is installed in web container
18. Fresh Drupal 10 install should get PHP Version 8.1
19. Fresh Laravel install should get PHP Version 8.0
20. `ddev tableplus` should work for both mysql/mariadb and postgres projects
21. nodejs and nvm support
    1. Override nodejs version in .ddev/config.yaml
    2. Use `ddev nvm` to get any nodejs version.
22. Gitpod users should be able to use Xdebug, #3597
23. `ddev delete` should delete any volume named in any `docker-compose.*.yaml`
24. when mutagen_enabled, ddev now mounts upload_dir into container using regular docker bind-mount. 
25. Verify that segment/amplitude reporting is working adequately.
26. A new ddev project should be able to start up even if there’s no internet (assuming images have been downloaded already)
27. `ddev debug download-images` should download default images (maybe more???) and also get docker-compose and mutagen.
28. New `ddev php` command
29. New `ddev debug clean` command (WIP, not in v1.19.0-rc1)
30. Ability to use `ddev config global --no-bind-mounts` to not use docker bind mounts at all (for remote machines, where $DOCKER_HOST is used, etc.) Test with a remote machine.
31. docker-compose v1: Use `ddev config global --required-docker-compose-version=v1.29.2` and verify normal usage.
32. Casual Webhosting: Verify that casual webhosting feature is working OK.

**Comment by cmuench** [comment]
Just started to test Magento 2.4. My test project started without any issues and without any modification.

**Comment by rfay** [comment]
1. ✅ `ddev debug dockercheck` worked fine on WSL2. The first time I tried it I did see `Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 192.168.65.5:53: no such host` but I've seen that before on Docker Desktop (quite a lot) and it didn't repeat later.
2. ✅ `ddev debug test` worked fine (WSL2). The launch took a little longer than expected because I had the WSL2 set up to use X instead of launching on the Windows browser.
3.

**Comment by cmuench** [comment]
On my Arch Linux (amd64) machine.

:white_check_mark: ddev get drud/ddev-beanstalkd
:white_check_mark: ddev get drud/ddev-memcached
:x: ddev get drud/ddev-redis
:white_check_mark :ddev get drud/ddev-drupal9-solr

Redis service -> "No releases found for ddev-redis"

**Comment by rpkoller** [comment]
Tested on MacOS 10.13.6, Docker  2.4.0.0. and Mutagen activated.

1.  ✅ worked fine. excellent addition.
2. ✅ works fine. an indepth option checking the setup. love it. the only question i wonder. i've ran the command in the directory of an already running project. if i take a look at the `.ddev/config.yml` file there is no indication of the debug project that is recommended deleting. 
3. ❌ `.ddev/homeadditions/.bashrc.d/path.sh` with contents `export PATH=$PATH:/some/random/path` in my projects homeadditions like you did in your example @rfay but the file got removed on startup. not sure why it gets removed. the file had no #ddev-generated statement in it neither. there is also some odd behaviour with `.bash_aliases` as well i'Ve tried along the line
4. ✅ works. only the indefinte running of the command after successfully finishing the task remains but that seems something fringe on my installation somehow. 
5. ✅ works. one feedback about the current iteration. i wouldn't place the asterisk at the end of the description line. the user has to scan the whole description line figuring out if it is an official or community add on. the information has to be front loaded and the goal should be to have the important information within the first ~11 characters which equals roughly 2 words. therefor i still thing a dedicated third column would be worth to consider with either an empty cell or a cell containing an asterisk. and the column order asterisk, add-on and description.
6.   ❌ i can confirm that the redis release couldn't be found `No releases found for ddev-redis`
_**beanstalked:**_
```
ddev get drud/ddev-beanstalkd
Downloading https://api.github.com/repos/drud/ddev-beanstalkd/tarball/v1.1.1
v1.1.1_191959826.tar.gz 6.32 KiB / ? [-------------------------------------=------------------------------------------------------------------]  64.72% 0s
if [ "$(arch)" = "arm64" -o "$(arch)" = "aarch64" ]; then echo "This package does not work on arm64 machines"; exit 1; fi

Installed file /Users/danton/Sites/toolbartest/.ddev/docker-compose.beanstalkd.yaml
Downloaded add-on drud/ddev-beanstalkd, use `ddev restart` to enable.
For more information about this add-on visit the source repo at https://github.com/drud/ddev-beanstalkd 
```
the if statement shoulnd't be shown imho
**_solr:_** 
```
$> ddev get drud/ddev-drupal9-solr
Downloading https://api.github.com/repos/drud/ddev-drupal9-solr/tarball/v1.0.1
v1.0.1_1256256353.tar.gz 1.22 MiB / ? [----------------------------------------------------------------------------------=------------------] 12805.27% 0s
docker volume rm ddev-${DDEV_PROJECT}_solr 2>/dev/null || true

Installed file /Users/danton/Sites/toolbartest/.ddev/solr
Installed file /Users/danton/Sites/toolbartest/.ddev/docker-compose.solr.yaml
Executed post-install action chmod +x solr/docker-entrypoint-initdb.d/solr-configupdate.sh.
Downloaded add-on drud/ddev-drupal9-solr, use `ddev restart` to enable.
For more information about this add-on visit the source repo at https://github.com/drud/ddev-drupal9-solr
```
the docker volume rm line should also be hidden imho. and when restarting the project after `ddev get` ddev isnt that chatty anymore but now there is no progress indication anymore at all: 
```
beanstalkd Pulling
solr Pulling
memcached Pulling
beanstalkd Pulled
memcached Pulled
solr Pulled
```
so as a user you have no idea if the dl is stalled or not and if things still advance correctly. after installing and downloading all available images i've applied ddev get for memcached in another project and the image hasn't downloaded a second time. so no surprises and everything behaves as expected. 
7. ✅ works. only nitpick. without taking a look at the documentation i first tried `ddev service disable drud/ddev-memcached` then `ddev service disable ddev-memcached` and finally `ddev service disable memcached`. i would have expected ddev-memcached and memcached was kind of unexpected. would it be better to stay consistent with the naming maybe? 
8. 
9. ❌ tested with drupal installations.  it took forever until the `network...`line  showed:  
``` 
$> ddev start
Starting postgres...
Network ddev-postgres_default  Created
``` probably the postgres 12 container got downloaded for the first time. same for postgres9
     **Postgres 12**
          i. ✅ `ddev export-db --file=postgres12.sql.sz` worked
         ii. ❌ `ddev import-db --src=postgres12.sql.sz`, `ddev import-db --src=./postgres12.sql.sz` and i tried also `ddev import-db` with path `~/Sites/postgres/postgres12.sql.sz` but i always get `Failed to import database db for postgres: open : no such file or directory` but the file is there
         iii. ✅ `ddev snapshot` worked
         iv. ✅  `ddev snapshot restore postgres_20220302132857` worked
         v.  ✅  Manually installed drupal instead of using drush site install and everything went without any problem as well as after restoring a snapshot. only nitpick the `ddev pgsql -c 'CREATE EXTENSION pg_trgm;'` command you mentioned in another issue doesnt work since postgres 12 doesnt come with the pgsql command
     **Postgres 9** minimum requirement for drupal 9 is postgres 10 the
      **Postgres 10** 
          i. ✅ `ddev export-db --file=postgres10.sql.sz` worked
         ii. ❌ `ddev import-db --src=postgres10.sql.sz`, `ddev import-db --src=./postgres10.sql.sz` and i tried also `ddev import-db` with path `~/Sites/postgres/postgres10.sql.sz` but i always get `Failed to import database db for postgres: open : no such file or directory` but the file is there
         iii. ✅ `ddev snapshot` worked
         iv. ✅  `ddev snapshot restore postgres_20220302132857` worked  but the first time i got `Failed to restore snapshot postgres10_20220302141731 for project postgres10: failed to start project for RestoreSnapshot: web container failed to become ready: web container failed: log=, err=health check timed out: labels map[com.ddev.site-name:postgres10 com.docker.compose.service:web] timed out without becoming healthy, status=` probably too much load workwise for my computer that lead to the timing issue. retried the command then it worked properly
         v.  ✅  Manually installed drupal instead of using drush site install and everything went without any problem as well as after restoring a snapshot. only nitpick the `ddev pgsql -c 'CREATE EXTENSION pg_trgm;'` command you mentioned in another issue doesnt work since postgres 9 doesnt come with the pgsql command 
      **Postgres 11** 
              ❌ dont know why but somehow the postgres 11 project fails to become health `Failed to restart postgres11: web container failed to become ready: web container failed: log=, err=health check timed out: labels map[com.ddev.site-name:postgres11 com.docker.compose.service:web] timed out without becoming healthy, status=

**Comment by rfay** [comment]
@rpkoller thanks so much for your testing! It's going to be a little too messy to discuss these in the issue here, so could we discuss in Discord or slack (Already created thread in discord).  Some of the things are misunderstandings (the one about ddev import-db not finding file). Others like not becoming healthy definitely need discussion. I imagine they have to do with the timeout value and your ancient machine, but definitely need discussion. But this issue will die a horrible death if we chase those here. Better to confirm in another venue and open separate issues.

**Comment by shaal** [comment]
Testing in Gitpod (empty workspace-full environment, Docker version 20.10.12, build e91ed57, Ubuntu 20.04.4 LTS)
Installed ddev with `brew install --HEAD drud/ddev/ddev`

1. ✅ 
2. ✅

**Comment by h1nds1ght** [comment]
> 21. ❌  nodejs and nvm support - nvm doesn't seem to work right at all. The nvm version set doesn't persist even for a minute.
>     
>     1. I set `nodejs_version: 12` and `ddev restart` and `ddev exec node --version`: v12.22.10 (OK)
>     2. Use `ddev nvm` to get any nodejs version: `ddev nvm install 6` : This seems to work, but then when you `ddev ssh` it's back to the system version. And I see inside /usr/local/nvm an additional version of everything, /usr/local/nvm/d9-web.
>     3. ❌  I also happened to notice that ddev isn't populating the .ddev/web-build or .ddev/db-build directories with the expected README and examples. It seems these are (oddly) only populated during `ddev config`

Not sure how this new Option was finally implemented. I use a custom implementation for a longer time, which just sets the environment variable `NODE_VERSION` in config.yaml and uses a custom post-start script. In this post-start script I then run

```
curl -s -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
```

which on the other hand then again [reads](https://github.com/nvm-sh/nvm/blob/39d9a42c359df5dbf37c5000af8192f14a280b94/install.sh#L87)  `NODE_VERSION` and installs the desired node version on each restart.

**Comment by rfay** [comment]
@h1nds1ght I hope you'll test it and report your findings. If you don't like it a new issue or a discussion in Discord would be great. What it does is the regular install.sh for nvm, but the primary system node version is set with `nodejs_version`. Docs at https://ddev.readthedocs.io/en/latest/users/cli-usage/#nodejs-npm-nvm-and-yarn.

**Comment by h1nds1ght** [comment]
I tested it. For me it works perfect within its limits. I can change to node versions 12, 14, 16 and 17 and `ddev ssh` as well as `ddev exec` show me the most recent version of the according major version. 

This is much better than before, of course, but there also might be people still using deprecated versions like 8. You might say, they can use the new `ddev nvm`, but I thought it might be nice to set whatever node version you want in config.yaml, therefore I shared my approach with `NODE_VERSION`. But if that is for some reason no option just ignore my post...

**Comment by rfay** [comment]
Thanks - in that case you haven't tried nvm, which allows anything. Please try out `ddev nvm` or just nvm inside the container.

**Comment by awilhelm13** [comment]
K, I see because it writes to `/mnt/ddev-global-cache/nvm_dir/${DDEV_PROJECT}-web`, you can restart and the node version is stored, at least for `ddev ssh`, `ddev exec` keeps the global node version.

Therefore one has to use `ddev nvm` one time to change to another version than 12, 14, 16 and 17. Right?

And there is no way for you to implement that automatically to nodejs_version? I.e if node version is not within [12, 14, 16, 17] install the given version with nvm on ddev start?

**Comment by rfay** [comment]
I'm working on `ddev exec` recognizing the nvm version, that will be in rc2. Yes, you have to use `ddev nvm` if you want an unsupported node version. This works the same as on a server. Typically there's a "system" node version, installed with apt or whatever, and then nvm takes over if you need more. 

> And there is no way for you to implement that automatically to nodejs_version? I.e if node version is not within [12, 14, 16, 17] install the given version with nvm on ddev start?

The nodejs_version is implemented at image build time, before nvm can even exist. There's probably some way to do what you ask, but we'll see how this goes for now. I suspect that even just the config.yaml option will work great for lots of people, and then nvm users will probably be happy too.

**Comment by rpkoller** [comment]
Rerun of most of the steps with RC3 - Tested on MacOS 10.13.6, Docker  2.4.0.0. and Mutagen activated.

1.  ✅
2.  ✅ i would extend ddev is working output. You will want to delete this project with `ddev delete -Oy tryddevproject-22972` to something like `ddev is working. You will want to delete this project and associated docker files with "ddev delete -Oy tryddevproject-22972" and manually remove the source files with rm -r ~/tmp/ tryddevproject-22972` until https://github.com/drud/ddev/issues/3679 has landed. that way the user is informed that there is a new directory and php file created when running `ddev debug test`
3. ✅
4. ❌ `ddev . drush role-add-perm authenticated 'administer comment types' `returns `Too many arguments, expected arguments "command" "machine_name" "permissions". Failed to execute command drush role-add-perm authenticated administer comment types: exit status 1` while `ddev drush role-add-perm authenticated 'administer comment types'` works (without the hang repeatedly ironically). `ddev exec --raw mysql -e "SHOW DATABASES;"` and `ddev mysql -e "SHOW DATABASES;"`also works ( the examples from the comment of @rfay) BUT 
```
$> ddev . mysql -e "SHOW DATABASES;"
ERROR 1044 (42000): Access denied for user 'db'@'%' to database 'DATABASES'
Failed to execute command mysql -e SHOW DATABASES;: exit status 1
```
seems the `.` shortcut causes issues in the context of ddev exec and quotes 
6.

**Comment by rfay** [comment]
Calling this one good. Thanks to all of you for testing - it made a huge difference. Followups are welcome, of course. If you thing something should still be addressed, feel free to comment here or open a new issue.
