### ISSUE TITLE
ddev 1.19.0-rc1: docker-compose v1 usage fails due to use of `docker-compose convert`

### ISSUE THREAD

**Issue by susannemoog** [drud/ddev#3649]
## Run a Diagnostic and Paste Link Here

https://gist.github.com/susannemoog/bd00588d3c107b9d49da1f15186bae0d

## Describe the bug

When docker-compose v2 usage is not enabled, docker-compose convert is not available and all ddev starts fail.

## To Reproduce

- Disable docker-compose v2
- Try to start a project (or run ddev debug test)

## Expected behavior

- projects start ;) 

## Additional context

- see gist above

**Comment by rfay** [comment]
Thanks for this, easy to solve, so glad you hit it. Ongoing discussion about your remaining issue in discord. Thanks so much for all your great DDEV contributions!
