### ISSUE TITLE
Consider automatically adding the pg_trgm extension to DDEV Postgres projects

### ISSUE THREAD

**Issue by rpkoller** [drud/ddev#3653]
While testing the Postgres integration for DDEV 1.19.0-rc1 from a drupal perspective i ran into the following issue. The current version of Drupal (9.x) as well as all older versions of drupal supporting Postgres recommend the pg_trgm extension. From Drupal 10 on it is a required extension. It is possible to add the extension by simply writing `ddev psql -c 'CREATE EXTENSION pg_trgm;'` (thanks for the line @rfay) . But manually installing that extension for every project inherits the possibility of failure or simply to forget about the exact syntax. Question is, especially to the folks more savvy and used to Postgres, would it be a reasonable step, since from my understanding that extensions purpose is to improve the performance in the context of matching and searching, to add that extension per default to ddev postgres installations? or would adding that extension cause troubles for other CMSes and projects in any way?

**Comment by rfay** [comment]
I think this is a CMS-specific request that Postgres users will be able to deal with themselves, and this hasn't gotten any traction yet. Happy to reopen if others stumble on this.

**Comment by rfay** [comment]
See 
* https://github.com/drud/ddev/issues/3653
