### ISSUE TITLE
`ddev delete` needs to clean up ddev-global-cache sections

### ISSUE THREAD

**Issue by rfay** [drud/ddev#3666]
`ddev delete` doesn't currently clean up things in ddev-global-cache volume that pertain to individual projects. For example, subdirectories of nvm_dir, bash_history, mysqlhistory.

**Comment by hanoii** [comment]
removing the volume with `docker volume rm ddev-global-cache` wipes the global cache volume. You will lose composer cache and other global ones.

**Comment by hanoii** [comment]
Is `ddev delete` the same as `ddev stop --remove-data` and if not, shouldn't `ddev stop --remove-data` remove this project specific global cache?

**Comment by rfay** [comment]
Yes, `ddev delete` is the same as `ddev stop --remove-data` and the code that should be updated here is the same code used by both. `ddev stop --remove-data` was an older way to do this.
