### ISSUE TITLE
Installation with install_ddev.ssh is failing

### ISSUE THREAD

**Issue by justafish** [drud/ddev#3686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
❯ curl -LO https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh && bash install_ddev.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6837  100  6837    0     0  36174      0 --:--:-- --:--:-- --:--:-- 36174
curl: (22) The requested URL returned error: 404 
Failed downloading https://github.com/drud/ddev/releases/download/v1.19.0/ddev_linux-amd64.v1.19.0.tar.gz
```

### Expected Behavior

ddev installs per the installation instructions

**Comment by rfay** [comment]
Hi @justafish - The v1.19.0 release is building right now. It will be available within a few hours anyway.

If you need anything at all in the meantime, you can use `install_ddev.sh <version>`, for example `install_ddev.sh v1.19.0-rc4`

Thanks!

**Comment by justafish** [comment]
Ok - thank you! :pray:
