### ISSUE TITLE
After upgrading to 1.19.0: "Unable to get docker context"

### ISSUE THREAD

**Issue by svewap** [drud/ddev#3694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

Unable to execute ddev command

### Current Behavior

ddev command returns:
FATA[0000] Unable to get docker context: unable to run 'docker context inspect' - please make sure docker client is in path and up-to-date: exit status 125 

### Expected Behavior

ddev command is executable

### Anything else?

The problem is, that the `docker context` command is **only available as root user**.
ddev is installed with homebrew with my user.

`docker info`
> Containers: 42
 Running: 0
 Paused: 0
 Stopped: 42
Images: 352
Server Version: 20.10.12-ce
Storage Driver: btrfs
 Build Version: Btrfs v5.16.1 
 Library Version: 102
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: io.containerd.runtime.v1.linux oci runc io.containerd.runc.v2
Default Runtime: runc
Init Binary: docker-init
containerd version: 9cc61520f4cd876b86e77edfeb88fbcd536d1f9d
runc version: v1.1.0-0-g605c1cb1cc0c
init version: 
Security Options:
 apparmor
 seccomp
  Profile: default
 cgroupns
Kernel Version: 5.16.11-1-default
Operating System: openSUSE Tumbleweed
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.17GiB
Name: lupus.wappler.systems
ID: Z352:EUCS:N3WY:DMM5:RYTJ:BEZJ:K6PA:2LMU:A42E:2OC3:TDGU:U3WV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by rfay** [comment]
Hmm, ddev does not yet support rootless docker, see feature request in 
* https://github.com/drud/ddev/issues/2899

But experiment with this using just the docker command, `docker context ls` for example.

I know of no reason `docker context` would be unavailable without root privs, see if you can sort that out by looking at docker plugins. 

Anyway, see if you can find out why `docker context` isn't working. See if there's a `context` plugin in ~/.docker that maybe has the wrong privs.

**Comment by svewap** [comment]
Thank you for your support. The solution was: I had installed a docker version with homebrew and this was incompatible with the running docker daemon. I don't know why it was installed :-D
Regarding the non-root version: I think I need to revise that. Therefore, I have taken that out of my original post again ;-)

**Comment by rfay** [comment]
Glad it's working for you!

**Comment by Stargate-project** [comment]
I installed a docker  extention but now I am getting a error ...

`
FATA[0000] Unable to get docker context: unable to run 'docker context inspect' - please make sure docker client is in path and up-to-date: exit status 1 

`

**Comment by rfay** [comment]
Hi @Stargate-project - You're best to open a new issue, or come for help to [discord](https://discord.gg/hCZFfAMc5k), but you have broken Docker I guess. You can `docker context ls` to see what's happening. And `docker version` should show you some things. But if you had opened a new issue with the results of `ddev debug test` I wouldn't have to ask you these things.

**Comment by t-franz** [comment]
I solved it by (re)installing [Docker Desktop](https://www.docker.com/products/docker-desktop/)

**Comment by rfay** [comment]
@t-franz you had an (ancient?) docker client that didn't have the `docker context inspect` command, I would imagine. Installing Docker Desktop is one way to get it but you can easily get it by updating docker client any other way.
