### ISSUE TITLE
1.19.0: Assignment of container stdout to a variable doesn't work (stdout/stderr issues)

### ISSUE THREAD

**Issue by julienloizelet** [drud/ddev#3698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

I am using some custom commands and I assign the result of such a command in a variable (in some other bash script or even in other ddev command) : 

`MY_VARIABLE=$(ddev my-custom-command)`

The current result is an empty variable.

### Expected Behavior

Before 1.19.0, the variable was well assigned.

### Steps To Reproduce

As I guess my real custom commands won't be useful, I tested with the following:

- Create a custom command `.ddev/commands/web/web-command-test`

```
#!/usr/bin/env bash

## Description: TEST
## Usage: web-command-test value
## Example: "ddev web-command-test hello"

echo "$@"
exit 0
```

This command just returns a value that you pass as a parameter:

- Launch `ddev start`

- Then, in your terminal, run : 

```
export MY_VALUE=$(ddev web-command-test hello)

```
With 1.18.2 : nothing is displayed on the terminal; 
With 1.19.0: "hello" is displayed

- Then: 

```
echo ${MY_VALUE}

```
With 1.18.2 : "hello" is displayed on the terminal (this is the expected behavior)
With 1.19.0: a blank line is displayed

**Comment by jonaseberle** [comment]
Related: https://github.com/drud/ddev/pull/3689

**Comment by rfay** [comment]
Yes, thanks for the issue, there's an odd problem with stdout support in docker-compose v2.2.3, we're working on this in 
* https://github.com/drud/ddev/pull/3689
