### ISSUE TITLE
ComposeCmd fails to run on `ddev start`

### ISSUE THREAD

**Issue by michaelchadwick** [drud/ddev#3705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/michaelchadwick/00e78e2c5bd022b6c6fde8a5bc819a52

### Current Behavior

Trying to start a ddev project (Drupal 9) on macOS Monterey that I've used for years (both on Monterey and previous macOS releases), but getting an unexpected error now.

`failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c chmod 600 ~mchadwick/.pgpass ~mchadwick/.my.cnf]: exit code: 1`

I have other Drupal 9 ddev projects that are nearly identical (they use the same `.webimageBuild/Dockerfile` even!) that start up fine, but this one does not. The `.pgpass` and `.my.cnf` files must be created dynamically, because they don't seem to exist in the ddev project file system.

This issue seems to have only started happening in the latest 1.19.0 version.

### Expected Behavior

Drupal 9 project successfully starts and a URL is created that I can go to in a browser.

### Steps To Reproduce

1. macOS 12.2.1, ddev v1.19.0
2. cd /ddev/project/root
3. `ddev start`

### Anything else?

[ddev-muzcom-log.txt](https://github.com/drud/ddev/files/8256340/ddev-muzcom-log.txt)

**Comment by rfay** [comment]
Hi @michaelchadwick - thanks for taking the time to do the diagnostic and for providing the build failure log. Obviously with `ddev debug test` the dummy project there works fine.

It looks like the user inside the container isn't getting built right. In this case, it's apparently confused between user "www" and user "mchadwick". The bottom line is that user "mchadwick" is not getting built, and instead user "www" is getting built. So ~mchadwick/.pgpass doesn't exist. 

```
#7 [drud/ddev-dbserver-mariadb-10.3:v1.19.0-muzcom-web-built 2/2] RUN (groupadd --gid 20 "www" || groupadd "www" || true) && (useradd  -l -m -s "/bin/bash" --gid "www" --comment '' --uid 503 "www" || useradd  -l -m -s "/bin/bash" --gid "www" --comment '' "www" || useradd  -l -m -s "/bin/bash" --gid "20" --comment '' "www")
#7 sha256:68a48a319f4b3eb2944ec8be6219f4556b6ffb54af249a5144f4060d65451794
#7 CACHED
```

Do you have any idea where user "www" (typically uid 33) comes from here? I imagine this is some kind of bug with the build process.  You're not using sudo anywhere are you?

If you could provide these things for a recreation scenario it would help me a lot. The easiest thing is to do this as a gist on gist.github.com, but I'd take them however I can get them.

* contents of `.ddev/.webimageBuild/Dockerfile`
* contents of `.ddev/.ddev-docker-compose-full.yaml`
* .ddev/config.yaml (just the part that's not comments)
* Your custom Dockerfile of course.

You might consider just tarring up the .ddev directory if that's allowable.

BTW, for debugging you can use `cd .ddev && ~/.ddev/bin/docker-compose -f .ddev-docker-compose-full.yaml build --no-cache --progress=plain`. With that and some extra `RUN echo` statements you may be able to figure out what's up.

**Comment by rfay** [comment]
I should have asked you, why did you title this "ComposeCmd fails to run on `ddev start`"? 

What is ComposeCmd? How does it factor in here?

**Comment by michaelchadwick** [comment]
@rfay Your analysis was spot on. I had a `docker-compose.override.yaml` file that I was using to force a username of `www`, and as soon as I deleted that override file, the project came right up.

I've had those override files for a while, and they were not causing this issue, so I don't know _why_ this does not work now.

Regardless, thank you for the help!

P.S. I titled this "ComposeCmd..." because that was in the error message (the full one attached to this issue), and it stuck out to me.

**Comment by rfay** [comment]
Great, glad you got it sorted! Closing, happy to continue the conversation here or elsewhere.

The reason it suddenly fails is that in v1.19 ddev tries to create (and set perms on) the .my.cnf and .pgpass in a different way, so that made it all confused about what user was what.

**Comment by jimafisk** [comment]
I was getting this error when trying to import a database:

```
failed to import database: composeCmd failed to run 'COMPOSE_PROJECT_NAME=
```

I was initially doing `ddev import-db < mydb.sql.gz` which was throwing this error ❌ 

Then I switched to `ddev import-db --file=mydb.sql.gz` and that worked without error ✅

**Comment by rfay** [comment]
Hi @jimafisk - `ddev import-db -h` will show you several examples of how you can do it. For more detail, see 
* the doc https://ddev.readthedocs.io/en/stable/users/usage/commands/#import-db
* The database management section (with imports), https://ddev.readthedocs.io/en/stable/users/usage/database-management/
