### ISSUE TITLE
ddev snapshot --all fails if any projects are stopped

### ISSUE THREAD

**Issue by FLeudts** [drud/ddev#3707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/FLeudts/51c1c7ab6d0051c1939d1305b2cd3507 

### Current Behavior

If I run the ddev snapshot --help command it tells me that ddev snapshot --all should only snapshot running projects. It still tries to snapshot a stopped project and then fails because the db container is stopped. 

### Expected Behavior

ddev snapshot --all should ignore stopped projects or the description should be edited. 

### Steps To Reproduce

1. Have two or more projects
2. Stop the first project in ddev list and start the others
3. Execute ddev snapshot --all
4. No snapshots will be created

**Comment by rfay** [comment]
Thanks, I can recreate that. It used to work!

**Comment by mikebarkas** [comment]
I will work on this.
