### ISSUE TITLE
Remove single quote in help of export-db

### ISSUE THREAD

**Issue by froemken** [drud/ddev#3710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ddev export-db -h

results in

```
...
Examples:
ddev export-db --file=/tmp/db.sql.gz'
ddev export-db -f /tmp/db.sql.gz
...
```

### Expected Behavior

ddev export-db -h

should result in

```
...
Examples:
ddev export-db --file=/tmp/db.sql.gz
ddev export-db -f /tmp/db.sql.gz
...
```

### Steps To Reproduce

Just execute following command:

`ddev export-db -h`

**Comment by rfay** [comment]
Thanks for this! PR is welcome, would have probably been easier than writing the issue. But regardless, THANKS!
