### ISSUE TITLE
Session variables wrong values with nginx-fpm

### ISSUE THREAD

**Issue by elmarputz** [drud/ddev#3714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/elmarputz/2cdd52420dce6c4ec4397bc7bb0df4c7

### Current Behavior

Running this code in PHP always increments the variable "$test"  by 2 instead of 1 on each page reload.
This only happens if i use the webserver "nginx-fpm", with "apache-fpm" the increment value is correctly one! 

```
<?php 

session_start();
$test = $_SESSION['myvar'] ?? 0;
$test++;
$_SESSION['myvar'] = $test; 
echo $test;
?>
```

### Expected Behavior

The value of "test" should only increment by 1 on each reload of the page!

### Steps To Reproduce

1. OSX 12.2.3, Docker Desktop 4.6
2. DDEV config webserver "nginx-fpm" 
3. Code 
```
<?php 

session_start();
$test = $_SESSION['myvar'] ?? 0;
$test++;
$_SESSION['myvar'] = $test; 
echo $test;
?>
```
4. Result: variable "$test" increments by 2 instead of 1

**Comment by rfay** [comment]
I imagine that your php script is executing twice? 

Nothing you're showing here has anything to do with nginx, so it's pretty odd! 

I think you'll want to do some more intermediate prints to see what's going on. Also... just use xdebug and step through to try to understand.

**Comment by rfay** [comment]
It's also possible that this is an actual nginx or php-fpm bug...

Have you tried various versions of php?

Could you make a demo repository that shows the behavior?

**Comment by rfay** [comment]
No response from OP, so closing, but happy to continue the conversation here or elsewhere when you get back to this.
