### ISSUE TITLE
Allow `omit_containers[db]` globally

### ISSUE THREAD

**Issue by plexmaniax** [drud/ddev#3718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Some co-worker likes to work with one central database (nativ or dockerized) other likes the ddev-way.
At the moment we have to version this in the project and so everyone has to go the same way.

### Describe the solution you'd like

It would be nice if we could omit db container in config_global.yaml instead of doing it in each project. 
So every co-worker could decide on his own, which database way he prefered. 

### Describe alternatives you've considered

Allow omit_containers: [dba,db] in global_config.yaml

**Comment by rfay** [comment]
This would break so many projects for unexplainable reasons, I don't think it makes sense. Even when a developer doesn't want the db container on some projects, they almost always want it on *some* project.

**Comment by rfay** [comment]
I guess I'm open to a PR, but won't prioritize development for it. I know you understand that everybody wants things to fit their exact workflow, but optimizing for everybody is a little different from optimizing for each individual developer.

**Comment by rfay** [comment]
For most people, having a db container running (even if it isn't used) doesn't do any harm at all, and doesn't use much in the way of resources. Why is it important not to run the db container?

**Comment by rfay** [comment]
If it's the settings that are the issue, the developer may want to override those instead?

**Comment by plexmaniax** [comment]
If the frontend overwrites the settings in a gitlab project, he has to be sure, that he doesn't push his changes into the repo. 

I thought it wouldn't be a big deal to enable this property. But I understand if you won't do it.

**Comment by rfay** [comment]
Oh, we forgot something really important. Your developer can create a `config.nodb.yaml` with 
```yaml
omit_containers: [db]
```

It's gitignored by default, so won't get checked in.

**Comment by plexmaniax** [comment]
We could deal with this, but it has to be done for every project or did I get it wrong?
A global config would be very convinient, so every developer could choose his default config and no one has to change any project related config.

Please don't misunderstand me, your project is great and a helpful wrapper and makes things so easy for us.
It's just an idea :)

**Comment by rfay** [comment]
I'm just explaining to you that your developer doesn't have to worry about committing the config.yaml if you use this technique. It's their preference, so can just add config.nodb.yaml when working on a project instead of editing config.yaml

**Comment by plexmaniax** [comment]
Hi @rfay  

I tried your workaround with config.nodb.yaml, it works on project level. 

Could you please think about it, to give us the opportunity to handle this in global_config.yaml?
It would ne nice to have some docker instances globally, like database or mailhog and some with your automatic workflow.

**Comment by rfay** [comment]
I think overall adding omit_containers[db] globally would create way too much confusion, so closing.
