### ISSUE TITLE
Error response from daemon: invalid mount config for type "bind": stat /run/desktop/mnt/host/c/Users/rober/<ProjectName>: input/output error

### ISSUE THREAD

**Issue by RobertoZeppilli** [drud/ddev#3719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We set up Docker and ddev for running a Magento project faster.  Sorry if I will not explain so well but it's the first time for me facing these problems. But all I can say is that yesterday I was able to run **ddev start** and enter in **ddev ssh** to install the composer dependencies. 
The install of composer failed, so I thought tomorrow I will try again.
That tomorrow is today, and today I cannot run **ddev start** anymore. I don't know why.
I will leave you all the screenshots of the errors of yesterday and the error of today.

Notes: 
1. Yesterday, after failing in composer install, I switched to composer 2
2. the project that i cloned from Bitbucket is located in C:\Users\me\<ProjectName> and not in a dedicated folder like C:\Users\me\work\<ProjectName>
3. My php version is 7.4.1
4. My OS is windows
5. I've used Ubuntu to install ddev 
6. Docker is using WSL2

Again, I'm sorry if I'm not providing any other info, but I want to ask you anyway if you can help me understand what's happening, and why yesterday ddev was working and now it doesn't

### Expected Behavior

I want **composer** to install all the dependencies and make **ddev start** work again

### Anything else?

This is the result of composer install yesterday
![composer v-2 error](https://user-images.githubusercontent.com/78091609/159119298-4e983f4b-02e9-4577-bc43-bb98b7e13a17.jpg)

![page](https://user-images.githubusercontent.com/78091609/159119299-46c93d2a-22e2-4415-b7dc-a346c6dfcb4b.jpg)

![composer v-1 error](https://user-images.githubusercontent.com/78091609/159119300-d6dbc85c-4777-4e75-9c9b-8eca5de813a4.jpg)

This is today error, ddev start returns this one
![errore oggi](https://user-images.githubusercontent.com/78091609/159119301-50244377-86cc-4ab4-a165-e96a3ea39a2f.jpg)

**Comment by rfay** [comment]
Hi there, sorry for the trouble.

First, I strongly recommend using WSL2 for anybody on Windows, because it's perhaps 100 times faster. WSL2 is the [recommended install for ddev on windows](https://ddev.readthedocs.io/en/latest/#windows-wsl2)
Second, magento (2? I assume) has so many files that it's even more important to do it with WSL2, 

Now, for your trouble, please start with the General Troubleshooting Strategies in https://ddev.readthedocs.io/en/latest/users/troubleshooting/#general-troubleshooting-strategies - that will mean restarting docker, rebooting your machine, trying a trivial installation, etc.

If you had run the requested diagnostic with `ddev debug test` I'd be able to give a bit more info, but I'm flying in the dark now.

I would consider doing a Docker Factory Reset, knowing that you'll lose any databases you may have had in any projects.

**Comment by RobertoZeppilli** [comment]
Hi rfay, thanks for the response. 
As you said i ran **ddev debug test** and this down here is the result.
Seems like is failed, then I delete the project as you can see. 
For what concerns the troubleshooting guide, I did **ddev poweroff** to no success.

PS C:\Users\rober\cialdemania2> ddev debug test
Running C:\Program Files\Git\bin\bash.exe [-c /c/Users/rober/AppData/Local/Temp/test_ddev.sh] 
OS Information: MINGW64_NT-10.0-19044 DESKTOP-MV46M22 3.1.7-340.x86_64 2020-10-23 13:08 UTC x86_64 Msys
User information: uid=197609(rober) gid=197609 groups=197609
DDEV version:  ITEM             VALUE
 DDEV version     v1.19.0
 architecture     amd64
 db               drud/ddev-dbserver-mariadb-10.3:v1.19.0 
 dba              phpmyadmin:5
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.19.0
 docker           20.10.13
 docker type      Docker Desktop For Windows
 docker-compose   v2.2.3
 docker-platform  docker-desktop
 mutagen          0.12.0
 os               windows
 router           drud/ddev-router:v1.19.0
 web              drud/ddev-webserver:v1.19.0-1
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
mutagen-enabled=false
nfs-mount-enabled=false
router-bind-all-interfaces=false
internet-detection-timeout-ms=750
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
auto-restart-containers=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=
use-docker-compose-from-path=false
no-bind-mounts=false

======= DOCKER info =========
docker location: -rwxr-xr-x 1 rober 197609 1359 mar 17 15:29 '/c/Program Files/Docker/Docker/resources/bin/docker'
Docker Desktop Version: Docker Desktop for Windows 4.6.0.75818

======= Mutagen Info =========
======= Docker Info =========
Docker platform: docker-desktop 
Using docker context: default (npipe:////./pipe/docker_engine) 
docker-compose: v2.2.3
Using DOCKER_HOST=npipe:////./pipe/docker_engine
Docker version: 20.10.13
Able to run simple container that mounts a volume. 
Able to use internet inside container. 
Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                 251.0G      5.8G    232.3G   2% /

Container ddev-cialdemania-dba  Removed 
Container ddev-cialdemania-elasticsearch  Removed 
Container ddev-cialdemania-db  Removed
Network ddev-cialdemania_default  Removed 
Project cialdemania has been stopped. 
The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again. 
Existing docker containers: 
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
Creating a new ddev project config in the current directory (C:\Users\rober\tmp\tryddevproject-22804) 
Once completed, your configuration will be written to C:\Users\rober\tmp\tryddevproject-22804\.ddev\config.yaml
 
Found a php codebase at C:\Users\rober\tmp\tryddevproject-22804
Project type has no settings paths configured, so not creating settings file. 
Configuration complete. You may now run 'ddev start'. 
Network ddev_default created 
Starting tryddevproject-22804... 
Container ddev-ssh-agent  Started 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
Pushed mkcert rootca certs to ddev-global-cache/mkcert 
v1.19.0: Pulling from drud/ddev-dbserver-mariadb-10.3
08c01a0ec47e: Pulling fs layer
a2bcb14c13a1: Pulling fs layer
29c56760f879: Pulling fs layer
a95000a218fc: Pulling fs layer
a765d76e68d9: Pull complete
c6945738f085: Pull complete
62787b7c58c5: Pull complete
09068eced0b6: Pull complete
9cf18bfce121: Pull complete
8e703ab2dfb1: Pull complete
7cdbba010e4a: Pull complete
8472da579791: Pull complete
2e31f9c9813b: Pull complete
a5b92ef65f18: Pull complete
5001690ac471: Pull complete
71bfbb2f368f: Pull complete
9c11af3d9fbc: Pull complete
4667e4d26cbc: Pull complete
00306e7008e0: Pull complete
417f4d31e78d: Pull complete
a946433908f3: Pull complete
1c3722fa18f0: Pull complete
8648276b01e6: Pull complete
89fd7cc64713: Pull complete
8f3e88c84b0a: Pull complete
Digest: sha256:82c48e725468eda3fb6e6747ef3671cb9e4bc12d33525e76b463e701f9d37c7d
Status: Downloaded newer image for drud/ddev-dbserver-mariadb-10.3:v1.19.0
docker.io/drud/ddev-dbserver-mariadb-10.3:v1.19.0
The hostname tryddevproject-22804.ddev.site is not currently resolvable, trying to add it to the hosts file 
ddev needs to add an entry to your hostfile.
It will require administrative privileges via the sudo command, so you may be required
to enter your password for sudo. ddev is about to issue the command:
    sudo C:\Program Files\DDEV\ddev.exe hostname tryddevproject-22804.ddev.site 127.0.0.1 
Please enter your password if prompted.
Running   Command=sudo C:\Program Files\DDEV\ddev.exe hostname tryddevproject-22804.ddev.site 127.0.0.1
Network ddev-tryddevproject-22804_default  Created 
Error response from daemon: invalid mount config for type "bind": stat /run/desktop/mnt/host/c/Users/rober/tmp/tryddevproject-22804: input/output error 
Failed to start tryddevproject-22804: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-tryddevproject-22804 docker-compose -f C:\Users\rober\tmp\tryddevproject-22804\.ddev\.ddev-docker-compose-full.yaml up --build -d', action='[up --build -d]', err='exit status 1', stdout='#2 [drud/ddev-dbserver-mariadb-10.3:v1.19.0-tryddevproject-22804-built internal] 
load build definition from Dockerfile
#2 sha256:fcc720435038ec54bcccf45fbbab21aefa79342dc2d4d64ef150e3270d8ce2ee
#2 transferring dockerfile: 408B done
#2 DONE 0.0s

#1 [drud/ddev-webserver:v1.19.0-1-tryddevproject-22804-built internal] load build definition from Dockerfile
#1 sha256:a068fcaf528732659ca7b3b7fd64dee77f0089715f56c20362fa945197d34adf
#1 transferring dockerfile: 577B done
#1 DONE 0.0s

#4 [drud/ddev-dbserver-mariadb-10.3:v1.19.0-tryddevproject-22804-built internal] load .dockerignore
#4 sha256:5d6aca35b97229c6abfb75a78e65c254cbcc2d8fd4c7d19816a4d1af8d697a2e
#4 transferring context: 2B done
#4 DONE 0.0s

#3 [drud/ddev-webserver:v1.19.0-1-tryddevproject-22804-built internal] load .dockerignore
#3 sha256:42a2df7449b0f582eb0418aa7db891dc898dd041badfe13755ebf573c1d3a857
#3 transferring context: 2B done
#3 DONE 0.0s

#5 [drud/ddev-webserver:v1.19.0-1-tryddevproject-22804-built internal] load metadata for docker.io/drud/ddev-webserver:v1.19.0-1
#5 sha256:2b4fd8bbf2356a765bd6395b99071564405fc1abb30b93f8cf50c1d503ecae93
#5 DONE 0.0s

#9 [drud/ddev-webserver:v1.19.0-1-tryddevproject-22804-built 1/4] FROM docker.io/drud/ddev-webserver:v1.19.0-1
#9 sha256:b52962fcf44919d3b8baf1f779e78da50a31770f13a470f8ecb97ba2a539d56d
#9 DONE 0.0s

#6 [drud/ddev-webserver:v1.19.0-1-tryddevproject-22804-built 2/4] RUN (groupadd --gid 1000 "rober" || groupadd "rober" || true) && (useradd  -l -m -s "/bin/bash" --gid "rober" --comment '' --uid 1000 "rober" || useradd  -l -m -s "/bin/bash" --gid "rober" --comment '' "rober" || useradd  -l -m -s "/bin/bash" --gid "1000" --comment '' "rober")
#6 sha256:808da5f18f45fb4774fe0ce687e0b177482f8cae2a7477055b3856523fc4a4ec
#6 CACHED

#10 [drud/ddev-dbserver-mariadb-10.3:v1.19.0-tryddevproject-22804-built internal] load metadata for docker.io/drud/ddev-dbserver-mariadb-10.3:v1.19.0
#10 sha256:1b73e1d4a9545681a41ec8811917ee3a5008ce026f33f7e6387f6fd998d15478
#10 DONE 0.0s

#11 [drud/ddev-dbserver-mariadb-10.3:v1.19.0-tryddevproject-22804-built 1/2] FROM docker.io/drud/ddev-dbserver-mariadb-10.3:v1.19.0
#11 sha256:e1e6388adb2e177361f50d8bb1115159556fd23148ea9e6fed43997a8f8f2dd4
#11 DONE 1.0s

#12 [drud/ddev-dbserver-mariadb-10.3:v1.19.0-tryddevproject-22804-built 2/2] RUN (groupadd --gid 1000 "rober" || groupadd "rober" || true) && (useradd  -l -m -s "/bin/bash" --gid 
"rober" --comment '' --uid 1000 "rober" || useradd  -l -m -s "/bin/bash" --gid "rober" --comment '' "rober" || useradd  -l -m -s "/bin/bash" --gid "1000" --comment '' "rober")    
#12 sha256:0c9b8c82c078c443f52bd8712e60b5f06d484fe70675bb8559a9a88a56e1593d
#12 DONE 1.4s

#7 [drud/ddev-webserver:v1.19.0-1-tryddevproject-22804-built 3/4] RUN export XDEBUG_MODE=off && ( composer self-update --2 || composer self-update --2 || true )
#7 sha256:2ee9a302f535040abe3c1c54418e67120b6930605e433a7595b186e47a6ef22b
#7 1.041 Upgrading to version 2.2.9 (2.x channel).
#7 1.077
#7 1.388 Use composer self-update --rollback to return to version 2.2.7
#7 DONE 2.4s

#13 [drud/ddev-dbserver-mariadb-10.3:v1.19.0-tryddevproject-22804-built] exporting to image
#13 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#13 exporting layers 0.0s done
#13 writing image sha256:e44daaf42981a270709ed90e61b5d4b3df19b8a920d5095141d2f153ef375504 done
#13 naming to docker.io/drud/ddev-dbserver-mariadb-10.3:v1.19.0-tryddevproject-22804-built done
#13 DONE 0.1s

#8 [drud/ddev-webserver:v1.19.0-1-tryddevproject-22804-built 4/4] RUN chmod 600 ~rober/.pgpass ~rober/.my.cnf
#8 sha256:f5e1408c6c387b4f56615610b7d6e164a9f1cfe8708f248d105f945a2b5b22a6
#8 DONE 0.9s

#13 [drud/ddev-webserver:v1.19.0-1-tryddevproject-22804-built] exporting to image
#13 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#13 exporting layers 0.1s done
#13 writing image sha256:222129ffb8d64148a06fc9cdd1b4a2281b3ee4516efb6d7d6dfe94f0c50957e4 done
#13 naming to docker.io/drud/ddev-webserver:v1.19.0-1-tryddevproject-22804-built done
#13 DONE 0.1s
', stderr='Network ddev-tryddevproject-22804_default  Creating
Network ddev-tryddevproject-22804_default  Created
Container ddev-tryddevproject-22804-web  Creating
Container ddev-tryddevproject-22804-db  Creating
Container ddev-tryddevproject-22804-dba  Creating
Container ddev-tryddevproject-22804-db  Created
Container ddev-tryddevproject-22804-dba  Created
Error response from daemon: invalid mount config for type "bind": stat /run/desktop/mnt/host/c/Users/rober/tmp/tryddevproject-22804: input/output error' 
┌──────────────────────┬─────────┬────────────────────────────┬─────┬─────────┐
│ NAME                 │ TYPE    │ LOCATION                   │ URL │ STATUS  │
├──────────────────────┼─────────┼────────────────────────────┼─────┼─────────┤
│                      │ 2       │                            │     │         │
├──────────────────────┼─────────┼────────────────────────────┼─────┼─────────┤
│ tryddevproject-22804 │ php     │ ~/tmp/tryddevproject-22804 │     │ stopped │
│                      │         │                            │     │ db:     │
├──────────────────────┼─────────┼────────────────────────────┼─────┼─────────┤
│ Router               │         │ stopped                    │     │         │
└──────────────────────┴─────────┴────────────────────────────┴─────┴─────────┘

========= web container healthcheck ======

Error: No such object: ddev-tryddevproject-22804-web
+ curl --fail -I tryddevproject-22804.ddev.site
curl: (7) Failed to connect to tryddevproject-22804.ddev.site port 80: Connection refused
+ '[' 7 -ne 0 ']'
+ set +x
Unable to curl the requested project Please provide this output in a new gist at gist.github.com.

Please delete this project after debugging with 'ddev delete -Oy tryddevproject-22804'
Failed running test_ddev.sh: exit status 1
. You can run it manually with `curl -sL -O https://raw.githubusercontent.com/drud/ddev/master/cmd/ddev/cmd/scripts/test_ddev.sh && bash test_ddev.sh`
PS C:\Users\rober\cialdemania2> ddev delete -Oy tryddevproject-22804
Container ddev-tryddevproject-22804-dba  Removed 
Container ddev-tryddevproject-22804-db  Removed 
Network ddev-tryddevproject-22804_default  Removed 
ddev needs to remove an entry from your hosts file.
It will require administrative privileges via the sudo command, so you may be required
to enter your password for sudo. ddev is about to issue the command:
    sudo C:\Program Files\DDEV\ddev.exe hostname --remove tryddevproject-22804.ddev.site 127.0.0.1 
Please enter your password if prompted.
Running   Command=sudo C:\Program Files\DDEV\ddev.exe hostname --remove tryddevproject-22804.ddev.site 127.0.0.1
Volume tryddevproject-22804-mariadb for project tryddevproject-22804 was deleted 
Volume tryddevproject-22804-postgres for project tryddevproject-22804 was deleted 
Volume tryddevproject-22804_project_mutagen for project tryddevproject-22804 was deleted
Deleted docker image drud/ddev-dbserver-mariadb-10.3:v1.19.0-tryddevproject-22804-built 
Deleted docker image drud/ddev-webserver:v1.19.0-1-tryddevproject-22804-built 
Project tryddevproject-22804 was deleted. Your code and configuration are unchanged.

**Comment by rfay** [comment]
That helps a lot, and it shows that a trivial project has the same problem you reported. It was requested to put it in a gist on gist.github.com where it makes less of a mess, but it helps here. 

Now it's time for you to do the troubleshooting steps.

**Comment by RobertoZeppilli** [comment]
I tried the last part of the page, no results. At the point to start the project it fails returning the same error: 

**Error response from daemon: invalid mount config for type "bind": stat /run/desktop/mnt/host/c/Users/rober/cialdemania2: input/output error' **

ddev poweroff
docker rm -f $(docker ps -aq) # stop any other random containers that may be running
docker rmi -f $(docker images -q) # You might have to repeat this a time or two to get rid of all images

**Comment by rfay** [comment]
It looks like docker isn't working, please work all the way through, including reboot. 

You'll want to look at https://ddev.readthedocs.io/en/latest/users/docker_installation/#testing-and-troubleshooting-your-docker-installation as well.

**Comment by RobertoZeppilli** [comment]
![Immagine 2022-03-19 144345](https://user-images.githubusercontent.com/78091609/159123538-135ec1c6-d735-4194-98ba-72941075757a.jpg)


This is the response from git bash using this comand:
`docker run --rm -t -p 80:80 -v "/$PWD:/tmp/projdir" busybox sh -c "echo ---- Project Directory && ls /tmp/projdir"`

I think it's a better idea to wait until monday and check with the others, I don't want to cause any trouble. But it would've been awesome if I could fix it. Anyway THANKS a lot for your availability, really.

**Comment by rfay** [comment]
I have never seen the source path /run/desktop before, think it should just be /mnt/c. 

Anyway, you've proved that docker itself is broken I think.

**Comment by rfay** [comment]
I assume you haven't already done this with your magento project? I can't imagine how long the `ddev composer create` will take or how slowly the web server will run. Definitely encourage you to move to wsl2, where it's very, very fast. The more files in a system, the slower docker is on traditional Windows. But it doesn't even affect wsl2.

**Comment by RobertoZeppilli** [comment]
In fact I am using wsl2 instead of hyper-v, or at least is what docker desktop says. I think that the best thing to do is delete the project and reclone it in a dedicated folder this time, maybe.

**Comment by rfay** [comment]
You're using WSL2 for the Docker Desktop backend, that's a separate topic. The recommended way to use ddev is to run it inside WSL2, the instructions are at https://ddev.readthedocs.io/en/latest/#windows-wsl2

There's a shorter but dated explanation at https://ddev.com/ddev-local/ddev-wsl2-getting-started/ and a screencast (also somewhat dated) at https://ddev.com/ddev-local/watch-ddev-local-from-scratch-with-windows-wsl2/

**Comment by RobertoZeppilli** [comment]
![wsl -l -v](https://user-images.githubusercontent.com/78091609/159125006-c71fc78f-4977-40b7-b7e0-fa89d6b0cea7.jpg)

I've followed the guide from installing chocolatey to ddev. The only thing that was strange during the process was that running `echo $CAROOT` it didn't return  something like `/mnt/c/Users/<you>/AppData/Local/mkcert`. Instead it returns nothing but without errors.

**Comment by RobertoZeppilli** [comment]
Good news! I restarted docker from docker desktop, run `ddev start` and now this is the result

![eureka](https://user-images.githubusercontent.com/78091609/159126373-6d4622e2-6edc-477b-adc8-50cc988c9d92.jpg)

**Comment by RobertoZeppilli** [comment]
Now I'm exactly at the point of yesterday. All three of the url provided take me to this page. It is because of `composer install`?  

![ppp](https://user-images.githubusercontent.com/78091609/159126443-0c51715a-8c6b-4de6-bf0c-3cdd69ff4b8b.jpg)

**Comment by rfay** [comment]
For composer, it's recommended to use `ddev composer install`, especially on Windows. https://ddev.readthedocs.io/en/latest/users/developer-tools/#ddev-and-composer

I'm not sure where you're at now, whether you're trying to switch to WSL2 or what. I hope you'll keep going down that path.

I strongly recommend that you try a trivial installation like the TYPO3 quickstart when you get docker going and all. There may be something wrong with the composer.json you're using. https://ddev.readthedocs.io/en/latest/users/cli-usage/#typo3-quickstart

**Comment by RobertoZeppilli** [comment]
Thanks a lot Randy, I'm sure everything will be fine for Monday. 
Practically, what I had to do is enter in this project to start make some changes, and to do so, I had to install everything from scratch to support magento2, ddev and docker in Windows10. I will have to work on the frontend of the application, can't wait to do so! 

I left the colleagues with the installation of composer almost done, when suddenly an error pops out so i decided to try and fix it before Monday.

Sorry for all the messy info that I've provided, and thank you again!

**Comment by rfay** [comment]
If you do end up staying on traditional Windows, you'll want to look at https://ddev.readthedocs.io/en/latest/users/performance/ and use at a minimum mutagen or NFS. Mutagen has gotten some good reports on Windows, but it takes forever on the first sync.

**Comment by RobertoZeppilli** [comment]
Thanks for helping me out! So (for future viewers) the solution was to just restart docker desktop, and ddev start runs again!

**Comment by rfay** [comment]
Also for future viewers, start with 

[General troubleshooting strategies](https://ddev.readthedocs.io/en/latest/users/troubleshooting/#general-troubleshooting-strategies) and
[Troubleshooting docker](https://ddev.readthedocs.io/en/latest/users/docker_installation/#testing-and-troubleshooting-your-docker-installation) 

both mentioned in this thread. But restart docker or reboot your machine early!
