### ISSUE TITLE
1.19.0: TYPO3 configuration incorrectly excludes fileadmin from mutagen

### ISSUE THREAD

**Issue by dmitryd** [drud/ddev#3732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/dmitryd/fbac1fcd890fbdcb166f4e09cc10a30a

### Current Behavior

ddev now excludes the whole `fileadmin` from mutagen. This causes problems because this folder can contain files that are in git and they have to be synchronized on host/guest file systems (like TYPO3 form definitions or default images, for example).

This prevents 1.19.0+mutagen from working with TYPO3 properly.

If I remove `html/fileadmin` from `.ddev/mutagen/mutagen.yaml` I get mutagen error `html/fileadmin: scan crossed filesystem boundary`.

Please, allow `fileadmin` to be synced with mutagen again. Currently it is not usable, only NFS option remains usable.

Related but different: #3279 (I have everything on a single filesystem with all default permissions)

### Expected Behavior

`fileadmin` directory is not excluded from mutagen sync with TYPO3.

### Steps To Reproduce

1. Create a TYPO3 project
1. Enable mutagen
1. Edit `.ddev/mutagen/mutagen.yaml` to comment exclusion of `fileadmin` directory
1. `ddev restart` and see mutagen sync errors

**Comment by rfay** [comment]
Hi @dmitryd  - This is a new feature of v1.19, and it was added because people were concerned about the massive amount of space that mutagen could use up managing the copies of the user files. In CMSs that I'm familiar with, the user files areas are never checked into git (and are rarely accessed by the webserver), so this isn't an issue. 

However, you can easily change DDEV's behavior on this. It's determined by the setting of `upload_dir`, which has a default for TYPO3 of fileadmin.  I assume you do not have a custom setting for this?

The easiest thing to do is to change the project type to 'php' so ddev no longer knows or cares where the upload_dir is. 

As you know, another technique is to take over the .ddev/mutagen/mutagen.yml file, just remove the `#ddev-generated` line from it and change the config to remove the exclusion. The docs may give you some hints here in https://ddev.readthedocs.io/en/stable/users/performance/#advanced-mutagen-configuration-options

I hope that helps for your configuration. I'm certainly interested that you have files inside fileadmin checked into git - is that normal? It seems unusual. If that's common practice then this is indeed a bug and will need to be changed for TYPO3 projects.

**Comment by rfay** [comment]
The reason you're seeing the "html/fileadmin: scan crossed filesystem boundary" errors is that when you comment out the exclusion, mutagen stumbles across the separate bind-mounted filesystem that fileadmin has. You can see the setup by looking at the generated .ddev/.ddev-docker-compose-base.yaml

I did find another simple workaround for you - Just set `upload_dir: junk` (or any other directory that you don't care about). I don't think that will have any bad effects, and it will trick ddev into configuring both docker and mutagen to mounting the special dir elsewhere, where it doesn't matter.

**Comment by dmitryd** [comment]
@rfay 

Thanks for the fast response! :)

>  In CMSs that I'm familiar with, the user files areas are never checked into git (and are rarely accessed by the webserver), so this isn't an issue.

In TYPO3 `fileadmin` is not the directory with only user files. While it does contain files uploaded by editors, it is not limited to those. It can contain any files that are not created by the CMS. Here is an example of what we often put there:
- Yaml definitions of any custom forms. This is configuration but it is editable by the user, thus it is in `fileadmin`. it has to be committed to git. It can be edited, modified and committed again and again. Since it is in git, it has to be synced with mutagen into docker.
- Report files (like CSV, PDF, special graphics, etc). If they are generated by custom code, they are put to `fileadmin`. Then they can be opened by Excel or LibreOffice or another editor during development. If they are not synced, it becomes manual work to move them somewhere and open from another directory.
- Directories and stock images in site templates. Many companies have standard templates with a number of stock images and certain structure inside `fileadmin`, like `fileadmin/images`, `fileadmin/documents`, etc. These directories can contain READMEs and need to be available on both host and inside docker.

For one customer we had json files for importing data, which were put by them via ftp on the actual server. When we developed and did troubleshooting, we worked with these files manually on the host system directly in `fileadmin`. So it is really important that fileadmin is not excluded.

What definitely should be excluded from mutagen is `fileadmin/_processed_ ` because this usually contains hundreds of resized runtime images. `fileadmin/_temp_` is also a good candidate. But excluding the whole `fileadmin` from sync breaks existing behavior for many sites. I just upgraded to 1.19.0 from 1.18.2 and suddenly the site was broken because it did not have any forms and predefined images on template pages.

I would also suggest to add&comment `{publicdir}/typo3temp` to `mutagen.yaml` as an example of directories to exclude (just like `/var`).

And finally an excerpt from the [TYPO3 docs](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/CreateNewDistribution/Index.html?highlight=fileadmin#concept-of-distributions) about creating pre-packaged TYPO3 distributions:

> The distributions are full TYPO3 CMS websites that only need to be unpacked. They offer a simple and quick introduction to the use of the TYPO3 CMS. The best known distribution is the Introduction Package. Distributions are easiest to install via the Extension Manager (EM) under “Get preconfigured distribution”.
>
> A distribution is just an extension enriched with some further data that is loaded or executed upon installing that extension. A distribution takes care of the following parts:
>
> * Deliver initial database data
> * **Deliver fileadmin files**
> * Deliver configuration for a package
> * Hook into the process after saving configuration to trigger actions dependent on configuration values
> * Deliver dependent extensions if needed (e.g., customized versions or extensions not available through TER)

So as seen from the official docs, `fileadmin` can contain impiortant data that needs to be synced to docker.

> I did find another simple workaround for you - Just set upload_dir: junk

If this directory exists, it has to be excluded or it shows the same error. If it does not exist it is created inside docker. I can live with that. However I see it will breal `import-files`. I can live with that too but I have a better idea :) 

I'd wish there was an option not to exclude `upload_dir` from sync (`exclude_upload_dir_from_mutagen: true` by default). That would server both cases perfectly well. What do you think?

**Comment by rfay** [comment]
Note that fileadmin is being synced regardless, it's just the kind of sync we're talking about. Right now it's being synced with a regular docker mount. But that makes keeping it in git not work.

And yes, `ddev import-files` won't work with the workaround I suggested.

If the community agrees with you, I definitely think there needs to be a way to turn off this feature.

**Comment by rfay** [comment]
Thinking about this... could you say more about what the actual current problem is (if you don't modify anything)? Are you using git inside the web container? That's the only thing I can think of that would cause any disruption.

**Comment by dmitryd** [comment]
No git operations inside docker.

Problem is: I need to sync certain subdirectories of `web/fileadmin` directory from host to docker. These subdirectories contain files that I check out from git on host and those files are part of the web site. Here is the structure from the real site:

```
$ ls -1 public/fileadmin/
_processed_
_temp_
files
form_definitions
form_uploads
user_upload
```

Here you can see several important folders:

| Name | Needs to sync | In git | Description |
|-------|---------------|-------|-------------|
| `_processed_` | No | No | Temporary images generated in docker here. This should be excluded from sync completely |
| `_temp_` | No | No | Temporary previews generated in docker here. This should be excluded from sync completely |
| files | No | No | Customer files (uploaded via CMS), no need to sync but does not hurt to sync |
| form_definitions | Yes | Yes | This contains form definitions for web pages. These **must** be synced. The site breaks if they are missing |
| form_uploads | No | No | If the visitor uploads the file using web site forms, they go here |
| reports | Yes | No | These are reports generated by the CMS. They need to be synced because they are examined during development. |
| user_upload | No | No | Images are uploaded here using CMS |

This is just one of projects but sometimes we also have other directories that have to be synched, like format definitions for product import, for example. They are in git and in `fileadmin`.

Therefore leaving `fileadmin` completely out of sync breaks sites. `fileadmin` is **not** an "upload directory" in TYPO3. It is a directory that contains any files used by CMS. This includes both files uploaded by CMS editors (not in git) and provided by the developer (in git). Therefore excluding `fileadmin` completely is not the right idea for TYPO3.

How did it work in 1.18.2? Very well, by using `.ddev/mutagen/mutagen.yml`:

```yaml
sync:
  defaults:
    mode: "two-way-resolved"
    stageMode: "neighboring"
    ignore:
      paths:
      - "/.git"
      - "/.tarballs"
      - "/.ddev/db_snapshots"
      - "/.ddev/.importdb*"
      - ".DS_Store"
      - ".idea"
      - "/var"
      - "/public/typo3temp"
      - "/public/fileadmin/_processed_"
      - "/public/fileadmin/_temp_"
      - "/public/fileadmin/files"
      - "/public/fileadmin/user_upload"
```

How does it work in 1.19.0? It does not unless I put something non-existing into `upload_dir`.

I hope this helps.

**Comment by rfay** [comment]
With the default config, all the files that you have on the host should appear in the container and vice versa. It's just using docker bind-mounting for the fileadmin.

**Comment by dmitryd** [comment]
Yes but not with mutagen. Default is too slow. NFS is like 5x faster but mutagen is even faster. For now I went back to NFS.

**Comment by rfay** [comment]
With v1.19, the sync of things in fileadmin should be *faster*, not slower. It's bind-mounted, meaning that docker takes care of it immediately. The only issue is if you are using something a LOT in there, and it changes a LOT.

Is this issue about webserving performance of the fileadmin directory ? Or is it about something else?

**Comment by dmitryd** [comment]
I am using docker on macOS. There default docker bind mounting is terribly slow. There is a [three years old ticket](https://github.com/docker/for-mac/issues/3677) about it for docker. It is bad even on M1 Max macOS.

**Comment by rfay** [comment]
Right, but the webserver only rarely accesses things in fileadmin, true?  I know all the tickets and am *still* getting notifications about them and following all of them. The tradeoff implemented in v1.19 is to bind-mount upload_dir because it may have gigabytes of things, but they're rarely accessed. Is the problem here that your application accesses them often? 

Note that colima is faster, and see the comparisons in https://ddev.com/ddev-local/docker-desktop-and-colima-benchmarking-on-macos/

And intro to colima in https://ddev.com/ddev-local/docker-desktop-alternatives-arrive-for-ddev-colima/

**Comment by dmitryd** [comment]
> Right, but the webserver only rarely accesses things in fileadmin, true?

I would not say so because this directory also contains all web site images.

**Comment by rfay** [comment]
RIght, but website images are typically accessed only once on a page load. Unlike code, where php files often require a hundred or a thousand accesses on a page load. That's the tradeoff idea here.

Can you quantify the problem you're talking about (with default config + mutagen)? Can you show the difference that's worrying you?

**Comment by dmitryd** [comment]
I already described it more than once: `fileadmin` should be synced when using mutagen. I cannot make it simpler than that. If this is not possible, let's just close the ticket and I will go back to NFS.

**Comment by rfay** [comment]
The question is "why". Please make the case for why this is important. I think you're saying that you ran into performance trouble, but I've been waiting for you to quantify what your experience was. Syncing all of the upload_dir is very expensive for many applications (especially when there are gazillions of files) so this change has been very well received in v1.19. But if you can make the case for the actual problem you're seeing, it's important to understand. "Should be synced" is a statement that you disagree with the design, but I'm looking for something that explains how and why the design should be different and why.

**Comment by dmitryd** [comment]
Sorry. This simple issue takes much longer than it should and I am not willing to explain this again and again. I already did multiple times. It is counterproductive.

Do not do anything about it. I will simply use NFS or 1.18.2.

**Comment by jonaseberle** [comment]
Setups are so vastly different. And ddev makes some assumptions to facilitate getting newbies up quickly that might interfere with power-users' demands. 

`ddev` being such an important part of our tool chain and giving us so much value we do compromise to cater for it when it comes to file structure and deployment, ... but it took me some time, too to find a suitable setup. I would say "fileadmin is shared, volatile, user (non-gitted) data" but that is not a given.

Dmitry, if there is something that could be improved by means of an additional configuration option I think it is worth to pursue.
