### ISSUE TITLE
PDFreactor service addon

### ISSUE THREAD

**Issue by blankse** [drud/ddev#3733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

We use DDEV for Pimcore projects. There we use a PDFrector service to generate PDFs from Web2Print documents. I created an addon for DDEV to quickly install it: https://github.com/blankse/ddev-pdfreactor

### Describe the solution you'd like

Do you want to add it to the official addons?

**Comment by rfay** [comment]
Congrats on all the work on this! 

We can move this to "official" whenever you want to. It's slightly complicated to move it to the drud org. You have to temporarily give me admin permissions on your user so I have permissions to move the repo. Alternately, it can be forked to drud org, but that loses issues and PR history.  (This is easier when the repo starts out on an org, but it does seem like GitHub makes it unnecessarily hard. Giving privs on the repo would seem to be enough, not having to give privs on the user.)

**Comment by blankse** [comment]
Transfer worked :) Thanks for your work.

**Comment by rfay** [comment]
Congrats, and thanks for maintaining this. I'm signed up for all activity as well.
