### ISSUE TITLE
Hanging/docker broken when xdebug enabled and disabled (Docker Desktop Bug)

### ISSUE THREAD

**Issue by penance316** [drud/ddev#3735]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/penance316/4dca60cb6562a968018ecdf1736f17cf

### Current Behavior

I am running with mutagen enabled.
Before updating to v1.19.1 this behaviour was working fine.

Recently I noticed I am unable to run my PHP project while xdebug is enabled in ddev. 
Unless my IDE is also currently listening for the xdebug breakpoint.

While xdebug is disabled and my IDE is closed.

1. curl site 'mysite.ddev.site' and get a response 👍 
2. enable xdebug with 'ddev xdebug enable'
3. curl site again.
4. Curl hangs indefinitely. ❌ 
Unless
5. open IDE (PHPSTORM)
6. start listening for xdebug connections in PHPSTORM
7. curl site again
8. breakpoint is hit 👍 
9. resume execution
10. curl response is received 👍 
 
Seems very odd but it appears when xdebug is enabled my page wont actually load unless it hits a breakpoint. It doesn't seem to have anything to do with PHPstorm itself because the behaviour is seen even when PHPstorm hasn't been started yet.

### Expected Behavior

The website/project behaves the same when xdebug is enabled as when it is disabled. 
I should be able to navigate to or curl the project when xdebug is enabled on ddev without the need to run a debugger.

Previously I would work by leaving xdebug enabled on the ddev server and then toggle the listening from my IDE.

### Steps To Reproduce

xdebug disabled and IDE closed.

1. curl site 'mysite.ddev.site' and get a response
2. enable xdebug with 'ddev xdebug enable'
3. curl site again.
4. Curl hangs indefinitely. ❌ 
Unless
5. open IDE (PHPSTORM)
6. start listening for xdebug connections in PHPSTORM
7. curl site again
8. breakpoint is hit 👍 
9. resume execution
10. curl response is received 👍 
 

### Anything else?

Please let me know if i need to provide some more info or clarify anything.
Thanks

**Comment by penance316** [comment]
Thanks for your speedy help.

So it seems the issue is with the IDE or some combination of it listening to debug connections.

Using the trivial project as you recommended `mkdir junk && cd junk && ddev config --auto && printf "<?php\nphpinfo();\n" >index.php && ddev launch`

Everything works fine until I enable then disable the "listening for debug connections" in PHPstorm.
My steps with the junk project.

Restarted laptop.
1. run command above to create launch junk project. (all good 👍 )
2. enable debug `ddev xdebug enable`
3. refresh junk site at `https://junk.ddev.site/`  (all good 👍 )
4. Now open PHPstorm and refresh website (still working 👍 )
5. Enable "start listening for PHP debug connections" in PHPstorm with a breakpoint.
6. Refresh site, 👍 it hits the breakpoint and continues to load the page as expected.
7. Now disable the "start listening for PHP debug connections" in phpstorm
8. Refresh the page ❌ Page continues to hang and never loads.


And then to workaround the hanging I either `ddev restart` or start listening for debug connections again in PHPstorm then refresh the site and back to working. But of course now I have to leave xdebug enabled and the debugger listening.

**Comment by rfay** [comment]
Note that there is a related problem with Docker Desktop 4.6+, 
* https://github.com/docker/for-mac/issues/6235

**Comment by rfay** [comment]
I imagine that's the problem. You may want to try it with Colima, super easy to do, and doesn't conflict with Docker Desktop, https://ddev.readthedocs.io/en/latest/users/docker_installation/#macos-installation-colima

Or to roll back Docker Desktop to before 4.6.x, there are links in https://docs.docker.com/desktop/mac/release-notes/

**Comment by rfay** [comment]
Updates on this in 
* https://github.com/docker/for-mac/issues/6235#issuecomment-1089259576

You can easily work around it by just `ddev xdebug off` when you're wanting to continue, then enable it again when you need it.

**Comment by rfay** [comment]
They have a fix for this in https://github.com/docker/for-mac/issues/6235#issuecomment-1110148046 - should be in next docker desktop release.

**Comment by rfay** [comment]
This problem seems to be resolved in Docker Desktop 4.8.1
