### ISSUE TITLE
ddev yarn --cwd XYZ unexpected EOF while looking for matching

### ISSUE THREAD

**Issue by HeineDeelstra** [drud/ddev#3741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/HeineDeelstra/a5e647aa35b2f5a56e2a8e21a8f8ae0a

### Current Behavior

ddev yarn with a cwd given via --cwd results in an error message "unexpected EOF while looking for matching `" instead of executing the yarn command.

For example:

$ ddev yarn --cwd frontend build
frontend: unexpected EOF while looking for matching `''
frontend: syntax error: unexpected end of file
Failed to execute command bash -ic yarn '--cwd frontend build': exit status 2

### Expected Behavior

I would expect the yarn command to run in the given cwd.

### Steps To Reproduce

In a drupal9 or php project with a dir projectroot/subdir run on the host:
ddev yarn --cwd subdir [command]

### Anything else?

I normally use /opt/homebrew/bin/bash on the host (GNU bash, version 5.1.16(1)-release (aarch64-apple-darwin21.1.0). This bash is also in PATH.

**Comment by rfay** [comment]
Hmm, shouldn't do that. 

Note that `ddev exec yarn --cwd web install` works fine.

**Comment by rfay** [comment]
I think `ddev yarn` should be moved from a host command to web command to make it behave better.

**Comment by m4olivei** [comment]
I ran into this today as well. Working on a Drupal 10 core patch, wanting to compile post css for core, trying:

```
$ ddev yarn --cwd core install
core: unexpected EOF while looking for matching `''
core: syntax error: unexpected end of file
Failed to execute command bash -ic yarn '--cwd core install': exit status 2
```

As noted, the following work around works for me:

```
$ ddev exec yarn --cwd core install
```

**Comment by rfay** [comment]
* The `yarn` shell command should really be a web command instead of host command, will make things simpler.
* I think we should add an instruction to the custom commands to say "do a mutagen sync after", and that would be a better workaround to the current situation.

**Comment by rfay** [comment]
This was fixed by 
* https://github.com/drud/ddev/pull/3836
You can test it with `brew install --HEAD ddev`
