### ISSUE TITLE
define path to package.json as node_root

### ISSUE THREAD

**Issue by plexmaniax** [drud/ddev#3747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

With the composer_root you could define the path to your composer.json and you could use ddev composer install.
For the npm command you have to set the path to your package.json.

### Describe the solution you'd like

It would be great to define the path to the package.json in the .ddev//config.yaml (as composer_root does), so we could use the ddev npm install or ddev npm update command without any additionals.

**Comment by rfay** [comment]
But can't there be more than one package.json in a project? (and wouldn't it be npm_root)? It seems to me like I've eeen lots of package.json that were particular to a particular (deep) subdirectory, like a Drupal theme, for example.

**Comment by plexmaniax** [comment]
You're right, I missed that point. In our company, we normally doesn't work with multiple package.jsons'.

I think I could edit the edit the npm command, which find and set the right path for my packages.json

**Comment by rfay** [comment]
You may want to create a custom command for your project that does exactly what you want to do...

**Comment by rfay** [comment]
I'm going to close this for now, but happy to continue the conversation here or elsewhere.

**Comment by rfay** [comment]
Actually, you don't have to do this at all any more. These days the `ddev npm` command has
`## HostWorkingDir: true`

which means that it automatically executes in the same relative directory you're in on the host.
