### ISSUE TITLE
Implement virtiofs instead of nfs for file sharing

### ISSUE THREAD

**Issue by ericdsd** [drud/ddev#3750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When using DDEV with docker desktop for mac, 
we can either use NFS sharing that is incredibly slow or mutagen that is really faster, but has synchnization potential delay, and requires double disk space tu run.
Since Docker Desktop 4.6 virtiofs experimental support is provided and seems to be an interesting alternative to NFS and mutagen.

### Describe the solution you'd like

Implement virtiofs implementation.
see https://virtio-fs.gitlab.io/ and https://docs.docker.com/desktop/mac/#experimental-features

**Comment by rfay** [comment]
VirtioFS is still off to a really rough start in Docker Desktop. However, you can already turn it on in Docker Desktop, but I don't recommend it yet. However, if it ever achieves reliability, you'll be able to just turn it on.

For the foreseeable future though I recommend Mutagen, which people are using very happily. `ddev config global --mutagen-enabled`. https://ddev.readthedocs.io/en/latest/users/performance/#using-mutagen

But be assured I've been in the issues about VirtioFS and every other thing Docker Desktop has tried for many years now.

I should note that Colima with Mutagen gets by far the best usable performance, https://ddev.com/ddev-local/docker-desktop-and-colima-benchmarking-on-macos/

I'll close this now as there's nothing actionable for DDEV, and no changes will need to be made to DDEV when VirtioFS gets reliable.

**Comment by ericdsd** [comment]
Thanks for your reply, my goal was mainly to be able to test virtiofs and eventually report issues, i'm aware it is still very experimental.
By the way thanks a lot for your tremendous work on ddev.

**Comment by rfay** [comment]
Hopefully they'll be able to resolve the permissions issues that are bothering everybody at this point. But I don't think that anything will need to be done on the ddev end when they get those sorted. OTOH, it doesn't seem like  it will be as fast as mutagen already is.
