### ISSUE TITLE
Running `ddev auth ssh` in Gitpod results in error

### ISSUE THREAD

**Issue by shaal** [drud/ddev#3755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/shaal/d53bfac95e7b33b2cb409d69c524f64f

### Current Behavior

In Gitpod workspace, running `ddev auth ssh` display this error message:
```bash
Docker command 'docker [run -it --rm --volumes-from=ddev-ssh-agent --user=33333 --entrypoint= --mount=type=bind,src=/home/gitpod/.ssh,dst=/tmp/sshtmp drud/ddev-ssh-agent:v1.19.0-built bash -c cp -r /tmp/sshtmp ~/.ssh && chmod -R go-rwx ~/.ssh && cd ~/.ssh && ssh-add $(file * | awk -F: "/private key/ { print \$1 }")]' failed: exit status 1
```

### Expected Behavior

I would like to be able to run `ddev auth ssh`, so I can have my host environment variables (that I set in Gitpod's user or project account) in ddev container.

### Steps To Reproduce

1. Open DrupalPod (or any ddev project in Gitpod)
2. run in terminal `ddev auth ssh`

**Comment by rfay** [comment]
Did you copy your private key up there?

I didn't understand what this has to do with environment variables.

**Comment by shaal** [comment]
My bad, I somehow thought it's related to environment variables.
Environment variables work well and as expected (https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#providing-custom-environment-variables-to-a-container) 

The error message above was simply because I didn't have `~/.ssh/id_rsa` file in the host, so `ddev auth ssh` couldn't copy a missing file.
