### ISSUE TITLE
Add support for MariaDB 10.7

### ISSUE THREAD

**Issue by calipzo** [drud/ddev#3759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

MariaDB 10.7 has reached GA. It's in Docker Hub.

### Describe the solution you'd like

Add support of MariaDB 10.7.

**Comment by rfay** [comment]
Will do, but can you say why it's important to you?

**Comment by calipzo** [comment]
For testing. Some clients love new stable versions of software. And for testing new features of MariaDB.

**Comment by kamilmaliszewski** [comment]
@rfay There is the option to use e.g for testing other version of MariaDB? I've found bug in MariaDB's older version https://jira.mariadb.org/browse/MDEV-27937  . Even I make update of ddev config I have still 1.5.12. There is the option to instal 1.5.16 in any way?

**Comment by rfay** [comment]
@kamilmaliszewski does this have to do with this issue? It doesn't look like it. Also the versions you mention don't correlate with either ddev or mariadb versions, so please open a new issue with your question and be more specific about what you want

**Comment by kamilmaliszewski** [comment]
@rfay for me it is similar issue because it is also connected with update MariaDB. My bug is fixed also in [10.7.4]. But sure. I can create new issue if for you it is something separated.

**Comment by rfay** [comment]
@calipzo @kamilmaliszewski I'd love it if you could test this, instructions in https://github.com/drud/ddev/pull/3783#issuecomment-1113550264
