### ISSUE TITLE
"ddev describe" should report information about the routed and unrouted web ports

### ISSUE THREAD

**Issue by rfay** [drud/ddev#376]
## What happened (or feature request):

Our users may well want to know about the exposed ports (especially http) on their localhost, as it makes many things possible, as in #375 where ngrok is suggested. This is easily accessible in `docker ps`, but would be better coming from ddev.

We should report in `ddev describe`:
* The actual correct port the router is providing
* The unrouted ports exposed by the web container.

## Related source links or issues:

**Comment by rickmanelius** [comment]
This seems valuable enough to revisit on the next iteration of the roadmap.

**Comment by rfay** [comment]
Duplicate of closed #323. To be solved in #481 , so closing here.
