### ISSUE TITLE
.webimageBuild/Dockerfile has wrong file path references

### ISSUE THREAD

**Issue by gormus** [drud/ddev#3761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After upgrading to v1.19.1, I noticed the `.ddev/.webimageBuild/Dockerfile` file includes false references for `.pgpass` and `.my.cnf` files:

```dockerfile
RUN chmod 600 ~USERNAME/.pgpass ~USERNAME/.my.cnf
ENV NVM_DIR=/home/USERNAME/.nvm
```

### Expected Behavior

The path references should be:

```dockerfile
RUN chmod 600 /home/USERNAME/.pgpass /home/USERNAME/.my.cnf
ENV NVM_DIR=/home/USERNAME/.nvm
```

**Comment by rfay** [comment]
Both ways should work... And this is working. Not sure why I used tilde notation though.

**Comment by gormus** [comment]
TIL. 

I wasn't aware of the `~username` expansion, and thought it was a typo. It's totally valid as is.
Sorry about the noise.


Here's some more details on it:
https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html 

> ~

The value of `$HOME`

> ~/foo

`$HOME/foo`

> ~fred/foo

The subdirectory `foo` of the home directory of the user `fred`
