### ISSUE TITLE
docroot option not respected

### ISSUE THREAD

**Issue by josefglatz** [drud/ddev#3764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

Following the TYPO3 QuickStart at https://ddev.readthedocs.io/en/stable/users/cli-usage/#typo3-quickstart doesn't set docroot correctly

### Current Behavior

Running

```
mkdir my-typo3-site
cd my-typo3-site
ddev config --project-type=typo3 --docroot=public --create-docroot
ddev start
ddev composer create "typo3/cms-base-distribution" --no-install
ddev composer install
ddev exec touch public/FIRST_INSTALL
ddev launch
```

must create a webserver config where public folder needs to be set as docroot. apache and nginx. **both of them not created actually**. https://my-typo3-site.ddev.site/public/index.php needs to be opened.

Please see following asciicast https://asciinema.org/a/vk7bAkU5dTFDqnWwxFa8nsxan

```
 ITEM             VALUE
 DDEV version     v1.19.1
 architecture     arm64
 db               drud/ddev-dbserver-mariadb-10.3:v1.19.0
 dba              phpmyadmin:5
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.19.0
 docker           20.10.11
 docker-compose   v2.3.3
 docker-platform  colima
 mutagen          0.12.0
 os               darwin
 router           drud/ddev-router:v1.19.0
 web              drud/ddev-webserver:v1.19.0-1
```

### Expected Behavior

public needs to be set as document root

### Steps To Reproduce

Run TYPO3 QuickStart https://ddev.readthedocs.io/en/stable/users/cli-usage/#typo3-quickstart

### Anything else?

Seems not related to TYPO3 as the Laravel QuickStart doesn't also work.

**Comment by rfay** [comment]
I'm unable to recreate this. The Discord discussion was about Apache, so I changed the command to `ddev config --project-type=typo3 --docroot=public --create-docroot --webserver-type=apache-fpm` and it all worked perfectly per the quickstart.

I'm happy to do a call/screenshare with you to see your experience if you're still able to recreate this, but AFAICT it's not an issue hitting others, so there must be some other thing.

Happy to continue the conversation here or elsewhere, but closing this for now.

**Comment by ursbraem** [comment]
I've had the same issue, finally it turned out that the reason was that the site wasn't in the homedir. Colima only mounts the home directory by default as Randy pointed out. https://github.com/drud/ddev/pull/4086/files

**Comment by rfay** [comment]
@josefglatz when you experienced this, were you using a directory that was not in your home directory, and were you using colima? You didn't fill in the requested diagnostic so there wasn't any way I could research this in the end. But if that was the case, @ursbraem and I now understand how to get it. But it wouldn't have anything to do with apache-fpm, it would be the same with apache and nginx.

**Comment by TheNaderio** [comment]
@rfay We experience the same problem on macOS, using colima and projects on a Volume.
As mentioned by @ursbraem, `colima start --mount /Volumes/Somefolder/Somesubfolder` solves the start-problem here too.

This leads to a new problem: `ddev auth ssh` cannot start the ssh agent. 
```
docker: Error response from daemon: invalid mount config for type “bind”: bind source path does not exist: /Users/naderio/.ssh.
```

Possibly docker/colima is searching the .ssh-folder on the volume now.

**Comment by rfay** [comment]
Please use the colima configuration to mount your home directory (which is the default) anad both of these will work.

Your current strategy *only* mounts the explicit folder.

You can also mount multiple folders, in the .colima/default/colima.yaml file. 

```yaml
# Configure volume mounts for the virtual machine.
# Colima mounts user's home directory by default to provide a familiar
# user experience.
#
# EXAMPLE
# mounts:
#   - location: ~/secrets
#     writable: false
#   - location: ~/projects
#     writable: true
#
# Colima default behaviour: $HOME and /tmp/colima are mounted as writable.
# Default: []
mounts: []
```

Or, of course, just use the default behavior (HOME is mounted) and you won't have this problem.
