### ISSUE TITLE
Drush is not found in Backdrop-Installation (project-type: backdrop)

### ISSUE THREAD

**Issue by a8w4** [drud/ddev#3765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

drush command is not found in backdrop-project

### Expected Behavior

drush should start just like in drupal7-project

### Steps To Reproduce

ddev config --project-type=backdrop --docroot=backdrop --create-docrootddev start
ddev ssh
drush is not found
drush8 is found

### Anything else?

There seems to be missing this symbolic link in /usr/local/bin, 
which is present in a drupal7-project:
drush -> /usr/local/bin/drush8*

**Comment by rfay** [comment]
I confirm this. You can use the techniques in https://stackoverflow.com/a/69470611/215713 to work around it very easily.

Is backdrop still dependent on drush8?, or are there other ways to use drush? I think drush8 is fully deprecated now.

Should the DDEV project continue to support Backdrop? We don't see much activity from backdrop users these days. Perhaps they should just use drupal7 project type and we should remove Backdrop?

**Comment by rfay** [comment]
I fixed this, but would love to hear your responses to the questions above. It's been an awfully long time that nobody noticed the missing drush!

**Comment by darby3** [comment]
Not sure what backdrop support entails/provides, but can confirm I've been using ddev to explore backdrop in advance of the drupal 7 end of life!

**Comment by rfay** [comment]
Thanks @darby3 - Explicit support for a project type means having auto-detection, a custom nginx config, and automated tests. But people use lots of project types that have no explicit support. Symfony, custom CMSs, etc etc. So I was just wondering out loud if there's enough usage of Backdrop with DDEV to justify continuing with its explicit support.
