### ISSUE TITLE
WordPress -- created wp-config-ddev.php is missing some settings

### ISSUE THREAD

**Issue by waviaei** [drud/ddev#3767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When non-latin texts (in my case Japanese characters) are saved into database, it is corrupted/garbbled.

I found that this is due to `wp-config-ddev.php` created during `ddev config --project-type=wordpress` is missing following two `define()`

```
/** Database charset to use in creating database tables. */
define( 'DB_CHARSET', 'utf8' );

/** The database collate type. Don't change this if in doubt. */
define( 'DB_COLLATE', '' );
```

These two, particulary the `DB_CHARSET`, when missing, WordPress will save into DB in latin and not utf8. This is not a custom extra setting needs to be added for unusual situation as such. It is coded in `wp-config-sample.php` of the WordPress Core
https://github.com/WordPress/WordPress/blob/master/wp-config-sample.php

### Expected Behavior

`wp-config-ddev.php` created during `ddev config --project-type=wordpress` should include `DB_CHARSET` and `DB_COLLATE` thus non-latin characters should be saved without corrupting.

Currently, to avoid this, after `ddev config --project-type=wordpress` I have to add below lines to autocreated `wp-config.php`, after `ddev wp core install` step, and I also have to drop all tables and restart the install. I expect this fix extra step should not be needed.

```
/** Database charset to use in creating database tables. */
define( 'DB_CHARSET', 'utf8' );

/** The database collate type. Don't change this if in doubt. */
define( 'DB_COLLATE', '' );
```

### Steps To Reproduce

1. launch new WordPress site as per https://ddev.readthedocs.io/en/stable/users/cli-usage/#wordpress-quickstart
2. login into admin, create a new post. Copy and paste below Japanese text.
3. Publish the post.
4. Check the text on the editor and the frontend. Texts are corrupted to something like `~~~~~~~~` (or something similar, sorry, forgot to capture but you will know)

Please try with these Japanese text

For title: 

```
私の個人主義
```

For content: 

```
あなたは先刻まあどんな下宿学として気のためをうろついですます。

すでに生涯に参考心はすこぶるこうした満足ならないかもを申し上げていないをも相当潰さたないて、更にには与えでしございませない。

主義にもっならのは無論今をしかるにたでた。もっと槙さんで矛盾人そうお話をできるあっ人その一つこれか腐敗がというご評だろただうて、その今もどこか泰平空の買うば、大森君の事を手の私の同時にご病気と見えるば私個人にお意味が流行るようにどうか実楽に云っんないので、あたかもさぞ安心の曲げなりてならだろ事をなっですた。すなわちあるいは大素因を云わ事はいろいろ不愉快と弱らでしと、その去就のは充たすですてについてらであるてみありた。こういう上西洋のためこの生徒もあなた上をするたかと大森君が引張りだろでしょ、かたがたの今日ですにおいてご講演ですたましながら、金力のうちに通りに今でもの根本の時間思うているて、それほどの今へしのでこういう以上へついに抱いなくありと喜ぶたものでと、好いましたがこう小他人作ったのでんた。
```

**Comment by waviaei** [comment]
@rfay Thanks. I had a look around and thinking somewhere here that needs to be edited? https://github.com/drud/ddev/blob/0aa4e1d27cd77d73c06b026a0ff0629dac61603d/pkg/ddevapp/wordpress.go#L41-L64

But I am not familiar with go and its build at all, and it would take time and perhaps I will not have time to do it.

**Comment by rfay** [comment]
Should be nothing more than an edit to https://github.com/drud/ddev/blob/master/pkg/ddevapp/wordpress/wp-config-ddev.php but if course I haven't studied carefully. Easy to test manually several ways

**Comment by rawdreeg** [comment]
I am happy to make a PR for this.
