### ISSUE TITLE
XDEBUG not working - wrong host.docker.internal IP in WSL2 environment (docker installed inside)

### ISSUE THREAD

**Issue by Raidri** [drud/ddev#3772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I switched from docker desktop to docker inside WSL2. 

When I try to use xdebug I got this error:
`Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-('`

I found out that ddev set the wrong IP addresse in my` /etc/hosts` file inside the ddev web container. 

`172.17.0.1     host.docker.internal`

If I remove that line xdebug works. ddev always get the wrong IP from the docker bridge network.

Maybe the problem is that docker desktop is already installed but not in use. 
We didn't try to uninstall docker desktop cause of all our active projects.

### Expected Behavior

xdebug works out of the box If I start my ddev project and activate xdebug.

### Steps To Reproduce

1. installed docker desktop (maybe) but not in use
2. install docker inside wsl2
3. start a ddev project
4. activate xdebug
5. ddev logs: could not connect to debugging client
6. connect to ddev web container `ddev ssh`
7. removed the line with the host.docker.internal from `/etc/hosts`
8. xdebug works now

**Comment by MurzNN** [comment]
In the issue https://github.com/drud/ddev/issues/3781 I've found a workaround for the similar problem in Linux, maybe it will work for WSL2 too?

**Comment by rfay** [comment]
If you got this to work by *removing* "removed the line with the host.docker.internal from /etc/hosts"

then I think it means that something else in your environment is providing host.docker.internal - normally that's something that Docker Desktop does.  Do you have Docker Desktop running and integrated with this WSL2 distro?

When it's working, what does host.docker.internal resolve to? (`ping host.docker.internal` inside container to find out)

If you know that, then you *can* fix it using the technique in #3781, but with the correct host.docker.internal value (it won't be 127.0.0.1 in your case)

**Comment by Raidri** [comment]
I had use docker desktop with the same WSL2 distro where I want to install docker inside now. Docker desktop is not running.

So I removed the entry from the /etc/hosts file in the ddev web container and tried ping host.docker.internal: `PING host.docker.internal (192.168.86.35) 56(84) bytes of data.`
But I didn't  get a response from the ping. But PHPStorm  with xdebug works

**Comment by rfay** [comment]
The official docs about WSL2 networking are at https://docs.microsoft.com/en-us/windows/wsl/networking

In this situation (PhpStorm running on Windows, but ddev in WSL2) we're talking about "Accessing Windows networking apps from Linux (host IP)" since PhpStorm is a Windows app that's listening. So the answer in the doc is "Look at /etc/resolv.conf and use the `nameserver` there. ". 

That seems to work in all cases that I've tested. 

It seems that my earlier testing of this was corrupted by a whole pile of different "host.docker.internal" entries that Docker Desktop had put in /etc/hosts and /c/Windows/System32/drivers/etc/hosts over the years. So I assume that's why I thought this was working OK.

So now I guess the thing to do is to get the nameserver from /etc/resolv.conf and use that for host.docker.internal. That should work on both Docker Desktop and docker-inside-wsl2. 

The problem is that there are at least two cases that aren't covered yet:

1. #3781 - where the host.docker.internal should be 127.0.0.1
2. The situation where people are running the linux version of PhpStorm or another IDE inside WSL2. Then the current derivation (using inspection of the docker bridge) is correct.

**Comment by rfay** [comment]
I'm working on this in #4252, but it won't be available in the upcoming release, but the temporary fix is pretty easy. 

This problem probably only happens for people running PhpStorm on Windows itself (not inside WSL2) who have docker-ce installed inside WSL2. 

1. In your WSL2 distro, if you `grep nameserver /etc/resolv.conf`, you'll see something like `nameserver 192.168.96.1`. That's the address that xdebug needs to access your IDE (PhpStorm running on Windows). 
2. In your project, create a file `.ddev/php/xdebug.ini` with the contents:
```ini
xdebug.client_host=<your_nameserver>
```

For example, 
```ini
xdebug.client_host=192.168.96.1
```

Note that another approach to this (especially on Windows 11) is just to run the linux version of PhpStorm inside WSL2, where the host.docker.internal has already been figured out. 

Again, I hope to have a comprehensive approach to this problem in 
* #4252

but for now, this should get you by.

**Comment by derickr** [comment]
FWIW, from Xdebug 3.2 you will be able to use `xdebug.client_host=xdebug://nameserver` (as long as your container doesn't use a linux distribution which uses musl, like alpine).

**Comment by rfay** [comment]
Cool, looking forward to that. When I tested it earlier though, it didn't work inside containers on WSL2. So many layers! looking forward to Xdebug 3.2 arriving in deb.sury.org distributions. (I do wish you'd do your releases on GitHub so I could easily subscribe to more things... but I'll get the info in your Sponsors email.)

BTW, oerdnj doesn't have PHP8.2 xdebug in there yet unfortunately, 
* https://github.com/oerdnj/deb.sury.org/issues/1840

**Comment by rfay** [comment]
With #4242 which just went in, you should be able to do this without workarounds now. `ddev config global --xdebug-ide-location=wsl2` if you're running Phpstorm or vscode inside wsl2.

You can use this latest version with `brew install --HEAD --fetch-head ddev` or several other ways.

**Comment by raphaelcangucu** [comment]
Hi,

For wsl you need to force the client host.

Just open a command prompt:

wsl hostname -I

And this will give the ip:

C:\Users\rapha>wsl hostname -I
172.23.103.149

So them put at you xdebug.ini

xdebug.client_host=172.23.103.149

**Comment by rfay** [comment]
I have heard of people having to do that, but if you can do that, you can also `ddev config global --xdebug-ide-location= 172.23.103.149`, but DDEV does try to figure out what the right IP address is.

**Comment by rfay** [comment]
Opened 
* https://github.com/ddev/ddev/issues/4803

**Comment by rfay** [comment]
@raphaelcangucu I'd sure appreciate if you could give more context on your situation, preferably in #4803. You don't say where you're running your IDE, for example. If you're running it inside WSL2 that makes a big difference. It would also help if you'd say the result of `ddev exec ping host.docker.internal`

**Comment by bernhardberger** [comment]
I can't get xdebug to do anything in PhpStorm 2023.1 after switching from the homebrew install to this method (to rid myself of docker desktop): https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#wsl2-docker-ce-inside-install-script

![image](https://user-images.githubusercontent.com/2110083/231440473-e82c6b7e-8ee3-43fb-b345-35a91309f960.png)

Not even the typical poup on the bottom right with "didn't break, configure servers... "

**Comment by rfay** [comment]
Thanks @bernhardberger - Please create a time on https://cal.com/randyfay/30min - I'll be available mostly today.

**Comment by rfay** [comment]
Also @bernhardberger please take a look at 

* https://github.com/ddev/ddev/issues/4803

which would have been a better place for your comment.

**Comment by bernhardberger** [comment]
```
 cat /etc/resolv.conf
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 172.27.48.1
```

**Comment by rfay** [comment]
@bernhardberger Please try the linux-amd64 binary in https://github.com/ddev/ddev/pull/4813#issuecomment-1508914827

Instructions on testing with it are https://ddev.readthedocs.io/en/latest/developers/building-contributing/#testing-a-pr

Make sure you're using the right binary before continuing, use `ddev --version`. Then `export DDEV_DEBUG=true` and `ddev start` and it should show the way it's gotten the host.docker.internal value. Please provide that info (just show the whole output of `ddev start`)

**Comment by rfay** [comment]
@bernhardberger ping - really hoping you'll be able to try this out as explained above. It's important to figure out why it didn't work in your situation.

**Comment by bernhardberger** [comment]
@rfay I have it on my list of things to do but I need a few days.

**Comment by rfay** [comment]
Thanks. Please prioritize it, as I prioritized a meeting with you to explore this. It should take less than 15 minutes. This is important for you and other WSL2 users.

**Comment by rfay** [comment]
Sure hoping to have your results @bernhardberger so we can learn what happened in your situation and help others not to have that.

**Comment by bernhardberger** [comment]
@rfay I am sorry that it took me this long, the past few days were pretty crazy on my end.

```bash
ddev start
Starting ddev-debug...
Pulling image for drud/ddev-webserver:20230315_drush8
Pulling image for busybox:stable
Pulling image for drud/ddev-ssh-agent:v1.21.5
Pulling image for traefik:v2.9
resolv.conf=# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 172.27.48.1

host.docker.internal='172.27.48.1' because IsWSL2 and !IsDockerDesktop; received from resolv.conf
resolv.conf=# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 172.27.48.1

Pulling image for drud/ddev-dbserver-mariadb-10.4:v1.21.5
Pulling image for phpmyadmin:5
Pulling image for drud/ddev-webserver:20230315_drush8
Pulling image for traefik:v2.9
Pulling image for drud/ddev-ssh-agent:v1.21.5
Executing docker-compose -f /home/beb/ddev-debug/.ddev/.ddev-docker-compose-full.yaml up --build -d
Network ddev-ddev-debug_default  Created
Container ddev-ddev-debug-dba  Started
Container ddev-ddev-debug-web  Started
Container ddev-ddev-debug-db  Started
Copied /mnt/c/Users/b.berger/AppData/Local/mkcert:CopyIntoVolume_xkxgmencwfyx into /mnt/v/mkcert in 199.218163ms
Exec chown -R 1000 /mnt/v/mkcert stdout=, stderr=, err=<nil>
Pushed mkcert rootca certs to ddev-global-cache/mkcert
VIRTUAL_HOST=ddev-debug.ddev.site for dba
HTTP_EXPOSE=8036:80 for dba
HTTPS_EXPOSE=8037:80 for dba
VIRTUAL_HOST=ddev-debug.ddev.site for web
HTTP_EXPOSE=80:80,8025:8025 for web
HTTPS_EXPOSE=443:80,8026:8025 for web
Copied /home/beb/ddev-debug/.ddev/traefik:CopyIntoVolume_xwbwdbpppmfo into /mnt/v/traefik in 184.705397ms
Exec chown -R 1000 /mnt/v/traefik stdout=, stderr=, err=<nil>
Copied traefik certs in /home/beb/ddev-debug/.ddev/traefik/certs to ddev-global-cache/traefik
Testing to see if /mnt/ddev_config is properly mounted
Copied /home/beb/.ddev/traefik:CopyIntoVolume_lpewvzoogsgy into /mnt/v/traefik in 123.681776ms
Exec chown -R 1000 /mnt/v/traefik stdout=, stderr=, err=<nil>
Copied global traefik config in /home/beb/.ddev/traefik/certs to ddev-global-cache/traefik
Container ddev-router  Started
Successfully started ddev-debug
Project can be reached at https://ddev-debug.ddev.site https://127.0.0.1:32788
Instrumentation is opted in, but SegmentKey is not available. This usually means you have a locally-built ddev binary or one from a PR build. It's not an error. Please report it if you're using an official release build.
```

**Comment by rfay** [comment]
Thanks @bernhardberger - It says `host.docker.internal='172.27.48.1' because IsWSL2 and !IsDockerDesktop; received from resolv.conf` - that isn't what we found is it? What does `ddev exec ping host.docker.internal` result in? And is 127.27.48.1 what's in your WSL2 /etc/resolv.conf?

**Comment by bernhardberger** [comment]
```bash
ddev exec ping host.docker.internal
PING host.docker.internal (172.27.48.1) 56(84) bytes of data.
```

**Comment by rfay** [comment]
@bernhardberger I think I caught the bug that caused you trouble in https://github.com/ddev/ddev/pull/4852/commits/a5f5ea55eaa087c5f800d32fad8b9a875277de3e

* https://github.com/ddev/ddev/pull/4852

**Comment by bernhardberger** [comment]
> So... it works fine now @bernhardberger , without any extra configuration on your system? I should have taken notes when we looked at this, but I know that host.docker.internal was not the same as what was in your resolv.conf when we looked at it.

Unfortunately I caught this at a very busy time and I haven't been as helpful on this as I wanted to be - I'm sorry about that.

I faintly remember having multiple IPs returned by (*I think*) `wsl hostname -I` and ddev taking the wrong one. Unfortunately after reverting back to the docker desktop install method I wasn't able to reproduce this anymore after switching back again to WSL2 witch docker inside.

If it helps, here a brief history/timeline of my ddev/WSL2 setup:
- originally Docker Desktop + linux homebrew ddev install
- migrated to ddev apt package and uninstalled brew version
- uninstalled Docker Desktop and moved to WSL2 + Docker CE Inside Install Script (this is where it started breaking and I reported my issue in this ticket)
- panicked and reverted back to Docker Desktop as I desperately needed xdebug to work
- upgraded WSL2 to the latest preview release because of issues with the latest stable + Docker Desktop
- we scheduled the call and I uninstalled Docker Desktop and moved to WSL2 with docker inside again
- was broken again, unless I added the php.ini with the correct IP
- haven't touched it since

Things finally have calmed down on my end, if I can do anything to verify a fix / provide further infos I'm happy to take all the time it needs!

I really appreciate you being so helpful and supporting ddev to the extent you do!

**Comment by rfay** [comment]
Thanks for testing. I'm pretty sure that PR solved the problem you had. Finally it happened to me so I was able to study it. 

You can also now use HEAD, https://ddev.readthedocs.io/en/latest/developers/building-contributing/#testing-latest-commits-on-head

**Comment by maciejsamotyj** [comment]
I had the same. This xdebug ini configuration solved the problem (params` xdebug.start_with_request` and `xdebug.client_port`)
```
[Xdebug]
zend_extension=xdebug.so
xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.client_host=host.docker.internal

;# 9003 is now the default (set this for old PhpStorm settings).
xdebug.client_port=9000
```

source:
https://stackoverflow.com/questions/64776338/xdebug-3-the-setting-xdebug-remote-has-been-renamed-see-the-upgrading-g

**Comment by rfay** [comment]
If you have to change to port 9000 it must mean you're using a really old or misconfigured IDE...

**Comment by joshsedl** [comment]
I am pretty much in the same situation as @bernhardberger

I recently switched from Docker Desktop + WSL2 to docker-ce + WSL 2, as I saw, that docker-ce is the recommended way to use ddev. But unfortunately, Xdebug seems to not work anymore now.

I have installed VSCode in Windows, but I am attaching VSCode to the ddev-webserver container.

Already disabled the firewall (both windows defender and the firewall inside WSL2 Ubuntu using `sudo ufw disable`) and tinkered with both the `dev config global --xdebug-ide-location=` (which used to be "container" for docker desktop) and the `xdebug.client_host` custom ini using both the ip shown by `ddev exec ping host.docker.internal` and `grep nameserver /etc/resolv.conf`.

Output of `grep nameserver /etc/resolv.conf` inside wsl:
~~~
nameserver 10.255.255.254
~~~
(shouldn't matter as VSCode is [attached](https://code.visualstudio.com/docs/devcontainers/attach-container) to the ddev webserver)

Output of `ddev exec ping host.docker.internal`:
~~~
PING host.docker.internal (172.28.64.1) 56(84) bytes of data.
64 bytes from host.docker.internal (172.28.64.1): icmp_seq=1 ttl=127 time=0.279 ms
64 bytes from host.docker.internal (172.28.64.1): icmp_seq=2 ttl=127 time=0.354 ms
64 bytes from host.docker.internal (172.28.64.1): icmp_seq=3 ttl=127 time=0.461 ms
64 bytes from host.docker.internal (172.28.64.1): icmp_seq=4 ttl=127 time=0.398 ms
~~~

Interestingly enough, when I run `telnet host.docker.internal 9003` I get the following output:
~~~
telnet host.docker.internal 9003
Trying 172.28.64.1...
telnet: Unable to connect to remote host: Connection refused
~~~

And having xdebug enabled and running anything (e.g. `ddev drush cr` Drupal) I get:
~~~
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port)
~~~

I used to get the same message with Docker Desktop, but xdebug still worked anyway and I enabled xdebug just for a quick debug, so it never really mattered to me.

This is my xdebug VSCode script:
~~~
{
  // See https://code.visualstudio.com/docs/editor/debugging#_launch-configurations
  // for the documentation about the launch.json format
  "version": "0.2.0",
  "configurations": [
      {
          "name": "Listen for Xdebug",
          "type": "php",
          "request": "launch",
          "hostname": "127.0.0.1",
          "port": 9003,
          "pathMappings": {
              "/var/www/html": "${workspaceFolder}"
          },
          "preLaunchTask": "DDEV: Enable Xdebug",
          "postDebugTask": "DDEV: Disable Xdebug"
      }
  ]
}
~~~

**Comment by rfay** [comment]
@joshsedl it's a long time since the post you're saying you have the same problem, and DDEV's approach to getting host.docker.internal changed since then. Please make sure you're running current DDEV v1.23.4, and open a new issue with the full information and the requested `ddev debug test`, thanks.

As shown in the docs, your hostname in launch.json should be 0.0.0.0, not 127.0.0.1

**Comment by joshsedl** [comment]
Thanks @rfay with the fast reply!

>As shown in the docs, your hostname in launch.json should be 0.0.0.0, not 127.0.0.1

Ouch, I hope that's not it 😅. I'll see if I figure it out and create a new issue otherwise, thanks!

**Comment by tyler36** [comment]
> I have installed VSCode in Windows, but I am attaching VSCode to the ddev-webserver container.

So your running VScode Dev Containers and are working side the web container?  "Container ddev/ddev-webserver:v1.23.4-...." shows in the bottom left.

**Comment by joshsedl** [comment]
Ok, just wanted to update ddev from v1.23.3 to v1.23.4 through choco, but received an error and the logs weren't very helpful.

Decided to just install ddev through the linux installation script in wsl instead `curl -fsSL https://raw.githubusercontent.com/ddev/ddev/master/scripts/install_ddev.sh | bash` (as I am not really a big fan of the whole choco passing ddev to wsl thing in general, but I tried it, as it was the recommended approach).

And now with the newly installed `v1.23.4` xdebug works like a charm again!

Small sidenote: both 0.0.0.0 and

**Comment by rfay** [comment]
There have been no changes in how xdebug works between v1.23.3 and v1.23.4. And the Chocolatey windows-side install has nothing to do with xdebug either (it's only used for escalating for hosts file updates when needed).  The preferred way to install and upgrade DDEV in wsl2 is `sudo apt update && sudo apt upgrade`

Glad it's working!

**Comment by rfay** [comment]
The official upgrade instructions for WSL2: https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/#windows
