### ISSUE TITLE
Improve opening description in project readme

### ISSUE THREAD

**Issue by beeradb** [drud/ddev#378]
## What happened (or feature request):
I really think we could do with a stronger “mission statement” for ddev. The opening paragraph on the project page is: 

“The purpose of ddev is to help Drupal and WordPress developers abstract away the complexity and effort of adopting and maintaining a docker based local development stack. You can see all “ddev” usages using the help commands, like ddev -h, ddev start -h, etc.”

I'm not sure that fully captures our goals, or leaves the uninitiated with a better understanding of what the project is. 

## What you expected to happen:
I expect someone who has never heard of the project to be able to read the opening paragraph of the project description and walk away with at least a base level understanding of what we're trying to achieve.

Something along the lines of “The purpose of ddev is to provide a docker-based local development environment for PHP apps. ddev aims to provide human readable configuration files which can be stored in version control and shared with other developers on a project”

## Anything else do we need to know:
Here are some examples from other projects we respect and/or are competing with:

#### Docker/Moby
Moby is an open-source project created by Docker to advance the software containerization movement. It provides a “Lego set” of dozens of components, the framework for assembling them into custom container-based systems, and a place for all container enthusiasts to experiment and exchange ideas.

#### Kubernetes
“Kubernetes is an open source system for managing containerized applications across multiple hosts, providing basic mechanisms for deployment, maintenance, and scaling of applications.

Kubernetes builds upon a decade and a half of experience at Google running production workloads at scale using a system called Borg, combined with best-of-breed ideas and practices from the community.”

#### DrupalVM
“Drupal VM makes building Drupal development environments quick and easy, and introduces developers to the wonderful world of Drupal development on virtual machines or Docker containers (instead of crufty old MAMP/WAMP-based development).”

#### Lando
“Lando seeks to provide stored-in-version-control, single-config-file and per-app configuration to manage the dependencies a project needs to run and developers need to develop. It aims to be easy to use and fast.”

#### Kalabox 
“Kalabox is a free and open source local development environment and workflow tool based on (Docker) container technology. Kalabox allows users to spin up hyper-customized, super-fast development environments and to integrate those environments with their hosting provider or continuous integration workflows.”

#### Terraform
"Terraform is a tool for building, changing, and versioning infrastructure safely and efficiently. Terraform can manage existing and popular service providers as well as custom in-house solutions."

#### Vault
"Vault is a tool for securely accessing secrets. A secret is anything that you want to tightly control access to, such as API keys, passwords, certificates, and more. Vault provides a unified interface to any secret, while providing tight access control and recording a detailed audit log."

**Comment by tannerjfco** [comment]
Here's a stab at it:

"ddev is an open source tool that provides quick and easy to use local development environments for PHP applications. With shareable and extendable environment configurations for every project, ddev aims to allow development teams to leverage the benefits of Docker in their workflow without having to face the upfront complexities."

**Comment by beeradb** [comment]
Much improved!  Here's a stab at a slightly modified version with @tannerjfco as a base:

"ddev is an open source tool that gets easy to use development environments for PHP applications up and running in just minutes. With shareable and extendable environment configurations for every project, ddev aims to allow development teams to leverage the power and flexibility of Docker in their workflow without the complexities of bespoke configuration."

**Comment by rickmanelius** [comment]
I like where this is going. When I'm back in front of my laptop, I might want to take a stab at a modification but I think we should be able to get the change in today for sure. Thanks!

**Comment by rickmanelius** [comment]
Another variation:

"ddev is an open source tool that makes it dead simple to get local PHP development environments up and running within minutes. With shareable and extendable environment configurations for every project, ddev aims to allow development teams to leverage the power and flexibility of Docker in their workflow without having to invest significant time and effort when addressing its upfront complexities."

Honestly, I'm over-optimizing at this time, so if either Brad or Tanner feel strongly at another turn at it, I'm happy to approve the next iteration or if there are no objections to what I proposed, opening a PR and getting that merged in as is.

**Comment by rickmanelius** [comment]
I actually also like what @tannerjfco had generated in [RTD](https://ddev.readthedocs.io/en/latest/): 

"ddev is a local web development environment management system powered by Docker and Docker Compose. It provides rapid, repeatable, and destructible environments geared for Drupal and WordPress development."

**Comment by rickmanelius** [comment]
@beeradb @rfay @tannerjfco Here's one more iteration:

"ddev is an open source tool that makes it dead simple to get local PHP development environments up and running within minutes. It's powerful and flexible as a result of its per-project environment configurations, which can be extended, version controlled, and shared. In short, ddev aims to allow development teams to use Docker in their workflow without the complexities of bespoke configuration."

And if there are still issue with this variation, I'm just going to go with @beeradb's and update the PRs :)

**Comment by rfay** [comment]
That works for me. Thanks!

**Comment by beeradb** [comment]
Works for me.

**Comment by rickmanelius** [comment]
Alright that's 3 votes up. I'll get the PR's updated. Thanks!
