### ISSUE TITLE
Customize PHPMyAdmin with a config.user.inc.php file

### ISSUE THREAD

**Issue by MurzNN** [drud/ddev#3791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I want to have some custom settings for PHPMyAdmin applied by default, for example to not group databases by prefix (`NavigationTreeEnableGrouping = false`) and show blobs contents as text (`ShowBlob = true`).

### Describe the solution you'd like

Solution for this problem is mounting the `/etc/phpmyadmin/config.user.inc.php` file into the Docker image, [regarding to docs](https://docs.phpmyadmin.net/en/latest/setup.html#customizing-configuration).
And here is example of this file contents for my situation:
```php
<?php
$cfg['NavigationTreeEnableGrouping'] = false;
$cfg['ShowBlob'] = true;
```

If this is already possible, please describe how to do this.

**Comment by rfay** [comment]
You could already do this with a `build` stanza in a `docker-compose.phpmyadmin.yaml` I imagine, but really, phpmyadmin should be moving out of default ddev and into an add-on in v1.20. You may want to pioneer that addon!

**Comment by rfay** [comment]
* Add .ddev/docker-compose.phpmyadmin.yaml with contents:
```yaml
services:
  dba:
    build:
      context: ./phpmyadmin
    image: phpmyadmin-${DDEV_SITENAME}-built
```
*  `mkdir .ddev/phpmyadmin`
* Create .ddev/phpmyadmin/Dockerfile with contents:
```yaml
FROM phpmyadmin:5
ADD config.user.inc.php /etc/phpmyadmin/config.user.inc.php
```
* Copy your config.user.inc.php into .ddev/phpmyadmin
* `ddev restart`

You can change the config at will.

Please let me know how this goes.

**Comment by rfay** [comment]
Closing, no response from OP, but this approach works fine for this need. Maybe it will help somebody else.
