### ISSUE TITLE
brew install drud/ddev/ddev --HEAD fails

### ISSUE THREAD

**Issue by josefglatz** [drud/ddev#3794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Installing DDEV --HEAD with homebrew in macOS fails with following error message

```
time="2022-05-03T09:43:07Z" level=fatal msg="\x1b[31mUnable to get docker context: unable to run 'docker context inspect' - please make sure docker client is in path and up-to-date: exec: \"docker\": executable file not found in $PATH\x1b[0m"
```

### Current Behavior

```
➜  ~ brew unlink ddev && brew install drud/ddev/ddev --HEAD
Unlinking /usr/local/Cellar/ddev/1.19.1... 0 symlinks removed.
==> Cloning https://github.com/drud/ddev.git
Updating /Users/jglatz/Library/Caches/Homebrew/ddev--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at cd8f83d0 Support MariaDB 10.7, fixes #3759 (#3783)
==> Installing ddev from drud/ddev
==> make VERSION=vHEAD-cd8f83d COMMIT=vHEAD-cd8f83d
==> mkdir -p /usr/local/Cellar/ddev/HEAD-cd8f83d/bin
==> cp .gotmp/bin/darwin_amd64/ddev /usr/local/Cellar/ddev/HEAD-cd8f83d/bin/ddev
==> .gotmp/bin/darwin_amd64/ddev_gen_autocomplete
Last 15 lines from /Users/jglatz/Library/Logs/Homebrew/ddev/04.ddev_gen_autocomplete:
2022-05-03 09:43:06 +0000

.gotmp/bin/darwin_amd64/ddev_gen_autocomplete

time="2022-05-03T09:43:07Z" level=fatal msg="\x1b[31mUnable to get docker context: unable to run 'docker context inspect' - please make sure docker client is in path and up-to-date: exec: \"docker\": executable file not found in $PATH\x1b[0m"

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/drud/homebrew-ddev/issues

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.
```

### Expected Behavior

Installing ddev --HEAD with `brew unlink ddev && brew install drud/ddev/ddev --HEAD` must end with a working `ddev` executable.

### Steps To Reproduce

`brew unlink ddev && brew install drud/ddev/ddev --HEAD`

### Anything else?

-

**Comment by rfay** [comment]
Thanks - it's important to have this fixed. I'll try to sort it out.

**Comment by rfay** [comment]
Please take a look and see if this already works for you, `brew update && brew install --HEAD drud/ddev/ddev`

**Comment by josefglatz** [comment]
# Test on Intel, macOS, Catalina

It worked out by doing following steps:

```bash
brew unlink ddev && brew update && brew install --HEAD drud/ddev/ddev # failed as no docker client was found

brew update && brew install docker && brew link --overwrite docker # as Docker Desktop for Mac were linked before

brew unlink ddev && brew update && brew install --HEAD drud/ddev/ddev # works! no errormessage

ddev --version # results in: ddev version vHEAD-4af55ef
```


Did I understand you correct @rfay in discord? the homebrew formulae `docker` must be installed before, right?

**Comment by rfay** [comment]
The problem with conflicts over the docker client is why I went the other direction with the second PR; I didn't want people to have that experience. 

The second PR has now been merged, and I reverted the homebrew-ddev setup that requires docker client for building HEAD. You should now be able to `brew update && brew install --HEAD ddev` without any of that trouble. 

You'll probably want to repair the Docker Desktop docker client link. Normally it looks like "docker -> /Applications/Docker.app/Contents/Resources/bin/docker". Probably `ln -sf  /Applications/Docker.app/Contents/Resources/bin/docker /usr/local/bin/docker` would fix it.

**Comment by rfay** [comment]
BTW, you catching this in advance saved me quite a lot of pain at release time. This would have affected normal brew update as well, it just hadn't happened yet. Thanks for finding it, reporting, and testing.
