### ISSUE TITLE
Drush 8.4.10 "make" command throws fatal error if makefile is YML and drush is phar

### ISSUE THREAD

**Issue by ssudhak** [drud/ddev#3809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

1. upgrade drush to 8.4.10
drush  status
 Drupal version         :  7.89
 PHP configuration      :  /usr/local/etc/php/php.ini
 PHP OS                 :  Linux
 Drush script           :  /usr/local/bin/drush8
 Drush version          :  8.4.10

2. run make command  - drush make -y make.yml

### Current Behavior

throws following error

PHP Fatal error:  Uncaught Error: Class "Drush\Internal\Symfony\Yaml\Yaml" not found in phar:///usr/local/bin/drush8/lib/Drush/Make/Parser/ParserYaml.php:26
Stack trace:
#0 phar:///usr/local/bin/drush8/commands/make/make.utilities.inc(662): Drush\Make\Parser\ParserYaml::parse('core: 7.x\napi: ...')
#1 phar:///usr/local/bin/drush8/commands/make/make.utilities.inc(40): _make_determine_format('core: 7.x\napi: ...')
#2 phar:///usr/local/bin/drush8/commands/make/make.utilities.inc(15): _make_parse_info_file('make.yml')
#3 phar:///usr/local/bin/drush8/commands/make/make.drush.inc(309): make_parse_info_file('make.yml')
#4 phar:///usr/local/bin/drush8/includes/command.inc(422): drush_make('make.yml')
#5 phar:///usr/local/bin/drush8/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#6 phar:///usr/local/bin/drush8/includes/command.inc(199): drush_command('make.yml')
#7 phar:///usr/local/bin/drush8/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#8 phar:///usr/local/bin/drush8/includes/preflight.inc(67): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#9 phar:///usr/local/bin/drush8/includes/startup.inc(465): drush_main()
#10 phar:///usr/local/bin/drush8/includes/startup.inc(369): drush_run_main(false, '/', 'Phar detected. ...')
#11 phar:///usr/local/bin/drush8/drush(114): drush_startup(Array)
#12 /usr/local/bin/drush8(14): require('phar:///usr/loc...')
#13 {main}
  thrown in phar:///usr/local/bin/drush8/lib/Drush/Make/Parser/ParserYaml.php on line 26

Fatal error: Uncaught Error: Class "Drush\Internal\Symfony\Yaml\Yaml" not found in phar:///usr/local/bin/drush8/lib/Drush/Make/Parser/ParserYaml.php:26
Stack trace:
#0 phar:///usr/local/bin/drush8/commands/make/make.utilities.inc(662): Drush\Make\Parser\ParserYaml::parse('core: 7.x\napi: ...')
#1 phar:///usr/local/bin/drush8/commands/make/make.utilities.inc(40): _make_determine_format('core: 7.x\napi: ...')
#2 phar:///usr/local/bin/drush8/commands/make/make.utilities.inc(15): _make_parse_info_file('make.yml')
#3 phar:///usr/local/bin/drush8/commands/make/make.drush.inc(309): make_parse_info_file('make.yml')
#4 phar:///usr/local/bin/drush8/includes/command.inc(422): drush_make('make.yml')
#5 phar:///usr/local/bin/drush8/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#6 phar:///usr/local/bin/drush8/includes/command.inc(199): drush_command('make.yml')
#7 phar:///usr/local/bin/drush8/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#8 phar:///usr/local/bin/drush8/includes/preflight.inc(67): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#9 phar:///usr/local/bin/drush8/includes/startup.inc(465): drush_main()
#10 phar:///usr/local/bin/drush8/includes/startup.inc(369): drush_run_main(false, '/', 'Phar detected. ...')
#11 phar:///usr/local/bin/drush8/drush(114): drush_startup(Array)
#12 /usr/local/bin/drush8(14): require('phar:///usr/loc...')
#13 {main}
  thrown in phar:///usr/local/bin/drush8/lib/Drush/Make/Parser/ParserYaml.php on line 26
Drush command terminated abnormally due to an unrecoverable error.                                [error]
Error: Uncaught Error: Class "Drush\Internal\Symfony\Yaml\Yaml" not found in
phar:///usr/local/bin/drush8/lib/Drush/Make/Parser/ParserYaml.php:26
Stack trace:
#0 phar:///usr/local/bin/drush8/commands/make/make.utilities.inc(662):
Drush\Make\Parser\ParserYaml::parse('core: 7.x\napi: ...')
#1 phar:///usr/local/bin/drush8/commands/make/make.utilities.inc(40):
_make_determine_format('core: 7.x\napi: ...')
#2 phar:///usr/local/bin/drush8/commands/make/make.utilities.inc(15):
_make_parse_info_file('make.yml')
#3 phar:///usr/local/bin/drush8/commands/make/make.drush.inc(309):
make_parse_info_file('make.yml')
#4 phar:///usr/local/bin/drush8/includes/command.inc(422): drush_make('make.yml')
#5 phar:///usr/local/bin/drush8/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#6 phar:///usr/local/bin/drush8/includes/command.inc(199): drush_command('make.yml')
#7 phar:///usr/local/bin/drush8/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#8 phar:///usr/local/bin/drush8/includes/preflight.inc(67):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#9 phar:///usr/local/bin/drush8/includes/startup.inc(465): drush_main()
#10 phar:///usr/local/bin/drush8/includes/startup.inc(369): drush_run_main(false, '/', 'Phar
detected. ...')
#11 phar:///usr/local/bin/drush8/drush(114): drush_startup(Array)
#12 /usr/local/bin/drush8(14): require('phar:///usr/loc...')
#13 {main}
  thrown in phar:///usr/local/bin/drush8/lib/Drush/Make/Parser/ParserYaml.php, line 26

### Expected Behavior

Drush make builds out the Drupal site.

**Comment by rfay** [comment]
When you create and issue and then close it, it's nice to tell people why you closed it, since someone else might have the same problem someday.

**Comment by ssudhak** [comment]
Sorry for the confusion, was supposed to be raising this issue in drush github. Wrongly added here.
