### ISSUE TITLE
Improve documentation if mutagen is enabled globally

### ISSUE THREAD

**Issue by josefglatz** [drud/ddev#3821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

-

### Expected Behavior

-

**Comment by rfay** [comment]
Thanks for this. FYI when the issue creation doesn't add any value (like this time) you don't have to create an issue.

**Comment by josefglatz** [comment]
> Thanks for this. FYI when the issue creation doesn't add any value (like this time) you don't have to create an issue.

Thank you Randy! Thought everything needs an issue like in the TYPO3 core ;-P
