### ISSUE TITLE
Requests from the WebContainer to the nginx server itself are always HTTPS = OFF

### ISSUE THREAD

**Issue by brannow** [drud/ddev#3829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

software: 

ddev version v1.19.1

nginx version: nginx/1.20.2
built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
built with OpenSSL 1.1.1k  25 Mar 2021

### Current Behavior

Requests from the webcontainer to itself, result in php $_SERVER['HTTPS'] is always "off" even with https://... or on 443 port.

execute from inside the container:
```
echo | openssl s_client -alpn h2 -connect PROJECTNAME.ddev.site:443 | grep ALPN
```
got: `No ALPN negotiated`

### Expected Behavior

expected:  `ALPN protocol: http/1.1` or `ALPN protocol: h2`

and in PHP that $_SERVER['HTTPS'] is ON

### Steps To Reproduce

ddev start - start up a generic (php) project with nginx as webserver software
ddev ssh - go into ddev web container
execute:
```
echo | openssl s_client -alpn h2 -connect PROJECTNAME.ddev.site:443 | grep ALPN
```

### Anything else?

My current Workaround is to use apache instead of nginx but would be nice if nginx also is able to accept local calls with https => on

**Comment by tyler36** [comment]
Just tested on 2 different PCs. Both are using WSL Ubuntu & the same NGINX project.

```
verify return:1
depth=0 O = mkcert development certificate, OU = root@932866e46358
verify return:1
ALPN protocol: h2
DONE
```


```
verify return:1
depth=0 O = mkcert development certificate, OU = root@51018fabfea2
verify return:1
ALPN protocol: h2
DONE
```

The 2nd here, doesn't have HTTPS working for some reason though (different issue I think)

**Comment by brannow** [comment]
@tyler36 Thx for the testing and reply,

could you pls confirm that you execute this INSIDE ddev (`ddev ssh`) and not from the "host"?
also can you pls provide your ddev/docker + nginx versions

on the host: `ddev version`
inside ddev container: `nignx -v`

thx

**Comment by rfay** [comment]
@brannow https termination is done on ddev-router, not in the web container, so all SSL activity is intended to be done to there. As a courtesy, and to allow direct-port-binds with port 443, https is in face running in port 443 inside the container, but nothing is done with that unless you deliberately use the direct-bind URL on localhost. 

So please test what ddev-router does, rather than testing https inside the container; like I say that's never used. 

Or explain what it is specifically that you're trying to accomplish. 

If you have an application that is trying to call itself, curl `https://<project>.ddev.site` instead of `https://localhost`. That will go through the ddev-router and be terminated in a normal way.

**Comment by brannow** [comment]
I have a TYPO3 Installation with Solr.

my_project is configured to only accept HTTPS request and my routing required it.

To Index the application "pages" into solr, the solr indexer crawled all pages via curl, for example, he call https://myproject.ddev.site/page_a/sub_a to get the html from it,

a valid use case, also examples a site calls itself for cachewarmup or other things.

The problem is that every call from the web container is $_SERVER['HTTPS']=OFF in php.
so my application route-matcher cannot find a route, cuz its a non-secure call and did not load the config so it ends in a 404. 

this only happen with nginx, apache works (not perfect) but the requests are marked a as $_SERVER['HTTPS']=ON

> If you have an application that is trying to call itself, curl https://<project>.ddev.site instead of https://localhost. That will go through the ddev-router and be terminated in a normal way.

this is the thing, its not working, or at least its still $_SERVER['HTTPS']=OFF,

 i tried both ways, and both result in the same non-secure connection

**Comment by jonaseberle** [comment]
https://myproject.ddev.site/page_a/sub_a is correct.

Ignore `$_SERVER['HTTPS']` and use the other proxy-relevant fields instead if you really need to check if the *client* has initiated an https:// request. TYPO3 does that for you usually. Check the core code around `NormalizedParams` if you need something similar. It is basic stuff for modern apps.

**Comment by rfay** [comment]
Again @brannow 

> If you have an application that is trying to call itself, curl https://<project>.ddev.site instead of https://localhost. That will go through the ddev-router and be terminated in a normal way.

**Comment by brannow** [comment]
@jonaseberle thx for the reply, 
### A bit offtopic (typo3 HTTPS detection): 
Indeed TYPO3 as a framework handles the Request in the core code, this way https://github.com/TYPO3/typo3/blob/main/typo3/sysext/core/Classes/Utility/GeneralUtility.php#L2549 as you can see this.

It starts in the ServerRequestFactory `GeneralUtility::getIndpEnv('TYPO3_REQUEST_URL')` that recursivly calls `self::getIndpEnv('TYPO3_REQUEST_HOST')` -> `self::getIndpEnv('TYPO3_SSL')` -> that calls `self::webserverUsesHttps()` that decides if the core handle it as HTTPS downgrade it to HTTP. 

### sry for the oftopic, back to ddev

@rfay I created an new empty TYPO3 Project and in this it works like you said, 

but it clearly did not work on other projects for me, for now I try to pinpoint the breaking element down.

**Comment by rfay** [comment]
Glad you got it sorted out! I'm surprised you're using `ddev.local` - what's up with that? So much easier to use ddev.site, which has been the default for years now.
