### ISSUE TITLE
ddev-router doesn't unbind from extra ports when project stops

### ISSUE THREAD

**Issue by njt1982** [drud/ddev#3830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I have a ddev app which uses Elastic, so when it starts ddev-router binds to port 9200.

When I `ddev stop` the ddev-router does not unbind from 9200.

This means my other projects that use port 9200 dont start unless I poweroff ddev.

### Describe the solution you'd like

It'd be nice if the router cleaned up (like "garbage collection") ports that are no longer needed when you stop a project without needing to poweroff the entire thing.

### Describe alternatives you've considered

well... I considered poweroff ;) It's a valid workaround, but not entirely convenient.

**Comment by jonaseberle** [comment]
Does `ddev stop` help, too?

**Comment by rfay** [comment]
The issue is that ddev-router (apparently) doesn't unbind from an extra port when `ddev stop` is done. Nobody has ever noticed/complained about that before, but it seems to be the case. 

* `ddev start` a project with Elasticsearch, for example.
* Verify that 9200 is bound.
* `ddev stop`
* Try to do something else with the port (`nc -l 9200`) and it will show occupied
* `ddev poweroff` and you can do it.

**Comment by rfay** [comment]
Related:
#3458 involves completely replacing the router

**Comment by njt1982** [comment]
@longwave I believe you confirmed the same behaviour on your Linux/Docker system (I was using OSX + Colima) when we discussed this in Slack yesterday afternoon?

**Comment by rfay** [comment]
Oh, I remember one issue with this... It's not just about ddev-router. The ddev-router container would always have to be restarted on `ddev stop` by any project if this worked the way you want, and thus is a performance issue.

**Comment by njt1982** [comment]
@rfay is that because the containers network config would have changed?

Is the `update` docker function helpful here? https://docs.docker.com/engine/reference/commandline/service_update/#add-or-remove-network

**Comment by rfay** [comment]
Related:
* https://github.com/drud/ddev/issues/3458

**Comment by rfay** [comment]
This request would require restarting ddev-router during ddev stop, regardless of Traefik or otherwise. I'm not sure that is worth doing, but interested in hearing. It would slow down `ddev stop`.

**Comment by rfay** [comment]
I don't think this can be done in a "happy" way. It will either cost extra overhead on `ddev stop` or on `ddev start`. I think we should leave it as is. Happy to continue the conversation here or elsewhere.
