### ISSUE TITLE
phpmyadmin:5 docker image is broken, so phpmyadmin is asking for login

### ISSUE THREAD

**Issue by richardfrankza** [drud/ddev#3837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

PHPmyadmin image is not connecting to the database automatically. I get a login screen and when typing in credentials I get an error "mysqli::real_connect(): (HY000/2002): No such file or directory"

Someone borked the official phpmyadmin image. Please see here:

https://github.com/phpmyadmin/docker/issues/365

### Expected Behavior

PHPmyadmin should be able to connect automatically to the database

### Steps To Reproduce

Clean install
```
brew install drud/ddev/ddev
ddev start -y
```
Try vist phpmyadmin

### Anything else?

Suggest pinning phpmyadmin and reviewing it rather than using the bleeding edge latest version.

**Comment by rfay** [comment]
Thanks for reporting and chasing this.  I note that the hostname must be broken too, because even logging in with db/db or root/root doesn't work.

The official image has been good for years, so not sure it's worth pinning it. Before we started using phpmyadmin:5 we were always running something too old and with security issues, etc.

I expect that in the v1.20 release cycle phpmyadmin will be removed from the default ddev setup and replace with an addon, so people can use adminer or whatever they like. Lots of people don't use phpmyadmin.

Please update when they've got it sorted.

**Comment by rfay** [comment]
Oh yay, the DDEV tests actually started catching this already, https://buildkite.com/drud/ddev-macos-m1/builds/2227#f2e18add-8590-4bcf-bcd0-870d37c31c89

**Comment by rfay** [comment]
I see the upstream problem has been closed, but there's not a new image yet.

**Comment by rfay** [comment]
This is fixed by the image being fixed upstream now. If it's still affecting you, `docker pull phpmyadmin:5` and you should be good.

**Comment by rfay** [comment]
@richardfrankza thanks so much for finding, chasing, reporting. Now we have to restart gobs of tests :)

**Comment by alanmels** [comment]
Has this been committed as we have to do it every single time?

**Comment by rfay** [comment]
This was fixed upstream a month ago, and the issue only happened for about 36 hours IIRC. What do you mean "We have to do it every single time". What is it you have to do? `docker pull phpmyadmin:5` ? That would only be done once on each affected machine to fix it by getting a working phpmyadmin image.

**Comment by alanmels** [comment]
@rfay, thanks for the update. We have `ddev version v1.19.2` and have to pull pma 5 for every new project we deploy. Does that mean we need to upgrade ddev and then wouldn't have to repeat pulling pma 5 every time?

**Comment by rfay** [comment]
No, nothing here had anything to do with ddev, it was a temporary problem with library/phpmyadmin:5. And when you do a `docker pull phpmyadmin:5` it updates the phpmyadmin image for all projects that are using the same docker service, for example Docker Desktop. So you have something much more exotic going on. I recommend doing a `docker images | grep phpmyadmin` and using `docker rmi` to kill all of them.

It's also possible that you have customized with a `docker-compose.*.yaml`? and that affects this? 

Maybe you can just see if you have this problem on a plain vanilla drupal 9 site (or whatever CMS you use)? https://ddev.readthedocs.io/en/latest/users/cli-usage/#quickstart-guides

**Comment by alanmels** [comment]
No, it should be pretty standard ddev setup. But running `docker images | grep phpmyadmin` shows two different versions, so probably newly created development environments pick up the earlier version:

```
docker images | grep phpmyadmin
phpmyadmin                        5                       0d0e4007d906   12 days ago    475MB
phpmyadmin                        <none>                  a2910b751aa7   4 weeks ago    475MB
```

Attempt to remove them give:

```
docker rmi 0d0e4007d906
Error response from daemon: conflict: unable to delete 0d0e4007d906 (cannot be forced) - image is being used by running container 13d9333e3357
```

```
docker rmi a2910b751aa7
Error response from daemon: conflict: unable to delete a2910b751aa7 (must be forced) - image is being used by stopped container ce645d49be38

```

but I've got the idea and will take it from here. Thanks a lot for pointers!

**Comment by rfay** [comment]
Do a `ddev poweroff` and `docker rm -f $(docker ps -aq)` and then use `docker rmi -f`.

If I were you I'd delete all images. They just get downloaded again.
