### ISSUE TITLE
Permission denied while creating a new database dump file

### ISSUE THREAD

**Issue by pmichelazzo** [drud/ddev#3845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

Since I'm totally lazy and an automation lover, I'm trying to create a new custom command to do a database dump with a short command, e.g. **ddev ddb** (ddev dump database :) 

I took the mysqldump.example command to start my own and I wrote this line:

`mysqldump -c -e -uroot -proot db | gzip >db.sql.gz`

I add the file inside of my ./ddev/commands/db directory but the command doesn't work, giving me this message:

```
/mnt/ddev_config/.global_commands/db/salva: line 7: db.sql.gz: Permission denied
mysqldump: Got errno 32 on write
Failed to run salva : exit status 1
```
The mysqldump works fine and I also check all permissions inside of my project and looks good.

This is the file command content:

```
#!/bin/bash

## Description: Executa um mysqldump e criar um arquivo db.sql.gz na raiz do projeto
## Usage: ddb
## Example: "ddev ddb"

mysqldump -c -e -uroot -proot db | gzip >db.sql.gz
```

On this way, somebody could help a lazy guy with this issue? :)

Thanks 

### Current Behavior

Cannot save a new dump file inside the project folder.

### Expected Behavior

Save the file

**Comment by jonaseberle** [comment]
I guess since you started from `mysqldump.example` you added that as a `db` container command.

Since you want to write to the project filesystem, you should put it in `.ddev/commands/web/ddb`.

**Comment by pmichelazzo** [comment]
Thanks @jonaseberle you're right. I move the new command to the web directory and it's working now.

Best regards
