### ISSUE TITLE
Windows: files directory contents must be writable by nginx user in container

### ISSUE THREAD

**Issue by rfay** [drud/ddev#385]
## What happened (or feature request):

I note that the files directory for my (windows ddev) drupal site is mounted as root, but the nginx process is running as nginx, as we'd expect. But with this mounting, nginx is not necessarily able to write into the files directory as it needs to do.  This is on windows.

Possible solutions include:
* Recursively Chowning the files dir to nginx owner and/or nginx group
* chmod directories and files carefully to add permissions.

The normal approach on a *server* would be to grant nginx group write perms on everything in the directory. 

All changes here have important implications for linux users, as changing the ownership must be done "right" or it results in very significant host-side permission problems.

## Related source links or issues:

**Comment by rickmanelius** [comment]
@rfay Given that this is specified as an issue affecting Windows only, what is the reason for the discrepancy? That is, I'm assuming Linux/Windows mount the files directory as the nginx user. Is this a deficiency in Docker for Windows?

**Comment by rfay** [comment]
I haven't studied it on other platforms, am not sure I know it's windows only. This may be related to the same problems we have on linux, which we've solved by changing the 'nginx' user/group after starting the container.

**Comment by rfay** [comment]
Ownership on Windows is fine, at least since #745 - I just tested it.
