### ISSUE TITLE
ddev snapshot --list works for the project, ddev-snapshot --list-all returns empty

### ISSUE THREAD

**Issue by hanoii** [drud/ddev#3855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`ddev snapshot --list`

Snapshots of project xxx: a bunch of snapshots

`ddev snapshot --list --all`

No output.

### Expected Behavior

`ddev snapshot --list --all` should include the current project's snapshots. (I have so far one project on this computer)

**Comment by rfay** [comment]
If you had included a link to the diagnostic as requested, I wouldn't have to ask this... Please update with that diagnostic. Are you using ddev v1.19.2?

**Comment by hanoii** [comment]
Sorry and yes, it is - https://pastebin.com/SQZgVrdP

In my lousy defense I did read the first item of the bug report which was to check it was the last version, which I knew it was, and for this broad simple command I assumed it's something general. My bad, will make sure to add diagnostics.

**Comment by rfay** [comment]
Thanks for doing that. It helps me a lot to understand the context of an issue.

Hmm, `ddev snapsot --list --all` for me shows the snapshots of all projects. 

I have two projects registered:
```
$ ddev snapshot --list --all
Snapshots of project d9: 202205190936, Y05190935, d9_20220519093328, d9_20220105123645, d9_20220105123358, d9_20220105123209
There are no snapshots for project laravel
```

If I unlist the laravel project I see:
```
$ ddev snapshot --list --all
Snapshots of project d9: 202205190936, Y05190935, d9_20220519093328, d9_20220105123645, d9_20220105123358, d9_20220105123209
```

Please help me to understand more about what's going on here.

**Comment by hanoii** [comment]
I think found the "issue", although not sure if it's like this by design.

If I remove my project with `ddev delete`, the snapshots are not deleted (and a new one gets created) and if I run `ddev snpashot --list` inside the project's directory I get the snapshots. If I run `--list --all` I get nothing, regardless of where I run it, as I assume `--all` is looking at the listed (`ddev list`) projects to find snapshots rather than some other context.

IMO, `--list --all` should also include those snapshots from deleted projects.

**Comment by rfay** [comment]
ddev has no way to know about deleted projects. That's what deleting is about.

**Comment by hanoii** [comment]
And how would you delete snapshots from deleted projects? You do have `--cleanup` but that only works from inside the ddev project root. Even `--cleanup --all` doesn't work for the snapshots of the deleted projects. 

Wouldn't a snapshot that outlives the registered project have a way to be managed by ddev? It looks like right now the only way to do that is within the root directory of the project. Is this also stored on the global-cache volume?

**Comment by rfay** [comment]
I keep my projects in the directory "workspaces". So I would do `rm -r ~/workspaces/*/.ddev/db_snapshots`

Once you delete a project, ddev knows nothing about it. I don't imagine you want ddev rummaging all over your disk drive looking for directories that might have a .ddev folder in them.

And no, `ddev-global-cache` does not keep registrations of projects.

**Comment by hanoii** [comment]
oh, snapshots are files in the filesystem of the project, ok... makes sense I guess. Good to know. Thanks!
