### ISSUE TITLE
Unable to import postgres database pulled from platform.sh

### ISSUE THREAD

**Issue by penance316** [drud/ddev#3867]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/penance316/f84d993406836bc5e9cf368e64b287ae

### Current Behavior

When running the `ddev pull` command for platform.sh integration the automatic import of my postgres database is failing and reporting an error like 
```
ERROR:  relation "public.users" does not exist
  68KiB 0:00:00 [1.65MiB/s] [>                                                                                                                         ]  0%
Failed to import database db for MyDBName: failed to import database: exit status 3
stdout:
stderr:
```

Running `ddev export-db` on my local DB then `ddev import-db` works correctly as expected.

### Expected Behavior

The database should be pulled from platform.sh provider and imported into my local environment.

### Steps To Reproduce

1. Setup platform.sh integration using `providers/platform.yaml`
2. run pull DB command `ddev pull platform --skip-files`
3. See database backup is pulled down successfully and stored in `.ddev/.downloads/db.sql.gz` as defined by platform.yaml.example file.
4. The command will now move onto importing the database, this is when the failure occurs due to a relation not existing.

### Anything else?

To get around this issue i have been using a custom `db_import_command` hook and a custom postgres script like this
```
\# First drop all tables.
psql -U db -c 'DROP SCHEMA public CASCADE; CREATE SCHEMA public; GRANT ALL ON SCHEMA public TO db; GRANT ALL ON SCHEMA public TO public;'

\# Import via user postgres to avoid credentials prompt
psql -U db db < /mnt/ddev_config/.downloads/db.sql
```

It seems to be an issue with how the platform.sh command takes the backup as it appears to not be compatible with the ddev built in import-db command. 
But it also seems that running this custom import to drop all SCHEMA etc before importing the DB works fine. So I am not sure from which end this issue should be tackled.

Thanks

**Comment by rfay** [comment]
Great stuff, I don't think anybody has ever tried *any* version of a `ddev pull` using postgres.  And it looks like you're already on the way to a PR that will make it work there. 

But let's talk about just the import of the database you're working on, just using `ddev import-db` - Does `ddev import-db` work with the database you're working on? If not, is there a way you can share the database privately?

**Comment by penance316** [comment]
No the import does not work for the database I am trying. :( 
Using the platform dump command 
`platform db:dump --yes --gzip --file=/var/www/html/.ddev/.downloads/db.sql.gz --project="${project_id}" --environment="${environment}"` 

Then importing with `ddev import-db --src=./db.sql.gz` 
I get the failure message 
```
ERROR:  relation "public.users" does not exist
  68KiB 0:00:00 [2.04MiB/s] [>                                                                    ]  0%
Failed to import database db for myneilson: failed to import database: exit status 3
stdout:
stderr:
```
I'm afraid I cannot share this database as it contains confidential data. 
It seems to be something to do with the way the platform.sh command performs the DB dump. 

The first thing I notice in the dump performed by platform.sh cli tool I can see a bunch of ALTER TABLE and DROP INDEX commands which are not present in the dump performed by ddev.
platform.sh dump
```
ALTER TABLE ONLY public.users DROP CONSTRAINT users_role_id_foreign;    <-------------------These tables don't exist yet during restore.
ALTER TABLE ONLY public.answers DROP CONSTRAINT answers_quiz_attempt_id_foreign;
ALTER TABLE ONLY public.answers DROP CONSTRAINT answers_question_id_foreign;
ALTER TABLE ONLY public.answers DROP CONSTRAINT answers_option_id_foreign;
DROP INDEX public.user_roles_user_id_index;
DROP INDEX public.user_roles_role_id_index;
DROP INDEX public.scheduled_events_command_index;
DROP INDEX public.question;
```
Whereas the dump from ddev has no DROP INDEX commands and has ALTER TABLE commands after CREATE TABLE.
```
--

CREATE TABLE public.accommodation_options (
    id integer NOT NULL,
    question_id character varying(255) NOT NULL,
    option_id character varying(255),
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);

ALTER TABLE public.accommodation_options OWNER TO db;
```

**Comment by rfay** [comment]
Thanks so much for your work on this. Postgres support in DDEV is very young, whereas the MySQL/MariaDB support has had years to mature, so I imagine we have to strip some DDL out of there on import.

You said that this fixed the problem, 

```
\# First drop all tables.
psql -U db -c 'DROP SCHEMA public CASCADE; CREATE SCHEMA public; GRANT ALL ON SCHEMA public TO db; GRANT ALL ON SCHEMA public TO public;'

\# Import via user postgres to avoid credentials prompt
psql -U db db < /mnt/ddev_config/.downloads/db.sql
```

So that's probably a good clue. 

Do you perhaps have privs to create a second demo site on Platform for which you could provide dumps from? Alternately, Platform is a valued sponsor of the DDEV project (the lead sponsor) and I'm sure we can get a path for a Postgres export to work with. Currently we have just the one MySQL site that we use for testing of the Platform pull integration.

**Comment by penance316** [comment]
I have managed to make a stripped down version to help test. :) 

The DB backup attached only has 2 tables (with a relationship) and no data and the backup was taken via the platform.sh cli tool again.
[platform-empty.sql.gz](https://github.com/drud/ddev/files/8779761/platform-empty.sql.gz)

Importing this is giving the same error RE trying to alter or drop a relation that doesn't exist yet `ERROR:  relation "public.user_roles" does not exist`.

It seems platform.sh's backups are intended to be restored on to existing databases. 
They mentioned on their docs page @ https://docs.platform.sh/add-services/mysql.html#importing-data
>  That runs the database backup against the SQL database on Platform.sh. That works for any SQL file, so the usual caveats about importing an SQL dump apply(for example, it’s best to run against an empty database)

**Comment by rfay** [comment]
I also have a platform Drupal 9 with Postgres site going (it was a good exercise for me) and see the same problem.

**Comment by rfay** [comment]
Looks like an appropriate dump (see https://docs.platform.sh/add-services/postgresql.html#importing-data) would be 

`pg_dump --no-owner --clean --if-exists`

**Comment by rfay** [comment]
I was able to get a clean dump (that could be imported) using this technique. 

The normal way to get a dump is with `platform db:dump`, but it's missing the --if-exists flag. But `platform db:dump` is just a wrapper that generates an ssh command. So we can find out what it's doing and then add the --if-exists flag:

1. `ddev exec platform db:dump -f db.sql.gz --gzip -v` will do a dump but also show you what it's doing so you can add the flag.
2. In my case I saw `ssh '-o' 'SendEnv TERM' '-o' 'CertificateFile /home/rfay/.platformsh/.session/sess-cli-default/ssh/id_ed25519-cert.pub' '-o' 'IdentityFile /home/rfay/.platformsh/.session/sess-cli-default/ssh/id_ed25519' 'cojj67jzpv5vk-main-bvxea6i--drupal@ssh.us-3.platform.sh' 'set -o pipefail; pg_dump --no-owner --clean --blobs '\''postgresql://main:main@database.internal:5432/main'\'' | gzip --stdout' > '/var/www/html/db.sql.gz'`
3. So I did a `ddev ssh` and did `ssh '-o' 'SendEnv TERM' '-o' 'CertificateFile /home/rfay/.platformsh/.session/sess-cli-default/ssh/id_ed25519-cert.pub' '-o' 'IdentityFile /home/rfay/.platformsh/.session/sess-cli-default/ssh/id_ed25519' 'cojj67jzpv5vk-main-bvxea6i--drupal@ssh.us-3.platform.sh' 'set -o pipefail; pg_dump --no-owner --clean --if-exists --blobs '\''postgresql://main:main@database.internal:5432/main'\'' | gzip --stdout' > '/var/www/html/db.sql.gz'`

That gave me a good dump. I'll do a PR against the platform tool and put the link here.

**Comment by rfay** [comment]
Platform cli PR at 
* https://github.com/platformsh/platformsh-cli/pull/1132

**Comment by penance316** [comment]
Thats a great idea 👍 , I didnt think about fixing/updating the platform.sh cli. 
I'm looking forward to pulling down the changes when they do the next release.

Appreciate your quick and professional responses

**Comment by rfay** [comment]
Thank you for your diagnosis, that's what made progress possible. I hope `ddev pull platform` will "just work" with next release of ddev, which will hopefully have a new platform release. It shouldn't be too far off.

**Comment by rfay** [comment]
I'll be releasing ddev v1.19.3 in the next couple of days, and I've confirmed over in #3882 that it solves the problem you reported @penance316 - I hope you'll try it out and see how it works in your environment. The new release includes the new release of the platform cli tool that got the upstream PR in it.

**Comment by rajesh-ivd** [comment]
I'm currently facing an issue when trying to import a PostgreSQL database backup, and I'm seeking assistance to resolve it.

The problem I'm encountering is as follows:

Error Message: 
![Screenshot (4)](https://github.com/dbeaver/dbeaver/assets/147796821/01254e94-d75e-4125-92f9-ffb83cebecbc)
![Screenshot (5)](https://github.com/dbeaver/dbeaver/assets/147796821/a491ecf9-dd61-4737-a84c-4875da3314c7)
![Screenshot (6)](https://github.com/dbeaver/dbeaver/assets/147796821/617d60e9-77ca-44e4-b50c-f70c592ab95f)
![Screenshot (7)](https://github.com/dbeaver/dbeaver/assets/147796821/3915d053-d646-4141-9ce8-71abd4e4376b)
![Screenshot (8)](https://github.com/dbeaver/dbeaver/assets/147796821/3da4aa39-53e6-48d9-becd-b373c70282f1)

The error seems to indicate that I'm performing a data-only restore, and I may be missing schema objects. I would like to restore both data and schema objects, and I'm unsure how to proceed.

Any suggestions, insights, or explanations on how to address this issue would be highly valuable. Thank you in advance for your help!

**Comment by stasadev** [comment]
Hi @rajesh-ivd,

Sorry, but your question is off topic and not related to DDEV.
Next time use a proper place like the PostgreSQL forums.
You can find the answer by googling `pg_restore: implied data-only restore`.
