### ISSUE TITLE
update NGROK settings

### ISSUE THREAD

**Issue by tyler36** [drud/ddev#3874]
Recently, I was required to share a DDEV host. When I attempted to run it Chrome, I got scary "Deceptive site ahead" warning page.

One suggested solution was to update NGROK (I was on 2.x). I bumped up to NGROK `3.0.4` however, this broken the config setting template.

- The [switch has changed](https://ngrok.com/docs/secure-tunnels#http-tunnels-basic-auth): "--auth" => "--basic-auth".
- There is also a 8-character minimum requirement on passwords.

The "--subdomain mysite" requires a paid-plan, therefore I don't think it should be included in the example template. I think the template should provide an example that anyone can use as is.

**Comment by tyler36** [comment]
Sorry for the messy workflow. My fingers are not working.

**Comment by rfay** [comment]
Subdomain has always required a paid plan, and it's critical for things like WordPress and Magento 1 that have wired domain names.  But as you already have... improvements in docs are welcome. https://ddev.readthedocs.io/en/latest/users/topics/sharing/
