### ISSUE TITLE
Magento2 acceptance test utils not available

### ISSUE THREAD

**Issue by sebastian-ehrling** [drud/ddev#3876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running the magento acceptance tests, an error occurs because the DEV tools are not available. 
The dev tools have to be available by request the current url:
https://[example].ddev.site/dev/tests/acceptance/utils/command.php

Currently I get the following error:
404 Not Found
nginx

### Expected Behavior

The dev tools must be available to run.

### Steps To Reproduce

Browse to: https://[example].ddev.site/dev/tests/acceptance/utils/command.php
Get error: Not found

### Anything else?

The issue can be solved, by adding the following to the nginx config (pkg/ddevapp/webserver_config_assets/nginx-site-magento2.conf) after line 34.
Is there a variable for current working dir available?

 location ~* ^/dev/tests/acceptance/utils($|/) {
        root /var/www/html/src;  #Variable for working dir?

        # This endpoint runs `bin/magento` CLI, be aware that it needs more time to finish
        location ~ ^/dev/tests/acceptance/utils/command.php {
            fastcgi_pass unix:/run/php-fpm.sock;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  /var/www/html/src$fastcgi_script_name;   #Variable for working dir?
            fastcgi_param  PATH_INFO        $fastcgi_path_info;
            fastcgi_read_timeout 600s;
            fastcgi_connect_timeout 600s;
            include        fastcgi_params;
        }
    }

**Comment by sebastian-ehrling** [comment]
HI @rfay 

thank you!  
Yes! That's is what I meant. When running "ddev exec" that is my working_dir.

No, the location entry above doesn't work for this because the magento dev utils are not available in the document root.
For example:
Public magento files are located in the document root ($document_root) /var/www/html/pub
The magento dev utils are available in /var/www/html/dev

I'd like to create a pull request, but I need a variable for the working dir in the nginx config, not the document root.

**Comment by cmuench** [comment]
@rfay That issues is not new for me, because @sebastian-ehrling and me already talked about a good way to integrate the Magento Acceptance Test Suite.
Let's see if we can get it to run.

**Comment by rfay** [comment]
I think the magento nginx config could have two stanzas in it with different roots...

**Comment by sebastian-ehrling** [comment]
Hi @cmuench 
that would be great! I've created a ddev addon to add and run and selenium container to a ddev project. 
ddev get sebastian-ehrling/ddev-selenium-standalone

What do you think is the best way to modify the nginx config?

**Comment by rfay** [comment]
I opened the first issue on your selenium add-on, great start! 
* https://github.com/sebastian-ehrling/ddev-selenium-standalone/issues/1

**Comment by cmuench** [comment]
> Hi @cmuench that would be great! I've created a ddev addon to add and run and selenium container to a ddev project. ddev get sebastian-ehrling/ddev-selenium-standalone
> 
> What do you think is the best way to modify the nginx config?

If you want then we can have a zoom call to discuss it. It depends :-)

**Comment by rfay** [comment]
I'll leave this in your hands. Let me know if I can help. Closing for now, happy to continue the conversation here or elsewhere.
