### ISSUE TITLE
Remove dependency to ngrok binary by using ngrok-api-go

### ISSUE THREAD

**Issue by nico-loeber** [drud/ddev#3883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Ngrok is an optional dependency that must be installed as a separate package, even if it is included in the installer.
It is quite well included in `ddev share` but it's behavior does differ from other ddev commands. It's ui does differ much from the default ddev output, also it does not support the --json-output option.

### Describe the solution you'd like

The ngrok binary is just an API Client. The same could be done in ddev itself by using https://github.com/ngrok/ngrok-api-go for example. This would allow a better integration of ngrok in ddev and would remove the dependency to the ngrok binary and related installation documentation.

I am aware of the challenges this would cause:
- API Key must be manged by ddev itself
- Common features of the ngrok binary must be implemented in ddev
- Breaking changes to configuration and behavior

I see the following advantages:
- The ngrok binary is closed source. Issues are hard to debug.
- Ngrok is currently a standalone dependency and must be kept up to date along with ddev
- A better integration in ddev
- Better control over the ngrok client version

### Describe alternatives you've considered

This is a proposal to improve the current state.

### Additional context

An example of a problem that is difficult to debug because the binary is closed source:
https://github.com/php-perfect/ddev-intellij-plugin/issues/53

The updating UI output of Ngrok is also hard to integrate in the PHPStorm integration plugin. But the main reason for this proposal is to get rid of the additional external dependency.

**Comment by rfay** [comment]
Super interesting! Thanks. 

Another thing that comes up regularly is the fact that ngrok is a fairly obnoxious closed-source system, and significant use usually requires paying money. A number of alternatives have come and gone, but ngrok seems to be the most long-lived and best maintained, even though they regularly break things.

**Comment by rfay** [comment]
This seems like it would be great, but I don't see it being a priority any time soon. Closing for now.
