### ISSUE TITLE
nginx snippet fails on startup

### ISSUE THREAD

**Issue by tyler36** [drud/ddev#3890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is an issue with Laravel and Livewire: [File upload over https fails signature verification](https://github.com/livewire/livewire/discussions/3084).

I have the current snippet in my `.ddev/nginx_full`:

```conf
# Fix: File upload over https fails signature verification
#      https://github.com/livewire/livewire/discussions/3084
location ^~ /livewire {
    try_files $uri $uri/ /index.php?$args;
}
```

Recently I became aware of nginx snippets and decided to extract this to `.ddev/nginx_conf/livewire.conf`. However, when I attempt to start the project, I get the following error:

```shell
Container ddev-debug-nginx-web  Started 
Container ddev-router  Running 
Failed to start debug-nginx: container(s) failed to become healthy after 61 seconds. This may be just a problem with the healthcheck and not a functional problem. container /ddev-debug-nginx-web is unhealthy: phpstatus: FAILED /var/www/html: OK mailhog: FAILED  
```

- If I comment out the entire contents of `livewire.conf` and `ddev restart`, I don't have a problem.

### Expected Behavior

I expect to be able to 

- copy a chunk of `nginx-site.conf`, 
- paste it into a `example.conf`
- use DDEV as if the snippet was in `nginx-site.conf`

### Steps To Reproduce

1. create a new project

  ```shell
  laravel new debug-nginx
  cd debug-nginx
  ```

2. add DDEV and accept defaults

  ```shell
  ddev config
  ```

3.  create `./.ddev/nginx_full/livewire.conf`

  ```shell
  # Fix: File upload over https fails signature verification
  #      https://github.com/livewire/livewire/discussions/3084
  location ^~ /livewire {
      try_files $uri $uri/ /index.php?$args;
  }
  ```

4. start ddev 

  ```shell
  $ ddev start
  ....
  Container ddev-debug-nginx-web  Started 
  Container ddev-router  Running 
  Failed to start debug-nginx: container(s) failed to become healthy after 61 seconds. This may be just a problem with the healthcheck and not a functional problem. container /ddev-debug-nginx-web is unhealthy: phpstatus: FAILED /var/www/html: OK mailhog: FAILED  
  ```

### Anything else?

I understand that this feature is deprecated,  and perhaps you do not want to spend time on it.

However, I hope you reconsider. 
- the feature works similar to `docker-composer.*.yaml` and ' `Dockerfile.*` 
- taking over the contents of `nginx-site.conf` prevents people from getting any future updates

OS: Ubuntu 20.04 via WSL on Win10
DDEV: `ddev version vHEAD-486d701`

**Comment by tyler36** [comment]
https://github.com/tyler36/debug-nginx

**Comment by rfay** [comment]
Snippets go into .ddev/nginx, not .ddev/nginx-full. Each item in .ddev/nginx-full must be a full nginx-site.conf.

Did you put it in .ddev/nginx? 

Based on @gilbertsoft 's love of snippets, I'm sure we won't remove them, and he was going to do a docs PR ti improve the description so people don't get confused and un-deprecate.

Interesting that the doc is so terrible, doesn't even include an example, https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#nginx-snippets-deprecated - but you can see in the default nginx-site.conf where it gets included.

**Comment by tyler36** [comment]
I understand.

Placing it in `.ddev/nginx* works.
