### ISSUE TITLE
`ddev clean .` stops all projects before discovering that "." isn't a valid project

### ISSUE THREAD

**Issue by dman-coders** [drud/ddev#3892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Summary: `ddev clean .` will nuke all projects without confirmation.

I was resetting a project today and ran the following command:

```
dman@raffles:/var/www/drupal9-multisite (master *)$ ddev clean
No project provided. See ddev clean --help for usage
```

"Meh" I thought. Just do the current project - the one I'm in now. Like the other commands do. 
The usual shortcut for $CWD is `.` :

```
dman@raffles:/var/www/drupal9-multisite (master *)$ ddev clean .

Powering off ddev to avoid conflicts 
Container ddev-drupal9-demo-db  Removed 
Container ddev-drupal9-demo-dba  Removed 
Container ddev-drupal9-demo-web  Removed 
Network ddev-drupal9-demo_default  Removed 
Project drupal9-demo has been stopped. 
Container ddev-drupal9-multisite-db  Removed 
Container ddev-drupal9-multisite-dba  Removed 
Container ddev-drupal9-multisite-web  Removed 
Network ddev-drupal9-multisite_default  Removed 
Project drupal9-multisite has been stopped. 
Container ddev-hello-world-dba  Removed 
Container ddev-hello-world-db  Removed 
Container ddev-hello-world-web  Removed 
Network ddev-hello-world_default  Removed 
.
..
...
```

... and all my 20 other local dev projects were wiped just like that!

:scream: 

### Describe the solution you'd like

1. Deleting all containers and all projects everywhere should at least have a confirmation step, listing all the projects affected!
2. I don't know what logic is expanding the `.` into meaning `--all` - but this behaviour is dangerous and unexpected.
3. I'd expect the `clean` command to be aware of "current project" like the other commands are, so it can possibly either confirm
    >  "Do you want to remove all containers connected to the current project 'Projectname' Y/n"
    or go interactive:
   > "Clean all containers connected to the project. Project Name (Projectname): "'

### Describe alternatives you've considered

Any of the three suggestions above would have prevented the total destruction this command unleashed.

### Additional context

Luckily only two of the 20 projects destroyed had working local content that I really lost, as I mostly just test things mirrored from upstream, but that's just lucky for me today. It's set back some local experimental work by a bit though, could have been worse.

**Comment by rfay** [comment]
Hi @dman-coders - Sorry you had a scary experience. 

Note that ddev recreates all containers on every `ddev start`. Containers aren't an issue, they are always recreated on `ddev start`. So the fact that it did a `ddev poweroff` is not a problem - you probably didn't want to be running all those at the same time any way.

What happened to you is that `ddev clean .` throught you wanted to clean a project named ".", which didn't exist. So it went through the process of doing a poweroff (which is what you saw, it does no damage) and then it looked for the project named ".", which didn't exists. You don't show that part.

Here's what I see:

```
 % ddev clean .
Powering off ddev to avoid conflicts
The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again.
Unable to remove network ddev: API error (403): error while removing network: network ddev_default id c7e7dc58c6119ed7c2f0883e1b96437b907cecf646105bd665d15176e7341d28 has active endpoints
Warning - Snapshots for the following project[s] will be permanently deleted
Failed to get project(s): could not find requested project ., you may need to use "ddev start" to add it to the project catalog
```

Note that last part... It couldn't find the project named "."

I think if you go to any of your projects and `ddev start` you'll find that nothing has changed, nothing has been deleted.

You can get help on any comand with `ddev help <command`, so `ddev help clean` shows

```
Stops all running projects and then removes downloads and snapshots
for the selected projects. Then clean will remove "drud/ddev-*" images.

Warning - This command will permanently delete your snapshots for the named project[s].

Additional commands that can help clean up resources:
  ddev delete --omit-snapshot
  docker rmi -f $(docker images -q)
  docker system prune --volumes

Usage:
  ddev clean [projectname ...] [flags]

Examples:
ddev clean
	ddev clean project1 project2
	ddev clean --all

Flags:
  -a, --all       Clean all ddev projects
      --dry-run   Run the clean command without deleting
  -h, --help      help for clean

Global Flags:
  -j, --json-output   If true, user-oriented output will be in JSON format.
```

And it explains what you saw...

**Comment by rfay** [comment]
I haven't heard from you again @dman-coders - I hope you found that everything was fine (because it was). But I understand why this was scary. So 
* #https://github.com/drud/ddev/pull/3901
does the poweroff later, after you say "yup, ok". 

But poweroff does no harm, and that's what you saw go by.

**Comment by dman-coders** [comment]
Thanks for the explanation! I was AFK for a day, but have gone back and checked the projects that had containers that were "removed" and found that the data still seems to be there, yes.
It's not the "Poweroff" that was worrying - it was the "Container ddev-drupal9-demo-db  Removed " messages.

In the past, when I've had data in a database inside a container, that's where I thought my data was. Deleting/removing a container from Docker or whatever would mean the end of that data. (This had happened to our team once in the very early days of virtualization and killed 2 weeks work, so maybe I've still got PTSD from that month.)

I guess the gotcha for me here was the use of the word "remove" seen in the help page there.

> "removes downloads and snapshots"

= deletes

> clean will remove "drud/ddev-*" images.

= deletes

> Container ddev-drupal9-demo-db  Removed 

= not deleted, just ... deactivated?

Thanks for the follow-up, it looks like I can get back to what I was supposed to be doing now :-)

**Comment by rfay** [comment]
Yay! 

A docker "image" is basically the pattern for a docker "container", which is the running instantiation of the image. 

There are (or used to be) tools that kept data inside the container, but certainly ddev hasn't done that for many years. In every case, containers are built straight-up from the image, and nothing is stored in them, so they can be killed off any time, and in fact they are every time you `ddev stop` or `ddev poweroff`. The database and any other state is kept in docker *volumes*, which are basically fast-access data stores inside the docker world.

**Comment by rfay** [comment]
I'm going to go ahead and close this now, but happy to continue the conversation here or elsewhere. And I think https://github.com/drud/ddev/pull/3901 will make for a happier experience the next time somebody does something like this.
