### ISSUE TITLE
Remove associated docker volumes when ddev-removing a site/app

### ISSUE THREAD

**Issue by tannerjfco** [drud/ddev#39]
## What happened (or feature request):
We are not cleaning up unused docker volumes, creating the potential for lots of disk space to be consumed. This also seems to occasionally create a scenario in which the mysql container for a site will end up stuck in a restart loop.

## What you expected to happen:
I expect to not have the mysql container intermittently exhibit a restart loop. I expect to have disk space used for useful things. Adding a step to prune volumes (maybe on remove?) would alleviate both of these issues.

## How to reproduce it (as minimally and precisely as possible):
The mysql container restart behavior is very difficult to reproduce. If you happen to find yourself producing it though, stopping/removing the container and running `docker volume prune` will allow you to successfully start a new mysql container. Running this command also demonstrates how much space was being needlessly consumed.

## Anything else do we need to know:
n/a

## Related source links or issues:
n/a

**Comment by tannerjfco** [comment]
I think it should be reasonable to do this at the end of `ddev remove`, unless anyone has any objections. @rickmanelius any other aspects of this issue requiring decision / further incubation?

I haven't seen the mysql issue originally noted in sometime, but I do think we still need to prune unused volumes when sites are removed. It does not take much site spin up/tear down for several gigs to end up being used.

**Comment by rfay** [comment]
As long as we filter with --filter and have a test that makes sure we're doing the right thing I'm good with pruning.

**Comment by rickmanelius** [comment]
Works for me. Tagging v0.8. Probably needs a little more specificity to get to actionable unless you feel there is a clear/obvious path.

**Comment by rickmanelius** [comment]
Needs more work before actionable. Need to consider volumes from non-ddev solutions and also factor in download times (for slow internect connections).

**Comment by rfay** [comment]
I *think* we only have residual volumes that aren't even necessary?

docker.nginx-php-fpm-local/Dockerfile.in:VOLUME /var/log/nginx
mysql-docker-local/5.7/Dockerfile.in:VOLUME /var/lib/mysql

I suspect we're not doing the right thing in those dockerfiles anyway? Volumes are normally for sharing filesystems between containers right, but we don't actually do that do we?

**Comment by rfay** [comment]
This should be totally actionable, and totally appropriate, as originally described. We just have to delete the related volumes.
