### ISSUE TITLE
Webserver fails to start with symlink in global homeadditions

### ISSUE THREAD

**Issue by mbomb007** [drud/ddev#3903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

I had been linking my .gitconfig file using `ln -s ~/.gitconfig ~/.ddev/homeadditions/.gitconfig` to create a symlink. This adds my up-to-date .gitconfig to my global DDEV homeadditions.

Recently, web containers no longer build and start successfully, and I get this error on every web container:

> cp: '/mnt/ddev_config/.homeadditions/./.gitconfig' and '/home/kali/./.gitconfig' are the same file

**Gist:** https://gist.github.com/mbomb007/d8fa53fac541271ffe53bbcd5ee34e05

### Current Behavior

I had been linking my .gitconfig file using `ln -s ~/.gitconfig ~/.ddev/homeadditions/.gitconfig` ([see this DDEV issue comment here](https://github.com/drud/ddev/issues/1459#issuecomment-805260856)), but now it causes web containers to fail to start with this error:

> cp: '/mnt/ddev_config/.homeadditions/./.gitconfig' and '/home/kali/./.gitconfig' are the same file

### Expected Behavior

I expect to see the symlinked .gitconfig file copied to my Docker containers, allowing my per-user settings to be used within containers.

### Steps To Reproduce

1. Create a .gitconfig in WSL2
2. Symlink to it in the DDEV global homeadditions: `ln -s ~/.gitconfig ~/.ddev/homeadditions/.gitconfig`
3. `ddev config`
4. `ddev start`
5. Webserver fails to start, showing:

> cp: '/mnt/ddev_config/.homeadditions/./.gitconfig' and '/home/kali/./.gitconfig' are the same file

I then verified this is the issue by removing the symlink, removing the container, reconfiguring, and recreating the container. It works fine. But I don't understand why there's an issue copying the file to the container.

### Anything else?

**Gist:** https://gist.github.com/mbomb007/d8fa53fac541271ffe53bbcd5ee34e05

Viewing the logs of the ddev-webserver container that failed to start for tryddevproject shows this at the end:

```
...
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
+ '[' -d /mnt/ddev_config/.homeadditions ']'
+ cp -r /mnt/ddev_config/.homeadditions/. /home/kali/
cp: '/mnt/ddev_config/.homeadditions/./.gitconfig' and '/home/kali/./.gitconfig' are the same file
```

**Comment by rfay** [comment]
Hi @mbomb007 - You can't use symlinks in homeadditions... because they won't resolve when they're in the context of the container. You have to copy things in there. See the caveat in https://ddev.readthedocs.io/en/latest/users/extend/in-container-configuration/#in-container-home-directory-and-shell-configuration

> Caveats:

> * Absolute symlinks inside a homeadditions directory won't work because they can't be resolved inside the container.

**Comment by mbomb007** [comment]
Couldn't the startup process copy the actual file that is linked instead of the symlink?

**Comment by rfay** [comment]
It's possible. Copying the target of symlinks can have some unexpected consequences, but I'm open to it!  Want to try a PR?

**Comment by rfay** [comment]
You did the right thing; existing tests should be OK. But as noted over there, you'll have to push image, I'm happy to help or  can do it for you.
