### ISSUE TITLE
Allow include additional php files into Drupal's settings.php via config.yaml, not only settings.ddev.php

### ISSUE THREAD

**Issue by dercheffe** [drud/ddev#3907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Sometimes I only have to change some paths in Drupal's settings like temp path or private files path. Sometimes also another setting overrides become necessary to avoid problems in dev environment.
I know there's settings.local.php, but IMO if you only need to change some paths, the use of settings.local.php is too much (caching gets disabled by default etc.). 
Of course it is also possible to modify settings.ddev php but it's recommended to leave the file untouched.

### Describe the solution you'd like

Allow in config.yaml the inclusion of additional file (paths) for PHP settings (perhaps somewhere in the .ddev dir) which then can included via ddev.settings.php similar to
`if (file_exists($path_from_config_yaml)  && getenv('IS_DDEV_PROJECT') == 'true') {
 include $path_from_config_yaml;
 }`

The advantage is here, that the user don't have to care about configs if the user does a new copy of the production site on the local dev machine after once defined in config.yaml.

### Describe alternatives you've considered

include the 
`if (file_exists($app_root . '/' . $site_path . '/MYSETTINGS.php')  && getenv('IS_DDEV_PROJECT') == 'true') {
 include $app_root . '/' . $site_path . '/MYSETTINGS.php';
 }` 
in the drupal settings.php manually is also an option. but it's easier if ddv could handle that automatically after once defined in config.yaml

**Comment by rfay** [comment]
The intention is that you'll control the settings.php (check it in). DDEV only creates it if you don't have one. So I recommend just checking in your settings.php and doing whatever you want with it. The default even has commented out suggestions about settings.local.php.

**Comment by dercheffe** [comment]
Agree, it's possible now already with settings.local.php. But if I activate settings.local.php a lot of dev settings for Drupal are activated automatically too, which are not wanted (in my case here). For now, I copied the if-loop made by ddev in settings.php and pasted it one more time. Then I  just changed the file name which contains my modifications for dev environment. It works for me :)

My intention to open the issue was to suggest a more generic solution in case a ddev project has to be rebuild or reconfigured.

**Comment by rfay** [comment]
Can you say why you don't just do whatever you want with settings.php? Including settings.local.php or any other include (or any other conditional)?

**Comment by dercheffe** [comment]
Hmm I try to less as possible modify it due to security- and maintenance reasons. I think it's better to leave things as close as possible to the original to avoiding security problems (at least in the productive version)

**Comment by rfay** [comment]
Most teams do what they need to with settings.php, and put specific values in with env vars or with includes like settings.local.php. Maybe you're saying that your team just doesn't have the option of fiddling with it? But then... how do you get the include for settings.ddev.php in there?

**Comment by dercheffe** [comment]
Well I'm a one man team to be honest :) Didn't know that it is common to modify settings.php in that way. I also put setting variables in there but for production use only. Well then I see no harm to include an additional php file with my development vars (which is not settings.local.php). I will use the similar loop like it's done for settings.ddev.php. Thanks for your advice :)

**Comment by rfay** [comment]
Thanks! I think that's the normal way. Closing this, but happy to continue the conversation here or elsewhere.
