### ISSUE TITLE
ddev config global --instrumentation-opt-in=false requires a docker connection

### ISSUE THREAD

**Issue by syssi** [drud/ddev#3910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since Commit https://github.com/drud/ddev/pull/3746/files (ddev 0.19) the command

```
ddev config global --instrumentation-opt-in=false
```

requires a docker connection:

```
Could not connect to a docker provider. Please start or install a docker provider.
For installation help go to: https://ddev.readthedocs.io/en/latest/users/docker_installation/
```

### Expected Behavior

At version 0.18 I could use the command to generated some configurations without running a dockerd:

```
$ ddev config global --instrumentation-opt-in=false --omit-containers=dba,ddev-ssh-agent
Global configuration:
instrumentation-opt-in=false
omit-containers=[dba,ddev-ssh-agent]
web-environment=[]
mutagen-enabled=false
nfs-mount-enabled=false
router-bind-all-interfaces=false
internet-detection-timeout-ms=75
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
auto-restart-containers=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=
use-docker-compose-from-path=false
```

### Steps To Reproduce

Stop dockerd + make sure dockerd doesn't start automatically using docker.socket and execute the command above.

### Anything else?

I am totally aware that it is unusual to have no dockerd running while executing some ddev commands. It looks like there is a special case for `ddev --version` already. May be `ddev config global` can be excluded too from the "safe-guard".

**Comment by rfay** [comment]
Please say why you need to config ddev without a docker provider running... This has been a hard thing to sort out. The idea is to not give people all kinds of scary messages about failures, but just make sure docker is running in the first place. I too had to make a change with v1.19, with the standard gitpod startup.

**Comment by syssi** [comment]
This is the background: https://github.com/drud/ddev/issues/3052#issuecomment-869742886

We build a custom ddev container based on a docker-in-docker image to be able to spin up a ddev instance at the Gitlab CI. The build fails here at the moment:

```
RUN sudo -u ddev-user ddev config global --instrumentation-opt-in=false --omit-containers=dba,ddev-ssh-agent
```

This is the workaround:

```
# https://github.com/drud/ddev/issues/3910
# RUN sudo -u ddev-user ddev config global --instrumentation-opt-in=false --omit-containers=dba,ddev-ssh-agent
COPY --chown=ddev-user:ddev-user global_config.yaml /home/ddev-user/.ddev/
```

**Comment by syssi** [comment]
Please ignore my request and close this issue if it doesn't fit the concept of ddev. To be able to generate a global configuration at the build step was nice in the past because of no maintenance effort.

**Comment by rfay** [comment]
What I did for gitpod (where the prebuild doesn't have a docker instance going) was just to write the needed ~/.ddev/global_config.yaml (which is all `ddev config global` does. that would work for you too.

I would sure love it if you could write up or share your gitlab implementation; people ask about that periodically, and I haven't had any answers. GitHub Actions is easy because things run in real VMs. 

One thing that might make a difference to you is the fact that ddev now allows remote docker (external DOCKER_HOST or docker context), although it's lightly used.

**Comment by syssi** [comment]
> What I did for gitpod (where the prebuild doesn't have a docker instance going) was just to write the needed ~/.ddev/global_config.yaml (which is all ddev config global does. that would work for you too.

I did the same (see above).

> I would sure love it if you could write up or share your gitlab implementation; people ask about that periodically, and I haven't had any answers. GitHub Actions is easy because things run in real VMs.

I am not very proud of the setup because it requires a self-hosted gitlab runner (because docker-in-docker requires a privileged docker instance etc.)... if you have the choice you should stick to Github because of the real VMs. ;-)

> One thing that might make a difference to you is the fact that ddev now allows remote docker (external DOCKER_HOST or docker context), although it's lightly used.

Nice! :-)

**Comment by rfay** [comment]
Yeah, have had to fiddle with this several times already in the last month or two. It's hard to get it right so you have docker when you need it and don't require it when you don't. I *think* that `ddev config global` could all work without docker, but don't know that for sure, haven't studied it.

**Comment by rfay** [comment]
I may fiddle with this at some point in the future, but the current approach of notifying people about the need for Docker has been working fine. Closing for now.
