### ISSUE TITLE
Stopped site can result in double notifications about router

### ISSUE THREAD

**Issue by rfay** [drud/ddev#393]
## What happened (or feature request):

* Start one site
* Stop the site
* `ddev list`

Ddev shows a single site, as stopped, correctly.
It shows DDEV ROUTER STATUS: not found (incorrect, as we wouldn't expect to find it)
And it shows two separate warnings "The router is not currently running. Your sites are likely inaccessible at this time.Try running 'ddev start' on a site to recreate the router"

```
$ ddev list
1 local site found.
NAME                TYPE     LOCATION                          URL                                   STATUS
TestMainCmdDrupal8  drupal8  /tmp/TestMainCmdDrupal8331317292  http://TestMainCmdDrupal8.ddev.local  stopped

DDEV ROUTER STATUS: not found
The router is not currently running. Your sites are likely inaccessible at this time.
Try running 'ddev start' on a site to recreate the router.
The router is not currently running. Your sites are likely inaccessible at this time.
Try running 'ddev start' on a site to recreate the router.
```

## What you expected to happen:

No warnings about the router. 

## Version: Please include the output of `ddev version` and the project's .ddev/config.yaml.

(This particular test was on linux)

```
$ ddev version
cli:       	v0.7-44-gf1973c0
web:       	drud/nginx-php-fpm7-local:v0.7.3
db:        	drud/mysql-local-57:20170708_windows_works
dba:       	drud/phpmyadmin:v0.2.0
router:    	drud/ddev-router:v0.4.3
commit:    	v0.7-44-gf1973c0
build info:	Built Mon Jul 10 19:24:56 PDT 2017 rfay@ubuntu drud/golang-build-container:v0.4.2
```

## Related source links or issues:

**Comment by rickmanelius** [comment]
Needs a confirm and then hopefully it's a quick fix. Thanks, @rfay!

**Comment by tannerjfco** [comment]
I can reproduce the double-warning output on macOS. The double-warning is not intended, but the warning message shown for this state is valid and intended. With no sites running, there is no router, and no sites are accessible.

**Comment by rfay** [comment]
I guess I disagree about the router notification when there are only stopped sites. I would expect a reasonable user to understand that stopped sites are not accessible.

**Comment by rickmanelius** [comment]
At a minimum, a double warning (even if it's benign) is going to be seen as an oddity to an end-user. If it's a simple LOE to address, my vote would be to correct this.

**Comment by rickmanelius** [comment]
Not prioritized yet until we have reviewed the backlog.

**Comment by rfay** [comment]
I ran across this in https://github.com/drud/ddev/pull/483 so fixed it there.
