### ISSUE TITLE
Install Brush (Drush for Backdrop) on ddev?

### ISSUE THREAD

**Issue by alanmels** [drud/ddev#3937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

[Brush](https://github.com/backdrop-contrib/brush) is the same command line tool for Backdrop CMS as Drush for Drupal. And so far we are just running the following commands to get it running inside of Backdrop development containers:

```
cd /usr/local/src && sudo git clone https://github.com/backdrop-contrib/brush.git
sudo ln -s /usr/local/src/brush/brush /usr/local/bin
```

However, the problem is that every time we restart ddev Brush is gone and we have to install it again, whereas Drush is always there, but the problem with Drush is that not all commands work for Backdrop CMS.

### Describe the solution you'd like

Is it possible to get Brush included, so it is always available outside (ddev brush some-command) as well as inside (brush some-command) of ddev container for a Backdrop website?

**Comment by alanmels** [comment]
@rfay, thanks for the pointer as after bit of experimenting the following code in the Dockerfile worked for me:

```
RUN sudo /usr/bin/git clone https://github.com/backdrop-contrib/brush.git /usr/local/src/brush
RUN sudo /bin/ln -s /usr/local/src/brush/brush /usr/local/bin
```

and now we won't have to install Brush after each container restart. However, we still need to place that Dockerfile manually to each website we newly create, don't we? Copying the `web-build` directory from the website to `~/.ddev` of my MBP didn't have any effect on a new test project deployed. 

Is there any way to automate the process, so Brush is always running inside of all our Backdrop containers?

**Comment by rfay** [comment]
Global Dockerfiles aren's supported, and certainly not adding Dockerfiles to the ssh-agent image. 

Does your team use composer? Lots of teams that use composer for their project make a package that does particular DDEV customizations like this. Then if they have that package in every project they have it set...

**Comment by rfay** [comment]
If everybody in the backdrop world uses brush now, I'd be pretty happy to have a contribution to remove the backdrop drush extensions and add brush on backdrop projects.

**Comment by alanmels** [comment]
> If everybody in the backdrop world uses brush now, I'd be pretty happy to have a contribution to remove the backdrop drush extensions and add brush on backdrop projects.

Backdrop community doesn't have consensus which one of three different command line tools yet (see https://forum.backdropcms.org/forum/brush-command-line-shell-and-unix-scripting-interface-backdrop-cms), so please don't do that. None of two other tools have complete database commands working, but Brush does and we keep using it to sync databases between different stages of Backdrop sites. 

> Global Dockerfiles aren's supported, and certainly not adding Dockerfiles to the ssh-agent image.
> 
> Does your team use composer? Lots of teams that use composer for their project make a package that does particular DDEV customizations like this. Then if they have that package in every project they have it set...

Fair enough. The Dockerfile method already makes it much easier.

**Comment by alanmels** [comment]
Another fun method was to place the whole Brush directory in the `~/.ddev/homeadditions` to make it appear every new container's home directory, however aliasing the path or including to $PATH doesn't make it work, probably because some environment is missing.

**Comment by rfay** [comment]
You're getting more creative all the time! If you put it in ~/.ddev/homeadditions/bin it should work fine - ~/bin is already in the $PATH.

**Comment by alanmels** [comment]
> You're getting more creative all the time! If you put it in ~/.ddev/homeadditions/bin it should work fine - ~/bin is already in the $PATH.

That and placing `alias brush='~/bin/brush/brush'` into `~/.ddev/homeadditions/.bash_alias` made the trick: now every newly created or restarted container has brush running ready. Thanks for sorting this out!
