### ISSUE TITLE
Standardize our approach on database configuration files.

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#394]
## What happened (or feature request):

* Feature Request

## What you expected to happen:

During the creation of the Pantheon Plugin (#345) we identified additional use cases where we cannot assume the application is using or not using a database configuration file in a particular way. We adopted a standard approach in the Drupal 8 codebase of including a settings.local.php file, but this still requires us to ensure it's included in the parent config file.

@rfay proposed that we attempt to push these customized configuration files to a standardized approach where we have ddev signatures at the bottom of the main config and local config file. This will require additional thought on how we approach this given the number of ways one can arrive at these customizations across different providers. 

## Anything else do we need to know:

This is a stubbed out issue and will need a bit of research and working through all the scenarios before we can proceed.

## Related source links or issues:

* Pantheon Plugin #345
* Running ddev start should generate a settings.php #346 
* Manage settings.php if we create it #308

**Comment by rfay** [comment]
This seems stale. Closing. Please reopen if you agree, @rickmanelius
