### ISSUE TITLE
Add MailCatcher 

### ISSUE THREAD

**Issue by basteyy** [drud/ddev#3948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Mailhog isn't updates that regularly. Many bugs still opened (https://github.com/mailhog/MailHog/commits/master) and it does not look like this will change. 

### Describe the solution you'd like

Add the option to choose the used tool for smtp testing. This option should be part of the config.yaml to make it easy for noobs (like me) to change it. 

### Describe alternatives you've considered

Implement mailcatcher

**Comment by rfay** [comment]
Maybe you can add to the request a bit of discussion of why mailcatcher is better? Thanks.

**Comment by basteyy** [comment]
It's not better, in the way, that this should replace Mail Hog. The most significant difference (for me) is that mail catcher is still under further development. That means a few bugs are fixed from time to time. Mailhog has for example a subject-bug, which isn't fixed for over a year.

**Comment by rfay** [comment]
One thing you might consider is creating a ddev add-on to make this available easily on your projects and on others. Full instructions in https://github.com/drud/ddev-addon-template - that assumes you know what you want to do. 

I note that in your OP you didn't even include a link to mailcatcher :) Please edit to do that.

**Comment by tyler36** [comment]
@basteyy 

I created a addon that uses Mailpit instead of Mailhig: see https://github.com/tyler36/ddev-mailpit
It might help you if you are trying to make an addon for MailCatcher.

There's also a conversation about moving the default mail debugger from Mailhog to Mailpit if you have something to add: #4827

**Comment by basteyy** [comment]
> @basteyy
> 
> I created a addon that uses Mailpit instead of Mailhig: see https://github.com/tyler36/ddev-mailpit It might help you if you are trying to make an addon for MailCatcher.
> 
> There's also a conversation about moving the default mail debugger from Mailhog to Mailpit if you have something to add: #4827

Awesome, looks like it will fit my needs. TY!

**Comment by chrisfromredfin** [comment]
Looks like 4 days ago with 1.6.0 mailpit added the requested feature for release: https://github.com/axllent/mailpit/issues/29#issuecomment-1517174324

Definitely we should maintain this as an official add-on, and eventually replace (or drop) Mailhog. I would even be OK if the mailcatching stayed as an add-on, and wasn't added to "ddev core" (though I suppose I would still be happIER if it we just replaced mailhog w mailpit)

**Comment by tyler36** [comment]
[ddev-mailpit](https://github.com/tyler36/ddev-mailpit)  was updated recently to include the `1.6.0`.

There's current a [draft PR](https://github.com/tyler36/ddev-mailpit/pull/13) that updates the readme and adds the required boiler plate config.
