### ISSUE TITLE
npm can't build complex packages that require compiles by default without build-essential

### ISSUE THREAD

**Issue by tomasnorre** [drud/ddev#3956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/tomasnorre/963b1af6688265a11d8db6ce4ff876fc

### Current Behavior

We are having problems with NPM on Apple M1 (arm64). `make` and `g++` is missing in the image as far as we have seen. 

You can reproduce this on Apple M1, by following steps. 

1. Create a new ddev project (`ddev config`) , current folder and php
2. `ddev start`
3. `ddev ssh`
4. `npm install node-sass`

you will then first get the error that: `stack Error: not found: make` and if that gets installed it, you can run `npm install node-sass` again and will then complain about `g++` missing. 

### Expected Behavior

As NPM is installed within DDEV I would expect this to be possible without installing software/tools my self. 

So expecting `make` and `g++` to be part of the images, then this problem would not occur. 

### Steps To Reproduce

Please see current behaviour. 

### Anything else?

This problem cannot be reproduced on a Linux (Ubuntu 20.04 x86_64)

**Comment by rfay** [comment]
Yes, make and g++ are required for npm packages that do installs. As `build-essential` is a pretty heavyweight set of packages, it's not provided by default. I do recommend `webimage_extra_packages: [build-essential]` for this situation.

**Comment by rfay** [comment]
The likely reason that this happens to you on arm64 is that there aren't prebuilt packages for arm64, and there are for amd64.

**Comment by tomasnorre** [comment]
Thanks for a super fast reply. The `webimage_extra_package` was also the one we went for in the `config.local.yml` as it will not affect the ones not on M1.

**Comment by tomasnorre** [comment]
With respect to your feedback. I think this could be closed then, as it doesn't sound like a wanted situation to "bloat" up the images more than needed. The ones needed the extra pages, can install them. 

I just didn't think of the consequences of adding them as default.

**Comment by rfay** [comment]
I see problems like this when installing packages in the default build in tests. Sometimes the download fails and it tries to compile and fails because of missing build-essential. And of course it fails. If there weren't the problem of image bloat (it's bloated enough) I'd just add them. Maybe sometime I'll look at what that actually does to size. Closing, happy to continue the conversation here or elsewhere, and great to see you around!
