### ISSUE TITLE
Document nfs.server.mount.require_resv_port must be disabled

### ISSUE THREAD

**Issue by damienmckenna** [drud/ddev#3958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Setting up ddev on a new (Apple m1) laptop I hit problems getting nfs to work correctly. I followed the guide but it only worked when I added nfs.server.mount.require_resv_port=0 to the /etc/nfs.conf file.

### Describe the solution you'd like

Consider whether `nfs.server.mount.require_resv_port=0` should be specifically documented as a requirement for NFS to work.

### Describe alternatives you've considered

I tried all of the steps in the setup guide and it didn't work until I disabled `nfs.server.mount.require_resv_port`.

**Comment by rfay** [comment]
Hmm, the standard setup with the script actually sets this. It looks like you didn't run the setup script? 

https://github.com/drud/ddev/blob/5618b74927fc74b136d0a5d1607216cd79596886/scripts/macos_ddev_nfs_setup.sh#L47

See setup instructions in https://ddev.readthedocs.io/en/latest/users/performance/#macos-nfs-setup

I'm surprised you're not using mutagen, as it's so much faster and more satisfactory (and doesn't require any setup).

**Comment by rfay** [comment]
Closing. Anyway, next time use the install script :)
