### ISSUE TITLE
Proxy in custom Dockerfile in Version v.1.19.3

### ISSUE THREAD

**Issue by sbiniok** [drud/ddev#3960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

The update from v1.19.2 to v1.19.3 introduced a change in the way the web-build/Dockerfile is integrated into the .webimageBuild/Dockerfile. Since custom Dockerfiles are now appended below the auto-generated apt-get command for extra packages, our previously utilized way of setting the proxy for apt (detailed [here](https://github.com/drud/ddev-contrib/blob/master/recipes/proxy/Dockerfile)) is no longer valid. 

### Describe the solution you'd like

May we suggest, either giving developers a way of forcing a custom Dockerfile to be the first in .webimageBuild/Dockerfile (via naming convention for instance), or maybe introducing a new config.yaml parameter (e.g. web_container_proxy) that, if present, would add the following to the auto-generated code:

```
ENV HTTP_PROXY [value from web_container_proxy]
ENV HTTPS_PROXY [value from web_container_proxy]

RUN if [ ! -z "${HTTP_PROXY}" ]; then printf "Acquire {\nHTTP::proxy \"$HTTP_PROXY\";\nHTTPS::proxy \"$HTTPS_PROXY\";\n}\n"  > /etc/apt/apt.conf.d/proxy.conf ; fi
```

**Comment by rfay** [comment]
Thanks @sbiniok - Sorry to break that workflow. I'm going to see if there's a different solution path, and if not we'll have to add a way to introduce those ENV earlier. I think that those could be introduced all the time if they exist, possibly. 

BTW, You can currently do a `docker-compose.*.yaml` that would override the build...

**Comment by rfay** [comment]
It looks like docker-compose v2 had a fix for this, https://github.com/docker/compose-cli/pull/2053 - so there may not be a need for this approach any more. I'll take a look. but bottom line we're hoping for is that the docker cli's proxy settings will automatically be used in build.

**Comment by hanoii** [comment]
While I was working on #3870 I kind of thought something like this was bound to happen, not specifically this, but someone wanting to add something before what you are injecting.

At that point I couldn't think of anything, and there should definitely be a way for ddev to ship their own Dockerfile on top of any project specific ones. The naming convention mentioned here was also my first thought, something like `Dockerfile.pre` but we are adding probably too opinionated ways of doing this. Will think a bit more, and maybe this is a non issue all along. 

At any rate, a way to injecting some customization in the beginning might not be a bad idea, thoughts?

**Comment by rfay** [comment]
I spent some time exploring this today, set up a proxy lab again, etc. I was hoping that docker-compose v2 had matured to allow using the client config, it apparently hasn't. I was able to use the *docker* client on a Dockerfile without this requirement (after fiddling with the docker client config and getting the server config right).

**Comment by rfay** [comment]
I put together a demo for the compose folks at 

* https://github.com/docker/compose/issues/9034#issuecomment-1178418031
There is another similar issue running at 
* https://github.com/docker/compose/issues/8797

**Comment by rfay** [comment]
@sbiniok could you please try out the artifacts in https://github.com/drud/ddev/pull/3976#issuecomment-1178454615 and take a look at that PR and see if it will work to solve your problem, and hopefully others?

**Comment by rfay** [comment]
@sbiniok if I can get you to try out https://github.com/drud/ddev/pull/3976#issuecomment-1178454615 it may make it into the next release (soon) but if not, maybe not. Not many people use proxies.

**Comment by sbiniok** [comment]
Apologies for the late response. I installed your artifact (the amd64 Linux one) from #3976 and #3990. If I understood you correctly, the expected behaviour was for docker-compose to either auto-inject the proxy settings from the system's .bashrc/.zhsrc or for the custom Dockerfile content to be added earlier in the .webimageBuild/Dockerfile. After deleting the Dockerfile in web-build the resulting .webimageBuild/Dockerfile did not include any proxy settings:

### DDEV-injected base Dockerfile contents
ARG BASE_IMAGE
FROM $BASE_IMAGE

ARG username
ARG uid
ARG gid
RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username" || useradd  -l -m -s "/bin/bash" --gid "$gid" --comment '' "$username")

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests php8.1-ssh2 php8.1-oauth php8.1-amqp ffmpeg webp zip

RUN export XDEBUG_MODE=off && ( composer self-update --2 || composer self-update --2 || true )

RUN chmod 600 ~xxxx/.pgpass ~xxxx/.my.cnf
ENV NVM_DIR=/home/xxxx/.nvm

When the custom Dockerfile was present, it was still added to the bottom of the autogenerated file and thereby to late for the apt-get proxy settings.

**Comment by rfay** [comment]
Thanks, #3990 is the only one in play now. 

If you have HTTP_PROXY in your environment (use `echo $HTTP_PROXY` to see) then `ddev start` will create proxy settings. You can look to see the result in .ddev/.webimageBuild/Dockerfile. Maybe you can share the results of that, also show `ddev --version`

Thanks!

**Comment by rfay** [comment]
I went ahead and pulled this. If you use homebrew, you can now try out latest with `brew unlink ddev && brew install --HEAD --fetch-head drud/ddev/ddev`. If you use some other installation technique, you should find the necessary artifacts at https://nightly.link/drud/ddev/workflows/master-build/master

**Comment by rfay** [comment]
Don't bother with it now, we're going to give people many ways to do this, and the automatic proxy detection is coming out again I think.

**Comment by sbiniok** [comment]
The Homebrew one worked for me. The proxy settings and the Aquire for apt were added to the generated webimageBuild/Dockerfile.

Just out of curiosity for the artifacts: I did `which ddev` and got the path `/home/linuxbrew/.linuxbrew/bin/ddev`. That file I switched to the one from you artifact (ddev-linux-amd64.zip). Before the switch my `ddev --version` was 1.19.2. Afterwards, it's 1.19.3. So the file definitely changed. Which version was it supposed to show? Maybe I had to replace some other file instead?

**Comment by rfay** [comment]
Thanks so much for testing @sbiniok - We're going to do our best to get something that works for you here. You're the only user I know of behind a proxy so your real-life testing is super-important. I have a lab setup with VMs, but don't know if it reflects real-life situations. What OS are you on, and what docker provider? Could you please do a `ddev debug test` and give the results in a gist on gist.github.com that you give a link to? That will help me understand some things. It's possible that I should add proxy info to the test as well. And maybe .ddev/.webimageBuild/Dockerfile :)

As far as artifacts and results: 
* Right now, `brew install --HEAD --fetch-head ddev` results in 
```
$ ddev --version
ddev version vHEAD-6dea104
```

* Downloading the artifacts from https://github.com/drud/ddev/pull/3990#issuecomment-1182446024 results in this:
```
rfay@rfay-mbp-2021:~/Downloads$ pwd
/Users/rfay/Downloads
rfay@rfay-mbp-2021:~/Downloads$ wget https://nightly.link/drud/ddev/actions/artifacts/296802612.zip
--2022-07-15 11:25:05--  https://nightly.link/drud/ddev/actions/artifacts/296802612.zip
Resolving nightly.link (nightly.link)... 45.32.185.199
Connecting to nightly.link (nightly.link)|45.32.185.199|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://pipelines.actions.githubusercontent.com/serviceHosts/ace3f862-ebae-4526-89f3-21413f9fe484/_apis/pipelines/1/runs/13487/signedartifactscontent?artifactName=ddev-macos-arm64&urlExpires=2022-07-15T17%3A26%3A06.9962695Z&urlSigningMethod=HMACV2&urlSignature=%2BLBTmmKzJNHBtBXnw2SPt%2FjkevdsxRde6Z4JbDEQZR0%3D [following]
--2022-07-15 11:25:07--  https://pipelines.actions.githubusercontent.com/serviceHosts/ace3f862-ebae-4526-89f3-21413f9fe484/_apis/pipelines/1/runs/13487/signedartifactscontent?artifactName=ddev-macos-arm64&urlExpires=2022-07-15T17%3A26%3A06.9962695Z&urlSigningMethod=HMACV2&urlSignature=%2BLBTmmKzJNHBtBXnw2SPt%2FjkevdsxRde6Z4JbDEQZR0%3D
Resolving pipelines.actions.githubusercontent.com (pipelines.actions.githubusercontent.com)... 13.107.42.16
Connecting to pipelines.actions.githubusercontent.com (pipelines.actions.githubusercontent.com)|13.107.42.16|:443... connected.
uHTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘296802612.zip’

296802612.zip                        [      <=>                                                 ]   7.83M  4.75MB/s    in 1.6s

2022-07-15 11:25:09 (4.75 MB/s) - ‘296802612.zip’ saved [8210671]

rfay@rfay-mbp-2021:~/Downloads$ unzip -l 296802612.zip
Archive:  296802612.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
 16111330  07-13-2022 02:00   ddev
---------                     -------
 16111330                     1 file
rfay@rfay-mbp-2021:~/Downloads$ unzip 296802612.zip
Archive:  296802612.zip
  inflating: ddev
rfay@rfay-mbp-2021:~/Downloads$ ls -l ddev
ddev                                          ddev_macos-amd64.v1.19.4-aj1.tar.gz
ddev-logo.png                                 ddev_macos-arm64.v1.19.4-aj1.tar.gz
ddev_1.19.4-aa2_darwin_arm64/                 ddev_shell_completion_scripts.v1.19.3/
ddev_1.19.4-aa2_darwin_arm64.tar.gz           ddev_shell_completion_scripts.v1.19.3.tar.gz
ddev_linux-arm64.v1.19.3.tar.gz
rfay@rfay-mbp-2021:~/Downloads$ ls -l ddev
-rw-r--r--  1 rfay  staff  16111330 Jul 13 02:00 ddev
rfay@rfay-mbp-2021:~/Downloads$ chmod +x ddev
rfay@rfay-mbp-2021:~/Downloads$ ./ddev --version
ddev version v1.19.4-alpha3-13-gd880ac81
```

I'm surprised to see that the `ddev` executable here does not have executable mode by default, so maybe that's what tripped you up? If it's not executable and not (early) in the PATH then you won't be running it.

I'll fix the build process that doesn't make that executable if possible. That may be github's fault, but I'll see if it can make sure to deliver executable binaries inside that zipball.

BTW, we're giving this yet another try in https://github.com/drud/ddev/pull/3999, because we want this set of things to work for everybody. So please hang with us and test. I know it's a pain, and we seem to be on radically different timezones, but I really hope to make it work for your situation and everybody else's as well.

**Comment by sbiniok** [comment]
@rfay I really appreciate the effort! And yes, I am on German time, so I apologize for any delays in response. After chmod +x on the artifact `ddev --version` indeed showed v1.19.4-alpha3-13-gd880ac81. You can find the gist with the output of ddev debug test [here](https://gist.github.com/sbiniok/828e2b8de3e07b7585ed344777975bf0).

Using the pre.Dockerfile approach discussed in #3999, everything seems to work fine in terms of proxy settings inside the .webimgeBuild/Dockerfile:
```
#ddev-generated - Do not modify this file; your modifications will be overwritten.

### DDEV-injected base Dockerfile contents
ARG BASE_IMAGE
FROM $BASE_IMAGE

ARG username
ARG uid
ARG gid
RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username" || useradd  -l -m -s "/bin/bash" --gid "$gid" --comment '' "$username")


### From user file /home/xxxx/projects/othub/.ddev/web-build/pre.Dockerfile:
ENV HTTP_PROXY http://X.X.X.X:XXXX
ENV HTTPS_PROXY http://X.X.X.X:XXXX

RUN if [ ! -z "${HTTP_PROXY}" ]; then printf "Acquire {\nHTTP::proxy \"$HTTP_PROXY\";\nHTTPS::proxy \"$HTTPS_PROXY\";\n}\n"  > /etc/apt/apt.conf.d/proxy.conf ; fi
### DDEV-injected from webimage_extra_packages or dbimage_extra_packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests php8.1-ssh2 php8.1-oauth php8.1-amqp ffmpeg webp zip

### DDEV-injected composer update
RUN export XDEBUG_MODE=off && ( composer self-update --2 || composer self-update --2 || true )

### DDEV-injected extra content

RUN chmod 600 ~xxxx/.pgpass ~xxxx/.my.cnf
ENV NVM_DIR=/home/xxxx/.nvm
```
Obviously I did have to remove the
```
ARG BASE_IMAGE
FROM $BASE_IMAGE
```
Other than that, simply moving the custom Dockerfile content to pre.Dockerfile seems to work a treat and is a great way of giving users the ability to inject configs early on in the process!

**Comment by rfay** [comment]
Now to ask you to do it again  with DDEV v1.19.5, released yesterday.

1. Upgrade to DDEV v1.19.5
2. Remove any proxy adaptations you've done, anything you've put in a custom Dockerfile
3. `ddev get rfay/ddev-proxy-support`, which is an add-on that uses the new pre-Dockerfile feature to do what you need. More info at https://github.com/rfay/ddev-proxy-support - if it works out for you and others it will be promoted to an official add-on.
4. `ddev restart`

Thanks for working along on this!

**Comment by sbiniok** [comment]
I installed ddev 1.19.5 and rfay/ddev-proxy-support and it works perfectly in multiple projects with all my custom proxy settings removed while still installing extra packages via the web-build/Dockerfile. Thank you so much for your help @rfay!

**Comment by rfay** [comment]
Just a note @sbiniok - ddev-proxy-support has been promoted to drud/ddev-proxy-support, so please use that one in the future. I don't think you'll find any changes at this time.  (rfay/ddev-proxy-support is now a fork)
