### ISSUE TITLE
docs: search broken, snippets huge, don't use mkdocs-material-insiders

### ISSUE THREAD

**Issue by rfay** [drud/ddev#3967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

The new docs has search that is not useful, has to be fixed. Go to https://ddev.readthedocs.io/en/latest/ and search and you get a wall of text like this:

<img width="1066" alt="Get_Started_with_DDEV_-_DDEV-Local_Documentation" src="https://user-images.githubusercontent.com/112444/177801390-7e579648-c6f7-49bb-818c-9edeaba86010.png">
 

### Current Behavior

Wall of text

### Expected Behavior

Useful results

**Comment by rfay** [comment]
Chased this in https://github.com/readthedocs/readthedocs.org/issues/9419 but it definitely doesn't appear to be readthedocs.

**Comment by tyler36** [comment]
Confirmed. Encounted this this morning when I search for "addon".

**Comment by rfay** [comment]
The bottom-line problem here is that I had started to use features from [mkdocs-material-insiders](https://squidfunk.github.io/mkdocs-material/insiders/) because it seemed like a good idea. But then I realized it wasn't a good idea, because it messes up our entire open-source workflow. 

#3980 restores search functionality, but does it by adding mkdocs-material-insiders back in as a stop-gap. Next stop here will be to figure out how to completely back out mkdocs-material-insiders.
