### ISSUE TITLE
ddev-router on start failed: failed to create new OS thread (have 2 already; errno=22)

### ISSUE THREAD

**Issue by juliandi01** [drud/ddev#3971]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

[Gist-Link](https://gist.github.com/juliandi01/c8631d8550d1701d1b8264c323d5e01a)

### Current Behavior

I tried to setup ddev like described in documentation. After ddev-router tried to start, I'll get following error message: 
`Failed to start project: ddev-router failed to become ready; debug with 'docker logs ddev-router'; logOutput=nginx config valid:OK  ddev nginx config not yet generated , err=container /ddev-router unhealthy: nginx config valid:OK  ddev nginx config not yet generated `

After I run `docker logs ddev-router` I'll gett following debug message:
```
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x884500, 0x9)
        /usr/local/go1.6/src/runtime/panic.go:530 +0x90
runtime.newosproc(0xc820026000, 0xc820035fc0)
        /usr/local/go1.6/src/runtime/os1_linux.go:149 +0x18c
runtime.newm(0x932358, 0x0)
        /usr/local/go1.6/src/runtime/proc.go:1513 +0x135
runtime.main.func1()
        /usr/local/go1.6/src/runtime/proc.go:125 +0x2c
runtime.systemstack(0xa8e800)
        /usr/local/go1.6/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
        /usr/local/go1.6/src/runtime/proc.go:1048

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go1.6/src/runtime/asm_amd64.s:245 fp=0xc820020770 sp=0xc820020768
runtime.main()
        /usr/local/go1.6/src/runtime/proc.go:126 +0x62 fp=0xc8200207c0 sp=0xc820020770
runtime.goexit()
        /usr/local/go1.6/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200207c8 sp=0xc8200207c0
```

### Expected Behavior

ddev-router start correctly with `ddev start`

### Steps To Reproduce

1. Clone project from git repository
2. Run `ddev config`
3. Fill out config
4. Run `ddev start`

**Comment by juliandi01** [comment]
After I upgrading to the newest ddev and docker version, ddev-router still not become ready.
I already tried the troubleshooting steps and I turned off all VPN/Firewall.
Any other ideas?

**Comment by rfay** [comment]
1. Please upgrade docker to current 4.10.1. It won't make a difference, but we'll all be on the same page that way.
2. Please upgrade ddev to current v1.19.3. That also won't make a difference but...
3. Are you also using a proxy? If so, that's important and things have to change.
4. With the VPN and virus checker and firewall off (and proxy off) , and default docker settings, please do the `ddev debug test` again and provide a link here.

**Comment by juliandi01** [comment]
No, I'm not using any proxy.
[Here is the new debug link](https://gist.github.com/juliandi01/f987d0867d1fd722215cb49234ee9894)

**Comment by rfay** [comment]
Thanks so much for doing that. I think the only time I've seen this kind of behavior is when there's a proxy that tries to proxy 127.0.0.1

If that test project is still there (or create a new one), you can change directory into it (see `ddev list` for the directory) and

1. `ddev exec 'rm -f /tmp/healthy && bash -x /healthcheck.sh'` and add as a new file to the gist
2. `ddev exec 'set |grep PROXY'`
3. `ddev exec ping -c 1 127.0.0.1`
4. `ddev exec curl -I 127.0.0.1`

You can also experiment with what's going on by using `ddev ssh` and then `curl localhost` to see if you get a result.  

Thanks!

**Comment by juliandi01** [comment]
No, it does not look familiar to me. But why its redirecting there?

When i type item #2, I don't get any response from terminal

**Comment by juliandi01** [comment]
I already executed `docker rm -f $(docker ps -aq)` many many times, without any result.

When I start my dummy project (created by `ddev debug test`) and run `ddev exec curl -L 127.0.0.1` I get following message: `Success accessing database... db via TCP/IP ddev is working. You will want to delete this project with "ddev delete -Oy tryddevproject-16670"`

My Proxies settings in Docker Desktop are turned off.

**Comment by rfay** [comment]
Hmm, now it's working it seems? Something has changed? 

Could you please try Colima and see if it works better for you? You don't have to uninstall Docker Desktop or anything. https://ddev.readthedocs.io/en/latest/users/install/docker-installation/

I'll be back later today and will be around mostly tomorrow. I'll be happy to do a screenshare call with you. Let me know what time might be convenient. I'm in US MT, UTC-7

**Comment by rfay** [comment]
This is what you should be seeing:

```
$ ddev exec curl -I 127.0.0.1
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 12 Jul 2022 18:40:57 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding```

Instead, you have (at least sometimes) a redirect, (302) as demonstrated in https://github.com/drud/ddev/issues/3971#issuecomment-1180402602

That means that apparently you're hitting a webserver *other* than the one that's built into the web container. 

I appreciate you taking the time to try to chase this down, I know we can get it.

**Comment by juliandi01** [comment]
I'm currently working with dockware, that seems to work correctly.

Sadly I don't know, why ddev is not working for me.

**Comment by rfay** [comment]
It would be a great thing if you could take the time to help sort it out, by working on it or trying colima. I don't know what dockware is, but I assume you stopped it during these exercises?

**Comment by juliandi01** [comment]
Yes, I stopped it every time. I will try now, using colima with ddev.

**Comment by rfay** [comment]
Thank you so much. Even though you already have another environment that works for you, getting this solved helps others in this community. At least I assume this will happen again if it's happened to you. It's never been reported before except in cases of VPN or Proxy being involved.

**Comment by juliandi01** [comment]
DDEV still don't work, even with colima. I get the same error message like with docker

**Comment by rfay** [comment]
Again, I'd love to help you solve this, and it would be a gift to the community. But I don't think I have anything to offer besides an interactive screenshare session.

**Comment by rfay** [comment]
Another random thought: You don't have pi-hole running in your network do you?

**Comment by rfay** [comment]
I have a couple of more thoughts. 

1. Please remove your global config temporarily and see if it fixes things. `mv ~/.ddev ~/.ddev.bak`. In experimentation today I found that a global ~/.ddev/homeadditions/.bashrc.d script could cause behavior like yours.
2. To try to get more information about situations like yours I have improved the test_ddev.sh script that is run by `ddev debug test`. If you could download the PR's [test_ddev.sh](https://raw.githubusercontent.com/drud/ddev/b07eb48487eb62d5386da0898a10aa08aad65574/cmd/ddev/cmd/scripts/test_ddev.sh) and run it and give the results as yet another gist it would be wonderful.

Hoping we can understand this!

**Comment by juliandi01** [comment]
Thank you so much for your help so far!

I've tried to remove my global config without any success.

I've run your test script [here](https://gist.github.com/juliandi01/736d148591a52895a74d21dee4e344d9).

**Comment by juliandi01** [comment]
> Another random thought: You don't have pi-hole running in your network do you?

I don't have any pi-hole running in my network

**Comment by rfay** [comment]
Thanks for hanging in there. I don't have anything to offer besides a zoom or google meet to take a look.

**Comment by rfay** [comment]
Again, happy to work with you on this, just say the word. Closing this as no response after some time.

**Comment by scottatdrake** [comment]
@rfay I'm having the same or very similar issue after upgrading from ddev 1.19 to 1.20 this morning. Here is the contents of the debugging scripty output:

[test_ddev_output.txt](https://gist.github.com/scottatdrake/438028f9a7337af96c2f0bb90a96594e)

I have tried updating docker, and removing my global config as suggested above. If you have any ideas or would like to zoom, I would _love_ any help.

**Comment by rfay** [comment]
Thanks for the output @scottatdrake  - You did a `ddev poweroff` and restarting docker right? I'd be happy to do a screenshare call with you to try to sort this out. I also recommend `docker rm -f $(docker ps -aq) && docker rmi -f $(docker images -q)` to get a fresh start on all images. I'd love to know what's going on with this. 

I can do a call today, I'm on US MT,  UTC-6.

**Comment by rfay** [comment]
If you can come over to Discord, https://discord.gg/hCZFfAMc5k it will be easier for us to set up call and communicate better.

**Comment by rfay** [comment]
(tried your meeting ID, said it wasn't valid)

**Comment by scottatdrake** [comment]
Big thank you to @rfay for helping me figure this out. This stack overthrow thread provided the breakthrough: https://stackoverflow.com/questions/66349391/failed-to-create-new-os-thread-have-2-already-errno-22 

I'm on an Apple M1 chip and at some point in the past had set an environment variable `DOCKER_DEFAULT_PLATFORM=linux/amd64` in my `~/.zshenv` file (which could also have been set in `.bash_profile`, `.bashrc`, etc).  After removing that variable and removing the existing images in order to start fresh, the `ddev start` command completed successfully.

**Comment by rfay** [comment]
@juliandi01 I imagine that this was your problem also. If not, it will be a related problem, somehow running the amd64 ddev-router on your arm64 machine.

**Comment by juliandi01** [comment]
@rfay @scottatdrake Thank you very very much! It worked for me! I had this if-clause in my ~/.zshrc file:

`export DOCKER_DEFAULT_PLATFORM=linux/amd64
# useful only for Mac OS Silicon M1,
# still working but useless for the other platforms
docker() {
 if [[ `uname -m` == "arm64" ]] && [[ "$1" == "run" || "$1" == "build" ]]; then
    /usr/local/bin/docker "$1" --platform linux/amd64 "${@:2}"
  else
     /usr/local/bin/docker "$@"
  fi
}`

After comment out everything, ddev successfully started!

**Comment by rfay** [comment]
Yay!

**Comment by scottatdrake** [comment]
Excellent, @juliandi01! Thanks again, @rfay !
