### ISSUE TITLE
allow `ddev get` to function without Docker

### ISSUE THREAD

**Issue by tyler36** [drud/ddev#3972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I wanted to see a list of  ddev addon so I ran `ddev get --list`.
It complained because I had not started docker.

### Describe the solution you'd like

I feel like listing addons and installing them does not require Docker. This is simply querying github and pulling down files, no? 
If so, it would be nice to be able to run `ddev get ...` commands without Docker.

Obviously running them requires Docker.

### Additional context

On my system, Docker Desktop does not start correctly if ESET is running a background scan. I have to wait until it finished.
Also, if I need to restart WSL, I have to restart Docker Desktop too to re-inject the docker files. 
So there are times when I do not have Docker Desktop available.

**Comment by rfay** [comment]
I'm working on an add-on that definitely needs docker running :( 

This was a really difficult set of back-and-forth bugs already about what could run with and what could run without. I won't be voting for `ddev get` to be one of the "without" ones though. If you knew how many times it already went back and forth you'd be really sympathetic :)

**Comment by tyler36** [comment]
Thank you. I understand.
