### ISSUE TITLE
promote ddev-cron

### ISSUE THREAD

**Issue by tyler36** [drud/ddev#3974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

After using this without issue, I think its ready.

### Describe the solution you'd like

Promote to offical status.

**Comment by rfay** [comment]
Awesome! 

For both of these, moving from an "owner" account to an "org" account is slightly difficult. If you have an org account it can be transferred to first, that will work, or I have one that can be used for the intermediate situation.  With an individual account, you can't invite a collaborator as "owner" who can then move it to the drud org. 

I invited you as owner to the "pdevlocal" org; that way you can transfer these there, give me privs on it, and I can transfer them to drud then.

**Comment by tyler36** [comment]
transfer

**Comment by rfay** [comment]
Both are moved, thanks!
