### ISSUE TITLE
Need to be able to prepend Dockerfile commands before nodejs is installed due to corporate network SSL termination proxy

### ISSUE THREAD

**Issue by davereid-pfg** [drud/ddev#3988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Due to our corporate network using a SSL termination proxy for all HTTPS traffic, we need to install some manual CA certificates before our environments attempt to "talk" to anything using cURL or apt.

### Describe the solution you'd like

I would like to be able to *prepend* Dockerfile commands before the commands are generated by DDEV to install NodeJS via cURL and apt. The only way to modify the generated Dockerfile is by appending things after the generated contents.

### Describe alternatives you've considered

We currently have to turn off the `nodejs_version` setting in our config.yaml file, and manually add NodeJS back in our Dockerfile appending file:

```Dockerfile
ARG BASE_IMAGE
FROM $BASE_IMAGE

COPY *.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates --fresh

# This line is basically just copied from the .ddev/.webimageBuild/Dockerfile that was auto-generated by DDEV but now it runs after our certificates
RUN curl -sSL --fail https://deb.nodesource.com/setup_14.x | bash - && apt-get install nodejs && npm config set unsafe-perm true && npm install --global gulp-cli yarn
```

### Additional context

This is related to https://github.com/drud/ddev/issues/3960 but is a more generic ask to solve our problem since we not actually using an actual proxy.

**Comment by rfay** [comment]
This feature is in DDEV v1.19.5, hope it works out for you @davereid-pfg , looking forward to how it comes out.
