### ISSUE TITLE
Stop/remove the nginx-proxy container if no sites are up

### ISSUE THREAD

**Issue by tannerjfco** [drud/ddev#40]
## What happened (or feature request):
Currently our nginx-proxy container remains running regardless of whether or not a user has sites active in ddev.

## What you expected to happen:
If there are no active sites, there should be no running nginx-proxy container. Occupying port 80 can be trouble for other programs that want to use it, and I suspect there were some issues that we couldn't get to the point of valid bug reports that might relate to this running full time. There should be no adverse impact to stopping it when no sites are active, so I think it's just worth doing.

## How to reproduce it (as minimally and precisely as possible):
Add a site, then remove it. Run `docker ps`, you will see the nginx-proxy container still running.

## Anything else do we need to know:
kalabox also has a similar container running full time, and it was obnoxious to get fully out of the way. It would be great to avoid that experience.

## Related source links or issues:

**Comment by rfay** [comment]
Thanks for pursuing this. Please make sure that it works with tests as well. Probably tests should always stop and rm it?

**Comment by rickmanelius** [comment]
To be clear, you're suggesting stopping (not removing) the proxy container when all sites are paused (not necessarily removed)?

**Comment by rfay** [comment]
I was actually thinking perhaps rm, since a test should start from clean.

**Comment by tannerjfco** [comment]
Realistically either would work, but I was intending rm. Either way, the proxy config should be updated when a new site is added.

**Comment by rickmanelius** [comment]
FWIW, I can't speak to what would be best from the architectural/code standpoint. I just wanted to make sure we had this testable and thus actionable for @tannerjfco!

**Comment by rickmanelius** [comment]
@tannerjfco @beeradb This would also be something helpful to get unstuck and actionable. I have no preference on the architecture side of things.

**Comment by beeradb** [comment]
I'm not sure anything needs to be done to make this actionable. Seems like a fairly straightforward task to me:

- If no sites are running, stop/remove the proxy :)

**Comment by rickmanelius** [comment]
@beeradb Understood. Even though my role is not to make technical/architectural decisions, my bias is towards challenging assumptions so that things are not missed or skirted over quickly. So expect more nitpicky follow-ups :)

**Comment by rfay** [comment]
This is fixed in https://github.com/drud/ddev/pull/204 so closing. Reopen if it's missing something I don't know about.
