### ISSUE TITLE
ddev get requires config.yaml, config.yaml precludes addon

### ISSUE THREAD

**Issue by paul-m** [drud/ddev#4014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

```
% ddev --version
ddev version v1.19.5
```

### Current Behavior

I want to use `ddev get` to create a new project, but I can't use an addon to manage `config.yaml`.
```
% mkdir foo && cd foo
% ddev get /Path/to/my/project
Unable to get project(s) [/Path/to/my/project]: could not find a project in /Users/paul/test/foo. Have you run 'ddev config'? Please specify a project name or change directories: no .ddev/config.yaml file was found in this directory or any parent
% ddev config --project-name=foo
Creating a new ddev project config in the current directory (/Users/paul/test/foo) 
Once completed, your configuration will be written to /Users/paul/test/foo/.ddev/config.yaml
 
Found a php codebase at /Users/paul/test/foo 
Configuration complete. You may now run 'ddev start'. 
% ddev get /Path/to/my/project
NOT overwriting file/directory /Users/paul/test/foo/.ddev/config.yaml. The #ddev-generated signature was not found in the file, so it will not be overwritten. You can just remove the file and use ddev get again if you want it to be replaced: signature was not found in file /Users/paul/test/foo/.ddev/config.yaml
[...]
```

ddev wants there to be a config file, but unless I add #ddev-generated manually to it, I can't replace it with the one from the addon.

This removes much of the convenience of having an addon that manages config.

Am I just mistaken about the use case for addons?

### Expected Behavior

```
% mkdir foo && cd foo
% ddev get my/addon
% ddev restart
# SUCCESS!
```

### Steps To Reproduce

Repro in 'Current Behavior'.

**Comment by paul-m** [comment]
Sorry, I should have said /Path/to/my/addon. I want to use an addon as a starting point.

I want to be able to tell people: "Type `ddev get my/addon` and you'll have the config you need."

Trying now, and `ddev config --auto` has the same issue: It adds a config.yaml file which then can't be managed through `ddev get` because it lacks the `#ddev-generated` tag.

If I'm not allowed to change config.yaml using the addon, that's fine, it's just not documented anywhere and this becomes a documentation issue.

Thanks!

**Comment by rfay** [comment]
You can *certainly* change config.yaml with your add-on. You can use `ddev config --<whatever>` in your pre-install scripts...

**Comment by paul-m** [comment]
`install.yaml` is trying to add my `config.yaml` file from the addon, but it can't because it's disallowed from managing it.

Ideally I'd be able to have a starting point that's just a file instead of a script that modifies the file, sort of like you do with `composer create-project`. Then the user can modify it however they need. But if that's not possible or out of scope or whatever, then OK.

So now it's two documentation issues:

1) Update addon docs to point out that you shouldn't copy config.yaml using addons, or maybe even have ddev complain when you try.

2) Document the fact that you can say `ddev config --whatever`, because that's not documented anywhere.

**Comment by rfay** [comment]
`ddev config --help` will show you the many options. 

If you'd like to collaborate and talk more about what you're up to, you're welcome in discord, https://discord.gg/hCZFfAMc5k

You can do some very impressive things in install.yaml, but I don't understand why you couldn't add `#ddev-generated` to the config.yaml. I don't understand why you can't completely replace the config.yaml if you add that in the pre-install script.

**Comment by paul-m** [comment]
After conversation with @rfay:

- Don't muck with config.yaml.
- Add config.addon-name.yaml to override as needed.
- Otherwise use install.yaml events/hooks to modify config.
- All of this will work much better after https://github.com/drud/ddev/pull/3983
- addons are KEWL.

**Comment by rfay** [comment]
I do think the day could come that `ddev start --auto` might be allowed - it could check to see if an accidental new project were being created. And that would mean that `ddev get --auto` might work as well, but as we've discussed here, it probably isn't necessary.
