### ISSUE TITLE
Links to quickstart guides do not work as expected

### ISSUE THREAD

**Issue by tyler36** [drud/ddev#4019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

I'm not sure sure if this is a bug, or a mkdocs limitation.

### Current Behavior

When I click a link to a quickstart guide, the page does nothing.

In the below, I have clicked on "Magento 2", but the "Any (generic)" tab is shown.
![image](https://user-images.githubusercontent.com/7234392/179644978-5decf836-adb1-4e84-bb24-2e69cb840989.png)

In addition, if I scroll to the bottom of the page, and and click a framework quickstart, it does nothing. It does not even move to the table.

### Expected Behavior

1. If I click a sidebar link to an (tab) item, the page should move to (opened) tab item.
2. If I share a link to `https://ddev.readthedocs.io/en/latest/users/quickstart/#laravel`, the page should open to "Laravel quickstart"

## Test 1 

- Visit https://ddev.readthedocs.io/en/latest/users/quickstart/
- Click "Magento" on the left sidebar under "Quickstart"
- "Magento" tab should be displayed

## Test 2

- Visit https://ddev.readthedocs.io/en/latest/users/quickstart/
- Scroll to bottom of page
- Click "Magento" on the left sidebar under "Quickstart"
- Page should scroll to Quickstart guide with "Magento" tab opened

## Test 3

- Click https://ddev.readthedocs.io/en/latest/users/quickstart/#laravel
- Page should display as below

![image](https://user-images.githubusercontent.com/7234392/179644900-a51726c4-2902-4cb2-abf8-7c7e2e9d2126.png)

### Anything else?

I think the ability to share "https://ddev.readthedocs.io/en/latest/users/quickstart/#laravel" and have it open to the correct place is a great first impression for new users.

**Comment by rfay** [comment]
I agree that this is important. And this feature is in mkdocs-material-insiders. Unfortunately, using mkdocs-material-insiders means that open-source users of ddev can't build the docs. 

There's a related and super-important issue that concerns me a lot
* https://github.com/squidfunk/mkdocs-material/issues/4125
If you do a search, it will get you to the right page, but the content you were looking for is likely hidden in a tab you don't have open.

I discussed this issue with @squidfunk, who offered to prioritize it as contract work, but we weren't able to come up with a path that would be useful to the whole mkdocs-material community, so he's holding it based on a search redesign.

**Comment by tyler36** [comment]
I don't think it is a search issue. It's a navigation issue.

"https://ddev.readthedocs.io/en/latest/users/quickstart/#laravel" does not navigate the page to relevant section.

**Comment by rfay** [comment]
There is no #laravel link on that tab is there? 

I was saying the search issue is related.

**Comment by tyler36** [comment]
If you look at the screenshot above, the is a "¶" permalink after the laravel title. Click this will naviagte the page to the id section.
If you paste this link in another tab, it does not function. 

Eg. A example of a correctly functioning navigation is "https://ddev.readthedocs.io/en/latest/users/install/shell-completion/#tar-archive-of-completion-scripts-for-manual-deployment"
This takes me to the right page, to the specific section.


## The issue
![image](https://user-images.githubusercontent.com/7234392/179649114-1fe96592-7eb5-4576-b7c5-48349cf6ff67.png)
Of these, 
- "[Any PHP or HTML/JS environment](https://ddev.readthedocs.io/en/latest/users/quickstart/#any-php-or-htmljs-environment)" works, 
- CMS framework links do not
- It works from again [Configuration Files](https://ddev.readthedocs.io/en/latest/users/quickstart/#configuration-files)

**Comment by rfay** [comment]
Links to non-tabs work fine (the ones you show as working). But there are no anchors on those tabs that I can see. I don't see any tab that has an anchor on it.

**Comment by rfay** [comment]
Oh, I see -you're talking about the nav bar on the left, which seems to have links to tabs, but the tabs themselves don't have anchors, so it doesn't work. 

I thought you were just talking about the fact that you can't share a useful link to a tab.

**Comment by tyler36** [comment]
> Oh, I see -you're talking about the nav bar on the left, 
Yes.

> I thought you were just talking about the fact that you can't share a useful link to a tab.
It's related. The nav bar links does not work. If I right click and copy link, it doesn't work.

**Comment by rfay** [comment]
Looks like we have

* https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
* https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#superfences
* https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#tabbed

The next item in the docs is [anchor links](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#anchor-links) which is insiders.

However, I see [linked content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#linked-content-tabs) which is not insider (but is experimental).

Our feature lists are at https://github.com/drud/ddev/blob/cc268cbf550025a00f32a4227a74d99feb03031c/mkdocs.yml#L20-L36

**Comment by rfay** [comment]
I added headers in all the tabs, which helps this a little, but it's still pretty ugly because if you're not on the right tab you still can't get anywhere.

Should we remove the left-hand nav bar for now?

**Comment by tyler36** [comment]
2 option:
- remove left-hand nav bar
- link frameworks to parent. Id. Quickstart for many CMSs

Personal, I would rather they link somewhere. "Quickstart for many CMSs" seems like the ideal situation.

Would you prefer "nav bar missing links to quickstart" or "navbar quickstart links broken" bug reports down the line?

**Comment by rfay** [comment]
Added a comment on this issue at https://github.com/squidfunk/mkdocs-material/issues/4125#issuecomment-1193135894

**Comment by rfay** [comment]
It looks like from 
* https://github.com/squidfunk/mkdocs-material/issues/4125#issuecomment-1194185924
there won't be any solutions coming from mkdocs-material in the short term.

Should we just rip out all the tabs and turn them into headers and be sad? They're so great for categorizing content, but now that nav doesn't work and search doesn't work, it seems like we're at a dead end for now.

Thoughts?

**Comment by rfay** [comment]
* https://github.com/drud/ddev/pull/4046 
has fixed the original complaint here I think, but we certainly haven't won the war. 

See also
* https://github.com/drud/ddev/issues/4059

**Comment by rfay** [comment]
It seems to me like @mikesnoeren 's fixes have added up to complete success on this. Hope you agree @tyler36 , or we'll reopen. Congratulations @mikesnoeren !
