### ISSUE TITLE
mkcert should be *dependency* of ddev, not bundled, in apt package

### ISSUE THREAD

**Issue by bserem** [drud/ddev#4021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running `apt install ddev` from new Debian repos the installation fails if `mkcert` is already installed in the system:

```
$ sudo apt install -y ddev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  ddev
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
1 not fully installed or removed.
Need to get 0 B/11.6 MB of archives.
After this operation, 21.5 MB of additional disk space will be used.
(Reading database ... 333147 files and directories currently installed.)
Preparing to unpack .../archives/ddev_1.19.5_amd64.deb ...
Unpacking ddev (1.19.5) ...
dpkg: error processing archive /var/cache/apt/archives/ddev_1.19.5_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/mkcert', which is also in package mkcert 1.4.3-1+b1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/ddev_1.19.5_amd64.deb
```

Removing/purging mkcert (`apt purge mkcert`) and trying to install ddev again solves the problem.

### Expected Behavior

DDEV should be able to be installed alongside mkcert package, ideally DDEV should require mkcert rather than providing its own.

### Steps To Reproduce

1. Install `mkcert`
2. Install `ddev`
3. **See it fail**
4. Remove `mkcert`
5. Install `ddev`
6. **See it work**
7. Try to install `mkcert` affter ddev
8. See it fail

### Anything else?

Trying to install `ddev` when `mkcert` is already installed:
![image](https://user-images.githubusercontent.com/520237/179711431-28768eb2-20b2-495c-99f7-df98d1fea32c.png)

Trying to install `mkcert` when `ddev` is already installed:
![image](https://user-images.githubusercontent.com/520237/179711537-97be9d98-2b2c-4032-882b-a3cb0dad0ec4.png)

**Comment by rfay** [comment]
Thanks - I didn't even know that mkcert was available in apt, or it would be a dependency instead of bundled in. I thought I checked that.

**Comment by bserem** [comment]
Can't blame you, depending on which version of Debian you use you might not have it:
https://packages.debian.org/bookworm/mkcert

**Comment by rfay** [comment]
Oh, if you're running unreleased bookworm then that doesn't count. 

Available:
* Ubuntu 22.04

Not available:
* Ubuntu 20.04
* Debian 11 Bullseye 

I guess the way to resolve this is to make `mkcert` a "conflicts" item in the nfpms section, https://goreleaser.com/customization/nfpm/

**Comment by rfay** [comment]
Added a note in https://github.com/FiloSottile/mkcert/issues/369#issuecomment-1189184589, seems like somebody should do a README PR there to show the current state of things. But I wonder who is doing the package maintenance.

**Comment by rfay** [comment]
https://github.com/drud/ddev/pull/4027 fixes this by replacing mkcert with ddev. Please remember in a couple of years to remind us to change this!
