### ISSUE TITLE
drud/drupal8 site.tar.gz is a d7 site, has loads of .git that it doesn't need

### ISSUE THREAD

**Issue by rfay** [drud/ddev#403]
## What happened (or feature request):

I noted in tests that https://github.com/drud/drupal8/releases/download/v0.6.0/site.tar.gz actually contains a d7 kickstart site, which also contains extra files in .git, making things probably take longer. 

I think these were added for #303

I recommend that we 
* Use a d8 site tarball
* Remove the .git directories that got into the commerce_kickstart profile for windows performance reasons. (in the drupal7_kickstart version I imagine) 

This isn't a very big problem, but we don't seem to be testing what we think we're testing. 

## What you expected to happen:

I expected a d8 site in there

## Related source links or issues:

**Comment by rickmanelius** [comment]
@rfay Seems like a quick win/fix. Thanks for catching that! Feel free to knock this out while waiting for other test runs to complete, etc :)

**Comment by rfay** [comment]
I replaced this with a somewhat smaller D8 tarball, but it really matters very little. It's kind of a wasted exercise, as it seems we could use a far smaller tarball and include it in our checked-in testdata. Kicked off https://circleci.com/gh/drud/ddev/1385 to test it, if that succeeds we can close this.

**Comment by rfay** [comment]
Closing as it's fixed up there.
