### ISSUE TITLE
Set up node.js to trust mkcert CA

### ISSUE THREAD

**Issue by cweagans** [drud/ddev#4032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

We're trying to run a node.js script in the web container that sends requests to Drupal at the ddev project URL over HTTPS. Node.js has made the decision to maintain their own list of trusted certs for reasons that are unclear to me, so the CAs that are configured to be trusted at the OS-level don't help.

### Describe the solution you'd like

By default, let's set `NODE_EXTRA_CA_CERTS=/mnt/ddev-global-cache/mkcert/rootCA.pem` in the web container. This will tell Node to trust the mkcert CA.

**Comment by rfay** [comment]
Sounds like a good idea. Can you please add links to the relevant nodejs info/docs?

**Comment by rfay** [comment]
I assume that this works for you just adding that environment variable to web_environment in config.yaml?

**Comment by cweagans** [comment]
> Sounds like a good idea. Can you please add links to the relevant nodejs info/docs?

https://nodejs.org/api/cli.html#node_extra_ca_certsfile

> I assume that this works for you just adding that environment variable to web_environment in config.yaml?

Yep!

**Comment by rfay** [comment]
I'd sure appreciate you chiming in on https://github.com/drud/ddev/issues/3456 to say how you're using nodejs.

**Comment by rfay** [comment]
@cweagans could you please test https://github.com/drud/ddev/pull/4049 ?

Can you please suggest testing strategy there that will validate your situation?

**Comment by appleoddity** [comment]
This change hardcodes the dev environment root certificate into the docker-compose template which will overwrite the same environment variable if it is included in a custom Dockerfile. While this change might make sense for many environments, where node only needs to hit the local dev environment, it ignores that there are many other scenarios where custom root certificates might be needed, such as the case with SSL inspection.

Therefore, IMO, docker-compose should not overwrite `NODE_EXTRA_CA_CERTS`, and instead the user should have to make a choice of what certs to use, and how to use them (i.e. extending Dockerfile, or extending docker-compose). By assuming they want the dev root cert, it creates other unexpected behavior when trying to use a custom Dockerfile.

See here: https://github.com/ddev/ddev/issues/7209#issuecomment-2802858214
