### ISSUE TITLE
[Docs bug] Link to logos goes to a 404

### ISSUE THREAD

**Issue by RCheesley** [drud/ddev#4034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

N/A

### Current Behavior

When I go to https://ddev.readthedocs.io/en/latest/developers/styleguide/ there is a link to https://ddev.readthedocs.io/en/latest/developers/styleguide/logos which lands on a 404. Maybe the docs re-org has re-org'd them or the link is just broken, not sure!

### Expected Behavior

Go to a page or resource where the logos can be downloaded.

### Steps To Reproduce

As above :) 

### Anything else?

I am happy to make a PR to fix, but I could do with some guidance as to where the link _should_ go.

Maybe it should be going to https://github.com/drud/ddev/tree/master/docs/content/developers/logos or should there be some webpage listing out all the logos?

**Comment by rfay** [comment]
Thanks! Yes, the logos are in docs/content/developers/logos

Not sure how the link checker is missing yet another thing. 

I'm pretty sure though that mkdocs will balk at just a directory link. In the past, this developer section was only normally viewed using github, not on readthedocs/mkdocs. 

A simple solution would be to just link to the right place on github, https://github.com/drud/ddev/tree/master/docs/content/developers/logos

**Comment by rfay** [comment]
This will be fixed this week in a talk to a women in tech group about contributing to open source.
