### ISSUE TITLE
Unable to pull db from pantheon after switching to colima

### ISSUE THREAD

**Issue by tekNorah** [drud/ddev#4035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/tekNorah/86a17375f28d03ccfad7279ed53123bb

### Current Behavior

When I attempt to run `ddev pull pantheon --skip-files -y`, I encounter the error: `HTTP request has failed with error "Maximum retry attempts reached".`

This error occurs when `terminus backup:get ${project} --element=db --to=db.sql.gz` is run within the `db_pull_command`.

I am able to run this terminus command successfully outside of ddev.

If I ssh into ddev first, then run the terminus command above, I get the same error.  If I add the `--verbose` flag to the terminus command, I see warnings similar to the following:

```
[warning] HTTP request GET https://storage.googleapis.com/gcs-pantheon-backups/{sitehash}/{env}/{instance}/{site}_{env}_{datetime}_database.sql.gz?Expires={timecode}&GoogleAccessId=url-signer-us%40pantheon-backups.iam.gserviceaccount.com&Signature={signaturekey} has failed: Connection refused for URI https://storage.googleapis.com/gcs-pantheon-backups/{sitehash}/{env}/{instance}/{site}_{env}_{datetime}_database.sql.gz?Expires={timecode}&GoogleAccessId=url-signer-us%40pantheon-backups.iam.gserviceaccount.com&Signature={signaturekey}
```

Attempting to download the file via `wget {uri}` produces similar results, with the following output:

```
Resolving storage.googleapis.com (storage.googleapis.com)... failed: No address associated with hostname.
wget: unable to resolve host address ‘storage.googleapis.com’
```

### mkcert is installed

```
mkcert -install
The local CA is already installed in the system trust store! 👍
```

### Expected Behavior

I expect the `ddev pull` command to be able to successfully download the latest database

### Steps To Reproduce

1. ddev pull pantheon --skip-files -y

### Anything else?

I also tried rebuilding the ddev project using `ddev delete --omit-snapshot && ddev config && ddev start`

**Comment by tekNorah** [comment]
Chat with pantheon support in case it is relevant:

> Conversation with Pantheon
> Started on July 20, 2022 at 06:24 PM America/Los_Angeles time PDT (GMT-0700)
> 
> ---
> 
> 06:24 PM | Norah Shannon: When I attempt to run terminus backup:get from within a ddev container, I am encountering the following error: HTTP request has failed with error "Maximum retry attempts reached".
> 
> 06:24 PM | Norah Shannon: This command works successfully outside of the ddev environment
> 
> 06:25 PM | Operator: You’ll get replies here and in your email:
> ✉️ norah.medlin@mediacurrent.com 
>  Our usual reply time
> 🕒 under 4 minutes
> 
> 06:25 PM | Norah Shannon: Digging into this a bit more, when I include the --verbose flag, I see the following message 
>  [warning] HTTP request GET https://storage.googleapis.com/gcs-pantheon-backups/{sitehash}/{env}/{instance}/{site}_{env}_{datetime}_database.sql.gz?Expires={timecode}&GoogleAccessId=url-signer-us%40pantheon-backups.iam.gserviceaccount.com&Signature={signaturekey} has failed: Connection refused for URI https://storage.googleapis.com/gcs-pantheon-backups/{sitehash}/{env}/{instance}/{site}_{env}_{datetime}_database.sql.gz?Expires={timecode}&GoogleAccessId=url-signer-us%40pantheon-backups.iam.gserviceaccount.com&Signature={signaturekey}
> 
> 06:26 PM | Norah Shannon: I have reported this issue to the ddev maintainer: https://github.com/drud/ddev/issues/4035
> 
> 06:29 PM | Norah Shannon: However, per the ddev maintainer: 
>  rfay — Today at 7:59 PM
> It passes the tests every night. But it's not colima or ddev if you run ddev exec terminus backup:get and it fails. I would imagine it's on their end.
> 
> 06:29 PM | Norah Shannon: So, I am checking with you to see if there are any known issues with running terminus commands from inside a ddev/colima container?
> 
> 06:30 PM | Adolfo from Pantheon: Hi Norah, I'm Adolfo, a Customer Success Engineer at Pantheon. I will be assisting you today. You may be right as we did not have any existing known issues about this on our end. This might be specific to ddev
> 
> 06:31 PM | Adolfo from Pantheon: I'll check with the team for a moment if somebody encounters this issue Norah, just to confirm
> 
> 06:32 PM | Norah Shannon: ok, thank you!
> 
> 06:37 PM | Adolfo from Pantheon: Hi Norah, would you try if your are logged in by running terminus whoami in the ddev container?
> 
> 06:38 PM | Adolfo from Pantheon: terminus whoami
> 
> 06:39 PM | Norah Shannon: ```ddev exec terminus whoami
> norah.medlin@mediacurrent.com```
> 
> 06:39 PM | Norah Shannon: `ddev exec terminus whoami
> norah.medlin@mediacurrent.com`
> 
> 06:39 PM | Norah Shannon: lol, tried to mark as code.. clearly I'm not as cool as you :)
> 
> 06:40 PM | Adolfo from Pantheon: oh, was it only failing on specific command like the
> 
> 06:40 PM | Adolfo from Pantheon: terminus backup:get
> 
> 06:40 PM | Adolfo from Pantheon: other command work?
> 
> 06:41 PM | Norah Shannon: correct
> 
> 06:41 PM | Norah Shannon: [Image "Screen+Shot+2022-07-20+at+8.40.43+PM.png?expires=1658370180&signature=9e568b6703466906106ce0b657b44bb0ec8ebdf5e153b89b1ee04c7d2b43c827"]
> 
> 06:41 PM | Norah Shannon: [Image "Screen+Shot+2022-07-20+at+8.41.38+PM.png?expires=1658370180&signature=c190e58a4861b54d8cf72ffee16ae56dc464bc3fb0464a4620650c958a986e20"]
> 
> 06:45 PM | Norah Shannon: I am able to click on that url and download via my browser, btw
> 
> 06:45 PM | Adolfo from Pantheon: Thanks for additional information, it seems that it can not authenticate to the google storage
> 
> 06:45 PM | Norah Shannon: but wget within the ddev container errors out
> 
> 06:45 PM | Norah Shannon: [Image "Screen+Shot+2022-07-20+at+8.44.45+PM.png?expires=1658370180&signature=d0630adf0da01e78f213edc0af6700b315aa2f6e559f1e78c9d012fbfe13dbd5"]
> 
> 06:48 PM | Adolfo from Pantheon: yep, Pantheon have limited support for ddev as this is a third party tool actually. But what happen if you try to ping the hostname inside the ddev container? ping storage.googleapis.com
> 
> 06:48 PM | Norah Shannon: `ping: storage.googleapis.com: No address associated with hostname`
> 
> 06:49 PM | Adolfo from Pantheon: Oh the container aren't able to resolve it
> 
> 06:49 PM | Adolfo from Pantheon: So this is specific to ddev
> 
> 06:49 PM | Norah Shannon: ok, that's what I suspected, thank you for confirming, I'll follow-up with ddev
> 
> 06:50 PM | Norah Shannon: just to be sure I'm asking the right stuff here
> 
> 06:50 PM | Norah Shannon: I am able to ping other uris from within ddev
> 
> 06:50 PM | Adolfo from Pantheon: Thank you Norah, I'll go ahead and close the chat then.
> 
> 06:50 PM | Norah Shannon: like google.com
> 
> 06:51 PM | Norah Shannon: so, am I encountering an issue, specifically with resolving/routing to just storage.googleapis.com
> 
> 06:51 PM | Norah Shannon: is that how you would describe the issue?
> 
> 06:52 PM | Adolfo from Pantheon: Yes that's right Norah
> 
> 06:52 PM | Norah Shannon: sweet! Thanks Adolfo!
> 
> 06:52 PM | Adolfo from Pantheon: Great! I'm glad I was able to help you out today Norah. I'll go ahead and close this chat for now, you are welcome to reach out to us anytime if you encounter some difficulties on your end and we are happy to help you.
> ﻿
> ﻿Feel free to leave us some feedback, We highly appreciate it!
> ﻿
> ﻿Nice having chat with you. thank you and have a nice day!
> ﻿
> ﻿Adolfo Nasol 
>  Customer Success Engineer 🐲 
>  Pantheon Systems, Inc.
> 
> 06:52 PM | Operator: Help Adolfo understand how they’re doing:
> 
> 06:53 PM | Operator: Rate your conversation
> 
> ---
> Exported from Pantheon on July 20, 2022 at 06:53 PM America/Los_Angeles time PDT (GMT-0700)

**Comment by rfay** [comment]
No response from OP, so closing, but happy to continue the conversation here or elsewhere.

**Comment by wstocker** [comment]
I ran into this issue as well and confirming that after `colima stop ` and  `colima start --dns 1.1.1.1`, I was able to do a successful pull from Pantheon.

**Comment by DonWeaver** [comment]
I also just hit this issue (after months of running Colima w/o issue). `colima stop` and `colima start --dns 1.1.1.1` got me successfully running `ddev pull pantheon`. Thank you!
