### ISSUE TITLE
How can I use amd64 components/Docker images on Mac M1 (arm64) (Answer: Don't try)

### ISSUE THREAD

**Issue by jigarius** [drud/ddev#4037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/jigarius/d4651814db6d56fd916d9d491b3e2630

### Current Behavior

- My web-build runs a script to install sqlsrv and pdo_sqlsrv extensions along with [ODBC drivers](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15) needed to connect with sqlsrv.
- The build works fine except on MacBooks with the Apple M1 chip.
- Upon doing some research, I found that running Docker with `platform: linux/x86_64` can solve this issue.
  - This makes Docker simulate x86/x64, so it fetches the relevant packages correctly.
  - With the M1 chip, it tries to fetch the packages for arm64 and fails.
- I created a basic `Dockerfile` for my web-build with the following code:
```
ARG BASE_IMAGE
FROM --platform=linux/x86_64 $BASE_IMAGE
```
- After this, the web build starts failing with non-zero exit code. Here's what I get with `dd logs -s web`.
```
Site 000-default already disabled
+ '[' false = true ']'
+ disable_xdebug
Disabled xdebug
+ phpenmod assert
+ ls /var/www/html
+ sudo mkdir -p /mnt/ddev-global-cache/terminus/cache
sudo: you do not exist in the passwd database
```

My question, in short, is whether there is an easier way to specify `platform` such that things would work.

### Expected Behavior

The build should succeed.

**Comment by rfay** [comment]
1. The bottom line is you'll never be happy using any amd64 components in Docker on a mac M1. Docker Desktop (and only Docker Desktop) went way out of its way to try to be able to run amd64 components, but it really doesn't work out in general. 
2. DDEV v1.19+ doesn't do the `ARG BASE_IMAGE` any more. 
3. If it's the pdo_sqlsrv packages you need, they can now be used with arm64, see https://github.com/microsoft/msphpsql/issues/1377 and https://github.com/drud/ddev-contrib/pull/168#issuecomment-1122244410
4. I think you'll find that the [ddev-contrib sql-srv recipe](https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/sqlsrv) may get you on the right path for a native implementation.

**Comment by rfay** [comment]
I hope that answer was adequate and you're doing well. Closing, no response. Happy to continue the conversation here or elsewhere.

**Comment by jigarius** [comment]
I haven't had a chance to try the contrib sql-srv recipe yet. I was able to install sql-srv completely, but I wasn't able to make my containers use the non-M1 architecture (that's probably called amd64).

I tried setting `DOCKER_DEFAULT_PLATFORM=linux/amd64` but Ddev builds stopped failing after that. So, my question to the Ddev team, in summary, stands at:

>What is the recommended way to use `amd64` platform with Ddev projects?

The equivalent of this in `docker-compose.yml` is `platform: linux/amd64` or something similar. I want to be able to decide the `platform:` key in the Docker compose services declaration in the easiest way possible.

Thanks a tonne (:

**Comment by rfay** [comment]
Mostly using `platform: linux/amd64` will just end up making you unhappy. It doesn't work with most amd64 images. You get random crashes and failures. It also won't work with colima (at all).

**Comment by jigarius** [comment]
I tried a custom `docker-compose.yml` which solved all my problems, namely:
- Add `openvpn` capabilities to the `web` container.
- Install `sqlsrv` drivers
- Install `msodbcsql` drivers

The only container I've modified is the `web` or the `php` container. I was wondering if there is a way with Ddev to override or add to the definition of the `web` service, so that I can:
- Set `platform: linux/amd64`
- Run a script to install everything I need for `sqlsrv` drivers for PHP.
- Enable `NET_ADMIN` capabilities.

Is there an easy way to achieve this? If not, I'm afraid I'll have to miss out on all the nice Ddev features on this project by switching to a plain old `docker-compose.yml` setup 😢

**Comment by rfay** [comment]
You'll find unpredictable behavior with this path, unfortunately. Broken behavior when you least expect it. 

I'm happy to help you get a real arm64 solution going, and since sqlsrv now has a way to do that, I highly recommend it. 

I'm sure @drupal-daffie will also be willing to help. 

But regardless, go forward :)

If you needed to run a container alongside the web container using linux/amd64, you'd do that with a separate service, not by trying to change the web container to amd64 with a Dockerfile.

**Comment by deviantintegral** [comment]
For anyone coming across this - there is a way to do this, which is useful if you need to debug platform specific issues. For example, I was just fixing an issue with a nodejs project where the package-lock.json was broken and only contained arm, and not intel references for native modules. Builds were working fine on developer locals, but not on our actual servers running Intel processors.

- Shut down the project if it's running
- Run `export DOCKER_DEFAULT_PLATFORM=linux/amd64`
- As https://stackoverflow.com/a/69839676 mentions you need to re-pull the images in use, such as `docker pull ddev/ddev-webserver:v1.23.3` and `docker pull ddev/ddev-traefik-router:v1.23.3` and any others your project uses (updating the ddev version to match).
- Run `ddev start` and do your work.
- When done, close your terminal window and re-pull images to flip back to the arm versions.

In my case, I was using colima with rosetta support, and I assume this works with all other docker providers as well.

**Comment by rfay** [comment]
Thanks for this workaround. 

I think the technique in https://ddev.com/blog/amd64-on-apple-silicon-ddev/ is probably easier and quicker, and is explicit on which Docker providers can do this with Rosetta.
