### ISSUE TITLE
Use quotes in user prompts, avoid backticks

### ISSUE THREAD

**Issue by rfay** [drud/ddev#404]
## What happened (or feature request):

We have some places in our ddev output where we are using backticks for punctuation around suggestions and such, but backticks are really for markdown, and not used in normal communication with people.  They won't be recognized by many of our users I don't think, and are not normal usage. They look normal to us because we do markdown all the time.

## What you expected to happen:

Use double or single quotes.

Please note that this has nothing to do with how we do markdown docs, where backticks are just right.

## Related source links or issues:

**Comment by rfay** [comment]
The items in question can be found with 
```
grep -r "\`ddev" pkg cmd
```
There are 9 of them that are util.Failed() and one that is a fmt.ErrrorF()

**Comment by rickmanelius** [comment]
Thanks! Just needs a review on the approach and then prioritization.

**Comment by rfay** [comment]
This is just 
- Agree it's valid
- Search and replace

**Comment by rickmanelius** [comment]
Fair point. Let's use single quotes and this is now actionable.

**Comment by cweagans** [comment]
There are a number of instances of using backticks in comments to refer to ddev commands. If I change those too, we could add a test to enforce not using this pattern going forward (basically just test that `grep -r "\`ddev" pkg cmd` returns zero results). Should I change *all* of these? Or just the ones that are in user-facing text?

**Comment by tannerjfco** [comment]
I believe we're just concerned with the user-facing instances of these. IMO its fine to backtick them in our code comments. I don't feel like a test is necessary to enforce it.

**Comment by cweagans** [comment]
PR is open.

**Comment by cweagans** [comment]
PR is merged.
