### ISSUE TITLE
[Docs] Link to "advanced test example" is a dead link

### ISSUE THREAD

**Issue by torenware** [drud/ddev#4044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

On the ["Additional Service Configurations and Add-ons for ddev"](https://ddev.readthedocs.io/en/latest/users/extend/additional-services/) page, 

Section ["Template action replacements (advanced)"](https://ddev.readthedocs.io/en/latest/users/extend/additional-services/#template-action-replacements-advanced),

the link to "advanced test *example*" (`https://ddev.readthedocs.io/en/cmd/ddev/cmd/testdata/TestCmdGetComplex/recipe/install.yaml`) is currently a dead link, and yields a 404 page.

### Current Behavior

Tried several times; I get the 404 Not Found page.

### Expected Behavior

A live link :-)

### Steps To Reproduce

Listed above; should be plain as a post.

**Comment by torenware** [comment]
The Issue ID even _has_ a 404 in it. WHAT ARE THE ODDS?

**Comment by tyler36** [comment]
Thanks for the report.

Confirmed as a dead link (404) .

**Comment by rfay** [comment]
The link can go to https://github.com/drud/ddev/blob/master/cmd/ddev/cmd/testdata/TestCmdGetComplex/recipe/install.yaml

**Comment by rfay** [comment]
This will be fixed this week in a talk to a women in tech group about contributing to open source.
