### ISSUE TITLE
Router blocks upstream if the port is not up at start time?

### ISSUE THREAD

**Issue by torenware** [drud/ddev#4045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

Using HEAD; 

[Gist for ddev debug test](https://gist.github.com/torenware/8cef0b992e2e78bde0304aa42360f8fc)

### Current Behavior

I'm attempting to make a port available through the router, using my ddev-viteserve add-on.  The generated HTTP_EXPOSE and HTTPS_EXPOSE from .ddev-docker-compose-full.yaml look correct to me:

```yaml
      HTTP_EXPOSE: 80:80,8025:8025,3000:3000
      HTTPS_EXPOSE: 443:80,8026:8025,3010:3000
```

Doing ddev ssh and checking for connectivity, my add-on is indeed serving on port 3000:

```sh
root@phpunit-course-web:/var/www/html# curl web:3000
<!DOCTYPE html>
<html lang="en">
  <head>
    <script type="module" src="/@vite/client"></script>

    <meta charset="UTF-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite App</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>
```

But I can't get anything from the host:

```sh
n$ ping phpunit-course.ddev.site
PING phpunit-course.ddev.site (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.075 ms
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.336 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.093 ms
ç64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.110 ms
64 bytes from 127.0.0.1: icmp_seq=4 ttl=64 time=0.139 ms
64 bytes from 127.0.0.1: icmp_seq=5 ttl=64 time=0.097 ms
^C
--- phpunit-course.ddev.site ping statistics ---
6 packets transmitted, 6 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.075/0.142/0.336/0.089 ms
(base) Robs-MBP:phpunit-course rtoren$ curl phpunit-course.ddev.site:3000
<!DOCTYPE html>
<html>
<head>
    <title>502: Unresponsive/broken ddev back-end site</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
    </style>
</head>
<body>
<h1>502: Unresponsive/broken ddev back-end site.</h1>
<p>This is the ddev-router container: The back-end webserver at the URL you specified is not responding. You may want to use "ddev restart" to restart the site.</p>
</body>
</html>
```

Turns out that [the router is responsible](https://gist.github.com/torenware/8cef0b992e2e78bde0304aa42360f8fc#file-router-config-txt). Output is from `ddev debug router-nginx-config > router-config.txt`. Relevant part is the upstream definition for ports 3000 and 3010:

Around line 74:
```nginx
        upstream phpunit-course.ddev.site-3000 {
        keepalive 100;
            # Container=ddev-phpunit-course-web (down)
        server 192.168.176.9 down;
        }

```

Both 3000/HTTP and 3010/HTTPS proxy to:

```
                proxy_pass http://phpunit-course.ddev.site-3000;
```

Not sure why DDEV is flagging that upstream.  It's not up at start time, and probably cannot be up at that time, since the add-on needs to be run manually most of the time. Putting this into the post-start hook doesn't work either; tried it. I don't think that `ddev vite-serve` will run any earlier than that in any case.

### Expected Behavior

I'd expect the router to have a valid upstream() definition, even if the port from an add-on.

### Steps To Reproduce

1. Install the add-on as `ddev get torenware/ddev-viteserve`
2. The process will create (or modify) `.ddev/.env`.  Edit the file to use non-standard ports:
```
# start vite
VITE_PROJECT_DIR=frontend
VITE_HTTP_PORT=3000
VITE_HTTPS_PORT=3010
# end vite
```
3. Install an arbitrary vite project at the top of your project as frontend.  This will work:
```
npm create vite@latest frontend -- --template vanilla
```
4. ddev restart
5. ddev vite-serve
6. Check port 3000 inside the web container, and verify that it serves HTML with a vite script tag.
7. Check port 3000 from the browser, and verify that it shows the "broken upstream" 502 page.

**Comment by torenware** [comment]
Wondering if the problem is services.web.expose.  I recently removed this from my docker-compose.viteserve.yaml file, and adding it back seems to fix the problem.  Still have HMR issues, but that's a separate problem

**Comment by torenware** [comment]
Solved HMR. Short version:  the DDEV nginx router already does everything required for this to work.  But due to oddities in how HMR bootstraps in Vite, it helps a lot if the internal port used by Vite is the same as the port used by HTTPS externally. Then no weird configuration is required from the Vite end.

**Comment by torenware** [comment]
"Hot Module Replacement": a Vite app in the browser gets instructions via a web socket to request chunks of data that have changed.  Think of HMR as a signalling channel.  By default, one and the same port handles both the downloading of assets, and the HMR signalling function.  In general, unless you look at what bytes are moving down "on the wire", you won't know whether you're looking at HMR.  That HMR channel doesn't even use a recognizable end point.  Same port. Same REQUEST_URI. So I don't use `nc -l`; if Vite is set up with default settings, it's already listening on that port, both for asset requests _and_ for HMR.

The simplest way to know is to use the browser network tools to see if a call to that port got back a status 101, which is how I check in the browser tools.  Or to use the JavaScript debugger to see if the client.ts script is trying to phone home and getting or not getting a web socket connection.

The router needs to be configured to watch for the specific headers sent during the HMR handshake.  Since the DDEV router watches for this correctly (your configuration is clearly websocket aware and passes those headers on to the proxy's upstream), you already do what you need to do.

The HMR settings in vite.config.js deal with cases where the router does NOT do what you need it to do.  I'm still figuring out how the server communicates to the Vite nub on the browser how to "call back".  The HMR client needs to infer where to ask for an HMR channel, and by default, it seems to want to use the same port as was originally used for Vite, the hostname of the current page, and the protocol (http, https) of the current page. If you want the HMR client to do anything different, you need settings on the server to tell the client what those are.

The Vite docs don't really help you understand what the HMR settings really do. I only figured any of this out by experimentation ([I wrote a couple of articles about doing this](https://medium.com/@robthorne-26852/doing-frontend-development-with-golang-javascript-and-docker-part-the-first-e801ab6df940) earlier this week) and by talking with a couple of the engineers on the Vite 3 team.

**Comment by rfay** [comment]
I was just saying that a way to test your original hypothesis about ddev-router not proxying if the port isn't active on the web container would be to set it up simpler and test it.  Thanks for the HMR explanation!
