### ISSUE TITLE
`ddev composer --version` fails because there is no command

### ISSUE THREAD

**Issue by davereid-pfg** [drud/ddev#4047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

I am unable to provide pastebins or gists as they are blocked by our corporate network.

### Current Behavior

```bash
ddev composer --version
Error: unknown flag: --version
Usage:
  ddev composer [command] [flags]
  ddev composer [command]

Examples:
ddev composer install
ddev composer require <package>
ddev composer outdated --minor-only
ddev composer create drupal/recommended-project

Available Commands:
  create         Executes 'composer create-project' within the web container with the arguments and flags provided
  create-project

Flags:
  -h, --help   help for composer

Global Flags:
  -j, --json-output   If true, user-oriented output will be in JSON format.

Use "ddev composer [command] --help" for more information about a command.
```

### Expected Behavior

The same thing that happens when I run `ddev exec composer --version`

```
ddev composer --version
Composer version 2.3.10 2022-07-13 15:48:23
```

**Comment by rfay** [comment]
Yeah, the `ddev composer` command doesn't have a `--version` flag, so that's what's going on. I thought maybe @gilbertsoft 's recent PR https://github.com/drud/ddev/pull/4033 would have fixed this though. 

But you can easily do:
```
ddev composer -- --version
ddev exec composer --version
ddev . composer --version
```

@gilbertsoft possibly we should do the same thing for composer cmd?

**Comment by rfay** [comment]
I hope that's working out for you. No response from OP so closing, happy to continue the conversation here or elsewhere.

**Comment by davereid-pfg** [comment]
This is still a bug on 1.20:

```
ddev composer --version
Error: unknown flag: --version
Usage:
  ddev composer [command] [flags]
  ddev composer [command]
```

**Comment by rfay** [comment]
It hasn't been addressed, because you have `ddev composer -- --version` and `ddev exec composer --version` and `ddev . composer --version` and because you sadly didn't even respond here. If there's some reason that you can't use the existing techniques, please speak up.

**Comment by davereid-pfg** [comment]
Ah, the alternatives work, it's just odd that this one doesn't, but I'm fine with it being as designed.

**Comment by davereid-pfg** [comment]
Mostly I was responding to the statement of "I thought maybe @gilbertsoft 's recent PR https://github.com/drud/ddev/pull/4033 would have fixed this though."

**Comment by davereid-pfg** [comment]
I keep getting tripped up by this with other things like `ddev drush generate --help` too. I wonder if we could work on making this work without needing a command argument for all these shortcut commands.

**Comment by rfay** [comment]
Want to try to fix it? You may be able to just do what https://github.com/drud/ddev/pull/4033 did, but in https://github.com/drud/ddev/blob/master/cmd/ddev/cmd/composer.go

You don't even have to have a dev environment to try, you can just use gitpod. https://ddev.readthedocs.io/en/latest/developers/building-contributing/
