### ISSUE TITLE
Add configuration flags for `ddev pull` - --ignore-db, ignore-files, etc.

### ISSUE THREAD

**Issue by beeradb** [drud/ddev#405]
## What happened (or feature request):
In #345 we introduced pantheon provider support. This was a big step forward, but there are ways we can improve it. 

## What you expected to happen:
We should introduce additional flags for `ddev pull` which allow more control over its behavior. The following flags should be added:

- --ignore-db (does not download a new database archive and uses most recent version)
- --ignore-files (does not download a new file archive and uses most recent version)
- --skip-import (performs the download of files and/or db but does not perform the import)
- --env=ENV (allows users to target a different environment than the one specified in config)

## Related source links or issues:
https://github.com/drud/ddev/pull/345#issuecomment-313776460

**Comment by rickmanelius** [comment]
This looks mostly actionable, but probably needs another set of eyes from a UX perspective before we commit to this approach. Also needs prioritization.

**Comment by eojthebrave** [comment]
This would be a nice addition. Specifically the option to choose to skip downloading either the files, or the db. I'm using ddev with the Pantheon provider, and being able to update the DB with a fresh copy but not worry about the files directory would be nice. Especially for sites with files directories that are multiple Gigabytes of data.

**Comment by rickmanelius** [comment]
@eojthebrave We completely agree that this will be a necessary feature in the future. We're in the process of finding additional team members to support this and other requests. I've updated the labels to note that this needs final definition and prioritization. Thanks!

**Comment by ultimike** [comment]
Agreed - a way to only pull the DB is pretty necessary in the short-term, IMHO. I have sites with multiple-GB-sized files directories that I don't want pulled to my local (that's what Stage File Proxy is for).

**Comment by rickmanelius** [comment]
We need to get this in by next release... it's valuable and I don't believe it's a heavy lift.

**Comment by rickmanelius** [comment]
We'll want to do this for both Pantheon as well as drud-s3. I think this is one of those low effort, high value items.

**Comment by rfay** [comment]
It's just one effort, not separate things.

**Comment by eojthebrave** [comment]
Just stopping by to say thanks. This `--skip-files` feature works great and easily replaces a handful of commands I was using to do this using a combination of terminus and ddev. And saves a lot of time/bandwidth for me. 🙏

**Comment by rfay** [comment]
Awesome, thanks! Always love to hear how you're using ddev and what your needs are.

**Comment by rfay** [comment]
And looking forward to a drupalize.me training on getting started with ddev and drupal, that would be awesome. We're happy to help with anything it would need. Would love to see what you'd do with that.
