### ISSUE TITLE
mkdocs docker broken in gitpod

### ISSUE THREAD

**Issue by tyler36** [drud/ddev#4053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

Recently I tried to review a PR using the gitpod button. However, it only displayes a welcome page instead of the docs.

### Current Behavior

After the 
![image](https://user-images.githubusercontent.com/7234392/181674284-0cce78b7-8608-4cf7-903b-ae4c02fec670.png)

This seems to show mkdocs running but not pointing to the correct location.

### Expected Behavior

Use the following docker command on my local form opens DDEV documention.

```shell
docker run -it -p 8000:8000 -v "${PWD}:/docs" -e "ADD_MODULES=mkdocs-material mkdocs-redirects mkdocs-minify-plugin mdx_truly_sane_lists mkdocs-git-revision-date-localized-plugin" -e "LIVE_RELOAD_SUPPORT=true" -e "FAST_MODE=true" -e "DOCS_DIRECTORY=./docs" polinux/mkdocs;
```

### Steps To Reproduce

1. Open "https://github.com/drud/ddev/pull/4046#issuecomment-1198809180"
2. Click the "Open in GItpid" button in the OP under Manual Testing section
3. Wait for command prompt
4. Run the follow command to start mkdoc server

```shell
docker run -it -p 8000:8000 -v "${PWD}:/docs" -e "ADD_MODULES=mkdocs-material mkdocs-redirects mkdocs-minify-plugin mdx_truly_sane_lists mkdocs-git-revision-date-localized-plugin" -e "LIVE_RELOAD_SUPPORT=true" -e "FAST_MODE=true" -e "DOCS_DIRECTORY=./docs" polinux/mkdocs;
```

5. Wait untill you see "Serving on http://0.0.0.0:8000/"
6. Open the preview

**Comment by rfay** [comment]
You ran docker in the d9simple directory, which is automatically created by the .gitpod.yml setup.

If you `cd /workspace/ddev` it works fine.

**Comment by rfay** [comment]
Note that `mkdocs serve` also works fine in /workspace/ddev

**Comment by tyler36** [comment]
Thank you.

I was confused that the main repo and PRs opened to a Drupal project. 

Closing because it works as designed.
