### ISSUE TITLE
[feat] Show progress for "Moving install to composer root" (ddev composer create)

### ISSUE THREAD

**Issue by mandrasch** [drud/ddev#4058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Commands like `ddev composer create --prefer-dist laravel/laravel` can take a minute while DDEV rsyncs the files to the project root directory ( [composer-create.go:124](https://github.com/drud/ddev/blob/de9bde40ede28b702d22f5ddd27e5769f27ba295/cmd/ddev/cmd/composer-create.go#L124)), at least on my mac m1 air.

It would be great to see the overall progress of the rsync operation, also to be sure it doesn't got stuck. 

### Describe the solution you'd like

I found out that there is an rsync argument called `--info=progress2`, which was introduced with [rsync 3.1.0](https://download.samba.org/pub/rsync/NEWS#3.1.0). 

>   There is also a --info=progress2 option that outputs
              statistics based on the whole transfer, rather than
              individual files.  Use this flag without outputting a
              filename (e.g. avoid -v or specify --info=name0) if you
              want to see how the transfer is doing without scrolling
              the screen with a lot of names. (You don't need to specify
              the --progress option in order to use --info=progress2.) 
_Source: [manpage rsync](https://man7.org/linux/man-pages/man1/rsync.1.html)_

I quickly checked the rsync version of DDEV on Gitpod: 
```sh
gitpod /workspace/d9simple (main) $ ddev exec rsync --version
rsync  version 3.2.3  protocol version 31
```

**Unfortunately I'm not sure if DDEV container always use rsync > 3.1.0? 
Is it safe to assume this?**

Tested it quickly in gitpod and changed `composer-create.go`, worked on Gitpod:

```go
	output.UserOut.Printf("Moving install to composer root")

		rsyncArgs := "-rltgopD --info=progress2" // Same as -a
		if runtime.GOOS == "windows" {
			rsyncArgs = "-rlD --info=progress2" // on windows can't do perms, owner, group, times
		}

		// output.UserOut.Printf("Running rsync with %s", rsyncArgs)

		stdout, stderr, err = app.Exec(&ddevapp.ExecOpts{
			Service: "web",
			Cmd:     fmt.Sprintf(`rsync %s "%s/" "%s/"`, rsyncArgs, containerInstallPath, app.GetComposerRoot(true, false)),
			Dir:     "/var/www/html",
			Tty:     isatty.IsTerminal(os.Stdin.Fd()),
		})
```

![image](https://user-images.githubusercontent.com/777278/181906575-f08d4f5a-9d8c-4dcb-9415-20e9c324159b.png)

### Describe alternatives you've considered

There is also the option to use a pipe with `pv`, but you need to calculate the number of files beforehand`${RSYNC} ${RSYNC_ARGS} ${SOURCES} ${TARGET} | pv -l -e -p -s "$HOW_MANY_FILES"`. ([Source](https://serverfault.com/a/357829), Demo-Gif see "Use pv command to monitor progress of rsync command" -> [here](https://www.cyberciti.biz/faq/show-progress-during-file-transfer/#Use%20pv%20command%20to%20monitor%20progress%20of%20rsync%20command))

Additionally there are maybe third party progressbar packages.

### Additional context

Infos about `ddev composer create` (wrapper for composer create) can be found in [DDEV docs](https://ddev.readthedocs.io/en/stable/users/basics/developer-tools/#ddev-and-composer)

Thanks very much for suggestion & tips!

**Comment by rfay** [comment]
The web container currently has rsync v3.2.3; that's standard on Debian Bullseye, it won't be changing (except upward as time goes on).

**Comment by rfay** [comment]
PR would be great.

**Comment by rfay** [comment]
BTW, I recommend using `ddev composer create --no-install` everywhere these days. It avoids this whole thing, and a `ddev composer install` afterward is so much more satisfying.

**Comment by rfay** [comment]
Would love to see your solution @mandrasch , otherwise let's close this. Thanks!

**Comment by mandrasch** [comment]
I'll submit a PR (if I find time to test it locally as well) :+1: 

Thanks for the great advice with `ddev composer create --no-install`! It seems to be much more 'readable' anyway, less 'magic' involved, might switch to that for my personal projects. :+1:
