### ISSUE TITLE
[docs] Continuing improvement with tabs management on nav and search

### ISSUE THREAD

**Issue by rfay** [drud/ddev#4059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

From 
* #4046 

#4046 made significant improvements on tab management, but there's more to go, thanks @mikesnoeren 

* One thing I noticed that unfortunately isn't fixed by this PR is the highlighting bug in the menu, which is supposed to be a indicator showing the user how far they have scrolled. This strange behaviour is caused by the heading placement being in tabs which messes with the javascript detecting if we've scrolled past it..
* It's quite massively better, and a great step forward IMO. There are still problems that I don't know you could sort out with this technique, but I'd love you to try. If you search for "Ubuntu" and choose WSL2, you'll get https://ddev--4046.org.readthedocs.build/en/4046/users/install/ddev-installation/#windows-wsl2 - but it doesn't have the right tab open.
* This watches for hash changes. Could it be update to also check for hashes on page load? Eg. http://localhost:8000/en/latest/users/quickstart/#drupal should take me to the tab too.

### Describe the solution you'd like

Continued improvement thanks!

**Comment by rfay** [comment]
@mikesnoeren here you go, thanks. This stuff is really important. You may even be able to implement this for mkdocs-material, which would be a huge fix there.

**Comment by rfay** [comment]
Hoping you can spend some time on this @mikesnoeren , we're definitely not out of the woods here, but it seems like you know the path...

If you just visit https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#linux in a new tab it doesn't make it to the right place (stays on macos/default tab). that would be a great thing to work on.

**Comment by mikesnoeren** [comment]
I just released a [PR](https://github.com/drud/ddev/pull/4069) that fixes the following:

> - It's quite massively better, and a great step forward IMO. There are still problems that I don't know you could sort out with this technique, but I'd love you to try. If you search for "Ubuntu" and choose WSL2, you'll get https://ddev--4046.org.readthedocs.build/en/4046/users/install/ddev-installation/#windows-wsl2 - but it doesn't have the right tab open.
> - This watches for hash changes. Could it be update to also check for hashes on page load? Eg. http://localhost:8000/en/latest/users/quickstart/#drupal should take me to the tab too.

**Comment by rfay** [comment]
We're not out of the woods yet, although we've made progress. For example, if you just open a new tab and paste in https://ddev.readthedocs.io/en/latest/users/quickstart/#drupal-9-composer-build, you don't land on the correct tab.

**Comment by mikesnoeren** [comment]
The tabs themselves don't seem to be working correctly on that page, there is somehow 6 tabs nested within eachother. https://ddev.readthedocs.io/en/latest/users/quickstart/#drupal

**Comment by mikesnoeren** [comment]
Made a [PR](https://github.com/drud/ddev/pull/4084) to fix that.

**Comment by rfay** [comment]
Thanks so much. BTW, I added headings inside the tabs (which shouldn't really be necessary) in order to deal with this early on. If you get everything working maybe we can remove the headings inside the tabs.

**Comment by rfay** [comment]
So could we get rid of this for example, https://github.com/drud/ddev/pull/4084/files#diff-cdacb5ab99042792ddb67ee7d62ac1d36c4699992949005880517b4955e10f7eR164 ?

**Comment by rfay** [comment]
I think @mikesnoeren 's work has fixed this up, so closing this, we can open new issues for new problems. Congratulations!
