### ISSUE TITLE
Add a `ddev push <provider>` command

### ISSUE THREAD

**Issue by beeradb** [drud/ddev#406]
## What happened (or feature request):
There are times when pushing files/databases from a local development environment to a hosting provider is useful. Specifically, during the early stages of site development, there is often a need to add modules/plugins, perform initial configuration, and then push the result into an environment on a configured provider.

## What you expected to happen:
We should introduce a `ddev push` command, which will archive the local files and database and push them to the hosting provider. For Pantheon, this can be done via terminus using the following commands:

```
 import
  import:complete           [site:import:complete] Finalizes the Pantheon import process.
  import:database           [import:db] Imports a database archive to the environment.
  import:files              Imports a database archive to the environment.
  import:site               [site:import] Imports a site archive (code, database, and files) to the site.
```

We'll also need to do research on other potential providers to determine if/how we can achieve this.

## Related source links or issues:
#345

**Comment by dsquaredb** [comment]
A 'ddev push' command to push the database and files back to Pantheon would be extremely helpful. It is a feature on Kalabox/Lando I use frequently when doing a new site build.

**Comment by dclear** [comment]
This should be revisited, updated, and generalized.

**Comment by rfay** [comment]
I don't remember this being related to any OKR. Certainly not a ddev OKR.

**Comment by dclear** [comment]
@cyberswat asked that this be prioritized. Let's slot during the next planning meeting.

**Comment by rfay** [comment]
Yes, it needs to be discussed before being added as an OKR. It's much, much bigger than "adding a command'. It requires first access to an API on a hosting platform, then implementation of the api for the specific platform, then implementation of push for that platform. Huge scope. Cannot fit in this quarter under any circumstances I know of unless we remove most everything else, not sure if it would even then.

**Comment by cyberswat** [comment]
Oh for sure.  That's a ton of complexity.  It's likely to be a bit smaller in scope than a full blown api backed implementation and should continue to focus around the s3 integration similar to how the pull functionallity is working.  We'd probably want to pull @cweagans in at some point to help us understand if anything would be possible on the hosting api perspective.

**Comment by cyberswat** [comment]
FWIW It's related to Company OKR #3.  We'll get a meeting set up to discuss.

**Comment by sgrandchamp** [comment]
@rfay @cyberswat @dclear Agree that we do not want or encourage anyone to "slip" anything into OKR's.  It's certainly possible that we miss a few things when we are aligning company OKR's to Team OKR's, that's the whole point of the iterative process.  In the last board meeting we reviewed the Company OKR's and #3 is clearly a priority for the company.  I suggest we get chat about ensuring we find the right way to connect the team and the company OKR on this one.  It's totally ok to miss one of these and catch it and adjust.   Perhaps my own rationalization but I think this is normal and isn't "slipping" one in.

**Comment by dclear** [comment]
thx, I moved it to the correct Company OKR.

**Comment by rfay** [comment]
Can somebody please link to OKR 3?

**Comment by sgrandchamp** [comment]
@rfay yes sir, hence the word "defined" :-) . I'm sure we can figure out a good path to start.  much appreciated !

**Comment by rfay** [comment]
Depends on what the meaning of "is" is, of course.

**Comment by andrewfrench** [comment]
After a call this morning, I think we have a very actionable set of requirements for this command that maintain the spirit of ddev and are limited in scope and will greatly reduce the time to deploy an existing site (coming with a real-world database and file archive) to DDEV-Live.  Ultimately, we'll be adding a way for a user to *push* file and database archives to a hosting service in a generalized way:

- A file and/or database archive exists in the local development environment
- A user executes ddev push to upload the archives to the remote hosting environment
- ddev uploads the archives to a remote location (initially, an AWS S3 bucket)
- When complete, ddev sends a request to an HTTP endpoint with the location of the uploaded artifacts
- The response to the request allows the hosting service to indicate success/failure of the push request

To keep this generalized, we should openly define the expected HTTP response. I'm imagining a simple `application/json` response that looks something like this:

```
{
  "success": false,
  "message": "A database already exists for this site"
}
```

**Comment by cweagans** [comment]
> The response to the request allows the hosting service to indicate success/failure of the push request

As a heads up, one of the problems that we discussed related to the ddev-live API is that the time difference between kicking off a restore job and when the job actually completes can sometimes be pretty significant. One of the ways that we planned to mitigate this was to expose one endpoint for kicking off the job, and another that can be used for polling for the status.

There was some pretty serious disagreement about the idea of just keeping the request open until the job completes. We've seen it take 60+ minutes for very large databases.

I'd also like to bring up authentication here. If the endpoint that you're going to be hitting is part of the ddev-live API, you'll need the user's credentials to be able to do anything. Once a token has been issued, if you requested a far-future expiration, it'll be valid for a year. Happy to work with you on specifics if you want.

I wasn't following the ddev local stuff very closely today, but I'm happy to join calls related to ddev-live interaction if having additional information about the API would help.

**Comment by andrewfrench** [comment]
Authentication was on my mind when I was typing that but I wasn't sure if I wanted to open that can of worms just yet. I was imagining a token would be sent with the request, but we'll need direction on how to structure that.

At a surface level, I don't like the idea of keeping a connection open for an hour to wait for a response from an API endpoint. I also don't think that response _necessarily_ needs to wait until everything is done and has either succeeded or failed some time later, we could get a lot of value from an immediate response that just tells the user easy things like "request received, here's how to check for the status", "auth failed", "you already have a database, not going to delete it", etc.

**Comment by andrewfrench** [comment]
Gotcha, and the content of those responses (as well as what is and isn't allowed) would come from the logic of the hosting platform and be almost entirely out of ddev's hands, so that database note is fine with me.

It also dawned on me that uploading a real site's archives may already take a very serious amount of time &mdash; the common real-world use case for this may already take minutes and minutes to complete. With that in mind, maybe waiting a while for a response from the API is more reasonable? Either way, ddev's just the messenger. We'll just need to know how big the timeouts need to be.

**Comment by dclear** [comment]
we'll resume work on this after the functionality in working in the ddev-live cli
