### ISSUE TITLE
Add a host command to print and obfuscate environment variables

### ISSUE THREAD

**Issue by deviantintegral** [drud/ddev#4063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

One of my coworkers wrote something to the effect of "I wish I could easily print and obfuscate environment variables with something like `ddev cat-env-with-value-obscured`".

While it's easy enough to run `ddev exec printenv`, obfuscating variables is trickier for sure.

### Describe the solution you'd like

Add a `printenv` command implementing something like the following I prototyped in `.ddev/commands/host`:

```
#!/bin/bash

## #ddev-generated
## Description: Print environment variables, optionally obfuscating them to their last four characters.
## Usage: printenv [-o|--obfuscate] [-s|--service] [variable name...]
## Example: "ddev printenv" or "ddev printenv DDEV_DOCROOT" or "ddev printenv -s web -o BLACKFIRE_SERVER_TOKEN"

while :; do
     case ${1:-} in
         -h|-\?|--help)
             show_help
             exit
             ;;
         -o|--obfuscate)
            OBFUSCATE=1
             ;;
         -s|--service)
           shift
           SERVICE=${1:-}
           ;;
         -j|--json-output)
             echo "JSON output is not supported."
             exit 1
             ;;

         --)              # End of all options.
             shift
             break
             ;;
         -?*)
             printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
             ;;
         *)               # Default case: No more options, so break out of the loop.
             break
     esac

     shift
 done

if [[ -n $SERVICE ]]
then
  VARIABLES=$(ddev exec --service $SERVICE printenv "$*")
else
  VARIABLES=$(ddev exec printenv "$*")
fi

if [[ $OBFUSCATE == 1 ]]
then
  for variable in $VARIABLES
  do
    if [[ -n $* ]]
    then
      value=$(echo "$variable" | rev | cut -c -4 | rev)
      echo "$value"
    else
      name=$(echo "$variable" | cut -d= -f1)
      value=$(echo "$variable" | cut -d= -f2- | rev | cut -c -4 | rev)
      echo "$name"="$value"
    fi
  done
else
  for variable in $VARIABLES
  do
    echo "$variable"
  done
fi
```

### Describe alternatives you've considered

I haven't filed a PR yet because I wonder if this is better done in go. Obfuscation is noticeably slower due to all of the process forking. As well, the default help is a little confusing:

```console
Print environment variables, optionally obfuscating them to their last four characters. (shell host container command)

Usage:
  ddev printenv [-o|--obfuscate] [-s|--service] [variable name...] [flags]

Examples:
  "ddev printenv" or "ddev printenv DDEV_DOCROOT" or "ddev printenv -s web -o BLACKFIRE_SERVER_TOKEN"

Flags:
  -h, --help   help for printenv

Global Flags:
  -j, --json-output   If true, user-oriented output will be in JSON format.
```

1. `[flags]` are not actually supported, but ddev prints it anyways.
2. json output is forced into the command, even though it doesn't make a ton of sense in this case. I suppose we could do something like `{"output": "<...>"}` but that feels ugly.

**Comment by rfay** [comment]
Since this is not commonly done, and is something to be explored and see if it works out, it would be best to do it as a ddev-get add-on for now I'd think. Easy for everybody to use (and see if they use it). Maybe it could have a regular command that did a `printenv | grep DDEV` and another one that did the obfuscate. I would expect that since it doesn't happen a lot it the performance isn't that relevant?

**Comment by deviantintegral** [comment]
Done! I agree, performance is not really a consideration especially if it's an addon.

https://github.com/Lullabot/ddev-printenv

**Comment by rfay** [comment]
Awesome, thanks!
