### ISSUE TITLE
v1.20.0 Test Plan - Community help requested

### ISSUE THREAD

**Issue by rfay** [drud/ddev#4066]
It's testing time again here in the DDEVfactory. We love community help with every item that is interesting or relevant to you, and just *using* the release candidates is hugely helpful, because you may stumble across something in your regular workflow. Please use DDEV HEAD or later for your testing (or `brew unlink ddev && brew install --HEAD --fetch-head drud/ddev/ddev`).

I don't think in general you'll have trouble using this in your daily workflow, so would love you do do that. You can switch back and forth , see [How can I install a specific version of DDEV in the FAQ](https://ddev.readthedocs.io/en/latest/users/basics/faq/).

If you find a bug that you're pretty sure is a bug, then [just open an issue for it](https://github.com/drud/ddev/issues/new?assignees=&labels=&template=Bug_report.md&title=).

To give feedback or ask questions, please just reply on this issue or discuss in [discord](https://discord.gg/hCZFfAMc5k) or any other support channel.

I am maintaining the [provisional release notes for v1.20.0](https://www.notion.so/randyfay/v1-20-0-Provisional-Release-Notes-5f396dc023764e5c81fea1d797ea8182) and would love any comments on those.

1. **install_ddev.sh** should work with new pipe-based [install.sh](http://install.sh/). It should brew unlink where necessary.
2. `web_extra_exposed_ports`: Try it out with example from docs.
3. `web_extra_daemons`: try it out, especially with a daemon that exposes an extra port. Best and most difficult tests involve running something that is in code (in project) and with mutagen enabled.
4. `php`and `mariadb` default versions: Create a new project, `php` project is probably best. Defaults should be in it already. 
5. `config.*.yaml` merging: Create a few `config.*.yaml` that have extra elements like hooks, environment variables, web_extra_daemons, web_extra_exposed_ports. Should be merged.
6. `ddev craft` command - try out on craft project
7. `ddev npm` relative directory. Try out `ddev npm install` in a subdirectory of project. It should run in the same relative directory inside the container.
8. `ddev yarn` relative directory. Try out `ddev yarn install` in a subdirectory of project. It should run in the same relative directory inside the container.
9. config.yaml `composer_version` support: Try out all the options in [docs](https://ddev.readthedocs.io/en/latest/users/configuration/config_yaml/)
10. Platformsh provider support: Manually test the platform.sh support, pull and push.

**Comment by tyler36** [comment]
4. ✅ `ddev php -v` on a php project-type show `8.0.21`.  Host system running `7.2`
   - added Laravel project-type and was able to migrate database
   -  php project-type install MariaDB `10.4.25-MariaDB` with collation as `utf8mb4_general_ci`
7. ✅  `ddev npm`: confirmed. 
  - `ddev npm install` installed packages listed in `package.json` in a new project & it created `package.lock`. 
8. ✅  `ddev yarn`: confirmed. 
  - `ddev yarn` installed packages listed in `package.json` in a new project & it created `yarn.lock`.

**Comment by rfay** [comment]
1. ✅ install_ddev.sh
    * `curl -fsSL https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh | bash` works to get v1.19.5 (and did brew unlink for me)
    * `curl -fsSL https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh | bash -s v1.19.2` works to get v1.19.2
    * `curl -fsSL https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh | bash -s v1.18.0` works to get v1.18.0
2. ✅

**Comment by rfay** [comment]
Everything I tested was good. Hope it all works out!

**Comment by rfay** [comment]
Thanks for your testing @tyler36 !
