### ISSUE TITLE
Provide a warning if settings.local.php is not included

### ISSUE THREAD

**Issue by beeradb** [drud/ddev#407]
## What happened (or feature request):
As indicated in https://github.com/drud/ddev/pull/345#issuecomment-314527971 the inclusion of settings.local.php in Drupal 7, although common, is not in place by default. With the changes to settings file writing that took place in #345 it is possible for Drupal7 to write a settings.local.php which is not properly included. 

This can happen in the case of a Drupal 7 site being deployed with a settings.php file committed to git which does not have the settings.local.php include. It's also possible for it to happen on Drupal8 or WordPress if the default configurations are modified to not include settings.local.php or wp-config-local.php, respectively. 

## What you expected to happen:
If a settings.php file exists and is not maintained by ddev, we should do a simple check for the proper includes and present a warning to the user if they aren't present. It's unlikely that this can cover all situations, as there are countless ways to include a file in PHP, but we should be able to detect the majority of cases where the file is not being included properly and provide an appropriate warning to the user.

## Related source links or issues:
#345

**Comment by rickmanelius** [comment]
This looks completely actionable but just needs prioritization.

**Comment by beeradb** [comment]
Bump. I helped with a support request on this today. It feels relatively low effort and would be a beneficial fix I think.

Here's the console output for a db-import on a D7 site with a settings.php committed:

```
MacBook-Pro-7:physforpeace ddbow$ ddev import-db
Provide the path to the database you wish to import.
Import path: 
~/Downloads/physforpeace_dev_2017-08-14T16-01-23_UTC_database.sql.gz
You provided an archive. Do you want to extract from a specific path in your archive? You may leave this blank if you wish to use the full archive contents
Archive extraction path:
Generating settings.local.php file for database connection.
Successfully imported database for```

At the very least, having a warning message in place for D7 would be a huge win. D7 does not include settings.local.php by default, so our console output should probably not assume the file is included.

**Comment by rickmanelius** [comment]
I'd love to see @nmccrory take this on with @beeradb assisting with any question on implementation strategy, etc.

**Comment by rickmanelius** [comment]
This may appear simple, but it could also turn out to be quite involved. I'd like @rfay to take a look at this and ensure this is properly scoped before we bring this back to actionable. It could be a simple check and warning (quick and easy win) or it could be a bit more involved. I would prefer to warn the user and provide instructions versus attempt to fix and take on that responsibility for now.

**Comment by rfay** [comment]
I think we should close this one in favor of [Always create settings.ddev.php (and force it to be included)](https://github.com/drud/ddev/issues/468), since we've decided to go a completely different way with it.
