### ISSUE TITLE
Add PHPUnit command with path remapping

### ISSUE THREAD

**Issue by tyler36** [drud/ddev#4077]
I would like a command on the host that will run PHPUnit in the DDEV web container.

It should
- [ ] display output with color codes
- [ ] remap ddev container paths to project paths

**Comment by rfay** [comment]
One thing you should consider is using vscode's remote containers feature, it might work. https://code.visualstudio.com/docs/remote/containers

**Comment by rfay** [comment]
Also, as you're a resident expert on ddev-get add-ons, this would be better incubated as an add-on, rather than adding it to ddev, since it's vscode-specific and solves such an exact problem.

**Comment by rfay** [comment]
I'm all in favor of this, but it's best to work it outside the ddev repo; when it matures it can become an add-on, and of course if we can figure out how to do it for all CMSs we could include it in DDEV. Thanks for all your contributions! Closing this for now.
