### ISSUE TITLE
Documentation URL is wrong in error messages

### ISSUE THREAD

**Issue by njt1982** [drud/ddev#4081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://github.com/drud/ddev/blob/81ec233273208fcad39c37759abdc36ceadf8bc1/.ci-scripts/bump_homebrew.sh#L80

I'm not sure where else (if at all) this URL is used at the moment... 

I spotted it in this message (slightly out of date ddev):
```
Could not connect to a docker provider. Please start or install a docker provider.
For installation help go to: https://ddev.readthedocs.io/en/latest/users/docker_installation/
```

For me, that URL resolves to a 404.

### Current Behavior

https://ddev.readthedocs.io/en/latest/users/docker_installation/ is a 404

### Expected Behavior

https://ddev.readthedocs.io/en/latest/users/docker_installation/ shouldn't be a 404 😉

I suspect it should be https://ddev.readthedocs.io/en/latest/users/install/docker-installation/ ?

### Steps To Reproduce

I triggered it by doing `ddev help` without docker being started.

**Comment by rfay** [comment]
If you're using a slightly out of date ddev, could you please update ddev and see if it's a problem?

**Comment by rfay** [comment]
I tried to add a redirect for this in readthedocs, we'll see how it works out.

**Comment by rfay** [comment]
Looks like this works now, thanks for reporting it!

https://ddev.readthedocs.io/en/latest/users/docker_installation/ gets to the right page.

**Comment by njt1982** [comment]
I updated it and now help shows:
```
% ddev help
Could not connect to a docker provider. Please start or install a docker provider.
For install help go to: https://ddev.readthedocs.io/en/latest/users/install/
```

So looks like the URL was because I was a version or two behind.

Redirect works fine 👍🏻

**Comment by rfay** [comment]
Thanks. I did a huge rewrite of the docs without paying any attention to URL stability. It was a mistake, but the rewrite was good. Oh well. I've been adding a couple of redirects as time went along.
