### ISSUE TITLE
drush locale:import only runs when in 'web' foler

### ISSUE THREAD

**Issue by ReactMarc** [drud/ddev#4096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

[https://gist.github.com/ReactMarc/cbddf658a214d0d07e058481b388bdcd](https://gist.github.com/ReactMarc/cbddf658a214d0d07e058481b388bdcd)

### Current Behavior

When trying to import custom Drupal .po translation files, Drush throws the error: `path/to/my/file/custom.po not found or empty`. When I `cd` to the 'web' directory in my project, change the relative path to the .po file and run the locale:import command again, it starts importing the file.

### Expected Behavior

Since I can run almost any drush command using `ddev exec drush` just about anywhere (which is awesome), you would except that als to be true for the `drush exec drush locale:import` command. Assuming you've filled in the correct relative or absolute path to your folder with .po files

### Steps To Reproduce

1. In ddev v1.20.0 running on arm64 architecture in a Colima docker container, running the Drupal 9 config on nginx-fpm with PHP 7.4 and MySQL 5.7, Mutagen enabled.
2. Using Drupal 9.3.5 and Drush 11.1.1
3. Run the command `ddev exec drush locale:import de /Users/acme/Sites/acme_corporate/custom_translations/custom-translations.de.po --type=customized --override=all`

**Comment by rfay** [comment]
You're trying to do two different things... Drush inside the container can't in any way find your file "/Users/acme/Sites/acme_corporate/custom_translations/custom-translations.de.po". You should be referencing /var/www/html/custom_translations/custom-translations.de.po I think.

**Comment by ReactMarc** [comment]
Oh, sorry. I wasn't clear on that. I didn't ssh into the container. I opened iTerm, cd'd to project folder and ran `ddev exec drush` from there.

**Comment by rfay** [comment]
When you do `ddev exec drush` you're execing into the contianer, where /Users is not accessible.

**Comment by ReactMarc** [comment]
Oh! I see. I didn't get that part. That explains a lot. Could I have read this in the documentation? And if not, is there a way to document this?

**Comment by rfay** [comment]
It's a basic concept, that `ddev exec` does things inside a container in a completely different space. So does `ddev ssh` and everything else that ddev does. In general, nothing happens on the host, and nearly nothing can know about /Users in your case.

I'm sure this is a stumbling block for more than just you, but... on the other hand now that you know it, it won't be. 

It's possible that [this doc about basics](https://ddev.readthedocs.io/en/latest/users/basics/how-ddev-works) will help you, I'd love to have your feedback about it...

**Comment by ReactMarc** [comment]
Thank you. That page is helpful. I found it also in the first sentence of the [https://ddev.readthedocs.io/en/latest/users/basics/cli-usage/#executing-commands-in-containers]'Executing commands in containers' page. Thank you for your quick replies. Obviously I will close this issue.

**Comment by rfay** [comment]
Thanks for the feedback, and glad you've got it going!

**Comment by rfay** [comment]
You'll like `ddev drush` too, even though it only saves you 6 characters of typing :)
