### ISSUE TITLE
TYPO3: include ddev settings in extra file – and do not override AdditionalConfiguration.php

### ISSUE THREAD

**Issue by rr-it** [drud/ddev#4098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

In TYPO3 I'd like to configure additional settings via "AdditionalConfiguration.php". This file – configured via  `app.SiteDdevSettingsFile` – is already generated and managed by ddev.

### Describe the solution you'd like

Configure a new path or file-name for `SiteDdevSettings` and then re-include this file in my own settings-file.

E.g. for TYPO3:

`config.yaml`:
~~~yaml
site_ddev_settings_file: AdditionalConfigurationDdev.php
~~~

Own manually created `AdditionalConfiguration.php`:
~~~php
<?php
// include ddev managed configuration
require(__DIR__ . '/AdditionalConfigurationDdev.php');

// add own configuration
if (class_exists(\Undkonsorten\TYPO3AutoLogin\Utility\RegisterServiceUtility::class)
    && class_exists(\TYPO3\CMS\Core\Core\Environment::class)
    && \TYPO3\CMS\Core\Core\Environment::getContext()->isDevelopment()) {
    \Undkonsorten\TYPO3AutoLogin\Utility\RegisterServiceUtility::registerAutomaticAuthenticationService();
}

$GLOBALS["TYPO3_CONF_VARS"]["SYS"]["sqlDebug"] = 1;
~~~

### Describe alternatives you've considered

Right now, I already have an option to completely override the generated "SiteDdevSettingsFile", but this stops ddev from automatically managing the settings and "it is recommended that you leave this file alone".

~~~php
/**
 * #ddev-generated: Automatically generated TYPO3 AdditionalConfiguration.php file.
 * ddev manages this file and may delete or overwrite the file unless this comment is removed.
 * It is recommended that you leave this file alone.
 */
~~~

### Additional context

Maybe it's sufficient to add new YAML options in `ddevapp.go` – see below – and then `app.SiteSettingsPath` and `app.SiteDdevSettingsFile` become configurable via `config.yaml`.

https://github.com/drud/ddev/blob/16c3aa2a5f1aa198964bd5ce053a5c5773181efb/pkg/ddevapp/ddevapp.go#L110-L111

**Comment by rr-it** [comment]
I absolutely would like to keep settings management running. And then add additional configuration options on top.

In other use cases where `disable_settings_management: true` works, it is also possible to just remove the "special comment" in the generated `SiteDdevSettingsFile` file and then make changes to the file itself.

**Comment by rr-it** [comment]
## How are the ddev settings included in different CMS

### Drupal

In the default `settings.php` a special file `settings.ddev.php` gets included:
https://github.com/drud/ddev/blob/52566fe86b6b14f282188da12976efe80f352186/pkg/ddevapp/drupal/drupal10/settings.php#L759-L762

All ddev related settings are in the non-Drupal file `settings.ddev.php`.

### Wordpress

In the default `wp-config.php` a special file `wp-config-ddev.php` gets included:
https://github.com/drud/ddev/blob/52566fe86b6b14f282188da12976efe80f352186/pkg/ddevapp/wordpress/wp-config.php#L29-L33

All ddev related settings are in the non-Wordpress file `wp-config-ddev.php`.

### TYPO3

Right now, all ddev related settings are implemented via the default TYPO3 mechanism `AdditionalConfiguration.php` where ddev directly saves its settings.

Maybe a better implementation for TYPO3 is to also default to a 2-file-solution like other CMS are already using.

In default `AdditionalConfiguration.php` include a special file `AdditionalConfigurationDdev.php`:
~~~php
<?php

 // Automatically generated include for settings managed by ddev. 
 if (file_exists(__DIR__ . '/AdditionalConfigurationDdev.php') && getenv('IS_DDEV_PROJECT') == 'true') { 
   include __DIR__ . '/AdditionalConfigurationDdev.php'; 
 } 
~~~

Then put all ddev related settings in the non-TYPO3 file `AdditionalConfigurationDdev.php`.

Now, on this topic there is a need for feedback from the TYPO3 community.

**Comment by rfay** [comment]
I hope you read https://ddev.readthedocs.io/en/latest/users/topics/cms_specific_help/ and undestand that you can also remove the `#ddev-generated` from AdditionalConfiguration.php and do whatever you want with it.

**Comment by rr-it** [comment]
I know about the `#ddev-generated` comment. But I think in general for most TYPO3 projects there are changes neccessary to the TYPO3-system-file `AdditionalConfiguration.php`.

So I'm looking for a solution which does not unnecessarily removes the  "ddev settings management" for most TYPO3 projects.

**Comment by spoonerWeb** [comment]
What changes are necessary in AdditionalConfiguration that could not be in LocalConfiguration?

**Comment by spoonerWeb** [comment]
For my projects, AdditionalConfig includes only stuff that needs to be adjusted due to the environment (local dev, staging or production server). All other stuff is in the LocalConfig.

LocalConfig = all stuff that is same on every environment / stage
AdditionalConfig = adjustments for an environment / stage

**Comment by rr-it** [comment]
> What changes are necessary in AdditionalConfiguration that could not be in LocalConfiguration?

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Configuration/Typo3ConfVars/Index.html#typo3confvars-additionalconfiguration

> Although you can manually edit the **typo3conf/LocalConfiguration.php file, it is limited in scope because the file is expected to return a PHP array**. Also the file is rewritten every time an option is changed in the Install Tool or some other operation (like changing an extension configuration in the Extension Manager). **Thus custom code cannot reside in that file.**
> 
> **Such code should be placed in the typo3conf/AdditionalConfiguration.php file.** This file is never touched by TYPO3, so any code will be left alone.

E.g. the following code cannot live in `LocalConfiguration` and must live in `AdditionalConfiguration`:
~~~php
if (class_exists(\Undkonsorten\TYPO3AutoLogin\Utility\RegisterServiceUtility::class)
    && class_exists(\TYPO3\CMS\Core\Core\Environment::class)
    && \TYPO3\CMS\Core\Core\Environment::getContext()->isDevelopment()) {
    \Undkonsorten\TYPO3AutoLogin\Utility\RegisterServiceUtility::registerAutomaticAuthenticationService();
}
~~~

**Comment by rfay** [comment]
The reason that DDEV does TYPO3 the way it does... is because that's what the TYPO3 community asked for. 

Happy to continue the conversation, but if everybody has been doing OK with these things for years...

**Comment by spoonerWeb** [comment]
@rr-it Your code has conditions for the development context, so it's okay to have it in AdditionalConfig. Just place it below the ddev stuff and remove the comment so ddev doesn't overwrite it. :)

**Comment by rr-it** [comment]
Using ddev I'm in development context (allmost) all the time. That's why I always have to add special settings to AdditionalConfig. And right now I must remove the comment `#ddev-generated` so ddev doesn't overwrite it.

Here I'm looking for a general solution, that does  keep the "ddev settings management" running (e.g. not involve removing the comment `#ddev-generated` or setting `disable_settings_management: true`).
Thereby ddev is able to modify or update its TYPO3 settings as this might become neccessary with future ddev updates (e.g. involving new ImageMagick versions, db-settings etc.).

**Comment by rfay** [comment]
As far as I can tell, the TYPO3 community has been fine with how this works for years, and there are very straightforward ways of managing this without changes to DDEV. I'm going to close this for now, but happy to continue the conversation here or elsewhere.
