### ISSUE TITLE
Exclude user specific docker-compose.user.*.y*ml files in the default .gitignore

### ISSUE THREAD

**Issue by poebel** [drud/ddev#4107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Some of our developers need custom docker configurations, i.e. to include their SSH agent socket instead of using the default DDEV ssh auth container:

    # <project>/.ddev/docker-compose.user.ssh-agent.yaml
    version: '3.6'
    
    services:
      web:
        volumes:
          - '${SSH_AUTH_SOCK}:/home/.ssh-agent/socket'

As we want to minimize the files in our projects which differ from the default files generated by DDEV it would be nice to have `docker-compose.user.*.y*ml` files already ignored in the default `.gitignore` file generated by DDEV.

This might as well benefit other use cases were a developer / machine specific docker adjustment is needed.

### Describe the solution you'd like

Add `/docker-compose.user.*.y*ml` to the default `.gitignore` file.

A possible drawback/incompatibility might occur with existing setups where such files are already present and tracked by git.

### Describe alternatives you've considered

We're currently manually adjusting the `.gitignore` to our needs and not have it handled by DDEV.

**Comment by rfay** [comment]
Hmm, the normal expectation is that people *will* check in `docker-compose.*.yaml` because they're part of the configuration of the project. That's what people have done for years. Why would you not want to check them in? I guess because you're mounting the docker sock in this particular case, which is a good one, but I don't think it's appropriate for most of these. 

In this case, why don't you just add `.ddev/docker-compose.user.ssh-agent.yaml` to your project .gitignore?

**Comment by poebel** [comment]
> In this case, why don't you just add `.ddev/docker-compose.user.ssh-agent.yaml` to your project .gitignore?

That's actually a good idea wich didn't cross our mind so far 😅 

Thanks for the fast reply and suggestion!

**Comment by rfay** [comment]
This reminds me of
* https://github.com/drud/ddev/issues/1904
The only place that won't work now I think is traditional Windows, not sure about Colima. DDEV should probably start mounting it in by default in a future release. 

I'm going to close this for now, as your original suggestion would be pretty disruptive.
