### ISSUE TITLE
Windows with mutagen: files that should be executable (like drush) aren't executable in traditional Windows

### ISSUE THREAD

**Issue by tbeaudin** [drud/ddev#4108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I just downloaded ddev local on my windows 10 computer and enabled Mutagen. So far everything has worked fine until I tried to use Drush in the command line. I installed drush using the command: `ddev composer require drush/drush` as part of the Drupal setup. However, whenever I try and use a drush command I get the following message:
` /mnt/ddev_config/.global_commands/web/drush: line 14: /var/www/html/vendor/bin/drush: Permission denied`
`Failed to run drush --version: exit status 126`
While there are some fixed available online, all of them seem to be tailored towards Mac OS or a Linux Distro.

### Expected Behavior

I expected Drush commands to execute normally having installed Drush using the quick setup guide for Drupal in the ddev documentation.

### Steps To Reproduce

1. Setup ddev in a local windows environment
2. Follow the quickstart guide for Drupal on ddev's documentation page:
```
mkdir my-drupal9-site
cd my-drupal9-site
ddev config --project-type=drupal9 --docroot=web --create-docroot
ddev start
ddev composer create "drupal/recommended-project" --no-install
ddev composer require drush/drush --no-install
ddev composer install
ddev drush site:install -y
ddev drush uli
ddev launch
```
3. Enable Mutagen in the environment with the command `ddev config global --mutagen-enabled`
4. Try and run a Drush command. For example: `ddev exec drush`
5. A permission denied error should appear.

### Anything else?

A temporary solution to the issue was given on the discord for the problem by @rfay. By running `ddev exec chmod +x /var/www/html/vendor/bin/*` in the command line so that permissions are granted and the issue is solved until the environment is restarted. Furthermore, by creating a post-start exec hook the problem can basically be solved permanently by automatically running this command every time the environment is set up.

**Comment by rfay** [comment]
Thanks for creating the issue. It shouldn't be a hard fix once I understand the correct mutagen.yml settings.
