### ISSUE TITLE
`Unable to locate package certutil` error after running ` sudo apt-get update && sudo apt-get install -y certutil xdg-utils`  - step 14  of ddev wsl2 install

### ISSUE THREAD

**Issue by therobyouknow** [drud/ddev#4112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/therobyouknow/407fe334d59a66d3d3a040edf6d13697

### Current Behavior

`Unable to locate package certutil` error after running ` sudo apt-get update && sudo apt-get install -y certutil xdg-utils`  - step 14 of  https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/ for Windows WSL 2.

### Expected Behavior

No error.

### Steps To Reproduce

Windows 11 WSL2 Ubuntu 20.04, follow steps for Windows WSL2 up to and including step 14 https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/

**Comment by rfay** [comment]
Could you please say what Linux distro you were installing?

**Comment by rfay** [comment]
Ah, it should be libnss3-tools, see https://github.com/FiloSottile/mkcert#linux

Could you please do a PR to fix it? You can just click the pencil on the page.

**Comment by therobyouknow** [comment]
> Could you please say what Linux distro you were installing?

Ubuntu 20.04.  You're so good @rfay !  Thank you for responding so soon, always appreciate your help whenever you can.

> Ah, it should be libnss3-tools, see https://github.com/FiloSottile/mkcert#linux
> 
> Could you please do a PR to fix it? You can just click the pencil on the page.

Thank you! Sure, I think I will be able to do that.  I'll aim for tomorrow morning UK time. I'm probably going to pause for now at 2324.  I'm super grateful for your response @rfay
