### ISSUE TITLE
Why are WSL2 and Linux tab ddev install steps different when they both say to install inside distro?

### ISSUE THREAD

**Issue by therobyouknow** [drud/ddev#4113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

> I have searched the existing issues

- https://github.com/drud/ddev/issues?q=ddev+install+documentation
- https://github.com/drud/ddev/issues?q=ddev.readthedocs.io%2Fen%2Fstable%2Fusers%2Finstall%2Fddev-installation%2F

couldn't see similar issue, so raising this issue.

On "Windows WSL2" tab of https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/  to install ddev it says

> The Windows ddev works fine with the WSL2-based Docker engine. However, the WSL2 ddev setup is vastly preferable and at least 10 times as fast. 

So these are the steps for installing ddev _inside_ the distro running on WSL2:

> 12 Open the WSL2 terminal, for example Ubuntu from the Windows start menu.

> 13 Install ddev with curl -fsSL https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh | bash

There are also steps for installing ddev in Linux - in the Linux tab of the same page https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/

> Debian/Ubuntu and derivative distros - Install the ddev apt repositories with:
> 
> `curl https://apt.fury.io/drud/gpg.key | sudo apt-key add -`
> `echo "deb https://apt.fury.io/drud/ * *" | sudo tee -a /etc/apt/sources.list.d/ddev.list`
> `sudo apt update && sudo apt install -y ddev`

This step, like the step 14 for WSL2, is inside the distro, e.g. running these commands from a shell in Ubuntu.

Why are the steps different?  should we not have a single guide for Linux whether it be a standalone ordinary installation or one running on WSL2?

### Expected Behavior

Why are the steps different?  should we not have a single guide for Linux whether it be a standalone ordinary installation or one running on WSL2?

### Steps To Reproduce

Conpare ddev install steps for Linux with install steps for WSL2 https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/

<img width="935" alt="image" src="https://user-images.githubusercontent.com/1080646/184249855-8c9016bd-936c-4c07-9aa2-4a4d7368dae5.png">

<img width="949" alt="image" src="https://user-images.githubusercontent.com/1080646/184249992-c1363c23-0c53-4ca6-89c4-dfa71051cc0b.png">

<img width="954" alt="image" src="https://user-images.githubusercontent.com/1080646/184249923-8c22bddc-325d-4b72-9bad-5d06012eb9c3.png">

**Comment by rfay** [comment]
You have to do a number of extra things on the WSL2 install to use it in the way most people do, like sharing the CA with the browser on the Windows side, etc. That's why it's different.

**Comment by therobyouknow** [comment]
> You have to do a number of extra things on the WSL2 install to use it in the way most people do, like sharing the CA with the browser on the Windows side, etc. That's why it's different.

Noted thank you for responding.

As per my issue, I had wondered why there were 2 different ways to install 

Linux:

> curl https://apt.fury.io/drud/gpg.key | sudo apt-key add -
> echo "deb https://apt.fury.io/drud/ * *" | sudo tee -a /etc/apt/sources.list.d/ddev.list
> sudo apt update && sudo apt install -y ddev

WSL2, inside the distro (in its a shell in terminal):

`curl -fsSL https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh | bash`

But I guess that the difference is for "the extra things on the WSL2 install to use it in the way most people do, like sharing the CA with the browser on the Windows side, etc."  If the above steps account for that then I would understand that. I couldn't see CA mentioned in the steps though. Also, https://ddev.com/ddev-local/ddev-wsl2-getting-started/  says:

> Follow the [installation instructions for Linux/MacOS](https://ddev.readthedocs.io/en/stable/#homebrewlinuxbrew-macoslinux) as provided in the DDEV docs.

So if I did that then I think I would be clicking on the Linux tab in https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/

Sorry if this sounds pedantic, it's not meant to be and I'm very grateful for ddev. I wanted to help ensure I always followed the same steps every time. 

This query came about because I've had to do the ddev install twice due to unrelated problems with my machine - I had to re-install Windows 11.  The first time around I followed the Linux tab (I think) for ddev on wsl2 and this 2nd time around just now I followed the WSL2 tab which essentially says the same thing to install ddev inside a shell of the distro but gives me a different set of commands as I've mentioned.

This issue perhaps related https://github.com/drud/ddev/pull/3944 (about documentation overhaul)  I found when trying to see if others already had the same query as me (as the issue template advises me to check).

Thanks so much again for an amazing tool. I will always try to help with the issues I find.

**Comment by therobyouknow** [comment]
To clarify on my last comment, first time around I followed the steps here:

https://ddev.com/ddev-local/ddev-wsl2-getting-started/

(Which included the CA)

The above page then said to follow the linux/macos ddev install steps so then I followed the steps in the Linux tab https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/

**Comment by rfay** [comment]
Sorry, both Linux and wsl2 should use the apt technique to install by default. It's just inconsistent editing that made it end up that way. Would be appreciated if you could edit it.
