### ISSUE TITLE
ddev hostname vs. sudo brew - chicken/egg problem

### ISSUE THREAD

**Issue by herzmut** [drud/ddev#4114]
Hello there,

as a WSL2 user, and a grateful user of your magnificent software, I just came to the case that the project.ddev.site hostname had to be manually registered with `ddev hostname`. This command can only be executed with `sudo` permissions. `sudo`, however, wouldn't know ddev, as ddev lives, like the tool `brew` which brewed... _err_, brought it, in the current user's homespace. `sudo`'s root would require "its own copy" of brew in root's home in order to install ddev for root and to execute the hostname command. (Keeping $HOME with -s would not do a thing, nor is that option part of the output ddev tries to assist with.)

Concludingly, brew does not allow its execution as root. ddev can't be installed for root, and ddev hostname can't be executed that way as sudo.

I propose ddev hostname generates a shell script which calls itself with a sudo prompt, makes the required changes on /etc/hostname, and gets deleted after execution, if ddev would not manage to elevate itself temporarily. The latter would be the best and elegant attempt for a solution, but I believe developers of ddev already considered this and would have done that too, if it would be feasible, so my idea here might not be exactly original.

Feel free to close this issue unanswered if it duplicates an existing issue (which GitHub did not propose to me before sending this).

All the best and keep up the good work!

**Comment by rfay** [comment]
Hi @herzmut - not sure why you opened issue in ddev-contrib, so I moved it over to the ddev issue queue.

Why don't you just switch away from using homebrew for installing ddev, and instead use the [apt install](https://ddev--4106.org.readthedocs.build/en/4106/users/install/ddev-installation/#apt-packages-for-debian-based-systems) technique, and you won't have to worry about your PATH problem.

**Comment by herzmut** [comment]
Hey @rfay, thanks for moving the issue. The reason I used homebrew for installing ddev instead of using the system's package manager is simply that I did not get the memo. 😓  The problem does not seem to be as big as it was to me, yet it might still affect macOS users and those who chose homebrew for their Linux in ignorance like me or in bearing with legacy installations. So I'm uncertain if I should close the issue right away.

**Comment by rfay** [comment]
OK, your problem was that you didn't have the brew directory correctly in your PATH, or that you had sudo set up to use root's PATH instead of the user's PATH. I've never had the problem you had, but it had to do with `sudo ddev` not using the current user's PATH. 

Please note that normal usage of DDEV doesn't ever require sudo. If you're using `*.ddev.site`, which is the default, and if you have an internet connection, then you shouldn't need any sudo or any manipulation of the hosts file. If you are having that trouble you may want to look at https://ddev.readthedocs.io/en/latest/users/basics/troubleshooting/#dns-rebinding-prohibited-cannot-resolve-or-unknown-host-or-no-address-associated-with-hostname

Closing this for now, happy to continue the conversation here or elsehwere.

**Comment by herzmut** [comment]
> I've never had the problem you had, but it had to do with sudo ddev not using the current user's PATH.

That's correct.

> Please note that normal usage of DDEV doesn't ever require sudo. If you're using *.ddev.site, which is the default, and if you have an internet connection, then you shouldn't need any sudo or any manipulation of the hosts file.

True, that was my experience with ddev always. However, the CLI of v1.20.0 recommended to execute `ddev hostname project.ddev.site` for the reason that I am using WSL2. Concurring services, like Microsoft's Internet Information Server, might have had an influence on that: stopping the IIS, and re-starting the ddev containers again actually registered the project with ddev.site now, so neither the CLI advice nor a DNS Probe error in the browser appeared again. I'd like to leave this here in case anyone is googling this.

**Comment by rfay** [comment]
If you're running IIS somewhere, you'll be in the land of catastrophe, but it has no influence on the ability to lookup `*.ddev.site`. 

If you're able to look up `dkdkdk.ddev.site` (Use `ping dkdkdk.ddev.site` on both WSL2 and on the Windows side) then things are working. It should resolve to 127.0.0.1. If that *doesn't* work (if it says "can't resolve" or something like that) then you have no internet or you have the DNS binding problem.

The ordinary setup of WSL2 with a working network does not require hosts file manipulation. That's just a fallback.
