### ISSUE TITLE
ddev homebrew doesn't properly install bash completions

### ISSUE THREAD

**Issue by rfay** [drud/ddev#412]
## What happened (or feature request):

In [bash completion PR #309](https://github.com/drud/ddev/pull/309) I claimed that homebrew would install ddev's bash completion automatically, but it doesn't, I'm not sure what I missed there.

It would sure be nice if it did. (And our docs say that it does)

**Comment by rickmanelius** [comment]
Seems like this is low hanging fruit. Happy to knock out if/when there is downtime and/or waiting on tests/builds.

**Comment by rfay** [comment]
Fixed in https://github.com/drud/homebrew-ddev/commit/681a6e5fa325bf0006cc918f5068bf3542d3c8cb
