### ISSUE TITLE
macOS Ventura + nfs_mount_enabled: 504 Error on laravel and bedrock sites

### ISSUE THREAD

**Issue by shayanabbas** [drud/ddev#4122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/shayanabbas/5f7e4481027cce533824b845c76e1186

### Current Behavior

This is the most weirdest issue I have ever had.

I am trying to run my bedrock projects, everything was working fine until I updated to macOS Ventura

After lot of debugging and trying everything it seems like when ever I try to run a laravel and bedrock project the browsers keep loading and show 504 error.

### Expected Behavior

it should run out of the box, i am not sure what macOS Ventura might have changed?

### Steps To Reproduce

I have tried creating fresh projects of Drupal, Wordpress, Bedrock, Laravel  from Quick Start guide 
https://ddev.readthedocs.io/en/latest/users/quickstart/

Drupal and Wordpress (simple) are working and running

where as Bedrock and Laravel project runs successfully but when I visit in browser it keeps loading until it shows a 504 error page.

I tried changing with both nginx and apace webserver configuation in config.yaml

Server is working fine because when I put a index.php file with php info function, it does show that page. but as soon as I change it back to default laravel or bedrock it agains keeps showing 504 error.

I have updated version of ddev and dockers and docker is also has plenty of extra space assigned.

**Comment by rfay** [comment]
Hi - Since Ventura has not been released, I haven't tried it. I haven't heard any announcement that Docker Desktop supports it either (I see you're using Docker Desktop)

It's interesting that you're successful with Drupal and Wordpress, thanks for the careful testing. And the gist shows that a trivial project also works.

Maybe you can see if `ddev logs` after you visit the Bedrock/Laravel projects has any clue. And of course, you may want to step through them to see what fails.

Since you're great at trying things out many ways, you may want to try Colima+mutagen as well.

**Comment by shayanabbas** [comment]
I tried Colima+mutagen it seems to be working after setting up Colima.

thanks

**Comment by rfay** [comment]
I'd love to know what is wrong on the Docker Desktop side. I guess it will shortly be time to update a machine and try it out. Weird that it only affected those two project types, normally it's all-or-nothing.

**Comment by shayanabbas** [comment]
that's true, I will try it out with latest updates of MacOS Ventura or ask one of my colleague to try out same scenario.

**Comment by shayanabbas** [comment]
well i can confirm that this issue is not with Docker Desktop specifically atleast, with running it with Colima+Mutagen setup, I was having some code sync issues with mutagen so i decided to stop it, and run the project with just Colima and that issue again starts, it keep loading the page until it die with 504 error message.

**Comment by rfay** [comment]
I don't think you'll be happy with colima and not mutagen, because it uses sshfs for mounting, which is too slow; composer install fails, for example.

After it does with 504, please look at `ddev logs`.

**Comment by shayanabbas** [comment]
@rfay I have run it and after the error i did `ddev logs` 

`
[Wed Aug 17 16:41:02.386108 2022] [proxy_fcgi:error] [pid 2544] (70007)The timeout specified has expired: [client 172.21.0.6:58022] AH01075: Error dispatching request to : (polling)
`
https://gist.github.com/shayanabbas/5825a3747894af631410e956cfc82446

**Comment by rfay** [comment]
Thanks, I see your `ddev debug test` was with Colima. Was the failure in https://github.com/drud/ddev/issues/4122#issuecomment-1218261837 also with Colima?

It looks like php-fpm is taking a request and never finishing, which could be because of database or an fpm problem.

If this is with colima it's super interesting that you're having the same problem as with Docker Desktop.

I'll try to upgrade a machine in coming days. It does seem like beta5 should be pretty close to ready. 

I'm really surprised that there seem to be no ventura issues in the docker/for-mac queue at this point. Normally there would at least be some. https://github.com/docker/for-mac/issues?q=is%3Aissue+is%3Aopen+ventura+ - also seem to be none in colima queue, https://github.com/abiosoft/colima/issues?q=is%3Aissue+is%3Aopen+ventura

You're absolutely sure that this has to do with the OS version right? You can use the exact same built code/project on a machine that hasn't been upgraded without this problem?

**Comment by shayanabbas** [comment]
Yes the failure in #4122 was with Colima,

I am not sure if its the OS issue or not but it seems like it, because after the upgrade I run the project and it was having this issue, after that i tried to updated docker and ddev but doesnt worked.

and yes same code/project is working on other devices. I tried with fresh projects for laravel and bedrock it had same issue as well.

**Comment by rfay** [comment]
Thanks. It sure sounds like a problem. Could you please push the simplest possible demonstration project to a GitHub test repo, with exact instructions on how to recreate the failure in the README?

**Comment by shayanabbas** [comment]
I have created a repo with details in README https://github.com/shayanabbas/my-wp-bedrock-site

**Comment by rfay** [comment]
Thanks so much!

**Comment by rfay** [comment]
Oh, I saw your original `ddev debug test` was with an amd64 machine, do you have any experience with this on arm64/M1?

**Comment by shayanabbas** [comment]
No unfortunately not with the M1 variation

**Comment by rfay** [comment]
I see from the README (thanks) you were testing on beta5. Trying to install now; it wants to give me beta3 first :(

**Comment by rfay** [comment]
Unfortunately, I'm unable to confirm your results. I installed your demo repo and had no trouble on Ventura beta 5. The only thing was the PHP8.1 deprecations all over the screen. 

Version 13.0 Beta (22A5321d)
amd64, 16GB Dual-Core Intel Core i5
Mid-2017 MBP if I remember

My Docker Desktop settings are
Docker Desktop 4.11.1
CPUs: 2
Memory: 6GB
Swap: 1GB

I do occasionally see this with your WP demo site using `ddev logs -f` (which I recommend):
`[18-Aug-2022 01:03:57] WARNING: [pool www] server reached pm.max_children setting (8), consider raising it`

I assume that's a result of WP calling back to itself, and may be an argument for increasing pm.max_children, not sure. It also could be a factor in your Laravel situation.

I tried the same repo on a Mac M1 Pro with 5CPUs and didn't see that warning.

Could you please try this on a different machine, consider a Docker Desktop factory reset, and consider experimenting with your Docker Desktop settings?

My Ventura testing with

**Comment by shayanabbas** [comment]
super weird, I tried with Docker desktop factory reset as well.

Version 13.0 Beta (22A5321d)
amd64, 16 GB 2.3 GHz Quad-Core Intel Core i7
Year 2020

My Docker Desktop settings:
Docker Desktop 4.11.1 (Docker Engine: v20.10.17)
CPUs: 4
Memory: 8GB
Swap: 2GB


after running `ddev logs -f`

```sh
Server started
+ echo 'Server started'
+ unset PHP_IDE_CONFIG
+ exec /usr/bin/supervisord -n -c /etc/supervisor/supervisord-apache-fpm.conf
2022-08-18 08:44:40,608 INFO Included extra file "/etc/supervisor/apache.conf" during parsing
2022-08-18 08:44:40,608 INFO Included extra file "/etc/supervisor/php-fpm.conf" during parsing
2022-08-18 08:44:40,608 INFO Included extra file "/etc/supervisor/conf.d/mailhog.conf" during parsing
2022-08-18 08:44:40,608 INFO Included extra file "/etc/supervisor/conf.d/supervisor.conf" during parsing
2022-08-18 08:44:40,667 INFO RPC interface 'supervisor' initialized
2022-08-18 08:44:40,668 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2022-08-18 08:44:40,669 INFO supervisord started with pid 1
2022-08-18 08:44:41,680 INFO spawned: 'child_exit_monitor' with pid 2518
2022-08-18 08:44:41,709 INFO spawned: 'php-fpm' with pid 2519
2022-08-18 08:44:41,772 INFO spawned: 'apache2' with pid 2520
2022-08-18 08:44:41,785 INFO spawned: 'mailhog' with pid 2521
2022-08-18 08:44:42,889 INFO success: child_exit_monitor entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-08-18 08:44:42,890 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-08-18 08:44:42,890 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-08-18 08:44:42,890 INFO success: mailhog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.4. Set the 'ServerName' directive globally to suppress this message
[Thu Aug 18 08:44:42.924065 2022] [ssl:warn] [pid 2529] AH01909: 172.26.0.4:443:0 server certificate does NOT include an ID which matches the server name
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.4. Set the 'ServerName' directive globally to suppress this message
[Thu Aug 18 08:44:42.949577 2022] [ssl:warn] [pid 2529] AH01909: 172.26.0.4:443:0 server certificate does NOT include an ID which matches the server name
[Thu Aug 18 08:44:43.013086 2022] [mpm_prefork:notice] [pid 2529] AH00163: Apache/2.4.54 (Debian) OpenSSL/1.1.1n configured -- resuming normal operations
[Thu Aug 18 08:44:43.013281 2022] [core:notice] [pid 2529] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
[Thu Aug 18 08:44:43.966708 2022] [proxy:error] [pid 2543] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /var/run/php-fpm.sock (*:80) failed
[Thu Aug 18 08:44:43.966871 2022] [proxy_fcgi:error] [pid 2543] [client 127.0.0.1:35702] AH01079: failed to make connection to backend: httpd-UDS
[18-Aug-2022 08:44:45] NOTICE: fpm is running, pid 2519
[18-Aug-2022 08:44:45] NOTICE: ready to handle connections
[18-Aug-2022 08:44:45] NOTICE: systemd monitor interval set to 10000ms
[Thu Aug 18 08:50:12.697628 2022] [proxy_fcgi:error] [pid 2545] (70007)The timeout specified has expired: [client 172.18.0.6:44524] AH01075: Error dispatching request to : (polling)
```

does this show the error?
```sh
[Thu Aug 18 08:44:43.966708 2022] [proxy:error] [pid 2543] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /var/run/php-fpm.sock (*:80) failed
[Thu Aug 18 08:44:43.966871 2022] [proxy_fcgi:error] [pid 2543] [client 127.0.0.1:35702] AH01079: failed to make connection to backend: httpd-UDS
```

Is there anything related to server setup apache/nginx configuration I can do here to resolve this?

**Comment by rfay** [comment]
Looks like php-fpm is ceasing to respond. You could increase the number of pm.max_children but I'll bet it will just happen again. 

I hope you'll be able to try on another machine. You've already rebooted right?

Do you know WP well enough to know whether there's a reason for a single web hit to cause multiple http sessions?

**Comment by shayanabbas** [comment]
okay so my issue is resolved now I need to test more, but after disabling NFS mount my project starts working
`ddev config global --nfs-mount-enabled=false`

so maybe you try it on Ventura with nfs mount enable, that might generate same issue on your system?

**Comment by rfay** [comment]
Thanks, they had a problem with NFS in a previous beta of a previous OS. But now since everybody uses mutagen, it shouldn't show up as much. Glad you caught it!

**Comment by rfay** [comment]
I'm able to recreate this with your same results. I have no idea why laravel or bedrock would be affected and Drupal9 not. 

I used Console.app to watch for nfsd problems and it didn't show any, probably because nfsd just isn't working, it sticks/hangs.

Looks to me like others have had this class of problem, see https://www.reddit.com/r/MacOSBeta/comments/w070z4/ventura_file_sharing_issues/ (but that's all I found)

**Comment by shayanabbas** [comment]
maybe this will take a little bit of time to acknowledge what's the exact issue.

**Comment by rfay** [comment]
I just upgraded to Ventura public beta 4 (same as developer beta 6) and I don't see any difference in the behavior. Even though `ddev debug nfsmount` shows things working fine, and even though `ddev start` on your test site and `ddev describe` show it working with nfs, it never responds to web browser, and `curl -I https://my-wp-bedrock-site.ddev.site` hangs. 

I do see the interesting error in console.app
`Can't open /var/db/mountdtab: No such file or directory (2)`

**Comment by rfay** [comment]
Tried it with Public Beta 8, same behavior. 

I did learn some interesting things though:

* The behavior is the same with colima as with Docker Desktop
* If I create an index.html in the docroot (web) of the bedrock site, it properly loads the index.html (with both Docker Desktop  and colima, using nfs)

So I think based on the difference between CMSs in this context, that something is actually going wrong with *php-fpm* and we might be able to put a breakpoint in the index.php and step through until it hangs, and that would probably give us a clue.

**Comment by rfay** [comment]
I stepped through the WP initialization in PhpStorm. What happens is that when it gets to requiring formatting.php it freezes. formatting.php is a 330KB 6106 line PHP file, and as soon as it gets accessed, everything freezes. I also did a `ddev ssh` and all actions that try to access the content of formatting.php freeze. For example, in the container, `vi formatting.php` or `wc -l formatting.php` or `less formatting.php`. 

So it's an NFS bug in Ventura I would bet.  

You don't have to do anything interesting to demonstrate it. Just `ddev start` (with NFS enabled) and `ddev exec wc ./web/wp/wp-includes/formatting.php` which will hang.

**Comment by karlshea** [comment]
NFS is still broken on Ventura release, I'm also getting "nfsd send error 40" on a non-ddev Docker compose project.

**Comment by karlshea** [comment]
Seems to work without Docker. I disabled the firewall just in case because now it says "File sharing (SMB)", and I removed host restrictions from my export.

**Host**:
```
/Users/karl -alldirs -mapall=501:20
```

**Client:**
```
mount -t nfs hostmac:/Users/karl testmount
```

Everything works in this case between Macs, but it still doesn't work in Docker.

Snippets from my non-ddev docker-compose.override.yaml (because I'm not sure how ddev's NFS support works under the hood):

```
services:
  php:
    volumes:
      - type: volume
        source: nfsmount-repo
        target: /var/www/app

        volume:
          nocopy: true

...

volumes:
  nfsmount-repo:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=host.docker.internal,hard,nolock,rw"
      device: ":/System/Volumes/Data/Users/karl/the-path-here" # Also tried /Users/karl
```

**Comment by rfay** [comment]
In my [most recent test](https://github.com/drud/ddev/issues/4122#issuecomment-1272648461) I tried with Colima too, so it's likely not a docker-desktop-specific problem. And that makes me think it's a plain macOS problem. But it could possibly be a docker-ce problem with NFS on Ventura.

**Comment by karlshea** [comment]
It is strange that it works cross-Mac with no Docker involved, so maybe it really is a docker-ce problem?

I have a helper script that does `composer install` inside this container so the right version of PHP is being used, and it also hangs on "Generating optimized autoload files".

**Comment by karlshea** [comment]
I'm having a hard time reproducing this with a simple test case unfortunately... small docker-compose files that do some NFS mounts and install some composer packages all work fine. I'm pretty stumped.

**Comment by rfay** [comment]
Would you mind trying it out with the original WordPress case? In https://github.com/drud/ddev/issues/4122#issuecomment-1272707930 I found that it hung on particular files in bedrock, using the bedrock recipe from ddev quickstarts.

**Comment by rfay** [comment]
I confirm the same problem using bedrock install from https://ddev.readthedocs.io/en/latest/users/quickstart/#bedrock and nfs_mount_enabled: true.

**Comment by karlshea** [comment]
[#4122 (comment)](https://github.com/drud/ddev/issues/4122#issuecomment-1272707930) was a great clue! Sorry I didn't read your debugging, it's definitely a file size issue. I've got a plain Docker reproduction.

If you can reproduce I'll open an issue in docker/for-mac.

Clone this repo and change the volume path to match your own in docker-compose.yml: https://github.com/karlshea/docker-nfs

## Reproduction

### Setup

In one shell launch the container: `docker-compose up`

### Docker NFS
In another shell:

`docker compose exec php php /var/www/app/small.php` should print out "small"

`docker compose exec php php /var/www/app/large.php` should hang (or print out "large" if it works for you I guess).

### Plain NFS

On another Mac, mount that same directory over NFS. 

`cat small.php` works, as does `cat large.php`.

**Comment by karlshea** [comment]
Well this is weird, I added small.sh and large.sh to that repo and they both work fine (`docker compose exec php /bin/bash /var/www/app/large.sh`), while PHP hangs. I wonder if it's an issue with NFS and the PHP images?

**Comment by karlshea** [comment]
Okay even weirder, I wonder if it's actually a memory/opcode size issue. In that repo running `docker compose exec php php /var/www/app/test.php` is a PHP script that just reads the large.sh file contents into a var and it works, even though it's the same size file as the large.php script which hangs.

**Comment by noud-github** [comment]
Found this after encountering issue with docker NFS and wordpress and large plugins, disabling NFS fixed it, but is super slow but we are using 'ranger desktop' 
so it starts to look like MacOs Ventura NFS is not working well with docker.

**Comment by rfay** [comment]
It does seem like most people have moved on to mutagen, `ddev config global --mutagen-enabled`, which is way faster than NFS. But I wish NFS wasn't broken in Ventura.

**Comment by rfay** [comment]
Added a docs warning about this in
* https://github.com/drud/ddev/pull/4343

**Comment by cmuench** [comment]
> It does seem like most people have moved on to mutagen, `ddev config global --mutagen-enabled`, which is way faster than NFS. But I wish NFS wasn't broken in Ventura.

Mutagen is faster but has downsides in the amount of data which is used on the hard drive.
It would be good if both options are available.

**Comment by freef4ll** [comment]
Yes, on the NFS side; the problem reproduces when trying to iterate over a directory that has large number of files.

For example, listing somewhere between 800 and 900 files sometimes causes issues to reproduce; `ls 3000` will also likely hang.

```
function create_files()
{
	test_file="${1:-1000}"
	mkdir -p $test_file
	for i in $(seq 1 $test_file); do touch $test_file/$i; done
}

create_files 800
create_files 900
create_files 1000
create_files 1500
create_files 2000
create_files 3000
```

The problem feels like any large packets cannot be sent from `nfsd` to the hosts on the bridged network, as cannot even cat or md5sum large files.

**Comment by rfay** [comment]
This is fixable in the short term with this `ddev/docker-compose.nfs.yaml` - you have to look at existing .ddev/.ddev-docker-compose-base.yaml to find the `name` (change from `ddev-bedrock_nfsmount`), the IP address for the `o:` line, and the `device` (change from `/System/Volumes/Data/Users/rfay/workspace/bedrock`)

```yaml
volumes:
  nfsmount:
    name: "ddev-bedrock_nfsmount"
    driver: local
    driver_opts:
      type: nfs
      o: "addr=192.168.5.2,hard,nolock,rw,wsize=32768,rsize=32768"
      device: ':/System/Volumes/Data/Users/rfay/workspace/bedrock'
```

**Comment by karlshea** [comment]
You also have to delete the NFS Docker volume so it can be recreated with those new options.

**Comment by rfay** [comment]
`ddev stop` deletes the volume.

**Comment by shayanabbas** [comment]
@rfay I tried using the HEAD version of DDEV I have correctly setup the NFS 

if i do `ddev debug nfsmount` i get following error, even nfs is setup correctly
```
NFS does not seem to be set up yet, see debugging instructions at https://ddev.readthedocs.io/en/stable/users/install/performance/#debugging-ddev-start-failures-with-nfs_mount_enabled-true
Details: error=failed to StartContainer: API error (500): error while mounting volume '/var/lib/docker/volumes/testnfsmount/_data': failed to mount local volume: mount :/System/Volumes/Data/Users/username/work/generogrowth:/var/lib/docker/volumes/testnfsmount/_data, data: addr=192.168.65.2,hard,nolock,wsize=32768,rsize=32768: stale NFS file handle
output=
```

if i run project I get this error

```
Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
Using nginx snippets: [/Users/username/work/bedrock/.ddev/nginx/uploads-redirect.conf]
Custom configuration takes effect when the container is created.
Should something go wrong and no effect be visible use 'ddev restart'.
Pushed mkcert rootca certs to ddev-global-cache/mkcert
Network ddev-bedrock_default  Created
Volume "ddev-bedrock_nfsmount"  Created
Container ddev-bedrock-dba  Started
Container ddev-bedrock-db  Started
Error response from daemon: error while mounting volume '/var/lib/docker/volumes/ddev-bedrock_nfsmount/_data': failed to mount local volume: mount :/System/Volumes/Data/Users/username/work/bedrock:/var/lib/docker/volumes/ddev-bedrock_nfsmount/_data, data: addr=192.168.65.2,hard,nolock,wsize=32768,rsize=32768: stale NFS file handle
Failed to start bedrock: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-bedrock docker-compose -f /Users/username/work/bedrock/.ddev/.ddev-docker-compose-full.yaml up --build -d', action='[up --build -d]', err='exit status 1', stdout='#1 [drud/ddev-dbserver-mariadb-10.2:20221026_uid_collision-bedrock-built internal] load build definition from Dockerfile
#1 transferring dockerfile: 591B 0.0s done
#1 DONE 0.0s

#2 [drud/ddev-dbserver-mariadb-10.2:20221026_uid_collision-bedrock-built internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [drud/ddev-webserver:20221031_healthcheck_no_profile-bedrock-built internal] load build definition from Dockerfile
#3 transferring dockerfile: 922B done
#3 DONE 0.0s

#4 [drud/ddev-dbserver-mariadb-10.2:20221026_uid_collision-bedrock-built internal] load metadata for docker.io/drud/ddev-dbserver-mariadb-10.2:20221026_uid_collision
#4 DONE 0.0s

#5 [drud/ddev-dbserver-mariadb-10.2:20221026_uid_collision-bedrock-built 1/2] FROM docker.io/drud/ddev-dbserver-mariadb-10.2:20221026_uid_collision
#5 DONE 0.0s

#6 [drud/ddev-dbserver-mariadb-10.2:20221026_uid_collision-bedrock-built 2/2] RUN (groupadd --gid 20 "username" || groupadd "username" || true) && (useradd  -l -m -s "/bin/bash" --gid "username" --comment '' --uid 501 "username" || useradd  -l -m -s "/bin/bash" --gid "username" --comment '' "username" || useradd  -l -m -s "/bin/bash" --gid "20" --comment '' "username" || useradd -l -m -s "/bin/bash" --comment '' username )
#6 CACHED

#7 [drud/ddev-dbserver-mariadb-10.2:20221026_uid_collision-bedrock-built] exporting to image
#7 exporting layers done
#7 exporting layers done
#7 writing image sha256:17ebb57d443ad4cc838f6b172c39c592ed0decf77a8af1a85a421b3860bdd501 done
#7 naming to docker.io/drud/ddev-dbserver-mariadb-10.2:20221026_uid_collision-bedrock-built done
#7 writing image sha256:b6ab343e2508683c8599ff9a80ea52d4fca3f328be048bec9ebe85a614a30b4f done
#7 naming to docker.io/drud/ddev-webserver:20221031_healthcheck_no_profile-bedrock-built done
#7 DONE 0.1s

#8 [drud/ddev-webserver:20221031_healthcheck_no_profile-bedrock-built internal] load .dockerignore
#8 transferring context: 2B done
#8 DONE 0.0s

#9 [drud/ddev-webserver:20221031_healthcheck_no_profile-bedrock-built internal] load metadata for docker.io/drud/ddev-webserver:20221031_healthcheck_no_profile
#9 DONE 0.0s

#10 [drud/ddev-webserver:20221031_healthcheck_no_profile-bedrock-built 1/4] FROM docker.io/drud/ddev-webserver:20221031_healthcheck_no_profile
#10 DONE 0.0s

#11 [drud/ddev-webserver:20221031_healthcheck_no_profile-bedrock-built 2/4] RUN (groupadd --gid 20 "username" || groupadd "username" || true) && (useradd  -l -m -s "/bin/bash" --gid "username" --comment '' --uid 501 "username" || useradd  -l -m -s "/bin/bash" --gid "username" --comment '' "username" || useradd  -l -m -s "/bin/bash" --gid "20" --comment '' "username" || useradd -l -m -s "/bin/bash" --comment '' username )
#11 CACHED

#12 [drud/ddev-webserver:20221031_healthcheck_no_profile-bedrock-built 3/4] RUN export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2 || composer self-update --2 || true
#12 CACHED

#13 [drud/ddev-webserver:20221031_healthcheck_no_profile-bedrock-built 4/4] RUN mkdir -p /home/username && chown username /home/username && chmod 600 /home/username/.pgpass
#13 CACHED
', stderr='Network ddev-bedrock_default  Creating
Network ddev-bedrock_default  Created
Volume "ddev-bedrock_nfsmount"  Creating
Volume "ddev-bedrock_nfsmount"  Created
Container ddev-bedrock-web  Creating
Container ddev-bedrock-dba  Creating
Container ddev-bedrock-db  Creating
Container ddev-bedrock-dba  Created
Container ddev-bedrock-db  Created
Container ddev-bedrock-web  Created
Container ddev-bedrock-dba  Starting
Container ddev-bedrock-db  Starting
Container ddev-bedrock-web  Starting
Container ddev-bedrock-dba  Started
Container ddev-bedrock-db  Started
Error response from daemon: error while mounting volume '/var/lib/docker/volumes/ddev-bedrock_nfsmount/_data': failed to mount local volume: mount :/System/Volumes/Data/Users/username/work/bedrock:/var/lib/docker/volumes/ddev-bedrock_nfsmount/_data, data: addr=192.168.65.2,hard,nolock,wsize=32768,rsize=32768: stale NFS file handle'
Instrumentation is opted in, but SegmentKey is not available. This usually means you have a locally-built ddev binary or one from a PR build. It's not an error. Please report it if you're using an official release build.
```

**Comment by rfay** [comment]
@shayanabbas - Please open a new issue, or come to [Discord](https://discord.gg/hCZFfAMc5k) for support. In either case, please provide the results of `ddev debug test` in a gist on gist.github.com (give a link) and also give the results of going through the macOS NFS Debugging section in https://ddev.readthedocs.io/en/stable/users/install/performance/#nfs

The most likely situation is that you just don't have working NFS (run the [script](https://raw.githubusercontent.com/drud/ddev/master/scripts/macos_ddev_nfs_setup.sh) again, check your /etc/exports, etc)
