### ISSUE TITLE
Infrastructure requirements for Windows and OSX testing

### ISSUE THREAD

**Issue by rfay** [drud/ddev#413]
In https://github.com/drud/ddev/pull/411 we implemented surf testing for windows and OSX, but without working on the infrastructure requirements, so now my laptops are our Windows/OSX build system and they can't be used for development while a build is happening :(

Note that CircleCI claims they'll have OSX circleci v2.0 testing "real soon now". However, we don't know whether it will be possible to test on both OSX and Linux for a given PR, so their move to OSX might not really solve our issues.

So we need either our own hardware (no internet requirements, this is a polling system, no static IP requirements) or we need cloud machines to do this.

If we use our own hardware, we just need to be able to make sure the hardware is mostly up and that it's accessible without a lot of hassle if somebody needs to fix it. So we'd need to acquire or repurpose a Windows and an OSX machine and find a place to put them where they could be messed with.  **A simple option is to ship me 2 of our macbook PROs that are sitting unused, and buy a windows license for one**

Options for cloud:
* AWS Windows (sql web): t2.small: $77/month t2.medium: $155/month. It's not a given that docker will install on there, but if docker-for-windows does we should be golden.
* [hostmyapple](https://www.hostmyapple.com/macvps.html) has Mac VPS for $35-90/month. 

In general, I'm biased to using our own hardware. It's simple, a bit flaky, but this is *backup* testing, an extra measure of security. It's not our primary technique.

**Comment by rfay** [comment]
We agreed in meeting this morning that @rickmanelius will ship me two Macbooks today (no big rush). We'll buy a Windows license for one of them.

**Comment by rfay** [comment]
@cyberswat the budget requirement is just 1) shipping and 2) Windows license.

**Comment by rickmanelius** [comment]
@rfay and I have discussed 1x1 in Slack. We have a few machines pulled and ready to send out.

**Comment by rickmanelius** [comment]
An email was sent out to the team to address Windows license purchase and shipment of the two laptops. Once received and @rfay is operational, he can close out the ticket. Assigning over...

**Comment by rfay** [comment]
This is deployed and documented, so closing. Thanks for all the help on this everybody.
