### ISSUE TITLE
`ddev mutagen status --verbose` doesn't actually show full status (mutagen sync list -l)

### ISSUE THREAD

**Issue by zolthan** [drud/ddev#4146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When mutagen encounters a problem or conflict, the command `ddev mutagen status --verbose` only confirms that there is a conflict or problem. There is no way to see which files are the reason.

### Describe the solution you'd like

The command `mutagen list -l` normally lists the problems. The `--verbose` option  should also list the problematic files.

**Comment by rfay** [comment]
Hi @zolthan - `ddev mutagen status --verbose` just runs `mutagen sync list <syncname> -l`, so you should get what you're looking for already. 

What kind of problem are you running into?

**Comment by rfay** [comment]
You may also want to look at https://ddev.readthedocs.io/en/latest/users/install/performance/#advanced-mutagen-troubleshooting, which shows how to get the full log. 

But I'd love to know what kind of problem you're running into, and please do show the difference between `ddev mutagen status --verbose` and `mutagen sync list -l <syncname>`

**Comment by zolthan** [comment]
Hi @rfay thanks for the quick response.

Unfortunately I don't know how to run the mutagen commands directly, so I don't know how the output looks like in mutagen 0.15.

Currently I get this message in one of my projects:
```
❯ ddev mutagen status project --verbose
Mutagen: problems: 
--------------------------------------------------------------------------------
Name: project
Identifier: sync_3NbnDrtgXOYqsq7ohmILcU65yOpPxaLbqUHTPTD6YwU
Alpha:
        URL: /Volumes/.../.../project
        Connected: Yes
        Synchronizable contents:
                10993 directories
                25164 files (949 MB)
                0 symbolic links
Beta:
        URL: docker://cf0b960fa97dc3534b1fd448f5bc75a89014bed0e15bea8db575aa0a21f24640/var/www/html
                DOCKER_HOST=unix:///var/run/docker.sock
        Connected: Yes
        Synchronizable contents:
                10992 directories
                25164 files (949 MB)
                0 symbolic links
        Scan problems: 1
Status: Scanning files
--------------------------------------------------------------------------------
```
There is 1 scan problem, but I don't know what it is. I have the same output with conflicts. There it also only shows the number of conflicts but not which file it is. In older mutagen versions (before I used ddev) there where always the files listed that produced the problems/conflicts.

**Comment by rfay** [comment]
I really want to know what's going on here.

You have a couple of ways to run `mutagen sync list -l` directly, please do it. 

`ddev debug mutagen sync list -l`
`~/.ddev/bin/mutagen sync list -l`

**Comment by rfay** [comment]
Oh dear, I think you're right. The two approaches above will show what you're looking for, but 

https://github.com/drud/ddev/blob/777386662756585a8d2519e8e3a34a48d481d8db/pkg/ddevapp/mutagen.go#L316

**Comment by rfay** [comment]
It looks like this was fixed in
* https://github.com/drud/ddev/pull/4109
which went in yesterday. 

For your short-term solutions of understanding the conflict, use the techniques above:
```
`ddev debug mutagen sync list -l`
`~/.ddev/bin/mutagen sync list -l`
```

What I'd really love to have you do is use current HEAD of ddev and report your results,

`brew unlink ddev && brew install --HEAD --fetch-head ddev`

**Comment by zolthan** [comment]
Hi @rfay , looks good

```
❯ ddev mutagen status --verbose
Mutagen: problems: 
--------------------------------------------------------------------------------
Name: project
Identifier: sync_MkoZLbHhiZM8SEN3Qc7UEJ4j8Xw82dUiroLCMqz2Yrw
Labels:
	com.ddev.volume-signature: unix-var-run-docker-sock-1661794265
Configuration:
	Synchronization mode: Two Way Resolved
	Maximum allowed entry count: Default (2⁶⁴−1)
	Maximum staging file size: Default (18 EB)
	Symbolic link mode: Ignore
	Ignore VCS mode: Propagate
	Ignores:
		/.git
		/.tarballs
		/.ddev/db_snapshots
		/.ddev/.importdb*
		.DS_Store
		.idea
		/www/media
Alpha:
	URL: /Volumes/.../.../project
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: 2 seconds
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
	Connected: Yes
	Synchronizable contents:
		10988 directories
		25206 files (949 MB)
		0 symbolic links
Beta:
	URL: docker://ddev-project-web/var/www/html
		DOCKER_HOST=unix:///var/run/docker.sock
	Configuration:
		Watch mode: Default (Portable)
		Watch polling interval: 2 seconds
		Probe mode: Default (Probe)
		Scan mode: Default (Accelerated)
		Stage mode: Neighboring
		File mode: Default (0600)
		Directory mode: Default (0700)
		Default file/directory owner: Default
		Default file/directory group: Default
	Connected: Yes
	Synchronizable contents:
		10987 directories
		25206 files (949 MB)
		0 symbolic links
	Scan problems:
		www/var/upload: scan crossed filesystem boundary
Status: Scanning files
--------------------------------------------------------------------------------
 
```

Now I can see the reason. As I thought, it is the upload folder.

**Comment by rfay** [comment]
You can solve it by setting `upload_dir` in the .ddev/config.yaml.

**Comment by zolthan** [comment]
Where should I set the `upload_dir` to? I don't need it as everything is synced via mutagen.

**Comment by rfay** [comment]
Most people don't want mutagen to sync their upload_dir, because it may be large and it takes time to sync and uses lots of disk space. 

You would set your upload_dir to the relative path from your project root to where user-generated files are stored. I don't know what CMS you're using (or not). But from your output it looks like your upload_dir is `www/var/upload`

**Comment by rfay** [comment]
You can also take over the mutagen.yml and change what it does and not rely on this.

**Comment by zolthan** [comment]
Yeah. That is my solution. I‘ll add it to the ignore paths.

**Comment by rfay** [comment]
You can also change the project type to php for example, but easier to just change upload_dir.

Thanks for testing HEAD. As a sophisticated user I'd love you to stick with it and report on it. There is one more minor mutagen PR that will go in shortly, 

* https://github.com/drud/ddev/pull/4153

**Comment by zolthan** [comment]
I have the software development lead in our company so normally I have to stick on the stable version to be able to help our employees. So unfortunately I can't do the beta testing. But if I encounter another problem, I'll report it.

**Comment by rfay** [comment]
This was fixed in 
* https://github.com/drud/ddev/pull/4109

Per this discussion, I just added a warning about upload_dir in 
* https://github.com/drud/ddev/pull/4173
