### ISSUE TITLE
Create a Code of Conduct for the ddev community

### ISSUE THREAD

**Issue by deviantintegral** [drud/ddev#4159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Adding a simple and clear code of conduct will:

1. Signal that how we communicate and work with each other is important to the ddev community.
2. Reduce possible confusion over how we resolve conflicts.

Let's add a code of conduct, ideally adopted as-is from an upstream community or template.

### Describe the solution you'd like

- A code of conduct is added to the docs in https://github.com/drud/ddev/tree/master/docs
- `CODE_OF_CONDUCT.md` is added to the repository linking to the documentation for discoverability as recommended at https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

### Additional context

This was initially discussed at https://discord.com/channels/664580571770388500/914881059299131392/1014644656694370354

**Comment by gilbertsoft** [comment]
fyi I'm using https://www.contributor-covenant.org/ for my repositories.

**Comment by deviantintegral** [comment]
The contributor covenant is also what GitHub's templates recommend if you go through the process to set one up.

I looked at two possible upstream code of conduct documents to see if there were any major differences.

## Contributor Covenant

- Broad adoption as listed at https://www.contributor-covenant.org
- Notable upstream users include curl, git, homebrew-cask, linux, node.js, symfony, and yarn.
- Many translations available at https://www.contributor-covenant.org/translations/, though not always up to date.

## Drupal Code of Conduct

- Created for and by the Drupal community, so not broadly adopted.
- English only
- Conflict resolution documented separately at https://www.drupal.org/conflict-resolution with a JP translation
- Inspired by https://www.djangoproject.com/conduct/enforcement-manual/ and https://ubuntu.com/community/code-of-conduct

None of these documents really conflict with each other, but restate similar goals in similar ways. Some, like Drupal, have a bigger community document how their working groups address conflicts, which I think is beyond the scale of ddev today.

My suggestion is we adopt the contributor covenant, in particular because it has the most available translations. This isn't something that's set in stone, and the community and ddev maintainers can easily iterate and update a CoC in the future as needed.

@rfay if you agree, then we just need to figure out what we want to put in for contact information.

**Comment by rfay** [comment]
The contact email can be `conduct` (at) `localdev.foundation` - it's already live. If anybody would like something different... that's fine.

**Comment by rfay** [comment]
Fixed, thanks for 
* #4186
