### ISSUE TITLE
Mutagen enabled globally: "Could not write settings file: Mutagen sync session 'junk' does not exist"

### ISSUE THREAD

**Issue by rfay** [drud/ddev#4162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you create an empty directory named junk, and then `ddev config --auto` there with mutagen enabled globally, you get

`Could not write settings file: Mutagen sync session 'junk' does not exist`

Of course...

* With an empty directory (detected project type'php') it shouldn't be creating a settings file anyway
* During `ddev config` it doesn't care about mutagen... and it's never started yet.

### Expected Behavior

Shouldn't see that.

**Comment by rfay** [comment]
Any un-recognized codebase is reported as a "php" codebase, which is the default type. Doesn't have to be any code. This is the same report that's always been there for an unrecognized codebase.

**Comment by rpkoller** [comment]
ahhhh ok. that just looked odd for an empty directory getting a message that a php codebase was found ^^ but that explains that detail. thanks
