### ISSUE TITLE
`apt search ddev` lacks some information 

### ISSUE THREAD

**Issue by alexander-nitsche** [drud/ddev#4168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running `apt search ddev` on my Debian GNU/Linux 11 (bullseye) i get this information of the ddev package:
```
$ apt search ddev
Sorting... Done
Full Text Search... Done
ddev/unknown,now 1.21.1 amd64 [installed]
  no description given

golang-github-ddevault-go-libvterm-dev/stable 0.0~git20190526.b7d861d-2 all
  aerc fork of go-libvterm (library)
..
```

### Expected Behavior

Would be great to have the information complete with the package state (alpha, beta, stable, ..) and a description.

**Comment by rfay** [comment]
Thanks for the issue, should be fixed with #4174 and next release.
