### ISSUE TITLE
Custom, updatable project types

### ISSUE THREAD

**Issue by zolthan** [drud/ddev#4169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Currently we are working with a couple of Shopware 6 projects containing some project specific and some company wide identical settings, like custom web commands, docker-compose additions, etc.

### Describe the solution you'd like

It would be nice to have some solution, to keep our company stack in sync between different projects. So that I can just pull our current commands, if I change the `ddev update-theme` command for example

### Describe alternatives you've considered

Wen already thought about an integration via composer or git submodules, but that won't work. Asl submodules always need a whole directory and composer only copies files from a to b and doesn't keep track of the up-to-dateness of these files.

**Comment by rfay** [comment]
How about a pre-start exec-host hook that updated things you want to be consistent? That's another possibility.

Custom project types is a great idea, but I'm not sure I'd ever get to it.

**Comment by rfay** [comment]
The best approach I can think of right now is to create and maintain a ddev-get add-on and apply it during a pre-start exec-host hook. That way you've got it externally maintained, and update anything you want, and it's done on every start.

**Comment by rfay** [comment]
This is a great idea, but I don't expect any traction on it. Perhaps raising it will lead us along the path in the future, but for now I'm going to close it.

If you'd like to talk further, lots of people use private composer builds for this purpose, and there are many ways to handle your teams' needs. You might want to raise a conversation about your needs in [Discord](https://discord.gg/hCZFfAMc5k).

Closing for now, happy to continue the conversation here or elsewhere.
