### ISSUE TITLE
mysql 5.7: Failed to import database: exit status 137 (Out of Memory killed)

### ISSUE THREAD

**Issue by joelpittet** [drud/ddev#4170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/joelpittet/34b8737c976835ba88ca11b2a233aae4

```
❯ ddev debug get-volume-db-version
mysql:5.7

❯ ddev debug check-db-match
database in volume matches configured database: mysql:5.7
```

### Current Behavior

Database fails to import at a seemingly random % on a db that is 150M

```
❯ ddev import-db --src=/tmp/PROJECT.sql
mysql: [Warning] Using a password on the command line interface can be insecure.
Failed to import database db for PROJECT failed to import database: exit status 137================================================================================================================>             ] 93% ETA 0:00:01
stdout:
stderr:
```

### Expected Behavior

Database imports

### Steps To Reproduce

I believe it's mysql 5.7 config related, maybe `max_packet_size` and potentially running out of memory.

### Anything else?

During `ddev debug test` it powers off the projects, and after that the import goes through as expected.

So kind of a workaround, but this happens every so often so I thought I should report it to see if we can't get to the bottom of it, or if others have this issue too.

**Comment by rfay** [comment]
The classic reason for this is not having enough docker disk space, in Docker Desktop (mac) or colima. 

You're using Docker Desktop.. what is your allocated disk space and memory?

The problem goes away when you `ddev poweroff`? That might point to disk or memory.

**Comment by joelpittet** [comment]
```
❯ colima -v list
PROFILE    STATUS     ARCH       CPUS    MEMORY    DISK      RUNTIME    ADDRESS
default    Running    aarch64    4       8GiB      100GiB    docker
```

@rfay is there an easy way to check the disk space, I saw it in output of `debug test`
```
Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                  58.8G     46.4G      9.4G  83% /
```

**Comment by rfay** [comment]
Thanks, yes, `ddev debug test` does that, forgot you'd done the gist (and thanks for doing that). 

test_ddev.sh (`ddev debug test`) just does this, 

```
docker run --rm busybox:stable df -h
```

And it does look to me like you have a small amount of disk space available for somebody who likes to do large imports, as I understand.  It looks to me like you have the default, and I almost always set it to 100GB or higher. 

It's easy to change it, as I'm sure you know:

<img width="1168" alt="Settings_-_Docker_Desktop" src="https://user-images.githubusercontent.com/112444/188244163-3ae25e16-5613-42f5-8b41-aa6909228322.png">

As you see in my snapshot, sometimes the docker desktop GUI lies pretty badly.


And it's easy to free up disk space if space is tight. 

You can

* `ddev clean` (See `ddev help clean`)
* `ddev poweroff && docker rm -f $(docker ps -aq) && docker rmi -f $(docker images -q)` (Deletes all docker images, does no harm, they'll be downloaded again.)
* `ddev delete images` (Tries to delete images that aren't in use any more)

The only thing to be careful of when cleaning up is your docker *volumes* which is where the databases are.

**Comment by rfay** [comment]
I just noticed that you gave me a `colima -v list` but in your gist it said "Docker Desktop Version: Docker Desktop for Mac 4.6.1 build 76265", but I see in there you have " docker-platform  colima" - I'll have to pay more attention!  And probably need to improve that script. It found the Docker Desktop (which I hope isn't also running, but apparently is still installed, which is fine).

For colima, to increase the disk space you have to destroy everything and create the colima instance again, sadly. `colima delete && colima start --cpu 4 --memory 6 --dns=1.1.1.1. --disk 120`. You'll lose all databases.

To snapshot the databases of all registered projects you can `ddev snapshot -a` before you do that.

**Comment by rfay** [comment]
* https://github.com/drud/ddev/pull/4171

**Comment by rfay** [comment]
In your case, since `ddev poweroff` solves it, I would suspect memory usage. 

Yup:

> The OOMKilled error, also indicated by exit code 137, means that a container or pod was terminated because they used more memory than allowed. OOM stands for “Out Of Memory”.

**Comment by rfay** [comment]
I think you may in fact be able to change memory usage for colima with just `colima stop` and `colima start -e` with no disruption.

**Comment by joelpittet** [comment]
Docker Desktop is not running (as far as I can see). I just (a min ago) switched to the latest DDEV as per your tweet yesterday.
https://twitter.com/randyfay/status/1565395421496635392?s=20&t=DZSpTB5qBVSDJHvvRQHbgw

```
❯ docker run --rm busybox:stable df -h
Unable to find image 'busybox:stable' locally
stable: Pulling from library/busybox
4189ef966ca4: Pull complete
Digest: sha256:20142e89dab967c01765b0aea3be4cec3a5957cc330f061e5503ef6168ae6613
Status: Downloaded newer image for busybox:stable
Filesystem                Size      Used Available Use% Mounted on
overlay                  58.8G     46.6G      9.1G  84% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     3.9G         0      3.9G   0% /sys/fs/cgroup
shm                      64.0M         0     64.0M   0% /dev/shm
/dev/disk/by-label/data-volume
                         58.8G     46.6G      9.1G  84% /etc/resolv.conf
/dev/disk/by-label/data-volume
                         58.8G     46.6G      9.1G  84% /etc/hostname
/dev/disk/by-label/data-volume
                         58.8G     46.6G      9.1G  84% /etc/hosts
tmpfs                     3.9G         0      3.9G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                     3.9G         0      3.9G   0% /proc/scsi
tmpfs                     3.9G         0      3.9G   0% /sys/firmware

```

I'll try to get colima to bump the size up, thanks!

**Comment by rfay** [comment]
Oh I' so happy you're using latest ddev HEAD, thanks!

**Comment by joelpittet** [comment]
I will end up resizing the disk (because I wanted `100G`, but only have `60G` default), I have more memory to give it but I think `8G` is plenty. And I'll keep tabs on this https://github.com/abiosoft/colima/issues/398

As mentioned I think `max_packet_size` plays into this, or at least I'll explore that next, unless you'd like me to try anything else?

**Comment by rfay** [comment]
It looks to me like OOM kill (137), and memory will solve it. I don't think it has to do with the classic `max_packet_size` because we have that set so very high and because the import is right on the same machine, not even happening over network.

**Comment by joelpittet** [comment]
I was thinking that reducing `max_packet_size` (likely naive) would help throttle the memory to keep it at a reasonable amount and not exhaust it.

**Comment by joelpittet** [comment]
Thanks, I'll explore further when I run into it again.

**Comment by VladyslavSikailo** [comment]
faced with the same problem, changed memory for `colima` from 100 gb to 200 gb and this fixed the problem

**Comment by rfay** [comment]
If it's about memory... then it wasn't changing the filesystem from 100. It's about changing memory. You probably had 2GB allocated as memory and increased it to 6GB or something @VladyslavSikailo - but nobody has 100GB on their computer to allocate to colima memory.

**Comment by VladyslavSikailo** [comment]
yeah, that's true
changed RAM to 8gb
