### ISSUE TITLE
Can't use amd64 version of ddev on mac M1 (arm64)

### ISSUE THREAD

**Issue by kuhlware** [drud/ddev#4187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/kuhlware/ff1524088d6f7c45b889b015457dc564

### Current Behavior

I have the problem, that I can't start my ddev-projects with my new Macbook Pro M1 Max mit 64GB RAM, cause of nginx errors.

`Failed to start PROJECTNAME: ddev-router failed to become ready; debug with 'docker logs ddev-router'; logOutput=nginx config valid:OK  ddev nginx config not yet generated , err=container /ddev-router unhealthy: nginx config valid:OK  ddev nginx config not yet generated`

```
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc
```

I tried different stuff in my docker-compose.yml file with as example

    `platform: linux/amd64`

but nothing works.

### Expected Behavior

The ddev-projects starts as expected.

**Comment by rfay** [comment]
Please do not add platform statement anywhere, it won't work.

And `docker-compose.yml` is not supported by ddev.

Are you working with ddev?

Your gist from `ddev debug test` is not there any more, maybe you deleted it?

Anyway, please provide the output of `ddev debug test` as a gist on gist.github.com, and please don't add any extra configuration to the project you're working on... remove all that you've added.

**Comment by kuhlware** [comment]
Hi, I sent you the gist per mail cause of customer names etc.

I'm working with ddev, yes. I removed all the other stuff so it's like before my Macbook change yesterday :)

**Comment by rfay** [comment]
I see in your gist that you're running the amd64 version of ddev on an arm64 machine. Please don't do that. 

If you have copied your homebrew over from the old machine, you have to completely delete it and start over again. It's completely different on arm64.

 If you have installed ddev some other way, you need to delete it and reinstall, follow the instructions.

**Comment by kuhlware** [comment]
I uninstall homebrew & ddev and reinstall first homebrew and then ddev, but the error is the same. Any other ideas?

**Comment by kuhlware** [comment]
I uninstalled ddev again and installed it with the script from here: https://aureola.codes/de/blog/2021/wie-man-ddev-auf-apple-m1-installiert. Now there is the output:

```
ddev_macos-arm64.v1.21.1.tar.gz: OK
Download verified. Ready to place ddev and mkcert in your /usr/local/bin.
Attempting to unlink any homebrew-installed ddev with 'brew unlink ddev'
Installed ddev bash completions in /opt/homebrew/etc/bash_completion.d
zsh completion for ddev was not installed. You may manually install /tmp/ddev_zsh_completion.sh in your zsh-completions directory.
Running mkcert -install, which may request your sudo password.'.
Created a new local CA 💥
Sudo password:
The local CA is now installed in the system trust store! ⚡️
Warning: "certutil" is not available, so the CA can't be automatically installed in Firefox! ⚠️
Install "certutil" with "brew install nss" and re-run "mkcert -install" 👈

ddev is now installed. Run "ddev" and "ddev --version" to verify your installation and see usage.
```

So it should be now the arm64 version of ddev, right? But the error is still the same.

**Comment by rfay** [comment]
Your latest gist sent by email still has this:

> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

Perhaps it's because you already have some images cached from the previous runs. 

Please do a docker factory reset on your Docker Desktop setup.

Oh, I see you must have actually brought docker images and containers over from the old system somehow. Definitely do a docker factory reset. 

You're going to have trouble with lots of apps if you brought applications and their settings and data over from your old computer.

**Comment by kuhlware** [comment]
Okay that's it!!! I lost all of my setups & containers, but now it's working :) Thank you very much. 

In the next time I have to setup a lot of ddev-projects from beginning :D

**Comment by rfay** [comment]
All you lost is your databases, which you can bring from the other computer.
