### ISSUE TITLE
Audit documentation for consistency, accuracy, and flow

### ISSUE THREAD

**Issue by mattstein** [drud/ddev#4188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Despite being a helpful and detailed resource, the DDEV documentation could be more internally consistent, up to date, and at some times concise. Stronger documentation could reduce some support burden, help people get working or un-stuck faster, and make DDEV more of a pleasure to work with than it already is.

### Describe the solution you'd like

I’d like to suggest the following items and will tackle them myself as long as each seems reasonable:

1. In the spirit of the proposed [Code of Conduct](https://github.com/drud/ddev/pull/4186), draft a writing style guide that broadly encourages consistency of tone and convention.

    a. Describe an ideal tone for writing that’s ideal for DDEV and a natural fit for the code of conduct. (Welcoming, focused, warm, precise.)

    b. Describe the intended audience for the documentation that can be used to evaluate the appropriateness and accessibility of any writing.

    c. DDEV should appear in all caps in sentence form as long as it doesn’t reference the `ddev` command; retire “DDEV-Local” and “ddev”.

    d. Should avoid using “just” and “it’s easy” that subtly talk down to the reader and suggest anyone struggling is wrong, and instead use words like “straightforward” and offer reassurance by demonstration or illustration whenever possible.

2. Audit all documentation and implement suggestions from item 1 above.

3. Fix pedantic things across the board: use curly quotes, fix proper nouns (“Docker” not ”docker”, etc.), consistently capitalize headings, edit for brevity and clarity. Cross-link more liberally so readers can more easily land in the right place. Update `.spellcheckwordlist.txt` accordingly.

4. Rename the existing “Styleguide” page to “Brand Guide” and season accordingly.

5. Update installation instructions with a heading specifically for upgrading. (Easier to scan and link to, since upgrading is likely _more_ common than first-time installation.)

6. Split commands into organized subheadings for more efficient browsing. Emphasize—on that page or elsewhere—day-to-day usage and the most popular or expected commands.

7. Reduce redundant information that increases the risk of becoming stale, with a greater emphasis on links to canonical content.

8. Request related admin-level changes to things like the repository description. (Even disabling the unused [Packages section](https://share.cleanshot.com/3oyLup) and [Projects](https://github.com/drud/ddev/projects) feature—since every bit of cruft removed puts more emphasis on meaningful bits.)

9. Fix any 404s and bad links.

If these things are all agreeable, I can start a draft PR and get to work.

### Describe alternatives you've considered

I mean, I guess a series of videos? But I’m better at words on pages.

**Comment by rfay** [comment]
Awesome, looking forward to talking more about this. Great to have your brain working on it! 

I'm hoping to do a better response and also talk privately about paths forward still this week. Thanks!

**Comment by rfay** [comment]
This will be a paid adventure for @mattstein, hopefully the first adventure like this for several contributors. Those of you who are interested in taking on DDEV roles and getting paid something for it are welcome to discuss. We want to get more people involved in the manner that works for them.

**Comment by rfay** [comment]
How are we doing here? How close is this to obsolete? Awesome work, infinite backlog :)

**Comment by mattstein** [comment]
@rfay I think I’m actually at 90% of ∞, with updates to style, flow, and structure I’m pretty happy with—and for which there’s an accompanying style guide.

I still haven’t integrated [SmartyPants](https://daringfireball.net/projects/smartypants/) to handle quotes and general typography, or touched any of the underlying theme to fight tab inception. Both feel relevant to this effort.

We could close this if it’s bugging you! I can either file issues for the things in my head, or keep at it and submit random PRs that don’t reference this issue.

**Comment by rfay** [comment]
90% is mighty awesome! Please close this issue when it's no longer useful to you.

**Comment by mattstein** [comment]
With SmartyPants in the mix, I think it’s safe to consider this issue finished. I’ll tackle theme updates and future adventures elsewhere.

**Comment by rfay** [comment]
Congratulations, superb. And never-ending journey.

**Comment by bencroker** [comment]
Wow, amazing work!!

**Comment by chrisfromredfin** [comment]
Thank you Matt!!!
--
Christopher J. Wells (he/him/his)
Member / CTO
908-4-DRUPAL
***@***.***
www.redfinsolutions.com
