### ISSUE TITLE
Consider reworking dockerutil.ComposeCmd() to control stdout/stderr

### ISSUE THREAD

**Issue by rfay** [drud/ddev#419]
## What happened (or feature request):

When you use a command that is a wrapper on docker-compose, especially `ddev start`, it emits lots of underlying docker-compose info which is not helpful either to our users or to our test output. 

IMO it would be good to trip this output to what's actually useful to see in test output or what's useful to the user. We could do this with a bit of a rework of dockerutil.ComposeCmd() in order to capture that output instead of just letting it go. 

Some examples:

```
Stopping ddev-TestMainPkgWordpress-web ... 
Stopping ddev-TestMainPkgWordpress-dba ... 
Stopping ddev-TestMainPkgWordpress-db ... 
[2A[2K
Stopping ddev-TestMainPkgWordpress-dba ... [32mdone[0m
[2B[3A[2K
Stopping ddev-TestMainPkgWordpress-web ... [32mdone[0m
[3B[1A[2K
Stopping ddev-TestMainPkgWordpress-db ... [32mdone[0m
[1BStopping ddev-router ... 
[1A[2K
Stopping ddev-router ... [32mdone[0m
[1BRemoving ddev-router ... 
[1A[2K
Removing ddev-router ... [32mdone[0m
[1BNetwork ddev_default is external, skipping


The DDEV_HOSTNAME variable is not set. Defaulting to a blank string.
The DDEV_IMPORTDIR variable is not set. Defaulting to a blank string.
The DDEV_HOSTNAME variable is not set. Defaulting to a blank string.
The DDEV_IMPORTDIR variable is not set. Defaulting to a blank string.

```

## Related source links or issues:

**Comment by rickmanelius** [comment]
Seems like it would be useful for debugging.

**Comment by rfay** [comment]
This output is now controlled quite well and I don't think this is an issue any more. Rework of output was done when doing the json-logging-output issue.
