### ISSUE TITLE
/var/www/html/.ddev/.downloads/ doesn't appear in the web container when using mutagen

### ISSUE THREAD

**Issue by joelpittet** [drud/ddev#4193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

``` ITEM             VALUE
 DDEV version     vHEAD-619a212
 architecture     arm64
 db               drud/ddev-dbserver-mariadb-10.4:v1.20.0
 dba              phpmyadmin:5
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.20.0
 docker           20.10.11
 docker-compose   v2.10.1
 docker-platform  colima
 mutagen          0.15.1
 os               darwin
 router           drud/ddev-router:v1.20.0
 web              drud/ddev-webserver:20220826_path_adjusted_for_composer_root
```

### Expected Behavior

With mutagen and using this pull command
```
db_pull_command:
  command: |
    set -x   # You can enable bash debugging output by uncommenting
    set -eu -o pipefail
    # This just refreshes stale NFS if possible
    ls /var/www/html/.ddev >/dev/null
    cd /var/www/html
    drush -n @self.prod sql:dump > .ddev/.downloads/db.sql
    # DDEV expects db.sql.gz to import.
    gzip .ddev/.downloads/db.sql
  service: web
```
Which should work (has worked) as documented in the providers README.md:

> `db_pull_command`: A script that determines how ddev should pull a database. It's job is to create a gzipped database dump in /var/www/html/.ddev/.downloads/db.sql.gz.

I expect the `/var/www/html/.ddev/.downloads` to be available in the web container to store database dump files, yet it's not. It is on the host machine.

### Actual Behavior

Seems that it is ignored from `/var/www/html/.ddev` because of mutagen.

Resulting error is 
```
bash: line 6: .ddev/.downloads/db.sql: No such file or directory
```

### Anything else?

@rfay pointed out that it's available `/mnt/ddev_config` as a workaround.

**Comment by rfay** [comment]
BTW @joelpittet you can just remove .downloads from the mutagen.yml and take it over (remove #ddev-generated from the top)  to resolve this for yourself. I think that's what we should likely do to resolve this issue.

**Comment by joelpittet** [comment]
@rfay changing to `/mnt/ddev_config` yields:
`bash: line 4: .downloads/db.sql: Read-only file system`

**Comment by joelpittet** [comment]
Part of this PR https://github.com/drud/ddev/pull/4109
This commit:
https://github.com/drud/ddev/pull/4109/commits/12ec25d8bcd4736e536facd14658c043eee13d17
