### ISSUE TITLE
Optional DNS entries for containers

### ISSUE THREAD

**Issue by mfrieling** [drud/ddev#4207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The problem is that one specific hostname for unknown reasons can't be resolved inside the web container (but can on the WSL2 host and even in Windows Powershell). The host is serving an API which my site uses, but without access to the API my site is inoperable as the API also provides authentication etc.

This is a very isolated problem but a more common use case is that the API or whatever is running on a hostname is not yet publicly accessible and cannot be resolved by public DNS while the DDEV-hosted project must access it via a hostname and not an IP address, i. e. the API itself is still under development.

### Describe your solution

Provide a way to configure a list of DNS mappings which gets appended to the DDEV generated `/etc/hosts` file of the container(s) upon `ddev start`. This can either be an array for `config.*.yaml` in key-value format like

```yaml
additional_dns:
  x.x.x.x: "hostname1, hostname2"
  y.y.y.y: hostname
```

or a separate file `.ddev/hosts` which has the same format as `/etc/hosts` file and is appended to the DDEV generated `/etc/hosts` file inside the container after it has started.

**Comment by rfay** [comment]
DDEV isn't involved in name resolution, so web searches are called for on your environment.

Here are some things to do, in order:

1. Turn off your VPN and Firewall (and virus checker) temporarily
2. Change your system's DNS servers (either on Windows or inside WSL2) to a better DNS server, 1.1.1.1 (Cloudflare) often resolves this kind of problem

The bottom line though is to look at your system and google problems like this, as DDEV isn't involved in name resolution.

**Comment by rfay** [comment]
No response for 10 days, so closing, but happy to continue the conversation here or elsewhere.
