### ISSUE TITLE
yarn cacheFolder configuration breaks running yarn operations outside of ddev

### ISSUE THREAD

**Issue by sal-lochbaum** [drud/ddev#4215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

ddev 1.21.1
macOs 12.6
yarn stable (3.x)

### Expected Behavior

I have a project where I use yarn as "utility tool launcher" i.e. use it to start the project (includeing ddev), run storybook server import/export databases from remote server etcpp.

e.g. I use ` yarn start` to start ddev and start webpack dev server
Or I use `yarn run clearcache` to execute the command on the ddev web container to clear the typo3 cache

Then I call `yarn add somepackage` or other yarn package operations that succeed.

### Actual Behavior

After updating to ddev ~~1.20.1~~ v1.21.1 the behaviour changed.

When I run ``ddev start``, ddev adds a cacheFolder configuration to the .yarmrc.yml file pointing to a path that only exists in the docker container, but not on on the host (cacheFolder: /mnt/ddev-global-cache/yarn/my_project).

Subsequent yarn calls which operate on yarn packages (`yarn`, `yarn add x`, etc) fail with

> Internal Error: ENOENT: no such file or directory, mkdir '/mnt'

as the /mnt directory doesn't exist on my mac.

### Steps To Reproduce

➜  yarn set version stable
➤ YN0000: Retrieving https://repo.yarnpkg.com/3.2.3/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-3.2.3.cjs
➤ YN0000: Done in 0s 232ms

➜  yarn init
{
  name: 'foo',
  packageManager: 'yarn@3.2.3'
}

➜  yarn add webpack
...
➤ YN0000: Done with warnings in 1s 748ms

➜  ddev config
Creating a new ddev project config in the current directory (/tmp/foo) 
...
Configuration complete. You may now run 'ddev start'. 

➜ cat .yarnrc.yml 
yarnPath: .yarn/releases/yarn-3.2.3.cjs

➜ ddev start
Starting foo... 
...Project can be reached at https://foo.ddev.site https://127.0.0.1:53727 

➜ cat .yarnrc.yml
cacheFolder: /mnt/ddev-global-cache/yarn/foo-web

yarnPath: .yarn/releases/yarn-3.2.3.cjs

➜ yarn remove webpack
Internal Error: ENOENT: no such file or directory, mkdir '/mnt'
Error: ENOENT: no such file or directory, mkdir '/mnt'

### Anything else?

I really just need a way to block ddev from writing into the .yarnrc.yml file or change the path to something in .ddev?  

It's more of a nuisance currently as the change is easily undone and there probably are some workarounds like creating a /mnt dir or a post-start hook which removes the line again or something.

Thanks!

**Comment by rfay** [comment]
Could you please try DDEV v1.21.1? It had a major fix for yarn3 users... https://github.com/drud/ddev/releases/tag/v1.21.1

**Comment by sal-lochbaum** [comment]
Sorry, this happens with v1.21.1. I mistyped it above.

**Comment by rfay** [comment]
I imagine you have your .yarn folder linked into .ddev/homeadditions. You probably don't want to do that. DDEV won't touch any files in your home directory otherwise. 

DDEV does not change anything in your home directory unless you have some kind of symlink set up (DDEV doesn't change your code or configuration).

> ddev adds a cacheFolder configuration to the .yarmrc.yml

No, it doesn't - it doesn't change your yarmrc.yml on the host at all in any way.

**Comment by rfay** [comment]
Why don't you look at ~/.ddev/homeadditions and the project .ddev/hoomeadditions and remove that symlink...

**Comment by sal-lochbaum** [comment]
No there is nothing yarn related in either of those directories.

The .yarnrc.yml is only in the project root directory.
It's modified by the commands here: https://github.com/drud/ddev/blob/52566fe86b6b14f282188da12976efe80f352186/containers/ddev-webserver/ddev-webserver-base-scripts/start.sh#L83

**Comment by rfay** [comment]
Remember it's hidden, so you need to use `ls -la`

You're using yarn on the host side right? That uses your own yarn config on the host side.

**Comment by rfay** [comment]
If you would like to do a screenshare call/zoom/whatever to look at it we can do that.

**Comment by rfay** [comment]
I just did some checking to explore this. 

When DDEV does the `yarn config set cache-folder /mnt/ddev-global-cache/yarn/${HOSTNAME}` it affects the ~/.yarnrc inside the container, and puts these contents in it:

```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


cache-folder "/mnt/ddev-global-cache/yarn/d9-web"
```

It doesn't change the project contents at all, it only changes /home/<you>/.yarnrc *inside* the container, which is normally transient, and certainly not exposed on the host.  

I'm sure you know vastly more about. yarn than I do, you'll have to help me understand what's happening to your project, assuming it's the project that is being changed. DDEV certainly doesn't change a file named .yarnrc.yml... where is that?

Would you be willing to put up a simple demo repo that shows the behavior you're seeing? Just create a simple repo that demonstrates the problem you're seeing and give instructions on how to generate the problem, and push it up to github. Thanks!

**Comment by rfay** [comment]
No response after several days, but I'd love to review this with you and sort it out. Closing, but happy to continue the conversation here or elsewhere. I think if you can provide a demonstration repo, or if we can do a screenshare we could sort it out pretty easily.

**Comment by hanoii** [comment]
I just saw this happening on a coworkers machine, not on mine, and the issue is most surely yarn3 where it now users a .yarnrc.yaml local to the project, I am actually configuring it myselef and [that command](https://github.com/drud/ddev/issues/4215#issuecomment-1252063785) is likely the culprit

**Comment by hanoii** [comment]
I will see why it's not happening on my setup though that also uses yarn3 which now makes a binary being added to the repo...

They are recommending a very git anti-pattern in my opinion: https://yarnpkg.com/features/zero-installs but that's for another discussion :)

**Comment by hanoii** [comment]
And this is a problem because it may affects deploys that needs to use yarnrc.yml but obviously not any ddev reference

**Comment by hanoii** [comment]
I know why it's not running for me, I probably have the yarn v1 caches in there as I was using yarn v1 until recently.

**Comment by hanoii** [comment]
If you run `yarn config set cacheFolder /mnt/ddev-global-cache/yarn/${HOSTNAME} -H` (notice the `-H`)  it adds it to the home's .yarnrc.yml file.. I assume de second `yarn config set` with `cacheFolder` was for newer versions of yarn, maybe adding `-H` there?

**Comment by hanoii** [comment]
Is there a way to take over that file (`start.sh`) from ddev to avoid that in the meantime?

**Comment by rfay** [comment]
Yes, you can install your own start.sh using a custom Dockerfile.

But in the meantime, can you please flesh out what's happening here and provide a simple example to demonstrate it?

**Comment by hanoii** [comment]
This is driving me crazy, I am sure this happened and I reproduced it but not consistently.

Question: 

`yarn config set cache-folder /mnt/ddev-global-cache/yarn/${HOSTNAME} || yarn config set cacheFolder /mnt/ddev-global-cache/yarn/${HOSTNAME} || true` form your start.sh

What could make the first `yarn config set` that you have to try the second one?

Also, if I were to provide a `start.sh` should i be copying it to /start.sh on my Dockerfile?

**Comment by rfay** [comment]
The first yarn config tries it the yarn1 way. It fails on yarn 3, so the second config tries it the yarn3 way. They made a serious breaking change that there is no way around.

Yes, if you change start.sh, you would copy it to /

Thanks for chasing this! If we can get a repro case I'm sure we can make it work for everybody.

**Comment by hanoii** [comment]
I am pretty sure the solution is adding `-H` on the yarn3 command, even the yarn1 command accepts `-H` but I can't seem to reproduce it.

**Comment by rfay** [comment]
You are awesome, thanks!

**Comment by rfay** [comment]
Could you please give repro instructions for your https://github.com/hanoii/ddev-yarn-issue-4215 ? What do I need to do to demonstrate? It starts fine (mutagen off).

**Comment by hanoii** [comment]
@rfay start it, that's all. `git status` should show the modified `.yarnrc.yml`.

**Comment by rfay** [comment]
Ah, OK it does, thanks. Let's go to discord.

**Comment by rfay** [comment]
This can be tested with the artifacts in https://github.com/drud/ddev/pull/4234#issuecomment-1261144771

Would appreciate you doing the manual testing and review @hanoii @sal-lochbaum, followup over there unless it needs to be here.
