### ISSUE TITLE
Drupal 8/9 : BadRequestHttpException: Invalid contextual ID specified

### ISSUE THREAD

**Issue by Mit-suko** [drud/ddev#4223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

Hello,

I would share this drupal issue because many comments are related to ddev so it seems involved :
BadRequestHttpException: Invalid contextual ID specified
https://www.drupal.org/project/drupal/issues/3010562

Comment with ddev :
https://www.drupal.org/project/drupal/issues/3010562#comment-14505975
https://www.drupal.org/project/drupal/issues/3010562#comment-14590543
https://www.drupal.org/project/drupal/issues/3010562#comment-14595956
https://www.drupal.org/project/drupal/issues/3010562#comment-14692820

> We are running a Drupal 8.6.2 multisite and users have been reporting over the last few weeks that the the contextual links are disappearing on them. When I investigate, the links appear for me as admin, but do not for the user.
> 
> I am getting this error in the WatchDogs:
> 
> Location http://site.com/contextual/render
> Message Symfony\Component\HttpKernel\Exception\BadRequestHttpException: Invalid contextual ID specified. in Drupal\contextual\ContextualController->render() (line 76 of /core/modules/contextual/src/ContextualController.php).
> Severity Error
> 
> **Rebuilding the Drupal cache fixes the issue but problem comes back each time cache render expires** 

Maybe the $settings['hash_salt'] in settings.ddev.php play a role ...? 

### Expected Behavior

Contextual links are displayed if user has perms to see them.

### Actual Behavior

Contextual links are not visible.

**Comment by rfay** [comment]
If you'd like to pursue this, why don't you change the hash_salt? 

Just change it in settings.php below the inclusion of settings.ddev.php.

It would surprise me if this had anything to do with ddev, but if you want to explore it, please do. DDEV is just a webserver doing normal webserving things...

**Comment by Mit-suko** [comment]
Thank you for your answer.

I know, it's weird !
Changing the hash_salt does nothing when the problem occurs. 
As if there was a cache system somewhere.

I just wanted to share this issue with ddev users, just in case...

**Comment by rfay** [comment]
I imagine that the correlation between mentions of ddev and this issue is that people are using ddev a lot, I don't know. I'm very happy for you to explore this, but it really seems likely that it's all about Drupal and has nothing to do with ddev. I'm going to close for now, but super interested in what you think as you explore it, and happy to reopen it or discuss here or elsewhere at any time.
