### ISSUE TITLE
Support flags from the ddev wrappers being passed into their in-container equivalents

### ISSUE THREAD

**Issue by hanoii** [drud/ddev#4225]
### Expected Behavior

We should probably pass all arguments to the command

The goal would be so that that what you run from the host is exactly the same as when you run it from the container.

i.e.

`ddev platform --help` should run `platform --help` in the container.

### Actual Behavior

We get the ddev help for the command.

**Comment by hanoii** [comment]
I've been bitten with this again, I wonder if you'd consider something like this:

https://github.com/spf13/cobra/issues/1328

It's basically using `DisableFlagParsing`, then hiding the `-h` as apparently it's not automatically hidden.

This obviously renders https://ddev.readthedocs.io/en/latest/users/extend/custom-commands/#flags-annotation moot. I do wonder if that's a bad thing. I've search on my commands global `~/.ddev` directory to see if there were any out of the box commands that was using this and I didn't find any.

**Comment by rfay** [comment]
That sounds like a good idea. It's definitely annoying. `ddev composer` is affected by it, and all the wrappers. I'd love to see a good solution.

**Comment by gilbertsoft** [comment]
I'm wondering, did you ever test something like this?

`ddev -- platform --help` or `ddev platform -- --help`

This is the default behavior for most frameworks to circumvent the problem you have!

**Comment by hanoii** [comment]
@gilbertsoft I did yes.

`ddev -- platform --help` obviously doesn't work as `platform` never even gets `ddev`

`ddev platform -- --help` for some reason this doesn't work either. `--help` is not what `platform` receives in the container.

**Comment by hanoii** [comment]
For `composer` though it does seem to work, `ddev composer -- --help` works.. I wonder why that is.

**Comment by gilbertsoft** [comment]
`platform` is a custom command I guess? And if yes, how does it look like?

**Comment by hanoii** [comment]
https://github.com/platformsh/ddev-platformsh/tree/main/commands/web

**Comment by hanoii** [comment]
The problem is that cobra handles --help by default and there's no way to remove it, apparently.

@gilbertsoft I am still curious why removing flags from custom command would break anything other than the "reporting" or validation of the flags

**Comment by rfay** [comment]
Cobra's newest update (today) seems to fiddle with some of this class of problem, https://github.com/spf13/cobra/releases/tag/v1.6.0

**Comment by gilbertsoft** [comment]
> The problem is that cobra handles `--help` by default and there's no way to remove it, apparently.
> 
> @gilbertsoft I am still curious why removing flags from custom command would break anything other than the "reporting" or validation of the flags

Well, you break the help output. Which means I would have to implement it in various custom commands by myself. Many open source repos are affected and nobody pays me to fix it.

IIRC I've already a solution in some of my stashes for further custom commands optimizations, will have a look a.s.a.p.
