### ISSUE TITLE
Description about possible composer version config is insufficient

### ISSUE THREAD

**Issue by eliashaeussler** [drud/ddev#4227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

The `config.yaml` contains the following description for the `composer_version` config:

```
# composer_version: "2"
# You can set it to "" or "2" (default) for Composer v2 or "1" for Composer v1
# to use the latest major version available at the time your container is built.
# It is also possible to select a minor version for example "2.2" which will
# install the latest release of that branch. Alternatively, an explicit Composer
# version may be specified, for example "1.0.22". Finally, it is also possible
# to use one of the key words "stable", "preview" or "snapshot" see Composer
# documentation.
# To reinstall Composer after the image was built, run "ddev debug refresh".
```

This assumes that one can configure any Composer minor version, such as

```yaml
composer_version: "2.3"
# or
composer_version: "2.2"
# or
composer_version: "2.1"
# or
composer_version: "2.0"
```

and the latest patch release within the specified version range will be used.

### Actual Behavior

However, the only working minor version is `2.2`. This is because the 2.2 branch is added as additional version channel in Composer itself, see https://github.com/composer/composer/blob/2.4.2/src/Composer/SelfUpdate/Versions.php#L31. Specifying another minor version will result in DDEV installing the latest available Composer version, currently 2.4.2.

My suggestion is to

- either add support for specifying Composer minor versions
- or correct the information provided in `config.yaml` about possible config values for the `composer_version` config, supporting only the officially supported Composer channels (as per https://github.com/composer/composer/blob/2.4.2/src/Composer/SelfUpdate/Versions.php#L31)

Side note: This behavior was originally introduced with #3812.

### Steps To Reproduce

1. Configure a DDEV project with `composer_version: "2.3"`
2. Run `ddev debug refresh`
3. Run `ddev composer -- --version`
4. Compare the printed version with the configured version, the minor version branches should not match.

**Comment by rfay** [comment]
Interested in taking a look @gilbertsoft ?

**Comment by rfay** [comment]
Hmm, DDEV has always supported patch versions (like "2.2.18") for composer_version.

And when they introduced channels like "2.2", @gilbertsoft did #3812 for that. 

But I note that there still is no 2.3 or 2.4 channel:

```
rfay@d9-web:/var/www/html$ composer --version
Composer version 2.4.2 2022-09-14 16:11:15
rfay@d9-web:/var/www/html$ composer self-update -h
Description:
  Updates composer.phar to the latest version

Usage:
  self-update [options] [--] [<version>]
  selfupdate

Arguments:
  version                        The version to update to

Options:
  -r, --rollback                 Revert to an older installation of composer
      --clean-backups            Delete old backups during an update. This makes the current version of composer the only backup available after the update
      --no-progress              Do not output download progress.
      --update-keys              Prompt user for a key update
      --stable                   Force an update to the stable channel
      --preview                  Force an update to the preview channel
      --snapshot                 Force an update to the snapshot channel
      --1                        Force an update to the stable channel, but only use 1.x versions
      --2                        Force an update to the stable channel, but only use 2.x versions
      --2.2                      Force an update to the stable channel, but only use 2.2.x LTS versions
      --set-channel-only         Only store the channel as the default one and then exit
```

I guess @gilbertsoft was assuming they would continue the tradition. Perhaps we should just remove the "2.2" option introduced in #3812 and update the docs accordingly.

**Comment by eliashaeussler** [comment]
I guess they just added the `2.2` channel since this is the LTS version, so people can enforce updates within LTS version range only. Updating the docs would be enough, I'd say. That way the `composer_version` config reflects all available Composer channels as well as explicit versions.

**Comment by rfay** [comment]
Would you like to do a PR? For the docs, you can just click the little pencil in the upper right of the docs page. For the config.yaml, you just do a PR on https://github.com/drud/ddev/blob/38f7473b6903c4f6ed53019184a2d75a6cca8580/pkg/ddevapp/templates.go#L54-L62 - can be done right in the browser if you want.

**Comment by eliashaeussler** [comment]
Sure 🙂 Done → #4228
