### ISSUE TITLE
Allow hooks or other interventions earlier in the start and build process

### ISSUE THREAD

**Issue by hanoii** [drud/ddev#4233]
After working on 
* #4215 something else came to mind, which it's probably very custom but I wonder what your thoughts are.

`start.sh` does a lot of cool things, cool things that I may want to change or do different, or do things in between.

On a project I have `pm2` that serves a node app. I added `pm2` as an extra daemon. And `pm2` is being installed globally from a `Dockerfile`.

The first time the project is spun, it fails because there's no dependencies installed. I added `yarn install` to `post-start` hook but that happens after `start.sh` which starts `supervisord` which starts `pm2`. While that's fine, I now learned I can add my own start.sh that `yarn install` before the supervisor is run.

I am ok doing this but I wonder if we can add flexibility here. It may not be worth it, but taking over start.sh will force me to have it updated on newer versions if more things were added. I could probably do some `sed` that might be more update aware.

One thing I thought of is having something like a `/start.d/` directory where you can add things like `90-supervisor.sh`, `50-node-cache.sh` and something like this where the current bits of what start.sh does can go into sub files and `start.sh` executes those in order. In this scenario I might decide to take over a single snippet of `start.sh` or add something I want to do somewhere else by adding a `51-user.sh` to `/start.d`.

This could even be something an addon can add to it. 

Just an idea.

**Comment by hanoii** [comment]
@rfay yes, that's what I am doing,, I mentioned that in the first comment but maybe it was clear. `web_extra_daemons` adds a supervisord entry, so this happens before `post-start` hook, so the initial `yarn install` happens after the daemon started which I then have to manually restart it.

**Comment by rfay** [comment]
Thanks, sorry I missed it. 

There's a huge set of famous docker images that I can't quite remember right now that provide extra start directories like this. It's a reasonable approach. Of course, added possible complexity, there's always that tradeoff between potential complexity and expert usability.

**Comment by rfay** [comment]
Conversations from https://discord.com/channels/664580571770388500/1024698117246959756/1024708650054471721 and forward:

* A hook that would fire before supervisord starts the main services would be amazing
* A build-type hook that could do things that didn't require the repo/code would also be amazing, although we already have Dockerfile.* for that. 
* All of this relates very much to https://github.com/platformsh/ddev-platformsh plugin, because it has the problem of "build" hooks, which happen once at image build time... but there the code is in the image. 
* It's possible that in the future we might actually *want* a run mode like platform has, where the code is bundled into the image.

**Comment by rfay** [comment]
Needed over in 
* https://github.com/drud/ddev-platformsh/issues/89

**Comment by gilzow** [comment]
I've been following this thread and wondering if something like this could help with the platformsh addon.

**Comment by rfay** [comment]
Some bitnami images have 

* Files in /docker-entrypoint-initdb.d will only execute on the first container start.
* Files in /docker-entrypoint-startdb.d will execute on every container start.

See https://github.com/bitnami/containers/tree/main/bitnami/mysql#configuration

(Note that while it would be great to actually use bitnami images, they still publish only amd64 images)

**Comment by rfay** [comment]
@hanoii would you share what you did with start.sh to implement this? Working on it now and would love to benefit from your experience.

**Comment by rfay** [comment]
An interesting factoid here is that environment variables set in the startup (like start.sh) do not then show up in a bash environment, so we probably have to do things twice, once in the start.sh and also as we currently do, in Dockerfile (if not related to code) or in homeadditons .bashrc.d

**Comment by hanoii** [comment]
> @hanoii would you share what you did with start.sh to implement this? Working on it now and would love to benefit from your experience.

@rfay I don't think I ended up implementing any particular method, I simply, in the meantime, overrode start.sh until yarn issue got into a newer version. I think everything laid out here is what I thought about at the time.
