### ISSUE TITLE
XDEBUG not working in WSL2 environment with phpstorm on windows

### ISSUE THREAD

**Issue by mvinaj** [drud/ddev#4242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

```
DDEV version:  ITEM             VALUE
 DDEV version     v1.21.1
 architecture     amd64
 db               drud/ddev-dbserver-mariadb-10.4:v1.20.0
 dba              phpmyadmin:5
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.20.0
 docker           20.10.18
 docker-compose   v2.9.0
 mutagen          0.15.1
 os               linux
 router           drud/ddev-router:v1.20.0
 web              drud/ddev-webserver:20220808_yarn_crash
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=false
omit-containers=[]
mutagen-enabled=false
nfs-mount-enabled=false
router-bind-all-interfaces=false
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
auto-restart-containers=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=
use-docker-compose-from-path=false
no-bind-mounts=false

======= DOCKER info =========
docker location: -rwxr-xr-x 1 root root 50718336 Sep  9 01:09 /usr/bin/docker
docker version:
Client: Docker Engine - Community
 Version:           20.10.18
 API version:       1.41
 Go version:        go1.18.6
 Git commit:        b40c2f6
 Built:             Thu Sep  8 23:11:45 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.18
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.6
  Git commit:       e42327a
  Built:            Thu Sep  8 23:09:37 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
DOCKER_DEFAULT_PLATFORM=notset
```

### Expected Behavior

xdebug works out of the box If I start my ddev project and activate xdebug. 

### Actual Behavior

i get a error 

ddev logs show : 
 WARNING: [pool www] child 2706 said into stderr: "NOTICE: PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-("

in the container:

PING host.docker.internal (172.17.0.1) 56(84) bytes of data.

Trying 172.17.0.1...
telnet: Unable to connect to remote host: Connection refused

/etc/hosts

172.17.0.1 host.docker.internal

### Steps To Reproduce

docker running in WSL
phpstorm on windows
ddev  xdebug on
enable lisener in phpstorm

### Anything else?

![image](https://user-images.githubusercontent.com/96424441/193299715-117fa7bd-ace9-47d0-af5f-add65173ed73.png)

**Comment by rfay** [comment]
Hi @mvinaj - 

1. Are you running Docker Desktop, or do you have docker-ce installed in WSL2?
2. Where are you running PhpStorm? On Windows or inside WSL2?
3. Have you enabled PhpStorm's listen button? You'll certainly get this if you haven't

Could you please go more carefully through the [troubleshooting steps](https://ddev.readthedocs.io/en/latest/users/debugging-profiling/step-debugging/#troubleshooting-xdebug)? For example, you should have been doing `telnet host.docker.internal 9003`, not just `telnet host.docker.internal`.

**Comment by mvinaj** [comment]
Hi @rfay

1. I have docker-ce installed in wsl
2. Phpstorm is running on windows
3 yes he is enabled

Could you please go more carefully through the troubleshooting steps?
I tried:
-changed the Port to 11101
- checked the  php info
- Set to ipv4

telnet host.docker.internal 9003, not just telnet host.docker.internal:

Iam sorry i missed to copy the full command

**Comment by rfay** [comment]
Please don't change the port. Please remove any custom configuration. 

I imagine your problem is 
* https://github.com/drud/ddev/issues/3772
You'll see there that the way DDEV finds out host.docker.internal doesn't work for xdebug with docker-ce installed inside WSL2. 

The solution there may work for you, https://github.com/drud/ddev/issues/3772#issuecomment-1113972125

**Comment by rfay** [comment]
The temporary solution to this problem is in 
* https://github.com/drud/ddev/issues/3772#issuecomment-1266990171

Closing this in favor of the other issue. Please let me know how the solution works for you.

**Comment by mvinaj** [comment]
@rfay the solution didnt work for me still the same erros

**Comment by rfay** [comment]
If it's still showing "host.docker.internal" in the error, then you didn't set up the php config with the proper IP address. 

Please reply in the open issue, and say exactly what you did and exactly what the results were. You can say that you're coming from this issue. But note that if it still is trying to connect to host.docker.internal, I don't think you changed the php config properly.

**Comment by mvinaj** [comment]
if it's still showing "host.docker.internal": "NOTICE: PHP message: Xdebug: [Step Debug] Time-out connecting to debugging client, waited: 200 ms. Tried: 172.20.16.1:9003 (through xdebug.client_host/xdebug.client_port) :-("

please reply in the open issue, and say exactly what you did and exactly: i will 

Thanks for all your help

**Comment by rfay** [comment]
I'd be happy to do a screenshare with you to see if we can sort this out. I'm in US MT (UTC-6). Let me know what would be a good time for you.

In the meantime, please carefully go through the [troubleshooting steps](https://ddev.readthedocs.io/en/latest/users/debugging-profiling/step-debugging/#troubleshooting-xdebug) using the new IP address. But I'm surprised to see an IP like 172.20.16 - that's what you found in your WSL2 distro's /etc/resolv.conf? Maybe you can paste the /etc/resolv.conf here.  (That looks like what you might find inside the container, not in the WSL2 distro)

**Comment by mvinaj** [comment]
/etc/resolv.conf:
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 172.20.112.1

in 
/etc/resolv.conf with ddev ssh
nameserver 127.0.0.11
options: ndots:0

**Comment by rfay** [comment]
Yes, but in your testing you were not using `172.20.112.1`, you were using `172.20.16.1`, please try it with the value from your /etc/resolv.conf, which is `172.20.16.1` - put that in your .ddev/php/xdebug.ini and `ddev restart`:

```
xdebug.client_host=172.20.112.1
```

**Comment by rfay** [comment]
And, of course, try the [troubleshooting steps](https://ddev.readthedocs.io/en/latest/users/debugging-profiling/step-debugging/#troubleshooting-xdebug) in the doc, using `172.20.112.1` instead of `host.docker.internal`

**Comment by mvinaj** [comment]
Yes, but in your testing you were not using 172.20.112.1, you were using 172.20.16.1:  i think i need to disbale the automatic  generation of this file.

loading the .ini

Using custom PHP configuration: [/home/*/*/.ddev/php/xdebug.ini]

ddev logs:
[07-Oct-2022 13:08:50] WARNING: [pool www] child 2700 said into stderr: "NOTICE: PHP message: Xdebug: [Step Debug] Time-out connecting to debugging client, waited: 200 ms. Tried: 172.20.112.1:9003 (through xdebug.client_host/xdebug.client_port) :-("

in the container:

telnet 172.20.112.1 9003
Trying 172.20.112.1...
telnet: Unable to connect to remote host: Connection timed out

**Comment by rfay** [comment]
Please go through the troubleshooting steps. Have you enabled listen in PhpStorm? Please do it step by step. And please make sure you have disabled your firewall/VPN/Virus checker.

**Comment by rfay** [comment]
As I said above, I'm happy to do a screenshare call with you to sort this out. WSL2 is complicated in terms of networking, and different situations may result in different learning.

**Comment by mvinaj** [comment]
i think its a good idea to do a screenshare. iam from germany so we only need to find the right time

**Comment by rfay** [comment]
Hi @mvinaj - I can do today (Tuesday) between now (2:17pm your time) and 4pm your time, at 4:30pm your time, or tomorrow (Wed) between 3pm and 5pm your time. Let me know. It would be easier to schedule this more interactively in [DDEV discord](https://discord.gg/hCZFfAMc5k)

**Comment by rfay** [comment]
Thanks for taking the time to look at this today. It seems that your employer has locked down your computer in a way that WSL2 can't make a connection to Windows (where you have PhpStorm running).

Our ideas for workarounds for you:

* Talk to your IT department and get them to loosen things up
* Run the Linux version of PhpStorm inside WSL2, as described in https://ddev.readthedocs.io/en/latest/users/topics/phpstorm/#phpstorm-inside-wsl2-in-linux
* Try vscode instead

Your IT department also seems to have DNS rebinding prohibited, which is why you have to edit the windows hosts file. This would probably also be resolved by running your browser inside wsl2. https://ddev.readthedocs.io/en/latest/users/basics/troubleshooting/#dns-rebinding-prohibited

Hoping something works! Closing this for now, but happy to follow up any time.

**Comment by rfay** [comment]
I'm glad you got it solved. Firewall is the first thing on the troubleshooting list :) Some companies just make it too hard, don't they.

**Comment by ChristianAdamski** [comment]
Just for the log: ran into the same issue. Firewall setting solved it. Thanks @mvinaj

**Comment by funder7** [comment]
Hi guys, thanks for pointing me in the right direction... I had xdebug working correctly with phpStorm stable, and suddenly it didn't work once I switched to the EAP version. 

FYI I'm using `xdebug.remote_host = host.docker.internal` (xDebug 2.9.8), maybe you already now that, but just in case.. cheers!

**Comment by rfay** [comment]
@funder7 If you're using DDEV you do *not* have to do any configuration like `xdebug.remote_host = host.docker.internal`. However, if you're using DDEV you must be using a very ancient PHP version (7.1 and earlier) to be using xdebug 2. Regardless, DDEV does all that for you.

**Comment by funder7** [comment]
Hi @rfay, I'm not using DDEV actually, that's why I'm using that setting!
This project I'm working on uses php 7.4, xDebug 2.9.8 was the last version suggested in the [compatibility table](https://xdebug.org/docs/compat#f1). 
You're right though, I'd be supposed to upgrade @ v3.1, but this project is reaching it's EOL soon, and it will be migrated to php 8.x, we'll address this as well during the upgrade. Cheers

**Comment by rfay** [comment]
Yes, please comment in appropriate places. Otherwise you just create confusion. Commenting in unrelated repositories with out-of-date suggestions is not helpful.

**Comment by maciejsamotyj** [comment]
check this ini xdebug configuration. It works for me:
`
[Xdebug]
zend_extension=xdebug.so
xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.client_host=host.docker.internal

;# 9003 is now the default (set this for old PhpStorm settings).
xdebug.client_port=9000
`

source:
https://stackoverflow.com/questions/64776338/xdebug-3-the-setting-xdebug-remote-has-been-renamed-see-the-upgrading-g

**Comment by rfay** [comment]
Your problem has nothing to do with this issue; you seem to be using an IDE which is listening on port 9000 only. Current PhpStorm versions listen on 9000 and 9003.
