### ISSUE TITLE
Error in `web` container on startup in Ubuntu Live session: failed to create symbolic link '/home/kubuntu/.nvm': Permission denied

### ISSUE THREAD

**Issue by MurzNN** [drud/ddev#4243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/MurzNN/fcdc24a2d65bf9729f65d130855d60da

### Expected Behavior

I've got a problem with starting the `web` container on clean Ubuntu 22.04 image, with this output in the logs:
```
+ phpenmod assert
+ ls /var/www/html
+ sudo mkdir -p /mnt/ddev-global-cache/terminus/cache
+ sudo mkdir -p /mnt/ddev-global-cache/bashhistory/drupal-web /mnt/ddev-global-cache/mysqlhistory/drupal-web /mnt/ddev-global-cache/nvm_dir/drupal-web /mnt/ddev-global-cache/npm/drupal-web /mnt/ddev-global-cache/yarn/drupal-web
++ id -u
++ id -g
+ sudo chown -R 999:999 /mnt/ddev-global-cache/ /var/lib/php
+ yarn config set cache-folder /mnt/ddev-global-cache/yarn/drupal-web
Error: ENOTDIR: not a directory, open '/dev/null/.config/yarn'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at /usr/lib/node_modules/yarn/lib/cli.js:97395:58
    at Array.map (<anonymous>)
    at parseRcPaths (/usr/lib/node_modules/yarn/lib/cli.js:97393:78)
    at Object.findRc (/usr/lib/node_modules/yarn/lib/cli.js:97407:10)
    at getRcConfigForCwd (/usr/lib/node_modules/yarn/lib/cli.js:56965:74)
    at /usr/lib/node_modules/yarn/lib/cli.js:88756:56
    at Generator.next (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)
+ yarn config set cacheFolder /mnt/ddev-global-cache/yarn/drupal-web
Error: ENOTDIR: not a directory, open '/dev/null/.config/yarn'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at /usr/lib/node_modules/yarn/lib/cli.js:97395:58
    at Array.map (<anonymous>)
    at parseRcPaths (/usr/lib/node_modules/yarn/lib/cli.js:97393:78)
    at Object.findRc (/usr/lib/node_modules/yarn/lib/cli.js:97407:10)
    at getRcConfigForCwd (/usr/lib/node_modules/yarn/lib/cli.js:56965:74)
    at /usr/lib/node_modules/yarn/lib/cli.js:88756:56
    at Generator.next (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)
+ true
+ npm config set cache /mnt/ddev-global-cache/npm/drupal-web
 
+ true
+ ln -sf /mnt/ddev-global-cache/nvm_dir/drupal-web /home/kubuntu/.nvm
ln: failed to create symbolic link '/home/kubuntu/.nvm': Permission denied
```

### Actual Behavior

I guess it should start normally.

### Steps To Reproduce

1. Get a fresh Ubuntu 22.04 image, even Live USB is ok.
2. Install docker and ddev there
3. Create a Drupal project using Docker via commands like:
```
ddev config --docroot web --project-name drupal --project-type drupal9 --create-docroot
```
4. Start the `ddev`:
```
ddev start
```
5. See the error:
```
$ ddev start
Starting drupal... 
Unable to determine host.docker.internal - no gateway 
Network ddev-drupal_default  Created 
Container ddev-drupal-db  Started 
Container ddev-drupal-web  Started 
Container ddev-drupal-dba  Started 
Failed waiting for web/db containers to become ready: web container failed: log=phpstatus: FAILED /var/www/html: OK mailhog: FAILED , err=container /ddev-drupal-web unhealthy: phpstatus: FAILED /var/www/html: OK mailhog: FAILED  
Container ddev-router  Running 
Failed to start drupal: container(s) failed to become healthy before their configured timeout or in 120 seconds. This may be just a problem with the healthcheck and not a functional problem. (container 'web' exited, please use 'ddev logs -s web' to find out why it failed) 
```

**Comment by MurzNN** [comment]
If I install the system to the permanent storage, all works well. But on the Live session ("Try Ubuntu" / "Try Kubuntu" button in the installer) - I always got this error.

Seems the problem is related to the mount type of the system root partition
```
/cow on / type overlay (rw,relatime,lowerdir=/filesystem.squashfs,upperdir=/cow/upper,workdir=/cow/work,xino=off)
```
It is mounted as overlayfs. So maybe we can somehow adapt the DDEV scripts to work with this type of the mount?

**Comment by pt1602** [comment]
I have the same issue with an shopware 6 project and get the following error:

`+ ln -sf /mnt/ddev-global-cache/nvm_dir/our-project /usr/local/nvm
ln: failed to create symbolic link '/usr/local/nvm/esco-web': Permission denied`

**Comment by rfay** [comment]
Closing this as there hasn't been any followup from the original poster.

For @MurzNN, as stated in Discord, it will probably work with no_bind_mounts, `ddev config global --no-bind-mounts=true`

**Comment by MurzNN** [comment]
This bug is active for me on v1.21.3, also checked now on v1.21.2 - on there it exists too :(

**Comment by rfay** [comment]
I should note that while I'm happy to continue the conversation about this, Ubuntu Live is not something that Docker supports or ever intended to support, and the same goes for DDEV. It's not going to be a robust place for people to build a local development environment. There are many ways to build a robust DDEV environment. So many. Including Gitpod, which requires none of this...

**Comment by MurzNN** [comment]
> I immediately ran out of disk space. 

The live image uses RAM as the disk space, so just give about 12GB of RAM to the Virtual Machine with it, and here are the commands to install docker and ddev using one-liners: https://korepov.pro/infobase/vs-code/23#quick-config

**Comment by rfay** [comment]
Most people will never be able to give 12GB of RAM to a VM, and 12GB of disk is not normally enough to support more than one small project. But thanks for explaining why I ran out of disk!

**Comment by rfay** [comment]
I've been able to recreate the /dev/null/yarn/.berry failure on WSL2 with buildkite-agent setup and username. Reopening and will try to solve this particular variant.

**Comment by rfay** [comment]
On the test runner I was studying, the local user ID was 999, and DDEV tries to set the id inside the container to the same as the host. And it fails, because in the ddev-webserver, uid 999 is already taken by the user blackfire. So the proper user doesn't get created at all. I was able to fix the test runner by just changing to another uid (1023). But there are a couple of problems here. 

1. This statement doesn't work right, because `cd` lands the pwd on `/dev/null` because no user was created. https://github.com/drud/ddev/blob/a61a8935ee780acfa1846c1516696313adc0bad9/containers/ddev-webserver/ddev-webserver-base-scripts/start.sh#L88
2. We should just fail if we can't create the user in the first place probably, or try another UID. This problem is in https://github.com/drud/ddev/blob/bbcf9c1c9d8dd1fc29fb7b6ee890c1424ea2ba7f/pkg/ddevapp/config.go#L975 - we seem to continue processing even though it won't work out.

**Comment by rfay** [comment]
It turns out the blackfire user (uid 999) has this:
```
blackfire:x:999:999::/dev/null:/bin/false
```

So it has /dev/null for the homedir, which really doesn't work out.

**Comment by rfay** [comment]
And sure enough, the Ubuntu Live user "ubuntu" is also uid 999

**Comment by rfay** [comment]
Your Ubuntu live now works out of the box with no changes required (`--no-bind-mounts` is not required). 

But on my system with 11G of memory allocated to the machine in Virtualbox, that gives our filesystem 5.5GB, and just installing base drupal9 means that the disk is already 85% full

Please test with the artifacts at https://github.com/drud/ddev/pull/4346#issuecomment-1293929127

**Comment by rfay** [comment]
You can now test with `brew unlink ddev && brew install --HEAD--fetch-head ddev` if you use homebrew, or get the binaries from https://github.com/drud/ddev/actions/runs/3364639330
