### ISSUE TITLE
ddev issue template: Put diagnostic information inline into issues and hide under "details" collapsed block

### ISSUE THREAD

**Issue by MurzNN** [drud/ddev#4244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When reporting an issue with ddev, I need to create a gist and paste link to it.

### Describe your solution

Instead will be much easier to paste the full text into the issue creation form, and the issue template will hide (collapse) this text under the `<details>` block. Here is an example of this: https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab

**Comment by rfay** [comment]
I'm OK with it. Do you want to do a PR?

**Comment by MurzNN** [comment]
I still can't find the way how to insert wrappers to form elements in a template form :(
