### ISSUE TITLE
Since a few weeks the mutagen sync process takes a long time (~14 minutes vs. 1-2 minutes)

### ISSUE THREAD

**Issue by jepster** [drud/ddev#4258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

Link to debug output: https://gist.github.com/jepster/5ce49a9a6a9a373285eec1566ae59355

### Expected Behavior

The mutagen sync process takes 1-2 minutes in my projects. But not more than 14 minutes. This happens even on a restart. Not only on an initial project build.

### Actual Behavior

Since a few weeks the mutagen sync process takes much more time in my projects. Usually the sync process was pretty fast. Now it isn't. I have various Drupal projects and I see the behavior on all of them.

### Steps To Reproduce

1. ddev start
2. Afterwards I get such console output:
`Container ddev-im-nrw-1-dba  Started 
Container ddev-im-nrw-1-db  Started 
Container ddev-im-nrw-1-web  Started 
Starting mutagen sync process... This can take some time. 
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Mutagen sync flush completed in 14m43s.
`

**Comment by rfay** [comment]
Hi @jepster - It sounds like you have some huge files that you've added into your project, or maybe many, many files.

What project type are you using? 

Where are your user-generated files? It sounds like you may have many of them, and not have the upload_dir set properly for ddev to use a regular bind-mount for them.

If you can share the top part of your config.yaml, the project type is super important; if it's `php` then you need to set `upload_dir` to point to user-generated files. 

You can use `ddev mutagen monitor` in another terminal session to watch what all it's doing with all those dots...

**Comment by jepster** [comment]
Hi @rfay 

My project type is "drupal9".

I run "ddev mutagen monitor" and it shows me just "scanning files" as the dots are displayed:

`Identifier: sync_uFI5Z2QK6MqonWdhHqKWPNI6gLbmkUmqGYp9fIlyezT
Alpha:
	URL: /Users/user/dev/myproject
Beta:
	URL: docker://1371973bd94ca0cc94bc890fd40651b00323184183ee8771d3a299228504162b/var/www/html
		DOCKER_HOST=unix:///var/run/docker.sock
Scanning files                                                                  
`

There are no filepaths displayed which are causing the long startup time. This happens not only in one project. It happens in all my DDEV projects.

**Comment by rfay** [comment]
Thanks - 

* What does `ddev exec 'echo $DDEV_FILES_DIR'` show?
* You have a huge number of abandoned containers from times past. I recommend that you kill them all off. `docker rm -f $(docker ps -aq)`
* Did you have some change perhaps at the time this started taking longer?
* What is the size of the DDEV_FILES_DIR (sites/default/files) on one of the problem projects? `du -sh web/sites/default/files` ? How many files are in it? `cd web/sites/default/files && find . -type f | wc -l` ?
* Does a normal new dummy drupal 9 project have this problem? Use the [quickstart](https://ddev.readthedocs.io/en/latest/users/quickstart/#drupal-9-via-composer)
* Please do a `ddev poweroff && ~/.ddev/bin/mutagen sync terminate --all`

BTW, 1-2 minutes (what it used to take) is a horribly long time. 14 minutes is incomprehensible. Is this an older mac?

You may want to consider doing a reset on your Docker Desktop, although I'd not expect that to be the issue. You may want to try out Colima as well.

**Comment by jepster** [comment]
Thanks @rfay 

> What does ddev exec 'echo $DDEV_FILES_DIR' show?

I am getting the following output:
```
/var/www/html/project/docroot/sites/default/files
```

> You have a huge number of abandoned containers from times past. I recommend that you kill them all off. docker rm -f $(docker ps -aq)

I have done so.

> What is the size of the DDEV_FILES_DIR (sites/default/files) on one of the problem projects?
```
majmesku@im-nrw-1-web:/var/www/html/project$ du -sh docroot/sites/default/files
5M    docroot/sites/default/files
```
There are not so many files.

> Please do a ddev poweroff && ~/.ddev/bin/mutagen sync terminate --all

I have done so.

> Does a normal new dummy drupal 9 project have this problem? Use the [quickstart](https://ddev.readthedocs.io/en/latest/users/quickstart/#drupal-9-via-composer)

Yes, it has the same problem. See the following console output (still > 4 minutes):

```
(base) majmesku@nb100 ~/dev/various/ddev-mutagen-test $ d config
Creating a new ddev project config in the current directory (/Users/majmesku/dev/various/ddev-mutagen-test) 
Once completed, your configuration will be written to /Users/majmesku/dev/various/ddev-mutagen-test/.ddev/config.yaml
 
Project name (ddev-mutagen-test): 

The docroot is the directory from which your site is served.
This is a relative path from your project root at /Users/majmesku/dev/various/ddev-mutagen-test 
You may leave this value blank if your site files are in the project root 
Docroot Location (web): 
Found a drupal9 codebase at /Users/majmesku/dev/various/ddev-mutagen-test/web. 
Project Type [backdrop, drupal10, drupal6, drupal7, drupal8, drupal9, laravel, magento, magento2, php, shopware6, typo3, wordpress] (drupal9): 
Ensuring write permissions for ddev-mutagen-test 
No settings.php file exists, creating one 
Existing settings.php file includes settings.ddev.php 
Configuration complete. You may now run 'ddev start'. 
(base) majmesku@nb100 ~/dev/various/ddev-mutagen-test $ d start
Starting ddev-mutagen-test... 
Pushed mkcert rootca certs to ddev-global-cache/mkcert 
Network ddev-ddev-mutagen-test_default  Created 
Volume "ddev-mutagen-test_project_mutagen"  Created 
Container ddev-ddev-mutagen-test-db  Started 
Container ddev-ddev-mutagen-test-dba  Started 
Container ddev-ddev-mutagen-test-web  Started 
Starting mutagen sync process... This can take some time. 
..................................................................................................................................................................................................................................................Mutagen sync flush completed in 4m6s.
For details on sync status 'ddev mutagen status ddev-mutagen-test --verbose' 
Container ddev-router  Started 
Ensuring write permissions for ddev-mutagen-test 
Existing settings.php file includes settings.ddev.php 
Ensuring write permissions for ddev-mutagen-test 
Successfully started ddev-mutagen-test 
Project can be reached at https://ddev-mutagen-test.ddev.site https://127.0.0.1:53680 
(base) majmesku@nb100 ~/dev/various/ddev-mutagen-test $ 
```

> BTW, 1-2 minutes (what it used to take) is a horribly long time. 14 minutes is incomprehensible. Is this an older mac?

No, my Mac is not quite old:

![Bildschirmfoto 2022-10-07 um 12 22 49](https://user-images.githubusercontent.com/628434/194532320-6dad93b9-200d-4b8f-b6f1-a04ce266c6af.png)

Do you have another idea?

**Comment by rfay** [comment]
If it takes 4m to sync the default quickstart Drupal9 project, things are very, very bad. For me, on initial sync, it takes 18s, on second sync 3s.  And you have very, very few files and they're small. Something is wrong with your computer/setup I think. 

I would say the most likely culprit is a virus checker, taking too much time every time a file is touched for syncing. Please temporarily disable your virus checker.

I would have reset Docker Desktop by now, or tried Colima. It's not hard to do but you lose all your databases. If all your projects show in `ddev list` then `ddev snapshot -a` to get a snapshot of all of them, then under "Troubleshoot" do "Reset to factory defaults". (Or just try colima, which is the same process but you haven't destroyed anything.) 

You're also welcome to try the latest almost-released DDEV version, which has some significant mutagen changes, and I'd love to have you try it. `brew unlink ddev && brew install --HEAD --fetch-head ddev`. But from the things you've described I wouldn't expect much difference.

**Comment by jepster** [comment]
The file sync is must faster now. I have followed your hints and stopped Microsoft Defender. Maybe Microsoft Defender was slowing down the filesystem somehow or it was a mix of issues.

**Comment by rfay** [comment]
You'll probably want to just exclude your projects from MS Defender, rather than stopping it completely. But you're using MS Defender on macOS???

**Comment by jepster** [comment]
Yes, Microsoft Defender is installed by Microsoft Intune Company Portal. It‘s installed by the IT department of my employer.

**Comment by serverjohn** [comment]
I was having the same problem as @jepster. Mutagen was taking 14+ minutes. I am also part of a large organization and have Microsoft Defender on my Mac. The article [Killing Microsoft Defender on a Mac](https://uko.codes/killing-microsoft-defender-on-a-mac) helped me to confirm that it was actually Defender. Once the process was stopped mutagen was back to being snappy, 14-27 seconds. I wouldn't suggest permanently disabling this as your IT team will likely be very unhappy. I am planning on sharing this with our IT team and see if they have any suggestions for resolution.

**Comment by rfay** [comment]
In this situation it might be better to disable mutagen, `ddev config global --performance-mode=none` and use VirtioFS file sharing. Better yet, use OrbStack, which is really fast even without mutagen.

**Comment by ChristianOsswald** [comment]
Has anybody new experiences with Microsoft Defender? I got similar problems as described here. Without real-time protection enabled everything is fine.
1. I had long taking starts.
2. Excluded some folders then, so the ddev start / ddev mutagen reset works OK, in like 1 - 2 minutes.
3. I have now problems with sync. Without "ddev mutagen sync" my changes mostly don't get into the container. Even if it is only one line of code.
4. Now i am trying orbstack. (will report here)

**Comment by rfay** [comment]
Hi @ChristianOsswald - I think the guidance above is probably what you need, but otherwise open a new issue.

**Comment by rfay** [comment]
Note that in a project of type `drupal*`, sites/default/files would already have been excluded. 

I think that `ddev import-db` and `ddev pull` don't necessarily work with .importdb removed

Here are the defaults for a Drupal project:
```
        - "/.git"
        - "/.tarballs"
        - "/.ddev/db_snapshots"
        - "/.ddev/.importdb*"
        - ".DS_Store"
        - ".idea"
        - "/web/sites/default/files"
 ```

If you had a drupal project with `docroot: docroot` it whould have had that in there.

So it seems like perhaps you aren't using a project of type `drupal*` or you wouldn't have had to do this @serverjohn ?

**Comment by serverjohn** [comment]
@rfay great question! I am currently using a project type of Drupal10. It is possible that I did not have that set properly back in November... I should mention that there was an additional directory I have excluded that is specific to our project and custom modules.

**Comment by rfay** [comment]
Reported in discord: https://discordapp.com/channels/664580571770388500/1447908989600927908

**Comment by rfay** [comment]
ChatGPT configuration suggestions: https://chatgpt.com/share/693836f5-8b20-8003-9f3f-371d3b0db88a
