### ISSUE TITLE
Magento1/OpenMage - DDEV should mandatory create an admin user account for Backend

### ISSUE THREAD

**Issue by ADDISON74** [drud/ddev#4259]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

If a database is imported through the command ```ddev import-db --src=filename.extension```, it most likely has an admin account and it is no longer necessary to create one.

Let's see what is happening when we set up a test environment for OpenMage from scratch:

1. Create a new directory then clone OpenMage repository. Please note it doesn't include the **/etc/local.xml** file.
2. Run ```ddev config```, ```ddev start```, ```ddev launch``` commands.
3. The Frontend opens in the browser.

![screenshot-1](https://user-images.githubusercontent.com/8360474/194058334-c248f6d1-950a-45de-8903-b5fdab5b02c6.png)

4. Run ```ddev describe``` to get information about phpMyAdmin and open the link in the browser. 

5. Select from the left side the database named **db** then open the **admin_user** table. As you may see from the image bellow the table is empty.

![screenshot-2](https://user-images.githubusercontent.com/8360474/194059000-27084061-dd13-4260-8ad4-b4ca394d86b2.png)

This is a serious issue because without an admin account we cannot access the Backend.

### Describe your solution

If we end up in this situation there are two solutions identified by me:

1. Once you access the phpMyAdmin interface select the **db** database and run the SQL query from bellow (it creates a username: admin with password: admin):

```sql
INSERT INTO `admin_user` (`user_id`, `firstname`, `lastname`, `email`, `username`, `password`, `created`, `modified`, `logdate`, `lognum`, `reload_acl_flag`, `is_active`, `extra`, `rp_token`, `rp_token_created_at`) VALUES
(1, 'Open', 'Mage', 'contact@ddev.site', 'admin', '17ef9b5a13acc91cc8f7bfe49a90e01f1e04ad6c885616a07d2ad7229617992c:MKZ25yJs32F11JWKvbVbDqebeB35NV4n', '2022-10-04 16:26:46', '2022-10-04 17:16:57', '2022-10-04 17:16:57', 0, 0, 1, 'N;', NULL, NULL);
```

The account information can be changed in Backend later.

2. Rename the **/etc/local.xml** file to initiate the installation from scratch. It can be done in browser (Host: db, Database Name: db, User Name: db, User Password: db) or in the CLI.

### Additional context

The purpose of DDEV is to provide a test environment for OpenMage with minimal effort. Choosing for one of the solutions offered by me does not coincide with the intended goal.

I appreciate the feature that DDEV creates the **/etc/local.xml** file for me, without this file we are facing a new instance of Magento 1/OpenMage and accessing the website in the browser will initiate the installation. 

Going further DDEV should mandatory create an admin account for accessing the Backend. Once created, the information about it must be displayed either after running the command ```ddev start``` or better by using the command ```ddev describe```.

**Comment by rfay** [comment]
DDEV doesn't usually do database changes, but a simple docs PR could be added that adds the admin user. 

However, when I've gone through the standard [quickstart](https://ddev.readthedocs.io/en/latest/users/quickstart/#openmagemagento-1) I haven't ever had any trouble. Maybe you could do the quickstart and see if you have this problem? If you do, you could click the edit button on that page and create a docs PR with an extra line to accomplish what you want.

**Comment by ADDISON74** [comment]
DDEV does what it has to do, according to the documentation, but does not offer an account for website administration. You only have the functional interface with the visitor, you cannot configure the website. 

I think that it is fine to create the file **/etc/local.xml** if it doesn't exist because in this way the installation process that will last around 2 minutes is skipped. In addition, someone may have issues entering the correct information to connect to database. 

I'm not a fan of Docker configurations, but if we could execute that SQL script in the database, we would also have an admin account, without having to add anything to the DDEV documentation. You are the best able to evaluate if this would be a solution, you could even ask in the configuring process the username and password for the administration account. 

I only reported this issue from the perspective of a user who has been in contact with DDEV for a month and a half, without knowing in detail how it works. I have no problem creating that user account, but I would like everything to be done automatically when running ```ddev config```.

**Comment by ADDISON74** [comment]
I propose to leave this issue open. I introduced it to OpenMage community as well. I will analyze what you did in DDEV on the OM side, I don't want to limit myself to just adding that step in the documentation, but I want everything to happen within the ```ddev config``` command.

**Comment by rfay** [comment]
There is no database and no project existing at the time of `ddev config`, so it's not going to happen then. It could happen during `ddev start`. But again, there are currently no project types where we do anything to the database as a part of configuration. That seems extremely intrusive and likely to create trouble. If you're saying it can also be done in the config file, that would be acceptable.

Remember, this is a community project, and the OpenMage folks are the experts here. If they pipe up and have a proposed solution (and agree with you that there's a problem) we can take this up someday. It's better if somebody from the community does a PR.

**Comment by ADDISON74** [comment]
**The first option**, the easiest and fastest. DDEV will no longer create the **/etc/local.xml** file during the configuration steps. If this file is missing determines the initialization of the installation process at the end of which we will have an account for Backend. The only issue is that the one who will do it must know what information to fill in the form when he gets to the step related to the connection to the database. It can be solved by a message displayed when running the ```ddev config``` command, for example "_The project has not been installed yet, once launched in the browser you will have to go through the installation steps. For information about connecting to the database use ```ddev describe``` command._"

**The second option** involves running a bash script (there will be an issue here in Windows OS) that will automatically install. Something similar was done here: https://github.com/OpenMage/magento-lts/blob/260eb87140254f85c2a622814cc45f308923ef51/dev/openmage/install.sh. When the ```ddev config``` command is run, either the admin username and password are asked or something predefined is used, for example admin/admin and which is displayed to the user when the process ends successfully.

**Comment by rfay** [comment]
I'd be perfectly happy to drop the creation of /etc/local.xml if the folks involved with Magento1/OpenMage are good with that.

**Comment by ADDISON74** [comment]
@rfay - What do you think if there is a command to run that SQL query in the database container? There would be several advantages:

- the file local.xml no longer needs to be removed and we practically have a functional installation.
- the user can create an admin account for Backend whenever he wants. but it should be informed that he has this possibility (DDEV can ask for creating an account if the table **admin_user** is empty).
- if he forgot the password, he can recreate this account (like a reset).

**Comment by rfay** [comment]
But there are loads of ways to do that. The mysql and psql clients are installed in both web and db containers and preconfigured.

**Comment by sreichel** [comment]
I think there are different scenarios, with different issues ...

1. use an existing DB/project
If you have no edits made to your projects local.xml that one created by DDEV should work well. All you have to do is to import your DB and adjust base/secure_base_url in config table. 

2. use sample data (see docs)
If I remember correctly sample data has no admin user account. There are several way to create one:
    - add php script that uses correct models
    - add sql script (yours seems not complete, admin role have to be set too???)
    - use [N98-magerun](https://github.com/netz98/n98-magerun#create-admin-user)

3. fresh install
DDEVs local.xml has to be deleted to run install command. Just add `rm app/etc/local.xml` to install script or custom command?

imho ... i have no problems with created local.xml, but install process can be improved on OM side for sure.

**Comment by rfay** [comment]
It seems to me like this feature request was not going to make it as is, but happy to continue the conversation here or elsewhere. Closing for now.
