### ISSUE TITLE
Drupal 8/9: PHP warning "use of undefined constant CONFIG_SYNC_DIRECTORY" from the settings.ddev.php file

### ISSUE THREAD

**Issue by jepster** [drud/ddev#4267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

Link to debug output: https://gist.github.com/jepster/5ce49a9a6a9a373285eec1566ae59355

### Expected Behavior

DDEV does not create a `settings.ddev.php` file, where it tries to use an undefined constant.

### Actual Behavior

I am getting the following PHP warning on every page request:

```
Warning: Use of undefined constant CONFIG_SYNC_DIRECTORY - assumed 'CONFIG_SYNC_DIRECTORY' (this will throw an Error in a future version of PHP) in include() (line 53 of /var/www/html/project/docroot/sites/default/settings.ddev.php).
```

Therefor I need to modify the `settings.ddev.php` file, which is auto-generated by DDEV. My change will be overwritten soon. I have specified the path tho the Drupal config directory already in my `settings.php` file.

Please replace `$config_directories[CONFIG_SYNC_DIRECTORY]` with `$settings['config_sync_directory']` in the `settings.ddev.php` template file.

### Steps To Reproduce

Just spin up a Drupal 8/9 site with DDEV and use PHP > 7.4.

**Comment by rfay** [comment]
For Drupal9+ ddev creates this stanza in settings.ddev.php:

```
// Set $settings['config_sync_directory'] if not set in settings.php.
if (empty($settings['config_sync_directory'])) {
  $settings['config_sync_directory'] = 'sites/default/files/sync';
}
```

I'm not sure what you've got going on. Please delete your settings.ddev.php and let ddev recreate it. Maybe you have one from a couple of years ago and you modified it back then?

If you have an old Drupal 8 site, and you have the project type set to `drupal8` the generated code would be 

```
// This specifies the default configuration sync directory.
// For D8 before 8.8.0, we set $config_directories[CONFIG_SYNC_DIRECTORY] if not set
if (version_compare(Drupal::VERSION, "8.8.0", '<') &&
  empty($config_directories[CONFIG_SYNC_DIRECTORY])) {
  $config_directories[CONFIG_SYNC_DIRECTORY] = 'sites/default/files/sync';
}
// For D8.8/D8.9, set $settings['config_sync_directory'] if neither
// $config_directories nor $settings['config_sync_directory is set
if (version_compare(DRUPAL::VERSION, "8.8.0", '>=') &&
  empty($config_directories[CONFIG_SYNC_DIRECTORY]) &&
  empty($settings['config_sync_directory'])) {
  $settings['config_sync_directory'] = 'sites/default/files/sync';
}
```

So please take a look at your project type, and please inspect the settings.ddev.php.

**Comment by jepster** [comment]
Will DDEV re-create the file on restart?

**Comment by rfay** [comment]
Yes. DDEV always recreates it unless you remove the `#ddev-generated` line or unless you have `disable_settings_management: true` in the config.yaml. Please take a quick read of https://ddev.readthedocs.io/en/latest/users/topics/cms_specific_help/

**Comment by rfay** [comment]
No response from OP for some time so closing this. Would be happy to hear what you found.

**Comment by therobyouknow** [comment]
My solution to this same problem I came across was to just comment out:

```
$config_directories = array(
  CONFIG_SYNC_DIRECTORY => '../config/sync',
);
```

in `settings.php` in my codebase (`web/sites/default/settings.php`).

This solved the error `Error: Undefined constant "CONFIG_SYNC_DIRECTORY" in require() (line 265 of /var/www/html/web/sites/default/settings.php).` that I got when attempting drush commands.

There are if-checks further down that support the absence of `CONFIG_SYNC_DIRECTORY` so it's OK to just comment it out or remove it as far as I can see.

I would suggest that `settings.php` needs updating officially to address this issue.

**Comment by rfay** [comment]
If you have this problem it means you have the wrong project type...

**Comment by noel-rivas** [comment]
I stumbled upon this issue today on a site that had drupal8 in config.yaml but is actually a drupal 9 site.

Solution: change type to `drupal9` in config.yaml

Thanks @rfay for pointing us in the right direction.

**Comment by philippemellenger** [comment]
For me it was the settings.pantheon.php that had the same piece as @therobyouknow

`$config_directories = array(
  CONFIG_SYNC_DIRECTORY => '../config/sync',
);`
