### ISSUE TITLE
Docker troubleshooting command fails with docker installed inside wsl2

### ISSUE THREAD

**Issue by shaal** [drud/ddev#4276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

I want to be able to follow the documentation on a new Windows 11 installation, with no errors -
* Install WSL2
* Install Docker Desktop
* Install ddev

### Actual Behavior

I think the confusing part - is in https://ddev.readthedocs.io/en/latest/users/install/docker-installation/#testing-and-troubleshooting-your-docker-installation

After following these commands (WSL2 docker installation) - 
You cannot run docker yet (getting error about daemon permissions missing)

Specifically, these commands were "missing" (From the next section 'ddev installation' - https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#windows-wsl2 )

> Docker Desktop for Windows: If you already have the latest Docker Desktop, configure it in the General Settings to use the WSL2-based engine. Otherwise install the latest Docker Desktop for Windows and select the WSL2-based engine (not legacy Hyper-V) when installing. Install via Chocolatey with choco install docker-desktop or it can be downloaded from [desktop.docker.com](https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe). Start Docker. It may prompt you to log out and log in again, or reboot.
> Go to Docker Desktop’s Settings → Resources → WSL integration → enable integration for your distro. Now docker commands will be available from within your WSL2 distro.

After I installed Docker for Desktop in Windows (using choco) - I was able to run the test command for docker
`docker run --rm -t -p 80:80 -p 443:443 -v "//$PWD:/tmp/projdir" busybox sh -c "echo ---- Project Directory && ls /tmp/projdir"`

**Comment by shaal** [comment]
After creating this issue, I realized there IS a section called `Docker Desktop for Windows` https://ddev.readthedocs.io/en/latest/users/install/docker-installation/#docker-desktop-for-windows

My question is -
When I followed the instructions for `Docker CE Inside Windows WSL2`, why couldn't I run the docker test command without errors?
`docker run --rm -t -p 80:80 -p 443:443 -v "//$PWD:/tmp/projdir" busybox sh -c "echo ---- Project Directory && ls /tmp/projdir"`
(After installing Docker Desktop - I was able to run it with no errors)

**Comment by rfay** [comment]
If you'd say what error you got it would help. Most likely because after installing docker-ce (and adding the docker user to the group) you have to log out and log in again.

**Comment by rfay** [comment]
Since you're an expert novice now, would you please try this? It would help so much
* https://github.com/drud/ddev/pull/4150 

You can `wsl --unregister Ubuntu` assuming your distro is named Ubuntu.

**Comment by rfay** [comment]
Closing, happy to continue the conversation here or elsewhere.
