### ISSUE TITLE
Create configuration file for TYPO3 v12 installations

### ISSUE THREAD

**Issue by linawolf** [drud/ddev#4278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

With Change https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-98319-NewFileLocationForLocalConfigurationphpAndAdditionalConfigurationphp.html 

Creating a file at public/typo3conf/AdditionalConfiguration.php does not have effect anymore in TYPO3 v12.0 Installations. When 
creating a ddev project as described here:

https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/Installation/TutorialDdev.html

This leads to the database not being found.

### Describe your solution

Make a difference in project type for typo3-12 and create a file at typo3conf/system/additional.php then instead.

**Comment by rfay** [comment]
Please manually test and review https://github.com/drud/ddev/pull/4268#issuecomment-1271532128

**Comment by rfay** [comment]
Now pulled. You can also test now with techniques in https://ddev.readthedocs.io/en/latest/developers/building-contributing/

**Comment by rfay** [comment]
Fixed in 
* https://github.com/drud/ddev/pull/4268

Let me know if you have any trouble testing.
