### ISSUE TITLE
DDEV v1.21.2 Test Plan - Community Help Requested

### ISSUE THREAD

**Issue by rfay** [drud/ddev#4279]
It's testing time again here in the DDEV factory. We love community help with every item that is interesting or relevant to you, and just *using* the release candidates is hugely helpful, because you may stumble across something in your regular workflow. Please use DDEV HEAD for your testing (or `brew unlink ddev && brew install --HEAD --fetch-head drud/ddev/ddev`) or other techniques at [Testing Latest Commits].(https://ddev.readthedocs.io/en/latest/developers/building-contributing/#testing-latest-commits)

I don't think in general you'll have trouble using this in your daily workflow, so would love you do do that. You can switch back and forth , see [How can I install a specific version of DDEV in the FAQ](https://ddev.readthedocs.io/en/latest/users/basics/faq/).

If you find a bug that you're pretty sure is a bug, then [just open an issue for it](https://github.com/drud/ddev/issues/new?assignees=&labels=&template=Bug_report.md&title=).

To give feedback or ask questions, please just reply on this issue or discuss in [discord](https://discord.gg/hCZFfAMc5k) or any other support channel.

I am maintaining the [provisional release notes for v1.21.2](https://randyfay.notion.site/Release-process-v1-21-2-5e9e8a2cbef74008a302888ff28b8af0) and would love any comments on those.

1. PHP 8.2: Configure a project with PHP 8.2 and confirm correct behavior, and that you can use it with some site. Drupal 10 is probably nearly ready, latest TYPO3 v12 might be. 
2. Craft CMS: 
    - Configure a Craft CMS project from scratch using the [Quickstart](https://ddev.readthedocs.io/en/latest/users/quickstart/#craft-cms)
    - `ddev craft` should work
    - If project type is set to `php` then `ddev craft` should tell you to use the real project type.
3. TYPO3 v12: 
    - Use the [TYPO3 Quickstart](https://ddev.readthedocs.io/en/latest/users/quickstart/#typo3) to do a TYPO3 v12 install. 
    - Use the same quickstart with `ddev composer create "typo3/cms-base-distribution:^11" --no-install` to install TYPO3 v11 and verify that it also works.
4. Mutagen:
    - Use `ddev mutagen logs` to see full verbose output
    - Run multiple projects at the same time using mutagen.
    - Mess up DDEV with `docker kill ddev-router` with a project running, then try `ddev start` to get out of trouble and see if you get out of trouble.
    - Extra credit: Run mutagen outside ddev and verify it doesn't cause any conflict. Consider [installing mutagen](brew install mutagen-io/mutagen/mutagen) and verifying it has no impact when you run `mutagen daemon start`. Verify that you can delete ~/.mutagen and have no impact on DDEV.
5. Global `project_tld`:
    - Verify that you can set the global `project_tld` and it takes effect for all projects.
    - Verify that you can override it with project-level `project_tld`
6. Yarn and npm caches: 
    - With a project that has yarn v3, verify that https://github.com/drud/ddev/issues/4088 is not a problem.
    - Verify yarn and npm cache behavior using tests like @hanoii 's https://github.com/drud/ddev/pull/4234#issuecomment-1263540074
7. Old configured database (v1.18 database with this version of DDEV). 
    - Create a project with a v1.18.2 version of DDEV (Just download the binary from releases). It can be an empty project, or a composer-created one, doesn't matter. `ddev start` it with old ddev. Then `ddev poweroff` and `ddev start` with this version of ddev. It should work. See the problem in https://github.com/drud/ddev/issues/4129
8. Try using ddev with an old docker-compose v1 version. (https://github.com/drud/ddev/issues/4135). You can do this in Docker Desktop by switching to docker-compose v1 in the settings. Then `ddev config global --use-docker-compose-from-path`. DDEV's output should help you figure out what's wrong.
9. Use a `docker-compose.*.yaml` and remove the `version` line. It should still work fine. For example, `ddev get drud/ddev-adminer` and then edit the `docker-compose.adminer.yaml` to remove the version line and then `ddev restart` and use the adminer interface.
10. `postgres:9` detection: Create a project using `--database=postgres:9` and start it. Then `ddev restart`. It should work. Then move to `postgres:10`, it should complain. Use. `ddev debug check-db-match` to see if the installed database matches the configured database with a variety of differences.
11. Database migration to different version: Try migrating a mariadb or mysql database to another version using `ddev debug migrate-database <target_type:target_version>`
12. `composer_root` and `$PATH`: Create a project with a nonstandard composer root. For example, put the composer.json in `docroot` and set `composer_root` to `docroot`. Then after `ddev composer install` things in `docroot/vendor/bin` should be in `$PATH`. For example, for Drupal, `ddev drush` should work. Or `ddev exec typo3cms`.
13. Internet timeout: Verify that DDEV doesn't complain about internet detection except when there actually is no internet (wifi turned off for example). Test out the no-internet lifestyle.
14. Use `ddev debug test`:
    - It should refuse to run if not in a project
    - It should fail to run in home directory
    - It should show no obvious errors
    - It should refuse to run if the parent directory is not writable
    - Review its output of course
15. Verify DDEV behavior with fig, see https://github.com/drud/ddev/pull/4216
16. Using mutagen, make sure that `.ddev/.downloads` is available inside `ddev ssh` and that pull commands like `ddev pull platform` that use it still work with mutagen enabled. (https://github.com/drud/ddev/issues/4193)
17. Verify that zsh completion works with ddev installed using homebrew. (#4179)
18. If mutagen is enabled, and project type `php` or a project type without a default `upload_dir` (like `craftcms`), verify that ddev warns about that on start, and that the warning goes away if you set an upload_dir.
19. Mutagen on traditional Windows: binaries should be executable using mutagen in traditional Windows, so try out things like `ddev drush` or `ddev exec typo3cms` to make sure they work using Mutagen.

**Comment by rfay** [comment]
1. ✅ PHP8.2: I had no trouble installing Drupal 10.0.0-dev with PHP8.2 (rc3) using macOS on M1. I did have serious slowness issues on WSL2 with docker-ce inside, but couldn't figure out if it was the computer or something else. The commands, even `ddev config` and `ddev describe` had a noticeable delay.
2.

**Comment by rfay** [comment]
I think it's good!

**Comment by tyler36** [comment]
1. ✅ PHP8.2

Using WSL2 with Docker Desktop I didn't have any slowness.

- Setup Drupal 10

```shell
ddev config --project-type=drupal10 --docroot=web --create-docroot
```

- install Drush

```shell
ddev composer require drush/drush
```

- Install site

```shell
ddev drush si --site-name=d10-dev -y
```

- Visited site in browser and confirmed working.

## Test

- Check PHP

```shell
$ ddev php -v
PHP 8.1.11 (cli) (built: Sep 29 2022 22:17:15) (NTS)
```

- Re-install site

```shell
ddev drush si --site-name=d10-dev -y
```

Took `32s`

- Stop DDEV and (manually) update config to PHP `8.2`
- Check PHP

```shell
$ ddev php -v
PHP 8.2.0RC3 (cli) (built: Sep 29 2022 22:12:49) (NTS)
```

- Re-install site

```shell
ddev drush si --site-name=d10-dev -y
```

Took `22s`

- `ddev descibe` felt about the same (or snappier)

**Comment by rfay** [comment]
Thanks so much @tyler36 !
