### ISSUE TITLE
Drupal 9/10 & Mysql: "MySQL transaction isolation level"

### ISSUE THREAD

**Issue by tyler36** [drud/ddev#4281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

While testing the lastest head version (HEAD-c035fa2) with the latest Drupal version (10.1.0-dev), I noticed a new warning:

> Database Isolation Level
> REPEATABLE-READ
> For the best performance and to minimize locking issues, the READ-COMMITTED transaction isolation level is recommended. See the setting [MySQL transaction isolation level](https://www.drupal.org/docs/system-requirements/setting-the-mysql-transaction-isolation-level) page for more information.

Link: https://www.drupal.org/docs/system-requirements/setting-the-mysql-transaction-isolation-level

I made the following changes to `web/sitges/default/settings.ddev.php`  
  - remove `#ddev-generated`
  - add the following to database array

```php
$databases['default']['default'] = [
  ...
  'init_commands' => [
    'isolation_level' => 'SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED',
  ],
];
```

This change removed the warning.

Drupal 10 is due out in 2 months, on Dec 2022.

DDEV: `HEAD-c035fa2`
Drupal: `10.1.0-dev`

### Describe your solution

The config should be added to when
- database type = MySQL or MariaDB
- project type = Drupal 10

**Comment by rpkoller** [comment]
what i've learned the more preferable way would be adding a cnf file (.ddev/mysql/my.cnf) with 
```
[mysqld]
transaction-isolation = READ-COMMITTED
```
we've also created an issue for updating the corresponding doc page: https://www.drupal.org/project/documentation/issues/3308909

but in general i agree it would be nice to have it set to read-commited for drupal project (at least for drupal 10 ones)

**Comment by rfay** [comment]
It's a great idea to just add this suggested stanza (`init-commands`) to https://github.com/drud/ddev/blob/master/pkg/ddevapp/drupal/drupal10/settings.ddev.php (simple PR), but I think it will have to check the database type, not sure whether it would somehow breap postgres. 

It would also be possible to change the drupal10 mysql config, but we haven't done that before, so it's certainly more complex. IMO the changing of the mysql config is far more appropriate for a server, but for the case of DDEV we just want to make the user happy and comfortable, and the settings.ddev.php is a superb way to do that.

**Comment by tyler36** [comment]
@rpkoller 
Oh, that looks like a nicer solution.

**Comment by tyler36** [comment]
Ah ... found your conversion on [drupal.org](https://www.drupal.org/project/documentation/issues/3308909).

Adding here for cross reference.
