### ISSUE TITLE
DDEV 1.21.2 Mutagen projects fail with "Error: invalid label value: must be no more than 63 characters" error

### ISSUE THREAD

**Issue by juban** [drud/ddev#4285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

```
OS Information: Darwin MacBook-Pro-M1-de-Alban.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64
ProductName:    macOS
ProductVersion: 12.6
BuildVersion:   21G115
User information: uid=501(albanjubert) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae)
DDEV version:  ITEM             VALUE                                   
 DDEV version     v1.21.2                                 
 architecture     arm64                                   
 db               drud/ddev-dbserver-mariadb-10.4:v1.21.2 
 dba              phpmyadmin:5                            
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.2             
 docker           20.10.11                                
 docker-compose   v2.10.2                                 
 docker-platform  colima                                  
 mutagen          0.16.0-rc1                              
 os               darwin                                  
 router           drud/ddev-router:v1.21.2                
 web              drud/ddev-webserver:v1.21.2             
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
mutagen-enabled=true
nfs-mount-enabled=false
router-bind-all-interfaces=false
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
auto-restart-containers=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=
use-docker-compose-from-path=false
no-bind-mounts=false
project-tld=

======= DOCKER info =========
docker location: lrwxr-xr-x  1 albanjubert  admin  36 May 30 08:49 /opt/homebrew/bin/docker -> ../Cellar/docker/20.10.16/bin/docker
Docker Desktop Version: Docker Desktop for Mac 4.12.0 build 85629
docker version: 
Client: Docker Engine - Community
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.18.2
 Git commit:        aa7e414fdc
 Built:             Wed May 11 16:22:17 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.4
  Git commit:       847da184ad5048b27f5bdf9d53d070f731b43180
  Built:            Fri Nov 19 03:41:34 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.5.8
  GitCommit:        1e5ef943eb76627a6d3b6de8cd1ef6537f393a71
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        
DOCKER_DEFAULT_PLATFORM=notset
======= Mutagen Info =========
Mutagen is installed in ddev, version=0.16.0-rc1
--------------------------------------------------------------------------------
No synchronization sessions found
--------------------------------------------------------------------------------
======= Docker Info =========
Docker platform: colima 
Colima version: 0.4.6 
Using docker context: default (unix:///Users/albanjubert/.colima/default/docker.sock) 
docker-compose: v2.10.2 
Using DOCKER_HOST=unix:///Users/albanjubert/.colima/default/docker.sock 
Docker version: 20.10.11 
Able to run simple container that mounts a volume. 
Able to use internet inside container. 
Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                  58.8G     40.8G     14.9G  73% /

Stopped mutagen daemon 
The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again. 
Existing docker containers: 
CONTAINER ID   IMAGE          COMMAND                  CREATED        STATUS                    PORTS     NAMES
c5e48f789c8c   c22ad8fdf04b   "sh -c 'chown -R 501…"   3 months ago   Exited (0) 3 months ago             recursing_einstein
689b1eb71f75   8219b1a570b2   "sh -c 'chown -R 501…"   4 months ago   Exited (0) 4 months ago             dreamy_mirzakhani
Creating a new ddev project config in the current directory (/Users/albanjubert/Documents/htdocs/tryddevproject-10516) 
Once completed, your configuration will be written to /Users/albanjubert/Documents/htdocs/tryddevproject-10516/.ddev/config.yaml
 
Configuring unrecognized codebase as project type 'php' at /Users/albanjubert/Documents/htdocs/tryddevproject-10516/web 
Configuration complete. You may now run 'ddev start'. 
Network ddev_default created 
Starting tryddevproject-10516... 
Container ddev-ssh-agent  Started 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
Pushed mkcert rootca certs to ddev-global-cache/mkcert 
Network ddev-tryddevproject-10516_default  Created 
Container ddev-tryddevproject-10516-dba  Started 
Container ddev-tryddevproject-10516-db  Started 
Container ddev-tryddevproject-10516-web  Started 
You have mutagen enabled and your 'php' project type doesn't have an upload_dir set. 
For faster startup and less disk usage,
set upload_dir to where your user-generated files are stored. 
Starting mutagen sync process... This can take some time. 
Failed to start tryddevproject-10516: Failed to create mutagen sync session 'tryddevproject-10516'. You may be able to resolve this problem using 'ddev mutagen reset' (err=Failed to mutagen [sync create /Users/albanjubert/Documents/htdocs/tryddevproject-10516 docker://ddev-tryddevproject-10516-web/var/www/html --no-global-configuration --name tryddevproject-10516 --label com.ddev.volume-signature=unix-Users-albanjubert-colima-default-docker-sock-20221012104411 --configuration-file=/Users/albanjubert/Documents/htdocs/tryddevproject-10516/.ddev/mutagen/mutagen.yml] (exit status 1), output=Error: invalid label value: must be no more than 63 characters
) 
======== Curl of site from inside container:
curl: (22) The requested URL returned error: 404 Not Found
Failed to execute command curl --fail -I http://127.0.0.1: exit status 22
======== Curl of site from outside:
curl: (7) Failed to connect to tryddevproject-10516.ddev.site port 80 after 49 ms: Connection refused
Unable to curl the requested project Please provide this output in a new gist at gist.github.com.

Please delete this project after debugging with 'ddev delete -Oy tryddevproject-10516'
Failed running test_ddev.sh: exit status 1
```

### Expected Behavior

Project should start with Mutagen activated without issue.

### Actual Behavior

On MacOS with Colima, starting with DDEV 1.21.2 (works fine with DDEV 1.21.1), `ddev start` results with an issue when Mutagen tries to sync project files: `Error: invalid label value: must be no more than 63 characters`. Every project is affected.

In my case, the generated label is `com.ddev.volume-signature=unix-Users-albanjubert-colima-default-docker-sock-20221012104411`, which is 64 chars, leading to the error.

Looks like this is due to the new mutagen version introduced in DDEV 1.21.2.

### Steps To Reproduce

1. Be sure to run DDEV 1.21.2
2. Try to start a DDEV project (or debug test)

### Anything else?

Obviously, this is most likely an environment related issue as the generated label will differ depending on the host DDEV is running on.

**Comment by rfay** [comment]
Yeah, it's not due to the mutagen version, but rather to the way I decided to construct the label. The idea here is that since mutagen sessions now just *pause* instead of being recreated, which improves performance on restart and fixes a couple of obscure bugs, the name of the docker volume is built using the docker context value, `unix:///Users/albanjubert/.colima/default/docker.sock` in your case. 

You should be able to work around this by making a symlink to unix:///Users/albanjubert/.colima/default/docker.sock using `ln -s ~/.colima/default/docker.sock ~/.colima/docker.sock` and then using `export DOCKER_HOST=/Users/albanjubert/.colima/docker.sock`

I'll figure out a shorter representation!

**Comment by rfay** [comment]
If you're interested, you could also create a new colima profile with a name shorter than "default". `colima start d --dns=1.1.1.1 --disk=100 --memory=6 --cpu=4` but then you have to remember to `colima start d` and `colima stop d`. And you have to migrate your databases.

**Comment by juban** [comment]
OK thanks for the explanations and quick feedback @rfay . It's some kind of optimization side effect then (optimization is a good thing :) ).
I'll try the workarounds and let you know.
I'm not sure I did something special with my Docker / Colima setup, so this issue could probably occur petty often on other systems I guess.

**Comment by rfay** [comment]
I'm surprised not to have seen this elsewhere since your username `albanjubert` isn't *that* long. But it is longer than anything else I've used. I've also used different colima profiles, which would get this, but they've all been short profile names like "sshfs", which result in relatively longer names 

I was able to recreate your situation with a 74-character label:

```
cd ~/workspace/d9/web/sites/default
ln -s ~/.colima/docker.sock
export DOCKER_HOST=unix:///Users/rfay/workspace/d9/web/sites/default/docker.sock
ddev restart
```

`Failed to restart d9: Failed to create mutagen sync session 'd9'. You may be able to resolve this problem using 'ddev mutagen reset' (err=Failed to mutagen [sync create /Users/rfay/workspace/d9 docker://ddev-d9-web/var/www/html --no-global-configuration --name d9 --label com.ddev.volume-signature=unix-Users-rfay-workspace-d9-web-sites-default-docker-sock-20221012092525 --configuration-file=/Users/rfay/workspace/d9/.ddev/mutagen/mutagen.yml] (exit status 1), output=Error: invalid label value: must be no more than 63 characters
)`

**Comment by rfay** [comment]
The label length limitation turns out to be mutagen, not docker, but it should be easy to shorten it, with a hash or some other technique. The only idea is to make it unique so people moving between docker contexts or docker providers don't have "interesting" behavior.

**Comment by rfay** [comment]
* #4289 should fix this, binaries are at https://github.com/drud/ddev/pull/4289#issuecomment-1276542693 if you'd be willing to try them out. If you're using a changed DOCKER_HOST remember to unset it.

**Comment by BramDriesen** [comment]
We are also running into this issue. Multiple people are getting this issue now in our team after performing a clean install/upgrade.

name examples:
bram.driesen
Yannick.xxxxxxx (hidden last name)

Once this is fixed, can a new release be added asap? 😃

**Comment by BramDriesen** [comment]
The workaround in https://github.com/drud/ddev/issues/4285#issuecomment-1276227033 solved the issue for us for now. But people with longer names will still have that issue.

**Comment by YannickBloemen** [comment]
I also have this issue after installing the new ddev.

**Comment by rfay** [comment]
I'm pretty sure that #4289 is fine  but the colima tests are often flaky, and I haven't been able to get a successful full test run yet, so waiting on that.

**Comment by rfay** [comment]
This should be fixed in DDEV HEAD now, I would appreciate if those of you who are having trouble could update to current HEAD and verify that it fixes things for you.

```
brew unlink ddev && brew install --HEAD --fetch-head ddev
```

It's easy to do, nothing much else has changed, and you can go back to stable when the release comes out with `brew uninstall ddev && brew install ddev`

**Comment by mikesnoeren** [comment]
I can confirm the comment above fixes the issue, however..

Please be aware that, according to my testing, this version doesn't auto generate the right content for the `./ddev/.gitignore` file.
This causes a lot of the ddev generated files to be seen as changes by git.

**Comment by mikesnoeren** [comment]
> I would appreciate if those of you who are having trouble could update to current HEAD and verify that it fixes things for you.

I can confirm this fixes the issue, thanks!

**Comment by zolika42** [comment]
@rfay Thank you for the fix. I can also confirm it is working well. Please ping us when it is in the stable release. Thank you in advance!

**Comment by rfay** [comment]
Thanks for the reports!

**Comment by juban** [comment]
@rfay The fix works fine for me too. Thank you.
