### ISSUE TITLE
Project type `craftcms` doesn't listen to `upload_dir` config setting.

### ISSUE THREAD

**Issue by mikesnoeren** [drud/ddev#4302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Project type `craftcms` should listen to `upload_dir` config setting.

### Actual Behavior

Project type `craftcms` defaults to `files` as it is hard coded in the project type..
`files` shouldn't be seen as a default because it is opinionated.

### Steps To Reproduce

1. Start a new project `ddev config --project-type=craftcms && ddev start`.
2. Check the default value `ddev exec 'echo $DDEV_FILES_DIR' `  (returns `files`).
3. Change `upload_dir` in `.ddev/config.yaml` to anything.
4. Check for the custom value `ddev exec 'echo $DDEV_FILES_DIR' `  (still returns `files`).

**Comment by rfay** [comment]
We wouldn't want to change the behavior of the project type just to make a test pass, I'm sure we can figure something out.

**Comment by khalwat** [comment]
So I tried to make it such that if the `upload_dir` was set already, it wouldn't change it to `files` but I was unable to get that to work properly.

Any guidance on that front? Ideally we'd like it to set the `upload_dir` to `files` only if no `upload_dir` has been specified in the `.yaml` file.
