### ISSUE TITLE
Environment variables in .env file are not supported without extra configuration

### ISSUE THREAD

**Issue by flynnt** [drud/ddev#4309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Based on the instructions in the [CMS Quickstarts](https://ddev.readthedocs.io/en/stable/users/quickstart/) section of the docs for CraftCMS I expected to be able to set the `CRAFT_CMD_ROOT` variable in my `.env` file and have the `ddev craft` command use the value set there. I am running my Craft application in a subdirectory, `./app`, and having set that as the `CRAFT_CMD_ROOT`, and after restarting DDEV, I expected `ddev craft` to work.

### Actual Behavior

Running `ddev craft` after following the steps in the CMS Quickstart docs to change the `CRAFT_CMD_ROOT` setting yields:

`Could not open input file: craft`.

### Steps To Reproduce

1. Have an existing Craft project running in a subdirectory, e.g. `my-project/app`.
2. `ddev config --docroot=app/web --project-type=craftcms --composer-root=app`
3. `ddev start`
4. Import a DB
5. Update the Craft `.env` with `CRAFT_CMD_ROOT=./app`.
6. `ddev restart`
7. `ddev craft`

### Anything else?

For what it's worth, the main issue seems to be that the container has no awareness of that environment variable when it is set via the `.env` file. The `craft` command does work if you set the variable via `ddev config  --web-environment="CRAFT_CMD_ROOT=./app"`. This _seems_ to be a better way to do it in general, since there's a better separation of concerns between DDEV and Craft in that case. This also seems to be the way that some of the existing global web commands handle environment variables. For example, the `blackfire` command recommends setting any environment variables needed by the script via the DDEV global or project-level config.

**Comment by rfay** [comment]
Thanks for raising this issue. `.env` files are not explicitly supported by DDEV, but they probably will be in the future. See https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#providing-custom-environment-variables-to-a-container for how to support .env files.

**Comment by flynnt** [comment]
Oh nice. It will be pretty cool once `.env` files are supported. In the meantime, maybe the resolution for this specific issue as it relates to the `craftcms` project type would be to update the CMS Quickstart documentation to not reference the `.env` file as a way to modify the `CRAFT_CMD_ROOT` setting. Specifically this:

>If you have Craft CMS installed in a sub-directory in your project, you can add a CRAFT_CMD_ROOT environment variable to your .env file to specify a path relative to your project root where Craft CMS is installed.

**Comment by rfay** [comment]
Please do a PR to the doc. You just visit the page https://ddev.readthedocs.io/en/latest/users/quickstart/#craft-cms and click the pencil in the upper left and create a PR that way, thanks.

**Comment by flynnt** [comment]
I'm on it. Thanks!
