### ISSUE TITLE
github version check can result in indefinite hang if no internet or malfunctioning DNS lookups

### ISSUE THREAD

**Issue by rfay** [drud/ddev#431]
## What happened (or feature request):

I was thinking about @tannerjfco 's broken system with ddev unwilling to test, etc. I don't know that this is related to the issue, but it could be. (Tanner may have been using the techniques for minikube from https://stevesloka.com/2017/05/19/access-minikube-services-from-host/, which definitely can break DNS, and probably can break routing in general.)

When ~/.ddev/.update doesn't exist or is expired, we do a call to github to get the list of available ddev releases (using github.com/google/go-github/github).

However, we don't pass in a client struct, meaning that the timeout (which *can* be set) defaults to 0 == infinite wait. So in a system with broken networking or broken DNS lookups, we have really, really bad behavior. 

I think we can solve this by passing in an http client with timeout set to something other than 0. And, report the issue when it happens.

For extra credit: 
* Make sure that all errors on github lookup are correctly reported (they may be)
* Respect an environment variable like DDEV_NO_UPDATE_CHECK that prevents the update check behavior.

## What you expected to happen:

- A timeout should be configured for the github connection
- Ensure that failed github connection reports correctly.
- (stretch) add a variable like DDEV_NO_UPDATE_CHECK that prevents the update check behavior.

## Related source links or issues:

**Comment by rickmanelius** [comment]
For some reason, I thought work already began on this one. Yes/no @nmccrory?

**Comment by rfay** [comment]
Note that this may be difficult to recreate. I think the easiest way to recreate will be to delete the update file and turn off internet. Alternately, put a nonresponding IP address for the github API into /etc/hosts.

**Comment by rickmanelius** [comment]
Given that this hasn't crept up, I'm deprioritizing it. And since it could be a rabbit hole, I'm clearing the assignment because this might need @rfay because he has more visibility into the issue and how to bring it to a completion point.

I'm not sure if a simple ping to a known service (google.com?) could be a test that we run and abort the test if the connection isn't valid.

**Comment by tannerjfco** [comment]
I'd suggest against deprioritizing this issue. My understanding is that this effectively prevents ddev from being used offline, more specifically it requires github API to be available. This issue could show up in a lot of bad network scenarios. It also sounds like most of this should be addressed by defining a timeout value for the github connection, which doesn't seem like it should be a significant lift.

**Comment by rickmanelius** [comment]
Okie dokie. Needs better AC and then we can make actionable.

**Comment by tannerjfco** [comment]
Summarized AC under "What you expected to happen", hope that helps.

**Comment by rfay** [comment]
I don't think this is high-priority necessarily, but agree that a simple timeout on the connection would be an improvement. I think this could be set up and tested, but not sure it needs that much effort.

**Comment by rfay** [comment]
This happened to me again today. ddev just hung on startup. I was only able to get it to start by turning off wifi.

**Comment by rickmanelius** [comment]
Seems like we could address this alongside the public DNS issue.

**Comment by rickmanelius** [comment]
Explicitly linking #416

**Comment by rfay** [comment]
We haven't had reports of this recently, it's old. I'm going to close it until it raises its head again.
