### ISSUE TITLE
Connection timeout in Dockerfile

### ISSUE THREAD

**Issue by adrp** [drud/ddev#4319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

I have a following code in my `.ddev/web-build/Dockerfile`.

```
ARG BASE_IMAGE
FROM $BASE_IMAGE
RUN wget -P /tmp https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.buster_amd64.deb
```
When I try to `ddev start` I'm getting the following error:
```
> [drud/ddev-webserver:v1.21.3-slate-advisers-built  5/11] RUN wget -P /tmp https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.buster_amd64.deb:                                                                                                     
#14 0.487 --2022-10-21 04:32:02--  https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.buster_amd64.deb   
failed: Temporary failure in name resolution.                                                                                                
#14 12.79 wget: unable to resolve host address ‘github.com’
```
Running docker-compose directly doesn't help: `COMPOSE_PROJECT_NAME=project docker-compose -f .ddev/.ddev-docker-compose-full.yaml up --build -d`
In another project internet connectivity also fails in Dockerfile.

Ddev starts without issues after removing the `Dockerfile`. Also, when `ddev` is up, I have no problem with downloading the exactly same resource using  `wget` inside `ddev ssh`.

The problem appear with `ddev@1.21.2`, but at the same time I updated `docker` and `docker-compose`, so not sure where is the problem.

### Expected Behavior

No problem with internet connection.

### Actual Behavior

Connection timeouts.

### Steps To Reproduce

1. Create a `.ddev/web-build/Dockerfile` with:
```
ARG BASE_IMAGE
FROM $BASE_IMAGE
RUN wget -P /tmp https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.buster_amd64.deb
```
1. `ddev start`

**Comment by tyler36** [comment]
@adrp  Thank you for the report.

Unfortunately, I was unable to replicate the issue.

## Test

1. Check current DDEV

    ```shell
    $ ddev --version
    ddev version v1.21.3
    ```

2. Create new DDEV project  with `ddev config` and accept all defaults
    ```shell
    mkdir debug-wget
    cd debug-wget
    ddev config
    ```

3. Start project to confirm DDEV is working.

    ```shell
    $ ddev start
    ...
    Project can be reached at https://debug-wget.ddev.site https://127.0.0.1:63777
    ```

4. Add `.ddev/web-build/Dockerfile`

    ```docker
    ARG BASE_IMAGE
    FROM $BASE_IMAGE
    RUN wget -P /tmp https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.buster_amd64.deb
    ```

5. Restart ddev

    ```shell
    $ ddev restart
    ...
    Your project can be reached at https://debug-wget.ddev.site https://127.0.0.1:63889
    ```

**Comment by tyler36** [comment]
You could try updating to `1.21.3` which was released a couple of dayas ago.

I didn't see debug information which might help with furtther diagnostics.

**Comment by rfay** [comment]
No response, so I'll close this. You're welcome to continue the conversation here or elsewhere. If you give more hints about your setup, we'll be able to help better.
