### ISSUE TITLE
Cannot import "Remove Data"-Snapshot

### ISSUE THREAD

**Issue by rsiudzinski** [drud/ddev#4322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/rsiudzinski/29457d8cba841fc5baa2152bee8978c4#file-ddev-debug-test-txt

### Expected Behavior

The database snapshot gets imported.

### Actual Behavior

The database import fails:

````
ERROR: ASCII '\0' appeared in the statement, but this is not allowed unless option --binary-mode is enabled and mysql is run in non-interactive mode. Set --binary-mode to 1 if ASCII '\0' is expected. Query: ''.
 144KiB 0:00:00 [36.4MiB/s] [>                                                                         ]  2%
Failed to import database db for example: failed to import database: exit status 1
stdout:
stderr:
````

### Steps To Reproduce

1. Create a new Project with Standard-Configuration (In my case, this is [this one](https://gist.github.com/rsiudzinski/29457d8cba841fc5baa2152bee8978c4#file-config-yml).)
2. Fill the Database with dummy-data
3. Delete the project with `ddev delete`
4. Start the Project with `ddev start`
5. Import the Data-Snaspshot from Step 3 via `ddev import-db --src=.ddev/db_snapshots/project-name_remove_data_snapshot_20221023000000-mariadb_10.4.gz`

**Comment by rfay** [comment]
Database snapshots are not importable. You would restore a snapshot with `ddev snapshot restore`. Please try that. 

`ddev import-db` is for importing text-based database dump.

More info in the docs at https://ddev.readthedocs.io/en/latest/users/basics/database_management/

Let me know if you have further questions
