### ISSUE TITLE
File operations in `craftCmsPostStartAction` are not performed when Craft CMS is installed in a subdirectory

### ISSUE THREAD

**Issue by flynnt** [drud/ddev#4329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

When first starting a project with `--project-type=craftcms` after Craft CMS has been installed via `ddev composer create -y --no-scripts --no-install craftcms/craft`, the expectation is that the `.env.example.dev` file is copied and programmatically filled out with `ddev` aware configuration values. Additionally, `composer.json.default` is supposed to be renamed to `composer.json`.

### Actual Behavior

A Craft CMS project is installed, but without a copied and preconfigured `.env` file. `composer.json.default` is not renamed to `composer.json`. This then leads to a failure of the Craft installation script as there is no `.env` file and therefore no database configuration.

### Steps To Reproduce

**Set up a Craft CMS project and specify a subdirectory as the installation location:**
`ddev config --project-type=craftcms --docroot=app/web --create-docroot --composer-root=app --web-environment-add=CRAFT_CMD_ROOT=./app`

**Install Craft:**
`ddev composer create -y --no-scripts --no-install craftcms/craft`

`cd app`

Note the absence of an `.env` file.

### Anything else?

This is most likely due to the way that `craftCmsPostStartAction` is looking for files, e.g.:

`app.AppRoot` may not be the most reliable way to verify a Craft install or to check for the existence of the `.env` or `.env.example.dev` files, since once the Craft installation is in a subdirectory, it's outside `app.AppRoot` as far as DDEV is concerned. Maybe using `app.composerRoot` would be more reliable for these operations, since that is actually where `ddev composer create` puts Craft.

**Comment by flynnt** [comment]
I'll give it a shot. I'll be my first time writing Go. It'll be great. 🙂

**Comment by rfay** [comment]
Some help in https://ddev.readthedocs.io/en/latest/developers/building-contributing/ - would also love improvements to that.
