### ISSUE TITLE
README/docs need Wordpress quickstart and Drupal quickstart paragraphs

### ISSUE THREAD

**Issue by rfay** [drud/ddev#433]
## What happened (or feature request):

It's so easy to get started with an existing repo, we need to motivate and explain to people what to do for each platform. This can be the very beginning of the README.

1. `brew tap install drud/ddev && brew install ddev`
1. `cd myrepo && ddev config`
2. `ddev start`
3. `ddev import-db --src=dumpfile.sql.gz`
4. `ddev describe`

Edit: Adding more context here: People need to know how to set up their repo, either using git or composer, so we need a bit more besides the installation. And it needs to be a bit friendlier than just this checklist.

1. Install ddev (note what's a one-time event)
2. Clone your repo (or build it with composer, probably both options for D8)
3. ddev config
4. ddev start
5. Make sure no settings.php is there (Drupal/WP) so ddev can create one.
6. Optionally ddev import-db (explaining what kinds of dbs can be imported)
7, Visit the local site.

Please make sure to try out every step for every site type.

**Comment by rickmanelius** [comment]
@nmccrory This can be addressed both on the current version of the readme as well as in the readthedocs documentation.

**Comment by rickmanelius** [comment]
This looks good to go. This stanza should be put right before the installation section. Thanks

**Comment by rfay** [comment]
Sorry, I don't think this issue gave enough context about what we need here. I'll update the OP above. We need to have 3 separate sections for D7/D8/Wordpress, and it has to include:

0. Install ddev (note what's a one-time event)
1. Clone your repo (or build it with composer, probably both options for D8)
2. ddev config
3. ddev start
4. Make sure no settings.php is there (Drupal/WP) so ddev can create one.
5. Optionally ddev import-db (explaining what kinds of dbs can be imported)
6, Visit the local site.
