### ISSUE TITLE
`ddev craft install` step of new Craft CMS Composer project creation failing with bootstrap.php error

### ISSUE THREAD

**Issue by olets** [drud/ddev#4338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

<https://gist.github.com/olets/5cf613fe736e1b7325cbd21a0c92b202> (I've ellided some things with `#####`)

### Expected Behavior

Can install Craft CMS following the DDEV docs

### Actual Behavior

Craft CMS installation fails.

### Steps To Reproduce

1. Per https://ddev.readthedocs.io/en/latest/users/quickstart/#craft-cms
    ```shell
    mkdir my-craft-project
    cd my-craft-project
    ddev config --project-type=craftcms --docroot=web --create-docroot
    ddev start
    ddev composer create -y --no-scripts --no-install craftcms/craft
    ddev craft install
    ```

and then I get

```
PHP Warning:  require_once(/var/www/html/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/html/bootstrap.php on line 11

Warning: require_once(/var/www/html/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/html/bootstrap.php on line 11
PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/bootstrap.php:11
Stack trace:
#0 /var/www/html/craft(8): require()
#1 {main}
  thrown in /var/www/html/bootstrap.php on line 11

Fatal error: Uncaught Error: Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/bootstrap.php:11
Stack trace:
#0 /var/www/html/craft(8): require()
#1 {main}
  thrown in /var/www/html/bootstrap.php on line 11
Failed to run craft setup: exit status 255
```

**Comment by rfay** [comment]
I do apologize. I must have made a mistake with a merge conflict, because the `--no-install` shouldn't be in there.

You got this from [latest](https://ddev.readthedocs.io/en/latest/users/quickstart/#craft-cms) docs, which is unreleased, but 
* #4340 
should fix this, please try it (everything the same, just leave out the --no-install)

Also the stable docs quickstart should work fine with current release. https://ddev.readthedocs.io/en/stable/users/quickstart/#craft-cms

**Comment by rfay** [comment]
Doc is fixed, thanks for reporting the problem.

**Comment by olets** [comment]
Confirming that worked! Thank you!

Now I see the stable/latest url and the selector down in the corner, but didn't before and wouldn't have thought anything of it.
