### ISSUE TITLE
Make homebrew installation the default install technique for OSX, document

### ISSUE THREAD

**Issue by rfay** [drud/ddev#434]
## What happened (or feature request):

Installation via homebrew is really easy, and it's what people would expect. We should 
* add the technique to the docs
* probably start maintaining https://github.com/drud/homebrew-ddev via PRs instead of just pushing updates.

Technique for installing via homebrew:

`brew tap drud/ddev && brew install ddev`

Upgrading:  `brew upgrade ddev`

## Related source links or issues:

**Comment by nmccrory** [comment]
This PR was merged. Green light to close the issue? @rickmanelius

**Comment by rfay** [comment]
Shoot, there's more to be done. It seems there's parallel documentation in the docs directory. It would be nice if we figured out a way to DRY this out. The problem here is that https://github.com/drud/ddev/blob/master/docs/index.md repeats the info, and that's what goes into readthedocs.

**Comment by rickmanelius** [comment]
@rfay Looks like two small doc PRs that could potentially be reviewed/approved quickly.

**Comment by rfay** [comment]
Redo fixed in #470
