### ISSUE TITLE
Drupal 10 with PostgreSQL requires pg_trgm extension

### ISSUE THREAD

**Issue by tyler36** [drud/ddev#4341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

Drupal 10 **requires** PostgreSQL 12 or higher with the `pg_trgm` extension enabled. 
For Drupal 9,  `pg_trgm` is recommended, but not required.
See [Database server requirements](https://www.drupal.org/docs/system-requirements/database-server-requirements).

Adding this extension has been raised in the past, but its absence never prevented sites from working.
- #3584
- #3653

Drupal 10 is due out in 2 months, on Dec 2022.

### Expected Behavior

A happy message and working site.

```shell
$ ddev drush si --site-name=debug-pgsql -y
...
 [success] Installation complete.
```

### Actual Behavior

Drupal fails to interact with database and therefore site does not work.

```shell
$ ddev drush si --site-name=debug-pgsql -y
...
Failed to run drush si --site-name=debug-pgsql -y: exit status 1
```

## Fix

Manually enabling the extension resolves issue.

1. Log into database
```shell
$ ddev psql -d db -U db
```

2. Enable extension and exit
CREATE EXTENSION pg_trgm;
exit;
```

3. Install site

```shell
$ ddev drush si --site-name=debug-pgsql -y
...
 [success] Installation complete.
```

### Steps To Reproduce

1. Config DDEV

```shell
mkdir debug-pgsql
cd debug-pgsql
ddev config --project-type=drupal10 --docroot=web --create-docroot --database=postgres:14 --php-version=8.1  
ddev start
...
Project can be reached at https://debug-pgsql.ddev.site https://127.0.0.1:63121
```

2. Create Drupal 10 project

```shell
$ ddev composer create "drupal/recommended-project:^10" --no-install --stability=alpha -y
...
Ensuring write permissions for debug-pgsql
```

3. Add Drush

```shell
$ ddev composer require drush/drush --dev
...
No security vulnerability advisories found
```

4. Attempt site install

```shell
$ ddev drush si --site-name=debug-pgsql -y
 [warning] Undefined array key "value" install.core.inc:2303

In install.core.inc line 2311:

  Database settings:<br /><br />Resolve all issues below to continue the installation. For help configuring your data
  base server, see the <a href="https://www.drupal.org/docs/installing-drupal">installation handbook</a>, or contact
  your hosting provider.<div class="item-list"><ul><li>The <a href="https://www.postgresql.org/docs/current/pgtrgm.ht
  ml">pg_trgm</a> PostgreSQL extension is not present. The extension is required by Drupal 10 to improve performance
  when using PostgreSQL. See <a href="https://www.drupal.org/docs/system-requirements/database-server-requirements">D
  rupal database server requirements</a> for more information.</li></ul></div>


Failed to run drush si --site-name=debug-pgsql -y: exit status 1
```

### Anything else?

- See [Additional Supplied Modules documentation: pg_trgm ](https://www.postgresql.org/docs/current/pgtrgm.html)

**Comment by tyler36** [comment]
Ping @rpkoller for input.

**Comment by rfay** [comment]
Should we change the quickstart, which leaves things in people's hands, or do something more dramatic. the `pg_trm` extension is essentially database alteration, which ddev has not yet taken part in, although
* https://github.com/drud/ddev/issues/4281 
is related, but that's external configuration, not database alteration.

You're fully vindicated now @rpkoller :)
