### ISSUE TITLE
Replace docker-compose with newer `docker compose`

### ISSUE THREAD

**Issue by Firesphere** [drud/ddev#4349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The used `docker-compose` method works just fine, however, it's an older version, and Docker nowadays recommends installing the full `docker compose plugin`, which is more integrated in to the Docker systems.

Most default Docker installations nowadays come with the plugin installed

### Describe your solution

Remove the download and custom installation of `docker-compose` and use `docker compose` plugin

### Additional context

It feels quite a bit a doubling-up of having multiple ways of `docker compose`, self-installed `docker-compose` and the DDEV `docker-compose` hanging around.

**Comment by rfay** [comment]
Docker has been pushing this for a year or two, but there seems to be no known value to it. 

The reason that DDEV uses a custom "vendored" docker-compose is that it uses a tested, stable version. Nearly every new version of docker-compose breaks something, so before the version of DDEV's private docker-compose is used it is fully tested via the full automated test suite.  For example, I recently ran https://github.com/drud/ddev/pull/4256 to see if 2.11.2 would work, and it failed on one architecture.

Please note that neither the `compose` plugin nor an installation of `docker-compose` on your computer is required. 

Maybe you can explain more here. Again, the primary reason that DDEV "vendors" docker-compose is that it's regularly unstable, so we need a version that we know people can use successfully.

**Comment by rfay** [comment]
BTW, `docker compose` isn't a newer version of anything. It's just a different way of executing the same things. If you look at https://github.com/docker/compose/releases you'll see that docker-compose binaries for everything are published. In fact, oddly, you won't see the compose plugin released there.

**Comment by rfay** [comment]
Thinking about this a bit more... this proposal would then require DDEV to vendor the docker client as well as the compose plugin. I think there could be compatibility problems between vendored docker client and the related docker server, but I don't know. I guess I wouldn't mind having the docker client vendored.

**Comment by Firesphere** [comment]
I've never noticed those things you mention, but I trust your experience on it more than my own. Very valid reasoning.

> Please note that neither the compose plugin nor an installation of docker-compose on your computer is required.

Although that's true... it's very probably something most people _do_ have installed by default.

Doesn't matter though. Your logic is sound, I will retract my issue :)
