### ISSUE TITLE
Pantheon Integration: Failure parsing API response leads to fatal error

### ISSUE THREAD

**Issue by dsquaredb** [drud/ddev#435]
## What happened (or feature request):
After successfully installing ddev (ran ddev after installing and got the list of commands), I followed the Quick Start directions for integrating ddev with an existing Pantheon site with these steps:
1. Created a token and authenticated 
2. Git cloned a Pantheon site (polymer-test) into a local directory
3. Made a backup of the dev site on the Pantheon dashboard
4. Changed directories into the local copy of the site
5. Ran 'ddev config pantheon' and got the prompt to enter site name
6. Entered 'polymer-test' and got the following error:

invalid character ‘9’ in literal false (expecting ‘a’)

7. Tried variations of the site name in case I had enetered it incorrectly, but kept getting the same error. Had to terminate the process in the terminal.
8. Manually added ddev to the site and manually added the database and the site and ddev work fine.

9. I repeated this process with another Pantheon site and got the same error message after entering the site name.

## What you expected to happen:
I thought the ddev config Pantheon command would copy the files and database from Pantheon to the ddev site

## Version: Please include the output of `ddev version` and the project's .ddev/config.yaml.
This is the output of ddev version (after manually creating the site):
cli:       	v0.9                                                                                                                                 
web:       	drud/nginx-php-fpm7-local:v0.7.3                                                                                                     
db:        	drud/mysql-local-57:v0.6.2                                                                                                           
dba:       	drud/phpmyadmin:v0.2.0                                                                                                               
router:    	drud/ddev-router:v0.4.3                                                                                                              
commit:    	v0.9                                                                                                                                 
build info:	Built Tue Jul 18 14:21:48 UTC 2017 circleci@prealloc-va1j0mlh-36

This is the output of config.yaml (after manually creating the site):
APIVersion: "1"
name: polymer-test
type: drupal7
docroot: ""
webimage: drud/nginx-php-fpm7-local:v0.7.3
dbimage: drud/mysql-local-57:v0.6.2
dbaimage: drud/phpmyadmin:v0.2.0
provider: default

**Comment by rfay** [comment]
Hi @dsquaredb - Was the Pantheon name of the site itself "polymer" or "polymer-test"? Would appreciate it if you could just humor me by checking for sure on their dashboard. The exact name of the site is the one shown on the bottom. ( I know you know that, I'm just surprised I can't recreate the error.)

![randy_fay___pantheon_dashboard](https://user-images.githubusercontent.com/112444/29254330-a2fbfb92-8050-11e7-9727-d30aa8adeaa4.png)

I guess you didn't get to the question about which environment dev/staging/prod.

I tried this with my pantheon site "rfay-drupal8" thinking that maybe the "-" was problematic, but couldn't get that problem. It's possible that -test is somehow problematic.

**Comment by dsquaredb** [comment]
Okay, here you go...

On my Pantheon dashboard, the site name (just above Sandbox like in your image) is 'Polymer Test' with caps and space. When I access the dev of this site, the URL is http://dev-polymer-test.pantheonsite.io/ When I got the error, I tried several variations of the site nam (polymer test, polymertest, etc.) but I don't think I ever tried Polymer Test.

The name of the other site I attempted to spin up with ddev is "Physicians" again with cap. When I access the dev of this site, the URL is http://dev-physicians.pantheonsite.io/

And sorry, I must have missed the part about environment. Both times I used the dev environments.

**Comment by rfay** [comment]
Thanks so much - I'm suspecting I haven't ever used a Pantheon site name that had spaces in it, and that your "real name" may have the space (and caps) in it "Polymer Test". I probably won't be able to try that tonight, but it's sure a valid situation! Thanks so much for this. And @beeradb thinks I'm the only one that always comes up with new ways to break everything!

**Comment by dsquaredb** [comment]
Just tried spinning up two other Pantheon sites - a D7 site with the site name ’nchla’ and a D8 site named ’targetpharma’. Thought maybe it could be a version thing, too. Got the same error.  So that may rule out the space and caps arguments. - at least on my setup.

Just call me the “Queen of Breaking Things.” If it can’t be broken, I can break it.

**Comment by rfay** [comment]
Thanks so much for all the help on this.

I'm trying to recreate your experience with a similarly named site. I assume when you say "You were prompted to enter the site name" you meant "to enter the project name", like this, and that you just hit RETURN?

```
$ ddev config pantheon
Creating a new ddev project config in the current directory (/Users/rfay/workspace/polymer-test-2)
Once completed, your configuration will be written to /Users/rfay/workspace/polymer-test-2/.ddev/config.yaml


Project name (polymer-test-2):
```

And then you never got to the next prompt about the docroot, because it had all blown up by that point?

```
The docroot is the directory from which your site is served. This is a relative path from your application root (/Users/rfay/workspace/polymer-test-2)
You may leave this value blank if your site files are in the application root
Docroot Location:
```

And it never prompted you for the import environment:
```
Found a drupal8 codebase at /Users/rfay/workspace/polymer-test-2

Configure import environment:

	- live
	- test
	- dev

Type the name to select an environment to import from (dev):
```

Shucks, I think I've failed to recreate the error.

**Comment by rfay** [comment]
Just grasping for straws here, could you please provide the output of 
`docker version` and `docker-compose version`?  I have "17.06.0-ce" and "docker-compose version 1.14.0" on the clean test mac I used.  I don't *think* docker is even used by the point of your failure.

**Comment by dsquaredb** [comment]
MacBook-Pro-7:~ ddbow$ docker version
Client:
 Version:      17.07.0-ce-rc2
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   36ce605
 Built:        Mon Aug  7 23:43:03 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.07.0-ce-rc2
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   36ce605
 Built:        Mon Aug  7 23:48:34 2017
 OS/Arch:      linux/amd64
 Experimental: true

MacBook-Pro-7:~ ddbow$ docker-compose version
docker-compose version 1.15.0, build e12f3b9
docker-py version: 2.4.2
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016

**Comment by dsquaredb** [comment]
Yes, I hit Return. I also tried with typing in the name of the sites. 

MacBook-Pro-7:targetpharma ddbow$ ddev config pantheon

Creating a new ddev project config in the current directory (/Users/ddbow/ddev/targetpharma)
Once completed, your configuration will be written to /Users/ddbow/ddev/targetpharma/.ddev/config.yaml


Project name (targetpharma): 
invalid character '9' in literal false (expecting 'a')
Project name (targetpharma): 

When I hit enter or type in the site name, I get the error and have to close the terminal to get out of it.

**Comment by rfay** [comment]
Thanks so much for sharing with us - we can easily recreate now. I can even recreate it with my own sites that previously worked.

**Comment by rickmanelius** [comment]
Once we have traced the issue, we can figure out the level of effort to address and then we can get this planned/scheduled. Thanks!

**Comment by rickmanelius** [comment]
Updated to actionable and put into our project board!

**Comment by nmccrory** [comment]
@beeradb and I traced this issue back to a field in the Pantheon API response that was being converted to the wrong type (jsonInt64 instead of string). This should be a relatively easy fix. We're working on this now and hope to have an update soon!

**Comment by rfay** [comment]
@nmccrory when you fix that, please make sure to wrap the error at every point it needs to be wrapped so it gives adequate context if something goes wrong in the future. Thanks!

**Comment by beeradb** [comment]
This is fixed as of #439.

**Comment by dsquaredb** [comment]
Sorry to comment on a closed issue, but wanted all involved to know that ddev/pantheon is working great for me with this fix. Thanks!

**Comment by rfay** [comment]
Awesome - we *thank* you for commenting on this closed issue!
