### ISSUE TITLE
Mailhog 1025 Port Not Available to Other DDev Services

### ISSUE THREAD

**Issue by timnolte** [drud/ddev#4353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I have a headless CMS setup with the CMS running in a different service. The Mailhog service doesn't run as it's own Docker services and only runs in the `web` container and other than the web GUI port nothing else is exposed to other Docker services. This means that I am unable to use the Mailhog service locally for testing email functionality in any other DDev services, like our CMS backend service. Simply trying to add to our custom service's Docker Composer file an entry for the `web` service to `expose` port `1025` doesn't work and just results in a Connected Refused error when attempting to use it.

### Describe your solution

The Mailhog service should either be it's own standalone service, or expose the SMTP port 1025 in the `web` service to all Docker services.

**Comment by rfay** [comment]
You can change this in your config.yaml with 
```yaml
web_environment:
- MH_SMTP_BIND_ADDR=0.0.0.0:1025
```

Could you please give that a try and see if it solves it for you? It may be reasonable to change the default as long as it has no security implications, which I don't think it would. https://github.com/drud/ddev/blob/master/containers/ddev-webserver/Dockerfile#L168

**Comment by timnolte** [comment]
@rfay ha, thanks for this. After some persistence I finally cam across that configuration item in the Mailhog configs and added it into a `docker-compose.override.yml` and confirmed it is working. I think leaving things as-id is probable the best course as I think if you have multiple DDev projects tring to run Mailhog bound to all interfaces you'll run into problems with failures and port in use issues in the DDev network.

**Comment by rfay** [comment]
You don't need to do the `docker-compose.override.yaml`, but of course there's no harm done with that. Just putting it in config.yaml does the job. 

And this environment variable only determines what mailhog does *inside* the container, whether it binds only to localhost inside or also to the container's external interface. It wouldn't have any impact on multiple projects.

**Comment by rfay** [comment]
Glad it's working for you. This should do no harm. I'll close for now though as nobody has ever come across this before.
