### ISSUE TITLE
Disable or hide unused GitHub features

### ISSUE THREAD

**Issue by mattstein** [drud/ddev#4355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

DDEV’s GitHub repository features links to _Projects_ and a _Wiki_ that aren’t really in use, taking attention away from far more important things.

Projects contains only a “DDEV-Local Sprint Board” that was closed in 2020, and the Wiki obscures a semi-useful list of previous releases—which you must expand the navigation to reach—and a Roadmap page with a broken link to version history.

Further, the project’s landing page features an unused “Packages” section and a questionable “Used by” list with one reference. The “Environments” section points to GitHub Pages documentation, and should probably be removed in favor of the documentation link at the top of the sidebar.

### Describe your solution

- [x] disable mostly-unused _Projects_ and _Wiki_ features
- [x] hide _Packages_, ~~_Used by_~~, and _Environments_ sections on the GitHub Project’s landing page

While we’re here, it wouldn’t hurt to update the project’s labels:

- [x] remove `ddev-local`
- [x] add `moodle`
- [x] add `craftcms`

And maybe update the short description:

> ~~DDEV: a local web development environment system for PHP~~

> Docker-based local PHP web development environments

The “DDEV” is redundant in this context, “system” is of questionable value since this is clearly an application on GitHub, and we can rearrange to be a little more terse without losing meaning. The “Docker” part feels important enough to add. Environments can be plural since the ability to have lots of them is an important feature!

### Describe alternatives

I honestly did not consider alternative solutions.

### Additional context

Related to #4188.

## Main navigation

![Screen Shot 2022-10-31 at 01 29 43 PM@2x](https://user-images.githubusercontent.com/2488775/199104373-00ef9964-5a50-4ac7-8522-2d4f8f57faf3.png)

## Sidebar

<img src="https://user-images.githubusercontent.com/2488775/199104598-702e9333-2f4e-4e12-af27-5bf1d2e0368c.png" width="250"/>

**Comment by rfay** [comment]
I fiddled with the tags, but had to remove some. 

Removed project-level "project" and wiki. 

No idea how to get rid of packages and "used-by". We could probably ask the owner of that repo to remove that.

**Comment by mattstein** [comment]
Ha! An admin should see a little gear icon on the landing page. It’ll open a modal where you can toggle features just beneath the topics.

<img width="200" src="https://user-images.githubusercontent.com/2488775/199108869-053d68ce-351a-4d93-9ef4-67a5ce51f3f6.png">

<img width="193" alt="Screen Shot 2022-10-31 at 01 54 49 PM@2x" src="https://user-images.githubusercontent.com/2488775/199108875-1341a062-8fbb-4d0b-80de-e8cd498eafb4.png">

**Comment by mattstein** [comment]
I’m also seeing

> Docker-based local PHP+NodeJS web development environments

Where `NodeJS` should be `Node.js` if we’re being consistent.

**Comment by rfay** [comment]
Got everything but "used by" then.

**Comment by rfay** [comment]
* https://github.com/iammati/ddev-userinterface-vue/issues/3
