### ISSUE TITLE
Create new release of nginx container

### ISSUE THREAD

**Issue by beeradb** [drud/ddev#436]
## What happened (or feature request):
We added some improvements to our nginx container at https://github.com/drud/docker.nginx-php-fpm-local and didn't roll a release. The most important of these changes is bypassing the drush prompts when running commands via `ddev exec`.

## What you expected to happen:
Let's get an updated release of that container rolled, and update ddev to ensure it's using that release.

This will involves the followup updates:
- Pushing a `v0.7.4` tag to https://github.com/drud/docker.nginx-php-fpm-local
- Running `make push` on the nginx-php-fpm-local repo after pushing the tag
- Updating the `/pkg/version/version.go` file of ddev to use the new tag.

**Comment by rickmanelius** [comment]
Tagging w/v1.0.0. Thanks, @beeradb!
