### ISSUE TITLE
Nit: Consider improving text on "ddev config" - don't offer pull if not correct

### ISSUE THREAD

**Issue by rfay** [drud/ddev#437]
## What happened (or feature request):

A `ddev config` results in this message even when `ddev pull` is inappropriate:

```
Found a drupal7 codebase at /Users/rfay/workspace/randyfay.com
Configuration complete. You may now run `ddev start` or `ddev pull`
Initial configuration file written successfully. See the configuration file for additional configuration options.
```

We should consider improving the message based on context, and only showing it when a provider plugin is in use.

## Related source links or issues:

**Comment by rickmanelius** [comment]
Seems like a quick win. Actionable.

**Comment by rickmanelius** [comment]
@rfay Looks like this is ready to close?
