### ISSUE TITLE
Cannot run "ddev auth ssh" on MacOS because the operation is not permitted

### ISSUE THREAD

**Issue by jepster** [drud/ddev#4374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/jepster/b58434f2235fd8a7b38716fee7e8f75b

### Expected Behavior

I run 
```
ddev auth ssh
```
and afterwards DDEV is using the SSH keys from my MacOS host machine. Then I can access private repositories by executing the following command from the DDEV container:
```
composer update
```

### Actual Behavior

I would like to use my local ssh certs inside DDEV (via ddev ssh). Therefor I am using the following command:
```
ddev auth ssh
```

However, I am getting the following error message:
```
(base) majmesku@nb100 ~/dev/project (feature/WO-396-updates) $ ddev auth ssh
cp: cannot access '/tmp/sshtmp/old_cert': Operation not permitted
Docker command 'docker [run -it --rm --volumes-from=ddev-ssh-agent --user=501 --entrypoint= --mount=type=bind,src=/Users/majmesku/.ssh,dst=/tmp/sshtmp drud/ddev-ssh-agent:v1.20.0-built bash -c cp -r /tmp/sshtmp ~/.ssh && chmod -R go-rwx ~/.ssh && cd ~/.ssh && ssh-add $(file * | awk -F: "/private key/ { print \$1 }")]' failed: exit status 1
```

I have already tried to set permissions or run DDEV by sudo. E.g.:
```
sudo chmod -R 777 /tmp
sudo ddev auth ssh
```

### Steps To Reproduce

1. Make sure you are using macOS Monterey (Version 12.6)
2. Run `ddev auth ssh`

**Comment by rfay** [comment]
I see you're using Docker Desktop - Is it possible you don't have your home directory shared in Docker Desktop? If you move your keys to a temp directory that is shared in Docker Desktop, does that make a diference (use `ddev auth ssh -d /your/shared/temp/dir`) ?

Although there haven't been any changes in this area it would be kind if you use the current stable version, v1.21.3.

**Comment by rfay** [comment]
Oh, you have an item there that isn't a cert, don't you. Is `old_cert` and actual cert? Does the problem go away if you delete it (or just move it to another directory?)

**Comment by rfay** [comment]
But I think it's really that you don't have your home directory shared via docker. If you update that, or just add ~/.ssh as a share, I imagine it will work.

**Comment by jepster** [comment]
@rfay Thanks for your quick and profund response. I have resolved it by your help. There was a folder in my `~/.ssh` folder as you have noticed. I have removed this folder and afterwards I could execute `ddev auth ssh`.

Maybe it would be a good improvement, if `ddev` could recognize subfolders in the `~/.ssh` directory.

**Comment by rfay** [comment]
Yay, glad it's working for you!
