### ISSUE TITLE
New ddev-selenium-standalone-chrome service now available

### ISSUE THREAD

**Issue by weitzman** [drud/ddev#4375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

FYI it lives at [ddev-selenium-standalone-chrome](https://github.com/weitzman/ddev-selenium-standalone-chrome). Lets make it official once folks are happy with the docs and tests.

### Describe your solution

n/a

### Describe alternatives

n/a

**Comment by rfay** [comment]
Awesome!

**Comment by davereid-pfg** [comment]
I'm curious what the differences are between `seleniarm/standalone-chromium:4.1.4-20220429` and `drupalci/chromedriver:production` which we've been using to run webdriver as per https://mglaman.dev/blog/running-drupals-functionaljavascript-tests-ddev

**Comment by rfay** [comment]
drupalci/chromedriver has never had arm64 images pushed, see https://hub.docker.com/r/drupalci/chromedriver/tags, so can't be used on mac M1 or other arm64 situations.

There is also no info on dockerhub about what its source is.

**Comment by tyler36** [comment]
Just want to say thanks to @weitzman for this.
I was able to get AJAX functionalJavascipt tests working with.

Well done!

**Comment by weitzman** [comment]
I've tagged this repo with 1.0.0. I humbly request that this project be added to the official list for `ddev get list`

**Comment by rfay** [comment]
Thanks @weitzman - I made you an owner of https://github.com/ddevlocal. Please transfer the repo to ddevlocal, and then I'll transfer it to drud and we can do the needed cleanup. (It's really hard to transfer a personal repo to an org without org privs, so ddevlocal is a spare org just used for moving things like this.)

**Comment by weitzman** [comment]
Transferred.

**Comment by rfay** [comment]
It's there now! Just some cleanup needed to make sure that tests and docs refer to the right repository.  Mostly global search/replace weitzman/drud will do it.

https://github.com/drud/ddev-selenium-standalone-chrome

Thanks so much for this!

**Comment by rfay** [comment]
Don't forget new release. Thanks!

**Comment by rfay** [comment]
https://twitter.com/randyfay/status/1594727611195760644
