### ISSUE TITLE
Updating Node version with nvm is failing

### ISSUE THREAD

**Issue by stefanfrede** [drud/ddev#4376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/stefanfrede/c7bffd4264661dc020dacf3db9b1ac0a

### Expected Behavior

Using `nvm` changes the Node version.

### Actual Behavior

When installing a Node version with `nvm` and switching to it `ddev exec node --version` is sticking to whatever version is installed in the container.

### Steps To Reproduce

1. ddev nvm install 18.12
2. ddev exec node --version
> v14.21.1
3. ddev ssh
4. node --version
> v18.12.1

**Comment by rfay** [comment]
Thanks for the issue. I'm pretty sure this is a regression.

**Comment by rfay** [comment]
Ah, I think both you and I misunderstood nvm. 

`ddev nvm install 18.12` will install a node version. If it's the first use, it sets that as default.
`ddev nvm use 18.12` will set node 18.12 as the default node *for the current terminal session*
`ddev nvm alias default 18.12` actually sets 18.12 as the default for next use.

Please give it a try. I think if you `ddev nvm install 18.12 && ddev nvm alias default 18.12 && ddev exec node --version` you'll see `v18.12.1`

**Comment by stefanfrede** [comment]
Thank you very much! That did the trick :smile:
