### ISSUE TITLE
ddev drush needs to support php 8.1 to avoid Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /var/www/html/vendor/consolidation/site-alias/src/SiteSpecParser.php on line 144

### ISSUE THREAD

**Issue by therobyouknow** [drud/ddev#4382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

ddev version v1.21.3

robdavisprojects@Workstation-W64:~/Work/probonoclients/internationalgospelchoir.uk/sites/ligc-dev$ ddev debug test
Running bash [-c /tmp/test_ddev.sh]
OS Information: Linux Workstation-W64 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
User information: uid=1000(robdavisprojects) gid=1000(robdavisprojects) groups=1000(robdavisprojects),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),117(netdev),1001(docker)
DDEV version:  ITEM             VALUE
 DDEV version     v1.21.3
 architecture     amd64
 db               drud/ddev-dbserver-mariadb-10.4:v1.21.3
 dba              phpmyadmin:5
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.3
 docker           20.10.21
 docker-compose   v2.10.2
 docker-platform  docker-desktop
 mutagen          0.16.0
 os               linux
 router           drud/ddev-router:v1.21.3
 web              drud/ddev-webserver:v1.21.3
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
mutagen-enabled=false
nfs-mount-enabled=false
router-bind-all-interfaces=false
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
auto-restart-containers=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=
use-docker-compose-from-path=false
no-bind-mounts=false
project-tld=

======= DOCKER info =========
docker location: lrwxrwxrwx 1 root root 48 Nov 14 11:46 /usr/bin/docker -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker
docker version:
Client: Docker Engine - Community
 Cloud integration: v1.0.29
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:28 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:19 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
DOCKER_DEFAULT_PLATFORM=notset
======= Mutagen Info =========
======= Docker Info =========
Docker platform: docker-desktop
Using docker context: default (unix:///var/run/docker.sock)
docker-compose: v2.10.2
Using DOCKER_HOST=unix:///var/run/docker.sock
Docker version: 20.10.21
Able to run simple container that mounts a volume.
Able to use internet inside container.
Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                 251.0G     12.7G    225.4G   5% /

Container ddev-ligc-develop-dba  Removed
Container ddev-ligc-develop-db  Removed
Container ddev-ligc-develop-web  Removed
Network ddev-ligc-develop_default  Removed
Project ligc-develop has been stopped.
The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again.
Existing docker containers:
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
Creating a new ddev project config in the current directory (/home/robdavisprojects/Work/probonoclients/internationalgospelchoir.uk/sites/tryddevproject-5266)
Once completed, your configuration will be written to /home/robdavisprojects/Work/probonoclients/internationalgospelchoir.uk/sites/tryddevproject-5266/.ddev/config.yaml

Configuring unrecognized codebase as project type 'php' at /home/robdavisprojects/Work/probonoclients/internationalgospelchoir.uk/sites/tryddevproject-5266/web
Configuration complete. You may now run 'ddev start'.
Network ddev_default created
Starting tryddevproject-5266...
Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
Pushed mkcert rootca certs to ddev-global-cache/mkcert
v1.21.3: Pulling from drud/ddev-dbserver-mariadb-10.4
fb0b3276a519: Already exists
825c4435e9b4: Already exists
c48535fb256b: Already exists
65142e3bf01b: Already exists
c994327ef3cc: Already exists
40d12c21872a: Already exists
dd18621bd4ea: Already exists
e6ca5edbc07b: Pull complete
641a5a3e68f4: Pull complete
4cfed758962f: Pull complete
56c5e9224b41: Pull complete
6b3c3e229eaa: Pull complete
4f4fb700ef54: Pull complete
b558e546cd59: Pull complete
1096e11c45c7: Pull complete
e834b2ce8a35: Pull complete
2471d4807267: Pull complete
31ce89a46be8: Pull complete
bf4e07ce9440: Pull complete
b609af14d61e: Pull complete
c75172fd45dc: Pull complete
4e6e3aaf2990: Pull complete
5685893e04d6: Pull complete
bce314026fd5: Pull complete
ba59cf931afd: Pull complete
82d39d80a2cc: Pull complete
Digest: sha256:49fd0139b4790a8c8f2dd790d15b9e4ddc43cf6cb4039dc9ff8ad7b37cdf883c
Status: Downloaded newer image for drud/ddev-dbserver-mariadb-10.4:v1.21.3
docker.io/drud/ddev-dbserver-mariadb-10.4:v1.21.3
Network ddev-tryddevproject-5266_default  Created
Container ddev-tryddevproject-5266-dba  Started
Container ddev-tryddevproject-5266-web  Started
Container ddev-tryddevproject-5266-db  Started
Container ddev-router  Started
Successfully started tryddevproject-5266
Project can be reached at https://tryddevproject-5266.ddev.site https://127.0.0.1:52514
======== Curl of site from inside container:
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 15 Nov 2022 01:27:10 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== Curl of site from outside:
HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Tue, 15 Nov 2022 01:27:10 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== Project ownership on host:
drwxr-xr-x 4 robdavisprojects robdavisprojects 4096 Nov 15 01:26 ../tryddevproject-5266
======== Project ownership in container:
drwxr-xr-x 4 robdavisprojects robdavisprojects 4096 Nov 15 01:26 /var/www/html
======== In-container filesystem:
Filesystem     Type 1K-blocks    Used Available Use% Mounted on
/dev/sdd       ext4 263174212 6635152 243100904   3% /var/www/html
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-5266'
Thanks for running the diagnostic. It was successful.
Please provide the output of this script in a new gist at gist.github.com
Running ddev launch in 5 seconds
If you're brave and you have jq you can delete all tryddevproject instances with this one-liner:
    ddev delete -Oy $(ddev list -j |jq -r .raw[].name | grep tryddevproject)
In the future ddev debug test will also provide this option.

Please delete this project after debugging with 'ddev delete -Oy tryddevproject-5266'

### Expected Behavior

ddev drush works as normal

### Actual Behavior

ddev drush gives fatal error

Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /var/www/html/vendor/consolidation/site-alias/src/SiteSpecParser.php on line 144
PHP Deprecated:  preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /var/www/html/vendor/consolidation/site-alias/src/SiteSpecParser.php on line 144

### Steps To Reproduce

Run ddev drush in usual ddev setup

### Anything else?

I fixed this manually, making use of the solution here: https://github.com/consolidation/site-alias/issues/48

![image](https://user-images.githubusercontent.com/1080646/201802782-410153d0-ae14-4350-90e1-de0cb1660965.png)

But the ideal solution is that this needs to be fixed in the drush that runs inside ddev docker containers.

**Comment by therobyouknow** [comment]
This can also be solved by deleting `.ddev` folder and also deleting the ddev project and then running `ddev config`.

After which, I edited `config.yml` to have `php` at version `8.1`. Which is the same version as on Ubuntu 22.04 by default which is my production server.

**Comment by tyler36** [comment]
This is not a DDEV issue.  
DDEV does not install or manage Drush. 

## Steps

1. Configure DDEV

    ```shell
    ddev config --project-type=drupal9 --docroot=web --create-docroot --php-version=8.1
    ```

2. Install Drupal

    ```shell
    ddev composer create "drupal/recommended-project" -y
    ```

3. Install Drush

    ```shell
    ddev composer require drush/drush --dev
    ```

4. Use Drush to configure Drupal

    ```shell
    ddev drush si --site-name=drush-ddev-debug -y
    ```

5. Confirm site works

**Comment by rfay** [comment]
You most likely had the wrong project type, `ddev config` detected the correct project type.

**Comment by leymannx** [comment]
`composer update drush/drush -W` fixed it for me.

**Comment by la558** [comment]
`composer update drush/drush -W`
did not make any difference
still having the same issue

**Comment by rfay** [comment]
Hi @la558 - Please use `ddev composer`.  And make sure your .ddev/config.yaml has php 8.1 in it.

**Comment by la558** [comment]
Thanks for your response.

I've installed ddev :

ddev version v1.21.6


Just, so you know, I'm NOT running my Drupal site inside Docker.

Does your recommendation still apply?

When you say to run:

> ddev composer
>

you mean:

> ddev composer update consolidation/* --with-dependencies
>

Best,

--

Laura Addiego Prospero  |  Software Application Developer - Software
Engineer

GEORGETOWN LAW  | ***@***.***

600 New Jersey Avenue, N.W.  |  Washington, D.C. 20001

Phone: 202.662.9142

Website <http://www.law.georgetown.edu/> |  Facebook
<https://www.facebook.com/georgetownlaw/>  |  Twitter
<https://twitter.com/georgetownlaw>  |  YouTube
<https://www.youtube.com/user/GeorgetownLawChannel>  |  LinkedIn
<https://www.linkedin.com/edu/georgetown-university-law-center-18052>  |
Instagram <https://www.instagram.com/gtownlaw/>

**Comment by la558** [comment]
FYI - I'm running consolidation/site-alias version 4.0.0
"name": "consolidation/site-alias",
"version": "4.0.0",
This is what my current function looks like, and it's giving me the error:

[image: Screen Shot 2023-03-29 at 11.30.24 AM.png]

Best,

--

Laura Addiego Prospero  |  Software Application Developer - Software
Engineer

GEORGETOWN LAW  | ***@***.***

600 New Jersey Avenue, N.W.  |  Washington, D.C. 20001

Phone: 202.662.9142

Website <http://www.law.georgetown.edu/> |  Facebook
<https://www.facebook.com/georgetownlaw/>  |  Twitter
<https://twitter.com/georgetownlaw>  |  YouTube
<https://www.youtube.com/user/GeorgetownLawChannel>  |  LinkedIn
<https://www.linkedin.com/edu/georgetown-university-law-center-18052>  |
Instagram <https://www.instagram.com/gtownlaw/>

**Comment by rfay** [comment]
If you're not using DDEV, you're in the wrong place. If you're running Drupal somewhere other than in ddev/docker, why are you asking here?

**Comment by la558** [comment]
After updating to PHP 8.1.17,
Whenever I run any drush command, I get:

PHP Deprecated:  preg_match(): Passing null to parameter #2 ($subject) of
type string is deprecated in
<path_to_drupal_site>/vendor/consolidation/site-alias/src/SiteSpecParser.php
on line 144


in the 'composer.lock' file states the url for support > issues

"support": {
> "issues": "https://github.com/consolidation/site-alias/issues",
> "source": "https://github.com/consolidation/s"
> },
>
Best,

--

Laura Addiego Prospero  |  Software Application Developer - Software
Engineer

GEORGETOWN LAW  | ***@***.***

600 New Jersey Avenue, N.W.  |  Washington, D.C. 20001

Phone: 202.662.9142

Website <http://www.law.georgetown.edu/> |  Facebook
<https://www.facebook.com/georgetownlaw/>  |  Twitter
<https://twitter.com/georgetownlaw>  |  YouTube
<https://www.youtube.com/user/GeorgetownLawChannel>  |  LinkedIn
<https://www.linkedin.com/edu/georgetown-university-law-center-18052>  |
Instagram <https://www.instagram.com/gtownlaw/>

**Comment by rfay** [comment]
Please go to Drupal.org or wherever you want, but if you're not using DDEV to run Drupal, you're in the wrong place.
