### ISSUE TITLE
Running phpunit with WordPress (and testing a plugin)

### ISSUE THREAD

**Issue by Ebeldev** [drud/ddev#4383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

I wanted to know if there is a way to setup or guide on how to setup a WordPress plugin to use the phpunit with DDEV ?

So far my reasearch and tests have not been successfull. 

Thank you for your help, 

### Expected Behavior

I want to use the wp cli scaffold command with the use of their script to install and use phpunit. 

But it does not work. 

### Actual Behavior

I want to setup a WordPress plugin to include phpunit tests. 

### Anything else?

I wanted to know if there is a way to setup or guide on how to setup a WordPress plugin to use the phpunit with DDEV ?

So far my reasearch and tests have not been successfull. 

Thank you for your help,

**Comment by rfay** [comment]
Do you already have the phpunit tests in there? Have you composer-installed phpunit?

**Comment by rfay** [comment]
You need phpunit in your code's vendor directory. Install it with composer.  Having it on your computer is not relevant. The code in the container cannot access anything on your computer. 

Please use `ddev ssh` to start learning about this. When you can use `phpunit` in there, then you are ready to start.

**Comment by rfay** [comment]
phpunit when installed is usually in vendor/bin/phpunit, for example. see https://github.com/weitzman/ddev-selenium-standalone-chrome and its readme.

**Comment by rfay** [comment]
@mandrasch can you offer any help here? (@mandrasch is an expert with WP and DDEV)

**Comment by Ebeldev** [comment]
@rfay I forgot to mentionned it, I also did try it in ssh in the container. 

Here is the error when I then start my unit tests. 

mac-dw-eti@rabaischocs-web:/var/www/html/wp-content/plugins/rc-reports$ ./vendor/bin/phpunit 
Could not find /tmp/wordpress-tests-lib/includes/functions.php, have you run bin/install-wp-tests.sh ?

I did follow the setup instruction : https://pippinsplugins.com/unit-tests-wordpress-plugins-setting-up-testing-suite/.  you set up wordpress with phpunit, with the wp cli it uses a bash script. After the script has been run. And then try to do any unit test I get the error mentionned. 

From our understanding the error would be in the bash script. The script seems to not know it's in a container.

**Comment by Ebeldev** [comment]
@rfay By the way, I really like working with ddev.

**Comment by rfay** [comment]
Have you run bin/install-wp-tests.sh? 

It seems to install something in /tmp/wordpress-tests-lib, and /tmp is a volatile directory in ddev (it gets recreated on every start)

**Comment by Ebeldev** [comment]
Yes I did run bin/install-wp-tests.sh command.

**Comment by rfay** [comment]
No response after quite some time, I'll convert this to a discussion.
