### ISSUE TITLE
export-db should automatically stop the project if after automatically starting it

### ISSUE THREAD

**Issue by mikehayesuk** [drud/ddev#4385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When running the `export-db` command, the project is automatically started if necessary. However the project isn't automatically stopped afterwards.  I want to be able to loop through a bunch of projects, exporting the database for each of them, without worrying about the projects being left running afterwards.

For comparison, when taking a snapshot, if the project is automatically started then it's automatically stopped afterwards.

### Describe your solution

I think it would make sense for `export-db` to stop the project after completing the export (where the project has been automatically started), this would make the command consistent with snapshots.

**Comment by rfay** [comment]
I recommend `ddev snapshot --all`, which has the behavior you suggest, and is also easier because you don't have to tell it where to put the dumpfile.

**Comment by mikehayesuk** [comment]
Thanks – I'm using snapshots for daily backups:

```
ddev snapshot --name dailybackup --cleanup --all --yes
ddev snapshot --name dailybackup --all
```

This works well. However I like to dump the SQL too for portability and the (perhaps irrational) desire to see the data in plain SQL, then I can be 100% sure everything is safely backed up 😅  Each has its benefits I guess.

**Comment by rfay** [comment]
You have a script that runs through your projects and exports, right? Why don't you have it stop also?

**Comment by mikehayesuk** [comment]
I wouldn't want to stop a project which was already running if that makes sense. But you're right, I could just parse the project status from `ddev list` beforehand and issue the stop command only where necessary.

I thought it may make sense to make the command behaviour consistent with snapshots, it's a nice touch for snapshots to return projects to their original status. However I appreciate the two features aren't strictly related and there may be other reasons for them working differently.

**Comment by rfay** [comment]
BTW, you can `ddev list -j | jq -r .raw[].name` and do lots of fun things. 

`ddev snapshot --all ` was cleaned up very nicely by @mikebarkas , we can thank him for that - that's where that nice feature came from! If you're interested in taking on a PR to scratch your itch here I'll be happy to coach you :)

**Comment by mikehayesuk** [comment]
That's good to know, thanks. Not sure how I missed the `-j` flag. I'll go this route for now to get things working the way I'm comfortable with for my work set up (have only just began playing with and migrating to ddev).

Thanks for the offer to help! I haven't written any Go before but looking at how the [snapshot command](https://github.com/drud/ddev/blob/10e574e6f4a7776e4605c21831341bd3e816dfbd/cmd/ddev/cmd/snapshot.go#L94-L104) handles this, I don't think a PR is completely out of my league. I'm more likely to have trouble writing the test. I might give it a try when I get a moment and see how it goes.

**Comment by rfay** [comment]
Closing for now, but happy to get a PR. Happy to reopen if others say "me too".
