### ISSUE TITLE
PostgreSQL v9, v10, v11 do not start (due to changes in upstream)

### ISSUE THREAD

**Issue by stasadev** [drud/ddev#4391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Projects with PostgreSQL v9, v10 and v11 should start out of the box.

### Actual Behavior

PostgreSQL v9, v10 and v11 depend on Debian stretch.
But it is not supported now - [Debian stretch is no longer supported](https://www.postgresql.org/message-id/Y2kmqL%2BpCuSZiQBV%40msg.df7cb.de).
You will see an error when starting any project with these versions.

### Steps To Reproduce

1. Create a new project with one of these commands
```
ddev config --database=postgres:9
ddev config --database=postgres:10
ddev config --database=postgres:11
```
2. Start the project.
3. See this error
```text
W: The repository 'http://apt.postgresql.org/pub/repos/apt stretch-pgdg Release' does not have a Release file.
E: Failed to fetch http://apt.postgresql.org/pub/repos/apt/dists/stretch-pgdg/main/binary-amd64/Packages  404  Not Found
```

### Anything else?

The current workaround is to add this `pre.Dockerfile` to the project's database build:

```bash
echo "RUN rm /etc/apt/sources.list.d/pgdg.list
RUN apt-get update && apt-get -y install apt-transport-https
RUN echo \"deb https://apt-archive.postgresql.org/pub/repos/apt/ stretch-pgdg main\" > /etc/apt/sources.list.d/pgdg.list
" > .ddev/db-build/pre.Dockerfile
```

And it will start as expected.

**Comment by rfay** [comment]
Looks like there's no intent to maintain these:
* https://github.com/docker-library/postgres/issues/1012

**Comment by stasadev** [comment]
I was upgrading from v10 to v11 due to EOL for v10, and noticed this issue.
I'm just wondering why they haven't updated the repo for v11 in docker if it's not EOL.

**Comment by rfay** [comment]
But it looks like they failed to update the base, just 11-bullseye.

**Comment by rfay** [comment]
Fixed in #4394 - the artifacts will be there for download in a few minutes, would appreciate if you could test. Don't forget to remove your pre-Dockerfile first.

**Comment by stasadev** [comment]
It works nice! I tested 9, 10, 11.

I see you injected my suggestion also to postgres 11, and after that added `ARG BASE_IMAGE=postgres:11-bullseye`.
This argument has no effect, because it is inserted not at the start, and maybe it is better to change it in `.ddev-docker-compose-full.yaml`

**Comment by rfay** [comment]
Oh, I was supposed to remove that. Thanks!

**Comment by rfay** [comment]
Fixed, thanks.

**Comment by rfay** [comment]
As you saw, I decided to just go ahead with the stretch-based postgres:11 image for now.

**Comment by stasadev** [comment]
Ok, good.
