### ISSUE TITLE
Old files left after git-fetch-rebase-push when using Mutagen

### ISSUE THREAD

**Issue by BernhardBaumrock** [drud/ddev#4397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

We are using a git workflow where we work on our own branches for features (here the `bb` branch) and then merge those changes into main after rebasing.

That's a great setup, but doing all the checkouts and rebase stuff manually is tedious, so I have this alias:

```sh
function gitpush() {
    local branch=$1
    if [ -z "$branch" ]; then
        branch="main"
    fi
    git fetch --all
    git checkout $branch
    git pull
    git checkout bb
    git rebase $branch
    git checkout $branch
    git merge bb --no-ff --no-edit
    git push
    git checkout bb
    git merge $branch
    git push -f
}
```

![image](https://user-images.githubusercontent.com/8488586/203327703-d48face3-74b1-4c33-8292-7eeba36c8ee6.png)

### Actual Behavior

The problem is that mutagen somehow gets messed up on almost every `gitpush`. I often end up with old files in the mutagen cache which is really annoying or can at worst cause lots of wasted time trying to fix an issue that is actually not there (as it is only in old versions of files).

I then have to `ddev mutagen reset` and `ddev start` which can take quite long.

Is there something like `ddev mutagen sync` which forces mutagen to just sync all files without actually restarting everything?

If such a feature was there I could add that to my alias and that would be fine I think.

### Steps To Reproduce

Sorry it's hard to reproduce I guess but I can try to provide more information if necessary!

### Anything else?

Thanks for the great project!! Really enjoying to work with it and already promoted it in the ProcessWire community where I'm quite active :) https://processwire.com/talk/topic/27433-using-ddev-for-local-processwire-development-tips-tricks/

**Comment by rfay** [comment]
You skipped the requested step where you do a `ddev debug test` and provide the results, so I don't know anything about your environment, including even knowing what DDEV version you're using. Please provide a link to a gist with the results of `ddev debug test`. 

If you can reproduce this, I can debug it.

You don't say whether you are doing your git activities inside the container or on the host... On the host?

Please note that it takes time for mutagen to finish syncing when you do any massive change. You may want to add a `ddev mutagen sync` after each major step of your recipe, especially the branch checkout and merges.  This is discussed in https://ddev.readthedocs.io/en/latest/users/install/performance/#mutagen-integration-caveats

**Comment by BernhardBaumrock** [comment]
hey @rfay thx that already seemed to help! I've updated my alias to the following:

```
function gp() {
    local branch=$1
    if [ -z "$branch" ]; then
        branch="main"
    fi
    git fetch --all
    git checkout $branch
    ddev mutagen sync
    git pull
    git checkout bb
    ddev mutagen sync
    git rebase $branch
    git checkout $branch
    ddev mutagen sync
    git merge bb --no-ff --no-edit
    git push
    git checkout bb
    ddev mutagen sync
    git merge $branch
    git push -f
}
```

I'll close the issue and reopen it if I still get unexpected results.

**Comment by rfay** [comment]
Glad it's working for you. Note that DDEV v1.21.3 made significant changes to how mutagen is managed, so I'd love to know if you were on 1.21.3.

**Comment by BernhardBaumrock** [comment]
Yeah I'm on 1.21.3 but not sure since when. I'm also not sure since when I'm having the issue... It's been one of those "it's not so bad I'll look into that the other day" things ;) But I guess it's been there all the time (I'm using ddev for around a year now)

**Comment by rfay** [comment]
Thanks!

**Comment by rfay** [comment]
It's not a surprise that mutagen could get overrun by massive changes done rapidly, so your solution is probably the best anyway.

**Comment by rfay** [comment]
However, if you get ambitious and can figure out a shareable reproduction scenario, I'll work with the maintainer of Mutagen on it.

**Comment by BernhardBaumrock** [comment]
hey @rfay thx for your enthusiasm on that. Unfortunately it's really hard to debug and also to share I guess, because it might also be an issue with my sse based live reload feature that kicks in when doing git checkouts (https://www.youtube.com/watch?v=7CoIj--u4ps&t=272s)

I guess it's really an edge-case scenario and if ddev mutagen sync works I'm absolutely fine with that :) It just didn't seem to do anything. Maybe it could confirm that it is done?

**Comment by BernhardBaumrock** [comment]
Yeah, macOS. I'll do so if it pops up again, thx!

**Comment by BernhardBaumrock** [comment]
Hey @rfay unfortunately the issue still pops up, but I'm really lost how I could provide a reproducible setup :(
