### ISSUE TITLE
How can I manage the database version via shared config and have ddev update it automatically?

### ISSUE THREAD

**Issue by davereid-pfg** [drud/ddev#4398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

We control a managed configuration of DDEV via a config.shared.yaml across several sites. This file is managed by composer scaffolding from our Drupal install profile. If I wanted to deploy a database version update to everyone from MariaDB 10.3 to 10.4, this results in requiring every individual developer to run `ddev debug migrate-database mariadb:10.4` locally first before they do a composer update that brings in the new version of the DDEV config file, then they need to do a restart. 

### Describe your solution

Is there a way I can better automate this? I can't add the migrate-database command to a pre-start hook, because again, their current datbase is on 10.3 but the config file says 10.4 and the command errors.

**Comment by rfay** [comment]
The only way I know is to do the `ddev debug migrate-database` *before* changing the config.yaml. You could possibly do it in two steps, first change config.yaml (or add a config.temp.yaml?), then migrate the database.

Perhaps easier to export-db and import-db.

**Comment by davereid-pfg** [comment]
Hrm, I'd need to think about this. I would love if the migrate-database command didn't fail if the current db is 10.3 but the config points to 10.4, or if the migration could automatically use the current version specified in the config somehow.

**Comment by rfay** [comment]
PR is welcome. It's not complicated stuff. The problem may remain that you can't change or start with the different setting. But https://github.com/drud/ddev/blob/c0491ac1d0b1cfc3c7e46b01f7031ecc4ed2fbe0/cmd/ddev/cmd/debug-migrate-database.go#L14

**Comment by rfay** [comment]
Seems like this is a requirement particular to your projects. Thoughts on this are welcome. For now, I'm closing this, but happy to continue the conversation here or elsewhere.
