### ISSUE TITLE
As CLI user, I want the ability to interact with each site from any directory.

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#44]
PROPOSAL STAGE

## What happened (or feature request):

Feature request.

## What you expected to happen:

I would like an optional parameter that allows me to target a ddev working directory from any directory. Example: "ddev describe" when within the working directory or "ddev @PROJECT describe" when anywhere else.

## Anything else do we need to know:

This will require the creation of a global configuration that ddev checks when using the optional @PROJECT parameter. This is similar to how drush works.

**Comment by rickmanelius** [comment]
This already works for ddev stop, rm, and describe. It could probably work for start, but for now I'm going to call this done as it's been handled elsewhere.

**Comment by rickmanelius** [comment]
Good point by @rfay in that we may need to cross check this against new ddev-ui needs.

**Comment by rickmanelius** [comment]
@cyberswat Here was the original issue filed with the request to add an "@app" option prior to the specific ddev command. The discussion in this thread might be a bit out of date given that we've introduced the ability for several other commands to work outside of the app's working directory, and we should revisit.

**Comment by cyberswat** [comment]
It may be worth opening the conversation again.  I ran into this today setting up for a sales call.  I wanted to ddev ssh into containers from outside of the projects root folder.  ```ddev @app ssh``` seemed like it would have been valuable.

**Comment by rfay** [comment]
Many of our commands take the sitename  after the command. Imo all should. Putting the sitename BEFORE the command would be a major breaking change.

**Comment by rfay** [comment]
About the only thing you can't do now is `ddev config` and `ddev start`, I think this is good enough until we feel like revisiting it.
