### ISSUE TITLE
Apache2 uses port 80 by default, conflicting with DDEV default ports, may appear when enabling systemd on WSL2

### ISSUE THREAD

**Issue by tyler36** [drud/ddev#4405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

It's not a feature request, but it's not a bug either.

This morning I updated to the Windows Subsystem for Linux `1.0.0.0` in the Microsoft Store. 
One of the new features I was keen to try was systemd support (which was previously a Win11 only feature).

However, after activating, I found DDEV would not start because port 80 was in use.

It seems enabling systemd automatically starts an apache2 web server which prevents DDEV from working.  I'm not why this is the case or if the apache2 server is nessasary for certain features to function. 

This issue was created to
- see how many people might be affected
- find a solution for DDEV users
- prompt a PR to update automated WSL setup script, as required

## Test 

- Edit  `/etc/wsl.conf` inside a WSL terminal.

```shell
sudo /etc/wsl.conf
```

- Add following lines and save

```conf
[boot]
systemd=true
```

- Restart WSL (from a Windows terminal)

```shell
wsl --shutdown
```

- Wait 10 seconds ([See 8 second rule](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#the-8-second-rule))
- Restart Docker Desktop
- Attempt to start a DDEV project

```shell
$ ddev start
Failed to start d9-demo: Unable to listen on required ports, port 80 is already in use,
```

- Check port usage

```shell
$ sudo lsof -i -P -n | grep LISTEN | grep 80
apache2   445            root    4u  IPv6  24953      0t0  TCP *:80 (LISTEN)
apache2   486        www-data    4u  IPv6  24953      0t0  TCP *:80 (LISTEN)
apache2   487        www-data    4u  IPv6  24953      0t0  TCP *:80 (LISTEN)
apache2   488        www-data    4u  IPv6  24953      0t0  TCP *:80 (LISTEN)
apache2   489        www-data    4u  IPv6  24953      0t0  TCP *:80 (LISTEN)
apache2   490        www-data    4u  IPv6  24953      0t0  TCP *:80 (LISTEN)
```

## Workaround

- Remove apache2 from WSL

```shell
sudo systemctl stop apache2.service
sudo apt remove apache2 -y
```

- Restart WSL 
- Restart Docker Desktop

```shell
$ sudo lsof -i -P -n | grep LISTEN | grep 80

$
```

I am not sure if there is a better way to handle this. It can easily be reinstall so the service is running at startup (and the DDEV conflict is present). 

### Additional context

DDEV `vHEAD-7162dda` with trafiks enabled.
Ubuntu `20.04` via WSL `1.0.0.0` on Win10

**Comment by tyler36** [comment]
For reference, link to [Advanced settings configuration in WSL](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#the-8-second-rule)

**Comment by rfay** [comment]
Isn't systemd great? So wonderful to have snaps working and so many things that were previously missing.

This isn't actually related to WSL2, it's just that you had Apache2 installed for some reason and now with systemd it starts itself. 

This is actually covered and has been for years in the docs, and when you got the message

> Failed to start d9-demo: Unable to listen on required ports, port 80 is already in use,

it gave you the link on the next line to the docs. This is a perpetual problem on regular linux and even on macOS, which sometimes seems to ship with Apache enabled. 

All you have to do is `sudo apt remove -y apache2` to solve this (you don't have to also stop the service). 

Docs at https://ddev.readthedocs.io/en/latest/users/basics/troubleshooting/#web-server-ports-already-occupied

If you think we need to add more to that for people who might have apache or nginx installed but never used on WSL2/Ubuntu, a PR is welcome, but to me it's the same problem as always.

Also, the default Ubuntu you get with `wsl --install` or `wsl --install Ubuntu` does not have Apache installed. So somehow you had it installed.

**Comment by rfay** [comment]
BTW, I find that now that systemd is there it's even a better reason to use docker-ce inside WSL2 instead of using Docker Desktop. And the upcoming v1.21.4 will have the known problems with docker-ce resolved (xdebug).

**Comment by tyler36** [comment]
Thanks for the update.

I don't recall install apache2 but it was perhaps bundled in with something.
I just check the default Ubuntu 22.04 WSL container and the problem didn't occur. 

I think the docs read fine.  👍 

Closing because no action is needed.

**Comment by tyler36** [comment]
Had another report the wide in a Discord thread - [Problems with Port 80 in WSL2 since 1.21.4 with docker-ce](https://discord.com/channels/664580571770388500/1053204717385285773/1053204717385285773)

Discord OP was able to fix it by running: `sudo apt remove -y apache2`

**Comment by rfay** [comment]
Thanks, and thanks for handling that. It seems to me like the error message, with a link to the troubleshooting doc, should get people past this quite quickly, so I'm surprised it's not happening. I guess it must just be redirection; people don't realize what has happened.
