### ISSUE TITLE
Axe CLI Recipe

### ISSUE THREAD

**Issue by bbertucc** [drud/ddev#4406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

[Equalify](https://github.com/bbertucc/equalify) users can't easily run our accessibility app locally because setting up [axe-cli](https://github.com/dequelabs/axe-core-npm/blob/develop/packages/cli/README.md) on ddev (our preferred local environment) is a pain.

### Describe your solution

Create a recipe to setup axe-cli, vis-a-vie the [ddev-selenium-chrome](https://github.com/thunder/ddev-selenium-chrome) recipe. 

### Describe alternatives

Run the [ddev-selenium-chrome](https://github.com/thunder/ddev-selenium-chrome) recipe then bang your head against the wall trying to get axe to run.

### Additional context

If a simple recipe was created, we could offer free and easy WCAG accessibility audits on sites.

**Comment by rfay** [comment]
If it's headless chrome that you're after, how about trying https://github.com/drud/ddev-selenium-standalone-chrome, 
`ddev get drud/ddev-selenium-standalone-chrome` ?

**Comment by rfay** [comment]
It seems that because this is so relevant to at least one team, an add-on will be in the future, but the first step is to make it work. Then get it systematized into an add-on with automated tests.

**Comment by bbertucc** [comment]
I created a [README](https://github.com/bbertucc/axe-equalify/blob/main/README.md#setup-on-linux) with details on getting it working with Linux. I imagine someone could replicate the steps to get @kreynen work working.

FYI.. if this recipe gets finished, I'll probably add it as a basic install requirement for [Equalify](https://github.com/bbertucc/equalify).

**Comment by rfay** [comment]
When you figure it out, please let us know and I hope you'll make a DDEV add-on for it! Thanks! Closing for now, happy to continue the conversation here or elsewhere.
