### ISSUE TITLE
Add Domain to `ddev version` output

### ISSUE THREAD

**Issue by beeradb** [drud/ddev#441]
## What happened (or feature request):
`ddev version` currently prints some great info:

```
git:(master) » ddev version
cli:           v0.9-18-ga5514aa
web:           drud/nginx-php-fpm7-local:v0.7.3
db:            drud/mysql-local-57:v0.6.2
dba:           drud/phpmyadmin:v0.2.0
router:        drud/ddev-router:v0.4.3
commit:        v0.9-18-ga5514aa
build info:    Built Tue Aug 22 15:11:01 MDT 2017 beeradb@Brads-MacBook-Pro-3.local drud/golang-build-container:v0.4.2
```

As we build a GUI for DDEV, we'll need a way to pass additional configuration items such as the TLD being used by ddev ("ddev.local" currently). That way if this value changes in the future we won't completely break the GUI.

## What you expected to happen:
Add a "domain" or "TLD" section to `ddev version` which outputs the current value of the [DDevTLD constant](https://github.com/drud/ddev/blob/master/pkg/ddevapp/config.go#L34). While we're at it, we might consider moving this constant into our [version package](https://github.com/drud/ddev/tree/master/pkg/version)

**Comment by rfay** [comment]
Please review what else might be missing from `ddev version` when looking at this.

Also note that `ddev version -j` doesn't work correctly, it just outputs a hunk of text. Not sure if we want to fiddle with that at this point. It would be pretty easy to put explicit items in the 'raw' field as is done with ddev list and desc.

Related: #487 - ddev version should provide info about the PHP version we're using.

**Comment by cweagans** [comment]
PR is open - #586. It's fairly basic. There's a different ticket open for the PHP version. I'm not sure what else should go into `ddev version` - we're already outputting what we can output quickly, it looks like.

**Comment by rickmanelius** [comment]
@cweagans With the PR in, anything else remaining on this or shall we close this out?

**Comment by cweagans** [comment]
I think we're good.

**Comment by rfay** [comment]
You can close an issue when given an opening like that @cweagans :)
