### ISSUE TITLE
Get DATABASE_URL env var for Symfony project

### ISSUE THREAD

**Issue by flovntp** [drud/ddev#4410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When trying to get an existing PSH project and then, executing this commands, i needed to add DATABASE_URL manually to make it works fine.

```
symfony get llynyw5ygskhg
ddev config
ddev get platformsh/ddev-platformsh
ddev pull platform 
ddev restart
```

If there is no DATABASE_URL defined in the .ddev/config.yaml file, this raise an error trying to connect to DB 
```
web_environment:
...
- DATABASE_URL=pgsql://db:db@db:5432/db
```

### Describe your solution

adding this line into config.yaml file

```
web_environment:
...
- DATABASE_URL=pgsql://db:db@db:5432/db
```

**Comment by rfay** [comment]
I didn't know there was a standard technique for database description on Symfony. Seems like this can be done just like for Laravel. 

Are there other things that could be done to make Symfony easier? upload_dir? nginx config? If we wanted to add a full project type, this is how, https://ddev.readthedocs.io/en/latest/developers/project-types/

**Comment by flovntp** [comment]
Hi @rfay 
sorry, really busy these days
i will have a look on how to add a project-type, i think it could be great to add `symfony` in the list of available php project during `ddev config` ;) 
you don't need to reopen the issue, i will work on it silently and ping you here if needed.
thanks Randy

**Comment by rfay** [comment]
Thanks @flovntp - It would be great it you could start by just describing here what things would need to be configured for a symfony project type. Is there a standard place for uploaded files?  Are things usually configured in a .env file? What would normally be in the .env file?
