### ISSUE TITLE
Can't resolve hostname www.youtube.com inside web container on Colima

### ISSUE THREAD

**Issue by renatho** [drud/ddev#4413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/renatho/9cc240e9b751a8be5bb08534d1a6f965

### Expected Behavior

I expected to be able to ping www.youtube.com from my container.

### Actual Behavior

I can ping any domain, but www.youtube.com. And it happens only in the docker container.

```
> ping www.youtube.com
ping: www.youtube.com: Temporary failure in name resolution
```

### Steps To Reproduce

1. Create an env selecting all the default options from `ddev config`.
2. Run `ddev start`.
3. Run `ddev ssh`.
4. Run `ping www.youtube.com` and see the error: `ping: www.youtube.com: Temporary failure in name resolution`
5. Run `ping www.vimeo.com`, and see that it works well: `PING www.vimeo.com (162.159.138.60) 56(84) bytes of data.`

I use Colima.

**Comment by renatho** [comment]
Extra information is that inside the container, I edited the `/etc/resolv.conf`, changing the nameserver to `8.8.8.8` and the ping worked properly, but it makes other things stop working, like the database connection.

**Comment by rfay** [comment]
This is a problem with Colima in some network environments. Please use the suggested `--dns 1.1.1.1` to get a neutral and functional DNS server. See https://ddev.readthedocs.io/en/latest/users/install/docker-installation/#macos

**Comment by rfay** [comment]
Added to 
* https://github.com/abiosoft/colima/issues/466

**Comment by renatho** [comment]
Awesome! It worked! Thank you very much @rfay!
