### ISSUE TITLE
Unable to pull database from platform.sh if more than one exists

### ISSUE THREAD

**Issue by bserem** [drud/ddev#4415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

It passes, but contains several project/client names so I haven't uploaded it. I can do so if absolutely required.

### Expected Behavior

`ddev pull platform --skip-files` should be able to fetch and import a database dump.

### Actual Behavior

When more than one DB is configured, `platform` expects a parameter for which DB to work with.

```
Authenticating...
Obtaining database...
More than one relationship found.
Use the --relationship (-r) option to specify a relationship. Options:
    legacy
    database
Pull failed: Failed to exec #set -x   # You can enable bash debugging output by uncommenting
set -eu -o pipefail
ls /var/www/html/.ddev >/dev/null # This just refreshes stale NFS if possible
platform db:dump --yes --gzip --file=/var/www/html/.ddev/.downloads/db.sql.gz --project="${PLATFORM_PROJECT}" --environment="${PLATFORM_ENVIRONMENT}"
 on web: exit status 1
```

### Steps To Reproduce

1. Create a project with multiple mysql relationships in platform.sh
2. `.platform.app.yaml`
```
relationships:
  database: 'mysqldb:mysql'
  legacy: 'legacydb:mysql'
  redis: 'rediscache:redis'
```
3. Run `ddev pull platform --skip-files`
4. See error (under **Actual Behavior** above)

### Anything else?

This fails (from inside DDEV):
```
platform db:dump --yes --gzip --file=/var/www/html/.ddev/.downloads/db.sql.gz --project="${PLATFORM_PROJECT}" --environment="${PLATFORM_ENVIRONMENT}" -r 0
More than one relationship found.
Use the --relationship (-r) option to specify a relationship. Options:
    legacy
    database
```

This works (from inside DDEV):
```
platform db:dump --yes --gzip --file=/var/www/html/.ddev/.downloads/db.sql.gz --project="${PLATFORM_PROJECT}" --environment="${PLATFORM_ENVIRONMENT}" -r database
Creating gzipped SQL dump file: /var/www/html/.ddev/.downloads/db.sql.gz
```

See the `-r database` at the end (stands for `--relationship`).

_I understand this is an edge case, but it happened to me so it made sense to file it._

**Comment by rfay** [comment]
Also reported in 
* https://github.com/platformsh/ddev-platformsh/issues/59

but it's better here.

**Comment by bserem** [comment]
A good first start for this is to document what is needed to get the DB is such a case. It is not as "fancy" as pull, but it would make it easier for people.

It might also be possible to imporve on the work done on #4180 

In any case, documentation is gonna be my first step here.

**Comment by rfay** [comment]
Currently `ddev pull platform` doesn't know about PLATFORM_RELATIONSHIPS so there are a few problems here. PLATFORM_RELATIONSHIPS *is* parsed/created by platformsh/ddev-platformsh addon, but we'd have to have it in platform.yaml for this to work OOTB, right?

**Comment by bserem** [comment]
I can't say if `relationships` are of such importance that we need to have them in DDEV. To be honest, only 1/50 of the projects I deal with in platformsh uses it.
Might not be worth the time needed?

**Comment by rfay** [comment]
@lolautruche the PR downloads all databases, and allows you to specify which one should go into 'db' if you want. Would love to have you try it out, 
* https://github.com/drud/ddev/pull/4426
