### ISSUE TITLE
Run Composer from working directory

### ISSUE THREAD

**Issue by hockdudu** [drud/ddev#4421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

In our project, we have a monorepo with multiple composer packages (made with https://github.com/symplify/monorepo-builder). This means, the folder structure is like the following:

```
packages/
  project-a/
    composer.json
  project-b/
    composer.json
composer.json
```

We'd like to run `ddev composer` in the subprojects, but the command is always executed in the root composer.json.

Example:
```
cd packages/project-a
ddev composer install # This should run at `packages/project-a`, but instead it runs at the project's root.
```

### Describe your solution

We'd like to run `ddev composer` in the subproject's folder.

The best solution for us would be with a config entry in `.ddev/config.yaml`.

### Describe alternatives

We've also tried "overwriting" the `composer` command (e.g. with a custom command at `.ddev/commands/web/composer`), but it doesn't work. The custom command is listed as an available command, but `ddev composer` always runs the original composer command.

**Comment by rfay** [comment]
Hi @hockdudu - DDEV has two features that can help you.

1. `composer_root` (or `ddev config --composer-root=project-a` for example). You can say where the composer.json is.
2. `ddev composer --working-dir` will tell composer where to run. 

Resources for these: `ddev config -help` would point you to the --working-dir.  [DDEV and Composer](https://ddev.readthedocs.io/en/latest/users/basics/developer-tools/#ddev-and-composer) in docs gives more detail.

Also, for most people, it would make more sense to have two DDEV projects here, one in project-a and one in project-b. This will work even though they're in the same repository.

**Comment by hockdudu** [comment]
Hello @rfay 

Hmm, neither the first nor the second option would solve our problem. We can't change the `composer_root` for the whole project because there are many projects inside the main project. Passing `--working-dir` works, but it makes the command complicated (e.g. ` ddev composer install --working-dir packages/package-a`), and the developer must remember it every time.

Having a DDEV project for each package might be the most sensible option. But it complicates the configuration of our packages, especially keeping them all in sync (unless we're to use symlinks, but that can become cumbersome as well).

I don't know how feasible these options are, but something like an entry at `.ddev/config.yaml`, e.g. `relative_composer_working_dir: true`, or the ability to overwrite ddev commands, would solve this for us.

I have no experience in Go, but if you think an entry like such in the config could be merged, then I can give it a try.

**Comment by rfay** [comment]
Sorry, it's just not reasonable to build out whole new features of DDEV to support one team's workflow.

You can easily add a post-start exec hook that will do a `for dir in projects; do composer install -d $dir; done` and there are loads of other approaches you can use.

**Comment by tyler36** [comment]
If you find you need to run these commands alot, here are a couple of options:

1.  Use `ddev ssh` to open a terminal inside the container and run whatever command as/when needed.
     In Vscode, I'll have a terminal open for the project and another opened with `ddev ssh`.  I tend to do this alot since it's less 
     typing to run tests, install patches etc. I don't need to use `ddev ...` before every command. 

2. Create a [custom command](https://ddev.readthedocs.io/en/latest/users/extend/custom-commands/).
    This can do what ever you want and can be shared with the team.

    ```
    #!/bin/bash
    
    ## Description: Run composer commands from inside project 1
    ## Usage: comp1 [flags] [args]
    ## Example: "ddev comp1"
    
    cd ../project-1 && composer  "$@"
    ````

**Comment by hockdudu** [comment]
@rfay I totally understand. Our use-case is unique indeed :sweat_smile: 

@tyler36 Thanks for the tip. We'll probably use a custom command. Using the option `HostWorkingDir` we can create a single command that works for all projects.

```shell
#!/usr/bin/env sh

## Description: Executes a composer command in the current project folder
## Usage: composerp
## Example: "ddev composerp install"
## HostWorkingDir: true

composer "$@"
```
The downside is, the command can't be called `ddev composer` (it can't replace the built-in command), it must have a different name (in this case `ddev composerp`). But that's okay in our case.
