### ISSUE TITLE
Mention homebrew as an installation option in readme

### ISSUE THREAD

**Issue by cyberswat** [drud/ddev#443]
## What happened (or feature request):
I'm walking through the Readme and noticed that the installation instructions do not mention Homebrew.

## What you expected to happen:
The readme should be updated to include mention of homebrew as an installation option.

**Comment by cyberswat** [comment]
Just noting that there doesn't seem to be a mention of homebrew in the documentation site either.

**Comment by rfay** [comment]
Duplicate of #434, right?

**Comment by rickmanelius** [comment]
Yup, duplicate.
