### ISSUE TITLE
Passing custom variables to ddev container commands

### ISSUE THREAD

**Issue by jigarius** [drud/ddev#4436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

* I've created a custom command: `.ddev/commands/web/npx`.
* I run the command as follows: `theme=foo ddev npx webpack`
* I want to catch the `theme=foo` so that I can send to `npx`.
  * Or even better, the variable should be sent automatically to `npx`.
* Note: I would've used `--theme=foo`, which would work, but Webpack throws an error if it finds switches that it doesn't support, in this case, `--theme`.

### Describe your solution

Will it be possible to have all such variables available when custom commands are called?

**Comment by rfay** [comment]
No response or extra information, so closing this. Happy to continue the conversation here or elsewhere if you can figure out more specifics of what you want to do.
