### ISSUE TITLE
Support/RFC: Generic CI/CD integration

### ISSUE THREAD

**Issue by pataquets** [drud/ddev#4446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

Maybe extending ddev's providers.

### Is your feature request related to a problem?

I've started using ddev recently and found it awesomely useful. Thanks for putting up such a great tool!
As an experienced DevOps and Docker practitioner, what I'm currently missing is come build/deploy workflow. Before the needs, some considerations:
* I'm aware that ddev is mainly intended as a *local* development tool, so I understand it not being strong in this regard, but I think it would be in scope to add the extensibility to do some CI/CD. Not sure, thou. Let me know if not.
* Aside of being in scope or not, I've found ddev's extensibility and customization very powerful and worth exploring. Awesome work in this space!
* I'm still getting used to it and not too deep in ddev, so maybe there is some functionality I haven't discovered yet.
* However, I've already read about hosting provider extensibility and I think it might suit my needs. I have to go deeper, yet, but just dumping my needs in case anyone else finds them useful and worth giving feedback, and hopefully, attracting more eyeballs and brains to it.

### Describe your solution

As for my requirements, we're currently using ddev as our local development tool of choice for Drupal 7 & 8+ sites. Nothing fancy, just check out some repo, load some db dump, do some `composer`/`drush make` commands and start working locally on the contrib/custom modules. What we'd like to accomplish is some CI/CD tooling to allow us to:
* Run some sort of `ddev build` command which would ideally run some basic "it works" tests and build a deployable artifact to test locally. Build artifact should include all necessary code, but repos contain only `composer.*`/`*.make` files, custom code and not much else. So build would do at the very least some `composer` or `drush make` steps.
* For the above, we would have to use a custom Dockerfile (most probably based on some official `php-fpm` image), as ddev's web image is not suitable for production because of complexity (although I'd like it to be, for consistency). It hosts several services (fpm and webserver, at the least), which is a Docker antipattern and also I guess it might contain development & debugging functionality not suitable for production (xdebug & others). Even if it could be disabled, I guess it would be more work and having to track ddev's image. But having to create some custom Dockerfile it's not the end of the world, so I can bear with it.
* (Maybe) After building and testing OK, some kind of `ddev push` for the built artifact to be pushed and deployed to QA/test/staging environments by the developers themselves. Production will be deployed by manually triggering some pipeline (at least for now).

### Additional context

As we're still exploring ddev's abilities in this space, requirements might change/adapt/extend to fit or take advantage of ddev's features. I'm just putting up this write-up to gather feedback on ideas, suggestions and even maybe how people are currently addressing this. With my current knowledge of ddev, I'd bet that the missing stage to deployment to QA (and even production) in the development workflow would fit nicely, with the proper tooling and I think it could be useful for others even under different workflows and CI/CD scenarios, if done properly.

**Comment by rfay** [comment]
You'll want to take a look at https://ddev.readthedocs.io/en/latest/users/details/alternate-uses/#continuous-integration-ci

**Comment by rfay** [comment]
DDEV's focus is on local development. Specific idea you have can be implemented as DDEV Add-ons pretty easily. But since this is actually out of scope for the primary focus of the tool, I'm going to close for now, but happy to continue the discussion here or elsewhere.

**Comment by pataquets** [comment]
Turns out that, while delving into the docs familiarizing with ddev, the link you gave me above was not among my reading :facepalm:. Much appreciated.
I agree it's out of scope. I was thinking more in some opportunistic (and generic enough) way of extending ddev right into production. I'm OK with closing this, since there is a valuable link and also can attract eyeballs. I will keep it handy while progressing with our production dockerization and hopefully I'll be able to come back with more input. Anyway, the initiative has been shelved, by now.
Thanks for your feedback, @rfay.

**Comment by rfay** [comment]
Unfortunately, with one dedicated developer and a significant (and great) community, it's not possible to expand scope very much. Thanks for your understanding!

**Comment by tmotyl** [comment]
new link to docs is here: https://ddev.readthedocs.io/en/latest/users/topics/remote-docker/#integration-of-ddev-docker-images-into-other-projects
