### ISSUE TITLE
Make `ddev share` extensible (as done with hosting providers)

### ISSUE THREAD

**Issue by pataquets** [drud/ddev#4447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Currently, `ddev share` only supports ngrok.com, which is only one of the possible solutions.

### Describe your solution

Make `ddev share` to be extensible as done with hosting providers, to allow alternative implemetations.

### Additional context

See #4365.

**Comment by rfay** [comment]
Another approach here is to just create custom commands that do what's needed. That capability already exists, and should be pretty easy. https://ddev.readthedocs.io/en/latest/users/extend/custom-commands/ - would love to hear about what you come up with. It can also be shared as a DDEV add-on.

**Comment by rfay** [comment]
This is a worthy suggestion, but without a contribution in this area I don't think it will be worked on any time soon.

**Comment by tyler36** [comment]
Custom command or addon is probably the way to go. 
If it becomes the new default (most popular or ngrok falls away) then we could mabe swap it in.

**Comment by wolcen** [comment]
I've successfully used pagekite for this myself and it's worked just fine. I'll try making it a custom command (or addin) and see where I get. Just wanted to put the name out there anyway - they've been around forever (well, since 2010 in internet-years is close enough).

**Comment by pataquets** [comment]
Copying here recent comment from #4365, for completion:

> @skeemer has already been there, see https://leolutz.dev/blog/ddev-and-cloudflare-tunnel/ - There's plenty more discussion over in [discord](https://discord.gg/5wjP76mBJD) including discussion of other alternates.

/cc @nickchomey: Actually, I was thinking on CF when I filed this one :smile:
