### ISSUE TITLE
DB container way slow to come up and status check succeed

### ISSUE THREAD

**Issue by rfay** [drud/ddev#445]
## What happened (or feature request):

We used to see the db container come up plenty fast enough, it now seems to not come up successfully at first. Waiting or issuing another `ddev start` are workarounds, but it's not what we want. It shouldn't take a lot of debugging to just bring up the container and see what happens with it.

## Related source links or issues:

**Comment by rfay** [comment]
I had this problem today, and was able to docker exec into the container; in the mysql container, a `mysql` command hung or said "can't connect".

**Comment by rickmanelius** [comment]
Seems like a bug worthy of prioritizing for our next release. Need confirmation that we can reproduce.

**Comment by rickmanelius** [comment]
I'd like to give this a bit of testing to confirm it's still an issue.

**Comment by rfay** [comment]
I suspect this is related to ["ddev start" can result in web container without /var/www/html mount (no status provided)](https://github.com/drud/ddev/issues/449) and my theory is that it's related to inadequate docker resources (memory?). I haven't had it happen lately, it could even have been a particular docker version.

**Comment by rickmanelius** [comment]
Hi @rfay. I started 4 different sites (WordPress, Drupal 8, Commerce Kickstart, Drupal 7 vanilla) all within 5 minutes and no issue seeting the container come up. I'm using docker `Docker version 17.09.0-ce, build afdb6d4` and I have 2GB of memory allocated. Happy to pull this back in if we can more easily recreate it.

**Comment by rickmanelius** [comment]
I don't see this as a recurring issue. Closing for now and we can re-open if it resurfaces.
