### ISSUE TITLE
DDEV v1.21.4 Test Plan

### ISSUE THREAD

**Issue by rfay** [drud/ddev#4452]
It's testing time again here in the DDEV factory. We love community help with every item that is interesting or relevant to you, and just *using* the release candidates is hugely helpful, because you may stumble across something in your regular workflow. Please use DDEV HEAD for your testing (or `brew unlink ddev && brew install --HEAD --fetch-head drud/ddev/ddev`) or other techniques at [Testing Latest Commits](https://ddev.readthedocs.io/en/latest/developers/building-contributing/#testing-latest-commits).

You can test on gitpod with the [gitpod link for this issue](https://gitpod.io/#https://github.com/drud/ddev/issues/4452).

**Please do a `docker pull drud/ddev-webserver:v1.21.4` to make sure you have latest ddev-webserver**

I don't think in general you'll have trouble using this in your daily workflow, so would love you do do that. You can switch back and forth , see [How can I install a specific version of DDEV in the FAQ](https://ddev.readthedocs.io/en/latest/users/basics/faq/)].

If you find a bug that you're pretty sure is a bug, then [just open an issue for it](https://github.com/drud/ddev/issues/new?assignees=&labels=&template=Bug_report.md&title=)]

To give feedback or ask questions, please just reply on this issue or discuss in [discord](https://discord.gg/hCZFfAMc5k)] or any other support channel.

I am maintaining the [provisional release notes for v1.21.4](https://www.notion.so/b42d8d5939ed46f0998d3e5f5ec26805) and would love any comments on those.

See [commits since v1.21.3](https://github.com/drud/ddev/compare/v1.21.3...master) and [PRs merged since Oct 18, 2022](https://github.com/drud/ddev/pulls?q=is%3Apr+is%3Aclosed+merged%3A%3E2022-10-18+)

1. host.docker.internal/xdebug supported better lots of places
    1. Gitpod
    2. WSL2 with docker-ce installed inside
    3. WSL2 with Docker Desktop
    4. Linux
    5. PhpStorm with new options on WSL2
2. WSL2
    1. Try the docker-ce install script
    2. Try the docker desktop install script
    3. xdebug should work OOTB with both of them
    4. Verify windows-side hosts file management
3. `ddev config --xdebug-ide-location`
    1. Test with new PhpStorm approach on WSL2
    2. Test with PhpStorm running inside WSL2
4. Test Postgresql on Gitpod
5. Test `ddev launch` on Gitpod
6. Drupal 10. Install and check for warnings about
    1. MySQL transaction level
    2. Postgresql pg_trm extension
7. Test nfs_mount_enabled on macOS Ventura
8. Test `ddev self-upgrade` on Linux, macOS, Windows, WSL2
9. Test adding web environment variables using a .ddev/.env file
10. `ddev get` output. Test with a a a number of add-ons, make sure it’s readable.
11. `ddev pull platform` should work with multiple databases and with single databases, should work with PLATFORM_PRIMARY_RELATIONSHIP.
12. Make sure postgres:9 through postgres:11 work properly
13. Traefik:
    1. General usage
    2. Overriding project configuration
    3. Overriding global configuration
    4. Try with several `ddev get` add-ons.
14. Test Craft CMS and Laravel quickstarts
15. `ddev pull --environment=` can be used to pull from different environment on [[Platform.sh](http://platform.sh/)](http://Platform.sh) for example. Is that in docs?
16. Flags on custom commands should work right if the flag is passed through. `ddev composer` complex things, `ddev php --help`

**Comment by rfay** [comment]
1. host.docker.internal: I had no trouble installing Drupal 10.0.0-dev with PHP8.2 (rc3) using macOS on M1. I did have serious slowness issues on WSL2 with docker-ce inside, but couldn't figure out if it was the computer or something else. The commands, even ddev config and ddev describe had a noticeable delay.
  * ✅ Gitpod
2. WSL2
3. `ddev config --xdebug-ide-location`
4. Test Postgresql on Gitpod
5. Test `ddev launch` on Gitpod
6. Drupal 10. Install and check for warnings about
    1. MySQL transaction level
    2. Postgresql pg_trm extension
7. Test nfs_mount_enabled on macOS Ventura
8. Test `ddev self-upgrade` on Linux, macOS, Windows, WSL2
9. Test adding web environment variables using a .ddev/.env file
10. `ddev get` output. Test with a a a number of add-ons, make sure it’s readable.
11. `ddev pull platform` should work with multiple databases and with single databases, should work with PLATFORM_PRIMARY_RELATIONSHIP.
12. Make sure postgres:9 through postgres:11 work properly
13. Traefik:
    1. General usage
    2. Overriding project configuration
    3. Overriding global configuration
    4. Try with several `ddev get` add-ons.
14. Test Craft CMS and Laravel quickstarts
15. `ddev pull --environment=` can be used to pull from different environment on [[Platform.sh](http://platform.sh/)](http://Platform.sh) for example. Is that in docs?
16. Flags on custom commands should work right if the flag is passed through. `ddev composer` complex things, `ddev php --help`

**Comment by tyler36** [comment]
1. host.docker.internal/xdebug supported better lots of places
    - ✅  Gitpod
    - ✅  WSL2
2.
3.
4. Test Postgresql on Gitpod. 
     - ✅ Postgres 12 with Drupal 9 site install
     - ✅ Postgres 14 with Drupal 9 site install
5. ✅ Test ddev launch on Gitpod - no problems!
6. Drupal 10. Install and check for warnings about 
     - ✅ MySQL transaction level - 10.4.27-MariaDB with Drupal 10.0.0-rc3
     - ✅Postgresql pg_trm extension - Postgres 14 with Drupal 10.0.0-rc3
7.
8. Test ddev self-upgrade on Linux, macOS, Windows, WSL2
     - ✅ WSL detected brew install with approriate message
```shell
$ ddev self-upgrade
/home/linuxbrew/.linuxbrew/bin/brew
DDEV appears to have been installed with homebrew, upgrade with 'brew update && brew upgrade ddev'
```
🤷 Gitpod - message feels confusing. Maybe detect Gitpod environment and nudge to a specific command?

```shell
$ ddev self-upgrade
Unable to determine how you installed ddev, but you can remove /home/gitpod/bin/ddev and reinstall with one of the techniques in https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/
```

10. ddev get output. Test with a number of add-ons, make sure it’s readable.
     - ✅ `drud/ddev-browsersync`
     - ✅ `drud/ddev-cron`
     - ✅ `tyler36/cypress`
11. 
12. Make sure postgres:9 through postgres:11 work properly
     - ✅ Postgres 10 with Drupal 9 site install
     - ✅ Postgres 11 with Drupal 9 site install

**Comment by rfay** [comment]
Thanks @tyler36 !

> 🤷 Gitpod - message feels confusing. Maybe detect Gitpod environment and nudge to a specific command?

The case there is that ddev has been compiled from HEAD in Gitpod, so it's like a downloaded binary just stuck somewhere. I agree it can be confusing, but it's the default case in the switch... "Sorry, we don't know where you got this ddev from..."

**Comment by bserem** [comment]
- [x] 11. Multiple DBs on platformsh works flawlessly. Primary DB is mapped to `db` in DDEV correclty. Secondary DB gets automatically created and imported in mysql. Made https://github.com/drud/ddev/pull/4457 in the process

Tested with a Drupal multisite:
```
Obtaining databases...
PLATFORM_PRIMARY_RELATIONSHIP=default so using it as database 'db' instead of the upstream 'firstdb'
Creating gzipped SQL dump file: /var/www/html/.ddev/.downloads/db.sql.gz
Creating gzipped SQL dump file: /var/www/html/.ddev/.downloads/seconddb.sql.gz
Downloaded db dumps for databases 'firstdb seconddb'
```

Thanks!

**Comment by rfay** [comment]
I think we're done! I think all the issues were mostly doc-ish, this should be ready to release when passing all tests, https://github.com/drud/ddev/pull/4456 should be the last.

Thanks all!
