### ISSUE TITLE
How to use multiple hostnames/URLs to get different sites (multisite, multiple docroots)

### ISSUE THREAD

**Issue by Firesphere** [drud/ddev#4465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I'd like to be able to have the following system:
- https://mywebsite.ddev.site
- https://shop.mywebsite.ddev.site
etc.

So I can have a single website that uses the subdomain to show a certain part of the website, or, in very extreme circumstances, an entirely different website.

### Describe your solution

Enable the router to forward subdomains

### Describe alternatives

Copy the whole project to a new folder
Start a new ddev project in the new folder
Now, whenever you make a change, sync the original and the copy, just in case.
And if the DB goes wonky, unwonky it by syncing the db as well

**Comment by rfay** [comment]
Hi @Firesphere - There are two different ways to approach this.

1. Many CMSs (like Drupal and TYPO3 for example) have "multisite" capability, where the site behaves differently based on the domain name it's accessed by.
2. If the code is actually different for your different sites, you'd want to use the nginx or apache second-docroot techniques to point different domain names (subdomains) to a different docroot. See [nginx multiple docroots](https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#multiple-docroots-in-nginx-advanced) or [apache example](https://github.com/drud/ddev/blob/master/pkg/ddevapp/webserver_config_assets/apache_second_docroot_example-site-php.conf)

**Comment by gilzow** [comment]
At @Firesphere if you're wanting to route multiple subdomains to the _same codebase_ ddev supports adding hostnames in the `.ddev/config.yaml` file via the `additional_hostnames` key. See [this section in the docs](https://ddev.readthedocs.io/en/latest/users/extend/additional-hostnames/).

**Comment by rfay** [comment]
No response, so closing. Happy to continue the conversation here or elsewhere.
