### ISSUE TITLE
Test out new colima options vz and virtiofs mounting

### ISSUE THREAD

**Issue by rfay** [drud/ddev#4466]
We need to test out the complexities and possibilities of colima v05.0 and what the heartaches are regarding DDEV.

- [x] vz virtualization (try `ddev composer install`) for example
- [x] 9p mounting, `ddev composer install`
- [x] `virtiofs` mounting
- [x] Performance comparisons, dust off https://github.com/drud/ddev-puppeteer

**Comment by 75th** [comment]
Tried to `ddev import-db` a large database using the new options. Both a 500+ MB .sql file uncompressed, and the same data as a 75 MB gzip. Results:

||qemu|vz|
|---|---|---|
|virtiofs|Done in 3 minutes|Incredibly slow. ETA and import speed fluctuated widely, with completion estimates between 20 minutes and over an hour. With the gzipped file it took a longer time for the progress bar to even appear, and when it did it wasn't significantly faster than the uncompressed.|
|sshfs|Done in 3 minutes|Fails entirely with an error like `pv: /mnt/ddev_config/.importdb3453168728/*.*sql: No such file or directory`|

**Comment by 75th** [comment]
Re: my EDIT above, I opened [an issue](https://github.com/abiosoft/colima/issues/517) at colima

**Comment by abiosoft** [comment]
@75th as mentioned in the issue, `vz` and `virtiofs` goes hand in hand. The test result above is most likely `9p` and not `virtiofs`.

**Comment by balajiv113** [comment]
@75th I believe the poor performance in vz is related to how persistent disk are attached in lima. I will update this in lima once  https://github.com/Code-Hex/vz/pull/117 is merged.

Temporarily if you are interested you can do this workaround and then try importing.
```
colima ssh
sudo -i
echo 'write through' > /sys/class/block/vda/queue/write_cache
```
Check this for more [Detailed Reference](https://github.com/docker/roadmap/issues/7#issuecomment-1044018513)

**Comment by rfay** [comment]
@balajiv113 I confirm that that makes colima with vz BLAZINGLY fast on `ddev import-db`.

**Comment by rfay** [comment]
Here are my results of testing the various permutations, https://ddev.com/ddev-local/ddev-docker-desktop-and-colima-benchmarking-updated-dec-2022/

**Comment by abiosoft** [comment]
This https://github.com/drud/ddev/issues/4466#issuecomment-1361261185 can be handled in Colima directly as a workaround for now.

**Comment by abiosoft** [comment]
> This [#4466 (comment)](https://github.com/drud/ddev/issues/4466#issuecomment-1361261185) can be handled in Colima directly as a workaround for now.

Now that this is included in v0.5.2, it would be nice to see the blog post updated.

**Comment by rfay** [comment]
Awesome, will test!

**Comment by rfay** [comment]
@abiosoft updated the blog, it did indeed solve lots of things, and Colima/VirtioFS is now the fastest non-mutagen option out there! https://ddev.com/ddev-local/ddev-docker-desktop-and-colima-benchmarking-updated-dec-2022/

Of course I know you already saw my report of SEGFAULTS in VirtioFS, 
* https://github.com/abiosoft/colima/issues/547
