### ISSUE TITLE
Cleanup PATH variable in web container

### ISSUE THREAD

**Issue by webseppel** [drud/ddev#4471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When I run `echo $PATH` in the web container of a fresh configured ddev project I get the following:

`~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/html/vendor/bin:/var/www/html/bin:/var/www/html/vendor/bin`

You can see there are:
- double entries for `/var/www/html/vendor/bin` 
- these paths might do not exists on some projects:
   ```
   /var/www/html/vendor/bin
   /var/www/html/bin
   ```

### Describe your solution

On a fresh configured ddev Project the PATH variable in the ddev webcontainer should look like this:

`~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

### Describe alternatives

Additional paths could be added depending on:

- The ddev project type
- a new config key like `webimage_extra_paths: []`

### Additional context

The PATH variable seems to be set in [https://github.com/drud/ddev/blob/master/containers/ddev-webserver/ddev-webserver-base-files/etc/bashrc/commandline-addons.bashrc](https://github.com/drud/ddev/blob/master/containers/ddev-webserver/ddev-webserver-base-files/etc/bashrc/commandline-addons.bashrc)

**Comment by rfay** [comment]
Why do you think it's important to not have items in the PATH that don't exist? This is a common situation. Does it do you some harm?

**Comment by webseppel** [comment]
This is just my aspiration for keeping things as clean and clear as possible. I found the extra unused and double paths distracting when I found it.

**Comment by rfay** [comment]
Yeah, but adding the code to make it feel clean to you would be many lines of code, adding significant complexity. There's more than one side to these things! Closing for now, happy to continue the conversation here or elsewhere.
