### ISSUE TITLE
php-raphf not installing with php 8.1 in ddev v1.21.4 (needs php8.1-raphf)

### ISSUE THREAD

**Issue by giraz82** [drud/ddev#4472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

I expect `webimage_extra_packages` works for every version of PHP

### Actual Behavior

`webimage_extra_packages` only works with PHP 8.2

### Steps To Reproduce

Create a new ddev project with this config:

```yaml
php_version: "8.2"
webimage_extra_packages: [php-raphf]
```

```shell
$ ddev ssh

$ php -v
PHP 8.2.0 (cli) (built: Dec  8 2022 15:03:15) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.0, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.0, Copyright (c), by Zend Technologies

$ php -m | grep raph
raphf

$ php --ini | grep raph
/etc/php/8.2/cli/conf.d/20-raphf.ini,
```

Everything is ok 🎉 

Then

```yaml
php_version: "8.1"
webimage_extra_packages: [php-raphf]
```

```shell
$ ddev ssh

$ php -v
PHP 8.1.13 (cli) (built: Nov 26 2022 14:27:02) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.13, Copyright (c), by Zend Technologies

$ php -m | grep raph

$ php --ini | grep raph
```
Not ok 🙁 

Same for php 8.0

```shell
$ php -v
PHP 8.0.26 (cli) (built: Dec  5 2022 21:59:43) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.26, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.26, Copyright (c), by Zend Technologies

$ php -m | grep raph

$ php --ini | grep raph
```

### Anything else?

It worked in the past, but I cannot remember if on v1.21.2 or also in v1.21.3

**Comment by rfay** [comment]
I imagine your problem is that php8.1-raph is not available upstream, don't know. 

but please do a `ddev debug refresh` to completely rebuild on php8.1 and see what you get.

**Comment by rfay** [comment]
Oh, I see. You'll want to use 
```
webimage_extra_packages: [php8.1-raphf]
```

I've never understood exactly how and when the meta-packages like `php-raphf` are supposed to work with different PHP versions, but they most often don't. You need to use `php8.1-raphf` etc.

**Comment by giraz82** [comment]
Thank you @rfay, you definitely hit the problem!

```shell
$ php --ini | grep raphf
/etc/php/8.1/cli/conf.d/20-raphf.ini
```

But is something new to me because in our team we use `php-*` from long time in our ddev config, and we never had problems since now.
Ok, I learned the lesson, thank you again 🙂

**Comment by rfay** [comment]
Probably the upstream deb.sury.org packages changed their configuration in the recent releases. If you want to install all versions for your team, you can do `webimage_extra_packages: [php8.0-raphf, php8.1-raphf, php8.2-raphf]` and it should do no harm. 

Closing, happy to continue the conversation here or elsewhere.
