### ISSUE TITLE
How can I order hooks when they come from different `config.*.yaml` files?

### ISSUE THREAD

**Issue by hanoii** [drud/ddev#4473]
I have a bunch of start actions (related to platformsh) that I wanted to bundle into an addon so that I maintain it on a single place rather than start copying things from project to project and I found myself doing small tweaks to these commands that I then don't usually trickle them down to old projects.

I did bundle it into https://github.com/hanoii/ddev-platformsh-lite/blob/main/config.platformsh-lite.yaml.

Although not strictly necessary in this case, I like these hooks to run first of all. I went to see if I had a way to do that somehow and not unless I redesign the config files. The config.*.y*ml are merged after the main config.yaml.

I know that I can create, say, a config.platformsh-lite.after.yaml if I have hooks that need to run after this, so I have means around it.

I am just wondering if there's something that worth doing to be able to control the order of hooks outside of the order of the merge of configs.

My initial thought was to do something like module weights on drupal, so everything will work as it is now, but you could do something like:

```yaml
hooks:
  post-start:
    - 
       exec: 'some command'
       weight: -1
```

Which will run it before all zero weighted (default). Same could be used for a higher weight, etc..

Thoughts?

**Comment by rfay** [comment]
Hmm, I don't think anybody has ever looked at this this way before.

You can see what the result of the merge is with `ddev debug configyaml`, and experiment with that.

**Comment by hanoii** [comment]
I think I gathered how it works from the code, config.yaml goes first, then all of the overrides in lexicographic order. I was thinking of a way to order hooks outside of this method, I know it's very custom and likely not worth implementing as you can always do it in different ways.

**Comment by rfay** [comment]
Can you be specific about a use-case you're trying to accomplish?

**Comment by hanoii** [comment]
I tried to explain it in the first post, but bear in mind that I know it's not necessary, but I moved https://github.com/hanoii/ddev-platformsh-lite/blob/main/config.platformsh-lite.yaml out of my different project's `config.yaml` and I tend to do those first of all. Now they happen after the other project specific post-start hooks. This is not important if it happens before or after, but I just thought of a mean to alter order not just based on file overrides. 

so, if you have config.yaml with

```yaml
post-start:
  - exec: 'command 1' 
```

and config.extra.yaml

```yaml
post-start:
  -exec :'command 2'
```

you have no way of running command 1 before command 2. Unless you move command 1 to an extra config.extra2.yml file.

That's all, not too important, I know!

**Comment by rfay** [comment]
I understood what you were trying to do, was just trying to understand a practical example to see if there were other ways I'd propose to look at it.

**Comment by hanoii** [comment]
For now I have a theoretical use case.

Let's say I need tu run a platform command after setting the drush aliases, as I am setting the drush alias inside `config.plaformsh-lite.yaml`, I would have to move this post start outside of the main config.yaml into a secondary `config.platformsh-lite-after.yaml` to make sure it runs AFTER setting the drush aliases.

**Comment by rfay** [comment]
This seems pretty theoretical right now, so closing, but maybe it will pick up interest in the future. Happy to continue the conversation.
