### ISSUE TITLE
WSL DDEV cant find Win10 DDEV: "ddev.exe not found in $PATH"

### ISSUE THREAD

**Issue by tyler36** [drud/ddev#4474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

I have DDEV installed via brew in WSL

```shell
$ ddev -v
ddev version v1.21.4
```

When I delete try to delete docker images I get an error:

```shell
$ ddev delete -Oy
ddev.exe not found in $PATH, please install it on Windows side; err=exec: "ddev.exe": executable file not found in $PATH
Volume postgres-snapshot-debug-mariadb for project postgres-snapshot-debug was deleted
```

However, DDEV is installed in Win10 (via choco)

```shell
❯ pwd
D:\code

❯ ddev -v
ddev version v1.21.4

❯  which ddev
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     ddev.exe                                           0.0.0.0    C:\Program Files\DDEV\ddev.exe
```

### Expected Behavior

The error is a false positive and should not be displayed.

### Actual Behavior

```shell
$ ddev delete -Oy
ddev.exe not found in $PATH, please install it on Windows side; err=exec: "ddev.exe": executable file not found in $PATH
```

**Comment by rfay** [comment]
Please install DDEV on the Windows side so it can be used to manage the Windows hosts file. You can do this with `choco install -y ddev` or by downloading the Windows installer.

**Comment by rfay** [comment]
Oh, sorry, looks like you did. You can debug this by trying to run ddev.exe in WSL2. If it can't be found, take a look at $PATH.

**Comment by tyler36** [comment]
I'm sorry, I don't understand.

I have DDEV working in WSL2. IE. I can start projects install inside Ubuntu.
I have DDEV working on Win10. IE. I can start projects running on "d:\code"

## Windows 10

```shell
❯ ddev start
...
Project can be reached at https://debug.ddev.site https://127.0.0.1:60486
❯ pwd
D:\code\temp\debug
❯  which ddev
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     ddev.exe                                           0.0.0.0    C:\Program Files\DDEV\ddev.exe
```

- DDEV is still found despite being in a different directory, so it is on a path

## WSL

```ddev
$ ddev start
Project can be reached at https://postgres-snapshot-debug.ddev.site https://127.0.0.1:60412
$ pwd
/home/user13/code/playground/postgres-snapshot-debug
$ ddev delete -Oy
Container ddev-postgres-snapshot-debug-dba  Removed
Container ddev-postgres-snapshot-debug-db  Removed
Container ddev-postgres-snapshot-debug-web  Removed
Network ddev-postgres-snapshot-debug_default  Removed
ddev.exe not found in $PATH, please install it on Windows side; err=exec: "ddev.exe": executable file not found in $PATH

```

**Comment by rfay** [comment]
In WSl2, `echo $PATH`. We're looking for the Windows PATH to be in there for accessing ddev.exe on the Windows side. This is set up by default by WSL2, but perhaps you've overridden it with something in your .profile, .bash_profile, .zshrc, etc.

**Comment by tyler36** [comment]
I've just removed DDEV from windows and re-installed.

`choco install ddev -y` adds DDEV to the system variable path, NOT the user variable path.

**Comment by tyler36** [comment]
Confirming; in WSL2, `echo $PATH` reports the user variable path.

**Comment by tyler36** [comment]
I get a warning, rightfully, when trying to install DDEV via choco in a "normal" terminal.

```shell
 choco install ddev
Chocolatey v1.2.1
Chocolatey detected you are not running from an elevated command shell
 (cmd/powershell).

 You may experience errors - many functions/packages
 require admin rights. Only advanced users should run choco w/out an
 elevated shell. When you open the command shell, you should ensure
 that you do so with "Run as Administrator" selected. If you are
 attempting to use Chocolatey in a non-administrator setting, you
 must select a different location other than the default install
 location. See
 https://docs.chocolatey.org/en-us/choco/setup#non-administrative-install
 for details.


 Do you want to continue?([Y]es/[N]o):
```

Running from an elevated terminal ("Run as administrator") add DDEV to the system variable path.

**Comment by rfay** [comment]
The system variable PATH is included for every user, that's what it means to be the system PATH. 

You should have `/mnt/c/Program Files/DDEV` in your $PATH in WSL2. That would normally be there; it's easy to add it anyway if it's not, in your .profile/.bash_profile/.zshrc/.bashrc/etc

Maybe you can see if `wsl -t Ubuntu` (or name of your distro) followed by a restart of the distro ends you up with `/mnt/c/Program Files/DDEV` in your $PATH in WSL2. Otherwise, look for suspicious things in your config that are overriding PATH instead of adding to it.

**Comment by rfay** [comment]
`choco` must always be run from an admin PS.

**Comment by rfay** [comment]
BTW, thanks for working on this. I'm sure if you're having this others will as well. I found that it worked perfectly with the new WSL2 install scripts though...

**Comment by tyler36** [comment]
On the Windows site, my user variable path do NOT include all of my system variables. Eg. the recently append DDEV entry only appears on my system variable side; even after a hard reboot. Seems my system is not syncing them; no idea why.

**Comment by rfay** [comment]
This is just a normal Windows feature, but you should probably reboot to see if things get sorted. Your $PATH on the Windows side should always be the combination of your system and user PATH variables.

**Comment by rfay** [comment]
To be clear, on the Windows side %PATH% in cmd or $env:PATH in PS should show the concatenation of the system and user settings for PATH that you would set in Windows settings.

**Comment by tyler36** [comment]
No luck. After powering off, fetching a coffee and powering on, that Windows "feature" was not working.
System variables path contained referencing to DDEV and multiple php versions (and others) that did not exist in my user variables path.

Manually sync'd path and rebooted and it works.

**Comment by rfay** [comment]
How did you "manually sync the path"?

**Comment by tyler36** [comment]
Under "Environmental Variables" popup
![image](https://user-images.githubusercontent.com/7234392/208805634-152f7d3d-8122-4f5e-ac12-4b1f30e3cb31.png)

Now I get a popup from `gsudo` which I have to click to continue. I think I preferred it "broken".

**Comment by rfay** [comment]
You're saying that you just added the system PATH into your User path? Shouldn't have to do that.

* To calm down gsudo, you can cache it. https://github.com/gerardog/gsudo#credentials-cache
* I assume you're using a domain name that cannot be resolved? Otherwise you shouldn't have to deal with this?

**Comment by tyler36** [comment]
> You're saying that you just added the system PATH into your User path? Shouldn't have to do that.
Yes, that what I did. Even after a reboot, and a shutdown, there were missing values so something was amiss. Perhaps, now that they are the same, that will continue (?).

> I assume you're using a domain name that cannot be resolved? Otherwise you shouldn't have to deal with this?
Just "normal" domains; "d95-demo", "postgres-snapshot-debug", "lara-docker". Have not had a problem resolving names and I spin up 5-6 different projects from WSL.

This morning, I created a "postgres-snapshot-debug" project. Then I went to delete it with `ddev delete -Oy`, and saw the message.

**Comment by rfay** [comment]
On `ddev delete`, DDEV inside WSL2 has no way to know if there is an entry in the Windows-side hosts file, so that can definitely happen.

But you're not seeing escalation or ddev.exe run with normal ddev.site project creation are you?

**Comment by tyler36** [comment]
No escalation during normal use, only with `ddev delete -Oy`.

Thanks for the follow up and help. The initial problem seems to from my borked path sync. DDEV is working as intended!

**Comment by rfay** [comment]
I am interested in your experience. I wish we knew what was going on with the Windows-side PATH. (Note that you could also have sorted this out on the WSL2 side by adding a bit to the PATH).

But...
* We may want to add to the docs about `gsudo config CacheMode auto` and `gsudo cache on`
* This feature does help people a lot who use additional_fqdns, use a project_tld that is not ddev.site, or who can't resolve ddev.site for other reasons (typically a Fritzbox router). 
* I did stumble on the annoyance of `ddev delete` always escalating, and think there ought to be a way around that. What happens is that wsl2 ddev issues `gsudo.exe ddev.exe hostname -r <hostname>`, but of course, the escalation is done then. Probably adding a feature to ddev.exe to *check* for the hostname, `ddev.exe hostname --check <something>` could help sort this in cases like yours. If WSL2 ddev executed `ddev.exe hostaname --check <domainname> && gsudo.exe ddev.exe hostname -r <domainname>` then the escalation wouldn't happen. It has potential.

**Comment by tyler36** [comment]
I understand.

- `gsudo config CacheMode auto` in the docs would some people who can self-debug, and theres a reference for future users.
- I don't require additional_fqdns, so I haven't walked down any of those workflows (no need to complicate things 😄 )
- I've seen a few debugging threads from our EU friends that often use Fritzbox routers, so I would recommend keeping it.
- A check _would_ be useful for people in my case. 

There's always an option of a simple settings. 
- If you use fritzbox, or add additional_fqdns, you need to set the `manage_hosts: true`. 

Checks can be good, but harder to maintain. 
Settings are simple, but can be overlooked / forgotten.
