### ISSUE TITLE
`ddev composer create` No longer respects composer root configuration

### ISSUE THREAD

**Issue by flynnt** [drud/ddev#4475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Running the following commands:
`ddev config --project-type=craftcms --docroot=app/web --create-docroot --composer-root=app --web-environment-add=CRAFT_CMD_ROOT=./app`
`ddev start`
`ddev composer create -y --no-scripts craftcms/craft`

should initialize a Craft project in the configured composer root and install the project dependencies based on the `composer.json` file in the composer root.

### Actual Behavior

Running the following commands:
`ddev config --project-type=craftcms --docroot=app/web --create-docroot --composer-root=app --web-environment-add=CRAFT_CMD_ROOT=./app`
`ddev start`
`ddev composer create -y --no-scripts craftcms/craft`

does initialize a Craft project that is moved correctly to the Composer root, but the subsequent `composer install --no-scripts` command run fails with: `Composer could not find a composer.json file in /var/www/html`, which suggests that composer is being run outside of the configured composer root.

### Steps To Reproduce

`ddev config --project-type=craftcms --docroot=app/web --create-docroot --composer-root=app --web-environment-add=CRAFT_CMD_ROOT=./app`
`ddev start`
`ddev composer create -y --no-scripts craftcms/craft`

See error: `Composer could not find a composer.json file in /var/www/html`

### Anything else?

This appears to be a regression, as this did work in `v1.21.3`.

**Comment by rfay** [comment]
Interestingly enough, `ddev composer install` afterward works fine.

**Comment by rfay** [comment]
It looks like the problem is here, 
https://github.com/drud/ddev/blob/8fa51f444a88ee95fa2535b563a234b377c12a4c/cmd/ddev/cmd/composer-create.go#L192-L198

I think it should be `Dir: /var/www/html/<composer_root>`, not sure

/cc @gilbertsoft

**Comment by rfay** [comment]
Also `ddev composer create -y --no-scripts craftcms/craft --no-install` works fine, followed by `ddev composer install`. And I think this was previously in the quickstart this way, which is why this wasn't discovered probably.

**Comment by rfay** [comment]
Changed title, as I don't think this has to do with Craft CMS.

**Comment by rfay** [comment]
@flynnt I'd sure appreciate if you could test and review
* https://github.com/drud/ddev/pull/4611#issuecomment-1416582838

**Comment by flynnt** [comment]
I'll have a look today.

**Comment by flynnt** [comment]
@rfay This looks good to me. I tested it with the commands from the original issue and also with the steps in the DDEV Craft CMS quickstart documentation. In both cases `ddev composer create` worked as expected.

**Comment by rfay** [comment]
Thanks so much @flynnt
