### ISSUE TITLE
Database isolation warning error on new Drupal 9 install (fixed by `ddev restart`)

### ISSUE THREAD

**Issue by pheski** [drud/ddev#4483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

started new Drupal 9.5 with current ddev and got a database isolation level warning that requires a restart to make the warning go away. Site works fine despite the warning.

### Expected Behavior

Expected success.

### Actual Behavior

I got (repeated 4 times to ensure not a fluke) a warning thatr database isolation level was REPEATABLE HEAD and should be changed to READ COMMIT. This error goes away with a restart.

<img width="1095" alt="Screen Shot 2022-12-22 at 1 59 24 PM" src="https://user-images.githubusercontent.com/1130881/209209456-4135118a-4d33-4692-a3a0-49912da8a298.png">

### Steps To Reproduce

Mac OS 12.6.2 using DDEV v1.21.4 following this process to spin up a new Drupal 9.5 project:

mkdir <test-project>
cd <test-project>
ddev config --project-type=drupal9 --docroot=web --create-docroot --database=mysql:8.0
ddev start
ddev composer create "drupal/recommended-project:^9.0" --no-install
ddev composer require drush/drush --no-install
ddev composer install
ddev drush site:install -y  
ddev drush uli
ddev launch

After ddev restart the warning is gone.  

### Anything else?

(My first time submitting an issue. Sorry if I have not done it correctly.)

**Comment by pheski** [comment]
Perhaps only needs a comment in the docs about a restart?

**Comment by rfay** [comment]
Thanks for the issue. I don't understand why this requires a restart :)

**Comment by tyler36** [comment]
Was able to replicate issue with OP's instructions

## Test

- Config DDEV

    ```shell
    ddev config --project-type=drupal9 --docroot=web --create-docroot --database=mysql:8.0
    ddev start
    ```

- Install Drupal

    ```shell
    ddev composer create "drupal/recommended-project:^9" --no-install
    ddev composer require drush/drush --no-install
    ddev composer install
    ddev drush site:install -y
    ```

- Log in and visit `/admin/reports/status#warning`

## Additional 

- If you stop DDEV and remove the database, the warning does NOT occur

    ```shell
    ddev stop
    ddev delete -Oy
    ddev drush site:install -y
    ```

## Additional Gitpod

- A repo based on steps in test and opened with DDEV Gitpod bookmark did NOT show warning.

**Comment by rfay** [comment]
> A repo based on steps in test and opened with DDEV Gitpod bookmark did NOT show warning.

That's *really* weird.

**Comment by tyler36** [comment]
At first, I expect Gitpod to fail.

Looking at the CLI though, there appears to be a restart after composer install:

```shell
...
  - Copy [web-root]/themes/README.txt from assets/scaffold/files/themes.README.txt
  * Homepage: https://www.drupal.org/project/drupal
  * Support:
    * docs: https://www.drupal.org/docs/user_guide/en/index.html
    * chat: https://www.drupal.org/node/314178
Container ddev-d9-db-commit-dba  Removed 
Container ddev-d9-db-commit-db  Removed 
Container ddev-d9-db-commit-web  Removed 
Network ddev-d9-db-commit_default  Removed 
Project d9-db-commit has been stopped. 
Starting d9-db-commit... 
Network ddev-d9-db-commit_default  Created 
Container ddev-d9-db-commit-db  Started 
Container ddev-d9-db-commit-web  Started 
Container ddev-d9-db-commit-dba  Started 
Successfully started d9-db-commit 
```

Don't remember if I tested the original PR in Gitpod or WSL2

**Comment by tyler36** [comment]
Just tested postgres (`postgres:14`) on WSL2 and hitting the same issue. 

## Test

- Config DDEV, note `--database=postgres:14`

```shell
ddev config --project-type=drupal9 --docroot=web --create-docroot --database=postgres:14
ddev start
```

- Install Drupal

```shell
ddev composer create "drupal/recommended-project:^9" --no-install
ddev composer require drush/drush --no-install
ddev composer install
ddev drush site:install -y
```

- Log in and visit `/admin/reports/status#warning`
   - `PostgreSQL pg_trgm extension Not created`

- Restart DDEV, visit `/admin/reports/status#warning` and warning does NOT show.

```shell
ddev restart
```

**Comment by rfay** [comment]
Here's the code; it's done in drupal9+ post-start:

https://github.com/drud/ddev/blob/c6a2fc4caedf5f9240c05c8c6e8e4a3937b9c2a6/pkg/ddevapp/drupal.go#L384-L408

**Comment by rfay** [comment]
So IsDrupal9App() and IsDrupal10App() use the *code* to determine whether the project is of those types:

https://github.com/drud/ddev/blob/c6a2fc4caedf5f9240c05c8c6e8e4a3937b9c2a6/pkg/ddevapp/drupal.go#L317-L331

But in the scenario shown here, the *code* is not there at start time. Nothing is there yet. that's why this works when you do a `ddev restart`.

Since the recommended technique in the quickstart works fine, and since this works after a restart even when you do it this way, I'm going to close this; I don't think we need to chase it.  Other opinions are welcome.

**Comment by gitressa** [comment]
I also got this warning after starting a project, possibly due to running `ddev composer install`, forgetting to run `ddev start` first?

Anyway, like others have observed, after a restart the warning is gone.
