### ISSUE TITLE
"ddev start" can result in web container without /var/www/html mount (no status provided)

### ISSUE THREAD

**Issue by rfay** [drud/ddev#449]
## What happened (or feature request):

On more than one site I started from scratch, did a ddev config and start, had ddev list showing everything fine, but it was completely broken due to /var/www/html not being a valid mount. We should probably check that in the status check.

I did `rm -rf .ddev` then a `ddev config`, then a `ddev start`

`ddev list` showed everything running just fine. However, /var/www/html was apparently not mounted at all:

```
$ ddev ssh
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
root@6fd62d32ff64:.# cd /var/www/html
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

root@6fd62d32ff64:/var/www/html# df /var/www/html
Filesystem     1K-blocks      Used Available Use% Mounted on
osxfs          487358464 328864588 158237876  68% /var/www/html
```

The problem could be solved with a `ddev start && ddev stop`, but after I had to do that a couple of times I got suspicious.

## Version: Please include the output of `ddev version` and the project's .ddev/config.yaml.

docker 17.06.1-ce

```
$ ddev version
cli:       	v0.9.1
web:       	drud/nginx-php-fpm7-local:v0.7.4
db:        	drud/mysql-local-57:v0.6.2
dba:       	drud/phpmyadmin:v0.2.0
router:    	drud/ddev-router:v0.4.3
commit:    	v0.9.1
build info:	Built Wed Aug 23 19:23:48 UTC 2017 circleci@prealloc-dmiqwyml-0bdaa5ed-1565-4a78-95e9-68dbad331de6 drud/golang-build-container:v0.4.2
```

```
APIVersion: "1"
name: aplv
type: drupal7
docroot: ""
webimage: drud/nginx-php-fpm7-local:v0.7.4
dbimage: drud/mysql-local-57:v0.6.2
dbaimage: drud/phpmyadmin:v0.2.0
provider: default

# Certain ddev commands can be extended to run tasks before or after the ddev
# command is executed.
# See https://ddev.readthedocs.io/en/latest/users/extending-commands/ for more
# information on the commands that can be extended and the tasks you can define
# for them.
# hooks:
#   post-import-db:
#     - exec: "drush cc all"
```

## Related source links or issues:

**Comment by rfay** [comment]
This just happened to me another time.  This time I checked and the mount was there, but then did a ddev import-db and when I checked again the mount (on web container) was gone.

**Comment by rickmanelius** [comment]
Seems like a bug worth prioritizing in 1.0.0. Need to confirm we can recreate this first before it's truly actionable.

**Comment by rickmanelius** [comment]
I'm going to add this one to my plate. If I can't recreate, I'll close or just remove the milestone and leave it open in case it comes back to bite us.

**Comment by rickmanelius** [comment]
Similar to the reference #445, I'm curious if this is more of a memory allocation/Docker performance issue specific to your machine. If it is and we track it down to that, we may want to provide a warning/caveat to users regarding a preferred minimum hardware setup or memory allocation.

**Comment by rfay** [comment]
Both Brad and I have had repeated issues with this, but I haven't seen it for a couple of weeks. I think both can be closed, but will be surprised if we don't see them again.

**Comment by rickmanelius** [comment]
Cool. If we see it happen again with a clear path to repeat, we'll make this sucker actionable.

**Comment by rfay** [comment]
Happened to run across associated docker issue for this. Sounds like this may still be "live". The description in the docker issue tracks when the problem appeared for us, and appears to be the same. https://github.com/docker/for-mac/issues/1509

**Comment by rfay** [comment]
I'm seeing this quite a lot in a testing scenario; reopening for now in case it's a reappearance in docker world.

**Comment by rfay** [comment]
As far as I can tell, this is a docker issue and is likely to reappear.

We'll see it a bit more now as ddev version v1.3 adds a healthcheck to looks to see if /var/www/html is healthy. So now this will be reported more instead of being something we have to study whenever it happens.

Note that it's easy to *create* this problem by starting a project and then `mv <approot> <somewhereelse>` on the host.

Closing for now.

**Comment by rfay** [comment]
The issue in https://github.com/docker/for-mac/issues/1509#issuecomment-429420872 continues to gain traction, and in the noted comment implies the situation of mounting a directory onto one container and a subdirectory of it onto another container. Which we do with .ddev.
