### ISSUE TITLE
xhprof admin

### ISSUE THREAD

**Issue by sreichel** [drud/ddev#4492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I’m always frustrated when...

... i run xhprof and can't compare runs easily.

### Describe your solution

Replace default (or extend) xhprof with something that offers better output.

### Describe alternatives

Possible alternative ... https://github.com/SergeyRock/xhprof-admin / https://github.com/OpenMage/magento-lts/pull/2821#issuecomment-1364655438

**Comment by rfay** [comment]
Maybe you could add this to 
* https://github.com/drud/ddev/issues/3782

Or maybe you want to work on a PR?

**Comment by sreichel** [comment]
Will add it there. I'm no docker/ddev expert ... not sure whre to start with a PR.

**Comment by sreichel** [comment]
Moved to #3782
