### ISSUE TITLE
$DDEV_PHP_VERSION build time environment variable incorrect

### ISSUE THREAD

**Issue by krlucas** [drud/ddev#4497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

Running bash [-c /var/folders/_k/dl3lc4fn5rg7mtcknf5x2lpm0000gq/T/test_ddev.sh] 
======= Existing project config =========
These config files were loaded for project accounts: [/Users/XXXXX/Projects/XXXXXX/.ddev/config.yaml]
name: accounts
type: drupal9
docroot: docroot
php_version: 8.0
webserver_type: nginx-fpm
webimage: drud/ddev-webserver:v1.21.4
router_http_port: 80
router_https_port: 443
additional_hostnames: []
additional_fqdns: []
database: {mariadb 10.4}
mailhog_port: 8025
mailhog_https_port: 8026
phpmyadmin_port: 8036
phpmyadmin_https_port: 8037
project_tld: ddev.site
use_dns_when_possible: true
composer_version: 2
nodejs_version: 16
default_container_timeout: 120
======= Creating dummy project named  tryddevproject-9582 in ../tryddevproject-9582 =========
OS Information: Darwin L105576MUS 21.6.0 Darwin Kernel Version 21.6.0: Sun Nov  6 23:29:57 PST 2022; root:xnu-8020.240.14~1/RELEASE_ARM64_T8101 arm64
ProductName:	macOS
ProductVersion:	12.6.2
BuildVersion:	21G320
User information: uid=503(lucak) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),80(admin),701(com.apple.sharepoint.group.1),33(_appstore),98(_lpadmin),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),400(com.apple.access_remote_ae)
DDEV version:  ITEM             VALUE                                   
 DDEV version     v1.21.4                                 
 architecture     arm64                                   
 db               drud/ddev-dbserver-mariadb-10.4:v1.21.4 
 dba              phpmyadmin:5                            
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.4             
 docker           20.10.21                                
 docker-compose   v2.14.0                                 
 docker-platform  docker-desktop                          
 mutagen          0.16.0                                  
 os               darwin                                  
 router           drud/ddev-router:v1.21.4                
 web              drud/ddev-webserver:v1.21.4             
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=false
omit-containers=[]
mutagen-enabled=false
nfs-mount-enabled=false
router-bind-all-interfaces=false
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
auto-restart-containers=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=
use-docker-compose-from-path=false
project-tld=
xdebug-ide-location=
no-bind-mounts=false
use-traefik=false

======= DOCKER info =========
docker location: lrwxr-xr-x  1 root  wheel  54 Aug  5 15:53 /usr/local/bin/docker -> /Applications/Docker.app/Contents/Resources/bin/docker
Docker Desktop Version: Docker Desktop for Mac 4.15.0 build 93002
docker version: 
Client:
 Cloud integration: v1.0.29
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:18 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.15.0 (93002)
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 17:59:41 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
DOCKER_DEFAULT_PLATFORM=notset
======= Mutagen Info =========
======= Docker Info =========
Docker platform: docker-desktop 
Using docker context: default (unix:///var/run/docker.sock) 
docker-compose: v2.14.0 
Using DOCKER_HOST=unix:///var/run/docker.sock 
Docker version: 20.10.21 
Able to run simple container that mounts a volume. 
Able to use internet inside container. 
Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                 393.4G     30.0G    343.4G   8% /

Container ddev-accounts-dba  Removed 
Container ddev-accounts-db  Removed 
Container ddev-accounts-web  Removed 
Network ddev-accounts_default  Removed 
Project accounts has been stopped. 
The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again. 
Existing docker containers: 
CONTAINER ID   IMAGE                       COMMAND                  CREATED        STATUS                      PORTS                        NAMES
3c6c085fe6c1   docksal/web:apache2.2       "httpd-foreground"       6 days ago     Exited (255) 20 hours ago   80/tcp, 443/tcp              accounts_web_1
de10c94a0026   accounts_cli                "/opt/startup.sh sup…"   6 days ago     Exited (255) 20 hours ago   22/tcp, 3000/tcp, 9000/tcp   accounts_cli_1
aad859c6f5e2   mailhog/mailhog             "MailHog"                6 days ago     Exited (255) 20 hours ago   80/tcp, 1025/tcp, 8025/tcp   accounts_mail_1
f17316bb5a73   docksal/mariadb:10.6-1.3    "docker-entrypoint.s…"   2 months ago   Exited (255) 2 months ago   127.0.0.1:55024->3306/tcp    forums_db_1
dc15c186ad1c   docksal/web:2.1-apache2.4   "httpd-foreground"       2 months ago   Exited (255) 2 months ago   80/tcp, 443/tcp              forums_web_1
8cd28a56f31a   forums_cli                  "/opt/startup.sh sup…"   2 months ago   Exited (255) 2 months ago   22/tcp, 3000/tcp, 9000/tcp   forums_cli_1
b4246cfc3443   mailhog/mailhog:v1.0.1      "MailHog"                2 months ago   Exited (255) 2 months ago   1025/tcp, 8025/tcp           forums_mail_1
315ecc516c07   memcached                   "docker-entrypoint.s…"   2 months ago   Exited (255) 2 months ago   127.0.0.1:55019->11211/tcp   forums_memcached_1
94888b670f10   docksal/solr:6-2.1          "docker-entrypoint.s…"   2 months ago   Exited (255) 2 months ago   0.0.0.0:8983->8983/tcp       forums_solr_1
3b5a2b63e83a   docksal/mariadb:10.6-1.3    "docker-entrypoint.s…"   3 months ago   Exited (255) 20 hours ago   127.0.0.1:55001->3306/tcp    accounts_db_1
551527cde92b   memcached                   "docker-entrypoint.s…"   4 months ago   Exited (255) 20 hours ago   127.0.0.1:55000->11211/tcp   accounts_memcached_1
Creating a new ddev project config in the current directory (/Users/lucak/Projects/tryddevproject-9582) 
Once completed, your configuration will be written to /Users/lucak/Projects/tryddevproject-9582/.ddev/config.yaml
 
Configuring unrecognized codebase as project type 'php' at /Users/lucak/Projects/tryddevproject-9582/web 
Configuration complete. You may now run 'ddev start'. 
Network ddev_default created 
Starting tryddevproject-9582... 
Container ddev-ssh-agent  Started 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
Network ddev-tryddevproject-9582_default  Created 
Container ddev-tryddevproject-9582-dba  Started 
Container ddev-tryddevproject-9582-db  Started 
Container ddev-tryddevproject-9582-web  Started 
mkcert may not be properly installed, we suggest installing it for trusted https support, `brew install mkcert nss`, `choco install -y mkcert`, etc. and then `mkcert -install` 
Container ddev-router  Started 
Successfully started tryddevproject-9582 
Project can be reached at http://tryddevproject-9582.ddev.site http://127.0.0.1:51652 
======== Curl of site from inside container:
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 27 Dec 2022 22:47:00 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== curl -I of http://tryddevproject-9582.ddev.site from outside:
HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Tue, 27 Dec 2022 22:47:00 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== full curl of http://tryddevproject-9582.ddev.site from outside:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-9582'
======== Project ownership on host:
drwxr-xr-x  4 lucak  staff  128 Dec 27 17:46 ../tryddevproject-9582
======== Project ownership in container:
drwxr-xr-x 4 root root 128 Dec 27 22:46 /var/www/html
======== In-container filesystem:
Filesystem       Type      1K-blocks      Used Available Use% Mounted on
/host_mark/Users fakeowner 971350180 135626924 835723256  14% /var/www/html
======== curl again of tryddevproject-9582 from host:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-9582'
Thanks for running the diagnostic. It was successful.
Please provide the output of this script in a new gist at gist.github.com
Running ddev launch in 5 seconds
If you're brave and you have jq you can delete all tryddevproject instances with this one-liner:
    ddev delete -Oy $(ddev list -j |jq -r .raw[].name | grep tryddevproject)
In the future ddev debug test will also provide this option.

Please delete this project after debugging with 'ddev delete -Oy tryddevproject-9582'

### Expected Behavior

When using the `DDEV_PHP_VERSION` build time environment variable, I expect it to match the setting in my config.yaml file.

### Actual Behavior

I need to build a custom PHP extension so I tried installing some prerequisites using the $DDEV_PHP_VERSION environment variable.
```
RUN sudo apt install -y build-essential zlib1g-dev libssl-dev libsasl2-dev php${DDEV_PHP_VERSION}-dev
```
but it installs php8.2-dev instead of php8.0-dev as specified in my config.yml.

```
#11 [ 8/10] RUN sudo apt install -y build-essential zlib1g-dev libssl-dev libsasl2-dev php${DDEV_PHP_VERSION}-dev
...
#11 1.026 The following NEW packages will be installed:
#11 1.026   autopoint binutils binutils-aarch64-linux-gnu binutils-common bsdextrautils
#11 1.026   build-essential cpp cpp-10 debhelper dh-autoreconf dh-strip-nondeterminism
#11 1.026   dpkg-dev dwz fakeroot g++ g++-10 gcc gcc-10 groff-base intltool-debian
#11 1.026   libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl
#11 1.026   libarchive-cpio-perl libarchive-zip-perl libasan6 libbinutils libc-dev-bin
#11 1.026   libc-devtools libc6-dev libcc1-0 libcrypt-dev libctf-nobfd0 libctf0
#11 1.026   libdebhelper-perl libdpkg-perl libfakeroot libfile-fcntllock-perl
#11 1.026   libfile-stripnondeterminism-perl libgcc-10-dev libisl23 libitm1
#11 1.026   liblocale-gettext-perl liblsan0 libltdl-dev libmail-sendmail-perl libmpc3
#11 1.026   libmpfr6 libnsl-dev libpcre2-16-0 libpcre2-32-0 libpcre2-dev libpcre2-posix3
#11 1.026   libpipeline1 libsasl2-dev libssl-dev libstdc++-10-dev libsub-override-perl
#11 1.026   libsys-hostname-long-perl libtirpc-dev libtool libtsan0 libubsan1
#11 1.026   libuchardet0 linux-libc-dev make man-db manpages manpages-dev php-dev
#11 1.026   php-pear php8.2-dev pkg-config pkg-php-tools po-debconf shtool xz-utils
#11 1.026   zlib1g-dev
```

I confirmed that hardcoding the correct version (8.0) works as expected.

**Comment by rfay** [comment]
I apologize. DDEV_PHP_VERSION is available in current HEAD and will be in the next release. The "latest" docs are absolute latest (unreleased). Stable docs are the current release.

**Comment by rfay** [comment]
I'll do a docs PR saying that up through v1.21.4 you have to add that yourself.

**Comment by rfay** [comment]
* https://github.com/drud/ddev/pull/4498

You can either use DDEV HEAD (with homebrew `brew unlink ddev && brew install --HEAD ddev`) or just define DDEV_PHP_VERSION in your Dockerfile - `ENV DDEV_PHP_VERSION=8.1`

**Comment by krlucas** [comment]
Wow thanks for the quick response @rfay! 

Got it. Thanks for the explanation.

So I think I could do something like 
`ENV DDEV_PHP_VERSION=${DDEV_PHP_VERSION:-8.0}`
and I won't necessarily need to update the Dockerfile once `DDEV_PHP_VERSION` appears in the next release.

**Comment by rfay** [comment]
I'm not sure that (bash) notation works (`DDEV_PHP_VERSION=${DDEV_PHP_VERSION:-8.0}`) in Dockerfile, but if you'll confirm that it does with a docs link I'll update the PR.

**Comment by krlucas** [comment]
It does seem to work.

I updated my Dockerfile:
```
ENV DDEV_PHP_VERSION=${DDEV_PHP_VERSION:-8.0}
...
RUN sudo apt install -y build-essential zlib1g-dev libssl-dev libsasl2-dev php${DDEV_PHP_VERSION}-dev
```

and now the (partial) output from `ddev debug refresh && ~/.ddev/bin/docker-compose -f .ddev/.ddev-docker-compose-full.yaml build web --no-cache --progress=plain` is 
```
#11 [ 8/10] RUN sudo apt install -y build-essential zlib1g-dev libssl-dev libsasl2-dev php8.0-dev
...
#11 1.054 The following NEW packages will be installed:
#11 1.054   autopoint binutils binutils-aarch64-linux-gnu binutils-common bsdextrautils
#11 1.054   build-essential cpp cpp-10 debhelper dh-autoreconf dh-strip-nondeterminism
#11 1.054   dpkg-dev dwz fakeroot g++ g++-10 gcc gcc-10 groff-base intltool-debian
#11 1.054   libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl
#11 1.054   libarchive-cpio-perl libarchive-zip-perl libasan6 libbinutils libc-dev-bin
#11 1.054   libc-devtools libc6-dev libcc1-0 libcrypt-dev libctf-nobfd0 libctf0
#11 1.054   libdebhelper-perl libdpkg-perl libfakeroot libfile-fcntllock-perl
#11 1.054   libfile-stripnondeterminism-perl libgcc-10-dev libisl23 libitm1
#11 1.054   liblocale-gettext-perl liblsan0 libltdl-dev libmail-sendmail-perl libmpc3
#11 1.054   libmpfr6 libnsl-dev libpcre2-16-0 libpcre2-32-0 libpcre2-dev libpcre2-posix3
#11 1.054   libpipeline1 libsasl2-dev libssl-dev libstdc++-10-dev libsub-override-perl
#11 1.054   libsys-hostname-long-perl libtirpc-dev libtool libtsan0 libubsan1
#11 1.054   libuchardet0 linux-libc-dev make man-db manpages manpages-dev php-pear
#11 1.054   php8.0-dev pkg-config pkg-php-tools po-debconf shtool xz-utils zlib1g-dev
```

I got the tip for that notation here: https://stackoverflow.com/questions/37057468/conditional-env-in-dockerfile
