### ISSUE TITLE
As a ddev developer, I want a flow diagram indicating typical use cases as well as CMS and provider support.

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#45]
This is a documentation item to note the different use cases.

Suggestion from @beeradb is to split the current diagram into the installation and usage phases to reduce complexity.

**Comment by rickmanelius** [comment]
I'll take the lead in converting this to an actionable state. Additionally, I believe flow diagrams will help address a few common questions that have come up with respect to CMS and hosting provider support. We're tracking an overall meta issue here https://github.com/drud/ddev/issues/469, and I believe this issue would be a reasonable deliverable to roll up into that.

**Comment by rickmanelius** [comment]
I've started to work on this in #534 (see attached google doc w/images).

**Comment by rickmanelius** [comment]
Related to #242. Moving to that moment in time.

**Comment by rfay** [comment]
This has been around a long time. If there's something we're going to do, let's say it and do it. Otherwise, let's close this.

**Comment by rickmanelius** [comment]
Old and stale. There will be other opportunities to address this from a marketing side of things.
