### ISSUE TITLE
DDev fails to update hosts file on NixOS

### ISSUE THREAD

**Issue by jgonyea** [drud/ddev#4500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/jgonyea/241b00df24c4bb7babdbc57614b079bf

### Expected Behavior

ddev creates host entries

### Actual Behavior

Due to how NixOS generates its hosts file, the hosts file is read-only.  The attempted addition of new hostnames into the hosts file fails.

### Steps To Reproduce

1. Install NixOS
2. Install docker/ docker compose
3. Download ddev binary from github ddev releases, as the typical installation methods fail
4. Run `ddev config` on a project
5. Run `ddev start` on said project
6. Project starts, but with errors while attempting to generate the hosts entries

### Anything else?

This bug report is an extreme edge case, and I just wanted to note it down if someone else tried to use ddev on NixOS.

The hosts file on NixOS can be updated via editing the /etc/nixos/configuration.nix (or subsequent nix import) that modifies the following property:
```
networking.extraHosts = ''
  127.0.0.2 other-localhost
  10.0.0.1 server
'';
```
as per https://nixos.wiki/wiki/Networking

and then performing a `nixos-rebuild switch` to apply the configuration.

**Comment by jgonyea** [comment]
I forgot to mention that ddev does start a container that is reachable via the IP address in `ddev describe`

**Comment by jgonyea** [comment]
Thanks, @rfay.  I really don't expect ddev to support nixOS, but I wanted to just let the next person who tries this to see what I had found.

**Comment by rfay** [comment]
Interested in what you're up to, and thanks for pointing it out. What is driving your use of nixOS, or were you just trying it out? I know that @shaal is fascinated with it.

**Comment by rfay** [comment]
But also, were you unable to look up `*.ddev.site` in NixOS?

**Comment by jgonyea** [comment]
> But also, were you unable to look up *.ddev.site in NixOS?

Correct, this doesn't load via the dns name.  The IP address entry into the project loads just fine.

> Interested in what you're up to, and thanks for pointing it out. What is driving your use of nixOS, or were you just trying it out? I know that @shaal is fascinated with it.

Is morbid curiosity a valid reason? I'm often developing across sometimes 3 or more devices, and the ability to configure everything on the system via a programmatic configuration that's deployable to all machines seems like a neat idea.

**Comment by rfay** [comment]
Well, DDEV is already trying to solve the fundamental problem that NixOS is good at... getting all your configuration into source control and running a project the same everywhere.

I would think you might want to chase down why DNS isn't working in NixOS. Is all DNS broken? There are some classic answers in https://ddev.readthedocs.io/en/latest/users/usage/troubleshooting/#ddev-starts-but-browser-cant-access-url

**Comment by jgonyea** [comment]
The problem in NixOS is that the /etc/hosts is read-only, even to root, as it's generated from a nix config (sort of a json-y file). I can manually add the entries the nix config and run the `nixos-rebuild switch` command and then the DNS entry of my project works.

**Comment by rfay** [comment]
Hosts and DNS are not the same thing. DDEV normally does not have to update the hosts file for any project that doesn't have a custom TLD or have broken DNS. So the question is... can you `ping junk.ddev.site` and get a response? Can you `ping google.com` and get a response?

**Comment by jgonyea** [comment]
> Well, DDEV is already trying to solve the fundamental problem that NixOS is good at... getting all your configuration into source control and running a project the same everywhere.

DDev solves so many of my problems for PHP development!  I was attempting to solve all the rest of my development/ sysadmin things via Nix, thus my attempt (albeit done poorly so far) to marry both ddev and NixOS.

Sorry if I'm not explaining this well:

The nixos machine can reach the internet just fine.

When I start a ddev project I get the error:
```
[33mFailed to execute sudo /home/jgonyea/.local/bin/ddev hostname tryddevproject-23208.ddev.site 127.0.0.1, you will need to manually execute 'sudo /home/jgonyea/.local/bin/ddev hostname tryddevproject-23208.ddev.site 127.0.0.1' with administrative privileges, err=exit status 1, output=time="2022-12-28T12:40:23-05:00" level=warning msg="not reading global config file because running with root privileges"

[33mNot populating custom commands or hostadditions because running with root privileges
[0mCould not write hosts file: open /etc/hosts: read-only file system
```

Which led me to checking the local hosts file and finding the missing hosts entries for any ddev project.  Attempting to reach via a browser the *.ddev.site results in it attempting to reach the internet for that FQDN.  Going to http://IP:port of the project loads the webpage as expected.

I can manually add the hosts entry via nix configurations, and then the browser loads the site at the *.ddev.site as expected.

**Comment by rfay** [comment]
Right, but if `tryddevproject-23208.ddev.site` were resolvable in your setup, DDEV wouldn't be trying to add it to the hosts file. That's why I say try out `ping junk.ddev.site`. It's apparently not resolving, or DNS rebinding is blocked, or something. Because DDEV wouldn't be trying to edit the hosts file for that normally.

**Comment by jgonyea** [comment]
I think we're saying the same thing.

I see hosts entries for my ddev projects on both of my Ubuntu (x86_64) and Manjaro (ARM) installs, which were added on the first starting of a ddev project.

On Nixos, during the ddev initial site spin-up, the add hosts entry step fails, which makes the resolving break for that name.  Manually adding the hosts entry on nixos resolves the the container, and subsequent attempts of `ddev start` no longer present the error.

**Comment by rfay** [comment]
You shouldn't see hosts entries for ddev projects that don't use non ddev.site setups. On any platform that can resolve DNS.

We are not saying the same thing. Your Ubuntu and Manjaro installs (or your network) are broken; see the earlier link, https://ddev.readthedocs.io/en/latest/users/usage/troubleshooting/#ddev-starts-but-browser-cant-access-url

**Comment by rfay** [comment]
Hope I'm being clear: In a normal working situation, a normal config of DDEV will never add to the hosts file. It will add to the hosts file if you have an unresolvable fqdn (something.example.com, junk.google.com) or you have no internet access.

**Comment by jgonyea** [comment]
I understand now.

OpenDNS (my upstream DNS provider) seems to be blocking *.ddev.site, labeling it as "blocked due to a security threat", which means that ddev has been using the local hosts as its fallback.

I've always seen the hosts entry, which meant I thought that was normal behavior.  Thanks for your explanation (and patience).

**Comment by rfay** [comment]
See if you can add an exception in opendns for `*.ddev.site` - It's "helping" you with protecting you from "DNS Rebinding", not letting a hostname evaluate to 127.0.0.1. https://ddev.readthedocs.io/en/latest/users/usage/troubleshooting/#dns-rebinding-prohibited

**Comment by jgonyea** [comment]
I was able to add a whitelist for `ddev.site` (no wildcards allowed) but still keep the rebinding block enabled.  This seems to work as asdfaldskfj.ddev.site now returns a 127.0.0.1 ip address.

**Comment by rfay** [comment]
Yay!

**Comment by rfay** [comment]
@jgonyea I didn't know about OpenDNS and this rebinding issue, would like to add that to the docs. Could you please do a docs PR in the DNS rebinding section (click the pencil in upper right) or else explain step-by-step here what you had to do to whitelist ddev.site?

**Comment by Tuurlijk** [comment]
Setting `environment.etc.hosts.mode = "0644";` in `/etc/nixos/configuration.nix` solves this problem.

Please add this to the manual @rfay

**Comment by rfay** [comment]
@Tuurlijk it's not clear how that has anything to do with this issue. I recommend that you add docs to the NixOS recipe if you think something can be improved.  If you have new information on NixOS, please open a new issue with a full description, but IMO it may be better in the NixOS recipe. DDEV doesn't currently have any docs about NixOS usage. However, a guest blog in ddev.com would also be welcome.

**Comment by Tuurlijk** [comment]
This setting makes the /etc/hosts file writable by root user. Which will enable ddev to modify it. It's not something you add to the recipe, but a system wide setting that is needed to enable the hosts file to be changed. See discussion above.

Maybe I'll write a guest blog about ddev on nixos, but am booked for the coming months.

**Comment by rfay** [comment]
I guess https://github.com/ddev/ddev/issues/4500#issuecomment-1366852136 does present what you're suggesting. IIRC the actual problem in this issue was that DNS was not working, and fixing that fixed it for the user. 

But thanks for your discovery that 

> Setting environment.etc.hosts.mode = "0644"; in /etc/nixos/configuration.nix solves this problem.

A PR to the docs would be welcome, but I don't know where to put it. We don't tell people how to set up their Linux/Mac/Windows machines, so there's no real place for this to land. Thanks for pointing it out!

**Comment by rfay** [comment]
@Tuurlijk NixOS setup can be added to https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#linux - A little edit there would be very welcome, just add NixOS to the bottom, with your details for setup. You can do a regular PR or just click the pencil in the upper right.
