### ISSUE TITLE
DB container with MySQL 8 spams mbind: Operation not permitted in logs

### ISSUE THREAD

**Issue by jamesmacwhite** [drud/ddev#4504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

No mbind errors to appear in logs.

### Actual Behavior

When using MySQL 8, the logs of the DB container will continuously log:

```
mbind: Operation not permitted
```

This is a known issue and can be resolved by adding cap_add to the docker compose file for the DB container.

```yaml
cap_add:
      - SYS_NICE
```

### Steps To Reproduce

1. Use MySQL 8 for DB
2. View logs for DB container
3. Observe many logs entries for `mbind: Operation not permitted`

**Comment by rfay** [comment]
Sounds easy to solve. Could you please link to the "known issue"?

Are you able to recreate this with a trivial project?

**Comment by jamesmacwhite** [comment]
Sure, here's an example reference of the issue:

https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log

This is what it leads to with the Docker logs in the DB container:

![image](https://user-images.githubusercontent.com/8067792/209879122-a0b37c70-4aca-4b3c-a3ad-98e13b658251.png)

You should be able to trigger it by just having a DB container using MySQL 8 up and running, those logs will then be constantly written as you can see from having it running for a period of time.

**Comment by rfay** [comment]
Thanks so much for reporting this @jamesmacwhite - Should be fixed in https://github.com/drud/ddev/pull/4644 and will appear in upcoming v1.21.5.
