### ISSUE TITLE
PHPStorm does not recognise craftcms as a project type (Schema validation error) 

### ISSUE THREAD

**Issue by jamesmacwhite** [drud/ddev#4507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

I am running DDEV 1.21.4 and PHPStorm with the DDEV integration plugin using the craftcms project type. 

The setting value is valid for the version of DDEV and works fine for when using ddev commands itself.

### Actual Behavior

PHPStorm shows schema validation error with `config.yaml` when using the value "craftcms".

![image](https://user-images.githubusercontent.com/8067792/209954982-2616c92a-7d44-4314-87e4-222aa56c9cea.png)

Note: This does not cause any issues with DDEV itself

### Steps To Reproduce

1. Use PHPStorm with DDEV integration plugin
2. Setup a `config.yaml` using "craftcms" as the type
3. PHPStorm will show a validation error with the type value

**Comment by jamesmacwhite** [comment]
Just realised, this should possibly be reported to: https://github.com/php-perfect/ddev-intellij-plugin?

**Comment by jamesmacwhite** [comment]
Looks like, the problem is here: https://github.com/php-perfect/ddev-intellij-plugin/blob/main/src/main/resources/schema/ddev-config-1.19.schema.json

**Comment by jamesmacwhite** [comment]
FYI, reported to DDEV integration plugin repo: https://github.com/php-perfect/ddev-intellij-plugin/issues/141

**Comment by rfay** [comment]
Thanks, yeah, that's the right place. Thanks for chasing it down.

**Comment by jamesmacwhite** [comment]
No worries. It looks like the schema was done for 1.19 so it might need a new schema file creating for 1.20, 1.21, I'm not familar with PHPStorm plugins, but one way or another, I'm sure the schema can be updated.
