### ISSUE TITLE
Fix "Get Started" docs

### ISSUE THREAD

**Issue by claudiu-cristea** [drud/ddev#4509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

Here https://ddev.com/get-started/ it states:

> This was a one-time configuration, and configuration files were created for the project. Take a look at the project’s **.ddev/ddev.yaml** file.

### Expected Behavior

I think the file should be **.ddev/config.yaml**

### Actual Behavior

**.ddev/ddev.yaml** is documented.

**Comment by rfay** [comment]
Thanks, fixed. ddev.com is pretty neglected, but we're hoping to do better with it in 2023.
