### ISSUE TITLE
Formatting issue in installation instructions

### ISSUE THREAD

**Issue by mbomb007** [drud/ddev#4518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/

At the bottom in the section called "WSL2 hostname management", there is a problem with the code formatting.

### Expected Behavior

Formatting should be correct.

### Actual Behavior

There's probably a missing ending code tag, or a typo.

### Anything else?

![Screenshot](https://user-images.githubusercontent.com/22807401/210652863-7168d391-d9f1-4b26-b7c6-20faf7432c58.PNG)

**Comment by rfay** [comment]
You can just click the pencil at the top of that page to edit it, would you like to try that? Thanks for pointing this out!
