### ISSUE TITLE
[Craft CMS] `.env` file is not written to correct location when app is in a sub directory

### ISSUE THREAD

**Issue by flynnt** [drud/ddev#4519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

When a project type of Craft CMS is configured and the Craft application files live in a subdirectory - e.g., `/app` - the project initialization script should write the `.env` file to the location in which the app is installed. In my case, this is also usually the Composer root.

### Actual Behavior

DDEV attempts to write out the `.env` file to the project root (that is, `app.AppRoot`) instead of the subdirectory in which Craft is installed.

### Steps To Reproduce

**Configure the project:**
`ddev config --project-type=craftcms --docroot=app/web --create-docroot --composer-root=app --web-environment-add=CRAFT_CMD_ROOT=./app`

**Install Craft**
`ddev composer create -y --no-scripts --no-install craftcms/craft`
`ddev composer install`

Note that the base `.env.example.dev` file is correctly copied to `.env` within `/app`, but when `WriteProjectEnvFile` is called, it does not actually write to the correct file, so you end up with one `.env` file in the `/app` and one in `app.AppRoot`.

### Anything else?

This looks to be the result of the abstraction related to writing `.env` files that happened in #4197. I hesitate to call it a regression or even a bug, really, but the `.env` file operations previously written in `craftcms.go` were working prior to this. It may just be a matter of parameterizing the path, or adding something like:

`envFilePath := filepath.Join(app.AppRoot, app.ComposerRoot, ".env")`

**Comment by rfay** [comment]
Want to try a PR to fix it? Seems like you've explored it well.. And thanks!

**Comment by flynnt** [comment]
Yep. I'll give it a shot. And thank _you_! :)

**Comment by rfay** [comment]
Some guidance in https://ddev.readthedocs.io/en/latest/developers/building-contributing/ and the rest of that section, thanks for giving it a go!

**Comment by rfay** [comment]
This was fixed in #4526, thanks!
