### ISSUE TITLE
Drupal Console Support

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#452]
* [Official website](https://drupalconsole.com/)
* [1 Million downloads](https://drupalconsole.com/articles/drupal-console-hits-1-million-downloads)

Just want to make sure this gets the attention it needs on the D8 side to ensure there are no major gaps or additional pieces of functionality we need.

**Comment by rickmanelius** [comment]
Based on recent discussions, it looks like having it enabled within /usr/local/bin/drupal is sufficient and we can close this out for now unless/until someone has something specific to improve support.

**Comment by rfay** [comment]
This was fixed in https://github.com/drud/docker.nginx-php-fpm-local/pull/49 and then https://github.com/drud/ddev/pull/651. It was released in [v0.13.1](https://github.com/drud/ddev/releases/tag/v0.13.1)
