### ISSUE TITLE
Extensibility for `ddev launch` (Nice to have)

### ISSUE THREAD

**Issue by ayacoo** [drud/ddev#4524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

`ddev launch` is hardcoded for phpmyadmin and mailhog because these services are included by default. To be able to open my own services, such as a solr admin panel, I have to build my own command, see https://ddev.readthedocs.io/en/latest/users/extend/custom-commands/

Due to different commands for opening, I lack consistency. 

solr, for example, runs via a port without a file. For example, I cannot give the complete URL because it refers to the web container. And I would also like to use the shorthand variant ;-)

File: https://github.com/drud/ddev/blob/master/pkg/ddevapp/global_dotddev_assets/commands/host/launch

### Describe your solution

There are several variants.

Variant A: We simply extend the `ddev launch` command with shorthands for the letter s, so that solr is read out. But this is less sustainable and not everyone uses a solr image.

Variant B: We read out the services and their "public URL" dynamically, as in ddev describe. There would be no shorthand but something like `ddev launch -sSERVICENAME` This could possibly throw false positives, e.g. with a Redis service that does not necessarily have a frontend.

Variant C: We offer, in whatever form, an extension for shorthands. So a hook for `ddev launch`.

**Comment by rfay** [comment]
Hi @ayacoo - `launch` is just a shell script installed in ~/.ddev/commands/host. You can change it any way you want (just remove the #ddev-generated on top so ddev doesn't overwrite it). So that means you can
* Copy it and do something new
* Change it the way you like
* Create a PR for an improved version

Do any of those appeal to you? Please see https://ddev.readthedocs.io/en/latest/users/extend/custom-commands/

**Comment by ayacoo** [comment]
Thank you very much for the information. Since I can't find a general way for everyone here, I would stick with using the custom commands to also get updates for ddev launch.

**Comment by rfay** [comment]
You'll note that the [ddev adminer add-on](https://github.com/drud/ddev-adminer) uses an additional command, launcha, for its changes. https://github.com/drud/ddev-adminer/blob/main/commands/host/launcha - you could do the same general approach.
