### ISSUE TITLE
xdebug cannot connect from within the ddev web container

### ISSUE THREAD

**Issue by scubafly** [drud/ddev#4530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

[ddev debug test](https://gist.github.com/scubafly/f83a80d149144f86affffb03e8b8f682#file-gistfile1-txt)

Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003

### Expected Behavior

When visiting the ddev site, xdebug should trigger in phpstorm

### Actual Behavior

I get an error from the ddev container:
```
WARNING: [pool www] child 2948 said into stderr: "NOTICE: PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port)."
2023/01/06 15:49:05 [error] 2303#2303: *792 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port)" while reading response header from upstream, client: 172.20.0.6, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "d9simple.ddev.site", referrer: "https://d9simple.ddev.site/core/install.php?langcode=en&profile=demo_umami&id=3&op=start"
[06-Jan-2023 15:49:10] WARNING: [pool www] child 2948 said into stderr: "NOTICE: PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port)."
```

### Steps To Reproduce

I'm using Docker Desktop 4.15.0 ( for mac )
On an m1 chip mac OSX 13.0.1
ddev version v1.21.4
phpstorm 2022.3.1

- Clone the drud/d9simple repo
- run ddev install ( ddev config, start, xdebug on )
- Start debug listner in php storm on port 9003
- visit the website

### Anything else?

I disabled my firewall on the mac

When i run `sudo lsof -i :9003 -sTCP:LISTEN` i see that php storm is listening:
```
COMMAND  PID USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
phpstorm 600 jack  568u  IPv6  0x...5f      0t0  TCP *:9003 (LISTEN)
```

### in the ddev container

When i run `telnet host.docker.internal 9003` in the ddev container:
`telnet: could not resolve host.docker.internal/9003: Name or service not known`

`cat /etc/hosts`:
```
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.21.0.3	d9simple-web
172.20.0.9	d9simple-web
```

**Comment by rfay** [comment]
Thanks so much for providing the gist with your information; that helps me so much. And thanks for going through the [Troubleshooting instructions](https://ddev.readthedocs.io/en/latest/users/debugging-profiling/step-debugging/) as well!

With Docker Desktop, it's Docker Desktop's job to provide `host.docker.internal`, on many other environments, DDEV does it. 

Could you please test basic functionality with
```
docker run busybox ping host.docker.internal
```

?

I just tested with Docker Desktop on mac M1 and it all works as expected.

**Comment by rfay** [comment]
I can't tell you how much I appreciate your issue report and how much effort you went to before submitting it :)

**Comment by scubafly** [comment]
Thanks for your quick response.
I also tried using vscode, but no luck. Somehow the host.docker.internal is not available.

```docker run busybox ping host.docker.internal```
Results in:
```ping: bad address 'host.docker.internal'```

**Comment by rfay** [comment]
I don't know how Docker Desktop can mess up on that, it's been working fine for many years. Do you have any "interesting" DNS setup, or Docker Desktop configuration? 

I can certainly tell you how to get by the problem, as long as we can figure out what the IP address should be.

What are your settings in docker? I have this, but have never seen this fail with any setting ever.

<img width="512" alt="Settings_-_Docker_Desktop" src="https://user-images.githubusercontent.com/112444/211057242-f1f2d697-f91e-47f7-aff0-4f05ef0d5385.png">

There are a few issues in the queue, but none that seems that promising, https://github.com/docker/for-mac/issues?q=is%3Aissue+in%3Atitle+host.docker.internal+

**Comment by rfay** [comment]
I see the long-running https://github.com/docker/for-mac/issues/2965 but looks like it was resolved long ago. It does seem like you can configure custom DNS in the docker engine config and that would break it.

**Comment by rfay** [comment]
If your network is set to 192.168.5.0 as here, then host.docker.internal is likely 192.168.5.2. You can add the PHP override file .ddev/php/xdebug.ini with these contents:

```
xdebug.client_host=192.168.5.2
```

<img width="840" alt="Settings_-_Docker_Desktop" src="https://user-images.githubusercontent.com/112444/211058788-bb84c4d9-c220-4a12-8457-fa8e29cac8a5.png">

**Comment by rfay** [comment]
Other followup questions: 
* Does DNS work at all ? For example, can you `ddev exec ping google.com` ? (I think it works based on your gist).
* Do you have 192.168.5.* set up as a network in your network infrastructure? It's possible there's a conflict between the IP ranges chosen for Docker and your local network.
* You don't have any proxy or VPN stuff going on right?

**Comment by scubafly** [comment]
I uninstalled docker desktop for mac, reinstalled and now got it working!
Thanks for your help pointing me in the right direction. :)

**Comment by rfay** [comment]
Glad it's working for you!

**Comment by scubafly** [comment]
Found the issue:
I had the following in my docker engine:
```
"dns": [
    "10.8.64.1",
    "1.1.1.1",
    "8.8.8.8"
  ],
```
When I add that back it breaks, when I remove it xdebug ( host.docker.internal ) works again.
![Screenshot 2023-01-06 at 18 16 49](https://user-images.githubusercontent.com/820268/211063502-f2869d48-f743-4478-85a1-4ece22d490e2.png)

**Comment by noahsol30** [comment]
@scubafly you are a life saver!!
