### ISSUE TITLE
[docs] Fix broken link to providers docs on commands page

### ISSUE THREAD

**Issue by Ticolyle** [drud/ddev#4541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

n/a

### Expected Behavior

Able to read the provider documentation on the ddev website.

'Provider' documentation at https://ddev.readthedocs.io/en/latest/users/usage/providers/

I see that the docs still exist in the repo: https://github.com/drud/ddev/tree/master/docs/content/users/providers

Linked in Pull/Push commands: https://ddev.readthedocs.io/en/latest/users/usage/commands/#pull

### Actual Behavior

Providers urls (https://ddev.readthedocs.io/en/latest/users/usage/providers/) displays 404

### Steps To Reproduce

Providers page: https://ddev.readthedocs.io/en/latest/users/usage/providers/

Intended docs page: https://github.com/drud/ddev/tree/master/docs/content/users/providers

**Comment by rfay** [comment]
Seems we actually lost the providers entrypoint in the docs. Maybe just that we lost the index.md?
