### ISSUE TITLE
Configure Google Search Console to get better understanding of Site's performance in Google SERPs

### ISSUE THREAD

**Issue by mayankguptadotcom** [drud/ddev#4542]
Google Search Console (formerly Google Webmaster Tools) is a free platform for anyone with a website to monitor how Google views their site and optimize its organic presence. That includes viewing your referring domains, mobile site performance, rich search results, and highest-traffic queries and pages.

It lets you add sitemaps to it - that helps in faster indexing and even figuring out any potential issues that may come on the website. The most important part is that it helps you see how the site ranks against various keywords.

It's important to note that Google Search console is not Google Analytics which requires you to add a javascript snippet on the website, rather it's a console of how Google sees your website as a search engine - so there is no Javascript to add on the site.

However, it needs to be verified so that Google can start showing the data to the people of the organization that controls the domain.

For that - we'll need to add the following string as a TXT record in the DNS of https://ddev.com

`google-site-verification=H_xc7qehFnDI05FGKYQr1OULXmV4k_55X1H3vlHrugM`

- [x] @rfay to add the TXT DNS record in ddev.com domain.
- [x] Once verified - @mayankguptadotcom to share the admin rights with @rfay and @mattstein

**Comment by rfay** [comment]
These are done. 

We did ddev.readthedocs.io too, but don't know how to verify it until next release, as it redirects to stable.

**Comment by mayankguptadotcom** [comment]
@rfay - Did you verify it in your account? As I can't see it anymore in my account.
If you did verify it from your account, will it be possible to please share the access with me please?

**Comment by rfay** [comment]
It isn't in your account @mayankguptadotcom - I invited you to it though. Look at your email. 

ddev.readthedocs.io is also done.

**Comment by mayankguptadotcom** [comment]
@rfay - I am able to see ddev.readthedocs.io but I don't see ddev.com, and I checked the email - I don't see any notification either.

**Comment by rfay** [comment]
I must have messed up, but it should be in your mailbox now, sorry.

**Comment by mayankguptadotcom** [comment]
Please don't apologize! Thank you so much sir! 
Got the access -> have configured Google search console with Plausible, linked with my Google account.

**Comment by rfay** [comment]
I was impressed to see that we have longstanding data here. This was already set up years ago, so the data has been there, we just took over access to it.
