### ISSUE TITLE
Custom config.*.yaml files - support new variables

### ISSUE THREAD

**Issue by detrax** [drud/ddev#4544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

It should be possible, to introduce new variables within a extended config file config.*.yaml

For example, if I use the following file (extract, not full):
**config.solr.yaml**
```
...
typo3_solr_ext_path: 'htdocs/typo3conf/ext/solr/Resources/Private/Solr/'
typo3_solr_configset: 'ext_solr_11_0_0'
hooks:
 post-start:
   - exec: |
       SOLR_EXT_PATH=(`yq e '.typo3_solr_ext_path' .ddev/config.yaml`)
...
```
The hook does not know about the "typo3_solr_ext_path".

If I use this configuration in the main config.yaml - all works fine.

### Expected Behavior

New variables, introduced in config.*.yaml files should be read and made usable too.

### Actual Behavior

This does not seem to happen - only merge or override of existing variables

**Comment by rfay** [comment]
Hi @detrax - This is a result of how bash works. When you set an environment variable in bash, it only exists until the end of the bash session. In your case, that's the end of the SOLR_EXT_PATH= statement, it does not live on past your exec. 

If you want to set a variable dynamically, you'll probably have to do it another way. For example, you can write the generated value to a file and load it and inject it into the environment later.

**Comment by detrax** [comment]
@rfay - yes, I agree. The BASH variable will only be valid during that BASH session. But this is not what I meant :-) Maybe the example with the hook was a bit misleading.

I will try to explain two things, which seem be related. The "problem" seems to be in the merging of "default" config values with the ones from config.yaml and config.*.yaml. As new config values vanish during this process.

We have some additional values set in config.yaml. For example these two:
**config.yaml**
```
typo3_solr_ext_path: 'private/typo3conf/ext/solr/Resources/Private/Solr/'
typo3_solr_configset: 'ext_solr_10_0_0'
```

This work fine and those **are** available inside the DDEV Environment - e.g. in a custom web-command

`ddev createsolr`

**.ddev/commands/web/createsolr**
```
#!/bin/bash

## Description: Create the solr cores for the project
## Usage: createsolr
## Example: ddev createsolr

SOLR_EXT_PATH=(`yq e '.typo3_solr_ext_path' .ddev/config.yaml`)
...
```
I can access and use them. Everything works fine this way.

BUT:
If I declare those values inside of an config.solr.yaml - they are not available. The merging of the configurations files seems to be limited to predefined values only. So new configuration values are ignored, if "merged in" via config.*.yaml.

_ANOTHER ISSUE_

If we define both variables in config.yaml (as above) it works.

BUT:
If the configuration is changed via ddev, they are removed. For example, if 

`ddev config --xdebug-enabled`

is called, only the "default" values remain in the file. All custom set variables (the solr configuration in this case) is gone.

**Comment by rfay** [comment]
AFAICT, this isn't about merging I don't think. It's about dynamic environment variables in docker-compose. I don't think you'll find that they're supported, https://docs.docker.com/compose/compose-file/

You said
> We have some additional values set in config.yaml. For example these two:
typo3_solr_ext_path: 'private/typo3conf/ext/solr/Resources/Private/Solr/'
typo3_solr_configset: 'ext_solr_10_0_0'

But those aren't values, those are (illegal and unsupported) keys in the docker-compose, right? 

I'm afraid I don't understand why you think you can do what you're doing here. But if you give a full example, perhaps with a gist, maybe I can help point the way. But do take a look at the compose spec, and please do try for simple techniques to demonstrate the problem.

**Comment by detrax** [comment]
The values I am talking about are in the ".ddev/config.yaml" file (see file). Is this a docker-compose file? 

Fact is, the variables are available to custom ddev commands, if they are written in the projects ".ddev/config.yaml". So I guessing, that they are valid there. But I may be wrong.

The whole file is here : [config.yaml](https://gist.github.com/detrax/86cf7433b7ebeb2d5ab14706cf018e2d)

**Comment by rfay** [comment]
I'm baffled what you're up to.

None of these are part of the DDEV config.yaml schema, nor is there a way I know of to use them.

```
typo3_solr_cores:
  - { name: core_customer_de, schema: "german/schema.xml" }
  - { name: core_customer_en, schema: "english/schema.xml" }
typo3_solr_ext_path: 'private/typo3conf/ext/solr/Resources/Private/Solr/'
typo3_solr_configset: 'ext_solr_10_0_0'
```

Perhaps you could make a simple demonstration repo that explains what you're trying to do in the simplest way. Neither yaml nor docker-compose is going to allow initialization of variables with dynamic constructs I don't think, but I'm quite sure there's a way to accomplish whatever it is you're after.

**Comment by detrax** [comment]
Ah.. I see. _I checked again_ and made a mistake... 

You are right! 

DDEV is not involved in this case - our DDEV custom command reads these values **directly** out of DDEVs config.yaml. In hindsight it might not be a good idea to mix configurations. Although is is nice to only have ONE file to configure the complete development environment.

So... the solution could be creating an own configuration file for the extra service - maybe config.solr.yaml. 

And some more explanation for this case:
Yes, solr runs in its own docker-composer container, which is started together with the other containers by "ddev start". The initial configuration is done (once) with the ddev custom command I told you about.

**Comment by rfay** [comment]
Congratulations! I think you're on the right track. I think you probably want to put config into a `docker-compose.*.yaml` or use environment variables. Doing it in config.solr.yaml also would mean violating the schema.

**Comment by detrax** [comment]
That sounds like a good idea, as it belongs to the  docker-compose domain. Thank you!
