### ISSUE TITLE
Windows with numeric username still not working, fix with overriding username

### ISSUE THREAD

**Issue by IvanFloripa** [drud/ddev#4547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here
<details><summary>ddev debug test</summary>

```
ddev debug test
Running C:\Program Files\Git\bin\bash.exe [-c /c/Users/2242723/AppData/Local/Temp/3/test_ddev.sh]
======= Existing project config =========
These config files were loaded for project teste-project: [C:\Users\2242723\test\teste-project\.ddev\config.yaml]
name: teste-project
type: craftcms
docroot: web
php_version: 8.0
webserver_type: nginx-fpm
webimage: drud/ddev-webserver:v1.21.4
router_http_port: 80
router_https_port: 443
additional_hostnames: []
additional_fqdns: []
database: {mariadb 10.4}
mailhog_port: 8025
mailhog_https_port: 8026
phpmyadmin_port: 8036
phpmyadmin_https_port: 8037
project_tld: ddev.site
use_dns_when_possible: true
composer_version: 2
nodejs_version: 16
default_container_timeout: 120
======= Creating dummy project named  tryddevproject-18966 in ../tryddevproject-18966 =========
OS Information: MINGW64_NT-10.0-19042 LTBR099511 3.3.5-341.x86_64 2022-07-08 09:41 UTC x86_64 Msys
User information: uid=4096(CTS+2242723) gid=4096 groups=4096
DDEV version:  ITEM             VALUE
 DDEV version     v1.21.4
 architecture     amd64
 db               drud/ddev-dbserver-mariadb-10.4:v1.21.4
 dba              phpmyadmin:5
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.4
 docker           20.10.21
 docker type      Docker Desktop For Windows
 docker-compose   v2.14.0
 docker-platform  docker-desktop
 mutagen          0.16.0
 os               windows
 router           drud/ddev-router:v1.21.4
 web              drud/ddev-webserver:v1.21.4
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
mutagen-enabled=false
nfs-mount-enabled=false
router-bind-all-interfaces=false
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
auto-restart-containers=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=
use-docker-compose-from-path=false
project-tld=
xdebug-ide-location=
no-bind-mounts=false
use-traefik=false

======= DOCKER info =========
docker location: -rwxr-xr-x 1 CTS+2242723 4096 1359 Jan  9 14:58 '/c/Program Files/Docker/Docker/resources/bin/docker'
Docker Desktop Version: Docker Desktop for Windows 4.14.0.91374

docker version:
Client:
 Cloud integration: v1.0.29
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:08:16 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.14.0 (91374)
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:19 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
DOCKER_DEFAULT_PLATFORM=notset
======= Mutagen Info =========
======= Docker Info =========
Docker platform: docker-desktop
Using docker context: default (npipe:////./pipe/docker_engine)
docker-compose: v2.14.0
Using DOCKER_HOST=npipe:////./pipe/docker_engine
Docker version: 20.10.21
Able to run simple container that mounts a volume.
Able to use internet inside container.
Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                 251.0G      5.0G    233.2G   2% /

The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again.
Existing docker containers:
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
Creating a new ddev project config in the current directory (C:\Users\2242723\test\tryddevproject-18966)
Once completed, your configuration will be written to C:\Users\2242723\test\tryddevproject-18966\.ddev\config.yaml

Configuring unrecognized codebase as project type 'php' at C:\Users\2242723\test\tryddevproject-18966\web
Configuration complete. You may now run 'ddev start'.
Network ddev_default created
Starting tryddevproject-18966...
Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
failed to solve: executor failed running [/bin/bash -c (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username" || useradd  -l -m -s "/bin/bash" --gid "$gid" --comment '' "$username" || useradd -l -m -s "/bin/bash" --comment '' $username )]: exit code: 3
Failed to start tryddevproject-18966: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-tryddevproject-18966 docker-compose -f C:\Users\2242723\test\tryddevproject-18966\.ddev\.ddev-docker-compose-full.yaml up --build -d', action='[up --build -d]', err='exit status 17', stdout='#1 [drud/ddev-dbserver-mariadb-10.4:v1.21.4-tryddevproject-18966-built internal] load build definition from Dockerfile
#1 transferring dockerfile: 30B 0.0s
#1 transferring dockerfile: 885B 0.0s done
#1 DONE 0.1s

#2 [drud/ddev-webserver:v1.21.4-tryddevproject-18966-built internal] load build definition from Dockerfile
#2 transferring dockerfile: 1.32kB 0.1s done
#2 DONE 0.1s

#3 [drud/ddev-dbserver-mariadb-10.4:v1.21.4-tryddevproject-18966-built internal] load .dockerignore
#3 transferring context: 2B 0.0s done
#3 DONE 0.1s

#4 [drud/ddev-webserver:v1.21.4-tryddevproject-18966-built internal] load .dockerignore
#4 transferring context: 2B 0.0s done
#4 DONE 0.1s

#5 [drud/ddev-webserver:v1.21.4-tryddevproject-18966-built internal] load metadata for docker.io/drud/ddev-webserver:v1.21.4
#5 DONE 0.0s

#6 [drud/ddev-dbserver-mariadb-10.4:v1.21.4-tryddevproject-18966-built internal] load metadata for docker.io/drud/ddev-dbserver-mariadb-10.4:v1.21.4
#6 DONE 0.0s

#7 [drud/ddev-dbserver-mariadb-10.4:v1.21.4-tryddevproject-18966-built 1/3] FROM docker.io/drud/ddev-dbserver-mariadb-10.4:v1.21.4
#7 CACHED

#8 [drud/ddev-webserver:v1.21.4-tryddevproject-18966-built 1/6] FROM docker.io/drud/ddev-webserver:v1.21.4
#8 DONE 0.0s

#9 [drud/ddev-webserver:v1.21.4-tryddevproject-18966-built 2/6] RUN (groupadd --gid 1000 "2242723" || groupadd "2242723" || true) && (useradd  -l -m -s "/bin/bash" --gid "2242723" --comment '' --uid 1000 "2242723" || useradd  -l -m -s "/bin/bash" --gid "2242723" --comment '' "2242723" || useradd  -l -m -s "/bin/bash" --gid "1000" --comment '' "2242723" || useradd -l -m -s "/bin/bash" --comment '' 2242723 )
#9 CACHED

#10 [drud/ddev-dbserver-mariadb-10.4:v1.21.4-tryddevproject-18966-built 2/3] RUN (groupadd --gid 1000 "2242723" || groupadd "2242723" || true) && (useradd  -l -m -s "/bin/bash" --gid "2242723" --comment '' --uid 1000 "2242723" || useradd  -l -m -s "/bin/bash" --gid "2242723" --comment '' "2242723" || useradd  -l -m -s "/bin/bash" --gid "1000" --comment '' "2242723" || useradd -l -m -s "/bin/bash" --comment '' 2242723 )
#10 0.624 groupadd: '2242723' is not a valid group name
#10 0.626 groupadd: '2242723' is not a valid group name
#10 0.629 useradd: group '2242723' does not exist
#10 0.631 useradd: group '2242723' does not exist
#10 0.634 useradd: group '1000' does not exist
#10 0.636 useradd: invalid user name '2242723'
#10 ERROR: executor failed running [/bin/bash -c (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username" || useradd  -l -m -s "/bin/bash" --gid "$gid" --comment '' "$username" || useradd -l -m -s "/bin/bash" --comment '' $username )]: exit code: 3

#11 [drud/ddev-webserver:v1.21.4-tryddevproject-18966-built 3/6] RUN export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2 || composer self-update --2 || true
#11 CANCELED
------
 > [drud/ddev-dbserver-mariadb-10.4:v1.21.4-tryddevproject-18966-built 2/3] RUN (groupadd --gid 1000 "2242723" || groupadd "2242723" || true) && (useradd  -l -m -s "/bin/bash" --gid "2242723" --comment '' --uid 1000 "2242723" || useradd  -l -m -s "/bin/bash" --gid "2242723" --comment '' "2242723" || useradd  -l -m -s "/bin/bash" --gid "1000" --comment '' "2242723" || useradd -l -m -s "/bin/bash" --comment '' 2242723 ):
#10 0.624 groupadd: '2242723' is not a valid group name
#10 0.626 groupadd: '2242723' is not a valid group name
#10 0.629 useradd: group '2242723' does not exist
#10 0.631 useradd: group '2242723' does not exist
#10 0.634 useradd: group '1000' does not exist
#10 0.636 useradd: invalid user name '2242723'
------
', stderr='failed to solve: executor failed running [/bin/bash -c (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username" || useradd  -l -m -s "/bin/bash" --gid "$gid" --comment '' "$username" || useradd -l -m -s "/bin/bash" --comment '' $username )]: exit code: 3'
┌──────────────────────┬─────────┬──────────────────────────────────┬─────┬───────────┐
│ NAME                 │ STATUS  │ LOCATION                         │ URL │ TYPE      │
├──────────────────────┼─────────┼──────────────────────────────────┼─────┼───────────┤
│ projeto-docker       │ stopped │ ~/test/projeto-docker       │     │ craftcms  │
├──────────────────────┼─────────┼──────────────────────────────────┼─────┼───────────┤
│ teste-project        │ stopped │ ~/test/teste-project        │     │ craftcms  │
├──────────────────────┼─────────┼──────────────────────────────────┼─────┼───────────┤
│ tryddevproject-18966 │ stopped │ ~/test/tryddevproject-18966 │     │ php       │
├──────────────────────┼─────────┼──────────────────────────────────┼─────┼───────────┤
│ Router               │ stopped │ ~/.ddev                          │     │ original: │
│                      │         │                                  │     │  v1.21.4  │
└──────────────────────┴─────────┴──────────────────────────────────┴─────┴───────────┘

```
</details>

### Expected Behavior

I expected running ddev containers without admin privileges

### Actual Behavior

Ddev running ok with admin privileges

### Steps To Reproduce

execute ddev start in windows 10

**Comment by IvanFloripa** [comment]
Here below show log error when i running `ddev start`

`
 ddev start
Starting teste-project...
failed to solve: executor failed running [/bin/bash -c (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username" || useradd  -l -m -s "/bin/bash" --gid "$gid" --comment '' "$username" || useradd -l -m -s "/bin/bash" --comment '' $username )]: exit code: 3
Failed to start teste-project: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-teste-project docker-compose -f C:\Users\2242723\test\teste-project\.ddev\.ddev-docker-compose-full.yaml up --build -d', action='[up --build -d]', err='exit status 17', stdout='#1 [drud/ddev-webserver:v1.21.4-teste-project-built internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.31kB 0.1s done
#1 DONE 0.1s

#2 [drud/ddev-webserver:v1.21.4-teste-project-built internal] load .dockerignore
#2 transferring context: 2B 0.0s done
#2 DONE 0.1s

#3 [drud/ddev-dbserver-mariadb-10.4:v1.21.4-teste-project-built internal] load build definition from Dockerfile
#3 transferring dockerfile: 878B 0.0s done
#3 DONE 0.1s

#4 [drud/ddev-dbserver-mariadb-10.4:v1.21.4-teste-project-built internal] load .dockerignore
#4 transferring context: 2B 0.0s done
#4 DONE 0.1s

#5 [drud/ddev-dbserver-mariadb-10.4:v1.21.4-teste-project-built internal] load metadata for docker.io/drud/ddev-dbserver-mariadb-10.4:v1.21.4
#5 DONE 0.0s

#6 [drud/ddev-dbserver-mariadb-10.4:v1.21.4-teste-project-built 1/3] FROM docker.io/drud/ddev-dbserver-mariadb-10.4:v1.21.4
#6 CACHED

#7 [drud/ddev-webserver:v1.21.4-teste-project-built internal] load metadata for docker.io/drud/ddev-webserver:v1.21.4
#7 DONE 0.0s

#8 [drud/ddev-webserver:v1.21.4-teste-project-built 1/6] FROM docker.io/drud/ddev-webserver:v1.21.4
#8 DONE 0.0s

#9 [drud/ddev-webserver:v1.21.4-teste-project-built 2/6] RUN (groupadd --gid 1000 "2242723" || groupadd "2242723" || true) && (useradd  -l -m -s "/bin/bash" --gid "2242723" --comment '' --uid 1000 "2242723" || useradd  -l -m -s "/bin/bash" --gid "2242723" --comment '' "2242723" || useradd  -l -m -s "/bin/bash" --gid "1000" --comment '' "2242723" || useradd -l -m -s "/bin/bash" --comment '' 2242723 )
#9 CACHED

#10 [drud/ddev-dbserver-mariadb-10.4:v1.21.4-teste-project-built 2/3] RUN (groupadd --gid 1000 "2242723" || groupadd "2242723" || true) && (useradd  -l -m -s "/bin/bash" --gid "2242723" --comment '' --uid 1000 "2242723" || useradd  -l -m -s "/bin/bash" --gid "2242723" --comment '' "2242723" || useradd  -l -m -s "/bin/bash" --gid "1000" --comment '' "2242723" || useradd -l -m -s "/bin/bash" --comment '' 2242723 )
#10 0.423 groupadd: '2242723' is not a valid group name
#10 0.424 groupadd: '2242723' is not a valid group name
#10 0.427 useradd: group '2242723' does not exist
#10 0.429 useradd: group '2242723' does not exist
#10 0.431 useradd: group '1000' does not exist
#10 0.433 useradd: invalid user name '2242723'
#10 ERROR: executor failed running [/bin/bash -c (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username" || useradd  -l -m -s "/bin/bash" --gid "$gid" --comment '' "$username" || useradd -l -m -s "/bin/bash" --comment '' $username )]: exit code: 3

#11 [drud/ddev-webserver:v1.21.4-teste-project-built 3/6] RUN export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2 || composer self-update --2 || true
#11 CANCELED
------
 > [drud/ddev-dbserver-mariadb-10.4:v1.21.4-teste-project-built 2/3] RUN (groupadd --gid 1000 "2242723" || groupadd "2242723" || true) && (useradd  -l -m -s "/bin/bash" --gid "2242723" --comment '' --uid 1000 "2242723" || useradd  -l -m -s "/bin/bash" --gid "2242723" --comment '' "2242723" || useradd  -l -m -s "/bin/bash" --gid "1000" --comment '' "2242723" || useradd -l -m -s "/bin/bash" --comment '' 2242723 ):
#10 0.423 groupadd: '2242723' is not a valid group name
#10 0.424 groupadd: '2242723' is not a valid group name
#10 0.427 useradd: group '2242723' does not exist
#10 0.429 useradd: group '2242723' does not exist
#10 0.431 useradd: group '1000' does not exist
#10 0.433 useradd: invalid user name '2242723'
------
', stderr='failed to solve: executor failed running [/bin/bash -c (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username" || useradd  -l -m -s "/bin/bash" --gid "$gid" --comment '' "$username" || useradd -l -m -s "/bin/bash" --comment '' $username )]: exit code: 3'


`

**Comment by rfay** [comment]
I imagine the problem is that you have a numeric username, `2242723`.

I strongly recommend that you use WSl2 rather than traditional Windows, especially since you seem to be stuck with a numeric uid.  You'll be so much happier.

I thought this was already sorted out, but you can do something like the workaround in https://github.com/drud/ddev/issues/3187#issuecomment-902812223

**Comment by IvanFloripa** [comment]
Hi @rfay , thanks i add your code on my project, and that's amazing!
Thanks for your support!

**Comment by rfay** [comment]
Glad to hear it's working for you. Do give WSL2 a try, it's way faster and more likely to work for you all the time.
