### ISSUE TITLE
Docker Desktop 4.16.0 DDEV fails with "sudo: effective uid is not 0"

### ISSUE THREAD

**Issue by liayn** [drud/ddev#4551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/liayn/4ab0416695522f7428af58498833956b

### Expected Behavior

ddev should start

### Actual Behavior

fails with 
> + sudo mkdir -p /mnt/ddev-global-cache/terminus/cache
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root 

### Docker Desktop Issues
* https://github.com/docker/for-mac/issues/6675
* https://github.com/docker/for-win/issues/13161

### How to roll back to earlier version

You can get earlier versions from https://docs.docker.com/desktop/release-notes/

### Alternate Docker Providers

* On macOS you may be interested in using Colima instead of Docker Desktop. See https://ddev.readthedocs.io/en/latest/users/install/docker-installation/#macos
* On WSL2 you may be interested in using docker-ce instead of Docker Desktop, see https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#windows-wsl2

**Comment by rfay** [comment]
Could you please do the requested `ddev debug test` and put the results in a gist on gist.github.com and give the link? Please edit your issue. You haven't even said what OS this happens to you on.

**Comment by liayn** [comment]
> You haven't even said what OS this happens to you on.
It's in the title ;-) Windows 10

> Could you please do the requested ddev debug test and put the results in a gist on gist.github.com and give the link? Please edit
I only posted the only failure and last line of it. Will extend to everything

**Comment by rfay** [comment]
I can reproduce this on WSL2.  Just this reproduces it:
```
$ docker run -it --rm -u 33:33 drud/ddev-webserver:v1.21.4 sudo ls
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
```

**Comment by adriancotter** [comment]
I am having the same issue on MacOS 12.6 Monterey.

**Comment by rfay** [comment]
Thanks @adriancotter - may be time for colima for you :) And docker-ce for @liayn :) Of course Colima has had some stumbles in the last couple of months too.

**Comment by rfay** [comment]
It's easy enough to download the older version of Docker Desktop and move on though. Get older versions from https://docs.docker.com/desktop/release-notes/

**Comment by adriancotter** [comment]
Thanks @rfay it is good to be able to easily walk it back. Also, a relief to know that it is not just me! I'll have to have a look a Colima as well at some point.

**Comment by ashabed** [comment]
FYI - Docker released a new version which they say addresses the `sudo` bug.

**Comment by rfay** [comment]
Docker Desktop 4.16.1 solves this problem. Thanks!

**Comment by a-r-m-i-n** [comment]
I've updated to ddev version v1.21.4 using
```
curl -fsSL https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh | bash -s v1.21.4
```
Also tried with `sudo`.

I've destroyed the project, removed all files, uploaded .ddev/ files from git and still 
web container failes with this in error log:
> sudo mkdir -p /mnt/ddev-global-cache/terminus/cache
> sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

**Comment by a-r-m-i-n** [comment]
Updating Docker itself to latest version fixed the issue 👍
