### ISSUE TITLE
File permissions changed on "drush cex" (macOS, Docker Desktop)

### ISSUE THREAD

**Issue by unipro-LeighMason** [drud/ddev#4560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/unipro-LeighMason/ea64991635d058d6964e3e1eb332ba99

### Expected Behavior

On ddev version v1.21.3 when I did a "ddev drush cex" command the generated files would have the permissions 644 (git would only show files whose contents had actually changed)

I have updated to v1.21.4 and now when I run the command every file is showing as changed in git because the file permission for every generated file is now 755. It should be 644 like it was before I did the update

### Actual Behavior

Files generated from ddev drush cex should have the 644 permission.

I can confirm there has been no update to drush versions and no other changes other than updating ddev since this was working 

The same happens if you "ddev ssh" and then "drush cex". So it appears whatever user/group these commands are running as has changed and its writing the files with different read/write permissions?

### Steps To Reproduce

I am using the standard CMS quickstart config for Drupal 9 

_No response_

**Comment by rfay** [comment]
You skipped the requested diagnostic, `ddev debug test`, so I don't even know what OS you're on, or what docker provider you're using, or whether you're using mutagen. Could you please do it and edit the issue? Put the results in a gist or other pastebin.

**Comment by rfay** [comment]
You do *not* install mutagen to use it with ddev; you just `ddev config global --mutagen-enabled` or `ddev config --mutagen-enabled`. But it looks like you already know this.

(Most folks are on macOS always use mutagen)

**Comment by unipro-LeighMason** [comment]
> You do _not_ install mutagen to use it with ddev; you just `ddev config global --mutagen-enabled` or `ddev config --mutagen-enabled`. But it looks like you already know this.
> 
> (Most folks are on macOS always use mutagen)

Yeah that's right when I used it I followed the instructions from the ddev docs. I also did the same to disable it. I did that a long time ago so would guess it's not related to my issue

**Comment by rfay** [comment]
Are you sure that your change is not a result of a new drush version? I think it's possible that's the problem; 

If you do a `ddev exec touch /var/www/html/junk.txt` what are the permissions? I see 0644. 

I just tried to recreate this, and couldn't; drush definitlely says it's removing all the files and recreating them, so they'd get default perms, and on my system I get all 0644. 

What are your settings on Docker Desktop? Are you perhaps using the new VirtioFS? What is your file sharing setting in Docker Desktop? And would you consider updating to current Docker Desktop 4.16.1 to see if that affects this? I wasn't able to recreate your situation.

If you can come up with a simplest scenario for this, step by step demonstrating the creation of 0755 files it would help a lot.

**Comment by rfay** [comment]
I wasn't able to recreate your results using Colima with sshfs filesharing or Docker Desktop 4.16.1 using either virtiofs or gRPC Fuse filesharing. So maybe updating your Docker Desktop would make a difference. Are you sure you can recreate this by going back to DDEV v1.21.3? https://ddev.readthedocs.io/en/latest/users/usage/faq/#how-can-i-install-a-specific-version-of-ddev

**Comment by unipro-LeighMason** [comment]
Thanks for the reply. I think you're right about Docker Desktop. At some point its auto dated to 4.15.0.

There's now a 4.16.0 and in the release notes  https://docs.docker.com/desktop/release-notes/#4160 it has:

- Fixed files created on VirtioFS having the executable bit set. Fixes [docker/for-mac#6614](https://github.com/docker/for-mac/issues/6614).

It looks like that was the issue. I've updated to 4.16.1 and that's resolved it. Apologies for assuming it was the ddev update that was just bad timing and led me down the wrong path

**Comment by rfay** [comment]
Thanks!
