### ISSUE TITLE
homebrew

### ISSUE THREAD

**Issue by wp-coin** [drud/ddev#4561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

why don't you have ddev on homebrew?

### Describe your solution

upload ddev to homebrew!!

### Describe alternatives

there is no alternative

### Additional context

no

**Comment by rfay** [comment]
DDEV has been in homebrew for years, both macOS and Linux. Please see the docs, https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#macos

**Comment by chrisfromredfin** [comment]
I'm curious... how did you not find it in homebrew? Were you trying something like `brew install ddev/ddev`?

I ask because I'm wondering if the odd "drud" namespace you need prevented you from finding what you wanted?

**Comment by tyler36** [comment]
In support of OP, DDEV does NOT appear when searching on [brew homepage](https://brew.sh/): 

![brew search](https://user-images.githubusercontent.com/7234392/213327337-c96df4ef-0340-489e-a0b3-c3d89fdd7361.png)

... but something appears when searching WSL2 Ubuntu CLI; the namespace in the name might be confusing for new users.

```shell
$ brew search ddev 
==> Formulae
drud/ddev/ddev  ✔                 devd
```

**Comment by rfay** [comment]
There are two ways to get something into homebrew. The first is as an official PR into the homebrew-core repo. With that one you don't have control of when it goes in. The second is called a Homebrew "tap". DDEV is done that way, so the tap is drud/ddev (`brew tap drud/ddev`), or the direct install of both tap and ddev is `brew install drud/ddev/ddev`). With a tap changes take effect immediately, with homebrew-core they can sometimes languish a day or two.

I've thought it would be reasonable to move into homebrew-core for some time, but the impact on everybody seems like it would be annoying. Alternatively, both could be maintained I imagine. But it seems that would be confusing too.

**Comment by rfay** [comment]
DDEV works with homebrew on linux and has for years. `brew install drud/ddev/ddev`. It's not the preferred approach any more since we have install via apt package manager, but it was the preferred approach for years, and still works great.
