### ISSUE TITLE
How to install ddev using apt on debian/ubuntu

### ISSUE THREAD

**Issue by wp-coin** [drud/ddev#4568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

```
sudo apt install ddev
[sudo] password for mason: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package ddev


```

### Expected Behavior

I expect it to work

### Actual Behavior

error

### Steps To Reproduce

sudo apt install ddev

**Comment by rfay** [comment]
Hi @wp-coin - Please follow the instructions in the docs, https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#linux

```
curl -fsSL https://apt.fury.io/drud/gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/ddev.gpg > /dev/null
echo "deb [signed-by=/etc/apt/trusted.gpg.d/ddev.gpg] https://apt.fury.io/drud/ * *" | sudo tee /etc/apt/sources.list.d/ddev.list
sudo apt update && sudo apt install -y ddev
```

**Comment by rfay** [comment]
But just yesterday you wanted to install with homebrew and I explained how :)

**Comment by rfay** [comment]
@wp-coin DDEV runs on Linux, Windows, Windows WSL2, and macOS. On each of those it installs with the expected package manager. On Debian/Ubuntu it installs with apt, which is the normal and longest-standing technique. It also installs with homebrew and with an install script. On macOS it installs with homebrew, and on Windows it has an installation package and installs with chocolatey. 

I hope you'll get a chance to look at the install docs. https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/

**Comment by lolautruche** [comment]
There is no need to be rude @wp-coin .
Ddev is open source software and installable on all major Linux distribution. 
I understand you may be frustrated, but please remain respectful to the people maintaining free software.
