### ISSUE TITLE
[defect] failed to RunSimpleContainer to inspect database version/type: failed to StartContainer: API error (500): failed to create endpoint elegant_benz on 

### ISSUE THREAD

**Issue by ElijahLynn** [drud/ddev#4570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

Rubber ducking this here, it is incomplete right now. 

https://gist.github.com/ElijahLynn/14a1470d3a344b16489b6b9678e28956

### Expected Behavior

`ddev start`

works

### Actual Behavior

`Failed to describe project(s): could not find a project in /home/elijah/Projects/va.gov/tryddevproject-15360. Have you run 'ddev config'? Please specify a project name or change directories: no .ddev/config.yaml file was found in this directory or any parent`

**Comment by rfay** [comment]
Thanks for doing the `ddev debug test`! 

Your docker isn't working:
> docker: Error response from daemon: failed to create endpoint vigorous_bouman on network bridge: failed to add the host (veth9766b1b) <=> sandbox (veth33c66e2) pair interfaces: operation not supported.
[33mFailed removing custom certs/traefik configuration: failed to StartContainer: API error (500): failed to create endpoint eloquent_keldysh on network bridge: failed to add the host (veth7998d21) <=> sandbox (veth18272a0) pair interfaces: operation not supported[0m

**Comment by rfay** [comment]
It looks like you're on Arch Linux with a nonfunctional docker setup. Please see if you can get to where `docker ps` works to begin with.

**Comment by ElijahLynn** [comment]
> It looks like you're on Arch Linux with a nonfunctional docker setup. Please see if you can get to where `docker ps` works to begin with.

Thanks, it has been a bit since I ran `ddev` or docker for that matter. 

```
❯ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

```
❯ docker run --name test -it alpine
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
8921db27df28: Pull complete 
Digest: sha256:f271e74b17ced29b915d351685fd4644785c6d1559dd1f2d4189a5e851ef753a
Status: Downloaded newer image for alpine:latest
docker: Error response from daemon: failed to create endpoint test on network bridge: failed to add the host (veth5cf5015) <=> sandbox (vethb206679) pair inter
faces: operation not supported.
ERRO[0003] error waiting for container: context canceled 
```

I'll fuddle with this and post my update here when I get it working, we can close this for now.

**Comment by rfay** [comment]
Glad you got it! Arch is like that :)
