### ISSUE TITLE
503: No ddev back-end site available after just changing php_version & webserver_type in config.yaml

### ISSUE THREAD

**Issue by a8w4** [drud/ddev#4577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/a8w4/5390e468d7fc2942318f543da5f70863

### Expected Behavior

I only changed two normally harmless parameters and did a ddev restart:
php_version from 8.1 to 8.0 and webserver_type from nginx-fpm to apache-fpm

My expectation was, that ddev would still work and display the functional website just as it did before those small changes.

Btw: the reason I changed the php_version was, that a php -v after ddev ssh reported 8.2 although to my surprise 8.1 was configured in the config.yaml of the project.

### Actual Behavior

Only this error message is displayed: 

503: No ddev back-end site available.
This is the ddev-router container: There is no back-end webserver at the URL you specified. You may want to use "ddev start" to start the site.

### Steps To Reproduce

I don't know how to reproduce it - but it happend before and is a big showstopper to my development work...
For the first time though I could pinpoint the problem to the actual changes I made and prove that it cannot be caused by changes of the project itself - a drupal 9 website, because it worked before and the project itself was unchanged .

It might be important, that it is a drupal9-Project - my Drupal7-projects don't seem to be affected.

### Anything else?

I have tried ddev delete --omit-snapshot,
deleted the .ddev directory of the project,
did ddev config & ddev start
-> no change

This is very strange, there seem to be factors outside of the individual project configuration...

**Comment by rfay** [comment]
Well, a new project works fine. (You're almost out of disk space but that's not causing this).

Please do a `ddev poweroff && docker rm -f $(docker ps -aq)` to remove all stale containers, see if that helps.

Your approach of removing the .ddev folder was a good one.

**Comment by rfay** [comment]
I'll be happy to do a call and look at this with you if you can't sort it out. As you see, it must be something specific to your machine.

Please do make sure that you've read through the [Troubleshooting docs](https://ddev.readthedocs.io/en/latest/users/usage/troubleshooting/)

Note that the thing to do is to remove customizations like `.ddev/docker-compose.*.yaml` and in `config.yaml` but it seems like your approach would already have done that.

`ddev logs` may show you what happened to the project, or `docker logs ddev-<projectname>-web` might help, or `docker inspect --format "{{json .State.Health }}" ddev-<projectname>-web | jq` might show if the healthcheck is timing out.

**Comment by rfay** [comment]
No response, so closing. Happy to continue the conversation here or elsewhere.

**Comment by a8w4** [comment]
Thank you @rfay for offering support for my specific machine - sorry, I didn't react immediately - I was saturated with lots of other issues.

Meanwhile, one morning I had a brain-wave, that the issue might be connected to the www subdomain. Unknowingly, although I could have known - in the .htaccess file of this project there is defined a redirect from the main domain to www\.main-domain. Now, because name in config.yaml is not www\.project-name but only project-name there was indeed no back-end available!

Adding:
additional_hostnames:
 \- "www.project-name"
solved the problem.

Although this seems simple and obvious enough in hindsight - the root cause, as described above, was obstructed from view by three contributing factors.

1. by switching from nginx-fpm to apache-fpm the .htaccess-file was read and put to effect for the first time - the redirect was issued to the browser and lead to the error message in the first place.
2. The browser I use almost exclusively for web development - Chrome - hides the www-subdomain in the location bar, so that it's not obvious, what might be the problem.
3. Also browsers save and remember redirects with code 301, so that when switching back to the state before the changes, which in this regard is switching back to nginx-fpm, the error persisted, because the redirect to www\.project-name\.ddev\.site was still executed!

So to avoid this problem in the future for everyone who might fall in this trap as well, I propose a change on how ddev handles the www-subdomain:

Proposal:

Define www\.project-name as default, so that redirects to that will never be a problem again.

This could be done by a default directive in config.yaml like:
www_subdomain: true

Or more general:
add_subdomains:
   \- www

What do you think?

**Comment by rfay** [comment]
Since DDEV has been around for many years and people haven't stumbled on this, and since the problem was apparently a result of your .htaccess (and using apache_fpm), it doesn't seem like this needs to be addressed. But I'll certainly listen if people hit it in the future. 

Glad you got it sorted out.

**Comment by subbee** [comment]
I had a similar issue, the problem was with my .htaccess file, where there was a www redirection that was hidden in the browser's address bar, so I didn't notice it immediately.
