### ISSUE TITLE
Simplify/remove plugin interface (remove interface, use LocalApp)

### ISSUE THREAD

**Issue by rfay** [drud/ddev#458]
## What happened (or feature request):

We've had a longstanding complexity in ddev that is related to past unmet aspirations in the drud tool. In pkg/plugins we have a fancy plugin/interface pattern used in [types.go](https://github.com/drud/ddev/blob/master/pkg/plugins/platform/types.go) that only makes the code more complex, and doesn't add value. 

Recommendation: Lose the App interface and just use LocalApp in its place, lose GetPluginApp(). This is a very straightforward change, will take just a few minutes or hours, plus verification. I think all tests will continue without any issues. We can do this now and it will be something that will make maintenance, updates, and training on ddev code easier for all our future.

**Comment by rfay** [comment]
@rickmanelius IMO this is less than a day's work and would make our entire codebase more accessible to new developers for all time going forward. 

This is only about removing an original structure which envisioned local development as being one of many similar things (like hosting) in the same binary. We left that behind but kept the confusing interface structure. 

I'd propose that we do this before refactoring apptype for multiple CMS if @beeradb and @tannerjfco were good with it.

**Comment by rickmanelius** [comment]
@rfay I'm ok with this if it both maintains existing functionality and makes the codebase easier to maintain/develop on going forward. I would like to see if @beeradb or @tannerjfco have any objection from a technical perspective, otherwise it's a 👍  from me.

**Comment by rfay** [comment]
Yes, there would be no change in functionality, and it would be much easier to understand code structure.

**Comment by beeradb** [comment]
Big +1.

I'd add to this that I believe we should combine the local "platform" and appconfig while doing this. It would make for a slightly larger change, but I believe it would simplify things and make the code much more maintainble.

**Comment by tannerjfco** [comment]
No objection here, agreed w/ localapp/appconfig consolidation too.

**Comment by rickmanelius** [comment]
Remaining actions.
* @rfay If you feel there is any additional detail necessary to make this actionable and testable, I would appreciate it. Adding to Incubate for now.
* @rickmanelus. I need to get this attached to an appropriate milestone along with the updates to the roadmap (#534). Until then, I am going to bat out of order and bring to the dev board and we'll just make sure this gets handled in the next upcoming release because it feels like a good ROI given the time/impact.

**Comment by rfay** [comment]
Comment from @beeradb 
> I also think LocalApp & appConfig should be the same struct

**Comment by rfay** [comment]
I will do the appConfig struct consolidation in a separate PR after this one goes in.

**Comment by rfay** [comment]
The first and biggest round is in. Next step is a PR that consolidates the appConfig into LocalApp.
