### ISSUE TITLE
Improve export-db experience

### ISSUE THREAD

**Issue by Greg-Boggs** [drud/ddev#4580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Everytime I need to get a SQL dump with ddev, I remember it being problematic, and always forget why until I crash my system running the command.

Instead of outputting gigs of Gz output to stdout, can we have it create a file by default perhaps with a progress bar?

### Describe your solution

Here's one example command that works outside of ddev to give us a nice progress bar and to dump to a file.

mysqldump <parameters> | pv --progress --size 100m > dumpfile.sql

### Describe alternatives

We could add an are you sure y/n before starting the dump. We could also update the help text to warn folks to direct it to a file before running it.

**Comment by rfay** [comment]
`ddev export-db -h` gives you a bunch of different examples, easy to look at every time you need it.

**Comment by Greg-Boggs** [comment]
I'll just stick to mysqldump to pv I guess.

**Comment by rfay** [comment]
It's super easy to create your own custom command as well that does what you want. https://ddev.readthedocs.io/en/latest/users/extend/custom-commands/
