### ISSUE TITLE
Local Installs not reaching WP's Server

### ISSUE THREAD

**Issue by bbertucc** [drud/ddev#4586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/bbertucc/64db9c44038802277433d836b77adbae#file-ddev-debug-test

### Expected Behavior

WordPress to download when I ran `ddev wp core download` and no WP error everytime I login to WordPress.

### Actual Behavior

When I ran the wp core download I got this error:
```
Error: RuntimeException: Failed to get url 'https://api.wordpress.org/core/version-check/1.7/?locale=en_US': cURL error 28: Resolving timed out after 10000 milliseconds.
Failed to run wp core download: exit status 1
```
When I login to WordPress (on different installations) I get these errors:
```
Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the [support forums](https://wordpress.org/support/forums/). (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /var/www/html/wp-includes/update.php on line 447
```
```
Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the [support forums](https://wordpress.org/support/forums/). (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /var/www/html/wp-includes/update.php on line 728
```

### Steps To Reproduce

Run `ddev wp core download` or login to a local instance of WordPress.

**Comment by rfay** [comment]
I'm not sure that `ddev wp core download` does anything at all with composer... is it possible you have a `composer install` in your .ddev/config.yaml?

The message you're getting comes from the wp tool, and it may mean that you have no connectivity inside docker. 

I'd know more if your gist was complete. thanks for uploading it, but it seems to end in the middle of the output. Maybe you can take a look and see if it gets farther?

**Comment by bbertucc** [comment]
Oops! Sorry @rfay .. I was too quick on the trigger. I updated my original message with a complete gist and behavior.. composer wasn't the issue. Thanks again!

**Comment by rfay** [comment]
Yeah, 
> Error: RuntimeException: Failed to get url 'https://api.wordpress.org/core/version-check/1.7/?locale=en_US': cURL error 28: Resolving timed out after 10000 milliseconds.

It can't resolve api.wordpress.org, so your docker is broken. You can experiment with `ping api.wordpress.org` inside the container (`ddev ssh`) to learn more. Again, firewall and vpn are starting place. And restarting docker. And restarting your computer.

**Comment by bbertucc** [comment]
o darn.. the `ping api.wordpress.org` indeed doesn't work. i went down the firewall and VPN route with no success. restarted docker & computer.. no success.. i guess, reinstalling docker and ddev?

**Comment by rfay** [comment]
Has nothing to do with ddev, and you shouldn't need to reinstall docker. But you may be interested in using Colima if you're not wedded to Docker Desktop. Note that all the things you're about to do destroy your databases, so make sure you have dumps or snapshots. Colima instructions at https://ddev.readthedocs.io/en/latest/users/install/docker-installation/#macos

**Comment by bbertucc** [comment]
Thanks @rfay - I got it going after I got rid of Docker Desktop and switched to Colima.
