### ISSUE TITLE
ddev remove only removes sites based on a .ddev/config.yml and root directory 

### ISSUE THREAD

**Issue by nmccrory** [drud/ddev#459]
## What happened (or feature request):
When straightening out ddev #374 another issue arose that is totally detached from `ddev list`. In the case of a missing site directory, ddev remove cannot be used to clean up old sites - due to the fact that it looks for a .ddev/config.yml to do so.  

## What you expected to happen:
It was expected that `ddev rm` could be used to remove all containers or assets leftover from a site with a missing directory. 

## How to reproduce this:
This can easily be reproduced. Simply create a wordpress or drupal site and run `ddev config` then `ddev start`. Once the site is running, `rm -r` the site directory and then try cleaning up its containers using its site name: `ddev rm <site-name>`. This should result in output that reads `Failed to remove: unable to determine the application for this command. Have you run 'ddev config'? Error: no .ddev/config.yaml file was found in this directory or any parent`

## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.
ddev version:
```
cli:       	v0.9.1-7-geae481c6                                                                 
web:       	drud/nginx-php-fpm7-local:v0.7.4                                                   
db:        	drud/mysql-local-57:v0.6.2                                                         
dba:       	drud/phpmyadmin:v0.2.0                                                             
router:    	drud/ddev-router:v0.4.3                                                            
commit:    	v0.9.1-7-geae481c6                                                                 
build info:	Built Fri Sep 8 11:12:56 CDT 2017 Nick@Nicks-Air drud/golang-build-container:v0.5.0
```
docker version: 
```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:12:06 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

## Related source links or issues:
#374

**Comment by rfay** [comment]
Note that 
* `ddev describe <site>` has the same problem. 
* `ddev stop <site>` has the same problem.

However:
* `ddev logs <site>` works in this case. 
* `ddev ssh <site>` works.

And there's the weirdness that `ddev start` and `ddev restart` don't take the sitename arg. `ddev start` probably doesn't because it's the first-round creation sometimes. No reason in the world that restart shouldn't work with sitename. All of these kind of issues are important for the gui.

**Comment by rfay** [comment]
This is not yet quite to completion, as the final work to prevent error doesn't quite work  yet.

**Comment by brace110** [comment]
This still seems to be an active issue? any progress?

**Comment by rfay** [comment]
This was long solved. Happy to help you here or elsewhere with any trouble you're having.

**Comment by brace110** [comment]
I had to remove certain ddev projects from 'ddev list' that no longer had a ddev folder. Removing them seemed impossible with any command, but I was successful by manually removing them from the ~/.ddev/global_config.yaml

**Comment by rfay** [comment]
Thanks. The canonical way to do this would be `ddev delete <project>` or `ddev stop -RO <project>` but the way you did it was just fine (IF all containers were destroyed first)
