### ISSUE TITLE
WSL2 - PHPStorm on Windows - XDebug works - CLI does not

### ISSUE THREAD

**Issue by ChristianAdamski** [drud/ddev#4598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/ChristianAdamski/aaa7acb3872b66fc80f2cc78e5084bec

### Expected Behavior

The CLI in PHPStorm does not work. See attached Sceenshot. Visiting the site in Windows at XXX.ddev.site works, Xdebug works, CLI does not.

Specifically tried to enable CodeSniffer.

### Actual Behavior

![ddev-docker-compose](https://user-images.githubusercontent.com/8464825/215269175-c1226df5-c0bd-43ee-8d2a-deeb58537b80.jpg)

\\wsl$\Ubuntu\home\cap\.ddev\bin\docker-compose exists

PHPStorm Docker is set to WSL, PHPStorm can connect.

**Comment by rfay** [comment]
What CLI are we talking about here? The `ddev` cli?

Does it work in the WSL terminal?

What are you doing to get this to happen?

Are you using the DDEV PhpStorm plugin?

Does your project have extra configuration, like `.ddev/docker-compose.*.yaml` files? Have you tried removing them? It seems to be complaining that you have an invalid configuration, and is probably telling you what line it's on...

Thank you for showing the output of `ddev debug test`, which says that ddev is doing everything fine.

Squinting to read your screenshot, I see it saying that `docker-compose config --file` is invalid, I imagine your PhpStorm is not configured to point to the proper docker-compose, and probably you have a version of docker-compose v1 somewhere in your $PATH. 

Please take another look at https://ddev.readthedocs.io/en/latest/users/install/phpstorm/#phpstorm-setup and walk through each thing step-by-step, and if you're not using the plugin, you'll sure like it.

**Comment by ChristianAdamski** [comment]
What CLI are we talking about here? The ddev cli?
=> Yes

Does it work in the WSL terminal?
=> What does that mean?
Simply opening a Terminal (from PHPStorm) and calling "php" does not work. php-cli is not installed.

What are you doing to get this to happen?
=> Simply opening the DDEV CLI configuration screen in PHPStorm. It's just there. I think for a split second the "web" service can be seen, but then the service-drop-down-select is empty and the error is shown

Are you using the DDEV PhpStorm plugin?
=> Yes

Does your project have extra configuration, like .ddev/docker-compose.*.yaml files? Have you tried removing them? It seems to be complaining that you have an invalid configuration, and is probably telling you what line it's on...
=> No. I did not touch the .ddev-*-.yml

Thank you for showing the output of ddev debug test, which says that ddev is doing everything fine.

Squinting to read your screenshot, I see it saying that docker-compose config --file is invalid, I imagine your PhpStorm is not configured to point to the proper docker-compose, and probably you have a version of docker-compose v1 somewhere in your $PATH.
=> Calling docker-compose from Terminal does not work. It's not installed. The specifc docker-compose at ~/.ddev/bin shows version 2
The docker settings in PHPStorm want me to point to a Windows executable. In WSL. ???

Please take another look at https://ddev.readthedocs.io/en/latest/users/install/phpstorm/#phpstorm-setup and walk through each thing step-by-step, and if you're not using the plugin, you'll sure like it.
=> I'm pretty sure I did that :(

----

I don't know what to do from here. It generally work, I just can't use any tools in PHPStorm based on CLI.

**Comment by rfay** [comment]
The problem you're demonstrating in the screenshot is not about the ddev CLI, but about docker-compose failing.

If you go through and make sure you've done the instructions again, I'll be glad to do a screenshare call with you to help you figure it out. Lots of people are using this successfully.

**Comment by ChristianAdamski** [comment]
Well, I do think the relevant documentation is this:

```
Prerequisite
Regardless of your setup, you need to have PhpStorm use DDEV’s private docker-compose executable.

In PhpStorm, navigate to Preferences → Build, Execution, Deployment → Docker → Tools, and set the docker-compose executable to the full path of your .ddev/bin/docker-compose file relative to your home directory.

If you’re using WSL2 and running PhpStorm on the Windows side, PhpStorm can’t use docker-compose from WSL2, so configure Docker Desktop in Settings → General to “Use Docker Compose V2” and use a recent version of Docker Desktop.
```

But how? I do not have docker desktop installed, as the documentation advises against it. So docker is within WSL2. PHPStorm is installed on Windows. PHPStorm therefor demands a Windows executable file. So what to do?

**Comment by rfay** [comment]
I don't think you ever said that you are using the docker-ce install here.

* The plugin has not really yet been thoroughly tested with non-docker-desktop.
* However, latest PhpStorm allows you to configure the Docker integration to use docker-inside-wsl2. I casually tested it and found that it worked:
![Screenshot_20221214_041946 (1)](https://user-images.githubusercontent.com/112444/215285319-185efdad-fd9c-47e5-9e6a-8af21eae0842.png)

**Comment by ChristianAdamski** [comment]
Hmm. Wanna do a screenahre? If yes, how?

Alternatively: You do recommend docker-desktop?

From the documentation I assumed it to be outdated:

`Windows[¶](https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#windows)

You can install DDEV on Windows three ways:

    [Using WSL2 with Docker inside](https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#wsl2-docker-ce-inside-install-script)
    [Using WSL2 with Docker Desktop](https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#wsl2-docker-desktop-install-script)
    [Installing directly on traditional Windows](https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#traditional-windows) with an installer

We strongly recommend using WSL2. While its Linux experience may be new for some Windows users, it’s worth the performance benefit and common experience of working with Ubuntu and Bash.`

**Comment by rfay** [comment]
My recommendation is docker-ce for most things. Docker Desktop is fully supported. Only in the latest version did PhpStorm start working with docker-ce-inside-WSL2.

Screenshare with google meet, zoom, anything you want. I don't have a WSL2 machine with me just this moment so can't do it right now What timezone are you in? I'm US MT, UTC-7

**Comment by ChristianAdamski** [comment]
Berlin, Germany. christian.adamski@googlemail.com

Google works, Zoom I can install. Send me an invite and I can show you. Might be interesting.

**Comment by rfay** [comment]
If you'll be available tomorrow afternoon/evening your time? or Monday? That way I can try it out and see how it's working for me before our call.

**Comment by ChristianAdamski** [comment]
Tomorrow before 4pm or after 8pm, Monday before 7pm, Berlin time is fine. Or right now, just to demonstrate the issue.

**Comment by rfay** [comment]
I think maybe you're saying this, that WSL2 does not have PHP installed. It generally should not (I don't recommend installing it because it will cause confusion). `php` lives in the ddev-webserver container; you get there with `ddev ssh` or you can `ddev exec php`. 

![image](https://user-images.githubusercontent.com/112444/215294500-8fecfc24-b2f9-4497-8c1d-15a8cc3ac960.png)

All you have to do is `ddev ssh` to get into the container where everything is happening.

**Comment by rfay** [comment]
Sent you an invite for Monday.

If just knowing that the WSL2 shell and the ddev-webserver container are different things gets you farther along, we don't have to do that. But happy to spend some time taking a look.

**Comment by rfay** [comment]
This section of the docs may help as well, https://ddev.readthedocs.io/en/latest/users/usage/architecture/#container-architecture

**Comment by rfay** [comment]
Thanks for taking the time to study this PhpStorm problem today, and will look forward to what you learn with experimentation. I'm sure that PhpStorm can do better here, and the PhpStorm plugin may need some effort for this too. And it may be that we should put in the docs that the Docker Desktop setup is best if you're using PhpStorm on the Windows side. 

I'm going to close this for now because it doesn't lead anywhere but I think now that you understand the various things going on we can create new issues as needed (or you may want to click the edit button on the PhpStorm integration page in the docs to create a PR). Looking forward to hearing more, and of course you're invited to [DDEV Discord Channel](https://discord.gg/hCZFfAMc5k)
