### ISSUE TITLE
`ddev get --list` is not showing the official add-ons

### ISSUE THREAD

**Issue by rfay** [drud/ddev#4608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

`ddev get --list` should show official add-ons

### Actual Behavior

It's not showing add-ons that have moved to github.com/ddev (which will soon be all of them)

### Workarounds

`ddev get --list --all` shows all add-ons
`ddev get ddev/redis` etc work fine. 

The problem is that existing code has "drud" wired into the idea of "official" add-ons.

**Comment by tyler36** [comment]
Current behavior:

- `ddev get --list` shows addons from `drud` domain.
- `ddev get --list --all` shows unofficial addons and official addons on the `ddev` domain

**Comment by gilbertsoft** [comment]
Prerelease fixing this issue is available https://github.com/drud/ddev/releases/tag/v1.21.5-alpha1
