### ISSUE TITLE
Error when composer version updated (Linux, docker 23.0.0)

### ISSUE THREAD

**Issue by sanoopuio** [drud/ddev#4624]
### Is there an existing issue for this?

Existing issue with docker 23.0.0 is at 
* https://github.com/drud/ddev/issues/4616 

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

I need composer versin less than 2.4

So i updated composer_version: "2.2" in config.yaml 

ddev restart gives below error 

`----
', stderr='failed to solve: process "/bin/sh -c export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2.2 || composer self-update --2.2 || true" did not complete successfully: exit code: 1' 
`

### Expected Behavior

Composer show be downgarded to 2.2 and ddev starts

### Actual Behavior

ddev start shows error

**Comment by sanoopuio** [comment]
![image](https://user-images.githubusercontent.com/904870/217831550-3035a50a-83de-4eb2-9179-bbe444823ff5.png)

**Comment by rfay** [comment]
I'm unable to reproduce this. Please provide the requested `ddev debug test` output (preferably as a gist or other pastebin) and please show the full output of your `ddev restart`. It's most likely a network problem.

**Comment by sanoopuio** [comment]
`ddev restart
Restarting project shopware... 
Container ddev-shopware-dba  Removed 
Container ddev-shopware-db  Removed 
Container ddev-shopware-web  Removed 
Network ddev-shopware_default  Removed 
failed to solve: process "/bin/sh -c export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2.2 || composer self-update --2.2 || true" did not complete successfully: exit code: 1 
Failed to restart shopware: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-shopware docker-compose -f /home/sanoop/Projects/shopware/.ddev/.ddev-docker-compose-full.yaml up --build -d', action='[up --build -d]', err='exit status 17', stdout='#1 [drud/ddev-dbserver-mariadb-10.4:v1.21.4-shopware-built internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.1s

#2 [drud/ddev-dbserver-mariadb-10.4:v1.21.4-shopware-built internal] load build definition from Dockerfile
#2 transferring dockerfile: 591B done
#2 DONE 0.1s

#3 [drud/ddev-webserver:v1.21.4-shopware-built internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [drud/ddev-webserver:v1.21.4-shopware-built internal] load build definition from Dockerfile
#4 transferring dockerfile: 926B done
#4 DONE 0.1s

#5 [drud/ddev-dbserver-mariadb-10.4:v1.21.4-shopware-built internal] load metadata for docker.io/drud/ddev-dbserver-mariadb-10.4:v1.21.4
#5 DONE 0.0s

#6 [drud/ddev-dbserver-mariadb-10.4:v1.21.4-shopware-built 1/2] FROM docker.io/drud/ddev-dbserver-mariadb-10.4:v1.21.4
#6 DONE 0.0s

#7 [drud/ddev-dbserver-mariadb-10.4:v1.21.4-shopware-built 2/2] RUN (groupadd --gid 1000 "sanoop" || groupadd "sanoop" || true) && (useradd  -l -m -s "/bin/bash" --gid "sanoop" --comment '' --uid 1000 "sanoop" || useradd  -l -m -s "/bin/bash" --gid "sanoop" --comment '' "sanoop" || useradd  -l -m -s "/bin/bash" --gid "1000" --comment '' "sanoop" || useradd -l -m -s "/bin/bash" --comment '' sanoop )
#7 CACHED

#8 [drud/ddev-webserver:v1.21.4-shopware-built internal] load metadata for docker.io/drud/ddev-webserver:v1.21.4
#8 DONE 0.0s

#9 [drud/ddev-webserver:v1.21.4-shopware-built 1/4] FROM docker.io/drud/ddev-webserver:v1.21.4
#9 DONE 0.0s

#10 [drud/ddev-dbserver-mariadb-10.4:v1.21.4-shopware-built] exporting to image
#10 exporting layers done
#10 writing image sha256:7f7f3be3dc97d84f46cc2baeb502c361f48db5d61a8de83865c298f5c2efb57b 0.0s done
#10 naming to docker.io/drud/ddev-dbserver-mariadb-10.4:v1.21.4-shopware-built done
#10 DONE 0.0s

#11 [drud/ddev-webserver:v1.21.4-shopware-built 2/4] RUN (groupadd --gid 1000 "sanoop" || groupadd "sanoop" || true) && (useradd  -l -m -s "/bin/bash" --gid "sanoop" --comment '' --uid 1000 "sanoop" || useradd  -l -m -s "/bin/bash" --gid "sanoop" --comment '' "sanoop" || useradd  -l -m -s "/bin/bash" --gid "1000" --comment '' "sanoop" || useradd -l -m -s "/bin/bash" --comment '' sanoop )
#11 CACHED

#12 [drud/ddev-webserver:v1.21.4-shopware-built 3/4] RUN export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2.2 || composer self-update --2.2 || true
#12 0.305 runc run failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory
#12 ERROR: process "/bin/sh -c export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2.2 || composer self-update --2.2 || true" did not complete successfully: exit code: 1
------
 > [drud/ddev-webserver:v1.21.4-shopware-built 3/4] RUN export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2.2 || composer self-update --2.2 || true:
#12 0.305 runc run failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory
------
', stderr='failed to solve: process "/bin/sh -c export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2.2 || composer self-update --2.2 || true" did not complete successfully: exit code: 1' 
sanoop@sanoop-TUXEDO:~/Projects/shopware$ 
`

**Comment by sanoopuio** [comment]
ddev restart
Restarting project shopware... 
Container ddev-shopware-dba  Removed 
Container ddev-shopware-db  Removed 
Container ddev-shopware-web  Removed 
Network ddev-shopware_default  Removed 
failed to solve: process "/bin/sh -c export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2.2 || composer self-update --2.2 || true" did not complete successfully: exit code: 1 
Failed to restart shopware: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-shopware docker-compose -f /home/sanoop/Projects/shopware/.ddev/.ddev-docker-compose-full.yaml up --build -d', action='[up --build -d]', err='exit status 17', stdout='#1 [drud/ddev-dbserver-mariadb-10.4:v1.21.4-shopware-built internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.1s

#2 [drud/ddev-dbserver-mariadb-10.4:v1.21.4-shopware-built internal] load build definition from Dockerfile
#2 transferring dockerfile: 591B done
#2 DONE 0.1s

#3 [drud/ddev-webserver:v1.21.4-shopware-built internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [drud/ddev-webserver:v1.21.4-shopware-built internal] load build definition from Dockerfile
#4 transferring dockerfile: 926B done
#4 DONE 0.1s

#5 [drud/ddev-dbserver-mariadb-10.4:v1.21.4-shopware-built internal] load metadata for docker.io/drud/ddev-dbserver-mariadb-10.4:v1.21.4
#5 DONE 0.0s

#6 [drud/ddev-dbserver-mariadb-10.4:v1.21.4-shopware-built 1/2] FROM docker.io/drud/ddev-dbserver-mariadb-10.4:v1.21.4
#6 DONE 0.0s

#7 [drud/ddev-dbserver-mariadb-10.4:v1.21.4-shopware-built 2/2] RUN (groupadd --gid 1000 "sanoop" || groupadd "sanoop" || true) && (useradd  -l -m -s "/bin/bash" --gid "sanoop" --comment '' --uid 1000 "sanoop" || useradd  -l -m -s "/bin/bash" --gid "sanoop" --comment '' "sanoop" || useradd  -l -m -s "/bin/bash" --gid "1000" --comment '' "sanoop" || useradd -l -m -s "/bin/bash" --comment '' sanoop )
#7 CACHED

#8 [drud/ddev-webserver:v1.21.4-shopware-built internal] load metadata for docker.io/drud/ddev-webserver:v1.21.4
#8 DONE 0.0s

#9 [drud/ddev-webserver:v1.21.4-shopware-built 1/4] FROM docker.io/drud/ddev-webserver:v1.21.4
#9 DONE 0.0s

#10 [drud/ddev-dbserver-mariadb-10.4:v1.21.4-shopware-built] exporting to image
#10 exporting layers done
#10 writing image sha256:7f7f3be3dc97d84f46cc2baeb502c361f48db5d61a8de83865c298f5c2efb57b 0.0s done
#10 naming to docker.io/drud/ddev-dbserver-mariadb-10.4:v1.21.4-shopware-built done
#10 DONE 0.0s

#11 [drud/ddev-webserver:v1.21.4-shopware-built 2/4] RUN (groupadd --gid 1000 "sanoop" || groupadd "sanoop" || true) && (useradd  -l -m -s "/bin/bash" --gid "sanoop" --comment '' --uid 1000 "sanoop" || useradd  -l -m -s "/bin/bash" --gid "sanoop" --comment '' "sanoop" || useradd  -l -m -s "/bin/bash" --gid "1000" --comment '' "sanoop" || useradd -l -m -s "/bin/bash" --comment '' sanoop )
#11 CACHED

#12 [drud/ddev-webserver:v1.21.4-shopware-built 3/4] RUN export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2.2 || composer self-update --2.2 || true
#12 0.305 runc run failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory
#12 ERROR: process "/bin/sh -c export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2.2 || composer self-update --2.2 || true" did not complete successfully: exit code: 1
------
 > [drud/ddev-webserver:v1.21.4-shopware-built 3/4] RUN export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2.2 || composer self-update --2.2 || true:
#12 0.305 runc run failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory
------
', stderr='failed to solve: process "/bin/sh -c export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2.2 || composer self-update --2.2 || true" did not complete successfully: exit code: 1' 
sanoop@sanoop-TUXEDO:~/Projects/shopware$

**Comment by rfay** [comment]
Apparently you're on Linux and you updated to Docker v23.0.0. Please see pinned issue
* https://github.com/drud/ddev/issues/4616

Try the fixes in https://github.com/drud/ddev/issues/4616#issuecomment-1421429448

**Comment by sanoopuio** [comment]
> Apparently you're on Linux and you updated to Docker v23.0.0. Please see pinned issue
> 
> * [Linux: Can't start project with docker 23.0.0; fix with `ddev debug refresh` #4616](https://github.com/drud/ddev/issues/4616)
> 
> Try the fixes in [#4616 (comment)](https://github.com/drud/ddev/issues/4616#issuecomment-1421429448)

thanks very much , it solved my issue

**Comment by rfay** [comment]
Glad it's working for you!
