### ISSUE TITLE
Pantheon ddev pull fails with mysql container unhealthy

### ISSUE THREAD

**Issue by dsquaredb** [drud/ddev#466]
## What happened (or feature request):
Database import failed after creating a ddev version of a D7 Pantheon site

## What you expected to happen:
Import Pantheon database and files with 'ddev pull' after configuring the ddev site

## How to reproduce this:
1. Git clone Pantheon dev site
2. Run 'ddev config pantheon'
3. After receiving the 'Configuration complete' message, run 'ddev pull'
4. ddev process begins but times out at 'Starting service health checks...' with this message:
'Could not perform import: db service health check timed out'

## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.

No .ddev/config.yaml for this site

`MacBook-Pro-7:innovationhub ddbow$ ddev version
cli:       	v0.9.1                                                                                                                               
web:       	drud/nginx-php-fpm7-local:v0.7.4                                                                                                     
db:        	drud/mysql-local-57:v0.6.2                                                                                                           
dba:       	drud/phpmyadmin:v0.2.0                                                                                                               
router:    	drud/ddev-router:v0.4.3                                                                                                              
commit:    	v0.9.1                                                                                                                               
build info:	Built Wed Aug 23 19:23:48 UTC 2017 circleci@prealloc-dmiqwyml-0bdaa5ed-1565-4a78-95e9-68dbad331de6 drud/golang-build-container:v0.4.2`

`MacBook-Pro-7:innovationhub ddbow$ docker version
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:38 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:54:55 2017
 OS/Arch:      linux/amd64
 Experimental: true`

**Comment by beeradb** [comment]
@dsquaredb We've seen some occasional timeouts for the database container health checks when starting. We probably need to raise that timeout.

Can you run a `ddev start` followed by a `ddev pull` and see if that resolves the issue? In the past when I've seen the health check issue it usually resolves itself with another attempt or two at `ddev start`.  

I'll also get a ticket in place to raise that timeout/investigate why that container is sometimes slow to start.

**Comment by beeradb** [comment]
I believe the source of this issue is https://github.com/drud/ddev/issues/445

**Comment by rfay** [comment]
Related issue [DB container slow to start](https://github.com/drud/ddev/issues/445)

On my own machine, I *think* I've seen this more when I had lots of sites going, and I *think* it's calmed down when I added more memory for docker to use. 

Would love to see if this happens with increased memory (or if it's repeatable at all, we're a bit fuzzy on when/why it would happen).

![advanced_and_pantheon_ddev_pull_fails_ _issue__466_ _drud_ddev](https://user-images.githubusercontent.com/112444/30550904-14aea02a-9c56-11e7-9976-ca118b253a73.png)

**Comment by dsquaredb** [comment]
Per suggestion by @rfay, I increased the docker memory limit and restarted docker. 

I then got errors that the ddev-router failed to start. 

I discovered that when I restart docker, it inadvertently restarts Kalabox. Once I discovered that and spun those containers down, I no longer get the dev-router error but am back to ‘db service health check timed out’.

I tried dev start followed by dev pull several times with no success.

To see if it was site-specific, I cloned another D7 site from Pantheon, ran ‘dev config pantheon’ successfully. Then ran ‘dev pull’ and got  ‘db service health check timed out’ on this site, too.

**Comment by rfay** [comment]
Wow, thanks for that.

Could you please get the logs from the docker container? To do that,

* `docker ps` and you'll see the mysql containers that aren't healthy.
* `docker logs <hash>` of an unhealthy mysql container.

**Comment by dsquaredb** [comment]
`MacBook-Pro-7:physforpeace ddbow$ docker ps
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                    PORTS                                                                         NAMES
2588e9ff989a        drud/ddev-router:v0.4.3            "/app/docker-entry..."   44 minutes ago      Up 44 minutes (healthy)   0.0.0.0:80->80/tcp, 0.0.0.0:8025->8025/tcp, 0.0.0.0:8036->8036/tcp, 443/tcp   ddev-router
51634318d75d        drud/phpmyadmin:v0.2.0             "/run.sh phpmyadmin"     2 hours ago         Up 2 hours (healthy)      0.0.0.0:32779->80/tcp                                                         ddev-innovationhub-dba
f68ba16fa827        drud/nginx-php-fpm7-local:v0.7.4   "/start.sh"              2 hours ago         Up 2 hours (unhealthy)    443/tcp, 0.0.0.0:32778->80/tcp, 0.0.0.0:32777->8025/tcp                       ddev-innovationhub-web
13b0c56d84ec        drud/mysql-local-57:v0.6.2         "/entrypoint.sh my..."   2 hours ago         Up 2 hours (unhealthy)    33060/tcp, 0.0.0.0:32776->3306/tcp                                            ddev-innovationhub-db`

**Comment by rfay** [comment]
Did you mean to close this? 

The key issue is the `docker logs <container>`, not the actual docker ps

I had also edited https://github.com/drud/ddev/issues/466#issuecomment-330377136 with some other suggestions.

**Comment by dsquaredb** [comment]
No, accidentally closed it and gave you the wrong file. Geez...
[untitled.txt](https://github.com/drud/ddev/files/1312523/untitled.txt)

**Comment by rfay** [comment]
@dsquaredb and I screenshared and chased this down.

The simple description:
* The db container did not have user/pass set on the db, so user=db/pass=db did not work. Obviously that would ruin the healthcheck as well.
* This was easy to fix by doing `ddev rm -R` on the site, then doing the `ddev pull` again.

My speculation:
* She had earlier created these sites with ddev and used them, so there were databases in ~/.ddev
* She removed all of the git checkouts completely from the filesystem
* She checked out the site again and did `ddev config pantheon` and `ddev pull`
* The mysql container entrypoint.sh may have a path where if the db is already there, it doesn't properly initialize it. 

I suspect this having to do with ddev's pantheon support, as we've never seen it before. 

But... I'm pretty sure that the current workflow (start->pull) is not quite right, for `ddev pull` we should be doing rm->start->pull - there's no reason we'd want the existing database to be around.

So:
* If customer has problem, `ddev rm --remove-data` is the solution.
* We should make `ddev pull` more robust to blow away the db before start
* We should figure out what happened in https://github.com/drud/docker.mysql-local/entrypoint.sh to *not* properly set up the db, and how the mount could have messed us up here.

**Comment by rfay** [comment]
Thanks so much for the report and the patience and the help @dsquaredb !

**Comment by dsquaredb** [comment]
Follow up after the screen share:

ddev pull completed and returned “Successfully started…”

Went to the url provided for the site and got the Drupal installation screen.

Logged in to the database with the ‘ddev describe' credentials and the database was present but not being recognized.

Checked the settings.php and added a call to the settings.local.php file and, finally, the site worked.

If I remember correctly, @beeradb had me add a call to settings.local.php on another site a couple of weeks ago.

**Comment by rfay** [comment]
I expected to be able to recreate this with this sequence, but could not:
1. Create site from pantheon
2. ddev rm
3. rm -rf .ddev
4. ddev config pantheon
5. ddev pull

But sadly, was not able to do it.

**Comment by rfay** [comment]
This was solved in the end by re-pulling the database.
