### ISSUE TITLE
DDEV in WSL2 Fedora 36 with Docker-CE tries to execute Windows binary: /ddev.exe: exec format error

### ISSUE THREAD

**Issue by konstantinblaesi** [drud/ddev#4667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

Inside WSL2 as my regular user
```
$ ddev start
Starting example-app...
Container ddev-ssh-agent  Recreate
Container ddev-ssh-agent  Recreated
Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
The hostname example-app.ddev.site is not currently resolvable, trying to add it to the hosts file
unable to run ddev.exe, please check it on Windows side; err=fork/exec /mnt/c/Program Files/DDEV/ddev.exe: exec format error; output=
Failed to start example-app: ddev.exe is not installed on the Windows side, please install it with 'choco install -y ddev'. It is used to manage the Windows hosts file

$ file "/mnt/c/Program Files/DDEV/ddev.exe"
/mnt/c/Program Files/DDEV/ddev.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
```

### Expected Behavior

ddev works

### Actual Behavior

ddev run from linux tries to execute a windows binary in linux and fails

### Steps To Reproduce

1. ddev start

### Anything else?

I am not a ddev/php user/dev most of the time, I just try to get a project up and running and had an existing fedora 36 wsl2 instance. Why does the linux ddev binary try to exec/fork a windows binary (which is obviusly expected to fail)?

**Comment by rfay** [comment]
Hi @konstantinblaesi - Latest DDEV uses ddev.exe on the WIndows side to manage hosts in the hosts file if you are using non-ddev.site hostnames. Please install latest Windows DDEV on the Windows side (v1.21.5-alpha1).

If you were not using non-ddev.site hostnames it would not have to do this.

**Comment by konstantinblaesi** [comment]
Ok I updated ddev on windows, both sides then had the same version v1.21.5-alpha1 but that didn't change the log above (kinda expected).
The issue was that my WSL2 Fedora instance did not know how to execute Windows binaries (ddev.exe here)

The reason being
a) I manually set the Fedora WSL2 [instance using this guide](https://dev.to/bowmanjd/install-fedora-on-windows-subsystem-for-linux-wsl-4b26)
b) I enabled systemd support to run the docker systemd service or generally let linux init properly
c) I used ddev within WSL2 Fedora, which failed to execute **any windows binary**

I did not even know that WSL2 **can** execute .exe so I figured ddev is acting weird. I learned that

a) WSL2 instances without systemd as init can run .exe out of the box (change /etc/wsl.conf and restart wsl2 instance)
b) WSL2 instances with systemd might need this file inside the WSL2 instance
```
$ cat /usr/lib/binfmt.d/WSLInterop.conf
:WSLInterop:M::MZ::/init:PF
```

Maybe of interest to others
```
$ cat /etc/wsl.conf
[boot]
systemd=true

[user]
default=konstantin

[interop]
enabled=true
```

I picked this info up from https://github.com/microsoft/WSL/issues/8843#issuecomment-1361064855

With these changes `ddev start` now works! :)

**Comment by rfay** [comment]
I like systemd as well, but the crux of your issue was not having interop configured, right? Doesn't have to do with systemd as far as I know. 

But the key for you is adding `/usr/lib/binfmt.d/WSLInterop.conf`  ?

**Comment by konstantinblaesi** [comment]
Adding interop=true was not enough with systemd=true, adding the file fixed that.

**Comment by rfay** [comment]
I don't think that should have happened, but thanks:

You had to add to `wsl.conf` 

```
[interop]
enabled=true
```

And you had to add `/usr/lib/binfmt.d/WSLInterop.conf`
