### ISSUE TITLE
META: inventory, research, and rank CMS and hosting provider support plans.

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#469]
I'm hearing more and more about this CMS and I'd like to dive in and start playing around with it to see if it's a compelling CMS and what the lift is to support it. No current plans to support it, but this is something worth paying attention to.

**Comment by rfay** [comment]
I'd like to see backdrop sooner.  I wouldn't be surprised if you can' get typo going though. Thought it was a thing of the past.

**Comment by rickmanelius** [comment]
@rfay I have a few other CMSs and so forth to add to the list. Perhaps I'll convert this to a meta to inventory both CMSs and providers and go from there!

**Comment by rickmanelius** [comment]
From a CMS/Framework side of things, I could see the following as useful in the short/mid term (not comprehensive and not ranked):

* Magento 
* Typo3
* Joomla
* Backdrop
* Node.js
* Symfony
* Laravel

From a hosting provider standpoint, this is a start (not comprehensive and not ranked):

* Lagoon
* Acquia
* Platform.sh
* newmedia

**Comment by rickmanelius** [comment]
Updated title to reflect the more overarching desires/needs.

**Comment by rickmanelius** [comment]
@Carlosbo1116 Just mentioning you in this thread for visibility.

**Comment by rickmanelius** [comment]
We will probably need to file an issue to support D6 as well.

**Comment by rickmanelius** [comment]
@CRReigan Tagging you in this issue because this is where we may decide to spin out Magento support if there is enough demand and it fits in line with our overall business objectives/direction.

**Comment by rickmanelius** [comment]
This issue might be a too unwieldy and should probably get closed/split out into something more specific. That said, going to split out a request for Sugar CRM.

**Comment by rfay** [comment]
I think we continue to listen to users and respond to them, so we can close this out in favor of our ongoing listening process.

**Comment by rickmanelius** [comment]
While this is parent issue is closed, cross referencing for audit trail purposes. Here's an explicit note about Laravel https://github.com/drud/ddev/issues/898.
