### ISSUE TITLE
Mailhog doesn't work on WSL2 when using Windows-side browser

### ISSUE THREAD

**Issue by mbomb007** [drud/ddev#4696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

[Link to `ddev debug test` Gist](https://gist.github.com/mbomb007/74b3473c84b272c14b8247168b6c2661)

After running the test container with `ddev debug test`, I ran `ddev launch -m` from the created project directory, and I had the same issue.

### Expected Behavior

Running `ddev launch -m` should bring me to working Mailhog.

### Actual Behavior

The command opens the proper URL in the browser, which then says:

> This site can’t be reached

### Steps To Reproduce

I have the pre-release because of https://github.com/drud/ddev/issues/4628

1. Create a Drupal project
2. put `$config['symfony_mailer.mailer_transport.sendmail']['configuration']['query']['command'] = ini_get('sendmail_path') . ' -t';` in settings.php
3. `ddev launch -m` doesn't work

Alternatively,

1. `ddev debug test`
2. `ddev launch -m` in the test project's directory doesn't work

**Comment by rfay** [comment]
I have no trouble with this, can't demonstrate your problem. Do you perhaps have a custom `launch` command? Maybe you can `rm -f ~/.ddev/commands/host/launch .ddev/commands/host/launch` and `ddev restart` to recreate them.

And please say what `ddev launch -m` "doesn't work" at? What does that mean, doesn't work? That you can't access the mailhog web UI? What happens instead?

You don't have to change any config in settings.php to use mailhog, so maybe you can remove that?

**Comment by rfay** [comment]
Also, `ddev describe` will show you the URL that `ddev launch -m` would open. It's just `https://<project>.ddev.site:8026`; you can put that in the browser to see what happens.

**Comment by rfay** [comment]
Site can't be reached won't have anything to do with your settings. 

Oh, I see you're using WSL2. It's fairly likely that you have a firewall problem. Plesae start by temporarily disabling firewall and VPN.

Do you have successful access to the site itself?

Can you `curl https://<project>.ddev.site:8026 ` inside WSL2? If so, it's a networking problem.

**Comment by rfay** [comment]
First, you're on WSL2, so please install DDEV v1.21.5-alpha1 on both WSL2 and Windows. That will let DDEV properly manage the Windows-side hosts file. 

But if you're using `*.ddev.site` you do not have to do anything to make `novarnish.*.ddev.site` work. It will work out of the box. No additional hostnames have to be added. 

You can `ping novarnish.something.ddev.site` to test this. Do it on the Windows side if you use the browser on Windows.

**Comment by rfay** [comment]
Earlier you had a completely different problem (failed to connect), https://github.com/drud/ddev/issues/4696#issuecomment-1452503286

So we're making progress?

Do you have the site running? And it would be `novarnish.<yourproject>.ddev.site`

**Comment by rfay** [comment]
Have you tried the http URL? `http://<projectname>.ddev.site:8025` ?

**Comment by rfay** [comment]
It's odd that 8025/8026 are affected by your firewall, but 80/43 are not. But I can't help you with your organization's firewall setup.

**Comment by rfay** [comment]
Does `ddev launch -p` work for you? (getting phpMyAdmin?)

And just regular URL `ddev launch` works OK?

**Comment by rfay** [comment]
I got a WSL2 machine out, and am able to get the 502 error I think you are getting, even with the traefik router.

Did you know that you can use `host_mailhog_port` in your config.yaml to bind a specific localhost port? Try that. 

`host_mailhog_port: 2002` will make mailhog appear at `http://localhost:2002` - it seems to work fine on WSL2 with browser on the Windows side.

**Comment by rfay** [comment]
Oh, interesting, I can just change the `mailhog_https_port: 8031` and everything works perfectly. There must be an odd conflict with 8025 on the Windows side?

**Comment by rfay** [comment]
Glad it's working for you.
