### ISSUE TITLE
`composer_version: 2.3` is not supported (2.3 is not LTS/no branch)

### ISSUE THREAD

**Issue by dkd-seidenberg** [drud/ddev#4698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

Hello,

I am currently using the latest "1.21.4" of ddev.

```
ddev -v
ddev version v1.21.4
```

Despite the configuration of the composer version "2.3" in the file ".ddev/config.yaml", the composer version 2.5 is used.

```
ddev composer -V
Composer version 2.5.4 2023-02-15 13:10:06
```

### Expected Behavior

I expect that version 2.3 will be used.

### Actual Behavior

Currently the version 2.5 is used 

Please check the reason for the wrong composer version.

Best regards

**Comment by rfay** [comment]
`2.3` is not a valid version for `composer_version`, see https://ddev.readthedocs.io/en/latest/users/configuration/config/#composer_version and

See the comments in .ddev/config.yaml:

```
# composer_version: "2"
# You can set it to "" or "2" (default) for Composer v2 or "1" for Composer v1
# to use the latest major version available at the time your container is built.
# It is also possible to use each other Composer version channel. This includes:
#   - 2.2 (latest Composer LTS version)
#   - stable
#   - preview
#   - snapshot
# Alternatively, an explicit Composer version may be specified, for example "2.2.18".
# To reinstall Composer after the image was built, run "ddev debug refresh".
```

`2.2` is a supported LTS version of composer though. 

If you need a specific version (with patch version) use that.

**Comment by rfay** [comment]
I think you'll probably be happy with 
`composer_version: 2.3.10` 

if you need an older composer version and 2.3 is important. 

With that I get:

```
$ ddev composer --version
Composer version 2.3.10 2022-07-13 15:48:23
```

Closing for now, happy to continue the conversation here or elsewhere.
