### ISSUE TITLE
Clear docker environment variables after using docker-compose.

### ISSUE THREAD

**Issue by beeradb** [drud/ddev#472]
## What happened (or feature request):
When using docker-compose we rely on environment variables for inserting things which are configurable via DDEV. We only set them within the context of the ddev binary, but rather than clearing them we rely on the process ending.

Unfortunately, when running tests, sometimes those environment variables stick around and cause unintended site effects. They could also cause problems if we tried to interact with multiple sites in the same `ddev command`.

## What you expected to happen:
Rather than relying on the ddev process finishing and these environment variables automatically going away, we should unset them after the docker-compose call ends. You can see the pain this causes in testing by looking at the testcommon.ClearDockerEnv() method. 

## How to reproduce this:
delete a few calls to testcommon.ClearDockerEnv() in local_test.go and see how things start failing and how confusing it is to figure out what is going on 😢

**Comment by rfay** [comment]
I spent a bit of time with this and found it was too destabilizing, so not going to do it.

**Comment by rfay** [comment]
Sadly, #7118 did not fix this issue
