### ISSUE TITLE
Packagist Support

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#474]
## What happened (or feature request):

* Feature request

## What you expected to happen:

As composer based development and builds become more prevalent, developers will need to rely on service like packagist to download/compile custom or paid modules and plugins. See https://packagist.org/.

**Comment by rickmanelius** [comment]
As @tannerjfco and I discussed outside the issue queue, this may not require anything specific to packagist, but it may require additional workflow support (particularly on ddev UI) for those adopting a composer first approach.

**Comment by tannerjfco** [comment]
Just to confirm, I tested a site with composer deps from packagist and composer install from the container worked as expected. I don't see that anything is going to be actionable for this issue, so I'm closing. If packagist-related issues somehow manage to crop up with ddev (I really can't see it happening), an issue can be filed at such time.
