### ISSUE TITLE
Failure to remove settings.php on ddev rm --remove-data (Don't remove settings file!)

### ISSUE THREAD

**Issue by rfay** [drud/ddev#478]
## What happened (or feature request):

I did a `ddev rm --remove-data` and got the error message

`Failed to remove gchistory: remove /Users/rfay/workspace/gchistory/docroot/sites/default/settings.php: permission denied
`

The settings.php in this case is in fact ddev-generated, so removing it would be legit in almost any context.

## What you expected to happen:

I didn't think it was such a hard task. I didn't expect an error. 

The problem here is just the classic problem that Drupal is *always* trying to set sites/default to unwriteable, even by the owner of the directory. So any user that wants to change sites/default/settings.php has to make the sites/default directory writeable first. We need to do that.

**Comment by rfay** [comment]
I don't think we should be removing any settings files - --remove-data is only to remove the db.

**Comment by rickmanelius** [comment]
Related:
https://github.com/drud/ddev/issues/603
https://github.com/drud/ddev/issues/517
https://github.com/drud/ddev/issues/394

A good summary of related issues is found in this issue summary. https://github.com/drud/ddev/issues/517

**Comment by rfay** [comment]
There's a secondary problem with this: When this happens, things that might happen after the settings removal don't get done. For example, the db won't be removed if doing a `ddev rm -R`. Just happened to me :(
