### ISSUE TITLE
High Sierra is out for OSX - Test and Update docs to "Sierra and higher"

### ISSUE THREAD

**Issue by rfay** [drud/ddev#480]
## What happened (or feature request):

We shortsightedly put a [requirement for OSX Sierra](https://github.com/drud/ddev#system-requirements) in our README (probably in docs also?). So:

1. Test on High Sierra
2. Update docs to say "Sierra and higher". 

Related, #398 where the discussion is about versions of OSX prior to Sierra.

**Comment by rickmanelius** [comment]
@rfay I'm happy to be the guinea pig in case something bad happens it doesn't block you unless you're already starting.

**Comment by rickmanelius** [comment]
Tagging myself or @nmccrory. Should be easy to test and confirm.

**Comment by rickmanelius** [comment]
So two warnings thus far:
* Install time on my machine (16GB 2.2 GHz Intel Core i7) was about 40 minutes.
* Requires an upgrade to Xcode 9.0 before you can do a home brew install.

**Comment by rickmanelius** [comment]
## Preparation

* Build ddev to `v0.9.1-11-g855a64c8`
* Confirmed the following commands pass manual testing (before upgrade to Xcode 9.X)
  * `start`
  * `stop`
  * `restart`
  * `rm`
  * `lsit`
  * `describe`
    * phpmyadmin
    * mailhog
  * `ssh`
  * `version`
* While this is cursory and I would prefer a manual test run, I'm not experiencing any obvious breaks. It looks like upgrading is safe and I say that once we prove a full test suite run that we state "macOS High Sierra" is the currently supported OS.

**Comment by rickmanelius** [comment]
@nmccrory When you're at a convenient point to upgrade overnight (so as to not cause downtime), please upgrade and run the local automated tests. If these pass, then I would update our docs. Thanks!

**Comment by rfay** [comment]
PR #492 makes the trivial docs change, if that's good enough for us.
I have also upgraded, and am ready to upgrade our macOS testbot when we see fit.

**Comment by rickmanelius** [comment]
@rfay I apologize if this is a naive question. What is the best approach to kickoff a test locally? I can run on my machine and confirm this so we can move on accepting the PR.

**Comment by rfay** [comment]
If you want to just run the normal tests, `make test`.

**Comment by rfay** [comment]
For future reference, see if the docs at https://github.com/drud/ddev/blob/master/docs/developers/building-contributing.md are good enough.

**Comment by rickmanelius** [comment]
@rfay Thanks! I'll file a separate issue because that already hits me up against things like: "pkg/appimport/appimport.go:12:2: cannot find package "github.com/mitchellh/go-homedir" in any of:... make: *** [testpkg] Error 1"

**Comment by rfay** [comment]
From my end, I got a clean `make test`, without GOTEST_SHORT being set (so it ran most tests). Also without the DDEV_PANTHEON_API_TOKEN set, so it didn't run pantheon tests.

**Comment by rickmanelius** [comment]
So I was able to run the tests with the $GOPATH fix from #493. I'm not familiar how to set GOTEST_SHORT, but I did see an error during the Solr tests. I haven't had the time to address, but there are instructions to resolve:

```
You must manually add the following entry to your hosts file:
127.0.0.1 TestServicesDrupal8.ddev.local
```

That said, I'm not the most adept at running tests and inferring the results, so it probably will take @rfay upgrading to confirm if I become a roadblock.

**Comment by rfay** [comment]
The "You must manually add"  is just normal for the tests (you'll see it in every test run on circle). The tests actually bypass the whole hostsfile issue, but the output to the user can still show.

GOTEST_SHORT *shortens* the test, which we don't want to do for you at this point. But if you want to, `export GOTEST_SHORT=true`

The key issue is whether `make test` succeeds (`echo $?`) after it's done, should be a 0.

**Comment by rfay** [comment]
@rickmanelius Reopening, you can close this when you're happy. The doc PR closed it automatically and `make test` comes clean for me, and I think we're in a good place, but want you to be comfortable with it.

**Comment by rickmanelius** [comment]
When I run `make test` using `export GOTEST_SHORT=true` as a preceding step, my run still ends with "make: *** [testpkg] Error 1". Seems like we're not fully done with this, at least from the perspective of my machine's configuration with High Sierra.

**Comment by rickmanelius** [comment]
At this point, I'm happy to not be a blocker here if this is more on me not having a proper Golang set up. I think it's safe enough to upgrade and @rfay or @tannerjfco will more likely determine if this is actually an issue with ddev or just me.

**Comment by rfay** [comment]
`make test` worked for me and I have had no trouble with the general usage. Closing.  This is one great thing about golang: It bundles everything in the binary, so is far less sensitive to new OS. Docker is also written in golang, so it should also be far less sensitive than past experiences.
