### ISSUE TITLE
ddev should provide info about PHP version we're using

### ISSUE THREAD

**Issue by rfay** [drud/ddev#487]
## What happened (or feature request):

Let's add php version into either `ddev version` or `ddev describe` .  Currently that would require a hit on our nginx container, or separate config, but it's a very obvious thing to want. Suggestions about how to do that effectively @beeradb @tannerjfco ?Anyway, it is a very normal question for people to want an answer to.  This question came up in my ddev demo the other day, and the answer was "You have to know how to do `ddev exec php --version` on an already running site" - Not sure if that's good enough.

**Comment by rfay** [comment]
I think the exec from ddev describe might be OK. Didn't like it in the version command, as that's supposed to be much faster. 

I'd love to have a php5.6 or lower container to run my D6 sites in for maintenance. Kind of wonder if we should bring that back.  I imagine I'm not the only one in the world, although also don't think it's "normal" for us to support d6. OTOH my prod server runs 5.6 with php7, and there might be some modules that aren't that good on 7.

**Comment by rickmanelius** [comment]
Semi-related https://github.com/drud/ddev/issues/330

**Comment by rfay** [comment]
I think this reporting needs to go into `ddev describe` and absolutely not into `ddev version`. The version command tells static things about how ddev was built. `ddev describe` tells about the site.

**Comment by cweagans** [comment]
PR is merged.
