### ISSUE TITLE
Convert ddev to use mariadb image instead of mysql image

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#488]
## What happened (or feature request):

* Change request.

## What you expected to happen:

* See PR here https://github.com/drud/docker.mysql-local/pull/27#issuecomment-330607039.
* Essentially, given the mariadb container has both feature parity with the mysql container and it utilizes a more preferential license, we should swap.
* Not urgent, but something worth addressing sooner than later if it's not a complicated lift.

**Comment by cweagans** [comment]
Are we just using the stock mariadb image? Or should the drud/docker.mysql-local image be completely rebuilt on top of mariadb?

**Comment by tannerjfco** [comment]
We've made some customization over time to the mysql image, and we'll need to be sure those changes are present in the maria replacement image. Off-hand I'm aware of custom my.cnf, healthcheck script, and I believe we've altered the entrypoint script. I'm sure there are others as well though.

**Comment by rfay** [comment]
So to add to Tanner's response: Just modify docker.mysql-local to use the official mariadb image as upstream, making whatever changes are required to do that.
