### ISSUE TITLE
ddev requires docker-compose, not just docker - make that clear and check

### ISSUE THREAD

**Issue by rfay** [drud/ddev#491]
## What happened (or feature request):

We have a number of checks (install script, ddev startup) that check to make sure docker is installed, but the reality is we need docker-compose too, and it's *not* bundled with docker on Linux, (although it mostly is on macOS and Linux). We might consider testing for both docker-compose *and* docker, or just let the linux people figure it out, or ... But docker-compose is fundamental of course.

**Comment by rickmanelius** [comment]
This is a weird inconsistency. Short term it should be noted, but should we file an issue with Docker to see if they are willing to rectify upstream?

**Comment by rickmanelius** [comment]
We've run into this again, this time when @nerdstein was attempting to install on Linux. We'll need to prioritize this in order to truly support the Linux userbase.

**Comment by cweagans** [comment]
PR is open!
