### ISSUE TITLE
Additional instructions needed for running local tests.

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#493]
## What happened (or feature request):

* Request for additional instructions and/or documentation.

## What you expected to happen:

When attempting to run `make test` on ddev master, I was unsuccessful. The documentation here https://github.com/drud/ddev/blob/master/docs/developers/building-contributing.md seems to imply there are no dependencies, and yet I'm getting a considerable amount of warnings stating that certain packages cannot be found. I'll paste my output in a comment.

## How to reproduce this:

* From a new machine (or at least my machine), git clone ddev and run `make test`

## Related source links or issues:

See comment here https://github.com/drud/ddev/issues/480#issuecomment-333567138

**Comment by rickmanelius** [comment]
Quick update. It looks like I simply didn't have my $GOPATH setup properly. I'll update and I should be good to Go! (get it?).

**Comment by rickmanelius** [comment]
Here are the instructions that assisted me. Add the following to .zshrc

```
mkdir -p ~/go/src/github.com/drud/ddev
export GOPATH=~/go
```

We should probably update the documentation (linked above in the issue summary) to Go's documentation regarding how to properly set up $GOPATH and then perhaps the snippet above as the quick and dirty solution.

**Comment by rfay** [comment]
You wouldn't want to add the mkdir to your .zshrc; you only create that directory once. And it needs to be populated with the checkout. So *one time only*

```
mkdir -p ~/go/src/github.com/drud/ddev
cd ~/go/src/github.com/drud/ddev
git clone git@github.com:drud/ddev.git .
```

Then after that, in that directory, with GOPATH set to ~/go, `make test`

**Comment by rickmanelius** [comment]
Sorry I was moving too fast! Yes, I wouldn't need to make the directory each time, but rather set the variable.

**Comment by rfay** [comment]
I think we were moving just too fast in general. If we're going to get you running local tests we need to get your environment set up before anything else, and probably get you a hello-world golang program. Here's the official starter, https://golang.org/doc/code.html - It's a lot better thing to do than ddev. Try the hello-world there after doing the environment setup. Then the tricky thing is to remember you always have to be in the golang workspace/GOPATH.  First programming languages I've ever seen that had arcane setup weirdness like this. You are *not* the first.

**Comment by rickmanelius** [comment]
Going to move this to hibernate for a bit. The motivating issue was closed and we can revisit if/when outside collaborators need assistance getting up to speed.
