### ISSUE TITLE
keepalive connection warnings in web container logs

### ISSUE THREAD

**Issue by rfay** [drud/ddev#494]
## What happened (or feature request):

I notice this in our test output, don't remember it before. I think maybe our FPM connection is going away or something? 

```
2017/10/02 15:44:41 [info] 19#19: *15 client 127.0.0.1 closed keepalive connection
DEBU[0000] framesize: 83
2017/10/02 15:44:46 [info] 19#19: *16 client 127.0.0.1 closed keepalive connection
```

This may be just a result of https://stackoverflow.com/questions/24924237/linux-curlnginx-cant-request-with-no-keepalive and how we're testing, and if it only happens on tests/curl it's no biggie.

## How to reproduce this:

Do a `ddev logs` on one of out test containers (from `make test` while it's up. I did `ddev logs` on TestMainCmdWordpress

**Comment by rfay** [comment]
This is really annoying, and basically makes `ddev logs` useless.

This could also be fixed by just changing to outputting the php-fpm logs instead. I'm not sure a dev would be very interested in the nginx logs usually.

@rickmanelius I'd like to see this get prioritized as it's important to our users.

**Comment by rickmanelius** [comment]
I'd be a fan of defaulting to php-fpm logs. It does raise a bigger question of how to target specific services within each container versus only allowing `ddev logs` to target a specific container.

**Comment by rickmanelius** [comment]
@rfay I'm assuming we can close this given the PRs are in... unless there were some release instructions that you were keeping this open for.

**Comment by rfay** [comment]
No, can't be closed until we make a release of nginx-php-fpm-local (with other things that will come in for the next release).

Alternately, we can release an interim nginx-php-fpm-local with just this, which would probably fix our nightly build.

**Comment by rickmanelius** [comment]
I can confirm this is now in the latest drud/nginx-php-fpm-local:v1.1.0 used in master.
