### ISSUE TITLE
Add cobra command suggestions to command-line parsing

### ISSUE THREAD

**Issue by beeradb** [drud/ddev#496]
## What happened (or feature request):
When doing commands for ddev we initially decided to stay away from the command alias features that [cobra](https://github.com/spf13/cobra) provides due to not wanting to confuse people with multiple aliases for each command. This was done in an effort to keep things simple, and not end up with a bunch of aliases which people would get used to and we'd have to support ad-infinitum. 

## What you expected to happen:
I just came across the [cobra feature for suggestions](https://github.com/spf13/cobra#suggestions-when-unknown-command-happens), which is similar to aliases but merely provides a command suggestion if you use it. We should consider implementing this as we could still give command hints for similar terms (delete, rm, remove, etc.) but push people to use the canonical command, rather than supporting multiple versions of the same command.

**Comment by rfay** [comment]
Cobra automatically provides suggestions, so we've had this for a long time.
