### ISSUE TITLE
Add support for install profiles

### ISSUE THREAD

**Issue by bdlangton** [drud/ddev#5]
For local Drupal development, sometimes we have a site that we want to install brand new every time we build it. Currently, `drud dev add ...` is limited to always pulling down an archive and using that site with the accompanying database. I would like the option to be able to `add` a site and specify that it should be built from the install profile instead. Typically, we have done this with a `new_site: true` flag in the databag. I don't think drud even looks at our databags for a build, but perhaps another option is to add a flag to the `add` command that tells drud to ignore the archived database and build from an install profile. Maybe something like `drud dev add client staging --install-profile=client_profile`.

**Comment by rickmanelius** [comment]
Hi @bdlangton. Sorry for the massively long response time. In addition to the previously mentioned option of appending a `ddev exec` after a `ddev start` to essentially wrap drush, there is another alternative that we are pursuing to balance ddev being agnostic while supporting CMS specific functionality. See this issue [Create Strategy for Pre/Post Hook Functionality](https://github.com/drud/ddev/issues/183). Once issue #183 is addressed, this specific functionality could be one of the first use cases.

At the moment, [here is the published roadmap](https://github.com/drud/ddev/wiki/roadmap) and [here is the progress we've made on the various milestones](https://github.com/drud/ddev/milestones).

**Comment by rickmanelius** [comment]
A long-standing issue, but this is now doable through the post-hooks (https://ddev.readthedocs.io/en/latest/users/extending-commands/). On `ddev rm` one could force a database remove and on `ddev start` one could follow-up with the exact parameters passed in through a drush site install. If you'd like, I can put together a demo set and then we can see if that allows us to close this out.

**Comment by rfay** [comment]
There are many ways to accomplish things in ddev, and I think we've pointed out some of them. I'm going to close this because it's been a year without followup or interest from others. Feel free to reopen!
