### ISSUE TITLE
Generated settings.php needs 'sync' key in drupal8

### ISSUE THREAD

**Issue by rfay** [drud/ddev#504]
## What happened (or feature request):

Drupal 8 insists on a `sync` key, to a writeable directory, in settings.php. We should add that. 

* For extra credit, add the "Trusted Hosts" directive to avoid that complaint from D8

![status_report___rfay-drupal8](https://user-images.githubusercontent.com/112444/31462498-32c32590-ae8a-11e7-937d-835fd31bd85a.png)

**Comment by rickmanelius** [comment]
Potentially related to  https://github.com/drud/ddev/issues/463
