### ISSUE TITLE
Change homebrew binary to bintray link

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#508]
## What happened (or feature request):

Change request

## What you expected to happen:

As per our desire to get download statistics (https://github.com/drud/ddev/issues/307), we are generating and using links to Bintray. This requires two changes:

1. Update Bintray to include the latest binary whenever we tag a release.
2. Update our homebrew recipe to point to the Bintray location.

## Anything else do we need to know:

I need to get access to the Bintray account from @cyberswat. I just wanted to get this issue filed ahead of time so I can keep track of it.

**Comment by rickmanelius** [comment]
Bump @cyberswat only because I know we're trying to better track downloads during BADCamp:

1. Are the Bintray links pointing to the v0.9.3 binaries?
2. Can you paste the macOS link one here so we can point the homebrew to it?

**Comment by cyberswat** [comment]
v0.9.3 was not uploaded to bintray.  It is now. https://drud.bintray.com/ddev/

fwiw bintray is a terrible system and is only being used because it was the easiest to get started.

**Comment by rfay** [comment]
This has been done for v0.9.3 *homebrew* only. The links would need to be updated on the release for other systems if we want to track.

**Comment by cyberswat** [comment]
We have the essence of this request completed, but there are a few items we need to address moving forward.  I'm placing this list here, but expect most of this will be moved to another issue.

- Bintray leaves a large amount to be desired.  It is a poorly written Java based system that feels like something that came out of the early 1990s.  We need to determine if we are going to keep using it.  
- If we continue to use bintray we need to determine if the statistics being generated are useful and what we are looking for.
- SAML integration was set up with bintray but doesn't seem to be working.
- Bintray has a RESTful interface that we should use to manage assets from CircleCI.
- There is a disconnect between generating a release, uploading it to bintray, and updating the ddev.drud.com site to point to the correct downloads.  This will need to be resolved to support automation between CircleCI and Bintray.

**Comment by rickmanelius** [comment]
Looks like this was addressed here https://github.com/drud/homebrew-ddev/pull/5.
