### ISSUE TITLE
Antivirus "Cylance" kills ddev with panic on launch

### ISSUE THREAD

**Issue by rfay** [drud/ddev#513]
## What happened (or feature request):

Demo-ing ddev at BADCamp, first demo, ddev installed fine on MacOS Sierra using homebrew. 

But then when we launched ddev we got

```
$ ddev list

fatal error: runtime: bsdthread_register error



runtime stack:

runtime.throw(0x1672024, 0x21)

/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0x7fff5fbff690 sp=0x7fff5fbff670 pc=0x1029c55

runtime.goenvs()

/usr/local/go/src/runtime/os_darwin.go:108 +0x83 fp=0x7fff5fbff6c0 sp=0x7fff5fbff690 pc=0x10274f3

runtime.schedinit()

/usr/local/go/src/runtime/proc.go:482 +0xa1 fp=0x7fff5fbff700 sp=0x7fff5fbff6c0 pc=0x102c601

runtime.rt0_go(0x7fff5fbff738, 0x2, 0x7fff5fbff738, 0x0, 0x0, 0x2, 0x7fff5fbff908, 0x7fff5fbff90d, 0x0, 0x7fff5fbff912, ...)

/usr/local/go/src/runtime/asm_amd64.s:175 +0x1eb fp=0x7fff5fbff708 sp=0x7fff5fbff700 pc=0x10546fb
```

A quick web search indicates this may have been the antivirus program [cylance](https://www.cylance.com/en_us/home.html) killing off potentially all golang binaries. There are a number of golang issues with similar stack traces, https://github.com/golang/go/issues/18171

It's likely we don't have any recourse with this, also possible that Cylance has corrected this behavior now. 

I *have not* yet confirmed that Cylance was installed on this user's laptop, the analysis here is based on web search.

**Comment by rfay** [comment]
I was able to talk with her yesterday, and in fact, she has Cylance on her enterprise-managed machine. 

I don't believe there's any action we can or should take on this Cylance bug.

**Comment by rickmanelius** [comment]
Agreed. Closing out and we can reopen if this becomes an ongoing problem.
