### ISSUE TITLE
Consider supporting *.mysql file type for import-db

### ISSUE THREAD

**Issue by rfay** [drud/ddev#516]
## What happened (or feature request):

Rick noted with a ddev demo that an import of a backup-migrate module backup failed.  For example, `ddev import-db --src=APLVDatabaseBackup-2017-10-23T06-30-32.mysql.gz`:

```
Failed to import database for aplv: no .sql files found to import
```
The issue here is that backup-migrate uses the very nonstandard "*.mysql" file type inside the gzip file, and ddev recognizes only the more-likely "*.sql" filetype.

backup-migrate has gzip files like `APLVDatabaseBackup-2017-10-23T06-30-32.mysql.gz` containing a file like `APLVDatabaseBackup-2017-10-23T06-30-32.mysql`. If you gunzip and give the .mysql file to ddev import-db, it imports just fine. 

It shouldn't be hard to expand our vision to looking for *.mysql as equivalent to *.sql

**Comment by rickmanelius** [comment]
We can re-open if anyone else trips up on this.

**Comment by nigelwhite** [comment]
As a frequent user of backup_migrate for its one-click downloads of remote databases (and I can't be the only one) this would be a big help.

**Comment by rfay** [comment]
Please open a new issue with your request, thanks!

**Comment by nigelwhite** [comment]
Done https://github.com/drud/ddev/issues/1483
