### ISSUE TITLE
Settings.php: Remove automatic creation and make it a separate ddev command

### ISSUE THREAD

**Issue by rfay** [drud/ddev#517]
## What happened (or feature request):

We have loads of problems with settings.php (and wp-config.php). 
1. It may be checked in
2. The user may want to generate it through a site install
3. The user may prefer a settings.local.php approach

Bottom line is that we may not be able to create a settings.php at all, and it's probably something that belongs in the user's workflow. 

@tannerjfco suggested adding a separate command that would write a ddev-specific settings.php, which would make this a more manual step, which could be customized by the user for their needs. So, for example, the final step of import-db could be to *tell them* they could now issue `ddev write-settings` or something, rather than doing it for them. It could also direct them to docs about what they are up to.

Related issues:
* [User docs and settings support #468](https://github.com/drud/ddev/issues/468)
* [import-db false failure with managed settings.php #451](https://github.com/drud/ddev/issues/451)
* [Warning if settings.local.php not included #407](https://github.com/drud/ddev/issues/407)
* [ Standardize our approach on db config files #394](https://github.com/drud/ddev/issues/394)
* [Running ddev start should create settings.php #346](https://github.com/drud/ddev/issues/346)

**Comment by rickmanelius** [comment]
As part of our decision around Semver and what we wish to support moving forward along our next major release, we need to get to a decision on this important topic. See roadmap https://github.com/drud/ddev/wiki/roadmap#v100-official-release--semantic-versioning-commitment

**Comment by rfay** [comment]
Closing in favor of https://github.com/drud/ddev/pull/693, which will do the settings creation at config time.
