### ISSUE TITLE
Consider replacing inline stdin prompting with a package

### ISSUE THREAD

**Issue by rfay** [drud/ddev#523]
## What happened (or feature request):

Ddev has a few interactive prompts (config, pantheon config, import-db, import-files) which are done as inline stdout prompt with stdin receipt. It's a fairly crude approach, and no prompting library is used. We should consider replacing the prompting with a more sophisticated prompt library, even one of our own. However, @beeradb points out [survey](https://github.com/AlecAivazis/survey) and [go-prompt](https://github.com/segmentio/go-prompt), which might be very useful.

**Comment by beeradb** [comment]
https://github.com/AlecAivazis/survey would be an option as well.

**Comment by rickmanelius** [comment]
Not sure if this is still relevant. Tagging hibernate.

**Comment by rfay** [comment]
survey didn't work out, not cross-platform enough. But mostly we're now using util.Prompt() and such, so closing.
