### ISSUE TITLE
readthedocs search is broken

### ISSUE THREAD

**Issue by rfay** [drud/ddev#528]
## What happened (or feature request):

I don't think search on ddev.readthedocs.io works at all at this time. Searching for anything in the search box returns no results. For example, a search for [ddev](https://readthedocs.org/search/?q=ddev&check_keywords=yes&area=default&project=ddev&version=latest&type=file) returns no results. 

![search__ddev___read_the_docs](https://user-images.githubusercontent.com/112444/32345558-29a8e970-bfd0-11e7-9136-33bddb29e2b9.png)

**Comment by rfay** [comment]
After #530 search seems to be broken still, sadly. But maybe it takes time.

**Comment by tannerjfco** [comment]
This is resolved now in #531 with an updated workaround.
