### ISSUE TITLE
Use local site domain names that have a TLD of .local

### ISSUE THREAD

**Issue by rfay** [drud/ddev#54]
## What happened (or feature request):

We are currently using bare hostnames for our site URLs, for example "local-drud-d7-production". These pack a bunch of information in, but 1) It's not easy to sort out what each part means necessarily and 2) It makes it difficult to take specific actions based on the TLD. For example, a TLD of '.local' or '.ddev' might give more context about what's going on.

## What you expected to happen:

I expect a URL/hostname that implies more about where it comes from (and perhaps is easier to parse).

## Proposal:

Just use ".local" as the TLD for all ddev sites. It's not an official [reserved tld](https://tools.ietf.org/html/rfc2606) but it doesn't do any harm and people will accept it. Using .local instead of .ddev insulates us from possible product name shifts and the like.

So when we remove the environment concept, this would just be `<sitename>.local`, like `mycrazysite.local`.

**Comment by rickmanelius** [comment]
While this is marked as a dupe, it's worth revisiting based on the TLD information surfaced here https://github.com/drud/ddev/issues/232#issuecomment-330221687.

**Comment by rickmanelius** [comment]
The valid TLD will be addressed as part of this item https://github.com/drud/ddev/issues/416. I believe this will resolve the issues surfaced here and we can close this out. Please re-open if you don't agree, @rfay!
