### ISSUE TITLE
META: Project Upgrade Path Strategy

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#541]
Edited:
We occasionally make changes that break a given project/site. For example, when adding php_version to config.yaml and docker-compose.yml we orphaned existing projects, so they can't use those features without removing and regenerating docker-compose.yml.

We need to take ownership of docker-compose.yml, and update it on occasion. We can update the docs to say people shouldn't touch it and we can mark it as our own with a signature/hash, and add some various info.

**Comment by rickmanelius** [comment]
Hit a snag on the recent PHP version feature. Received this during a `ddev start` => "The DDEV_PHP_VERSION variable is not set. Defaulting to a blank string." This is just an example of things we need to be aware of and address.

**Comment by rfay** [comment]
Yeah, that's a result of having an established site with new ddev. If you remove .ddev that won't happen. I don't know of a way around that since we don't overwrite docker-compose.yml. I *think* a `ddev config` would rewrite the existing .ddev/config.yaml and make that statement go away, but the php_version still won't work because the docker-compose.yml isn't listening.

**Comment by rickmanelius** [comment]
All good. Just placing here as a datapoint of things to consider if we support upgrade paths between minor releases and what those instructions might look like.

**Comment by rfay** [comment]
It's an interesting point; we have this basic problem any time a site is configured and we upgrade ddev, because the default .ddev contents do not get touched. We may want to consider a method of upgrading docker-compose.yml and config.yaml on ddev upgrade in order to deal with it. It's all tied in with the who-owns-docker-compose issue as well.

**Comment by rickmanelius** [comment]
Related to the conversation thus far #343 

Note there are other issues as well.

**Comment by rickmanelius** [comment]
[Here's another consideration](https://github.com/drud/ddev-ui/issues/17#issuecomment-355595101) pulled from the ddev-ui repo, specifically to consider using a --remove-yml or a --remove-ddev flag as part of `ddev remove`. This could have a few benefits. The first is that it could address any clean-up with respect to starting from scratch before ddev (removing any global ~/.ddev/project folders, the local .ddev/ folder, and any database files). This may require its own issue and it may be better from a scoping perspective for people wanting/needing to do this to address on the command line. However, I can imagine a situation related to upgrade paths where we may wish to clear out existing config and re-run ddev config to generate updated config.yml and docker-compose.yml files.

Just a thought. It needs more fleshing out in conjunction with other decisions on how we manage / who manages these files.

**Comment by rickmanelius** [comment]
This has been discussed a few time, but a common fix when end-users encounter a bug/issue is to delete the .ddev folder and generate a new configuration. A while ago we included the "APIVersion" key in config.yml with the intention of using that as a way of tracking which version of DDEV was used to generate it. I suggest we modify this label to "ddev_version" and note the version of DDEV at the time of generation (this includes non-stable releases). In this manner, when the version number of DDEV is greater than the version within the config file, we should append to the output a prominent message to upgrade or recreate. Bonus points if we link to the latest release notes if there are any special instructions, like we did for the MariaDB container change https://github.com/drud/ddev/releases/tag/v0.13.1.

If we wanted to get really fancy, we could prompt them with a yes/no to do that, but this might break things and we could always add that in as a later feature.

Minimally, we want end-users to always update to the latest version and not feel hesitant to upgrade because of these small gotchas.

**Comment by rickmanelius** [comment]
I need to bump this for myself. It continues to be a UX/DX trip up and now that our userbase is growing it will help with support questions.

**Comment by rfay** [comment]
Please close this if you think it's done @rickmanelius ; otherwise let's spin it off into specific issues you think are remaining.

**Comment by rickmanelius** [comment]
The config.yml and docker-compose.yml changes have made this significantly easier. However, there are still areas that could be focused on as it pertains to break changes and whether or not we can provide a means around them beyond just informing our users within the release notes.

I'm fine with closing for now, but I imagine we will be revisiting this down the road.
