### ISSUE TITLE
Edge case. Running "ddev config" can detect D7 in a D8 repo

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#545]
## What happened (or feature request):

* Download D8
* Run `ddev config`
* Mistakenly answer "core" as "docroot" instead of "./"
* The app type is detected as Drupal7

## What you expected to happen:

No app detection instead of a false positive for Drupal 7.

## Acceptance Criteria

* [ ] Entry in the ddev documentation that specifies apptype is now a suggestion versus a detection.
* [ ] Entry in the ddev documentation that notes that the php apptype is a generic fallback that will be used if a supported CMS is not detected (regardless of this is caused by user error OR it's simply not a folder strucutre containing a supported CMS).

**Comment by rfay** [comment]
This will have changed now to detecting php. However, I don't know any way around it (except more automatic docroot detection). We're not going to detect the right thing in the wrong place.

I'd say we should either repurpose this and plan for more robust docroot detection, or else close this one.

**Comment by rickmanelius** [comment]
Fair enough. I'll consider this done when we note that apptype is now a suggestion and that we have PHP as our generic fallback!

**Comment by rickmanelius** [comment]
Issue acceptence criteria updated and milestone tagged for v1.2.0.

**Comment by mglaman** [comment]
Here's my PHP toolstack identifier library https://github.com/mglaman/toolstack-helper/tree/develop/src/Stacks

One check is to see if it is a built or not Drupal site, from the days of yore with Drush make.

But the real identifier is

```
return (file_exists($dir . '/core/composer.json')) ? self::DRUPAL8 : self::DRUPAL7;
```

**Comment by rfay** [comment]
This issue is outdated and we have much better detection now. However, with a bogus docroot, "php" would be detected, and I think that's correct behavior. 

I'm going to close this in favor of the real better alternative, [almost always detecting and suggesting the right docroot](https://github.com/drud/ddev/issues/663)

**Comment by rfay** [comment]
Reopening so we at least get to see @mglaman's PR for this!

**Comment by rfay** [comment]
Closing again. @mglaman's https://github.com/drud/ddev/pull/678 is going to be great for this, and a very adequate solution.
