### ISSUE TITLE
Feature Request: implement `ddev list --continuous` to eliminate UI polling

### ISSUE THREAD

**Issue by andrew-c-tran** [drud/ddev#552]
## Feature Request:
implement `ddev list --continuous` that instead of exiting, the process will remain alive and will broadcast the current sites list when initially run, then will rebroadcast a new, complete site list whenever there has been a change to any site to stdout.

## Anything else do we need to know:
currently, we are polling `ddev list -j` every 1000ms, parsing the JSON output, then comparing it to the current sitelist in the UI. If a difference is found, then the UI is updated accordingly. If the CLI would simply return an entire updated sitelist JSON whenever it detects a change, we can eliminate polling from the UI, as well as removing the "ignore ddev list polling spam" bandaid that we had implemented in logging. 

## Please use a complexity rating of 1-5 (5 is high) for a feature request. (High complexity implies more PR planning)
2 (from Randy): This should mean just putting the list functionality in an infinite loop, but exiting after one run if --continuous is not set.

**Comment by rfay** [comment]
@rickmanelius would love to lobby you on this. It should simplify ddev-ui and make it lighter-weight.

**Comment by rickmanelius** [comment]
@rfay @andrew-c-tran I'm all good on this but wouldn't the "infinite loop" be even more process intensive when it's on or would be you still anticipate putting a time delay/spacer of ~ 100-1000ms?

**Comment by cweagans** [comment]
+1 for a 1000ms delay in the loop somewhere. I don't think there's not a lot of point in asking the Docker daemon for new data much faster than that anyway.

**Comment by rfay** [comment]
Yes, it's an infinite loop, but it has a configurable pause that suits ddev-ui.

**Comment by cweagans** [comment]
> Yes, it's an infinite loop, but it has a configurable pause that suits ddev-ui.

@rfay how set are you on the loop pause being configurable? It's not a huge deal, but I think we should just pick a sane value and hardcode it. 1000ms will output changes often enough that the UI will be updated by the time the user switches windows to ddev ui.

**Comment by rfay** [comment]
I would say just make it an extra argument --loop-delay=xxxms ? So maybe the arg could be --loop ? Default the delay to 1000ms?

**Comment by rickmanelius** [comment]
@cweagans It appears this is in progress but labels were not added and I'm not sure we got to an AC on whether or not the --loop-delay was worth putting in. FWIW since the only thing using this is ddev-ui and since the end-user testing seems to indicate it's a working amount, I don't know when changing that value would ever happen unless it was a preference in ddev-ui. Unless/until that is a request, I say we punt on making that configurable at this time.

**Comment by cweagans** [comment]
PR is ready for review!

**Comment by rickmanelius** [comment]
@cweagans It looks like the PR was merged. Any issue with closing this out?

**Comment by cweagans** [comment]
Nope!
