### ISSUE TITLE
Split mailhog out of the web container and run one instance globally

### ISSUE THREAD

**Issue by cweagans** [drud/ddev#557]
## What happened (or feature request):

Mailhog isn't specific to any particular application. I think we can still fulfill the requirement of having mailhog and using it for outbound mail in a dev environment, but only spin up one instance of it.

This would involve running mailhog in a similar way as the router container, and then configuring web containers to route mail messages to the separate mailhog container (potentially via https://github.com/mailhog/mhsendmail)?

**Comment by rickmanelius** [comment]
I think this might need to fit within a more global architectural decision/choice of how many global containers to pursue. What about phpmyadmin? ssh-agent (#414), etc.

**Comment by beeradb** [comment]
One consideration here would be the (presumed) increased memory footprint. We already have some issues w/ the default docker memory limit once you get over 2-3 deployed sites.

**Comment by cweagans** [comment]
@rickmanelius Probably, yes. I'm in favor of not running duplicated instances of things if we can get away with just running one. phpmyadmin might be nice to split off as well, especially if we can use some kind of [docker-gen](https://github.com/jwilder/docker-gen)-esque method of generating phpmyadmin config files. This way, you'd have one phpmyadmin instance that has access to all of your site databases. Where is the appropriate place to reach a decision on this?

@beeradb I think this would actually _decrease_ memory consumption. Rather than having one mailhog instance per site, we'd just have one instance globally. This should decrease memory consumption by `(x - 1) * number_of_sites`, where `x` is the amount of memory mailhog consumes.

**Comment by rickmanelius** [comment]
FWIW, I'm not arguing for or against this strategy at this time. In theory, I'm in favor but the only reason I commented and tagged with "needs decision" is that it will both impact technical implementation globally as well as have some impact on the end-user. Otherwise, this would be a quicker yay/nay.

**Comment by rfay** [comment]
As a developer, I wouldn't want to have emails from all sites thrown into one web UI. It's uncommon that I would work on mail issues on two sites at the same time, but OTOH I could get very confused by seeing mixed stuff from more than one site. That's my only significant objection. That and it works as it is.

**Comment by rickmanelius** [comment]
I think there is merit to this approach. However, from the perspective of end-user value the only two real gains are 1) reduction in memory footprint and 2) the possibility of having a single url to track all captured mail. To that end, I don't see this as a significant enough gain (yet) until we're getting reports from end users attempting to push the limits of their system memory and needing to find these types of optimizations. Tagging hibernate for now.

**Comment by rfay** [comment]
Nothing is pushing us to do anything with this at this point, so closing it until something does.
