### ISSUE TITLE
Support multiple drush versions for users

### ISSUE THREAD

**Issue by rfay** [drud/ddev#559]
## What happened (or feature request):

There are a number of situations where our users may want to select the drush version they use. This is one of our key problems with backdrop as well, because you need to be explicit about drush version. 

https://backdropcms.org/news/dealing-drush gives a backdrop strategy for multiple drush versions that will probably work for us in general. Basically, installing drush6/7/8/9 as named drush versions, like /usr/local/bin/drush6, /usr/local/bin/drush7, etc. 

We'll probably want to provide a default drush as well.

## Related source links or issues:

Related: https://github.com/drud/ddev/issues/515 on backdrop with drush considerations.

## Please use a complexity rating of 1-5 (5 is high) for a feature request. (High complexity implies more PR planning)

Complexity 2

**Comment by rfay** [comment]
This all *seems* to work fine when there's both a global and a local, it starts with the global and actually uses the site installed drush, which appears to work out ok.

**Comment by cweagans** [comment]
Drush 8 and below will work fine with a global installation. Drush 9 will not. I'm saying that while we can support multiple Drush versions for the time being, we'll need to re-evaluate our strategy as new versions of Drush are released due to upstream changes (maybe we just stop adding Drush itself to the container after Drush 8, and rely on users to do site-local installs?).

**Comment by rickmanelius** [comment]
Related https://github.com/drud/ddev/issues/463

**Comment by tannerjfco** [comment]
The challenge is that, at least to my understanding, site-local installs are only supported for D8 and later. I think we still need a global drush installation to support pre-D8 releases. I wouldn't be surprised if Backdrop needs similar support.

**Comment by cweagans** [comment]
If you're using composer for D7, site local is supported and encouraged, AFAIK. I know for sure that they at least _work_. Either way, we're going to eventually have to decide how to square this circle in a way that works for all users. In the short term, that will mean not adding Drush 9.x as an option.

**Comment by rickmanelius** [comment]
Minimally this needs an answer by the time we move officially on #571 (backdrop support) in milestone v1.2.

**Comment by rickmanelius** [comment]
Needs to be surfaced for future/additional Backdrop support.

**Comment by rfay** [comment]
Until we're forced to move to drush 9 we don't need to take any action AFAICT. Right now (and always) we've had drush 8. That works with backdrop. There's really no action to take here, so I'm closing this. Feel free to reopen.
