### ISSUE TITLE
Additional Improvements to File System Performance

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#564]
## What happened (or feature request):

Despite a bit of attention on Drupal 8 performance to date, there is still room for improvement while waiting for the Docker for Mac team to address these issues at a more fundamental level. To that end, there is interest in taking another pass at this to ensure we have an acceptable level of performance for CMS's with high demands on file read/write performance, such as Drupal 8 and TYPO3.

**Comment by rickmanelius** [comment]
Surfacing a potential trail to follow provided ty @cweagans https://hub.docker.com/r/cweagans/bg-sync/.

**Comment by cweagans** [comment]
I've got some old benchmarks that I dug up. I'll clean them up and put them on the bg-sync wiki tomorrow. They're likely somewhat out of date at this point, but should be a good starting point.

**Comment by rfay** [comment]
Closing this as too vague, without a path forward.
