### ISSUE TITLE
Consider using bonjour to advertise sites hosted by ddev

### ISSUE THREAD

**Issue by cweagans** [drud/ddev#565]
## What happened (or feature request):

This would sidestep the `hosts` file editing, and also not require fiddling with DNS setups on users' machines. Avahi/Zeroconf/Bonjour would allow us to advertise the presence of sites hosted by ddev and allow users to connect to them with "sitename.local"

We did something similar for Aegir a while back: https://github.com/GetValkyrie/provision_avahi (publish.py is the file to look at there).

**Comment by rickmanelius** [comment]
@cweagans supported on Windows and Linux as well?

**Comment by cweagans** [comment]
I believe so. I know for sure it works on Linux. Can't say for sure on Windows

**Comment by rickmanelius** [comment]
Cool. Ultimately, we want to make sure we're supporting all 3 OSes equally and we don't want to necessarily maintain separate, OS-specific solutions for a given feature unless the gains outweigh the additional costs. This is certainly a problem that we've been wanting to address for a long time, notably to reduce a potential security risk. Therefore, I anticipate that we'll be evaluating our options sooner than later and I'll add this to the mix. Thanks!

**Comment by beeradb** [comment]
ngrok has been suggested many times for this sort of functionality as well - https://ngrok.com/

**Comment by rfay** [comment]
IMO this is too much of a Mac-specific approach; to date we're trying to avoid any OS-specific approaches, so closing this for now.
