### ISSUE TITLE
Drush based Drupal 8 install breaks on Linux

### ISSUE THREAD

**Issue by nerdstein** [drud/ddev#567]
## What happened (or feature request):

Drupal themes will not load by default when running a command line Drush install on Linux

## What you expected to happen:

A nice shiny baby Drupal to show up

## How to reproduce this:
1. drush dl drupal
1. cd drupal-8.4.3
1. composer install
1. ddev config
1. ddev start
1. ddev exec drush si standard --account-name=admin --account-pass=admin --db-url=mysql://db:db@db/db
1. Load Drupal from a browser

The theme does not load and it throws an error about not being able to write a temp dir.

This is fixed by opening up the file permissions on sites/default
 

## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.

0.9.3

## Anything else do we need to know:

Reproduced on Ubuntu, likely caused by root password prompt, which sets sites/default ownership to root when it needs to be www-data

## Related source links or issues:

https://github.com/drud/ddev/issues/131

## Please use a complexity rating of 1-5 (5 is high) for a feature request. (High complexity implies more PR planning)

3, theres a fix by changing the permissions but doesnt work OOTB on install

**Comment by rfay** [comment]
Thanks so much for this. On our hosting platform container we were able to solve this more effectively, so we'll be able to transplant that approach over here, probably have the user execute commands as the nginx/www-data user.

**Comment by nerdstein** [comment]
Manually? It would be nice if ddev could automate this

**Comment by rfay** [comment]
No, the container needs to be set up so that when you `ddev exec` you're not using the root user, but instead an appropriate user that www-data will be then able to manipulate files (like sites/default and sites/default/files)

**Comment by rfay** [comment]
This was resolved in [v0.16.0](https://github.com/drud/ddev/releases/tag/v0.16.0) - Containers now run as the appropriate user on Linux.
