### ISSUE TITLE
Improve json output from "ddev version -j"

### ISSUE THREAD

**Issue by rfay** [drud/ddev#568]
## What happened (or feature request):

The json output of `ddev version -j` is not parseable, it's just the user-destined text.

To fix it, we can just

1. Create a `versionmap map[string]string` (I think that's the easiest thing) with each of the elements in it.
2. Populate each item we want in the map (all the version info)
3.  change https://github.com/drud/ddev/blob/master/cmd/ddev/cmd/version.go#L25 to `output.UserOut.WithField("raw", versionmap).Println(out)`

Test with `ddev version -j` and the 'raw' element should come out with parseable info.

**Comment by cweagans** [comment]
PR is open.

**Comment by cweagans** [comment]
PR is merged.
