### ISSUE TITLE
Officially Support Backdrop CMS

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#571]
## What happened (or feature request):

* Feature Request tied to [v1.2.0](https://github.com/drud/ddev/wiki/roadmap#120-cms-support) of the roadmap.

## What you expected to happen:

We've tested and [manually stood up a Backdrop site](https://github.com/drud/ddev/issues/515) to get a sense of what would be necessary to make it a supported, 1st class citizen alongside WordPress and Drupal 7/8. Once we [refactor how we handle CMS specific logic](https://github.com/drud/ddev/issues/535), we will be using that as a way to officially support TYPO3.

More details and acceptance criteria to follow once we get within 2 sprints of starting this issue.

**Comment by rickmanelius** [comment]
Moving this out of v0.12.0 and we'll target merging in the next release.

**Comment by cweagans** [comment]
PR was merged!
