### ISSUE TITLE
JSON output under-reports severity of docker failure

### ISSUE THREAD

**Issue by andrew-c-tran** [drud/ddev#573]
## What happened (or feature request):
When encountering a docker error on connection timeout, the docker error message is passed as a message, but the severity level of the cli output json object is listed as "info". Sample error message:

```
{
    "level": "info",
    "msg": "ERROR: for db  Cannot start service db: connection error: desc = \"transport: dial unix:///var/run/docker/containerd/docker-containerd.sock: timeout\": unknown",
    "time": "2017-12-13T11:31:12-07:00"
}
```

## What you expected to happen:
For a docker failure of this level, the severity should be higher than "info"

## How to reproduce this:
exact steps unknown, docker is currently in a broken state.

## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.
DDEV Version: V0.10.0
Docker Version: 17.11.0-ce

## Please use a complexity rating of 1-5 (5 is high) for a feature request. (High complexity implies more PR planning)
Unknown

**Comment by rickmanelius** [comment]
@andrew-c-tran What you suggest? Repeating is as "error"? Additionally, what are all the possibilities from docker's side?

**Comment by rfay** [comment]
Hibernating, as not relevant until ddev-ui work proceeds.

**Comment by rfay** [comment]
I'm pretty sure this is valid, so will reopen and leave hibernated.

**Comment by rfay** [comment]
Closing as outdated
