### ISSUE TITLE
Use Circle CI for macOS testing

### ISSUE THREAD

**Issue by cweagans** [drud/ddev#575]
## What happened (or feature request):

CircleCI now supports building in multiple environments from the same project (https://discuss.circleci.com/t/how-to-use-circleci-for-linux-xcode-in-one-project/693/6). We should consider migrating macOS testing to Circle and deprecate mac surf testing.

**Comment by rfay** [comment]
I certainly support this, it's apparently easy enough to do, just a bit of work to get the circle config working.

**Comment by cweagans** [comment]
Turns out that this still isn't going to work for us. Mac builds on Circle run inside a VM that doesn't support nested virtualization, which means we won't be able to run the Docker for Mac VM inside the Mac VM.

**Comment by rfay** [comment]
No certainty of course, but the technique in https://circleci.com/docs/2.0/building-docker-images/ *may* let us use docker on the macos (like 'machine') build machine.

**Comment by rfay** [comment]
I took a little visit with this and the setup_remote_docker will absolutely not work for us, it's only implemented for 'docker' type builds. 

The only remaining path to macOS-on-circleci for ddev with docker is to install docker for mac non-interactively, which I failed at last time I tried. And it may not work anyway, but worth one more effort.

**Comment by cweagans** [comment]
> install docker for mac non-interactively

`brew cask install docker` is how I do it on my machine. Not sure if it'll work on Circle though.

**Comment by rfay** [comment]
I wasn't able to get `brew cask install docker` do start up after install; I imagine this is just some magic I need to understand. `open /Applications/Docker.app` doesn't seem to work, probably because we're headless.

**Comment by rfay** [comment]
According to https://github.com/docker/for-mac/issues/717 docker has no intention of providing a way to install docker-for-mac without GUI user intervention.

**Comment by rfay** [comment]
I had some success with that, at least manually when ssh-ed into mac build on circleci.

sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended &
Wait for the startup to succeed (When we see "Analytics: Sent eventBackendStarted event.")
sudo chmod 777 /var/root/Library /var/root/Library/Containers
sudo chmod ugo+rw /var/run/docker.sock
docker ps

**Comment by rfay** [comment]
Requested info on the possible arguments over in https://github.com/docker/for-mac/issues/2359

**Comment by rfay** [comment]
Closing in favor of #639
