### ISSUE TITLE
Security implications of exec-host

### ISSUE THREAD

**Issue by andrew-c-tran** [drud/ddev#583]
## What happened (or feature request):
During security discussions of ddev-ui's privilege escalation, it was discussed that only allowing `ddev` prefixed commands to be sudo'd via the UI. This led to the conclusion that `ddev exec-host` could be similarly as disastrous (i.e. `ddev exec-host rm -rf /*`). While commands that ddev-ui uses can be very tightly controlled, the security/safety implications of exec-host needs to be addressed on a CLI level.

## What you expected to happen:
`ddev exec-host` should provide a level of safety in which an accidental command does not cause system-wide damage.

## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.
all

## Anything else do we need to know:
N/A

## Related source links or issues:
DDEV-UI Issue 14

## Please use a complexity rating of 1-5 (5 is high) for a feature request. (High complexity implies more PR planning)
Unknown

**Comment by rfay** [comment]
I never heard of ddev exec-host.  ? 

I definitely think we should only exec *ddev* with advanced privs, and only with a full path to known executable, and only one command that we need.

**Comment by rfay** [comment]
Yeah, I still don't understand this one so it's not going to be much use to assign it to me :)

**Comment by rickmanelius** [comment]
Adding back to my plate to get it to a clarified state :)

**Comment by tannerjfco** [comment]
I think I can help clarify this one a bit - I believe @andrew-c-tran is referring to the `exec-host` task supported for pre/post commands. There is not a `ddev exec-host` command to my knowledge, just the task for extending commands. http://ddev.readthedocs.io/en/latest/users/extending-commands/

The intent of providing this task is to allow users to define command they may need to run locally before or after a ddev command. For example, exec-host could be used to download an archive to be imported before ddev start runs. There are potential implications for a user misconfiguring and affecting their system, but the commands are not run w/ any escalated privilege, so they can only do as much damage as the user can do on their own.

**Comment by rfay** [comment]
There we go! I forgot that existed. That's important to think through. Although it would require the user to insert sudo there if they wanted to do real damage. Really worth thinking about critically though.

**Comment by rfay** [comment]
I'm pretty sure this can be closed. ddev does not have a command "exec-host" that could be executed by ddev-ui. 

It does have hooks for config.yaml, https://ddev.readthedocs.io/en/latest/users/extending-commands/#exec-host-execute-a-shell-command-on-your-system - and exec-host is one of them. However, they require a user to deliberately add these, and if the user uses sudo that's their choice (and crazy). 

I know of no reason at this point that ddev-ui would be interacting with this capability. 

Closing, feel free to reopen.
