### ISSUE TITLE
ddev list -j should/could return empty array (and router status) when no sites running

### ISSUE THREAD

**Issue by rfay** [drud/ddev#588]
## What happened (or feature request):

ddev-ui has to resort to backup techniques to handle the case where no sites are running. Instead it would be better if ddev gave it an empty array, perhaps with some context.

More discussion at https://github.com/drud/ddev-ui/pull/62#discussion_r158038523

**Comment by rickmanelius** [comment]
There is a referenced, merged PR on this issue. I also was able to confirm it's complete by shutting down all projects and then running `ddev list -j` with the following as output:

```
{
    "level": "info",
    "msg": "There are no running ddev applications.",
    "time": "2018-01-22T20:56:48-07:00"
}
```

I'm going to consider this closed, but feel free to re-open if there is more to do.

**Comment by rfay** [comment]
No, sorry, that isn't an empty array, it's an info-level statement.

**Comment by rickmanelius** [comment]
@rfay Understood. I just thought the "perhaps with some context" portion of your comment might indicate having some basic information would be ideal, but if you want a literal empty array, I agree that it's not done :)

**Comment by rfay** [comment]
Hibernated this, as it's not relevant until ddev-ui work proceeds.

**Comment by rfay** [comment]
This is a valid issue and I'd rather not lose it, so will leave it hibernated but open.
