### ISSUE TITLE
Determine how nginx configs could be configured per-site

### ISSUE THREAD

**Issue by tannerjfco** [drud/ddev#59]
## What happened (or feature request):
Feature Request

Currently, we provide a pre-configured site config for nginx in the container that largely works for drupal or wordpress sites. We do not provide a way that a user would be able to change an nginx configuration with any persistence.

## What you expected to happen:
There are a variety of reasons why an nginx configuration might need to change specifically for a site, so overall I believe we will need to expose a way to alter the nginx configurations for a site.

## Anything else do we need to know:
We do not yet have an understanding of what circumstances could require that the nginx configuration change for a site. There are a couple we do know about at least to some extent:

- For drupal, if the public files dir is a non-standard path (e.g. `sites/default/files`, then the rewrite rule supporting image styles needs to be updated.
- Wordpress similarly allows its uploads folder to be a configurable path. While we currently have no nginx rules related to this path, its possible there are considerations here we're not aware of.
- Various plugins or modules could require additional rewrite rules
- Sites sometimes need to define rules specific to their function

Based on those and other circumstances we hopefully uncover, we will need to define what level of customization is appropriate to provide, and what that implementation will look like.

## Related source links or issues:
The discussion surrounding #57 is where we identified this as something we will need to address eventually, but not in the scope of 0.1/0.2 milestones.

**Comment by rickmanelius** [comment]
Related to #195

**Comment by tannerjfco** [comment]
This relates to #189, and could potentially addressed with the same underlying solution.

**Comment by rickmanelius** [comment]
One alternative approach to consider. One of the tenets of Docker, as I understand it, is that of inheritance of containers. So we have two options:

* Have a default container configuration and allow ddev to override those through ddev's config.yml.
* Have a default container configuration and use an override Docker config.

Thoughts?

**Comment by tannerjfco** [comment]
This was addressed in #314 with ability to override nginx config with user-provided version in .ddev directory.
