### ISSUE TITLE
Homebrew install and docs should alert user to install docker-compose

### ISSUE THREAD

**Issue by budda** [drud/ddev#597]
## What happened (or feature request):

First-time install of ddev via brew and it would not work, and no instructions mention further steps required on https://github.com/drud/ddev/blob/master/README.md or http://ddev.readthedocs.io/en/latest/users/cli-usage/#drupal-8-quickstart (for example)

## What you expected to happen:

docker-compose to be installed as a required component of ddev system.

## How to reproduce this:

$ brew install ddev
$ ddev config
docker-compose does not appear to be installed.

## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.

$ ddev version
docker-compose does not appear to be installed.

## Anything else do we need to know:
No

## Related source links or issues:
No

## Please use a complexity rating of 1-5 (5 is high) for a feature request. (High complexity implies more PR planning)

1

**Comment by rfay** [comment]
I agree that this should be called out better. We actually just improved ddev (and installer) to *check* for docker-compose but didn't improve the docs. https://ddev.readthedocs.io/en/latest/#system-requirements mentions docker but not docker-compose. I assume you're on linux; on Windows and Mac docker-compose comes with docker.

**Comment by budda** [comment]
I was actually on MacOS - and had completely forgotten I didn't have Docker installed already.

Anyway, turns out my i7 CPU is too old (2009) for Docker use at home :(

**Comment by rfay** [comment]
Shucks! Thanks for the issue, it's a good pointer for us.
