### ISSUE TITLE
"ddev remove" does not remove database data

### ISSUE THREAD

**Issue by helhum** [drud/ddev#599]
## What happened:
Documentation [states](https://ddev.readthedocs.io/en/latest/users/cli-usage/#removing-a-site) that `ddev remove` is destructive and will remove database data.

However `ddev remove` and a subsequent `ddev start` will get me into a state with the same database data being present as before the remove.

## What you expected to happen:
As stated in the docs, I would expect the database to be fresh.

## How to reproduce this:
```
ddev config
ddev start
# create some db tables
ddev stop
ddev remove
ddev start
# tables still there
```

## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.

```
$ ddev version
cli:       	v0.11.0                                                                                                                             
web:       	drud/nginx-php-fpm-local:v0.9.0                                                                                                     
db:        	drud/mysql-local-57:v0.6.3                                                                                                          
dba:       	drud/phpmyadmin:v0.2.0                                                                                                              
router:    	drud/ddev-router:v0.5.0                                                                                                             
commit:    	v0.11.0                                                                                                                             
domain:    	ddev.local                                                                                                                          
build info:	Built Mon Jan 8 17:44:21 UTC 2018 circleci@prealloc-thzqktqj-e98cafb1-eaae-4090-9ae8-bbd7e80cb02d drud/golang-build-container:v0.5.0 
```

```
$ docker version
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:22:25 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

```yaml
APIVersion: "1"
name: test
type: php
docroot: public
php_version: "7.1"
webimage: drud/nginx-php-fpm-local:v0.9.0
dbimage: drud/mysql-local-57:v0.6.3
dbaimage: drud/phpmyadmin:v0.2.0
provider: default
```

## Anything else do we need to know:
Looking at docker-composer.yaml, the reason for that is pretty clear.
A volume is mounted for the mysql data dir, which is (for me) `~/.ddev/test/mysql`
Since this directory is not removed on `ddev remove`, database data will be present
on `ddev start`

## Related source links or issues:

https://ddev.readthedocs.io/en/latest/users/cli-usage/#removing-a-site

## Please use a complexity rating of 1-5 (5 is high) for a feature request. 

1

**Comment by rfay** [comment]
Thanks so much! I had that on my own agenda this weekend. The help has it right but the docs don't. We changed this many months ago and consider the change a big help (at least it helps me). I love being about to just start up one of my dev sites and have the database waiting already there for me. And of course I can kill it off with `ddev remove --remove-data` if I want it gone.

**Comment by helhum** [comment]
Ah, cool. Wasn't aware of `ddev remove --remove-data` as it was not mentioned in the docs.
Makes sense to allow users to decide whether they want to remove the data as well or only the built containers 👍 

Also thanks for the documentation update!

**Comment by rickmanelius** [comment]
@helhum. I believe this solves this issue but we'll keep this open until the documentation PR gets approved/merged. I also wanted to thank you for taking the time to provide so much detail in the issue summary! It's always nice to have more information than less.

**Comment by cweagans** [comment]
Personally, I'd prefer to have `ddev remove` actually clean up that data, with a flag that allows for keeping it (basically invert what we have now). It's really frustrating to have to do it manually if you're reinstalling Drupal a few times as I did when I was testing the D6 PR. This would also make ddev consistent with other tools (docker compose, vagrant, et al).

**Comment by rickmanelius** [comment]
@cweagans Probably worth highlighting that we've been itching to get a rename in place https://github.com/drud/ddev/issues/484 to address any confusion around semantics/expectations.
