### ISSUE TITLE
Determine how to support non-default drupal public/private files directories

### ISSUE THREAD

**Issue by tannerjfco** [drud/ddev#60]
## What happened (or feature request):
We currently assume that sites will use the standard public files path of sites/default/files when determining where imported files should go, and how nginx rewrite rules are configured to support imagestyles. 

## What you expected to happen:
We will need to provide a way to make public and private file paths configurable. Unfortunately these configurations are not trivial to change after a site has been in existence for some time, as this path gets stored in entries in the files table for d7, and could also be in any WYWIWYG-derived content.

## Related source links or issues (like source JIRA issue):
#57 is where we originally discussed this need, though it does not fit within the scope of that or the 0.1 milestone.
This also relates closely to #59

**Comment by rickmanelius** [comment]
Related https://github.com/drud/ddev/issues/59

**Comment by rickmanelius** [comment]
Leaving this in v0.8 because of the dependency in #293.

**Comment by rfay** [comment]
IMO this is easier (technically) than we might have been thinking. 
* We can easily mount any host-level directory onto any expected directory in the container, meaning that the directory will "just be there" where the code expects. This works perfectly for private files, which are not exposed to the webserver at all and thus require no configuration.
* The most common way of managing alternate directories for public files is the lowly symlink - that's true almost everywhere in production. So if the files are stored in /var/data, people use sudo ln -s /var/data ..../sites/default/files - We could easily create a symlink and a mount where needed.

**Comment by rickmanelius** [comment]
@rfay's last comment certainly describes how to solve the problem at a technical level. We would still need to address how a user implements this (when in the config process does this occur? how do they set/update it? etc). Need to think a little more before we have a path forward.

**Comment by rickmanelius** [comment]
We need to review if this is still worth pursuing... perhaps we can push post 1.0.

**Comment by rickmanelius** [comment]
It looks like we technically have an approach that can achieve this. See comment here https://github.com/drud/ddev/issues/293#issuecomment-307964866. I would argue that we should provide direction in our docs so that end-users looking to achieve this can connect the dots. And if there tends to be a lot of demand for this, we can re-evaluate whether we need a more robust approach.

**Comment by rickmanelius** [comment]
Converted to actionable. We will scope this to just documenting how to achieve this using custom nginx configs.

**Comment by rickmanelius** [comment]
This is related to CMS support, which we are prioritizing in v1.2.0 (or earlier).

**Comment by rfay** [comment]
*If* the various files directories are on the host mount with the code (which would often be the case), and *if* we drop the import-files explicit command, then the basic case here is pretty easy. 

OTOH when public files is in a strange place... I wouldn't be surprised if people don't just have to work with that, and they could add one of @tannerjfco's lovely post-import steps to update the db to point public and private files to a decent location. I'm pretty sure we're not going to solve this one entirely on our own, there's going to be a mixture of support from us and action from our customers.

**Comment by rfay** [comment]
Since this never seems to come up at all, and since files directories innately live on host anyway, and since nobody seems to use import-files anyway (except by extension Pantheon users), I'm going to close. We'll come back if it becomes an issue. But it's been quiet a really long time.
