### ISSUE TITLE
Editing config.yaml (or running ddev config) can really mess up running projects

### ISSUE THREAD

**Issue by rfay** [drud/ddev#601]
## What happened (or feature request):

@andrew-c-tran points out that we don't defend against changing the project name while a project is running. Very nasty things can happen.

His path to doing this is at https://gist.github.com/rfay/fda35e6186cb2899f4f31eb45957c432 but there are many ways to mess things up by changing project name, even when it's not running. The stored database is stored by project name, for example, so if you change the project name it's not necessarily obvious that you'll not have a stored database.

**Comment by rfay** [comment]
This is really a duplicate of #540

**Comment by rickmanelius** [comment]
The previously filed #540 has a bit more detail. Let's focus our effort there and close this one as the duplicate.
