### ISSUE TITLE
Upgrade of existing mysql db to mariadb 10.1 (ddev v0.12.0) not supported

### ISSUE THREAD

**Issue by rfay** [drud/ddev#615]
## What happened (or feature request):

This is an advisory issue for ddev v0.12.0, but if 

* An existing project has an existing database created with our old mysql-local-57 image
* The .ddev/config.yml is updated to refer to drud/mariadb-local:v0.7.x

then the mariadb server continually restarts. The user-visible result is that ddev complains:

`Failed to start typo3composer: db service container ddev-typo3composer-db: detected container restart; invalid configuration or container. consider using `docker logs 1e431fe37ecc1eda2bd272e6ad29b84ba1af8d36144ee7118ffa050f7d15fd9c` to debug`

The docker-visible result is

`1e431fe37ecc        drud/mariadb-local:v0.7.1         "/docker-entrypoint.…"   Less than a second ago   Restarting (1) 1 second ago                                                                                                   ddev-typo3composer-db`

The actual cause is an incompatibility of some type between the mysql database and mariadb database. It seems that mariadb 10.1 (which we're using in the drud/mariadb-local:v0.7.*) detects the mysql-5.7 database as a mariadb 10.2 db.

```
2018-01-23 17:21:06 140200324049800 [Note] InnoDB: Highest supported file format is Barracuda.
InnoDB: No valid checkpoint found.
InnoDB: A downgrade from MariaDB 10.2.2 or later is not supported.
InnoDB: If this error appears when you are creating an InnoDB database,
InnoDB: the problem may be that during an earlier attempt you managed
InnoDB: to create the InnoDB data files, but log file creation failed.
InnoDB: If that is the case, please refer to
InnoDB: http://dev.mysql.com/doc/refman/5.6/en/error-creating-innodb.html
2018-01-23 17:21:06 140200324049800 [ERROR] Plugin 'InnoDB' init function returned error.
2018-01-23 17:21:06 140200324049800 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2018-01-23 17:21:06 140200324049800 [Note] Plugin 'FEEDBACK' is disabled.
2018-01-23 17:21:06 140200324049800 [ERROR] Could not open mysql.plugin table. Some plugins may be not l
2018-01-23 17:21:06 140200324049800 [ERROR] Unknown/unsupported storage engine: InnoDB
2018-01-23 17:21:06 140200324049800 [ERROR] Aborting
```

The simple fix here is `ddev rm -R` followed by `ddev start` and if needed a `ddev import-db`. It's not the kind of seamless behavior we'd hope for.

**Comment by rickmanelius** [comment]
I've tagged this issue with the appropriate [v0.12.0](https://github.com/drud/ddev/milestone/22) milestone. Also, thanks for putting this information within the [v0.12.0 release notes](https://github.com/drud/ddev/releases/tag/v0.12.0). To that end, I think we've covered everything we can for this and we should consider this closed.

**Comment by rfay** [comment]
Yeah, I just wrote this because I wanted everybody doing support to know about it. It's not actually an issue. I'm surprised how little we've heard about it.
