### ISSUE TITLE
ddev v0.12.0 config command requires --apptype and shouldn't

### ISSUE THREAD

**Issue by rfay** [drud/ddev#616]
## What happened (or feature request):

Somewhere we made it so ddev v0.12.0 `ddev config --docroot=docroot` can't work because the apptype detection doesn't get to the right place at the right time. (It works with --apptype)

```
ddev config --docroot=.
You are reconfiguring the app at /Users/rfay/workspace/randyfay.
The existing configuration will be updated and replaced.
apptype must be one of drupal7, drupal8, wordpress, drupal6, typo3, php
```

This breaks ddev-ui, with configures sites expecting autodetect to do the job.

**Comment by rickmanelius** [comment]
Thanks for catching. Added labels and attached as a dependency to the v0.12.0 release.
