### ISSUE TITLE
vscode - mkdir: cannot create directory ‘/workspaces/d9simple’: Permission denied

### ISSUE THREAD

**Issue by jonesrussell** [drud/ddev#6187]
### Preliminary checklist

- [X] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [X] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [X] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [X] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
======== Please make sure that you have already looked at troubleshooting guide ========
Troubleshooting guide: https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/ 
Simple things to check:
* ddev poweroff
* Restart Docker Provider
* Reboot computer
* Temporarily disable VPN and firewall
Press any key to continue:

```
</details>

### Expected Behavior

When creating the vscode devcontainer /workspaces/d9simple should be created by "setup_test_project.sh"

### Actual Behavior

mkdir: cannot create directory ‘/workspaces/d9simple’: Permission denied

### Steps To Reproduce

1. In VSCode in WSL2
2. From a fresh repository
3. Dev Containers: Reopen in Container

### Anything else?

$ ls -al /workspaces
drwxr-xr-x  4 root      root      4096 May 15 16:21 .
drwxr-xr-x  1 root      root      4096 May 15 16:21 ..
drwxr-xr-x 23 codespace codespace 4096 May 15 15:54 ddev

**Comment by rfay** [comment]
The provided launch.json is just an example file. You'll want to edit it to point to a real project on your machine.

**Comment by stasadev** [comment]
It should be good to go in the today's release:

- #6194
