### ISSUE TITLE
Allow end-users to (optionally) submit error logs back to DRUD.

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#627]
## What happened (or feature request):

* Feature request

## What you expected to happen:

We've been wanting to have additional mechanisms to receive feedback from end-users in order to ensure that DDEV is providing value, is reliable, etc. We have a larger proposal https://github.com/drud/ddev/issues/307 that is a bit ambitious, and we decided to chunk it down into something more manageable as an initial rollout.

To that end, we decided to focus on error reporting (see comment here https://github.com/drud/ddev/issues/307#issuecomment-357811084) as the first step toward the broader vision of another layer of opt-in usage data collection.

## Working Acceptance Criteria:

* [ ] Provision a Sentry account https://sentry.io/for/go/
* [ ] Inventory all areas where we currently have error handling in place.
  * [ ] Note any deficiencies where we may wish to add as part of this initiative.
* [ ] If environment variable is set to TRUE/ALLOW, push to Sentry.
* [ ] If environment variable is not set, prompt user with question (default's to NO) with links to data usage policies and documentation.
* [ ] Provide instructions OR a ddev command where a user can reset their answer to this question/preference. Ideally, make this accessible via a json response for ddev-ui.
* [ ] Generate a weekly report within Sentry and have it post the the email list containing the DDEV product team.

## Related source links or issues:

* [Proposal: Gather (Optional/Opt-in) Usage Statistics to Inform Roadmap Decisions ](https://github.com/drud/ddev/issues/307)

## Please use a complexity rating of 1-5 (5 is high) for a feature request. (High complexity implies more PR planning)

4

**Comment by rfay** [comment]
This is being done in #307
