### ISSUE TITLE
Define Strategy for Container Management Spanning CMSs, Providers, etc.

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#629]
## What happened (or feature request):

* Feature request

## What you expected to happen:

See roadmap issue https://github.com/drud/ddev/issues/430. One open loop from the comments was the process of defining how flexible we would be in supporting containers across dimensions such as CMS and hosting provider.

**Comment by rickmanelius** [comment]
Here's an example where there is a Drupal 7/8 difference where having different default containers would be of value https://github.com/drud/ddev/issues/648.

**Comment by rfay** [comment]
I think this one is obsolete.
