### ISSUE TITLE
Make TYPO3 AdditionalConfiguration file compatible with TYPO3 >= 8.6

### ISSUE THREAD

**Issue by tmotyl** [drud/ddev#632]
## What happened (or feature request):
The config seen in https://github.com/drud/ddev/blob/master/pkg/ddevapp/typo3.go
 is valid for TYPO3 7.6 (old LTS). For v8.7 (current LTS) and version 9 (will become LTS end of this year), the config should be different:

```
$GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default'] = array_merge($GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default'], [
                    'dbname' => 'db',
                    'host' => 'db',
                    'password' => 'db',
                    'port' => '3306',
                    'user' => 'db',
]);
```

**Comment by tmotyl** [comment]
interesting, I will double check that, but according to the documentation it's like I said:
https://docs.typo3.org/typo3cms/extensions/core/8.7/Changelog/8.1/Breaking-75454-LocalConfigurationDBConfigStructureHasChanged.html

**Comment by rfay** [comment]
Yup, you're right. I somehow must have had an edited LocalConfiguration.php. We'll get this fixed. 

Good news for 9.x: when https://github.com/drud/ddev/pull/651 lands (hopefully today) we'll have php7.2 for TYPO3 9.x.

**Comment by tmotyl** [comment]
Great to hear!
