### ISSUE TITLE
ddev import-db - misleading error

### ISSUE THREAD

**Issue by tmotyl** [drud/ddev#633]
## What happened (or feature request):
I've created configuration file manually.
I've run command `ddev import-db --src=typo3.sql`
This command resulted in an red error like:
```
Failed to import database for typo3-core-master: failed to write settings file for typo3-core-master: Failed to get Typo3 AdditionalConfiguration.php file path: settings files already exist and are being managed by the user 
```
I've checked the DB and all data is in there, so the dump went through successfully. 
It's also quite surprising that ddev import-db is trying to create a config for me. I would expect that this happens when calling `ddev configure` or `ddev start`.

## What you expected to happen:
I would expect a success message, maybe with a warning that config file is managed manually.

## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.
ddev version
cli   	v0.12.0                        
web   	drud/nginx-php-fpm-local:v0.9.1
db    	drud/mariadb-local:v0.7.1      
dba   	drud/phpmyadmin:v0.2.0         
router	drud/ddev-router:v0.5.0        
commit	v0.12.0                        
domain	ddev.local

**Comment by rfay** [comment]
I'm quite sure this is a duplicate of https://github.com/drud/ddev/issues/451

**Comment by tmotyl** [comment]
Right, havent seen the other one. Lets close this one then.
