### ISSUE TITLE
missing php intl package (important for TYPO3 v9)

### ISSUE THREAD

**Issue by tmotyl** [drud/ddev#634]
## What happened (or feature request):
TYPO3 v9 requires php intl module to be present.

## Please use a complexity rating of 1-5 (5 is high) for a feature request. (High complexity implies more PR planning)

1

**Comment by rickmanelius** [comment]
@tmotyl Seems straightforward and I'll get it in this upcoming sprint before our next release of DDEV next Monday/Tuesday. Thanks!

BTW, are there any other notable differences in TYPO3 v9 that we should be aware of? We currently have detection to differentiate between Drupal 6, 7, and 8 but I'm not entirely sure if there are infrastructure level differences between TYPO3 v8 and v9 to warrant splitting them apart. Happy to split that off into its own ticket if you feel it's a larger discussion while we focus this on the specific request for the php intl package.

**Comment by tmotyl** [comment]
The other difference is that TYPO3 9 requires PHP 7.2 when 8.7 works starting from 7.0. There are no other difference in infrastructure requirements.
