### ISSUE TITLE
File permissions on linux host (folders not being writable from within docker)

### ISSUE THREAD

**Issue by tmotyl** [drud/ddev#635]
## What happened (or feature request):
Following documentation, especially http://ddev.readthedocs.io/en/latest/users/cli-usage/#typo3-quickstart 
TYPO3 failed to run because some subfolder of typo3temp was not writable from within docker.
After little googling I found : http://ddev.readthedocs.io/en/latest/users/linux_notes/
Changing permissions to make files and folders world writable in typo3temp fixed the issue, 

At later point I had similar issue - some CMS functions were failing because of the insufficient file permissions of the fileadmin and typo3conf folders.

## What you expected to happen:

I would expect that 
a) ideally, ddev would not require any fiddling with file permissions
b) if a) is not possible, then  setting file permissions should be documented in the quickstart guide
c) ddev should detect if folders have wrong permissions and warn the user about it.

**Comment by rfay** [comment]
Related: https://github.com/drud/ddev/issues/385

This is a hard issue to solve for all three platforms because of the differences in Docker's implementation of mounts. But agreed that it's an important one.

**Comment by tmotyl** [comment]
Maybe as a first step we can add the appropriate info to the quickstart guide?

**Comment by rickmanelius** [comment]
Hi @tmotyl. Thank you very much for catching this because, in our testing, I don't use TYPO3 enough from the day to day end-user perspective to catch these types of things. I think we take this in two steps as suggested. The first would be a few typical post-install instructions. The second would involve getting @rfay involved for the more robust solution. @rfay was instrumental in the security audits while we implemented all the file mounts across each OS and I would want his buy-in on a direction before we proceeded.

On a related note, Drupal has similar needs on the sites/default and sites/default/files directories that we could potentially mirror or enforce permissions at startup using os.Chmod() and target these specific directories.

@tmotyl I know you already inventoried the specific folders in the issue summary, but can you also share the permissions you needed to alter them to as well as the host OS you are using?

Tagging incubate until we have a specific plan of attack.

**Comment by tmotyl** [comment]
Hi
I'm using ubuntu 16.04. 
I can provide you a list of folders with default permissions (however permission mask for folders and files is configurable in TYPO3).
What you also need to know is that TYPO3 has and api checking whether folder structure is correct (you can call a "check and fix" button from the "install tool"). 
I'm pretty sure typo3console  project also provides a cli command fixing folder structure (however it's a 3rd party dependency).

The question is whether fixing the structure from within the container will be sufficient, or do we need to handle that outside the container?

**Comment by rfay** [comment]
Some issues:

* The container does not know where the files directory is, so probably can't do what is needed.
* Assuming that we solve the problem with permissions and not ownership, then it can be solved either inside the container or on the host, and it should work on all three platforms.
* ddev *does* know  where the files directory is based on apptype, and could set reasonable file write and directory setuid permissions as a post-start action. I'm not sure there's anything wrong with that. That seems like the most obvious path. Add a post-start action, and based on type do what needs to be done. This could act on permissions, no ownership. The only worry is that we'd be violating our contract with the user by altering things in their host filesystem without transparency. This problem of our obligation to the user deserves attention as we think about this.

**Comment by rickmanelius** [comment]
"I can provide you a list of folders with default permissions (however permission mask for folders and files is configurable in TYPO3)."

That seems like something that would be more appropriate to address that the hosting level where a user may need the ability (security implications aside) to further expand access control. However at the local dev level, I would assume there is a set of sane defaults that would meet the 99% use case. Then we could adopt an approach like @rfay mentioned and instruct users on how to specify pre/post start hooks to make changes that way. What might be most appropriate is rely on typo3console to make the permission changes from a `ddev exec-host` call. 

The biggest concern, as @rfay already noted, is not making host system modifications that could open an attack vector to the host machine.

**Comment by tmotyl** [comment]
one thing more - I've just checked and my user on the linux host has id 1000, and the docs states that chmod is required only if running user other then 1000
```
As a result, if you are not using the default Linux user 1000 and you need to create ....
``` 
http://ddev.readthedocs.io/en/latest/users/linux_notes/

**Comment by snpdev** [comment]
For any value it adds to the discussion...

- Windows 10 
- IMCE module
- Drupal 7
- Docker for Windows 18.03.0-ce-rc1-win54 (16164) edge

Upon browsing, the IMCE window displays:

```
Directory . is not accessible.
Unable to get a working directory for the file browser!
```
I see that it is not possible to  ```chmod -R 777 ./files```, after bashing into the host via  ```winpty ddev ssh```.

In Windows, Everyone group has CRUD permissions.

**Comment by rfay** [comment]
@snpdev that actually sounds like broken docker - not mounting the code. If you're in the *module* directory (or just in /var/www/html) that's what I see when docker is misbehaving and not mounting anything. Please try `ddev rm` and `ddev start`. You might want to try stopping and starting docker. Also, if you have a lot of projects running it can outrun docker's capabilities, so I make a habit of only having 2-3 projects going at a time with my 2GB (default) memory allottment in docker.

**Comment by snpdev** [comment]
@rfay I tried the steps you mention and even reinstalled Docker 4 Windows. The site runs fine, so the code is mounted. I just can't write to the ./files directory.

In the container, the permissions on the ./files directory are 755.

At the moment, I only have this one project running. Currently on Docker for Windows 17.12.0-ce-win47 (15139) stable.

**Comment by snpdev** [comment]
@rfay I just installed a fresh WordPress site and have no problem uploading to ```wp-content/uploads```. In the container I see that the file permissions are the same as for the Drupal 7 ```./files``` directory, i.e. 755. So I am scratching my head wondering, "why is Drupal 7 with IMCE giving me a hard time?" Later today I'll try a fresh install of Drupal 7 and see what happens. Perhaps I'll try CKFinder instead of IMCE. Time for lunch now. Cheers - Mike

**Comment by rfay** [comment]
Oh, ok, it wasn't clear that you were talking about the files directory, you were mentioning "IMCE module". I thought you were having trouble  seeing code in sites/all/modules/imce or something. Not sure what you were saying about that? What is the "IMCE window"?

I believe I can replicate your problem, but only on Docker edge. It looks to me like they may have changed the file mounting equation. We may have to change the container to adjust the users that Windows is allowing (which didn't seem to matter in the past). I think you also able to grant permissions on the files to anybody for anything on the *host* (Windows) side and have some success.

**Comment by snpdev** [comment]
@rfay [IMCE](https://www.drupal.org/project/imce) is an image/file uploader and browser. Figure 1 depicts the IMCE window and error. I apologize for assuming familiarity with this Drupal module.

**Figure 1**
![image](https://user-images.githubusercontent.com/1825479/37574122-e8946276-2af4-11e8-8078-0f54f18693b5.png)

**Comment by rfay** [comment]
Thanks! It has nothing to do with imce then - the same results would happen trying to upload a file to any node.  That's a much simpler test.

**Comment by snpdev** [comment]
@rfay, you are correct, the results are the same, but with the IMCE module the test is more comprehensive - we can also see that it is not possible to browse the _uploaded_ files. (Drupal 7, unlike WordPress, does not include media library utilities in core, so a module like IMCE is required.)

**Comment by rfay** [comment]
Working on this in #745 - it's definitely an issue for various users. Thanks for hanging with us on this. Hopefully we can get that all going. It's a little complicated, but the end result will be better several ways.
