### ISSUE TITLE
Support/test ddev on Windows 10 Home (Or with Docker Toolbox anywhere)

### ISSUE THREAD

**Issue by cweagans** [drud/ddev#636]
## What happened (or feature request):

One of the issues identified in the conversations about Drupal sprints is that there are some sprinters that come to sprints with Windows 10 Home. I think we should be able to support Docker Toolbox on Windows 10 Home. We could look at managing the Docker VM on behalf of the user as well, but that might not be necessary out of the gate - documentation is also a valid approach to solving that problem.

This might also be useful for Windows 10 Pro users who don't want to/can't enable HyperV for whatever reason (some enterprise Windows deployments lock down HyperV, but Virtualbox still works fine). This is very common on government laptops as well.

## Anything else do we need to know:

Once we're done with Phase 0 and 1 of #621, it would be pretty straightforward to bring up a Windows 10 Home machine on MacStadium and add that to our fleet of test bots.

**Comment by rfay** [comment]
I tried win 10 home way back in the day with docker toolbox and it worked if you just set up the env var for docker host. That's basically the same as what you have to do to use wsl also. However... Who knows today.

Our decision to support docker for Windows was about limiting permutations, not really feasibility.

**Comment by rfay** [comment]
Yep, drud/mariadb-local#53 works fine on Win 10 Home with Docker Toolbox. But the performance (see the issue) is pretty abysmal. @cweagans suggests there might be tolerable workarounds on this.
