### ISSUE TITLE
Question about documentation configuration 

### ISSUE THREAD

**Issue by nearlythere** [drud/ddev#637]
Is this by design? Seems like these links are missing, and I don't know if it's intentional or an error with RTD. Looks like an error. 

## What you expected to happen:

- Missing in sidebar: download links to versions and formats. 
- Missing in upper right hand corner:  "Edit on GitHub"

Examples of what I expected to see (screenshotted from other projects)

<img width="257" alt="missing-edit-github" src="https://user-images.githubusercontent.com/330552/35816412-8cdaa1e8-0a92-11e8-8690-6fec3fd4bd66.png">

<img width="317" alt="read-docs-downloads" src="https://user-images.githubusercontent.com/330552/35816304-467c5908-0a92-11e8-94e4-37b8088ba066.png">

## How to reproduce this:

Visit the site https://ddev.readthedocs.io/ 

## Anything else do we need to know:

These links help people know which version of docs they are looking at and how to suggest improvements.

**Comment by rfay** [comment]
Assigned to @tannerjfco for review. Thanks for pointing this out, it seems like the approach in some other projects could help us.

**Comment by rickmanelius** [comment]
Related issue https://github.com/drud/ddev/issues/630. This is yet another issues/snag we've hit upon using readthedocs. It might be worth re-evaluating if build/search issues persist.

**Comment by tannerjfco** [comment]
We've gained the "Edit on Github" link with the fix in #641, but unfortunately it looks as though the workaround we're using to fix search breaks the RTD footer pop-up menu. Given that we only provide one version of our docs and dont have PDF or Epub versions, I don't think the loss of this menu impacts our project all that much. If the situation with search issues changes, or a better workaround surfaces, we may be able to have both working, but I think we've addressed what we can at this time.

Thanks for letting us know about these issues!

**Comment by nearlythere** [comment]
@tannerjfco @rfay Can we reopen this? Or is it simply "won't fix" at this time? (I couldn't find info about the search issue, is that related to the RTD service?)

I should have specified in the original post: We would like to have downloadable PDFs for installation instructions, especially for use in onboarding newcomers at sprints and training. 

If they can be elegantly generated from Docs directly this would ensure the materials are up to date.

**Comment by rickmanelius** [comment]
Linking to our documentation audit #242 because we need to do a more significant update/upgrade. To that end, I would prefer to solve that there at both a content and a structure level. If that works, let's close this sub-issue out, @nearlythere!

**Comment by nearlythere** [comment]
@rickmanelius sounds good to me!
