### ISSUE TITLE
Jupyter Notebook for DDEV Demos

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#652]
## What happened (or feature request):

I've provided several demos stepping through basic functionality like configuring a new project, configuring, etc. Given how rote/routine this is, we should consider moving this to a Jupyter Notebook project in parallel with our documentation so that anyone wanting to test DDEV can click through it.

## What you expected to happen:

* An end-user or trainer could provide the notebook as a way to step through the basics.

## Related source links or issues:

* #650
* [Jupyter Notebook](https://jupyter.org/)

## Please use a complexity rating of 1-5 (5 is high) for a feature request. (High complexity implies more PR planning)

3 (not difficult, but potentially time consuming to build and then ongoing effort to maintain).

**Comment by rickmanelius** [comment]
cc @cyberswat. Thanks for the idea!

**Comment by cyberswat** [comment]
This is neat because you would ideally be able to run the demo from ddev itself. There are a bunch of official Jupyter containers on dockerhub that would work with mounted notebooks. However, they need to exec to the host laptop which is problematic.

**Comment by rickmanelius** [comment]
@sgrandchamp This is the issue we were discuss re:notebooks for demo.

**Comment by rickmanelius** [comment]
@cyberswat I know you've been working on this. Do you have a sense of where you're thinking/planning on storing these? Within our Read The Docs? Separate folder? Separate repo?

**Comment by cyberswat** [comment]
https://github.com/drud/ddev-demo

**Comment by rickmanelius** [comment]
@cyberswat Not urgent, but are you looking for a review or can we consider this done?

**Comment by sgrandchamp** [comment]
@rickmanelius @cyberswat perhaps just me but I don't consider it done until I can actually run the demo on my machine.  I know I'm on the hook for "reading the docs" and sorting it out and that is on my short list for this week so I'd like to leave this open.  my .02

**Comment by rickmanelius** [comment]
Sounds good! Added a calendar invite for next week to get this moving/closed.

**Comment by rfay** [comment]
Is this complete? If so, please close. Not sure it belonged in this queue?

**Comment by sgrandchamp** [comment]
@rfay It is not complete, at least from my (sales) perspective.  Certainly could have been in the Drud/Admin space.  Happy to close and reopen in that queue.

**Comment by rfay** [comment]
I'd think a screencast would be simpler and more effective, and would have been long since done :)

May I move this issue to the ddev-demo repo?

**Comment by rfay** [comment]
This issue was moved to drud/ddev-demo#8
