### ISSUE TITLE
ddev config.yaml hooks don't allow nontrivial commands (shell commands)

### ISSUE THREAD

**Issue by rfay** [drud/ddev#658]
## What happened (or feature request):

It's a pretty normal expectation that you could do something like `apt-get update && apt-get install bash` or `ls -l | tail -3l` in a ddev config.yaml hook exec command (or exec-host). But you can't, none of the things that are interpreted by the shell are available, so &&, ||, |, > $ENVVAR, none of those are available.

**Comment by tmotyl** [comment]
related to https://github.com/drud/ddev/issues/1023

**Comment by rfay** [comment]
I updated the OP on #1023 to reflect this; it's the same issue, should be dealt with together, so closing this one as a duplicate.
