### ISSUE TITLE
Add docs HOWTO section for small challenges so people can solve them themselves

### ISSUE THREAD

**Issue by rfay** [drud/ddev#659]
## What happened (or feature request):

People are asking lots of great questions. Let's add the solutions to a docs HOWTO.

- [ ] How to set an environment variable in web container (we probably can't yet without editing of docker-compose.yml, but we should)
- [x] How to turn off xdebug
- [x] How to install an extra needed package in web container (or other random changes to web container)
- [x] Running composer on start (in container)
- [x] Running composer on start (on host)
- [ ] Using drush inside and outside the container
- [x] Viewing nginx, php-fpm, mariadb logs, ddev logs -f
- [x] Solving "Index column size too large" as in #654  ([answer](https://stackoverflow.com/questions/49785419/ddev-import-db-index-column-size-too-large-the-maximum-column-size-is-767-byte/49785420#49785420)
- [ ] Other examples of PHP config override and mysql override
- [x] Drupal 8 and composer workflow with ddev by @dsquaredb ([composer answers](https://stackoverflow.com/questions/49660082/how-can-i-run-composer-with-ddev))
- [x] Composer create-project by @ultimike (see the cross-referenced issue) ([composer answers](https://stackoverflow.com/questions/49660082/how-can-i-run-composer-with-ddev))
- [ ] Linux users often miss that they have to add the normal user to the "docker" group to be able to use docker without sudo.
- [x] Using `ddev logs` to debug 500 or related errors.
- [ ] Platform.sh instructions/howto
- [x] Getting to the D7 /install.php page for a fresh website ([answer](https://stackoverflow.com/questions/49696010/i-set-up-a-drupal-project-in-ddev-and-i-get-a-pdoexception-when-hitting-the-proj))
- [x] xdebug troubleshooting ([answer](https://stackoverflow.com/questions/49677199/how-do-i-get-xdebug-step-debugging-working-with-ddev))

Please edit this or comment to add howtos as they come up or are requested.

**Comment by rickmanelius** [comment]
Related to this https://github.com/drud/ddev/issues/654.

**Comment by rickmanelius** [comment]
I'm willing to take a stab at some of the bulleted items.

**Comment by rfay** [comment]
I'm stuck on where this should live. Normally things like this would gestate in blog posts or something, or wikis. But our normal approach is in the docs. I'm convinced we should get this going ASAP though, even if we choose the wrong place to start.

**Comment by rickmanelius** [comment]
Updated the issue summary to reflect inclusion of the articles/HOWTOs by @ultimike and @dsquaredb

**Comment by rickmanelius** [comment]
Hi @rfay. If we were really picky, could have up to 3 different sections: HOWTOs/Tutorials, FAQs, and Troubleshooting. There are gray areas because some could exist in multiple at the same time. I think the HOWTO suggestion would be sufficient out of the gates and that could include/address all but  #654, which might better go in "Troubleshooting."

Most of the verbiage could be pulled from closed issues in our queue, with some additional clean-up for grammar/spelling/context. I'm not sure what makes sense from an overall prioritization, but I would imagine before Drupalcon would make sense. Tagging in the v0.17.0 release. I can share working on this one.

**Comment by rickmanelius** [comment]
This might be a great issue for @nearlythere to weigh in on.

**Comment by nearlythere** [comment]
Making note that we need a tutorial on:
- How to test updates to Drupal locally before pushing to prod

**Comment by rickmanelius** [comment]
Let's prioritize 2-3 and get started on this from a flow perspective.

**Comment by rickmanelius** [comment]
I'm not a typical Linux user, so this was incredibly helpful to get operational with Docker
https://docs.docker.com/install/linux/linux-postinstall/#configure-docker-to-start-on-boot

**Comment by rickmanelius** [comment]
Another request from @lisastreeter in the [Drupal #ddev Slack channel](https://drupal.slack.com/messages/C5TQRQZRR). Having instructions on how to best connect with or use a site from Platform.sh.

**Comment by rickmanelius** [comment]
Another item. Now that we have #692 in place, CMSes like D7 can result in DX issues because Drupal 7 is trying to load from a blank database instead of immediately redirecting to install.php. This was unexpected behavior.

I'm not sure what the best approach is for D7 (which has an immense install base), but it's something to consider or at least warn users about.

**Comment by rfay** [comment]
I really think we should implement this one on Stackexchange, adding to the scope of [set up support on stackexchange](https://github.com/drud/ddev/issues/702). Each important item can be asked there, and we can give a good supported answer.

**Comment by rfay** [comment]
* DB service stopped: https://stackoverflow.com/questions/49659766/my-ddev-project-says-db-service-stopped-and-i-cant-get-it-started

* Running composer: https://stackoverflow.com/questions/49660082/how-can-i-run-composer-with-ddev/49660083#49660083

* Web container won't start: https://stackoverflow.com/questions/49657246/i-upgraded-ddev-and-now-the-web-container-wont-start

**Comment by rfay** [comment]
Examining logs: https://stackoverflow.com/questions/49660210/how-can-i-find-out-whats-going-wrong-with-a-ddev-container-or-see-the-logs/49660277#49660277

**Comment by rfay** [comment]
I think all the ones that can really be done right now within our expertise are done in https://stackoverflow.com/questions/tagged/ddev - Things like platform.sh (which we have no current experience with) should probably be spun off into an investigation/docs ticket. 

My strategy from here on out is to just write up things when they get solved as long as the question seems reasonable and likely to be repeated.

So I'm ready to close this.

**Comment by rickmanelius** [comment]
Alrighty. That makes sense. It looks like we only had 5 left, so we can simply wait until someone actually touches on them again to prioritize/complete. Thanks, @rfay!
