### ISSUE TITLE
Expose xdebug.remote_enable status in config.yaml (or generically all php settings)

### ISSUE THREAD

**Issue by rfay** [drud/ddev#660]
## What happened (or feature request):

In at least some contexts, xdebug being enabled causes a slowdown, and we don't want that.

We can easily provide a config in config.yaml to control this.

It's worth considering though whether we just want to make it generic and allow overriding any php setting.

The short-term fix for anybody that wants to disable xdebug - put this in your site's config.yaml and then `ddev start`:

```
hooks:
 post-start:
  - exec: phpdismod xdebug
```

**Comment by ultimike** [comment]
Big +1 for this. 

I'd love to see a way to tweak the following php.ini values (at a minimum) in the config.yml as well:

- memory_limit
- max_execution_time
- max_input_time

thanks,  
-mike

**Comment by cweagans** [comment]
We already have a way to replace the nginx conf. Can we put a php.ini in the .ddev directory and include it if it exists? I don't think we should bother with wiring up a separate config flag for every option. Someone that wants to modify php.ini values should just be able to modify php.ini values.

**Comment by rfay** [comment]
I think that's a totally legitimate approach.

**Comment by rickmanelius** [comment]
All. I believe this is now in place as of https://github.com/drud/ddev/releases/tag/v0.15.0, specifically as a result of the PR in #707 and documented here [PHP](https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#providing-custom-php-configuration-phpini) and here [MySQL](https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#providing-custom-mysqlmariadb-configuration-mycnf). The Xdebug-by-default issue is being handled separately here https://github.com/drud/ddev/pull/718, so I say we focus our efforts there and close this ticket. Happy to re-open if there is more to address apart from that!
