### ISSUE TITLE
TYPO3 environment extremely slow 

### ISSUE THREAD

**Issue by misterboe** [drud/ddev#664]
Working on TYPO3 in the DDEV environment is extrem slow.  Saving Content needs 1-3 Seconds. Also FE needs lots of time. 

Any ideas what i could do to speed up? 

Working on:
macOS 10.12
Docker Version 17.12.0-ce-mac49 (21995)

<img width="618" alt="bildschirmfoto 2018-02-20 um 09 59 15" src="https://user-images.githubusercontent.com/6050140/36415050-c9ae2ab6-1624-11e8-8a6e-c1f3789ce401.png">

**Comment by rfay** [comment]
A TYPO3 user this week seems to have found that turning off xdebug made a difference. He also found that the 

You can turn off xdebug with this in the .ddev/config.yaml:
```
hooks:
 post-start:
  - exec: “phpdismod xdebug”
```

(and then `ddev start`)

He also found that the dev  application context, TYPO3_CONTEXT seemed to be responsible. 

I'd be interested to hear your results turning off xdebug and trying the prod TYPO3_CONTEXT. 

Thanks!

**Comment by misterboe** [comment]
I set the TYPO3_CONTEXT to Production and tried your hook. There was not a really big difference. 
The only thing what gave some speed was to raise CPU Cores and RAM on Docker. 
But i still need 1-2 seconds for loading. 
The same web on my local MAMP is fast as hell. I think ddev is a great tool what i want to use, but it had to be faster.

**Comment by dahaupt** [comment]
@misterboe You should try downgrading docker to 17.09, installation guide says:
> As of 13 Feb 2018, the latest stable docker version (17.12) hangs regularly when using docker-compose and bind-mounted filesystems. The docker issue is moby/moby#35933. As a result, we're using 17.09 exclusively until this can be solved upstream. Note that the "edge" version 18.02 may have the new fix in it.

**Comment by misterboe** [comment]
thanks for the hint - i will check that and give you a report

**Comment by rfay** [comment]
@misterboe there are some wild variations in docker, especially on macOS. The key contributor to performance issue on docker is the mount filesystem, and that's exacerbated by huge numbers of files.

On the docker Edge channel they seem to have solved the hanging problem in stable 17.12, so Docker 18.02 seems to be both fixed and faster (maybe a lot faster). But I've also seen weird situations where restarting docker or resetting it changed behavior enormously. Note that switching to edge destroys all your containers and images.

I'd be interested in knowing how many files there are in your repo. If you could let me know (`find /path/to/repo -type f | xargs wc -l` is one way).

Thanks for working on this, and we always love to hear and learn from your feedback.

**Comment by misterboe** [comment]
Project has: 55116 Files
Docroot: 42850 Files

I Updated Docker from 17.12.0 to 18.02.0 with these results:

## Backend: 
![bildschirmfoto 2018-02-22 um 18 55 20](https://user-images.githubusercontent.com/6050140/36556055-3523dab2-1804-11e8-96cd-5cdac0c1ef03.png)
![bildschirmfoto 2018-02-22 um 19 03 22](https://user-images.githubusercontent.com/6050140/36556056-353f9efa-1804-11e8-957b-a59b6c5d026f.png)

## Frontend:
![bildschirmfoto 2018-02-22 um 18 56 34](https://user-images.githubusercontent.com/6050140/36556103-5782ce06-1804-11e8-9a80-655530992b77.png)
![bildschirmfoto 2018-02-22 um 19 02 50](https://user-images.githubusercontent.com/6050140/36556104-57a3e456-1804-11e8-8caa-bdfd8158fbd3.png)

**Comment by rfay** [comment]
Thanks. Please comment on what that meant to you.

Also, could you mention the specs of your mac?

**Comment by misterboe** [comment]
Upgrading Docker is a good performace boost. But i think it could be a bit faster for a good development speed. 

Here are the specs of my mac. 
![specs](https://user-images.githubusercontent.com/6050140/36583133-9a82de06-1874-11e8-9e90-698ce1231a76.png)

If you want me to test anything else - just tell me what i should do.

**Comment by rfay** [comment]
Thanks so much! You've got a much beefier machine than I use. Thanks for responding with that.

We're always sensitive to performance, because it means a lot to all of us. Mostly we're at the mercy of docker, and they're making some significant progress, so that's good.

**Comment by rickmanelius** [comment]
Updated assignments and labels. We'll work on this during this sprint to do some profiling and see if there are other areas/items to hit on.

**Comment by rickmanelius** [comment]
Hi @misterboe. Thank you for submitting this data. I think we need to do a few more things before we can move forward.

* [ ] Can you provide us the FE/BE metrics for your MAMP setup as well as some basic information about which version of PHP/MYSQL you're running.
* [ ] There is a bit of data to parse, and not all performance indicators are primary. I assume total page load time is the big one (versus server response time, etc).
* [ ] Acceptable/Ideal tolerances. So if your MAMP set up is the best case scenario and we're currently at X ms slower, what is the threshold that we can consider a win? Within 100ms? 300? I know it's hard to say and the "ideal" is "just as fast", but I'm trying to see how feasible it is or if this is simply unobtainable give Docker-related IO issues. 
* [ ] Acceptable workarounds. While I hate to use Docker in a VM, using a Linux VM even on mac hardware is a significant performance boost. Is this an acceptable workaround for you/other FEEs or does that negate this as a viable option?

**Comment by rickmanelius** [comment]
Tagging @andrew-c-tran to come in and see if there is anything obvious we might be missing.

**Comment by misterboe** [comment]
First of all - Thanks for the great support here. 

Here are the MAMP Informations:
MAMP 4.4.1
PHP-CGI Version for the Web: 7.1.12
MYSQL 5.6.38
Apache

Here are the metrics from that:
## FE
<img width="502" alt="bildschirmfoto 2018-03-07 um 08 10 05" src="https://user-images.githubusercontent.com/6050140/37078621-4812f4ba-21e0-11e8-92ce-3028f697f3e5.png">

## BE
![bildschirmfoto 2018-03-07 um 08 10 50](https://user-images.githubusercontent.com/6050140/37078637-5ac343d0-21e0-11e8-86bc-5957b5956cc7.png)

These Infos are for your first question. Please give me some time to think about the others.

**Comment by rfay** [comment]
@misterboe Would love it if you could disable xdebug and repeat to see what your experience is.

The two commands inside the web container would be
```
phpdismod xdebug
killall -1 php-fpm
```

You can do that with `ddev exec` also, and you can set it up to do that on every container start with this config in your .ddev/config.yaml:

```
hooks:
  post-start:
    - exec: phpdismod xdebug
    - exec: killall -1 php-fpm
```
```

**Comment by rfay** [comment]
@misterboe this was closed automatically by the PR being committed, but would very much appreciate your re-test on release which will hopefully be tomorrow. Please reopen or tell us to reopen if it has not sorted out the issues. Testers have reported excellent results with performance.

**Comment by rickmanelius** [comment]
Re-opening because I want to get a little first-hand experience on the testing of this so I can speak to this when people surface performance issues as a concern. I believe this new set of updates covers this, but I want to take a crack at this for 30 minutes or so.

**Comment by rfay** [comment]
@misterboe I'm happy to see you seem to be working successfully with ddev... I'm going to close this now as it seems to have the issues resolved? Please comment if not.
