### ISSUE TITLE
Add Google Analytics to Our Documentation

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#668]
## What happened (or feature request):

Feedback is helpful, and knowing what pages are being viewed vs not used will help us focus on what's working and what isn't. Also, adding analytics seems trivial based on docs 
https://docs.readthedocs.io/en/latest/guides/google-analytics.html

## What you expected to happen:

* [x] Generate a new GA code specific to this property.
* [x] Add to our Read the Docs settings.
* [x] Verify tracking is working.
* [ ] Send a weekly report to engineering.

**Comment by rickmanelius** [comment]
Received credentials from @tannerjfco. Added the UA code and triggered a new build.

**Comment by rickmanelius** [comment]
Finally received a successful build, but the code isn't there. I'll kick another time, but I may have to leave this if it doesn't immediately work as advertised.

**Comment by rickmanelius** [comment]
Might be an issue with the theme. See https://bcb.github.io/rtd-analytics

**Comment by tannerjfco** [comment]
We aren't using a custom theme, and we're using MkDocs, not sphinx, which that post seems to be in reference to. It looks like this can take an hour, sometimes up to a day: https://github.com/rtfd/readthedocs.org/blob/master/docs/guides/google-analytics.rst

**Comment by rickmanelius** [comment]
@tannerjfco I get that it can take up to an hour or a day for GA to report it, but when I view source, I don't see the script or that UA code. Good to know that we're using a stock theme and therefore it's some other factor preventing the script from appearing on the page...

**Comment by rickmanelius** [comment]
@tannerjfco Nevermind. Apparently, I no longer know how GA works :) They must be calling and reporting server-side versus in JS. I can confirm it's now reporting. Thanks for your help! :)

**Comment by rickmanelius** [comment]
Weekly report scheduled to go to ops@drud.com. I had a test email sent and it worked just fine. Closing.
