### ISSUE TITLE
Move plugin name from container name prefix to docker label

### ISSUE THREAD

**Issue by tannerjfco** [drud/ddev#67]
## What happened (or feature request):
Currently, our containers are named in the format of [plugin]-[sitename]-[container-type]. This exposes concept of plugin which is not really necessary until we are listing sites sorted by plugin, in the list function. 

## What you expected to happen:
We should be able to move the plugin from a prefix of the container name to a docker label in the compose file. This would allow us to have cleaner container names that are more relevant to the user, while still providing the plugin name in a label to allow us to filter and sort the containers that should be listed in ddev list.

## Related source links or issues (like source JIRA issue):

**Comment by rickmanelius** [comment]
I don't know enough about this to make it actionable or where to prioritize. Tagging w/hibernate for now.

**Comment by tannerjfco** [comment]
Plugin has been introduced as a label via the new "com.ddev.platform" label, which is used to determine apps in list now, as opposed to the container name. The only remaining aspect of this issue would be to remove platform from the container name, if we decided we wanted to.

**Comment by tannerjfco** [comment]
As part of providing documentation for extending ddev in #214, one of the conventions I defined in the documentation is for users to follow the same naming convention for containers that we do. I think it would be much clearer to users to have a simpler convention consisting of only the site name and the service name.

**Comment by rickmanelius** [comment]
@tannerjfco Still valid?

**Comment by tannerjfco** [comment]
This can be closed. Service names no longer have plugin or sitename. Container names still do, but we're going to replace plugin with a ddev- prefix in #288, at which point this ticket's concerns are all met.
