### ISSUE TITLE
custom my.cnf doesn't load server_id value

### ISSUE THREAD

**Issue by nickchomey** [drud/ddev#6768]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

======== Output file will be in /home/nick/tmp/ddev-debug-test.txt ========

======== Existing project config ========
ddev installation alternate locations:
/usr/bin/ddev
/bin/ddev

These config files were loaded for project stfgz: [/home/nick/ddev-projects/stfgz/.ddev/config.yaml]
name: stfgz
type: wordpress
php_version: 8.2
webserver_type: nginx-fpm
webimage: ddev/ddev-webserver:v1.23.5
additional_hostnames: []
database: {mysql 8.0}
project_tld: ddev.site
use_dns_when_possible: true
composer_version: 2
disable_settings_management: true
nodejs_version: 20
default_container_timeout: 120

======== existing project customizations ========
.ddev/docker-compose.unixsockets.yaml
.ddev/php/xdebug.ini
.ddev/web-build/relay.cron
.ddev/mysql/conduit.cnf

======== installed DDEV add-ons ========
┌───────────────────────┬─────────┬────────────────────────────────────┬───────────────────────────┐
│ ADD-ON                │ VERSION │ REPOSITORY                         │ DATE INSTALLED            │
├───────────────────────┼─────────┼────────────────────────────────────┼───────────────────────────┤
│ ddev-cron             │ 1.8.0   │ ddev/ddev-cron                     │ 2024-09-13T17:44:55-06:00 │
├───────────────────────┼─────────┼────────────────────────────────────┼───────────────────────────┤
│ ddev-share-cloudflare │ v0.2.0  │ nickchomey/ddev-cloudflare         │ 2024-09-15T21:49:19-06:00 │
├───────────────────────┼─────────┼────────────────────────────────────┼───────────────────────────┤
│ ddev-wordpress        │         │ /home/nick/tool-dev/ddev-wordpress │ 2024-09-15T13:41:54-06:00 │
├───────────────────────┼─────────┼────────────────────────────────────┼───────────────────────────┤
│ redis                 │ v2.7.1  │ ddev/ddev-redis-7                  │ 2024-09-12T20:19:32-06:00 │
├───────────────────────┼─────────┼────────────────────────────────────┼───────────────────────────┤
│ spx                   │ v0.0.2  │ fullfatthings/ddev-spx             │ 2024-11-03T08:38:19-06:00 │
├───────────────────────┼─────────┼────────────────────────────────────┼───────────────────────────┤
│ xhgui                 │ 2.1.2   │ ddev/ddev-xhgui                    │ 2024-09-17T20:54:52-06:00 │
└───────────────────────┴─────────┴────────────────────────────────────┴───────────────────────────┘

======== mutagen situation ========
looking for #ddev-generated in mutagen.yml in project /home/nick/ddev-projects/stfgz
.ddev/mutagen/mutagen.yml not found

======== Creating dummy project named tryddevproject-12708 in ../tryddevproject-12708 ========
Creating a new DDEV project config in the current directory (/home/nick/ddev-projects/tryddevproject-12708)
Once completed, your configuration will be written to /home/nick/ddev-projects/tryddevproject-12708/.ddev/config.yaml

Configuring a 'php' project named 'tryddevproject-12708' with docroot 'web' at '/home/nick/ddev-projects/tryddevproject-12708/web'.
For full details use 'ddev describe'.
Configuration complete. You may now run 'ddev start'.

======== OS Information ========
Linux wsl2 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

======== User information ========
uid=1002(nick) gid=1002(nick) groups=1002(nick),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),100(users),107(netdev),989(docker)

======== DDEV version ========
 ITEM             VALUE                                    
 DDEV version     v1.23.5                                  
 architecture     amd64                                    
 cgo_enabled      0                                        
 db               ddev/ddev-dbserver-mariadb-10.11:v1.23.5 
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.23.5              
 docker           27.3.1                                   
 docker-api       1.47                                     
 docker-compose   v2.29.7                                  
 docker-platform  wsl2-docker-ce                           
 global-ddev-dir  /home/nick/.ddev                         
 mutagen          0.17.2                                   
 os               linux                                    
 router           ddev/ddev-traefik-router:v1.23.5         
 web              ddev/ddev-webserver:v1.23.5              

======== proxy settings ========

 HTTP_PROXY=''
 HTTPS_PROXY=''
 http_proxy=''
 NO_PROXY=''
 

======== DDEV global info ========
developer-mode=false
disable-http2=false
fail-on-hook-fail=false
instrumentation-opt-in=true
instrumentation-queue-size=0
instrumentation-reporting-interval=0s
instrumentation-user=
internet-detection-timeout-ms=3000
last-started-version=v1.23.5
letsencrypt-email=
mailpit-http-port=8025
mailpit-https-port=8026
mkcert-caroot=/mnt/c/Users/nick_/AppData/Local/mkcert
no-bind-mounts=false
omit-containers=[]
performance-mode=none
project-tld=ddev.site
required-docker-compose-version=v2.29.7
router=traefik
router-bind-all-interfaces=false
router-http-port=80
router-https-port=443
simple-formatting=false
table-style=default
traefik-monitor-port=10999
use-docker-compose-from-path=false
use-hardened-images=false
use-letsencrypt=false
wsl2-no-windows-hosts-mgt=false
xdebug-ide-location=

======== DOCKER provider info ========
docker client location: -rwxr-xr-x 1 root root 40937024 Sep 20 05:40 /usr/bin/docker

docker client alternate locations:
/usr/bin/docker
/bin/docker

Docker provider: wsl2-docker-ce
docker version: 
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:40:59 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:40:59 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.23
  GitCommit:        57f17b0a6295a39009d861b89e3b3b87b005ca27
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

DOCKER_DEFAULT_PLATFORM=notset
Docker platform: wsl2-docker-ce
Using Docker context: default (unix:///var/run/docker.sock)
docker-compose: v2.29.7
Using DOCKER_HOST=unix:///var/run/docker.sock
Docker version: 27.3.1
Able to run simple container that mounts a volume.
Able to use internet inside container.
Docker disk space:Filesystem                Size      Used Available Use% Mounted on
overlay                1006.9G     58.9G    896.7G   6% /

======== Existing docker containers ========
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

======== mkcert information ========
/home/nick/.local/share/mise/installs/mkcert/1.4.4/bin/mkcert
/usr/bin/mkcert
/bin/mkcert
/mnt/c/Users/nick_/AppData/Local/mkcert
total 8
-r-x------ 1 nick nick 2484 Jun  6 16:10 rootCA-key.pem
-rwx------ 1 nick nick 1826 Jun  6 16:10 rootCA.pem

======== ping attempt on ddev.site ========
PING dkdkd.ddev.site (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.041 ms

--- dkdkd.ddev.site ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.041/0.041/0.041/0.000 ms

======== ddev debug rebuild ========
Rebuilding project images...
Rebuilding project tryddevproject-12708 with `/home/nick/.ddev/bin/docker-compose -f /home/nick/ddev-projects/tryddevproject-12708/.ddev/.ddev-docker-compose-full.yaml --progress plain build web --no-cache`
#0 building with "default" instance using docker driver

#1 [web internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.36kB done
#1 DONE 0.0s

#2 [web internal] load metadata for docker.io/ddev/ddev-webserver:v1.23.5
#2 DONE 0.0s

#3 [web internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [web 1/8] FROM docker.io/ddev/ddev-webserver:v1.23.5
#4 CACHED

#5 [web 2/8] RUN (groupadd --gid 1002 "nick" || groupadd "nick" || true) && (useradd  -l -m -s "/bin/bash" --gid "nick" --comment '' --uid 1002 "nick" || useradd  -l -m -s "/bin/bash" --gid "nick" --comment '' "nick" || useradd  -l -m -s "/bin/bash" --gid "1002" --comment '' "nick" || useradd -l -m -s "/bin/bash" --comment '' nick )
#5 DONE 0.4s

#6 [web 3/8] RUN mkdir -p /home/nick && chown nick /home/nick && chmod 600 /home/nick/.pgpass
#6 DONE 0.6s

#7 [web 4/8] RUN mariadb-client-install.sh || true
#7 0.477 This script is not intended to run with mariadb:10.11
#7 DONE 0.5s

#8 [web 5/8] RUN export XDEBUG_MODE=off; composer self-update --stable || composer self-update --stable || true; composer self-update --2 || log-stderr.sh composer self-update --2 || true
#8 0.870 Storing "stable" as default update channel for the next self-update run.
#8 6.169 Upgrading to version 2.8.3 (stable channel).
#8 6.563    
#8 9.569 Use composer self-update --rollback to return to version 2.8.1
#8 14.96 You are already using the latest available Composer version 2.8.3 (2.x channel).
#8 DONE 15.0s

#9 [web 6/8] RUN apt-get update
#9 0.834 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
#9 0.876 Get:2 https://packages.sury.org/php bookworm InRelease [7551 B]
#9 0.964 Get:3 https://dl.cloudsmith.io/public/platformsh/cli/deb/debian bookworm InRelease [3675 B]
#9 1.001 Get:4 https://packages.sury.org/php bookworm/main amd64 Packages [244 kB]
#9 1.086 Get:5 http://nginx.org/packages/debian bookworm InRelease [2869 B]
#9 1.099 Get:6 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
#9 1.223 Get:8 https://dl.cloudsmith.io/public/platformsh/upsun-cli/deb/debian bookworm InRelease [3681 B]
#9 1.312 Get:9 http://nginx.org/packages/debian bookworm/nginx amd64 Packages [14.9 kB]
#9 1.360 Get:10 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
#9 1.452 Get:11 http://deb.debian.org/debian bookworm/main amd64 Packages [8789 kB]
#9 1.482 Get:12 https://dl.cloudsmith.io/public/symfony/stable/deb/debian bookworm InRelease [4422 B]
#9 1.620 Get:13 https://dl.cloudsmith.io/public/platformsh/cli/deb/debian bookworm/main amd64 Packages [4384 B]
#9 1.685 Get:7 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm InRelease [4625 B]
#9 1.797 Get:14 https://dl.cloudsmith.io/public/platformsh/upsun-cli/deb/debian bookworm/main amd64 Packages [3235 B]
#9 1.933 Get:15 https://dl.cloudsmith.io/public/symfony/stable/deb/debian bookworm/main amd64 Packages [7810 B]
#9 2.029 Get:16 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg InRelease [129 kB]
#9 2.381 Get:18 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg/main amd64 Packages [359 kB]
#9 2.396 Get:17 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm/main amd64 Packages [41.2 kB]
#9 3.033 Get:19 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm/main arm64 Packages [34.5 kB]
#9 7.044 Get:20 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [2468 B]
#9 7.166 Get:21 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [204 kB]
#9 7.961 Fetched 10.1 MB in 7s (1368 kB/s)
#9 7.961 Reading package lists...
#9 DONE 8.6s

#10 [web 7/8] RUN curl -I https://www.google.com
#10 0.516   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#10 0.516                                  Dload  Upload   Total   Spent    Left  Speed
#10 0.516 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
#10 1.014 HTTP/2 200 
#10 1.014 content-type: text/html; charset=ISO-8859-1
#10 1.014 content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-RWOjH99Pc8XjbiKvl1QCFQ' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
#10 1.014 accept-ch: Sec-CH-Prefers-Color-Scheme
#10 1.014 p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
#10 1.014 date: Sat, 23 Nov 2024 01:29:58 GMT
#10 1.014 server: gws
#10 1.014 x-xss-protection: 0
#10 1.014 x-frame-options: SAMEORIGIN
#10 1.014 expires: Sat, 23 Nov 2024 01:29:58 GMT
#10 1.014 cache-control: private
#10 1.014 set-cookie: AEC=AZ6Zc-XDdKWttdtPZCYghux5UtEp9iMpqrhKC3LSOkBK8TeuAlBZpHmQSw; expires=Thu, 22-May-2025 01:29:58 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
#10 1.014 set-cookie: NID=519=jAp_hYd5_qJ7lQc0FoE4cSFn7Q-D2IIZP41WNEWjrYQAM8y7BkJtxWPsommcU_q8ZsiK_8sYMdmI2BrRk1KklbEIngbV3v-o2eTYT-uyZETv5nULyj5eLKWa4V6-5Kxh5b9sA73YWStjxWSGVwn2Asacsqn17_Oy1rswcPfb4XLWGa6xSkC--qHgEmQj4Q0; expires=Sun, 25-May-2025 01:29:58 GMT; path=/; domain=.google.com; HttpOnly
#10 1.014 alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
#10 1.014 
#10 DONE 1.0s

#11 [web 8/8] RUN chmod 777 /run/php /var/log
#11 DONE 0.5s

#12 [web] exporting to image
#12 exporting layers
#12 exporting layers 0.2s done
#12 writing image sha256:189ac599cb9a0012adbc00c1e481cc9a99595be4015b6d5d70179c727be84663 done
#12 naming to docker.io/ddev/ddev-webserver:v1.23.5-tryddevproject-12708-built done
#12 DONE 0.2s

#13 [web] resolving provenance for metadata file
#13 DONE 0.0s
Rebuilt Docker cache for project tryddevproject-12708 in 27s
Network ddev_default created
 Container ddev-ssh-agent  Created
 Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
Building project images...
.Project images built in 2s.
 Network ddev-tryddevproject-12708_default  Created
 Container ddev-tryddevproject-12708-web  Created
 Container ddev-tryddevproject-12708-db  Created
 Container ddev-tryddevproject-12708-db  Started
 Container ddev-tryddevproject-12708-web  Started
Waiting for containers to become ready: [web db]
Starting ddev-router if necessary...
 Container ddev-router  Created
 Container ddev-router  Started

======== Project startup ========
Starting tryddevproject-12708...
2024-11-22T19:30:37.377 GetAvailableRouterPort(): Router is healthy and running
2024-11-22T19:30:37.379 GetAvailableRouterPort(): proposedPort 80 already bound on ddev-router, accepting it
2024-11-22T19:30:37.381 GetAvailableRouterPort(): Router is healthy and running
2024-11-22T19:30:37.383 GetAvailableRouterPort(): proposedPort 443 already bound on ddev-router, accepting it
2024-11-22T19:30:37.385 GetAvailableRouterPort(): Router is healthy and running
2024-11-22T19:30:37.387 GetAvailableRouterPort(): proposedPort 8025 already bound on ddev-router, accepting it
2024-11-22T19:30:37.388 GetAvailableRouterPort(): Router is healthy and running
2024-11-22T19:30:37.391 GetAvailableRouterPort(): proposedPort 8026 already bound on ddev-router, accepting it
2024-11-22T19:30:37.421 Pulled image for ddev/ddev-webserver:v1.23.5
2024-11-22T19:30:37.422 Pulled image for busybox:stable
2024-11-22T19:30:37.423 Pulled image for ddev/ddev-utilities
2024-11-22T19:30:37.424 Pulled image for ddev/ddev-ssh-agent:v1.23.5
2024-11-22T19:30:37.425 Pulled image for ddev/ddev-traefik-router:v1.23.5
2024-11-22T19:30:38.806 chowning /mnt/ddev-global-cache and /var/lib/mysql to 1002
2024-11-22T19:30:39.553 done chowning /mnt/ddev-global-cache and /var/lib/mysql to 1002
2024-11-22T19:30:39.577 host.docker.internal='172.29.64.1' because IsWSL2 and !IsDockerDesktop; received from ip -4 route show default
2024-11-22T19:30:39.6 Using automatically detected timezone: TZ=America/Guatemala
2024-11-22T19:30:39.655 Pulled image for ddev/ddev-dbserver-mariadb-10.11:v1.23.5
2024-11-22T19:30:39.656 Pulled image for ddev/ddev-webserver:v1.23.5
2024-11-22T19:30:39.657 Pulled image for ddev/ddev-traefik-router:v1.23.5
2024-11-22T19:30:39.658 Pulled image for ddev/ddev-ssh-agent:v1.23.5
Building project images...
2024-11-22T19:30:39.688 Executing docker-compose -f /home/nick/ddev-projects/tryddevproject-12708/.ddev/.ddev-docker-compose-full.yaml build --progress=plain
.Project images built in 2s.
2024-11-22T19:30:41.387 Removing dangling images for the project ddev-tryddevproject-12708
2024-11-22T19:30:41.392 Executing docker-compose -f /home/nick/ddev-projects/tryddevproject-12708/.ddev/.ddev-docker-compose-full.yaml up -d
 Container ddev-tryddevproject-12708-db  Recreate
 Container ddev-tryddevproject-12708-web  Recreate
 Container ddev-tryddevproject-12708-db  Recreated
 Container ddev-tryddevproject-12708-web  Recreated
 Container ddev-tryddevproject-12708-db  Started
 Container ddev-tryddevproject-12708-web  Started
2024-11-22T19:30:53.829 VIRTUAL_HOST=tryddevproject-12708.ddev.site for web
2024-11-22T19:30:53.829 HTTP_EXPOSE=80:80,8025:8025 for web
2024-11-22T19:30:53.829 HTTPS_EXPOSE=443:80,8026:8025 for web
2024-11-22T19:30:54.48 Copied /home/nick/ddev-projects/tryddevproject-12708/.ddev/traefik:CopyIntoVolume_yxxffxkbmwyo into /mnt/v/traefik in 50.900423ms
2024-11-22T19:30:54.52 Exec chown -R 1002 /mnt/v/traefik stdout=, stderr=, err=<nil>
2024-11-22T19:30:54.889 Copied Traefik certs in /home/nick/ddev-projects/tryddevproject-12708/.ddev/traefik/certs to ddev-global-cache/traefik
2024-11-22T19:30:54.889 Running /start.sh in ddev-webserver
Waiting for containers to become ready: [web db]
2024-11-22T19:30:59.995 Copied /home/nick/.ddev/commands:CopyIntoVolume_tmqgwuwiydax into /mnt/v/global-commands in 51.728001ms
2024-11-22T19:31:00.036 Exec chown -R 1002 /mnt/v/global-commands stdout=, stderr=, err=<nil>
2024-11-22T19:31:00.424 Testing to see if /mnt/ddev_config is properly mounted
2024-11-22T19:31:00.543 Getting stderr output from 'log-stderr.sh --show'
Starting ddev-router if necessary...
2024-11-22T19:31:01.268 Copied /home/nick/.ddev/traefik:CopyIntoVolume_ajieeukmhzrm into /mnt/v/traefik in 46.298315ms
2024-11-22T19:31:01.309 Exec chown -R 1002 /mnt/v/traefik stdout=, stderr=, err=<nil>
2024-11-22T19:31:01.68 Copied global Traefik config in /home/nick/.ddev/traefik/certs to ddev-global-cache/traefik
 Container ddev-router  Running
2024-11-22T19:31:01.732 Waiting for ddev-router to become ready. docker inspect --format "{{json .State.Health }}" ddev-router
2024-11-22T19:31:02.235 ddev-router is ready
Successfully started tryddevproject-12708
Your project can be reached at https://tryddevproject-12708.ddev.site
See 'ddev describe' for alternate URLs.

======== Curl of site from inside container ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 200 OK
Server: nginx
Date: Sat, 23 Nov 2024 01:31:05 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

======== curl -I of http://127.0.0.1:32769 (web container http docker bind port) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Server: nginx
Date: Sat, 23 Nov 2024 01:31:05 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== curl -I of http://tryddevproject-12708.ddev.site (router http URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Date: Sat, 23 Nov 2024 01:31:05 GMT
Server: nginx
Vary: Accept-Encoding

======== Full curl of http://tryddevproject-12708.ddev.site (router http URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   218    0   218    0     0   5273      0 --:--:-- --:--:-- --:--:--  5317
Success accessing database... db via TCP/IP<br />
ddev is working.<br />
The output file for Discord or issue queue is in
<b>/home/nick/tmp/ddev-debug-test.txt</b><br />
file:///home/nick/tmp/ddev-debug-test.txt<br />

======== Full curl of https://tryddevproject-12708.ddev.site (router https URL) from outside ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   218    0   218    0     0   1982      0 --:--:-- --:--:-- --:--:--  2000
Success accessing database... db via TCP/IP<br />
ddev is working.<br />
The output file for Discord or issue queue is in
<b>/home/nick/tmp/ddev-debug-test.txt</b><br />
file:///home/nick/tmp/ddev-debug-test.txt<br />

======== Curl google.com to check internet access and VPN ========
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/2 200 
content-type: text/html; charset=ISO-8859-1
content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-eR-rMcgCbZDfE4DLURQ4nQ' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
accept-ch: Sec-CH-Prefers-Color-Scheme
p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
date: Sat, 23 Nov 2024 01:31:05 GMT
server: gws
x-xss-protection: 0
x-frame-options: SAMEORIGIN
expires: Sat, 23 Nov 2024 01:31:05 GMT
cache-control: private
set-cookie: AEC=AZ6Zc-WlmtJ_lj38HGy1yzdSjZkluwh9kPVl8_YHnH5LPliuCcrJYpg4LA; expires=Thu, 22-May-2025 01:31:05 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
set-cookie: NID=519=cmepzDt-tYmRH4SHW3mGj4FMsR-xwUv_T_4ikmUGc7cF21RPn-ZTSpWj2aB0Y-F7Cuq5HvkhW13Gp_EXWYni2UqIkwpKr0mrJavKimjMYL566pvIe8QZ25rwbr1uvnaeLrii4QKHz4t_NMB3i9LiUVsF6lcmxpEhPweEqWEEgx1RdQy2iFqf-V709fG0pBE5; expires=Sun, 25-May-2025 01:31:05 GMT; path=/; domain=.google.com; HttpOnly
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000

======== host.docker.internal status ========
PING host.docker.internal (172.29.64.1) 56(84) bytes of data.
64 bytes from host.docker.internal (172.29.64.1): icmp_seq=1 ttl=127 time=0.467 ms

--- host.docker.internal ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.467/0.467/0.467/0.000 ms

======== Project ownership on host ========
drwxr-xr-x 4 nick nick 4096 Nov 22 19:29 ../tryddevproject-12708

======== Project ownership in container ========
drwxr-xr-x 4 nick nick 4096 Nov 22 19:29 //var/www/html

======== In-container filesystem ========
Filesystem     Type  1K-blocks     Used Available Use% Mounted on
/dev/sdc       ext4 1055762868 61926260 940133136   7% /var/www/html

======== Thanks for running the diagnostic! ========
Running ddev launch in 3 seconds
Running ddev launch
Waiting for ddev launch to complete before deleting project

Cleanup: deleting test project tryddevproject-12708
 Container ddev-tryddevproject-12708-db  Stopped
 Container ddev-tryddevproject-12708-web  Stopped
 Container ddev-tryddevproject-12708-db  Stopped
 Container ddev-tryddevproject-12708-web  Stopped
 Container ddev-tryddevproject-12708-db  Removed
 Container ddev-tryddevproject-12708-web  Removed
 Network ddev-tryddevproject-12708_default  Removed
Volume tryddevproject-12708-mariadb for project tryddevproject-12708 was deleted
Volume tryddevproject-12708-postgres for project tryddevproject-12708 was deleted
Volume tryddevproject-12708_project_mutagen for project tryddevproject-12708 was deleted
Project tryddevproject-12708 was deleted. Your code and configuration are unchanged.

Please remove the files from this test with 'rm -r ../tryddevproject-12708'
</details>

### Expected Behavior

manually defined db variables would be applied in the db when using mysql, as happens with mariadb

### Actual Behavior

They arent

### Steps To Reproduce

1. create a ddev project
2. change config.yaml to use mysql
```
database:
    type: mysql
    version: "8.0"
```
3. mysql:8.0
4. add this to `.ddev/mysql/new-config.cnf`
```
[mysqld]
server_id=1 #you can try with server-id as well, same result
```
5. `ddev start`
6. `ddev ssh`
7. `mysql`
8. `SHOW VARIABLES LIKE 'server_id';`

It will show 0, not 1.

**Comment by rfay** [comment]
I don't think you can change server_id except at database startup time.  Related:
* https://github.com/ddev/ddev/issues/6668

Please try a more normal config item, like the example in the docs.

**Comment by rfay** [comment]
The referenced issue showed how to override the startup script with a .ddev/db-build/Dockerfile and change it so that this can happen early enough. 

The other issue was also working with replication, which is not something people have poked at very often with DDEV.
