### ISSUE TITLE
Add in-depth testing of sites to ddev tests

### ISSUE THREAD

**Issue by rfay** [drud/ddev#677]
## What happened (or feature request):

In our tests we have a variety of CMSs that we install and start ddev.... but we don't actually do anything with the sites after starting, just test ddev functions like import-db and the like. For real test coverage we need to verify:

- [ ] Hitting the front page works
- [ ] Logging in works
- [ ] Visiting some important URLs works
- [ ] Imagecache/image styles or the equivalent work properly

We'll need to add to this list as we go.

**Comment by cweagans** [comment]
I've been using https://github.com/headzoo/surf on a personal project with a decent amount of success. Might be useful here.

**Comment by rickmanelius** [comment]
I'm not sure if this was already addressed in #671. Seems useful and will pin to v1.2.0 as a milestone related to CMS support.

**Comment by rfay** [comment]
No, this was a spin-off from #671  - We've never had any nontrivial tests for the test sites we install, and it will really improve our coverage and detection when we add them.

**Comment by rfay** [comment]
These should probably be spun off into separate tickets.

When doing Wordpress, please work closely with @alkymst to do something reasonable there.

**Comment by rfay** [comment]
So the way I'm thinking about this now is pretty easy to implement.

1. After https://github.com/drud/ddev/pull/1151 lands, it adds a URI+Expectation.
2. Add a non-static expectation URL (or array of expectations?) to the TestSite type
3. In TestDdevImportDB, test appropriate expected URLs for each project.

I think that's all we really have to do. Not very ambitious at all.
