### ISSUE TITLE
Docs - clarify expectations and assumptions

### ISSUE THREAD

**Issue by nearlythere** [drud/ddev#683]
What are "expectations and assumptions" - is this defined anywhere? Or is there a better way to put this?

In... users/extend/customization-extendibility.md

Under "Overriding default container images" 

> ddev currently has certain expectations and assumptions for what the web and database containers provide. 

Is there another way to put this or be explicit?

**Comment by rfay** [comment]
The expectations are that the container will behave exactly as the one we use. So a docker expert can do this, but not an ordinary person.

If we're not going to give people more info and specific instructions, we should just remove this possibility from the docs for now.

Alternately, we could write up how to derive from a ddev image and change something in it. Could be hard to maintain though.

**Comment by nearlythere** [comment]
OK! That helps, thank you!

**Comment by rfay** [comment]
Assuming this is good enough, closing. Please reopen if you disagree. Or yell if you can't. Thanks!
