### ISSUE TITLE
Docs - clarify language

### ISSUE THREAD

**Issue by nearlythere** [drud/ddev#684]
I'm reviewing the documentation and making some suggestions to improve clarity. I stupidly made a branch locally instead of forking, but I will apply the fixes properly in a fork. 

- Prefer active voice over passive. 
- Reword "you can" statements where we can be more clear about when and why to take an action.
- "We recommend" instead of "it is recommended"
- Remove "simply" in all cases and "easily/easy" in cases where it's subjective.

I'm proposing many changes, but these are generally grammatical. I've reserved anything where I had questions about the meaning. These are two examples: 

In general, instead of sentences with this structure “If you (take action) you can (result)” write “To (get result) do (action)”

Instead of passive voice. 

> These tasks can be defined in the config.yaml for your project, and allow for you to automate setup tasks specific to your project.

Change to active voice

> To automate setup tasks specific to your project, define them in the project's config.yaml file. 

## Testing

I ran MkDocs and checked the display of all pages I changed. It looks good.

**Comment by rickmanelius** [comment]
Cross-linking to the meta-issue of a full-blown documentation audit/rework https://github.com/drud/ddev/issues/242.

Regarding dev/doc norms, @beeradb literally just merged this in today!
https://github.com/drud/community/blob/master/development/development_norms.md

**Comment by rickmanelius** [comment]
Hi @nearlythere! This is not to discount the value of the work done in the PR, which will be reviewed later. I was simply catching up on email and triaging the issue queue to ensure we're connecting relevant issues, etc.

**Comment by nearlythere** [comment]
@rickmanelius @rfay Thanks for the PR review. I fixed most things, but had a few follow up questions in the PR comments. Over to you!
