### ISSUE TITLE
Docs - broken link to default NGINX configuration provided by ddev

### ISSUE THREAD

**Issue by nearlythere** [drud/ddev#687]
In users/extend/customization-extendibility.md

Link to this is broken

https://github.com/drud/docker.nginx-php-fpm-local/blob/master/files/etc/nginx/nginx-site.conf

Should be this, correct?

https://github.com/drud/docker.nginx-php-fpm-local/blob/master/files/etc/nginx/nginx-site-default.conf 

Here:

> - Add your configurations to the "nginx-site.conf" file. You can optionally use the [default NGINX configuration provided by ddev](https://github.com/drud/docker.nginx-php-fpm-local/blob/master/files/etc/nginx/nginx-site.conf) as a reference or starting point.

**Comment by rfay** [comment]
This is out of date, new PR in progress, please review https://github.com/rfay/ddev/blob/92a7d7a7e770427df4cfa6eb2ca566cbdcefe410/docs/users/extend/customization-extendibility.md

PR is https://github.com/drud/ddev/pull/669

**Comment by nearlythere** [comment]
Ah sorry. Closing!
