### ISSUE TITLE
Docs - Create a WordPress tutorial

### ISSUE THREAD

**Issue by nearlythere** [drud/ddev#689]
Create a WordPress tutorial that shows users how to set up WordPress projects with DDEV Local.

## What happened (or feature request):

Based on feedback from one of our other testers: Add a section in the WordPress Quick Start on how to install WP CLI on the container in order to install WP.  User went through the WP installation wizard, didn’t know that the Host was just db, and couldn’t get the site installed.

## Related source links or issues:

https://github.com/drud/ddev/issues/650

**Comment by rickmanelius** [comment]
Hi @nearlythere. I just want to make sure I understand the issue correctly. When logged into the default container via `ddev ssh`, WP CLI is already instead.

```
root@bda464d3211c:/var/www/html# /usr/local/bin/wp --version
WP-CLI 1.4.1
root@bda464d3211c:/var/www/html#
```

Let me know if that solves this issue!

**Comment by nearlythere** [comment]
Ah! OK, just grabbed what looked like a docs issue. Closing!
