### ISSUE TITLE
Resolve site repo / file structure assumptions and make them configurable

### ISSUE THREAD

**Issue by beeradb** [drud/ddev#7]
_From @tannerjfco on January 24, 2017 16:15_

Implement `dcfg` to facilitate handling the "last mile" configurations needed to deploy a working site while removing our rigid repo structure assumptions

##  Current plan of attack:

- [x] Implement a new "template" plugin in dcfg to handle writing/placing configs for drupal and wp
- [x] Update `ddev` cli to remove config file writing and provide stuff like db port as an env var to web container

Original issue reports:
Currently we are heavily assuming that site repos will have a folder called docroot in them that represents where the vhost will serve the site from. This is problematic as it currently requires a specific repo structure to dev or deploy a site with drud. It would be ideal to not require repos to be restructured in order to use our products.

Currently, we heavily assume a drupal site will have its files at `sites/default/files` (drupal default) and that a wordpress site will have its files at `content/uploads` (non-default derived from newmedia structure). Both provide options for this directory to be customized, and it can be a non-trivial task to change this path after a site has been operating for some time. Similar to #4, we should provide a way for developers to specify these paths so that sites do not require restructuring efforts to be used in our offerings.

These are options that can be controlled in the config file for both wordpress and drupal, which provides a straight-forward way for developers to specify the customization, but we would need to be able to define this path in our code for extracting/placing files as well.

_Copied from original issue: drud/general#10_

**Comment by rickmanelius** [comment]
@beeradb @tannerjfco I'm assuming there is nothing left in this issue that is still actionable.

**Comment by rickmanelius** [comment]
Updating labels. Seems like something worth addressing before 1.0 (if the components here are not already addressed elsewhere).

**Comment by rfay** [comment]
This issue is obsolete, closing. New approaches are in #293
