### ISSUE TITLE
Temporary proposal to get PRs reviewed and in, temporary process change

### ISSUE THREAD

**Issue by rfay** [drud/ddev#706]
## What happened (or feature request):

In [retro today](https://docs.google.com/document/d/1LlT8fQDgia4Djk3XE3Jns-8tG0T8YzRF0pszSW5xw9g/edit#heading=h.w4fvmw4hhsdr) we discussed at length the problem that we have 12 PRs stacked up here in ddev and no capacity for technical review. We're going to have to use a number of techniques to resolve this. This issue is an attempt to summarize what I think we said, and for discussion of the options. But it also is a go-ahead unless objections are raised.

These are temporary changes only. The old way "Always a technical review and manual test" is better. We hope to be back there soon.

1.  Docs PRs may go in without technical review. Trivial docs PRs may go in quickly without review. 
2. Trivial PRs like bumping the Homebrew URL and hash don't need review, but should remain PRs, not direct commits.
3. Smaller PRs that I consider to be safe I'll put a comment on them giving a drop-dead date in the issue and the title, probably 2 days out. On that date, I'll re-review and pull if I'm confident.
4. Quick PRs that @beeradb or @tannerjfco could take without spending a lot of time will be posted in slack's traffic-management channel.

**Comment by rfay** [comment]
I changed the settings on drud/ddev to allow administrators to pull without review.

**Comment by rickmanelius** [comment]
This looks accurate based on what we discussed. +1 to close unless anyone else has any objections.

**Comment by rickmanelius** [comment]
Closing for now. If someone feels strongly enough to cross reference from our community docs, I'm happy to re-open and get a PR going.
