### ISSUE TITLE
Container time should be same timezone as user

### ISSUE THREAD

**Issue by rfay** [drud/ddev#709]
## What happened (or feature request):

It's hard to read and understand logs from the containers as they're in GMT. It would be pretty easy to set them to be the same as the host timezone (I think).

**Comment by rickmanelius** [comment]
That's reasonable. Looks actionable as is.

**Comment by rfay** [comment]
So far this isn't as easy as I would have thought.

* The method of getting timezone on the host varies (mac requires sudo: `sudo systemsetup -gettimezone`
* Golang's zone response doesn't include the correct offset during DST.

```
	t := time.Now()
	tz, offset := t.Local().Zone()
	if offset < 0 {
		offset = offset * -1
	}
	zone := "XXX" + strconv.Itoa(offset/3600) + tz
```

**Comment by rickmanelius** [comment]
I know this wouldn't work with tail, but would it be crazy to address this as a regex replacement at the time of output? That seems silly that macOS requires sudo just to know timezone... I can't see how that would be a security attack vector.

**Comment by rfay** [comment]
There are so many different kinds of output that it's too painful to imagine. And people like me may want to work inside the container and see reasonable times.

**Comment by rickmanelius** [comment]
Completely fair. I was spitballing. Looks like we're then blocked unless/until this gets addressed upstream, correct?

**Comment by rfay** [comment]
Not blocked, just frustrated. It's probably solvable, might be slightly more effort than I expected. I was just trying to write down what I learned.

**Comment by rfay** [comment]
Most people don't need this, and for the ones that do there's a super easy workaround adding a $TZ environment variable, https://stackoverflow.com/questions/50255466/how-can-i-set-the-timezone-in-my-ddev-containers/50255467#50255467 - I think this is better than adding extra code to our codebase.
