### ISSUE TITLE
"pcntl_signal()" error running "composer create-project" in the web container

### ISSUE THREAD

**Issue by ultimike** [drud/ddev#710]
## What happened (or feature request):
I had just created a new ddev project using the method outlined on https://github.com/drud/ddev/issues/697 and when I tried the `composer create-project` step, I received the following error:

```
[ErrorException]                                       
  pcntl_signal() has been disabled for security reasons 
```

## What you expected to happen:
Composer to do its thing.

## How to reproduce this:
Follow the steps on https://github.com/drud/ddev/issues/697 - I had previously tried this on a Windows 10 Pro machine with no issues. Today, I was on Mac OS X.

## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.

```
cli   	v0.14.0                        
web   	drud/nginx-php-fpm-local:v1.0.0
db    	drud/mariadb-local:v0.7.1      
dba   	drud/phpmyadmin:v0.2.0         
router	drud/ddev-router:v0.5.0        
commit	v0.14.0                        
domain	ddev.local
```

```
~/Sites/test $ docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true
```

~/Sites/test $ cat .ddev/config.yaml 
APIVersion: "1"
name: test
type: drupal8
docroot: .
php_version: "7.1"
webimage: drud/nginx-php-fpm-local:v1.0.0
dbimage: drud/mariadb-local:v0.7.1
dbaimage: drud/phpmyadmin:v0.2.0
router_http_port: "80"
router_https_port: "8443"
provider: default

# Certain ddev commands can be extended to run tasks before or after the ddev
# command is executed.
# See https://ddev.readthedocs.io/en/latest/users/extending-commands/ for more
# information on the commands that can be extended and the tasks you can define
# for them.
# hooks:
#   post-import-db:
#     - exec: "drush cr"

**Comment by rickmanelius** [comment]
Need to recreate and then we can label/prioritize.

**Comment by rickmanelius** [comment]
Hi @ultimike. We'll move on this today after our sprint planning. Thanks for submitting!

**Comment by ultimike** [comment]
No worries. I'm planning on testing it on a Windows machine (after I update it to 0.14.0) as well.

-mike

**Comment by rfay** [comment]
If this is important and recreatable @ultimike I imagine we can get it into this week's release.

Also, we *will* have in this week's release PHP overrides. And this is just a php.ini issue I'm pretty sure.  We have that listed in the blacklisted functions.

**Comment by ultimike** [comment]
Yep, I figured it was a php.ini issue. I just don't understand why it worked on Windows, but not on Mac. The only difference is that haven't updated DDEV on my Windows machine to 0.14.0 yet. So maybe the blacklist is something that was introduced in 0.14.0?

**Comment by rfay** [comment]
Did you change PHP version maybe? I can't imagine it being different between windows and mac either, because this is all happening on linux.

**Comment by ultimike** [comment]
I don't think I did. In both cases I was trying out the process I defined in https://github.com/drud/ddev/issues/697 - I was really surprised when I hit the error on my Mac...

**Comment by ultimike** [comment]
So I just tried to recreate the issue on my Windows 10 laptop (DDEV 0.14) - same result. 

Prior to doing this on the Windows laptop, DDEV was at version 0.12 (this is what I used to create the procedure in https://github.com/drud/ddev/issues/697), so it seems pretty clear that something introduced between 0.12 and 0.14 is what is causing the issue.

-mike

**Comment by rfay** [comment]
Thanks so much!

**Comment by ultimike** [comment]
Seems like maybe adding a `composer create-project ...` test to DDEV's automated testing suite would be useful.

thanks,
-mike

**Comment by rfay** [comment]
Interesting, the only php config changes in the web container between ddev v0.12.0 (web container v0.9.1) and ddev v0.14.0 (web container v1.0.0) were related to higher timeouts, max_execution_time and request_terminate_timeout. It's possible that a new php patch version snuck in there and the behavior changed? Anyway, working on recreating. And the idea of adding a test with composer create-project is a great one.

**Comment by rfay** [comment]
Added the test, changed the config. This will be in v0.15.0. Thanks so much.

**Comment by ultimike** [comment]
Thank you!
