### ISSUE TITLE
Include skip_permissions_hardening in D8 generated settings (and make sites/default and sites/default/settings.php writeable

### ISSUE THREAD

**Issue by rfay** [drud/ddev#715]
## What happened (or feature request):

@mglaman points out that in D8 we can do this in settings.local.php to avoid the horrible-Drupal "I set sites/default to read-only just to frustrate you":

```
$settings['skip_permissions_hardening'] = TRUE;
```

We should add that to our generated settings for D8.

In addition, for D6/D7/D8 (and I don't think Backdrop needs this?)
on ddev start let's make sites/default (the directory) and sites/default/settings.php (the file) writeable.

**Comment by rfay** [comment]
Added to v0.18.0, and solves so much user abuse and is so easy to do, we should just get it done.

**Comment by rickmanelius** [comment]
Works for me! Seems like an easy one line change and I can review/approve the PR when ready.

**Comment by rfay** [comment]
Edited to add expected behavior for D6/D7/D8: On ddev start we'll make the dir and the file writeable.
