### ISSUE TITLE
"ddev logs" should work against stopped containers

### ISSUE THREAD

**Issue by rfay** [drud/ddev#719]
## What happened (or feature request):

Now that we have changed containers not to restart, we need to make `ddev logs` work against stopped containers. Docker is fine with this, and it's actually quite a lot better for us, but currently ddev refuses to do it and you have to `docker ps -a` and use `docker logs` to find out the reason for a failure.

**Comment by rickmanelius** [comment]
Related #642 (so that projects can be targetted from anywhere). Otherwise, you would have to be in the working directory anyway.

Good idea. Not sure it's urgent, but certainly a good wishlist item!
