### ISSUE TITLE
"ddev stop/rm/restart" hang when db container is stopped/broken

### ISSUE THREAD

**Issue by rfay** [drud/ddev#720]
## What happened (or feature request):

"ddev stop/rm/restart" hang when db container is stopped/broken. This is problematic. It probably doesn't happen a lot except when people use their own config and break things, but still, we need to be able to undertake these actions successfully even when a container is stopped (now that we don't auto-restart containers)

**Comment by rickmanelius** [comment]
I'm able to confirm the ability to `ddev rm` even when the DB is in a "db service stopped". See

```
Successfully started drupal7
Your project can be reached at http://drupal7.ddev.local and https://drupal7.ddev.local
➜  drupal-7.56 ddev exec -s db killall mysqld

➜  drupal-7.56 ddev list
NAME     TYPE     LOCATION                                 URL(s)                      STATUS
drupal7  drupal7  ~/git/drupal-7.56                        http://drupal7.ddev.local   db service stopped
                                                           https://drupal7.ddev.local

DDEV ROUTER STATUS: healthy
➜  drupal-7.56 ddev rm
Removing container: ddev-drupal7-web
Removing container: ddev-drupal7-dba
Removing container: ddev-drupal7-db
Successfully removed the drupal7 project.
➜  drupal-7.56
```

**Comment by rfay** [comment]
I can't recreate this problem either. Maybe was hospital wifi that hit me like https://github.com/drud/ddev/issues/717 ? But I thought I would have solved it by this time.

Closing.
