### ISSUE TITLE
Consider removing submodules used for nightly build (or moving containers into this repo)

### ISSUE THREAD

**Issue by rfay** [drud/ddev#722]
## What happened (or feature request):

Our submodules that we use only for the nightly build are apparently related to a bug in readthedocs. But we probably don't really need those. We could remove that feature from the nightly build and go forward. We could also consider moving the nginx-php-fpm-local and mariadb-local repos into this as subdirectories; this approach has not been too annoying to the hosting team.

**Comment by cweagans** [comment]
:+1: for merging the repos. Very in favor of this.

**Comment by rfay** [comment]
This was fixed in #727 

Followup actions in move image builds into ddev (#729) and Improve nightly build (#730)
