### ISSUE TITLE
Pantheon integration with "organization" site

### ISSUE THREAD

**Issue by jessehs** [drud/ddev#728]
## What happened (or feature request):
I first generated a machine token and added it using the "auth-pantheon" command. I then cloned the repo from Pantheon and navigated to its root directory. Then, I attempted to configure the project locally using the "config pantheon" command, which prompted me for the sitename. Typing in the sitename I got an error, "could not find a pantheon site named [sitename]".

## What you expected to happen:
I have successfully gotten ddev to do the "config pantheon" command on a different organization's website. When I attempt to do the "config pantheon" command with this particular site, however, I get the error message.

## How to reproduce this:
I'm hesitant to include more specific details publicly since it includes site names and ids of private organizations and repositories. However, I'd be happy to troubleshoot and provide more details privately. Reach out to me via my email (in my profile), and/or give me more debugging steps. This particular site is one site in an "organization" in Pantheon, and the site has not yet been launched (it has dev, test and live environments, but the DNS has not yet been switched over). I wonder if this is an idiosyncrasy in the Pantheon API due to this... Another quirk is that this site name ends with a number "1", so that could be causing a problem I suppose.

## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.

`ddev version`

cli   	v0.14.0
web   	drud/nginx-php-fpm-local:v1.0.0
db    	drud/mariadb-local:v0.7.1
dba   	drud/phpmyadmin:v0.2.0
router	drud/ddev-router:v0.5.0
commit	v0.14.0
domain	ddev.local

`docker version`

Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true

**Comment by rfay** [comment]
Thanks so much - I'll PM you - It would be awesome if it's possible to add someone else onto a failing site. We do have lots of people using pantheon, but not sure we've seen a number at the end of a pantheon site name, so could be something about that. 

Could you try using [terminus](https://pantheon.io/docs/terminus/), Pantheon's own setup, and see if you can see the site with that? If you can with terminus, and the API token for terminus is the same as the one you've configured for ddev, then we definitely have something to work on.

**Comment by rfay** [comment]
Just noting here that I sent you an email @jessehs so we can go forward with any discussion that needs to be more private over there.

**Comment by rfay** [comment]
Support on this one was carried out via email. It seems that the email address was not associated with the token @jessehs was using. There seem to be some complex ways you can grant permissions on Pantheon. But the bottom line is that the specific email address @jessehs was using needed to be granted access to the site on pantheon.

**Comment by rickmanelius** [comment]
Thanks, @rfay!

**Comment by rfay** [comment]
Thanks so much for following this through @jessehs - hoping it's working well for you now.

**Comment by jessehs** [comment]
Yes, thank you for the help. For the record, the issue was that I was granted access to an _organization_ on Pantheon that had multiple _sites_ associated with it. While this allowed me administrative access to all of the sites via the Pantheon interface, I needed to explicitly grant myself access to the _specific site_ in order for ddev to be able to work with it. This is done on the site-specific interface on Pantheon, by clicking the upper-left "Team" button. (See screenshot)

<img width="685" alt="screen shot 2018-03-13 at 11 34 32 am" src="https://user-images.githubusercontent.com/458586/37429624-837c153a-2795-11e8-9723-86a5a3178954.png">

**Comment by rfay** [comment]
Thank you so much for following up with the very clear docs on that. It will surely happen to somebody else in the future. Thanks!

**Comment by kreynen** [comment]
@jessehs 1 year later was getting `could not find a pantheon site named` errors on some Pantheon sites, but not others. The sites I was having issues with were all from the same organization.  I google `ddev pantheon organizations` and 30 seconds later, problem solved.

Thanks!

**Comment by jessehs** [comment]
@kreynen glad it helped!
