### ISSUE TITLE
Refactor command functions to move business logic out of cmd package

### ISSUE THREAD

**Issue by tannerjfco** [drud/ddev#73]
## What happened (or feature request):
The following command functions currently handle a lot of business logic that should be pulled out of the cmd package, and into either the platform package or another package as applicable. The command functions should then call the functions from the new package location to satisfy their functionality requirements.

- [x] exec
- [x] hostname
- [x] list
- [x] logs
- [x] ssh

## Related source links or issues (like source JIRA issue):
#71 
#72

**Comment by rickmanelius** [comment]
@tannerjfco Are these issues still a concern?

**Comment by tannerjfco** [comment]
At this point, all of the identified commands have been refactored. This is done!
