### ISSUE TITLE
Improve nightly build to build all PRs and build containers

### ISSUE THREAD

**Issue by rfay** [drud/ddev#730]
## What happened (or feature request):

In #722 we removed the git submodules that were used for a full nightly build, so now although we have a nightly build it does nothing more than a regular build. 

As a followup task we want to improve the nightly build to:

* Build all open PRs
* Build the containers and test with them.

**Comment by rickmanelius** [comment]
I'm assuming this is a relatively high priority to ensure our test coverage is meaningful.

**Comment by rfay** [comment]
Nice to have, but not sure it has to be super-high priority.
