### ISSUE TITLE
ddev ssh (or exec) hangs if any command retains stdout or other handles

### ISSUE THREAD

**Issue by rfay** [drud/ddev#732]
## What happened (or feature request):

We love ddev exec (and config hooks).

Unfortunately if any of our hooks invokes a command that holds stdout open, then all commands are permanently ruined and there's also no way to exit from `ddev ssh`.

## How to reproduce this:

Create this script in the project root, call it "runsomething.sh":

```
#!/bin/bash
tail -f /var/log/php-fpm.log &
```

Now `ddev exec ./runsomething.sh`, which will run that script in the container. it will never return (although ctrl-c will break successfully). 

Any additional `ddev ssh` or `docker exec -it <container> bash` will hang on exit.

## Related source links or issues:

I think this will be related to https://github.com/moby/moby/issues/33039 and/or https://github.com/moby/moby/issues/26403

**Comment by rfay** [comment]
The solution to this docker issue is to make sure that nothing is running that holds stdout or stderr open. So in the script above convert to:

```
#!/bin/bash
tail -f /var/log/php-fpm.log >/dev/null 2>&1 &
```

**Comment by rickmanelius** [comment]
Wow. Yeah I was able to recreate and it's basically a show stopper. You have to close your terminal to be able to ssh in again, but it also hangs on exit again.

**Comment by rfay** [comment]
Actually when you figure out how to do things "right" it's not a show-stopper, but it will sure impact our users, and I don't think we have options. Maybe.

**Comment by rfay** [comment]
Now that `ddev exec` is intended to provide interactive behavior, this one is obsolete. For example, you can `ddev exec "tail -f /var/log/supervisord.log"` and it will hang... as expected.
