### ISSUE TITLE
Report out Mailhog and phpmyadmin urls when starting ddev

### ISSUE THREAD

**Issue by BrianGilbert** [drud/ddev#733]
## What happened (or feature request):
Saw that phpmyadmin was there but didn't know how to access it.

## What you expected to happen:
Report out URL's to access any supplimentary services

## How to reproduce this:
```ddev start``` project, only shown URL to access website, not mailhog or phpmyadmin.

## Anything else do we need to know:
This would greatly simplify things for a new user.. It would also be great if it was possible to report out url's to access any othetr orchestrated services?

## Please use a complexity rating of 1-5 (5 is high) for a feature request. (High complexity implies more PR planning)
1-2

**Comment by rickmanelius** [comment]
This has surfaced a few times. One solution would be to run `ddev describe` immediately after a `ddev start` each time just to make this clear. Or we could just state "For more information about other running services, please run `ddev config`". I anticipate ddev describe growing over time, so I'd prefer to default to just highlighting this versus actual output.

Somewhat related #691

**Comment by rfay** [comment]
People are already overwhelmed by the number of URLs shown on start, so we've started scaling it back (to just https when possible, for example). So I think this one isn't going to fly; very few people use phpmyadmin, and people seem to use mailhog only when they really need it. Closing this for now, but happy to continue the conversation.
