### ISSUE TITLE
Wordpress settings creation improvements

### ISSUE THREAD

**Issue by rfay** [drud/ddev#742]
## What happened (or feature request):

Followup from https://github.com/drud/ddev/pull/693#issuecomment-373155492:

WordPress: Postpone the mirroring of the version control + local DB settings file for now. 

Discussion in #693 top comment:

> We need to replicate the pattern used for Drupal by defaulting to wp-config.php if it doesn’t exist and falling back to generating wp-config-local.php if #ddev-generated is not found in wp-config.php

**Comment by rickmanelius** [comment]
I think having @jdarrohn help on this would be helpful. He might be aware of WordPress best practices given all of his work with Nathan and Ben.

**Comment by alkymst** [comment]
One thing to note is that it seems `ddev config` wipes the `wp-config.php` even when you take it over completely, or DDEV no longer manages it. If we want to follow the same convention, then we should do a bit of a deeper dive of what should be going in here for WP and what happens currently.

`If wp-config.php does not exist, create it.
If a wp-config.php file exists that DDEV manages, recreate it.
If a wp-config.php file exists that DDEV does not manage, create wp-config-local.php.
If a wp-config-local.php file exists that DDEV manages, recreate it.
If a wp-config-local.php file exists that DDEV does not manage, warn the user and proceed.`

**Comment by alkymst** [comment]
Looks like it's being looked at already - https://github.com/drud/ddev/issues/756

**Comment by rfay** [comment]
Absolutely love it that ddev is being looked at by a WP expert, yay! We haven't had much traction in the world, and I know it shows.

**Comment by andrewfrench** [comment]
The discussion and resolution for this issue was in #932
