### ISSUE TITLE
Document settings file creation and what it means to users

### ISSUE THREAD

**Issue by rfay** [drud/ddev#743]
## What happened (or feature request):

Followup to #693 (moving settings files creation to start from import-db). We need to document when settings files are created and what it means to the user (and how they can override, etc. AFAIK this has never been in the docs.

@rickmanelius lists there these additional items:

* Getting Started. We should note the generation of these files alongside .ddev/config.yml. Example Addition: Also, if a Database configuration file doesn't already exist, it will be generated from a template.
* Import Assets. This will no longer need "Running this command will provide a prompt for you to specify the location of your database import". This should be deleted.

**Comment by rickmanelius** [comment]
@rfay I'm happy to take care of this within this PR. I found 3 areas that I think could be affected and briefly describe this here https://github.com/drud/ddev/pull/693#issuecomment-373803401.

**Comment by rickmanelius** [comment]
Blocker for the v0.16.0 because we need to ensure that end-users understand that we've changed this behavior. Should be a simple set of doc changes as well as a highlight in the release notes.

**Comment by rickmanelius** [comment]
Fixed in #752
