### ISSUE TITLE
Documentation for Arch users

### ISSUE THREAD

**Issue by ikit-claw** [drud/ddev#755]
If you get the are you sure Docker is running error.

First, restart if the issue persists the daemon will have stopped

systemctl start docker #will start docker again
systemctl enable docker #will allow it to autostart from now on. 

Add the user to the docker group

usermod -aG docker YOURUSERNAME

**Comment by rfay** [comment]
This is really all of Linux, the docs are at https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user. Added that as a task on https://github.com/drud/ddev/issues/754

**Comment by rfay** [comment]
And thanks so much for posting this important issue!
