### ISSUE TITLE
Make an easy way to populate environment variables in the web container

### ISSUE THREAD

**Issue by rfay** [drud/ddev#757]
## What happened (or feature request):

TYPO3 users often request a way to set environment variables in the web container. 

This is not hard to do with docker-compose.yaml, but we're really on course to take complete control of that file and recreate it on every start.

So we should provide a way to do it in config.yaml.

**Comment by kaystrobach** [comment]
suggestion:

beside the normal `nginx-site.conf` there should be an `nginx-env-vars.conf`

This file should have the same structure as `/etc/nginx/fastcgi_params` and could make it easy to add env vars ...

**Comment by rfay** [comment]
Nice work on this in https://github.com/drud/ddev/pull/758 - it probably can't go in there because it's not general enough (TYPO3-oriented) but it certainly explains one way to do it.

**Comment by kaystrobach** [comment]
not typo3 specific ... the composer package is just env vars ... and uses composer plugin architecture

**Comment by rfay** [comment]
When reworking our setup of docker-compose.yml in https://github.com/drud/ddev/issues/762 we can move away from using environment variables at all, and that will allow us to build a docker-compose.yml that populates the environment section more effectively.

**Comment by rfay** [comment]
Don't forget https://github.com/drud/ddev/pull/758 when working on this, it's an important specific approach.

**Comment by rfay** [comment]
Added a writeup in https://stackoverflow.com/questions/50109020/how-can-i-set-environment-variables-inside-ddevs-containers
