### ISSUE TITLE
DX: Check git branch tied to Pantheon multidev

### ISSUE THREAD

**Issue by nerdstein** [drud/ddev#764]
## What happened (or feature request):

Whenever I run the pull command from a Pantheon multidev environment, there is an assumption that the multidev correlates to a branch in Git.

DDEV has an opportunity to check the local branch to ensure it matches the branch in which the multidev is using.

## What you expected to happen:

I would like DDEV to tell me (a warning message possibly) if my local Git branch differs from the multidev branch when I run the pull command and I specify a multidev environment.

## How to reproduce this:

1. Git clone (you will likely be on branch `master`)
1. `ddev configure`, select pantheon and get the machine token set up
1. `ddev pull`, select a multidev to grab the database and files

The local branch for `master` is now out of sync with the database and files pulled from Pantheon's multidev environment. 

## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.

domain	ddev.local                     
cli   	v0.15.1                        
web   	drud/nginx-php-fpm-local:v1.1.0
db    	drud/mariadb-local:v0.8.0      
dba   	drud/phpmyadmin:v0.2.0         
router	drud/ddev-router:v0.5.0        
commit	v0.15.1 

## Please use a complexity rating of 1-5 (5 is high) for a feature request. (High complexity implies more PR planning)

1

**Comment by rickmanelius** [comment]
Hi @nerdstein. Again, thank you for taking the time to surface this and detail out your thoughts. I have a two hour block of time scheduled for backlog triage and sprint planning next Monday, so if I don't get to this today I will respond by then with questions/comments.

**Comment by rfay** [comment]
This hasn't gotten a lot of traction, or conversation, so closing for now. Happy to continue the conversation.
