### ISSUE TITLE
Add "export-db" command

### ISSUE THREAD

**Issue by ultimike** [drud/ddev#767]
I was surprised to find (or not find) a `ddev export-db` command (opposite of import-db).

Are there any plans to implement, or is the assumption that `ddev exec drush sql-dump` (for Drupal sites, at least) is sufficient?

thanks,  
-mike

**Comment by rfay** [comment]
I agree that would be really nice. What I currently do (on Drupal projects) is `ddev ssh` and `drush sql-dump --gzip >.tarballs/project_name_db.sql.gz` (I maintain a .tarballs folder in project root) But export-db would sure be nice! There are multiple other ways to do it too, using phpmyadmin, etc. But I'm with you!

**Comment by rickmanelius** [comment]
This is very much in alignment with my desire to have an import/export functionality as discussed here https://github.com/drud/ddev/issues/467. Leaving both issues open and linked until we determine which approach we adopt.

**Comment by rfay** [comment]
Just an FYI on what I currently do:

```
ddev ssh
mkdir /var/www/html/.tarballs
mysqldump db | gzip >/var/www/html/.tarballs/db.sql.gz
```

**Comment by rfay** [comment]
Marked this as actionable, it's very actionable and would be very useful to many.
