### ISSUE TITLE
PHP Storm plugin to start an already configured ddev env

### ISSUE THREAD

**Issue by kaystrobach** [drud/ddev#772]
## What happened (or feature request):

feature request

## What you expected to happen:

PHPStorm supports starting docker envs, vagrant and others out of the box.
It would be awesome to have the same ease of use for ddev as well.

![grafik](https://user-images.githubusercontent.com/1185776/38300178-6df7fd38-37fc-11e8-90ba-151f4c179a64.png)

## Related source links or issues:

* https://confluence.jetbrains.com/display/PhpStorm/Getting+started+with+Vagrant+in+PhpStorm

## Please use a complexity rating of 1-5 (5 is high) for a feature request. (High complexity implies more PR planning)

* 1 for an Java Developer
* 5 for a non Java Developer

**Comment by rfay** [comment]
It's a great idea! Thanks so much.

**Comment by kaystrobach** [comment]
@rfay i contacted a well known java dev from sgalinski already:

https://twitter.com/kaystrobach/status/981468270090969088

<blockquote class="twitter-tweet" data-lang="de"><p lang="en" dir="ltr"><a href="https://twitter.com/sgalinski?ref_src=twsrc%5Etfw">@sgalinski</a> can you estimate the amount of time to implement a <a href="https://twitter.com/hashtag/ddev?src=hash&amp;ref_src=twsrc%5Etfw">#ddev</a> phpstorm plugin? <a href="https://t.co/gOUkQO2dRt">https://t.co/gOUkQO2dRt</a> just for getting a reference … thank you … should not be that hard … 3 actions and some exec statements …</p>&mdash; Kay Strobach (@kaystrobach) <a href="https://twitter.com/kaystrobach/status/981468270090969088?ref_src=twsrc%5Etfw">4. April 2018</a></blockquote>

**Comment by cweagans** [comment]
I'm not sure we need a plugin for this, actually. PHPstorm has really great command line tool integration that allows you to define custom actions in a config file. It might be as simple as defining those actions in an XML file somewhere and calling it a day.

A plugin would certainly allow for a deeper integration (status reporting, a UI, etc) and would be really cool eventually, but the CLI support might be a good first step!

**Comment by kaystrobach** [comment]
I have searched for it can you point me to an example?

**Comment by kaystrobach** [comment]
Just found https://www.jetbrains.org/intellij/sdk/docs/tutorials/action_system/working_with_custom_actions.html

**Comment by kaystrobach** [comment]
Or do you mean https://confluence.jetbrains.com/plugins/servlet/mobile#content/view/51950913

**Comment by kaystrobach** [comment]
ok, just created one ...

* https://github.com/4viewture/ddev-phpstorm-cl-xml

Works, but esp. for some UX guys, who need to test a project quickly i would prefer a graphical solution.

**Comment by rfay** [comment]
We absolutely welcome community maintained tools that would integrate ddev with various IDEs, etc, but maintaining a PHPStorm plugin is not on our roadmap at this time. We're absolutely happy to link to community maintained projects of all types!  Closing this for now.
