### ISSUE TITLE
ddev stop and ddev rm need a way to execute without workspace 

### ISSUE THREAD

**Issue by rfay** [drud/ddev#78]
## What happened (or feature request):

I was trying to clean up sites/apps that were left running after tests and did not know where the related workspaces were. It led to a frustration that real users will have: "I want to delete an app but have no idea how".

## What you expected to happen:

I expect to be able to clean up without knowing arcane knowledge about where an app may be.

## How to reproduce it (as minimally and precisely as possible):

Try to delete an app when you don't know where the workspace is.

## Suggested resolution:

Allow `ddev stop` and `ddev rm` commands to take an argument, or alternately add a new command like vagrant's "global*" commands.

**Comment by rickmanelius** [comment]
Adding a needs decision flag because I know there was a larger discussion on what this looks like in terms of how to target it.

**Comment by rickmanelius** [comment]
This should have also been listed as a v0.7 milestone. Updating!
