### ISSUE TITLE
Poor handling of "sudo ddev hostname" - panic when sudo fails

### ISSUE THREAD

**Issue by rfay** [drud/ddev#780]
## What happened (or feature request):

Over in https://github.com/drud/quicksprint/issues/41 @jeolpittet reported what appears to be a perfectly obvious problem with `sudo ddev hostname` - We do a util.CheckErr() after it, which causes a panic and stacktrace, but the reality is that it can easily fail for various reasons (inadequate permissions, wrong password, etc). 

https://github.com/drud/ddev/blob/73517397dcc6707411a7c961d9fe8be146731ed2/pkg/ddevapp/ddevapp.go#L936-L937

**Comment by joelpittet** [comment]
Would one of these things help? https://blog.kowalczyk.info/article/wOYk/advanced-command-execution-in-go-with-osexec.html
(I don't know any go)

**Comment by rfay** [comment]
No this is just a simple coding error :) Somebody (probably me) never thought about the fact that the sudo attempt could fail for various reasons.
