### ISSUE TITLE
Add debug/verbose flag for visibility into problems

### ISSUE THREAD

**Issue by cweagans** [drud/ddev#782]
## What happened (or feature request):

Was helping debug a problem with ddev today, and the user noted that when ddev hangs, there's not really a good way to figure out why or how to fix it.

**Comment by rfay** [comment]
Normally when it hangs it's because of docker. Were they running 17.12? Just say no.

export DRUD_DEBUG=true

**Comment by rfay** [comment]
Of course DRUD_DEBUG wouldn't help at all currently if it's a docker-compose hang (as 17.12 did all the time). But we could enhance that or another flag to always say when docker-compose started and finished, and it would be a step forward. Kind of closing the barn door after the horse is out though.

**Comment by rfay** [comment]
We do have DRUD_DEBUG, and can implement it more, but mostly when we have trouble it's docker-compose, so that wouldn't help much. Closing until we come up with other ways to think about this.

**Comment by jigarius** [comment]
I've seen many apps use `-v` for `--verbose` and then `-V` for version. Just wanted to share that thought.

**Comment by rfay** [comment]
Could you please say what you're trying to work on @jigarius ? Some ddev commands have -v or --verbose.

**Comment by alesrebec** [comment]
I have a case where I have a complex Dockerfile and I would like to see what's going on in the background when it's trying to set up python, conda and some packages installed for 5 minutes.
It would be good to have ddev start or ddev restart with -v (--verbose) for that.
Only if there are errors I see the output but not if everything is "ok".

**Comment by rfay** [comment]
I don't know of a way to solve your problem @alesrebec at this time, because it's all done by the "build" in docker-compose. But the easy technique is to just practice all the things in your .ddev/web-build/Dockerfile by `ddev ssh` and do the lines one at a time. You'll quickly see what's taking the time.

**Comment by alesrebec** [comment]
@rfay thanks for the answer.
Can you check if you get anything out if you put --verbose before build.
(docker-compose --verbose build) <- in this order

https://nickjanetakis.com/blog/docker-tip-60-what-really-happens-when-you-run-docker-compose-up

**Comment by rfay** [comment]
We don't use `docker-compose build` but rather `docker-compose up` which does the build. You can actually do it yourself and see. `cd .ddev; docker-compose -f .ddev-docker-compose-full.yaml -v up` - give it a try. You can try build there also.

**Comment by alesrebec** [comment]
`docker-compose -f .ddev-docker-compose-full.yaml -v up
`
gives me docker-compose version

`docker-compose -f .ddev-docker-compose-full.yaml --verbose up
`
Doesn't work and returns an error:
```
ERROR: compose.cli.main.main: The Compose file './.ddev-docker-compose-full.yaml' is invalid because:
Unsupported config option for networks: 'default'
Unsupported config option for volumes: 'postgres'
Unsupported config option for services: 'postgres'

```

**Comment by rfay** [comment]
Yeah, you have to use docker-compose v2 to use that kind of yaml file, you must have v1. So you can use ~/.ddev/bin/docker-compose or else update your system docker-compose. If you use ~/.ddev/bin/docker-compose you'll know it's the right version.
