### ISSUE TITLE
FTP into container

### ISSUE THREAD

**Issue by testevez** [drud/ddev#784]
## What happened (or feature request):
Feature request: Transfer files into the container. My goal is to transfer a mysql dump file into the container so I an set up a second DB to test up a drupal 7 to 8 migration. 

## What you expected to happen:
1. transfer in my mysqldump
2. enter mysql command line to create a new DB _legacy_db_
3. run mysql -udb -pdb legacy_db < dump.sql
4. then go to mysite.ddev.local/upgrade and review

## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.
 
```
domain	ddev.local
cli   	v0.16.0
web   	drud/nginx-php-fpm-local:v1.2.1
db    	drud/mariadb-local:v0.9.0
dba   	drud/phpmyadmin:v0.2.0
router	drud/ddev-router:v0.5.0
commit	v0.16.0
```
```
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:06:22 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:14:32 2018
  OS/Arch:	linux/amd64
  Experimental:	true
```
```
APIVersion: "1"
name: atsnj8
type: drupal8
docroot: web
php_version: "7.1"
webimage: drud/nginx-php-fpm-local:v1.2.1
dbimage: drud/mariadb-local:v0.9.0
dbaimage: drud/phpmyadmin:v0.2.0
router_http_port: "80"
router_https_port: "443"
provider: default

# Certain ddev commands can be extended to run tasks before or after the ddev
# command is executed.
# See https://ddev.readthedocs.io/en/latest/users/extending-commands/ for more
# information on the commands that can be extended and the tasks you can define
# for them.
# hooks:
#   post-import-db:
#     - exec: "drush cr"
```

## Anything else do we need to know:
Sorry if I missed this info in the documentation, I read thru https://ddev.readthedocs.io/ and did not see relevant info.

**Comment by testevez** [comment]
Hmm never mind, I see something here that might work: https://ddev.readthedocs.io/en/latest/users/developer-tools/#database-connections-from-the-host

**Comment by testevez** [comment]
DDEV is awesome, thanks so much. Sorry to bother with this issue.

**Comment by rfay** [comment]
Yeah, that should work OK, but you'll need the root password. Use the info given in `ddev describe` and username=root, password=root to create a database. For example, (your port will be different)

```
mysql --host=127.0.0.1 --port=32841 --user=root --password=root
create database newdb;
```
then
`gzip -dc newdb.sql.gz | mysql --host=127.0.0.1 --port=32841 --user=root --password=root --database=newdb`

**Comment by testevez** [comment]
Thanks for this great comment @rfay !

**Comment by rfay** [comment]
Could you review https://stackoverflow.com/questions/49785023/how-can-i-create-and-load-a-second-database-in-ddev and see if it solves your problems?

**Comment by testevez** [comment]
Your last comment already solved it, i was able to add the 2nd DB with no issues.
