### ISSUE TITLE
include additional services (like solr) in ddev describe

### ISSUE THREAD

**Issue by tmotyl** [drud/ddev#788]
## What happened (or feature request):
I'm playing around with adding additional services to ddev, as described here:
https://ddev.readthedocs.io/en/latest/users/extend/additional-services/#apache-solr

I've followed the instruction, however the `ddev describe` is not showing the solr on the list of `Other services`

## What you expected to happen:
I would like to see url for accessing solr panel in the Other services section in ddev describe

**Comment by rfay** [comment]
Closed https://github.com/drud/ddev/issues/1623 as a duplicate of this one.

**Comment by rfay** [comment]
Related integration: clean up docker volumes owned by 3rd party services: https://github.com/drud/ddev/issues/1631

**Comment by rfay** [comment]
Finally @tmotyl ! Will be in v1.14
