### ISSUE TITLE
Duplicated additional hostname breaks ddev start

### ISSUE THREAD

**Issue by tmotyl** [drud/ddev#789]
## What happened (or feature request):
I have added an additonal hostname with the same name as project name. This prevented ddev from starting.

## What you expected to happen:
I would expect ddev to ignored duplicated name, or fail with a meaningful error saying what is wrong.

## How to reproduce this:
copy project name (`name` attribute value) to `additional_hostnames`
call `ddev start`

**Comment by rfay** [comment]
This is definitely true, is mentioned in the docs I think but it's worth solving and not too hard.

Also, of course, the name can't be duplicated among projects, that's a harder problem to solve.

**Comment by rfay** [comment]
What you see when this happens:
```
DDEV ROUTER STATUS: unhealthy
The router is not currently running. Your sites are likely inaccessible at this time.
Try running 'ddev start' on a site to recreate the router.
```

`docker logs ddev-router` shows

`"GET /healthcheck HTTP/1.1" 404 169 "-" "curl/7.52.1" "-"
nginx.1    | 2018/04/30 13:43:36 [error] 35#35: *233 open() "/usr/share/nginx/html/healthcheck" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /healthcheck HTTP/1.1", host: "localhost"`
