### ISSUE TITLE
ddev ssh does a poor job with long command lines and $TERM in general

### ISSUE THREAD

**Issue by rfay** [drud/ddev#799]
## What happened (or feature request):

When lines get long, `ddev ssh` starts to get really ugly, wrapping things wrong and messy. This is really from `docker exec`. 

[This docker issue](https://github.com/moby/moby/issues/33794) mentions an excellent workaround which we could just implement.

**Comment by mglaman** [comment]
> How to reproduce this:

Run `ddev ssh` and spam characters until they begin to overlap.

**Comment by rickmanelius** [comment]
Looks like this is a low-risk solution and it will help with nagging/annoying terminal usage.

**Comment by rfay** [comment]
Hope you can take https://github.com/drud/ddev/pull/804 for a spin @mglaman - thanks for the poke on this.

**Comment by tannerjfco** [comment]
Fixed by #804, for some reason this didn't close when that was merged

**Comment by rfay** [comment]
This doesn't seem to work on Windows, at least in the git-bash window or the CMD window.

**Comment by rfay** [comment]
This is still a little tweaky. The LINES and COLUMNS are set on `ddev start`, they don't seem to be reset on `ddev ssh`, which is pretty strange. So bottom line, if the window you're using is either the same (unresaized) or has the same size that you did the start from, things work right. But if you have a few windows of different sizes, doesn't seem to work right.
