### ISSUE TITLE
Patches defined by Composer don't always apply in container

### ISSUE THREAD

**Issue by ultimike** [drud/ddev#809]
## What happened (or feature request):
I have a composer.json file with a patch for a Drupal contributed module defined in the “extras” section.

When I run `composer update drupal/project_name --with-dependencies` using my host OS Composer, all is fine.

When I run the same command after `ddev ssh`ing into the container, the patch does not apply.
The error message is not super-helpful, `Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/...`

In chatting on the #ddev channel, @cweagans suggested that it could be an issue with the version of Git or Patch in the container. In my case, Git is 2.15.0 on host (Mac) OS, 2.1.4 in container and Patch is 2.5.8 on host (Mac) OS, not present in container. @cweagans said that "the plugin uses `git` if it's present, for sure. Having `patch` might be a good fallback, but if it doesn't apply with `git`, it usually won't apply with `patch` either."

## What you expected to happen:
The patch to apply.

## How to reproduce this:
I have a Drupal 8 site based on https://github.com/drupal-composer/drupal-project/, with the alpha4 version of Views Data Export module. I'm trying to apply this patch: https://www.drupal.org/files/issues/2018-04-20/views_data_export_format_path-2957085-19.patch 

## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.
0.17.0

## Anything else do we need to know:
@rfay had me install Patch in the container with `docker exec -it -u 0 ddev-<project>-web bash` and `apt-get update -y && apt-get install patch` to see if that resolved the issue. Which it did! Woot. @rfay indicated he'll have a pull request to fix this moving forward. (thank you!)

**Comment by donquixote** [comment]
I just had this happen to me, `patch` command is not installed by default in the container.
One way to fix is to add this to `.ddev/config.yaml` or '.ddev/config.local.yaml`:
```yml
webimage_extra_packages:
  - patch
```

>  @rfay indicated he'll have a pull request to fix this moving forward. (thank you!)

Of course this would be even better :)

**Comment by rfay** [comment]
Hmm, this is an issue from 2018.

The `ddev-webserver` image does in fact include `patch` at this point. 

```
rfay@MacBookAir:~/workspace/d11$ ddev exec patch --version
GNU patch 2.7.6
Copyright (C) 2003, 2009-2012 Free Software Foundation, Inc.
Copyright (C) 1988 Larry Wall

License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Larry Wall and Paul Eggert
```

If you can be specific about the actual problem you're having, and please give an actual example with an actual patch, we're happy to take a look. 

Please do open a new issue with the full reproduction scenario, thanks, and please include the requested `ddev debug test`

Thanks!
