### ISSUE TITLE
ddev import-db should drop all tables first

### ISSUE THREAD

**Issue by rfay** [drud/ddev#810]
## What happened (or feature request):

`ddev import-db` does not drop all tables before importing. This can lead to important problems for a few people. It should drop all tables.

**Comment by beeradb** [comment]
There are use cases where you do not want to drop all tables. The primary one that comes to mind is for people working on imports or migrations. It's fairly common to have data in tables in the Drupal DB which are not managed by Drupal.

We may very well want to do this change anyway, but it's worth thinking through use cases where having additional tables is 'normal'

**Comment by rfay** [comment]
It's not unusual to have data in tables that is not managed by drupal. It *is* unusual to do an import-db action (in any environment0 that ends up with data other than that which was provided in the import tarball.

I've been bit really, really badly by environments that do this wrong. The worst is a failed upgrade which leaves the new tables in place and then you try to start over with a clean db. Then the upgrade fails because the unexpected tables are still there.

**Comment by cweagans** [comment]
Sounds like maybe we could pick a default, and then add a flag to change it? e.g.: `ddev import-db --no-drop` or something to skip dropping tables?

**Comment by rfay** [comment]
Also, we had an issue where a `ddev pull` didn't successfully solve problems with a corrupted (or pre-mariadb 10.1) database. It really should. We should be building everything from scratch on a pull or import-db. 

IMO people can import one table at a time with many techniques, and it's an unusual requirement; import-db should blow away everything (even system tables) and start from scratch.
