### ISSUE TITLE
Add ".mysql" to allowable database extensions for import

### ISSUE THREAD

**Issue by jmarkel** [drud/ddev#812]
Databases that are exported from Drupal using the backup_migrate module are exported with the file extension "mysql.gz." Ignoring the gzip extension, DDev's import-db command accepts only "sql," not "mysql," as an extension, forcing the user to rename the file in order to import it.

Could you please add "mysql" as an acceptable database file-extension for import-db?

**Comment by rfay** [comment]
Sounds like a pretty reasonable request, thanks for making it.

**Comment by rickmanelius** [comment]
Related request that went stale https://github.com/drud/ddev/issues/516.

**Comment by jmarkel** [comment]
Thanks! Guess I'd missed the earlier one, since it was closed quite a while ago.
