### ISSUE TITLE
ddev-router failed to become ready: health check timed out

### ISSUE THREAD

**Issue by mdyoung3** [drud/ddev#814]
## What happened (or feature request):
Output from when I run ddev start:

ddev start
Restarting project pveducation... 
Stopping ddev-pveducation-dba ... done
Stopping ddev-pveducation-web ... done
Stopping ddev-pveducation-db  ... done
 
Removing ddev-router ... done
Network ddev_default is external, skipping 
Starting ddev-pveducation-db ...  
Starting ddev-pveducation-db ... done
Starting ddev-pveducation-dba ...  
Starting ddev-pveducation-web ...  
Starting ddev-pveducation-dba 
Starting ddev-pveducation-web ... done
 
Network ddev_default is external, skipping 
Creating ddev-router ...  
Creating ddev-router ... done
 
Failed to restart pveducation: ddev-router failed to become ready: health check timed out

## How to reproduce this:
Not sure how to reproduce it. Everything was working fine until it wasn't. 

My computer's OS is Fedora 27. First time it was installed, everything worked out of the box. Next time I started it, I got the above error. 

## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.
Docker version 18.04.0-ce, build 3d479c0
Ran the update script. Should be on the latest version of ddev.

## Anything else do we need to know:
I went through the troubleshooting page and ran all the recommendations therein. Nothing is listening on the 80 or 443 ports.

**Comment by rfay** [comment]
We've had a lot of recent trouble with Docker Edge, and are now recommending Docker Stable (18.03).

Things to try:

1. `ddev rm` all your running projects
2. `docker ps -a` to make sure all containers are gone.
3. Please delete the docker-compose.yaml in each project.
4. Please delete the "webimage" and "dbimage" lines in the config.yaml for each project. 

Have you added any additional_hostnames? If so, please remove them until you get it going. Just delete that line in your config.yaml. That is definitely a way to get this behavior.

To debug, if you're comfortable with linux, you can `ddev exec -it ddev_router bash` and inspect the /var/log/nginx/error.log

**Comment by mdyoung3** [comment]
I ran through those steps, but to no avail. 

When I ran `ddev exec -it ddev_router bash` I get this: `Error: unknown shorthand flag: 'i' in -it`

**Comment by rfay** [comment]
Sorry, my fingers were broken. Wow, did I fat-finger that.

What I thought you wanted was `docker exec -it ddev-router bash`... but skip that :) It doesn't help much.

Please try

`docker logs ddev-router`

If you see

```
*2 open() "/usr/share/nginx/html/healthcheck" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /healthcheck HTTP/1.1", host: "localhost"
```
It's likely a duplicate item in additional_hostnames.

**Comment by rfay** [comment]
I'd be super happy to take a look at this with you, sure want it to work for you. I'm normally in Drupal's #ddev Slack channel, pinged you there.

**Comment by rfay** [comment]
Closing this - no response. Happy to help if you come back @mdyoung3 

The only thing I've recently seen to break the router is the conflicting hostname problem, but would love to follow up on your problem here. Just return and comment and we can reopen it.
