### ISSUE TITLE
Add a ddev AUR repository

### ISSUE THREAD

**Issue by cweagans** [drud/ddev#818]
## What happened (or feature request):

Arch Linux users frequently use https://aur.archlinux.org to install packages that aren't in the core repositories. We should create a repo that installs the ddev binaries.

**Comment by cweagans** [comment]
I did this yesterday, but we need to figure out how/if we're going to to officially support it.

The info page is at https://aur.archlinux.org/packages/ddev-bin/. Right now, I'm the only maintainer on it, but I'm happy to add other people if you want. You can clone (read-only) from https://aur.archlinux.org/ddev-bin.git. To upgrade the version of ddev that is packaged, you just bump the version number in PKGINFO and update the sha256, commit, and push, and it gets repackaged.

It's difficult to provide exact instructions for using the package because everyone's setup is a little different. If you don't use an AUR helper, you can clone the AUR repo that I linked above, and run `makepkg -si` in the root of that repo. That will build the package and install it locally.

If you're using an AUR helper (for instance, I use `yay`), you can do `yay ddev` and it'll search AUR for any matching packages. If it finds one, it'll ask if you should install it. Under the hood, it performs the manual steps that I described above.

If we want to go further with this, we can also add a separate `ddev-git` package, which would be able to build, package, and install whatever is on `master` in our repo. This would make it very easy for arch users to help us test new features before they're released.

If we wanted to go crazy with it, we could hook the AUR repo into our build process and have the version and sha256 automatically updated and pushed to AUR so that new versions are available to arch users as soon as we tag them.

**Comment by rfay** [comment]
I guess you already created it, yay!

Questions are:
* Should it be community maintained or team maintained?
* How should it be documented? 

I'd suggest we might add a note to the installs pointing to it saying it's community-maintained?

I'm not terribly thrilled about having one more thing to do on a release, but guess that's inevitable.

It looks like it just needs a build trigger for each new release right?

**Comment by cweagans** [comment]
IMO:

* Mention the AUR repo in our docs in the install section
* Let the arch community maintain it. Realistically, I can handle this for the time being. It's literally 30 seconds of work to update on each release. If we want to automate it later, that's fine, but it'll take longer to automate than it will to do it manually for the next ~50 releases.

Arch users usually don't need a lot of hand holding in terms of how to use AUR, but we could also link to the Arch wiki page about the AUR: https://wiki.archlinux.org/index.php/Arch_User_Repository

**Comment by rickmanelius** [comment]
So basically...
* Create the repo.
* Get a working version for v0.18.0
* Wait for people to ping us in the aur repo or potentially open up to a co-maintainer to adjust per release?
* Note support in the docs https://ddev.readthedocs.io/en/latest/#system-requirements

Is this the acceptance criteria?

**Comment by cweagans** [comment]
Sounds good to me.
