### ISSUE TITLE
Get and implement windows code signing certificate

### ISSUE THREAD

**Issue by rfay** [drud/ddev#821]
_From @rfay on October 4, 2017 23:16_

## What happened (or feature request):

To send out trusted install packages for Windows we'll need a [code signing certificate](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate) which must be purchased.  Link to that page on https://www.electron.build/code-signing#where-to-buy-code-signing-certificate

There seem to be a variety of prices from the various vendors.

## Related source links or issues:

_Copied from original issue: drud/ddev-ui#34_

**Comment by rfay** [comment]
_From @andrew-c-tran on October 5, 2017 23:23_

According to electron-builder documentation (https://www.electron.build/code-signing#windows) we need either:

- EV Code Signing Certificate
- Code Signing Certificate

a code signing certificate will display a warning to the user until enough users have installed the app to build trust, at which point it'll stop showing to new installs. an EV code signing cert is more expensive, but will not show a warning ever. The drawback of the EV code signing cert though is that it's bound to a physical USB dongle, and thus will need to be physically attached to the machine that's doing the signing. This means no circle builds, so i'm not sure this route will work.

According to Microsoft, the certificate can be bought from a few vendors, such as DigiCert and Symantec:

https://www.digicert.com/friends/sysdev/
https://products.websecurity.symantec.com/orders/enrollment/winqualOrder.do

the EV Certificate can be bought from them as well:

https://trustcenter.websecurity.symantec.com/process/trust/productOptions?productType=EVCodeSigning&flavor=MSAuthentiCode&application_locale=VRSN_US&newLanguage=en
https://www.digicert.com/friends/sysdev/

We'll need to make a decision on the following points:

1) EV vs Standard Code Signing Certificate
2) Which Vendor to buy from (Symantec, Certum, Entrust, GlobalSign, DigiCert)

**Comment by rfay** [comment]
_From @andrew-c-tran on October 10, 2017 14:38_

any input @rickmanelius / @cyberswat ? The sooner we get an application in, the sooner we can get signing. I'm not sure how long the approval process is, but on mac it's quite the wait from what i've read.

**Comment by rfay** [comment]
_From @rickmanelius on October 10, 2017 14:58_

No input other than Kevin and I had overlapping PTO and I'm still catching up. Tagging as a blocker once https://github.com/drud/general/issues/137 gets in and we can triage/prioritize from there.

**Comment by rfay** [comment]
_From @cyberswat on October 10, 2017 15:51_

@rickmanelius just need to add this to the budget and proceed.  It's $449 per year if you buy it through digicert and pay 1 year at a time. $399x2 if you do it for 2 years, and $331x3 if you do it for 3 years.  The process for this is lengthy and will take a couple of weeks.  Let me know when we should start this process.

**Comment by rfay** [comment]
_From @rickmanelius on October 10, 2017 15:55_

Let's do one year!

**Comment by rfay** [comment]
_From @andrew-c-tran on October 10, 2017 15:57_

@cyberswat which cert are you looking at? The standard Code Signing Certificate is showing up at $267 for 3 years ($89 a year) and the EV Certificate at $497 for 3 years ($165.67 a year) through digicert for me?

**Comment by rfay** [comment]
_From @cyberswat on October 10, 2017 16:4_

 https://www.digicert.com/code-signing/ev-code-signing/ ... we started the order focusing on the per year cost.  Hopefully let's encrypt let's us sign these by the time next year rolls around.

**Comment by rfay** [comment]
_From @andrew-c-tran on October 10, 2017 16:16_

We might not want the EV cert. The EV cert is on a physical dongle and that means we will need a dedicated machine to sign our installers.

Also, MS directly linked me to https://www.digicert.com/friends/sysdev/ , which gets us 50% off as a developer. Not sure who would be buying a cert besides a developer, ha.

**Comment by rfay** [comment]
_From @rickmanelius on October 10, 2017 16:33_

Had a quick call w/@andrew-c-tran and @cyberswat. We'll just eat the cost of the EV and get the standard. Kevin may be following up with the need to get additional information.

**Comment by rfay** [comment]
_From @andrew-c-tran on December 5, 2017 22:42_

@cyberswat did we ever get this cert?

**Comment by rfay** [comment]
_From @cyberswat on January 31, 2018 23:59_

Placed an order for this. They are validating the address of the company.

**Comment by rfay** [comment]
_From @cyberswat on February 1, 2018 20:44_

@rickmanelius We changed our phone number which is leading to this response from them.  I'm not quite sure how to deal with this right now so I'm recording it here.

I am trying to finish the validation of your Code Signing certificate order for DRUD Technology, LLC and I need your help with just one thing:

To verify your phone number, please send a document such as a utility bill (telephone, gas, electric, water, or internet), bank statement, rental agreement, or any government issued document. You may block out any sensitive information as long as it shows your organization name (DRUD Technology, LLC) and phone number (8772288125). 

Send this document to support@digicert.com or fax it to +1-801-705-0481. Write "Validation #02558320" in the subject line.

Once we verify this, we will move to the next step of the validation process.

**Comment by rfay** [comment]
_From @cyberswat on February 1, 2018 21:35_

The address is on the bank statements, but not the phone number!

**Comment by rfay** [comment]
_From @cyberswat on February 5, 2018 19:12_

@pgalligan80126 Would our phone bill satisfy the conditions outlined above? Can you send me a copy outside of this issue if so?

**Comment by rfay** [comment]
@cyberswat Could you please let me know how this ended up? We need this for ddev Windows installer.

**Comment by rfay** [comment]
Moved this to ddev project, it's critical for our windows installer (although we can tell users about the workaround in the meantime). I scanned the issue for sensitive info and found none, so think it's ok to be in this public repo.

**Comment by rfay** [comment]
A TYPO3 user pointed out https://www.certum.eu/certum/cert,offer_en_open_source_cs.xml - Special cert offer for open-source projects.

**Comment by rfay** [comment]
That link is about $100. I will plan to take that path and expense it if we don't have progress on the previous approaches during this release cycle.

**Comment by rickmanelius** [comment]
Honestly, taking that approach will involve the least number of moving parts and just get it done... I'm fine with it.

**Comment by cyberswat** [comment]
@rfay you should do that if it moves this forward.  If that doesn't work I'll change the number so that I can answer it and then resubmit the order.

**Comment by rfay** [comment]
The open source cert above says "OPEN SOURCE CODE SIGNING CERTIFICATES ARE ISSUED ONLY TO NATURAL PERSONS!", so that means it couldn't be signed by DRUD Tech. Also, with courier cost, this ends up being about $142. Also, this is a not-too-fancy outfit in Poland that's issuing.

Do we want to go for it and just see how it comes out? I'd have to provide my own authenticating info like passport and stuff, and it would then be signed by me, as I understand it.

There's also no complete assurance that I'll be able to figure out how to sign the nsis installer.

**Comment by rfay** [comment]
Buying this would also not be useful for ddev-ui assuming its eventual release, if it's not open-sourced.

**Comment by cyberswat** [comment]
I *think* we have the correct certificate in Randy's hands.  It is a [Microsoft Authenticode Code Signing Certificate](https://www.digicert.com/code-signing/microsoft-authenticode.htm). It looks like [these instructions](https://www.digicert.com/code-signing/signcode-signtool-command-line.htm) provide a command line example of using it with an additional tool.

**Comment by rfay** [comment]
Yay, thanks @cyberswat ! Will be trying it over in https://github.com/drud/ddev/issues/840
