### ISSUE TITLE
Clean up /etc/hosts on ddev remove (remove unused hostnames)

### ISSUE THREAD

**Issue by peterkraume** [drud/ddev#831]
## Feature request:
Please add some automatic cleanup to remove unused hostnames from `/etc/hosts`.
When you use a lot of projects or test a lot, the `/etc/hosts` gets cluttered with all the hostnames.
It would be great if `ddev remove --remove-data` would also remove the hostname from `/etc/hosts`.
Or maybe you want to introduce another flag that triggers the removal of unused hostnames.

**Comment by rfay** [comment]
I definitely agree, thanks for bringing this up.

**Comment by rickmanelius** [comment]
I suggest `ddev hostname --clean-up`.

**Comment by andrewfrench** [comment]
I was poking around this issue last night and uncovered how the `ddev hostname` command is used internally to add hostnames, but doesn't provide support for removing hostnames, a prerequisite to cleaning up.  Considering the v0 status, how do we feel about adding some explicit subcommands to `ddev hostname`?

- `sudo ddev hostname add mysite.ddev.local 127.0.0.1`
- `sudo ddev hostname remove mysite.ddev.local 127.0.0.1`
- `sudo ddev hostname cleanup`

As a user, an "add this hostname" command implies an equal and opposite "remove this hostname" command, but that doesn't currently exist.

**Comment by rfay** [comment]
I'm good with this general approach @andrewfrench . It's all the easier since we rarely suggest that people actually use the `ddev hostname` directly.

**Comment by rickmanelius** [comment]
👍 `ddev hostname` is largely something that end-users shouldn't need to muck with directly despite the fact that we expose it, so that approach is fine by me.

**Comment by beeradb** [comment]
It's trivial to hide: 
https://github.com/spf13/cobra/blob/master/command.go#L74-L75

Might not be desirable though, as it looks like we're adding more functionality to it.

**Comment by rickmanelius** [comment]
@beeradb Yeah, I'm not super concerned about hiding it. Similar to import-files, even if 99% of users never use it, it is there and our top level command list isn't so large to be unwieldy (yet). So I would say leaving it visible for now is fine.
