### ISSUE TITLE
Consider adding rendering settings for settings.ddev.php for themer dev

### ISSUE THREAD

**Issue by seguinj** [drud/ddev#833]
## What happened (or feature request):
I would like to be able to work on my drupal theme without having to clear Drupal's cache to preview my changes.

If I enable development settings via settings.local.php file I get an error. Here is the pretty version from the Drupal log:

_Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException : You have requested a non-existent service "cache.backend.null". Did you mean one of these: "cache.backend.memory", "cache.backend.apcu", "cache.backend.php"? dans Drupal\Component\DependencyInjection\Container->get() (ligne 151 de /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php).
--_

## What you expected to happen:
I'd like to be able to theme in Drupal 8 using twig templates without having to clear cache everytime I'd like to preview my work. I'd like to be able to use Drupal's best practice for disabling caching.

## How to reproduce this:
I'm using ddev on Windows 10 which is working awesome! (Except for this little issue)

Copy and paste code from _example.settings.local.php_ into the _settings.local.php_ file which ddev has created. Clear Drupal's cache to apply the changes (I even tried running ddev restart). 

Load your dev website and you'll get an error (noted above). 

Note that when I comment out the following lines in the settings.local.php file, the site comes up :
#$settings['cache']['bins']['render'] = 'cache.backend.null';
#$settings['cache']['bins']['dynamic_page_cache'] = 'cache.backend.null';

## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.

DDEV VERSION
drud/nginx-php-fpm-local:v1.2.2
db      drud/mariadb-local:v0.9.0
dba     drud/phpmyadmin:v0.2.0
router  drud/ddev-router:v0.5.0
commit  v0.17.0
domain  ddev.local
cli     v0.17.0      

DOCKER VERSION
Using Edge version 2018-04-26 18.05.0-ce-rc1-win63
Engine: 18.05.0-ce-rc1
Compose: 1.21.0

** Using "Linux containers" (and NOT Windows containers)
** I have reproduced this issue with the stable version of Docker as well.

.DDEV/CONFIG.YAML
APIVersion: "1"
name: my-website-name
type: drupal8
docroot: web
php_version: "7.1"
webimage: drud/nginx-php-fpm-local:v1.2.2
dbimage: drud/mariadb-local:v0.9.0
dbaimage: drud/phpmyadmin:v0.2.0
router_http_port: "8090"
router_https_port: "443"
additional_hostnames: []
provider: default

**Comment by rfay** [comment]
Thanks for this issue - this is important and has been mentioned before; it should be pretty simple nginx config change. 

You *can* make the minor change in nginx as custom config; but this is important, thanks!

**Comment by seguinj** [comment]
OK - I figured it was a config change needed in nginx (I've never had any issues with Apache nor IIS out of the box).

Can you provide the steps required to apply the nginx custom config within ddev?

**Comment by rfay** [comment]
Custom nginx config docs: https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#providing-custom-nginx-configuration

We'd love to have your config when you get it going the way you want, we'll try to figure out how to either implement or at least provide to people as an option for when they're doing front-end dev like that.

**Comment by seguinj** [comment]
After some digging around, I've found my issue and it has nothing to do with ddev! :)

Here is the solution:

**1)** The issue relates to **Drupal 8.4 and above requiring a new configuration** in the settings.local.php file. 
_$settings['cache']['bins']['render'] = 'cache.backend.null';_

More details can be found here:
[https://www.drupal.org/node/2598914](https://www.drupal.org/node/2598914)

**2)** Making matters worse, a **front-end dev MUST be logged in Drupa**l in order to see the changes. An anonymous user does not refresh the cache automatically unless the cache is explicitly cleared (via Drush or a signed in user). This isn't very obvious nor does this seem to documented clearly anywhere (that I've seen). I'll add a note to the drupal.org page noted above and see where that takes us.

With the notes mentioned above, ddev works great with D8!

My only suggestion would be to include the default settings.local.php configuration below what ddev is currently providing for settings.local.php. This would make it easier for devs to go in and enable/disable the caching settings without having copy/paste the configuration lines required.

**Comment by rfay** [comment]
Thanks so much for this! We'll definitely consider just adding `$settings['cache']['bins']['render'] = 'cache.backend.null';` to the settings.local.php. I only worry that there might be side-effects of that for non-frontend-devs, but think it might just be fine.

**Comment by seguinj** [comment]
I agree about the side-effects. You could include the defaults which Drupal provides in example.settings.local.php and comment out all the lines that are active. Users could then just uncomment what they need when doing front-end local dev. 

Adding only the line  `$settings['cache']['bins']['render'] = 'cache.backend.null';` is not enough. 

At least another line would be requried:
`$settings['container_yamls'][] = DRUPAL_ROOT . '/sites/development.services.yml';`

And likely to kick off CSS and JS caching:
```
$config['system.performance']['css']['preprocess'] = FALSE;
$config['system.performance']['js']['preprocess'] = FALSE;
```

That's why I'm thinking best to just use what Drupal provides as a template and let users decide on what they need.

**Comment by rfay** [comment]
I'm pretty sure ddev shouldn't provide this option, it's the developer's job to add it as they need it, so closing.
