### ISSUE TITLE
Experiment with docker-sync to improve ddev performance

### ISSUE THREAD

**Issue by rfay** [drud/ddev#835]
## What happened (or feature request):

@tmotyl pointed out http://docker-sync.io/, which looks like it has some real performance possibilities. Although we've tried unison before (and it was unreliable) it was a year or more ago; also the key benefit here seems to be *native* macOS, so there's some real potential.

**Comment by cweagans** [comment]
For what it's worth, the `native_osx` strategy is functionally equivalent to https://github.com/cweagans/docker-bg-sync/, as far as I can tell.

**Comment by idziakjakub** [comment]
That would be great for Mac users!

**Comment by rfay** [comment]
First sadness is for Windows: https://github.com/EugenMayer/docker-sync/wiki/docker-sync-on-Windows says that the Windows support is only on WSL, Windows Subsystem for Linux, a lovely environment, but one on which we have yet to get ddev going.

**Comment by rfay** [comment]
Second sadness is for Mac: The default (best performance) technique has a whole page dedicated to "Debugging when it stops syncing", https://github.com/EugenMayer/docker-sync/wiki/8.1.-native_osx-sync-strategy-debugging-guide

**Comment by LionsAd** [comment]
FWIW, I tried the rsync strategy with docker-sync and it worked very well.

**Comment by rfay** [comment]
@LionsAd yay, could you please write a quick description of what you did (and on what host OS)? AND... SO LOVELY TO SEE YOU HERE!

**Comment by wizonesolutions** [comment]
@LionsAd I'm guessing the rsync is only one-way, though, so wondering how that would work with stuff like Fea...I mean config export :)

**Comment by rfay** [comment]
https://github.com/drud/ddev/pull/1277 is an attempt at using a fork of https://github.com/cweagans/docker-bg-sync/ to work for this purpose. It has great value once the initial sync is done, but the initial sync on D8 or TYPO3 can take a really, really long time, far longer than I'm willing to wait. But after it's done webserving is super fast.

**Comment by rfay** [comment]
This was completed in #1277 although we still will carry the work forward for Windows, especially if it's successful with our macOS crowd.
