### ISSUE TITLE
Using DDEV for the Drutopia Software Development Kit

### ISSUE THREAD

**Issue by cedewey** [drud/ddev#860]
Hi ddev team,

I've been impressed with the ease of use, performance and support of ddev. I'd like to learn more on how ddev might be able to help us with our [SDK](https://gitlab.com/drutopia/drutopia_sdk). Would someone be available to chat further about this? If there's any info I can provide ahead of that conversation let me know.

Thanks!

**Comment by rfay** [comment]
Happy to chat any time, always over in the #ddev room in Drupal slack, pinging you there.

**Comment by rfay** [comment]
Great to chat with you, check in any time. Closing.
