### ISSUE TITLE
Check and warn for low docker disk space (or memory)?

### ISSUE THREAD

**Issue by tannerjfco** [drud/ddev#863]
**Is your feature request related to a problem? Please describe.**
I was recently spinning up a ddev site when the web container failed its health check. I decided to `ddev rm -R` and `ddev start` to retry, and found the health check failed again. When I inspected `docker ps` for containers, I was surprised to find only 2 containers - router and phpmyadmin, instead of the expected 4 containers - router, phpmyadmin, web, and db. Further inspection with `docker ps -a` showed the missing containers exited almost immediately. Inspecting the web container logs revealed the issue: `envsubst: write error: No space left on device`.

Once you're able to determine the issue is due to low or no disk space, it's pretty easy to resolve. In my case, I simply upped the Disk space alotment in Docker for Mac in Docker->Preferences->Disk. `docker system prune` in addition to cleanup of unused images would also address this. However, it's quite likely that our users that are less familiar with troubleshooting Docker would be confused by this issue, as it is surfaced in a strange and unclear way initially.

**Describe the solution you'd like**

Ideally, it would be great to add a check to `ddev start` to check `docker system df` or an API equivalent, so that we could provide the user with a properly useful error message for the situation.

**Describe alternatives you've considered**

This could also be addressed by adding a section in our Troubleshooting documentation to cover this scenario.

**Additional context**

**Comment by rfay** [comment]
I haven't hit this, but have definitely hit the memory issue; I'm not sure how to check for that. Until yesterday we had [Warn user if docker resources might be under pressure ](https://github.com/drud/ddev/issues/512) open, but I just closed it based on not knowing what to do. At least with disk we *could* check.

**Comment by PapaGrande** [comment]
Could you grep the logs on failures for key phrases like "failed (28: No space left on device)"?

**Comment by rfay** [comment]
I wonder if there's a way to get docker to say what it's situation is. 

`docker system df` shows usage, but not related to available.

**Comment by rfay** [comment]
@PapaGrande as you see in the OP here, the message can be lots of things, like `envsubst: write error: No space left on device`

**Comment by PapaGrande** [comment]
Could you start with "No space left on device" and see if that catches the majority of cases?  Based on https://success.docker.com/article/no-space-left-on-device-error, it sounds like a standard message.

**Comment by rfay** [comment]
That's standard with the En-Us locale. Not sure what happens with Linux and different locale. I imagine it's different. The "no space left on device" is not a Docker error, but a Linux system error.

**Comment by rfay** [comment]
A recent incident like this reported from the ddev-webserver: "nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (28: No space left on device)" 

I'll try to track these in support so we can have better troubleshooting docs at least.

**Comment by UltraBob** [comment]
I just ran into this, and googling got me here.  It would definitely be helpful if the error message was more useful.

**Comment by rfay** [comment]
It turns out this is pretty easy to do:

```
testbot@rfay-m1-air junk % docker run -it --rm busybox df -h .
Filesystem                Size      Used Available Use% Mounted on
overlay                  94.2G      1.5G     87.9G   2% /
```

Just check the available space on any overlay filesystem.
