### ISSUE TITLE
ddev import-files with an invalid source path destroys sites/default/files

### ISSUE THREAD

**Issue by rfay** [drud/ddev#865]
**Describe the bug**

* A user did `ddev import-files --src=/sites/default/files` where /sites/default/files did not exist (on a Drupal 7 site)
* The result is an error `Failed to import files for ...: file not found. Please provide a valid asset path.` but it *also* destroys the project's sites/default/files, which ends up empty.

**To Reproduce**

On a Drupal 7 site:
* `ddev import-files --src=/sites/default/files`

**Expected behavior**

A simple error message of some kind.

Instead sites/default/files was emptied.

**Screenshots**

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: [e.g. Windows 10, macOS High Sierra]
 - Docker version information (use `docker version`) and insert it here.
 - ddev version information (use `ddev version`)
 - config.yaml contents for the misbehaving project
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

**Additional context**
Add any other context about the problem here. Thanks!

**Comment by jenlampton** [comment]
I had a similar experience:

* I did `cd sites/default` and then `ddev import-files --src=files` where `sites/default/files` DID exist (on a Drupal 7 site).
* The result is an error `Failed to import files for ...: destination already exists ` AND it also destroyed the project's sites/default/files, which ends up empty.

**Comment by rfay** [comment]
Put this down for Andrew and v0.19.0, but it's a natural thing to be solved in the refactor of import-files in #666
