### ISSUE TITLE
Allow 'partial' reconfiguration (ddev config that only updates empty values)

### ISSUE THREAD

**Issue by mlncn** [drud/ddev#866]
For [Drutopia](drutopia) we want to give as much of a head start as possible for people using the site.  At the least, that will mean setting the web directory.  But people will be starting different projects, so we can't configure the project name.  We'd like a start or configure command that just fills in the project name, and leaves the rest alone.

Basically we'd like to have everything set except the project name, which would be taken from the folder per usual.  @rfay had mentioned not allowing configuration of the project name, and just using the directory name, and that would also suit our purposes, although i will note of course that there are possible legal folder names (with underscores, for example) that aren't allowed for host names— but that could be easily handled with an error message to change ones folder name?  Not sure about subsequent folder name changes though.

Anyhow, our desire is to provide people with a project including a config file, but give as close to a one step start (or two step, config and start) that's just commands, not editing the config file. 

cc @cedewey

**Comment by mlncn** [comment]
Hmm... i got:

```
$ ddev config
You are reconfiguring the project at /home/mlncn/Code/sandbox/drutemptest. 
The existing configuration will be updated and replaced.
```

And then i got all the same prompts i did when running config the first time: Project name, Docroot Location, and Project Type.

Ah, ok, i can see now that while it prompts it *does* leave as the default the existing values (i hadn't changed them so didn't realize that) for project name and docroot location.  For project type, though, it was sent to drupal8 and it's defaulting to set it to php:

```
Found a php codebase at /home/mlncn/Code/sandbox/drutemptest/web. 
Project Type [wordpress, typo3, backdrop, php, drupal6, drupal7, drupal8] (php)
```

**Comment by rfay** [comment]
Yes, and if there are any items manually configured in the config.yaml (like ports or xdebug_enabled) they should be left alone.

**Comment by mlncn** [comment]
Given a better codebase to work from, however, `ddev config` tends to get everything right— name defaults to folder name (as long as there's no illegal character in it), it finds the web root, and gets the project type right.

Given that, i'd change this feature request to add the equivalent of drush's -y (yes) flag or the GNU standard -n (not interactive, no clobber) flag.

**Comment by rfay** [comment]
You'll also want to checkout `ddev config -h` for command-line flags.

**Comment by mlncn** [comment]
Ah i see i could pass them in... blank, and it'd be configured in one line?  Nope, that doesn't work.

Essentially, looking for promptless configuration.  Run something, presumably `ddev config` with some flag, and the defaults are automatically set.  So we hand someone a project base, tell them to set the folder name, and there's no need for them to look into the config file, or even have to hit 'enter' at prompts.

**Comment by rfay** [comment]
ddev config with any flag is promptless. If you start with a beginning .ddev/config.yaml (provided by you) and have them do `ddev config --projectname=myproject` it will keep anything you provided in the config.yaml, and override the project name. No prompt.

**Comment by mlncn** [comment]
Aha!  So we can leave the project name blank in the preconfigured yaml, tell people to run `ddev config --docroot web` (even though we already have the docroot set to web in the yaml), and it'll set the project name to the current directory.  There wasn't anything i actually wanted to set on the command line, except to keep the defaults, so i was trying the flags with blank or empty string but resetting something else to a known value to give the project name a chance to update works fine.

Thanks!

**Comment by rfay** [comment]
Yes, you can do that. I wasn't trying to talk you out of any of your suggestions, was just trying to make sure you knew the existing options.
