### ISSUE TITLE
ddev logs to provide only nginx error logs; instructions for advanced users on other logs

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#87]
This requires the containers to have logging enabled by default and the ability to access them. We don't have a top-level command stubbed out for this, so this would rely on `exec` for now.

**Comment by rickmanelius** [comment]
Ok. I have a fear that this can get complicated in a hurry. The challenge I have with the way we currently have this command setup is that there is no way to easily target a specific type of log within a specific service. For example, how would I target the nginx access log instead of the mysql error log?

So we could go a few routes. We could require `ddev logs SERVICE LOG-TYPE`, but that becomes tedious to type over and over again. We could also prompt users each time, but again that runs into the same issue of being tedious.

What if we stored a config in .ddev/config.yml OR an environment that defaulted the service and type to nginx error logs and reported that at the end of `ddev logs` with an instruction on how to change it. If a user then wanted to update their defaults, they could run something like `ddev logs -u` and then update their defaults. That way they can quickly run `ddev logs` each subsequent time as well as target individual logs by running the full command.

This might be too heavy a lift in the short term. Technically, viewing nginx error logs is helpful and we may wish to wait for feedback before we take this any further. However, if this is an easy lift, I think it would be very handy for quick targetting/debugging outside the container.

**Comment by beeradb** [comment]
Personally,  I would not try to get into "LOG TYPE" for this. Service seems adequate to me. If users want something beyond our standard container logging, I think we should direct them to interact with the containers directly.

**Comment by rickmanelius** [comment]
We're dropping "LOG TYPE" for now and only focusing on error logs for each service. This ticket needs to get updated a little further, but it's essentially actionable.

**Comment by rfay** [comment]
We are going to separate logs (normal on nginx) into the error and access logs, and `ddev logs` will just access the nginx error logs. 

No change is required to ddev AFAICT, just a minor change to nginx config in the container.

We may consider giving instructions to advanced users on how to use `ddev ssh` and `ddev exec` to access other log types.

**Comment by rickmanelius** [comment]
The documentation edits look great. So as soon as the functionality is in (if either @rfay or @beeradb test/approve, I'm good), we can get this one closed out. Thanks!

**Comment by beeradb** [comment]
I believe this can be closed?

**Comment by rfay** [comment]
Completed in https://github.com/drud/docker.nginx-php-fpm/issues/40 and https://github.com/drud/ddev/issues/186
