### ISSUE TITLE
Support custom TYPO3 folder structure

### ISSUE THREAD

**Issue by DanielSiepmann** [drud/ddev#879]
**Is your feature request related to a problem? Please describe.**
We are using the composer package https://packagist.org/packages/helhum/typo3-secure-web which will separate code and assets into two distinct folders for more security. This is not supported by ddev yet, as settings `typo3conf/*Configuration.php` is no longer inside of document root.

The reason is that the path is hardcoded in https://github.com/drud/ddev/blob/v0.18.0/pkg/ddevapp/typo3.go#L101

**Describe the solution you'd like**
DDEV should work with the default setup, as well as with custom configured folders. The paths are currently configured inside of `composer.json` and might be extracted from there: https://github.com/helhum/typo3-secure-web#configuration
This way you do not even have to configure the document root, as this is already configured in `composer.json`.

**Describe alternatives you've considered**
The only alternative right now might be to adjust the source code and re-compile.

**Comment by rfay** [comment]
Just a note - the edits that ddev wants to make to AdditionalConfiguration.php are entirely optional. You can manage them any other way you want. There are times that I think ddev shouldn't even participate in settings file manipulation because everybody does it differently at some point.

I don't think that reading composer.json to figure out information like this is going to be in our future, it's a very hard problem, since we support multiple CMSs.

**Comment by rfay** [comment]
We'd love to see a PR to drud/ddev-contrib explaining this use case!

**Comment by AMartinNo1** [comment]
IMO it's reasonable to support this because TYPO3 CMS in general is supported by ddev. In addition this particular project by helhum makes TYPO3 more secure.

A basic feature could be a flag: `disableGenerationOfAdditionaConfigurationFile: false`

**Comment by rfay** [comment]
Again, I'd love to see this, and would be happy to add explicit support. But to date nobody has come through with a tutorial or example or anything in ddev-contrib. Since I'm not a TYPO3 expert... and there were no comments on this issue for almost 2 years... it's waiting for action!

**Comment by AMartinNo1** [comment]
Fair enough. So let me push this a little at least:

What are your thoughts about introducing a flag or path? If possible `.ddev/config.yaml` feels like the right place.

**Comment by rfay** [comment]
I don't like adding CMS-specific flags or commands to ddev, because it adds complexity and confusion for all CMSs. I'd rather autodetect? Can that be done?

**Comment by gilbertsoft** [comment]
> 
> Today I learnt that TYPO [will most probably deprecate](https://github.com/TYPO3/CmsComposerInstallers/pull/127) the composer.json `app-dir` setting anyways. I wonder how that will work for `secure-web` but I guess that this is connected to upstream `secure-web`'s idea and improve the default TYPO3 directory structure security-wise by default?

fyi @jonaseberle typo3-secure-web is meant to die because we have direct support in the core for v11 now. The PR above will be merged soon and there will be a v4 alpha release so devs can give the composer compliant folder structure a try and fix their own extensions if needed.

**Comment by rfay** [comment]
If I understand right, this issue is obsolete, so closing, happy to continue the conversation and happy to reopen if needed.
