### ISSUE TITLE
As a developer, I want XDebug step-debugging support for IDEs like PHPStorm

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#88]
## What happened (or feature request): We need to provide PHP Step Debugging for ddev sites.

* There are two ways of doing step-debugging in PHPStorm, we'll need to explain both run/debug configurations and zero-configuration debugging approaches. They both work perfectly and immediately when host and container are configured properly.
* Requirements on the host:
    * Determining a usable port for the IDE to listen on. 9000 is often the default, but that often conflicts with a local php-fpm process. We may want to either use an oddball port, or else specifically test ports. *I propose we just use 10011 and hope it doesn't collide.*
    * Probably requires creating an extra interface on the host loopback interface so that there is a consistent IP address to hit from the container. See http://stackoverflow.com/a/39026136/215713 `sudo ifconfig lo0 alias 172.28.99.99`  *I propose we support only MacOS at this time and choose 172.28.99.99 as the add-on address.*
* Requirements on the container
    * Installing php7.0-xdebug (added in https://github.com/drud/docker.nginx-php-fpm-local/pull/10, currently available in drud/nginx-php-fpm7-local: 20170329_rfay_with_extra_tools)
    * detecting/creating a usable IP address for the host, so that the container PHP process can access the remote_host at remote_port. (Per above: Use the wired 172.28.99.99)
    * configuring /etc/php/7.0/mods-available/xdebug.ini with remote_host, remote_port (must agree with IDE settings) 
* Requirements for the IDE:
    * Configure the listen port chosen. (Languages->PHP->Debug)
* Requirements for ddev user interaction:
    * Notify user about how it's configured
    * Notify user about how to change the configuration
    * Path mapping so that server-side code can be mapped to project code.

Overall actions required:

- [x] Container updates and tools (xdebug package, xdebug config)
- [x] Documentation for PHPStorm and other leading IDEs
- [x] Manually test to make sure it works with more than one ddev site at the same time.

## Testing Instructions:

1. Build a site, configure it for ddev.
2. In your config.yaml use the WebTag 20170403_rfay_xdebug (or build ddev using `make clean && make WebTag=20170403_rfay_xdebug darwin`)
3. Experiment with the [instructions provided here](https://github.com/rfay/ddev/blob/197e25dd98b3db069afff95c53666cb81123fda1/docs/step-debugging.md)

**Comment by rickmanelius** [comment]
Given the PRs for the functionality (https://github.com/drud/docker.nginx-php-fpm-local/pull/11) and the documentation (https://github.com/drud/ddev/pull/124) have been merged, I think it's safe to call this done. Thanks, everyone!

**Comment by rfay** [comment]
When we come back to this and try to simplify it, it's worth looking at https://www.previousnext.com.au/blog/composing-docker-local-development-xdebug-osx
