### ISSUE TITLE
ddev_bash_completions.sh missing from release tarball

### ISSUE THREAD

**Issue by jeffsheltren** [drud/ddev#881]
The Getting Started CLI docs (`cli-usage.md`, very last section) say that `ddev_bash_completions.sh` should be in the release tarball, however I don't see it in the 0.18.0 release:

```
 ddev-0.18.0 $ find . -name ddev_bash_completions.sh
 ddev-0.18.0 $
```
If this is intentional, I'm happy to create a PR to update the docs.

I do have the bash completions present on OS X installed via brew, so no problem there.

**Comment by rfay** [comment]
You don't say which tarball you downloaded. The macos tarball has it, 
```
$ tar -tzf ddev_macos.v0.18.0.tar.gz
ddev
ddev_bash_completion.sh
```

And the linux tarball has it:
```
$ tar -tzf ddev_linux.v0.18.0.tar.gz
ddev
ddev_bash_completion.sh
```

I see - you're looking for it with an 's' in the name.  And I see that https://github.com/drud/ddev/blob/f9a31bb7e33727eed8f238efd64ae9968b5a36e6/docs/users/cli-usage.md does have it wrong. Thanks! And a docs PR removing the 's' would be lovely! Of course we can get that done pretty easily too. Low hanging fruit!

**Comment by jeffsheltren** [comment]
Thanks for checking @rfay! I was mistakenly looking within the **source** tarball, which is why I didn't see it. Docs clearly say **release** tarball...

I created #882 to remove the 's' from the filename in the docs.
