### ISSUE TITLE
Bundle PimpMyLog (as with MailHog or phpMyAdmin)

### ISSUE THREAD

**Issue by hexblot** [drud/ddev#885]
**Is your feature request related to a problem? Please describe.**
Nope, it's purely DX bonus to allow logs (same as per `ddev logs -f`) to be exposed on a non-CLI context.

**Describe the solution you'd like**
"[PimpMyLog](http://pimpmylog.com/) is a web app written in PHP. It displays server logs friendly."
It's basically an auto-refreshing log viewer, that can easily work with the existing stack.

**Describe alternatives you've considered**
`ddev logs -f` does the trick, but is messier (due to different log file concatenation to keep it all in one stream). PML provides a better experience.

**Comment by rfay** [comment]
This would mean having to have php available on the host, right? Because ddev doesn't assume that.

**Comment by hexblot** [comment]
I suppose the same strategy as per phpMyAdmin should be followed - though it only requires PHP5.2+ and a base config for log files to monitor.

**Comment by rfay** [comment]
Closing this for now, we appreciate you bringing this to our attention, but it doesn't seem like something we'll act on in the near future.
