### ISSUE TITLE
Determine best method for support container versions

### ISSUE THREAD

**Issue by beeradb** [drud/ddev#9]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

**Information**:
There is no way to specify nginx/mysql container versions except via the command line. It'd be nice to be able to commit this config so that it could be shared across a team. There's also no way to control templating for docker-compose.

Prior art:
https://github.com/docksal/drupal8/blob/master/.docksal/docksal.env#L11
http://docs.kalabox.io/en/v2.1/users/started/#kalabox-apps

**Related Issues**
This is a part of larger site configuration concerns, alongside #7 and #5. It feels like a single config file/format that could accommodate them all could be in order.

**Deliverable**: 
A proposal outlining a configuration method for containers and application templates, including a sample configuration.

**Comment by rickmanelius** [comment]
@beeradb Given that .ddev/config.yml contains these, I'm assuming this can be marked duplicate/closed?

**Comment by beeradb** [comment]
Yes, this should be good at this point.
