### ISSUE TITLE
Support Acquia Cloud as provider

### ISSUE THREAD

**Issue by wizonesolutions** [drud/ddev#905]
This issue is for me to manage trying to add this feature (and maybe get some help).

**Describe the solution you'd like**
`ddev config acquia_cloud` should work, similar to `ddev config pantheon`. `ddev pull` should then pull the database and files for the requested environment and site (specific site needs to be configurable in the case of multisite installations).

**Describe alternatives you've considered**
Manual DB/file download/import.

**Additional context**
I got the project cloned, and I more or less understand what integration points I have to cover...but I need to study the code more first when I have some time. I don't really know Go yet, so I'm sure it's going to be messy, but I'm going to try anyway. I do understand the Acquia Cloud API fairly well, so that shouldn't be a major issue.

**Comment by rfay** [comment]
Excellent, thanks!

**Comment by wizonesolutions** [comment]
(For the record and the readers: I'm not working on this feature atm.)

**Comment by cyberswat** [comment]
Thanks for the update.  This may be one we can move forward in the first part of this year.

**Comment by jameswilson** [comment]
Just stumbled across this issue and wanted to link it to #2681 a homegrown solution.  I think there are probably better ways to do this, but this is where we left it for now, with just a custom bash script.  I don't know the LOE to make this work with the `ddev config` command.

**Comment by rfay** [comment]
The new Acquia integration made it into ddev v1.17.0-alpha5, I hope you'll all try it out, https://github.com/drud/ddev/releases/tag/v1.17.0-alpha5
