### ISSUE TITLE
As a developer, I want the ability to use phpMyAdmin.

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#91]
## Acceptance Criteria

* Connection details accessible in ddev describe
* Documentation on usage.

## Testing Criteria

* Reaching the URL:port for php admin should return a 200.
* There should be a means to confirm phpMyAdmin is serving properly (perhaps attempt to pull a 200 response directly from index.php).

**Comment by beeradb** [comment]
Closed out with #144!
