### ISSUE TITLE
Add a command to open an app in the browser

### ISSUE THREAD

**Issue by andrewfrench** [drud/ddev#910]
**Is your feature request related to a problem? Please describe.**
Opening an app URL in the browser requires clicking or copy/pasting a link.

**Describe the solution you'd like**
It'd be great if I could open an app in the browser directly from the terminal using a `ddev` command like `ddev launch [appname]` or `ddev browse [appname]`, launching the current active app if no name is provided.

**Additional context**
Most (all?) operating systems provide a utility that can be provided a URL (and more), determine the user's default browser, and launch the page.  For example:

- darwin: `open http://wikipedia.org`
- linux: `xdg-open http://wikipedia.org`
- windows: `start http://wikipedia.org`

A prototype of this functionality using `ddev launch` can be experimented with [here](https://github.com/drud/ddev/compare/master...andrewfrench:2018-06-04_browser-command).

**Comment by rickmanelius** [comment]
Somewhat related to #375.

**Comment by jigarius** [comment]
Maybe have a list of choices?

```
ddev launch
OR ddev launch --browser=firefox

1. http://example.com/
2. https://example.com/
3. http://127.0.0.1/
4. http://127.0.0.1/

$Enter the URL you want to launch [1]: 2
Launching https://example.com/
```

**Comment by ultimike** [comment]
I was just thinking about how this would be a great command to have. I often find myself doing the following:

1. `ddev describe`
2. Crtl-click on the URL, then click "Open Url" (on Mac OS X)

I think it would be pretty great to just be able to do something like `ddev launch` that opens the default URL (https) in the user's default browser. @jigarius's idea of using switches to change URL and/or browser is a nice addition, but for me, simple and clean work best.

-mike

**Comment by rfay** [comment]
This is such a simple custom command. Time to just add it in that way.
