### ISSUE TITLE
Full Azure/MacStadium/Buildkite setup for ddev testing

### ISSUE THREAD

**Issue by rfay** [drud/ddev#911]
We're in the process of building out a full new testing system for macOS and Windows. 

The key issues are:

- [x] Moving macOS testing to MacStadium
- [x] Moving build orchestration to buildkite
- [x] Moving Windows testing to Microsoft Azure
- [x] Process and docs for buildkite
- [x] Process, docs, and access credentials to Azure

A writeup of the budget issues is in [gdocs](https://docs.google.com/document/d/1LTkeaI1MrAOyGWcWO06BFBAhSMBeN_T9QyLGtVhwsEk/edit?usp=sharing)

Much of the windows work is in [Windows 10 Home testing](https://github.com/drud/ddev/pull/902) PR.

We still have to get MS Azure instances properly set up and appropriate people signed up to manage them. That will have to be spun off into another issue.

**Comment by rfay** [comment]
As far as moving our testbots on Azure to a drud account, we don't have to do that for a couple of weeks, because my free credit and first-month's MSDN have us covered for June I think. So we don't have to hurry to do it.  I've given access to @andrewfrench and we'll take a tour today, and possibly set up another testbot, and we'll come up with a strategy for when they should be shut down to save money.

**Comment by rickmanelius** [comment]
Thank you for getting this provisioned, @rfay! I'm tagging @pgalligan80126 on this to assist with getting any payment credentials into the account so that there are no blockers when we are ready to transition this over.

**Comment by pgalligan80126** [comment]
The updated CC is in mac stadium.  Please let me know if you need anything else @rfay @rickmanelius

**Comment by rfay** [comment]
Thanks @pgalligan80126 - I noted that the recurring card for the new one provisioned today had newmedia steve's name on it.

**Comment by rfay** [comment]
This ticket is good enough for now. Andrew has credentials for everything and has had a tour. We'll need to move Azure to company-owned instances later in June. But ongoing work is just maintenance.
