### ISSUE TITLE
Add more topics to DDEV project 

### ISSUE THREAD

**Issue by nearlythere** [drud/ddev#915]
**Is your feature request related to a problem? Please describe.**

Make it easier for people browsing GitHub to find DDEV

**Describe the solution you'd like**

https://help.github.com/articles/classifying-your-repository-with-topics/

Add these topics:

docker
nginx
php
mariadb
docker-compose
php7
php71
php72
php-docker-stack
php-on-windows
local-development

**Comment by rfay** [comment]
I did this. There's a limit of 20 topics, so I had to use some discretion and do some editing. Thanks!
