### ISSUE TITLE
[QUESTION] Setup two vhosts in one ddev

### ISSUE THREAD

**Issue by sidferreira** [drud/ddev#917]
I'm just starting using ddev, but there's a need that is around having two websites running in parallel using the same db.
I see I could use two WEB containers for that, but it would use extra memory.
I checked some files and seem that ```{{ range $host, $containers := groupByMulti $ "Env.VIRTUAL_HOST" "," }}``` in https://github.com/drud/ddev/blob/2d3bab3c4e893bbc441e9d7f3f6fce0a1d5b908c/containers/ddev-router/nginx.tmpl could do it, assuming I understood the code properly.
So, with that in mind, can you help me to run this two sites at the same time?

**Comment by sidferreira** [comment]
Found out we can create a `.ddev/nginx-site.conf` to add custom configs

**Comment by rfay** [comment]
Not sure you noticed that we allow additional_hostnames in the config.yaml, so you can hit it with as many hostnames as you want. In the near future we'll also allow completely random (non-ddev.local) hostnames as well.  https://ddev.readthedocs.io/en/latest/users/extend/additional-hostnames/

**Comment by sidferreira** [comment]
@rfay yes I did, but I wanted another VHOST actually. Managed it in the end 👍
