### ISSUE TITLE
Allow a user to issue root commands from ddev

### ISSUE THREAD

**Issue by andrewfrench** [drud/ddev#918]
**Is your feature request related to a problem? Please describe.**
We provide users a way to execute arbitrary commands on a container, but we offer no way for a user to execute a command with root privileges.  A user can still do this, but it requires a user to work around `ddev` (instead of with it), requires some specific Docker knowledge, and can't be integrated with `ddev`'s native tooling.

**Describe the solution you'd like**
`ddev exec` already handles issuing commands within a container -- we can add an optional flag indicating the command should be executed as root:

`ddev exec -R <command>`

It'd be a good idea to alias `ddev exec -R` to something like `ddev rexec` so a root command can be issued in an event hook from `config.yml`:
```
hooks:
  post-start:
    rexec: <command_1>
    rexec: <command_2>
```

**Describe alternatives you've considered**

**Additional context**

**Comment by rfay** [comment]
Of course for occasional usage, we can just document the use of `docker exec -u root -it ddev-<project>-web bash` for this use case. I think it's a common-enough problem to address though.
