### ISSUE TITLE
Ability to add additional packages to web container

### ISSUE THREAD

**Issue by mglaman** [drud/ddev#919]
**Is your feature request related to a problem? Please describe.**

We use GravCMS with TNTSearch, which requires SQLite. When I configured ddev I got the following page:

<img width="993" alt="whoops_there_was_an_error_" src="https://user-images.githubusercontent.com/3698644/41358469-084ab8da-6eee-11e8-956c-9613a3ee4754.png">

```
[2018-06-13 08:23:25] grav.CRITICAL: could not find driver - Trace: #0 /var/www/html/user/plugins/tntsearch/vendor/teamtnt/tntsearch/src/TNTSearch.php(90): PDO->__construct('sqlite:/var/www...') #1 /var/www/html/user/plugins/tntsearch/classes/GravTNTSearch.php(53): TeamTNT\TNTSearch\TNTSearch->selectIndex('grav.index')
```

**Describe the solution you'd like**

I would like a way to have extra PHP extensions available for install and to enable (like pdo_sqlite)

**Describe alternatives you've considered**

None.

**Additional context**

**Comment by rickmanelius** [comment]
Related issue https://github.com/drud/ddev/issues/920.

**Comment by rickmanelius** [comment]
Also addressable with this one https://github.com/drud/ddev/issues/918 related to being able to run sudo commands within the containers.

**Comment by mglaman** [comment]
I was going to reference it to the `sudo` issues. But I feel this should be part of the config and more magical

**Comment by rickmanelius** [comment]
Fair enough and yes, I believe in magic... :)

**Comment by rfay** [comment]
Currently, you could use `docker exec -u root -it` to accomplish this. It's a bit of an awkward workaround, but it does in fact work.

**Comment by rfay** [comment]
I don't think the basic need though is for php extensions (as long as we're talking about apt-packaged extensions - the basic need is for extra packages via apt-get.

**Comment by rfay** [comment]
What we're going to do is support sudo in the container, so anybody can put whatever they need in there. https://github.com/drud/ddev/pull/935 - that indirectly fixes this.
