### ISSUE TITLE
Allow user additions to bashrc in web container

### ISSUE THREAD

**Issue by klonos** [drud/ddev#926]
**Is your feature request related to a problem? Please describe.**
Coming from https://github.com/beetboxvm/beetbox I have gotten used to have the `ll` command (short for `ls -la`) available OOTB when I ssh into the VM. With ddev, I have to type the whole command, which is an annoyance.

**Describe the solution you'd like**
I would like it if `ll` worked out of the box when I ssh to the VM.

**Describe alternatives you've considered**
I can set up the shortcut inside the VM, but having to do this every time I destroy/rebuild a VM is really tedious.

**Comment by rfay** [comment]
I think we should probably have a directory that auto-mounts if it exists, and have the container's .bashrc include scripts in there. That way every request like this could be resolved by the user.

**Comment by rfay** [comment]
I changed the title to a more generic solution. I propose that we add .ddev/bash_profile and .ddev/bashrc handling to the container's .bash_profile and .bashrc, so those get included. That way every project can have custom bash setup as needed.

**Comment by johndwells** [comment]
+1 for this please.

**Comment by rfay** [comment]
From https://github.com/drud/ddev/issues/1459 - host gitconfig would be completely reasonable here also.

**Comment by rfay** [comment]
@pcambra requested ~/.ssh/config configuration...

**Comment by rfay** [comment]
Another related request: Keep bash history around.

**Comment by rfay** [comment]
Related: Request for composer auth file in #1641
