### ISSUE TITLE
Make ddev updates more visible

### ISSUE THREAD

**Issue by hexblot** [drud/ddev#933]
**Is your feature request related to a problem? Please describe.**
If one of the team upgrades ddev to a newer version (in this case, 0.19), and they update the ddev config in the repo, things can potentially break for developers who didn't know/still have the old version (esp when dealing with custom scripts that get executed post-start).

**Describe the solution you'd like**
If ddev finds a greater config version than the currently installed one ( eg, in our case, config v0.19 and installed version 0.18), throw a big prompt that there is an update available, and since your config file is from that (newer) version, require it (ideally, do not allow the enviroment to start unless updated, but that may be too drastic for some). 

Alternatively, find a way to show in the CLI that there is a new version that is visible enough (ie not just a single line within a wall of text).

**Describe alternatives you've considered**
-

**Comment by rfay** [comment]
Great idea, thanks. Our thinking was focused on updating the *config.yaml* after ddev was installed.

Currently in the situation you describe ddev does this, focusing on updating the config.yaml:

```
Your .ddev/config.yaml version is v0.19.0, but ddev is version v0.18.0.
Please run 'ddev config' to update your config.yaml.
ddev may not operate correctly until you do.
```

I'm interested that you commit the config.yaml apparently? Has that helped you in general?

**Comment by hexblot** [comment]
We commit config.yaml since it has a number of pre/post start tasks that bootstrap the dev enviroment (the current flow is `git clone`, `ddev start` and that takes care of `composer install`, downloading other prerequisites, registering the dev enviroment, and enabling D8 demo content modules). We also commit `docker-compose.redis.yaml` and `my.cnf` / `php.ini` customizations.

That is also the reason why the message you mention is way too easy to miss -- once `ddev start` is run, there's a huge wall of text from all the things that happen, and as such we only pay attention to it if something actually goes wrong. 

One of the devs is having issues with `drush` (which is why we started looking into the wall) and noticed the above message you mention.

I don't know if this is best practice, until now we have a Vagrant/Ansible combo that works very well...until things get updated and start to break.

**Comment by rfay** [comment]
Thanks for the response! We originally expected people to commit config.yaml (and really, with post- steps it's really important to do that). But until recent releases where the container versions were removed from the default config.yaml, it caused more update trouble than it was worth. But now that we're rid if the `webcontainer` and `dbcontainer` statements in the config.yaml, it really probably is best practice to commit the config.yaml, or perhaps the whole .ddev directory. Thanks for the feedback!

**Comment by rfay** [comment]
Teams are often committing config.yaml these days, so only one person is in charge of updating it. 

These changes have been made to resolve this problem:
* config.local.yaml can be used for local developer overrides of the config (and not checked in)
* The ddev settings file (settings.ddev.php) is now created on start as well as on config, so developers who are *not* in charge of running ddev config can just `ddev start` and go.

If I'm not mistaken these changes solve the basic problems you had encountered, @hexblot , but please continue the conversation here if I'm wrong. Closing for now.
