### ISSUE TITLE
Allow user-provided general extensions/plugins (not just provider plugins)

### ISSUE THREAD

**Issue by jdoubleu** [drud/ddev#937]
I couldn't find any previous discussion on this.

**Describe the solution you'd like**
With v0.9 provider plugins were introduced (see https://github.com/drud/ddev/wiki/roadmap#previous-releases) but for now they have to be implemented in the ddev project and are hard-coded into the providers command (compare https://github.com/drud/ddev/blob/master/pkg/ddevapp/ddevapp.go#L1157-L1167).

I'd like to be able to write my own plugin (not limited to provider plugins), compile it with go's `-buildmode=plugin` flag to get a shared library and let ddev import/load this library and use it.

This would allow a developer to extend ddev not only with 3rd party provider plugins but with any kind of components. I can think of additional commands, etc.

**Additional context**
Maybe this requires additional refactoring of the current code-base, but I'd happy to contribute.

**Comment by rickmanelius** [comment]
Hi @jdoubleu This is a fantastic request and quite timely! In the upcoming months, we're focusing more on additional provider plugin implementations (we're more in the planning phase at this point before we have something actionable and scheduled). Going to add some labels and I'll try to get a better sense of when this can be addressed and loop you into that discussion.

**Comment by gusaus** [comment]
Sounds like this would be an ideal way for developers to incorporate DDEV into other providers. Also could provide opportunities to collaborate with other OSS projects and communities. Setting up DDEV and joining the OpenCollective community could be a great way to help facilitate both. https://opencollective.com/opensource#about

**Comment by rfay** [comment]
This hasn't gotten any traction, closing, happy to continue the conversation!
