### ISSUE TITLE
accessing a domain of shut down containers/projects should throw an error

### ISSUE THREAD

**Issue by tmotyl** [drud/ddev#942]
**Describe the bug**
Given you have multiple ddev projects. project-one is running and project-two is not. When accessing domain project-two.ddev.local will render a project-one page.
This is error prone especially when working with similar project, user might not be aware that he is interacting with wrong container.

**Expected behavior**
I expect to see the error.

**Version and configuration information (please complete the following information):**
 - Ubuntu 16.04
 - Docker version 18.03.1-ce, build 9ee9f40
- ddev version
router	drud/ddev-router:v0.5.1        
commit	v0.18.0                        
domain	ddev.local                     
cli   	v0.18.0                        
web   	drud/nginx-php-fpm-local:v1.3.0
db    	drud/mariadb-local:v0.9.0      
dba   	drud/phpmyadmin:v0.2.0

**Comment by rfay** [comment]
I have not seen this behavior, just tested (Start two sites, then stop one) and I got the expected "No ddev back-end site" message. Tested with v0.19.0, but no changes have been made here.

Could you recreate this with a specific step-by-step set of instructions? It's possible this is a symptom of https://github.com/drud/ddev/issues/623, but I wasn't able to recreate with a naive approach.

<img width="777" alt="503__no_ddev_back-end_site_available" src="https://user-images.githubusercontent.com/112444/41914524-a256acbe-7910-11e8-84bf-1f50f3e61964.png">

**Comment by rfay** [comment]
I think this works as expected `503 no ddev back-end site". Closing, but happy to continue the conversation here!
