### ISSUE TITLE
Unable to import database after update to 0.20.0

### ISSUE THREAD

**Issue by jenlampton** [drud/ddev#946]
**Describe the bug**
the command `ddev db-import` fails after update to 0.20.0 with the error:
```bash
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES) 
Failed to import database for site01: Failed to run docker-compose [-f site01/.ddev/docker-compose.yaml -f site01/.ddev/docker-composer.drush.yaml -f site01/.ddev/docker-composer.ssh.yaml exec -T db bash -c mysql --database=mysql -e 'DROP DATABASE IF EXISTS db; CREATE DATABASE db;' && cat /db/*.*sql | mysql db], err='exit status 1', stdout='', stderr='ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)' 
```

**To Reproduce**
1. upgrade/update to 0.20.0
2. Attempt to import a database using ddev db-import
3. Get the error above

**Expected behavior**
Database imported

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macOS High Sierra
 - Docker version information 18.03.1-ce
 - ddev version information 0.20.0
 - config.yaml contents
```bash
APIVersion: v0.20.0
name: site01
type: drupal7
docroot: ""
php_version: "7.1"
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
provider: default

```
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

I have the following additional files:
* docker-compose.drush.yaml
* docker-compose.ssh.yaml

**Comment by rfay** [comment]
H @jenlampton - I think you skipped v0.19.0, this was an issue with that, the fix is here, https://stackoverflow.com/questions/50635617/after-upgrading-to-ddev-v0-19-0-i-cant-do-a-ddev-import-db-access-denied-for-r - sorry you had to write the issue. Closing, but let me know if I was wrong.
