### ISSUE TITLE
Include registry_rebuild for drush

### ISSUE THREAD

**Issue by jenlampton** [drud/ddev#953]
**Is your feature request related to a problem? Please describe.**

Use cases:
* When importing a fresh database to a Drupal 7 site, I always run a registry rebuild. 
* When moving php classes around the the file system, Drupal 7 has a registry that can become corrupted. Doing a registry rebuild can fix this problem.

**Describe the solution you'd like**
It would be handy if the registry_rebuild command were included in the default drush

**Describe alternatives you've considered**
Do a  `drush dl registry_rebuild` in every container.

**Comment by rfay** [comment]
I'd recommend just using this in your config.yaml:

```
hooks:
  post-import-db:
    - exec: drush @none dl registry_rebuild-7.x
```

That approach lets anybody do whatever they want.

**Comment by jenlampton** [comment]
Almost...

`drush dl` only needs to be done once per site to get the code, but wouldn't need to be done at all if that happened automatically on set-up. 

Once the code is there, than a post-import-db hook for `drush rr` would work.

**Comment by rfay** [comment]
You can do 
```
hooks:
  post-start:
    - exec: drush @none dl registry_rebuild-7.x

  post-import-db:
    - exec: drush rr
```

If that suite you better. 

We're trying to make most specialty things like this configurable by the user. As the original author of registry_rebuild I certainly know its value, but also know that it's gotten done completely differently in d8 and there are various ways to use it.

**Comment by jenlampton** [comment]
> We're trying to make most specialty things like this

Is this a specialty thing? It's not something everyone who uses Drupal 7 needs?

**Comment by rfay** [comment]
Well, you're the first to ask for this, and Drupal 7 is getting to be more specialty. And there's a good solution that any user can implement. And we don't want to wire a thousand things into the code that people can do exactly the way they themselves want to do.

**Comment by rfay** [comment]
Closing for now, we're open to followups.

**Comment by geru** [comment]
I agree with @jenlampton It's pretty silly that this isn't automatically part of drush. Who is even using Drush 8? D7 users. Not so specialty for Drush 8.

**Comment by rfay** [comment]
As of ddev v1.17, drush is not even provided into the web container for D8, it's assumed that it will be site-installed.  (/usr/local/bin/drush8 is still in there but not linked to drush). So if `drush rr` is still a thing, it must be site installed for drush 10+

**Comment by jenlampton** [comment]
Is it not possible to add registry_rebuild for Drush 8, without also changing what happens for drush 10+?

Drupal 7 might be considered "specialty", but if drupal 7 is included as an option for ddev, you'd think it would include all the things a developer needs in order to work with Drupal 7. 

Doing this individually for every single ddev site is a huge pain when you have 20+ sites, and are trying to switch everything over to running on ddev. :D

**Comment by chrisfromredfin** [comment]
Another way to potentially solve this that might be easier is with a global homeadditions? IIRC the registry_rebuild command just lives in ~/.drush/ - so that might be a way to do a "set it and forget it" so you don't have to worry? I don't think it will hurt if you also have a Drupal 10 site - the command just wouldn't be compatible.

**Comment by jenlampton** [comment]
I do already have registry_rebuild in my global drush, but site-local drush overrides that (and I'm not sure if ddev can even "see" anything outside the container?) Either way, it doesn't seem to work unless I install it on each d7 ddev site. :/

**Comment by rfay** [comment]
He's saying put your drush stuff in global homeadditions. Anything you put in ~/.ddev/homeadditions gets added into your homedir in every project in the web container. Do it on your computer one time, it shows up in every project now and forever. See the examples in https://ddev.readthedocs.io/en/stable/users/extend/in-container-configuration/

That's a really simple solution, and probably better than an add-on, which would  also be nice.

**Comment by rfay** [comment]
Here I am with a d7 project running:
```
rfay@rfay-tag1-m1:~/workspace/d7$ ddev drush @none dl registry_rebuild-7.x
Project registry_rebuild (7.x-2.5) downloaded to /home/rfay/.drush/registry_rebuild.     [success]
Project registry_rebuild contains 0 modules: .
rfay@rfay-tag1-m1:~/workspace/d7$ docker cp ddev-d7-web:/home/rfay/.drush ~/.ddev/homeadditions
Successfully copied 91.1kB to /Users/rfay/.ddev/homeadditions
```

Now every project on this machine (after restart) will have ~/.drush in it and it will have registry_rebuild.  You can also override things with a project-level homeadditions. And you can do drush-ish things that affect ~/.drush as well.

**Comment by jenlampton** [comment]
Ah, thanks! TIL what `homeadditions` are. Linking here for future googling reference:
*  [in-container configuration](https://ddev.readthedocs.io/en/stable/users/extend/in-container-configuration)
* [global files](https://ddev.readthedocs.io/en/stable/users/usage/architecture/#directory-tour)

~In your example above, what is `ddev-d7-web`? Is that the name of the specific ddev instance? I'm getting the following error (when replacing `ddev-d7-web` with the name of my ddev project). In the Docker UI the name of the container is `ddev-[projectname]` so I tried that too, but still get  the error.~

> Error response from daemon: No such container: [projectname]
> Error response from daemon: No such container: ddev-[projectname]

Ah! Via `docker container ls` I can see the container is named `ddev-[projectname]-web` which makes total sense, it looks just like your example 🤦 It works 🎉 

> You can also override things with a project-level homeadditions.

Does "project-level" here mean "instance level" as opposed to "type-of-project level"?  I'd love to have drupal-7 and backdrop specific set of `homeadditions`, but I can't find any documentation on that (yet?) so I have created https://github.com/ddev/ddev/issues/6489 ;)

**Comment by rfay** [comment]
> Does "project-level" here mean "instance level" as opposed to "type-of-project level"? I'd love to have drupal-7 and backdrop specific set of homeadditions, but I can't find any documentation on that (yet?) so I have created https://github.com/ddev/ddev/issues/6489 ;)

Project-level means that you can also have a project .ddev/homeadditions, and that things at the project level override things that were done globally.

**Comment by jenlampton** [comment]
> Project-level means that you can also have a project .ddev/homeadditions, and that things at the project level override things that were done globally.

For clarification, a ddev "project" is `website-a` or `website-b`, and not `drupal-7` or `backdrop`. The latter is known as "type" in ddev terms. You can have a project  `.ddev/homeadditions` but not a drupal7 `.ddev/homeadditions` since there's no clear codebase to place the` .ddev` into for a "type".

**Comment by rfay** [comment]
You could easily use subdirectories of the global homeadditions, for example, ~/.ddev/homeadditions/drupal7, and adjust the drush config to use a different directory. But again, it might be better to check your drush config into your project.
