### ISSUE TITLE
Use Traefik as router

### ISSUE THREAD

**Issue by t3easy** [drud/ddev#956]
Traefik is a very small, build for cloud, reverse proxy. If can handle docker backends out of the box.
Even Let's encrypt is build in.
https://traefik.io/

**Comment by rfay** [comment]
We aren't unhappy with our router solution. Are you? Lets Encrypt is not useful since we are not dealing with something that letsencrypt can work with (for Lets Encrypt you have to have a reachable site). Could you please say why you'd make this change, make a stronger case for it?

**Comment by t3easy** [comment]
Mostly because it’s official, you just need to pass in a config (or parameters). It would reduce the code you need to maintain. In case of docker, it handles the routing with labels and don’t mess up the environment of the container. I’m very happy with it in local dev (not ddev) and on production.

The issue was for discussion and point you to Traefik if you don’t know it already.

**Comment by rfay** [comment]
Thanks, we are familiar with traefik, but ddev-router, which is a fork of https://github.com/jwilder/nginx-proxy, has served us well. It also is native to docker, listens to docker etc. 

It's always wonderful to be pointed to something useful like this, and thanks for bringing it to our attention!
