### ISSUE TITLE
Minor followup: Complaint setting permissions on file that doesn't exist

### ISSUE THREAD

**Issue by rfay** [drud/ddev#958]
**Describe the bug**

Probably from https://github.com/drud/ddev/pull/916: 

During ddev start:
`Ensuring write permissions for satirtraining...
Unable to set permissions: stat /Users/rfay/workspace/satirtraining/sites/default/settings.php: no such file or directory`

**To Reproduce**

Remove settings.php
ddev start

Files that don't exist don't need to have their permissions set.

**Comment by andrewfrench** [comment]
We're actually not setting the permissions of files that don't exist &mdash; that warning is emitted as a result of [checking for the settings file](https://github.com/drud/ddev/blob/8f956767188ba249329f545cb3e1b6eda37921d9/pkg/ddevapp/drupal.go#L469) and handling any error that could prevent a stat by printing a warning.

Maybe this should just continue quietly if the file doesn't exist?

**Comment by rfay** [comment]
I think it should check for the actual existence here - if os.IsExist(err) then it should set the perms. But if it doesn't exist, there's no error to emit.

We also have fileutil.FileExists,

https://github.com/drud/ddev/blob/90cb1944d24391afce4d15d33d29d1dacdedc991/pkg/fileutil/files.go#L122-L129 - so you could do if fileutil.FileExists(file) then set perms.
