### ISSUE TITLE
ddev version should show docker and docker-compose versions. Host info would be nice too!

### ISSUE THREAD

**Issue by rfay** [drud/ddev#960]
**Is your feature request related to a problem? Please describe.**

Doing support, we sometimes have trouble with people not giving adequate info. Today we had an oddball one with an Ubuntu 18.04 install with good docker-ce but old docker-compose, which definitely was bad.

I propose:

* ddev version shows docker and docker-compose versions.
* Consider raising the minimum versions for those at this time.
* ddev version shows basic host information (os, os version, whatever we can easily get)
* ddev version cli version always moves to the top.
* consider showing configured image versions instead of default versions, or at least explain what they are, see #1509
* Add a --version command that just shows the cli version.

**Comment by klausi** [comment]
docker and docker-compose versions are shown now.

* OS info is missing
* cli version is shown on the second line.

```
$ ddev version
bgsync        	drud/ddev-bgsync:v1.6.0       
cli           	v1.6.0                        
commit        	v1.6.0                        
db            	drud/ddev-dbserver:v1.6.0-10.2
dba           	drud/phpmyadmin:v1.6.0        
ddev-ssh-agent	drud/ddev-ssh-agent:v1.6.0    
docker        	18.06.1-ce                    
docker-compose	1.23.2                        
domain        	ddev.local                    
router        	drud/ddev-router:v1.6.0       
web           	drud/ddev-webserver:v1.6.0
```

BTW, super confusing that `ddev --version` does not work.

**Comment by rfay** [comment]
Thanks, yeah that would make piles of sense thanks!
