### ISSUE TITLE
Allow more extensive configuration of `ddev logs` to include other logfiles

### ISSUE THREAD

**Issue by kaystrobach** [drud/ddev#961]
**Is your feature request related to a problem? Please describe.**

Finding the correct logs is often not that easy. As you already have `ddev logs -f` it would and standardized HID to also get the Application log from there.

**Describe the solution you'd like**.

* Config array option to define other logfile locations, so that these are included in the logfile stream.

**Describe alternatives you've considered**

* a dedicated command to retrieve the application logs

**Comment by rfay** [comment]
No response from OP about what he'd like to examine, so closing. @kaystrobach happy to reopen and discuss this, or discuss your specific needs in the slack channel as well.

**Comment by kaystrobach** [comment]
Ahh sry missed your question. I would like to get the application logs via ddev. This would make it easy as common entry ooint for all projects. No need to fiddle with custom conf etc.

**Comment by rfay** [comment]
Which application logs would you like to get that you don't already get? Currently `ddev logs -s web` t's a mix of php-fpm and nginx error logs and `ddev logs -s db` is the mysqld logs

**Comment by kaystrobach** [comment]
F.e. if you have a TYPO3:

* typo3temp/var/logs/*.log

For a flow Application:

* Data/Logs/*.log

So it would be nice to configure a path with *.log for adding additional logfiles to your output provider of logfiles.

**Comment by rfay** [comment]
Thanks! I didn't even know TYPO3 had text logs.

**Comment by kaystrobach** [comment]
Depends, newer version ship monolog, so you can use whatever logging system compatible with monolog 😉

**Comment by rfay** [comment]
I think a better way to solve this in v1.10+ will be custom commands. 

For example, the
* [host-based solrtail.example](https://github.com/drud/ddev/blob/master/cmd/ddev/cmd/assets/commands/host/solrtail.example)
* [container-based solrtail.example](https://github.com/drud/ddev/blob/master/cmd/ddev/cmd/assets/commands/solr/solrtail.example)

Approaches like that should make you able to do any application-specific log catcher you want.

**Comment by rfay** [comment]
Closing for now because those seem to be good approaches. Happy to continue the conversation.

**Comment by kaystrobach** [comment]
> I think a better way to solve this in v1.10+ will be custom commands.
> 
> For example, the
> 
>     * [host-based solrtail.example](https://github.com/drud/ddev/blob/master/cmd/ddev/cmd/assets/commands/host/solrtail.example)
> 
>     * [container-based solrtail.example](https://github.com/drud/ddev/blob/master/cmd/ddev/cmd/assets/commands/solr/solrtail.example)
> 
> 
> Approaches like that should make you able to do any application-specific log catcher you want.

both links show a 404 - but the idea is awesome

**Comment by rfay** [comment]
Ah time moves on. Updated the links in https://github.com/drud/ddev/issues/961#issuecomment-513401294
