### ISSUE TITLE
win10: startup failure: ddev cannot mount ddev_datadir when User-Dir is on a network share

### ISSUE THREAD

**Issue by mac-dev** [drud/ddev#968]
After running ddev config doing a ddev start fails when trying to mount the db import volume.
ddev start has been tested in cmd and powershell.

This seems to happen because the mountpoints of ddev_datadir and ddev_importdir are in the users home directory and those are mounted via network share like in many larger companies.
Docker tries to mount the network volume i: asks for User and PW and fails.

As a Workaround If found that running ddev start from cmder (http://cmder.net/) seems to work.
It does not work while using git bash.
It looks like cmder is using the HOME envar and not the HOMESHARE like other shells do.

HOME=/c/Users/myuser
HOMEDRIVE=I:
HOMEPATH=\
HOMESHARE=\\itsshare.share.de\HZD\Home\myuser

Maybe it is possible to define the ddev_datadir and ddev_importdir in the config.yml before to make it work with Powershell / CMD
I didn't find instructions in the docs. 

**To Reproduce**
see above

Error:
ddev start
[0mStarting environment for portal...[0m
[33mWarning: containers will run as root. This is fine on Docker for Windows or Docker for Mac, but could be a security risk on Linux.[0m
[0mRecreating ddev-portal-db ... [0m
[1B[0m g ddev-portal-db ... [31merror[0m
[0mERROR: for ddev-portal-db  Cannot create container for service db: b'An error occured while sharing drive'[0m
[0m[0m
[0mERROR: for db  Cannot create container for service db: b'An error occured while sharing drive'[0m
[0mEncountered errors while bringing up the project.[0m
[31mFailed to start portal: Failed to run docker-compose [-f D:\seu\source\portal\.ddev\docker-compose.yaml up -d], err='exit status 1', stdout='', stderr='Recreating ddev-portal-db ...
[1Beating ddev-portal-db ... [31merror[0m
ERROR: for ddev-portal-db  Cannot create container for service db: b'An error occured while sharing drive'

ERROR: for db  Cannot create container for service db: b'An error occured while sharing drive'
Encountered errors while bringing up the project.'[0m

**Expected behavior**
Start ddev as usal

**Version and configuration information (please complete the following information):**
- windows10
 - Docker version information: Docker version 18.03.1-ce, build 9ee9f40
 - ddev version information (use `ddev version`)
ddev version
[0mdb          drud/mariadb-local:v0.9.0
dba     drud/phpmyadmin:v0.2.0
router  drud/ddev-router:v0.5.0
commit  v0.17.0
domain  ddev.local
cli     v0.17.0
web     drud/nginx-php-fpm-local:v1.2.2[0m

**Additional context**
I found a workaround

**Comment by mac-dev** [comment]
Just found this Issue here would solve the problem:
https://github.com/drud/ddev/issues/883

**Comment by rfay** [comment]
You say "I found a workaround" - That's the workaround in https://github.com/drud/ddev/issues/883 or something else? Thanks for the report.

**Comment by mac-dev** [comment]
Somehow running ddev start from http://cmder.net/ works like described above.
We compared the env variables in cmder and in cmd / powershell just to see they are identically, but somhow cmder puts the .ddev basdir unter c:/users/somone and not under share:/user/someone
Using git bash in win10 which too emulates some linux (mingw64) does not work.

**Comment by rfay** [comment]
Closing as a duplicate of #883, thanks!
