### ISSUE TITLE
Sequelpro command fails for case sensitive filesystems

### ISSUE THREAD

**Issue by codemonkey1988** [drud/ddev#969]
**Describe the bug**
I try to call `ddev sequelpro` on my mac. Sequelpro is installed and works fine. When running the command, I get the error _The sequelpro command is not available because sequel pro.app is not detected on your workstation_

I figured out, the ddev is looking for `/Applications/sequel pro.app` folder. But Sequel Pro is installed to `/Applications/Sequel Pro.app` by default. When you got a case-sensitive formatted hard disk, the call will fail because the folder can not be found.

**To Reproduce**
1. Use a Mac with case sensitive file system
2. Install Sequel Pro to the Applications folder
3. Setup a ddev project
4. Run `ddev sequelpro`

**Expected behavior**
Sequel Pro will start and automatically connect to the ddev database.

**Version and configuration information (please complete the following information):**
 - macOS High Sierra 10.13.5 with case-sensitive filesystem
 - Docker version 18.03.1-ce
 - ddev version 0.20.0

**Comment by rfay** [comment]
Thanks! Sounds like that one should be pretty easy.

**Comment by jdoubleu** [comment]
Can confirm this on my machine with a case sensitive filesystem (APFS). Got:
```
$ ddev sequelpro
The sequelpro command is not available because sequel pro.app is not detected on your workstation
```

**Comment by rfay** [comment]
@jdoubleu @codemonkey1988 Would appreciate if you could test the ddev version in https://circleci.com/gh/drud/ddev/3054#artifacts/containers/0 and add your review to #973 - It's awkward for me to test this properly.
