### ISSUE TITLE
xdebug is not working when i'm using uppercase letters in project name

### ISSUE THREAD

**Issue by lukaszuznanski** [drud/ddev#974]
I'm working with project on ddev 0.20 on ubuntu 18.04. I add to .ddev dir file docker-compose.xdebug.yaml with configuration of host.docker.internal (i don't know if it's still necessary), and setup Phpstorm configuration like in documentation. It's working when im using project name like "foobar", but this time, I used something like "FooBar" and I can't get xdebug to work. After name change to "foobar", everything works like charm.

1. Create project with project name "FooBar"
2. Try to setup xdebug like in documentation (this should fail)
3. Change project name to "foobar"
4. Now, xdebug should work.

**Expected behavior**
Add information to documentation to avoid uppercase letters or we should be able to set case sensitive project name and work with xdebug

**Version and configuration information (please complete the following information):**
 - ubuntu 18.04
 - Docker:
```
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:10:09 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm
```
 - ddev version:
```
domain  ddev.local                      
cli     v0.20.0                         
web     drud/nginx-php-fpm-local:v0.20.0
db      drud/mariadb-local:v0.20.0      
dba     drud/phpmyadmin:v0.20.0         
router  drud/ddev-router:v0.20.0        
commit  v0.20.0    
```
 - config.yaml 
```
APIVersion: v0.20.0
name: FooBar
type: typo3
docroot: web
php_version: "7.0"
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
provider: default
```
 - I use docker-compose.xdebug.yaml for Linux xdebug setup, I also tried without this file.
```
version: "3"
services:
  web:
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
```

**Comment by rfay** [comment]
Hmm, you have `xdebug_enabled: false` in your config.yaml? Don't you want that to be true?

**Comment by lukaszuznanski** [comment]
I just exec 
```
ddev exec enable_xdebug
```
when I want to debug

**Comment by rfay** [comment]
I tried this approach and had no trouble, worked right out of the box (PHPStorm and a project named MyTestProject, running on Ubuntu 16.04)

In recent versions of ddev you don't have to add the extra_hosts configuration you added in docker-compose.xdebug.yam, ddev does that for you, so please remove that. Not sure if that might be the problem?

**Comment by rfay** [comment]
No response after 4 days, this was tested and seemed to work ok. Feel free to follow up and I'll be happy to discuss further, but I didn't find what would be the problem with a mixed-case project name.
