### ISSUE TITLE
Add the list of supported additional services to the README.md

### ISSUE THREAD

**Issue by fedir** [drud/ddev#978]
I already met some developers and proposed them to try ddev, and the first reaction was "Does it have X service (varnish, memcachd, ... ) I'm using in my everyday work?".

So I thought it will be great to show current list of supported services for new ddev users.

For example, in the [Lando](https://raw.githubusercontent.com/lando/lando/master/README.md) project's README, You could find following:

```
And then mix in additional auxiliary services
---------------------------------------------

*   [apache](http://docs.devwithlando.io/services/apache.html)
*   [elasticsearch](http://docs.devwithlando.io/services/elasticsearch.html)
*   [mailhog](http://docs.devwithlando.io/services/mailhog.html)
*   [mariadb](http://docs.devwithlando.io/services/mariadb.html)
*   [memcached](http://docs.devwithlando.io/services/memcached.html)
*   [mongo](http://docs.devwithlando.io/services/mongo.html)
*   [mssql](http://docs.devwithlando.io/services/mssql.html)
*   [mysql](http://docs.devwithlando.io/services/mysql.html)
*   [nginx](http://docs.devwithlando.io/services/nginx.html)
*   [phpmyadmin](http://docs.devwithlando.io/services/phpmyadmin.html)
*   [postgres](http://docs.devwithlando.io/services/postgres.html)
*   [redis](http://docs.devwithlando.io/services/redis.html)
*   [solr](http://docs.devwithlando.io/services/solr.html)
*   [tomcat](http://docs.devwithlando.io/services/tomcat.html)
*   [varnish](http://docs.devwithlando.io/services/varnish.html)
```
Let's add such list to the ddev's README. It'll give the understanding to ddev's contributors, which additional services we could add to make the current state even better.

**Comment by rickmanelius** [comment]
I very much want this to be a goal of this project. Bonus points if one could optionally answer some additional questions or run another command to drop in the additional service starting points.

**Comment by rfay** [comment]
I think this is currently up-to-date - https://ddev.readthedocs.io/en/latest/users/extend/additional-services/#additional-services-in-ddev-contrib-mongodb-blackfire-postgressql-etc
