### ISSUE TITLE
As an end-user, I want a way to quickly install ddev via a script

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#98]
## What happened (or feature request):

Feature request.

## What you expected to happen:

At the present moment, end-users need to download all necessary dependencies for ddev (i.e. Docker and Go), clone the ddev repository, compile the binary, and set the environment path. While this should not be difficult for a user that is familiar with the command line, it would be preferable to have a script or mechanism to get someone up and operational faster.

## Anything else do we need to know:

The faster we can get someone up and operational, the better. As theorized here (https://betta.io/blog/2017/02/23/understanding-developers/), "Explorers" typically have "low motivation" and "low persistence" when evaluating new alternatives. Therefore, first impressions do matter in capturing the largest possible percentage of this 

## Done Criteria
- Bash script that works on both macOS (latest) and Ubuntu Linux (16.04, 14.04)
- Requirements check
  - Should fail the installation if a supported version of docker is not installed, and provide a link to the docker installation page if it isn't.
  - Should report if other common tools such as a mysql client are not installed. This should not fail the installation.
- Download the correct binary based on the architecture (darwin/linux) and put in in the users $PATH (suggest /usr/bin since /usr/local/bin is not in OSX path by default)
- Write a quickstart guide which walks a user through installation and starting their first site.
- The install script should be in the ddev git repo, and have a shortlink which points to the latest tags installation instructions

**Comment by tannerjfco** [comment]
I have an initial install script for consideration. Did as gist for now, if we're good with approach I can start tracking a PR: https://gist.github.com/tannerjfco/f4a3c06c249753f8940f3da84108c2da

**Comment by tannerjfco** [comment]
Resolved with #182

**Comment by rfay** [comment]
Just an FYI, experimental homebrew installation is now available.

* Install with `brew tap drud/ddev && brew install ddev`
* Updates are automatic when homebrew-ddev changes and user does an upgrade: `brew upgrade ddev`
* Maintenance is in [homebrew-ddev](https://github.com/drud/homebrew-ddev/blob/master/Formula/ddev.rb) and that has to be updated for a new release.
