### ISSUE TITLE
Enable automatic creation of additional databases

### ISSUE THREAD

**Issue by nadavoid** [drud/ddev#980]
Currently, when creating additional databases, it must be done manually. One must use the mysql cli to issue `CREATE DATABASE` etc. commands.

**Potential solution**
I would like to be able to define additional databases directly in `.ddev/config.yaml`, and have ddev create them for me, applying the same access permissions as the main `db` database.

Something that might work is to add an `additional_databases`, similar to `additional_hostnames`. When used, it could look like this:
```
additional_databases:
  - wp
  - drupal6
```

I've poked around in the source code a little, and I think I have an idea of how this might be implemented. But since I've never worked directly with this code or even the go language, other folks will probably have better implementation ideas. In case it's helpful, here's what it looks like to me:

1. In `ddev/pkg/ddevapp/ddevapp.go`, add a property to `DdevApp`, similar to the `AdditionalHostnames` property.
2. In the same file, add a loop after the database creation portion of `ImportDB`.

Would something like that work well?

**Alternatives considered**
I've looked at using a `post-start` command, described in this StackOverflow post: [How can ddev automatically create additional databases?](https://stackoverflow.com/questions/51253642/how-can-ddev-automatically-create-additional-databases)

**Additional context**
Automatically creating additional databases can be very helpful when collaboration with others on migrations from other databases, or when a project simply requires an additional database for data isolation, or when a project requires using multisite.

**Comment by nadavoid** [comment]
Yep, it does for me.

**Comment by rfay** [comment]
Thanks!
