### ISSUE TITLE
Manual restart of php fails due to missing user/group www-data

### ISSUE THREAD

**Issue by neufeind** [drud/ddev#981]
php-fpm (and nginx) run with user uid_1001. But when trying to manually restart php like
/etc/init.d/php7.1-fpm restart
it fails because the php-fpm-configuration contains user/group www-data:www-data.

Should we adjust the php-fpm-configuration? Or make uid_1001 (as well as the group) be actually www-data in the container?

**Comment by rfay** [comment]
Hi @neufeind ! 

The web container doesn't use the init system, and php-fpm runs as the same uid (on Mac and Linux) and the host user. So /etc/init.d isn't going to be the right way.

You could hit the master php-fpm with SIGHUP to reload config `killall -HUP php-fpm`, you could hit supervisord with a HUP I think (process 1). You could `ddev restart`

Let me know what you're trying to accomplish though...

**Comment by neufeind** [comment]
I edited a php.ini-entry. Okay, a SIGHUP would do then. I didn't expect the init-scripts "don't work at all". Okay then.

**Comment by rfay** [comment]
For changing php.ini, you'll be a lot better using a custom php config in .ddev/php, https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#providing-custom-php-configuration-phpini - That way it won't go away every time you start the container. And for that a `ddev restart` should get you what you want.

**Comment by rfay** [comment]
Closing, happy to continue the conversation here though!
