### ISSUE TITLE
Handle multiple version warnings for list command

### ISSUE THREAD

**Issue by codemonkey1988** [drud/ddev#982]
The agency I'm working at started using ddev a few weeks ago and it's really nice working with it. So thanks for that great product!

I currently have about 20 ddev projects configured and it's growing. So, to keep up what ddev projects are currently running, I run the command `ddev list` which works fine. (Currently I also use it to check if there are running projects before shutting down because of the mariaDB database crashing)
Lately I updated ddev to 0.20.0. When I now run ddev list, I get a version warning for each project thats in the list. Of course, thats a correct behaviour, but it is very annoying when using the command a lot and getting 20 warnings with 3 lines of text for each warning.

I'm aware of updating the project to get rid of that message is the way to go, but there are projects that I started only twice a year. So before starting the project again, I might need to update the config several times, just to get rid of the warnings.

For agencies it's often more efficient to update the projects ddev config when working again on the project.

So it would be nice if there is a way to hide these warnings. I have several suggestions for this handling:

- Hide them completely for `ddev list` command
- Add a flag to the command to hide or show them
- Just print one warning with a list of incompatible projects

There might be far more solutions to that tiny problem and I want to discuss them here. Maybe I'm the only one that is annoyed by this behaviour. ^^

**Comment by rfay** [comment]
This is a dup of https://github.com/drud/ddev/pull/963, fixed in next release. You weren't the only one to be annoyed. Thanks.
