### ISSUE TITLE
Completely remove a deleted site from ~/.ddev after ddev rm -R

### ISSUE THREAD

**Issue by jmarkel** [drud/ddev#989]
After running ddev rm -R, a site's directory still exists in the global ddev directory ~/.ddev - with an empty import-db directory within it.

After fully removing a site via ddev rm -R, the full site directory and all its contents should be removed from ~/.ddev. (Note that I DO NOT mean deleting the site code a la Acquia Dev Desktop :( - that's an abomination! Just the ddev-related files, thanks :) )

This goes hand in hand with the already open Issue #831  to remove the site's entry from etc/hosts)

**Comment by rfay** [comment]
This sounds good to me. And if https://github.com/drud/ddev/pull/987 (database stored in docker volume) succeeds and makes it in, there won't be that much of a need to even have the ~/.ddev/sitename

**Comment by rfay** [comment]
So `ddev rm --remove-data` should:
* Remove ~/.ddev/<project>
* Remove any provider downloads in ~/.ddev/<provider>/<projectname>
* Remove any database or file downloads anywhere else

**Comment by rfay** [comment]
This was solved in #883 (stop bind-mounting), as projects no longer even create a directory in ~/.ddev.
