### ISSUE TITLE
As an end-user, I want notifications and instructions regarding upgrades.

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#99]
## What happened (or feature request):

Feature Request

## What you expected to happen:

Given that we decided to not allow for upgrades/updates (see https://github.com/drud/ddev/issues/28#issuecomment-286201906), we still should prompt a user every so often to inform them an update exists. We will do this whenever an end-user runs `ddev version`, but not everyone will check that and we may want to run a check every day or week and then nudge the user. We can also provide a link to instructions on how to perform the upgrade.

oh-my-zsh does a pretty good job of this by prompting every so often when an update exists. Of course, they take on the responsibility of installing whereas we will require the end-user to do this by either manually installing or re-reruning the install script here https://github.com/drud/ddev/issues/98.

## Related source links or issues (like source JIRA issue):

* As an end-user, I want a way to quickly install ddev https://github.com/drud/ddev/issues/98

**Comment by beeradb** [comment]
After looking into this here's what I proposed:

### Periodic Update Checking
We already have the ~/.ddev folder with the router config. My thought process is just to add a .update file in that folder and key off the creation timestamp to trigger updates. We can add a `PersistantPreRun` to cobra commands that performs the check, and outputs a message to the user if an update exists. It's probably also prudent to add a `DDEV_UPDATECHECK_DISABLE` environment variable which completely disables the update functionality.

### Detecting New Releases

It looks like we should be able to detect updates using the (github release API)[https://github.com/google/go-github/blob/master/github/repos_releases.go].  We'll likely also have to parse semver versions, which would necessitate bringing in a semvar parsing package, of which there appear to be many. Masterminds (glide), hashicorp, and others all have released semvar parsing packages. There doesn't appear to be a clear winner in popularity from preliminary research.


### Self-updating (optional)

There are a couple reasonable looking go-packages for doing a self-update. they are:

- https://github.com/inconshreveable/go-update
- https://github.com/sanbornm/go-selfupdate

Both have fairly simple looking APIs. If we wanted to prompt the user and actually perform the update on their behalf, it doesn't look like much more work. We don't need to decide on this right away, as the work to notify and do the self-update largely overlaps.

**Comment by rfay** [comment]
I'd personally rather see the update be external (notification internal). It seems lots of mac apps are done this way. It's slightly less convenient, but somewhat more secure, and leaves the user in charge. It's also simpler. I won't battle to the death though.

**Comment by rickmanelius** [comment]
We have two issues at play:

1. Notification of an available update
2. Process of upgrading

In terms of item 1, if we don't actually perform the upgrade, I would suggest we also pick a reasonable window of time to re-remind them (once a week?) instead of reminding them every run.

In terms of item 2, we have a larger discussion to come back to regarding installation and updating ddev. See this thread https://github.com/drud/ddev/issues/98#issuecomment-291636118. If we do end up adopting a package manager, we would probably toss away the auto-update functionality being proposed and place that responsibility elsewhere.

If it's a small lift, I'd prefer the prompt to self-update in the short term knowing that it's more to help early adopters and we'll likely revisit.

**Comment by rickmanelius** [comment]
@beeradb updated the flags. I do still think that even with the self-update that we have another component where we don't ask to update every run and instead have a check once per week.
