### ISSUE TITLE
Mailhog: Requests to move to a global container and provide user the ability to disable per project.

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#997]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NeoBlack** [comment]
It would be very nice to disable mailhog in config.yaml or configure the ports.
At the moment I can't start ddev because port 8025 is used by my local mailhog setup.

**Comment by rfay** [comment]
This remains a reasonable architecture, but the current architecture is causing no trouble and nobody has worried about this too much, so closing.
