### ISSUE TITLE
Create drud-s3 Provider Plugin

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#998]
On the path towards building out our integrations with additional hosting providers, we are going to start smaller with an authentication with and pulling from an S3 + folder endpoint. This was defined elsewhere and it will be brought into this issue. More detail required before proceeding...

**Comment by rickmanelius** [comment]
As stated in the referenced issues above, the backup structure for drud's hosting solution is currently generating backups in the following pattern:

s3://bucket/project-name/production/mybackup.files.tgz
s3://bucket/project-name/production/mybackup.sql.gz

**Comment by rickmanelius** [comment]
A necessary item to begin work on this is the provisioning of two sites into DRUD hosting for the explicit usage of the DDEV-Local engineering team to build the plugin and the DDEV-Local Circle CI runs to confirm this continues to work. To that end, we will need to address the following dependencies:

* Create a "ddev-internal" org in our production cluster.
* Create two projects within that:
  * D7 Commerce Kickstart https://www.drupal.org/project/commerce_kickstart/releases/7.x-2.54
    * Projectname can be d7-kickstart
  * D8 Umami distributions https://www.drupal.org/project/umami/releases/8.x-1.x-dev
  	* Projectname can be d8-umami
* Create two environments for each:
  * production => tracks master branch
  * staging => attached to staging branch
* Create an S3 bucket called "ddev-local-tests"
  * DDEV-Local team needs S3 token for full access, stored in 1password
* Backups. Ideally we need at least one backup for each environment out of the gate with nighthly generation.
* Code. We need a list of both git endpoints as well as access for anyone in the DRUD org.

Once this is completed we should be good to go. 

@cweagans

**Comment by cweagans** [comment]
I'll tackle this before EOD tomorrow. Do you want a Wordpress site as well?

**Comment by rickmanelius** [comment]
@cweagans Wouldn't hurt... "wordpress4" should suffice for a project name.

**Comment by cweagans** [comment]
:+1:

**Comment by cweagans** [comment]
I've done everything above with a couple of exceptions and changes:

* Creds and environment details are in 1password
* The Drupal 8 site was installed from Drupal 8.6.0 alpha1 -- the demo_umami profile is included in that, so it was a bit easier to get pushed up.
* Right now, the D8 site is broken and I don't know why.
* Right now, staging environments don't exist, but I will create them asap.
* We cannot configure an environment to track a particular branch on ddev-live. The `staging` environment tracks the `staging` branch. `production` tracks `production`. You can somewhat work around this by doing `git push yourremote master:production` to push your local `master` branch to the remote `production` branch.

There is one manual backup from the production environment for all three sites in the bucket right now, and they will be automatically generated once per day. Daily backups are retained once per day for a week and once per week for a month.

**Comment by rfay** [comment]
We won't be doing any pushing at this point anyway (or, I don't expect, any git pulling either). We don't do any push activity of any kind in the pantheon plugin, it's just a way to pull files and db.

**Comment by rickmanelius** [comment]
Let's name this "drud-s3" as the plugin name. Let's store the full S3 bucket + path in the .ddev/provider.yml. We'll need to prompt the end user for the path during config.

**Comment by rickmanelius** [comment]
We will not consider utilizing more than one S3 key at this time. Users will need to manually delete/change.

**Comment by rickmanelius** [comment]
While there is work going on within the PR, there was still some open items that came out of Friday's meeting between myself and @rfay that should get documented as our working plan. Since things are a little scattered about, here's where I think they landed:

* The [proposed AC from the previous/related issue](https://github.com/drud/rocks/issues/8#issuecomment-404930630) is out of date and should not be taken literally.
* Authentication and Keys
  * We will assume a drud-s3 user needs access to one S3 bucket to avoid managing multiple AWS keys.
  * We will not use the `ddev auth-PLUGIN` approach. Instead we will optionally ask for a token during configuration after answering the standard config questions of project name, docroot, and project type.
  * The S3 bucketname + projectname will be a string stored in .ddev/config.yml
* Caching. We should mirror the approach of the Pantheon plugin by storing a copy locally in case someone tries to pull/download again.

* Mocked Steps
  * `ddev config drud-s3`
    * Answer standard questions of procect name, docroot, project type.
    * S3 Key:
      * If found, simply state we have found a key.
      * If not found, request that they paste.
    * S3 Bucket:
      * Enter the string of bucket + folder
    * Environment
      * Enter the environment to use as either production or staging with production as default.

Wishlist but not necessary
* Adding --files or --database to specify just one type of asset download. See related https://github.com/drud/ddev/issues/405

Some of this may be redundant to what's in the related issue or what's in the PR. However, just trying to wrangle this and I'm more than happy to finalize the discussion and get this issue's summary/description updated.

**Comment by rfay** [comment]
This should be good for another round @rickmanelius , AWS credentials are now collected in the config process, testing procedure has been updated. @andrewfrench would love to have you take this for a spin as well. In addition, the D8 Umami project info is now correct in the 1Password entry, so it's possible to try that out.

This now uses https://github.com/AlecAivazis/survey for prompting, very nice, but a bit of a different feel. We'll want to use it everywhere, as they're doing in hosting.
